### ISSUE TITLE
Update 7 > 7.0.1 - problem with db update

### ISSUE THREAD

**Issue by mrlars** [owncloud/core#10211]
Hi guys
Upgrading a fresh 7 install I received this message:
```
Updating ownCloud to version 7.0.1, this may take a while.

Modalità di manutenzione attivata
The table with name 'NAME_OF_MY_DB.group' already exists.

The update was unsuccessful.Please report this issue to the ownCloud community.
```
and there's no table with that name 

In the logfile I read:
```
{"app":"core","message":"Simulated database structure update failed (exception 'OC\\DB\\MigrationException' with message 'The table with name 'NAME_OF_MY_DB.group' already exists.' in \/PATH_TO_OWNCLOUD\/lib\/private\/db\/migrator.php:117\nStack trace:\n#0 \/PATH_TO_OWNCLOUD\/lib\/private\/db\/migrator.php(75): OC\\DB\\Migrator->checkTableMigrate(Object(Doctrine\\DBAL\\Schema\\Table))\n#1 \/PATH_TO_OWNCLOUD\/lib\/private\/db\/mdb2schemamanager.php(111): OC\\DB\\Migrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#2 \/PATH_TO_OWNCLOUD\/lib\/private\/db.php(337): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/accounts\/albon...')\n#3 \/PATH_TO_OWNCLOUD\/lib\/private\/updater.php(186): OC_DB::simulateUpdateDbFromStructure('\/accounts\/albon...')\n#4 \/PATH_TO_OWNCLOUD\/lib\/private\/updater.php(137): OC\\Updater->doUpgrade('7.0.1.1', '7.0.0.8')\n#5 \/PATH_TO_OWNCLOUD\/core\/ajax\/update.php(35): OC\\Updater->upgrade()\n#6 {main})","level":4,"time":"2014-08-06T10:55:48+00:00"}
```

How can I work around?

**Comment by enoch85** [comment]
ping @icewind1991

**Comment by PVince81** [comment]
Either it's the old problem where the migration was trying to migrate non-OC tables or the one where OC tables have no prefix. They should both be fixed already.

Please try again with 7.0.7 or 8.0.5.
