### ISSUE TITLE
Encryption bugs with respect to movable mount points

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#10371]
spotted by @PVince81 while reviewing https://github.com/owncloud/core/pull/10181
- [ ] BUG: if you rename the ext storage mount point (all users), the folder in `data/files_encryption/keyfiles` still keeps the old name
- [ ] BUG: deleting the system-wide mount point `sftp` still leaves the keys in `data/files_encryption/keyfiles/sftp`
- [ ] BUG: renaming/moving a personal mount point also doesn't update keyfiles location

**Comment by enoch85** [comment]
Any update here @schiesbn ?

**Comment by PVince81** [comment]
@schiesbn does this still apply for the new encryption ?

**Comment by schiesbn** [comment]
Most likely yes as renaming mount points or removing them completely in the external storage settings doesn't trigger any hooks the encryption app could listen to

**Comment by PVince81** [comment]
CC @Xenopathic @icewind1991 

We might need to introduce new hooks for mount point renaming

**Comment by PVince81** [comment]
The new external storage code is much cleaner and it should be much easier to introduce new hook triggers. Setting to 9.1 to look into this.

**Comment by PVince81** [comment]
@icewind1991 @Xenopathic we should probably just trigger the regular rename hook when renaming an external storage, so that all apps listening to rename hooks can activate.

**Comment by schiesbn** [comment]
Just tested it... it is still an issue.

>we should probably just trigger the regular rename hook when renaming an external storage, so that all apps listening to rename hooks can activate.

Yes, I think this would be the right solution.

**Comment by PVince81** [comment]
This makes integration tests fail on master when running the tests twice. This is because the first test creates an ext storage and deletes it at the end. But the second test run would find the stray keys from the previous run and cause issues.

Maybe at least the encryption code should ignore existing keys if the actual file isn't there and work as if the keys did not exist.

Test result:
```
% sudo -uwwwrun OC_TEST_ENCRYPTION_ENABLED=1 ./run.sh features/external-storage.feature

...

  @local_storage
  Scenario: Share by link a file inside a local external storage                       # /srv/www/htdocs/owncloud/build/integration/features/external-storage.feature:7
[Tue Jan 24 14:41:23 2017] 127.0.0.1:35750 [404]: /ocs/v2.php/cloud/users/user0
[Tue Jan 24 14:41:25 2017] Successful addUser call with userid: user0
[Tue Jan 24 14:41:25 2017] 127.0.0.1:35754 [200]: /ocs/v1.php/cloud/users
[Tue Jan 24 14:41:25 2017] copying skeleton for user0 from /srv/www/htdocs/owncloud/core/skeleton to /user0/files/
[Tue Jan 24 14:41:27 2017] 127.0.0.1:35758 [200]: /ocs/v1.php/cloud/users/user0
[Tue Jan 24 14:41:28 2017] 127.0.0.1:35762 [200]: /ocs/v2.php/cloud/users/user0
    Given user "user0" exists                                                          # FeatureContext::assureUserExists()
[Tue Jan 24 14:41:28 2017] 127.0.0.1:35766 [404]: /ocs/v2.php/cloud/users/user1
[Tue Jan 24 14:41:30 2017] Successful addUser call with userid: user1
[Tue Jan 24 14:41:30 2017] 127.0.0.1:35770 [200]: /ocs/v1.php/cloud/users
[Tue Jan 24 14:41:31 2017] copying skeleton for user1 from /srv/www/htdocs/owncloud/core/skeleton to /user1/files/
[Tue Jan 24 14:41:32 2017] 127.0.0.1:35774 [200]: /ocs/v1.php/cloud/users/user1
[Tue Jan 24 14:41:33 2017] 127.0.0.1:35778 [200]: /ocs/v2.php/cloud/users/user1
    And user "user1" exists                                                            # FeatureContext::assureUserExists()
    And As an "user0"                                                                  # FeatureContext::asAn()
[Tue Jan 24 14:41:33 2017] 127.0.0.1:35782 [201]: /remote.php/webdav/local_storage/foo
    And user "user0" created a folder "/local_storage/foo"                             # FeatureContext::userCreatedAFolder()
[Tue Jan 24 14:42:06 2017] fclose() expects parameter 1 to be resource, string given at /srv/www/htdocs/owncloud/lib/private/Files/Storage/Wrapper/Encryption.php#749
[Tue Jan 24 14:42:06 2017] Exception: {"Message":"multikeydecrypt with share key failed:error:0E06D06C:configuration file routines:NCONF_get_string:no value","Exception":"OCA\\Encryption\\Exceptions\\MultiKeyDecryptException","Code":0,"Trace":"#0 \/srv\/www\/htdocs\/owncloud\/apps\/encryption\/lib\/KeyManager.php(423): OCA\\Encryption\\Crypto\\Crypt->multiKeyDecrypt('\\xD8\\x93\\xB6\\xFA\\x0E\"\\x93\\xDBq\\x8B(\\xAA\\xDC\\xFF<...', '\\xE7\\xB50\\xDE}\/\\x9F\\xDF\\xD5\\xA7K\\xF0\\xB2\\x8Eg...', '-----BEGIN PRIV...')\n#1 \/srv\/www\/htdocs\/owncloud\/apps\/encryption\/lib\/Crypto\/Encryption.php(186): OCA\\Encryption\\KeyManager->getFileKey('\/user0\/files\/lo...', 'user0')\n#2 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Stream\/Encryption.php(257): OCA\\Encryption\\Crypto\\Encryption->begin('\/user0\/files\/lo...', 'user0', 'w', Array, Array)\n#3 [internal function]: OC\\Files\\Stream\\Encryption->stream_open('ocencryption:\/\/', 'w', 0, NULL)\n#4 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Stream\/Encryption.php(197): fopen('ocencryption:\/\/', 'w', false, Resource id #561)\n#5 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Stream\/Encryption.php(179): OC\\Files\\Stream\\Encryption::wrapSource(Resource id #560, Resource id #561, 'ocencryption', 'OC\\\\Files\\\\Stream...', 'w')\n#6 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php(459): OC\\Files\\Stream\\Encryption::wrap(Resource id #560, 'foo\/textfile0.t...', '\/user0\/files\/lo...', Array, 'user0', Object(OCA\\Encryption\\Crypto\\Encryption), Object(OC\\Files\\Storage\\Local), Object(OC\\Files\\Storage\\Wrapper\\Encryption), Object(OC\\Encryption\\Util), Object(OC\\Encryption\\File), 'w', 0, 0, 0, true)\n#7 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php(743): OC\\Files\\Storage\\Wrapper\\Encryption->fopen('foo\/textfile0.t...', 'w')\n#8 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php(613): OC\\Files\\Storage\\Wrapper\\Encryption->copyBetweenStorage(Object(OCA\\Files_Trashbin\\Storage), 'files\/textfile0...', 'foo\/textfile0.t...', true, true)\n#9 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(568): OC\\Files\\Storage\\Wrapper\\Encryption->moveFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'files\/textfile0...', 'foo\/textfile0.t...')\n#10 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/View.php(789): OC\\Files\\Storage\\Wrapper\\Wrapper->moveFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'files\/textfile0...', 'foo\/textfile0.t...')\n#11 \/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php(262): OC\\Files\\View->rename('\/textfile0.txt', '\/local_storage\/...')\n#12 \/srv\/www\/htdocs\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/CorePlugin.php(642): OCA\\DAV\\Connector\\Sabre\\ObjectTree->move('textfile0.txt', 'local_storage\/f...')\n#13 [internal function]: Sabre\\DAV\\CorePlugin->httpMove(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#14 \/srv\/www\/htdocs\/owncloud\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#15 \/srv\/www\/htdocs\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:MOVE', Array)\n#16 \/srv\/www\/htdocs\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#17 \/srv\/www\/htdocs\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(58): Sabre\\DAV\\Server->exec()\n#18 \/srv\/www\/htdocs\/owncloud\/remote.php(164): require_once('\/srv\/www\/htdocs...')\n#19 {main}","File":"\/srv\/www\/htdocs\/owncloud\/apps\/encryption\/lib\/Crypto\/Crypt.php","Line":653,"User":"user0"}
[Tue Jan 24 14:42:06 2017] 127.0.0.1:35786 [500]: /remote.php/webdav/textfile0.txt
    And User "user0" moved file "/textfile0.txt" to "/local_storage/foo/textfile0.txt" # FeatureContext::userMovedFile()
      Server error response [url] http://localhost:8080/remote.php/webdav/textfile0.txt [status code] 500 [reason phrase] Internal Server Error (GuzzleHttp\Exception\ServerException)
    And folder "/local_storage/foo" of user "user0" is shared with user "user1"        # FeatureContext::assureFileIsShared()
    And As an "user1"                                                                  # FeatureContext::asAn()
    When creating a share with                                                         # FeatureContext::creatingShare()
      | path      | foo |
      | shareType | 3   |                                                                                                                                                                                         
    Then the OCS status code should be "100"                                           # FeatureContext::theOCSStatusCodeShouldBe()
    And the HTTP status code should be "200"                                           # FeatureContext::theHTTPStatusCodeShouldBe()
    And Share fields of last share match with                                          # FeatureContext::checkShareFields()
      | id       | A_NUMBER             |
      | url      | AN_URL               |                                                                                                                                                                         
      | token    | A_TOKEN              |                                                                                                                                                                         
      | mimetype | httpd/unix-directory |                                                                                                                                                                         

```

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
