### ISSUE TITLE
[stable6] Setup S3 with non-empty bucket exception, OC unusable

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11870]
### Steps to reproduce:
1. Create a S3 bucket and upload a single file in it (I uploaded the picture of a delicious burger)
2. Setup ownCloud 6.0.6 RC1 (stable6)
3. Enable external storage and setup S3 storage against this bucket

### Expected result
Bucket can be accessed.

### Actual result
As soon as I went to the files app, this exception appears:
```
{"reqId":"54524a638e5f2","app":"index","message":"Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `path_hash`, `path`, `parent`, `name`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)':\n\nSQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'mtime' at row 1","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #1 \/srv\/www\/htdocs\/owncloud\/lib\/private\/db\/statementwrapper.php(70): Doctrine\\DBAL\\Statement->execute(Array)","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #2 \/srv\/www\/htdocs\/owncloud\/lib\/private\/db.php(285): OC_DB_StatementWrapper->execute(Array)","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #3 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/cache\/cache.php(232): OC_DB::executeAudited('INSERT INTO `*P...', Array)","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #4 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/cache\/scanner.php(184): OC\\Files\\Cache\\Cache->put('', Array)","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #5 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/cache\/scanner.php(155): OC\\Files\\Cache\\Scanner->addToCache('', Array)","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #6 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/view.php(905): OC\\Files\\Cache\\Scanner->scanFile('')","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #7 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/filesystem.php(695): OC\\Files\\View->getDirectoryContent('\/', '')","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #8 \/srv\/www\/htdocs\/owncloud\/apps\/files\/lib\/helper.php(73): OC\\Files\\Filesystem::getDirectoryContent('\/')","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #9 \/srv\/www\/htdocs\/owncloud\/apps\/files\/index.php(78): OCA\\Files\\Helper::getFiles('\/')","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #10 \/srv\/www\/htdocs\/owncloud\/lib\/base.php(807): require_once('\/srv\/www\/htdocs...')","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #11 [internal function]: OC::loadAppScriptFile(Array)","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #12 \/srv\/www\/htdocs\/owncloud\/lib\/private\/router.php(127): call_user_func(Array, Array)","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #13 \/srv\/www\/htdocs\/owncloud\/lib\/base.php(725): OC_Router->match('\/apps\/files')","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #14 \/srv\/www\/htdocs\/owncloud\/index.php(30): OC::handleRequest()","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: #15 {main}","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
{"reqId":"54524a638e5f2","app":"index","message":"Exception: Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `path_hash`, `path`, `parent`, `name`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)':\n\nSQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'mtime' at row 1 - Caused by: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'mtime' at row 1[22007] ","level":4,"time":"2014-10-30T14:25:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files"}
```

The exception appears full screen on the web page, so I have no way to access the web UI.
I need to delete "mount.json" to get access back.

**Comment by PVince81** [comment]
There were no other reports of this issue in OC 6, so might not be worth a backport.
Closing.
