### ISSUE TITLE
White screen accessing admin or personal page

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13527]
### Steps to reproduce

1. Install master
2. Navigate to admin page (or personal page)

### Expected behaviour

Admin or personal page renders

### Actual behaviour

Get white screen

This is in the server log:

```

{"reqId":"0d9799eeb73fc8b7ba59ea3ec4474f6a","remoteAddr":"192.168.1.218","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/owncloud\/settings\/controller\/appsettingscontroller.php#70","level":3,"time":"2015-01-20T19:03:05+00:00"}
{"reqId":"afa79f367dbcd58005941d2d47a7a0b0","remoteAddr":"192.168.1.218","app":"index","message":"Exception: {\"Message\":\"js file not found: script:js\\\/select2\\\/select2 serverroot:\\\/var\\\/www\\\/html\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(153): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(104): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('user', 'settings')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/settings\\\/admin.php(125): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_75', Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(28): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-01-20T19:03:24+00:00"}
{"reqId":"afa79f367dbcd58005941d2d47a7a0b0","remoteAddr":"192.168.1.218","app":"PHP","message":"js file not found: script:js\/select2\/select2 serverroot:\/var\/www\/html\/owncloud at \/var\/www\/html\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-01-20T19:03:24+00:00"}


```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

Can't get to the build info - this is happening with the latest build

**Comment by karlitschek** [comment]
@DeepDiver1975

**Comment by LukasReschke** [comment]
https://github.com/owncloud/sharepoint/issues/143 ?

**Comment by LukasReschke** [comment]
Which was fixed 5 hours ago by https://github.com/owncloud/sharepoint/pull/144

**Comment by jnfrmarks** [comment]
and verified :)  I was just about to close this as user error because the install now works.  Closing.
