### ISSUE TITLE
Error while trying to get work using HHVM: Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function getSecureRandom() on a non-object (NULL)'

### ISSUE THREAD

**Issue by xaionaro** [owncloud/core#13521]
$ ./autotest-hhvm.sh 
        Using database oc_autotest
        Setup environment for sqlite testing ...
        INDEX

        Notice: Undefined index: SERVER_PROTOCOL in /srv/xnas/var/www/xnas.dxnet.ru/root/lib/private/response.php on line 57

        Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function getSecureRandom() on a non-object (NULL)' in /srv/xnas/var/www/xnas.dxnet.ru/root/lib/private/request.php:52
        Stack trace:
        #0 /srv/xnas/var/www/xnas.dxnet.ru/root/lib/private/log/owncloud.php(71): OC_Request::getRequestID()
        #1 (): OC_Log_Owncloud::write()
        #2 /srv/xnas/var/www/xnas.dxnet.ru/root/lib/private/log.php(157): call_user_func()
        #3 /srv/xnas/var/www/xnas.dxnet.ru/root/lib/private/log.php(49): OC\Log->log()
        #4 /srv/xnas/var/www/xnas.dxnet.ru/root/lib/private/legacy/log.php(50): OC\Log->emergency()
        #5 /srv/xnas/var/www/xnas.dxnet.ru/root/lib/public/util.php(82): OC_Log::write()
        #6 /srv/xnas/var/www/xnas.dxnet.ru/root/lib/public/util.php(99): OCP\Util::writeLog()
        #7 /srv/xnas/var/www/xnas.dxnet.ru/root/index.php(40): OCP\Util::logException()
        #8 {main}
        Error during setup

**Comment by xaionaro** [comment]
$ hhvm ./lib/base.php
    
    Notice: Undefined index: SERVER_PROTOCOL in /srv/xnas/var/www/xnas.dxnet.ru/root/lib/private/response.php on line 57
    
    Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function getSession() on a non-object (NULL)' in /srv/xnas/var/www/xnas.dxnet.ru/root/lib/private/template.php:53
    Stack trace:
    #0 /srv/xnas/var/www/xnas.dxnet.ru/root/lib/private/template.php(206): OC_Template->__construct()
    #1 /srv/xnas/var/www/xnas.dxnet.ru/root/lib/base.php(481): OC_Template::printErrorPage()
    #2 /srv/xnas/var/www/xnas.dxnet.ru/root/lib/base.php(1002): OC::init()
    #3 {main}

**Comment by xaionaro** [comment]
Sorry, the problem was that I didn't "clone"-d "3rdparty"…
