### ISSUE TITLE
Remote share with password cannot be mounted

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13526]
On master, but nees https://github.com/owncloud/core/pull/13506 to be applied first:

### Steps
1. As "user1": create a folder "folder"
2. Share "folder" with link, set a password
3. Log out
4. As "user2" on the same instance, open the link
5. Add to ownCloud (the same instance)
6. Getting "unknown error"

The log says "Passed token is not valid".
```
{"reqId":"0a75dbcbf1557247ced4272b6b14aff1","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the server container is deprecated. Use type annotations to inject core services instead!","level":0,"time":"2015-01-20T17:08:33+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_sharing\/external"}
{"reqId":"15b662b406ae36d2b8618953d494a469","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the server container is deprecated. Use type annotations to inject core services instead!","level":0,"time":"2015-01-20T17:08:34+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_sharing\/shareinfo?t=wNN0001MDhGfTpx"}
{"reqId":"15b662b406ae36d2b8618953d494a469","remoteAddr":"127.0.0.1","app":"core-preview","message":"Passed token parameter is not valid","level":0,"time":"2015-01-20T17:08:34+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_sharing\/shareinfo?t=wNN0001MDhGfTpx"}
{"reqId":"0a75dbcbf1557247ced4272b6b14aff1","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\Files_Sharing\\\\External\\\\Storage->getShareInfo()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(466): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(22): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->__call('getShareInfo', Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(22): OCA\\\\Files_Trashbin\\\\Storage->getShareInfo()\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/ajax\\\/external.php(55): OCA\\\\Files_Sharing\\\\External\\\\Scanner->scanAll()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_2406', Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_sha...')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(28): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/storage.php\",\"Line\":228}","level":4,"time":"2015-01-20T17:08:34+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_sharing\/external"}
```

@icewind1991 @LukasReschke @schiesbn 

Marked as OC 8 showstopper @karlitschek @DeepDiver1975

**Comment by PVince81** [comment]
CC @jnfrmarks did you observe this too ?

**Comment by PVince81** [comment]
This is the one with "Add to ownCloud", not the new style server to server sharing (which I haven't tried)

**Comment by PVince81** [comment]
Ok got it... the JS dialog that prompt for the password is broken. It doesn't send the password to the server.

Working on a fix.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/13540
