### ISSUE TITLE
owncloud.log full of "Sabre\\DAV\\Exception\\RequestedRangeNotSatisfiable"

### ISSUE THREAD

**Issue by chemnic** [owncloud/core#13565]
Hi.

My owncloud.log file is full of this:
```
{"app":"webdav","message":"Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (4146071) exceeded the size of the entity (4146071)","level":4,"time":"2015-01-21T15:17:49+00:00"}
{"app":"webdav","message":"Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (4146071) exceeded the size of the entity (4146071)","level":4,"time":"2015-01-21T15:19:50+00:00"}
{"app":"webdav","message":"Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (4146071) exceeded the size of the entity (4146071)","level":4,"time":"2015-01-21T15:21:50+00:00"}
{"app":"webdav","message":"Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (4146071) exceeded the size of the entity (4146071)","level":4,"time":"2015-01-21T15:23:49+00:00"}
{"app":"webdav","message":"Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (4146071) exceeded the size of the entity (4146071)","level":4,"time":"2015-01-21T15:25:49+00:00"}
{"app":"webdav","message":"Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (4146071) exceeded the size of the entity (4146071)","level":4,"time":"2015-01-21T15:27:50+00:00"}
{"app":"webdav","message":"Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (4146071) exceeded the size of the entity (4146071)","level":4,"time":"2015-01-21T15:29:50+00:00"}
{"app":"webdav","message":"Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (4146071) exceeded the size of the entity (4146071)","level":4,"time":"2015-01-21T15:38:51+00:00"}
{"app":"webdav","message":"Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (4146071) exceeded the size of the entity (4146071)","level":4,"time":"2015-01-21T15:40:51+00:00"}
{"app":"webdav","message":"Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (4146071) exceeded the size of the entity (4146071)","level":4,"time":"2015-01-21T15:42:51+00:00"}
```
Sync between clients is working. Web admin page shows the log as FATAL, but nothing more:

"Connectivity Checks: No problems found"

A quick google search tells me: "This exception is normally thrown when the user request a range that is out of the entity bounds."

Can someone give me a hint of what that means?
## Server configuration

Operating system: Ubuntu 12.04 (Container OpenVZ / Proxmox)

Web server: Apache 2.2.22

Database: MySql 5.5.40

PHP version: 5.4.36

ownCloud version: 7.0.4 (stable)

Installed since version 6

List of activated apps:
- Activity
- Deleted files
- Documents
- First Run Wizard
- Full Text Search
- ownCloud dependecies info
- ODF Viewer
- Pictures
- Share Files
- Text Editor
- Updater
- Versions
- Video Viewer
- Videos
## Config/config.php:
```
<?php
$CONFIG = array (
  'instanceid' => 'oc7ad26eb688',
  'passwordsalt' => 'nottherealpasswordsalt',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'nottherealdbpassword',
  'installed' => true,
  'loglevel' => '3',
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'overwritewebroot' => '/owncloud',
  'trusted_domains' => 
  array (
    0 => 'nube.example.com',
    1 => 'nube.example.locald',
  ),
  'secret' => 'nottherealsecret',
);
```
### All browsers are 

Firefox 34. Client's OS are Windows 7 and Ubuntu 12.04/14.04.

**Comment by karlitschek** [comment]
@icewind1991 any idea?

**Comment by v6sa** [comment]
Hello, same problem here.

**Comment by zubanst** [comment]
Hello; same problem here, OwnCloud 8.03:
Exception: {"Message":"The start offset (611844096) exceeded the size of the entity (611844096)","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/server.php(89): Sabre\\DAV\\Server->httpGet('photos\/DSCN3423...')\n#1 [internal function]: OC_Connector_Sabre_Server->httpGet('photos\/DSCN3423...')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(474): call_user_func(Array, 'photos\/DSCN3423...')\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('GET', 'photos\/DSCN3423...')\n#4 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(61): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(54): require_once('\/var\/www\/ownclo...')\n#6 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php","Line":605}

**Comment by Leicas** [comment]
Same here, owncloud 8.2
Exception: {"Message":"HTTP\/1.1 416 The start offset (391040) exceeded the size of the entity (391040)","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#6 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","Line":157}

**Comment by jwd42** [comment]
I'd like to add, that these errors for me are the cause of very large log files of 1.5GB+ in size.

**Comment by DeepDiver1975** [comment]
Which webdav Clients are you using?

**Comment by jwd42** [comment]
On my owncloud instance, we're using the following webdav clients: the official owncloud sync client, the windows builtin webdav client, and the nautilus webdav client on linux with gnome.

**Comment by chemnic** [comment]
Hi.

I have not seen this error in months. I think the problem was related with some bugs in Owncloud Client. Thare has been a lot of bug fixing in the client since I opened this issue. I think my specific issue is fixed.

I have only used the owncloud client and the web interface to access owncloud.

**Comment by PVince81** [comment]
Any steps to reproduce ? (ideally without synology)

**Comment by PVince81** [comment]
Is this still happening on 8.2.2 ?

The only case where the sync client uses range requests is when resuming downloads for big files when a download was interrupted.

**Comment by chemnic** [comment]
No. I'm closing.

**Comment by cdamken** [comment]
I'm seeing this behavior with 2.3.1 Client and WND with the server 9.1.5 

```
{"reqId":"A8FwbM7I9ayDTxlsDX/w","remoteAddr":"93.193.125.24","app":"webdav","message":"Exception: {"Message":"HTTP/1.1 416 The start offset (1354752) exceeded the size of the entity (709632)","Exception":"Sabre\DAV\Exception\RequestedRangeNotSatisfiable","Code":0,"Trace":"
#0 [internal function]: Sabre\DAV\CorePlugin->httpGet^^(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#1 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#2 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(459): Sabre\Event\EventEmitter->emit('method:GET', Array)
#3 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#4 /var/www/owncloud/apps/dav/appinfo/v1/webdav.php(61): Sabre\DAV\Server->exec()
#5 /var/www/owncloud/remote.php(164): require_once('/var/www/ownclo...')
#6 {main}","File":"/var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","Line":178,"User":"carlos"}","level":4,"time":"2017-06-27T15:46:34+02:00","method":"GET","url":"/remote.php/webdav/External-Storages/Ext-Sally/Western%20Digital/Series/Ingl%C3%A9s/The%20IT%20Crowd/Season%201/The%20IT%20Crowd%20-%201x01%20-%20Yesterdays%20Jam%20(Spanish%20sub).avi","user":"carlos"}
```

**Comment by cdamken** [comment]
in sync-client I get `connection closed`

**Comment by cdamken** [comment]
in my case the sync-client 2.3.2

**Comment by PVince81** [comment]
The desktop client is able to resume downloads. For this, it stores the already downloaded range and then requests the next range.

Now if the file was modified remotely on the SMB storage and ownCloud hasn't found out about this yet, it is possible that the desktop client is still sending the range expecting the old file to be there.

Normally if OC is able to detect the remote change, it would already stop that request with "Precondition Failed" as it would have a different etag.

I suspect that this could be a "remote update detection" issue of some sorts.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
