### ISSUE TITLE
Not all remote shares removed

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13569]
### Steps to reproduce
1. Install owncloud on two systems
2. on system one, upload a files and directories and remote share them with a user on system 2 (I don't know the exact number needed; I had around 5 remote shares)
3. on system two, log in and accept the shares
4. on system one, delete all the shares
5. on system two, verify all shares removed
### Expected behaviour

All shares removed from system one
### Actual behaviour

Some shares remain.
### Server Host info:

Ubuntu 14.04
PHP 5.5.9
### Log file

```

{"reqId":"b4b84ca355bcb53066a5fbb5891f3a4a","remoteAddr":"","app":"PHP","message":"touch():
 Unable to create file \/var\/www\/html\/owncloud\/data\/owncloud.log because No such file
or directory at \/var\/www\/html\/owncloud\/lib\/private\/log\/owncloud.php#48","level":3,"
time":"2015-01-21T15:01:19+00:00"}
{"reqId":"0dfc8cc3af4fc214689d7b3a99b7df3c","remoteAddr":"192.168.1.218","app":"mail","mess
age":"Could not instantiate mail function.","level":3,"time":"2015-01-21T15:39:49+00:00"}
{"reqId":"1a1e82586a3c78330c85df641ccf8984","remoteAddr":"192.168.1.218","app":"PHP","messa
ge":"Undefined index: \/var\/www\/html\/owncloud\/data\/at_admin\/files\/admFolder at \/var
\/www\/html\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"
2015-01-21T16:17:26+00:00"}
{"reqId":"64f68ea42edab9b961daa7bfd1483a7a","remoteAddr":"192.168.1.218","app":"index","mes
sage":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/own
cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(357): OCA\\\\Files_Sh
aring\\\\External\\\\Storage->hasUpdated('', 1421856577)\\n#1 \\\/var\\\/www\\\/html\\\/own
cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(357): OC\\\\Files\\\\
Storage\\\\Wrapper\\\\Wrapper->hasUpdated('', 1421856577)\\n#2 \\\/var\\\/www\\\/html\\\/ow
ncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(67): OC\\\\Files\\\\Storage\\\\Wr
apper\\\\Wrapper->hasUpdated('', 1421856577)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib
\\\/private\\\/files\\\/view.php(932): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Arr
ay)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(78
2): OC\\\\Files\\\\View->getFileInfo('\\\/\\\/p1_90.PNG', true)\\n#5 \\\/var\\\/www\\\/html
\\\/owncloud\\\/core\\\/ajax\\\/preview.php(34): OC\\\\Files\\\\Filesystem::getFileInfo('\\
\/\\\/p1_90.PNG')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/rou
te.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\
n#7 [internal function]: __lambda_func(Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/li
b\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_1033', Array)\\n#9 \\\/va
r\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/cor
e\\\/preview.p...')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(28): OC::handleRe
quest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_shari
ng\\\/lib\\\/external\\\/storage.php\",\"Line\":157}","level":4,"time":"2015-01-21T17:32:30
+00:00"}
{"reqId":"5a55e6af53669166a0421589140f482b","remoteAddr":"192.168.1.218","app":"index","mes
sage":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/own
cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(357): OCA\\\\Files_Sh
aring\\\\External\\\\Storage->hasUpdated('', 1421856310)\\n#1 \\\/var\\\/www\\\/html\\\/own
cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(357): OC\\\\Files\\\\
Storage\\\\Wrapper\\\\Wrapper->hasUpdated('', 1421856310)\\n#2 \\\/var\\\/www\\\/html\\\/ow
ncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(67): OC\\\\Files\\\\Storage\\\\Wr
apper\\\\Wrapper->hasUpdated('', 1421856310)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib
\\\/private\\\/files\\\/view.php(932): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Arr
ay)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(78
2): OC\\\\Files\\\\View->getFileInfo('\\\/\\\/p1_3.PNG', true)\\n#5 \\\/var\\\/www\\\/html\
\\/owncloud\\\/core\\\/ajax\\\/preview.php(34): OC\\\\Files\\\\Filesystem::getFileInfo('\\\
/\\\/p1_3.PNG')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/route
.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#
7 [internal function]: __lambda_func(Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\
\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_2729', Array)\\n#9 \\\/var\
\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/core\
e\\\/preview.p...')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(28): OC::handleRe
quest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_shari
ng\\\/lib\\\/external\\\/storage.php\",\"Line\":157}","level":4,"time":"2015-01-21T17:32:30
+00:00"}
{"reqId":"5a55e6af53669166a0421589140f482b","remoteAddr":"192.168.1.218","app":"index","mes
sage":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/own
cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(357): OCA\\\\Files_Sh
aring\\\\External\\\\Storage->hasUpdated('', 1421856310)\\n#1 \\\/var\\\/www\\\/html\\\/own
cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(357): OC\\\\Files\\\\
Storage\\\\Wrapper\\\\Wrapper->hasUpdated('', 1421856310)\\n#2 \\\/var\\\/www\\\/html\\\/ow
ncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(67): OC\\\\Files\\\\Storage\\\\Wr
apper\\\\Wrapper->hasUpdated('', 1421856310)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib
\\\/private\\\/files\\\/view.php(932): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Arr
ay)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(78
2): OC\\\\Files\\\\View->getFileInfo('\\\/\\\/p1_3.PNG', true)\\n#5 \\\/var\\\/www\\\/html\
\\/owncloud\\\/core\\\/ajax\\\/preview.php(34): OC\\\\Files\\\\Filesystem::getFileInfo('\\\
/\\\/p1_3.PNG')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/route
.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#
7 [internal function]: __lambda_func(Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\
\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_2729', Array)\\n#9 \\\/var\
\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/core\
\\/preview.p...')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(28): OC::handleRequ
est()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_sharing
\\\/lib\\\/external\\\/storage.php\",\"Line\":157}","level":4,"time":"2015-01-21T17:32:30+0
0:00"}
{"reqId":"8e02cb52c0749c903d3fa038d033368a","remoteAddr":"192.168.1.218","app":"index","mes
sage":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/own
cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(357): OCA\\\\Files_Sh
aring\\\\External\\\\Storage->hasUpdated('', 1421855364)\\n#1 \\\/var\\\/www\\\/html\\\/own
cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(357): OC\\\\Files\\\\
Storage\\\\Wrapper\\\\Wrapper->hasUpdated('', 1421855364)\\n#2 \\\/var\\\/www\\\/html\\\/ow
ncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(67): OC\\\\Files\\\\Storage\\\\Wr
apper\\\\Wrapper->hasUpdated('', 1421855364)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib
\\\/private\\\/files\\\/view.php(932): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Arr
ay)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(78
2): OC\\\\Files\\\\View->getFileInfo('\\\/\\\/pre_127.txt', true)\\n#5 \\\/var\\\/www\\\/ht
ml\\\/owncloud\\\/core\\\/ajax\\\/preview.php(34): OC\\\\Files\\\\Filesystem::getFileInfo('
\\\/\\\/pre_127.txt')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\
/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...
')\\n#7 [internal function]: __lambda_func(Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\
\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_1601', Array)\\n#9 \\
\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\
/core\\\/preview.p...')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(28): OC::hand
leRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_s
haring\\\/lib\\\/external\\\/storage.php\",\"Line\":157}","level":4,"time":"2015-01-21T17:3
2:30+00:00"}
{"reqId":"31f2ee1400774a17ae1d8b787cade1a8","remoteAddr":"192.168.1.218","app":"files","mes
sage":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/own
cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(357): OCA\\\\Files_Sh
aring\\\\External\\\\Storage->hasUpdated('', 1421855520)\\n#1 \\\/var\\\/www\\\/html\\\/own
cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(357): OC\\\\Files\\\\
Storage\\\\Wrapper\\\\Wrapper->hasUpdated('', 1421855520)\\n#2 \\\/var\\\/www\\\/html\\\/ow
ncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(67): OC\\\\Files\\\\Storage\\\\Wr
apper\\\\Wrapper->hasUpdated('', 1421855520)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib
\\\/private\\\/files\\\/view.php(932): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Arr
ay)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(78
2): OC\\\\Files\\\\View->getFileInfo('\\\/myphotos', true)\\n#5 \\\/var\\\/www\\\/html\\\/o
wncloud\\\/apps\\\/files\\\/ajax\\\/list.php(12): OC\\\\Files\\\\Filesystem::getFileInfo('\
\\/myphotos')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.p
hp(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#7
[internal function]: __lambda_func(Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\
/private\\\/route\\\/router.php(250): call_user_func('?lambda_287', Array)\\n#9 \\\/var\\\/
www\\\/html\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/apps\\\/
files\\\/aja...')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(28): OC::handleRequ
est()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_sharing
\\\/lib\\\/external\\\/storage.php\",\"Line\":157}","level":4,"time":"2015-01-21T17:32:59+0
0:00"}

```
### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-21T04:13:37+00:00

**Comment by karlitschek** [comment]
@schiesbn

**Comment by DeepDiver1975** [comment]
@PVince81 handled by your PR to catch exceptions in s2s? THX

**Comment by PVince81** [comment]
Possibly. Note that some shares only auto-delete when navigating into them (whenever something tries to find out whether they were updated). If the sync client runs once on them they should all disappear.

PR is here, need to try out: #13525

**Comment by nickvergessen** [comment]
This works as described by PVince81 for folders.
Files however, are not removed and can not be browsed into. So we need another way for them to proc the "find out whether still shared" thing, background job?

**Comment by PVince81** [comment]
The problem with the background job approach is that it will ping the remote server with a regular interval, which might not be desirable (especially when many users have lots of shares). On the other hand, it could be used as a general process to detect unavailable/obsolete remote storages (a bit like @Xenopathic's work)

**Comment by PVince81** [comment]
ref: https://github.com/owncloud/core/pull/13641

**Comment by DeepDiver1975** [comment]
@PVince81 8.2 I assume? THX

**Comment by PVince81** [comment]
Yes, let's move it to 8.2

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
