### ISSUE TITLE
S2S invite can't be browsed

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#13601]
Steps to reproduce

    * Install owncloud on two systems
    * on system one, remote share a file with a user on system two
    * on system two, accept share and validate access

Expected behaviour

I can browse the shared folder

Actual behaviour

I can't browse the shared folder (got redirected to the parent folder)

Recipient (that received the share)
```
{
	"reqId":"8a48c4a2c644449063469ffe97833e0d",
	"remoteAddr":"127.0.0.1",
	"app":"index",
	"message":"Exception: {
		"Message":"",
		"Code":0,
		"Trace":"
			#0 apps/files_sharing/lib/external/storage.php(166): OCA\Files_Sharing\External\Storage->getShareInfo()
			#1 [internal function]: OCA\Files_Sharing\External\Storage->checkStorageAvailability()
			#2 lib/private/files/storage/wrapper/wrapper.php(466): call_user_func_array(Array, Array)
			#3 [internal function]: OC\Files\Storage\Wrapper\Wrapper->__call('checkStorageAva...', Array)
			#4 [internal function]: OCA\Files_Trashbin\Storage->checkStorageAvailability()
			#5 lib/private/files/storage/wrapper/wrapper.php(466): call_user_func_array(Array, Array)
			#6 apps/files_sharing/lib/external/scanner.php(47): OC\Files\Storage\Wrapper\Wrapper->__call('checkStorageAva...', Array)
			#7 apps/files_sharing/lib/external/scanner.php(47): OCA\Files_Trashbin\Storage->checkStorageAvailability()
			#8 apps/files_sharing/lib/external/scanner.php(23): OCA\Files_Sharing\External\Scanner->scanAll()
			#9 lib/private/files/cache/scanner.php(332): OCA\Files_Sharing\External\Scanner->scan('', true, 1)
			#10 lib/private/files/utils/scanner.php(108): OC\Files\Cache\Scanner->backgroundScan()
			#11 apps/files/ajax/scan.php(29): OC\Files\Utils\Scanner->backgroundScan('')
			#12 lib/private/route/route.php(135) : runtime-created function(1): require_once('/home/mjob/Proj...')
			#13 [internal function]: __lambda_func(Array)
			#14 lib/private/route/router.php(250): call_user_func('\x00lambda_506', Array)
			#15 lib/base.php(763): OC\Route\Router->match('/apps/files/aja...')
			#16 index.php(28): OC::handleRequest()
			#17 {main}","File":"apps/files_sharing/lib/external/storage.php",
		"Line":250
	}",
	"level":4,
	"time":"2015-01-22T14:34:06+00:00",
	"method":"GET",
	"url":"/master/index.php/apps/files/ajax/scan.php?force=false&dir=&requesttoken=aIL4BLN6c03hc8RjCoLjdqx4Faeh4a"
}
```
Server (where the share is initiated)

```
{
	"reqId":"c1732ad34ae2b72815531927d5b03645",
	"remoteAddr":"127.0.0.1",
	"app":"index",
	"message":"Exception: {
		"Message":"The requested uri(/core/index.php/apps/files_sharing/shareinfo) cannot be processed by the script '/core//index.php')",
		"Code":0,
		"Trace":"
			#0 lib/base.php(763): OC_Request::getRawPathInfo()
			#1 index.php(28): OC::handleRequest()
			#2 {main}","File":"lib/private/request.php",
		"Line":297
	}",
	"level":4,
	"time":"2015-01-22T14:30:00+00:00"
}
```

**Comment by MorrisJobke** [comment]
cc @PVince81 s2s fun ;)

**Comment by karlitschek** [comment]
@schiesbn

**Comment by DeepDiver1975** [comment]
@MorrisJobke this versions did you test with? @icewind1991 fixed the double slash issue yesterday/today

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core/pull/13552

**Comment by MorrisJobke** [comment]
@DeepDiver1975 clone of 1 hour ago. But I will retest

**Comment by DeepDiver1975** [comment]
> "Message":"The requested uri(/core/index.php/apps/files_sharing/shareinfo) cannot be processed by the script '/core//index.php')",

maybe we need to remove double slashes from the scipt as well? @icewind1991 maybe you fine the time to have a look at this as well - THX

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Oh. This could also be caused by heavy quoting stuff that I tried to remove.

**Comment by MorrisJobke** [comment]
Unchanged message:

```
{"reqId":"695c80aa4f8289654362f88742b676c8","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/storage.php(166): OCA\\\\Files_Sharing\\\\External\\\\Storage->getShareInfo()\\n#1 [internal function]: OCA\\\\Files_Sharing\\\\External\\\\Storage->checkStorageAvailability()\\n#2 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(466): call_user_func_array(Array, Array)\\n#3 [internal function]: OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->__call('checkStorageAva...', Array)\\n#4 [internal function]: OCA\\\\Files_Trashbin\\\\Storage->checkStorageAvailability()\\n#5 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(466): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(47): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->__call('checkStorageAva...', Array)\\n#7 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(47): OCA\\\\Files_Trashbin\\\\Storage->checkStorageAvailability()\\n#8 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(23): OCA\\\\Files_Sharing\\\\External\\\\Scanner->scanAll()\\n#9 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(332): OCA\\\\Files_Sharing\\\\External\\\\Scanner->scan('', true, 1)\\n#10 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/files\\\/utils\\\/scanner.php(108): OC\\\\Files\\\\Cache\\\\Scanner->backgroundScan()\\n#11 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files\\\/ajax\\\/scan.php(29): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#12 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/home\\\/mjob\\\/Proj...')\\n#13 [internal function]: __lambda_func(Array)\\n#14 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_686', Array)\\n#15 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#16 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/index.php(28): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/storage.php\",\"Line\":250}","level":4,"time":"2015-01-22T14:34:00+00:00","method":"GET","url":"\/master\/index.php\/apps\/files\/ajax\/scan.php?force=false&dir=&requesttoken=aIL4BLN6c03hc8RjCoLjdqx4Faeh4a"}
```
and
```
{"reqId":"c1732ad34ae2b72815531927d5b03645","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Message\":\"The requested uri(\\\/core\\\/index.php\\\/apps\\\/files_sharing\\\/shareinfo) cannot be processed by the script '\\\/core\\\/\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/core\\\/lib\\\/base.php(763): OC_Request::getRawPathInfo()\\n#1 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/core\\\/index.php(28): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/core\\\/lib\\\/private\\\/request.php\",\"Line\":297}","level":4,"time":"2015-01-22T14:30:00+00:00"}
```

**Comment by MorrisJobke** [comment]
> `\\\/core\\\/\\\/index.php`

Nevertheless: It still seems to have the same doubled slash

**Comment by MorrisJobke** [comment]
I just retried and I missed an git pull on the first server. No it works.

**Comment by DeepDiver1975** [comment]
> I just retried and I missed an git pull on the first server. Now it works.

are you testing with two servers which run oc master branch?
can you please test a stable7 server to be mounted - just to make sure if this slash fix needs to be backported? THX

**Comment by DeepDiver1975** [comment]
@MorrisJobke ^

**Comment by MorrisJobke** [comment]
Just tested with stable7 and it works there too

**Comment by DeepDiver1975** [comment]
> Just tested with stable7 and it works there too

awesome - thx a lot!
