### ISSUE TITLE
Upgrade 7.4 --> 8.0: SQLSTATE[23000]: Integrity constraint violation: 19 oc_share_external.remote_id may not be NULL

### ISSUE THREAD

**Issue by mistersixt** [owncloud/core#13970]
Hi,

I just tried to do a manual upgrade von 7.04 to 8.0 on my Debian Wheezy machine with SQLite backend, during the upgrade I receive this error message:

$ ./occ upgrade
Turned on maintenance mode
Checked database schema update
An exception occurred while executing 'INSERT INTO oc_share_external (id, "remote", "share_token", "password", "name", "owner", "user", "mountpoint", "mountpoint_hash") SELECT id, remote, share_token, password, name, owner, user, mountpoint, mountpoint_hash FROM __temp__oc_share_external':

SQLSTATE[23000]: Integrity constraint violation: 19 oc_share_external.remote_id may not be NULL
Turned off maintenance mode
Update failed
$ 

Any help is welcome,

kind regards, Joerg.

**Comment by DeepDiver1975** [comment]
@icewind1991 migration testing seems to have issues.  Please have a look.  Thx

**Comment by jocelynthode** [comment]
Yep same exact problem here.

**Comment by steiff-clauss** [comment]
same problem here

**Comment by RPDiep** [comment]
Me as well

**Comment by svenehret** [comment]
same.

**Comment by berni123** [comment]
same problem

**Comment by berni123** [comment]
is there a work around to get the system up and running?

**Comment by berni123** [comment]
I fixed it, via sqlite3 owncloud.db / select * from oc_share_external (backing up the data) / delete from oc_share_external - redoing the upgrade task via the web interface - now my owncloud is running again. But please fix the issue ...

**Comment by svenehret** [comment]
Thanks, @berni123!

**Comment by LukasReschke** [comment]
@schiesbn Also FYI – getting tons of user reports of that in the forum and the tracker.

**Comment by RealRancor** [comment]
@LukasReschke Another one in #14369

**Comment by PVince81** [comment]
Ok, got some steps to reproduce:
1. Setup 7.0.4 with sqlite
2. Create two users "user1" and "user2"
3. Login as "user1"
4. Create a folder
5. Share folder with link
6. Log out
7. Open link, add to ownCloud
8. Login as "user2"
9. Confirm adding the remote share
10. Upgrade to 8.0.0
11. BOOM

Skipping the migration test with `./occ upgrade --skip-migration-test` does NOT work.
So it's not a problem with the upgrade simulation but a general problem.

**Comment by berni123** [comment]
My way into crash was:
1. Owncloud 7.x with sqlite
2. Login as user
3. Add a link to a remote share (from a foreign owncloud instance)
4. Upgrade to 8.0
5. BOOM

As mentioned above - deleting the entry in oc_share_external let the upgrade process running without error.

**Comment by PVince81** [comment]
Next time you find an issue, try and get into the habit of posting owncloud.log as stated in the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md.
A bit more helpful than "me too". :wink: 

So, here it is (wow, so long!):
```
{
  "reqId": "136ba14b526d479303cf8eaf3d93de73",
  "remoteAddr": "",
  "app": "core",
  "message": "
Failed to update database structure (exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_share_external.remote_id' in \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/PDOConnection.php:104\nStack trace:\n
#0 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/PDOConnection.php(104): PDO->query('INSERT INTO oc_...')\n
#1 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(937): Doctrine\\DBAL\\Driver\\PDOConnection->query('INSERT INTO oc_...')\n
#2 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db\\/migrator.php(200): Doctrine\\DBAL\\Connection->query('INSERT INTO oc_...')\n
#3 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db\\/migrator.php(50): OC\\DB\\Migrator->applySchema(Object(Doctrine\\DBAL\\Schema\\Schema))\n
#4 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db\\/mdb2schemamanager.php(101): OC\\DB\\Migrator->migrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n
#5 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db.php(235): OC\\DB\\MDB2SchemaManager->updateDbFromStructure('\\/srv\\/www\\/htdocs...')\n
#6 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/app.php(1159): OC_DB::updateDbFromStructure('\\/srv\\/www\\/htdocs...')\n
#7 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/updater.php(299): OC_App::updateApp('files_sharing')\n
#8 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/updater.php(225): OC\\Updater->doAppUpgrade()\n
#9 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/updater.php(149): OC\\Updater->doUpgrade('8.0.0.7', '7.0.4.2')\n
#10 \\/srv\\/www\\/htdocs\\/owncloud\\/core\\/command\\/upgrade.php(118): OC\\Updater->upgrade()\n
#11 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Command\\/Command.php(252): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#12 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(889): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#13 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(193): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#14 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(124): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#15 \\/srv\\/www\\/htdocs\\/owncloud\\/console.php(58): Symfony\\Component\\Console\\Application->run()\n
#16 \\/srv\\/www\\/htdocs\\/owncloud\\/occ(11): require_once('\\/srv\\/www\\/htdocs...')\n
#17 {main}\n\nNext exception 'Doctrine\\DBAL\\Driver\\PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_share_external.remote_id' in \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/PDOConnection.php:106\nStack trace:\n
#0 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(937): Doctrine\\DBAL\\Driver\\PDOConnection->query('INSERT INTO oc_...')\n
#1 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db\\/migrator.php(200): Doctrine\\DBAL\\Connection->query('INSERT INTO oc_...')\n
#2 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db\\/migrator.php(50): OC\\DB\\Migrator->applySchema(Object(Doctrine\\DBAL\\Schema\\Schema))\n
#3 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db\\/mdb2schemamanager.php(101): OC\\DB\\Migrator->migrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n
#4 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db.php(235): OC\\DB\\MDB2SchemaManager->updateDbFromStructure('\\/srv\\/www\\/htdocs...')\n
#5 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/app.php(1159): OC_DB::updateDbFromStructure('\\/srv\\/www\\/htdocs...')\n
#6 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/updater.php(299): OC_App::updateApp('files_sharing')\n
#7 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/updater.php(225): OC\\Updater->doAppUpgrade()\n
#8 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/updater.php(149): OC\\Updater->doUpgrade('8.0.0.7', '7.0.4.2')\n
#9 \\/srv\\/www\\/htdocs\\/owncloud\\/core\\/command\\/upgrade.php(118): OC\\Updater->upgrade()\n
#10 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Command\\/Command.php(252): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#11 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(889): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#12 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(193): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#13 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(124): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#14 \\/srv\\/www\\/htdocs\\/owncloud\\/console.php(58): Symfony\\Component\\Console\\Application->run()\n
#15 \\/srv\\/www\\/htdocs\\/owncloud\\/occ(11): require_once('\\/srv\\/www\\/htdocs...')\n
#16 {main}\n\nNext exception 'Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException' with message 'An exception occurred while executing 'INSERT INTO oc_share_external (id, \"remote\", \"share_token\", \"password\", \"name\", \"owner\", \"user\", \"mountpoint\", \"mountpoint_hash\") SELECT id, remote, share_token, password, name, owner, user, mountpoint, mountpoint_hash FROM __temp__oc_share_external':\n\nSQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_share_external.remote_id' in \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractSQLiteDriver.php:53\nStack trace:\n
#0 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n
#1 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(947): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOSqlite\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO oc_...')\n
#2 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db\\/migrator.php(200): Doctrine\\DBAL\\Connection->query('INSERT INTO oc_...')\n
#3 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db\\/migrator.php(50): OC\\DB\\Migrator->applySchema(Object(Doctrine\\DBAL\\Schema\\Schema))\n
#4 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db\\/mdb2schemamanager.php(101): OC\\DB\\Migrator->migrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n
#5 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/db.php(235): OC\\DB\\MDB2SchemaManager->updateDbFromStructure('\\/srv\\/www\\/htdocs...')\n
#6 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/app.php(1159): OC_DB::updateDbFromStructure('\\/srv\\/www\\/htdocs...')\n
#7 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/updater.php(299): OC_App::updateApp('files_sharing')\n
#8 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/updater.php(225): OC\\Updater->doAppUpgrade()\n
#9 \\/srv\\/www\\/htdocs\\/owncloud\\/lib\\/private\\/updater.php(149): OC\\Updater->doUpgrade('8.0.0.7', '7.0.4.2')\n
#10 \\/srv\\/www\\/htdocs\\/owncloud\\/core\\/command\\/upgrade.php(118): OC\\Updater->upgrade()\n
#11 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Command\\/Command.php(252): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#12 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(889): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#13 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(193): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#14 \\/srv\\/www\\/htdocs\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(124): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n
#15 \\/srv\\/www\\/htdocs\\/owncloud\\/console.php(58): Symfony\\Component\\Console\\Application->run()\n
#16 \\/srv\\/www\\/htdocs\\/owncloud\\/occ(11): require_once('\\/srv\\/www\\/htdocs...')\n
#17 {main})
",
  "level": 4,
  "time": "2015-02-26T10:46:31+00:00",
  "method": "--",
  "url": "--"
}
```

**Comment by PVince81** [comment]
From what I see the DB schema is expecting "remote_id" to be non-null.
"remote_id" is a new column that was added in OC 8.0.0.

So whenever the schema upgrade runs, the schema migration will create that column. But there is no value for that column, but we also want it to be non-null. No wonder that it fails.

What wonders me even more is why that even works with MySQL ?!
Let's see... maybe with MySQL it puts in a dummy value.

**Comment by berni123** [comment]
Maybe in MySQL '' (empty string) is inserted or set as default value to never be null ;-)

**Comment by PVince81** [comment]
Hmm, but "empty string" does not fit into an "integer" column.

@schiesbn why is the column "remote_id" non-null ?

**Comment by PVince81** [comment]
The positive thing is that it seems that many people already adopted server to server sharing, which is good to know :smile:

**Comment by PVince81** [comment]
Ok, with Mariadb 10.0 the remote_id column automatically gets the value "0", which probably isn't much better than NULL.

@schiesbn can we remove the non-null requirement ?

**Comment by PVince81** [comment]
And if I use "add to ownCloud" in OC 8.0, the column remote_id gets the value "-1"...
Another idea would be to set a default value in the DB schema and set it to -1.

**Comment by PVince81** [comment]
Fixes here:
- stable8 (upcoming 8.0.1): https://github.com/owncloud/core/pull/14533
- master: https://github.com/owncloud/core/pull/14532

You can help testing this by applying the stable8 patch  https://github.com/owncloud/core/pull/14533.patch on your install (the one that refuses to upgrade) and let us know whether it worked.

Thanks!
