### ISSUE TITLE
Mixed errors on a fresh install of ownCloud 8.

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#14021]
### Steps to reproduce

Don´t know.

### Expected behavior

No errors

### Actual behavior

(You should make new lines in the downloadable owncloud.log)

```
[{"reqId":"c66669e3fc541d2cdaa36ced1ca934b6","remoteAddr":"46.236.021.00","app":"PHP","message":"Array to string conversion at \/var\/www\/html\/example.se\/owncloud\/lib\/private\/l10n\/string.php#75","level":3,"time":"2015-02-10T00:48:34+00:00"},{"reqId":"4694e4a550ae1bb3e31c6fa682f97c25","remoteAddr":"132.123.123.21","app":"webdav","message":"Exception: {\"Message\":\"expected filesize 1798759 got 0\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(84): OC_Connector_Sabre_File->put(Resource id #107)\\n#1 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(1647): OC_Connector_Sabre_Directory->createFile('IMG_2361.JPG', Resource id #107)\\n#2 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(900): Sabre\\\\DAV\\\\Server->createFile('Bilder\\\/2012\\\/Emm...', Resource id #107, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\Server->httpPut('Bilder\\\/2012\\\/Emm...')\\n#4 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 'Bilder\\\/2012\\\/Emm...')\\n#5 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PUT', 'Bilder\\\/2012\\\/Emm...')\\n#6 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/html\\\/f...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":130}","level":4,"time":"2015-02-09T21:45:42+00:00"},{"reqId":"6a676a50d517c00281d9f13ecb7b5ed8","remoteAddr":"123.123.23.13","app":"webdav","message":"Exception: {\"Message\":\"expected filesize 1735786 got 16384\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(84): OC_Connector_Sabre_File->put(Resource id #107)\\n#1 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(1647): OC_Connector_Sabre_Directory->createFile('IMG_2360.JPG', Resource id #107)\\n#2 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(900): Sabre\\\\DAV\\\\Server->createFile('Bilder\\\/2012\\\/Emm...', Resource id #107, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\Server->httpPut('Bilder\\\/2012\\\/Emm...')\\n#4 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 'Bilder\\\/2012\\\/Emm...')\\n#5 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PUT', 'Bilder\\\/2012\\\/Emm...')\\n#6 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/html\\\/f...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":130}","level":4,"time":"2015-02-09T21:45:42+00:00"},{"reqId":"9d068383241146997d86e0a73cf7a118","remoteAddr":"123.123.123.12","app":"webdav","message":"Exception: {\"Message\":\"expected filesize 1838293 got 16384\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(84): OC_Connector_Sabre_File->put(Resource id #107)\\n#1 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(1647): OC_Connector_Sabre_Directory->createFile('IMG_2359.JPG', Resource id #107)\\n#2 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(900): Sabre\\\\DAV\\\\Server->createFile('Bilder\\\/2012\\\/Emm...', Resource id #107, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\Server->httpPut('Bilder\\\/2012\\\/Emm...')\\n#4 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 'Bilder\\\/2012\\\/Emm...')\\n#5 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PUT', 'Bilder\\\/2012\\\/Emm...')\\n#6 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/html\\\/f...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":130}","level":4,"time":"2015-02-09T21:45:42+00:00"},{"reqId":"7e7d3f67eaf222c643ee6b880af76627","remoteAddr":"123.123.123.12","app":"index","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `permissions`, `path_hash`, `path`, `parent`, `name`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\\\"1\\\", \\\"2\\\", 1423498505, -1, \\\"54d8dd09e0764\\\", 1423498505, 31, \\\"3b8779ba05b8f0aed49650f3ff8beb4b\\\", \\\"thumbnails\\\", \\\"1\\\", \\\"thumbnails\\\", \\\"1\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-3b8779ba05b8f0aed49650f3ff8beb4b' for key 'fs_storage_path_hash'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/db\\\/statementwrapper.php(63): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/db.php(141): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(243): OC_DB::executeAudited('INSERT INTO `*P...', Array)\\n#5 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(184): OC\\\\Files\\\\Cache\\\\Cache->put('thumbnails', Array)\\n#6 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(155): OC\\\\Files\\\\Cache\\\\Scanner->addToCache('thumbnails', Array)\\n#7 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(125): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('thumbnails')\\n#8 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(214): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('thumbnails\\\/355', 3)\\n#9 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/updater.php(54): OC\\\\Files\\\\Cache\\\\Scanner->scan('thumbnails\\\/355', false)\\n#10 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(815): OC\\\\Files\\\\Cache\\\\Updater->update('\\\/thumbnails\\\/355')\\n#11 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(185): OC\\\\Files\\\\View->basicOperation('mkdir', 'thumbnails\\\/355\\\/', Array)\\n#12 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/preview.php(537): OC\\\\Files\\\\View->mkdir('thumbnails\\\/355\\\/')\\n#13 \\\/var\\\/www\\\/html\\\/fexample.se\\\/owncloud\\\/lib\\\/private\\\/preview.php(565): OC\\\\Preview->getPreview()\\n#14 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/core\\\/ajax\\\/preview.php(44): OC\\\\Preview->showPreview()\\n#15 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/f...')\\n#16 [internal function]: __lambda_func(Array)\\n#17 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_8832', Array)\\n#18 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#19 \\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/example.se\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66}","level":4,"time":"2015-02-09T16:15:05+00:00"},
```

So if any DEV out there care to interpret this error messages I would be happy to help you solve them.

### Server configuration

Ubuntu Server 14.04

**Database:**
Server version: 5.5.41-0ubuntu0.14.04.1 - (Ubuntu)
PHP version:
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version: (see ownCloud admin page)**
8.0
*Updated from an older ownCloud or fresh install:*
Fresh install on a new system

**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer

**Are you using external storage, if yes which one: local/smb/sftp/...**
No
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Version 39.0.2171.71 m
**Operating system:**
Windows 8.1
**Sync Client**
1.7.1 stable

### Logs

**Web server error log**

```
Insert your webserver log here
```

**ownCloud log (data/owncloud.log)**

```
As mentioned above
```

**Browser log**

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

CCing @PVince81 @LukasReschke since you helped me before.

**Comment by karlitschek** [comment]
@icewind1991 What do you think?

**Comment by MorrisJobke** [comment]
```
Array to string conversion at \/var\/www\/html\/example.se\/owncloud\/lib\/private\/l10n\/string.php#75
```

cc @DeepDiver1975

**Comment by PVince81** [comment]
@enoch85 can you enable the XDebug extension, hopefully it will show a stack trace in the log that can help find out the root cause for this message ? Thanks.

**Comment by PVince81** [comment]
Ok there seems to be a stack trace already, let me reformat it.

**Comment by PVince81** [comment]
```
{
  "reqId": "c66669e3fc541d2cdaa36ced1ca934b6",
  "remoteAddr": "46.236.021.00",
  "app": "PHP",
  "message": "Array to string conversion at /var/www/html/example.se/owncloud/lib/private/l10n/string.php#75",
  "level": 3,
  "time": "2015-02-10T00:48:34+00:00"
},
{
  "reqId": "4694e4a550ae1bb3e31c6fa682f97c25",
  "remoteAddr": "132.123.123.21",
  "app": "webdav",
  "message": "Exception: {\"Message\":\"expected filesize 1798759 got 0\",\"Code\":0,\"Trace\":\"
	#0 /var/www/html/example.se/owncloud/lib/private/connector/sabre/directory.php(84): OC_Connector_Sabre_File->put(Resource id #107)\n
	#1 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(1647): OC_Connector_Sabre_Directory->createFile('IMG_2361.JPG', Resource id #107)\n
	#2 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(900): Sabre\\DAV\\Server->createFile('Bilder/2012/Emm...', Resource id #107, NULL)\n
	#3 [internal function]: Sabre\\DAV\\Server->httpPut('Bilder/2012/Emm...')\n
	#4 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, 'Bilder/2012/Emm...')\n
	#5 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\\DAV\\Server->invokeMethod('PUT', 'Bilder/2012/Emm...')\n
	#6 /var/www/html/example.se/owncloud/apps/files/appinfo/remote.php(61): Sabre\\DAV\\Server->exec()\n
	#7 /var/www/html/example.se/owncloud/remote.php(54): require_once('/var/www/html/f...')\n
	#8 {main}\",\"File\":\"/var/www/html/example.se/owncloud/lib/private/connector/sabre/file.php\",\"Line\":130}",
  "level": 4,
  "time": "2015-02-09T21:45:42+00:00"
},
{
  "reqId": "6a676a50d517c00281d9f13ecb7b5ed8",
  "remoteAddr": "123.123.23.13",
  "app": "webdav",
  "message": "Exception: {\"Message\":\"expected filesize 1735786 got 16384\",\"Code\":0,\"Trace\":\"#0 /var/www/html/example.se/owncloud/lib/private/connector/sabre/directory.php(84): OC_Connector_Sabre_File->put(Resource id #107)\n#1 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(1647): OC_Connector_Sabre_Directory->createFile('IMG_2360.JPG', Resource id #107)\n#2 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(900): Sabre\\DAV\\Server->createFile('Bilder/2012/Emm...', Resource id #107, NULL)\n#3 [internal function]: Sabre\\DAV\\Server->httpPut('Bilder/2012/Emm...')\n#4 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, 'Bilder/2012/Emm...')\n#5 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\\DAV\\Server->invokeMethod('PUT', 'Bilder/2012/Emm...')\n#6 /var/www/html/example.se/owncloud/apps/files/appinfo/remote.php(61): Sabre\\DAV\\Server->exec()\n#7 /var/www/html/example.se/owncloud/remote.php(54): require_once('/var/www/html/f...')\n#8 {main}\",\"File\":\"/var/www/html/example.se/owncloud/lib/private/connector/sabre/file.php\",\"Line\":130}",
  "level": 4,
  "time": "2015-02-09T21:45:42+00:00"
},
{
  "reqId": "9d068383241146997d86e0a73cf7a118",
  "remoteAddr": "123.123.123.12",
  "app": "webdav",
  "message": "Exception: {\"Message\":\"expected filesize 1838293 got 16384\",\"Code\":0,\"Trace\":\"#0 /var/www/html/example.se/owncloud/lib/private/connector/sabre/directory.php(84): OC_Connector_Sabre_File->put(Resource id #107)\n#1 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(1647): OC_Connector_Sabre_Directory->createFile('IMG_2359.JPG', Resource id #107)\n#2 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(900): Sabre\\DAV\\Server->createFile('Bilder/2012/Emm...', Resource id #107, NULL)\n#3 [internal function]: Sabre\\DAV\\Server->httpPut('Bilder/2012/Emm...')\n#4 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, 'Bilder/2012/Emm...')\n#5 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\\DAV\\Server->invokeMethod('PUT', 'Bilder/2012/Emm...')\n#6 /var/www/html/example.se/owncloud/apps/files/appinfo/remote.php(61): Sabre\\DAV\\Server->exec()\n#7 /var/www/html/example.se/owncloud/remote.php(54): require_once('/var/www/html/f...')\n#8 {main}\",\"File\":\"/var/www/html/example.se/owncloud/lib/private/connector/sabre/file.php\",\"Line\":130}",
  "level": 4,
  "time": "2015-02-09T21:45:42+00:00"
},
{
  "reqId": "7e7d3f67eaf222c643ee6b880af76627",
  "remoteAddr": "123.123.123.12",
  "app": "index",
  "message": "Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `permissions`, `path_hash`, `path`, `parent`, `name`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\\"1\\", \\"2\\", 1423498505, -1, \\"54d8dd09e0764\\", 1423498505, 31, \\"3b8779ba05b8f0aed49650f3ff8beb4b\\", \\"thumbnails\\", \\"1\\", \\"thumbnails\\", \\"1\\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-3b8779ba05b8f0aed49650f3ff8beb4b' for key 'fs_storage_path_hash'\",\"Code\":0,\"Trace\":\"#0 /var/www/html/example.se/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 /var/www/html/example.se/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 /var/www/html/example.se/owncloud/lib/private/db/statementwrapper.php(63): Doctrine\\DBAL\\Statement->execute(Array)\n#3 /var/www/html/example.se/owncloud/lib/private/db.php(141): OC_DB_StatementWrapper->execute(Array)\n#4 /var/www/html/example.se/owncloud/lib/private/files/cache/cache.php(243): OC_DB::executeAudited('INSERT INTO `*P...', Array)\n#5 /var/www/html/example.se/owncloud/lib/private/files/cache/scanner.php(184): OC\\Files\\Cache\\Cache->put('thumbnails', Array)\n#6 /var/www/html/example.se/owncloud/lib/private/files/cache/scanner.php(155): OC\\Files\\Cache\\Scanner->addToCache('thumbnails', Array)\n#7 /var/www/html/example.se/owncloud/lib/private/files/cache/scanner.php(125): OC\\Files\\Cache\\Scanner->scanFile('thumbnails')\n#8 /var/www/html/example.se/owncloud/lib/private/files/cache/scanner.php(214): OC\\Files\\Cache\\Scanner->scanFile('thumbnails/355', 3)\n#9 /var/www/html/example.se/owncloud/lib/private/files/cache/updater.php(54): OC\\Files\\Cache\\Scanner->scan('thumbnails/355', false)\n#10 /var/www/html/example.se/owncloud/lib/private/files/view.php(815): OC\\Files\\Cache\\Updater->update('/thumbnails/355')\n#11 /var/www/html/example.se/owncloud/lib/private/files/view.php(185): OC\\Files\\View->basicOperation('mkdir', 'thumbnails/355/', Array)\n#12 /var/www/html/example.se/owncloud/lib/private/preview.php(537): OC\\Files\\View->mkdir('thumbnails/355/')\n#13 /var/www/html/fexample.se/owncloud/lib/private/preview.php(565): OC\\Preview->getPreview()\n#14 /var/www/html/example.se/owncloud/core/ajax/preview.php(44): OC\\Preview->showPreview()\n#15 /var/www/html/example.se/owncloud/lib/private/route/route.php(135) : runtime-created function(1): require_once('/var/www/html/f...')\n#16 [internal function]: __lambda_func(Array)\n#17 /var/www/html/example.se/owncloud/lib/private/route/router.php(250): call_user_func('?lambda_8832', Array)\n#18 /var/www/html/example.se/owncloud/lib/base.php(763): OC\\Route\\Router->match('/core/preview.p...')\n#19 /var/www/html/example.se/owncloud/index.php(36): OC::handleRequest()\n#20 {main}\",\"File\":\"/var/www/html/example.se/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php\",\"Line\":66}",
  "level": 4,
  "time": "2015-02-09T16:15:05+00:00"
},
```

**Comment by enoch85** [comment]
Could this have something to do with the sync client? @danimo

**Comment by enoch85** [comment]
Closing as the errors are gone. Just during the update.
