### ISSUE TITLE
Apache crashes and needs a restart

### ISSUE THREAD

**Issue by ckruetze** [owncloud/core#14256]
I'm having an issue with owncloud 8.0
For some reason apache crashes and needs a restart. I've also noticed that just restarting the service seems to not always work but restarting the entire server seems to solve the problem.

The system is an Ubuntu 14.04 server with a fresh install (no update) of owncloud 8.0 using ldap for user authentication.

I get the following messages in /var/log/apache2/error.log
```
[Sun Feb 15 11:40:18.446191 2015] [core:notice] [pid 1332] AH00052: child pid 1667 exit signal Segmentation fault (11)
[Sun Feb 15 11:40:18.512729 2015] [core:notice] [pid 1332] AH00052: child pid 1659 exit signal Segmentation fault (11)
[Sun Feb 15 11:40:19.781881 2015] [mpm_prefork:notice] [pid 1332] AH00169: caught SIGTERM, shutting down
[Sun Feb 15 11:40:34.478980 2015] [mpm_prefork:notice] [pid 1322] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Sun Feb 15 11:40:34.479704 2015] [core:notice] [pid 1322] AH00094: Command line: '/usr/sbin/apache2'
[Sun Feb 15 12:57:37.708964 2015] [core:notice] [pid 1322] AH00052: child pid 1666 exit signal Segmentation fault (11)
[Sun Feb 15 12:57:37.774930 2015] [core:notice] [pid 1322] AH00052: child pid 1556 exit signal Segmentation fault (11)
[Sun Feb 15 12:57:37.775178 2015] [mpm_prefork:notice] [pid 1322] AH00169: caught SIGTERM, shutting down
[Sun Feb 15 12:57:49.900431 2015] [mpm_prefork:notice] [pid 1357] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Sun Feb 15 12:57:49.901009 2015] [core:notice] [pid 1357] AH00094: Command line: '/usr/sbin/apache2'
[Sun Feb 15 15:45:22.983337 2015] [authz_core:error] [pid 1588] [client 10.49.1.17:47684] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Sun Feb 15 23:00:05.062013 2015] [mpm_prefork:notice] [pid 1357] AH00169: caught SIGTERM, shutting down
[Sun Feb 15 23:00:19.415868 2015] [mpm_prefork:notice] [pid 1378] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Sun Feb 15 23:00:19.416405 2015] [core:notice] [pid 1378] AH00094: Command line: '/usr/sbin/apache2'
[Mon Feb 16 12:17:06.042591 2015] [core:notice] [pid 1378] AH00052: child pid 1740 exit signal Segmentation fault (11)
[Mon Feb 16 12:17:06.108696 2015] [core:notice] [pid 1378] AH00052: child pid 1658 exit signal Segmentation fault (11)
[Mon Feb 16 12:17:06.109184 2015] [mpm_prefork:notice] [pid 1378] AH00169: caught SIGTERM, shutting down
[Mon Feb 16 12:17:21.047453 2015] [mpm_prefork:notice] [pid 1351] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Feb 16 12:17:21.048442 2015] [core:notice] [pid 1351] AH00094: Command line: '/usr/sbin/apache2'
[Mon Feb 16 15:35:32.448492 2015] [:error] [pid 1671] [client 10.49.1.112:54136] PHP Warning:  apc_store(): GC cache entry 'ochkgc8ykk8s/AutoloaderOCP\\Activity\\IConsumer' was on gc-list for 3612 s$
[Mon Feb 16 15:40:16.788443 2015] [core:notice] [pid 1351] AH00052: child pid 1676 exit signal Segmentation fault (11)
[Mon Feb 16 15:40:16.788828 2015] [mpm_prefork:notice] [pid 1351] AH00169: caught SIGTERM, shutting down
[Mon Feb 16 15:40:32.613631 2015] [mpm_prefork:notice] [pid 1351] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Feb 16 15:40:32.614286 2015] [core:notice] [pid 1351] AH00094: Command line: '/usr/sbin/apache2'
```
I have no idea of the messages are related but the timing is the same for when the server stops.

/var/log/owncloud.log is empty but the webinterface shows some messages.
The webinterface error messages don't correlate to the time the server needs a restart, they are just there all the time.
```
Error	PHP	ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58
```
(I think I had something like that before on owcCloud 7 on a different machine.

I also have some of the following messages, but I'm not sure if they correlate to the timings when the server needs a reboot. I'll investigate this more.
```
Fatal	webdav	Exception: {"Message":"The locktoken supplied does not match any locks on this entity","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Locks\/Plugin.php(94): Sabre\\DAV\\Locks\\Plugin->httpUnlock('Documents\/E-mai...')\n#1 [internal function]: Sabre\\DAV\\Locks\\Plugin->unknownMethod('UNLOCK', 'Documents\/E-mai...')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(433): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(478): Sabre\\DAV\\Server->broadcastEvent('unknownMethod', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('UNLOCK', 'Documents\/E-mai...')\n#5 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(61): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(54): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Locks\/Plugin.php","Line":356}
```

Please let me know if there is anything else I could test to help solve this issue.

**Comment by RealRancor** [comment]
Hi,

do you have an installed PHP ACPu running? If yes this could be related to https://github.com/owncloud/core/issues/14175

**Comment by ckruetze** [comment]
Hi @RealRancor 

not that I know. A fresh install of Ubuntu and then ownCloud. I didn't configure anything manually so if the default config includes this it might be the case.
But I'll try the suggestion from there and do an apt-get purge php5-apcu to see if it solves my problem.

**Comment by enoch85** [comment]
@ckruetze Please try the fix in #14175 

Here: https://github.com/owncloud/core/issues/14175#issuecomment-74573088 

If this works, please let us know.

**Comment by ckruetze** [comment]
Ok, tried the fix from #14175 now I just need to wait and see if it crashes. I'll report back tomorrow.

**Comment by enoch85** [comment]
@ckruetze Does it work?

**Comment by enoch85** [comment]
Closing via #14273

**Comment by ckruetze** [comment]
Sorry for the late reply, yes, it worked as expected. Thanks for finding a solution so quickly.

**Comment by enoch85** [comment]
Thank you for reporting.
