### ISSUE TITLE
Issue adding S3 External Storage

### ISSUE THREAD

**Issue by wingZero21** [owncloud/core#14371]
Hi,

I am trying to test adding the S3 External Storage option, however currently I am getting the below errors.

Any ideas on what might be causing this to occur.

I can access amazon s3 on port 443 from the server currently.

Details:
Error
```
Error	PHP	Undefined index: defaultValue at /var/www/html/owncloud/core/ajax/appconfig.php#30	2015-02-19T11:58:49+00:00
Fatal	files_external	Exception: {"Message":"Access Denied","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Exception\/NamespaceExceptionFactory.php(76): Aws\\Common\\Exception\\NamespaceExceptionFactory->createException('Aws\\\\S3\\\\Exceptio...', Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Message\\Response), Array)\n#1 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Exception\/ExceptionListener.php(55): Aws\\Common\\Exception\\NamespaceExceptionFactory->fromResponse(Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Message\\Response))\n#2 [internal function]: Aws\\Common\\Exception\\ExceptionListener->onRequestError(Object(Guzzle\\Common\\Event), 'request.error', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#3 \/var\/www\/html\/owncloud\/3rdparty\/symfony\/event-dispatcher\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\\Common\\Event), 'request.error', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#4 \/var\/www\/html\/owncloud\/3rdparty\/symfony\/event-dispatcher\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php(53): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\\Common\\Event))\n#5 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Message\/Request.php(589): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('request.error', Object(Guzzle\\Common\\Event))\n#6 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Message\/Request.php(378): Guzzle\\Http\\Message\\Request->processResponse(Array)\n#7 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(286): Guzzle\\Http\\Message\\Request->setState('complete', Array)\n#8 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(244): Guzzle\\Http\\Curl\\CurlMulti->processResponse(Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Curl\\CurlHandle), Array)\n#9 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(227): Guzzle\\Http\\Curl\\CurlMulti->processMessages()\n#10 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(211): Guzzle\\Http\\Curl\\CurlMulti->executeHandles()\n#11 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(105): Guzzle\\Http\\Curl\\CurlMulti->perform()\n#12 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMultiProxy.php(91): Guzzle\\Http\\Curl\\CurlMulti->send()\n#13 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Client.php(282): Guzzle\\Http\\Curl\\CurlMultiProxy->send()\n#14 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Client\/AbstractClient.php(262): Guzzle\\Http\\Client->send(Object(Guzzle\\Http\\Message\\Request))\n#15 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Message\/Request.php(198): Aws\\Common\\Client\\AbstractClient->send(Object(Guzzle\\Http\\Message\\Request))\n#16 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/RedirectPlugin.php(221): Guzzle\\Http\\Message\\Request->send()\n#17 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/RedirectPlugin.php(82): Guzzle\\Http\\RedirectPlugin->sendRedirectRequest(Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Message\\Response))\n#18 [internal function]: Guzzle\\Http\\RedirectPlugin->onRequestSent(Object(Guzzle\\Common\\Event), 'request.sent', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#19 \/var\/www\/html\/owncloud\/3rdparty\/symfony\/event-dispatcher\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\\Common\\Event), 'request.sent', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#20 \/var\/www\/html\/owncloud\/3rdparty\/symfony\/event-dispatcher\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php(53): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'request.sent', Object(Guzzle\\Common\\Event))\n#21 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Message\/Request.php(536): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('request.sent', Object(Guzzle\\Common\\Event))\n#22 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Message\/Request.php(577): Guzzle\\Http\\Message\\Request->dispatch('request.sent', Array)\n#23 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Message\/Request.php(378): Guzzle\\Http\\Message\\Request->processResponse(Array)\n#24 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(286): Guzzle\\Http\\Message\\Request->setState('complete', Array)\n#25 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(244): Guzzle\\Http\\Curl\\CurlMulti->processResponse(Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Curl\\CurlHandle), Array)\n#26 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(227): Guzzle\\Http\\Curl\\CurlMulti->processMessages()\n#27 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(211): Guzzle\\Http\\Curl\\CurlMulti->executeHandles()\n#28 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(105): Guzzle\\Http\\Curl\\CurlMulti->perform()\n#29 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMultiProxy.php(91): Guzzle\\Http\\Curl\\CurlMulti->send()\n#30 \/var\/www\/html\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Client.php(282): Guzzle\\Http\\Curl\\CurlMultiProxy->send()\n#31 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Client\/AbstractClient.php(262): Guzzle\\Http\\Client->send(Object(Guzzle\\Http\\Message\\Request))\n#32 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Guzzle\/Service\/Client.php(136): Aws\\Common\\Client\\AbstractClient->send(Object(Guzzle\\Http\\Message\\Request))\n#33 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Guzzle\/Service\/Command\/AbstractCommand.php(153): Guzzle\\Service\\Client->execute(Object(Aws\\S3\\Command\\S3Command))\n#34 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Guzzle\/Service\/Command\/AbstractCommand.php(189): Guzzle\\Service\\Command\\AbstractCommand->execute()\n#35 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Guzzle\/Service\/Client.php(76): Guzzle\\Service\\Command\\AbstractCommand->getResult()\n#36 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Client\/AbstractClient.php(107): Guzzle\\Service\\Client->__call('GetBucketAcl', Array)\n#37 \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/amazons3.php(548): Aws\\Common\\Client\\AbstractClient->__call('getBucketAcl', Array)\n#38 \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/amazons3.php(548): Aws\\S3\\S3Client->getBucketAcl(Array)\n#39 \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/config.php(457): OC\\Files\\Storage\\AmazonS3->test(false)\n#40 \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/config.php(392): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\n#41 \/var\/www\/html\/owncloud\/apps\/files_external\/settings.php(47): OC_Mount_Config::getSystemMountPoints()\n#42 \/var\/www\/html\/owncloud\/lib\/private\/app.php(713): include('\/var\/www\/html\/o...')\n#43 \/var\/www\/html\/owncloud\/settings\/admin.php(88): OC_App::getForms('admin')\n#44 \/var\/www\/html\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/html\/o...')\n#45 [internal function]: __lambda_func(Array)\n#46 \/var\/www\/html\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('\\x00lambda_373', Array)\n#47 \/var\/www\/html\/owncloud\/lib\/base.php(763): OC\\Route\\Router->match('\/settings\/admin')\n#48 \/var\/www\/html\/owncloud\/index.php(36): OC::handleRequest()\n#49 {main}","File":"\/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Exception\/NamespaceExceptionFactory.php","Line":91}	2015-02-19T11:58:46+00:00
Error	PHP	Undefined index: lastmodified at /var/www/html/owncloud/apps/files_external/lib/amazons3.php#298	2015-02-19T11:47:04+00:00
```
Access
```
telnet s3.amazonaws.com 443
Trying 54.231.13.56...
Connected to s3.amazonaws.com.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
``

**Comment by karlitschek** [comment]
@butonic any idea?

**Comment by mckaygerhard** [comment]
i have same problem, before using oc 7.X

i suspect its a incompatibility with php 5.3 versions.. same problem happened to me in a plugin that uses php 4 only, so i guess must revise the code of apps and of the ajax core
 fix that problem, are afffecting me the mail php sending method

**Comment by PVince81** [comment]
Are you still seeing this issue with 7.0.7 or 8.0.5 ?

**Comment by mckaygerhard** [comment]
still have

**Comment by PVince81** [comment]
PHP 5.3 isn't supported any more. Please upgrade.

If this issue still happens with 8.1.5 or 8.2.2, feel free to reopen.
