### ISSUE TITLE
Pictures view does not build

### ISSUE THREAD

**Issue by tps800** [owncloud/core#14434]
### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure LDAP access
2. Upload a wealth of pictures
3. Browse to your owncloud instance, switch to pictures view

### Expected behaviour
Building pictures view with galerie

### Actual behaviour
Shows "Working Weel" forever

### Server configuration
**Operating system:** Oracle Linux 6.6

**Web server:** Apache 2.2.15-39.0.1

**Database:** PostgreSQL 9.3.6

**PHP version:** PHP 5.5.21

**ownCloud version:** 8.0.0-23.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:** ?

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server>.<local>.<domain>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by LukasReschke** [comment]
Thanks for reporting bugs back to us! Can I ask you to provide some server logs? Thanks!

**Comment by tps800** [comment]
```
$ grep 10.160.2.12 /data/owncloud/data/owncloud.log | grep 2015-02-24T10
{"reqId":"fdd7a33291f239526b101d1a4e7378f5","remoteAddr":"10.160.2.12","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=ghe-m,ou=users,ou=sw,ou=muc,dc=bfs,dc=de\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2015-02-24T10:01:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"fdd7a33291f239526b101d1a4e7378f5","remoteAddr":"10.160.2.12","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-02-24T10:01:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"fdd7a33291f239526b101d1a4e7378f5","remoteAddr":"10.160.2.12","app":"user_ldap","message":"readAttribute: uid=ghe-m,ou=users,ou=sw,ou=muc,dc=bfs,dc=de found","level":0,"time":"2015-02-24T10:01:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"fdd7a33291f239526b101d1a4e7378f5","remoteAddr":"10.160.2.12","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=ghe-m,ou=users,ou=sw,ou=muc,dc=bfs,dc=de\n)\n attr Array\n(\n    [0] => displayname\n)\n limit 500 offset 0","level":0,"time":"2015-02-24T10:01:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"fdd7a33291f239526b101d1a4e7378f5","remoteAddr":"10.160.2.12","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-02-24T10:01:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"b64fd99fe8539f294ecae121b0a0653f","remoteAddr":"10.160.2.12","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=sct-muc,ou=users,ou=z,ou=muc,dc=bfs,dc=de\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2015-02-24T10:03:16+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"b64fd99fe8539f294ecae121b0a0653f","remoteAddr":"10.160.2.12","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-02-24T10:03:16+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"b64fd99fe8539f294ecae121b0a0653f","remoteAddr":"10.160.2.12","app":"user_ldap","message":"readAttribute: uid=sct-muc,ou=users,ou=z,ou=muc,dc=bfs,dc=de found","level":0,"time":"2015-02-24T10:03:16+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"b64fd99fe8539f294ecae121b0a0653f","remoteAddr":"10.160.2.12","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=sct-muc,ou=users,ou=z,ou=muc,dc=bfs,dc=de\n)\n attr Array\n(\n    [0] => uid\n)\n limit 500 offset 0","level":0,"time":"2015-02-24T10:03:16+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"b64fd99fe8539f294ecae121b0a0653f","remoteAddr":"10.160.2.12","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-02-24T10:03:16+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"b64fd99fe8539f294ecae121b0a0653f","remoteAddr":"10.160.2.12","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=sct-muc,ou=users,ou=z,ou=muc,dc=bfs,dc=de\n)\n attr Array\n(\n    [0] => primaryGroupID\n)\n limit 500 offset 0","level":0,"time":"2015-02-24T10:03:16+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"b64fd99fe8539f294ecae121b0a0653f","remoteAddr":"10.160.2.12","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-02-24T10:03:16+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"b64fd99fe8539f294ecae121b0a0653f","remoteAddr":"10.160.2.12","app":"user_ldap","message":"Requested attribute primarygroupid not found for uid=sct-muc,ou=users,ou=z,ou=muc,dc=bfs,dc=de","level":0,"time":"2015-02-24T10:03:16+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"5e2eab136e60f2f55e328c54b7bce8c4","remoteAddr":"10.160.2.12","app":"index","message":"Exception: {\"Message\":\"js file not found: script:js\\\/chosen\\\/chosen.jquery.min serverroot:\\\/var\\\/www\\\/html\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(155): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(106): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('user', 'settings')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/settings\\\/admin.php(127): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_6', Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-02-24T10:03:48+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"}
{"reqId":"5e2eab136e60f2f55e328c54b7bce8c4","remoteAddr":"10.160.2.12","app":"PHP","message":"js file not found: script:js\/chosen\/chosen.jquery.min serverroot:\/var\/www\/html\/owncloud at \/var\/www\/html\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-02-24T10:03:48+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"}
{"reqId":"e66acf63db97da78294d2bfd8963e5a1","remoteAddr":"10.160.2.12","app":"user_ldap","message":"No DN found for  on ldap:\/\/ldap-muc.bfs.de","level":0,"time":"2015-02-24T10:06:37+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=a6c32469005b1fb50e84c5a1b7a16c24"}
{"reqId":"46d8a9496eab36e3b1d57532035bd01b","remoteAddr":"10.160.2.12","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=sct-muc,ou=users,ou=z,ou=muc,dc=bfs,dc=de\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2015-02-24T10:13:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"46d8a9496eab36e3b1d57532035bd01b","remoteAddr":"10.160.2.12","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-02-24T10:13:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"46d8a9496eab36e3b1d57532035bd01b","remoteAddr":"10.160.2.12","app":"user_ldap","message":"readAttribute: uid=sct-muc,ou=users,ou=z,ou=muc,dc=bfs,dc=de found","level":0,"time":"2015-02-24T10:13:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"46d8a9496eab36e3b1d57532035bd01b","remoteAddr":"10.160.2.12","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=sct-muc,ou=users,ou=z,ou=muc,dc=bfs,dc=de\n)\n attr Array\n(\n    [0] => uid\n)\n limit 500 offset 0","level":0,"time":"2015-02-24T10:13:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"46d8a9496eab36e3b1d57532035bd01b","remoteAddr":"10.160.2.12","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-02-24T10:13:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"46d8a9496eab36e3b1d57532035bd01b","remoteAddr":"10.160.2.12","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=sct-muc,ou=users,ou=z,ou=muc,dc=bfs,dc=de\n)\n attr Array\n(\n    [0] => primaryGroupID\n)\n limit 500 offset 0","level":0,"time":"2015-02-24T10:13:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"46d8a9496eab36e3b1d57532035bd01b","remoteAddr":"10.160.2.12","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-02-24T10:13:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"46d8a9496eab36e3b1d57532035bd01b","remoteAddr":"10.160.2.12","app":"user_ldap","message":"Requested attribute primarygroupid not found for uid=sct-muc,ou=users,ou=z,ou=muc,dc=bfs,dc=de","level":0,"time":"2015-02-24T10:13:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"2c55a0790d2d16c4b6ec75be3f113aff","remoteAddr":"10.160.2.12","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(123): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(103): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-02-24T10:17:37+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav"}
{"reqId":"8c972f6b7e5375920abaa54ebcb87613","remoteAddr":"10.160.2.12","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=sct-muc,ou=users,ou=z,ou=muc,dc=bfs,dc=de\n)\n attr Array\n(\n    [0] => displayname\n)\n limit 500 offset 0","level":0,"time":"2015-02-24T10:18:54+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/"}
{"reqId":"8c972f6b7e5375920abaa54ebcb87613","remoteAddr":"10.160.2.12","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-02-24T10:18:54+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/"}
{"reqId":"718ccc316183864ddae68e5e549ecae9","remoteAddr":"10.160.2.12","app":"core","message":"OC\\Tags::__construct, tags: Array\n(\n)\n","level":0,"time":"2015-02-24T10:18:55+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/list.php?dir=%2F&sort=name&sortdirection=asc"}
```

**Comment by PVince81** [comment]
Gallery app I suppose ? https://github.com/owncloud/gallery

**Comment by enoch85** [comment]
This is a dup. Will find the correct issue and link here.

**Comment by enoch85** [comment]
https://github.com/owncloud/gallery/issues/158

**Comment by enoch85** [comment]
@tps800 Please track this issue in the old issue instead.
