### ISSUE TITLE
6 to 7 to 8 upgrade fails 

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#14558]
### Steps to reproduce

1. Install owncloud 6.0.7 using the tarball
2. Sync local copy of S3 to 6.0.7
3. Upgrade to 7.0.5 using the tarball
4. Add the files_mv app
5. Create a few users
6. Share a few files
7. upgrade to 8.0 using the tarballs
8. Finish the upgrade in the UI

Note: I have done done any further analysis; I wanted to get this issue in.

### Expected behaviour

The admin user should be brought to ownCloud

### Actual behaviour

The admin user gets a white screen

Server Log file content:

```

{"reqId":"dc35af21f830cda0241234647793c4ff","remoteAddr":"192.168.1.219","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/private\\\/app.php(77): OC_App::loadApp('activity')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/private\\\/util.php(75): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/base.php(765): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/index.php(36): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/private\\\/app.php\",\"Line\":96}","level":4,"time":"2015-02-26T20:09:50+00:00"}
{"reqId":"9a02661b7d084b22eca0b21b76a6a6bc","remoteAddr":"192.168.1.219","app":"index","message":"Exception: {\"Message\":\"js file not found: script:js\\\/chosen\\\/chosen.jquery.min serverroot:\\\/var\\\/www\\\/html\\\/owncloud-607\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/private\\\/templatelayout.php(155): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/private\\\/templatelayout.php(106): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('guest', '')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/private\\\/template.php(197): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/private\\\/util.php(826): OC_Template::printGuestPage('', 'login', Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/base.php(869): OC_Util::displayLoginPage(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/base.php(824): OC::handleLogin()\\n#8 \\\/var\\\/www\\\/html\\\/owncloud-607\\\/index.php(36): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud-607\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-02-26T20:10:11+00:00"}
{"reqId":"9a02661b7d084b22eca0b21b76a6a6bc","remoteAddr":"192.168.1.219","app":"PHP","message":"js file not found: script:js\/chosen\/chosen.jquery.min serverroot:\/var\/www\/html\/owncloud-607 at \/var\/www\/html\/owncloud-607\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-02-26T20:10:11+00:00"}


```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

**Comment by LukasReschke** [comment]
> {"reqId":"9a02661b7d084b22eca0b21b76a6a6bc","remoteAddr":"192.168.1.219","app":"PHP","message":"js file not found: script:js\/chosen\/chosen.jquery.min serverroot:\/var\/www\/html\/owncloud-607 at \/var\/www\/html\/owncloud-607\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-02-26T20:10:11+00:00"}


This is a bug in files_mv which is not shipped by us and uses a file that we no longer ship with ownCloud => Nothing we can do.

**Comment by jnfrmarks** [comment]
I believe that we're supposed to handle this.  Let me do some follow up and will comment with my findings.

**Comment by LukasReschke** [comment]
> I believe that we're supposed to handle this. 

3rdparty apps will be disabled when updating by default since https://github.com/owncloud/core/pull/14518 which has been merged in the stable8 branch just 4 hours ago.

**Comment by jnfrmarks** [comment]
ohhhhh I thought it was already in .... I will retest

**Comment by LukasReschke** [comment]
It was in master but not in stable8 :)

**Comment by jnfrmarks** [comment]
OK.  I'll close this and reopen if the upgrade fails.
