### ISSUE TITLE
[stable7 only] encryption key broken for owner when deleting shared file as recipient

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14588]
### Steps
1. Enable encryption
2. Create two users "root" and "user1"
3. Login as "root"
4. Create a folder "test" and upload a file "test/pic.jpg" into it
5. Share "test" with "user1"
6. Login as "user1"
7. Delete the file "test/pic.jpg"
8. Login as "root"
9. Restore the file "pic.jpg" from trash
10. Try downloading the restored "test/pic.jpg"

### Expected result
File can be downloaded

### Actual result
File cannot be downloaded or is corrupt.

### Versions
Happens **only** on stable7 (eb778eb2b09636c4e34739e64e43ea7a6b590d6d)
Works properly on stable8 and master.

### Logs
```
{"reqId":"54f0a44cc6229","app":"core","message":"Encryption key not found for \"\/root\/files\/test\/pic.jpg\" during attempted read via stream","level":0,"time":"2015-02-27T17:07:24+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2Ftest%2Fpic.jpg&c=54f0a41f7ecc4&x=36&y=36&forceIcon=0"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: Encryption key not found for \"\/root\/files\/test\/pic.jpg\" during attempted read via stream","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #1 \/srv\/www\/htdocs\/owncloud\/apps\/files_encryption\/lib\/util.php(443): fread(Resource id #307, 8144)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #2 \/srv\/www\/htdocs\/owncloud\/apps\/files_encryption\/lib\/proxy.php(388): OCA\\Encryption\\Util->getFileSize('\/root\/files\/tes...')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #3 \/srv\/www\/htdocs\/owncloud\/lib\/private\/fileproxy.php(124): OCA\\Encryption\\Proxy->postFileSize('\/root\/files\/tes...', 1179600)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #4 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/view.php(783): OC_FileProxy::runPostProxies('filesize', '\/root\/files\/tes...', 1179600)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #5 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/view.php(269): OC\\Files\\View->basicOperation('filesize', '\/test\/pic.jpg')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #6 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/filesystem.php(582): OC\\Files\\View->filesize('\/test\/pic.jpg')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #7 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files.php(51): OC\\Files\\Filesystem::filesize('\/test\/pic.jpg')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #8 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files.php(115): OC_Files::sendHeaders('\/test\/pic.jpg', 'pic.jpg', false)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #9 \/srv\/www\/htdocs\/owncloud\/apps\/files\/ajax\/download.php(37): OC_Files::get('\/test', Array, false)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #10 \/srv\/www\/htdocs\/owncloud\/lib\/base.php(799): require_once('\/srv\/www\/htdocs...')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #11 [internal function]: OC::loadAppScriptFile(Array)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #12 \/srv\/www\/htdocs\/owncloud\/lib\/private\/route\/router.php(227): call_user_func(Array, Array)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #13 \/srv\/www\/htdocs\/owncloud\/lib\/base.php(707): OC\\Route\\Router->match('\/apps\/files\/aja...')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #14 \/srv\/www\/htdocs\/owncloud\/index.php(28): OC::handleRequest()","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44dcdd43","app":"index","message":"Exception: #15 {main}","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: Encryption key not found for \"\/root\/files\/test\/pic.jpg\" during attempted read via stream","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #1 \/srv\/www\/htdocs\/owncloud\/apps\/files_encryption\/lib\/util.php(443): fread(Resource id #307, 8144)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #2 \/srv\/www\/htdocs\/owncloud\/apps\/files_encryption\/lib\/proxy.php(388): OCA\\Encryption\\Util->getFileSize('\/root\/files\/tes...')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #3 \/srv\/www\/htdocs\/owncloud\/lib\/private\/fileproxy.php(124): OCA\\Encryption\\Proxy->postFileSize('\/root\/files\/tes...', 1179600)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #4 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/view.php(783): OC_FileProxy::runPostProxies('filesize', '\/root\/files\/tes...', 1179600)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #5 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/view.php(269): OC\\Files\\View->basicOperation('filesize', '\/test\/pic.jpg')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #6 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/filesystem.php(582): OC\\Files\\View->filesize('\/test\/pic.jpg')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #7 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files.php(51): OC\\Files\\Filesystem::filesize('\/test\/pic.jpg')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #8 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files.php(115): OC_Files::sendHeaders('\/test\/pic.jpg', 'pic.jpg', false)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #9 \/srv\/www\/htdocs\/owncloud\/apps\/files\/ajax\/download.php(37): OC_Files::get('\/test', Array, false)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #10 \/srv\/www\/htdocs\/owncloud\/lib\/base.php(799): require_once('\/srv\/www\/htdocs...')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #11 [internal function]: OC::loadAppScriptFile(Array)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #12 \/srv\/www\/htdocs\/owncloud\/lib\/private\/route\/router.php(227): call_user_func(Array, Array)","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #13 \/srv\/www\/htdocs\/owncloud\/lib\/base.php(707): OC\\Route\\Router->match('\/apps\/files\/aja...')","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #14 \/srv\/www\/htdocs\/owncloud\/index.php(28): OC::handleRequest()","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
{"reqId":"54f0a44df0c4d","app":"index","message":"Exception: #15 {main}","level":4,"time":"2015-02-27T17:07:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Ftest&files=pic.jpg"}
```

### State
This is the state after deleting the file as "user1":
```
root/files_encryption
root/files_encryption/root.private.key
root/files_encryption/share-keys
root/files_encryption/share-keys/test
root/files_encryption/share-keys/test/pic.jpg.root.shareKey
root/files_encryption/keyfiles
root/files_encryption/keyfiles/test
root/files_trashbin
root/files_trashbin/share-keys
root/files_trashbin/keyfiles
root/files_trashbin/versions
root/files_trashbin/files
root/files_trashbin/files/pic.jpg.d1425056978
user1/files_encryption
user1/files_encryption/user1.private.key
user1/files_encryption/share-keys
user1/files_encryption/keyfiles
user1/files_trashbin
user1/files_trashbin/share-keys
user1/files_trashbin/share-keys/pic.jpg.user1.shareKey.d1425056978
user1/files_trashbin/keyfiles
user1/files_trashbin/keyfiles/pic.jpg.key.d1425056978
user1/files_trashbin/versions
user1/files_trashbin/files
user1/files_trashbin/files/pic.jpg.d1425056978
```

And after restoring as "root":
```
root/files_encryption
root/files_encryption/root.private.key
root/files_encryption/share-keys
root/files_encryption/share-keys/test
root/files_encryption/share-keys/test/pic.jpg.root.shareKey
root/files_encryption/keyfiles
root/files_encryption/keyfiles/test
root/files_trashbin
root/files_trashbin/share-keys
root/files_trashbin/keyfiles
root/files_trashbin/versions
root/files_trashbin/files
user1/files_encryption
user1/files_encryption/user1.private.key
user1/files_encryption/share-keys
user1/files_encryption/keyfiles
user1/files_trashbin
user1/files_trashbin/share-keys
user1/files_trashbin/share-keys/pic.jpg.user1.shareKey.d1425056978
user1/files_trashbin/keyfiles
user1/files_trashbin/keyfiles/pic.jpg.key.d1425056978
user1/files_trashbin/versions
user1/files_trashbin/files
user1/files_trashbin/files/pic.jpg.d1425056978
```

The encryption code and keys logic has changed in stable8, which is likely to have indirectly fixed the issue. I didn't find anything yet that we could backport to stable7.

@schiesbn @icewind1991 @th3fallen @DeepDiver1975

**Comment by PVince81** [comment]
From what I see it looks like the deletion code "forgot" to also move the share key for "root" into the trashbin.

**Comment by PVince81** [comment]
@DeepDiver1975 @karlitschek please schedule. Will need a OC 7 specific fix.

**Comment by PVince81** [comment]
CC @jnfrmarks (for the test case)

**Comment by schiesbn** [comment]
fix merged
