### ISSUE TITLE
Thumbnail cache gets deleted after upload from smartphone

### ISSUE THREAD

**Issue by jmit79** [owncloud/core#14671]
Steps to reproduce

Take a picture with your smartphone (Instant upload enabled, filesize >1MB)
check your thumbnails cache directory on the server ($OC_HOME/data/user/thumbnails)

Expected result

Thumbnail cache persists upload

Actual result

The complete directory $OC_HOME/data/user/thumbnails gets deleted

Versions

ownCloud 8 (stable8)

Hints

I've traced the deletion of the folder back to this function call in $OC_HOME/lib/private/preview.php:

```php
/**
 * deletes all previews of a file
 */
public function deleteAllPreviews() {
        $file = $this->getFile();

        $fileInfo = $this->getFileInfo($file);

        $toDelete = $this->getChildren();
        $toDelete[] = $fileInfo;

        foreach ($toDelete as $delete) {
                if ($delete !== null && $delete !== false) {
                        /** @var \OCP\Files\FileInfo $delete */
                        $fileId = $delete->getId();

                        $previewPath = $this->getPreviewPath($fileId);
                        $this->userView->deleteAll($previewPath);
                        $this->userView->rmdir($previewPath);
                }
        }
}
```

If $fileId is null (for whatever reason) $previewPath results in thumbnails// and rmdir removes the whole directory.

This happens on my server every time i upload a picture and it's pretty annoying :-\

**Comment by nickvergessen** [comment]
I mean, we can easily add a `if (!$fileId) continue;` in there.
But the question is, why does it not have one, but still gets a FileInfo returned.

**Comment by jmit79** [comment]
i've raised the loglevel and added some debug messages (=DEBUG:) just before the rmdir and that's the output (truncated):

```
{"reqId":"cc2f5d57f2715167266bddc60c4ab3b2","remoteAddr":"10.10.10.10","app":"webdav","message":"Exception: {\"Message\":\"File with name SofortUpload\\\/IMG_20150302_132444.jpg could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(661): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('SofortUpload\\\/IM...')\\n#1 [internal function]: Sabre\\\\DAV\\\\Server->httpHead('SofortUpload\\\/IM...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 'SofortUpload\\\/IM...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('HEAD', 'SofortUpload\\\/IM...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":100}","level":0,"time":"2015-03-02T13:24:47+01:00","method":"HEAD","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg"}
{"reqId":"9301c3c58ca82b0c2294d9fdaba6e721","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Write lock requested for \/var\/www\/owncloud\/data\/testuser\/cache\/IMG_20150302_132444.jpg-chunking-5733-0","level":0,"time":"2015-03-02T13:24:48+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-0"}
{"reqId":"e0443db7835679e61760ee31d4e3ff71","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Write lock requested for \/var\/www\/owncloud\/data\/testuser\/cache\/IMG_20150302_132444.jpg-chunking-5733-2","level":0,"time":"2015-03-02T13:24:53+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-2"}
{"reqId":"e0443db7835679e61760ee31d4e3ff71","remoteAddr":"10.10.10.10","app":"lock","message":"PASS: Write lock succeeded on \/var\/www\/owncloud\/data\/testuser\/cache\/IMG_20150302_132444.jpg-chunking-5733-2","level":0,"time":"2015-03-02T13:24:53+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-2"}
...
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Destroying locks on \/var\/www\/owncloud\/data\/testuser\/cache\/IMG_20150302_132444.jpg-chunking-5733-3","level":0,"time":"2015-03-02T13:24:57+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/testuser\/cache\/IMG_20150302_132444.jpg-chunking-5733-3","level":0,"time":"2015-03-02T13:24:57+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Released lock handle Resource id #185 on \/var\/www\/owncloud\/data\/testuser\/cache\/IMG_20150302_132444.jpg-chunking-5733-3","level":0,"time":"2015-03-02T13:24:57+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/testuser\/cache\/IMG_20150302_132444.jpg-chunking-5733-3","level":0,"time":"2015-03-02T13:24:57+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"core","message":"DEBUG: previewPath:\"thumbnails\/\/\" deleted","level":0,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks\\Files::indexFile): An exception occurred while executing 'INSERT INTO `oc_lucene_status`(`status`) VALUES(?)' with params [\"N\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'","level":3,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Read lock requested for \/var\/www\/owncloud\/data\/testuser\/files\/SofortUpload\/IMG_20150302_132444.jpg.ocTransferId5733.part","level":0,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
...
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Incrementing lock type 2 count for \/var\/www\/owncloud\/data\/testuser\/files\/SofortUpload\/IMG_20150302_132444.jpg","level":0,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/testuser\/files\/SofortUpload\/IMG_20150302_132444.jpg","level":0,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Released lock handle Resource id #242 on \/var\/www\/owncloud\/data\/testuser\/files\/SofortUpload\/IMG_20150302_132444.jpg","level":0,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/testuser\/files\/SofortUpload\/IMG_20150302_132444.jpg","level":0,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"core","message":"DEBUG: previewPath:\"thumbnails\/184076\/\" deleted","level":0,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Destroying locks on \/var\/www\/owncloud\/data\/testuser\/files\/SofortUpload\/IMG_20150302_132444.jpg.ocTransferId5733.part","level":0,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/testuser\/files\/SofortUpload\/IMG_20150302_132444.jpg.ocTransferId5733.part","level":0,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"INFO: Released lock handle Resource id #238 on \/var\/www\/owncloud\/data\/testuser\/files\/SofortUpload\/IMG_20150302_132444.jpg.ocTransferId5733.part","level":0,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
{"reqId":"0cc3967237b22181d1cb2fde782d8842","remoteAddr":"10.10.10.10","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/testuser\/files\/SofortUpload\/IMG_20150302_132444.jpg.ocTransferId5733.part","level":0,"time":"2015-03-02T13:24:59+01:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20150302_132444.jpg-chunking-5733-4-3"}
```

**Comment by oparoz** [comment]
If Preview is using Node to get the FileInfo, then maybe this fixes things
https://github.com/owncloud/core/pull/14437

But I also see an exception in the logs and I think it would be a good idea to catch that before doing any delete operation.
cc @georgehrke

**Comment by nickvergessen** [comment]
I don't see it using the Node API, but it has a static cache, maybe that causes the troubles:
https://github.com/owncloud/core/blob/06aef4e8b1f2086971c62b064f810e24785fb215/lib/private/preview.php#L177-L178

**Comment by oparoz** [comment]
Actually, a couple of lines below
`$this->info = $this->fileView->getFileInfo($this->file);`
https://github.com/owncloud/core/blob/06aef4e8b1f2086971c62b064f810e24785fb215/lib/private/preview.php#L180

That's the same method which triggered this bug https://github.com/owncloud/core/issues/14390 and which is supposed to be fixed by https://github.com/owncloud/core/pull/14437

View->getFileInfo() can return null, false or a valid ID and there is no check in place afaict.

**Comment by oparoz** [comment]
Actually, on 8.0.1+, we just need to catch the exceptions returned by `getFileInfo()`
