### ISSUE TITLE
Upgrade 8.0.0 to 8.0.1 crashes OC

### ISSUE THREAD

**Issue by arnold-maderthaner** [owncloud/core#14700]
Hi !

I just upgraded from 8.0.0 to 8.0.1 using the ubuntu 14.04.2 LTS packages and now I'm not able to login anymore.
The owncloud log show the following:
```
{"reqId":"57067f96b9c3f4e522914cdc97c3a252","remoteAddr":"217.19.42.203","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(77): OC_App::loadApp('files_sharing')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(75): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(766): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":96}","level":4,"time":"2015-03-05T08:17:00+00:00"}
```

anyone can help on resovling this issue ?

**Comment by arnold-maderthaner** [comment]
after running sudo -u www-data php occ  upgrade OC 8.0.1 works again on my system
