### ISSUE TITLE
Establishing s2s connection not possible, issues in cert verification

### ISSUE THREAD

**Issue by godfuture** [owncloud/core#14747]
I have imported the self signed cert of the source server, but external storage connection is not established anyway. Maybe the verification is too strict. Is it possible to completely turn off cert verification for external storage connections?

```
Array
(
    [Exception] => Array
        (
            [Message] => Sabre\DAV\Exception: [CURL] Error while making request: SSL certificate problem: unable to get local issuer certificate (error code: 60)
            [Code] => 0
            [Trace] => #0 /var/www/owncloud/lib/private/files/storage/dav.php(382): OC\Files\Storage\DAV->convertSabreException(Object(Sabre\DAV\Exception))
#1 /var/www/owncloud/lib/private/files/storage/common.php(393): OC\Files\Storage\DAV->stat('')
#2 /var/www/owncloud/apps/files_external/lib/config.php(457): OC\Files\Storage\Common->test(true)
#3 /var/www/owncloud/apps/files_external/lib/config.php(539): OC_Mount_Config::getBackendStatus('\\OC\\Fiiiles\\Sttora..'Array, true)
#4 /var/www/owncloud/apps/files_external/ajax/addMountPoint.php(25): OC_Mount_Config::addMountPoint('WebDAV', '\\OC\\Fiiiles\\Sttora..'Array, 'user', 'Future', true)
#5 /var/www/owncloud/lib/private/route/route.php(135) : runtime-created function(1): require_once('/var/www/ownclo...')
#6 [internal function]: __lambda_func(Array)
#7 /var/www/owncloud/lib/private/route/router.php(250): call_user_func('\x00lambda_da_1', Array)
#8 /var/www/owncloud/lib/base.php(763): OC\Route\Router->match('/apps/files_ext...')
#9 /var/www/owncloud/index.php(36): OC::handleRequest()
#10 {main}
            [File] => /var/www/owncloud/lib/private/files/storage/dav.php
            [Line] => 594
        )

)
```

![e544cf04-c1ff-11e4-8aed-f51e57d0b444 1](https://cloud.githubusercontent.com/assets/4669278/6547874/9c17cf4a-c5e5-11e4-8e43-85e738efa6ca.png)

Source server: oc 7.0.4, iis 7.5 win 7 x64, php 5.5.15
Target server: oc 8.0.0, apache2, ubuntu 14.10, php 5.5.12

**Comment by karlitschek** [comment]
@LukasReschke any idea?

**Comment by LukasReschke** [comment]
@godfuture I received the certificate. Can you create a test share for me as well so that I can test mounting it using S2S?

**Comment by godfuture** [comment]
You can login now with test / its4test and mount root.

**Comment by LukasReschke** [comment]
Just for my understanding: When you refer to S2S do you mean an actual S2S share which can be created when accessing a public link and in the top right click "Add to your ownCloud" or a mounted external ownCloud instance via the files_external application?

**Comment by godfuture** [comment]
Good that you ask, my issue title is confusing. I originally intended to use s2s, but as I noticed "Add to your owncloud" button in files app was missing (Federated-Cloud-Sharing options are checked), I tried to mount the folder by external storage.

So the issue occurs when mounting another owncloud instance in files_external application.

**Comment by godfuture** [comment]
Can you imagine why the button is missing even options in admin page for sharing are set? Is s2s a completely differant case to external storage?

**Comment by karlitschek** [comment]
@LukasReschke What is your recommendation?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
