### ISSUE TITLE
S3 External Storage - Athentication mechanism v4 not supported?

### ISSUE THREAD

**Issue by flasheater** [owncloud/core#14893]
Trying to add external storage via Amazon S3 Bucket in Region Frankfurt fails with following
Exception: http://hastebin.com/devetufuxa.tex .

Possible explanation: https://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975 @butonic

**Comment by PVince81** [comment]
From reading https://github.com/owncloud/core/issues/12023 it seems it has worked before.

**Comment by flasheater** [comment]
It may be a regression. I have tested creating a bucket in Ireland, which works.

I will experiment with the "Region" setting, also as soon as 8.0.2 is available through the build service, I will try again.

On 16 March 2015 10:43:41 CET, Vincent Petry <notifications@github.com> wrote:
>From reading https://github.com/owncloud/core/issues/12023 it seems it
>has worked before.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/core/issues/14893#issuecomment-81542260

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PVince81** [comment]
@flasheater any more luck with 8.1.3 ?

**Comment by cmonteroluque** [comment]
@flasheater sorry, any update? thanks!

**Comment by flasheater** [comment]
#Update

Small test of external storage with 3 AWS S3 buckets in 3 different regions.

bucket/region/mapped folder in OC
* own-dump / Frankfurt(eu-central-1) / Dump
* own-place / US Standard(US) / Place
* own-yard / Ireland(eu-west-1) / Yard

## Result with minimal config

Configured only Folder name , bucket name and keys in OC.

* [ red ] (own-dump)[
http://owncloud.bugabinga.net/index.php/s/s1Hj3j2bKJtLLqN]
* [ green ] (own-place)[
http://owncloud.bugabinga.net/index.php/s/jZWwoIODG8NgCu3]
* [ green ] (own-yard)[
http://owncloud.bugabinga.net/index.php/s/p8Is0O05gyLQcbW]

"Dump" fails to mount. Corresponding log:
  > 2015-10-26T06:26:28+00:00Errorfiles_externalException:
{"Exception":"Exception","Message":"Creation of bucket failed. The
authorization mechanism you have provided is not supported. Please use
AWS4-HMAC-SHA256.","Code":0,"Trace":"#0
\/var\/www\/owncloud\/apps\/files_external\/lib\/amazons3.php(565):
OC\\Files\\Storage\\AmazonS3->getConnection()\n#1
\/var\/www\/owncloud\/apps\/files_external\/lib\/config.php(261):
OC\\Files\\Storage\\AmazonS3->test(false)\n#2
\/var\/www\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(237):
OC_Mount_Config::getBackendStatus('\\OC\\Files\\Stora...', Array,
false)\n#3
\/var\/www\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(257):
OCA\\Files_External\\Controller\\StoragesController->updateStorageStatus(Object(OCA\\Files_external\\Lib\\StorageConfig))\n#4
[internal function]:
OCA\\Files_External\\Controller\\StoragesController->show(1)\n#5
\/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159):
call_user_func_array(Array, Array)\n#6
\/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89):
OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_External\\Controller\\GlobalStoragesController),
'show')\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108):
OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_External\\Controller\\GlobalStoragesController),
'show')\n#8
\/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45):
OC\\AppFramework\\App::main('GlobalStoragesC...', 'show',
Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#9
[internal function]:
OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#10
\/var\/www\/owncloud\/lib\/private\/route\/router.php(282):
call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler),
Array)\n#11 \/var\/www\/owncloud\/lib\/base.php(831):
OC\\Route\\Router->match('\/apps\/files_ext...')\n#12
\/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#13
{main}","File":"\/var\/www\/owncloud\/apps\/files_external\/lib\/amazons3.php","Line":619}

## Result by specifying region
Unchanged. "Dump" never seems to authenticate.

Tested on OC 8.2.0
Am 25.10.2015 19:10 schrieb "C. Montero Luque" <notifications@github.com>:

**Comment by DeepDiver1975** [comment]
This is related to the heavily out dated aws sdk

@cmonteroluque 9.0 topic from my pov
@flasheater I see no way to get this working in the scope of 8.2 since the sdk is heavily out dated - sorry

**Comment by PVince81** [comment]
Feature freeze, moving to 9.1.

PRs are welcome if anyone would like to attempt updating the AWS SDK lib used by ownCloud.

**Comment by jaceq** [comment]
Any chance of this getting into 9.1 ?

**Comment by PVince81** [comment]
@Xenopathic do you have time to attempt updating the AWS SDK in files_external ?

**Comment by Xenopathic** [comment]
@PVince81 Yes, but I'm not very familiar with AWS and don't have access to a test instance in Frankfurt that only allows the v4 auth. If you could set me up with one however...

**Comment by PVince81** [comment]
@Xenopathic I think if you can submit a PR with the updated AWS libs and if the tests run against our CI it's already a big step. Then we can ask other folks here to help testing it.

**Comment by jaceq** [comment]
Is there anything I can maybe help with on this front?

**Comment by PVince81** [comment]
@butonic said that upgrading to the latest library requires PHP > 5.4.
However ownCloud needs to support PHP 5.4 for now, so we'll have to postpone upgrading the library.

This, unless there is a newer but not newest version that both supports PHP 5.4 and fixes the Frankfurt auth issue ? @butonic @rullzer

**Comment by rullzer** [comment]
Not as far as I know. We even use the old deprecated lib because of 5.4.... so I don't see a way to do this..

**Comment by PVince81** [comment]
If we could move the S3 ext storage into a separate app there could be two apps: one with the old lib and another one with the updated lib. The info.xml requirements already makes it possible to specify PHP versions, so one could only enable one of both at the same time.

Might be more complicated to maintain and test though...

CC @DeepDiver1975 as it brushes the topic of moving ext storage backends into apps

**Comment by jaceq** [comment]
It seems that latest SDK v2 (php 5.3 compatible) works with signature v4, this DOC seems to suggest that:
http://docs.aws.amazon.com/aws-sdk-php/v2/guide/configuration.html (section Endpoint and Signature Options have following description: The signature service scope for Signature V4. )

**Comment by PVince81** [comment]
@jaceq okay cool, so there's hope!

**Comment by PVince81** [comment]
Is this still an issue on master ? We updated some libraries...

**Comment by jaceq** [comment]
it seems to work now

**Comment by Zaheer22** [comment]
After updating to the latest stable 9.1.4.on Ubuntu 14.04 This issue persists for the ca-central-1 region. (This region is almost brand new to AWS). Fails with error 

"Exception: Creation of bucket failed. The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256" 

The bucket in fact, already exists but OwnCloud fails to connect. Specifying the "ca-central-1" region makes no difference. If you specify a non-existing bucket , it successfully auto-creates in the US standard region. Based on what I read here , I cannot simply update the AWS SDK. Any hopes?

**Comment by butonic** [comment]
@Zaheer22 if ca-central-1 is brand now, the sdk may not choose the correct signature algorithm. You can try forcing the signature with
```
--- apps/files_external/lib/Lib/Storage/AmazonS3.php	(revision )
+++ apps/files_external/lib/Lib/Storage/AmazonS3.php	(revision )
@@ -573,6 +573,7 @@
 			'secret' => $this->params['secret'],
 			'base_url' => $base_url,
 			'region' => $this->params['region'],
+			'signature' => 'v4',
 			S3Client::COMMAND_PARAMS => [
 				'PathStyle' => $this->params['use_path_style'],
 			],
```

But this forces v4 for all buckets ... It seems we need to update the library again, or allow giving the signature as a parameter.

**Comment by Zaheer22** [comment]
@butonic Thanks, I'll give that a shot. Which file are you referring to modifying though? I am new to OwnCloud.

**Comment by Zaheer22** [comment]
@butonic Adding the 'signature' => 'v4', makes everything work 100%. Perhaps adding it as a parameter is a safer way to go, to allow easier customization in the GUI in the future. Thanks!

**Comment by dirigeant** [comment]
I can still reproduce this issue with London zone (eu-west-2) even I set zone name. Suggested solution helped.

# sudo -u www-data ./occ status
  - installed: true                                                                                                                                                                                  
  - version: 10.0.2.1                                                                                                                                                                                
  - versionstring: 10.0.2                                                                                                                                                                            
  - edition: Community
