### ISSUE TITLE
"Could not acquire a shared lock on the config file" exception

### ISSUE THREAD

**Issue by ghost** [owncloud/core#15417]
Hi,

sorry currently not using the issue template because its not an issue of mine. But have seen this now several times for OC 8.0.x and want to report this. It seems that wrong permissions on the config file (or folder?) is thrown when some one is using either occ/console.php or cron.php like:

```
php occ db:convert-type --all-apps mysql _www 127.0.0.1 oc_mysql_db
PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /path/to/owncloud/lib/private/config.php on line 178
An unhandled exception has been thrown:
exception 'Exception' with message 'Could not acquire a shared lock on the config file /path/to/owncloud/config/config.php' in /path/to/owncloud/lib/private/config.php:179
Stack trace:
#0 /path/to/owncloud/lib/private/config.php(38): OC\Config->readData()
#1 /path/to/owncloud/lib/base.php(100): OC\Config->__construct('/path/to...')
#2 /path/to/owncloud/lib/base.php(473): OC::initPaths()
#3 /path/to/owncloud/lib/base.php(1011): OC::init()
#4 /path/to/owncloud/console.php(12): require_once('/Library/Server...')
#5 /path/to/owncloud/occ(11): require_once('/Library/Server...')
#6 {main}server:serverURL Server$ 
```

Sources:
https://forum.owncloud.org/viewtopic.php?f=31&t=27013#p81787
https://forum.owncloud.org/viewtopic.php?f=31&t=27071&p=81983#p81983

or

```
php /var/www/owncloud/occ files:scan --all
PHP Warning: flock() expects parameter 1 to be resource, boolean given in /var/www/owncloud/lib/private/config.php on line 178
An unhandled exception has been thrown:
exception 'Exception' with message 'Could not acquire a shared lock on the config file /var/www/owncloud/config/config.php' in /var/www/owncloud/lib/private/config.php:179
Stack trace:
#0 /var/www/owncloud/lib/private/config.php(38): OC\Config->readData()
#1 /var/www/owncloud/lib/base.php(100): OC\Config->__construct('/var/www/ownclo...')
#2 /var/www/owncloud/lib/base.php(473): OC::initPaths()
#3 /var/www/owncloud/lib/base.php(1011): OC::init()
#4 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#5 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
```

Source: https://forum.owncloud.org/viewtopic.php?f=31&t=27488&p=84211#p84209

Instead of throwing such an unhanded exception it might be useful to throw an message to the user that they should fix this permissions or use the correct user.

**Comment by Xenopathic** [comment]
The problem is, we can't write the error anywhere else at that point, since we couldn't read the configuration file and we might be in an undefined state. Trying to do anything smart there will result in corruption of some kind. The best we can do is abort the current execution by throwing an exception, and have that printed to the console or to the PHP error log.

However, this problem isn't actually anything to do with the exception. `flock() expects parameter 1 to be a resource, boolean given` indicates that the `fopen()` returned false, which means that the file itself couldn't be opened. The exception message is a bit misleading in this case. We just need an extra check if `fopen()` returned false instead of the file handle, and throw a different exception if this is the case.

**Comment by RealRancor** [comment]
Mhhh, the main problem here is that most users can't interpret this error/exception. But if its possible to fix the initial problem:

> flock() expects parameter 1 to be a resource, boolean given indicates that the fopen() returned false

and throw a meaningful exception that the user has to fix some permissions it would prevent a lot of trouble.

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/pull/15369

**Comment by RealRancor** [comment]
@nickvergessen 
In occ this check is already included but the flock error is also seen here (See first reported issue and the links)

**Comment by PVince81** [comment]
@RealRancor has this still been reported with recent versions ?

The only time I saw this error was when trying to run a command on a non-installed OC if I remember correctly.

**Comment by RealRancor** [comment]
@PVince81 Still happens from time to time like seen here:

https://forum.owncloud.org/viewtopic.php?t=32531

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
