### ISSUE TITLE
Sharing API malfunctions with maintenance mode

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15436]
### Steps to reproduce
1. Add several shares to the account
2. Set the maintenance mode
3. Use the sharing APIs (checked with `curl -u "$userpass" -v -X POST -F "path=$dir_to_share" -F "shareType=0" -F "shareWith=$user_share" -F "publicUpload=false" -F "permissions=1" "$baseOcUrl/ocs/v1.php/apps/files_sharing/api/v1/shares"` and `curl -u "userpass" -v -X GET "http://server/ocs/v1.php/apps/files_sharing/api/v1/shares"`  (GET and POST)

### Expected behaviour
Return a consistent error message, probably warning about the maintenance mode

### Actual behaviour
Inconsistent error message with the sharing backend

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

#### ownCloud log (data/owncloud.log)
```
{"reqId":"d80571dd22d9fd322b03d0cde6abc6d0","remoteAddr":"10.40.10.254","app":"OCP\\Share","message":"Sharing backend for file not found","level":3,"time":"2015-04-07T11:43:47+00:00"}
```

#### POST share
```
> POST http://10.40.30.21:8120/ocs/v1.php/apps/files_sharing/api/v1/shares HTTP/1.0
> Authorization: Basic anZpbGxhZmFuZXpAc29saWRnZWFyLmNvbTpvd25jbG91ZDEyMw==
> User-Agent: curl/7.35.0
> Host: 10.40.30.21:8120
> Accept: */*
> Proxy-Connection: Keep-Alive
> Content-Length: 556
> Content-Type: multipart/form-data; boundary=------------------------31041d6045167a8c
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Date: Tue, 07 Apr 2015 11:38:53 GMT
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.7
< Set-Cookie: ocecf5fb7748=ggvdr1c819b1pl70enmutr4a96; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
< X-Robots-Tag: none
< Set-Cookie: ocecf5fb7748=1fsavqbltbcbjed68ko6cqv8o6; path=/; HttpOnly
< Set-Cookie: oc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0
< Set-Cookie: oc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0
< Set-Cookie: oc_remember_login=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0
< Set-Cookie: oc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
< Set-Cookie: oc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
< Set-Cookie: oc_remember_login=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
< Set-Cookie: ocecf5fb7748=4mqttm79pe2ruv116st6l9d4t6; path=/; HttpOnly
< Vary: Accept-Encoding
< Content-Length: 175
< Content-Type: text/xml; charset=UTF-8
< X-Cache: MISS from squid.solidgear.prv
< X-Cache-Lookup: MISS from squid.solidgear.prv:3128
< Via: 1.0 squid.solidgear.prv (squid/3.1.19)
* HTTP/1.0 connection set to keep alive!
< Connection: keep-alive
< 
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>403</statuscode>
  <message>Sharing backend for file not found</message>
 </meta>
 <data/>
</ocs>
* Connection #0 to host 10.40.10.254 left intact
```

#### GET shares
```
> GET http://10.40.30.21:8120/ocs/v1.php/apps/files_sharing/api/v1/shares HTTP/1.0
> Authorization: Basic anZpbGxhZmFuZXpAc29saWRnZWFyLmNvbTpvd25jbG91ZDEyMw==
> User-Agent: curl/7.35.0
> Host: 10.40.30.21:8120
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Date: Tue, 07 Apr 2015 11:43:47 GMT
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.7
< Set-Cookie: ocecf5fb7748=o7rt5ufvsguoa0ilbushfes0m0; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
< X-Robots-Tag: none
< Set-Cookie: ocecf5fb7748=g2b1ej2e5311hbuuqmpa42upn3; path=/; HttpOnly
< Vary: Accept-Encoding
< Content-Type: text/html; charset=UTF-8
< X-Cache: MISS from squid.solidgear.prv
< X-Cache-Lookup: MISS from squid.solidgear.prv:3128
< Via: 1.0 squid.solidgear.prv (squid/3.1.19)
< Connection: close
< 
<!DOCTYPE html>
<!--[if lt IE 7]><html class="ng-csp ie ie6 lte9 lte8 lte7" data-placeholder-focus="false" lang="en"><![endif]-->
<!--[if IE 7]><html class="ng-csp ie ie7 lte9 lte8 lte7" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if IE 8]><html class="ng-csp ie ie8 lte9 lte8" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if IE 9]><html class="ng-csp ie ie9 lte9" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if gt IE 9]><html class="ng-csp ie" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if !IE]><!--><html class="ng-csp" data-placeholder-focus="false" lang="en" ><!--<![endif]-->

	<head data-requesttoken="">
		<title>
		ownCloud		</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=543672169">
		<link rel="shortcut icon" type="image/png" href="/core/img/favicon.png" />
		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png" />
					<link rel="stylesheet" href="/core/css/styles.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/header.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/mobile.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/icons.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/fonts.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/apps.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/fixes.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/multiselect.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/jquery-tipsy.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/styles.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/header.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
							<script type="text/javascript" src="/core/vendor/jquery/jquery.min.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/jquery/jquery-migrate.min.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/underscore/underscore.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/moment/min/moment-with-locales.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/handlebars/handlebars.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/placeholders.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/jquery-tipsy.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/compatibility.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/jquery.ocdialog.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/oc-dialogs.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/js.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/l10n.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/octemplate.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/eventsource.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/config.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/search/js/search.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/oc-requesttoken.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/apps.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/snapjs/dist/latest/snap.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/placeholder.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/blueimp-md5/js/md5.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/jquery.avatar.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/avatar.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					</head>
	<body id="body-login">
		<noscript><div id="nojavascript"><div>This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank">enable JavaScript</a> and reload the page.</div></div></noscript>
		<div class="wrapper"><!-- for sticky footer -->
			<div class="v-align"><!-- vertically centred box -->
									<header>
						<div id="header">
							<div class="logo svg">
								<h1 class="hidden-visually">
									ownCloud</h1>
							</div>
							<div id="logo-claim" style="display:none;"></div>
						</div>
					</header>
								<span class="error error-wide">
	<h2><strong>Internal Server Error</strong></h2>
		<p>The server encountered an internal error and was unable to complete your request.</p>
		<p>Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.</p>
		<p>More details can be found in the server log.</p>
	<br />

	<h2><strong>Technical details</strong></h2>
	<ul>
		<li>Remote Address: 10.40.10.254</li>
		<li>Request ID: d80571dd22d9fd322b03d0cde6abc6d0</li>
					<li>Code: 0</li>
			<li>Message: Sharing backend for file not found</li>
			<li>File: /home/jvillafanez/src/owncloud/owncloud2/lib/private/share/share.php</li>
			<li>Line: 1234</li>
			</ul>

			<br />
		<h2><strong>Trace</strong></h2>
		<pre>#0 /home/jvillafanez/src/owncloud/owncloud2/lib/private/share/share.php(1353): OC\Share\Share::getBackend(&#039;file&#039;)
#1 /home/jvillafanez/src/owncloud/owncloud2/lib/private/share/share.php(494): OC\Share\Share::getItems(&#039;file&#039;, NULL, NULL, NULL, &#039;jvillafanez@sol...&#039;, -1, NULL, -1, false)
#2 /home/jvillafanez/src/owncloud/owncloud2/lib/public/share.php(207): OC\Share\Share::getItemShared(&#039;file&#039;, NULL, -1, NULL, false)
#3 /home/jvillafanez/src/owncloud/owncloud2/apps/files_sharing/api/local.php(55): OCP\Share::getItemShared(&#039;file&#039;, NULL)
#4 [internal function]: OCA\Files_Sharing\API\Local::getAllShares(Array)
#5 /home/jvillafanez/src/owncloud/owncloud2/lib/private/api.php(117): call_user_func(Array, Array)
#6 [internal function]: OC_API::call(Array)
#7 /home/jvillafanez/src/owncloud/owncloud2/lib/private/route/router.php(250): call_user_func(Array, Array)
#8 /home/jvillafanez/src/owncloud/owncloud2/ocs/v1.php(45): OC\Route\Router-&gt;match(&#039;/ocs/apps/files...&#039;)
#9 {main}</pre>
	</span>
				<div class="push"></div><!-- for sticky footer -->
			</div>
		</div>

		<footer>
			<p class="info">
				<a href="https://owncloud.org" target="_blank">ownCloud</a> – web services under your control			</p>
		</footer>
	</body>
</html>
* Closing connection 0
```

### Notes
Both requests works fine without the maintenance mode

**Comment by nickvergessen** [comment]
Related to #15430

**Comment by MorrisJobke** [comment]
@karlitschek Backport request for this is pending: https://github.com/owncloud/core/pull/15465#issuecomment-90884651

**Comment by nickvergessen** [comment]
We should make a list of this, since we fiddled at a lot of places with maintenance/single user latly, to make sure that all of them are fixed in master, 8 and 7

**Comment by nickvergessen** [comment]
Did I miss any feature? And can someone ( @DeepDiver1975 ) confirm the expected result? Then I will go through master/stable8/stable7 and try to find out what is not working where correctly.

### Expected 

Feature | Maintenance | Single user
---------- | ----------- | -----------
WebUI / Ajax (index.php) | :no_entry_sign: (should not work) | :children_crossing: (admin only)
Login (index.php) | :no_entry_sign: | :children_crossing:
Dav (remote.php) | :no_entry_sign: | :no_entry_sign:
ocs (ocs/v1.php) | :no_entry_sign: | :no_entry_sign:
cron.php | :no_entry_sign: | :no_entry_sign:
occ (console.php) | :white_check_mark: (works) | :white_check_mark:
status.php | :white_check_mark: | :white_check_mark:

**Comment by MorrisJobke** [comment]
I would tend to write a test in smashbox for this. Or is this too hard? Can the maintenance/single-user mode be enabled via remote/API?

**Comment by MorrisJobke** [comment]
@nickvergessen Regarding the table: looks good

**Comment by MorrisJobke** [comment]
#16110 is merged.
