### ISSUE TITLE
Files app misbehaves trying to interact with a deleted federated cloud share

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15487]
### Steps to reproduce
1. Upload a file (checked with a png and a text file file) and share it by link in server A
2. Add the link in server B
3. Delete the image file in server A
4. Download the file from server B
### Expected behaviour

An error is thrown and the file is automatically deleted in server B (it's no longer accessible)
### Actual behaviour

An internal error is thrown, and the file is still there
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install
### Notes

The share action is still accessible throwing "Not authenticated" errors when trying to share the deleted file from server B. This is misleading as the source file is missing.

**Comment by jvillafanez** [comment]
Linking with https://github.com/owncloud/gallery/issues/179 and https://github.com/owncloud/files_texteditor/issues/67
The cause looks like the same, although the bugs are different depending on the app.

There might be other apps such as the pdf viewer affected by this. I haven't checked the behaviour of all of them.

**Comment by jvillafanez** [comment]
Adding logs (trying to download the missing file from server B):
```
{"reqId":"d840e210c319543791574ddf28b9d76b","remoteAddr":"10.40.10.254","app":"index","message":"Exception: {\"Message\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated: Not authenticated\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(152): OC\\\\Files\\\\Storage\\\\DAV->convertSabreException(Object(Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(57): OC\\\\Files\\\\Storage\\\\DAV->filetype('')\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(79): OC\\\\Files\\\\Storage\\\\Common->is_dir('')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(836): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->is_dir('')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(254): OC\\\\Files\\\\View->basicOperation('is_dir', '\\\/\\\/sample.pdf')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(586): OC\\\\Files\\\\View->is_dir('\\\/\\\/sample.pdf')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files.php(87): OC\\\\Files\\\\Filesystem::is_dir('\\\/\\\/sample.pdf')\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(37): OC_Files::get('\\\/', Array, false)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#9 [internal function]: __lambda_func(Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_245', Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#12 \\\/opt\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php\",\"Line\":588}","level":4,"time":"2015-04-10T09:15:19+00:00"},{"reqId":"d840e210c319543791574ddf28b9d76b","remoteAddr":"10.40.10.254","app":"files_external","message":"Not authenticated","level":3,"time":"2015-04-10T09:15:19+00:00"},{"reqId":"6d7efd1e421442eb09c78486c324baac","remoteAddr":"10.40.10.254","app":"index","message":"Exception: {\"Message\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated: Not authenticated\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(152): OC\\\\Files\\\\Storage\\\\DAV->convertSabreException(Object(Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(57): OC\\\\Files\\\\Storage\\\\DAV->filetype('')\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(79): OC\\\\Files\\\\Storage\\\\Common->is_dir('')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(836): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->is_dir('')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(254): OC\\\\Files\\\\View->basicOperation('is_dir', '\\\/\\\/sample.pdf')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(586): OC\\\\Files\\\\View->is_dir('\\\/\\\/sample.pdf')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files.php(87): OC\\\\Files\\\\Filesystem::is_dir('\\\/\\\/sample.pdf')\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(37): OC_Files::get('\\\/', Array, false)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#9 [internal function]: __lambda_func(Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_483', Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#12 \\\/opt\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php\",\"Line\":588}","level":4,"time":"2015-04-10T09:06:45+00:00"},{"reqId":"6d7efd1e421442eb09c78486c324baac","remoteAddr":"10.40.10.254","app":"files_external","message":"Not authenticated","level":3,"time":"2015-04-10T09:06:45+00:00"}
```

**Comment by jvillafanez** [comment]
I have similar behaviour with a password-protected share:

1. Upload a file (checked with a png and a text file file) and share it by link with password in server A
2. Add the link in server B
3. Change the password of the file in server A
4. Download the file from server B

**Comment by PVince81** [comment]
@nickvergessen you mentionned something similar that you observed ?

**Comment by nickvergessen** [comment]
yeah, I thought the fix for #15589 would also fix it, but #15596 does not

**Comment by PVince81** [comment]
Should I continue investigating this then or do you want to take over ?

**Comment by nickvergessen** [comment]
@PVince81 feel free to

**Comment by cmonteroluque** [comment]
@nickvergessen is out this week, so if this is going to make 8.0.4 it's on @PVince81

**Comment by PVince81** [comment]
Can we get a severity ?

Also not sure why @nickvergessen decided to set this to 8.0.4 instead of 8.1. Maybe the bug only happens on stable8 and not master. If that's the case, maybe there's a backport that could be done.

**Comment by PVince81** [comment]
Tested this:
- share a folder with s2s, open files UI, unshare, try downloading the "expired" file: getting "File not found" page
- share a file: in this case I get a page "Internal Server Error". This is because the first access to an expired share will throw StorageInvalidException instead of FileNotFoundException.

A possible fix is to translate the exception to FileNotFoundException in case of a download. Or maybe always do it ?
The purpose of StorageInvalidException is to tell some parts of the code to discard the mount point. But once the mount point is discarded, the exception could be thrown as FileNotFoundException instead.

Will look into it.

**Comment by PVince81** [comment]
For the record, here is the stack for the StorageInvalidException when trying to download an expired file:
```
{
  "reqId": "WQ8xZh74qNUf32gdkbCR",
  "remoteAddr": "127.0.0.1",
  "app": "index",
  "message": "Exception: {
\"Exception\":\"OCP\\\\Files\\\\StorageInvalidException\",
\"Message\":\"Sabre\\\\HTTP\\\\ClientHttpException: Unauthorized\",
\"Code\":0,
\"Trace\":\"
#0 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/private\\\\/files\\\\/storage\\\\/dav.php(290): OC\\\\Files\\\\Storage\\\\DAV->convertException(Object(Sabre\\\\HTTP\\\\ClientHttpException))\n
#1 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/private\\\\/files\\\\/storage\\\\/common.php(89): OC\\\\Files\\\\Storage\\\\DAV->filetype('')\n
#2 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/private\\\\/files\\\\/storage\\\\/wrapper\\\\/wrapper.php(97): OC\\\\Files\\\\Storage\\\\Common->is_dir('')\n
#3 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/private\\\\/files\\\\/storage\\\\/wrapper\\\\/wrapper.php(97): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->is_dir('')\n
#4 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/private\\\\/files\\\\/view.php(938): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->is_dir('')\n
#5 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/private\\\\/files\\\\/view.php(311): OC\\\\Files\\\\View->basicOperation('is_dir', '\\\\/\\\\/newfile.txt')\n
#6 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/private\\\\/files\\\\/filesystem.php(610): OC\\\\Files\\\\View->is_dir('\\\\/\\\\/newfile.txt')\n
#7 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/private\\\\/files.php(108): OC\\\\Files\\\\Filesystem::is_dir('\\\\/\\\\/newfile.txt')\n
#8 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/apps\\\\/files\\\\/ajax\\\\/download.php(42): OC_Files::get('\\\\/', Array, false)\n
#9 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/private\\\\/route\\\\/route.php(153) : runtime-created function(1): require_once('\\\\/srv\\\\/www\\\\/htdocs...')\n
#10 [internal function]: __lambda_func(Array)\n
#11 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/private\\\\/route\\\\/router.php(272): call_user_func('\\\\x00lambda_257', Array)\n
#12 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/base.php(862): OC\\\\Route\\\\Router->match('\\\\/apps\\\\/files\\\\/aja...')\n
#13 \\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/index.php(40): OC::handleRequest()\n
#14 {main}\",\"File\":\"\\\\/srv\\\\/www\\\\/htdocs\\\\/owncloud\\\\/lib\\\\/private\\\\/files\\\\/storage\\\\/dav.php\",\"Line\":779}",
  "level": 4,
  "time": "2015-05-28T10:21:13+00:00",
  "method": "GET",
  "url": "\\/owncloud\\/index.php\\/apps\\/files\\/ajax\\/download.php?dir=%2F&files=newfile.txt"
}

```

**Comment by PVince81** [comment]
Hmm, it looks like this is yet another code path that doesn't trigger the auto-unmount.

Accessing through web UI (ajax/download.php) does not auto-unmount.
However when accessing through WebDAV, it properly returns a Sabre NotFound exception and unmounts it.

**Comment by PVince81** [comment]
Note: when we move the files app to use the WebDAV endpoints later here https://github.com/owncloud/core/issues/12353 the problem would not appear (long-term).

In the WebDAV case, it calls `getFileInfo()` which itself will trigger the watcher that will check if the mount point is still valid.
In the web UI case, it just calls FS methods directly which do not do such check.

Two possible fixes:
1) Make the web UI just call getFileInfo() instead of is_dir() to find out if the downloaded file is a dir
or
2) Make all code FS paths that don't call getFileInfo() catch the StorageInvalidException and somehow forward it to the code that auto-unmounts the expired mount point

@icewind1991 any comment on this ?

**Comment by PVince81** [comment]
This also means that any app that use the Filesystem class (or the Node API) might bump into the same issue and receive StorageInvalidException instead of NotFoundException.

or
3) Make all code path in Filesystem class transaltion StorageInvalidException to NotFoundException (without auto-umounting, which might or might not happen during a later PROPFIND)

**Comment by icewind1991** [comment]
> Make the web UI just call getFileInfo() instead of is_dir() to find out if the downloaded file is a dir

Something we probably want to do anyway

> Make all code path in Filesystem class transaltion StorageInvalidException to NotFoundException 

Would prefer not to change the exception, maybe make `StorageInvalidException` extend `NotFoundException` instead

**Comment by PVince81** [comment]
I also wondered why we even have "is_dir()" and "is_file()" on the Filesystem/View class. These should probably be rewired to use "getFileInfo()" and get the info from there. (having these methods on storage level is ok). Probably something for later...

**Comment by PVince81** [comment]
Observed on master, changing milestone to 8.1

**Comment by PVince81** [comment]
I feel stuck here. The problem isn't critical enough to do a proper fix that touches the architecture.
On the other hand, adding `getFileInfo()` + mimetype check to replace `is_dir()` feels wrong because it will not influence other code paths that might or might not be affected.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
