### ISSUE TITLE
Disconnected LDAP server causes several errors.

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15588]
### Steps to reproduce
1. Configure the LDAP app correctly with a server
2. Make sure you can see all the users in the settings/users page, and can login with any of them
3. Turn off or disconnect the LDAP server

### Expected behaviour
- The settings/users page show all available users, except those who are in the LDAP server.
- Login with a LDAP user shows an error

### Actual behaviour
- The settings/users page loads forever (there are some ajax errors, and the spinner doesn't stop)
- Login with a LDAP user throws an internal server error

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** 8.1 pre alpha

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by PVince81** [comment]
@blizzz is this related to the issues you have been working on with @butonic ?

**Comment by blizzz** [comment]
> The settings/users page loads forever (there are some ajax errors, and the spinner doesn't stop)

Might be the timeout (a guess).

> Login with a LDAP user throws an internal server error

Details?

**Comment by jvillafanez** [comment]
For the settings/user page, there are an internal server error in the ajax call (the user count comes from local users, not LDAP users):

![screenshot from 2015-04-14 13 52 11](https://cloud.githubusercontent.com/assets/1477829/7136600/ab6424e6-e2b2-11e4-97dc-1b8ca7e8b0a4.png)

And the login page shows the following trying to login with an LDAP user from the disconnected server:

![screenshot from 2015-04-14 13 50 35](https://cloud.githubusercontent.com/assets/1477829/7136630/04cc76a0-e2b3-11e4-8c62-a69703f24800.png)


Log:
```
{"reqId":"AudoudQCmH6eo3PyZVm6","remoteAddr":"10.40.30.21","app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":2,"time":"2015-04-14T11:49:52+00:00"}
{"reqId":"AudoudQCmH6eo3PyZVm6","remoteAddr":"10.40.30.21","app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":2,"time":"2015-04-14T11:49:52+00:00"}
{"reqId":"AudoudQCmH6eo3PyZVm6","remoteAddr":"10.40.30.21","app":"user_ldap","message":"No LDAP Connection to server 10.40.40.74","level":3,"time":"2015-04-14T11:49:52+00:00"}
{"reqId":"AudoudQCmH6eo3PyZVm6","remoteAddr":"10.40.30.21","app":"handleLogin","message":"Exception: {\"Message\":\"Connection to LDAP server could not be established\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(729): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#1 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(877): OCA\\\\user_ldap\\\\lib\\\\Access->executeSearch('(&(|(objectclas...', Array, Array, NULL, NULL)\\n#2 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(665): OCA\\\\user_ldap\\\\lib\\\\Access->search('(&(|(objectclas...', Array, Array, NULL, NULL)\\n#3 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(622): OCA\\\\user_ldap\\\\lib\\\\Access->searchUsers('(&(|(objectclas...', Array, NULL, NULL)\\n#4 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(610): OCA\\\\user_ldap\\\\lib\\\\Access->fetchListOfUsers('(&(|(objectclas...', Array)\\n#5 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/user_ldap.php(85): OCA\\\\user_ldap\\\\lib\\\\Access->fetchUsersByLoginName('aaliyah_adams', Array)\\n#6 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/user\\\/manager.php(178): OCA\\\\user_ldap\\\\USER_LDAP->checkPassword('aaliyah_adams', 'secret')\\n#7 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/user\\\/session.php(217): OC\\\\User\\\\Manager->checkPassword('aaliyah_adams', 'secret')\\n#8 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/user.php(241): OC\\\\User\\\\Session->login('aaliyah_adams', 'secret')\\n#9 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(1069): OC_User::login('aaliyah_adams', 'secret')\\n#10 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(965): OC::tryFormLogin()\\n#11 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(927): OC::handleLogin()\\n#12 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/index.php(40): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/connection.php\",\"Line\":173}","level":4,"time":"2015-04-14T11:49:52+00:00"}
{"reqId":"Mwzb\/\/A3PnB7p2OzVIDm","remoteAddr":"10.40.30.21","app":"user_ldap","message":"No LDAP Connection to server 10.40.40.74","level":3,"time":"2015-04-14T11:51:10+00:00"}
{"reqId":"Mwzb\/\/A3PnB7p2OzVIDm","remoteAddr":"10.40.30.21","app":"index","message":"Exception: {\"Message\":\"Connection to LDAP server could not be established\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(595): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#1 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(548): OCA\\\\user_ldap\\\\lib\\\\Connection->bind()\\n#2 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(158): OCA\\\\user_ldap\\\\lib\\\\Connection->establishConnection()\\n#3 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(166): OCA\\\\user_ldap\\\\lib\\\\Connection->init()\\n#4 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(819): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#5 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(676): OCA\\\\user_ldap\\\\lib\\\\Access->count('(&(|(objectclas...', Array, Array, NULL, NULL)\\n#6 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/user_ldap.php(384): OCA\\\\user_ldap\\\\lib\\\\Access->countUsers('(&(|(objectclas...')\\n#7 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/user\\\/manager.php(296): OCA\\\\user_ldap\\\\USER_LDAP->countUsers()\\n#8 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/settings\\\/ajax\\\/geteveryonecount.php(40): OC\\\\User\\\\Manager->countUsers()\\n#9 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/home\\\/jvillafan...')\\n#10 [internal function]: __lambda_func(Array)\\n#11 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('?lambda_17282', Array)\\n#12 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(869): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#13 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/connection.php\",\"Line\":173}","level":4,"time":"2015-04-14T11:51:10+00:00"}
{"reqId":"8gXkfooaGeXh4XAgCilb","remoteAddr":"10.40.30.21","app":"user_ldap","message":"No LDAP Connection to server 10.40.40.74","level":3,"time":"2015-04-14T11:51:11+00:00"}
{"reqId":"tzZTpndQe6\/9C5YW7RyZ","remoteAddr":"10.40.30.21","app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":2,"time":"2015-04-14T12:31:02+00:00"}
{"reqId":"tzZTpndQe6\/9C5YW7RyZ","remoteAddr":"10.40.30.21","app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":2,"time":"2015-04-14T12:31:02+00:00"}
{"reqId":"tzZTpndQe6\/9C5YW7RyZ","remoteAddr":"10.40.30.21","app":"user_ldap","message":"No LDAP Connection to server 10.40.40.74","level":3,"time":"2015-04-14T12:31:02+00:00"}
{"reqId":"tzZTpndQe6\/9C5YW7RyZ","remoteAddr":"10.40.30.21","app":"handleLogin","message":"Exception: {\"Message\":\"Connection to LDAP server could not be established\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(729): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#1 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(877): OCA\\\\user_ldap\\\\lib\\\\Access->executeSearch('(&(|(objectclas...', Array, Array, NULL, NULL)\\n#2 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(665): OCA\\\\user_ldap\\\\lib\\\\Access->search('(&(|(objectclas...', Array, Array, NULL, NULL)\\n#3 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(622): OCA\\\\user_ldap\\\\lib\\\\Access->searchUsers('(&(|(objectclas...', Array, NULL, NULL)\\n#4 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(610): OCA\\\\user_ldap\\\\lib\\\\Access->fetchListOfUsers('(&(|(objectclas...', Array)\\n#5 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/user_ldap.php(85): OCA\\\\user_ldap\\\\lib\\\\Access->fetchUsersByLoginName('aaliyah_adams', Array)\\n#6 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/user\\\/manager.php(178): OCA\\\\user_ldap\\\\USER_LDAP->checkPassword('aaliyah_adams', 'secret')\\n#7 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/user\\\/session.php(217): OC\\\\User\\\\Manager->checkPassword('aaliyah_adams', 'secret')\\n#8 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/user.php(241): OC\\\\User\\\\Session->login('aaliyah_adams', 'secret')\\n#9 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(1069): OC_User::login('aaliyah_adams', 'secret')\\n#10 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(965): OC::tryFormLogin()\\n#11 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(927): OC::handleLogin()\\n#12 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/index.php(40): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/connection.php\",\"Line\":173}","level":4,"time":"2015-04-14T12:31:02+00:00"}
```

**Comment by blizzz** [comment]
Part1: Are you logged in with an LDAP user or as local admin?

Part 2: Well, the error page is correct eventually. It's an internal error (LDAP server not reachable) and contacting the admin is the way to go. I see nothing wrong with that.

**Comment by jvillafanez** [comment]
> Part1: Are you logged in with an LDAP user or as local admin?

I'm as a local admin, logged in after disconecting the LDAP server


> Part 2: Well, the error page is correct eventually. It's an internal error (LDAP server not reachable) and contacting the admin is the way to go. I see nothing wrong with that.

Now that you say that, I agree. I'm a bit worried about the exception that happens in the logs as it looks like isn't handled. If this is how it should be, then it's case closed.

**Comment by blizzz** [comment]
@jvillafanez you could try this also against https://github.com/owncloud/core/pull/15332, especially with the ajax requests in mind (part1).

**Comment by jvillafanez** [comment]
@blizzz it shows an error page

![screenshot from 2015-04-15 09 30 33](https://cloud.githubusercontent.com/assets/1477829/7154116/e74ebdd6-e352-11e4-9250-533bf5889ae6.png)

**Comment by blizzz** [comment]
This is expected.

**Comment by karlitschek** [comment]
@butonic @blizzz @felixboehm What is the status here? Should be fixed, right?

**Comment by karlitschek** [comment]
@jvillafanez Can you retest please?

**Comment by jvillafanez** [comment]
For 8.1 alpha 3:

![screenshot from 2015-05-07 09 09 32](https://cloud.githubusercontent.com/assets/1477829/7510093/efd926f6-f498-11e4-98d6-35f5fa69350f.png)

```
{"reqId":"A1+v2LbFKchn2bIUdSS0","remoteAddr":"10.40.30.21","app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":2,"time":"2015-05-07T07:06:29+00:00"}
{"reqId":"A1+v2LbFKchn2bIUdSS0","remoteAddr":"10.40.30.21","app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":2,"time":"2015-05-07T07:06:29+00:00"}
{"reqId":"A1+v2LbFKchn2bIUdSS0","remoteAddr":"10.40.30.21","app":"user_ldap","message":"No LDAP Connection to server 10.40.40.74","level":3,"time":"2015-05-07T07:06:29+00:00"}
{"reqId":"A1+v2LbFKchn2bIUdSS0","remoteAddr":"10.40.30.21","app":"handleLogin","message":"Exception: {\"Exception\":\"OC\\\\ServerNotAvailableException\",\"Message\":\"Connection to LDAP server could not be established\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(729): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#1 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(877): OCA\\\\user_ldap\\\\lib\\\\Access->executeSearch('(&(|(objectclas...', Array, Array, NULL, NULL)\\n#2 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(665): OCA\\\\user_ldap\\\\lib\\\\Access->search('(&(|(objectclas...', Array, Array, NULL, NULL)\\n#3 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(622): OCA\\\\user_ldap\\\\lib\\\\Access->searchUsers('(&(|(objectclas...', Array, NULL, NULL)\\n#4 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/access.php(610): OCA\\\\user_ldap\\\\lib\\\\Access->fetchListOfUsers('(&(|(objectclas...', Array)\\n#5 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/user_ldap.php(85): OCA\\\\user_ldap\\\\lib\\\\Access->fetchUsersByLoginName('007_abernathy', Array)\\n#6 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/user\\\/manager.php(178): OCA\\\\user_ldap\\\\USER_LDAP->checkPassword('007_abernathy', 'secret')\\n#7 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/user\\\/session.php(217): OC\\\\User\\\\Manager->checkPassword('007_abernathy', 'secret')\\n#8 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/user.php(241): OC\\\\User\\\\Session->login('007_abernathy', 'secret')\\n#9 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(1058): OC_User::login('007_abernathy', 'secret')\\n#10 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(954): OC::tryFormLogin()\\n#11 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(916): OC::handleLogin()\\n#12 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/index.php(40): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/user_ldap\\\/lib\\\/connection.php\",\"Line\":173}","level":4,"time":"2015-05-07T07:06:29+00:00"}
```

**Comment by blizzz** [comment]
@jvillafanez so, all good?

**Comment by jvillafanez** [comment]
If everyone agrees with the solution, no problems on my side
