### ISSUE TITLE
t3.pl is failing on master

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#15878]
## Background

git bisect did show that this is the failing commit https://github.com/owncloud/core/commit/2990b0e07e418577d55368c21200ada86c381b51

Detailed log of t3.pl execution: https://ci.owncloud.org/job/client-test-matrix-linux-8.1-enc/compiler=g++,label=master,mirallBranch=master,serverVersion=owncloud8.1,tc=t3/12/consoleFull

The failing test case is described in here https://github.com/owncloud/client/blob/master/csync/tests/ownCloud/t3.pl#L61

```perl
# Make a new directory, moves a sub directory into. Remove the parent directory.
# create a new file on the server in the directory that will be renamed
printInfo( "Create a new directory and move subdirs into." );
my $newfile_md5 = createLocalFile(localDir()."remoteToLocal1/rtl1/rtl11/newfile.dat", 123);
unlink( localDir() . 'remoteToLocal1/rtl1/rtl11/test.txt' );
mkdir( localDir() . 'newdir' );
move( localDir() . 'remoteToLocal1/rtl1', localDir() . 'newdir/rtl1' );
system( "rm -rf " . localDir() . 'remoteToLocal1' );
system( "echo \"my file\" >> /tmp/myfile.txt" );
put_to_dir( '/tmp/myfile.txt', 'remoteToLocal1/rtl1/rtl11' );
# Also add a file with symbols
my $symbolName = "a\%b#c\$d-e";
system( "echo \"my symbols\" >> /tmp/$symbolName" );
put_to_dir( "/tmp/$symbolName", 'remoteToLocal1/rtl1/rtl11' );
my $fileid = remoteFileId( 'remoteToLocal1/rtl1/', 'rtl11' );
my $fid2 = remoteFileId( 'remoteToLocal1/rtl1/', 'La ced' );
assert($fid2 eq "" or $fileid ne $fid2, "File IDs are equal" );
csync();
my $newFileId = remoteFileId( 'newdir/rtl1/', 'rtl11' );
my $newfid2 = remoteFileId( 'newdir/rtl1/', 'La ced' );
assert($newFileId eq "" or $newFileId ne $newfid2, "File IDs are equal" );
assert( $fileid eq $newFileId, "file ID mixup: 'newdir/rtl1/rtl11" );
assert( $fid2 eq $newfid2, "file ID mixup: 'newdir/La ced" );
assertLocalAndRemoteDir( 'newdir', 0);
```

The error:
````
Stat failed for file t1-20150426060433-89/newdir/rtl1/rtl11/myfile.txt at ownCloud/Test.pm line 793
	ownCloud::Test::assert('', 'Stat failed for file t1-20150426060433-89/newdir/rtl1/rtl11/m...') called at ownCloud/Test.pm line 365
	ownCloud::Test::assertFile('t1-20150426060433-89/newdir/rtl1/rtl11/myfile.txt', 'HTTP::DAV::Resource=HASH(0x26cdce0)') called at ownCloud/Test.pm line 426
	ownCloud::Test::traverse('newdir/rtl1/rtl11/', 0, undef) called at ownCloud/Test.pm line 414
	ownCloud::Test::traverse('newdir/rtl1/', 0, undef) called at ownCloud/Test.pm line 414
	ownCloud::Test::traverse('newdir', 0, undef) called at ownCloud/Test.pm line 473
	ownCloud::Test::assertLocalAndRemoteDir('newdir', 0) called at ./t3.pl line 89
````

## What happens?
1. A file is put to the server https://github.com/owncloud/client/blob/master/csync/tests/ownCloud/t3.pl#L74
2. The sync client is not detecting the change in https://github.com/owncloud/client/blob/master/csync/tests/ownCloud/t3.pl#L81

**Comment by DeepDiver1975** [comment]
webdav move operation is falling apart:

````
{"reqId":"kYdarahpDhI9pMvxPME7","remoteAddr":"::1","app":"webdav","message":"Exception: {\"Message\":\"No default encryption module defined\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/oc8.1\\\/lib\\\/private\\\/encryption\\\/update.php(140): OC\\\\Encryption\\\\Manager->getDefaultEncryptionModule()\\n#1 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/oc8.1\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(235): OC\\\\Encryption\\\\Update->update('\\\/admin\\\/files\\\/t1...')\\n#2 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/oc8.1\\\/lib\\\/private\\\/files\\\/view.php(645): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->rename('files\\\/t1-201504...', 'files\\\/t1-201504...')\\n#3 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/oc8.1\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php(222): OC\\\\Files\\\\View->rename('t1-201504271047...', 't1-201504271047...')\\n#4 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/oc8.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(630): OC\\\\Connector\\\\Sabre\\\\ObjectTree->move('t1-201504271047...', 't1-201504271047...')\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/oc8.1\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/oc8.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#8 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/oc8.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/oc8.1\\\/apps\\\/files\\\/appinfo\\\/remote.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/oc8.1\\\/remote.php(84): require_once('\\\/home\\\/deepdiver...')\\n#11 {main}\",\"File\":\"\\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/oc8.1\\\/lib\\\/private\\\/encryption\\\/manager.php\",\"Line\":172}","level":4,"time":"2015-04-27T08:49:58+00:00"}

**Comment by DeepDiver1975** [comment]
caused by https://github.com/owncloud/core/commit/2990b0e07e418577d55368c21200ada86c381b51#diff-77a99814cfcdf1bba7acd9ff95d4e143R140

**Comment by DeepDiver1975** [comment]
introducing change: https://github.com/owncloud/core/commit/2990b0e07e418577d55368c21200ada86c381b51#diff-a36b9c0307e0126dd50baa38fb4bb74aR235

**Comment by DeepDiver1975** [comment]
we are missing some checks in here https://github.com/owncloud/core/blob/master/lib/private/encryption/update.php#L140

**Comment by DeepDiver1975** [comment]
Status as of now: 8.1 without encryption is now green :tada: 

With encryption there is a issue related to webdav move:

```json
{
   "level" : 4,
   "url" : "/oc/core/remote.php/webdav/t1-20150428150819-59/remoteToLocal1/rtl1",
   "message" : "Exception: {\"Message\":\"Cannot multikeyencrypt empty plain content\",\"Code\":0,\"Trace\":\"#0 \\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/apps\\/encryption\\/lib\\/crypto\\/encryption.php(267): OCA\\\\Encryption\\\\Crypto\\\\Crypt->multiKeyEncrypt('', Array)\\n#1 \\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/lib\\/private\\/encryption\\/update.php(144): OCA\\\\Encryption\\\\Crypto\\\\Encryption->update('\\/test\\/files\\/t1-...', 'test', Array)\\n#2 \\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(239): OC\\\\Encryption\\\\Update->update('\\/test\\/files\\/t1-...')\\n#3 \\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/lib\\/private\\/files\\/view.php(645): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->rename('files\\/t1-201504...', 'files\\/t1-201504...')\\n#4 \\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/lib\\/private\\/connector\\/sabre\\/objecttree.php(222): OC\\\\Files\\\\View->rename('t1-201504281508...', 't1-201504281508...')\\n#5 \\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(630): OC\\\\Connector\\\\Sabre\\\\ObjectTree->move('t1-201504281508...', 't1-201504281508...')\\n#6 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#9 \\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/apps\\/files\\/appinfo\\/remote.php(81): Sabre\\\\DAV\\\\Server->exec()\\n#11 \\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/remote.php(84): require_once('\\/home\\/deepdiver...')\\n#12 {main}\",\"File\":\"\\/home\\/deepdiver\\/Development\\/ownCloud\\/core\\/apps\\/encryption\\/lib\\/crypto\\/crypt.php\",\"Line\":453}",
   "app" : "webdav",
   "remoteAddr" : "::1",
   "time" : "2015-04-28T13:09:51+00:00",
   "reqId" : "aeUpgLom/E6jV6pdj7O9",
   "method" : "MOVE"
}

**Comment by DeepDiver1975** [comment]
no key file after upload of an empty file:

```sh
deepdiver@alien:~/Development/ownCloud/core [master]$ ll data/test/files/t1-20150428161959-21/newdir/rtl1/rtl11/zerofile.txt 
-rw-r--r-- 1 www-data www-data 8192 Apr 28 16:21 data/test/files/t1-20150428161959-21/newdir/rtl1/rtl11/zerofile.txt
deepdiver@alien:~/Development/ownCloud/core [master]$ ll data/test/files_encryption/keys/files/t1-20150428161959-21/newdir/rtl1/rtl11/
insgesamt 16
drwxr-xr-x 3 www-data www-data 4096 Apr 28 16:22 church.jpg
drwxr-xr-x 3 www-data www-data 4096 Apr 28 16:22 myfile.txt
drwxr-xr-x 3 www-data www-data 4096 Apr 28 16:22 red_is_the_rose.jpg
drwxr-xr-x 3 www-data www-data 4096 Apr 28 16:22 test.txt

**Comment by DeepDiver1975** [comment]
t3.pl now executed -> closing
