### ISSUE TITLE
External Storage app: failed WebDAV connection with OpenText Livelink

### ISSUE THREAD

**Issue by sbelov1** [owncloud/core#15990]
Our appliance: oC 8.0.2, Apache, OpenSUSE 13.1, MariaDB
User is trying to connect OpenText Livelink via WebDAV.
 He's filling in the fields for the WebDAV connection, but unable to see the share
![1](https://cloud.githubusercontent.com/assets/8365936/7420571/94cdfb6c-ef4b-11e4-9e80-12cf8e2b020c.jpg)

 Log:
```
{"reqId":"1b6cc3322370bd0d6bc77c812d5aaf95","remoteAddr":"<IP>","app":"files_external","message":"Not authenticated","level":3,"time":"2015-04-29T18:41:46+00:00"}
{"reqId":"1b6cc3322370bd0d6bc77c812d5aaf95","remoteAddr":"<IP>","app":"files_external","message":"Exception: {\"Message\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated: Not authenticated\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(382): OC\\\\Files\\\\Storage\\\\DAV->convertSabreException(Object(Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(393): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(457): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(539): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/ajax\\\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('LL Webdav', '\\\\OC\\\\Files\\\\Stora...', Array, 'user', 'all', false)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_4151', Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php\",\"Line\":588}","level":4,"time":"2015-04-29T18:41:46+00:00"}
{"reqId":"717a8f073e96f42581e1edaa6d6302b5","remoteAddr":"<IP>","app":"files_external","message":"Not authenticated","level":3,"time":"2015-04-29T18:41:49+00:00"}
{"reqId":"717a8f073e96f42581e1edaa6d6302b5","remoteAddr":"<IP>","app":"files_external","message":"Exception: {\"Message\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated: Not authenticated\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(382): OC\\\\Files\\\\Storage\\\\DAV->convertSabreException(Object(Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(393): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(457): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(539): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/ajax\\\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('LL Webdav', '\\\\OC\\\\Files\\\\Stora...', Array, 'group', 'G-TA1-ocusers-R...', false)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_4271', Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php\",\"Line\":588}","level":4,"time":"2015-04-29T18:41:49+00:00"}
{"reqId":"cdc1da6f92b77ecd7145bae105635f80","remoteAddr":"<IP>","app":"files_external","message":"Not authenticated","level":3,"time":"2015-04-29T18:41:49+00:00"}
{"reqId":"cdc1da6f92b77ecd7145bae105635f80","remoteAddr":"<IP>","app":"files_external","message":"Exception: {\"Message\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated: Not authenticated\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(382): OC\\\\Files\\\\Storage\\\\DAV->convertSabreException(Object(Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(393): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(457): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(539): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/ajax\\\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('LL Webdav', '\\\\OC\\\\Files\\\\Stora...', Array, 'group', 'G-TA1-ocusers-R...', false)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_4311', Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php\",\"Line\":588}","level":4,"time":"2015-04-29T18:41:49+00:00"}
{"reqId":"9667ba7fe5fd4dae2a9a1add2aab2d7f","remoteAddr":"<IP>","app":"files_external","message":"Not authenticated","level":3,"time":"2015-04-29T18:41:51+00:00"}
{"reqId":"9667ba7fe5fd4dae2a9a1add2aab2d7f","remoteAddr":"<IP>","app":"files_external","message":"Exception: {\"Message\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated: Not authenticated\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(382): OC\\\\Files\\\\Storage\\\\DAV->convertSabreException(Object(Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(393): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(457): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(539): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/ajax\\\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('LL Webdav', '\\\\OC\\\\Files\\\\Stora...', Array, 'user', 'all', false)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_4351', Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php\",\"Line\":588}","level":4,"time":"2015-04-29T18:41:51+00:00"}
{"reqId":"ae3073f479ff819fc3f27ae1c9b403fd","remoteAddr":"<IP>","app":"files_external","message":"Not authenticated","level":3,"time":"2015-04-29T18:41:56+00:00"}
{"reqId":"ae3073f479ff819fc3f27ae1c9b403fd","remoteAddr":"<IP>","app":"files_external","message":"Exception: {\"Message\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated: Not authenticated\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(382): OC\\\\Files\\\\Storage\\\\DAV->convertSabreException(Object(Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(393): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(457): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(539): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/ajax\\\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('LL Webdav', '\\\\OC\\\\Files\\\\Stora...', Array, 'group', 'G-TA1-ocusers-w...', false)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_659', Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php\",\"Line\":588}","level":4,"time":"2015-04-29T18:41:56+00:00"}
{"reqId":"b7f13bb575ebf74f4dac6b8c408bc041","remoteAddr":"<IP>","app":"files_external","message":"Not authenticated","level":3,"time":"2015-04-29T18:41:56+00:00"}
{"reqId":"b7f13bb575ebf74f4dac6b8c408bc041","remoteAddr":"<IP>","app":"files_external","message":"Exception: {\"Message\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated: Not authenticated\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(382): OC\\\\Files\\\\Storage\\\\DAV->convertSabreException(Object(Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(393): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(457): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(539): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/ajax\\\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('LL Webdav', '\\\\OC\\\\Files\\\\Stora...', Array, 'group', 'G-TA1-ocusers-w...', false)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_1043', Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php\",\"Line\":588}","level":4,"time":"2015-04-29T18:41:56+00:00"}
{"reqId":"91e4dfdc4c35dcfb6a962a54fcae9d3a","remoteAddr":"<IP>","app":"files_external","message":"Not authenticated","level":3,"time":"2015-04-29T18:41:57+00:00"}
{"reqId":"91e4dfdc4c35dcfb6a962a54fcae9d3a","remoteAddr":"<IP>","app":"files_external","message":"Exception: {\"Message\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated: Not authenticated\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(382): OC\\\\Files\\\\Storage\\\\DAV->convertSabreException(Object(Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(393): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(457): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(539): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/ajax\\\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('LL Webdav', '\\\\OC\\\\Files\\\\Stora...', Array, 'group', 'G-TA1-ocusers-w...', false)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_5014', Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php\",\"Line\":588}","level":4,"time":"2015-04-29T18:41:57+00:00"}
```

**Comment by sbelov1** [comment]
Any assistance with this? We have the prospect waiting..

**Comment by DeepDiver1975** [comment]
We have no understanding of this webdav service. Can you please run litmus against it to see if this implementation fulfills the specs? Thx

**Comment by sbelov1** [comment]
@DeepDiver1975 Ok, I'm assuming you're talking about this tool: http://www.webdav.org/neon/litmus/.

 Ok, we'll give it a shot and I'll report here later.

**Comment by bboule** [comment]
@sbelov1 just a ping any luck with the litmus test?

**Comment by PVince81** [comment]
All errors in the log are "Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated", so it is likely that it cannot authenticate.

Are other webdav tools like cadaver able to connect to it ?

**Comment by sbelov1** [comment]
@PVince81 @bboule Guys, sorry, didn't provide an update on this yet. The litmus test has failed and they also failed connecting via WebDAV using the Windows tool I provided. They've identified that the issue is on their end (they think its a possible domain authentication issue). Thanks for looking into to this. Closing the case for now.
