### ISSUE TITLE
Files cannot be deleted.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16062]
### Steps to reproduce

1. Upload some files.
2. Delete them.

### Expected behaviour
Files are deleted and put in the trashbin.

### Actual behaviour
Files cannot be deleted, the spinner gif keeps turning forever.

Please note that only happens with encryption deactivated. With encryption enabled it is working fine.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

### Client configuration

**browser**
Chrome 41

**Operating system**
Mac OS X

**Comment by nickvergessen** [comment]
Something in the log?

Also when you say:
> Please note that only happens with encryption deactivated. With encryption enabled it is working fine.

do you mean the setting on the admin page, the encryption app, or both?

**Comment by SergioBertolinSG** [comment]
With both encryption app and setting in admin page enabled working fine.

some logs:
```
{"reqId":"YDLbKO9nPo23JsWF7i0U","remoteAddr":"172.16.101.5","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\LockNotAcquiredException\",\"Message\":\"Could not obtain lock type 1 on \\\"\\\/tmp\\\/oc_tmp_GN1yoY-.pdf\\\".\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(44): OCA\\\\Files_Locking\\\\Lock->addLock(1, NULL)\\n#1 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(126): OCA\\\\Files_Locking\\\\LockingWrapper->getLock('files\\\/ownCloudU...', 1)\\n#2 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(645): OCA\\\\Files_Locking\\\\LockingWrapper->rename('files\\\/ownCloudU...', 'files_trashbin\\\/...')\\n#3 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(192): OC\\\\Files\\\\View->rename('\\\/files\\\/ownCloud...', '\\\/files_trashbin...')\\n#4 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(100): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('ownCloudUserMan...')\\n#5 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(181): OCA\\\\Files_Trashbin\\\\Storage->unlink('files\\\/ownCloudU...')\\n#6 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(938): OCA\\\\Files_Locking\\\\LockingWrapper->unlink('files\\\/ownCloudU...')\\n#7 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(573): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/\\\/ownCloudUserM...', Array)\\n#8 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(677): OC\\\\Files\\\\View->unlink('\\\/\\\/ownCloudUserM...')\\n#9 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/delete.php(59): OC\\\\Files\\\\Filesystem::unlink('\\\/\\\/ownCloudUserM...')\\n#10 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/daily\\\/...')\\n#11 [internal function]: __lambda_func(Array)\\n#12 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('\\\\x00lambda_277', Array)\\n#13 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/base.php(860): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#14 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lock.php\",\"Line\":251}","level":4,"time":"2015-05-05T08:44:42+00:00"}
{"reqId":"oU0dq0Lpx8kUDaR9HlDp","remoteAddr":"172.16.101.5","app":"PHP","message":"fopen(\/srv\/www\/daily\/master\/owncloud\/data\/admin\/thumbnails\/20\/2048-2048-max.png): failed to open stream: No such file or directory at \/srv\/www\/daily\/master\/owncloud\/lib\/private\/files\/storage\/local.php#256","level":3,"time":"2015-05-05T08:46:59+00:00"}
{"reqId":"oU0dq0Lpx8kUDaR9HlDp","remoteAddr":"172.16.101.5","app":"PHP","message":"fopen(\/): failed to open stream: Is a directory at \/srv\/www\/daily\/master\/owncloud\/apps\/files_locking\/lib\/lock.php#135","level":3,"time":"2015-05-05T08:46:59+00:00"}
{"reqId":"oU0dq0Lpx8kUDaR9HlDp","remoteAddr":"172.16.101.5","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\LockNotAcquiredException\",\"Message\":\"Could not obtain lock type 2 on \\\"\\\/\\\".\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(44): OCA\\\\Files_Locking\\\\Lock->addLock(2, NULL)\\n#1 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(93): OCA\\\\Files_Locking\\\\LockingWrapper->getLock('thumbnails\\\/20\\\/2...', 2)\\n#2 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(936): OCA\\\\Files_Locking\\\\LockingWrapper->file_put_contents('thumbnails\\\/20\\\/2...', '\\\\x89PNG\\\\r\\\\n\\\\x1A\\\\n\\\\x00\\\\x00\\\\x00\\\\rIHD...')\\n#3 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(554): OC\\\\Files\\\\View->basicOperation('file_put_conten...', 'thumbnails\\\/20\\\/2...', Array, '\\\\x89PNG\\\\r\\\\n\\\\x1A\\\\n\\\\x00\\\\x00\\\\x00\\\\rIHD...')\\n#4 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/preview.php(856): OC\\\\Files\\\\View->file_put_contents('thumbnails\\\/20\\\/2...', '\\\\x89PNG\\\\r\\\\n\\\\x1A\\\\n\\\\x00\\\\x00\\\\x00\\\\rIHD...')\\n#5 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/preview.php(816): OC\\\\Preview->storeMaxPreview('thumbnails\\\/20\\\/')\\n#6 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/preview.php(521): OC\\\\Preview->generatePreview(20)\\n#7 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/preview.php(544): OC\\\\Preview->getPreview()\\n#8 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/core\\\/ajax\\\/preview.php(61): OC\\\\Preview->showPreview()\\n#9 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/daily\\\/...')\\n#10 [internal function]: __lambda_func(Array)\\n#11 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('\\\\x00lambda_409', Array)\\n#12 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/base.php(860): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#13 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lock.php\",\"Line\":251}","level":4,"time":"2015-05-05T08:46:59+00:00"}
{"reqId":"OWoyVm0ROK+muQhdmZWL","remoteAddr":"172.16.101.5","app":"PHP","message":"fopen(\/srv\/www\/daily\/master\/owncloud\/data\/admin\/files_trashbin\/files\/networkjobs.h.d1430815647): failed to open stream: No such file or directory at \/srv\/www\/daily\/master\/owncloud\/lib\/private\/files\/storage\/local.php#256","level":3,"time":"2015-05-05T08:47:29+00:00"}
{"reqId":"OWoyVm0ROK+muQhdmZWL","remoteAddr":"172.16.101.5","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\LockNotAcquiredException\",\"Message\":\"Could not obtain lock type 1 on \\\"\\\/tmp\\\/oc_tmp_qrO9rI-.h\\\".\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(44): OCA\\\\Files_Locking\\\\Lock->addLock(1, NULL)\\n#1 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(126): OCA\\\\Files_Locking\\\\LockingWrapper->getLock('files\\\/networkjo...', 1)\\n#2 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(645): OCA\\\\Files_Locking\\\\LockingWrapper->rename('files\\\/networkjo...', 'files_trashbin\\\/...')\\n#3 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(192): OC\\\\Files\\\\View->rename('\\\/files\\\/networkj...', '\\\/files_trashbin...')\\n#4 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(100): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('networkjobs.h')\\n#5 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(181): OCA\\\\Files_Trashbin\\\\Storage->unlink('files\\\/networkjo...')\\n#6 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(938): OCA\\\\Files_Locking\\\\LockingWrapper->unlink('files\\\/networkjo...')\\n#7 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(573): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/\\\/networkjobs.h', Array)\\n#8 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(677): OC\\\\Files\\\\View->unlink('\\\/\\\/networkjobs.h')\\n#9 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/delete.php(59): OC\\\\Files\\\\Filesystem::unlink('\\\/\\\/networkjobs.h')\\n#10 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/daily\\\/...')\\n#11 [internal function]: __lambda_func(Array)\\n#12 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('\\\\x00lambda_122', Array)\\n#13 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/lib\\\/base.php(860): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#14 \\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/srv\\\/www\\\/daily\\\/master\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lock.php\",\"Line\":251}","level":4,"time":"2015-05-05T08:47:29+00:00"}
{"reqId":"jwZ47vgmeIbwLw\/XTg4K","remoteAddr":"172.16.101.5","app":"PHP","message":"Array to string conversion at \/srv\/www\/daily\/master\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-05-05T09:25:40+00:00"}

```

**Comment by MorrisJobke** [comment]
@SergioBertolinSG It seems that files_locking is enabled. Can you confirm this?

**Comment by MorrisJobke** [comment]
Does it work if files_locking is disabled?

**Comment by nickvergessen** [comment]
@MorrisJobke yes I chatted with him in IRC and the other issue and he commented in https://github.com/owncloud/files_locking/issues/17

**Comment by SergioBertolinSG** [comment]
@MorrisJobke Yes, disabling files_locking it works correctly.

**Comment by MorrisJobke** [comment]
Then it's a files_locking app issue -> close here

**Comment by MorrisJobke** [comment]
Let's reopen this here to not forget about the ticket, that breaks core

**Comment by DeepDiver1975** [comment]
for sure related to the storage wrapper order ...

**Comment by karlitschek** [comment]
O.K. So files_locking is still shipped and enabled by default. So it still should be fixed.

**Comment by jnfrmarks** [comment]
@SergioBertolinSG Can you please retest with the latest code? thanks!

**Comment by SergioBertolinSG** [comment]
Working fine in master.
