### ISSUE TITLE
Music: Exception: {\"Message\":\"js file not found: script:js\\\/md5\\\/md5.min

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#16095]
And now, when opening the music app, I see this error in the owncloud.log and the browser screen is plain white:

```
{"reqId":"f6e0d609ed4c5b3610aef622e7124cc6","remoteAddr":"203.84.135.120","app":"index","message":"Exception: {\"Message\":\"js file not found: script:js\\\/md5\\\/md5.min serverroot:\\\/var\\\/www\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(156): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(107): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('user', 'music')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/http\\\/templateresponse.php(146): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(105): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Music\\\\Controller\\\\PageController), 'index')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('PageController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/apps\\\/music\\\/')\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-05-06T01:06:35+00:00"}
{"reqId":"f6e0d609ed4c5b3610aef622e7124cc6","remoteAddr":"203.84.135.120","app":"PHP","message":"js file not found: script:js\/md5\/md5.min serverroot:\/var\/www\/owncloud at \/var\/www\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-05-06T01:06:35+00:00"}
```

**Comment by RealRancor** [comment]
Hi,

the issue tracker of the music app is located here:

https://github.com/owncloud/music/issues

Please also make sure you're running the latest version of the music app from the appstore released for OC8

**Comment by binarykitchen** [comment]
thx
