### ISSUE TITLE
ModuleAlreadyExistsException on app activation

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#16103]
```json


{
  "reqId": "tzEThQXcmCZWF5j5rc7y",
  "remoteAddr": "192.168.178.24",
  "app": "index",
  "message": "Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\ModuleAlreadyExistsException\",\"Message\":\"Id \\\"OC_DEFAULT_MODULE\\\" already used by encryption module \\\"ownCloud Default Encryption\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core-autotest\\\/apps\\\/encryption\\\/appinfo\\\/application.php(109): OC\\\\Encryption\\\\Manager->registerEncryptionModule('OC_DEFAULT_MODU...', 'ownCloud Defaul...', Object(Closure))\\n#1 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core-autotest\\\/apps\\\/encryption\\\/appinfo\\\/app.php(30): OCA\\\\Encryption\\\\AppInfo\\\\Application->registerEncryptionModule()\\n#2 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core-autotest\\\/lib\\\/private\\\/app.php(388): require('\\\/home\\\/deepdiver...')\\n#3 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core-autotest\\\/settings\\\/ajax\\\/navigationdetect.php(30): OC_App::getAppNavigationEntries('encryption')\\n#4 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core-autotest\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/home\\\/deepdiver...')\\n#5 [internal function]: __lambda_func(Array)\\n#6 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core-autotest\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('\\\\x00lambda_2587', Array)\\n#7 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core-autotest\\\/lib\\\/base.php(860): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#8 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core-autotest\\\/index.php(40): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core-autotest\\\/lib\\\/private\\\/encryption\\\/manager.php\",\"Line\":101}",
  "level": 4,
  "time": "2015-05-06T08:30:08+00:00",
  "method": "GET",
  "url": "\/index.php\/settings\/ajax\/navigationdetect.php?app=encryption"
}

**Comment by nickvergessen** [comment]
Okay, I guess we can catch the exception in `navigationdetect.php` because that file doesn't really care about this exception, but it would also potentially incorrectly misbehave if an app has an encryption module and a navigation entry?

The other idea is to catch the exception in the the registration method of the app and then log something normal instead, but then we defeat the purpose of the exception and will not realise a potential problem.

Your call @DeepDiver1975

**Comment by DeepDiver1975** [comment]
well - the question is why are we trying to register it twice

**Comment by nickvergessen** [comment]
because when including the [app.php](https://github.com/owncloud/core/blob/master/lib/private/app.php#L385-L392), although the app has already been loaded before, because it was enabled before.

**Comment by karlitschek** [comment]
@DeepDiver1975 So by putting this on 8.1 you volunteer to do this? ;-)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 So by putting this on 8.1 you volunteer to do this? ;-)

me don't care who fixes this - but we wanted to have clean logs - right? :speak_no_evil:

**Comment by nickvergessen** [comment]
Simple PR for now https://github.com/owncloud/core/issues/16146
