### ISSUE TITLE
Unknown database type  requested, OC\DB\OCSqlitePlatform may not support it.

### ISSUE THREAD

**Issue by mehturt** [owncloud/core#16134]
### Steps to reproduce
php occ upgrade

### Expected behaviour
Update should complete

### Actual behaviour
Update failed with message:
Unknown database type  requested, OC\DB\OCSqlitePlatform may not support it.

### Server configuration
Debian Wheezy
Apache 2.2.22
database sqlite
php 5.4.39
OC 8.0.2

**Updated from an older ownCloud or fresh install:**
updated

**List of activated apps:**
Enabled:
 - calendar
 - contacts
 - files
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - galleryplus
 - news
 - updater

Disabled:
 - activity
 - external
 - files_encryption
 - files_external
 - files_locking
 - gallery
 - galleryplus-2.0.10
 - galleryplus-2.0.8
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

**Comment by mehturt** [comment]
DB schema dump

```
CREATE TABLE oc_appconfig (appid VARCHAR(32) DEFAULT '' NOT NULL, configkey VARCHAR(64) DEFAULT '' NOT NULL, configvalue CLOB DEFAULT NULL, PRIMARY KEY(appid, configkey));
CREATE TABLE oc_clndr_calendars (id INTEGER NOT NULL, userid VARCHAR(255) DEFAULT NULL COLLATE BINARY, displayname VARCHAR(100) DEFAULT NULL COLLATE BINARY, uri VARCHAR(255) DEFAULT NULL COLLATE BINARY, active INTEGER DEFAULT 1 NOT NULL, calendarcolor VARCHAR(10) DE
FAULT NULL COLLATE BINARY, timezone CLOB DEFAULT NULL COLLATE BINARY, components VARCHAR(100) DEFAULT NULL COLLATE BINARY, "ctag" INTEGER UNSIGNED DEFAULT 0 NOT NULL, "calendarorder" INTEGER UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_clndr_objects (id INTEGER NOT NULL, startdate DATETIME DEFAULT '1970-01-01 00:00:00', enddate DATETIME DEFAULT '1970-01-01 00:00:00', summary VARCHAR(255) DEFAULT NULL COLLATE BINARY, calendardata CLOB DEFAULT NULL COLLATE BINARY, uri VARCHAR(255) DE
FAULT NULL COLLATE BINARY, objecttype VARCHAR(40) DEFAULT '' NOT NULL COLLATE BINARY, "repeating" INTEGER DEFAULT 0, "lastmodified" INTEGER DEFAULT 0, "calendarid" INTEGER UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_clndr_repeat (id INTEGER NOT NULL, startdate DATETIME DEFAULT '1970-01-01 00:00:00', enddate DATETIME DEFAULT '1970-01-01 00:00:00', "eventid" INTEGER UNSIGNED DEFAULT 0 NOT NULL, "calid" INTEGER UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_clndr_share_calendar (active INTEGER DEFAULT 1 NOT NULL, owner VARCHAR(255) NOT NULL COLLATE BINARY, share VARCHAR(255) NOT NULL COLLATE BINARY, sharetype VARCHAR(6) NOT NULL COLLATE BINARY, "calendarid" BIGINT UNSIGNED DEFAULT 0 NOT NULL, "permissio
ns" SMALLINT NOT NULL);
CREATE TABLE oc_clndr_share_event (owner VARCHAR(255) NOT NULL COLLATE BINARY, share VARCHAR(255) NOT NULL COLLATE BINARY, sharetype VARCHAR(6) NOT NULL COLLATE BINARY, "eventid" BIGINT UNSIGNED DEFAULT 0 NOT NULL, "permissions" SMALLINT NOT NULL);
CREATE TABLE oc_contacts_addressbooks (id INTEGER NOT NULL, displayname VARCHAR(255) DEFAULT NULL COLLATE BINARY, uri VARCHAR(200) DEFAULT NULL COLLATE BINARY, description VARCHAR(255) DEFAULT NULL COLLATE BINARY, active INTEGER DEFAULT 1 NOT NULL, userid VARCHAR(25
5) DEFAULT '' NOT NULL COLLATE BINARY, "ctag" INTEGER UNSIGNED DEFAULT 1 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_contacts_cards (id INTEGER NOT NULL, fullname VARCHAR(255) DEFAULT NULL COLLATE BINARY, carddata CLOB DEFAULT NULL COLLATE BINARY, uri VARCHAR(200) DEFAULT NULL COLLATE BINARY, "addressbookid" INTEGER UNSIGNED DEFAULT 0 NOT NULL, "lastmodified" INTEG
ER UNSIGNED DEFAULT 0, PRIMARY KEY(id));
CREATE TABLE oc_contacts_cards_properties (id INTEGER NOT NULL, name VARCHAR(64) DEFAULT NULL COLLATE BINARY, value VARCHAR(255) DEFAULT NULL COLLATE BINARY, preferred INTEGER DEFAULT 1 NOT NULL, userid VARCHAR(255) DEFAULT '' NOT NULL COLLATE BINARY, "contactid" IN
TEGER UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_documents_invite (es_id VARCHAR(64) NOT NULL, "uid" VARCHAR(64) DEFAULT NULL, "status" INTEGER DEFAULT '0', "sent_on" INTEGER DEFAULT 0);
CREATE TABLE oc_documents_member ("member_id" INTEGER NOT NULL, es_id VARCHAR(64) NOT NULL, token VARCHAR(32) DEFAULT NULL, "uid" VARCHAR(64) DEFAULT NULL, "color" VARCHAR(32) DEFAULT NULL, "last_activity" INTEGER DEFAULT NULL, "status" INTEGER DEFAULT '1' NOT NULL,
 "is_guest" INTEGER DEFAULT '0' NOT NULL, PRIMARY KEY("member_id"));
CREATE TABLE oc_documents_op ("seq" INTEGER NOT NULL, es_id VARCHAR(64) NOT NULL, opspec CLOB DEFAULT NULL, "member" INTEGER DEFAULT 1 NOT NULL, PRIMARY KEY("seq"));
CREATE TABLE oc_documents_revisions (es_id VARCHAR(64) NOT NULL, save_hash VARCHAR(128) NOT NULL, "file_id" VARCHAR(512) DEFAULT NULL, "seq_head" INTEGER NOT NULL, "member_id" INTEGER NOT NULL);
CREATE TABLE oc_documents_session (es_id VARCHAR(64) NOT NULL, genesis_hash VARCHAR(128) NOT NULL, owner VARCHAR(64) NOT NULL, "genesis_url" VARCHAR(512) DEFAULT NULL, "file_id" VARCHAR(512) DEFAULT NULL, PRIMARY KEY(es_id));
CREATE TABLE oc_file_map ("logic_path" VARCHAR(512) DEFAULT '' NOT NULL, "logic_path_hash" VARCHAR(32) DEFAULT '' NOT NULL, "physic_path" VARCHAR(512) DEFAULT '' NOT NULL, "physic_path_hash" VARCHAR(32) DEFAULT '' NOT NULL, PRIMARY KEY("logic_path_hash"));
CREATE TABLE oc_filecache (fileid INTEGER NOT NULL, storage INTEGER DEFAULT 0 NOT NULL, parent INTEGER DEFAULT 0 NOT NULL, name VARCHAR(250) DEFAULT NULL COLLATE BINARY, mimetype INTEGER DEFAULT 0 NOT NULL, mimepart INTEGER DEFAULT 0 NOT NULL, mtime INTEGER DEFAULT
0 NOT NULL, encrypted INTEGER DEFAULT 0 NOT NULL, path_hash VARCHAR(32) DEFAULT '' NOT NULL COLLATE BINARY, etag VARCHAR(40) DEFAULT NULL COLLATE BINARY, storage_mtime INTEGER DEFAULT 0 NOT NULL, path VARCHAR(4000) DEFAULT NULL COLLATE BINARY, permissions INTEGER DE
FAULT 0, "size" BIGINT DEFAULT 0 NOT NULL, "unencrypted_size" BIGINT DEFAULT 0 NOT NULL, PRIMARY KEY(fileid));
CREATE TABLE oc_files_trash (id VARCHAR(250) DEFAULT '' NOT NULL, user VARCHAR(64) DEFAULT '' NOT NULL, timestamp VARCHAR(12) DEFAULT '' NOT NULL, location VARCHAR(512) DEFAULT '' NOT NULL, "type" VARCHAR(4) DEFAULT NULL, "mime" VARCHAR(255) DEFAULT NULL, "auto_id"
INTEGER NOT NULL, PRIMARY KEY("auto_id"));
CREATE TABLE oc_gallery_sharing (gallery_id INTEGER DEFAULT 0 NOT NULL, token VARCHAR(64) NOT NULL, "recursive" INTEGER NOT NULL);
CREATE TABLE oc_group_admin ("gid" VARCHAR(64) DEFAULT '' NOT NULL, "uid" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("gid", "uid"));
CREATE TABLE oc_group_user ("gid" VARCHAR(64) DEFAULT '' NOT NULL, "uid" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("gid", "uid"));
CREATE TABLE oc_groups ("gid" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("gid"));
CREATE TABLE oc_jobs ("id" INTEGER NOT NULL, class VARCHAR(255) DEFAULT '' NOT NULL, argument VARCHAR(256) DEFAULT '' NOT NULL, last_run INTEGER DEFAULT 0, PRIMARY KEY("id"));
CREATE TABLE oc_locks (id INTEGER NOT NULL, userid VARCHAR(64) DEFAULT NULL COLLATE BINARY, owner VARCHAR(100) DEFAULT NULL COLLATE BINARY, token VARCHAR(100) DEFAULT NULL COLLATE BINARY, uri CLOB DEFAULT NULL COLLATE BINARY, "timeout" INTEGER UNSIGNED DEFAULT NULL,
 "created" BIGINT DEFAULT NULL, "scope" SMALLINT DEFAULT NULL, "depth" SMALLINT DEFAULT NULL, PRIMARY KEY(id));
CREATE TABLE oc_lucene_status ("fileid" INTEGER DEFAULT 0 NOT NULL, status VARCHAR(1) DEFAULT NULL, PRIMARY KEY("fileid"));
CREATE TABLE "oc_media_albums" ("album_id" INTEGER PRIMARY KEY AUTOINCREMENT, "album_name" VARCHAR(200) DEFAULT ' ' NOT NULL, "album_artist" INTEGER DEFAULT 0 NOT NULL, "album_art" VARCHAR(200));
CREATE TABLE "oc_media_artists" ("artist_id" INTEGER PRIMARY KEY AUTOINCREMENT, "artist_name" VARCHAR(200) DEFAULT ' ' NOT NULL);
CREATE TABLE "oc_media_sessions" ("session_id" INTEGER PRIMARY KEY AUTOINCREMENT, "token" VARCHAR(64) DEFAULT ' ' NOT NULL, "user_id" VARCHAR(64) DEFAULT ' ' NOT NULL, "start" DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL);
CREATE TABLE "oc_media_songs" ("song_id" INTEGER PRIMARY KEY AUTOINCREMENT, "song_name" VARCHAR(200) DEFAULT ' ' NOT NULL, "song_artist" INTEGER DEFAULT 0 NOT NULL, "song_album" INTEGER DEFAULT 0 NOT NULL, "song_path" VARCHAR(200) DEFAULT ' ' NOT NULL, "song_user" V
ARCHAR(64) DEFAULT '0' NOT NULL, "song_length" INTEGER DEFAULT 0 NOT NULL, "song_track" INTEGER DEFAULT 0 NOT NULL, "song_size" INTEGER DEFAULT 0 NOT NULL, "song_playcount" INTEGER DEFAULT 0 NOT NULL, "song_lastplayed" INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE "oc_media_users" ("user_id" VARCHAR(64) DEFAULT '0' NOT NULL, "user_password_sha256" VARCHAR(64) DEFAULT ' ' NOT NULL);
CREATE TABLE oc_mimetypes ("id" INTEGER NOT NULL, "mimetype" VARCHAR(255) DEFAULT '' NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_mozilla_sync_collections ("id" INTEGER NOT NULL, name VARCHAR(32) NOT NULL, "userid" INTEGER NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_mozilla_sync_users ("id" INTEGER NOT NULL, username VARCHAR(64) NOT NULL, sync_user VARCHAR(128) NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_mozilla_sync_wbo ("id" INTEGER NOT NULL, parentid VARCHAR(64) DEFAULT NULL, predecessorid VARCHAR(64) DEFAULT NULL, payload CLOB NOT NULL, name VARCHAR(64) NOT NULL, sortindex INTEGER DEFAULT NULL, modified NUMERIC(12, 2) DEFAULT '0.00' NOT NULL, "collectionid" INTEGER NOT NULL, "ttl" INTEGER DEFAULT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_news_feeds ("id" INTEGER NOT NULL, url CLOB NOT NULL COLLATE BINARY, title CLOB NOT NULL COLLATE BINARY, link CLOB DEFAULT NULL COLLATE BINARY, favicon_link CLOB DEFAULT NULL COLLATE BINARY, prevent_update BOOLEAN DEFAULT '0' NOT NULL, user_id VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, url_hash VARCHAR(32) NOT NULL COLLATE BINARY, location CLOB DEFAULT NULL COLLATE BINARY, last_modified CLOB DEFAULT NULL COLLATE BINARY, etag CLOB DEFAULT NULL COLLATE BINARY, "added" BIGINT UNSIGNED DEFAULT 0, "deleted_at" BIGINT UNSIGNED DEFAULT 0, "folder_id" BIGINT NOT NULL, "articles_per_update" BIGINT DEFAULT 0 NOT NULL, "ordering" INTEGER DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_news_folders ("id" INTEGER NOT NULL, opened BOOLEAN DEFAULT '1' NOT NULL, name VARCHAR(100) NOT NULL COLLATE BINARY, user_id VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, "parent_id" BIGINT DEFAULT NULL, "deleted_at" BIGINT UNSIGNED DEFAULT 0, PRIMARY KEY(id));
CREATE TABLE oc_news_items ("id" INTEGER NOT NULL, guid CLOB NOT NULL COLLATE BINARY, author CLOB DEFAULT NULL COLLATE BINARY, body CLOB DEFAULT NULL COLLATE BINARY, enclosure_mime CLOB DEFAULT NULL COLLATE BINARY, enclosure_link CLOB DEFAULT NULL COLLATE BINARY, guid_hash VARCHAR(32) NOT NULL COLLATE BINARY, url CLOB DEFAULT NULL COLLATE BINARY, title CLOB DEFAULT NULL COLLATE BINARY, "pub_date" BIGINT UNSIGNED DEFAULT NULL, "feed_id" BIGINT NOT NULL, "status" BIGINT DEFAULT 0 NOT NULL, "last_modified" BIGINT UNSIGNED DEFAULT 0, PRIMARY KEY(id));
CREATE TABLE oc_permissions (fileid INTEGER DEFAULT 0 NOT NULL, permissions INTEGER DEFAULT 0 NOT NULL, "user" VARCHAR(64) DEFAULT NULL);
CREATE TABLE oc_pictures_images_cache ("uid_owner" VARCHAR(64) NOT NULL, "path" VARCHAR(256) NOT NULL, "width" INTEGER NOT NULL, "height" INTEGER NOT NULL);
CREATE TABLE oc_preferences (configvalue CLOB DEFAULT NULL, "userid" VARCHAR(64) DEFAULT '' NOT NULL, "appid" VARCHAR(32) DEFAULT '' NOT NULL, "configkey" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("userid", "appid", "configkey"));
CREATE TABLE oc_privatedata ("keyid" INTEGER NOT NULL, app VARCHAR(255) DEFAULT '' NOT NULL, "key" VARCHAR(255) DEFAULT '' NOT NULL, value VARCHAR(255) DEFAULT '' NOT NULL, user VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("keyid"));
CREATE TABLE oc_properties ("userid" VARCHAR(64) DEFAULT '' NOT NULL, "propertypath" VARCHAR(255) DEFAULT '' NOT NULL, "propertyname" VARCHAR(255) DEFAULT '' NOT NULL, "propertyvalue" VARCHAR(255) NOT NULL, "id" INTEGER NOT NULL, PRIMARY KEY("id"));
CREATE TABLE "oc_queuedtasks" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "app" VARCHAR(255) DEFAULT ' ' NOT NULL, "klass" VARCHAR(255) DEFAULT ' ' NOT NULL, "method" VARCHAR(255) DEFAULT ' ' NOT NULL, "parameters" VARCHAR(255) DEFAULT ' ' NOT NULL);
CREATE TABLE oc_share (id INTEGER NOT NULL, share_with VARCHAR(255) DEFAULT NULL COLLATE BINARY, item_source VARCHAR(255) DEFAULT NULL COLLATE BINARY, item_target VARCHAR(255) DEFAULT NULL COLLATE BINARY, file_target VARCHAR(512) DEFAULT NULL COLLATE BINARY, expiration DATETIME DEFAULT NULL, token VARCHAR(32) DEFAULT NULL COLLATE BINARY, parent INTEGER DEFAULT NULL, item_type VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, file_source INTEGER DEFAULT NULL, uid_owner VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, "share_type" SMALLINT DEFAULT 0 NOT NULL, "permissions" SMALLINT DEFAULT 0 NOT NULL, "stime" BIGINT DEFAULT 0 NOT NULL, "accepted" SMALLINT DEFAULT 0 NOT NULL, "mail_send" SMALLINT DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_share_external (id INTEGER NOT NULL, "remote" VARCHAR(512) NOT NULL, "share_token" VARCHAR(64) NOT NULL, "password" VARCHAR(64) DEFAULT NULL, "name" VARCHAR(64) NOT NULL, "owner" VARCHAR(64) NOT NULL, "user" VARCHAR(64) NOT NULL, "mountpoint" VARCHAR(4000) NOT NULL, "mountpoint_hash" VARCHAR(32) NOT NULL, "remote_id" INTEGER DEFAULT -1 NOT NULL, "accepted" INTEGER DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_storages ("numeric_id" INTEGER NOT NULL, id VARCHAR(64) DEFAULT NULL, PRIMARY KEY("numeric_id"));
CREATE TABLE oc_users (displayname VARCHAR(64) DEFAULT NULL, "uid" VARCHAR(64) DEFAULT '' NOT NULL, "password" VARCHAR(255) DEFAULT '' NOT NULL, PRIMARY KEY("uid"));
CREATE TABLE oc_vcategory ("id" INTEGER NOT NULL, uid VARCHAR(64) DEFAULT '' NOT NULL, type VARCHAR(64) DEFAULT '' NOT NULL, category VARCHAR(255) DEFAULT '' NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_vcategory_to_object (type VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, objid INTEGER UNSIGNED DEFAULT 0 NOT NULL, categoryid INTEGER UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY("categoryid", "objid", "type"));
CREATE INDEX album_artist_index ON "oc_media_albums" (album_artist ASC);
CREATE INDEX album_name_index ON "oc_media_albums" (album_name ASC);
CREATE INDEX appconfig_appid_key ON oc_appconfig ("appid");
CREATE INDEX appconfig_config_key_index ON oc_appconfig (configkey);
CREATE UNIQUE INDEX artist_name ON "oc_media_artists" (artist_name ASC);
CREATE INDEX c_addressbook_userid_index ON oc_contacts_addressbooks (userid);
CREATE INDEX c_addressbookid_index ON oc_contacts_cards (addressbookid);
CREATE INDEX category_index ON oc_vcategory (category);
CREATE INDEX cp_contactid_index ON oc_contacts_cards_properties (contactid);
CREATE INDEX cp_name_index ON oc_contacts_cards_properties (name);
CREATE INDEX cp_value_index ON oc_contacts_cards_properties (value);
CREATE UNIQUE INDEX documents_op_eis_idx ON oc_documents_op (es_id, seq);
CREATE UNIQUE INDEX documents_rev_eis_idx ON oc_documents_revisions (es_id, seq_head);
CREATE UNIQUE INDEX file_map_pp_index ON "oc_file_map" (physic_path_hash);
CREATE INDEX file_source_index ON oc_share (file_source);
CREATE INDEX fs_parent_name_hash ON oc_filecache (parent, name);
CREATE INDEX fs_storage_mimepart ON oc_filecache (storage, mimepart);
CREATE INDEX fs_storage_mimetype ON oc_filecache (storage, mimetype);
CREATE UNIQUE INDEX fs_storage_path_hash ON oc_filecache (storage, path_hash);
CREATE INDEX fs_storage_size ON oc_filecache (storage, size, fileid);
CREATE INDEX group_admin_uid ON "oc_group_admin" (uid);
CREATE INDEX id_index ON oc_files_trash (id);
CREATE INDEX id_user_index ON "oc_permissions" ("fileid", "user");
CREATE INDEX item_share_type_index ON oc_share (item_type, share_type);
CREATE INDEX job_class_index ON oc_jobs (class);
CREATE UNIQUE INDEX mimetype_id_index ON "oc_mimetypes" (mimetype);
CREATE INDEX news_feeds_folder_id_index ON oc_news_feeds (folder_id);
CREATE INDEX news_feeds_url_hash_index ON oc_news_feeds (url_hash);
CREATE INDEX news_feeds_user_id_index ON oc_news_feeds (user_id);
CREATE INDEX news_folders_parent_id_index ON oc_news_folders (parent_id);
CREATE INDEX news_folders_user_id_index ON oc_news_folders (user_id);
CREATE INDEX news_items_feed_id_index ON oc_news_items (feed_id);
CREATE INDEX news_items_item_guid ON oc_news_items (guid_hash, feed_id);
CREATE INDEX oc_mozilla_sync_collections_userid_name ON "oc_mozilla_sync_collections" (userid, name);
CREATE INDEX oc_mozilla_sync_users_sync_user ON "oc_mozilla_sync_users" (sync_user);
CREATE INDEX oc_mozilla_sync_wbo_coll_name ON "oc_mozilla_sync_wbo" (collectionid, name);
CREATE INDEX oc_mozilla_sync_wbo_coll_name_mod ON "oc_mozilla_sync_wbo" (collectionid, name, modified);
CREATE INDEX oc_mozilla_sync_wbo_collectionid ON "oc_mozilla_sync_wbo" (collectionid);
CREATE INDEX property_index ON "oc_properties" (userid);
CREATE UNIQUE INDEX sh_external_mp ON oc_share_external (user, mountpoint_hash);
CREATE INDEX sh_external_user ON oc_share_external (user);
CREATE INDEX song_album_index ON "oc_media_songs" (song_album ASC);
CREATE INDEX song_artist_index ON "oc_media_songs" (song_artist ASC);
CREATE INDEX song_name_index ON "oc_media_songs" (song_name ASC);
CREATE INDEX status_index ON oc_lucene_status (status);
CREATE UNIQUE INDEX storages_id_index ON "oc_storages" (id);
CREATE INDEX timestamp_index ON oc_files_trash (timestamp);
CREATE INDEX token_index ON oc_share (token);
CREATE INDEX type_index ON oc_vcategory (type);
CREATE INDEX uid_index ON oc_vcategory (uid);
CREATE INDEX user_index ON oc_files_trash (user);
CREATE INDEX vcategory_objectd_index ON oc_vcategory_to_object (objid, type);

```

**Comment by MorrisJobke** [comment]
@mehturt Is there any log message in your data/owncloud.log?

**Comment by mehturt** [comment]
Yes, I found something:

```
{"reqId":"8f3464c78f54b96675552cfd78ee48e5","remoteAddr":"192.168.100.31","app":"core","message":"Simulated database structure update failed (exception 'OC\\DB\\MigrationException' with message 'Unknown database type  requested, Doctrine\\DBAL\\Platforms\\SqlitePlatform may not support it.' in \/var\/www\/owncloud8\/lib\/private\/db\/sqlitemigrator.php:39\nStack trace:\n#0 \/var\/www\/owncloud8\/lib\/private\/db\/mdb2schemamanager.php(113): OC\\DB\\SQLiteMigrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#1 \/var\/www\/owncloud8\/lib\/private\/db.php(252): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#2 \/var\/www\/owncloud8\/lib\/private\/updater.php(238): OC_DB::simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#3 \/var\/www\/owncloud8\/lib\/private\/updater.php(211): OC\\Updater->checkCoreUpgrade()\n#4 \/var\/www\/owncloud8\/lib\/private\/updater.php(150): OC\\Updater->doUpgrade('8.0.2.0', '8.0.2.0')\n#5 \/var\/www\/owncloud8\/core\/ajax\/update.php(50): OC\\Updater->upgrade()\n#6 {main})","level":4,"time":"2015-04-24T21:11:01+00:00"}
```

**Comment by DeepDiver1975** [comment]
I created a sqlite db based on the schema above and upgrade was working - really strange

**Comment by mehturt** [comment]
Upgrade from 8.0.2 to 8.0.3? Strange.
I will try to rerun later this week and report here.

**Comment by DeepDiver1975** [comment]
> I will try to rerun later this week and report here.

what might help before you upgrade:
there are some tables in your schema which are no longer required - they might cause this.

The list of tables which are no longer needed is here https://github.com/owncloud/core/blob/master/lib/repair/dropoldtables.php#L73

**Comment by mehturt** [comment]
@DeepDiver1975 
I checked the list of tables and I don't have any of the tables mentioned there (all my tables start with oc_ prefix and I don't see such table in oldDatabaseTables())
Is there a way to enhance the logging to see what table (or other DB object) is causing it?

**Comment by mehturt** [comment]
So I debugged this further and found out the table sqlite_stat1 is causing this error.  Unfortunately it's not listed in .tables or .schema output.
This issue can be closed now.
