### ISSUE TITLE
Files aren't removed from the trashbin list when restored.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16141]
### Steps to reproduce

1. Enable encryption app.
2. Enable default encryption module (admin page).
3. Log out and log in again.
4. Mount a SFTP folder.
5. Delete files from the SFTP folder.
6. Restore them in the trashbin.

### Expected behaviour
Files are removed from the trashbin list when restoring them.
Files are restored to the SFTP folder.

### Actual behaviour
Files are restored to the SFTP folder, but files are not removed from the list of files in trashbin and other files cannot be restored since the restoring icon dissapeared from files. 

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
Postgresql and SQLite (tested both)

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition.
Encryption.
External Storage

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes one sftp enabled.

**Are you using encryption:** 
yes

**Logs**
```
{"reqId":"t0b0SXDBvYrzB0FpEZhH","remoteAddr":"82.159.139.58","app":"index","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Encryption library: Decryption (symmetric) of content failed: error:0906D06C:PEM routines:PEM_read_bio:no start line\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(294): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(false, false, '', 'AES-128-CFB')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(275): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('\\\/*? * Copyright...', '', 'AES-128-CFB')\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(432): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('\\\/*? * Copyright...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(278): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/helper.php(611): fread(Resource id #48, 8192)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(436): OC_Helper::streamCopy(Resource id #48, Resource id #62)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(383): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_trashbin\\\/...', 'networksettings...', true, true)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(526): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_trashbin\\\/...', 'networksettings...')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(650): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_trashbin\\\/...', 'networksettings...')\\n#10 \\\/opt\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(317): OC\\\\Files\\\\View->rename('\\\/files_trashbin...', '\\\/files\\\/SFTP\\\/net...')\\n#11 \\\/opt\\\/owncloud\\\/apps\\\/files_trashbin\\\/ajax\\\/undelete.php(72): OCA\\\\Files_Trashbin\\\\Trashbin::restore('\\\/\\\/networksettin...', 'networksettings...', '1430983758')\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#13 [internal function]: __lambda_func(Array)\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('?lambda_1786', Array)\\n#15 \\\/opt\\\/owncloud\\\/lib\\\/base.php(860): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_tra...')\\n#16 \\\/opt\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":351}","level":4,"time":"2015-05-07T07:36:42+00:00"}
{"reqId":"3leQlf+uLaNwPzvlP1Cd","remoteAddr":"82.159.139.58","app":"PHP","message":"fread(): Length parameter must be greater than 0 at \/opt\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#67","level":3,"time":"2015-05-07T07:37:01+00:00"}
{"reqId":"3leQlf+uLaNwPzvlP1Cd","remoteAddr":"82.159.139.58","app":"index","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Encryption library: Decryption (symmetric) of content failed: error:0906D06C:PEM routines:PEM_read_bio:no start line\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(294): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(false, false, '', 'AES-128-CFB')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(275): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('\\\/*? * Copyright...', '', 'AES-128-CFB')\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(432): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('\\\/*? * Copyright...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(278): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/helper.php(611): fread(Resource id #48, 8192)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(436): OC_Helper::streamCopy(Resource id #48, Resource id #64)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(383): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_trashbin\\\/...', 'networksettings...', true, true)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(526): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_trashbin\\\/...', 'networksettings...')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(650): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_trashbin\\\/...', 'networksettings...')\\n#10 \\\/opt\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(317): OC\\\\Files\\\\View->rename('\\\/files_trashbin...', '\\\/files\\\/SFTP\\\/net...')\\n#11 \\\/opt\\\/owncloud\\\/apps\\\/files_trashbin\\\/ajax\\\/undelete.php(72): OCA\\\\Files_Trashbin\\\\Trashbin::restore('\\\/\\\/networksettin...', 'networksettings...', '1430983758')\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#13 [internal function]: __lambda_func(Array)\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('?lambda_230', Array)\\n#15 \\\/opt\\\/owncloud\\\/lib\\\/base.php(860): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_tra...')\\n#16 \\\/opt\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":351}","level":4,"time":"2015-05-07T07:37:01+00:00"}
```
### Client configuration

**browser**
Chrome 41

**Comment by karlitschek** [comment]
@schiesbn can you have a look?

**Comment by PVince81** [comment]
Works for me without encryption.

With encryption I have a different behavior than described.
There have been many fixes with trashbin and encryption, so the original issue was likely to be solved.

Now to the new bad behavior: after I restore the folder from trash, the folder is back. But the file that was in it appears TWICE in the web UI!

**Comment by PVince81** [comment]
I'll raise this separately to avoid confusion.

**Comment by PVince81** [comment]
Raised here: https://github.com/owncloud/core/issues/16475

**Comment by SergioBertolinSG** [comment]
Tested on 8.1.0.6, it is fixed, a bit slow but it works.

**Comment by PVince81** [comment]
It is slow because it needs to re-upload the file to SFTP.
