### ISSUE TITLE
smashbox test test_shareFile fails

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16182]
### Steps to reproduce

1. Install 8.1 
2. Install client 1.8.1
3. Run smashbox tests lib/oc-tests/test_shareFile.py

### Expected behaviour

Test should pass

### Actual behaviour

The test fails with this error in the server log file:

```
{"reqId":"wIQB02xT42yvg+XJaX88","remoteAddr":"172.18.5.197","app":"PHP","message":"fopen(\/var\/www\/html\/owncloud\/data\/user2): failed to open stream: Is a directory at \/var\/www\/html\/owncloud\/apps\/files_locking\/lib\/lock.php#134","level":3,"time":"2015-05-07T19:57:10+00:00"}
{"reqId":"wIQB02xT42yvg+XJaX88","remoteAddr":"172.18.5.197","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Target file  is locked by another process.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #30)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('TEST_FILE_MODIF...', Resource id #30, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":174}","level":4,"time":"2015-05-07T19:57:10+00:00"}


```

The test runs successfully against 8.0.3

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 alpha 3 (daily) Build:2015-05-07T03:08:39+00:00 55eaa165f8cd98aebc457fcfbd98c7a7c40f3e30

**Comment by DeepDiver1975** [comment]
duplicate

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/files_locking/issues/24
