### ISSUE TITLE
Exception thrown disabling external sites app

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16297]
### Steps to reproduce

1. Install 8.1 
2. Enable External sites app & configure
3. Disable External Sites app 

### Expected behaviour

No errors in the log file

### Actual behaviour

I'm seeing this error in the log file:

```

{"reqId":"LP9wygxfxtsL4PBEirCj","remoteAddr":"x.x.x.x","app":"index","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"external_index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(304): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('external_index', Array, false)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(65): OC\\\\Route\\\\Router->generate('external_index', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/helper.php(139): OC\\\\URLGenerator->linkToRoute('external_index', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/util.php(286): OC_Helper::linkToRoute('external_index', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/external\\\/appinfo\\\/app.php(34): OCP\\\\Util::linkToRoute('external_index', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/app.php(389): require('\\\/var\\\/www\\\/html\\\/o...')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/settings\\\/ajax\\\/navigationdetect.php(30): OC_App::getAppNavigationEntries('external')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('?lambda_7358', Array)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(860): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":4,"time":"2015-05-12T19:02:48+00:00"}

```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 1 (daily) Build:2015-05-12T03:08:46+00:00 20d2d8d3ddee2750343bdec69a3e7031b710039a

**Comment by karlitschek** [comment]
strange @DeepDiver1975 what do you think?

**Comment by DeepDiver1975** [comment]
We have seen similar log messages for activity. 
There is no really much we can do. All this exception is telling us: somebody requested an url which we don't know (anymore).

This can happen anytime - in this case there is/was still someone trying to access the url of the just disabled app.

**Comment by nickvergessen** [comment]
In this case there is something we can do. Will create a PR on the externals app

**Comment by nickvergessen** [comment]
Fixed with https://github.com/owncloud/apps/pull/2063

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Doesn't this sound familiar? I reported this over a year ago ;) #8361

**Comment by MorrisJobke** [comment]
The fixed behaviour just is a side effect of the actual code change, because it is now executed only if the nav entry is needed ;) I will try this with music and news app again ;)

**Comment by MorrisJobke** [comment]
The actual problem here is, that we somehow load apps even if they are disabled during the very same request.

**Comment by MorrisJobke** [comment]
This doesn't seem to occur anymore in master.
