### ISSUE TITLE
Spinner keeps spinning when deleting a file in a recipient shared folder with encryption

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16348]
### Steps to reproduce

1. Enable encryption app.
2. Enable encryption module in admin page.
3. Relogin.
4. Create user1.
5. As admin, share a folder "sub" with "user1"
6. Login as user1. (Relogin if needed).
7. Create a text file "sub/test.txt"
8. Remove "sub/test.txt".

### Expected behaviour
File is deleted, quickly removing the file from the file list.

### Actual behaviour
File is deleted but spinner keeps spinning and file is not removed from the list. It is removed if you refresh the page.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
Exception: {"Exception":"OC\\Encryption\\Exceptions\\DecryptionFailedException","Message":"Encryption library: Decryption (symmetric) of content failed: error:0906D06C:PEM routines:PEM_read_bio:no start line","Code":0,"Trace":"#0 \/opt\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php(294): OCA\\Encryption\\Crypto\\Crypt->decrypt(false, false, '', 'AES-128-CFB')\n#1 \/opt\/owncloud\/apps\/encryption\/lib\/crypto\/encryption.php(275): OCA\\Encryption\\Crypto\\Crypt->symmetricDecryptFileContent('\/*? * Copyright...', '', 'AES-128-CFB')\n#2 \/opt\/owncloud\/lib\/private\/files\/stream\/encryption.php(432): OCA\\Encryption\\Crypto\\Encryption->decrypt('\/*? * Copyright...')\n#3 \/opt\/owncloud\/lib\/private\/files\/stream\/encryption.php(278): OC\\Files\\Stream\\Encryption->readCache()\n#4 [internal function]: OC\\Files\\Stream\\Encryption->stream_read(8192)\n#5 \/opt\/owncloud\/lib\/private\/helper.php(611): fread(Resource id #53, 8192)\n#6 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(430): OC_Helper::streamCopy(Resource id #53, Resource id #54)\n#7 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(403): OC\\Files\\Storage\\Wrapper\\Encryption->copyBetweenStorage(Object(OCA\\Files_Trashbin\\Storage), 'files_trashbin\/...', 'files_trashbin\/...', false, false)\n#8 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(516): OC\\Files\\Storage\\Wrapper\\Encryption->copyFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'files_trashbin\/...', 'files_trashbin\/...')\n#9 \/opt\/owncloud\/lib\/private\/files\/view.php(737): OC\\Files\\Storage\\Wrapper\\Wrapper->copyFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'files_trashbin\/...', 'files_trashbin\/...')\n#10 \/opt\/owncloud\/apps\/files_trashbin\/lib\/trashbin.php(702): OC\\Files\\View->copy('user1\/files_tra...', 'admin\/files_tra...')\n#11 \/opt\/owncloud\/apps\/files_trashbin\/lib\/trashbin.php(144): OCA\\Files_Trashbin\\Trashbin::copy_recursive('user1\/files_tra...', 'admin\/files_tra...', Object(OC\\Files\\View))\n#12 \/opt\/owncloud\/apps\/files_trashbin\/lib\/trashbin.php(220): OCA\\Files_Trashbin\\Trashbin::copyFilesToOwner('CARPETA\/mir??ll...', 'admin', '\/CARPETA\/mir??l...', 1431590025)\n#13 \/opt\/owncloud\/apps\/files_trashbin\/lib\/storage.php(100): OCA\\Files_Trashbin\\Trashbin::move2trash('CARPETA\/mir??ll...')\n#14 \/opt\/owncloud\/lib\/private\/files\/view.php(938): OCA\\Files_Trashbin\\Storage->unlink('mir??ll????????...')\n#15 \/opt\/owncloud\/lib\/private\/files\/view.php(573): OC\\Files\\View->basicOperation('unlink', '\/CARPETA\/mir??l...', Array)\n#16 \/opt\/owncloud\/lib\/private\/files\/filesystem.php(677): OC\\Files\\View->unlink('\/CARPETA\/mir??l...')\n#17 \/opt\/owncloud\/apps\/files\/ajax\/delete.php(59): OC\\Files\\Filesystem::unlink('\/CARPETA\/mir??l...')\n#18 \/opt\/owncloud\/lib\/private\/route\/route.php(153) : runtime-created function(1): require_once('\/opt\/owncloud\/a...')\n#19 [internal function]: __lambda_func(Array)\n#20 \/opt\/owncloud\/lib\/private\/route\/router.php(272): call_user_func('?lambda_821', Array)\n#21 \/opt\/owncloud\/lib\/base.php(862): OC\\Route\\Router->match('\/apps\/files\/aja...')\n#22 \/opt\/owncloud\/index.php(40): OC::handleRequest()\n#23 {main}","File":"\/opt\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php","Line":351}
```

### Client configuration

**browser**
Chrome 41

**Comment by schiesbn** [comment]
Fixed with the latest changes to the trashbin on master:

https://github.com/owncloud/core/pull/16404
https://github.com/owncloud/core/pull/16399
https://github.com/owncloud/core/pull/16405

**Comment by SergioBertolinSG** [comment]
Tested in 
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}
working fine.
