### ISSUE TITLE
"No such file or directory" error in log when accessing trashbin and no files have been deleted

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#16365]
On current master:
1. Setup a new ownCloud instance as user "admin"
2. Create a user "test"
3. Login as user "test"
4. Click on "Deleted files" in the files apps sidebar
5. Take a look at the log

```
{"reqId":"+1I1sOa\/fmsH5NlR2y1s","remoteAddr":"::1","app":"PHP","message":"opendir(\/Users\/lukasreschke\/Documents\/Programming\/master\/data\/test\/files_trashbin\/files): failed to open dir: No such file or directory at \/Users\/lukasreschke\/Documents\/Programming\/master\/lib\/private\/files\/storage\/local.php#105","level":3,"time":"2015-05-15T07:17:48+00:00"}
```

**Comment by LukasReschke** [comment]
Partially caused by stuff like https://github.com/owncloud/core/issues/16366

**Comment by PVince81** [comment]
Ah yes, known issue

**Comment by MorrisJobke** [comment]
Stack trace:

```

{"reqId":"9H9eAX\/OGr08P9Nt99bP","remoteAddr":"::1","app":"no app in context","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"\",\"Code\":0,\"Trace\":\"
#0 lib/private/files/storage/wrapper/wrapper.php(90): OC\Files\Storage\Local->opendir('files_trashbin/...')
#1 lib/private/files/storage/wrapper/wrapper.php(90): OC\Files\Storage\Wrapper\Wrapper->opendir('files_trashbin/...')
#2 lib/private/files/view.php(1059): OC\Files\Storage\Wrapper\Wrapper->opendir('files_trashbin/...')
#3 lib/private/files/view.php(343): OC\Files\View->basicOperation('opendir', '/', Array)
#4 apps/files_trashbin/lib/helper.php(54): OC\Files\View->opendir('/')
#5 apps/files_trashbin/ajax/list.php(34): OCA\Files_Trashbin\Helper::getTrashFiles('/', 'abc', 'mtime', true)
#6 lib/private/route/route.php(154) : runtime-created function(1): require_once('/Users/morrisjo...')
#7 [internal function]: __lambda_func(Array)
#8 lib/private/route/router.php(273): call_user_func('\x00lambda_6094', Array)
#9 lib/base.php(856): OC\Route\Router->match('/apps/files_tra...')
#10 index.php(39): OC::handleRequest()
#11 {main}\",\"File\":\"lib/private/files/storage/local.php\",\"Line\":96}","level":3,"time":"2016-02-10T13:58:45+00:00","method":"GET","url":"\/master\/index.php\/apps\/files_trashbin\/ajax\/list.php?dir=%2F&sort=mtime&sortdirection=desc"}
```

**Comment by laodan** [comment]
This problem is still existing in ownCloud 9.02 (fresh install).

"message":"opendir(\/home\/liusolas\/ownclouddata\/laodan\/files_trashbin\/files): failed to open dir: No such file or directory at \/home\/liusolas\/public_html\/owncloud\/lib\/private\/files\/storage\/local.php#99","level":3,"time":"2016-06-06T01:39:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files_trashbin\/ajax\/list.php?dir=%2F&sort=mtime&sortdirection=desc","user":"laodan"}

Does the log mean that I need to change the php code at line 99 of file local.php? Here is the code aat line 99:
98            public function opendir($path) {
99		return opendir($this->getSourcePath($path));
100	        }

**Comment by PVince81** [comment]
Please reopen if issue persists with 10.0.4.
