### ISSUE TITLE
Cannot upload a file to FTP or ownCloud external storages if the LDAP server is down

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16390]
### Steps to reproduce
1. Install and enable external storage and LDAP users (checked also with encryption, but it might not be related)
2. Configure correctly a LDAP server
3. Setup an ownCloud and/or FTP external storages
4. Shutdown the LDAP server
5. Upload a file to the external storage with a local user (checked with the admin one)

### Expected behaviour
The file is uploaded correctly

### Actual behaviour
"Connection to LDAP server could not be established" error message shows up. The file is uploaded with 0KB. Other external storages (checked SFTP, SMB, Dropbox) don't present this issue

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
 - encryption: 1.0.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_sharing: 0.6.1
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - user_ldap: 0.6.0

#### ownCloud log (data/owncloud.log)
For the ownCloud external storage
```
{"reqId":"y3tLduS94SBBsRCXbxgA","remoteAddr":"10.40.30.21","app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":2,"time":"2015-05-18T07:34:15+00:00"}
{"reqId":"y3tLduS94SBBsRCXbxgA","remoteAddr":"10.40.30.21","app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":2,"time":"2015-05-18T07:34:15+00:00"}
{"reqId":"y3tLduS94SBBsRCXbxgA","remoteAddr":"10.40.30.21","app":"user_ldap","message":"No LDAP Connection to server 10.40.40.74","level":3,"time":"2015-05-18T07:34:15+00:00"}
{"reqId":"y3tLduS94SBBsRCXbxgA","remoteAddr":"10.40.30.21","app":"webdav client","message":"curl GET http:\/\/10.40.30.21:8140\/remote.php\/webdav\/android_settings.xcf returned status code 201","level":3,"time":"2015-05-18T07:34:15+00:00"}
```

For FTP external storage
```
{"reqId":"vxIsGzGe5gXbRx3W+3nT","remoteAddr":"10.40.30.21","app":"index","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Encryption library: Decryption (symmetric) of content failed: error:0906D06C:PEM routines:PEM_read_bio:no start line\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(294): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(false, false, '', 'AES-128-CFB')\\n#1 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(275): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('??????JFIF?????...', '', 'AES-128-CFB')\\n#2 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(432): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('??????JFIF?????...')\\n#3 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(278): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/image.php(480): stream_get_contents(Resource id #28)\\n#6 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/preview.php(562): OC_Image->loadFromFileHandle(Resource id #28)\\n#7 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/preview.php(517): OC\\\\Preview->getCachedPreview(267, 'thumbnails\\\/267\\\/...')\\n#8 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/preview.php(544): OC\\\\Preview->getPreview()\\n#9 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/core\\\/ajax\\\/preview.php(61): OC\\\\Preview->showPreview()\\n#10 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/home\\\/jvillafan...')\\n#11 [internal function]: __lambda_func(Array)\\n#12 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('?lambda_273', Array)\\n#13 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(862): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#14 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/index.php(40): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":351}","level":4,"time":"2015-05-18T07:40:41+00:00"}
{"reqId":"8Myi3lKh2fJ\/9l6bq6qn","remoteAddr":"10.40.30.21","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"File not found.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/core\\\/ajax\\\/preview.php(61): OC\\\\Preview->showPreview()\\n#1 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/home\\\/jvillafan...')\\n#2 [internal function]: __lambda_func(Array)\\n#3 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('?lambda_298', Array)\\n#4 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(862): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#5 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/index.php(40): OC::handleRequest()\\n#6 {main}\",\"File\":\"\\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/preview.php\",\"Line\":539}","level":4,"time":"2015-05-18T07:40:43+00:00"}
{"reqId":"W1va2txhJ0+y4q\/+gxdP","remoteAddr":"10.40.30.21","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"File not found.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/core\\\/ajax\\\/preview.php(61): OC\\\\Preview->showPreview()\\n#1 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/home\\\/jvillafan...')\\n#2 [internal function]: __lambda_func(Array)\\n#3 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('?lambda_64', Array)\\n#4 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(862): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#5 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/index.php(40): OC::handleRequest()\\n#6 {main}\",\"File\":\"\\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/preview.php\",\"Line\":539}","level":4,"time":"2015-05-18T07:40:43+00:00"}
{"reqId":"6P2ytcJQJP\/nz2b6yxWk","remoteAddr":"10.40.30.21","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"File not found.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/core\\\/ajax\\\/preview.php(61): OC\\\\Preview->showPreview()\\n#1 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/home\\\/jvillafan...')\\n#2 [internal function]: __lambda_func(Array)\\n#3 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('?lambda_99', Array)\\n#4 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(862): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#5 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/index.php(40): OC::handleRequest()\\n#6 {main}\",\"File\":\"\\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/preview.php\",\"Line\":539}","level":4,"time":"2015-05-18T07:40:44+00:00"}
{"reqId":"RoBMJiq9gSHF5CDu5SrV","remoteAddr":"10.40.30.21","app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":2,"time":"2015-05-18T07:40:59+00:00"}
{"reqId":"RoBMJiq9gSHF5CDu5SrV","remoteAddr":"10.40.30.21","app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":2,"time":"2015-05-18T07:40:59+00:00"}
{"reqId":"RoBMJiq9gSHF5CDu5SrV","remoteAddr":"10.40.30.21","app":"user_ldap","message":"No LDAP Connection to server 10.40.40.74","level":3,"time":"2015-05-18T07:40:59+00:00"}
```

**Comment by karlitschek** [comment]
Not sure this is a bug. As soon as an LDAP server is uses this becomes a hard requirements. Doesn't work if the LDAP sever is down.
