### ISSUE TITLE
CSRF error after setup with redis module when redis is down

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16624]
### Steps to reproduce
1. Enable the PHP redis module
2. Shut down / do not start any redis server
3. Setup ownCloud from scratch (do not touch the config.php)

### Expected result
ownCloud can be setup

### Actual result
Getting internal server error, ownCloud unusable

### Versions
ownCloud 8.0.3 and stable8

Not sure if intended.
Maybe I should manually disable redis in config.php if I don't want to use it ?
(some people might have the redis module enabled for other apps but do not want to use it for OC)

### Log
```
{"reqId":"8aa32645c5f9ad5617eed63307c5c2c6","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Message\":\"Redis server went away\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/redis.php(68): Redis->exists('ocakm2951494\\\/ro...')\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/cachingrouter.php(36): OC\\\\Memcache\\\\Redis->hasKey('localhost#\\\/ownc...')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(42): OC\\\\Route\\\\CachingRouter->generate('settings_help', Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/helper.php(112): OC\\\\URLGenerator->linkToRoute('settings_help', Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/app.php(422): OC_Helper::linkToRoute('settings_help')\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(68): OC_App::getSettingsNavigation()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('user', 'files')\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/index.php(148): OC\\\\Template\\\\Base->printPage()\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#10 [internal function]: __lambda_func(Array)\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_38', Array)\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(791): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/redis.php\",\"Line\":68}","level":4,"time":"2015-05-29T11:55:52+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/"}
{"reqId":"871681c20fd8856330be2bd4be328dad","remoteAddr":"127.0.0.1","app":"no app in context","message":"CSRF check failed","level":0,"time":"2015-05-29T11:55:53+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files_sharing\/api\/externalShares"}
```

@LukasReschke @butonic @icewind1991

**Comment by LukasReschke** [comment]
> Maybe I should manually disable redis in config.php if I don't want to use it ?
> (some people might have the redis module enabled for other apps but do not want to use it for OC)

With 8.1 this will be opt-in, that said I have not much clue about our redis integration :see_no_evil:

**Comment by PVince81** [comment]
Since 8.1 the redis config / detection was improved, closing
