### ISSUE TITLE
Fatal error after configuring LDAP via occ to a server that isn't up

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16695]
-
### Steps to reproduce

1. Install 8.1 
2. Enable and configure ldap via occ - in my case the LDAP I configured was on a system that was not reachable
3. From the UI, navigate to the users page

### Expected behaviour

The UI users page is displayed

### Actual behaviour

The UI session exits with a fatal error message.  This is in the server log file:

```

{"reqId":"wTcZ0sjJ2py6yZZT+iy4","remoteAddr":"172.18.0.165","app":"index","message":"Exception: {\"Exception\":\"OC\\\\ServerNotAvailableException\",\"Message\":\"Lost connection to LDAP server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(259): OCA\\\\user_ldap\\\\lib\\\\LDAP->postFunctionCall()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(42): OCA\\\\user_ldap\\\\lib\\\\LDAP->invokeLDAPMethod('bind', Resource id #35, 'cn=admin,dc=own...', 'owncloud123')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(605): OCA\\\\user_ldap\\\\lib\\\\LDAP->bind(Resource id #35, 'cn=admin,dc=own...', 'owncloud123')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(537): OCA\\\\user_ldap\\\\lib\\\\Connection->bind()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(156): OCA\\\\user_ldap\\\\lib\\\\Connection->establishConnection()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(164): OCA\\\\user_ldap\\\\lib\\\\Connection->init()\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(729): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(877): OCA\\\\user_ldap\\\\lib\\\\Access->executeSearch('(&(|(cn=aggrega...', Array, Array, '500', NULL)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(690): OCA\\\\user_ldap\\\\lib\\\\Access->search('(&(|(cn=aggrega...', Array, Array, '500', NULL)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(633): OCA\\\\user_ldap\\\\lib\\\\Access->searchGroups('(&(|(cn=aggrega...', Array, '500', NULL)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/group_ldap.php(649): OCA\\\\user_ldap\\\\lib\\\\Access->fetchListOfGroups('(&(|(cn=aggrega...', Array, '500', NULL)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/group_ldap.php(689): OCA\\\\user_ldap\\\\GROUP_LDAP->getGroupsChunk('', '500', NULL)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/group\\\/manager.php(178): OCA\\\\user_ldap\\\\GROUP_LDAP->getGroups('', NULL, NULL)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/group\\\/metadata.php(185): OC\\\\Group\\\\Manager->search('')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/group\\\/metadata.php(95): OC\\\\Group\\\\MetaData->getGroups('')\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/settings\\\/users.php(46): OC\\\\Group\\\\MetaData->get()\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#17 [internal function]: __lambda_func(Array)\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func('?lambda_3', Array)\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(864): OC\\\\Route\\\\Router->match('\\\/settings\\\/users')\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php\",\"Line\":289}","level":4,"time":"2015-06-02T18:34:52+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/users"}


```

![p352](https://cloud.githubusercontent.com/assets/8480343/7943844/390f2e14-0935-11e5-90a9-2c9d5fc91d38.PNG)

### Server 1 Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-02T03:08:51+00:00 1acdef5e347e368ca99014084e30c9b69f1df181

**Comment by karlitschek** [comment]
@blizzz

**Comment by DeepDiver1975** [comment]
This works as designed from my understanding - as soon as an configured LDAP server is not reachable - we will bail out. Otherwise we will run into these known error scenarios where user folders are being generated and so on.

No LDAP is like No database -> No cloud

**Comment by jnfrmarks** [comment]
I would think that ownCloud is still usable in this case for local users.  

Based on the won't fix label, I'm going to close this.

**Comment by DeepDiver1975** [comment]
> I would think that ownCloud is still usable in this case for local users.

given the current architecture this is no possible
