### ISSUE TITLE
SMB files disappear from OC file list after deleting without permission

### ISSUE THREAD

**Issue by My1** [owncloud/core#16741]
### Steps to reproduce
1. have an SMB folder/file without delete permissions 
2. delete it

### Expected behaviour
error -> "you have no permissions"
file stays in list of OC and on SMB Server

### Actual behaviour
no error, files disappears from OC (not okay)
but stays on server (okay)

### Server configuration
**Operating system**:
openSUSE 13.2
**Web server:**
XAMPP for Linux
**Database:**
MySQL
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
8.0.3
**Updated from an older ownCloud or fresh install:**
fresh
**List of activated apps:**
file lock, ext storage, ldap user/group backend, updater
**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
<?php
$CONFIG = array (
  'instanceid' => 'oc2pfl40i5q5',
  'passwordsalt' => 'HIDDEN',
  'secret' => 'HIDDEN',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '192.168.69.2',
  ),
  'datadirectory' => '/opt/lampp/htdocs/owncloud/data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'HIDDEN',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 0,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb with OC login
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

Active Directory (with LDAP)

#### LDAP configuration (delete this part if not used)

```
"user_ldap";"cleanUpJobOffset";"0"
"user_ldap";"enabled";"yes"
"user_ldap";"installed_version";"0.5.0"
"user_ldap";"s01has_memberof_filter_support";"1"
"user_ldap";"s01home_folder_naming_rule";
"user_ldap";"s01last_jpegPhoto_lookup";"0"
"user_ldap";"s01ldap_agent_password";"eFRyZW11bTU="
"user_ldap";"s01ldap_attributes_for_group_search";
"user_ldap";"s01ldap_attributes_for_user_search";
"user_ldap";"s01ldap_backup_host";
"user_ldap";"s01ldap_backup_port";
"user_ldap";"s01ldap_base";"DC=bbw-azubi,DC=de"
"user_ldap";"s01ldap_base_groups";"DC=bbw-azubi,DC=de"
"user_ldap";"s01ldap_base_users";"DC=bbw-azubi,DC=de"
"user_ldap";"s01ldap_cache_ttl";"600"
"user_ldap";"s01ldap_configuration_active";"1"
"user_ldap";"s01ldap_display_name";"displayname"
"user_ldap";"s01ldap_dn";"CN=PJ Admin,OU=Operatoren,OU=Benutzer,DC=bbw-azubi,DC=de"
"user_ldap";"s01ldap_email_attr";"mail"
"user_ldap";"s01ldap_experienced_admin";"0"
"user_ldap";"s01ldap_expert_username_attr";"sAMAccountName"
"user_ldap";"s01ldap_expert_uuid_group_attr";
"user_ldap";"s01ldap_expert_uuid_user_attr";
"user_ldap";"s01ldap_group_display_name";"cn"
"user_ldap";"s01ldap_group_filter";"(&(|(objectclass=top))(|(cn=Ausbilder FI)(cn=Auszubildende)))"
"user_ldap";"s01ldap_group_filter_mode";"0"
"user_ldap";"s01ldap_group_member_assoc_attribute";"member"
"user_ldap";"s01ldap_groupfilter_groups";"Ausbilder FI
Auszubildende"
"user_ldap";"s01ldap_groupfilter_objectclass";"top"
"user_ldap";"s01ldap_host";"172.16.4.1"
"user_ldap";"s01ldap_login_filter";"(&(&(|(objectclass=organizationalPerson)(objectclass=person)(objectclass=top)(objectclass=user))(|(memberof=CN=2012 FI,OU=2012,OU=- Gruppen -,OU=Auszubildende,OU=Benutzer,DC=bbw-azubi,DC=de)(memberof=CN=2013 FI,OU=2013,OU=- Gruppen -,OU=Auszubildende,OU=Benutzer,DC=bbw-azubi,DC=de)(memberof=CN=2014 FI,OU=2014,OU=- Gruppen -,OU=Auszubildende,OU=Benutzer,DC=bbw-azubi,DC=de)))(|(samaccountname=%uid)(|(sAMAccountName=%uid)(userPrincipalName=%uid))))"
"user_ldap";"s01ldap_login_filter_mode";"0"
"user_ldap";"s01ldap_loginfilter_attributes";"userPrincipalName"
"user_ldap";"s01ldap_loginfilter_email";"0"
"user_ldap";"s01ldap_loginfilter_username";"1"
"user_ldap";"s01ldap_nested_groups";"1"
"user_ldap";"s01ldap_nocase";"1"
"user_ldap";"s01ldap_override_main_server";"0"
"user_ldap";"s01ldap_paging_size";"500"
"user_ldap";"s01ldap_port";"389"
"user_ldap";"s01ldap_quota_attr";
"user_ldap";"s01ldap_quota_def";
"user_ldap";"s01ldap_tls";"0"
"user_ldap";"s01ldap_turn_off_cert_check";"0"
"user_ldap";"s01ldap_user_filter_mode";"0"
"user_ldap";"s01ldap_userfilter_groups";"Alle FI
Ausbilder FI"
"user_ldap";"s01ldap_userfilter_objectclass";"user"
"user_ldap";"s01ldap_userlist_filter";"(&(|(objectclass=user))(|(memberof=CN=Alle FI,OU=- Gruppen -,OU=Auszubildende,OU=Benutzer,DC=bbw-azubi,DC=de)(memberof=CN=Ausbilder FI,OU=- Gruppen -,OU=Mitarbeiter,OU=Benutzer,DC=bbw-azubi,DC=de)))"
"user_ldap";"types";"authentication"
```

### Client configuration
**Browser:**
Browser or Webdav via Windows Explorer
**Operating system:**
Win7x64
#### ownCloud log
```
Error 	core 		2015-06-04T08:44:25+00:00
Error 	core 		2015-06-04T08:44:25+00:00
Debug 	core 	OC\Tags::__construct, tags: Array ( ) 	2015-06-04T08:44:06+00:00
Error	core		2015-06-04T08:44:30+00:00
Error	core		2015-06-04T08:44:29+00:00
Error	core		2015-06-04T08:44:29+00:00
Error	core		2015-06-04T08:44:28+00:00
Error	core		2015-06-04T08:44:28+00:00
Error	core		2015-06-04T08:44:28+00:00
Error	core		2015-06-04T08:44:28+00:00
Error	core		2015-06-04T08:44:28+00:00
Error	core		2015-06-04T08:44:28+00:00
Error	core		2015-06-04T08:44:27+00:00
Error	core		2015-06-04T08:44:28+00:00
Error	core		2015-06-04T08:44:27+00:00
Error	core		2015-06-04T08:44:27+00:00
Error	core		2015-06-04T08:44:27+00:00
Error	core		2015-06-04T08:44:27+00:00
Fatal	files_external	Exception: {"Message":"","Code":0,"Trace":"#0 \/opt\/lampp\/htdocs\/owncloud\/apps\/files_external\/lib\/config.php(456): OC\\Files\\Storage\\SMB_OC->__construct(Array)\n#1 \/opt\/lampp\/htdocs\/owncloud\/apps\/files_external\/lib\/config.php(392): OC_Mount_Config::getBackendStatus('\\OC\\Files\\Stora...', Array, false)\n#2 \/opt\/lampp\/htdocs\/owncloud\/apps\/files_external\/settings.php(47): OC_Mount_Config::getSystemMountPoints()\n#3 \/opt\/lampp\/htdocs\/owncloud\/lib\/private\/app.php(720): include('\/opt\/lampp\/htdo...')\n#4 \/opt\/lampp\/htdocs\/owncloud\/settings\/admin.php(93): OC_App::getForms('admin')\n#5 \/opt\/lampp\/htdocs\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/opt\/lampp\/htdo...')\n#6 [internal function]: __lambda_func(Array)\n#7 \/opt\/lampp\/htdocs\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('?lambda_6', Array)\n#8 \/opt\/lampp\/htdocs\/owncloud\/lib\/base.php(782): OC\\Route\\Router->match('\/settings\/admin')\n#9 \/opt\/lampp\/htdocs\/owncloud\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/opt\/lampp\/htdocs\/owncloud\/apps\/files_external\/lib\/smb_oc.php","Line":47}	2015-06-04T08:44:25+00:00
Fatal	files_external	Exception: {"Message":"","Code":0,"Trace":"#0 \/opt\/lampp\/htdocs\/owncloud\/apps\/files_external\/lib\/config.php(456): OC\\Files\\Storage\\SMB_OC->__construct(Array)\n#1 \/opt\/lampp\/htdocs\/owncloud\/apps\/files_external\/lib\/config.php(392): OC_Mount_Config::getBackendStatus('\\OC\\Files\\Stora...', Array, false)\n#2 \/opt\/lampp\/htdocs\/owncloud\/apps\/files_external\/settings.php(47): OC_Mount_Config::getSystemMountPoints()\n#3 \/opt\/lampp\/htdocs\/owncloud\/lib\/private\/app.php(720): include('\/opt\/lampp\/htdo...')\n#4 \/opt\/lampp\/htdocs\/owncloud\/settings\/admin.php(93): OC_App::getForms('admin')\n#5 \/opt\/lampp\/htdocs\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/opt\/lampp\/htdo...')\n#6 [internal function]: __lambda_func(Array)\n#7 \/opt\/lampp\/htdocs\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('?lambda_6', Array)\n#8 \/opt\/lampp\/htdocs\/owncloud\/lib\/base.php(782): OC\\Route\\Router->match('\/settings\/admin')\n#9 \/opt\/lampp\/htdocs\/owncloud\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/opt\/lampp\/htdocs\/owncloud\/apps\/files_external\/lib\/smb_oc.php","Line":47}	2015-06-04T08:44:25+00:00
Error	core		2015-06-04T08:44:25+00:00
Error	core		2015-06-04T08:44:25+00:00
Debug	core	OC\Tags::__construct, tags: Array ( ) 	2015-06-04T08:44:06+00:00
Error	core		2015-06-04T08:44:25+00:00
Debug	core	OC\Tags::__construct, tags: Array ( ) 	2015-06-04T08:44:06+00:00
Error	PHP	NT_STATUS_ACCESS_DENIED deleting remote file \Klasse\2012\FI\TestFI\test für zugriff params(-d 0 '//172.16.4.3/Berufsschule' -c 'del "Klasse\2012\FI\TestFI\test für zugriff extern.docx"') at /opt/lampp/htdocs/owncloud/apps/files_external/3rdparty/smb4php/smb.php#201	2015-06-04T08:44:01+00:00
Debug	core	OC\Tags::__construct, tags: Array ( ) 	2015-06-04T08:43:50+00:00
Debug	core	OC\Tags::__construct, tags: Array ( ) 	2015-06-04T08:43:46+00:00
Debug	core	OC\Tags::__construct, tags: Array ( ) 	2015-06-04T08:43:43+00:00
Debug	core	OC\Tags::__construct, tags: Array ( ) 	2015-06-04T08:43:40+00:00
Debug	core	OC\Tags::__construct, tags: Array ( ) 
```

**Comment by LukasReschke** [comment]
@icewind1991

**Comment by My1** [comment]
No edit button?
Then I'll write it here. 
For a further clarification. Create the folder or file on your smb server or some client that full smb access like Windows Explorer and mod its permissions there. 
Then try to delete it via the oc Web interface it's not there anymore even in Webdav. Deleting via webdav needs to be tested (I could do that tomorrow...

**Comment by PVince81** [comment]
There is an edit button, the little pencil :smile: 

Does the folder reappear if you refresh the page ?
I'd think it's only a display issue where it believes that deletion was successful and removes if from the UI, while it was not.

If it doesn't reappear after refresh then this problem is more serious than just display.

**Comment by My1** [comment]
On mobile the only pencil is the one at the top left which creates a new issue. 
The files stay out of the list after a Refresh, someone pointed out that it may be the cached file list..

**Comment by PVince81** [comment]
Ah yes, the github mobile web interface is lacking...

**Comment by PVince81** [comment]
Works for me in 8.1, I get "cannot delete folder 'sub'". (this is Samba on Linux)
Same on 8.0.3.

What I did:
1. Mount SMB folder under "/smb"
2. Create a folder "/smb/perms/sub" in the web UI
3. On the Samba server, `chmod a-w perms`
4. In the web UI, delete "sub"

I get "cannot delete" and the folder stays.
This is on openSUSE Factory x86_64 with samba-4.2.1-2.1.x86_64

**Comment by PVince81** [comment]
Maybe if the SMB server is on Windows, the server returns a different response and maybe it isn't detected properly as a failure.

**Comment by My1** [comment]
But if you say mounting in /smb are you mounting on the server and only associating int storage or are you reqlly saying to oc, get the smb share with that data and so on. 
But the logs do say that the delete couldn't be made (last error)

**Comment by PVince81** [comment]
Sorry, to clarify:
1. Enable external storage app
2. Go to the admin page, external storage section
3. Type "smb" as mount point name
4. Select "SMB" as mount type
5. Enter credentials and share name
6. etc

This is not a Linux system mount.

**Comment by My1** [comment]
Hm. But to be honest your rights in linux aee much more simple. In my case we may create files but we may neither change nor delete them

**Comment by PVince81** [comment]
Hmm not sure. @jmaciasportela are you able to reproduce this issue with a SMB mount that has more complex permissions ?

**Comment by jmaciasportela** [comment]
Sorry @PVince81 OOTO until next week, maybe @davitol

**Comment by davitol** [comment]
@PVince81 Same behaviour as you got. I cannot reproduce the issue. I got the message: 'cannot delete ...'

**Comment by PVince81** [comment]
@My1 if the problem still appears for you in 8.1.3 we'll need more detailed information about your SMB server and permissions

**Comment by My1** [comment]
Well I am not working in the environment so I cannot gather much more info for that.

I might try something with my Raspberry pi someday but it may take some time as my pi isnt really configured and the Pi 1 B-Model isnt really good enough for OC and I dont have a linux machine nearby.

**Comment by PVince81** [comment]
Please try again with 8.2.2, if the problem persists, please reopen. Thanks.
