### ISSUE TITLE
Upgrade from 8.0.3 to 8.0.4 failed on database migration

### ISSUE THREAD

**Issue by wiget** [owncloud/core#16779]
Error message:

An exception occurred while executing 'CREATE INDEX 3w6bsych61q95 ON appconfig_bm64j7fs04lqm ("appid")': SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "3" LINE 1: CREATE INDEX 3w6bsych61q95 ON appconfig_bm64j7fs04lqm ("appi... ^

Ubuntu 15.04,

 grep dbtype /var/www/owncloud/config/config.php 
  'dbtype' => 'pgsql',

PostgreSQL 9.4

**Comment by wiget** [comment]
Different errors on different runs:
```
root@localhost:/var/www/owncloud# sudo -u www-data php ./occ upgrade
Turned on maintenance mode
An exception occurred while executing 'CREATE UNIQUE INDEX 20uu42nrknltl ON file_map_n9huh2mbjcxsr ("physic_path_hash")':

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "20"
LINE 1: CREATE UNIQUE INDEX 20uu42nrknltl ON file_map_n9huh2mbjcxsr ...
                            ^
Turned off maintenance mode
Update failed
root@localhost:/var/www/owncloud# sudo -u www-data php ./occ upgrade
Turned on maintenance mode
An exception occurred while executing 'CREATE INDEX 4wb9swud1o0sa ON appconfig_q64l0awuj7b3h ("appid")':

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "4"
LINE 1: CREATE INDEX 4wb9swud1o0sa ON appconfig_q64l0awuj7b3h ("appi...
                     ^
Turned off maintenance mode
Update failed
root@localhost:/var/www/owncloud# sudo -u www-data php ./occ upgrade
Turned on maintenance mode
An exception occurred while executing 'CREATE INDEX 3xjpl3x3es0wy ON share_ebvjx4rm1p9uv ("file_source")':

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "3"
LINE 1: CREATE INDEX 3xjpl3x3es0wy ON share_ebvjx4rm1p9uv ("file_sou...
                     ^
Turned off maintenance mode
Update failed

```

**Comment by jperville** [comment]
Confirmed here with postgresql also. The generated index names are probably illegal.

**Comment by DeepDiver1975** [comment]
Hmmm .... upstream issue in doctrine? @vicdeo can I ask you to please have a look? Thx

**Comment by jperville** [comment]
This one is critical because the package server at download.opensuse.org only contains the last version of the package (8.0.4-0), making it impossible to revert to old version unless the files have been kept in some kind of cache.

**Comment by wiget** [comment]
Yes, know I have unworking service. :cry:

**Comment by DeepDiver1975** [comment]
> Yes, know I have unworking service. :cry:

You can run the upgrade command with the option --skip-migration-test

**Comment by DeepDiver1975** [comment]
@wiget @jperville what's your database table prefix (config setting 'dbtableprefix')?

I assume this is empty which results in this error based on this code:

```php

				$indexName = $this->config->getSystemValue('dbtableprefix', 'oc_') . $this->random->generate(13, ISecureRandom::CHAR_LOWER . ISecureRandom::CHAR_DIGITS);

**Comment by DeepDiver1975** [comment]
@VicDeo no upstream issue - we shall add a dummy prefix to the index name in case no dbtableprefix is set

**Comment by jperville** [comment]
@DeepDiver1975 Using empty string as dbtableprefix (according to grep).

**Comment by wiget** [comment]
@DeepDiver1975 empty.
```
'dbtableprefix' => '',
```

**Comment by wiget** [comment]
As experiment I removed `dbtableprefix` from config.php and got this:
```
# sudo -u www-data php -f /var/www/owncloud/occ upgrade
An unhandled exception has been thrown:
exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "oc_appconfig" does not exist
LINE 1: SELECT "configvalue", "appid" FROM "oc_appconfig" WHERE "con...
                                           ^' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(830): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 /var/www/owncloud/lib/private/db/connection.php(113): Doctrine\DBAL\Connection->executeQuery('SELECT "configv...', Array, Array, NULL)
#3 /var/www/owncloud/lib/private/appconfig.php(259): OC\DB\Connection->executeQuery('SELECT `configv...', Array)
#4 /var/www/owncloud/lib/private/app.php(219): OC\AppConfig->getValues(false, 'enabled')
#5 /var/www/owncloud/lib/private/app.php(71): OC_App::getEnabledApps()
#6 /var/www/owncloud/lib/base.php(551): OC_App::loadApps(Array)
#7 /var/www/owncloud/lib/base.php(1039): OC::init()
#8 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#9 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#10 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "oc_appconfig" does not exist
LINE 1: SELECT "configvalue", "appid" FROM "oc_appconfig" WHERE "con...
                                           ^' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(830): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#1 /var/www/owncloud/lib/private/db/connection.php(113): Doctrine\DBAL\Connection->executeQuery('SELECT "configv...', Array, Array, NULL)
#2 /var/www/owncloud/lib/private/appconfig.php(259): OC\DB\Connection->executeQuery('SELECT `configv...', Array)
#3 /var/www/owncloud/lib/private/app.php(219): OC\AppConfig->getValues(false, 'enabled')
#4 /var/www/owncloud/lib/private/app.php(71): OC_App::getEnabledApps()
#5 /var/www/owncloud/lib/base.php(551): OC_App::loadApps(Array)
#6 /var/www/owncloud/lib/base.php(1039): OC::init()
#7 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#8 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#9 {main}

Next exception 'Doctrine\DBAL\Exception\TableNotFoundException' with message 'An exception occurred while executing 'SELECT "configvalue", "appid" FROM "oc_appconfig" WHERE "configkey" = ?' with params ["enabled"]:

SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "oc_appconfig" does not exist
LINE 1: SELECT "configvalue", "appid" FROM "oc_appconfig" WHERE "con...
                                           ^' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:75
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT "configv...', Array)
#2 /var/www/owncloud/lib/private/db/connection.php(113): Doctrine\DBAL\Connection->executeQuery('SELECT "configv...', Array, Array, NULL)
#3 /var/www/owncloud/lib/private/appconfig.php(259): OC\DB\Connection->executeQuery('SELECT `configv...', Array)
#4 /var/www/owncloud/lib/private/app.php(219): OC\AppConfig->getValues(false, 'enabled')
#5 /var/www/owncloud/lib/private/app.php(71): OC_App::getEnabledApps()
#6 /var/www/owncloud/lib/base.php(551): OC_App::loadApps(Array)
#7 /var/www/owncloud/lib/base.php(1039): OC::init()
#8 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#9 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#10 {main}
```

**Comment by DeepDiver1975** [comment]
> As experiment I removed dbtableprefix from config.php and got this:

the result is not that of an surprise - your db basically holds no owncloud tables anymore ... this is not the way to go

**Comment by VicDeo** [comment]
@wiget So the prefix was not empty?

**Comment by VicDeo** [comment]
@DeepDiver1975 Ouch! Adding a dummy prefix will reintroduce https://github.com/owncloud/core/issues/14916#issuecomment-103086291
I suggest to teach our random generator to generate characters starting with a-z characters instead.

**Comment by DeepDiver1975** [comment]
> $indexName = $this->config->getSystemValue('dbtableprefix', 'oc_') . $this->random->generate(13, ISecureRandom::CHAR_LOWER . ISecureRandom::CHAR_DIGITS);

@VicDeo this is possible if you remove  . ISecureRandom::CHAR_DIGITS

**Comment by VicDeo** [comment]
@wiget @jperville Can you test https://github.com/owncloud/core/pull/16807 ?

**Comment by wiget** [comment]
@VicDeo works for me.

**Comment by jperville** [comment]
Cannot try the patch right now sadly (need to use existing data from dump), but will keep in touch tomorrow. I got a feeling that using temporary index names that do not start with a digit will help a lot.

**Comment by wiget** [comment]
@VicDeo THX. You saved my live.
