### ISSUE TITLE
[Experimental files locking] Renaming a folder while uploading files on it is allowed.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16824]
### Steps to reproduce

1. Enable redis as cache system.
2. Enable experimental files locking.
3. Create a folder 'FOLDER'.
4. Login using chrome and firefox, have both opened and logged in.
5. Using firefox upload a big file ~500MiB.
6. Using chrome rename 'FOLDER' to 'RENAMEDFOLDER'

### Expected behaviour
You are not able to rename it, it should be locked and a message should appear.

### Actual behaviour
You can rename the folder in chrome and in firefox appears Internal server error and uploading ends.

Same situation uploading with chrome and renaming with firefox leads to have firefox ui freeze.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Experimental files locking.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
{"reqId":"gAy82d6p3pG8aNW35d\/k","remoteAddr":"10.40.40.45","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Lock\\\\LockedException\",\"Message\":\"files\\\/1a14e7bf2a1851ab9beca561877fe62d is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(651): OC\\\\Lock\\\\MemcacheLockingProvider->changeLock('files\\\/1a14e7bf2...', 2)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(571): OC\\\\Files\\\\Storage\\\\Common->changeLock('files\\\/FOLDER', 2, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(571): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->changeLock('files\\\/FOLDER', 2, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/private\\\/files\\\/view.php(1691): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->changeLock('files\\\/FOLDER', 2, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/private\\\/files\\\/view.php(646): OC\\\\Files\\\\View->changeLock('\\\/FOLDER', 2)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/apps\\\/files\\\/lib\\\/app.php(117): OC\\\\Files\\\\View->rename('\\\/FOLDER', '\\\/FOLDER234234')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/apps\\\/files\\\/ajax\\\/rename.php(40): OCA\\\\Files\\\\App->rename('\\\/', 'FOLDER', 'FOLDER234234')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func('?lambda_182', Array)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/base.php(850): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/index.php(40): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/private\\\/lock\\\/memcachelockingprovider.php\",\"Line\":121}","level":4,"time":"2015-06-09T08:53:37+00:00"}
{"reqId":"Qq8J+hEyXtJXihgtHMMg","remoteAddr":"10.40.40.45","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/apps\\\/files\\\/lib\\\/helper.php(45): OC_Helper::getStorageInfo('\\\/FOLDER')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/apps\\\/files\\\/ajax\\\/upload.php(104): OCA\\\\Files\\\\Helper::buildFileStorageStatistics('\\\/FOLDER')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#3 [internal function]: __lambda_func(Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func('?lambda_1065', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/base.php(850): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/index.php(40): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud_04-06-15\\\/lib\\\/private\\\/helper.php\",\"Line\":971}","level":4,"time":"2015-06-09T08:55:58+00:00"}
```

### Client configuration

**browser**
Chrome 41, Firefox

**Comment by PVince81** [comment]
Same problem as explained here: https://github.com/owncloud/core/issues/16769#issuecomment-109351205

The uploaded file hasn't reached the PHP code, this is not fixable except by changing the web UI to use PUT (which streams the file) instead of POST (for which PHP first saves into a temp file before passing it to ownCloud)

**Comment by PVince81** [comment]
The locking would only kick in at the time where PHP is passing the file to ownCloud.

If you use external storage, that phase might happen once the progress bar reached 100% in the web UI, which is then followed by a delay which is the time where ownCloud gets access to the file and uploads it to SFTP.

**Comment by PVince81** [comment]
Related ticket: use PUT instead of POST on upload: https://github.com/owncloud/core/issues/4380

**Comment by SergioBertolinSG** [comment]
OK, i'll use webdav then.

**Comment by SergioBertolinSG** [comment]
Using webdav to upload and chrome/firefox to rename, spinner keeps turning forever, after refreshing, folder isn't renamed.
Happening in chrome and firefox.

**Comment by PVince81** [comment]
Does the network console show a 500 entry ?
The error message was supposed to be displayed in the web UI.

**Comment by SergioBertolinSG** [comment]
There are no errors in the UI or in the console.

In the log there is a fatal one:
```
Exception: {"Exception":"OCP\\Lock\\LockedException","Message":"files\/a977fb14559b0bc52b9066472c035c94 is locked","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud_04-06-15\/lib\/private\/files\/storage\/common.php(651): OC\\Lock\\MemcacheLockingProvider->changeLock('files\/a977fb145...', 2)\n#1 \/var\/www\/html\/owncloud_04-06-15\/lib\/private\/files\/storage\/wrapper\/wrapper.php(571): OC\\Files\\Storage\\Common->changeLock('files\/CARPETA', 2, Object(OC\\Lock\\MemcacheLockingProvider))\n#2 \/var\/www\/html\/owncloud_04-06-15\/lib\/private\/files\/storage\/wrapper\/wrapper.php(571): OC\\Files\\Storage\\Wrapper\\Wrapper->changeLock('files\/CARPETA', 2, Object(OC\\Lock\\MemcacheLockingProvider))\n#3 \/var\/www\/html\/owncloud_04-06-15\/lib\/private\/files\/view.php(1691): OC\\Files\\Storage\\Wrapper\\Wrapper->changeLock('files\/CARPETA', 2, Object(OC\\Lock\\MemcacheLockingProvider))\n#4 \/var\/www\/html\/owncloud_04-06-15\/lib\/private\/files\/view.php(646): OC\\Files\\View->changeLock('\/CARPETA', 2)\n#5 \/var\/www\/html\/owncloud_04-06-15\/apps\/files\/lib\/app.php(117): OC\\Files\\View->rename('\/CARPETA', '\/ADIOS')\n#6 \/var\/www\/html\/owncloud_04-06-15\/apps\/files\/ajax\/rename.php(40): OCA\\Files\\App->rename('\/', 'CARPETA', 'ADIOS')\n#7 \/var\/www\/html\/owncloud_04-06-15\/lib\/private\/route\/route.php(153) : runtime-created function(1): require_once('\/var\/www\/html\/o...')\n#8 [internal function]: __lambda_func(Array)\n#9 \/var\/www\/html\/owncloud_04-06-15\/lib\/private\/route\/router.php(274): call_user_func('?lambda_1291', Array)\n#10 \/var\/www\/html\/owncloud_04-06-15\/lib\/base.php(850): OC\\Route\\Router->match('\/apps\/files\/aja...')\n#11 \/var\/www\/html\/owncloud_04-06-15\/index.php(40): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/html\/owncloud_04-06-15\/lib\/private\/lock\/memcachelockingprovider.php","Line":121}
```

**Comment by PVince81** [comment]
Okay thanks. Then maybe something has changed recently.
I'll try and find out why the exception isn't passed to the UI.

**Comment by SergioBertolinSG** [comment]
Retested with last changes.
Upload by webdav + rename by chrome = error message saying: 
files/a977fb14559b0bc52b9066472c035c94 is locked
Ok.

**Comment by SergioBertolinSG** [comment]
Since web ui upload can't be solved now until https://github.com/owncloud/core/issues/12353 is done  moving to 8.2.

**Comment by PVince81** [comment]
Since this worked, closing.

For the web UI to use PUT, see https://github.com/owncloud/core/issues/4380
