### ISSUE TITLE
Exceptions in server log running test with files_locking enabled

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16843]
### Steps to reproduce

1. Install 8.1 with encryption and files_locking enabled
2. Run new smashbox test test_dirDepthUpload.py which is currently in the dir-depth-rb-2 branch

### Expected behaviour

Test passes with no errors in the server log

### Actual behaviour

I see the following errors in the server log (this is from two different runs):

```

{"reqId":"jUjdv\/nlXcRqucE8RdOi","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/f9213687e3cf4914be130096c259d91f is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/TE...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:18:50+00:00"}
{"reqId":"F0sVdw+lj6qUZ9waVnat","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:54+00:00"}
{"reqId":"WxIlFdgxSYKY8xbj2ev3","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:54+00:00"}
{"reqId":"L9bQ\/sl8Q2Y9gCfhjVai","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:54+00:00"}
{"reqId":"gGDQRWBef6DhmQqROExL","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:54+00:00"}
{"reqId":"Lhi+KR7vMi82tUwyeSC9","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:54+00:00"}
{"reqId":"1NXvAtZnGxfSsvjfeZOV","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:56+00:00"}
{"reqId":"eYdv8unIGaznwa776Y4F","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:58+00:00"}


```

and from a second run:

```

{"reqId":"jlp1GD1dygwOO6VWcfal","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/af523733991f665d733e29a73f3391b0 is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"UvdQLPMR+dpdcj9Mm4CY","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/e003c124b615e6ba30cd568ee0a569e9 is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"KD2GsYB8XOFnOLf5yrqR","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/e6b9a9846c58166a2d6c6fa94d8ad149 is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"t+DVHrjMUu7Ad60RBU03","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/beb747696d9234440a421a43a4b765c7 is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"Yaf7TtZWXhrjJVhWPTOh","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/aeb2519251e150a57ea0b9d24a3b109a is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"OGBthQadmfwFaHNqMd7v","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/30bf02a6a0e939e834186cfbcc274dd7 is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"al5zGraEq\/LQNrqPMNSp","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/b48e7079ffcc4c5335db7479cc5a465e is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:55+00:00"}
{"reqId":"qzEEm80al3js+2R\/I8fR","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/c7cb567e5e3754803c3bd08b809095cc is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:55+00:00"}
{"reqId":"w\/LhncUWYmgcoxNry+Lm","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:56+00:00"}
{"reqId":"w5s\/NwMJr\/C\/mx2LMl5B","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:56+00:00"}
{"reqId":"dJQmd02ZG\/yruWu83vrM","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:56+00:00"}
{"reqId":"\/wRhEk8oSb\/Od2eyXl7Y","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:56+00:00"}
{"reqId":"cRTafru0+g+ml8eAdlGp","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:57+00:00"}
{"reqId":"x\/q+wHcdg4EPzxyAUtW+","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:57+00:00"}
{"reqId":"AfAS\/3ogCPceVPUMIhJV","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:57+00:00"}

```

I could not reproduce the error when running the same test with files_locking disabled.

### Server 1 Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-08T03:08:20+00:00 35421487610462b12e3600954f23a777c54abee3

**Comment by PVince81** [comment]
files_locking the old app or the new files locking ? Please be precise.
We probably should really rename the new locking...

**Comment by PVince81** [comment]
How about "redis file locking" ?

**Comment by jnfrmarks** [comment]
New redis locking in core.

I don't like "redis file locking" because it's possible to configure something other than redis.

@MTRichards 

I think we need some marketing speak here on naming  the new file locking approach.  I agree that we should come up with another name before we ship 8.1

**Comment by MTRichards** [comment]
There are two different levels, one higher the other lower. 
The old one was file system locking, if the filesystem supported locks.
The new one is transaction or application level file locking.

So perhaps we call them that?

**Comment by PVince81** [comment]
The is a slight chance that some of the concurrency from the smashbox tests run into a temporary locking situation. Not sure how to gracefully recover from that. (@nickvergessen saw similar cases).

However one strange error it this one: `Module 'redis' already loaded at Unknown#0`

**Comment by DeepDiver1975** [comment]
> However one strange error it this one: Module 'redis' already loaded at Unknown#0

I assume the load command for the redis module is simply duplicated in the inis somewhere - should have no sideeffects

**Comment by nickvergessen** [comment]
The exception that is caught in that place is the following:
```
exception 'OCP\Lock\LockedException' with message 'files/6399c111f0b8f16e79000d452563a5c7 is locked' in /home/nickv/ownCloud/Smashbox/master/lib/private/lock/memcachelockingprovider.php:70
Stack trace:
#0 /home/nickv/ownCloud/Smashbox/master/lib/private/files/storage/common.php(633): OC\Lock\MemcacheLockingProvider->acquireLock('files/home::tes...', 1)
#1 /home/nickv/ownCloud/Smashbox/master/lib/private/files/storage/wrapper/wrapper.php(553): OC\Files\Storage\Common->acquireLock('files_encryptio...', 1, Object(OC\Lock\MemcacheLockingProvider))
#2 /home/nickv/ownCloud/Smashbox/master/lib/private/files/storage/wrapper/wrapper.php(553): OC\Files\Storage\Wrapper\Wrapper->acquireLock('files_encryptio...', 1, Object(OC\Lock\MemcacheLockingProvider))
#3 /home/nickv/ownCloud/Smashbox/master/lib/private/files/view.php(1674): OC\Files\Storage\Wrapper\Wrapper->acquireLock('files_encryptio...', 1, Object(OC\Lock\MemcacheLockingProvider))
#4 /home/nickv/ownCloud/Smashbox/master/lib/private/files/view.php(1724): OC\Files\View->lockPath('/test1/files_en...', 1)
#5 /home/nickv/ownCloud/Smashbox/master/lib/private/files/view.php(975): OC\Files\View->lockFile('/test1/files_en...', 1)
#6 /home/nickv/ownCloud/Smashbox/master/lib/private/files/view.php(243): OC\Files\View->basicOperation('mkdir', '/test1/files_en...', Array)
#7 /home/nickv/ownCloud/Smashbox/master/lib/private/encryption/keys/storage.php(312): OC\Files\View->mkdir('/test1/files_en...')
#8 /home/nickv/ownCloud/Smashbox/master/lib/private/encryption/keys/storage.php(203): OC\Encryption\Keys\Storage->keySetPreparation('/test1/files_en...')
#9 /home/nickv/ownCloud/Smashbox/master/lib/private/encryption/keys/storage.php(109): OC\Encryption\Keys\Storage->setKey('/test1/files_en...', 's\xB8\x16\xEF\xF6m\xB6\x03B\xE4\x9C\"\xB4a\xD4...')
#10 /home/nickv/ownCloud/Smashbox/master/apps/encryption/lib/keymanager.php(269): OC\Encryption\Keys\Storage->setFileKey('/test1/files/lo...', 'fileKey', 's\xB8\x16\xEF\xF6m\xB6\x03B\xE4\x9C\"\xB4a\xD4...', 'OC_DEFAULT_MODU...')
#11 /home/nickv/ownCloud/Smashbox/master/apps/encryption/lib/keymanager.php(279): OCA\Encryption\KeyManager->setFileKey('/test1/files/lo...', 's\xB8\x16\xEF\xF6m\xB6\x03B\xE4\x9C\"\xB4a\xD4...')
#12 /home/nickv/ownCloud/Smashbox/master/apps/encryption/lib/crypto/encryption.php(203): OCA\Encryption\KeyManager->setAllFileKeys('/test1/files/lo...', Array)
#13 /home/nickv/ownCloud/Smashbox/master/lib/private/files/stream/encryption.php(394): OCA\Encryption\Crypto\Encryption->end('/test1/files/lo...')
#14 [internal function]: OC\Files\Stream\Encryption->stream_close()
#15 /home/nickv/ownCloud/Smashbox/master/lib/private/connector/sabre/file.php(136): fclose(Resource id #47)
#16 /home/nickv/ownCloud/Smashbox/master/lib/private/connector/sabre/directory.php(111): OC\Connector\Sabre\File->put(Resource id #23)
#17 /home/nickv/ownCloud/Smashbox/master/3rdparty/sabre/dav/lib/DAV/Server.php(1053): OC\Connector\Sabre\Directory->createFile('TEST_FILE_USER_...', Resource id #23)
#18 /home/nickv/ownCloud/Smashbox/master/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(513): Sabre\DAV\Server->createFile('localShareDir/T...', Resource id #23, NULL)
#19 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#20 /home/nickv/ownCloud/Smashbox/master/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#21 /home/nickv/ownCloud/Smashbox/master/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)
#22 /home/nickv/ownCloud/Smashbox/master/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#23 /home/nickv/ownCloud/Smashbox/master/apps/files/appinfo/remote.php(83): Sabre\DAV\Server->exec()
#24 /home/nickv/ownCloud/Smashbox/master/remote.php(84): require_once('/home/nickv/own...')
#25 {main}
```

So the problem is that the directory for encryption keys can not be created,
because it is locked by :question: :grey_question: :question: 

This is somewhat problematic after a short discussion with @schiesbn and @PVince81 we came to the conclusion, that encryption directories should never be locked, because they can not be touched, because the original file is already locked. So I will try to come up with a short PR about this.
