### ISSUE TITLE
[Experimental files locking] Mounting of SFTP folder fails.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16854]
### Steps to reproduce

1. Enable redis as cache system.
2. Enable experimental files locking.
3. Enable external storage app.
4. Mount a SFTP folder.

### Expected behaviour
Folder is mounted.

### Actual behaviour
Folder can't be mounted.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Experimental files locking.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Trying to use SFTP.

**Are you using encryption:** 
No.

**Logs**
```
  Exception: {"Exception":"Exception","Message":"Login failed","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud_10-06-15\/apps\/files_external\/lib\/sftp.php(129): OC\\Files\\Storage\\SFTP->getConnection()\n#1 \/var\/www\/html\/owncloud_10-06-15\/apps\/files_external\/lib\/config.php(497): OC\\Files\\Storage\\SFTP->test(false)\n#2 \/var\/www\/html\/owncloud_10-06-15\/apps\/files_external\/controller\/storagescontroller.php(123): OC_Mount_Config::getBackendStatus('\\OC\\Files\\Stora...', Array, false)\n#3 \/var\/www\/html\/owncloud_10-06-15\/apps\/files_external\/controller\/globalstoragescontroller.php(157): OCA\\Files_External\\Controller\\StoragesController->updateStorageStatus(Object(OCA\\Files_external\\Lib\\StorageConfig))\n#4 [internal function]: OCA\\Files_External\\Controller\\GlobalStoragesController->update(1, 'SFTP', '\\OC\\Files\\Stora...', Array, NULL, Array, Array, 100)\n#5 \/var\/www\/html\/owncloud_10-06-15\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#6 \/var\/www\/html\/owncloud_10-06-15\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'update')\n#7 \/var\/www\/html\/owncloud_10-06-15\/lib\/private\/appframework\/app.php(107): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'update')\n#8 \/var\/www\/html\/owncloud_10-06-15\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('GlobalStoragesC...', 'update', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#9 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#10 \/var\/www\/html\/owncloud_10-06-15\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#11 \/var\/www\/html\/owncloud_10-06-15\/lib\/base.php(867): OC\\Route\\Router->match('\/apps\/files_ext...')\n#12 \/var\/www\/html\/owncloud_10-06-15\/index.php(40): OC::handleRequest()\n#13 {main}","File":"\/var\/www\/html\/owncloud_10-06-15\/apps\/files_external\/lib\/sftp.php","Line":113}
```

### Client configuration

**browser**
Chrome 41, Firefox

**Comment by SergioBertolinSG** [comment]
Just a mistake, I had a white space in the login name, which reminds the needing of fixing this one:
https://github.com/owncloud/core/issues/16457
