### ISSUE TITLE
Unexpected locked exception overwriting a file

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#17098]
### Steps to reproduce
1. Install 8.1 RC1 (daily) Build:2015-06-23T03:09:53+00:00 25581c7b638a5349c0180b6210b2e1d332e19e49  with high level locking enabled and redis (checked against http://docker.oc.solidgear.es:50858/)
2. Run smashbox test: lib/oc-tests/new_locking/test_overwriteFilePlusAction.py second test `bin/smash -t 1 lib/oc-tests/new_locking/test_overwriteFilePlusAction.py`  (the test is in the locking_tests branch)

### Expected behaviour
Test pass. The target file is overwritten and then downloaded

### Actual behaviour
An unexpected 423 locked exception is thrown overwriting the file.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.1 RC1 (daily) Build:2015-06-23T03:09:53+00:00 25581c7b638a5349c0180b6210b2e1d332e19e49 

**Updated from an older ownCloud or fresh install:** fresh install

#### ownCloud log (data/owncloud.log)
```
{"reqId":"PAizkTc0QHF7LykIM7LG","remoteAddr":"82.159.139.58","app":"admin_audit","message":"Create \"\/user2\/files\/folder\/bigfile.dat.ocTransferId1689309736.part\" by user user2, owner: user2","level":1,"time":"2015-06-23T09:41:21+00:00","method":"PUT","url":"\/remote.php\/webdav\/folder\/bigfile.dat-chunking-1689309736-4-3"}
{"reqId":"PAizkTc0QHF7LykIM7LG","remoteAddr":"82.159.139.58","app":"admin_audit","message":"Create \"\/user2\/files\/folder\/bigfile.dat\" by user user2, owner: user2","level":1,"time":"2015-06-23T09:41:21+00:00","method":"PUT","url":"\/remote.php\/webdav\/folder\/bigfile.dat-chunking-1689309736-4-3"}
{"reqId":"\/WxLUYPk7wNrdxaYf3Vs","remoteAddr":"82.159.139.58","app":"admin_audit","message":"Create \"\/user1\/files\/folder\/bigfile.dat.ocTransferId1689309738.part\" by user user1, owner: user1","level":1,"time":"2015-06-23T09:41:32+00:00","method":"PUT","url":"\/remote.php\/webdav\/folder\/bigfile.dat-chunking-1689309738-4-3"}
{"reqId":"\/WxLUYPk7wNrdxaYf3Vs","remoteAddr":"82.159.139.58","app":"admin_audit","message":"Create \"\/user1\/files\/folder\/bigfile.dat\" by user user1, owner: user1","level":1,"time":"2015-06-23T09:41:32+00:00","method":"PUT","url":"\/remote.php\/webdav\/folder\/bigfile.dat-chunking-1689309738-4-3"}
{"reqId":"jGmOqykydnVBrDBolxVz","remoteAddr":"82.159.139.58","app":"admin_audit","message":"Read \"\/user1\/files\/folder\/bigfile.dat\" by user user1, owner: user1","level":1,"time":"2015-06-23T09:41:33+00:00","method":"GET","url":"\/remote.php\/webdav\/folder\/bigfile.dat"}
{"reqId":"lx+b8vtUA+fQrnRVlAXS","remoteAddr":"82.159.139.58","app":"admin_audit","message":"Read \"\/user2\/files\/folder\/bigfile.dat\" by user user2, owner: user2","level":1,"time":"2015-06-23T09:41:33+00:00","method":"GET","url":"\/remote.php\/webdav\/folder\/bigfile.dat"}
{"reqId":"1yNjHdITA\/uNsUGgY0Vh","remoteAddr":"82.159.139.58","app":"admin_audit","message":"Update \"\/user1\/files\/folder\/bigfile.dat\" by user user1, owner: user1","level":1,"time":"2015-06-23T09:41:43+00:00","method":"PUT","url":"\/remote.php\/webdav\/folder\/bigfile.dat"}
{"reqId":"1yNjHdITA\/uNsUGgY0Vh","remoteAddr":"82.159.139.58","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"folder\\\/bigfile.dat\\\" is locked\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #34)\\n#1 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('folder\\\/bigfile....', Resource id #34, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/opt\\\/owncloud\\\/remote.php(84): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":198}","level":4,"time":"2015-06-23T09:41:43+00:00","method":"PUT","url":"\/remote.php\/webdav\/folder\/bigfile.dat"}
{"reqId":"TZWWMp4NjwOpe0yzqmfG","remoteAddr":"82.159.139.58","app":"admin_audit","message":"Update \"\/user2\/files\/folder\/bigfile.dat\" by user user2, owner: user2","level":1,"time":"2015-06-23T09:41:47+00:00","method":"PUT","url":"\/remote.php\/webdav\/folder\/bigfile.dat"}
{"reqId":"TZWWMp4NjwOpe0yzqmfG","remoteAddr":"82.159.139.58","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"folder\\\/bigfile.dat\\\" is locked\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #34)\\n#1 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('folder\\\/bigfile....', Resource id #34, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/opt\\\/owncloud\\\/remote.php(84): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":198}","level":4,"time":"2015-06-23T09:41:47+00:00","method":"PUT","url":"\/remote.php\/webdav\/folder\/bigfile.dat"}
```

### Notes
I remember this was happening some time ago, and I think it was fixed later.

Server version 8.1 beta 2 (daily) Build:2015-06-12T03:13:02+00:00 cda9685c0ece25fe99a8046a94f06f145191a09d  (http://docker.oc.solidgear.es:50696) doesn't present that behaviour and pass the test fine

**Comment by PVince81** [comment]
Is encryption enabled ?

**Comment by nickvergessen** [comment]
When testing locking, please always use latest master. 10 days ago is way too much for locking testing.
Also please adjust your test to use existing smashbox functions only, or explain why this is not possible.

And last but not least, this is why I said we can't bother with new tests atm, because we don't have the time atm to verify that they are written in a reliable way. As long as https://ci.owncloud.org/job/smashbox/ is not green, there is no need for a comment on any new test, because we have reliable ways to break it. When those that are known to be reliable pass with lock+enc we can have a look at new tests.

**Comment by jvillafanez** [comment]
Encryption is disabled, as well as the old files_locking

**Comment by DeepDiver1975** [comment]
> When testing locking, please always use latest master. 10 days ago is way too much for locking testing.

closing this - please retest with latest master - THX
