### ISSUE TITLE
External storage folder doesnt appear

### ISSUE THREAD

**Issue by nasli** [owncloud/core#17107]
### Steps to reproduce
1.Activate external storage app.
2.    Add dropbox folder as external storage for all users. The folder is created.
3.    Delete the dropbox folder from admin settings. The folder is removed.
4.    Add again same folder. 

### Expected behaviour
Folder should appear as shared folder for all users.

### Actual behaviour
The folder doesnt appear. In admin external storage setting the folder has the icon color red.

### Server configuration
**ownCloud version:** 
{"installed":true,"maintenance":false,"version":"8.1.0.7","versionstring":"8.1 RC1","edition":""}
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":""}
**Updated from an older ownCloud or fresh install:**
Fresh install
**List of activated apps:**
Default apps

**Are you using encryption:** no

### Logs
```
Fatal 	files_external 	Exception: {"Exception":"Exception","Message":"Creating \\OC\\Files\\Storage\\Dropbox storage failed","Code":0,"Trace":"
#0 \/opt\/owncloud\/apps\/files_external\/lib\/config.php(496): OC\\Files\\Storage\\Dropbox->__construct(Array)\n
#1 \/opt\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(123): OC_Mount_Config::getBackendStatus('\\OC\\Files\\Stora...', Array, false)\n
#2 \/opt\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(138): OCA\\Files_External\\Controller\\StoragesController->updateStorageStatus(Object(OCA\\Files_external\\Lib\\StorageConfig))\n
#3 [internal function]: OCA\\Files_External\\Controller\\StoragesController->show(2)\n
#4 \/opt\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n
#5 \/opt\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'show')\n
#6 \/opt\/owncloud\/lib\/private\/appframework\/app.php(107): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'show')\n
#7 \/opt\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('GlobalStoragesC...', 'show', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n
#8 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n
#9 \/opt\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n
#10 \/opt\/owncloud\/lib\/base.php(867): OC\\Route\\Router->match('\/apps\/files_ext...')\n
#11 \/opt\/owncloud\/index.php(40): OC::handleRequest()\n
#12 {main}","File":"\/opt\/owncloud\/apps\/files_external\/lib\/dropbox.php","Line":57} 
Error	PHP	Array to string conversion at /opt/owncloud/lib/private/template/functions.php#36
Error 	core 	Creating \OC\Files\Storage\Dropbox storage failed 
```

**Comment by DeepDiver1975** [comment]
More of an exceptional usage scenario furthermore we will not touch DropBox code in 8.1 -> moveing to 8.2

**Comment by PVince81** [comment]
Works for me on stable8.1 (the upcoming 8.1.2)

@nasli did you click "Grant access" again after re-adding the Dropbox storage ?
If it still doesn't work please provide more details about your UI interactions and their order.

Thanks.

**Comment by SergioBertolinSG** [comment]
I can confirm dropbox is working in stable8.1 but not in the 8.1 tarball (owncloud-enterprise-complete-8.1.0.tar.bz2), that is the confusion.

**Comment by PVince81** [comment]
stable8.1 is already post 8.1.1

**Comment by nasli** [comment]
I just created a new instance with 8.1 and I still have the same issuee, the second time does not work.

**Comment by SergioBertolinSG** [comment]
I'm seeing the same, removing the dropbox mount, and adding it again in stable8.1 makes it fail like in 8.1.0:

```
Exception: {"Exception":"Exception","Message":"Creating \\OC\\Files\\Storage\\Dropbox storage failed","Code":0,"Trace":"#0 \/opt\/owncloud\/apps\/files_external\/lib\/config.php(496): OC\\Files\\Storage\\Dropbox->__construct(Array)\n#1 \/opt\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(123): OC_Mount_Config::getBackendStatus('\\OC\\Files\\Stora...', Array, false)\n#2 \/opt\/owncloud\/apps\/files_external\/controller\/globalstoragescontroller.php(100): OCA\\Files_External\\Controller\\StoragesController->updateStorageStatus(Object(OCA\\Files_external\\Lib\\StorageConfig))\n#3 [internal function]: OCA\\Files_External\\Controller\\GlobalStoragesController->create('Dropbox', '\\OC\\Files\\Stora...', Array, NULL, Array, Array, 100)\n#4 \/opt\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/opt\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'create')\n#6 \/opt\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'create')\n#7 \/opt\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('GlobalStoragesC...', 'create', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#9 \/opt\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#10 \/opt\/owncloud\/lib\/base.php(873): OC\\Route\\Router->match('\/apps\/files_ext...')\n#11 \/opt\/owncloud\/index.php(40): OC::handleRequest()\n#12 {main}","File":"\/opt\/owncloud\/apps\/files_external\/lib\/dropbox.php","Line":57} 
```

**Comment by PVince81** [comment]
can you confirm that you didn't forget to click on "Grant access" after re-adding it ?

**Comment by SergioBertolinSG** [comment]
yes, I granted access again.

**Comment by nasli** [comment]
We click granted access, a window is displayed and then we allow the access to the dropbox account

**Comment by PVince81** [comment]
Thanks.

I'll need to find a way to reproduce this.

Do you see the same issue with other external storages like GDrive or SFTP ?

**Comment by SergioBertolinSG** [comment]
Tried with SMB, no problems there.

**Comment by PVince81** [comment]
Is this still happening on 9.0 after the many changes to the FS logic and also a few Dropbox fixes ?

**Comment by cmonteroluque** [comment]
re-open if necessary
