### ISSUE TITLE
Sharing unit tests of pyocclient fails in oC 7.0.7 community

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#17322]
### Steps to reproduce
1.- Install last oC 7.0.7
2.- Execute pyocclient unit tests against it,

### Expected behaviour
All test pass.

### Actual behaviour
Tests related with sharing fails.

This only happens in community edition, enterprise edition works correctly. 

```
..E.......................E...E............
======================================================================
ERROR: test_delete_share (__main__.TestFileAccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sergio/AUTOMATIZACION_PAQUETES/ENTORNOVIRTUAL/local/lib/python2.7/site-packages/unittest_data_provider/__init__.py", line 7, in repl
    fn(self, *i)
  File "../pyocclient/owncloud/test/test.py", line 485, in test_delete_share
    share_info = self.client.share_file_with_user(path, self.share2user)
  File "/home/sergio/AUTOMATIZACION_PAQUETES/pyocclient/owncloud/owncloud.py", line 855, in share_file_with_user
    self.__check_ocs_status(tree)
  File "/home/sergio/AUTOMATIZACION_PAQUETES/pyocclient/owncloud/owncloud.py", line 1181, in __check_ocs_status
    raise ResponseError(r)
ResponseError: HTTP error: 403

======================================================================
ERROR: test_share_with_user (__main__.TestFileAccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sergio/AUTOMATIZACION_PAQUETES/ENTORNOVIRTUAL/local/lib/python2.7/site-packages/unittest_data_provider/__init__.py", line 7, in repl
    fn(self, *i)
  File "../pyocclient/owncloud/test/test.py", line 469, in test_share_with_user
    share_info = self.client.share_file_with_user(path, self.share2user)
  File "/home/sergio/AUTOMATIZACION_PAQUETES/pyocclient/owncloud/owncloud.py", line 855, in share_file_with_user
    self.__check_ocs_status(tree)
  File "/home/sergio/AUTOMATIZACION_PAQUETES/pyocclient/owncloud/owncloud.py", line 1181, in __check_ocs_status
    raise ResponseError(r)
ResponseError: HTTP error: 403

======================================================================
ERROR: test_update_share_user (__main__.TestFileAccess)
Test updating a share parameters - user share
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../pyocclient/owncloud/test/test.py", line 555, in test_update_share_user
    share_info = self.client.share_file_with_user(path, self.share2user)
  File "/home/sergio/AUTOMATIZACION_PAQUETES/pyocclient/owncloud/owncloud.py", line 855, in share_file_with_user
    self.__check_ocs_status(tree)
  File "/home/sergio/AUTOMATIZACION_PAQUETES/pyocclient/owncloud/owncloud.py", line 1181, in __check_ocs_status
    raise ResponseError(r)
ResponseError: HTTP error: 403
```

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
oc 7.0.7RC1

**Updated from an older ownCloud or fresh install:**
fresh install using package.

**List of activated apps:**
none

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No.

**Logs**
```

```

### Client configuration
pyocclient

cc @PVince81

**Comment by PVince81** [comment]
Ok let's bisect this then.

I wonder if it's related to your changes to the tests here https://github.com/owncloud/pyocclient/pull/100.
Did you check if the user "share" was properly created on that 7.0.7 instance ?

**Comment by SergioBertolinSG** [comment]
I didn't. That should be the problem, thanks.

**Comment by SergioBertolinSG** [comment]
It works now.
