### ISSUE TITLE
Double slash in URL gives error page

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17384]
### Steps to reproduce
1. Setup ownCloud
2. Open the URL http://localhost/owncloud//index.php/apps/files/ (notice the double slash)
### Expected result

Page appears, or at least redirect to the correct URL
### Actual result

Error page "Internal Server Error"
### Versions

ownCloud 8.1 RC2 and master
### Logs

```
{"reqId":"3Yz68AvBzat3LSa+nJCD","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/owncloud\\\/index.php\\\/apps\\\/files\\\/) cannot be processed by the script '\\\/owncloud\\\/\\\/index.php')\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(867): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n
#2 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":560}","level":4,"time":"2015-07-03T15:48:54+00:00","method":"GET","url":"\/owncloud\/\/index.php\/apps\/files\/"}
```

Possible problem with the router ? @LukasReschke @DeepDiver1975 @Raydiation

**Comment by Raydiation** [comment]
Seems like this was done intentionally https://github.com/owncloud/core/blob/master/lib/private/appframework/http/request.php#L555

**Comment by Raydiation** [comment]
None issue imho

**Comment by PVince81** [comment]
lol the FIXME

**Comment by PVince81** [comment]
Still happening on master O_o

**Comment by PVince81** [comment]
Still happening on stable9.1

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
