### ISSUE TITLE
Infinite redirection since upgrade to 8.1

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/core#17580]
### Steps to reproduce
1. Upgrade using the [linux package manager](https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html#upgrading-with-your-linux-package-manager)
2. Call the command line `sudo -u www-data php occ upgrade`
3. Access https://cloud.foolstep.com with your browser
4. See the error from the browser

### Expected behaviour
It should work as before (OC 8.0). It was getting me to https://cloud.foolstep.com/index.php/apps/files/ and displaying the proper content of the page.

### Actual behaviour
My browser (Firefox) complains about redirection issues

```
The page isn't redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies.
```

The desktop and mobile clients does work, it seems to only be a web interface problem.

### Server configuration
**Operating system**: Debian 8.1

**Web server:** nginx 1.6.2

**Database:** mysql 5.5.43

**PHP version:** 5.6.7

**ownCloud version:** 8.1 (can't see it since the web interface doesn't work)

**Updated from an older ownCloud or fresh install:** From and older ownCloud (8.0)

**List of activated apps:**

`sudo -u www-data php occ app:list` gives me nothing, maybe `occ` or `console.php` is broken?

I activated these apps: documents, calendar, tasks, contacts, music and ocusagecharts.

**The content of config/config.php:**

Again `sudo -u www-data php occ config:list system --public` gives me nothing.

```
<?php

define('DEBUG', true);

$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'cloud.foolstep.com',
  ),
  'datadirectory' => '/home/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'loglevel' => '0',
  'theme' => '',
  'forcessl' => true,
  'maintenance' => false,
  'secret' => 'xxx',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'cloud.foolstep.com',
  'mail_smtpmode' => 'php',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 38.0.5

**Operating system:** Fedora 22

#### Web server error log
```
sudo tail /var/log/nginx/owncloud_error.log
2015/07/11 17:40:57 [error] 7254#0: *20597 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/owncloud/3rdparty/react/promise/src/functions_include.php): failed to open stream: Permission denied in /var/www/owncloud/3rdparty/composer/autoload_real.php on line 58
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/owncloud/3rdparty/react/promise/src/functions_include.php' (include_path='/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:/var/www/owncloud/lib:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') in /var/www/owncloud/3rdparty/composer/autoload_real.php on line 58" while reading response header from upstream, client: 132.210.97.99, server: cloud.foolstep.com, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.owncloud.sock:", host: "cloud.foolstep.com"
2015/07/11 17:40:57 [error] 7252#0: *20846 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/owncloud/3rdparty/react/promise/src/functions_include.php): failed to open stream: Permission denied in /var/www/owncloud/3rdparty/composer/autoload_real.php on line 58
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/owncloud/3rdparty/react/promise/src/functions_include.php' (include_path='/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:/var/www/owncloud/lib:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') in /var/www/owncloud/3rdparty/composer/autoload_real.php on line 58" while reading response header from upstream, client: 132.210.22.12, server: cloud.foolstep.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.owncloud.sock:", host: "cloud.foolstep.com"
2015/07/11 17:40:57 [error] 7254#0: *20668 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/owncloud/3rdparty/react/promise/src/functions_include.php): failed to open stream: Permission denied in /var/www/owncloud/3rdparty/composer/autoload_real.php on line 58
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/owncloud/3rdparty/react/promise/src/functions_include.php' (include_path='/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:/var/www/owncloud/lib:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') in /var/www/owncloud/3rdparty/composer/autoload_real.php on line 58" while reading response header from upstream, client: 132.210.97.97, server: cloud.foolstep.com, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.owncloud.sock:", host: "cloud.foolstep.com"
2015/07/11 19:19:54 [error] 21296#0: *1027 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 216.98.56.20, server: cloud.foolstep.com, request: "POST /index.php/heartbeat HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.owncloud.sock:", host: "cloud.foolstep.com", referrer: "https://cloud.foolstep.com/index.php/apps/files/?dir=~~private~~"
2015/07/11 19:31:43 [error] 3573#0: *188 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 216.98.56.20, server: cloud.foolstep.com, request: "POST /index.php/heartbeat HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.owncloud.sock:", host: "cloud.foolstep.com", referrer: "https://cloud.foolstep.com/index.php/apps/files/~~private~~"
2015/07/11 19:43:43 [error] 3570#0: *526 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 216.98.56.20, server: cloud.foolstep.com, request: "POST /index.php/heartbeat HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.owncloud.sock:", host: "cloud.foolstep.com", referrer: "https://cloud.foolstep.com/index.php/apps/files/?dir=~~private~~"
```

These errors doesn't seem to be linked to the problem, maybe they come from the moment I was applying the [strong directory permissions](https://doc.owncloud.org/server/8.1/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions). I don't have them when I refresh the web site.

#### ownCloud log (data/owncloud.log)
```
sudo tail /var/www/owncloud/data/owncloud.log
{"reqId":"AxshlQLE0aNz7ysT+boI","remoteAddr":"132.210.97.97","app":"music","message":"update - \/~~private~~\/files\/~~private~~","level":0,"time":"2015-07-11T17:45:54+00:00","method":"PUT","url":"\/remote.php\/webdav\/~~private~~"}
{"reqId":"AxshlQLE0aNz7ysT+boI","remoteAddr":"132.210.97.97","app":"music","message":"update - mimetype application\/vnd.openxmlformats-officedocument.wordprocessingml.document","level":0,"time":"2015-07-11T17:45:54+00:00","method":"PUT","url":"\/remote.php\/webdav\/~~private~~"}
{"reqId":"o+PPCGdsAO3x9EPzGgvh","remoteAddr":"132.210.228.111","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-07-11T17:46:15+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"o\/BlgU8cYTTp95kznOIW","remoteAddr":"132.210.97.97","app":"music","message":"update - \/~~private~~\/files\/~~private~~","level":0,"time":"2015-07-11T17:46:26+00:00","method":"PUT","url":"\/remote.php\/~~private~~"}
{"reqId":"o\/BlgU8cYTTp95kznOIW","remoteAddr":"132.210.97.97","app":"music","message":"update - mimetype application\/vnd.openxmlformats-officedocument.wordprocessingml.document","level":0,"time":"2015-07-11T17:46:26+00:00","method":"PUT","url":"\/remote.php\/webdav\/~~private~~"}
{"reqId":"eHb03+y0lBy\/\/KsRuqnX","remoteAddr":"132.210.228.111","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-07-11T17:47:37+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"VgshpEhCHxikHePoaIyA","remoteAddr":"192.222.172.139","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-07-11T17:49:45+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"7S4\/R8x9YLnSbD5JRf\/T","remoteAddr":"132.210.97.97","app":"music","message":"update - \/~~private~~\/files\/~~private~~","level":0,"time":"2015-07-11T17:50:25+00:00","method":"PUT","url":"\/remote.php\/webdav\/~~private~~"}
{"reqId":"7S4\/R8x9YLnSbD5JRf\/T","remoteAddr":"132.210.97.97","app":"music","message":"update - mimetype application\/vnd.openxmlformats-officedocument.wordprocessingml.document","level":0,"time":"2015-07-11T17:50:25+00:00","method":"PUT","url":"\/remote.php\/webdav\/~~private~~"}
{"reqId":"Nd5OelcM+ZC3CDTW7GaB","remoteAddr":"132.210.228.111","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-07-11T17:51:09+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
```

These errors keep coming... maybe that's the problem?

#### Browser log
```
The page isn't redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies.
```

```
curl -v https://cloud.foolstep.com/
*   Trying 37.187.121.53...
* Connected to cloud.foolstep.com (37.187.121.53) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
* Server certificate:
* 	subject: CN=cloud.foolstep.com,OU=Gandi Standard SSL,OU=Domain Control Validated
* 	start date: fév 12 00:00:00 2015 GMT
* 	expire date: fév 12 23:59:59 2016 GMT
* 	common name: cloud.foolstep.com
* 	issuer: CN=Gandi Standard SSL CA,O=GANDI SAS,C=FR
> GET / HTTP/1.1
> User-Agent: curl/7.40.0
> Host: cloud.foolstep.com
> Accept: */*
> 
< HTTP/1.1 302 Moved Temporarily
< Server: nginx/1.6.2
< Date: Sat, 11 Jul 2015 17:56:59 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: oc034e17b04e=qndk0617k78r8tqaoc53uuics0; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< X-Robots-Tag: none
< Location: https://cloud.foolstep.com/index.php
< Strict-Transport-Security: max-age=15768000; includeSubDomains; preload;
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< 
* Connection #0 to host cloud.foolstep.com left intact
```

**Comment by RealRancor** [comment]
Mhhh, do you have done a full upgrade (removing all files / folders except /config/ and /data/)?

Using the official NginX config from the oC8.1 docs?

Restarted php-fpm to clear the browser cache?

**Comment by MightyCreak** [comment]
I didn't do a full upgrade (I upgraded using the openSUSE repository, using dist-upgrade because update didn't want to update from 8.0 to 8.1)

I used the official 8.1 documentation (for both [strong directory permissions](https://doc.owncloud.org/server/8.1/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions) and [nginx config](https://doc.owncloud.org/server/8.1/admin_manual/installation/nginx_configuration.html)).

I've restarted nginx and php5-fpm and the result is the same.

From what I understand, the problem is an infinite loop in redirection. https://cloud.foolstep.com redirects to https://cloud.foolstep.com/index.php (because of the index directive) and https://cloud.foolstep.com/index.php redirects to https://cloud.foolstep.com/index.php... and here goes the loop. I don't know how to debug that though...

**Comment by MightyCreak** [comment]
I commented some code in index.php and the problem starts with `OC::handleRequest();`.

**Comment by MightyCreak** [comment]
Inside the function handleRequest (lib/base.php ~L860), I added an `echo 'test';` before and after the `if` block and I get only one 'test', meaning that the problem is within this code:

```
        if (!self::$CLI and (!isset($_GET["logout"]) or ($_GET["logout"] !== 'true'))) {
            try {
                if (!$systemConfig->getValue('maintenance', false) && !\OCP\Util::needUpgrade()) {
                    OC_App::loadApps(array('filesystem', 'logging'));
                    OC_App::loadApps();
                }
                self::checkSingleUserMode();
                OC_Util::setupFS();
                OC::$server->getRouter()->match(\OC::$server->getRequest()->getRawPathInfo());
                return;
            } catch (Symfony\Component\Routing\Exception\ResourceNotFoundException $e) {
                //header('HTTP/1.0 404 Not Found');
            } catch (Symfony\Component\Routing\Exception\MethodNotAllowedException $e) {
                OC_Response::setStatus(405);
                return;
            }
        }
```

Still investigating...

**Comment by MightyCreak** [comment]
I found the issue!

It was because of the ocusagecharts app...

I `rm -rf` it and it works now... so it's good to know that even if the app [says it's compatible with 8.1](https://apps.owncloud.com/content/show.php/Storage+Usage+%2B+Activity+Charts?content=166746), well it isn't...

**Comment by RealRancor** [comment]
Strange, the latest version 3.4.5 works here just fine on a similar setup.

**Comment by MightyCreak** [comment]
I'll try to do a fresh install. But I suspect that there is a problem in the DB.

**Comment by RealRancor** [comment]
There was a user reporting the same at the forums: https://forum.owncloud.org/viewtopic.php?f=31&t=29257

Maybe report this to the developer of the app to make him aware of this: https://github.com/arnovr/ocusagecharts/issues

**Comment by MightyCreak** [comment]
I don't know why, but I fixed the problem by removing all the apps that are not in the official `owncloud` package, and then reactivating them one by one.

##### How to know the packaged apps (tested on Debian 8.1)

Get the list of ownCloud package with this command:

    dpkg -l '*owncloud*' | grep '^.i'

And then, in the following command, replace `{packages}` with all the listed packages above:

    dpkg -L {packages} | grep '^/var/www/owncloud/apps/[^/]*$'

**Comment by johanehnberg** [comment]
I confirm this error. Similar environment (deb packages). I actually installed the usage charts after upgrading to 8.1. Everything still worked until I rebooted the server with a new kernel. sudo rm -rf /var/www/owncloud/apps/storagecharts2 did the trick.

**Comment by RealRancor** [comment]
@johanehnberg As storagecharts2 is a different app please report this issue to: https://github.com/hypery2k/owncloud/issues

**Comment by q1x** [comment]
I was having the same issue, all of a sudden my working Owncloud 8.1 install started giving a redirect loop. No errors in apache log or anythin. After hours of searching I found this issue and moved storagecharts2 to another location. Problem was solved directly after that.

**Comment by Worst45** [comment]
I confirm that removing storagecharts2 did the trick.

**Comment by Saxfusion** [comment]
I confirm as well. Removing the soragecharts2 (v2.6.1) from the app folder resolved the problem instantly.
I am not sure though when it started exactly since after the install of the app i was still working in the Web-UI. Maybe after all users were logged of, or webserver restart, or ... just experienced it the next day.

**Comment by RealRancor** [comment]
I wonder if anyone managed to report this to the dev of this app?

**Comment by MightyCreak** [comment]
Apparently yes: https://github.com/hypery2k/owncloud/issues/351
