### ISSUE TITLE
PHP error in the log about HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/core#17593]
### Steps to reproduce
1. See error log

### Expected behaviour
Not have the error

### Actual behaviour
There is this entry in the log:

```
{"reqId":"fldnAbRhR5StEDcZMN0Z","remoteAddr":"192.222.172.139","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-07-12T18:27:05+00:00","method":"POST","url":"\/index.php\/heartbeat"}
```

### Server configuration
**Operating system**: Debian 8.1

**Web server:** nginx 1.6.2

**Database:** MySQL 5.5.43

**PHP version:** 5.6.9

**ownCloud version:** 8.1.0

**Updated from an older ownCloud or fresh install:** from an older ownCloud

**List of activated apps:**

```
Enabled:
 - activity: 2.0.1
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.10.0
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - tasks: 0.7.1
 - templateeditor: 0.1
Disabled:
 - encryption
 - external
 - files_external
 - files_locking
 - music
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

*Note: `sudo -u www-data php occ config:list system --public` doesn't exist anymore.*

```php
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'datadirectory' => '/home/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'loglevel' => '0',
  'theme' => '',
  'forcessl' => true,
  'maintenance' => false,
  'secret' => 'xxx',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'xxx',
  'mail_smtpmode' => 'php',
  'appstore.experimental.enabled' => false,
  'memcache.local' => '\OC\Memcache\APCu',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 38.0.5

**Operating system:** Fedora 22

#### Web server error log
```
2015/07/12 15:42:20 [error] 712#0: *8992 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getUID() on null in /var/www/owncloud/apps/tasks/appinfo/application.php on line 124" while reading response header from upstream, client: 192.222.172.139, server: ~~private~~, request: "GET /index.php/apps/tasks/ HTTP/1.1", upstream: "fastcgi://~~private~~:", host: "~~private~~"
2015/07/12 15:42:21 [error] 712#0: *8992 open() "/var/www/owncloud/favicon.ico" failed (2: No such file or directory), client: 192.222.172.139, server: ~~private~~, request: "GET /favicon.ico HTTP/1.1", host: "~~private~~"
2015/07/12 15:42:21 [error] 712#0: *8992 open() "/var/www/owncloud/favicon.ico" failed (2: No such file or directory), client: 192.222.172.139, server: ~~private~~, request: "GET /favicon.ico HTTP/1.1", host: "~~private~~"
2015/07/12 15:42:53 [error] 712#0: *9039 access forbidden by rule, client: 37.187.121.53, server: ~~private~~, request: "GET /data/htaccesstest.txt HTTP/1.1", host: "~~private~~"
2015/07/12 16:47:39 [error] 13215#0: *10130 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Sabre\DAV\Exception\ServiceUnavailable' not found in /var/www/owncloud/remote.php on line 62" while reading response header from upstream, client: 192.222.172.139, server: ~~private~~, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://~~private~~:", host: "~~private~~:"
2015/07/12 18:26:26 [error] 18928#0: *13572 access forbidden by rule, client: 37.187.121.53, server: ~~private~~, request: "GET /data/htaccesstest.txt HTTP/1.1", host: "~~private~~"
2015/07/12 19:56:26 [error] 21575#0: *16072 access forbidden by rule, client: 2001:41d0:a:f235::1, server: ~~private~~, request: "GET /data/htaccesstest.txt HTTP/1.1", host: "~~private~~"
2015/07/12 20:15:10 [error] 21572#0: *16403 access forbidden by rule, client: 2001:41d0:a:f235::1, server: ~~private~~, request: "GET /data/htaccesstest.txt HTTP/1.1", host: "~~private~~"
2015/07/12 20:18:23 [crit] 21574#0: *16287 connect() to ~~private~~ failed (2: No such file or directory) while connecting to upstream, client: 192.222.172.139, server: ~~private~~, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://~~private~~:", host: "~~private~~"
2015/07/12 20:42:48 [error] 25382#0: *278 access forbidden by rule, client: 2001:41d0:a:f235::1, server: ~~private~~, request: "GET /data/htaccesstest.txt HTTP/1.1", host: "~~private~~"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"BFmmZ37JcenPlR2FTcSm","remoteAddr":"","app":"files_versions","message":"Expire: \/~~private~~","level":0,"time":"2015-07-12T18:45:04+00:00","method":"--","url":"--"}
{"reqId":"PbrErb6wHRVeC1o3Ub9q","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-07-12T18:48:07+00:00","method":"--","url":"--"}
{"reqId":"PbrErb6wHRVeC1o3Ub9q","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/documents\/appinfo\/app.php#49","level":3,"time":"2015-07-12T18:48:07+00:00","method":"--","url":"--"}
{"reqId":"LyGYTBanQsxPRfMzHvAb","remoteAddr":"192.222.172.139","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-07-12T18:49:46+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
```

**Comment by RealRancor** [comment]
Follow this:

> To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini
