### ISSUE TITLE
CalDav sync not working, 503 Exception App not installed

### ISSUE THREAD

**Issue by ka223** [owncloud/core#17733]
Hi,

since I upgraded from 8.1.0-1 to owncloud 8.1.0-2, the calendar sync fails.
This error is only located at the caldav app, carddav sync is working.

Used Link:
https://domain.de/owncloud/remote.php/caldav

I can access and manage my calendar via the web interface but it is not possible to sync with other devices.

Folder permissions are correct, I used the bash script from the installation wiki.
https://doc.owncloud.org/server/8.1/admin_manual/installation/installation_wizard.html

App installed:  Calendar 0.7.2
Removing the .../owncloud/apps/calendar folder and reinstalling the app is not helping.

```
Error	PHP	Undefined index: Please double check the <a target="_blank" href="%s">installation guides ↗</a>, and check for any errors or warnings in the <a href="#log-section">log</a>. at /var/www/owncloud/lib/private/l10n/string.php#70	2015-07-18T21:28:01+00:00
Error	PHP	Undefined index: Please double check the <a target="_blank" href="%s">installation guides ↗</a>, and check for any errors or warnings in the <a href="#log-section">log</a>. at /var/www/owncloud/lib/private/l10n/string.php#64	2015-07-18T21:28:01+00:00
```

```
Fatal	webdav	Exception: {"Message":"HTTP\/1.1 503 Exception: App not installed: ","Code":0,"Trace":"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/remote.php(64): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(135): handleException(Object(Exception))\n#6 {main}","File":"\/var\/www\/owncloud\/remote.php","Line":62}
```

EDIT after Owncloud 8.1.0-3 update:

The Error messages changed a bit:

```
Fatal 	remote 	App not installed: 	2015-08-02T09:08:56+00:00
Error 	PHP 	Undefined index: Please double check the <a target="_blank" href="%s">installation guides ↗</a>, and check for any errors or warnings in the <a href="#log-section">log</a>. at /var/www/owncloud/lib/private/l10n/string.php#70 	2015-08-02T09:08:33+00:00
Error 	PHP 	Undefined index: Please double check the <a target="_blank" href="%s">installation guides ↗</a>, and check for any errors or warnings in the <a href="#log-section">log</a>. at /var/www/owncloud/lib/private/l10n/string.php#64 	2015-08-02T09:08:33+00:00
Error	PHP	Undefined index: Please double check the <a target="_blank" href="%s">installation guides ↗</a>, and check for any errors or warnings in the <a href="#log-section">log</a>. at /var/www/owncloud/lib/private/l10n/string.php#70	2015-08-02T09:08:33+00:00
Error	PHP	Undefined index: Please double check the <a target="_blank" href="%s">installation guides ↗</a>, and check for any errors or warnings in the <a href="#log-section">log</a>. at /var/www/owncloud/lib/private/l10n/string.php#64
Fatal 	remote 	App not installed: 	2015-08-02T08:59:37+00:00
Error 	PHP 	Undefined index: Please double check the <a target="_blank" href="%s">installation guides ↗</a>, and check for any errors or warnings in the <a href="#log-section">log</a>. at /var/www/owncloud/lib/private/l10n/string.php#70 	2015-08-02T08:58:34+00:00
Error 	PHP 	Undefined index: Please double check the <a target="_blank" href="%s">installation guides ↗</a>, and check for any errors or warnings in the <a href="#log-section">log</a>. at /var/www/owncloud/lib/private/l10n/string.php#64 	2015-08-02T08:58:34+00:00 
Error 	PHP 	session_regenerate_id(): Cannot regenerate session id - headers already sent at /var/www/owncloud/apps/calendar/appinfo/update.php#73 	2015-08-02T08:38:06+00:00
Error 	PHP 	Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/user/session.php#313 	2015-08-02T08:38:06+00:00
Error 	PHP 	Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/user/session.php#312 	2015-08-02T08:38:06+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/user/session.php#313	2015-08-02T08:38:06+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/user/session.php#312	2015-08-02T08:38:06+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/user/session.php#311	2015-08-02T08:38:06+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/user/session.php#308	2015-08-02T08:38:06+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/user/session.php#307	2015-08-02T08:38:06+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/user/session.php#306	2015-08-02T08:38:06+00:00
Error	PHP	file_put_contents(/var/www/owncloud/data/.htaccess): failed to open stream: Permission denied at /var/www/owncloud/lib/private/setup.php#435	2015-08-02T08:37:25+00:00
Error	PHP	Undefined index: Hide description … at /var/www/owncloud/lib/private/l10n/string.php#70	2015-08-02T08:34:58+00:00
Error	PHP	Undefined index: Hide description … at /var/www/owncloud/lib/private/l10n/string.php#64	2015-08-02T08:34:58+00:00
Error	PHP	Undefined index: Show description … at /var/www/owncloud/lib/private/l10n/string.php#70	2015-08-02T08:34:58+00:0
```

CalDav is still not working, calendar at the web interface works fine.

Update: I reinstalled owncloud

source:
/etc/apt/sources.list.d $ cat owncloud.list 
deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ /

sudo apt-get purge owncloud*
sudo apt-get purge libaio1 libdbd-mysql-perl libdbi-perl libhtml-template-perl libmcrypt4 libmysqlclient16 libpq5 mysql-client-5.5 mysql-server mysql-server-5.5 mysql-server-core-5.5 php-xml-parser php5 php5-intl php5-mcrypt php5-mysqlnd php5-pgsql php5-sqlite
sudo rm -r /var/www/owncloud
* Restore 
** mysql Database
** current data Folder
** config folder from two month ago ...

sudo apt-get install owncloud*

The calendar sync worked, but the same message appears again:

```
 Fatal 	webdav 	Exception: {"Message":"HTTP\/1.1 503 Exception: App not installed: ","Code":0,"Trace":"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/remote.php(64): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(135): handleException(Object(Exception))\n#6 {main}","File":"\/var\/www\/owncloud\/remote.php","Line":62} 
```

```
Error 	PHP 	Undefined index: Please double check the <a target="_blank" href="%s">installation guides ↗</a>, and check for any errors or warnings in the <a href="#log-section">log</a>. at /var/www/owncloud/lib/private/l10n/string.php#70 	2015-08-11T10:17:14+00:00
Error 	PHP 	Undefined index: Please double check the <a target="_blank" href="%s">installation guides ↗</a>, and check for any errors or warnings in the <a href="#log-section">log</a>. at /var/www/owncloud/lib/private/l10n/string.php#64 	2015-08-11T10:17:14+00:00 
```

The line numbers from the PHP Error are located at the "function __toString" and it seems to be "$translations[$this->text]" what causes this message.

Please help, thanks!

**Comment by DeepDiver1975** [comment]
> App not installed

did you enable the calendar app?

**Comment by ka223** [comment]
Shure, I can manage my calendar in the web interface.

**Comment by PVince81** [comment]
@ka223 please do `select * from oc_appconfig where configkey like 'remote_%';`.

There should be an entry for the calendar app.
Strangely on my server I have both "caldav" and "calendar":
```
+-------+-------------------------+-----------------------------+
| appid | configkey               | configvalue                 |
+-------+-------------------------+-----------------------------+
| core  | remote_caldav           | calendar/appinfo/remote.php |
| core  | remote_calendar         | calendar/appinfo/remote.php |
```

**Comment by ka223** [comment]
Me too, this link is also not working.
domain.de/owncloud/calendar/appinfo/remote.php

```
mysql> select * from oc_appconfig where configkey like 'remote_%';
+-------+-----------------+-----------------------------+
| appid | configkey       | configvalue                 |
+-------+-----------------+-----------------------------+
| core  | remote_caldav   | calendar/appinfo/remote.php |
| core  | remote_calendar | calendar/appinfo/remote.php |
| core  | remote_carddav  | contacts/appinfo/remote.php |
| core  | remote_contacts | contacts/appinfo/remote.php |
| core  | remote_files    | files/appinfo/remote.php    |
| core  | remote_webdav   | files/appinfo/remote.php    |
+-------+-----------------+-----------------------------+
6 rows in set (0.01 sec)
```

**Comment by PVince81** [comment]
can you also confirm that the calendar app you installed is under "apps/calendar" and the name is "calendar", not something else ?

**Comment by PVince81** [comment]
@ka223 the link to test should be "domain.de/owncloud/remote.php/caldav" actually.
It is rewired internally to these PHP files.

**Comment by ka223** [comment]
I completely removed the ./owncloud/apps/calendar folder and reinstalled the app.
```
ls -l owncloud/apps/calendar
insgesamt 56
drwxr-x--- 8 www-data www-data 4096 Jul 26 11:58 3rdparty
drwxr-x--- 8 www-data www-data 4096 Jul 26 11:58 ajax
drwxr-x--- 2 www-data www-data 4096 Jul 26 11:58 appinfo
-rw-r----- 1 www-data www-data  214 Jul 26 11:58 caldav.php
-rw-r----- 1 www-data www-data  388 Jul 26 11:58 calendar.php
drwxr-x--- 2 www-data www-data 4096 Jul 26 11:58 css
-rw-r----- 1 www-data www-data 1126 Jul 26 11:58 export.php
drwxr-x--- 2 www-data www-data 4096 Jul 26 11:58 img
-rw-r----- 1 www-data www-data 2845 Jul 26 11:58 index.php
drwxr-x--- 2 www-data www-data 4096 Jul 26 11:58 js
drwxr-x--- 3 www-data www-data 4096 Jul 26 11:58 l10n
drwxr-x--- 5 www-data www-data 4096 Jul 26 11:58 lib
-rw-r----- 1 www-data www-data  492 Jul 26 11:58 settingswrapper.php
drwxr-x--- 2 www-data www-data 4096 Jul 26 11:58 templates
```

**Comment by PVince81** [comment]
@georgehrke have you heard of such issues before ?

**Comment by DeepDiver1975** [comment]
can we please have a dump of the table oc_appconfig:

> select * from oc_appconfig

**Comment by ka223** [comment]
yes
```
mysql> select * from oc_appconfig;
+-------------------+--------------------------------------+-----------------------------------------------------+
| appid             | configkey                            | configvalue                                         |
+-------------------+--------------------------------------+-----------------------------------------------------+
| activity          | enabled                              | yes                                                 |
| activity          | installed_version                    | 2.0.1                                               |
| activity          | types                                | filesystem                                          |
| backgroundjob     | lastjob                              | 3                                                   |
| calendar          | enabled                              | ["users"]                                           |
| calendar          | installed_version                    | 0.7.2                                               |
| calendar          | ocsid                                | 168707                                              |
| calendar          | types                                |                                                     |
| contacts          | enabled                              | ["users"]                                           |
| contacts          | installed_version                    | 0.4.0.0                                             |
| contacts          | ocsid                                | 166044                                              |
| contacts          | types                                |                                                     |
| core              | global_cache_gc_lastrun              | 1435962762                                          |
| core              | installedat                          | 1425032049.5983                                     |
| core              | lastcron                             | 1437662801                                          |
| core              | lastupdateResult                     | {"version":{},"versionstring":{},"url":{},"web":{}} |
| core              | lastupdatedat                        | 1437257099                                          |
| core              | public_caldav                        | calendar/share.php                                  |
| core              | public_calendar                      | calendar/share.php                                  |
| core              | public_files                         | files_sharing/public.php                            |
| core              | public_gallery                       | gallery/public.php                                  |
| core              | public_webdav                        | files_sharing/publicwebdav.php                      |
| core              | remote_caldav                        | calendar/appinfo/remote.php                         |
| core              | remote_calendar                      | calendar/appinfo/remote.php                         |
| core              | remote_carddav                       | contacts/appinfo/remote.php                         |
| core              | remote_contacts                      | contacts/appinfo/remote.php                         |
| core              | remote_files                         | files/appinfo/remote.php                            |
| core              | remote_webdav                        | files/appinfo/remote.php                            |
| core              | repairlegacystoragesdone             | yes                                                 |
| core              | shareapi_allow_links                 | no                                                  |
| core              | shareapi_allow_public_upload         | no                                                  |
| core              | shareapi_allow_resharing             | no                                                  |
| files             | enabled                              | yes                                                 |
| files             | installed_version                    | 1.1.9                                               |
| files             | types                                | filesystem                                          |
| files_locking     | enabled                              | yes                                                 |
| files_locking     | installed_version                    |                                                     |
| files_locking     | types                                | filesystem                                          |
| files_pdfviewer   | enabled                              | yes                                                 |
| files_pdfviewer   | installed_version                    | 0.7                                                 |
| files_pdfviewer   | ocsid                                | 166049                                              |
| files_pdfviewer   | types                                |                                                     |
| files_sharing     | enabled                              | yes                                                 |
| files_sharing     | incoming_server2server_share_enabled | no                                                  |
| files_sharing     | installed_version                    | 0.6.2                                               |
| files_sharing     | outgoing_server2server_share_enabled | no                                                  |
| files_sharing     | types                                | filesystem                                          |
| files_texteditor  | enabled                              | yes                                                 |
| files_texteditor  | installed_version                    | 0.4                                                 |
| files_texteditor  | ocsid                                | 166051                                              |
| files_texteditor  | types                                |                                                     |
| files_trashbin    | enabled                              | yes                                                 |
| files_trashbin    | installed_version                    | 0.6.3                                               |
| files_trashbin    | types                                | filesystem                                          |
| files_versions    | enabled                              | yes                                                 |
| files_versions    | installed_version                    | 1.0.6                                               |
| files_versions    | types                                | filesystem                                          |
| files_videoviewer | enabled                              | yes                                                 |
| files_videoviewer | installed_version                    | 0.1.3                                               |
| files_videoviewer | ocsid                                | 166054                                              |
| files_videoviewer | types                                |                                                     |
| firstrunwizard    | enabled                              | yes                                                 |
| firstrunwizard    | installed_version                    | 1.1                                                 |
| firstrunwizard    | ocsid                                | 166055                                              |
| firstrunwizard    | types                                |                                                     |
| gallery           | enabled                              | yes                                                 |
| gallery           | installed_version                    | 0.6.0                                               |
| gallery           | ocsid                                | 166056                                              |
| gallery           | types                                |                                                     |
| provisioning_api  | enabled                              | yes                                                 |
| provisioning_api  | installed_version                    | 0.2                                                 |
| provisioning_api  | types                                | filesystem                                          |
| templateeditor    | enabled                              | yes                                                 |
| templateeditor    | installed_version                    | 0.1                                                 |
| templateeditor    | types                                |                                                     |
| updater           | enabled                              | yes                                                 |
| updater           | installed_version                    | 0.4                                                 |
| updater           | ocsid                                | 166059                                              |
| updater           | types                                |                                                     |
+-------------------+--------------------------------------+-----------------------------------------------------+
79 rows in set (0.01 sec)
```

**Comment by georgehrke** [comment]
> @georgehrke have you heard of such issues before ?

No

> `| calendar          | enabled                              | ["users"] `

Did you enable calendar for a certain group only?

**Comment by ka223** [comment]
yes, but my user is in that group.
I also tested the app without group restrictions, with the same issue ...

**Comment by DeepDiver1975** [comment]
@ka223 please comment these 3 lines - let's see how far we get then:
https://github.com/owncloud/core/blob/master/remote.php#L124-L126

**Comment by ka223** [comment]
ok, no "app not installed" massages

But I can not use caldav and lots of these PHP error messages (as above) if I try to use it.

**Comment by DeepDiver1975** [comment]
> But I can not use caldav and lots of these PHP error messages (as above) if I try to use it.

hmmm .... TBH: I'm out of this game then ... no clue what did break your setup.

Maybe you can try to access the caldav url using cadaver and see what the responses look like?

**Comment by ka223** [comment]
I manually modified nothing in these folders, and only updated the owncloud with the opensuse ppa.
@DeepDiver1975 
Sorry, that I can not provide better results, but thanks for your support.

I do not know "cadaver" ... the wiki says an adventure game ...

The thunderbird calendar respond:
```
Warning: There has been an error reading data for calendar: owncloud.  However, this error is believed to be minor, so the program will attempt to continue. Error code: DAV_NOT_DAV. Description: The resource at https:/****.de/owncloud/remote.php/caldav is either not a DAV collection or not available
```

**Comment by DeepDiver1975** [comment]
http://www.webdav.org/cadaver/

**Comment by ka223** [comment]
```
$ cadaver https:/****.de/owncloud/remote.php/caldav
WARNING: Untrusted server certificate presented for `****.de':
Issued to: Internet Widgits Pty Ltd, Some-State, DE
Issued by: Internet Widgits Pty Ltd, Some-State, DE
Certificate is valid from *** 2015 **** GMT to ***** Feb 2025 *** GMT
Do you wish to accept the certificate? (y/n) y
Could not open collection:
302 Found
dav:/owncloud/remote.php/caldav/? 
```

**Comment by pdtwonotes** [comment]
After my upgrade, I too lost the cal and card apps.  The database has entries similar to ks223 reports, but the web interface does not show either Cal or Card apps available - only "Files".

I do not want to break anything now, so I will delete everything and reinstall in a few weeks.

**Comment by DeepDiver1975** [comment]
@pdtwonotes why reinstall? During upgrade apps get disabled and you have to manually enable them one by one.

**Comment by pdtwonotes** [comment]
I tried that.  I click the Enable button and it says "App directory already exists" and it stays disabled.   Well, of course the app directory still exists.  I should hope that an upgrade does not delete all my calendar and contacts information.

**Comment by georgehrke** [comment]
@pdtwonotes How did you upgrade? If you used your distribution's package-system, what package-source do you use?

> "App directory already exists"

please try deleting the existing directory. There is probably a folder called `calendar` in the `apps` folder, which is located in the installation directory.

**Comment by pdtwonotes** [comment]
I connected to my server using the web interface one day and it told me I had to upgrade.  So I told it to go ahead.  It was not my choice to upgrade at this time.   But perhaps the distro upgrade mechanism had upgraded OC files earlier during a general system upgrade.  This is Arch Linux, using pacman, and upgrades are a regular way of life on Arch.

There is definitely both a 'calendar' and a 'contacts' directory under /usr/share/webapps/owncloud, containing PHP files, etc.

I am not used to upgrades losing major settings and configuration like this.  (I worked many years on corporate server automatic upgrade technologies).   Pacman warns about changes to system configuration files, but it does not know about what specific applications may need for post processing.

**Comment by ka223** [comment]
I added a bunch of errors above, does it make any sense to go further?

Maybe a owncloud backup and reinstall would help?
https://doc.owncloud.org/server/8.0/admin_manual/maintenance/backup.html

**Comment by bcutter** [comment]
Did you enable calendar for a certain group only?

This fixed it for me. Before on OC v8.1.1 no sync of calender events anymore. Without group restriction it immediately worked again. Will check the remaining cal- and carddav related errors in logs. Thanks for the hint. But in general... what a flub :(

**Comment by MorrisJobke** [comment]
> "Undefined index: Please double check the installation guides ↗, and check for any errors or warnings in the log. at /var/www/owncloud/lib/private/l10n/string.php#64"

@bcutter Can I ask you to open a new issue for this. Otherwise it will get lost below here. Thanks.

Closing this ticket then. Please create new tickets if new problems occur. Thanks :)

**Comment by dper** [comment]
I also had badness upgrading and reinstalled from scratch to get things working again. The error was similar or identical to the one opening this issue, IIRC, but I don't have the logs lying around any more, sorry.
