### ISSUE TITLE
Can't upload large files (oc_filecache)

### ISSUE THREAD

**Issue by notaduck** [owncloud/core#17777]
I have a problem with uploading large files ?  
My Owncloud is installed on a Ubuntu 14.04 LTS and connected through to a remote Mysql server,
the connection to owncloud is going through a Nginx Reverseproxy

```
Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`encrypted`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\"3\", \"8\", 1231371487, 396, \"02b84a84f157942c185b5dd3494b5149\", 1231371487, 27, 1, \"27762\", \"45fe04dc83ab3311f79593f75490f8ba\", \"files\\\/Dokumenter\\\/Skole\\\/Design\\\/politikken.rtf\", \"politikken.rtf\", \"5\", \"5\", \"45fe04dc83ab3311f79593f75490f8ba\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5-45fe04dc83ab3311f79593f75490f8ba' for key 'fs_storage_path_hash'","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/db\/connection.php(151): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/var\/www\/owncloud\/lib\/private\/db\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array)\n#4 \/var\/www\/owncloud\/lib\/private\/db\/connection.php(190): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*filecac...', Array, Array)\n#5 \/var\/www\/owncloud\/lib\/private\/files\/cache\/cache.php(322): OC\\DB\\Connection->insertIfNotExist('*PREFIX*filecac...', Array, Array)\n#6 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(225): OC\\Files\\Cache\\Cache->put('files\/Dokumente...', Array)\n#7 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(188): OC\\Files\\Cache\\Scanner->addToCache('files\/Dokumente...', Array, -1)\n#8 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php(208): OC\\Files\\Cache\\Scanner->scanFile('files\/Dokumente...')\n#9 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/directory.php(113): OC\\Connector\\Sabre\\File->put(Resource id #260)\n#10 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('politikken.rtf', Resource id #260)\n#11 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('Dokumenter\/Skol...', Resource id #260, NULL)\n#12 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#13 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#14 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#15 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#16 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#17 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#18 {main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66} 
```

**Comment by RealRancor** [comment]
From the first look it seems to be a dup of: https://github.com/owncloud/core/issues/17683

**Comment by DeepDiver1975** [comment]
@RealRancor I want to day "Thank you" for helping us to fight the bug waves hitting us - much appreciated! 

Feel free to close dups if you like - THX
