### ISSUE TITLE
Sync fails randomly

### ISSUE THREAD

**Issue by nodomain** [owncloud/core#17851]
Hi,

when syncing some files cannot be synced. This is a copy of the client issue, as advised. https://github.com/owncloud/client/issues/3491

Following error occurs. How can this happen and how can this be fixed? Perhaps a hash collision?

```
{"reqId":"RvI6RotnifUtpAZJOOAY","remoteAddr":"2.242.145.108","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`encrypted`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\\\"3\\\", \\\"4\\\", 1437655813, 407525, \\\"71a454fc2175f8b739a81223e8c42c0b\\\", 1437655813, 27, 1, \\\"15364\\\", \\\"65d66885085cc10d771bc8537a418fbb\\\", \\\"files\\\\\\\/xxxxx\\\\\\\/xxxz.pdf\\\", \\\" xxxz.pdf\\\", \\\"4\\\", \\\"4\\\", \\\"65d66885085cc10d771bc8537a418fbb\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-65d66885085cc10d771bc8537a418fbb' for key 'fs_storage_path_hash'\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n
#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n
#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/db\\\/connection.php(151): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n
#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/db\\\/adapter.php(93): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array)\\n
#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/db\\\/connection.php(190): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*filecac...', Array, Array)\\n
#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(322): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*filecac...', Array, Array)\\n
#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(225): OC\\\\Files\\\\Cache\\\\Cache->put('files\\\/Seminar F...', Array)\\n
#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(188): OC\\\\Files\\\\Cache\\\\Scanner->addToCache('files\\\/Seminar F...', Array, -1)\\n
#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(208): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('files\\\/Seminar F...')\\n
#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(113): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #33)\\n
#10 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('6. Skript Hausr...', Resource id #33)\\n
#11 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('Seminar Familie...', Resource id #33, NULL)\\n
#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#13 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#14 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n
#15 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#16 \\\/var\\\/www\\\/html\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n
#17 \\\/var\\\/www\\\/html\\\/remote.php(132): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n
#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66}","level":4,"time":"2015-07-23T14:50:13+02:00"}
```

Newest client and server, Windows 7.
PHP Version 5.6.9-0+deb8u1, Debian 8.1, Apache 2.4.10.

**Comment by PVince81** [comment]
This is like to be the known concurrency case.
This can happen if a scanner is run on the folder (through a concurrent PROPFIND) while at the same time the sync client is uploading a file. If the scanner finds the file first, the entry will be inserted by the scanner and the upload will try to insert it too.

Something like this. But I thought we added code to prevent this recently using an "insert of update" @nickvergessen @MorrisJobke ?

This problem should hopefully disappear with transactional file locking. (https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_experimental.html)

**Comment by nickvergessen** [comment]
You can see the "insert if not exists" part in the error message:
```
INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`encrypted`,`parent`,`path_hash`,`path`,`name`,`storage`)
SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?
FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0
```
with params (first select, second is compare)
```
[
\\\"3\\\", \\\"4\\\", 1437655813, 407525, \\\"71a454fc2175f8b739a81223e8c42c0b\\\", 1437655813, 27, 1, \\\"15364\\\", \\\"65d66885085cc10d771bc8537a418fbb\\\", \\\"files\\\\\\\/xxxxx\\\\\\\/xxxz.pdf\\\", \\\" xxxz.pdf\\\", \\\"4\\\",
\\\"4\\\", \\\"65d66885085cc10d771bc8537a418fbb\\\"
]
```

**Comment by PVince81** [comment]
@nodomain any luck with 8.1.3 and sync client 2.0.1 ?

You can also try setting "filesystem_check_changes" to 0 in your config.php.

**Comment by nodomain** [comment]
All good after migrating to own server with 8.1, activating file system locking via redis and the new client. Issue can be closed.
