### ISSUE TITLE
Stop over backslashing the log !!! Make them useful for admins

### ISSUE THREAD

**Issue by tigerfoot** [owncloud/core#17880]
When a component failed or log something it is almost impossible to find the root cause 

Example trying to activate APCu give a white page. check the log and find this kind of 

```text
{"reqId":"dfcKIkV+ewTaOcAFJpev","remoteAddr":"MASKEDIP","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 OC\\\\HintException: Missing memcache class \\\\OC\\\\Memcache\\\\APCu for local cache\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/srv\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(OC\\\\HintException))\\n#6 {main}\",\"File\":\"\\\/srv\\\/www\\\/owncloud\\\/remote.php\",\"Line\":62}","level":4,"time":"2015-07-26T19:40:33+00:00"}

```
What is the stupid reason to not have a correct path, and url ? 
Escaping is good, backshlashing is evil. ;-)
A path is / and url is / (even under windows, php understand / as path separator)
and \ is a reserved word for php so don't try to fool it and be too much smarter.

**Comment by DeepDiver1975** [comment]
The log is written in json format. 
We neither implement stupid things nor do we try to be tooooo smart

**Comment by tigerfoot** [comment]
Even if you think it's right the path is wrongly writen and not useable by copy and paste.
```\/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php```

Which doesn't allow quick and easy interaction (aka debugging)

```json
Exception: {"Message":"This recurrence rule does not generate any valid instances","Code":0,"Trace":"#0 \/srv\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Component\/VEvent.php(33): Sabre\\VObject\\Recur\\EventIterator->__construct(Object(Sabre\\VObject\\Component\\VEvent))\n#1 \/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(291): Sabre\\VObject\\Component\\VEvent->isInTimeRange(Object(DateTime), Object(DateTime))\n#2 \/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(79): Sabre\\CalDAV\\CalendarQueryValidator->validateTimeRange(Object(Sabre\\VObject\\Component\\VEvent), Object(DateTime), NULL)\n#3 \/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(41): Sabre\\CalDAV\\CalendarQueryValidator->validateCompFilters(Object(Sabre\\VObject\\Component\\VCalendar), Array)\n#4 \/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(145): Sabre\\CalDAV\\CalendarQueryValidator->validate(Object(Sabre\\VObject\\Component\\VCalendar), Array)\n#5 \/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(115): Sabre\\CalDAV\\Backend\\AbstractBackend->validateFilterForObject(Array, Array)\n#6 \/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Calendar.php(427): Sabre\\CalDAV\\Backend\\AbstractBackend->calendarQuery(7, Array)\n#7 \/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(621): Sabre\\CalDAV\\Calendar->calendarQuery(Array)\n#8 \/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(231): Sabre\\CalDAV\\Plugin->calendarQueryReport(Object(DOMDocument))\n#9 [internal function]: Sabre\\CalDAV\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\/8687c...')\n#10 \/srv\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#11 \/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(705): Sabre\\Event\\EventEmitter->emit('report', Array)\n#12 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#13 \/srv\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#14 \/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#15 \/srv\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#16 \/srv\/www\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#17 \/srv\/www\/owncloud\/remote.php(132): require_once('\/srv\/www\/ownclo...')\n#18 {main}","File":"\/srv\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Recur\/EventIterator.php","Line":199}
```

**Comment by LukasReschke** [comment]
You can json decode the message. Or use something like https://github.com/icewind1991/logreader (which is WIP)

**Comment by tigerfoot** [comment]
Would be perfect to name owncloud.log owncloud.log.json thus ... :-)
@LukasReschke thanks for the pointer, this will allow us to read them on ssh console too.
