### ISSUE TITLE
Error Uploading files to OC 8.1

### ISSUE THREAD

**Issue by kaplandani** [owncloud/core#17887]
This is a new installation of OC 8.1 on a CentOS 7. 
Same server holds 8.0.3 server that was fine with these files. 
Client version is 1.8.4

I get connection closed on the client side and this on the server:

this happens on the first upload of the local folder to the server. 

Exception: 
```
{"Message":"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`encrypted`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\"5\", \"6\", 1437959088, 367651, \"c0a13526915aa631b306c032b90b0fcc\", 1437959088, 27, 1, \"89264\", \"77133fc846cc467dd942e84be2ef31c6\", \"files\\\/EGOZ\\\/Joshua-Bin-Nun\\\/\\u05e0\\u05d9\\u05d4\\u05d5\\u05dc \\u05ea\\u05e9\\u05dc\\u05d5\\u05de\\u05d9\\u05dd \\u05dc\\u05e1\\u05e4\\u05e7\\u05d9\\u05dd\\\/\\u05e7\\u05d1\\u05dc\\u05e0\\u05d9\\u05dd \\u05e7\\u05d8\\u05e0\\u05d9\\u05dd \\u05d1\\u05e9\\u05d8\\u05d7\\\/\\u05d4\\u05dc\\u05e4\\u05e8\\u05d9\\u05df \\u05de\\u05d3\\u05d1\\u05e7\\u05d5\\u05ea \\u05d7\\u05d9\\u05e8\\u05d5\\u05dd\\\/\\u05d4\\u05e6\\u05e2\\u05ea \\u05de\\u05d7\\u05d9\\u05e8 \\u05de\\u05d3\\u05d1\\u05e7\\u05d5\\u05ea \\u05e9\\u05d9\\u05dc\\u05d5\\u05d8 \\u05d7\\u05d9\\u05e8\\u05d5\\u05dd \\u05d7\\u05ea\\u05d5\\u05de\\u05d4 \\u05dc\\u05d5\\u05d9.pdf\", \"\\u05d4\\u05e6\\u05e2\\u05ea \\u05de\\u05d7\\u05d9\\u05e8 \\u05de\\u05d3\\u05d1\\u05e7\\u05d5\\u05ea \\u05e9\\u05d9\\u05dc\\u05d5\\u05d8 \\u05d7\\u05d9\\u05e8\\u05d5\\u05dd \\u05d7\\u05ea\\u05d5\\u05de\\u05d4 \\u05dc\\u05d5\\u05d9.pdf\", \"4\", \"4\", \"77133fc846cc467dd942e84be2ef31c6\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-77133fc846cc467dd942e84be2ef31c6' for key 'fs_storage_path_hash'","Code":0,"Trace":"#0 \/home\/clserver\/public_html\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/home\/clserver\/public_html\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/home\/clserver\/public_html\/cloud\/lib\/private\/db\/connection.php(151): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/home\/clserver\/public_html\/cloud\/lib\/private\/db\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array)\n#4 \/home\/clserver\/public_html\/cloud\/lib\/private\/db\/connection.php(190): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*filecac...', Array, Array)\n#5 \/home\/clserver\/public_html\/cloud\/lib\/private\/files\/cache\/cache.php(322): OC\\DB\\Connection->insertIfNotExist('*PREFIX*filecac...', Array, Array)\n#6 \/home\/clserver\/public_html\/cloud\/lib\/private\/files\/cache\/scanner.php(225): OC\\Files\\Cache\\Cache->put('files\/EGOZ\/Josh...', Array)\n#7 \/home\/clserver\/public_html\/cloud\/lib\/private\/files\/cache\/scanner.php(188): OC\\Files\\Cache\\Scanner->addToCache('files\/EGOZ\/Josh...', Array, -1)\n#8 \/home\/clserver\/public_html\/cloud\/lib\/private\/connector\/sabre\/file.php(208): OC\\Files\\Cache\\Scanner->scanFile('files\/EGOZ\/Josh...')\n#9 \/home\/clserver\/public_html\/cloud\/lib\/private\/connector\/sabre\/directory.php(113): OC\\Connector\\Sabre\\File->put(Resource id #270)\n#10 \/home\/clserver\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('???????? ??????...', Resource id #270)\n#11 \/home\/clserver\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('EGOZ\/Joshua-Bin...', Resource id #270, NULL)\n#12 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#13 \/home\/clserver\/public_html\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#14 \/home\/clserver\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#15 \/home\/clserver\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#16 \/home\/clserver\/public_html\/cloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#17 \/home\/clserver\/public_html\/cloud\/remote.php(132): require_once('\/home\/clserver\/pub...')\n#18 {main}","File":"\/home\/clserver\/public_html\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66}
```

**Comment by karlitschek** [comment]
@icewind1991 @DeepDiver1975 any idea how this can happen on a new installation?

**Comment by DeepDiver1975** [comment]
Looks like concurrent scan operations.  

Which database engine is this?

**Comment by kaplandani** [comment]
Mysql

**Comment by kaplandani** [comment]
Can I disable concurrency until this one is fixed ? is it a server / client bug ?

**Comment by PVince81** [comment]
@kaplandani if you are using your storages exclusively through OC, you can disable "discovery of new files" by setting this to 0: https://github.com/owncloud/core/blob/master/config/config.sample.php#L978

**Comment by PVince81** [comment]
and with 8.1.3 and 8.2RC1 there will be transactional file locking https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_transactional.html which should prevent such situations to happen
