### ISSUE TITLE
Misconfigured SSL on remote share breaks client sync

### ISSUE THREAD

**Issue by kordianbruck** [owncloud/core#18022]
So I have several files from a friend via remote sharing on my owncloud. Unfortunately his SSL configuration is broken with the new 8.1 upgrade. This breaks my sync altogether though, as I am getting the following messages in my log:

*cURL error 60: SSL certificate problem: unable to get local issuer certificate*

The exception gets thrown when my OC client trys to sync and the server tries to access the remote host. This results in a 500 - Internal Server Error. 

Would it not be better, that it just does not sync that folder?! Or at least give some hint in the web UI that the sync for that folder is currently broken.

Full error stacktrace:
```

 {"Message":"cURL error 60: SSL certificate problem: unable to get local issuer certificate","Code":0,"Trace":"
#0 /3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(104): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
#1 /3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#2 /3rdparty/react/promise/src/FulfilledPromise.php(24): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#3 /3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#4 /3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#5 /3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(135): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#6 /3rdparty/guzzlehttp/guzzle/src/Client.php(232): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#7 /3rdparty/guzzlehttp/guzzle/src/Client.php(217): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#8 /lib/private/http/client/client.php(181): GuzzleHttp\Client->post('https://ownlcou...', Array)
#9 /apps/files_sharing/lib/external/storage.php(251): OC\Http\Client\Client->post('https://ownlcou...', Array)
#10 /apps/files_sharing/lib/external/storage.php(182): OCA\Files_Sharing\External\Storage->getShareInfo()
#11 /apps/files_sharing/lib/external/storage.php(167): OCA\Files_Sharing\External\Storage->checkStorageAvailability()
#12 /lib/private/files/storage/wrapper/wrapper.php(376): OCA\Files_Sharing\External\Storage->hasUpdated('', 1436967539)
#13 /lib/private/files/cache/watcher.php(89): OC\Files\Storage\Wrapper\Wrapper->hasUpdated('', 1436967539)
#14 /lib/private/files/view.php(1182): OC\Files\Cache\Watcher->checkUpdate('', Array)
#15 /lib/private/connector/sabre/objecttree.php(148): OC\Files\View->getFileInfo('myFolder')
#16 /lib/private/connector/sabre/custompropertiesbackend.php(101): OC\Connector\Sabre\ObjectTree->getNodeForPath('myFolder')
#17 /3rdparty/sabre/dav/lib/DAV/PropertyStorage/Plugin.php(86): OC\Connector\Sabre\CustomPropertiesBackend->propFind('myFolder', Object(Sabre\DAV\PropFind))
#18 [internal function]: Sabre\DAV\PropertyStorage\Plugin->propFind(Object(Sabre\DAV\PropFind), Object(OC\Connector\Sabre\Directory))
#19 /3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#20 /3rdparty/sabre/dav/lib/DAV/Server.php(1016): Sabre\Event\EventEmitter->emit('propFind', Array)
#21 /3rdparty/sabre/dav/lib/DAV/Server.php(936): Sabre\DAV\Server->getPropertiesByNode(Object(Sabre\DAV\PropFind), Object(OC\Connector\Sabre\Directory))
#22 /3rdparty/sabre/dav/lib/DAV/CorePlugin.php(327): Sabre\DAV\Server->getPropertiesForPath('', Array, 1)
#23 [internal function]: Sabre\DAV\CorePlugin->httpPropfind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#24 /3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#25 /3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:PROPFIND', Array)
#26 /3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#27 /apps/files/appinfo/remote.php(83): Sabre\DAV\Server->exec()
#28 /remote.php(132): require_once('/var/www/ownclo...')
#29 {main}","File":"/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php","Line":51}","level":4,"time":"2015-08-02T12:22:53+00:00","method":"PROPFIND","url":"/remote.php/webdav/"}
```

**Comment by LukasReschke** [comment]
> So I have several files from a friend via remote sharing on my owncloud. Unfortunately his SSL configuration is broken with the new 8.1 upgrade.

Self-signed? Is the certificate imported to the user settings?

> Would it not be better, that it just does not sync that folder?! Or at least give some hint in the web UI that the sync for that folder is currently broken.

Yes. Should be handled gracefully.

**Comment by kordianbruck** [comment]
> Self-signed? Is the certificate imported to the user settings?

No, startssl but he is missing the anchor / bundle

**Comment by PVince81** [comment]
Hmmm, normally RequestException should get converted to a StorageNotAvailable exception and just skip the folder.

**Comment by MorrisJobke** [comment]
I have a similiar one with an self-signed cert.

* receive a remote share from a self-signed SSL host
* accept it
* Web UI works just fine - no errors
* try to add a folder to the sync client - broken because of a 500 response

Server log entry:

```
{"reqId":"pzEo\/Y50UsLxuqdTxksH","remoteAddr":"...","app":"webdav","message":"Exception: {\"Message\":\"cURL error 60: SSL certificate problem: certificate has expired\",\"Code\":0,\"Trace\":\"#0 owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(104): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\RingException))\\n#1 owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(24): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(135): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(232): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(217): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 owncloud\\\/lib\\\/private\\\/http\\\/client\\\/client.php(181): GuzzleHttp\\\\Client->post('https:\\\/\\\/cloud.j...', Array)\\n#9 owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/storage.php(251): OC\\\\Http\\\\Client\\\\Client->post('https:\\\/\\\/cloud.j...', Array)\\n#10 owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/storage.php(182): OCA\\\\Files_Sharing\\\\External\\\\Storage->getShareInfo()\\n#11 owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/storage.php(167): OCA\\\\Files_Sharing\\\\External\\\\Storage->checkStorageAvailability()\\n#12 owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(376): OCA\\\\Files_Sharing\\\\External\\\\Storage->hasUpdated('', 1438873890)\\n#13 owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(89): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated('', 1438873890)\\n#14 owncloud\\\/lib\\\/private\\\/files\\\/view.php(1182): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Array)\\n#15 owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php(148): OC\\\\Files\\\\View->getFileInfo('2015 Gothenburg')\\n#16 owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/custompropertiesbackend.php(101): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('2015 Gothenburg')\\n#17 owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropertyStorage\\\/Plugin.php(86): OC\\\\Connector\\\\Sabre\\\\CustomPropertiesBackend->propFind('2015 Gothenburg', Object(Sabre\\\\DAV\\\\PropFind))\\n#18 [internal function]: Sabre\\\\DAV\\\\PropertyStorage\\\\Plugin->propFind(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre\\\\Directory))\\n#19 owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#20 owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1016): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#21 owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(936): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre\\\\Directory))\\n#22 owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(327): Sabre\\\\DAV\\\\Server->getPropertiesForPath('', Array, 1)\\n#23 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropfind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#24 owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#25 owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#26 owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#27 owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#28 owncloud\\\/remote.php(132): require_once('\\\/usr\\\/share\\\/weba...')\\n#29 {main}\",\"File\":\"owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":51}","level":4,"time":"2015-08-09T08:56:57+00:00"}
```

cc @LukasReschke because we discussed it just now in IRC

**Comment by LukasReschke** [comment]
@jancborchardt Would be awesome if you could share a folder to me,

**Comment by MorrisJobke** [comment]
WebDAV response is

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>GuzzleHttp\Exception\RequestException</s:exception>
  <s:message>cURL error 60: SSL certificate problem: certificate has expired</s:message>
</d:error>
```

cc @PVince81 for the Exception translation. 

BTW: This is on a 8.1 instance.

**Comment by PVince81** [comment]
Please try again with more recent ownCloud versions, like 8.2.2.

There is new code that should detect errors and fail more gracefully.

If this problem still occurs with recent versions, feel free to reopen.
