### ISSUE TITLE
permission denied for relation oc_appconfig, after posgres install

### ISSUE THREAD

**Issue by novoxudonoser** [owncloud/core#18023]
Owncloud 8.1, php 5.5, posgres 9.4.4, docker-alpine. After install at first visit:

owncloud log:
```
{"reqId":"ymlcApvsczPBXDGZYKg7","remoteAddr":"172.17.42.1","app":"index","message":"Exception:
 {"Exception":"Doctrine\DBAL\Exception\DriverException","Message":"An exception occurred while executing 'SELECT "configvalue", "appid" FROM "oc_appconfig" WHERE "configkey" = ?' with params ["enabled"]:SQLSTATE[42501]: Insufficient privilege: 7 ERROR: permission denied for relation oc_appconfig","Code":0,"Trace":"
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116):Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT "configv...', Array)
#2 /var/www/owncloud/lib/private/db/connection.php(130): Doctrine\DBAL\Connection->executeQuery('SELECT "configv...', Array, Array, NULL)
#3 /var/www/owncloud/lib/private/appconfig.php(272): OC\DB\Connection->executeQuery('SELECT `configv...', Array)
#4 /var/www/owncloud/lib/private/app/appmanager.php(79): OC\AppConfig->getValues(false, 'enabled')
#5 /var/www/owncloud/lib/private/app/appmanager.php(94): OC\App\AppManager->getInstalledAppsValues()
#6 /var/www/owncloud/lib/private/app.php(246): OC\App\AppManager->getInstalledApps()
#7 /var/www/owncloud/lib/private/app.php(93): OC_App::getEnabledApps()
#8 /var/www/owncloud/lib/base.php(592): OC_App::loadApps(Array)
#9 /var/www/owncloud/lib/base.php(1115): OC::init()
#10 /var/www/owncloud/index.php(38): require_once('/var/www/ownclo...')
#11 {main}","File":"/var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":91}","level":4,"time":"2015-08-03T01:03:49+00:00"}
```

db work ( postgres is root user):
```
CREATE DATABASE owncloud TEMPLATE template0 ENCODING 'UNICODE';
ALTER DATABASE owncloud OWNER TO postgres;
GRANT ALL PRIVILEGES ON DATABASE owncloud TO postgres;
```

**Comment by karlitschek** [comment]
Strange. This works for other postgresql setups. Something must be special in your setup

**Comment by novoxudonoser** [comment]
Wheare can I dig? I installed nginx php-fpm and fresh posgres (in docker contaners), then enterd username pasword etc. at the config page, after thaht it took some time (i fink the db shema was made) and after that at i got this error at /owncloud/files/index.php

**Comment by hugosenari** [comment]
Same problem here.

But if I use 'postgres' (default database name)  created by 'docker run' of postgres, works fine.

I tried here running postgres docker with -e POSTGRES_USER=owncloud (this create [database owncloud](https://github.com/docker-library/postgres/blob/a82c28e1c407ef5ddfc2a6014dac87bcc4955a26/9.4/docker-entrypoint.sh#L64)) worked too.

**Comment by DeepDiver1975** [comment]
To me this is a permission issue within the setup. No issue in the codebase -> close. Thx
