### ISSUE TITLE
Upgrade from 7.0.7 to 8.0.6 broken

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#18031]
### Steps to reproduce
1. Install OC 7.0.7
2. Upload a file and share it by link (probably this step can be skipped)
2. Upgrade to 8.0.6 (currently stable8)
3. Try to login

### Expected behaviour
Users can login

### Actual behaviour
ownCloud isn't loaded

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** stable8 {"installed":true,"maintenance":false,"version":"8.0.6.0","versionstring":"8.0.6 beta1","edition":""}

**Updated from an older ownCloud or fresh install:** upgraded from 7.0.7

**List of activated apps:**

```
Enabled:
 - activity
 - calendar
 - contacts
 - files
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - search_lucene
 - templateeditor
 - updater
Disabled:
 - bookmarks
 - documents
 - external
 - files_encryption
 - files_external
 - files_locking
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth
```

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"fopen(\/opt\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/opt\/owncloud\/lib\/private\/config.php#141","level":3,"time":"2015-08-03T12:10:01+00:00"}
{"reqId":"f6676bd00c748e84e5327a38342a9dd6","remoteAddr":"","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/opt\/owncloud\/lib\/private\/app.php#1232","level":3,"time":"2015-08-03T12:10:53+00:00"}
{"reqId":"f6676bd00c748e84e5327a38342a9dd6","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/opt\/owncloud\/lib\/private\/app.php#1235","level":3,"time":"2015-08-03T12:10:53+00:00"}
{"reqId":"7b804357c079e3654c34e6c8e6a6503e","remoteAddr":"10.40.30.21","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/opt\/owncloud\/lib\/private\/app.php#1232","level":3,"time":"2015-08-03T12:10:54+00:00"}
{"reqId":"7b804357c079e3654c34e6c8e6a6503e","remoteAddr":"10.40.30.21","app":"PHP","message":"Invalid argument supplied for foreach() at \/opt\/owncloud\/lib\/private\/app.php#1235","level":3,"time":"2015-08-03T12:10:54+00:00"}
{"reqId":"7b804357c079e3654c34e6c8e6a6503e","remoteAddr":"10.40.30.21","app":"index","message":"Exception: {\"Message\":\"js file not found: script:miniColors\\\/l10n\\\/en serverroot:\\\/opt\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(156): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(107): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('guest', '')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template.php(197): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/util.php(807): OC_Template::printGuestPage('', 'login', Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/base.php(898): OC_Util::displayLoginPage(Array, Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/base.php(849): OC::handleLogin()\\n#8 \\\/opt\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-08-03T12:10:54+00:00"}
{"reqId":"7b804357c079e3654c34e6c8e6a6503e","remoteAddr":"10.40.30.21","app":"PHP","message":"js file not found: script:miniColors\/l10n\/en serverroot:\/opt\/owncloud at \/opt\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-08-03T12:10:54+00:00"}
{"reqId":"27cfbb3573fd2b0f4d0ac7b7db5e0ecb","remoteAddr":"10.40.30.21","app":"PHP","message":"Class OCA\\Contacts\\Share\\Addressbook contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\Share_Backend::isShareTypeAllowed) at \/opt\/owncloud\/apps\/contacts\/lib\/share\/addressbook.php#130","level":3,"time":"2015-08-03T12:10:55+00:00"}
{"reqId":"97c52b861f6bbacc1e697a0f3a14347c","remoteAddr":"10.40.30.21","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/opt\/owncloud\/lib\/private\/app.php#1232","level":3,"time":"2015-08-03T12:25:27+00:00"}
{"reqId":"97c52b861f6bbacc1e697a0f3a14347c","remoteAddr":"10.40.30.21","app":"PHP","message":"Invalid argument supplied for foreach() at \/opt\/owncloud\/lib\/private\/app.php#1235","level":3,"time":"2015-08-03T12:25:27+00:00"}
{"reqId":"97c52b861f6bbacc1e697a0f3a14347c","remoteAddr":"10.40.30.21","app":"index","message":"Exception: {\"Message\":\"js file not found: script:miniColors\\\/l10n\\\/en serverroot:\\\/opt\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(156): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(107): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('guest', '')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template.php(197): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/util.php(807): OC_Template::printGuestPage('', 'login', Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/base.php(898): OC_Util::displayLoginPage(Array, Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/base.php(849): OC::handleLogin()\\n#8 \\\/opt\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-08-03T12:25:27+00:00"}
{"reqId":"97c52b861f6bbacc1e697a0f3a14347c","remoteAddr":"10.40.30.21","app":"PHP","message":"js file not found: script:miniColors\/l10n\/en serverroot:\/opt\/owncloud at \/opt\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-08-03T12:25:27+00:00"}
```

**Comment by LukasReschke** [comment]
> {"reqId":"97c52b861f6bbacc1e697a0f3a14347c","remoteAddr":"10.40.30.21","app":"PHP","message":"js file not found: script:miniColors\/l10n\/en serverroot:\/opt\/owncloud at \/opt\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-08-03T12:25:27+00:00"}

My guess is that you did not remove calendar and contacts before the update.

**Comment by jvillafanez** [comment]
Yep, that's true.

So options are manually disable / remove those apps before the upgrade, no other options?

**Comment by LukasReschke** [comment]
> So options are manually disable / remove those apps before the upgrade, no other options?

Delete `/apps` before the update and reinstall everything manually is the bullet-proof solution. Data will still stay since it is in the DB.

**Comment by jvillafanez** [comment]
Disabling both app seems to be enough.

@carlaschroder  is this documented? I've seen a couple of posts in the forums but not in the official documentation (I haven't look in depth though)

**Comment by MorrisJobke** [comment]
@LukasReschke @jvillafanez Shouldn't they get disabled?

**Comment by LukasReschke** [comment]
> @LukasReschke @jvillafanez Shouldn't they get disabled?

app.php fun :speak_no_evil:

**Comment by cmonteroluque** [comment]
@carlaschroder moved to have documented (if not already)

**Comment by DeepDiver1975** [comment]
closing this one here - documentation issue is open and assigned to this milestone - THX
