### ISSUE TITLE
No basic authentication headers were found again (owncloud 8.1 + iOS 8.4): iPhone calendar does not see all events

### ISSUE THREAD

**Issue by sophonet** [owncloud/core#18089]
Hi there, after upgrading to owncloud 8.1 on my ubuntu-trusty-server (standard installation which comes from official ubuntu repository on opensuse) one month ago, I am not able to see all calendar entries on iOS 8.4. They are there in the web front-end and in the MacOS calendar application, but not on iOS. When I try to update them on my iPhone (by first de-selecting and then re-selecting the specific calendar on which some events are missing), the owncloud log mentions a few of the issues mentioned above:

```
Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Code":0,"Trace":"
#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(149): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(Sabre\\DAV\\Server), 'ownCloud')\n
#1 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(122): OC\\Connector\\Sabre\\Auth->auth(Object(Sabre\\DAV\\Server), 'ownCloud')\n
#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(Sabre\\DAV\\Server), 'ownCloud')\n
#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n
#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#7 \/var\/www\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n
#8 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n
#9 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}
```

With the curl command above

```
curl -D - -X PROPFIND -k https://user:password@yourhost/remote.php/caldav/
```

I receive a reply with the following xml content:

```
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/">
<d:response><d:href>/remote.php/caldav/</d:href><d:propstat><d:prop><d:getlastmodified>Sun, 02 Aug 2015 14:12:19 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/caldav/principals/</d:href><d:propstat><d:prop><d:getlastmodified>Sun, 02 Aug 2015 14:12:19 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/caldav/calendars/</d:href><d:propstat><d:prop><d:getlastmodified>Sun, 02 Aug 2015 14:12:19 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
```

Any chance how I can do further debugging / solving the problem? I also deleted the CalDav account from my iPhone and added it again - same effect...

This is related to issue #14510, however, since that bug was closed, I was not able to reopen it.

**Comment by karlitschek** [comment]
Can you post this please in the calendar repository including a full bug report using the issue template? Thanks
