### ISSUE TITLE
app:encryption Memory overflow when migrating encryption

### ISSUE THREAD

**Issue by g4challenge** [owncloud/core#18176]
Hello,

I have a serious problem with migrating the encryption from 8.0.5 to 8.1.0-4. When I start the migration process on the system the memory starts filling up quickly on a VPS with 1GB of RAM no swap possible. I turned off every other process, Ubuntu is version 14.04 with about 60 GB of encrypted data.

The result is that either the database crashes or the ssh server stops without any further log or information. No error found in the logs.

Is there a possibility to run it in tranches?

Thanks a lot

**Comment by karlitschek** [comment]
@schiesbn Any idea about the memory consumption?

**Comment by DeepDiver1975** [comment]
> @schiesbn Any idea about the memory consumption?

On vacation this week ..... @icewind1991 can you help out here to fight this? THX

**Comment by cmonteroluque** [comment]
@schiesbn welcome back :). Any ideas?

**Comment by PVince81** [comment]
@g4challenge can you use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

We need logs to be able to pinpoint the issue.

**Comment by schiesbn** [comment]
@g4challenge what kind of user backend do you use? LDAP? Any error messages in your apache or owncloud.log. Would be great if you could use the issue template as suggested by  @PVince81

**Comment by g4challenge** [comment]
### Steps to reproduce
1. Machine with 60GB encrypted Files 
2. Upgrade to 8.1
3. Start the encryption:migration process using 
  
     sudo -u www-data php /var/www/owncloud/occ encryption:migrate

### Expected behaviour
Migration should finish with new encryption keys.

### Actual behaviour
Server stops due to out of memory exception(s). SSH Server stops, Database stops...

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4.7

**Database:** MariaDB 5.5.44

**PHP version:** 5.5.9

**ownCloud version:** 8.1.1 stable

**Updated from an older ownCloud or fresh install:** Updated since OC7

**List of activated apps:** Encryption

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'forcessl' => true,
  'loglevel' => 0,
  'maintenance' => false,
  'theme' => '',
);

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome 44

**Operating system:** Tried with Mac OSX 10.10, Windows 7, Ubuntu 14.04

### Logs
#### Web server error log
```
[Tue Aug 25 13:35:35.599243 2015] [:error] [pid 19349] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Permission\\Response\\Response' not found in /var/www/html/concrete5/concrete/src/Permission/Response/CollectionVersionResponse.php on line 12
[Tue Aug 25 14:11:47.755470 2015] [:error] [pid 19349] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Controller\\AbstractController' not found in /var/www/html/concrete5/concrete/src/Block/BlockController.php on line 21
[Tue Aug 25 14:26:47.752725 2015] [:error] [pid 19349] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Workflow\\Request\\PageRequest' not found in /var/www/html/concrete5/concrete/src/Workflow/Request/DeletePageRequest.php on line 19
[Tue Aug 25 16:07:09.675621 2015] [:error] [pid 19349] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Permission\\Assignment\\Assignment' not found in /var/www/html/concrete5/concrete/src/Permission/Assignment/SitemapAssignment.php on line 3
[Tue Aug 25 17:22:56.975633 2015] [:error] [pid 5189] [client] PHP Fatal error:  Class 'PageController' not found in /var/www/html/concrete5/concrete/src/Page/Controller/PageTypeController.php on line 6
[Tue Aug 25 18:38:43.891166 2015] [:error] [pid 10818] [client ] PHP Fatal error:  Class 'Zend\\Validator\\AbstractValidator' not found in /var/www/html/concrete5/concrete/vendor/zendframework/zend-validator/Zend/Validator/Csrf.php on line 18
[Tue Aug 25 18:57:22.806341 2015] [:error] [pid 13687] [client ] PHP Fatal error:  Class 'Pagerfanta\\Exception\\NotValidCurrentPageException' not found in /var/www/html/concrete5/concrete/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Exception/OutOfRangeCurrentPageException.php on line 20
[Tue Aug 25 20:33:55.568016 2015] [:error] [pid 13733] [client ] PHP Fatal error:  Interface 'Concrete\\Core\\Foundation\\Repetition\\RepetitionInterface' not found in /var/www/html/concrete5/concrete/src/Foundation/Repetition/AbstractRepetition.php on line 11
[Tue Aug 25 21:10:18.156318 2015] [:error] [pid 23082] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Area\\Layout\\Layout' not found in /var/www/html/concrete5/concrete/src/Area/Layout/CustomLayout.php on line 7
[Tue Aug 25 22:26:04.735915 2015] [:error] [pid 23082] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Gathering\\Item\\Item' not found in /var/www/html/concrete5/concrete/src/Gathering/Item/Twitter.php on line 4
[Tue Aug 25 23:41:51.838632 2015] [:error] [pid 13733] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Permission\\Assignment\\Assignment' not found in /var/www/html/concrete5/concrete/src/Permission/Assignment/SitemapAssignment.php on line 3
[Wed Aug 26 00:57:38.651388 2015] [:error] [pid 23082] [client ] PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /var/www/html/concrete5/concrete/vendor/zendframework/zend-queue/tests/ZendQueue/CustomTest.php on line 27
[Wed Aug 26 02:13:38.846457 2015] [:error] [pid 15828] [client 66.249.79.19:34532] PHP Fatal error:  Class 'Concrete\\Core\\Foundation\\Object' not found in /var/www/html/concrete5/concrete/src/Block/BlockType/Set.php on line 9
[Wed Aug 26 03:29:12.989820 2015] [:error] [pid 17811] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Permission\\Assignment\\Assignment' not found in /var/www/html/concrete5/concrete/src/Permission/Assignment/SitemapAssignment.php on line 3
[Wed Aug 26 04:15:24.500491 2015] [:error] [pid 15828] [client ] PHP Fatal error:  Interface 'Pagerfanta\\Adapter\\AdapterInterface' not found in /var/www/html/concrete5/concrete/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Adapter/CallbackAdapter.php on line 20
[Wed Aug 26 04:44:59.603315 2015] [:error] [pid 27660] [client ] PHP Fatal error:  Class 'PageController' not found in /var/www/html/concrete5/concrete/src/Page/Controller/PageTypeController.php on line 6
[Wed Aug 26 05:00:24.617338 2015] [:error] [pid 30562] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Foundation\\Object' not found in /var/www/html/concrete5/concrete/attributes/select/option.php on line 7
[Wed Aug 26 05:30:24.496963 2015] [:error] [pid 30562] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Foundation\\Service\\Provider' not found in /var/www/html/concrete5/concrete/src/Authentication/Type/Google/ServiceProvider.php on line 13
[Wed Aug 26 06:00:46.591792 2015] [:error] [pid 30562] [client ] PHP Fatal error:  Class 'Zend\\Validator\\AbstractValidator' not found in /var/www/html/concrete5/concrete/vendor/zendframework/zend-validator/Zend/Validator/Csrf.php on line 18
[Wed Aug 26 07:16:33.588322 2015] [:error] [pid 5903] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Area\\Layout\\Layout' not found in /var/www/html/concrete5/concrete/src/Area/Layout/CustomLayout.php on line 7
[Wed Aug 26 07:45:24.581915 2015] [:error] [pid 30966] [client ] PHP Fatal error:  Class 'Doctrine\\Common\\Cache\\CacheProvider' not found in /var/www/html/concrete5/concrete/vendor/doctrine/cache/lib/Doctrine/Common/Cache/XcacheCache.php on line 34
[Wed Aug 26 08:32:20.612623 2015] [:error] [pid 30966] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Gathering\\Item\\Item' not found in /var/www/html/concrete5/concrete/src/Gathering/Item/Twitter.php on line 4
[Wed Aug 26 10:12:00.742255 2015] [:error] [pid 21906] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Legacy\\DatabaseItemList' not found in /var/www/html/concrete5/concrete/src/User/Point/ActivityList.php on line 5
[Wed Aug 26 11:03:54.704543 2015] [:error] [pid 27933] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Permission\\Assignment\\Assignment' not found in /var/www/html/concrete5/concrete/src/Permission/Assignment/SitemapAssignment.php on line 3
[Wed Aug 26 11:43:33.212599 2015] [:error] [pid 30538] [client ] PHP Fatal error:  Class 'Symfony\\Component\\EventDispatcher\\Event' not found in /var/www/html/concrete5/concrete/src/Page/PagePathEvent.php on line 5
[Wed Aug 26 12:19:41.737591 2015] [:error] [pid 639] [client ] PHP Fatal error:  Class 'Concrete\\Core\\Workflow\\Request\\PageRequest' not found in /var/www/html/concrete5/concrete/src/Workflow/Request/DeletePageRequest.php on line 19
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"q1lEc9v6o9r4m6w1odXC","remoteAddr":"","app":"no app in context","message":"did not move key \"recovery_8282450c.shareKey\" could not find the corresponding file in \/data\/xxx\/files.Most likely the key was already moved in a previous migration run and is already on the right place.","level":2,"time":"2015-08-26T11:57:04+00:00","method":"--","url":"--"}
{"reqId":"z6h6QV9JGtg6tyOOLA5H","remoteAddr":"","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Doctrine\\\\DBAL\\\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(Doctrine\\\\DBAL\\\\DBALException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":62}","level":4,"time":"2015-08-26T12:08:33+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
```

**Comment by schiesbn** [comment]
The apache error log message are all unrelated to ownCloud also the ownCloud log message are unrelated to the migration step. The whole migration just rename some files/folders there is nothing which should need a lot of memory. Does the error message in your apache log happen while you run the migration? What application is it? Maybe it get somehow in your way?

**Comment by cmonteroluque** [comment]
will close if no additional information is forthcoming
