### ISSUE TITLE
Owncloud fails on downloading or uploading large files

### ISSUE THREAD

**Issue by obsidiannonparity** [owncloud/core#18216]
### Steps to reproduce
Upload or download a large file. Anything over 600MB seems to do the trick. Upload limit is set to 4GB, increased post, and other settings per the owncloud guide but that has not helped. This is also occurring on download or upload. I have attempted via the owncloud desktop sync app and webdav.

### Actual behaviour
Connection aborts and and the file sync either reattempts or fails outright depending on 

### Server configuration
Ubuntu 14.04.2
Apache 2.4.7
PHP 5.5.9
Mysql 5.5.44
Owncloud 8.1.1 (was also occurring in 8.1.0)
Apps Activity, Deleted files, documents, file locking, first run wizard, mail template editor, pdf viewer, pictures, provisioning api, share files, text editor, updater, versions, video viewer, calendar, contacts, files move, mail, news, direct menu, ownnote, and tasks

After the update from 8.1.0 to 8.1.1 most of those apps were disabled and the error still occured during that. 

No external storage

No outside auth

No encryption

### Client configuration
Owncloud Desktop Client
Firefox
Chrome

**Operating system:**
Windows 8
Ubuntu 15.04

#### ownCloud log

{"reqId":"oTuTlC07HON9v+wTVraQ","remoteAddr":"50.59.173.54","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#))\\n#4 \\\/home\\\/cloud\\\/public_html\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home\\\/cloud\\\/public_html\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/home\\\/cloud\\\/public_html\\\/remote.php\",\"Lin,\"Line\":55}","level":4,"time":"2015-08-11T16:15:00+00:00"}

**Comment by DeepDiver1975** [comment]
Desktop sync client and mobile clients use a different mechanism regarding upload compared to regular webdav and the webui.

Anything related to 
>  Upload limit is set to 4GB, increased post, and other settings per the owncloud guide but that has not helped. 

is only relevant for the webui

**Comment by RealRancor** [comment]
@obsidiannonparity Sounds to me like an issue with timeouts.

https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/big_file_upload_configuration.html#configuring-your-webserver

provides some which you could raise.

**Comment by guruz** [comment]
If you start the client with:

```OWNCLOUD_MAX_PARALLEL=1 owcloud --logfile -``` you might see which operation/chunk causes the server error or timeout...

**Comment by MorrisJobke** [comment]
Closing this due to inactivity.

@obsidiannonparity Please reopen this issue if you have further information.
