### ISSUE TITLE
After upgrade to 8.1.1 enabling apps take down owncloud

### ISSUE THREAD

**Issue by kalletabur** [owncloud/core#18315]
### Steps to reproduce
1. Have 8.0.2 owncloud with encryption
2. Upgrade to 8.1.1 (enable memcache, migrate keys etc) so everything works (tested most ordinary stuff, also tested Federated Cloud ID)
3. Go to Apps -> Productivity enable Documents app + enable News app

### Expected behaviour
Documents apps should be working, News app should be working as normal

### Actual behaviour
After enabling Documents app I wanted to verify that app is enabled (on 8.0.4 Documents app was impossible to enable), going to Enabled tab show empty page. Going to another App/Conf page (Files app, Admin page) triggers some new update - User is thrown out and Owncloud Update page is shown. When "Update" is finished and user is let in. Now after going to enable News app owncloud is unresponsible - pages are empty even when going to URL with an another browser

Reloading services or system reboot don't fix

News app wasn't actually important. I just wanted to test whether owncloud starts again updating process - it didn't .. instead disabled owncloud. Maybe installing other apps don't disable owncloud or maybe they do.

### Server configuration
**Operating system**:
Debian 7.8

**Web server:**
NGINX 1.2.1-2.2+wheezy3

**Database:**
MySQL 5.5.44-0+deb7u1

**PHP version:**
PHP 5.4.41-0+deb7u1

**ownCloud version:** (see ownCloud admin page)
8.1.1-1 (this is Debian package version .. cause web interface isn't responding)
8.1.1.3 (version from config.php)

**Updated from an older ownCloud or fresh install:**
8.0.2

**List of activated apps:**
Activity, Deleted files, External storage support, First Run Wizard, LDAP user and group backend, Mail Template Editor, PDF Viewer, Pictures, Server-side Encryption, Share Files, Text Editor, Versions, Video Viewer (taken from earlier issue - web interface is not responding and occ script not working)

Running occ scripts (app:list, config:list,occ ldap:show-config) throws exception:
sudo -u www-data php occ app:list
```
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APC for local cache (Is the matching PHP module installed and enabled ?)

```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '01010101010101',
  'passwordsalt' => '01010101010101',
  'trusted_domains' => 
  array (
    0 => 'oc.example.net',
    1 => '101.101.101.101',
  ),
  'datadirectory' => '/var/ocdatafolder/',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'ocdb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'ocdb_',
  'dbuser' => 'ocuser',
  'dbpassword' => '01010101010101',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => '0',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'oc.example.net',
  'mail_smtpport' => 25,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'secret' => '01010101010101',
  'memcache.local' => '\OC\Memcache\APC',
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:**
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
|appid|configkey|configvalue|
|user_ldap|cleanUpJobOffset|600|
|user_ldap|enabled|yes|
|user_ldap|has_memberof_filter_support|1|
|user_ldap|home_folder_naming_rule||
|user_ldap|installed_version|0.5.0|
|user_ldap|last_jpegPhoto_lookup|0|
|user_ldap|ldap_agent_password||
|user_ldap|ldap_attributes_for_group_search||
|user_ldap|ldap_attributes_for_user_search||
|user_ldap|ldap_backup_host||
|user_ldap|ldap_backup_port||
|user_ldap|ldap_base|DC=example,DC=local|
|user_ldap|ldap_base_groups|DC=example,DC=local|
|user_ldap|ldap_base_users|DC=example,DC=local|
|user_ldap|ldap_cache_ttl|600|
|user_ldap|ldap_configuration_active|1|
|user_ldap|ldap_display_name|displayname|
|user_ldap|ldap_dn|CN=Comp-Ownc,OU=COM,OU=Company,DC=example,DC=local|
|user_ldap|ldap_email_attr|mail|
|user_ldap|ldap_experienced_admin|0|
|user_ldap|ldap_expert_username_attr|sAMAccountName|
|user_ldap|ldap_expert_uuid_group_attr||
|user_ldap|ldap_expert_uuid_user_attr||
|user_ldap|ldap_group_display_name|cn|
|user_ldap|ldap_group_filter|(&(|(objectclass=group))(|(cn=Dev)(CN=Comp-Ownc)(cn=Comp-admis)))|
|user_ldap|ldap_group_filter_mode|0|
|user_ldap|ldap_group_member_assoc_attribute|member|
|user_ldap|ldap_groupfilter_groups|Comp-DevComp-Owncloud Comp-admis|
|user_ldap|ldap_groupfilter_objectclass|group|
|user_ldap|ldap_host|dc300|
|user_ldap|ldap_login_filter|(&(&(|(objectclass=person))(|(memberof=CN=Comp-Ownc,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-Dev,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-admis,OU=DL,OU=Company,DC=example,DC=local)))(samaccountname=%uid))|
|user_ldap|ldap_login_filter_mode|0|
|user_ldap|ldap_loginfilter_attributes||
|user_ldap|ldap_loginfilter_email|0|
|user_ldap|ldap_loginfilter_username|1|
|user_ldap|ldap_nested_groups|0|
|user_ldap|ldap_nocase|1|
|user_ldap|ldap_override_main_server|0|
|user_ldap|ldap_paging_size|500|
|user_ldap|ldap_port|389|
|user_ldap|ldap_quota_attr||
|user_ldap|ldap_quota_def||
|user_ldap|ldap_tls|0|
|user_ldap|ldap_turn_off_cert_check|1|
|user_ldap|ldap_user_filter_mode|1|
|user_ldap|ldap_userfilter_groups||
|user_ldap|ldap_userfilter_objectclass||
|user_ldap|ldap_userlist_filter|(&(|(objectclass=person))(|(memberof=CN=Comp-Ownc,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-Dev,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-SystemAdministrators,OU=DL,OU=Company,DC=example,DC=local)))|
|user_ldap|ocsid|166061|
|user_ldap|types|authentication|

```

### Client configuration
**Browser:**
Chrome, FF

**Operating system:**
Ubuntu 14

#### Web server error log
```

error.log
2015/08/14 10:12:55 [error] 8191#0: *351 access forbidden by rule, client: 101.101.101.101, server: oc.example.net, request: "GET /data/htaccesstest.txt HTTP/1.1", host: "oc.example.net"
2015/08/14 10:16:25 [error] 8191#0: *389 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/owncloud/apps/news/appinfo/application.php on line 51" while reading response header from upstream, client: 192.168.1.4, server: oc.example.net, request: "GET /index.php/settings/ajax/navigationdetect.php?app=168040 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "oc.example.net", referrer: "https://oc.example.net/index.php/settings/apps"

access.log
192.168.1.4 - - [14/Aug/2015:12:35:19 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:40.0) Gecko/20100101 Firefox/40.0"
```

#### ownCloud log (data/owncloud.log)
```
Going to Apps app

enable documents app

Upgrade

{"reqId":"zF4ay1CAKcOrp0yKkE+x","remoteAddr":"192.168.1.4","app":"core","message":"starting upgrade from 8.1.1.3 to 8.1.1.3","level":0,"time":"2015-08-14T10:12:33+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=01010101010101"}
{"reqId":"zF4ay1CAKcOrp0yKkE+x","remoteAddr":"192.168.1.4","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/lib\/private\/eventsource.php:99) at \/var\/www\/owncloud\/lib\/private\/user\/session.php#306","level":3,"time":"2015-08-14T10:12:37+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=01010101010101"}
{"reqId":"zF4ay1CAKcOrp0yKkE+x","remoteAddr":"192.168.1.4","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/lib\/private\/eventsource.php:99) at \/var\/www\/owncloud\/lib\/private\/user\/session.php#307","level":3,"time":"2015-08-14T10:12:37+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=01010101010101"}
{"reqId":"zF4ay1CAKcOrp0yKkE+x","remoteAddr":"192.168.1.4","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/lib\/private\/eventsource.php:99) at \/var\/www\/owncloud\/lib\/private\/user\/session.php#308","level":3,"time":"2015-08-14T10:12:37+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=01010101010101"}
{"reqId":"zF4ay1CAKcOrp0yKkE+x","remoteAddr":"192.168.1.4","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/lib\/private\/eventsource.php:99) at \/var\/www\/owncloud\/lib\/private\/user\/session.php#311","level":3,"time":"2015-08-14T10:12:37+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=01010101010101"}
{"reqId":"zF4ay1CAKcOrp0yKkE+x","remoteAddr":"192.168.1.4","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/lib\/private\/eventsource.php:99) at \/var\/www\/owncloud\/lib\/private\/user\/session.php#312","level":3,"time":"2015-08-14T10:12:37+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=01010101010101"}
{"reqId":"zF4ay1CAKcOrp0yKkE+x","remoteAddr":"192.168.1.4","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/lib\/private\/eventsource.php:99) at \/var\/www\/owncloud\/lib\/private\/user\/session.php#313","level":3,"time":"2015-08-14T10:12:37+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=01010101010101"}



After upgrade is finished

{"reqId":"Z\/ooh7DELn3cf1nNUPHH","remoteAddr":"192.168.1.4","app":"PHP","message":"Declaration of OCA\\Files_Sharing\\External\\Scanner::scanFile() should be compatible with OC\\Files\\Cache\\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL, $lock = true) at \/var\/www\/owncloud\/apps\/files_sharing\/lib\/external\/scanner.php#121","level":3,"time":"2015-08-14T10:12:53+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"Z\/ooh7DELn3cf1nNUPHH","remoteAddr":"192.168.1.4","app":"files_external","message":"Unauthorized","level":3,"time":"2015-08-14T10:12:53+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"Z\/ooh7DELn3cf1nNUPHH","remoteAddr":"192.168.1.4","app":"files_external","message":"Unauthorized","level":3,"time":"2015-08-14T10:12:54+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"Z\/ooh7DELn3cf1nNUPHH","remoteAddr":"192.168.1.4","app":"files_external","message":"Unauthorized","level":3,"time":"2015-08-14T10:12:54+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"Z\/ooh7DELn3cf1nNUPHH","remoteAddr":"192.168.1.4","app":"files_external","message":"Unauthorized","level":3,"time":"2015-08-14T10:12:54+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"Z\/ooh7DELn3cf1nNUPHH","remoteAddr":"192.168.1.4","app":"files_external","message":"Unauthorized","level":3,"time":"2015-08-14T10:12:55+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"YZcdD9hwZyKsXkDrBL8P","remoteAddr":"192.168.1.4","app":"PHP","message":"Declaration of OCA\\Files_Sharing\\External\\Scanner::scanFile() should be compatible with OC\\Files\\Cache\\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL, $lock = true) at \/var\/www\/owncloud\/lib\/autoloader.php#133","level":3,"time":"2015-08-14T10:13:16+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/scan.php?force=false&dir=&requesttoken=01010101010101"}
{"reqId":"l2NX8n6418UrTX1e\/JfH","remoteAddr":"192.168.1.4","app":"core","message":"Exception while scanning storage \"webdav::user1@oc.example.net\/\/remote.php\/webdav\/testisiinmidagi\/\": Sabre\\HTTP\\ClientHttpException: Not Found","level":3,"time":"2015-08-14T10:13:16+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/list.php?dir=%2F&sort=name&sortdirection=asc"}



going to Apps app

{"reqId":"+TGW\/miud\/8\/sTLvPWit","remoteAddr":"192.168.1.4","app":"core","message":"No update found at the ownCloud appstore for app 166056","level":1,"time":"2015-08-14T13:17:36+03:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"+TGW\/miud\/8\/sTLvPWit","remoteAddr":"192.168.1.4","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":1,"time":"2015-08-14T13:17:37+03:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"+TGW\/miud\/8\/sTLvPWit","remoteAddr":"192.168.1.4","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":1,"time":"2015-08-14T13:17:37+03:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"+TGW\/miud\/8\/sTLvPWit","remoteAddr":"192.168.1.4","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":1,"time":"2015-08-14T13:17:37+03:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}


enable news app


{"reqId":"\/fHE6qHLAGQI\/dL5Q2PX","remoteAddr":"192.168.1.4","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_6KZ57e-folder\/news\/vendor\/bin): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#466","level":3,"time":"2015-08-14T13:18:21+03:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php"}
{"reqId":"\/fHE6qHLAGQI\/dL5Q2PX","remoteAddr":"192.168.1.4","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_6KZ57e-folder\/news\/vendor): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#466","level":3,"time":"2015-08-14T13:18:21+03:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php"}
{"reqId":"\/fHE6qHLAGQI\/dL5Q2PX","remoteAddr":"192.168.1.4","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_6KZ57e-folder\/\/news): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#472","level":3,"time":"2015-08-14T13:18:21+03:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php"}
{"reqId":"\/fHE6qHLAGQI\/dL5Q2PX","remoteAddr":"192.168.1.4","app":"PHP","message":"unlink(): No such file or directory at \/var\/www\/owncloud\/lib\/private\/helper.php#468","level":3,"time":"2015-08-14T13:18:22+03:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php"}
{"reqId":"\/fHE6qHLAGQI\/dL5Q2PX","remoteAddr":"192.168.1.4","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_6KZ57e-folder\/news\/vendor\/bin): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#466","level":3,"time":"2015-08-14T13:18:22+03:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php"}
{"reqId":"\/fHE6qHLAGQI\/dL5Q2PX","remoteAddr":"192.168.1.4","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_6KZ57e-folder\/news\/vendor): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#466","level":3,"time":"2015-08-14T13:18:22+03:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php"}
{"reqId":"\/fHE6qHLAGQI\/dL5Q2PX","remoteAddr":"192.168.1.4","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_6KZ57e-folder\/news): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#466","level":3,"time":"2015-08-14T13:18:22+03:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php"}
{"reqId":"\/fHE6qHLAGQI\/dL5Q2PX","remoteAddr":"192.168.1.4","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_6KZ57e-folder): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#472","level":3,"time":"2015-08-14T13:18:22+03:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php"}
{"reqId":"EBE22M6eP1gmvWVG+757","remoteAddr":"192.168.1.4","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":0,"time":"2015-08-14T13:18:22+03:00","method":"GET","url":"\/index.php\/settings\/ajax\/navigationdetect.php?app=168040"}
{"reqId":"EBE22M6eP1gmvWVG+757","remoteAddr":"192.168.1.4","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=user1,ou=example,dc=local\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2015-08-14T13:18:22+03:00","method":"GET","url":"\/index.php\/settings\/ajax\/navigationdetect.php?app=168040"}
{"reqId":"EBE22M6eP1gmvWVG+757","remoteAddr":"192.168.1.4","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-08-14T13:18:22+03:00","method":"GET","url":"\/index.php\/settings\/ajax\/navigationdetect.php?app=168040"}
{"reqId":"EBE22M6eP1gmvWVG+757","remoteAddr":"192.168.1.4","app":"user_ldap","message":"readAttribute: cn=user1,ou=example,dc=local found","level":0,"time":"2015-08-14T13:18:22+03:00","method":"GET","url":"\/index.php\/settings\/ajax\/navigationdetect.php?app=168040"}
{"reqId":"EBE22M6eP1gmvWVG+757","remoteAddr":"192.168.1.4","app":"PHP","message":"syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' at \/var\/www\/owncloud\/apps\/news\/appinfo\/application.php#51","level":3,"time":"2015-08-14T13:18:22+03:00","method":"GET","url":"\/index.php\/settings\/ajax\/navigationdetect.php?app=168040"}


go to enable tab -> screen empty

{"reqId":"xvrTmzMnA5AqAK4X8YR5","remoteAddr":"192.168.1.4","app":"PHP","message":"syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' at \/var\/www\/owncloud\/apps\/news\/appinfo\/application.php#51","level":3,"time":"2015-08-14T13:18:39+03:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=0"}
{"reqId":"5ndD5HGBr4xmqV4XuJTs","remoteAddr":"192.168.1.4","app":"PHP","message":"syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' at \/var\/www\/owncloud\/apps\/news\/appinfo\/application.php#51","level":3,"time":"2015-08-14T13:18:39+03:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}


go to files app -> screen empty

going to new browser

{"reqId":"d23zVZs3llFIuSdJzOAi","remoteAddr":"192.168.1.4","app":"PHP","message":"syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' at \/var\/www\/owncloud\/apps\/news\/appinfo\/application.php#51","level":3,"time":"2015-08-14T13:21:21+03:00","method":"GET","url":"\/favicon.ico"}

```

Screenshots

![no-apps-found-for-your-version-after-documents-app-enable](https://cloud.githubusercontent.com/assets/8167593/9274303/423e4cda-429d-11e5-92e7-2757f21d58d3.png)

![update-message-after-changing-app](https://cloud.githubusercontent.com/assets/8167593/9274304/483ce2c2-429d-11e5-99b9-23085124684f.png)

![app-file-screen-empty](https://cloud.githubusercontent.com/assets/8167593/9274307/50534f6e-429d-11e5-8c5f-5a9b3838062a.png)

**Comment by MorrisJobke** [comment]
Related to #18224 

@LukasReschke You worked on the app management code recently. Can we combine re-activation and upgrade of an app in app management?

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975

**Comment by Raydiation** [comment]
My guess is that the app.php gets loaded after an app update even if the requirements in the info.xml are not met

**Comment by Raydiation** [comment]
Linking relevant issue https://github.com/owncloud/news/issues/838

**Comment by tflidd** [comment]
I have seen the same problem on my test-machine (Debian 7/Apache/PHP 5.4.x/MySQL), upgrade to 8.1.1 (from 8.1.0) via SuSE-repo, that was ok. Owncloud broke after upgrade of News app to latest version.
So news-app requires php 5.5 but for some reason, the php version is not checked before installing this app.

Disabling via occ-command (sudo -u www-data....) fails as well:
````PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/owncloud/apps/news/appinfo/application.php on line 51````
That is really a very bad user experience. I needed to disable the news-app in the database:
````UPDATE `owncloud-osdfj`.`appconfig` SET `configvalue` = 'no' WHERE `appconfig`.`appid` = 'news' AND `appconfig`.`configkey` = 'enabled';````

**Comment by tflidd** [comment]
A small follow up: there is still the background-job in the database causing errors when executing the cron.
The apps-menu is not really consistent. In the section non-activated apps, news is listed with a warning of the php version:
![shot1](https://cloud.githubusercontent.com/assets/8111200/9292634/6980e23a-4405-11e5-8d96-6d01be39abfa.png)
I would expect a similar warning in the multimedia section but there is no warning at all:
![shot2](https://cloud.githubusercontent.com/assets/8111200/9292638/aab23f10-4405-11e5-858d-8da962939251.png)

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by kalletabur** [comment]
As I see it might be related to [News 6.0.0 breaks owncloud] (https://github.com/owncloud/news/issues/838). Ok but how should I now disable News (or any app) if it breaks owncloud?

**Comment by Raydiation** [comment]
@kalletabur according to @PVince81 this should work in the top owncloud directory:

    ./occ app:disable news

**Comment by PVince81** [comment]
you might need to enable maintenance mode first by editing config/config.php and setting "maintenance" to true. This will prevent loading broken apps and should restore core CLI functionality.

**Comment by kalletabur** [comment]
This doesn't work.
I enabled maintenance mode and got error 

``
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APC for local cache (Is the matching PHP module installed and enabled ?)
``

then removed   'memcache.local' => '\OC\Memcache\APC' and error changed

``
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/owncloud/apps/news/appinfo/register_command.php on line 17
``

**Comment by Raydiation** [comment]
Ah, apparently too many internal ifs and hacks. 

Another way would be to connect to the database and run the first command listed here: https://github.com/owncloud/news#how-do-i-reset-the-news-app 

```sql
DELETE FROM oc_appconfig WHERE appid = 'news';
```

**Comment by Raydiation** [comment]
Basically there should be one entry point for apps that parses all info.xml files, does all the dependency checks if the app is upgraded and disables it if needed and finally progresses with execution.

**Comment by kalletabur** [comment]
Deleting from DB works.
But what about this upgrade from 8.1.1.3 to 8.1.1.3.? Is this normal?

**Comment by PVince81** [comment]
@kalletabur yes, it's basically updating the DB for apps, the message is misleading and needs to be fixed.

**Comment by MorrisJobke** [comment]
@Xenopathic Could this also be fixed by #18839?

**Comment by Xenopathic** [comment]
@MorrisJobke Hmm, it would certainly prevent the errors when the News app is disabled, but it doesn't help the case where a broken app can take down the entire oC instance. That issue is being tracked in #17451

**Comment by Regg86** [comment]
I seemed to have the same problem..I upgraded to 8.1.1 Owncloud and after enabling the the gallery app, my owncloud crashed and returned a blank startup screen. I tried deleting the app:gallery from the database as mentioned above... but they system is still down.. appreciate any help..

**Comment by LukasReschke** [comment]
> I am having the same problem..I upgraded to 8.1.1 Owncloud and after upgrade, enabling the gallery app, my owncloud service crashed and returned a blank startup screen. I tried deleting the app:gallery from the database as mentioned above...restart the server, I am not able to get the Owncloud back running.. appreciate any help..

Please take a look in your ownCloud and apache error logs

**Comment by Wermorl** [comment]
Did you get news back to work? I currently get the same error:
```PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/owncloud/apps/news/appinfo/application.php on line 56```
Owncloud Version is 8.2 beta1

**Comment by LukasReschke** [comment]
Aha. You guys are using the news app.

**Comment by LukasReschke** [comment]
The news app requires PHP 5.5 as minimum: https://github.com/owncloud/news/pull/811. Please update.

Let's close this issue then as we're aware of the "app can kill ownCloud" issue and are discussing this at other places.

**Comment by karlitschek** [comment]
argh. another example that we can't just drop support for other software that our users out there still use. this is also true for for important apps. kills the user experience and reputation of ownCloud

**Comment by BernhardPosselt** [comment]
@karlitschek the issue here is a bug which kills the user experience ;)

**Comment by karlitschek** [comment]
an app that wants to have the official tag can't just drop for php 5.4 while it is still officially supported by the rest of ownCloud.

**Comment by BernhardPosselt** [comment]
5.4 is EOL

You can drop the official tag if you want to

**Comment by DeepDiver1975** [comment]
> 5.4 is EOL
> 
> You can drop the official tag if you want to

Sorry @BernhardPosselt - but this is so fuxxing ignorant of you! 

Is there any reason for being such an prick?

**Comment by BernhardPosselt** [comment]
Please let's not get personal. The issue here at hand is that due to a bug in owncloud the php requirement is not checked during upgrade -> app is not properly disabled -> owncloud breaks

**Comment by BernhardPosselt** [comment]
BTW you can always download an older version if you want to run 5.4

**Comment by Wermorl** [comment]
Which one would be the last version to run with 5.4?

**Comment by BernhardPosselt** [comment]
Check https://github.com/owncloud/news/releases

Anything prior to 6

**Comment by Wermorl** [comment]
thanks! Unfortunately it does not work with  8.2 beta1

```
Exception: {"Exception":"BadFunctionCallException","Message":"pinned is not a valid attribute","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php(145): OCP\\AppFramework\\Db\\Entity->setter('pinned', Array)\n#1 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php(69): OCP\\AppFramework\\Db\\Entity->__call('setPinned', Array)\n#2 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php(69): OCA\\News\\Db\\Feed->setPinned('0')\n#3 [internal function]: OCP\\AppFramework\\Db\\Entity::fromRow(Array)\n#4 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php(305): call_user_func('\\\\OCA\\\\News\\\\Db\\\\Fe...', Array)\n#5 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php(324): OCP\\AppFramework\\Db\\Mapper->mapRowToEntity(Array)\n#6 \/var\/www\/owncloud\/apps\/news\/db\/feedmapper.php(77): OCP\\AppFramework\\Db\\Mapper->findEntities('SELECT `feeds`....', Array)\n#7 \/var\/www\/owncloud\/apps\/news\/service\/feedservice.php(76): OCA\\News\\Db\\FeedMapper->findAllFromUser('Martin')\n#8 \/var\/www\/owncloud\/apps\/news\/controller\/itemcontroller.php(103): OCA\\News\\Service\\FeedService->findAll('Martin')\n#9 [internal function]: OCA\\News\\Controller\\ItemController->index(3, NULL, 40, 0, true, false, '')\n#10 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#11 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\News\\Controller\\ItemController), 'index')\n#12 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\News\\Controller\\ItemController), 'index')\n#13 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ItemController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/owncloud\/lib\/private\/route\/router.php(281): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#16 \/var\/www\/owncloud\/lib\/base.php(829): OC\\Route\\Router->match('\/apps\/news\/item...')\n#17 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#18 {main}","File":"\/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php","Line":114} ```

**Comment by BernhardPosselt** [comment]
See https://github.com/owncloud/news/issues/858
