### ISSUE TITLE
file sync fail with filelocking by another process

### ISSUE THREAD

**Issue by jlmttn** [owncloud/core#18375]
### Steps to reproduce
1 New file in a shared directory,
OC client can't upload file with timeout error
No problem with other some other shared directory or own directory
2 afetr retry file is uploaded, available by brower BUT not sync with other users by OCclient

### Expected behaviour
Sync file with the repository and other space

### Actual behaviour
File uploaded, available by internet borwser but not sync bu OCclient

### Server configuration
**Operating system**: 
OpenSuse 13.2
**Web server:** 
apache2, Version 2.4.10, Release 25.1, Architecture: x86_64apache

**Database:**
mysql-community-server, version 5.6.25, release 2.6.2

**PHP version:**
PHP5, version 5.6.1, release 33.1

**ownCloud version:** 
version 8.1.1, release 12.1

**Updated from an older ownCloud or fresh install:**
Update from 8.1.0 to 8.1.1

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - documents: 0.10.1
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.1
 - search_lucene: 0.6.0
 - templateeditor: 0.1

Disabled:
 - encryption
 - external
 - files_antivirus
 - files_external
 - galleryplus
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '*********',
  'passwordsalt' => '*******************************',
  'trusted_domains' => 
  array (
    0 => '****************',
    1 => '*****************’,
    2 => '*****************',
    3 => '*****************',
  ),
  'datadirectory' => '/data/OC',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***************',
  'dbpassword' => ‘********',
  'installed' => true,
  'loglevel' => 4,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'logtimezone' => 'Europe/Brussels',
  'log_rotate_size' => 104857600,
  'log_authfailip' => true,
  'session_lifetime' => 3600,
  'singleuser' => false,
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/srv/www/vhosts/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/srv/www/vhosts/owncloud/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'cron_log' => true,
  'mail_from_address' => 'lepluszen',
  'mail_smtpmode' => 'sendmail',
  'mail_domain' => '*******',
  'secret' => '*……………………………………*',
  'overwrite.cli.url' => '',
);
```

**Are you using external storage, if yes which one:** NA

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 
NO

#### LDAP configuration (delete this part if not used)
NA

### Client configuration
**Browser:**
Firefox
**Operating system:**
WIN7

#### Web server error log
No errors

#### ownCloud log (data/owncloud.log)
```
{"reqId":"JrX3eRjBqGIpZvS9eAYD","remoteAddr":"130.104.100.116","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 Target file  is locked by another process.\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(200): OC\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(OCP\\\\Files\\\\LockNotAcquiredException))\\n#1 \\\/srv\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #29)\\n#2 \\\/srv\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('partage-home\\\/Ol...', Resource id #29, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/srv\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/srv\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/srv\\\/www\\\/vhosts\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/srv\\\/www\\\/vhosts\\\/owncloud\\\/remote.php(132): require_once('\\\/srv\\\/www\\\/vhosts...')\\n#9 {main}\",\"File\":\"\\\/srv\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":450}","level":4,"time":"2015-08-18T09:39:11+02:00"}

{"reqId":"30\/4Hcf77oT1bYSZVjyo","remoteAddr":"","app":"no app in context","message":"Error while running background job: Expected response code 250 but got code \"\", with message \"\"","level":3,"time":"2015-08-18T09:45:43+02:00"}
{"reqId":"30\/4Hcf77oT1bYSZVjyo","remoteAddr":"","app":"PHP","message":"Undefined index: all at \/srv\/www\/vhosts\/owncloud\/apps\/files_versions\/lib\/storage.php#610","level":3,"time":"2015-08-18T09:45:43+02:00"}
{"reqId":"30\/4Hcf77oT1bYSZVjyo","remoteAddr":"","app":"PHP","message":"Undefined index: by_file at \/srv\/www\/vhosts\/owncloud\/apps\/files_versions\/lib\/storage.php#612","level":3,"time":"2015-08-18T09:45:43+02:00"}
{"reqId":"30\/4Hcf77oT1bYSZVjyo","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/srv\/www\/vhosts\/owncloud\/apps\/files_versions\/lib\/storage.php#612","level":3,"time":"2015-08-18T09:45:43+02:00"}
{"reqId":"30\/4Hcf77oT1bYSZVjyo","remoteAddr":"","app":"PHP","message":"ksort() expects parameter 1 to be array, null given at \/srv\/www\/vhosts\/owncloud\/apps\/files_versions\/lib\/storage.php#635","level":3,"time":"2015-08-18T09:45:43+02:00"}
{"reqId":"30\/4Hcf77oT1bYSZVjyo","remoteAddr":"","app":"PHP","message":"reset() expects parameter 1 to be array, null given at \/srv\/www\/vhosts\/owncloud\/apps\/files_versions\/lib\/storage.php#636","level":3,"time":"2015-08-18T09:45:43+02:00"}
```
#### Browser log
NA

Output of .owncloudsync.log
```
#=#=#=# Syncrun started 2015-08-18T10:08:03 until 2015-08-18T10:11:03 (179598 msec)
|0|partage-home/Olivia_Photos/0815  2 à3mois/test.docx|INST_NEW|Up|1439885281||0||2|Error downloading https://*/remote.php/webdav/partage-home/Olivia_Photos/0815  2 à3mois/test.docx - server replied: Internal Server Error|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-08-18T10:11:24 until 2015-08-18T10:16:35 (310863 msec)
08:11:33|1828|Owncloud issues/oc8.1.1.docx|INST_SYNC|Up|1439885345|097703e7593134bb278e48346995be5d|20944||4||0|14613|1439810861|097703e7593134bb278e48346995be5d|00349891oc71668a0cfa|INST_NONE|
|0|partage-home/Olivia_Photos/0815  2 à3mois/test.docx|INST_NEW|Up|1439885281||0||1|Délai d'attente de connexion dépassé|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-08-18T10:17:03 until 2015-08-18T10:17:15 (11630 msec)
|0|partage-home/Olivia_Photos/0815  2 à3mois/test.docx|INST_NEW|Up|1439885281||0||6|Conserver sur liste noire : Error downloading https://*/remote.php/webdav/partage-home/Olivia_Photos/0815  2 à3mois/test.docx - server replied: Locked (Target file  is locked by another process.)|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-08-18T10:18:08 until 2015-08-18T10:18:17 (9152 msec)
|0|partage-home/Olivia_Photos/0815  2 à3mois/test.docx|INST_NEW|Up|1439885281||0||6|Cet élément n'a pas été synchronisé en raison des erreurs précédentes : Error downloading https://*/remote.php/webdav/partage-home/Olivia_Photos/0815  2 à3mois/test.docx - server replied: Locked (Target file  is locked by another process.)|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-08-18T10:18:48 until 2015-08-18T10:18:57 (9377 msec)
|0|partage-home/Olivia_Photos/0815  2 à3mois/test.docx|INST_NEW|Up|1439885281||0||6|Cet élément n'a pas été synchronisé en raison des erreurs précédentes : Error downloading https://*/remote.php/webdav/partage-home/Olivia_Photos/0815  2 à3mois/test.docx - server replied: Locked (Target file  is locked by another process.)|0|0|0|||INST_NONE|
/remote.php/webdav/partage-home/Olivia_Photos/0815  2 à3mois/test.docx - server replied: Locked (Target file  is locked by another process.)|0|0|0|||INST_NONE|
```

**Comment by PVince81** [comment]
Locking can happen sometimes in concurrency situations, however if after retry the file isn't synced automatically it means that the etag update didn't work properly.

Is this a file shared inside ownCloud ? (I see "partage" so probably yes)

**Comment by PVince81** [comment]
Did you upload as owner or recipient of that share ?

**Comment by jlmttn** [comment]
This directory is shared inside OC. I upload as recipent, the owner is a virtual user created for charing files between real users. I can't test with OCclient as the owner user because of hight volume data.
If I run occ files:scan --all the files ares replicated to other OCclients.

**Comment by jlmttn** [comment]
@PVince81 
The problem is on directory "0815 2 à3mois"
![capture](https://cloud.githubusercontent.com/assets/12669590/9330779/a8d4794e-45bb-11e5-8db5-64ded333c85c.PNG)

**Comment by PVince81** [comment]
Is this still happening in 8.2.2 ?

**Comment by PVince81** [comment]
Please try again with 8.2.2 which has improved locking. If the problem persists, please reopen.

**Comment by ktWaran** [comment]
This happened with Server 8.1.0

**Comment by Markus872** [comment]
i have the same problem but im using nextcloud.
