### ISSUE TITLE
Unable to read all files (decryption issue)

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#18407]
### Steps to reproduce
Attempt to open a file within owncloud

### Expected behaviour
File opens with the built-in viewer the browser comes with

### Actual behaviour
It cannot open the file and outputs the error "Can't read file"

In the log I do not see a recent entry but I guess something failed during migration/encryption and ALL my 28 GB in the clouds are unreadable :( :(

When I grep the log with `decrypt` I see this interesting line

```
{"reqId":"Kq0Ckcy+4tndRJhuN\/hb","remoteAddr":"58.28.152.233","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: multikeydecrypt with share key failed:error:04065072:rsa routines:RSA_EAY_PRIVATE_DECRYPT:padding check failed\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(152): OC\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(OCA\\\\Encryption\\\\Exceptions\\\\MultiKeyDecryptException))\\n
#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #31)\\n
#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('M1\\\/home\\\/michael...', Resource id #31, NULL)\\n
#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n
#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n
#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n
#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":454}","level":4,"time":"2015-08-18T06:44:25+00:00"}
```

Maybe it says something?

### Server configuration

```
$   
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

```
$ uname -a      
Linux binarykitchen.com 3.12.27-xenU #1 SMP Thu Aug 28 23:13:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Web server:

```
$ nginx -v
nginx version: nginx/1.8.0
```

Database:

```
$ mysql --version
mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3
```

PHP version:

```
$ php -v
PHP 5.5.27-1+deb.sury.org~trusty+1 (cli) (built: Jul 15 2015 12:14:44) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

ownCloud version:
ownCloud 8.1.1.3 (stable) 

Updated from an older ownCloud or fresh install:
Fresh install via apt-get

```
$ sudo -u www-data php ./occ app:list                                                                                                                                                                      
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.10.1
 - encryption: 1.0.0
 - external: 1.2
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - galleryplus: 13.0.0
 - mozilla_sync: 1.4
 - provisioning_api: 0.2
 - tasks: 0.7.1
 - templateeditor: 0.1
 - videos: 1.0
Disabled:
 - files_external
 - files_trashbin
 - firstrunwizard
 - gallery
 - user_external
 - user_ldap
 - user_webdavauth
```

The content of config/config.php: (Without sensitive data)

```
$ cat config.php                                                                                                                                                                                         1 
<?php
$CONFIG = array (
  'instanceid' => 'oc02ca513338',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 1,
  'logfile' => '/var/log/owncloud.log',
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\OC\Memcache\APCu',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'mail_smtpmode' => 'smtp',
  'secret' => 'xxx',
  'forceSSLforSubdomains' => true,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => 'xxx',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'mail_smtpauthtype' => 'PLAIN',
);

```

Are you using external storage, if yes which one:
None

### Client configuration
Browser:
Firefox 40

Operating system:
Ubuntu 15.04

#### Web server error log

N/A

#### ownCloud log (data/owncloud.log)
N/A

#### Browser log
Irrelevant

**Comment by PVince81** [comment]
@schiesbn can you help ?

**Comment by binarykitchen** [comment]
ping??

**Comment by binarykitchen** [comment]
@schiesbn ping?

**Comment by binarykitchen** [comment]
@everyone can i somehow overwrite all these broken files form my local machine? is there such an option? might be a workaround ...

**Comment by PVince81** [comment]
@binarykitchen you should be able to reupload all the files from your local machine as a workaround.

If you think something went wrong with encryption migration, then it is likely that the encryption keys haven't all be properly copied to the target location. Have a look at https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/encryption_configuration.html#upgrading-encryption-label and also scroll down to "where keys are stored" and check that the files have the keys in the proper location.

I'm closing this bug as it's old. Sorry that you haven't got an answer earlier.
If you still have this issue, please reopen.

**Comment by binarykitchen** [comment]
indeed, this ticket is prehistoric - all works fine for me now since i reinstalled everything with v9.0.2
