### ISSUE TITLE
[php7/oracle] schema migration has issues .....

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#18414]
ORA-00955: name is already used by an existing object

````
Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-00955: name is already used by an existing object in /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
Stack trace:
#0 /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php(214): Doctrine\DBAL\Driver\OCI8\OCI8Exception::fromErrorInfo(Array)
#1 /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php(116): Doctrine\DBAL\Driver\OCI8\OCI8Statement->execute()
#2 /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(935): Doctrine\DBAL\Driver\OCI8\OCI8Connection->query('CREATE TABLE "o...')
#3 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db/mdb2schemamanager.php(168): Doctrine\DBAL\Connection->query('CREATE TABLE "o...')
#4 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db/mdb2schemamanager.php(71): OC\DB\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\DBAL\Schema\Schema))
#5 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db.php(218): OC\DB\MDB2SchemaManager->createDbFromStructure('/home/deepdiver...')
#6 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/installer.php(529): OC_DB::createDbFromStructure('/home/deepdiver...')
#7 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/app.php(1099): OC_Installer::installShippedApp('files_sharing')
#8 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/app.php(286): OC_App::installApp('files_sharing')
#9 /home/deepdiver/Development/ownCloud/master-autotest/tests/enable_all.php(13): OC_App::enable('files_sharing')
#10 /home/deepdiver/Development/ownCloud/master-autotest/tests/enable_all.php(19): enableApp('files_sharing')
#11 {main}

Next Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE "oc_share_external" ("id" NUMBER(10) NOT NULL, "remote" VARCHAR2(512) NOT NULL, "remote_id" NUMBER(10) DEFAULT -1 NOT NULL, "share_token" VARCHAR2(64) NOT NULL, "password" VARCHAR2(64) DEFAULT NULL NULL, "name" VARCHAR2(64) NOT NULL, "owner" VARCHAR2(64) NOT NULL, "user" VARCHAR2(64) NOT NULL, "mountpoint" VARCHAR2(4000) NOT NULL, "mountpoint_hash" VARCHAR2(32) NOT NULL, "accepted" NUMBER(10) DEFAULT 0 NOT NULL, PRIMARY KEY("id"))':

ORA-00955: name is already used by an existing object in /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:61
Stack trace:
#0 /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception))
#1 /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(945): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\OCI8\Driver), Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception), 'CREATE TABLE "o...')
#2 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db/mdb2schemamanager.php(168): Doctrine\DBAL\Connection->query('CREATE TABLE "o...')
#3 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db/mdb2schemamanager.php(71): OC\DB\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\DBAL\Schema\Schema))
#4 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db.php(218): OC\DB\MDB2SchemaManager->createDbFromStructure('/home/deepdiver...')
#5 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/installer.php(529): OC_DB::createDbFromStructure('/home/deepdiver...')
#6 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/app.php(1099): OC_Installer::installShippedApp('files_sharing')
#7 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/app.php(286): OC_App::installApp('files_sharing')
#8 /home/deepdiver/Development/ownCloud/master-autotest/tests/enable_all.php(13): OC_App::enable('files_sharing')
#9 /home/deepdiver/Development/ownCloud/master-autotest/tests/enable_all.php(19): enableApp('files_sharing')
#10 {main}Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-00955: name is already used by an existing object in /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
Stack trace:
#0 /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php(214): Doctrine\DBAL\Driver\OCI8\OCI8Exception::fromErrorInfo(Array)
#1 /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php(116): Doctrine\DBAL\Driver\OCI8\OCI8Statement->execute()
#2 /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(935): Doctrine\DBAL\Driver\OCI8\OCI8Connection->query('CREATE TABLE "o...')
#3 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db/mdb2schemamanager.php(168): Doctrine\DBAL\Connection->query('CREATE TABLE "o...')
#4 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db/mdb2schemamanager.php(71): OC\DB\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\DBAL\Schema\Schema))
#5 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db.php(218): OC\DB\MDB2SchemaManager->createDbFromStructure('/home/deepdiver...')
#6 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/installer.php(529): OC_DB::createDbFromStructure('/home/deepdiver...')
#7 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/app.php(1099): OC_Installer::installShippedApp('files_trashbin')
#8 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/app.php(286): OC_App::installApp('files_trashbin')
#9 /home/deepdiver/Development/ownCloud/master-autotest/tests/enable_all.php(13): OC_App::enable('files_trashbin')
#10 /home/deepdiver/Development/ownCloud/master-autotest/tests/enable_all.php(20): enableApp('files_trashbin')
#11 {main}

Next Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE "oc_files_trash" ("auto_id" NUMBER(10) NOT NULL, "id" VARCHAR2(250) DEFAULT '' NOT NULL, "user" VARCHAR2(64) DEFAULT '' NOT NULL, "timestamp" VARCHAR2(12) DEFAULT '' NOT NULL, "location" VARCHAR2(512) DEFAULT '' NOT NULL, "type" VARCHAR2(4) DEFAULT NULL NULL, "mime" VARCHAR2(255) DEFAULT NULL NULL, PRIMARY KEY("auto_id"))':

ORA-00955: name is already used by an existing object in /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:61
Stack trace:
#0 /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception))
#1 /home/deepdiver/Development/ownCloud/master-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(945): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\OCI8\Driver), Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception), 'CREATE TABLE "o...')
#2 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db/mdb2schemamanager.php(168): Doctrine\DBAL\Connection->query('CREATE TABLE "o...')
#3 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db/mdb2schemamanager.php(71): OC\DB\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\DBAL\Schema\Schema))
#4 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/db.php(218): OC\DB\MDB2SchemaManager->createDbFromStructure('/home/deepdiver...')
#5 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/installer.php(529): OC_DB::createDbFromStructure('/home/deepdiver...')
#6 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/app.php(1099): OC_Installer::installShippedApp('files_trashbin')
#7 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/app.php(286): OC_App::installApp('files_trashbin')
#8 /home/deepdiver/Development/ownCloud/master-autotest/tests/enable_all.php(13): OC_App::enable('files_trashbin')
#9 /home/deepdiver/Development/ownCloud/master-autotest/tests/enable_all.php(20): enableApp('files_trashbin')
#10 {main}
Error during setup
Kill the docker 9da62ace1e70b63a74be0617470f73038040fff08c253e34aa32169b3fd9a96d
9da62ace1e70b63a74be0617470f73038040fff08c253e34aa32169b3fd9a96d

**Comment by DeepDiver1975** [comment]
side effect of #18425
