### ISSUE TITLE
Documents app and MacOs calendar exception: Failed to connect to the database: An exception occured in driver: SQLSTATE Too many connections

### ISSUE THREAD

**Issue by Aurelien-** [owncloud/core#18462]
Hello,

I get the exception: 
`Failed to connect to the database: An exception occured in driver: SQLSTATE Too many connections`
when my MacOs calendar connects to owncloud or when I open the web app Documents to list my documents. Calendar seems to work and Documents also as I get the list of my documents. However, owncloud produce the exceptions given below.

I'am using mysql replication.

## Steps to reproduce:
I don't have another installation on which to try to reproduce the problem. However I did all the migration from 8.0 with manual modification because of the encrytion bug reported somewhere.
The migration to 8.1.1 went with no problem.

## Expected behaviour: 
These logs should not appear? Any hidden problem/misconfiguration?

## Server configuration

Operating system: Debian Jessie 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
Database: mysqld 10.0.21-MariaDB-1~jessie-log with replication
PHP version: 5.6.11-1
ownCloud version: 8.1.1.3
DRBD version: 8.4.3
Openldap-2.4.41+dfsg with replication
Web server: compiled nginx/1.9.4

compilation options: ./configure --user=www-data --group=www-data --with-http_ssl_module --with-http_spdy_module --with-http_secure_link_module --with-mail --with-mail_ssl_module --without-http_ssi_module --without-http_empty_gif_module --add-module=modules/ngx_cache_purge --add-module=modules/naxsi-0.53-2/naxsi_src --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/run/nginx.pid --lock-path=/run/nginx/lock --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log

## Updated from an older ownCloud : 
Yes

## List of activated apps:

Enabled:

    Activity 2.0.1
    Default encryption module 1.0.0
    Deleted files 0.6.3    
    Documents 0.10.1
    External Sites 1.2
    External storage support 0.2.3
    External user support 0.4
    File Locking 
    First Run Wizard 1.1
    LDAP user and group backend 0.6.1
    Mail Template Editor 0.1
    PDF Viewer 0.7
    Pictures 0.6.0
    Provisioning API 0.2
    Share Files 0.6.2
    Text Editor 0.4
    Updater 0.6
    Versions 1.0.6
    Video Viewer 0.1.3
    Calendar 0.7.3
    Contacts 0.4.0.0
    Files Move 0.8.1a
    Mail 0.1.3
    Tasks 0.7.1
    Grauphel: Tomboy note server 0.5.1

## The content of config/config.php:
```
<?php
$CONFIG = array (
  'instanceid' => 'id',
  'passwordsalt' => 'salt',
  'trusted_domains' => 
  array (
    0 => 'my-domain.com',
  ),
  'datadirectory' => '/data/owncloud-data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost:/var/run/mysqld/mysqld.sock',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'pass',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'log_type' => 'syslog',
  'log_file' => '/var/log/nginx/owncloud.log',
  'loglevel' => 0,
  'log_authfailip' => true,
  'log_rotate_size' => 10000000,
  'forcessl' => true,
  'logtimezone' => 'Europe/Paris',
  'theme' => '',
  'maintenance' => false,
  'appstoreenabled' => true,
  'secret' => 'secret',
  'mail_smtpmode' => 'php',
  'memcache.local' => '\\OC\\Memcache\\APCu',
);
```

## Are you using external storage, if yes which one: 
Ext4 on drbd version: 8.4.3
owncloud file www mounted on /dev/shm

## Are you using encryption: 
Yes

## Are you using an external user-backend, if yes which one: 
openldap-2.4.41+dfsg

#### When MacOS Calendar connect.
```
Aug 20 17:48:51 hostname ownCloud[10636]: {index} Exception: {"Exception":"Doctrine\\DBAL\\DBALException","Message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[08004] [1040] Too many connections","Code":0,"Trace":"#0 \/dev\/shm\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(429): OC\\DB\\Connection->connect()\n#1 \/dev\/shm\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 \/dev\/shm\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 \/dev\/shm\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(621): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 \/dev\/shm\/www\/owncloud\/lib\/private\/db\/connection.php(83): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 \/dev\/shm\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Configuration), Object(Doctrine\\Common\\EventManager))\n#6 \/dev\/shm\/www\/owncloud\/lib\/private\/db\/connectionfactory.php(124): Doctrine\\DBAL\\DriverManager::getConnection(Array, Object(Doctrine\\DBAL\\Configuration), Object(Doctrine\\Common\\EventManager))\n#7 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(300): OC\\DB\\ConnectionFactory->getConnection('mysql', Array)\n#8 \/dev\/shm\/www\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#9 \/dev\/shm\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(96): Pimple\\Container->offsetGet('DatabaseConnect...')\n#10 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(695): OC\\AppFramework\\Utility\\SimpleContainer->query('DatabaseConnect...')\n#11 \/dev\/shm\/www\/owncloud\/lib\/private\/db.php(42): OC\\Server->getDatabaseConnection()\n#12 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(208): OC_DB::getConnection()\n#13 \/dev\/shm\/www\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#14 \/dev\/shm\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(96): Pimple\\Container->offsetGet('AppConfig')\n#15 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(641): OC\\AppFramework\\Utility\\SimpleContainer->query('AppConfig')\n#16 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(342): OC\\Server->getAppConfig()\n#17 \/dev\/shm\/www\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#18 \/dev\/shm\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(96): Pimple\\Container->offsetGet('AppManager')\n#19 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(861): OC\\AppFramework\\Utility\\SimpleContainer->query('AppManager')\n#20 \/dev\/shm\/www\/owncloud\/lib\/private\/app.php(238): OC\\Server->getAppManager()\n#21 \/dev\/shm\/www\/owncloud\/lib\/private\/app.php(93): OC_App::getEnabledApps()\n#22 \/dev\/shm\/www\/owncloud\/lib\/base.php(592): OC_App::loadApps(Array)\n#23 \/dev\/shm\/www\/owncloud\/lib\/base.php(1121): OC::init()\n#24 \/dev\/shm\/www\/owncloud\/index.php(38): require_once('\/dev\/shm\/www\/la...')\n#25 {main}","File":"\/dev\/shm\/www\/owncloud\/lib\/private\/db\/connection.php","Line":50}
It appears some time: Aug 20 17:48:55 hostname ownCloud[10633]: {calendar} OC_Calendar_App::generateEventOutput Object contains not event: Array#012(#012    [id] => 0#012    [vevent] => Sabre\VObject\Component\VCalendar Object#012        (#012            [name] => VCALENDAR#012            [children] => Array#012                (#012                    [0] => Sabre\VObject\Property\FlatText Object#012                        (#012                            [delimiter] => ,#012                            [structuredValues:protected] => Array#012                                (#012                                    [0] => N#012                                    [1] => ADR#012                                    [2] => ORG#012                                    [3] => GENDER#012                                    [4] => REQUEST-STATUS#012                                )#012#012                            [minimumPropertyValues:protected] => Array#012                                (#012                                    [N] => 5#012                                    [ADR] => 7#012                                )#012#012                            [name] => VERSION#012                            [group] => #012                            [parameters] => Array#012                                (#012                                )#012#012                            [value:protected] => 2.0#012                            [parent] => Sabre\VObject\Component\VCalendar Object#012 *RECURSION*#012                            [iterator:protected] => #012                            [root:protected] => Sabre\VObject\Component\VCalendar Object#012 *RECURSION*#012                        )#012#012                    [1] => Sabre\VObject\Property\FlatText Object#012                        (#012                            [delimiter] => ,#012                            [structuredValues:protected] => Array#012                                (#012                                    [0] => N#012                                    [1] => ADR#012                                    [2] => ORG#012                                    [3] => GENDER#012                                    [4] => REQUEST-STATUS#012                                )#012#012                            [minimumPropertyValues:protected] => Array#012                                (#012                                    [N] => 5#012                                    [ADR] => 7#012                                )#012#012                            [name] => PRODID#012                            [group] => #012                            [parameters] => Array#012                                (#012                                )#012#012                            [value:protected] => -//ownCloud//NONSGML Contacts 0.4.0.0//EN#012                            [parent] => Sabre\VObject\Component\VCalendar Object#012 *RECURSION*#012                            [iterator:protected] => #012                            [root:protected] => Sabre\VObject\Component\VCalendar Object#012 *RECURSION*#012                        )#012#012                    [2] => Sabre\VObject\Property\FlatText Object#012                        (#012                            [delimiter] => ,#012                            [structuredValues:protected] => Array#012                                (#012                                    [0] => N#012                                    [1] => ADR#012                                    [2] => ORG#012                                    [3] => GENDER#012                                    [4] => REQUEST-STATUS#012                                )#012#012                            [minimumPropertyValues:protected] => Array#012                                (#012                                    [N] => 5#012                                    [ADR] => 7#012                                )#012#012                            [name] => CALSCALE#012                            [group] => #012                            [parameters] => Array#012                                (#012                                )#012#012                            [value:protected] => GREGORIAN#012                            [parent] => Sabre\VObject\Component\VCalendar Object#012 *RECURSION*#012                            [iterator:protected] => #012                            [root:protected] => Sabre\VObject\Component\VCalendar Object#012 *RECURSION*#012                        )#012#012                )#012#012            [parent] => #012            [iterator:protected] => #012            [root:protected] => Sabre\VObject\Component\VCalendar Object#012 *RECURSION*#012        )#012#012    [repeating] => 1#012    [summary] => #012    [calendardata] => BEGIN:VCALENDAR#015#012VERSION:2.0#015#012PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN#015#012CALSCALE:GREGORIAN#015#012END:VCALENDAR#015#012#012)
```

#### When listing documents threw the webgui using Documents app:
```
Aug 20 17:46:09 hostname ownCloud[10388]: {index} Exception: {"Exception":"Doctrine\\DBAL\\DBALException","Message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[08004] [1040] Too many connections","Code":0,"Trace":"#0 \/dev\/shm\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(429): OC\\DB\\Connection->connect()\n#1 \/dev\/shm\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 \/dev\/shm\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 \/dev\/shm\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(621): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 \/dev\/shm\/www\/owncloud\/lib\/private\/db\/connection.php(83): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 \/dev\/shm\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Configuration), Object(Doctrine\\Common\\EventManager))\n#6 \/dev\/shm\/www\/owncloud\/lib\/private\/db\/connectionfactory.php(124): Doctrine\\DBAL\\DriverManager::getConnection(Array, Object(Doctrine\\DBAL\\Configuration), Object(Doctrine\\Common\\EventManager))\n#7 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(300): OC\\DB\\ConnectionFactory->getConnection('mysql', Array)\n#8 \/dev\/shm\/www\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#9 \/dev\/shm\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(96): Pimple\\Container->offsetGet('DatabaseConnect...')\n#10 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(695): OC\\AppFramework\\Utility\\SimpleContainer->query('DatabaseConnect...')\n#11 \/dev\/shm\/www\/owncloud\/lib\/private\/db.php(42): OC\\Server->getDatabaseConnection()\n#12 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(208): OC_DB::getConnection()\n#13 \/dev\/shm\/www\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#14 \/dev\/shm\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(96): Pimple\\Container->offsetGet('AppConfig')\n#15 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(641): OC\\AppFramework\\Utility\\SimpleContainer->query('AppConfig')\n#16 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(342): OC\\Server->getAppConfig()\n#17 \/dev\/shm\/www\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#18 \/dev\/shm\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(96): Pimple\\Container->offsetGet('AppManager')\n#19 \/dev\/shm\/www\/owncloud\/lib\/private\/server.php(861): OC\\AppFramework\\Utility\\SimpleContainer->query('AppManager')\n#20 \/dev\/shm\/www\/owncloud\/lib\/private\/app.php(238): OC\\Server->getAppManager()\n#21 \/dev\/shm\/www\/owncloud\/lib\/private\/app.php(93): OC_App::getEnabledApps()\n#22 \/dev\/shm\/www\/owncloud\/lib\/base.php(592): OC_App::loadApps(Array)\n#23 \/dev\/shm\/www\/owncloud\/lib\/base.php(1121): OC::init()\n#24 \/dev\/shm\/www\/owncloud\/index.php(38): require_once('\/dev\/shm\/www\/la...')\n#25 {main}","File":"\/dev\/shm\/www\/owncloud\/lib\/private\/db\/connection.php","Line":50}
Aug 20 17:46:09 hostname hostname nginx: 2015/08/20 17:46:09 [notice] 9862#0: *23 "^/caldav(.*)$" does not match "/index.php/core/preview.png", client: ip-XXX.XXX.XXX.XXX, server: my-server.com, request: "GET /index.php/core/preview.png?file=%2FPath%2Path%2myfile.doc&x=200&y=200&c=5465204cd937c&forceIcon=0 HTTP/1.1", host: "my-server.com", referrer: "https://my-server.com/index.php/apps/documents/"
```

# Maria db config:
```
[client]
port		= 3306
socket		= /var/run/mysqld/mysqld.sock

[mysqld_safe]
socket		= /var/run/mysqld/mysqld.sock
nice		= 0

[mysqld]
user		= mysql
pid-file	= /var/run/mysqld/mysqld.pid
socket		= /var/run/mysqld/mysqld.sock
port		= 3306
basedir		= /usr
datadir		= /var/lib/mysql
tmpdir		= /tmp
lc_messages_dir	= /usr/share/mysql
lc_messages	= en_US
skip-external-locking
#bind-address		= 127.0.0.1

max_connections		= 1000
connect_timeout		= 5
wait_timeout		= 600
max_allowed_packet	= 16M
#Default 128
thread_cache_size       = 32
sort_buffer_size	= 4M
bulk_insert_buffer_size	= 16M
tmp_table_size		= 32M
max_heap_table_size	= 32M


myisam_recover          = BACKUP
#Default 128M
key_buffer_size		= 32M
#open-files-limit	= 2000
table_open_cache	= 400
myisam_sort_buffer_size	= 512M
concurrent_insert	= 2
read_buffer_size	= 2M
read_rnd_buffer_size	= 1M


query_cache_limit		= 128K
#Default 64M
query_cache_size		= 16M
# for more write intensive setups, set to DEMAND or OFF
#query_cache_type		= DEMAND


general_log_file        = /var/log/mysql/mysql.log
general_log             = 1

log_warnings		= 2
#slow_query_log[={0|1}]
slow_query_log_file	= /var/log/mysql/mariadb-slow.log
long_query_time = 10
#log_slow_rate_limit	= 1000
log_slow_verbosity	= query_plan

server-id		= 2

binlog-ignore-db=test
binlog-ignore-db=information_schema
binlog-ignore-db=mysql
log-slave-updates
replicate-ignore-db=test
replicate-ignore-db=information_schema
replicate-ignore-db=mysql
binlog_format=mixed
report_host		= host1
#auto_increment_increment = 2
#auto_increment_offset	= 1
log_bin			= /var/log/mysql/mariadb-bin
log_bin_index		= /var/log/mysql/mariadb-bin.index
# not fab for performance, but safer
#sync_binlog		= 1
expire_logs_days	= 10
max_binlog_size         = 100M
# slaves
relay_log		= /var/log/mysql/relay-bin
relay_log_index	= /var/log/mysql/relay-bin.index
#relay_log_info_file	= /var/log/mysql/relay-bin.info
#log_slave_updates
#read_only
#sql_mode		= NO_ENGINE_SUBSTITUTION,TRADITIONAL

#innodb_log_file_size	= 50M
innodb_buffer_pool_size	= 512M
innodb_log_buffer_size	= 256K
innodb_file_per_table	= 1
innodb_open_files	= 400
innodb_io_capacity	= 400
innodb_flush_method	= O_DIRECT
#ADDED
innodb_ft_cache_size=1600000
innodb_ft_total_cache_size=32000000


# ssl-ca=/etc/mysql/cacert.pem
# ssl-cert=/etc/mysql/server-cert.pem
# ssl-key=/etc/mysql/server-key.pem



[mysqldump]
quick
quote-names
max_allowed_packet	= 16M

[mysql]
#no-auto-rehash	# faster start of mysql but no tab completition

[isamchk]
key_buffer		= 16M


!includedir /etc/mysql/conf.d/
```

**Comment by karlitschek** [comment]
you should make sure that mariadb accepts more connection then you have as maximum number of running php processes.
