### ISSUE TITLE
ownCloud Client Crashes at Startup

### ISSUE THREAD

**Issue by rasusmilch** [owncloud/core#18535]
After an update on Fedora 22, ownCloud client fails to start with a segmentation fault. This is on a laptop that sleeps, few reboots. I sign out or quit owncloud while tethering to my mobile device and that's when I noticed I could not restart the owncloud client under KDE5.

`Linux t550.susmilch.com 4.1.5-200.fc22.x86_64 #1 SMP Mon Aug 10 23:38:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
```
# dnf info owncloud
Last metadata expiration check performed 2:00:40 ago on Mon Aug 24 12:31:53 2015.
Available Packages
Name        : owncloud
Arch        : noarch
Epoch       : 0
Version     : 8.0.5
Release     : 1.fc22
Size        : 21 M
Repo        : updates
Summary     : Private file sync and share server
URL         : http://owncloud.org
License     : AGPLv3+ and MIT and BSD and CC-BY and CC-BY-SA and GPLv3 and Public
            : Domain and (MPLv1.1 or GPLv2+ or LGPLv2+) and (MIT or GPL+) and (MIT
            : or GPLv2) and ASL 2.0 and LGPLv3
Description : ownCloud gives you universal access to your files through a web
            : interface or WebDAV. It also provides a platform to easily view &
            : sync your contacts, calendars and bookmarks across all your devices
            : and enables basic editing right on the web. ownCloud is extendable
            : via a simple but powerful API for applications and plugins.
```
Here is the backtrace from GDB,
```
#0  0x0000000000000000 in  ()
#1  0x00007ffff782bfc6 in QMenu::actionEvent(QActionEvent*) (this=0xcc1690, e=0x7fffffffd9c0) at widgets/qmenu.cpp:3186
#2  0x00007ffff76ef5d8 in QWidget::event(QEvent*) (this=this@entry=0xcc1690, event=event@entry=0x7fffffffd9c0) at kernel/qwidget.cpp:9034
#3  0x00007ffff7832023 in QMenu::event(QEvent*) (this=0xcc1690, e=0x7fffffffd9c0) at widgets/qmenu.cpp:2650
#4  0x00007ffff76ac4ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=0x7bf700, receiver=0xcc1690, e=0x7fffffffd9c0) at kernel/qapplication.cpp:3717
#5  0x00007ffff76b1976 in QApplication::notify(QObject*, QEvent*) (this=0x7fffffffde00, receiver=0xcc1690, e=0x7fffffffd9c0) at kernel/qapplication.cpp:3500
#6  0x00007ffff317d61b in QCoreApplication::notifyInternal(QObject*, QEvent*) (this=0x7fffffffde00, receiver=receiver@entry=0xcc1690, event=event@entry=0x7fffffffd9c0)
    at kernel/qcoreapplication.cpp:965
#7  0x00007ffff76e6855 in QWidget::insertAction(QAction*, QAction*) (event=0x7fffffffd9c0, receiver=0xcc1690) at ../../src/corelib/kernel/qcoreapplication.h:224
#8  0x00007ffff76e6855 in QWidget::insertAction(QAction*, QAction*) (this=0xcc1690, before=before@entry=0x0, action=0xcced20) at kernel/qwidget.cpp:3277
#9  0x00007ffff76e69aa in QWidget::addAction(QAction*) (this=<optimized out>, action=<optimized out>) at kernel/qwidget.cpp:3228
#10 0x00000000004986f3 in OCC::ownCloudGui::setupContextMenu() (this=this@entry=0x9e8f40) at /usr/src/debug/owncloudclient-1.8.4/src/gui/owncloudgui.cpp:305
#11 0x0000000000499897 in OCC::ownCloudGui::ownCloudGui(OCC::Application*) (this=0x9e8f40, parent=<optimized out>)
    at /usr/src/debug/owncloudclient-1.8.4/src/gui/owncloudgui.cpp:70
#12 0x00000000004604d7 in OCC::Application::Application(int&, char**) (this=0x7fffffffde00, argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/owncloudclient-1.8.4/src/gui/application.cpp:157
#13 0x00000000004501b8 in main(int, char**) (argc=1, argv=0x7fffffffdfd8) at /usr/src/debug/owncloudclient-1.8.4/src/gui/main.cpp:53
```
Here is the listing of the last few updates,
```
# dnf history
Last metadata expiration check performed 2:01:30 ago on Mon Aug 24 12:31:53 2015.
ID     | Command line             | Date a | Action | Altere
-------------------------------------------------------------------------------
    67 | debuginfo-install libffi | 2015-08-24 14:11 | Install        |    4  <
    66 | debuginfo-install freety | 2015-08-24 14:05 | Install        |   15 ><
    65 | debuginfo-install bzip2- | 2015-08-24 08:32 | Install        |  127 ><
    64 | debuginfo-install glibc  | 2015-08-23 23:59 | Install        |    3 ><
    63 | install kernel-debug     | 2015-08-23 23:52 | Install        |    2 > 
    62 | install kernel-debug     | 2015-08-23 23:48 | Install        |    3 *<
    61 | reinstall owncloud-clien | 2015-08-23 23:39 | Reinstall      |    1 ><
    60 | install owncloud-client- | 2015-08-23 12:47 | Install        |    1 ><
    59 | update                   | 2015-08-22 08:38 | E, I, U        |   68 ><
    58 | install filezilla        | 2015-08-21 23:12 | Install        |    1 ><
    57 | remove pulseaudio-qpaeq  | 2015-08-19 21:53 | Erase          |    1 ><
    56 | install pulseaudio-qpaeq | 2015-08-19 21:52 | Install        |    1 ><
    55 | install pulseaudio-equal | 2015-08-19 21:46 | Install        |    4 ><
    54 | update                   | 2015-08-18 21:26 | I, U           |   42 ><
    53 | remove wicd*             | 2015-08-18 20:28 | Erase          |    5 ><
    52 | update                   | 2015-08-17 12:19 | E, I, U        |   57 ><
```
And here is `dnf history info 59` for the update that I believe "broke" owncloud. Keep in mind this is on my laptop that sleeps most of the time. So I do not reboot unless a kernel or other update mandates it.
```
Last metadata expiration check performed 1:53:22 ago on Mon Aug 24 12:31:53 2015.
Transaction ID : 59
Begin time     : Sat Aug 22 08:38:31 2015
Begin rpmdb    : 3193:157160ae8ba2cdff5ea753e7f27524e6bcecea24
End time       :            08:40:49 2015 (138 seconds)
End rpmdb      : 3196:22c6b5a0504888d8fdf75a106fae8a94dcb40b57
User           : Robert Susmilch <rasusmilch>
Return-Code    : Success
Command Line   : update
Transaction performed with:
    Installed     dnf-1.1.0-2.fc22.noarch     @updates
    Installed     rpm-4.12.0.1-12.fc22.x86_64 @updates
Packages Altered:
    Upgraded audit-2.4.3-1.fc22.x86_64                         @updates
    Upgrade        2.4.4-1.fc22.x86_64                         @updates
    Upgraded audit-libs-2.4.3-1.fc22.i686                      @updates
    Upgraded audit-libs-2.4.3-1.fc22.x86_64                    @updates
    Upgrade             2.4.4-1.fc22.i686                      @updates
    Upgrade             2.4.4-1.fc22.x86_64                    @updates
    Upgraded gnupg2-2.1.5-1.fc22.x86_64                        @updates
    Upgrade         2.1.7-1.fc22.x86_64                        @updates
    Upgraded gnupg2-smime-2.1.5-1.fc22.x86_64                  @updates
    Upgrade               2.1.7-1.fc22.x86_64                  @updates
    Upgraded google-chrome-stable-44.0.2403.155-1.x86_64       @google-chrome
    Upgrade                       44.0.2403.157-1.x86_64       @google-chrome
    Erase    kernel-4.0.8-300.fc22.x86_64                      @updates
    Install  kernel-4.1.5-200.fc22.x86_64                      @updates
    Erase    kernel-core-4.0.8-300.fc22.x86_64                 @updates
    Install  kernel-core-4.1.5-200.fc22.x86_64                 @updates
    Erase    kernel-devel-4.0.8-300.fc22.x86_64                @updates
    Install  kernel-devel-4.1.5-200.fc22.x86_64                @updates
    Upgraded kernel-headers-4.1.4-200.fc22.x86_64              @updates
    Upgrade                 4.1.5-200.fc22.x86_64              @updates
    Erase    kernel-modules-4.0.8-300.fc22.x86_64              @updates
    Install  kernel-modules-4.1.5-200.fc22.x86_64              @updates
    Erase    kernel-modules-extra-4.0.8-300.fc22.x86_64        @updates
    Install  kernel-modules-extra-4.1.5-200.fc22.x86_64        @updates
    Upgraded kf5-knotifications-5.12.0-1.fc22.x86_64           @updates
    Upgrade                     5.12.0-2.fc22.x86_64           @updates
    Upgraded libblkid-2.26.2-1.fc22.x86_64                     (unknown)
    Upgrade           2.26.2-3.fc22.x86_64                     @updates
    Upgraded liberation-fonts-common-1:1.07.4-4.fc22.noarch    (unknown)
    Upgrade                          1:1.07.4-6.fc22.noarch    @updates
    Upgraded liberation-mono-fonts-1:1.07.4-4.fc22.noarch      (unknown)
    Upgrade                        1:1.07.4-6.fc22.noarch      @updates
    Upgraded liberation-narrow-fonts-1:1.07.4-4.fc22.noarch    (unknown)
    Upgrade                          1:1.07.4-6.fc22.noarch    @updates
    Upgraded liberation-sans-fonts-1:1.07.4-4.fc22.noarch      (unknown)
    Upgrade                        1:1.07.4-6.fc22.noarch      @updates
    Upgraded liberation-serif-fonts-1:1.07.4-4.fc22.noarch     (unknown)
    Upgrade                         1:1.07.4-6.fc22.noarch     @updates
    Upgraded libfdisk-2.26.2-1.fc22.x86_64                     (unknown)
    Upgrade           2.26.2-3.fc22.x86_64                     @updates
    Upgraded libkgapi-2.2.0-2.fc22.x86_64                      (unknown)
    Upgrade           2.2.0-5.fc22.x86_64                      @updates
    Upgraded libmount-2.26.2-1.fc22.x86_64                     (unknown)
    Upgrade           2.26.2-3.fc22.x86_64                     @updates
    Upgraded libsmartcols-2.26.2-1.fc22.x86_64                 (unknown)
    Upgrade               2.26.2-3.fc22.x86_64                 @updates
    Upgraded libuuid-2.26.2-1.fc22.i686                        (unknown)
    Upgraded libuuid-2.26.2-1.fc22.x86_64                      (unknown)
    Upgrade          2.26.2-3.fc22.i686                        @updates
    Upgrade          2.26.2-3.fc22.x86_64                      @updates
    Upgraded mariadb-1:10.0.20-1.fc22.x86_64                   @updates
    Upgrade          1:10.0.21-1.fc22.x86_64                   @updates
    Upgraded mariadb-common-1:10.0.20-1.fc22.x86_64            @updates
    Upgrade                 1:10.0.21-1.fc22.x86_64            @updates
    Upgraded mariadb-config-1:10.0.20-1.fc22.x86_64            @updates
    Upgrade                 1:10.0.21-1.fc22.x86_64            @updates
    Upgraded mariadb-embedded-1:10.0.20-1.fc22.x86_64          @updates
    Upgrade                   1:10.0.21-1.fc22.x86_64          @updates
    Upgraded mariadb-errmsg-1:10.0.20-1.fc22.x86_64            @updates
    Upgrade                 1:10.0.21-1.fc22.x86_64            @updates
    Upgraded mariadb-libs-1:10.0.20-1.fc22.x86_64              @updates
    Upgrade               1:10.0.21-1.fc22.x86_64              @updates
    Upgraded mariadb-server-1:10.0.20-1.fc22.x86_64            @updates
    Upgrade                 1:10.0.21-1.fc22.x86_64            @updates
    Upgraded openCOLLADA-0-20.git69b844d.fc22.x86_64           (unknown)
    Upgrade              0-24.git3335ac1.fc22.x86_64           @updates
    Upgraded openssh-6.9p1-4.fc22.x86_64                       @updates
    Upgrade          6.9p1-5.fc22.x86_64                       @updates
    Upgraded openssh-askpass-6.9p1-4.fc22.x86_64               @updates
    Upgrade                  6.9p1-5.fc22.x86_64               @updates
    Upgraded openssh-clients-6.9p1-4.fc22.x86_64               @updates
    Upgrade                  6.9p1-5.fc22.x86_64               @updates
    Upgraded openssh-server-6.9p1-4.fc22.x86_64                @updates
    Upgrade                 6.9p1-5.fc22.x86_64                @updates
    Upgraded procps-ng-3.3.10-5.fc22.x86_64                    (unknown)
    Upgrade            3.3.10-8.fc22.x86_64                    @updates
    Upgraded python-idna-1.0-1.fc22.noarch                     (unknown)
    Upgrade              2.0-1.fc22.noarch                     @updates
    Upgraded qt5-qtbase-5.4.2-2.fc22.x86_64                    (unknown)
    Upgrade             5.5.0-15.fc22.x86_64                   @updates
    Upgraded qt5-qtbase-common-5.4.2-2.fc22.noarch             (unknown)
    Upgrade                    5.5.0-15.fc22.noarch            @updates
    Upgraded qt5-qtbase-gui-5.4.2-2.fc22.x86_64                (unknown)
    Upgrade                 5.5.0-15.fc22.x86_64               @updates
    Upgraded qt5-qtdeclarative-5.4.2-2.fc22.x86_64             (unknown)
    Upgrade                    5.5.0-3.fc22.x86_64             @updates
    Upgraded qt5-qtgraphicaleffects-5.4.2-1.fc22.x86_64        (unknown)
    Upgrade                         5.5.0-2.fc22.x86_64        @updates
    Upgraded qt5-qtlocation-5.4.2-1.fc22.x86_64                (unknown)
    Upgrade                 5.5.0-3.fc22.x86_64                @updates
    Upgraded qt5-qtmultimedia-5.4.2-1.fc22.x86_64              (unknown)
    Upgrade                   5.5.0-3.fc22.x86_64              @updates
    Upgraded qt5-qtquickcontrols-5.4.2-1.fc22.x86_64           (unknown)
    Upgrade                      5.5.0-3.fc22.x86_64           @updates
    Upgraded qt5-qtscript-5.4.2-1.fc22.x86_64                  (unknown)
    Upgrade               5.5.0-3.fc22.x86_64                  @updates
    Upgraded qt5-qtsensors-5.4.2-1.fc22.x86_64                 (unknown)
    Upgrade                5.5.0-3.fc22.x86_64                 @updates
    Upgraded qt5-qtsvg-5.4.2-1.fc22.x86_64                     (unknown)
    Upgrade            5.5.0-3.fc22.x86_64                     @updates
    Upgraded qt5-qttools-5.4.2-3.fc22.x86_64                   @updates
    Upgrade              5.5.0-4.fc22.x86_64                   @updates
    Upgraded qt5-qttools-common-5.4.2-3.fc22.noarch            @updates
    Upgrade                     5.5.0-4.fc22.noarch            @updates
    Upgraded qt5-qttools-libs-designer-5.4.2-3.fc22.x86_64     @updates
    Upgrade                            5.5.0-4.fc22.x86_64     @updates
    Upgraded qt5-qtwebkit-5.4.2-1.fc22.x86_64                  (unknown)
    Upgrade               5.5.0-4.fc22.x86_64                  @updates
    Upgraded qt5-qtx11extras-5.4.2-1.fc22.x86_64               (unknown)
    Upgrade                  5.5.0-2.fc22.x86_64               @updates
    Upgraded qt5-qtxmlpatterns-5.4.2-1.fc22.x86_64             (unknown)
    Upgrade                    5.5.0-3.fc22.x86_64             @updates
    Upgraded selinux-policy-3.13.1-128.8.fc22.noarch           @updates
    Upgrade                 3.13.1-128.10.fc22.noarch          @updates
    Upgraded selinux-policy-targeted-3.13.1-128.8.fc22.noarch  @updates
    Upgrade                          3.13.1-128.10.fc22.noarch @updates
    Upgraded stoken-libs-0.81-2.fc22.x86_64                    (unknown)
    Upgrade              0.90-2.fc22.x86_64                    @updates
    Upgraded tzdata-2015e-1.fc22.noarch                        @updates
    Upgrade         2015f-1.fc22.noarch                        @updates
    Upgraded tzdata-java-2015e-1.fc22.noarch                   @updates
    Upgrade              2015f-1.fc22.noarch                   @updates
    Upgraded util-linux-2.26.2-1.fc22.x86_64                   (unknown)
    Upgrade             2.26.2-3.fc22.x86_64                   @updates
    Upgraded yum-utils-1.1.31-505.fc22.noarch                  (unknown)
    Upgrade            1.1.31-508.fc22.noarch                  @updates
Scriptlet output:
   1 Redirecting to /bin/systemctl start  atd.service
```
This is my first backtrace so if this is incorrect please let me know.

**Comment by RealRancor** [comment]
Hi,

> This is my first backtrace so if this is incorrect please let me know.

unfortunately you've picked the wrong repository. The one for the sync-client is available here:

https://github.com/owncloud/client/issues

When re-opeing there you could also use the issue template provided here:

https://github.com/owncloud/client/blob/master/CONTRIBUTING.md#bug-reporting-guidelines
