### ISSUE TITLE
Apache error: Error dispatching request to : (sending stdin)

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#18534]
```apache
[Mon Aug 24 10:53:24.789898 2015] [proxy_fcgi:error] [pid 11139] (32)Broken pipe: [client 89.132.195.247:1124] AH01075: Error dispatching request to : (sending stdin)
[Mon Aug 24 10:53:24.859573 2015] [proxy_fcgi:error] [pid 11135] (32)Broken pipe: [client 89.132.195.247:1119] AH01075: Error dispatching request to : (sending stdin)
[Mon Aug 24 10:53:27.180464 2015] [proxy_fcgi:error] [pid 11153] (32)Broken pipe: [client 89.132.195.247:1131] AH01075: Error dispatching request to : (sending stdin)
[Mon Aug 24 10:53:27.261375 2015] [proxy_fcgi:error] [pid 11154] (32)Broken pipe: [client 89.132.195.247:1133] AH01075: Error dispatching request to : (sending stdin)
[Mon Aug 24 10:53:29.375057 2015] [proxy_fcgi:error] [pid 11155] (32)Broken pipe: [client 89.132.195.247:1137] AH01075: Error dispatching request to : (sending stdin)
[Mon Aug 24 10:53:29.509502 2015] [proxy_fcgi:error] [pid 11156] (32)Broken pipe: [client 89.132.195.247:1139] AH01075: Error dispatching request to : (sending stdin)
[Mon Aug 24 10:53:29.605737 2015] [proxy_fcgi:error] [pid 11157] (32)Broken pipe: [client 89.132.195.247:1141] AH01075: Error dispatching request to : (sending stdin)
```
The client shows:
![occlient](https://cloud.githubusercontent.com/assets/952007/9449402/aead4e90-4aa2-11e5-894d-10047c4923ea.jpg)

Lastest oc and client.

*Nem írható* means not writable.

### Steps to reproduce
1. Upload folders with a lot of JPEG images by WindowsXP client

### Expected behaviour
We get no Apache errors

### Actual behaviour
There are Apache errors and errors in the clietn window

### Server configuration
**Operating system**: Debian 8.1 amd64

**Web server:** Apache 2.4 MPM-ITK

**Database:** MariaDB 10.0

**PHP version:** 5.6

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** 8.1

**List of activated apps:** (relevant) gallery

```
 - activity: 2.0.1
 - audios: 1.2.2
 - direct_menu: 0.3
 - encryption: 1.0.0
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking:
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - storagecharts2: 2.6.1
 - templateeditor: 0.1
 - updater: 0.6
```

**The content of config/config.php:**

```
occ config:list system --public

  [InvalidArgumentException]
  There are no commands defined in the "config" namespace.

  'trusted_domains' =>.
  array (
    0 => '*.net',
  ),
  'datadirectory' => '/home/owncloud/website/data',
  'overwrite.cli.url' => 'https://*.net',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'admin',
  'mail_domain' => '*.net',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'loglevel' => 2,
  'asset-pipeline.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'appstore.experimental.enabled' => true,
  'maintenance' => false,

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 31

**Operating system:** Windows XP SP3

### Logs
(above)

#### Web server error log
(above)

#### ownCloud log (data/owncloud.log)
```
{"reqId":"5PmTlruQQo9KO3rtC476","remoteAddr":"89.132.195.247","app":"webdav","message":"Exception: {\"Message\":\"Could not obtain lock type 1 on \\
\"/home/owncloud/website/data/andrea/files/y-szerver/FOTOK KICSI/\\u00d6csi 30 kicsi/DSCN2291.JPG.ocTransferId18957362
58.part".\",\"Code\":0,\"Trace\":\"#0 /home/owncloud/website/html/apps/files_locking/lib/lockingwrapper.php(45): OCA\F
iles_Locking\Lock->addLock(1, Resource id #421)
#1 /home/owncloud/website/html/apps/files_locking/lib/lockingwrapper.ph
p(172): OCA\Files_Locking\LockingWrapper->getLock('files/y-szerver...', 1, Resource id #421)
#2 /home/owncloud/website/html\\
\/lib/private/files/storage/wrapper/encryption.php(624): OCA\Files_Locking\LockingWrapper->fopen('files/y-szerver...', 'r')
#3 /home/owncloud/website/html/lib/private/files/storage/wrapper/encryption.php(692): OC\Files\Storage\Wrap
per\Encryption->readFirstBlock('files/y-szerver...')
#4 /home/owncloud/website/html/lib/private/files/storage/wra
pper/encryption.php(722): OC\Files\Storage\Wrapper\Encryption->getHeader('files/y-szerver...')
#5 /home/owncloud/websit
e/html/lib/private/files/storage/wrapper/encryption.php(217): OC\Files\Storage\Wrapper\Encryption->getEncryptionMod
ule('files/y-szerver...')
#6 [internal function]: OC\Files\Storage\Wrapper\Encryption->unlink('files/y-szerver...')
#7 /hom
e/owncloud/website/html/apps/files_trashbin/lib/storage.php(143): call_user_func_array(Array, Array)
#8 /home/owncloud\
\\/website/html/apps/files_trashbin/lib/storage.php(94): OCA\Files_Trashbin\Storage->doDelete('files/y-szerver...', 'unlink'
)
#9 /home/owncloud/website/html/lib/private/connector/sabre/file.php(150): OCA\Files_Trashbin\Storage->unlink('f
iles/y-szerver...')
#10 /home/owncloud/website/html/lib/private/connector/sabre/directory.php(113): OC\Connector\
\\\Sabre\File->put(Resource id #292)
#11 /home/owncloud/website/html/3rdparty/sabre/dav/lib/DAV/Server.php(1053):
 OC\Connector\Sabre\Directory->createFile('DSCN2291.JPG', Resource id #292)
#12 /home/owncloud/website/html/3rdparty/sa
bre/dav/lib/DAV/CorePlugin.php(513): Sabre\DAV\Server->createFile('y-szerver/FOTOK...', Resource id #292, NULL)
#13 [internal
 function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#14 /home/owncloud/w
ebsite/html/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#15 /home/owncloud/
website/html/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)
#16 /ho
me/owncloud/website/html/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\\\
\HTTP\Request), Object(Sabre\HTTP\Response))
#17 /home/owncloud/website/html/apps/files/appinfo/remote.php(83): S
abre\DAV\Server->exec()
#18 /home/owncloud/website/html/remote.php(132): require_once('/home/owncloud/...')
#19 {m
ain}\",\"File\":\"/home/owncloud/website/html/apps/files_locking/lib/lock.php\",\"Line\":257}","level":4,"time":"2015-08-24T
16:18:41+00:00"}
```

#### Browser log
-

**Comment by szepeviktor** [comment]
Is it a thumbnail generation-related issue?

**Comment by fossxplorer** [comment]
@szepeviktor 
Can you please use the issue template and provide more details: 4https://raw.githubusercontent.com/owncloud/core/master/issue_template.md.

**Comment by szepeviktor** [comment]
@fossxplorer Thank you!
I've found this in oc log:
`Could not obtain lock type 1 on`

**Comment by szepeviktor** [comment]
I've reported for the first time with this template.

**Comment by PVince81** [comment]
Hmm strange, the stack trace above shows that it's an upload (PUT method) but it is calling the trashbin's "doDelete" function.

**Comment by szepeviktor** [comment]
Could it be related to `Could not obtain lock type 1`?

**Comment by PVince81** [comment]
No, that is happening later as a consequence of that code path.
I'd like to check why it is even going there.

Are you overwriting the pictures or are they brand new ?

**Comment by szepeviktor** [comment]
There are only zero length files: `DSCN2288.JPG.ocTransferId1470891348.part`
So I think brand new.

**Comment by PVince81** [comment]
Ok got it, the reason why unlink is called is because of the **failed** upload, so it tries to delete the stray part file and that deletion clashes with locking... nice...

So we have two problems:
1) why is the upload failing in the first place
2) deletion of part files for failed uploads fails with files_locking

**Comment by PVince81** [comment]
I can't reproduce this locally.

@szepeviktor is the upload problem happening for any uploaded file or does it always happen ? Or randomly ?
Can you try temporarily disabling the "files_locking" app ?

**Comment by szepeviktor** [comment]
Yes. I've just disabled it.
Now I ask the user to report the state of her client software. And of course watching logs...

**Comment by szepeviktor** [comment]
Do you have any other idea what to test?

**Comment by szepeviktor** [comment]
We have got the same error.
This is the first-ish run of the client. It has never succeeded to upload those image files.

**Comment by PVince81** [comment]
Did you try disabling files_locking ?

**Comment by szepeviktor** [comment]
Yes, see https://github.com/owncloud/core/issues/18534#issuecomment-134696193

**Comment by PVince81** [comment]
Is this still happening with 8.2.2 ?

**Comment by szepeviktor** [comment]
I've stopped using OC.
