### ISSUE TITLE
 After upgrade to 8.1.1 - Bookmark upload via Xmarks and WebDAV fails

### ISSUE THREAD

**Issue by jletzel** [owncloud/core#18661]
### Client configuration
- Ubuntu 14.04
- Firefox 40.0.3
- Xmarks 4.3.7.1-signed
- URI for sync is: http://darkpi:8008/remote.php/webdav/bookmarks.txt

### Steps to reproduce
1. Do changes on local bookmarks
2. Try to synchronize with OC or make complete upload of bookmarks (via addon settings)

### Expected behaviour
Successful sync.

### Actual behaviour
Failed with HTTP status 400 (Bad Request). Owncloud.log says
```
{"reqId":"OBgB9LCwxoPwbq1xIebx","remoteAddr":"192.168.178.38","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 81675 got 0\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/darkcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #181)\\n#1 \\\/var\\\/www\\\/darkcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('bookmarks.txt', Resource id #181, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/darkcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/darkcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/darkcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/darkcloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/darkcloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/darkcl...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/darkcloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":144}","level":4,"time":"2015-08-28T20:40:41+00:00"}
```

### Server configuration
**Operating system**: Raspbian (Linux 3.4.90 #2 SMP PREEMPT Tue Aug 5 14:11:40 CST 2014 armv7l) on BananaPi

**Web server:** Apache/2.2.22 (Debian)

**Database:** mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (armv7l) using readline 6.2

**PHP version:** PHP 5.4.44-0+deb7u1 (cli) (built: Aug 27 2015 17:22:22) 

**ownCloud version:** 8.1.1.3

**Updated from an older ownCloud or fresh install:** Upgrade from 8.0.x via web updater

**List of activated apps:**

```
    Enabled:
     - bookmarks: 0.4
     - calendar: 0.7.3
     - contacts: 0.4.0.0
     - encryption: 1.0.0
     - files: 1.1.10
     - files_sharing: 0.6.2
     - files_texteditor: 0.4
     - firstrunwizard: 1.1
     - gallery: 0.6.0
     - notes: 1.0.0
     - templateeditor: 0.1
     - updater: 0.6
    Disabled:
     - activity
     - admin_dependencies_chk
     - documents
     - external
     - files_external
     - files_locking
     - files_pdfviewer
     - files_trashbin
     - files_versions
     - files_videoviewer
     - provisioning_api
     - search_lucene
     - user_external
     - user_ldap
     - user_webdavauth
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc8qghi17t9v',
  'passwordsalt' => 'SECRET',
  'secret' => 'SECRET',
  'trusted_domains' =>
  array (
    0 => 'darkpi',
  ),
  'datadirectory' => '/var/www/darkcloud/data',
  'overwrite.cli.url' => 'http://darkpi:8008/darkcloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'installed' => '1',
  'dbname' => 'DarkCloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_CloudMaster1',
  'dbpassword' => 'SECRET',
  'theme' => '',
  'maintenance' => false,
);
```

### References/Hints
- Original forum post 
https://forum.owncloud.org/viewtopic.php?f=31&t=30136
- Maybe same as https://github.com/owncloud/core/issues/17712 ?

**Comment by Xenopathic** [comment]
Correct, exactly the same as #17712. Another php://input getting read twice issue... It's funny how you get nothing for months, then suddenly in a week you get 3 issues caused by the same thing.

cc @LukasReschke @PVince81

**Comment by PVince81** [comment]
@Xenopathic can we maybe make a special ticket for the php://input issue or did we have a PR we could point to instead ?
