### ISSUE TITLE
en@pirate is not a valid locale

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18680]
### Steps

1. Setup OC 7.0.6
1. Set locale to "en@pirate"
1. Upgrade to OC 8.0.6
1. Open the files app

### Expected result
Files app works

### Actual result
Files app broken due to oc.js error:

```
{"reqId":"b5ca6133ee355d759ef2778df9e67822","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Message\":\"'en@pirate' is not a valid locale identifier\",\"Code\":10001,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/punic\\\/punic\\\/code\\\/Data.php(481): Punic\\\\Data::getLocaleAlternatives('en@pirate')\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/punic\\\/punic\\\/code\\\/Data.php(124): Punic\\\\Data::getLocaleFolder('en@pirate')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/punic\\\/punic\\\/code\\\/Calendar.php(647): Punic\\\\Data::get('calendar', 'en@pirate')\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/l10n.php(519): Punic\\\\Calendar::getDateFormat('short', 'en@pirate')\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/core\\\/js\\\/config.php(42): OC_L10N->getDateFormat()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(252): call_user_func('\\\\x00lambda_261', Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(791): OC\\\\Route\\\\Router->match('\\\/core\\\/js\\\/oc.js')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/punic\\\/punic\\\/code\\\/Data.php\",\"Line\":507}","level":4,"time":"2015-08-30T15:05:17+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=c278b0678681887118bdf1bae4e1f3d6"}
```

@DeepDiver1975 looks like the new punic doesn't accept "en@pirate" as locale ?

CC @tflidd

**Comment by Xenopathic** [comment]
Arr! This be bad!

**Comment by DeepDiver1975** [comment]
Update punic?

Add magic to choose en within punic

**Comment by PVince81** [comment]
Works for me in 9.0 RC1
