### ISSUE TITLE
New added external storage (SMB) does not get scanned

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#18718]
### Steps to reproduce
1. create a new instance with "sudo ocdev setup base --dir xxxx" and finalize the setup
2. enable external storage support
3. ceate an smb share and change to files

### Expected behaviour
when changing to files, scanning should start (check also with htop)

### Actual behaviour
nothig happens,
it startet once when I logged off and logged on again (waited until finished),
added a second smb share, changed to files, nothing, logged off/on - nothing...

### Server configuration
**Operating system** ubuntu 14.04

**Web server:** nginx 1.9.4

**Database:** mysql 14.14

**PHP version:** php5-fpm 5.5.9

**ownCloud version:** ownCloud 8.2 pre alpha (git)

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** default, external storage support

**The content of config/config.php:**
```
  'version' => '8.2.0.4',
  'logtimezone' => 'Europe/Vienna',
  'installed' => true,
  'memcache.local' => '\OC\Memcache\APCu',
  'assetdirectory' => '/var/www/xxx',
  'asset-pipeline.enabled' => true,
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' =>
    array (
      'OC\Preview\PNG',
      'OC\Preview\JPEG',
      'OC\Preview\GIF',
      'OC\Preview\Illustrator',
      'OC\Preview\Postscript',
      'OC\Preview\Photoshop',
      'OC\Preview\TIFF',
      'OC\Preview\Raw',
    ),
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:** Opera

**Operating system:** W7x64

#### Web server error log
```
none
```

#### ownCloud log (data/owncloud.log)
```
cat owncloud.log (entries only regarding initial setup...)

{"reqId":"Quk0EAqYo3gmIu7dsa6G","remoteAddr":"212.204.110.133","app":"PHP","message":"fopen(\/xxx\/config\/config.php): f
ailed to open stream: No such file or directory at \/xxx\/lib\/private\/config.php#188","level":3,"time":"2015-08-31T15:5
2:35+00:00"}
{"reqId":"Ic1nHloR89K3K9vH+NII","remoteAddr":"212.204.110.133","app":"PHP","message":"Undefined offset: 0 at \/xxx\/lib\/
private\/setup\/mysql.php#45","level":3,"time":"2015-08-31T15:55:13+00:00"}
```

**Comment by PVince81** [comment]
Do you see a call to "ajax/scan.php" in the network console of the browser ? (or in the access log)

**Comment by mmattel** [comment]
I just have given this a test again and checked for ajax/scan.php in the nginx access log for this webpage.

I have reset the instance like it would have been just fresh installed.
The first creation of a SMB mount let the scanner run and after a minute it was done sucessfully.
The second SMB mount was created but the scanner did not start.

In both cases the nginx access log showed: 
"GET /index.php/apps/files/ajax/scan.php?force=false&dir=&requesttoken=xxxxx"
This log entry came up more than once and stopped after I logged out of from the browser.

But what I also have identified that there is something poping up in the nginx error log:

````
2015/09/16 21:01:36 [error] 21473#21473: *1779 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction' in /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
Stack trace:
#0 /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(57): PDO->exec('DELETE FROM `oc...')
#1 /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(993): Doctrine\DBAL\Driver\PDOConnection->exec('DELETE FROM `oc...')
#2 /xxx/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)
#3 /xxx/lib/private/lock/dblockingprovider.php(156): OC\DB\Connection->executeUpdate('DELETE FROM `*P...')
#4 /xxx/lib/private/lock/dblockingprovider.php(160): OC\Lock\DBLockingProvider->cleanEmptyLocks()
#5 [internal function]: OC\Lock\DBLockingProvider->__destruct()
#6 {main}

Next e" while reading upstream, client: y.y.y.y, server: zzzz, request: "GET /index.php/apps/files HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "zzzz", referrer: "https://zzzz/index.php/settings/admin"
2015/09/16 21:02:27 [error] 21473#21473: *1779 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction' in /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
Stack trace:
#0 /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(57): PDO->exec('DELETE FROM `oc...')
#1 /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(993): Doctrine\DBAL\Driver\PDOConnection->exec('DELETE FROM `oc...')
#2 /xxx/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)
#3 /xxx/lib/private/lock/dblockingprovider.php(156): OC\DB\Connection->executeUpdate('DELETE FROM `*P...')
#4 /xxx/lib/private/lock/dblockingprovider.php(160): OC\Lock\DBLockingProvider->cleanEmptyLocks()
#5 [internal function]: OC\Lock\DBLockingProvider->__destruct()
#6 {main}

Next e" while reading upstream, client: y.y.y.y, server: zzzz, request: "GET /index.php/core/js/oc.js?v=988b4dc16847b1b0e32b8858fadf15be HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "zzzz", referrer: "https://zzzz/index.php/apps/files"
2015/09/16 21:03:17 [error] 21473#21473: *1779 upstream timed out (110: Connection timed out) while reading upstream, client: y.y.y.y, server: zzzz, request: "GET /index.php/apps/files/ajax/scan.php?force=false&dir=&requesttoken=ssss HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "zzzz", referrer: "https://zzzz/index.php/apps/files"
2015/09/16 21:03:19 [error] 21473#21473: *1779 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction' in /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
Stack trace:
#0 /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(57): PDO->exec('DELETE FROM `oc...')
#1 /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(993): Doctrine\DBAL\Driver\PDOConnection->exec('DELETE FROM `oc...')
#2 /xxx/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)
#3 /xxx/lib/private/lock/dblockingprovider.php(156): OC\DB\Connection->executeUpdate('DELETE FROM `*P...')
#4 /xxx/lib/private/lock/dblockingprovider.php(160): OC\Lock\DBLockingProvider->cleanEmptyLocks()
#5 [internal function]: OC\Lock\DBLockingProvider->__destruct()
#6 {main}

Next e...
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /xxx/cron.php:0" while reading upstream, client: y.y.y.y, server: zzzz, request: "GET /cron.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "zzzz", referrer: "https://zzzz/index.php/apps/files"
2015/09/16 21:03:19 [error] 21473#21473: *1779 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction' in /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
Stack trace:
#0 /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(57): PDO->exec('DELETE FROM `oc...')
#1 /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(993): Doctrine\DBAL\Driver\PDOConnection->exec('DELETE FROM `oc...')
#2 /xxx/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)
#3 /xxx/lib/private/lock/dblockingprovider.php(156): OC\DB\Connection->executeUpdate('DELETE FROM `*P...')
#4 /xxx/lib/private/lock/dblockingprovider.php(160): OC\Lock\DBLockingProvider->cleanEmptyLocks()
#5 [internal function]: OC\Lock\DBLockingProvider->__destruct()
#6 {main}

Next e" while reading upstream, client: y.y.y.y, server: zzzz, request: "GET /index.php/avatar/mmattel-oclg/184 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "zzzz", referrer: "https://zzzz/index.php/apps/files"
2015/09/16 21:03:19 [error] 21473#21473: *1779 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction' in /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
Stack trace:
#0 /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(57): PDO->exec('DELETE FROM `oc...')
#1 /xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(993): Doctrine\DBAL\Driver\PDOConnection->exec('DELETE FROM `oc...')
#2 /xxx/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)
#3 /xxx/lib/private/lock/dblockingprovider.php(156): OC\DB\Connection->executeUpdate('DELETE FROM `*P...')
#4 /xxx/lib/private/lock/dblockingprovider.php(160): OC\Lock\DBLockingProvider->cleanEmptyLocks()
#5 [internal function]: OC\Lock\DBLockingProvider->__destruct()
#6 {main}

Next e" while reading upstream, client: y.y.y.y, server: zzzz, request: "GET /index.php/apps/files_sharing/api/externalShares HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "zzzz", referrer: "https://zzzz/index.php/apps/files"
````

**Comment by PVince81** [comment]
I had it worked just now on master / 9.0, had to run cron.php several times / set last_run to 0 then run cron.

**Comment by PVince81** [comment]
It should now in 9.0.2 through the background job.
