### ISSUE TITLE
Update from 8.0.3 to 8.1.1: RouteNotFoundException "calendar_index"

### ISSUE THREAD

**Issue by Af0x** [owncloud/core#18738]
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.

**Comment by karlitschek** [comment]
can you please post a full bug report using the issue template? 
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by Helios07** [comment]
I would like to repoen the ticket since I think that is has not been fixed yet.

### Steps to reproduce
1. Start with an ownCloud installation running 8.1.x with calender app enabled
2. Update it to 8.1.x+1

### Expected behaviour
occ upgrade should run withour errors

### Actual behaviour
[root@zivcloudtest owncloud8.1.3]# sudo -u apache php occ upgrade --skip-migration-test
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Updated database
Disabled 3rd-party app: calendar
Disabled 3rd-party app: contacts
Disabled 3rd-party app: documents
Disabled 3rd-party app: galleryplus
Disabled 3rd-party app: mozilla_sync
Update 3rd-party app: calendar
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.
Update failed
Maintenance mode is kept active

### Server configuration
**Operating system**:
Happened with CentOS 6 and Ubuntu 15.04

**Web server:**
Apache 2.4

**Database:**
mySQL

**PHP version:**
5.5

**ownCloud version:** (see ownCloud admin page)
8.1.1

**Updated from an older ownCloud or fresh install:**
Updated from older than at least OC 7

**List of activated apps:**
See above


**The content of config/config.php:**


If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

Hmm, this does not work in 8.1.3

or 
```
  'datadirectory' => '/mnt/cloud01/cloud/owncloud4.0.4',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'owncloud-na',
  'dbhost' => 'zivcloudtestsql',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud-na',
  'installed' => true,
  'overwritewebroot' => '/owncloud',
  'forcessl' => true,
  'maintenance' => false,
  'ldapIgnoreNamingRules' => false,
  'overwrite.cli.url' => '/owncloud',
  'forceSSLforSubdomains' => true,
  'theme' => '',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'logtimezone' => 'Europe/Berlin',
  'activity_expire_days' => 180,
  'appstore.experimental.enabled' => true,
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
In one case LDAP, in the other case none

#### LDAP configuration (delete this part if not used)
Since this also happens without LDAP, I am pretty sure, it has no influence

### Logs
#### Web server error log
Nothing related

#### ownCloud log (data/owncloud.log)
```
{"reqId":"uIP5ojc1OMS9xcFCtuBV","remoteAddr":"","app":"update","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"calendar_index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/route\\\/router.php(306): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('calendar_index', Array, false)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/route\\\/cachingrouter.php(53): OC\\\\Route\\\\Router->generate('calendar_index', Array, false)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/urlgenerator.php(65): OC\\\\Route\\\\CachingRouter->generate('calendar_index', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/helper.php(139): OC\\\\URLGenerator->linkToRoute('calendar_index', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/public\\\/util.php(306): OC_Helper::linkToRoute('calendar_index', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/apps\\\/calendar\\\/appinfo\\\/app.php(30): OCP\\\\Util::linkToRoute('calendar_index')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/app.php(139): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/app.php(120): OC_App::requireAppFile('calendar')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/app.php(1173): OC_App::loadApp('calendar', false)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/installer.php(218): OC_App::updateApp('calendar')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/installer.php(248): OC_Installer::updateApp(Array)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/updater.php(487): OC_Installer::updateAppByOCSId('168707')\\n#12 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/updater.php(308): OC\\\\Updater->upgradeAppStoreApps(Array)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/updater.php(195): OC\\\\Updater->doUpgrade('8.1.3.0', '8.1.2.1')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/core\\\/command\\\/upgrade.php(181): OC\\\\Updater->upgrade()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Command\\\/Command.php(253): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#16 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(874): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#17 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(195): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#18 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(126): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#19 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/lib\\\/private\\\/console\\\/application.php(94): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#20 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/console.php(68): OC\\\\Console\\\\Application->run()\\n#21 \\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/occ(11): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud8.1.3\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":4,"time":"2015-09-16T10:26:23+02:00"}
```
