### ISSUE TITLE
[8.1.1] broken external WebDAV storage connection

### ISSUE THREAD

**Issue by RalfWW** [owncloud/core#18829]
### Steps to reproduce
1. Create a WebDAV-Connection to a external Storage, in my case hidrive,
2. Get "green" during definition for OK
3. Try to access the configured drive via fila browser
### Expected behaviour

Just show content of the external drive
### Actual behaviour

Get an error message "unbekannter Fehler" (unknown error)
### Server configuration

Strato hosting

**Web server:**

**Database:**

**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
8.1.1
**Updated from an older ownCloud or fresh install:**
Update from 7.0.9 -> 8.0.7 -> 8.1.1
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
WebDAV to Strato Hidrive Service
### Client configuration

Firefox 40.0.3 German

**Operating system:**
WIN 7 pro SP1 German 64bit
#### ownCloud log (data/owncloud.log)

```
{"reqId":"VelUf8CoKK8AAC0FsC8AAAAl","remoteAddr":"84.175.142.110","app":"files","message":"Exception: {\"Exception\":\"Sabre\\\\HTTP\\\\ClientHttpException\",\"Message\":\"Forbidden\",\"Code\":403,\"Trace\":\"
#0 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(233): Sabre\\\\HTTP\\\\Client->send(Object(Sabre\\\\HTTP\\\\Request))\\n
#1 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(262): Sabre\\\\DAV\\\\Client->propFind('.hidrive', Array)\\n
#2 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(690): OC\\\\Files\\\\Storage\\\\DAV->propfind('.hidrive')\\n
#3 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(605): OC\\\\Files\\\\Storage\\\\DAV->getPermissions('.hidrive')\\n
#4 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(149): OC\\\\Files\\\\Storage\\\\Common->getMetaData('.hidrive')\\n
#5 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(543): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getMetaData('.hidrive')\\n
#6 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(113): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData('.hidrive')\\n
#7 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(141): OC\\\\Files\\\\Cache\\\\Scanner->getData('.hidrive')\\n
#8 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(344): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('.hidrive', 3, 160, NULL, true)\\n
#9 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(267): OC\\\\Files\\\\Cache\\\\Scanner->scanChildren('', false, 3, Array, true)\\n
#10 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(91): OC\\\\Files\\\\Cache\\\\Scanner->scan('', false)\\n
#11 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/view.php(1182): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Array)\\n
#12 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/files\\\/filesystem.php(861): OC\\\\Files\\\\View->getFileInfo('\\\/hidrive', true)\\n
#13 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/apps\\\/files\\\/ajax\\\/list.php(35): OC\\\\Files\\\\Filesystem::getFileInfo('\\\/hidrive')\\n
#14 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/mnt\\\/weba\\\/b2\\\/60...')\\n
#15 [internal function]: __lambda_func(Array)\\n
#16 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func('\\\\x00lambda_5', Array)\\n
#17 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n
#18 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/index.php(40): OC::handleRequest()\\n
#19 {main}\",\"File\":\"\\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":154}","level":4,"time":"2015-09-04T08:21:21+00:00"}

```

**Comment by PVince81** [comment]
It looks like it's getting a 403 when doing a PROPFIND on a remote folder called ".hidrive". Is that a special folder ?

I would still expect the scanner to not stop at such errors, ignore them and continue scanning.

@icewind1991 @Xenopathic

**Comment by icewind1991** [comment]
#19128 should make it ignore the folder properly

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
