### ISSUE TITLE
External Local storage issue with non-English characters in files and folders names

### ISSUE THREAD

**Issue by iG8R** [owncloud/core#18909]
### Steps to reproduce
0. Enable "External Storage App" in Apps 
1. Go to Admin -> External Storage
2. Choose "Local"
3. Enter "Folder name" e.g. in Russian
4. In the "Configuration" enter full path of the directory that contains e.g. Russian characters in its name.
5. In the "Available for" enter the user what you want

### Expected behaviour
I'm expecting to see "green circle" near the "Folder name" and starting to use this folder in OC.

### Actual behaviour
I see "red square" near the "Folder name" and OC does not allow using it.

### Server configuration
**Operating system**: Windows 8.1 Pro 64bit

**Web server:** Apache 2.4.9 Win64

**Database:** mysql5.6.17

**PHP version:** php5.5.12

**ownCloud version:** ownCloud 8.0.7 (stable)

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**

```
Activity 1.2.2
Deleted files 0.6.3
External storage support 0.2.3
File Locking 
First Run Wizard 1.1
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.1
Provisioning API 0.2
Share Files 0.6.2
Text Editor 0.4
Updater 0.4.1
Versions 1.0.6
Video Viewer 0.1.3
```

**The content of config/config.php:**

```
<?php
define("DEBUG", true);
$CONFIG = array (
  'instanceid' => 'xxx]',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => 'C:\\wamp\\www\\owncloud\\data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.7.2',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'loglevel' => 0,
  'logfile' => "c:/wamp/logs/owncloud.log",
);
```

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 40.0.3

**Operating system:** Windows 8.1 Pro 64bit

#### Web server error log
```
[Tue Sep 08 17:54:58.223586 2015] [mpm_winnt:notice] [pid 3380:tid 456] AH00455: Apache/2.4.9 (Win64) OpenSSL/1.0.1g PHP/5.5.12 configured -- resuming normal operations
[Tue Sep 08 17:54:58.223586 2015] [mpm_winnt:notice] [pid 3380:tid 456] AH00456: Apache Lounge VC11 Server built: Mar 16 2014 12:42:59
[Tue Sep 08 17:54:58.223586 2015] [core:notice] [pid 3380:tid 456] AH00094: Command line: 'c:\\wamp\\bin\\apache\\apache2.4.9\\bin\\httpd.exe -d C:/wamp/bin/apache/apache2.4.9'
[Tue Sep 08 17:54:58.225586 2015] [mpm_winnt:notice] [pid 3380:tid 456] AH00418: Parent: Created child process 1668
[Tue Sep 08 17:54:59.469661 2015] [mpm_winnt:notice] [pid 1668:tid 348] AH00354: Child: Starting 64 worker threads.
[Tue Sep 08 17:57:23.611257 2015] [mpm_winnt:notice] [pid 3380:tid 456] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Tue Sep 08 17:57:25.613926 2015] [mpm_winnt:notice] [pid 1668:tid 348] AH00364: Child: All worker threads have exited.
[Tue Sep 08 17:57:25.685148 2015] [mpm_winnt:notice] [pid 3380:tid 456] AH00430: Parent: Child process 1668 exited successfully.
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"fa78d2c41eebea5d5730965549f3af92","remoteAddr":"127.0.0.1","app":"PHP","message":"stat(): stat failed for \\\\Htpc\\D\\\u0413\u043e\u043c\u0435\u043e\u043f\u0430\u0442\u0438\u044f\\ at C:\\wamp\\www\\owncloud\\lib\\private\\files\\storage\\mappedlocal.php#114","level":0,"time":"2015-09-08T14:56:03+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"fa78d2c41eebea5d5730965549f3af92","remoteAddr":"127.0.0.1","app":"files_external","message":"Exception: {\"Message\":\"<b>Source:<\\\/b> Unknown<br\\\/><b>Description:<\\\/b> Unknown\",\"Code\":-2147352567,\"Trace\":\"#0 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php(133): com->GetFile('\\\\\\\\\\\\\\\\Htpc\\\\\\\\D\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC...')\\n#1 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php(83): OC\\\\LargeFileHelper->getFileSizeViaCOM('\\\\\\\\\\\\\\\\Htpc\\\\\\\\D\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC...')\\n#2 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\mappedlocal.php(138): OC\\\\LargeFileHelper->getFileSize('\\\\\\\\\\\\\\\\Htpc\\\\\\\\D\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC...')\\n#3 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\mappedlocal.php(116): OC\\\\Files\\\\Storage\\\\MappedLocal->filesize('')\\n#4 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\common.php(393): OC\\\\Files\\\\Storage\\\\MappedLocal->stat('')\\n#5 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\lib\\\\config.php(457): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#6 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\lib\\\\config.php(544): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\\n#7 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\ajax\\\\addMountPoint.php(25): OC_Mount_Config::addMountPoint('\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC\\\\xD0\\\\xB5\\\\xD0\\\\xBE\\\\xD0\\\\xBF\\\\xD0\\\\xB0\\\\xD1...', '\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, 'user', 'all', false)\\n#8 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\route\\\\route.php(135) : runtime-created function(1): require_once('C:\\\\\\\\wamp\\\\\\\\www\\\\\\\\own...')\\n#9 [internal function]: __lambda_func(Array)\\n#10 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\route\\\\router.php(252): call_user_func('\\\\x00lambda_275', Array)\\n#11 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\base.php(791): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#12 C:\\\\wamp\\\\www\\\\owncloud\\\\index.php(36): OC::handleRequest()\\n#13 {main}\",\"File\":\"C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php\",\"Line\":133}","level":4,"time":"2015-09-08T14:56:03+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"aefeacdd2b2221dd90c0144c7546db72","remoteAddr":"127.0.0.1","app":"PHP","message":"stat(): stat failed for \\\\Htpc\\D\\\u0413\u043e\u043c\u0435\u043e\u043f\u0430\u0442\u0438\u044f\\ at C:\\wamp\\www\\owncloud\\lib\\private\\files\\storage\\mappedlocal.php#114","level":0,"time":"2015-09-08T14:56:05+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"aefeacdd2b2221dd90c0144c7546db72","remoteAddr":"127.0.0.1","app":"files_external","message":"Exception: {\"Message\":\"<b>Source:<\\\/b> Unknown<br\\\/><b>Description:<\\\/b> Unknown\",\"Code\":-2147352567,\"Trace\":\"#0 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php(133): com->GetFile('\\\\\\\\\\\\\\\\Htpc\\\\\\\\D\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC...')\\n#1 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php(83): OC\\\\LargeFileHelper->getFileSizeViaCOM('\\\\\\\\\\\\\\\\Htpc\\\\\\\\D\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC...')\\n#2 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\mappedlocal.php(138): OC\\\\LargeFileHelper->getFileSize('\\\\\\\\\\\\\\\\Htpc\\\\\\\\D\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC...')\\n#3 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\mappedlocal.php(116): OC\\\\Files\\\\Storage\\\\MappedLocal->filesize('')\\n#4 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\common.php(393): OC\\\\Files\\\\Storage\\\\MappedLocal->stat('')\\n#5 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\lib\\\\config.php(457): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#6 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\lib\\\\config.php(544): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\\n#7 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\ajax\\\\addMountPoint.php(25): OC_Mount_Config::addMountPoint('\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC\\\\xD0\\\\xB5\\\\xD0\\\\xBE\\\\xD0\\\\xBF\\\\xD0\\\\xB0\\\\xD1...', '\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, 'user', 'all', false)\\n#8 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\route\\\\route.php(135) : runtime-created function(1): require_once('C:\\\\\\\\wamp\\\\\\\\www\\\\\\\\own...')\\n#9 [internal function]: __lambda_func(Array)\\n#10 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\route\\\\router.php(252): call_user_func('\\\\x00lambda_361', Array)\\n#11 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\base.php(791): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#12 C:\\\\wamp\\\\www\\\\owncloud\\\\index.php(36): OC::handleRequest()\\n#13 {main}\",\"File\":\"C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php\",\"Line\":133}","level":4,"time":"2015-09-08T14:56:05+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"29e2c8997e8b71c7fb037374285eb18c","remoteAddr":"127.0.0.1","app":"PHP","message":"stat(): stat failed for D:\\\u0413\u043e\u043c\u0435\u043e\u043f\u0430\u0442\u0438\u044f\\ at C:\\wamp\\www\\owncloud\\lib\\private\\files\\storage\\mappedlocal.php#114","level":0,"time":"2015-09-08T14:56:19+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"29e2c8997e8b71c7fb037374285eb18c","remoteAddr":"127.0.0.1","app":"files_external","message":"Exception: {\"Message\":\"<b>Source:<\\\/b> Unknown<br\\\/><b>Description:<\\\/b> Unknown\",\"Code\":-2147352567,\"Trace\":\"#0 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php(133): com->GetFile('D:\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC\\\\xD0\\\\xB5\\\\xD0\\\\xBE\\\\xD0\\\\xBF...')\\n#1 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php(83): OC\\\\LargeFileHelper->getFileSizeViaCOM('D:\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC\\\\xD0\\\\xB5\\\\xD0\\\\xBE\\\\xD0\\\\xBF...')\\n#2 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\mappedlocal.php(138): OC\\\\LargeFileHelper->getFileSize('D:\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC\\\\xD0\\\\xB5\\\\xD0\\\\xBE\\\\xD0\\\\xBF...')\\n#3 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\mappedlocal.php(116): OC\\\\Files\\\\Storage\\\\MappedLocal->filesize('')\\n#4 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\common.php(393): OC\\\\Files\\\\Storage\\\\MappedLocal->stat('')\\n#5 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\lib\\\\config.php(457): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#6 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\lib\\\\config.php(544): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\\n#7 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\ajax\\\\addMountPoint.php(25): OC_Mount_Config::addMountPoint('\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC\\\\xD0\\\\xB5\\\\xD0\\\\xBE\\\\xD0\\\\xBF\\\\xD0\\\\xB0\\\\xD1...', '\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, 'user', 'all', false)\\n#8 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\route\\\\route.php(135) : runtime-created function(1): require_once('C:\\\\\\\\wamp\\\\\\\\www\\\\\\\\own...')\\n#9 [internal function]: __lambda_func(Array)\\n#10 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\route\\\\router.php(252): call_user_func('\\\\x00lambda_447', Array)\\n#11 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\base.php(791): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#12 C:\\\\wamp\\\\www\\\\owncloud\\\\index.php(36): OC::handleRequest()\\n#13 {main}\",\"File\":\"C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php\",\"Line\":133}","level":4,"time":"2015-09-08T14:56:19+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"2059737d3c74657960c2b55d2956e0eb","remoteAddr":"127.0.0.1","app":"PHP","message":"stat(): stat failed for D:\\\u0413\u043e\u043c\u0435\u043e\u043f\u0430\u0442\u0438\u044f at C:\\wamp\\www\\owncloud\\lib\\private\\files\\storage\\mappedlocal.php#114","level":0,"time":"2015-09-08T14:56:56+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"2059737d3c74657960c2b55d2956e0eb","remoteAddr":"127.0.0.1","app":"files_external","message":"Exception: {\"Message\":\"<b>Source:<\\\/b> Unknown<br\\\/><b>Description:<\\\/b> Unknown\",\"Code\":-2147352567,\"Trace\":\"#0 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php(133): com->GetFile('D:\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC\\\\xD0\\\\xB5\\\\xD0\\\\xBE\\\\xD0\\\\xBF...')\\n#1 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php(83): OC\\\\LargeFileHelper->getFileSizeViaCOM('D:\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC\\\\xD0\\\\xB5\\\\xD0\\\\xBE\\\\xD0\\\\xBF...')\\n#2 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\mappedlocal.php(138): OC\\\\LargeFileHelper->getFileSize('D:\\\\\\\\\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC\\\\xD0\\\\xB5\\\\xD0\\\\xBE\\\\xD0\\\\xBF...')\\n#3 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\mappedlocal.php(116): OC\\\\Files\\\\Storage\\\\MappedLocal->filesize('')\\n#4 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\files\\\\storage\\\\common.php(393): OC\\\\Files\\\\Storage\\\\MappedLocal->stat('')\\n#5 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\lib\\\\config.php(457): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#6 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\lib\\\\config.php(544): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\\n#7 C:\\\\wamp\\\\www\\\\owncloud\\\\apps\\\\files_external\\\\ajax\\\\addMountPoint.php(25): OC_Mount_Config::addMountPoint('\\\\xD0\\\\x93\\\\xD0\\\\xBE\\\\xD0\\\\xBC\\\\xD0\\\\xB5\\\\xD0\\\\xBE\\\\xD0\\\\xBF\\\\xD0\\\\xB0\\\\xD1...', '\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, 'user', 'all', false)\\n#8 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\route\\\\route.php(135) : runtime-created function(1): require_once('C:\\\\\\\\wamp\\\\\\\\www\\\\\\\\own...')\\n#9 [internal function]: __lambda_func(Array)\\n#10 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\route\\\\router.php(252): call_user_func('\\\\x00lambda_619', Array)\\n#11 C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\base.php(791): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#12 C:\\\\wamp\\\\www\\\\owncloud\\\\index.php(36): OC::handleRequest()\\n#13 {main}\",\"File\":\"C:\\\\wamp\\\\www\\\\owncloud\\\\lib\\\\private\\\\largefilehelper.php\",\"Line\":133}","level":4,"time":"2015-09-08T14:56:56+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
```

**Comment by RealRancor** [comment]
Hi,

quoting from the docs:

```
However, as apps like external storage are added, particularly SMB mounts, and non-English characters are used in filenames, some of the known Windows and IIS/Apache challenges start to appear as bugs.
```

https://doc.owncloud.org/server/7.0/admin_manual/installation/windows_installation.html

For this reason Windows supported was dropped in oC 8 as announced.

**Comment by iG8R** [comment]
Hi, RealRancor.
I'm very sorry for this topic. It's all my inattention.
Thank you.

**Comment by RealRancor** [comment]
Hi,

i think you could keep this open if someone is planning to bring back windows support in the future.

**Comment by iG8R** [comment]
Ok. I hope Windows support will be back.

**Comment by MorrisJobke** [comment]
> Ok. I hope Windows support will be back.

Support for windows on the server side was dropped. And there is currently no plan/resources to bring it back. Sorry for that.
