### ISSUE TITLE
Disabling Sharing makes ownCloud inaccessible

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#18930]
When I disable `files_sharing` and then access the ownCloud instance a fatal exception is thrown:
```
==> data/owncloud.log <==
{"reqId":"YTmHzHQRdU01QIlbDoev","remoteAddr":"31.10.132.179","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/opt\\\/owncloud\\\/apps\\\/files_sharing\\\/api\\\/server2server.php\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/autoloader.php(154): OC\\\\Autoloader->isValidPath('\\\/opt\\\/owncloud\\\/a...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\Files_Shari...')\\n#2 \\\/opt\\\/owncloud\\\/ocs\\\/routes.php(107): spl_autoload_call('OCA\\\\Files_Shari...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(175): require_once('\\\/opt\\\/owncloud\\\/o...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(252): OC\\\\Route\\\\Router->loadRoutes()\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/base.php(892): OC\\\\Route\\\\Router->match(false)\\n#6 \\\/opt\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":134}","level":4,"time":"2015-09-09T13:35:16+00:00"}
```

cc @Xenopathic

**Comment by Xenopathic** [comment]
Brilliant, another place where we just assume things to be available...
