### ISSUE TITLE
Installing via console fails

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#19019]
```
An unhandled exception has been thrown:
exception 'OCP\AutoloadNotAllowedException' with message 'Autoload path not allowed: .../apps/files/command/scan.php' in .../lib/autoloader.php:134
Stack trace:
#0 .../lib/autoloader.php(154): OC\Autoloader->isValidPath('/home/nickv/own...')
#1 [internal function]: OC\Autoloader->load('OCA\\Files\\Comma...')
#2 .../apps/files/appinfo/register_command.php(23): spl_autoload_call('OCA\\Files\\Comma...')
#3 .../lib/private/console/application.php(60): require('/home/nickv/own...')
#4 .../console.php(67): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 .../occ(11): require_once('/home/nickv/own...')
#6 {main}
```

@Xenopathic

**Comment by nickvergessen** [comment]
PS: this happens after install in my reset script:
https://gist.github.com/nickvergessen/6ca853fcda402c219b1f
in the `# Fill config` step

**Comment by Xenopathic** [comment]
Ah, this is because we load commands for not-enabled apps. This could be a tricky one to solve... Do we definitely need to have commands available for not-enabled apps?

**Comment by nickvergessen** [comment]
I don't think so?
