### ISSUE TITLE
Can't download file from federated file share

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19060]
### Steps

1. Setup an admin as "root"
1. Create a user "user1"
1. Login as "user1"
1. Upload a big file (200+ MB) data1.dat
1. Share "data1.dat" with "root@localhost/owncloud" (using federated share)
1. Login as "root" and accept the share
1. Setup sync client for user "root"
1. Wait for download

### Expected result
File can be downloaded

### Actual result
Service unavailable

```
{"reqId":"8z1lXMdQed6Kj7zap3Kr","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Failed to open file: \",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(82): OC\\\\Connector\\\\Sabre\\\\File->get()\\n
#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(137): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":272}","level":4,"time":"2015-09-15T16:17:47+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/data1.dat"}
```

The storage is marked as available in the oc_storages table:
```
MariaDB [owncloud]> select * from oc_storages;
+------------------------------------------+------------+-----------+--------------+
| id                                       | numeric_id | available | last_checked |
+------------------------------------------+------------+-----------+--------------+
| home::root                               |          1 |         1 |         NULL |
| local::/srv/www/htdocs/owncloud/data/    |          2 |         1 |         NULL |
| home::user1                              |          3 |         1 |         NULL |
| shared::820341b4853bded488a38d7f888e5e02 |          4 |         1 |   1442333827 |
+------------------------------------------+------------+-----------+--------------+
```

### Versions
ownCloud 8.2 pre-alpha git master e545c2eec56c1f5c99485d4a29949d975961084c

CC @icewind1991

**Comment by PVince81** [comment]
Weird, now it works again when setup from scratch.

Maybe it was caused by switching between branches

**Comment by PVince81** [comment]
When I switch from master to the branch from https://github.com/owncloud/core/pull/17104 the problem happens. But if I reset ownCloud and set it up again directly on the branch, it works again...

Weird shit

**Comment by PVince81** [comment]
Ok, got it.

Instead of using the sync client, try downloading the file *twice* with cadaver.
The first time it will work.
Starting with the second time I'm getting 503.

And this is on master (the commit from the original post)

**Comment by PVince81** [comment]
I bisected this and it points to 5ca690e2f8be9fae50a6d29786ab0da9188a71ad

You might need to reset ownCloud between every bisect step.
The commit before that worked properly.
On this commit, downloading the federated share file twice causes 503 issues.

@Xenopathic

**Comment by PVince81** [comment]
it's the PR about using integer in the column: https://github.com/owncloud/core/pull/18964

With this setup:
mariadb-10.0.20-1.1.x86_64
php5-5.6.13-1.1.x86_64
