### ISSUE TITLE
oc_file_locks constraint violation

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19094]
### Env
FreeBSD, ZFS
MariaDB 10
PHP 5.5
Encryption turned on

```
Enabled:
  - activity: 2.1.2
  - encryption: 1.0.0
  - files: 1.1.11
  - files_external: 0.2.3
  - files_sharing: 0.6.3
  - files_texteditor: 2.0
  - files_versions: 1.0.6
  - gallery: 14.0.0
  - provisioning_api: 0.2
```

### Description

Sometimes, in the Files app on master, things start to crumble and I can't get thumbnails of some images any more.

Here is the exception I get:

```
Exception: {"Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Message":"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/a3594fd4eca7119cb937772e1f8f5415\", 0, 0, \"files\\\/a3594fd4eca7119cb937772e1f8f5415\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\/a3594fd4eca7119cb937772e1f8f5415' for key 'lock_key_index'","Code":0,"Trace":"#0 \/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/lib\/private\/db\/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/lib\/private\/db\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array)\n#4 \/lib\/private\/db\/connection.php(242): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#5 \/lib\/private\/lock\/dblockingprovider.php(52): OC\\DB\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#6 \/lib\/private\/lock\/dblockingprovider.php(84): OC\\Lock\\DBLockingProvider->initLockField('files\/a3594fd4e...')\n#7 \/lib\/private\/files\/storage\/common.php(638): OC\\Lock\\DBLockingProvider->acquireLock('files\/a3594fd4e...', 1)\n#8 \/lib\/private\/files\/storage\/wrapper\/wrapper.php(571): OC\\Files\\Storage\\Common->acquireLock('files', 1, Object(OC\\Lock\\DBLockingProvider))\n#9 \/lib\/private\/files\/view.php(1763): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files', 1, Object(OC\\Lock\\DBLockingProvider))\n#10 \/lib\/private\/files\/view.php(1862): OC\\Files\\View->lockPath('\/', 1)\n#11 \/lib\/private\/files\/view.php(1174): OC\\Files\\View->lockFile('\/1280px-Chicago...', 1)\n#12 \/lib\/private\/files\/filesystem.php(861): OC\\Files\\View->getFileInfo('\/1280px-Chicago...', true)\n#13 \/core\/ajax\/preview.php(50): OC\\Files\\Filesystem::getFileInfo('\/1280px-Chicago...')\n#14 \/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/home\/icloud\/do...')\n#15 [internal function]: __lambda_func(Array)\n#16 \/lib\/private\/route\/router.php(281): call_user_func('\\x00lambda_47', Array)\n#17 \/lib\/base.php(893): OC\\Route\\Router->match('\/core\/preview.p...')\n#18 \/index.php(40): OC::handleRequest()\n#19 {main}","File":"\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66} 
```

occ files commands have no effect.

@PVince81 @DeepDiver1975

**Comment by oparoz** [comment]
Maybe files_versions still has a reference to those files?

**Comment by PVince81** [comment]
@oparoz still happening on master ? (there was a PR that fixed locking recently)

**Comment by oparoz** [comment]
The DB table is full of locks for files which don't exist in the filesystem.
I guess the solution would be to include a new step in `occ maintenance:repair`, but there are probably other use cases than testing which trigger the issue. If the admin removes a folder in data per example.

**Comment by PVince81** [comment]
@icewind1991 has added a TTL last week. This table only exists since 8.2, so I don't think a repair step is required in this case as this shouldn't be able to happen any more.

**Comment by oparoz** [comment]
Ah, OK. I'll empty the table and close this. I'll re-open if I notice any unorthodox behaviour.
