### ISSUE TITLE
upgrade 8.1.1-3 -> 8.1.3-13.1 'CREATE UNIQUE INDEX' failed

### ISSUE THREAD

**Issue by cyboman32** [owncloud/core#19142]
### Steps to reproduce

Installed Owncloud version 8.1.1-3
sudo apt-get update // upgrade
Updated to 8.1.3-13.1

sudo -u www-data ./occ -vvv upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Repair step: Repair MySQL database engine
Repair info: Not a mysql database -> nothing to do
Repair step: Repair MySQL collation
Repair info: Not a mysql database -> nothing to no
Repair step: Repair SQLite autoincrement
Repair step: Repair duplicate entries in oc_lucene_status
Repair info: removing duplicate entries from lucene_status
Repair step: Repair config
OC\DB\MigrationException: An exception occurred while executing 'CREATE UNIQUE INDEX oc_ksksvbdxsxwbz ON oc_oc_filecache_6j9tosqix4hl0 ("storage", "path_hash")':

SQLSTATE[23505]: Unique violation: 7 ERROR:  could not create unique index "oc_ksksvbdxsxwbz"
DETAIL:  Key (storage, path_hash)=(3, 4885a073b74075beacf9d3dd66b656d6) is duplicated.
Update failed
Maintenance mode is kept active

Every time random postfixes for oc_* and oc_oc_filecache_* is different. All other info is the same

### Expected behaviour

Finishing upgrade without problems

### Actual behaviour

Upgrade error at the console

Server configuration

Operating system: Ubuntu 15.04
Web server: nginx 1.6.2-5ubuntu3.1
Database: mysql 5.6.25-0ubuntu0.15.04.1
PHP version: 5.6.4+dfsg-4ubuntu6.2

ownCloud version: 8.1.3-13.1
Updated from an older ownCloud or fresh install: updated
List of activated apps: 
Enabled:
 - activity: 2.0.1
 - external: 1.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3

Disabled:
 - appframework
 - encryption
 - files_locking
 - firstrunwizard
 - gallery
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_ldap
 - user_webdavauth

The content of config/config.php:
```php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'xxxxxxxxxxxxxxxxx',
  ),
  'datadirectory' => '/stor/raid/owncloud',
  'dbtype' => 'pgsql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxxxxxxxxxx',
  'dbpassword' => 'xxxxxxxxxxxxxxxx',
  'installed' => true,
  'forcessl' => true,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/owncloud/appsx',
      'url' => '/appsx',
      'writable' => true,
    ),
  ),
  'theme' => '',
  'maintenance' => true,
  'share_folder' => '/Shared',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
);
```

Are you using external storage, if yes which one: no
Are you using encryption: no
Are you using an external user-backend, if yes which one: no

### Logs
owncloud.log
```
{"reqId":"NGAOjLlel1+3VKU4H+SW","remoteAddr":"","app":"core","message":"Simulated database structure update failed (exception 'OC\\DB\\MigrationException' with message 'An exception occurred while executing 'CREATE UNIQUE INDEX oc_isfnixcysqwax ON oc_oc_filecache_dbdg1xuriukjw (\"storage\", \"path_hash\")':\n\nSQLSTATE[23505]: Unique violation: 7 ERROR:  could not create unique index \"oc_isfnixcysqwax\"\nDETAIL:  Key (storage, path_hash)=(3, 4885a073b74075beacf9d3dd66b656d6) is duplicated.' in \/var\/www\/owncloud\/lib\/private\/db\/migrator.php:152\nStack trace:\n#0 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(110): OC\\DB\\Migrator->checkTableMigrate(Object(Doctrine\\DBAL\\Schema\\Table))\n#1 \/var\/www\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(133): OC\\DB\\Migrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#2 \/var\/www\/owncloud\/lib\/private\/db.php(248): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#3 \/var\/www\/owncloud\/lib\/private\/updater.php(326): OC_DB::simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#4 \/var\/www\/owncloud\/lib\/private\/updater.php(293): OC\\Updater->checkCoreUpgrade()\n#5 \/var\/www\/owncloud\/lib\/private\/updater.php(195): OC\\Updater->doUpgrade('8.1.3.0', '8.1.1.3')\n#6 \/var\/www\/owncloud\/core\/command\/upgrade.php(181): OC\\Updater->upgrade()\n#7 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(253): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(126): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/var\/www\/owncloud\/lib\/private\/console\/application.php(94): Symfony\\Component\\Console\\Application->run(NULL, NULL)\n#12 \/var\/www\/owncloud\/console.php(68): OC\\Console\\Application->run()\n#13 \/var\/www\/owncloud\/occ(11): require_once('\/var\/www\/ownclo...')\n#14 {main})","level":4,"time":"2015-09-17T19:19:16+00:00"}
{"reqId":"NGAOjLlel1+3VKU4H+SW","remoteAddr":"","app":"update","message":"Exception: {\"Exception\":\"OC\\\\DB\\\\MigrationException\",\"Message\":\"An exception occurred while executing 'CREATE UNIQUE INDEX oc_isfnixcysqwax ON oc_oc_filecache_dbdg1xuriukjw (\\\"storage\\\", \\\"path_hash\\\")':\\n\\nSQLSTATE[23505]: Unique violation: 7 ERROR:  could not create unique index \\\"oc_isfnixcysqwax\\\"\\nDETAIL:  Key (storage, path_hash)=(3, 4885a073b74075beacf9d3dd66b656d6) is duplicated.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/migrator.php(110): OC\\\\DB\\\\Migrator->checkTableMigrate(Object(Doctrine\\\\DBAL\\\\Schema\\\\Table))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/mdb2schemamanager.php(133): OC\\\\DB\\\\Migrator->checkMigrate(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db.php(248): OC\\\\DB\\\\MDB2SchemaManager->simulateUpdateDbFromStructure('\\\/var\\\/www\\\/ownclo...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(326): OC_DB::simulateUpdateDbFromStructure('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(293): OC\\\\Updater->checkCoreUpgrade()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(195): OC\\\\Updater->doUpgrade('8.1.3.0', '8.1.1.3')\\n#6 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/upgrade.php(181): OC\\\\Updater->upgrade()\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Command\\\/Command.php(253): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(874): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(195): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(126): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(94): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#12 \\\/var\\\/www\\\/owncloud\\\/console.php(68): OC\\\\Console\\\\Application->run()\\n#13 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/migrator.php\",\"Line\":152}","level":4,"time":"2015-09-17T19:19:16+00:00"}
{"reqId":"+YixEcT2MMZHvvkD8sqC","remoteAddr":"1.0.0.7","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-09-17T19:19:21+00:00"}
{"reqId":"HAYGPTiX4lSMmxoij1XW","remoteAddr":"46.39.231.125","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-09-17T19:19:23+00:00"}
```

**Comment by nickvergessen** [comment]
Try `./occ -vvv upgrade --skip-migration-test` but create a backup of your database before.

**Comment by PVince81** [comment]
Still, that index "fs_storage_path_hash" is supposed to exist already in 8.1.1, so the old database cannot already contain any duplicate entries.

Well, unless @cyboman32 had update issues in the past and somehow managed to skip past this index creation ?

**Comment by PVince81** [comment]
@cyboman32 can you run `show index from oc_filecache;` on the database before the upgrade and post the result here ? This is to check whether that index existed in your previous version, which is supposed to be.

**Comment by cyboman32** [comment]
thanks guys, but seems problem was in the broken/faulty DB. the oc_filecache table actually has a lot of records with duplicated path_hash (as well as names etc). i dunno how this is possible but the solution was simple:
- empty oc_filecache table whatever how
- occ upgrade (otherwise files:scan won't work)
- rescan files using occ files:scan --all

probably owncloud need a new command files:??? to delete oc_filecache content, since it's easy to rebuild. important part is that command should work even on non-upgraded DB, otherwise it is no use and you stiil need manually clean oc_filecache. also files:cleanup seems doesn't solve this at all

ps. yeap the index fs_storage_path_hash is exist

**Comment by PVince81** [comment]
I hope you didn't have any shares because emptying the filecache table will kill all references

**Comment by cyboman32** [comment]
no, we didn't. but writing of some reparing code to correctly remove duplicates in filecache, seems too heavy in terms of development cost. well maybe this issue will help someone at least.

thanks.

**Comment by KSSea** [comment]
This same bug appears to have just happened to me today even thought this issue is closed.  Am running Debian 7.9 and did update of system today which included OC components.  Web interface said that upgrade was in progress but just stayed there.  Logged in to shell and ran "sudo -u www-data php /var/www/owncloud/occ upgrade"  which resulted in following error message, very similar to what is reported above:

OC\DB\MigrationException: An exception occurred while executing 'CREATE UNIQUE INDEX oc_watdcbmwzjsxx ON oc_oc_filecache_0wm3i09hejr8x ("storage", "path_hash")':

SQLSTATE[23505]: Unique violation: 7 ERROR: could not create unique index "oc_watdcbmwzjsxx"
DETAIL: Key (storage, path_hash)=(2, b9ab5e30e0177fb71c641a54f98dec36) is duplicated.
Update failed
Maintenance mode is kept active
