### ISSUE TITLE
Error "Server is temporarily unavailable" after upgrading to 8.2beta1

### ISSUE THREAD

**Issue by atroxix** [owncloud/core#19519]
I know this is a known issue for 8.2beta1, but maybe there's a workaround or fix/patch available for that?

I guess downgrading is not really an option, is it?

**Comment by MorrisJobke** [comment]
Is there something in the owncloud.log?

**Comment by atroxix** [comment]
Yes there is:
```
{"reqId":"uF6zAarAAywupKK6aMuj","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in single user mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(137): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/maintenanceplugin.php\",\"Line\":80}","level":4,"time":"2015-10-02T10:21:37+00:00"}

```

**Comment by nickvergessen** [comment]
Unset the singleuser config value in your `config/config.php`

Manually.

There was an error with encryption, it's fixed since the day after beta1

**Comment by atroxix** [comment]
Ah, that was easy, sorry :)
