### ISSUE TITLE
occ not work (also cron not work) and login redirect loop

### ISSUE THREAD

**Issue by AdminJack** [owncloud/core#19586]
### Steps to reproduce

1.I install the calendarplus app
2. I execute "sudo -u www-data php occ app:disable calendar" and at the same time I switch in https://owncloud.de/index.php/settings/apps the calendar app off
3. Oops ;(
### Actual behaviour

If I want to login in Owncloud I get an error page in my browser: This webpage has a redirect loop.
But If go to https://owncloud.de/remote.php/calendarplus/ than I can login with Basic Authentication and use Owncloud normal ;) But it is cumbersome.
Now I get no input our output if I execute  "sudo -u www-data php occ" and cron not working.

And If I set the "maintenance" => true in the config.php the ownCloud console work normal. (But if I run "sudo -u www-data php occ maintenance:mode -off" the problem is alive.)
### Server configuration

**Operating system**: Ubuntu 14.04.3 LTS

**Web server:** apache2 2.4.7-1ubuntu4.6

**Database:** mysql-server  5.5.44-0ubuntu0.14.04.1

**PHP version:** php5   5.5.9+dfsg-1ubuntu4.13

**ownCloud version:** 8.1.3

**Updated from an older ownCloud:** yes (before without problems)

**List of activated apps:**
Enabled:
- activity: 2.0.2
- calendarplus: 1.1.1
- contacts: 0.4.0.0
- contactsplus: 1.0.9
- documents: 0.10.2
- encryption: 1.0.0
- external: 1.2
- files: 1.1.10
- files_external: 0.2.3
- files_locking: 
- files_pdfviewer: 0.7
- files_sharing: 0.6.2
- files_texteditor: 0.4
- files_trashbin: 0.6.3
- files_versions: 1.0.6
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- gallery: 0.6.0
- roundcube: 2.6.1
- search_lucene: 0.7.0
- templateeditor: 0.1

Disabled:
- calendar
- mail
- notes
- ocDashboard
- ocdownloader
- polls
- provisioning_api
- updater
- user_external
- user_ldap
- user_webdavauth
- youtubedl

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxx',
  'passwordsalt' => 'xxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'x.x.x.76',
    1 => 'owncloud.de',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'sendmail',
  'theme' => '',
  'maintenance' => true,
  'mail_smtpsecure' => 'ssl',
  'loglevel' => 3,
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'dbname' => 'owncloud',
 'dbhost' => '127.0.0.1',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxxxxxxxxxxxxxxx',
  'asset-pipeline.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);
```

**Are you using encryption:** yes
### Client configuration

**Browser:** Firefox 41.0.1

**Operating system:** Win 7
#### Web server access log

```
193.200.138.12 - - [02/Oct/2015:12:27:26 +0000] "GET /index.php HTTP/1.1" 302 798 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
193.200.138.12 - - [02/Oct/2015:12:27:26 +0000] "GET /index.php HTTP/1.1" 302 798 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
193.200.138.12 - - [02/Oct/2015:12:27:26 +0000] "GET /index.php HTTP/1.1" 302 798 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
193.200.138.12 - - [02/Oct/2015:12:27:26 +0000] "GET /index.php HTTP/1.1" 302 798 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
```
#### Web server error log

```
[Mon Sep 28 07:35:33.674666 2015] [ssl:warn] [pid 28889] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Sep 28 10:49:46.817659 2015] [:error] [pid 12390] [client 193.200.138.12:34244] PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/owncloud/lib/private/config.php on line 178, referer: https://owncloud.de/index.php/apps/roundcube
[Mon Sep 28 10:49:46.818052 2015] [:error] [pid 12390] [client 193.200.138.12:34244] PHP Fatal error:  Call to a member function getValue() on a non-object in /var/www/owncloud/lib/private/legacy/config.php on line 46, referer: https://owncloud.de/index.php/apps/roundcube
[Mon Sep 28 11:03:10.608901 2015] [ssl:warn] [pid 12386] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Sep 28 11:12:13.210745 2015] [:error] [pid 16856] [client 193.200.138.12:40898] PHP Fatal error:  Access to undeclared static property: Sabre\\VObject\\Component::$classMap in /var/www/owncloud/apps/contacts/appinfo/app.php on line 15, referer: https://owncloud.de/index.php/apps/files
[Mon Sep 28 11:12:41.943278 2015] [ssl:warn] [pid 17011] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Sep 28 11:12:49.180562 2015] [:error] [pid 17018] [client 193.200.138.12:41116] PHP Fatal error:  Access to undeclared static property: Sabre\\VObject\\Component::$classMap in /var/www/owncloud/apps/contacts/appinfo/app.php on line 15
[Mon Sep 28 11:13:44.057574 2015] [ssl:warn] [pid 17012] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Sep 28 11:19:53.398113 2015] [:error] [pid 17169] [client 193.200.138.12:42935] PHP Fatal error:  Class 'OC_Request' not found in /var/www/owncloud/apps/roundcube/templates/tpl.mail.php on line 55, referer: https://owncloud.de/index.php/settings/personal
[Mon Sep 28 11:37:54.735033 2015] [:error] [pid 17169] [client 193.200.138.12:48717] PHP Fatal error:  Class 'OC_Request' not found in /var/www/owncloud/apps/roundcube/lib/RoundCubeAuthHelper.class.php on line 118, referer: https://owncloud.de/index.php/apps/activity/?filter=all
[Mon Sep 28 14:06:40.830535 2015] [:error] [pid 17163] [client 193.200.138.12] ModSecurity: Request body no files data length is larger than the configured limit (131072).. Deny with code (413) [hostname "owncloud.de"] [uri "/index.php/apps/calendarplus/getimportdialogtplcalendar"] [unique_id "VglJcIL-SUwAAEMLVCQAAAAH"]
[Mon Sep 28 23:05:53.932881 2015] [ssl:error] [pid 20125] AH02032: Hostname 130.255.73.76 provided via SNI and hostname owncloud.de provided via HTTP are different
[Wed Sep 30 13:23:27.276582 2015] [:error] [pid 28234] [client 84.183.194.204:38183] PHP Fatal error:  Call to undefined method OCA\\ContactsPlus\\VObject\\StringPropertyCategories::addGroup() in /var/www/owncloud/apps/contacts/lib/vobject/vcard.php on line 381, referer: https://owncloud.de/index.php/apps/contacts/
[Thu Oct 01 06:52:43.843688 2015] [ssl:warn] [pid 5769] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Oct 02 08:33:50.989963 2015] [:error] [pid 20910] [client 193.200.138.12:58733] PHP Fatal error:  Call to undefined method OCA\\ContactsPlus\\VObject\\StringPropertyCategories::addGroup() in /var/www/owncloud/apps/contacts/lib/vobject/vcard.php on line 381, referer: https://owncloud.de/index.php/apps/contacts/
[Fri Oct 02 09:59:50.179463 2015] [ssl:warn] [pid 2041] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Oct 02 10:54:57.805039 2015] [:error] [pid 2178] [client 109.47.195.15:60418] PHP Fatal error:  require_once(): Failed opening required '/appinfo/remote.php' (include_path='/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:/var/www/owncloud/lib:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') in /var/www/owncloud/remote.php on line 132
[Sat Oct 03 10:17:41.084341 2015] [ssl:warn] [pid 8950] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"Vg5364L-SUwAAA7FGSsAAAAB","remoteAddr":"193.200.138.12","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":1,"time":"2015-10-02T12:26:20+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"Vg5384L-SUwAAA7GJmMAAAAC","remoteAddr":"193.200.138.12","app":"OCP\\Share","message":"Sharing backend \\OCA\\CalendarPlus\\Share\\Backend\\Calendar not registered, \\OCA\\CalendarPlus\\Share\\Backend\\Calendar is already registered for calpl","level":2,"time":"2015-10-02T12:26:28+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/navigationdetect.php?app=calendarplus"}
{"reqId":"Vg5384L-SUwAAA7GJmMAAAAC","remoteAddr":"193.200.138.12","app":"OCP\\Share","message":"Sharing backend \\OCA\\CalendarPlus\\Share\\Backend\\Event not registered, \\OCA\\CalendarPlus\\Share\\Backend\\Event is already registered for calplevent","level":2,"time":"2015-10-02T12:26:28+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/navigationdetect.php?app=calendarplus"}
{"reqId":"Vg53@oL-SUwAAA7RSXwAAAAG","remoteAddr":"193.200.138.12","app":"roundcube","message":"OC_RoundCube_AuthHelper.class.php->refresh(): Preparing refresh for roundcube","level":0,"time":"2015-10-02T12:26:34+00:00","method":"POST","url":"\/index.php\/apps\/roundcube\/refresh"}
{"reqId":"Vg53@oL-SUwAAA7RSXwAAAAG","remoteAddr":"193.200.138.12","app":"roundcube","message":"OC_RoundCube_AuthHelper.class.php->getServerHost(): rcHost: owncloud.de","level":0,"time":"2015-10-02T12:26:34+00:00","method":"POST","url":"\/index.php\/apps\/roundcube\/refresh"}
{"reqId":"Vg53@oL-SUwAAA7RSXwAAAAG","remoteAddr":"193.200.138.12","app":"roundcube","message":"OC_RoundCube_App.class.php->refresh(): Trying to refresh RoundCube session under \/roundcubemail\/","level":0,"time":"2015-10-02T12:26:34+00:00","method":"POST","url":"\/index.php\/apps\/roundcube\/refresh"}
{"reqId":"Vg53@oL-SUwAAA7RSXwAAAAG","remoteAddr":"193.200.138.12","app":"roundcube","message":"OC_RoundCube_App.class.php->refresh(): Failed to refresh the RC session.","level":1,"time":"2015-10-02T12:26:34+00:00","method":"POST","url":"\/index.php\/apps\/roundcube\/refresh"}
{"reqId":"Vg53@oL-SUwAAA7RSXwAAAAG","remoteAddr":"193.200.138.12","app":"roundcube","message":"OC_RoundCube_AuthHelper.class.php->refresh(): Finished refresh for roundcube","level":0,"time":"2015-10-02T12:26:34+00:00","method":"POST","url":"\/index.php\/apps\/roundcube\/refresh"}
{"reqId":"Vg53-oL-SUwAAA7WmkcAAAAJ","remoteAddr":"193.200.138.12","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":1,"time":"2015-10-02T12:26:39+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}

{"reqId":"VhJJZYL-SUwAAF@7chkAAAAI","remoteAddr":"193.200.138.12","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 501 There was no handler found for this \\\"GET\\\" method\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#2 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#3 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":472}","level":4,"time":"2015-10-05T09:56:53+00:00"}
{"reqId":"VhJJbYL-SUwAAF-cpZYAAAAD","remoteAddr":"193.200.138.12","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 501 There was no handler found for this \\\"GET\\\" method\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#2 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#3 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":472}","level":4,"time":"2015-10-05T09:57:01+00:00"}
{"reqId":"yJPgvkYAI8mBbYlkpvJL","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-10-05T10:00:02+00:00"}
{"reqId":"VhJMdYL-SUwAAF@7cjEAAAAI","remoteAddr":"193.200.138.12","app":"PHP","message":"Undefined offset: 2 at \/var\/www\/owncloud\/apps\/external\/templates\/settings.php#22","level":3,"time":"2015-10-05T10:09:57+00:00"}
{"reqId":"VhJNkoL-SUwAAGAv8fEAAAAA","remoteAddr":"193.200.138.72","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Exception: App not installed: calendar\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(Exception))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":62}","level":4,"time":"2015-10-05T10:14:42+00:00"}
```

sorry for my English and the bad log

**Comment by MorrisJobke** [comment]
@AdminJack Can I ask you to disable roundcube, calendarplus, contactsplus and contacts to try if one of them maybe cause an issue?

**Comment by AdminJack** [comment]
@MorrisJobke No, it don't solve the issue. 
What is these log meaning(?): 
[Mon Oct 05 20:10:14.605384 2015] [ssl:error] [pid 24732] AH02032: Hostname 130.255.73.7 provided via SNI and hostname owncloud.de provided via HTTP are different

**Comment by MorrisJobke** [comment]
> [Mon Oct 05 20:10:14.605384 2015] [ssl:error] [pid 24732] AH02032: Hostname 130.255.73.7 provided via SNI and hostname owncloud.de provided via HTTP are different

cc @LukasReschke

**Comment by LukasReschke** [comment]
> [Mon Oct 05 20:10:14.605384 2015] [ssl:error] [pid 24732] AH02032: Hostname 130.255.73.7 provided via SNI and hostname owncloud.de provided via HTTP are different

Probably just a misbehaving client.

**Comment by fpytloun** [comment]
Hello, I am experiencing just the same issue. SNI issue doesn't appear in my case, also nothing interesting in logs so I am pretty stucked with debuging :-/
Redirect loop disappears if I set `installed` to `false` in config.php

**Comment by AdminJack** [comment]
The Problem must be in the database or in the /data directory, because I have played all other directories with a backup back and the issue wasn't solved.

**Comment by AdminJack** [comment]
@libasys: It is a problem with calendar plus?

**Comment by fpytloun** [comment]
Checked database and data dir, still didn't find anything wrong. Debug log of owncloud is silent and my reverse-engineering of where it's happening was not successful yet. Anyone who succeeded with finding workaround?

**Comment by fpytloun** [comment]
Ok, so I have restored MySQL database of affected server on clean ownCloud installation and successfuly reproduced the issue.
After trying to randomly truncate tables and delete specific rows, I have found that following fixes the issue:
```DELETE FROM oc_appconfig WHERE appid = 'storagecharts2';```

After that, ownCloud login page works.

Cleanup after storage charts:
```
DROP TABLE oc_storagecharts2;
DROP TABLE oc_storagecharts2_uconf;
```
```rm -rf /var/www/owncloud/apps/storagecharts2```

And install again from UI. Voilá :-)

**Comment by MorrisJobke** [comment]
cc @icewind1991  @DeepDiver1975 Another app that went crazy.

**Comment by PVince81** [comment]
Please reopen if this still occurs on recent versions of OC without third party apps.
