### ISSUE TITLE
Warning messages during the package upgrade from 8.1.3 to 8.2RC1

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#19617]
### Steps to reproduce
1. Install OC 8.1.3 from packages
2. Upgrade to 8.2RC1 from packages

### Expected behaviour
Upgrade is done smoothly

### Actual behaviour
Fatal error during the upgrade about the file_locks table

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apapche 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.2RC1

**Updated from an older ownCloud or fresh install:** updated from 8.1.3

### Upgrade trace
```
INFO Ign http://download.opensuse.org  InRelease
INFO Ign http://archive.ubuntu.com trusty InRelease
INFO Get:1 http://download.opensuse.org  Release.gpg [189 B]
INFO Get:2 http://download.opensuse.org  Release [1054 B]
INFO Ign http://archive.ubuntu.com trusty-updates InRelease
INFO Ign http://archive.ubuntu.com trusty-security InRelease
INFO Get:3 http://download.opensuse.org  Packages [5134 B]
INFO Hit http://archive.ubuntu.com trusty Release.gpg
INFO Hit http://archive.ubuntu.com trusty-updates Release.gpg
INFO Hit http://archive.ubuntu.com trusty-security Release.gpg
INFO Hit http://archive.ubuntu.com trusty Release
INFO Hit http://archive.ubuntu.com trusty-updates Release
INFO Hit http://archive.ubuntu.com trusty-security Release
INFO Hit http://archive.ubuntu.com trusty/main Sources
INFO Hit http://archive.ubuntu.com trusty/restricted Sources
INFO Hit http://archive.ubuntu.com trusty/universe Sources
INFO Hit http://archive.ubuntu.com trusty/main amd64 Packages
INFO Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
INFO Hit http://archive.ubuntu.com trusty/universe amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-updates/main Sources
INFO Hit http://archive.ubuntu.com trusty-updates/restricted Sources
INFO Hit http://archive.ubuntu.com trusty-updates/universe Sources
INFO Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-security/main Sources
INFO Hit http://archive.ubuntu.com trusty-security/restricted Sources
INFO Hit http://archive.ubuntu.com trusty-security/universe Sources
INFO Hit http://archive.ubuntu.com trusty-security/multiverse Sources
INFO Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-security/multiverse amd64 Packages
INFO Fetched 6377 B in 3s (1616 B/s)
INFO Reading package lists...
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-3rdparty
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-activity
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-encryption
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-external
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-encryption
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-external
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-locking
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-pdfviewer
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-sharing
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-texteditor
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-trashbin
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-versions
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-videoviewer
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-firstrunwizard
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-gallery
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-provisioning-api
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-templateeditor
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-updater
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-user-external
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-user-ldap
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-user-webdavauth
WARNING W: You may want to run apt-get update to correct these problems
INFO run_remote {'error_log_level': 30, 'cmd': ('apt-cache', 'madison', u'owncloud'), 'output_log_level': 20}
INFO   owncloud | 8.2~RC1-2.1 | http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.2:/testing/xUbuntu_14.04/  Packages
INFO   owncloud | 6.0.1+dfsg-1ubuntu1.2 | http://archive.ubuntu.com/ubuntu/ trusty-updates/universe amd64 Packages
INFO   owncloud | 6.0.1+dfsg-1ubuntu1 | http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
INFO   owncloud | 6.0.1+dfsg-1ubuntu1 | http://archive.ubuntu.com/ubuntu/ trusty/universe Sources
INFO   owncloud | 6.0.1+dfsg-1ubuntu1.2 | http://archive.ubuntu.com/ubuntu/ trusty-updates/universe Sources
INFO run_remote {'error_log_level': 30, 'cmd': ('apt-get', 'install', '-y', u'owncloud'), 'output_log_level': 20}
INFO Reading package lists...
INFO Building dependency tree...
INFO Reading state information...
INFO The following extra packages will be installed:
INFO   owncloud-config-apache owncloud-server
INFO Suggested packages:
INFO   clamav clamav-daemon smbclient libreoffice-writer php5-apcu php-apc
INFO The following packages will be upgraded:
INFO   owncloud owncloud-config-apache owncloud-server
INFO 3 upgraded, 0 newly installed, 0 to remove and 89 not upgraded.
INFO Need to get 22.4 MB of archives.
INFO After this operation, 1657 kB of additional disk space will be used.
INFO Get:1 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.2:/testing/xUbuntu_14.04/  owncloud-server 8.2~RC1-2.1 [22.4 MB]
INFO Get:2 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.2:/testing/xUbuntu_14.04/  owncloud 8.2~RC1-2.1 [30.0 kB]
INFO Get:3 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.2:/testing/xUbuntu_14.04/  owncloud-config-apache 8.2~RC1-2.1 [6794 B]
WARNING debconf: unable to initialize frontend: Dialog
WARNING debconf: (TERM is not set, so the dialog frontend is not usable.)
WARNING debconf: falling back to frontend: Readline
WARNING debconf: unable to initialize frontend: Readline
WARNING debconf: (This frontend requires a controlling tty.)
WARNING debconf: falling back to frontend: Teletype
WARNING dpkg-preconfigure: unable to re-open stdin: 
INFO Fetched 22.4 MB in 12s (1762 kB/s)
INFO (Reading database ... 29485 files and directories currently installed.)
INFO Preparing to unpack .../owncloud-server_8.2~RC1-2.1_all.deb ...
INFO owncloud-server: occ maintenance:mode --on
INFO Maintenance mode enabled
INFO Unpacking owncloud-server (8.2~RC1-2.1) over (8.1.3-3.1) ...
INFO Preparing to unpack .../owncloud_8.2~RC1-2.1_all.deb ...
INFO Unpacking owncloud (8.2~RC1-2.1) over (8.1.3-3.1) ...
INFO Preparing to unpack .../owncloud-config-apache_8.2~RC1-2.1_all.deb ...
INFO Unpacking owncloud-config-apache (8.2~RC1-2.1) over (8.1.3-3.1) ...
INFO Conf owncloud disabled.
INFO To activate the new configuration, you need to run:
INFO   service apache2 reload
INFO  * Reloading web server apache2
INFO  * 
INFO Setting up owncloud-server (8.2~RC1-2.1) ...
INFO ownCloud or one of the apps require upgrade - only a limited number of commands are available
INFO Maintenance mode disabled
WARNING PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.file_locks' doesn't exist' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
WARNING Stack trace:
WARNING #0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
WARNING #1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
WARNING #2 /var/www/owncloud/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `fi...', Array, Array)
WARNING #3 /var/www/owncloud/lib/private/lock/dblockingprovider.php(184): OC\DB\Connection->executeUpdate('DELETE FROM `*P...', Array)
WARNING #4 /var/www/owncloud/lib/private/lock/dblockingprovider.php(188): OC\Lock\DBLockingProvider->cleanEmptyLocks()
INFO owncloud-server: occ upgrade
WARNING #5 [internal function]: OC\Lock\DBLockingProvider->__destruct()
WARNING #6 {main}
WARNING 
WARNING Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[42S02] in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 53
INFO ownCloud or one of the apps require upgrade - only a limited number of commands are available
INFO Set log level to debug - current level: 'Warning'
INFO Turned on maintenance mode
INFO Checked database schema update
INFO Checked database schema update for apps
INFO Updated database
INFO Updating <files_texteditor> ...
INFO Updated <files_texteditor> to 2.0
INFO Updating <gallery> ...
INFO Updated <gallery> to 14.2.0
INFO Updating <files> ...
INFO Updated <files> to 1.1.11
INFO Updating <activity> ...
INFO Updated <activity> to 2.1.3
INFO Updating <files_sharing> ...
INFO Updated <files_sharing> to 0.6.3
INFO Update successful
INFO Turned off maintenance mode
INFO Reset log level to 'Warning'
INFO Maintenance mode disabled
INFO Setting up owncloud (8.2~RC1-2.1) ...
INFO Setting up owncloud-config-apache (8.2~RC1-2.1) ...
INFO Enabling conf owncloud.
INFO To activate the new configuration, you need to run:
INFO   service apache2 reload
INFO  * Reloading web server apache2
INFO  * 
WARNING apache2_invoke rewrite: already enabled
WARNING invoke-rc.d: policy-rc.d denied execution of restart.
WARNING apache2_invoke owncloud: already enabled
WARNING invoke-rc.d: policy-rc.d denied execution of reload.
INFO 2015-10-07T08:46:56.358028071Z Oct  7 08:46:55 2e5d9b152041 owncloud-config-apache: apache2_invoke rewrite: already enabled
INFO 2015-10-07T08:46:56.358028071Z Oct  7 08:46:56 2e5d9b152041 owncloud-config-apache: apache2_invoke owncloud: already enabled
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-3rdparty
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-activity
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-encryption
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-external
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-encryption
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-external
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-locking
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-pdfviewer
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-sharing
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-texteditor
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-trashbin
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-versions
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-videoviewer
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-firstrunwizard
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-gallery
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-provisioning-api
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-templateeditor
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-updater
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-user-external
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-user-ldap
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-user-webdavauth
WARNING W: You may want to run apt-get update to correct these problems
```

### Notes
The test is affected by https://github.com/owncloud/core/issues/19614 so I can't say if it's a critical issue or not, but it looks bad.

@jnweiger could you confirm that the lines regarding packaging can be safely ignored, so we can focus on the PHP fatal exception?

**Comment by nickvergessen** [comment]
@icewind1991 locking issue

**Comment by nickvergessen** [comment]
Should we catch the exception here:
https://github.com/owncloud/core/blob/b945d713845d640d63241de4d5a67813384b88ce/lib/private/lock/dblockingprovider.php#L188-188 ? 
Or is it too risky?

**Comment by nickvergessen** [comment]
Second idea, only call the method when we acquired at least one lock.

**Comment by jnweiger** [comment]
@jvillafanez 'The WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-3rdparty' is a different issue.  I am looking into that. It appears on some older versions of apt, where versioned Provides are not supported.

**Comment by DeepDiver1975** [comment]
> WARNING PHP Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.file_locks' doesn't exist' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91 WARNING Stack trace: WARNING #0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array) WARNING #1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array) WARNING #2 /var/www/owncloud/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `fi...', Array, Array) WARNING #3 /var/www/owncloud/lib/private/lock/dblockingprovider.php(184): OC\DB\Connection->executeUpdate('DELETE FROM `*P...', Array) WARNING #4 /var/www/owncloud/lib/private/lock/dblockingprovider.php(188): OC\Lock\DBLockingProvider->cleanEmptyLocks() INFO owncloud-server: occ upgrade WARNING #5 [internal function]: OC\Lock\DBLockingProvider->__destruct() WARNING #6 {main} WARNING

looks like we are executing a repair step before the table has been generated - we might want to add a check if the table exists

@icewind1991 @PVince81 @nickvergessen objections?

**Comment by icewind1991** [comment]
sounds good

**Comment by jvillafanez** [comment]
@jnweiger your packaging issue: https://github.com/owncloud/core/issues/19622
