### ISSUE TITLE
Open a federated shared file from external storage with encryption enabled in a server without encryption returns internal server error.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19881]
### Steps to reproduce

Having 2 servers, server A and server B.
In server A do:
1. Enable encryption app and default module.
2. Enable external storage.
3. Set up local external folder.
4. Upload a file file1.txt to the local external folder.
5. Using federated sharing share file1.txt with admin in server B.
In server B do:
6. Accept federated shared.
7. Open file.

### Expected behaviour
file is opened in server B.

### Actual behaviour
Internal server error.

### Server configuration
**Operating system**:
Server A uses Ubuntu 14.04
Server B uses CentOS 6.6 (php54)

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"8.2.0.12","versionstring":"8.2.0","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Encryption.
External storage.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes Local.

**Are you using encryption:** 
Yes. in server A.

**Server logs**
```
{"reqId":"tRIzpxfsJ5u6CYnIy\/Q5","remoteAddr":"IP_HIDDEN","app":"index","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ServerException\",\"Message\":\"Server error response [url] http:\\\/\\\/HOST_HIDDEN\\\/public.php\\\/webdav\\\/ [status code] 500 [reason phrase] Internal Server Error\",\"Code\":500,\"Trace\":\"
#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Subscriber\\\/HttpError.php(33): GuzzleHttp\\\\Exception\\\\RequestException::create(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Message\\\\Response))\\n
#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Event\\\/Emitter.php(109): GuzzleHttp\\\\Subscriber\\\\HttpError->onComplete(Object(GuzzleHttp\\\\Event\\\\CompleteEvent), 'complete')\\n
#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(91): GuzzleHttp\\\\Event\\\\Emitter->emit('complete', Object(GuzzleHttp\\\\Event\\\\CompleteEvent))\\n
#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n
#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(24): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n
#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n
#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n
#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(135): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n
#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(232): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n
#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(192): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n
#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/http\\\/client\\\/client.php(123): GuzzleHttp\\\\Client->get('http:\\\/\\\/docker.o...', Array)\\n
#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(347): OC\\\\Http\\\\Client\\\\Client->get('http:\\\/\\\/docker.o...', Array)\\n
#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(286): OC\\\\Files\\\\Storage\\\\DAV->fopen('', 'r')\\n
#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(302): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('', 'r')\\n
#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(286): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->fopen('', 'r')\\n
#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1021): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('', 'r')\\n
#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(871): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/Manuel.txt', Array, 'r')\\n
#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/preview\\\/txt.php(47): OC\\\\Files\\\\View->fopen('\\\/Manuel.txt', 'r')\\n
#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/preview.php(1136): OC\\\\Preview\\\\TXT->getThumbnail('\\\/Manuel.txt', 2048, 2048, false, Object(OC\\\\Files\\\\View))\\n
#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/preview.php(770): OC\\\\Preview->generatePreview(15)\\n
#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/preview.php(795): OC\\\\Preview->getPreview()\\n
#21 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/ajax\\\/preview.php(63): OC\\\\Preview->showPreview()\\n
#22 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n
#23 [internal function]: __lambda_func(Array)\\n
#24 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func('?lambda_605', Array)\\n
#25 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n
#26 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n
#27 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":89}","level":3,"time":"2015-10-20T07:58:31+00:00"}
```

**Comment by PVince81** [comment]
@schiesbn

**Comment by PVince81** [comment]
@SergioBertolinSG is this a regression ? I thought this used to work in 8.0 and/or 8.1

**Comment by SergioBertolinSG** [comment]
Yes it is a regression. It works fine on stable8.

**Comment by PVince81** [comment]
regression => bisect possible

**Comment by schiesbn** [comment]
@SergioBertolinSG did you also tried it without encryption? The error messages are not encryption specific.... a general bug with federated sharing and/or  external storages?

**Comment by PVince81** [comment]
Regression => setting to 8.2.1 @DeepDiver1975 @cmonteroluque @karlitschek

**Comment by SergioBertolinSG** [comment]
@schiesbn without encryption there is no problem.

**Comment by SergioBertolinSG** [comment]
After some bisecting this was the first commit to fail 9858a6f7059dbf327365a2b259a57de81b6a3e8a
After that failure something happened to the environment and it kept working all the time.

**Comment by PVince81** [comment]
I don't think that commit is the breaking one. We'd need to bisect again in an environment where we're sure we won't get false positives.

**Comment by PVince81** [comment]
I don't think this is necessarily a regression. When I original wrote this I didn't see that it was using an external storage. The part that should work is without the external storage.

**Comment by PVince81** [comment]
I just tested this, ownCloud v8.2.0 from git as server A and ownCloud 8.2 from the tarball as server B.
It works fine, I'm able to open the shared file.

@SergioBertolinSG did you log out then log in again after enabling encryption ?

**Comment by SergioBertolinSG** [comment]
Yes I did.
Well i have retested in a complete new environment and I can't reproduce, so I am closing this. If we see this again, please reopen.
