### ISSUE TITLE
Shared download produces owncloud server error message (no download)

### ISSUE THREAD

**Issue by enoversum** [owncloud/core#19929]
When I uploaded a file and share the link, clicking the download button on the resulting link gives out an error in the console (Uncaught ReferenceError: oc_appconfig is not defined - shareconfigmodel.js) plus an owncloud warning of an internal server error displayed on the page itself.

Owncloud log states (anonymised):
```
Exception: {"Exception":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","Message":"An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files_sharing\", \"public_shared_file_downloaded\", \"[\\\"\\\\\\\/[gfx]\\\\\\\/[Archiv]\\\\\\\/kiwi\\\\\\\/Dangel-Website\\\\\\\/Dangel-Website.rar\\\"]\", \"\", \"[]\", \"\\\/[gfx]\\\/[Archiv]\\\/kiwi\\\/Dangel-Website\\\/Dangel-Website.rar\", \"\", null, \"eno\", 1445420769, 30, \"public_links\", \"\", 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","Code":0,"Trace":"#0 \/var\/www\/xxxx\/html\/files\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/xxxx\/html\/files\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/var\/www\/xxxx\/html\/files\/lib\/private\/db\/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/var\/www\/xxxx\/html\/files\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php(208): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array, Array)\n#4 \/var\/www\/xxxx\/html\/files\/lib\/private\/db\/querybuilder\/querybuilder.php(121): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 \/var\/www\/xxxx\/html\/files\/apps\/activity\/lib\/data.php(126): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#6 \/var\/www\/xxxxm\/html\/files\/apps\/activity\/lib\/consumer.php(74): OCA\\Activity\\Data->send(Object(OC\\Activity\\Event))\n#7 \/var\/www\/xxxx\/html\/files\/lib\/private\/activitymanager.php(188): OCA\\Activity\\Consumer->receive(Object(OC\\Activity\\Event))\n#8 \/var\/www\/xxxx\/html\/files\/lib\/private\/activitymanager.php(215): OC\\ActivityManager->publish(Object(OC\\Activity\\Event))\n#9 \/var\/www\/xxxx\/html\/files\/apps\/files_sharing\/lib\/controllers\/sharecontroller.php(288): OC\\ActivityManager->publishActivity('files_sharing', 'public_shared_f...', Array, '', Array, '\/[gfx]\/[Archiv]...', '', 'eno', 'public_links', 30)\n#10 [internal function]: OCA\\Files_Sharing\\Controllers\\ShareController->downloadShare('nwBj9WILDDmOns4', NULL, '', '')\n#11 \/var\/www\/xxxx\/html\/files\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#12 \/var\/www\/xxxx\/html\/files\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#13 \/var\/www\/xxxx\/html\/files\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#14 \/var\/www\/xxxx\/html\/files\/lib\/public\/appframework\/app.php(134): OC\\AppFramework\\App::main('ShareController', 'downloadShare', Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#15 \/var\/www\/xxxx\/html\/files\/core\/routes.php(124): OCP\\AppFramework\\App->dispatch('ShareController', 'downloadShare')\n#16 [internal function]: OC\\Route\\Router->{closure}(Array)\n#17 \/var\/www\/xxxx\/html\/files\/lib\/private\/route\/router.php(282): call_user_func(Object(Closure), Array)\n#18 \/var\/www\/xxxx\/html\/files\/lib\/base.php(831): OC\\Route\\Router->match('\/s\/nwBj9WILDDmO...')\n#19 \/var\/www\/xxxx\/html\/files\/index.php(39): OC::handleRequest()\n#20 {main}","File":"\/var\/www\/xxxx\/html\/files\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":71}
```
*As proposed by @PVince81 , a separate ticket.*

**Comment by enoversum** [comment]
Addendum: Had a few issues yesterday producing download links via web interface in the first place pointing to the activities app already, so this might be the culprit.

**Comment by nickvergessen** [comment]
You didn't delete the old files and just uploaded the new files into the existing folder.

https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

**Comment by enoversum** [comment]
That’s possibly right. Will check then to make sure!

**Comment by nickvergessen** [comment]
The error you are seeing is form the activity app, because the database schema was not updated.
This is the case when your have an old file telling the activity app that you still have an old version.

**Comment by enoversum** [comment]
Confirmed, file is now downloadable. Sorry for the trouble!
