### ISSUE TITLE
[8.2.0] After upgrade get white screen upon login, probably encryption related

### ISSUE THREAD

**Issue by josh4trunks** [owncloud/core#19965]
![screenshot from 2015-10-21 22-15-10](https://cloud.githubusercontent.com/assets/1018807/10658566/0fec02f0-784d-11e5-9eff-252162ee48bb.png)
### Steps to reproduce
1. Upgrade from 8.1.3 with encryption enabled
2. Try to login
3. Tried running "occ encryption:migrate" just in case.

### Expected behaviour
Should be able to login and open files

### Actual behaviour
Something seemed to have gone wrong when I first tried 'occ upgrade' as seen in the screenshot.
After running 'occ upgrade' again everything seemed to have worked. But, when I try to login I'm shown a white screen.

Using occ I enabled files_locking and this allows me to login, but I always have the yellow banner ``Encryption App is enabled but your keys are not initialized, please log-out and log-in again``
Trying to download a file gives me an error ``Can't read file``

### Server configuration
**Operating system**: FreeBSD 10.1 64 bit

**Web server:** nginx

**Database:** MariaDB 10.0

**PHP version:** 5.6.11

**ownCloud version:** 8.2.0

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
```Enabled:
  - activity: 2.1.3
  - encryption: 1.1.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - updater: 0.6
```
Previously I also had the mail, news, ownnote, documents, calendar, contacts enabled as seen in the attached screenshot.

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocb072aa2d38",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.jruehlig.com"
        ],
        "datadirectory": "\/mnt\/files",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost:\/mnt\/mysql\/mysql.sock",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "syslog",
        "loglevel": 0,
        "forcessl": false,
        "mail_smtpmode": "smtp",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_domain": "jruehlig.com",
        "mail_from_address": "owncloud",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": true,
        "theme": "",
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/www.jruehlig.com\/owncloud",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Markdown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using encryption:** yes

### Client configuration
**Browser:** Firefox & Chrome

**Operating system:**
Arch Linux 64bit

#### Syslog (nginx/php-fpm/owncloud)
```
Oct 22 00:55:35 192.168.1.11 php-fpm[918]: {PHP} Call to a member function getUID() on boolean at /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php#92
Oct 22 00:55:35 192.168.1.11 kernel: Oct 22 00:55:35 webserver php-fpm[918]: {PHP} Call to a member function getUID() on boolean at /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php#92
Oct 22 00:55:35 192.168.1.11 nginx: 2015/10/22 00:55:35 [error] 32699#0: *1663 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getUID() on boolean in /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php on line 92" while reading response header from upstream, client: 192.168.3.185, server: www.jruehlig.com, request: "POST /owncloud/index.php HTTP/1.1", upstream: "fastcgi://unix:/usr/jails/owncloud/var/run/php-fpm.sock:", host: "www.jruehlig.com"
Oct 22 00:55:35 192.168.1.11 kernel: Oct 22 00:55:35 webserver webserver nginx: 2015/10/22 00:55:35 [error] 32699#0: *1663 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getUID() on boolean in /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php on line 92" while reading response header from upstream, client: 192.168.3.185, server: www.jruehlig.com, request: "POST /owncloud/index.php HTTP/1.1", upstream: "fastcgi://unix:/usr/jails/owncloud/var/run/php-fpm.sock:", host: "www.jruehlig.com"
Oct 22 00:55:38 192.168.1.11 ownCloud[918]: {webdav} Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 \/usr\/local\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(148): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/usr\/local\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(121): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/
Oct 22 00:55:39 192.168.1.11 php-fpm[918]: {PHP} Call to a member function getUID() on boolean at /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php#92
Oct 22 00:55:39 192.168.1.11 kernel: Oct 22 00:55:39 webserver php-fpm[918]: {PHP} Call to a member function getUID() on boolean at /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php#92
Oct 22 00:55:39 192.168.1.11 nginx: 2015/10/22 00:55:39 [error] 32699#0: *1667 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getUID() on boolean in /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php on line 92" while reading response header from upstream, client: 98.207.83.15, server: www.jruehlig.com, request: "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://unix:/usr/jails/owncloud/var/run/php-fpm.sock:", host: "www.jruehlig.com"
Oct 22 00:55:39 192.168.1.11 kernel: Oct 22 00:55:39 webserver webserver nginx: 2015/10/22 00:55:39 [error] 32699#0: *1667 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getUID() on boolean in /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php on line 92" while reading response header from upstream, client: 98.207.83.15, server: www.jruehlig.com, request: "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://unix:/usr/jails/owncloud/var/run/php-fpm.sock:", host: "www.jruehlig.com"
```

**Comment by josh4trunks** [comment]
I'd love some guidance in what's possibly wrong here. I have a few family members that rely on this owncloud install so I don't want to have it non-operational for too long. Also, I'd love to not lose their data. Worst case scenario I restore to a snapshot a day ago but I'd rather move to OC8.2 if possible.

Thanks!

**Comment by nickvergessen** [comment]
@schiesbn

**Comment by nickvergessen** [comment]
Your update shows an error in teh documents app. This may cause faulty/incomplete updates to be performed.

The `Call to a member function getUID() on boolean` from your log seems to be a valid issue, but it only affects writing another error message to the actual log:
`Encryption Library couldn't generate users key-pair for 'no-username-given'`

The code is not called for users that are not logged in. SO that might be caused by the `401 No basic authentication headers were found` error you have.

**Comment by josh4trunks** [comment]
Yeah, I was hit with another bug where an incompatible documents app was shipped in the tar. I replaced it with the correct one from the owncloud/documents repo and am successfully able to enable it.

**Comment by josh4trunks** [comment]
Also here's some non-standard details to my setup that didn't cause issues before. But might be causing hiccups with 8.2.0.
* My webserver stack is HAProxy (HTTPS) > Varnish (caching, gzip) > nginx > php-fpm
* My datadirectory is actually an NFS mountpoint. I played around with the "nolockd" option yesterday otherwise locks on this directory wouldn't work. Going to look into this more.
* owncloud connects to a mysql file socket, at a non-default location (not /tmp/mysql.sock)

I'm starting to think this might be caused by caching in the varnish layer. Gonna flush it, and also bypass it and see if I can get things to work.

**Comment by josh4trunks** [comment]
I cut out HAProxy and Varnish and accessed nginx directly. Same issue.

**Comment by josh4trunks** [comment]
@nickvergessen your fix https://github.com/owncloud/core/issues/19970 seemed to have fixed it for me =]
Everything works as expected with or without the files_locking app enabled.
