### ISSUE TITLE
[Proposal] Show username when triggering 507 Insufficient Storage

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#19974]
It would be really nice to get the username when the system is triggering **507 Insufficient Storage** in the logs.

**Comment by pierrejochem** [comment]
```json
{"reqId":"jd36n3yf0u5eICbG63dZ","remoteAddr":"X.X.X.X","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 507 Insufficient Storage\",\"Code                                                                                                                                                                \":0,\"Trace\":\"#0 [internal function]: OC\\\\Connector\\\\Sabre\\\\QuotaPlugin->checkQuota('one4all\\\/ALL_4_O...', Resource id #35, Object(OC\\\\Connector                                                                                                                                                                \\\\Sabre\\\\Directory), false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Arra                                                                                                                                                                y, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1051): Sabre\\\\Event\\\\EventEmitter->emit('beforeCreateFi                                                                                                                                                                l...', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('one4all\\                                                                                                                                                                \/ALL_4_O...', Resource id #35, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\                                                                                                                                                                \Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/v                                                                                                                                                                ar\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\                                                                                                                                                                /www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(                                                                                                                                                                Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www                                                                                                                                                                \\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connec                                                                                                                                                                tor\\\/sabre\\\/quotaplugin.php\",\"Line\":108}","level":4,"time":"2015-10-22T10:40:57+00:00"}
```

**Comment by DeepDiver1975** [comment]
well - with 9.0 we will migrate to the new dav interface which will hold the username in the url and since the url is logged as well this is then kind of fullfilled.

But in addition it should not hurt to add the username to the log.

@pierrejochem wana take care of this?

This where we can add this https://github.com/owncloud/core/blob/master/apps/dav/lib/connector/sabre/exceptionloggerplugin.php#L81

**Comment by pierrejochem** [comment]
Okay, this new structure is only in current master? Right?

**Comment by nickvergessen** [comment]
yes

**Comment by pierrejochem** [comment]
@nickvergessen Then I have to create a new DEV env ;-)

**Comment by pierrejochem** [comment]
Here we go:

https://github.com/owncloud/core/pull/19978
