### ISSUE TITLE
Error on Sidebar open - no activity shown

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/core#20039]
OC 8.2.0
-> Clicking on a file to open it
-> No Acitivity History shown, loading-icon keeps there endless
![no-activity](https://cloud.githubusercontent.com/assets/4741199/10726448/12f21ece-7bd3-11e5-8ce2-f108c324161f.png)
-> Other tabs like Share work without problems.
Exception in Admin Log:

`
Exception: {"Exception":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","Message":"An exception occurred while executing 'SELECT * FROM 'oc_activity' WHERE 'affecteduser' = ? AND 'type' IN (?,?,?,?,?,?,?) AND 'object_type' = ? AND 'object_id' = ? ORDER BY 'timestamp' DESC LIMIT 30 OFFSET 0' with params [\"xxxx\", \"file_created\", \"file_changed\", \"file_deleted\", \"file_restored\", \"shared\", \"remote_share\", \"public_links\", \"files\", 4293]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'where clause'","Code":0,"Trace":"#0 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT * FROM ...', Array)\n#2 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/apps\/activity\/lib\/data.php(253): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/apps\/activity\/lib\/data.php(233): OCA\\Activity\\Data->getActivities(30, 0, ' AND 'type' IN ...', Array, Object(OCA\\Activity\\GroupHelper))\n#4 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/apps\/activity\/controller\/activities.php(147): OCA\\Activity\\Data->read(Object(OCA\\Activity\\GroupHelper), Object(OCA\\Activity\\UserSettings), 0, 30, 'filter', '', 'files', 4293)\n#5 [internal function]: OCA\\Activity\\Controller\\Activities->fetch(1, 'filter', 'files', 4293)\n#6 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Activity\\Controller\\Activities), 'fetch')\n#8 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Activity\\Controller\\Activities), 'fetch')\n#9 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ActivitiesContr...', 'fetch', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/lib\/private\/route\/router.php(282): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/lib\/base.php(831): OC\\Route\\Router->match('\/apps\/activity\/...')\n#13 \/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/index.php(39): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/xxxx\/htdocs\/xxxx\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":71} 
`

**Comment by PVince81** [comment]
@stefan-niedermann did you properly update your activity app ?

CC @nickvergessen

**Comment by nickvergessen** [comment]
https://github.com/owncloud/activity/issues/419#issuecomment-149830559

**Comment by stefan-niedermann** [comment]
thanks! my fault.
