### ISSUE TITLE
MySQL exception while updating 8.1.3->8.1.4 with Aptitude on Debian Jessie

### ISSUE THREAD

**Issue by Pastafarianist** [owncloud/core#20247]
```
Preparing to unpack .../owncloud-server_8.1.4-12.1_all.deb ...
owncloud-server: occ maintenance:mode --on
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/owncloud/lib/private/db/connection.php:50
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/owncloud/lib/private/db/connection.php(83): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/owncloud/lib/private/db/connectionfactory.php(124): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/owncloud/lib/private/server.php(301): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/owncloud/lib/private/appframework/utility/simplecontainer.php(96): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /var/www/owncloud/lib/private/server.php(696): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /var/www/owncloud/lib/private/db.php(42): OC\Server->getDatabaseConnection()
#12 /var/www/owncloud/lib/private/server.php(209): OC_DB::getConnection()
#13 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#14 /var/www/owncloud/lib/private/appframework/utility/simplecontainer.php(96): Pimple\Container->offsetGet('AppConfig')
#15 /var/www/owncloud/lib/private/server.php(642): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /var/www/owncloud/lib/private/server.php(343): OC\Server->getAppConfig()
#17 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/owncloud/lib/private/appframework/utility/simplecontainer.php(96): Pimple\Container->offsetGet('AppManager')
#19 /var/www/owncloud/lib/private/server.php(862): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#20 /var/www/owncloud/lib/private/app.php(238): OC\Server->getAppManager()
#21 /var/www/owncloud/lib/private/app.php(93): OC_App::getEnabledApps()
#22 /var/www/owncloud/lib/base.php(592): OC_App::loadApps(Array)
#23 /var/www/owncloud/lib/base.php(1122): OC::init()
#24 /var/www/owncloud/console.php(41): require_once('/var/www/ownclo...')
#25 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#26 {main}Unpacking owncloud-server (8.1.4-12.1) over (8.1.3-13.1) ...
```
### Server configuration
- Debian Jessie ARM
- Apache 2.4.17
- MariaDB 10.0.22
- PHP 5.6.14

**Comment by DeepDiver1975** [comment]
@jnweiger please have a look - THX

**Comment by jnweiger** [comment]
My assumption is that occ maintenance:mode --on brings the server in a safe state, so that we can upgrade. It is unclear, what we should do if that assumption is false, as apparently is in this case.

**Comment by RealRancor** [comment]
From my PoV thats a state which can't be handled by the packages. If the MySQL server is not running the db update is also failing on manual installations.

**Comment by jnweiger** [comment]
occ maintenance:mode --on must not explode, when mysql server is unreachable.

**Comment by MorrisJobke** [comment]
> occ maintenance:mode --on must not explode, when mysql server is unreachable.

This would require to write a completely unrelated command that only updates the config.php entry without using the lib/base.php stack. I guess this is too much effort for that specific use case and also adds another maintenance penalty to the code.

Should we provide the maintenance:mode occ command without any lib/base.php bootstrapping to allow the above scenario? I guess this should be the decision of @PVince81 @karlitschek @DeepDiver1975

**Comment by PVince81** [comment]
Pffff.....

Maybe if the DB init code was totally lazy, like only create the DB connection whenever needed, for example when calling `getDatabaseConnection()` and not any time inside base.php. In this case it might help escape such errors.

**Comment by PVince81** [comment]
8.1 is EOL. Please try again with recent versions.
