### ISSUE TITLE
Internal server when downloading shared files

### ISSUE THREAD

**Issue by alexara** [owncloud/core#20276]
## Steps to reproduce
Share a folder.
Open the shared link and try to download the files.

## Expected behaviour
No error log should exist.
Actual behaviour.

## Additional information
Everything else works fine. Files can be downloaded without flaw when they are accessed by a non-shared link.

## Server configuration
**Operating system:** Raspbian GNU/Linux 8.0 (jessie)
**Web server:** Nginx 1.8.0
**Database:** MySQL 14.14 Distrib 5.5.44, for debian-linux-gnu (armv7l) using readline 6.3
**PHP version:** PHP 5.6.14-0+deb8u1 
**ownCloud version:** 8.2.0
**Updated from an older ownCloud or fresh install:** 8.1.3 -> 8.2.0
**List of activated apps:** default +calendar +contacts +filelocking
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** WebDav

### config.php
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'cloud.domain.tld',
  ),
  'filelocking.enabled' => 'true',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'cache_path' => '',
  'datadirectory' => '/var/www/domain.tld/htdocs/owncloud/data',
  'overwrite.cli.url' => 'https://cloud.domain.tld/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => '',
  'dbhost' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'loglevel' => 2,
  'theme' => '',
  'maintenance' => false,
);
```
## Client configuration
**Browser:** Firefox 41.0.2
**Operating system:** (X)Ubuntu 15.10

#### ownCloud log (data/owncloud.log)
```
{"reqId":"BTn3plmQSGKPf1aJvuFN","remoteAddr":"XX.XXX.XX.XXX","app":"hook","message":"error while running hook (OCA\\Activity\\FilesHooksStatic::fileCreate): An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files\", \"created_self\", \"[\\\"\\\\\\\/Documents\\\\\\\/ebooks\\\"]\", \"\", \"[]\", \"\\\/Documents\\\/ebooks\", \"https:\\\/\\\/cloud.domain.tld\\\/owncloud\\\/index.php\\\/apps\\\/files?dir=%2FDocuments\", \"alex\", \"alex\", 1446585188, 30, \"file_created\", \"files\", 323]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","level":3,"time":"2015-11-03T21:13:08+00:00"}
{"reqId":"yaRs807mvBDhytig7kbn","remoteAddr":"XX.XXX.XX.XXX","app":"hook","message":"error while running hook (OCA\\Activity\\FilesHooksStatic::fileCreate): An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files\", \"created_self\", \"[\\\"\\\\\\\/Documents\\\\\\\/ebooks\\\\\\\/file1.pdf\\\"]\", \"\", \"[]\", \"\\\/Documents\\\/ebooks\\\/file1.pdf\", \"https:\\\/\\\/cloud.domain.tld\\\/owncloud\\\/index.php\\\/apps\\\/files?dir=%2FDocuments%2Febooks\", \"alex\", \"alex\", 1446585240, 30, \"file_created\", \"files\", 324]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","level":3,"time":"2015-11-03T21:14:00+00:00"}
{"reqId":"Ykm8OJwRdRBwaSQfOS18","remoteAddr":"XX.XXX.XX.XXX","app":"hook","message":"error while running hook (OCA\\Activity\\FilesHooksStatic::fileCreate): An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files\", \"created_self\", \"[\\\"\\\\\\\/Documents\\\\\\\/ebooks\\\\\\\/file2.pdf\\\"]\", \"\", \"[]\", \"\\\/Documents\\\/ebooks\\\/file2.pdf\", \"https:\\\/\\\/cloud.domain.tld\\\/owncloud\\\/index.php\\\/apps\\\/files?dir=%2FDocuments%2Febooks\", \"alex\", \"alex\", 1446585243, 30, \"file_created\", \"files\", 325]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","level":3,"time":"2015-11-03T21:14:03+00:00"}
{"reqId":"BPVZc6ton2XK+puBILW9","remoteAddr":"XX.XXX.XX.XXX","app":"hook","message":"error while running hook (OCA\\Activity\\FilesHooksStatic::fileCreate): An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files\", \"created_self\", \"[\\\"\\\\\\\/Documents\\\\\\\/ebooks\\\\\\\/file3.pdf\\\"]\", \"\", \"[]\", \"\\\/Documents\\\/ebooks\\\/file3.pdf\", \"https:\\\/\\\/cloud.domain.tld\\\/owncloud\\\/index.php\\\/apps\\\/files?dir=%2FDocuments%2Febooks\", \"alex\", \"alex\", 1446585246, 30, \"file_created\", \"files\", 326]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","level":3,"time":"2015-11-03T21:14:06+00:00"}
{"reqId":"xEhYbk+lPfjk5Ahb5AOH","remoteAddr":"XX.XXX.XX.XXX","app":"hook","message":"error while running hook (OCA\\Activity\\FilesHooksStatic::fileCreate): An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files\", \"created_self\", \"[\\\"\\\\\\\/Documents\\\\\\\/ebooks\\\\\\\/file4.pdf\\\"]\", \"\", \"[]\", \"\\\/Documents\\\/ebooks\\\/file4.pdf\", \"https:\\\/\\\/cloud.domain.tld\\\/owncloud\\\/index.php\\\/apps\\\/files?dir=%2FDocuments%2Febooks\", \"alex\", \"alex\", 1446585249, 30, \"file_created\", \"files\", 327]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","level":3,"time":"2015-11-03T21:14:09+00:00"}
{"reqId":"t8YrGsrgf7bYMnBqGNw3","remoteAddr":"XX.XXX.XX.XXX","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'SELECT *  FROM `oc_activity`  WHERE `affecteduser` = ?  AND `type` IN (?,?,?,?,?,?,?) AND `object_type` = ? AND `object_id` = ? ORDER BY `timestamp` DESC LIMIT 30 OFFSET 0' with params [\\\"alex\\\", \\\"file_created\\\", \\\"file_changed\\\", \\\"file_deleted\\\", \\\"file_restored\\\", \\\"shared\\\", \\\"remote_share\\\", \\\"public_links\\\", \\\"files\\\", 323]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'where clause'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT *  FROM ...', Array)\\n#2 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/data.php(253): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/data.php(233): OCA\\\\Activity\\\\Data->getActivities(30, 0, ' AND `type` IN ...', Array, Object(OCA\\\\Activity\\\\GroupHelper))\\n#4 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/activity\\\/controller\\\/activities.php(147): OCA\\\\Activity\\\\Data->read(Object(OCA\\\\Activity\\\\GroupHelper), Object(OCA\\\\Activity\\\\UserSettings), 0, 30, 'filter', '', 'files', 323)\\n#5 [internal function]: OCA\\\\Activity\\\\Controller\\\\Activities->fetch(1, 'filter', 'files', 323)\\n#6 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Activity\\\\Controller\\\\Activities), 'fetch')\\n#8 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Activity\\\\Controller\\\\Activities), 'fetch')\\n#9 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ActivitiesContr...', 'fetch', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/apps\\\/activity\\\/...')\\n#13 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71}","level":3,"time":"2015-11-03T21:14:38+00:00"}
{"reqId":"1uqBpjvEALoyL67q0lze","remoteAddr":"XX.XXX.XX.XXX","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'SELECT *  FROM `oc_activity`  WHERE `affecteduser` = ?  AND `type` IN (?,?,?,?,?,?,?) AND `object_type` = ? AND `object_id` = ? ORDER BY `timestamp` DESC LIMIT 30 OFFSET 0' with params [\\\"alex\\\", \\\"file_created\\\", \\\"file_changed\\\", \\\"file_deleted\\\", \\\"file_restored\\\", \\\"shared\\\", \\\"remote_share\\\", \\\"public_links\\\", \\\"files\\\", 323]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'where clause'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT *  FROM ...', Array)\\n#2 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/data.php(253): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/data.php(233): OCA\\\\Activity\\\\Data->getActivities(30, 0, ' AND `type` IN ...', Array, Object(OCA\\\\Activity\\\\GroupHelper))\\n#4 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/activity\\\/controller\\\/activities.php(147): OCA\\\\Activity\\\\Data->read(Object(OCA\\\\Activity\\\\GroupHelper), Object(OCA\\\\Activity\\\\UserSettings), 0, 30, 'filter', '', 'files', 323)\\n#5 [internal function]: OCA\\\\Activity\\\\Controller\\\\Activities->fetch(1, 'filter', 'files', 323)\\n#6 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Activity\\\\Controller\\\\Activities), 'fetch')\\n#8 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Activity\\\\Controller\\\\Activities), 'fetch')\\n#9 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ActivitiesContr...', 'fetch', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/apps\\\/activity\\\/...')\\n#13 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71}","level":3,"time":"2015-11-03T21:14:45+00:00"}
{"reqId":"z\/HGpdT9GcqFPEzpz7\/3","remoteAddr":"XX.XXX.XX.XXX","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'SELECT *  FROM `oc_activity`  WHERE `affecteduser` = ?  AND `type` IN (?,?,?,?,?,?,?) AND `object_type` = ? AND `object_id` = ? ORDER BY `timestamp` DESC LIMIT 30 OFFSET 0' with params [\\\"alex\\\", \\\"file_created\\\", \\\"file_changed\\\", \\\"file_deleted\\\", \\\"file_restored\\\", \\\"shared\\\", \\\"remote_share\\\", \\\"public_links\\\", \\\"files\\\", 323]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'where clause'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT *  FROM ...', Array)\\n#2 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/data.php(253): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/data.php(233): OCA\\\\Activity\\\\Data->getActivities(30, 0, ' AND `type` IN ...', Array, Object(OCA\\\\Activity\\\\GroupHelper))\\n#4 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/activity\\\/controller\\\/activities.php(147): OCA\\\\Activity\\\\Data->read(Object(OCA\\\\Activity\\\\GroupHelper), Object(OCA\\\\Activity\\\\UserSettings), 0, 30, 'filter', '', 'files', 323)\\n#5 [internal function]: OCA\\\\Activity\\\\Controller\\\\Activities->fetch(1, 'filter', 'files', 323)\\n#6 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Activity\\\\Controller\\\\Activities), 'fetch')\\n#8 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Activity\\\\Controller\\\\Activities), 'fetch')\\n#9 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ActivitiesContr...', 'fetch', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/apps\\\/activity\\\/...')\\n#13 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71}","level":3,"time":"2015-11-03T21:14:45+00:00"}
{"reqId":"UWyD2M3qsxAJdxThWGIV","remoteAddr":"XX.XXX.XX.XXX","app":"hook","message":"error while running hook (OCA\\Activity\\FilesHooksStatic::share): An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files_sharing\", \"shared_link_self\", \"[\\\"\\\\\\\/Documents\\\\\\\/ebooks\\\"]\", \"\", \"[]\", \"\\\/Documents\\\/ebooks\", \"https:\\\/\\\/cloud.domain.tld\\\/owncloud\\\/index.php\\\/apps\\\/files?dir=%2FDocuments%2Febooks\", \"alex\", \"alex\", 1446585289, 30, \"shared\", \"files\", 323]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","level":3,"time":"2015-11-03T21:14:49+00:00"}
{"reqId":"axSsRmGEB4dJ48ftTE5x","remoteAddr":"XX.XXX.XX.XXX","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\\\"files_sharing\\\", \\\"public_shared_folder_downloaded\\\", \\\"[\\\\\\\"\\\\\\\\\\\\\\\/Documents\\\\\\\\\\\\\\\/ebooks\\\\\\\"]\\\", \\\"\\\", \\\"[]\\\", \\\"\\\\\\\/Documents\\\\\\\/ebooks\\\", \\\"\\\", null, \\\"alex\\\", 1446585299, 30, \\\"public_links\\\", \\\"\\\", 0]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(203): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array, Array)\\n#4 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/db\\\/querybuilder\\\/querybuilder.php(121): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/data.php(126): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/consumer.php(74): OCA\\\\Activity\\\\Data->send(Object(OC\\\\Activity\\\\Event))\\n#7 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/activitymanager.php(188): OCA\\\\Activity\\\\Consumer->receive(Object(OC\\\\Activity\\\\Event))\\n#8 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/activitymanager.php(215): OC\\\\ActivityManager->publish(Object(OC\\\\Activity\\\\Event))\\n#9 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/controllers\\\/sharecontroller.php(288): OC\\\\ActivityManager->publishActivity('files_sharing', 'public_shared_f...', Array, '', Array, '\\\/Documents\\\/ebooks', '', 'alex', 'public_links', 30)\\n#10 [internal function]: OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController->downloadShare('TmDDwDDIopa7lPk', '', '\\\/', '')\\n#11 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'downloadShare')\\n#13 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/app.php(134): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#15 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/core\\\/routes.php(124): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#16 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#17 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(Closure), Array)\\n#18 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/s\\\/TmDDwDDIopa7...')\\n#19 \\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/domain.tld\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71}","level":3,"time":"2015-11-03T21:14:59+00:00"}

```

**Comment by RealRancor** [comment]
@alexara Which version of the activity app are you running? This looks to me that you're running the code base of version 2.1.3 with an database structure of an older version.

Please remove /apps/activity and extract this folder again from the tar.bz2 archive of oC provided at owncloud.org

**Comment by MorrisJobke** [comment]
@alexara I will close this ticket until you tested this with the current code of the activity app. We can reopen this ticket if it still exists afterwards.

**Comment by alexara** [comment]
> @alexara Which version of the activity app are you running? This looks to me that you're running the code base of version 2.1.3 with a database structure of an older version.
Please remove /apps/activity and extract this folder again from the tar.bz2 archive of oC provided at owncloud.org

> @alexara I will close this ticket until you tested this with the current code of the activity app. We can reopen this ticket if it still exists afterwards.

Problem solved. Thanks! The activity app had indeed not been upgraded from 8.1.3 to 8.2.0 for whatever reason.
