### ISSUE TITLE
ownCloud crash when disable windows network drive app

### ISSUE THREAD

**Issue by jmaciasportela** [owncloud/core#20289]
### Steps to reproduce
1. Enable Windows network drive app (branch integration_fe_1)
2. Create a Mount point using WND backend
3. Disable WND app

### Expected behaviour
Mount point disappear

### Actual behaviour
ownCloud crash. Exception is not captured.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** Mysql

**PHP version:**

**ownCloud version:** Master

#### ownCloud log (data/owncloud.log)
```
{"reqId":"A4CMqP7r67\/axvk2ZMQ3","remoteAddr":"82.159.139.58","app":"index","message":"Exception: {\"Exception\":\"UnexpectedValueException\",\"Message\":\"Invalid backend windows_network_drive\",\"Code\":0,\"Trace\":\"
#0 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/service\\\/storagesservice.php(229): OCA\\\\Files_external\\\\Service\\\\StoragesService->populateStorageConfigWithLegacyOptions(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig), 'user', 'all', Array)\\n
#1 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/service\\\/storagesservice.php(341): OCA\\\\Files_external\\\\Service\\\\StoragesService->readConfig()\\n
#2 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/service\\\/storagesservice.php(350): OCA\\\\Files_external\\\\Service\\\\StoragesService->getAllStorages()\\n
#3 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/service\\\/userglobalstoragesservice.php(120): OCA\\\\Files_external\\\\Service\\\\StoragesService->getStorages()\\n
#4 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config\\\/configadapter.php(117): OCA\\\\Files_External\\\\Service\\\\UserGlobalStoragesService->getUniqueStorages()\\n
#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/config\\\/mountprovidercollection.php(61): OCA\\\\Files_External\\\\Config\\\\ConfigAdapter->getMountsForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n
#6 [internal function]: OC\\\\Files\\\\Config\\\\MountProviderCollection->OC\\\\Files\\\\Config\\\\{closure}(Object(OCA\\\\Files_External\\\\Config\\\\ConfigAdapter))\\n
#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/config\\\/mountprovidercollection.php(62): array_map(Object(Closure), Array)\\n
#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(426): OC\\\\Files\\\\Config\\\\MountProviderCollection->getMountsForUser(Object(OC\\\\User\\\\User))\\n
#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(351): OC\\\\Files\\\\Filesystem::initMountPoints('admin')\\n
#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/util.php(200): OC\\\\Files\\\\Filesystem::init('admin', '\\\/admin\\\/files')\\n
#11 \\\/opt\\\/owncloud\\\/lib\\\/base.php(851): OC_Util::setupFS()\\n
#12 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n
#13 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/service\\\/storagesservice.php\",\"Line\":88}","level":3,"time":"2015-11-04T07:54:54+00:00","method":"GET","url":"\/index.php\/apps\/notifications"}
```

**Comment by PVince81** [comment]
We should probably ignore / disable ext storages from disabled app, but log a warning.

CC @Xenopathic

**Comment by PVince81** [comment]
and @icewind1991

**Comment by jmaciasportela** [comment]
ping @Xenopathic @icewind1991

**Comment by PVince81** [comment]
Crash as in "completely unusable" ? If yes, please raise severity to critical.

**Comment by jmaciasportela** [comment]
```
{"reqId":"l31dLC3aCjEkZfOyxo3f","remoteAddr":"82.159.139.58","app":"index","message":"Exception: {\"Exception\":\"UnexpectedValueException\",\"Message\":\"Invalid backend windows_network_drive\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/service\\\/storagesservice.php(229): OCA\\\\Files_external\\\\Service\\\\StoragesService->populateStorageConfigWithLegacyOptions(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig), 'user', 'all', Array)\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/service\\\/storagesservice.php(341): OCA\\\\Files_external\\\\Service\\\\StoragesService->readConfig()\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/service\\\/storagesservice.php(350): OCA\\\\Files_external\\\\Service\\\\StoragesService->getAllStorages()\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/service\\\/userglobalstoragesservice.php(120): OCA\\\\Files_external\\\\Service\\\\StoragesService->getStorages()\\n#4 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config\\\/configadapter.php(117): OCA\\\\Files_External\\\\Service\\\\UserGlobalStoragesService->getUniqueStorages()\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/config\\\/mountprovidercollection.php(61): OCA\\\\Files_External\\\\Config\\\\ConfigAdapter->getMountsForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#6 [internal function]: OC\\\\Files\\\\Config\\\\MountProviderCollection->OC\\\\Files\\\\Config\\\\{closure}(Object(OCA\\\\Files_External\\\\Config\\\\ConfigAdapter))\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/config\\\/mountprovidercollection.php(62): array_map(Object(Closure), Array)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(426): OC\\\\Files\\\\Config\\\\MountProviderCollection->getMountsForUser(Object(OC\\\\User\\\\User))\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(351): OC\\\\Files\\\\Filesystem::initMountPoints('admin')\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/util.php(200): OC\\\\Files\\\\Filesystem::init('admin', '\\\/admin\\\/files')\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/base.php(851): OC_Util::setupFS()\\n#12 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/service\\\/storagesservice.php\",\"Line\":88}","level":3,"time":"2015-11-20T11:56:05+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/navigationdetect.php"}
```
![error](https://cloud.githubusercontent.com/assets/1454351/11299355/5aff86d6-8f86-11e5-9d97-390bd64362ea.jpg)

**Comment by PVince81** [comment]
Ok, so "completely unusable". Thanks

**Comment by icewind1991** [comment]
Ok, can reproduce this with files_external_ftp will look into it

**Comment by icewind1991** [comment]
Fix is here: https://github.com/owncloud/core/pull/20641
