### ISSUE TITLE
Cannot mount GDrive on master

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20280]
### Steps

1. Enable external storage
1. Enter "gdrive" as mount point name
1. Enter client id and client secret
1. Click "Grant access"

### Expected result
Redirected to google account page, then back.

### Actual result
Red dot appears directly, no redirection.

### Versions
ownCloud 9.0 pre-alpha git master 053effaa5124ac527712ac97193eb444259c69bc

Some suspicious errors:
```
{"reqId":"nLGh5+\/hqAcZaiFVMp4Y","remoteAddr":"127.0.0.1","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating \\\\OC\\\\Files\\\\Storage\\\\Google storage failed\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(258): OC\\\\Files\\\\Storage\\\\Google->__construct(Array)\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/globalstoragescontroller.php(109): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n
#3 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->create('gdrive', 'googledrive', 'oauth2::oauth2', Array, Array, Array, Array, 100)\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n
#8 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n
#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n
#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(852): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n
#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n
#12 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/google.php\",\"Line\":80}","level":3,"time":"2015-11-04T06:49:54+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/globalstorages"}
{"reqId":"nLGh5+\/hqAcZaiFVMp4Y","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined variable: e at \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/config.php#272","level":3,"time":"2015-11-04T06:49:54+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/globalstorages"}
{"reqId":"nLGh5+\/hqAcZaiFVMp4Y","remoteAddr":"127.0.0.1","app":"PHP","message":"Can only throw objects at \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/config.php#272","level":3,"time":"2015-11-04T06:49:54+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/globalstorages"}
```

Works properly in 8.2.0 or stable8.2, broken on master => regression

**Comment by PVince81** [comment]
This fixes it https://github.com/owncloud/core/pull/20358

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/pull/20358
