### ISSUE TITLE
update to 8.1.4 unsuccessful using apt-get: Unable to generate a URL for the named route "contacts_index" as such route does not exist.

### ISSUE THREAD

**Issue by leikinen** [owncloud/core#20347]
### Steps to reproduce
1. useing the package manager (apt-get) update to version 8.1.4 -> owncloud got stuck in maintenance mode (for several ten minutes)
2. restart system, but still stuck in maintenance mode 
3. disabled maintenance mode in config.php -> owncloud appeared to be running normally and showed a new version was available for update
4. press update to new version via web interface (the site before any login) -> update failed
![update to 8 1 4 failed](https://cloud.githubusercontent.com/assets/15685405/10992789/cb66b624-8469-11e5-80a4-fa7a53ded892.png)

### Expected behaviour
update should finish successfully an show login page

### Actual behaviour
the update failed

### Server configuration
**Operating system**:
Ubuntu server 14.04.3 LTS

**Web server:**
apache2

**Database:**
sqlite3

**PHP version:**
PHP Version 5.5.9-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)
8.1.3/4

**Updated from an older ownCloud or fresh install:**
update from 8.1.3

**List of activated apps:**
Defaults plus Calendar and Contacts

```
sudo -u www-data php occ app:list
```
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.3
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - calendar
 - contacts
 - encryption
 - external
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '**********',
  'passwordsalt' => '**********',
  'secret' => '**********',
  'trusted_domains' =>
  array (
    0 => '**********',
    1 => '**********',
  ),
  'datadirectory' => '**********',
  'overwrite.cli.url' => '**********',
  'dbtype' => 'sqlite3',
  'version' => '8.1.3.0',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
);
~                    
```
sudo -u www-data php occ config:list system --public                                                    
```
ownCloud or one of the apps require upgrade - only a limited number of commands are available

                                                            
  [InvalidArgumentException]                                
  There are no commands defined in the "config" namespace.  
    

**Are you using external storage, if yes which one:** local/smb/sftp/... 
no external storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:**
firefox (uptodate)

**Operating system:**
Linux Mint 17 Cinnamon (2.2.16)
Kernel 3.13.0-24

#### Web server error log
no error since restart; no error matching ownc (ignoring case)

#### ownCloud log (data/owncloud.log)

```
{"reqId":"hxxv5Gzc42cY3AD82GoJ","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at /...path...//owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-11-06T02:00:02+00:00"}
{"reqId":"iEsarMIs\/+S8W6KEa8aH","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at /...path...//owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-11-06T05:00:02+00:00"}
{"reqId":"OrweGXlFjccoxvgyzLVW","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at /...path...//owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-11-06T05:00:02+00:00"}
{"reqId":"N9+CUvpUEUn5PIyTuVRr","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at /...path...//owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-11-06T07:45:11+00:00"}
{"reqId":"5RQnnvwIXsZq2f4ZMznO",	"remoteAddr":"---.---.---.---","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-11-06T07:45:36+00:00"}
* deleted duplicates 
{"reqId":"PznrwzvKfqPEV2ogKIPm",	"remoteAddr":"---.---.---.---","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-11-06T08:21:11+00:00"}
{"reqId":"QixmLLViEi4D4SdOzjbY",	"remoteAddr":"---.---.---.---","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(98): OC_App::loadApp('files_sharing')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(127): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/owncloud\\\/index.php(48): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":118}","level":4,"time":"2015-11-06T08:22:13+00:00"}
{"reqId":"mfNllzslVbgMf8Jloc+B",	"remoteAddr":"---.---.---.---","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-11-06T08:22:15+00:00"}
* deleted duplicates 
{"reqId":"zD50WXhVLonZQa3iIG8r",	"remoteAddr":"---.---.---.---","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-11-06T08:23:19+00:00"}
{"reqId":"qCtTN455WdKrVV6gsfhz",	"remoteAddr":"---.---.---.---","app":"core","message":"starting upgrade from 8.1.3.0 to 8.1.4.2","level":0,"time":"2015-11-06T08:23:40+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=qTBoLLX9Nz9%2FzRqguAyw9i1BOkZQyz"}
{"reqId":"JNeaSoUcE0E72GiQgsy6",	"remoteAddr":"---.---.---.---","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-11-06T08:23:51+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"qCtTN455WdKrVV6gsfhz",	"remoteAddr":"---.---.---.---","app":"update","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"contacts_index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(306): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('contacts_index', Array, false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(65): OC\\\\Route\\\\Router->generate('contacts_index', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/helper.php(139): OC\\\\URLGenerator->linkToRoute('contacts_index', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/util.php(306): OC_Helper::linkToRoute('contacts_index', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/app.php(18): OCP\\\\Util::linkToRoute('contacts_index')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(139): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(120): OC_App::requireAppFile('contacts')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(1173): OC_App::loadApp('contacts', false)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(218): OC_App::updateApp('contacts')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(248): OC_Installer::updateApp(Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(511): OC_Installer::updateAppByOCSId('168708')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(332): OC\\\\Updater->upgradeAppStoreApps(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(208): OC\\\\Updater->doUpgrade('8.1.4.2', '8.1.3.0')\\n#13 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(93): OC\\\\Updater->upgrade()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":4,"time":"2015-11-06T08:24:19+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=qTBoLLX9Nz9%2FzRqguAyw9i1BOkZQyz"}
{"reqId":"JViyg2tbA15IQJfc\/DMt",	"remoteAddr":"---.---.---.---","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-11-06T08:24:23+00:00"}
* deleted duplicates 
{"reqId":"9FDWieklYm9G+DUG5Mvx",	"remoteAddr":"---.---.---.---","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-11-06T08:41:05+00:00"}
{"reqId":"pO2H7YVMpK43EDfj5Cq8",	"remoteAddr":"---.---.---.---","app":"remote","message":"Service unavailable","level":4,"time":"2015-11-06T08:41:06+00:00"}
{"reqId":"PQ9bFGX7xgeaO3EkqCXd",	"remoteAddr":"---.---.---.---","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-11-06T08:41:27+00:00"}
* deleted duplicates 
{"reqId":"5p7HQXMEpgoQWFPbOIU2",	"remoteAddr":"---.---.---.---","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-11-06T08:56:55+00:00"}

```

**Comment by MorrisJobke** [comment]
Dup of https://github.com/owncloud/core/issues/19145, https://github.com/owncloud/core/issues/20125, https://github.com/owncloud/core/issues/20207 and some more.

https://github.com/owncloud/core/issues/19145 is still open

Really wonder why people are not finding those duplicates?
