### ISSUE TITLE
is_dir(): open_basedir restriction in effect. OwnCloud 8.2

### ISSUE THREAD

**Issue by team4music** [owncloud/core#20451]
Hi, i get a open_basedir warning. The Problem is that he is trying to acess a folder that is not within my Webserver, correctly it would be /var/www/ but he is trying to reach /srv/www/. I think this might be a bug with a hardcoded variable

```
is_dir(): open_basedir restriction in effect. File(/srv/www/my-domain/team) is not within the allowed path(s): (/var/www/clients/client1/web33/team:/var/www/clients/client1/web33/private:/var/www/clients/client1/web33/tmp:/var/www/my-domain/team:/srv/www/my-domain/team:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/usr/bin:/srv/www/my-domain/team:/dev/urandom) at /var/www/clients/client1/web33/team/3rdparty/symfony/process/Symfony/Component/Process/ExecutableFinder.php#59
```

**Comment by karlitschek** [comment]
you you post a full bug report using this template please? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by team4music** [comment]
### Steps to reproduce
1. Login as Admin
2. Go to Admin Settings Dashboard
3.

### Expected behaviour
Don't know what the effect is

### Actual behaviour
A error message is created within the Logfile

### Server configuration
**Operating system**:
Debian Linux

**Web server:**
Nginx - Extra
**Database:**
Mysql
**PHP version:**
5.4.45-1~dotdeb+7.1 FPM
**ownCloud version:** (see ownCloud admin page)
8.2
**Updated from an older ownCloud or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'HIDDEN',
  'passwordsalt' => 'HIDDEN',
  'secret' => 'HIDDEN',
  'trusted_domains' => 
  array (
    0 => 'team.hidden.de',
  ),
  'datadirectory' => '/var/www/clients/client1/web33/team/data',
  'overwrite.cli.url' => 'http://hidden.de',
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => '1integration',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'HIDDEN_',
  'dbuser' => 'HIDDEN',
  'dbpassword' => 'HIDDEN',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'mail_from_address' => 'update',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'hidden.de',
  'loglevel' => 3,
  'theme' => 'hidden',
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No


### Client configuration
Firefox 42

**Operating system:**
Windows 10

### Logs
#### Web server error log
```
79.210.166.21 - - [10/Nov/2015:08:22:11 +0100] "GET /index.php/apps/notifications HTTP/1.1" 404 162 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
79.210.166.21 - - [10/Nov/2015:08:22:11 +0100] "GET /index.php/apps/encryption/ajax/getStatus HTTP/1.1" 404 162 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
79.210.166.21 - - [10/Nov/2015:08:22:11 +0100] "GET /index.php/apps/files_sharing/api/externalShares HTTP/1.1" 404 162 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
79.210.166.21 - - [10/Nov/2015:08:22:11 +0100] "GET /index.php/apps/files/ajax/scan.php?force=false&dir=&requesttoken=56ae1837bb33f167d9f18f9cea4b2f87df9509694f4cfb396a051e2f16c38df9%7CrhKoAtEZ22G4hhzn%7Cae1f951ad5ab10fa32ce6293cb4948801409cdc38f746b3cea2c50e558607ec4cb57e2fefa99cd1190408c54afe86075c74e7e9b567d972afea047a4c7e80945%3ARpAR%2FkS9VZ HTTP/1.1" 404 162 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
79.210.166.21 - - [10/Nov/2015:08:22:11 +0100] "GET /index.php/apps/documents/ajax/mimes.php HTTP/1.1" 404 162 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
79.210.166.21 - - [10/Nov/2015:08:22:22 +0100] "GET /index.php/apps/files HTTP/1.1" 404 162 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Gfn742wv+MzsxY0JB1Ks","remoteAddr":"79.210.166.21","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"\\\/files\\\/Sonstiges\\\/testfiles\\\/test-office.ods is application\\\/vnd.oasis.opendocument.spreadsheet and is not supported by Documents app\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/apps\\\/documents\\\/lib\\\/file.php(62): OCA\\\\Documents\\\\File->initViews()\\n#1 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/apps\\\/documents\\\/controller\\\/documentcontroller.php(125): OCA\\\\Documents\\\\File->__construct(741)\\n#2 [internal function]: OCA\\\\Documents\\\\Controller\\\\DocumentController->download('\\\/Sonstiges\\\/test...')\\n#3 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Documents\\\\Controller\\\\DocumentController), 'download')\\n#5 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Documents\\\\Controller\\\\DocumentController), 'download')\\n#6 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('DocumentControl...', 'download', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/apps\\\/documents...')\\n#10 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/index.php(39): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/apps\\\/documents\\\/lib\\\/file.php\",\"Line\":193}","level":3,"time":"2015-11-11T07:22:09+00:00"}
{"reqId":"cbfA9baCTsVDbo7vxUfW","remoteAddr":"79.210.166.21","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"\\\/files\\\/Sonstiges\\\/testfiles\\\/test-office.ods is application\\\/vnd.oasis.opendocument.spreadsheet and is not supported by Documents app\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/apps\\\/documents\\\/lib\\\/file.php(62): OCA\\\\Documents\\\\File->initViews()\\n#1 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/apps\\\/documents\\\/controller\\\/documentcontroller.php(125): OCA\\\\Documents\\\\File->__construct(741)\\n#2 [internal function]: OCA\\\\Documents\\\\Controller\\\\DocumentController->download('\\\/Sonstiges\\\/test...')\\n#3 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Documents\\\\Controller\\\\DocumentController), 'download')\\n#5 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Documents\\\\Controller\\\\DocumentController), 'download')\\n#6 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('DocumentControl...', 'download', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/apps\\\/documents...')\\n#10 \\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/index.php(39): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/clients\\\/client1\\\/web33\\\/team\\\/apps\\\/documents\\\/lib\\\/file.php\",\"Line\":193}","level":3,"time":"2015-11-11T07:22:09+00:00"}
{"reqId":"tVTeYSdMMtZDBo3ZqNEn","remoteAddr":"79.210.166.21","app":"PHP","message":"is_dir(): open_basedir restriction in effect. File(\/srv\/www\/hidden.de\/team) is not within the allowed path(s): (\/var\/www\/clients\/client1\/web33\/team:\/var\/www\/clients\/client1\/web33\/private:\/var\/www\/clients\/client1\/web33\/tmp:\/var\/www\/hidden.de\/team:\/srv\/www\/hidden.de\/team:\/usr\/share\/php5:\/usr\/share\/php:\/tmp:\/usr\/share\/phpmyadmin:\/etc\/phpmyadmin:\/var\/lib\/phpmyadmin:\/usr\/bin:\/srv\/www\/hidden.de\/team:\/dev\/urandom) at \/var\/www\/clients\/client1\/web33\/team\/3rdparty\/symfony\/process\/Symfony\/Component\/Process\/ExecutableFinder.php#59","level":3,"time":"2015-11-11T07:24:27+00:00"}
{"reqId":"tVTeYSdMMtZDBo3ZqNEn","remoteAddr":"79.210.166.21","app":"PHP","message":"is_dir(): open_basedir restriction in effect. File(\/srv\/www\/hidden.de\/team) is not within the allowed path(s): (\/var\/www\/clients\/client1\/web33\/team:\/var\/www\/clients\/client1\/web33\/private:\/var\/www\/clients\/client1\/web33\/tmp:\/var\/www\/hidden.de\/team:\/srv\/www\/hidden.de\/team:\/usr\/share\/php5:\/usr\/share\/php:\/tmp:\/usr\/share\/phpmyadmin:\/etc\/phpmyadmin:\/var\/lib\/phpmyadmin:\/usr\/bin:\/srv\/www\/hidden.de\/team:\/dev\/urandom) at \/var\/www\/clients\/client1\/web33\/team\/3rdparty\/symfony\/process\/Symfony\/Component\/Process\/ExecutableFinder.php#59","level":3,"time":"2015-11-11T07:24:27+00:00"}
{"reqId":"tVTeYSdMMtZDBo3ZqNEn","remoteAddr":"79.210.166.21","app":"PHP","message":"Array to string conversion at \/var\/www\/clients\/client1\/web33\/team\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-11-11T07:24:27+00:00"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://hidden 'unsafe-eval'").
	

(function(){var element = document.curre...

admin (Zeile 1)
4
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://hidden.de 'unsafe-eval'").
	

onsubmit attribute on DIV element

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://hidden 'unsafe-eval'").
	

(function(){var element = document.curre..

**Comment by MorrisJobke** [comment]
> The Problem is that he is trying to acess a folder that is not within my Webserver, correctly it would be /var/www/ but he is trying to reach /srv/www/. I think this might be a bug with a hardcoded variable

We don't hard code that path in ownCloud. Please check your nginx config for this value.

**Comment by Xenopathic** [comment]
This seems like a server configuration problem, please ask on the forums or IRC for help

**Comment by RealRancor** [comment]
@Xenopathic Might be related to https://github.com/owncloud/core/issues/17400#issuecomment-118635492

@team4music seems to just have configured the non-existent dir in open_basedir which is causing PHP to throw that message.

**Comment by Xenopathic** [comment]
@RealRancor Unlikely, this isn't about missing files, it's about a completely unexpected path, which indicates a server configuration problem

**Comment by hoorna** [comment]
This is strange. I have exactly the same warning as team4music. I have this warning for a long time now (I don't remember, but probably before owncloud version 8.0).

I edited open_basedir and add the missing subdirectory but this doesn't help.

This is the only line in the whole owncloud-code which generates this warning. Shouldn't it be a bug?

**Comment by hoorna** [comment]
I think I found the problem.

A search in the complete owncloud database points to the table oc_jobs because it gives to hits. Because of that, I have 3 questions:
1) The subdirectory in record 4 is the only one which points to the right directory. So can I safely delete the records 5, 6 and 7 manually?
If this is not possible:
2) The id's 6 and 7 have a wrong subdirectory: "\/volume1\" should be replaced by "\/var\/services\/web\". Is it safe to edit and change this manually?
3) Besides that, the subdirectory in id 5 is no longer existing. Can I delete this record safely?
