### ISSUE TITLE
WebDav : Connection timeout

### ISSUE THREAD

**Issue by notaduck** [owncloud/core#20507]
Hello. I have Owcnloud 8.1.4 running on Ubuntu 14.04 LTS with a fuly updated Apache, MysqlClient, Php stack.

But when I am trying to mount on another machine with [Webdav](https://doc.owncloud.org/server/8.0/user_manual/files/access_webdav.html) then i am getting this error message ?

```  
daniel@ubuntu-mysql:~$ mount ~/owncloud
/sbin/mount.davfs: connection timed out two times;
trying one last time
/sbin/mount.davfs: server temporarily unreachable;
mounting anyway
```

**Comment by rullzer** [comment]
We need a bit more information. Logs in particalar. Can I ask you to fill out the issue template ( https://github.com/owncloud/core/blob/master/issue_template.md )? Thanks in advance.

**Comment by RealRancor** [comment]
Connection timeout mostly means a connectivity issue between those systems. You could check that with cadaver like:

cadaver https://example.com/remote.php/webdav

**Comment by notaduck** [comment]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
I am trying to mount owncloud as WebDav on Ubuntu 14.04 LTS (the client work just fine on other systems)

### Actual behaviour
IT isn't getting mounted

### Server configuration
**Operating system**: Ubuntu 14.04 LTS

**Web server:** Server version: Apache/2.4.7 (Ubuntu)

**Database:** mysql  Ver 15.1 Distrib 5.5.46-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 

**ownCloud version:** : 8.1.4

**Updated from an older ownCloud or fresh install:** 8.1.3

**List of activated apps:**

```
daniel@owncloud:/var/www/owncloud$ sudo -u www-data php occ app:list
Enabled:
 - activity: 2.0.2
 - documents: 0.10.2
 - encryption: 1.0.0
 - files: 1.1.10
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.3
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - gallery: 0.6.0
 - ownnote: 1.05
 - provisioning_api: 0.2
 - templateeditor: 0.1
Disabled:
 - delete_confirmation
 - external
 - files_antivirus
 - files_locking
 - firstrunwizard
 - galleryplus
 - news
 - sharelinks
 - updater
 - user_external
 - user_ldap
 - user_webdavauth

```

**The content of config/config.php:**

```
daniel@owncloud:/var/www/owncloud/config$ sudo cat config.php 
<?php
$CONFIG = array (
  'instanceid' => 'ocnaoxamdmzh',
  'passwordsalt' => 'RCp0bY8I8I/kOtHmoHYNs45f2WFZsP',
  'secret' => 'acAp3h3F8WUMQFxKxChuSipNtWLXO5kCmyGO1A6sa9dfTO0W',
  'trusted_domains' => 
  array (
    0 => 'owncloud.techknight.eu',
  ),
  'datadirectory' => '/media/sdb1/ocdata',
  'overwrite.cli.url' => 'https://owncloud.techknight.eu',
  'dbtype' => 'mysql',
  'version' => '8.1.4.2',
  'dbname' => 'xxxxxxxxxxxxxx',
  'dbhost' => '10.0.2.4',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxxxxxxxxx',
  'dbpassword' => 'xxxxxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'log_type' => 'owncloud',
  'loglevel' => 0,
  'trusted_proxies' => 
  array (
    0 => '82.180.28.118',
  ),
  'forwarded_for_headers' => 
  array (
    0 => 'HTTP_X_FORWARDED',
    1 => 'HTTP_FORWARDED_FOR',
    2 => 'HTTPS_X_FORWARDED',
    3 => 'HTTPS_FORWARDED_FOR',
  ),
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'techknighteu',
  'mail_domain' => 'gmail.com',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpport' => '465',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpname' => 'techknighteu@gmail.com',
  'mail_smtppassword' => 'xxxxxxxxxxxxxxxxxx',
  'maintenance' => false,
  'theme' => '',
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/... : all my data is mounted on local storage (I do also have googlerive and dropbox synced)

**Are you using encryption:** yes


### Client configuration
**Browser:**

**Operating system:** Ubuntu 14.04 LTS headless

### Logs

#### Web server error log
```
There is no error regarding owncloud
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"lRPnSEx6l38sHKOqxRRG","remoteAddr":"10.0.2.14","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Doctrine\\\\DBAL\\\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(Doctrine\\\\DBAL\\\\DBALException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":62}","level":4,"time":"2015-11-13T20:49:36+00:00"}
{"reqId":"IGwFGA5E9AMhNi9h9Kmh","remoteAddr":"10.0.2.14","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Doctrine\\\\DBAL\\\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(Doctrine\\\\DBAL\\\\DBALException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":62}","level":4,"time":"2015-11-13T20:49:37+00:00"}
{"reqId":"7+SfqAKuCCFw2MF9dfBV","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T20:50:05+00:00"}
{"reqId":"ZnYym0vELgUC7MIrKWMp","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T20:50:09+00:00"}
{"reqId":"tUyl+UwyxGOSv62MnpTb","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T20:50:37+00:00"}
{"reqId":"iewnmlPzum+g6dhMIxCU","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T20:50:41+00:00"}
{"reqId":"jJWFsCp0LU9wm\/VGiHPB","remoteAddr":"10.0.2.14","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Doctrine\\\\DBAL\\\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(Doctrine\\\\DBAL\\\\DBALException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":62}","level":4,"time":"2015-11-13T20:50:49+00:00"}
{"reqId":"iFGHrAR6dQUV5D93m0+y","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T20:50:54+00:00"}
{"reqId":"l1Lhk\/ZH01Y5h9okHh8N","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T20:51:13+00:00"}
{"reqId":"amO8CzMQUeyqPX7u2BAE","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T20:51:26+00:00"}
{"reqId":"T2QvgOrm1pp57Is2Vc2G","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T20:51:45+00:00"}
{"reqId":"Cd5miiIjMtlfJ97Fpgtu","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T20:51:58+00:00"}
{"reqId":"sRhcKJkvvK65If\/JbyWt","remoteAddr":"10.0.2.14","app":"PHP","message":"PDOStatement::execute(): MySQL server has gone away at \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2015-11-13T22:10:50+00:00"}
{"reqId":"sRhcKJkvvK65If\/JbyWt","remoteAddr":"10.0.2.14","app":"PHP","message":"PDOStatement::execute(): Error reading result set's header at \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2015-11-13T22:10:50+00:00"}
{"reqId":"sRhcKJkvvK65If\/JbyWt","remoteAddr":"10.0.2.14","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT `id`, `mimetype` FROM `oc_mimetypes`':\\n\\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `m...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/statementwrapper.php(75): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db.php(147): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(154): OC_DB::executeAudited('SELECT `id`, `m...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(380): OC\\\\Files\\\\Cache\\\\Cache->loadMimetypes()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(267): OC\\\\Files\\\\Cache\\\\Scanner->scanChildren('', false, 3, Array, true)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(91): OC\\\\Files\\\\Cache\\\\Scanner->scan('', false)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1187): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php(148): OC\\\\Files\\\\View->getFileInfo('Dropbox')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/custompropertiesbackend.php(101): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Dropbox')\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropertyStorage\\\/Plugin.php(86): OC\\\\Connector\\\\Sabre\\\\CustomPropertiesBackend->propFind('Dropbox', Object(Sabre\\\\DAV\\\\PropFind))\\n#12 [internal function]: Sabre\\\\DAV\\\\PropertyStorage\\\\Plugin->propFind(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre\\\\Directory))\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1016): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(936): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre\\\\Directory))\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(327): Sabre\\\\DAV\\\\Server->getPropertiesForPath('', Array, 1)\\n#17 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropfind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#19 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#20 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#21 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#22 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#23 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":4,"time":"2015-11-13T22:10:55+00:00"}
{"reqId":"pOZbo\/LTmvhYGmAPo7XR","remoteAddr":"10.0.2.14","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Doctrine\\\\DBAL\\\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(Doctrine\\\\DBAL\\\\DBALException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":62}","level":4,"time":"2015-11-13T22:11:15+00:00"}
{"reqId":"KUAaf8Bnb0\/wZzkftg8Y","remoteAddr":"10.0.2.14","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Doctrine\\\\DBAL\\\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(Doctrine\\\\DBAL\\\\DBALException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":62}","level":4,"time":"2015-11-13T22:11:15+00:00"}
{"reqId":"LDV+D4O2UytchtGqjcbb","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T22:11:47+00:00"}
{"reqId":"nj3SBuVMNVQh7eK1XWvt","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T22:12:19+00:00"}
{"reqId":"tPMa6XhDzXozOw3NI3eJ","remoteAddr":"10.0.2.14","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused","level":4,"time":"2015-11-13T22:12:51+00:00"}
{"reqId":"RV8rRMh1omZdrhb3nPYX","remoteAddr":"10.0.2.14","app":"remote","message":"App not installed: ","level":4,"time":"2015-11-14T10:17:25+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav%20notaduck%20Supermand91"}
{"reqId":"Vq68l\/aPQxnlXCIXbdjf","remoteAddr":"10.0.2.14","app":"remote","message":"App not installed: ","level":4,"time":"2015-11-14T10:17:25+00:00","method":"GET","url":"\/owncloud\/remote.php\/core\/img\/breadcrumb.svg"}
{"reqId":"QMgilNqKkj\/fPcjgYrxN","remoteAddr":"10.0.2.14","app":"remote","message":"App not installed: ","level":4,"time":"2015-11-14T10:17:25+00:00","method":"GET","url":"\/owncloud\/remote.php\/cron.php"}
{"reqId":"Y13ZDj8jG+Jt9X4dxLTj","remoteAddr":"10.0.2.14","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-14T10:17:46+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav"}
{"reqId":"11MxHxg9V9lwvMi\/c4wU","remoteAddr":"10.0.2.14","app":"core","message":"Login failed: 'notaduck' (Remote IP: '10.0.2.14)","level":2,"time":"2015-11-14T10:17:52+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav"}
{"reqId":"11MxHxg9V9lwvMi\/c4wU","remoteAddr":"10.0.2.14","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 Username or password does not match\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":76}","level":0,"time":"2015-11-14T10:17:52+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav"}

```

**Comment by RealRancor** [comment]
It might be also useful if you post the fstab entry you're using for mounting. If other clients are working then this looks more like a configuration issue of the mount setup.

**Comment by notaduck** [comment]
```
daniel@ubuntu-mysql:~$ cat /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/dev/mapper/ubuntu--mysql--vg-root /               ext4    errors=remount-ro 0       1
# /boot was on /dev/sda1 during installation
UUID=fcdece44-854f-41f9-a4f2-82c93fbe4b9f /boot           ext2    defaults        0       2
/dev/mapper/ubuntu--mysql--vg-swap_1 none            swap    sw              0       0
/dev/fd0        /media/floppy0  auto    rw,user,noauto,exec,utf8 0       0
#owncloud webdav
owncloud.techknight.eu/owncloud/remote.php/webdav /home/daniel/owncloud          davfs user,rw,auto 0 0

```

**Comment by notaduck** [comment]
@RealRancor do you know the username and password for https://example.com/remote.php/webdav if i should test it?

**Comment by RealRancor** [comment]
You can test with:

https://demo.owncloud.org/remote.php/webdav

Username: test
Password: test

**Comment by notaduck** [comment]
i got this
```
/sbin/mount.davfs: mounting failed; the server does not support WebDAV

```

**Comment by rullzer** [comment]
Looking at your fstab and your log file I think you need to provide a username and password. This does not look like a bug but a configuration issue. Please consult the [mailing list](https://mailman.owncloud.org/mailman/listinfo/user) or [forums](https://forum.owncloud.org/).
