### ISSUE TITLE
Multiple PUT requests to new DAV backend results in locked file

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#20502]
Some DAV clients such as the famous OS X Finder one do perform 2 PUT requests when uploading new files. The new endpoint is however not able to handle this and this results in the following response:

```http
HTTP/1.1 423 Locked
Date: Fri, 13 Nov 2015 21:15:16 GMT
Server: Apache/2.4.16 (Unix) PHP/7.0.0RC5 OpenSSL/0.9.8zg
X-Powered-By: PHP/7.0.0RC5
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
Content-Length: 225
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"Lukas" is locked</s:message>
</d:error>
```

Note that this does only affect the new DAV backend from the DAV app. The older `/remote.php/webdav/` endpoint works perfectly fine. Can we have the old behaviour back? This will break clients.

Old endpoint that works:
```bash
#!/bin/bash
curl -i -s -k  -X 'PUT' -H 'User-Agent: WebDAVFS/3.0.0 (03008000) Darwin/15.0.0 (x86_64)' 'http://admin:admin@localhost/master/remote.php/webdav/Lukas'
curl -i -s -k  -X 'PUT' -H 'User-Agent: WebDAVFS/3.0.0 (03008000) Darwin/15.0.0 (x86_64)' 'http://admin:admin@localhost/master/remote.php/webdav/Lukas'
```

```
➜  Downloads  bash test.sh
HTTP/1.1 204 No Content
Date: Fri, 13 Nov 2015 21:18:52 GMT
Server: Apache/2.4.16 (Unix) PHP/7.0.0RC5 OpenSSL/0.9.8zg
X-Powered-By: PHP/7.0.0RC5
Set-Cookie: ocu0db7cmx3h=ega9vuufcklhqd7p891s3v5bi7; path=/master; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=crWyMJ6n1xThTMlwCL7%2BNhmZniDmcGModOwlepITF4BPrvW59uO2MxjU1Dxt0rIbV6y6M7mo5OgKPW%2BVZw6F8ilDKujKa7jd%2BM6YdxEU3bByTO9sir3D%2FM26bxMVF3Ho; path=/master; HttpOnly
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
OC-FileId: 00000435ocu0db7cmx3h
Content-Length: 0
ETag: "6c70bf1d0f01f063b912bc3342a7fe8b"
OC-ETag: "6c70bf1d0f01f063b912bc3342a7fe8b"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=UTF-8

HTTP/1.1 204 No Content
Date: Fri, 13 Nov 2015 21:18:52 GMT
Server: Apache/2.4.16 (Unix) PHP/7.0.0RC5 OpenSSL/0.9.8zg
X-Powered-By: PHP/7.0.0RC5
Set-Cookie: ocu0db7cmx3h=b6kgbgu2cld20g4emtc7lo0kg7; path=/master; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=PSFJ%2Br%2FcHMUMGNEnc0PXkNNcZiNPhMlR%2FNxUfJXF04Ki0VK%2BRu0DA2Yh5%2BDMl0RMo1rMVLOagxa%2FPUiSG%2BiHI1Lq5a37bViZmjR7U9q77frMRjBGiP3cIbXdVEz9LZl3; path=/master; HttpOnly
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
OC-FileId: 00000435ocu0db7cmx3h
Content-Length: 0
ETag: "6c70bf1d0f01f063b912bc3342a7fe8b"
OC-ETag: "6c70bf1d0f01f063b912bc3342a7fe8b"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=UTF-8
```

New endpoint that fails:
```bash
#!/bin/bash
curl -i -s -k  -X 'PUT' -H 'User-Agent: WebDAVFS/3.0.0 (03008000) Darwin/15.0.0 (x86_64)' 'http://admin:admin@localhost/master/remote.php/dav/files/admin/Lukas123'
curl -i -s -k  -X 'PUT' -H 'User-Agent: WebDAVFS/3.0.0 (03008000) Darwin/15.0.0 (x86_64)' 'http://admin:admin@localhost/master/remote.php/dav/files/admin/Lukas123'
```
```
➜  Downloads  bash test.sh
HTTP/1.1 201 Created
Date: Fri, 13 Nov 2015 21:19:41 GMT
Server: Apache/2.4.16 (Unix) PHP/7.0.0RC5 OpenSSL/0.9.8zg
X-Powered-By: PHP/7.0.0RC5
Set-Cookie: ocu0db7cmx3h=ceq1jr1h8pskfrblt0kpcahpv7; path=/master; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=qEnFHpBABPKY09GEqY9O9%2BDjDYWDaWpqAqZnzpFarv6vNRLFaG9NKlZ7sAXSrjAizhkqU2H3aL%2FvfkBD3h6%2BYuM2qv0udRwDvqznJAqw28cyYlXMFHzFRnXXut0WGDke; path=/master; HttpOnly
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
Content-Length: 0
ETag: "1feceab19f24f728587efd965320857f"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=UTF-8

HTTP/1.1 423 Locked
Date: Fri, 13 Nov 2015 21:19:41 GMT
Server: Apache/2.4.16 (Unix) PHP/7.0.0RC5 OpenSSL/0.9.8zg
X-Powered-By: PHP/7.0.0RC5
Set-Cookie: ocu0db7cmx3h=iisgssq5nmed2nksvrsvd71no4; path=/master; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=%2FwaMKuTI%2Fi0WczR79sEEcZ11XP3xBCcA%2FQraZFYoGQg6S5%2F5BzehVka83%2Bt8us1Txd0FamNuNCKoIxDPZDTwrZjEDE0vVrbIXIopVivVdV14t14%2BBs4MmhNIEqf3wAH5; path=/master; HttpOnly
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
Content-Length: 228
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"Lukas123" is locked</s:message>
</d:error>
```

@DeepDiver1975 @icewind1991 Have fun.

**Comment by kaplandani** [comment]
I think I got this too. all files fails to upload due to this error:
Exception: {"Message":"HTTP\/1.1 423 \"Docs\/EBooks\/Development\/web\/JavaTutor\/Java\/www.javasoft.com\/docs\/books\/tutorial\/information\/feature_article.html\" is locked","Exception":"OC\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/home\/mycld\/public_html\/oc\/lib\/private\/connector\/sabre\/directory.php(115): OC\\Connector\\Sabre\\File->put(Resource id #308)\n#1 \/home\/mycld\/public_html\/oc\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('feature_article...', Resource id #308)\n#2 \/home\/mycld\/public_html\/oc\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('Docs\/EBooks\/Dev...', Resource id #308, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/home\/mycld\/public_html\/oc\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/home\/mycld\/public_html\/oc\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#6 \/home\/mycld\/public_html\/oc\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/home\/mycld\/public_html\/oc\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#8 \/home\/mycld\/public_html\/oc\/remote.php(137): require_once('\/home\/mycld\/pub...')\n#9 {main}","File":"\/home\/mycld\/public_html\/oc\/lib\/private\/connector\/sabre\/file.php","Line":164}
