### ISSUE TITLE
CIFS-Mount broken (8.1.4 >> 8.2.1 RC2)

### ISSUE THREAD

**Issue by Pisoko** [owncloud/core#20554]
### Hey ownCloud,

I was testing the new RC2 Version of ownCloud 8.2.1 but i run into a problem with the smb/cifs-mount. The mount process is fine, but there were no subfolders (Look the pictures at the end)
With my current version (8.1.4) everthing is quite nice. (So there are a productiv and a testing-system)

### Server configuration
**Operating system**: Ubuntu 14.04.3

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** 8.2.1 RC2

Enabled:
  - activity: 2.1.3
  - direct_menu: 0.4
  - encryption: 1.1.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - ownbackup: 0.3.7
  - templateeditor: 0.1
  - updater: 0.6
  - user_ldap: 0.7.0

Disabled:
  - external
  - provisioning_api
  - proxy
  - user_external

**The content of config/config.php:**

```<?php
$CONFIG = array (
  'instanceid' => '****',
  'passwordsalt' => '****',
  'secret' => '****',
  'trusted_domains' =>
  array (
    0 => 'testcloud.intranet.ufz.de',
  ),
  'datadirectory' => '/mnt/owncloud/testcloud_data/',
  'overwrite.cli.url' => 'https://testcloud.intranet.ufz.de',
  'dbtype' => 'mysql',
  'version' => '8.2.1.1',
  'dbname' => 'test',
  'dbhost' => 'mysql1.intranet.ufz.de:3309',
  'dbuser' => '****',
  'dbpassword' => '****',
  'installed' => true,
  'dbtableprefix' => 'oc_',
  'theme' => 'ufz',
  'loglevel' => 2,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'enable_avatars' => false,
  'updatechecker' => true,
  'appstore.experimental.enabled' => true,
);
```

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP

**The two mount.json-files:**
![old and new json](https://cloud.githubusercontent.com/assets/11957656/11207577/46d22b5e-8d16-11e5-8acc-8d0f3d9ff6c7.JPG)

**The difference (8.1.4 <<>> 8.2.1 RC2):**
![difference_gruppen](https://cloud.githubusercontent.com/assets/11957656/11207769/6dc2b82c-8d17-11e5-8806-bc9d9c81d80e.JPG)
![difference_home](https://cloud.githubusercontent.com/assets/11957656/11207771/6f8c8bf6-8d17-11e5-9a1d-2601e816f836.JPG)

A local cifs-mount on the server is no problem.
I hope you can help me..

**Comment by Xenopathic** [comment]
Logs?

**Comment by Pisoko** [comment]
{"reqId":"8Eb04W3DmZPCElFQ3QJ0","remoteAddr":"141.65.129.232","app":"files_external","message":"Exception: {\"Exception\":\"Icewind\\\\SMB\\\\Exception\\\\InvalidHostException\",\"Message\":\"Connection unsuccessful\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Connection.php(43): Icewind\\\\SMB\\\\Connection->checkConnectionError('Connection to -...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Share.php(345): Icewind\\\\SMB\\\\Connection->read()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Share.php(120): Icewind\\\\SMB\\\\Share->execute('allinfo \\\"\\\"')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(102): Icewind\\\\SMB\\\\Share->stat('\\\/')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(136): OC\\\\Files\\\\Storage\\\\SMB->getFileInfo('')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(414): OC\\\\Files\\\\Storage\\\\SMB->stat('')\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(261): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(257): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#9 [internal function]: OCA\\\\Files_External\\\\Controller\\\\StoragesController->show(2)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Connection.php\",\"Line\":75}","level":3,"time":"2015-11-17T09:57:34+00:00"}

**Comment by Xenopathic** [comment]
ownCloud is unable to connect to your server. Please check for any network issues

**Comment by Pisoko** [comment]
A temporary mount from owncloud-server to NAS via cifs is no Porblem.
And as you can see on the picture.. the .txt-files are still available, but no folders.. so i don't think it's an network-issue.
But i will check this.

**Comment by Pisoko** [comment]
I can't find any network issues.

**Comment by Xenopathic** [comment]
In the ownCloud settings where you have your storages configured, try configuring a direct SMB storage (aka without session credentials) and make sure a green dot is appearing. You might want to use Wireshark to help debug this.

**Comment by Pisoko** [comment]
I configured a direct SMB storage with green dot, but the effect is the same. No folders.
![config](https://cloud.githubusercontent.com/assets/11957656/11294863/246dcb10-8f67-11e5-8158-fba6c79b7ef2.JPG)

![smb-view](https://cloud.githubusercontent.com/assets/11957656/11294864/268a94f0-8f67-11e5-8e5b-7d426212ef81.JPG)

**Comment by Xenopathic** [comment]
cc @icewind1991

**Comment by icewind1991** [comment]
Are there still connection errors showing up in the log?

**Comment by Pisoko** [comment]
Nope.. nothing

**Comment by seabird** [comment]
I seem to have the same problem, but it won't be network related as it both runs on the same server. mounting localhost. But it keeps from syncing everything nicely. Server 8.2.1 and sync client 2.0.2.11

**Comment by seabird** [comment]
And the green dot is there

**Comment by PVince81** [comment]
Is this still happening in 8.2.2 ?

Do you have special characters in the folder names ? Were these folders created with a Mac directly on the CIFS storage ??

**Comment by PVince81** [comment]
Closing due to lack of activity.
If this is still an issue with ownCloud v9.0.2RC1, feel free to reopen.
