### ISSUE TITLE
can't open Dropbox external storage (Storage not available)

### ISSUE THREAD

**Issue by kapcom01** [owncloud/core#20670]
### Steps to reproduce
1. I had a non working dropbox storage before upgrading to 8.2 and I never tried to fix it
2. Upgraded to 8.2.1
3. Admin > External Storage was empty even though in Files the storage still exists (cant delete it).
4. Added successfully the Dropbox storage again

### Expected behaviour
The newly added Dropbox storage should open and I should be able to delete the previous.

### Actual behaviour
Previous dropbox storage still not working and now when I go to Files > External Storage and click the newly added storage it says "Storage not available" and then opens the previous non-working unable-to-delete storage which is shown as empty.

### Server configuration
**Operating system**: Ubuntu 14.04.3 LTS

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** sqlite

**PHP version:** PHP 5.5.9-1ubuntu4.14

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** updated from the previous version

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - external: 1.2
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - news: 6.1.1
  - notifications: 0.1.0
  - tasks: 0.8.1
  - user_external: 0.4
Disabled:
  - direct_menu
  - encryption
  - mail
  - mozilla_sync
  - ocDashboard
  - provisioning_api
  - templateeditor
  - updater
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc5dbfa47aaf',
  'passwordsalt' => '----------------',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '8.2.1.4',
  'installed' => true,
  'loglevel' => 0,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'owncloud.kapcom.gr',
  ),
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_smtppassword' => '----------',
  'mail_domain' => 'kapcom.gr',
  'secret' => '--------------',
  'trashbin_retention_obligation' => 'auto',
);
```

**Are you using external storage, if yes which one:** SMB works fine, Dropbox has problems

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium 45.0.2454.101 Ubuntu 15.10 (64-bit)

**Operating system:** Ubuntu 15.10

#### Web server error log
```
no errors
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"tRnJHDkgpFhk1j\/bJnO6","remoteAddr":"192.168.1.19","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating \\\\OC\\\\Files\\\\Storage\\\\Dropbox storage failed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(258): OC\\\\Files\\\\Storage\\\\Dropbox->__construct(Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/globalstoragescontroller.php(109): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#3 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->create('itbm', 'dropbox', 'oauth1::oauth1', Array, Array, Array, Array, 100)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/dropbox.php\",\"Line\":59}","level":3,"time":"2015-11-22T17:58:43+00:00","method":"POST","url":"\/index.php\/apps\/files_external\/globalstorages"}
{"reqId":"+KR0UnpK8jfr88xffiGz","remoteAddr":"192.168.1.19","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating \\\\OC\\\\Files\\\\Storage\\\\Dropbox storage failed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(258): OC\\\\Files\\\\Storage\\\\Dropbox->__construct(Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(257): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#3 [internal function]: OCA\\\\Files_External\\\\Controller\\\\StoragesController->show(1)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/dropbox.php\",\"Line\":59}","level":3,"time":"2015-11-22T17:58:50+00:00","method":"GET","url":"\/index.php\/apps\/files_external\/globalstorages\/1"}
{"reqId":"Q5e5SUWnZ3EFnKVt7Ve8","remoteAddr":"192.168.1.19","app":"files_external","message":"Forbidden. This could mean a bad OAuth request, or a file or folder already existing at the target location.","level":3,"time":"2015-11-22T17:58:54+00:00","method":"PUT","url":"\/index.php\/apps\/files_external\/globalstorages\/1"}
{"reqId":"cdycO\/6nk6h8AP0VpBey","remoteAddr":"192.168.1.19","app":"files_external","message":"Forbidden. This could mean a bad OAuth request, or a file or folder already existing at the target location.","level":3,"time":"2015-11-22T17:59:13+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2Fitmb"}
{"reqId":"aM1MS+siG1raBziCsxVH","remoteAddr":"192.168.1.19","app":"files_external","message":"Forbidden. This could mean a bad OAuth request, or a file or folder already existing at the target location.","level":3,"time":"2015-11-22T17:59:50+00:00","method":"GET","url":"\/index.php\/apps\/files_external\/globalstorages\/1"}
{"reqId":"R2l7TDC9q00fXrztKjUx","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2015-11-22T18:00:02+00:00","method":"--","url":"--"}
{"reqId":"l1K8\/C7sV5a+iNzBD5uc","remoteAddr":"192.168.1.19","app":"files","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(223): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->checkAvailability()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(212): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->file_exists('')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(212): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1197): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(861): OC\\\\Files\\\\View->getFileInfo('\\\/itbm', true)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/list.php(34): OC\\\\Files\\\\Filesystem::getFileInfo('\\\/itbm')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 [internal function]: __lambda_func(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func('?lambda_1330', Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php\",\"Line\":63}","level":3,"time":"2015-11-22T18:00:22+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/list.php?dir=%2Fitbm&sort=name&sortdirection=asc"}
{"reqId":"Cx3TA4IU9eW4LSQkP7al","remoteAddr":"192.168.1.19","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(102): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->checkAvailability()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(99): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->is_dir('')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(99): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->is_dir('')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1023): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->is_dir('')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(327): OC\\\\Files\\\\View->basicOperation('is_dir', '\\\/\\\/itbm')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(89): OC\\\\Files\\\\View->is_dir('\\\/\\\/itbm')\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(53): OC_Files::get('\\\/', Array, false)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func('?lambda_1404', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php\",\"Line\":63}","level":3,"time":"2015-11-22T18:00:50+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/download.php?dir=%2F&files=itbm&downloadStartSecret=6iqqw28w71n0cnmi"}
{"reqId":"tCazEd4oO5OhuJlMmuVD","remoteAddr":"192.168.1.19","app":"no app in context","message":"CSRF check failed","level":0,"time":"2015-11-22T18:00:51+00:00","method":"GET","url":"\/index.php\/apps\/gallery\/config?extramediatypes=1"}
{"reqId":"4jRFaT3Eo8gaKMAii70R","remoteAddr":"192.168.1.19","app":"files_external","message":"Forbidden. This could mean a bad OAuth request, or a file or folder already existing at the target location.","level":3,"time":"2015-11-22T18:01:07+00:00","method":"GET","url":"\/index.php\/apps\/files_external\/globalstorages\/1"}
{"reqId":"dYZpRZqQiSsGE3DbSzDN","remoteAddr":"192.168.1.19","app":"files_external","message":"Forbidden. This could mean a bad OAuth request, or a file or folder already existing at the target location.","level":3,"time":"2015-11-22T18:01:22+00:00","method":"PUT","url":"\/index.php\/apps\/files_external\/globalstorages\/1"}
{"reqId":"aWbVDrq6cZf\/4Vr2TQCI","remoteAddr":"192.168.1.19","app":"files_external","message":"Forbidden. This could mean a bad OAuth request, or a file or folder already existing at the target location.","level":3,"time":"2015-11-22T18:01:32+00:00","method":"PUT","url":"\/index.php\/apps\/files_external\/globalstorages\/1"}
{"reqId":"Q8iA9zb61rTTOZEuCeRo","remoteAddr":"192.168.1.19","app":"files_external","message":"Forbidden. This could mean a bad OAuth request, or a file or folder already existing at the target location.","level":3,"time":"2015-11-22T18:01:35+00:00","method":"PUT","url":"\/index.php\/apps\/files_external\/globalstorages\/1"}
{"reqId":"MlCXie5QRXwfNwnPaLDb","remoteAddr":"192.168.1.19","app":"files_external","message":"Forbidden. This could mean a bad OAuth request, or a file or folder already existing at the target location.","level":3,"time":"2015-11-22T18:01:43+00:00","method":"PUT","url":"\/index.php\/apps\/files_external\/globalstorages\/1"}
{"reqId":"ZSmQIFdXin+3KQMhl9ev","remoteAddr":"192.168.1.19","app":"files_external","message":"Forbidden. This could mean a bad OAuth request, or a file or folder already existing at the target location.","level":3,"time":"2015-11-22T18:02:11+00:00","method":"GET","url":"\/index.php\/apps\/files_external\/globalstorages\/1"}```

**Comment by PVince81** [comment]
Can you post your "oc_storages" table ? Make sure to censor tokens if needed.

I suspect that you might have the same entry twice with a different format, or something.

**Comment by kapcom01** [comment]
select * from oc_storages;

```
1|home::user1|1|
2|home::user2|1|
3|local::/var/www/owncloud/data/|1|
4|home::user3|1|
5|home::user4|1|
6|dropbox::KEEFOX_CHECKED_FLAG_FALSE---censored---/|1|
7|dropbox::KEEFOX_CHECKED_FLAG_TRUE---censored---/|1|
8|dropbox::KEEFOX_CHECKED_FLAG_TRUE---censored---/|0|---censored---
9|home::user5|1|
10|shared::/Shared/Shared with user1|1|
11|shared::/user1|1|
12|failedstorage|1|
```

**Comment by kapcom01** [comment]
Should I delete 6,7,8? Maybe also 12?

**Comment by PVince81** [comment]
@kapcom01 try first deleting the config in the GUI, then delete 6, 7, 8 and 12.

**Comment by PVince81** [comment]
and then reconfigure Dropbox

**Comment by kapcom01** [comment]
thanks everything works fine now :+1:
