### ISSUE TITLE
[master] litmus on oracle broken?

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#20718]
```
{"reqId":"FvV3VMy5XghhJUH5eQ85","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT \\\"fileid\\\", \\\"storage\\\", \\\"path\\\", \\\"parent\\\", \\\"name\\\", \\\"mimetype\\\", \\\"mimepart\\\", \\\"size\\\", \\\"mtime\\\",\\n\\t\\t\\t\\t\\t   \\\"storage_mtime\\\", \\\"encrypted\\\", \\\"etag\\\", \\\"permissions\\\"\\n\\t\\t\\t\\tFROM \\\"oc_filecache\\\" WHERE \\\"storage\\\" = ? AND \\\"path_hash\\\" = ?' with params [\\\"1157\\\", \\\"45b963397aa40d4a0063e0d85e4fe7a1\\\"]:\\n\\nORA-01722: invalid number\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\OCI8\\\\OCI8Exception))\\n#1 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\OCI8\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\OCI8\\\\OCI8Exception), 'SELECT \\\"fileid\\\"...', Array)\\n#2 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/lib\\\/private\\\/db\\\/connection.php(182): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT \\\"fileid\\\"...', Array, Array, NULL)\\n#3 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(146): OC\\\\DB\\\\Connection->executeQuery('SELECT \\\"fileid\\\"...', Array)\\n#4 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/lib\\\/private\\\/files\\\/cache\\\/homecache.php(73): OC\\\\Files\\\\Cache\\\\Cache->get('files')\\n#5 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/lib\\\/private\\\/files\\\/view.php(1209): OC\\\\Files\\\\Cache\\\\HomeCache->get('files')\\n#6 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/serverfactory.php(125): OC\\\\Files\\\\View->getFileInfo('\\\/admin\\\/files')\\n#7 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ServerFactory->OCA\\\\DAV\\\\Connector\\\\Sabre\\\\{closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#9 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#10 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/remote.php(137): require_once('\\\/home\\\/deepdiver...')\\n#13 {main}\",\"File\":\"\\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/master-autotest\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractOracleDriver.php\",\"Line\":76}","level":4,"time":"433200"}
```

**Comment by PVince81** [comment]
@DeepDiver1975 is this still happening ? Move to 9.1 ?
Setting sev to medium for now.

**Comment by PVince81** [comment]
@DeepDiver1975 move to 9.2 ?

**Comment by PVince81** [comment]
@DeepDiver1975 medium -> backlog ?

**Comment by DeepDiver1975** [comment]
[litmus-0.13.tar.gz](https://github.com/owncloud/core/files/1426448/litmus-0.13.tar.gz)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
