### ISSUE TITLE
Class 'OC_Log' not found in /var/www/owncloud/lib/base.php on line 575

### ISSUE THREAD

**Issue by skibbipl** [owncloud/core#20759]
### Steps to reproduce
1. Upgraded OwnCloud instance from 8.1.4.2 to 8.2.1.4 from Debian packages.
2. OwnCloud stopped working due to some strange OC_Log class error.

### Expected behaviour
OwnCloud available and fully working.

### Actual behaviour
HTTP error 500 displayed on the web page.

### Server configuration
**Operating system**:
Debian stretch
Linux host 4.2.0-1-amd64 #1 SMP Debian 4.2.3-2 (2015-10-14) x86_64 GNU/Linux

**Web server:**
nginx 1.9.6

**Database:**
postgresql 9.4.5

**PHP version:**
5.6.15

**ownCloud version:** (see ownCloud admin page)
8.2.1.4

**Updated from an older ownCloud or fresh install:**
Upgraded

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - encryption: 1.1.0
  - external: 1.2
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - tasks: 0.8.1
  - templateeditor: 0.1
Disabled:
  - files_external
  - firstrunwizard
  - notifications
  - updater
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc0os0owhdhv",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "dbtype": "pgsql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "example.com",
        "loglevel": 2,
        "theme": "",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Mozilla Firefox Developer Version 44.0a2 (2015-11-25)

**Operating system:**
Windows 8.1

#### Web server error log
```
2015/11/26 15:37:01 [error] 22882#22882: *77386 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'OC_Log' not found in /var/www/owncloud/lib/bas
e.php on line 575" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: cloud.example.com, request: "GET /status.php HTTP/1.1",
upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.example.com"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"XYuSNOWhbMwGp1eHdrmC","remoteAddr":"","app":"core","message":"starting upgrade from 8.1.4.2 to 8.2.1.4","level":0,"time":"2015-11-26T14:06:38+00:00
","method":"--","url":"--"}
{"reqId":"XYuSNOWhbMwGp1eHdrmC","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotF
oundException\",\"Message\":\"Unable to generate a URL for the named route \\\"calendar_index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \
\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(314): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('calendar_ind
ex', Array, false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/cachingrouter.php(53): OC\\\\Route\\\\Router->generate('calendar_index', Arr
ay, false)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(65): OC\\\\Route\\\\CachingRouter->generate('calendar_index', Array)\\n#3 \\
\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/helper.php(66): OC\\\\URLGenerator->linkToRoute('calendar_index', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib
\\\/public\\\/util.php(301): OC_Helper::linkToRoute('calendar_index', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/app.php(25): O
CP\\\\Util::linkToRoute('calendar_index')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(160): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7
 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(141): OC_App::requireAppFile('calendar')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.ph
p(1171): OC_App::loadApp('calendar', false)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(219): OC_App::updateApp('calendar')\\n#10 \\\/
var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(249): OC_Installer::updateApp(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.
php(509): OC_Installer::updateAppByOCSId('168707')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(323): OC\\\\Updater->upgradeAppStoreApps
(Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.1.4', '8.1.4.2')\\n#14 \\\/var\\\/www\\\/ownclo
ud\\\/core\\\/command\\\/upgrade.php(213): OC\\\\Updater->upgrade()\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Componen
t\\\/Console\\\/Command\\\/Command.php(253): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(
Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Co
nsole\\\/Application.php(874): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Obje
ct(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#17 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\
/Console\\\/Application.php(195): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Co
mponent\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#18 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\
\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(126): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Comp
onent\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/priva
te\\\/console\\\/application.php(97): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#20 \\\/var\\\/www\\\/owncloud\\\/console.php(69): OC
\\\\Console\\\\Application->run()\\n#21 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#22 {main}\",\"File\":\"\\\/var\
\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":3,"time":"2
015-11-26T14:07:38+00:00","method":"--","url":"--"}
{"reqId":"XYuSNOWhbMwGp1eHdrmC","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotF
oundException\",\"Message\":\"Unable to generate a URL for the named route \\\"contacts_index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \
\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(314): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('contacts_ind
ex', Array, false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/cachingrouter.php(53): OC\\\\Route\\\\Router->generate('contacts_index', Arr
ay, false)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(65): OC\\\\Route\\\\CachingRouter->generate('contacts_index', Array)\\n#3 \\
\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/helper.php(66): OC\\\\URLGenerator->linkToRoute('contacts_index', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib
\\\/public\\\/util.php(301): OC_Helper::linkToRoute('contacts_index', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/app.php(18): O
CP\\\\Util::linkToRoute('contacts_index')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(160): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7
 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(141): OC_App::requireAppFile('contacts')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.ph
p(1171): OC_App::loadApp('contacts', false)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(219): OC_App::updateApp('contacts')\\n#10 \\\/
var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(249): OC_Installer::updateApp(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.
php(509): OC_Installer::updateAppByOCSId('168708')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(323): OC\\\\Updater->upgradeAppStoreApps
(Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.1.4', '8.1.4.2')\\n#14 \\\/var\\\/www\\\/ownclo
ud\\\/core\\\/command\\\/upgrade.php(213): OC\\\\Updater->upgrade()\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Componen
t\\\/Console\\\/Command\\\/Command.php(253): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(
Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Co
nsole\\\/Application.php(874): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Obje
ct(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#17 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\
/Console\\\/Application.php(195): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Co
mponent\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#18 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\
\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(126): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Comp
onent\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/priva
te\\\/console\\\/application.php(97): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#20 \\\/var\\\/www\\\/owncloud\\\/console.php(69): OC
\\\\Console\\\\Application->run()\\n#21 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#22 {main}\",\"File\":\"\\\/var\
\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":3,"time":"2
015-11-26T14:07:41+00:00","method":"--","url":"--"}
{"reqId":"XYuSNOWhbMwGp1eHdrmC","remoteAddr":"","app":"tasks","message":"Can not enable the Tasks app because the Calendar App is disabled.","level":3,"time"
:"2015-11-26T14:07:41+00:00","method":"--","url":"--"}
{"reqId":"Zu5e+u14wT3m\/EEi2isn","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.1.4 to 8.2.1.4","level":0,"time":"2015-11-26T14:22:21+00:0
0","method":"--","url":"--"}
```

**Comment by DeepDiver1975** [comment]
@skibbipl looks like the update did no properly replace all files

https://github.com/owncloud/core/blob/v8.2.1/lib/base.php#L575 does not talk about OC_Log

**Comment by skibbipl** [comment]
Any ideas how to fix it? How can I verify that my owncloud files are correct?

**Comment by DeepDiver1975** [comment]
> Upgraded OwnCloud instance from 8.1.4.2 to 8.2.1.4 from Debian packages.

what is the source of your debian packages?

**Comment by skibbipl** [comment]
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/

**Comment by DeepDiver1975** [comment]
@jnweiger

**Comment by skibbipl** [comment]
It seems php5-fpm had some cached data and I had to restart it to make OwnCloud working again.
