### ISSUE TITLE
OC broken on master: Autoload not allowed

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20819]
On latest master: 188b72a9f33ae2c330a73a103d4e96348f1b3ef0

### Steps
1. Setup OC from git master (no third party apps except the owncloud/apps repo)
2. Open the web UI

### Expected result
OC works

### Actual result
OC broken with internal server error:
```
{"reqId":"MjIxektg09OKmG9e6O4E","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/app.php\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/autoloader.php(178): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Files\\\\\\\\App')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/app.php(49): spl_autoload_call('OCA\\\\\\\\Files\\\\\\\\App')\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/app.php(159): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/app.php(140): OC_App::requireAppFile('files')\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('files')\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(845): OC_App::loadApps(Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":154}","level":3,"time":"2015-11-29T09:42:40+00:00","method":"GET","url":"\/owncloud\/"}
```

### Env:

- openSUSE 13.2 x86_64
- php5-5.6.1-36.1.x86_64

@DeepDiver1975 @icewind1991

**Comment by PVince81** [comment]
Broken by 50474c6041adc2be420c48c4acb6fd42b646215a from PR https://github.com/owncloud/core/pull/20792

**Comment by Xenopathic** [comment]
Ah, that would be because `stream_resolve_include_path()` resolves all symlinks, which is required for comparison of autoloaded paths. So we need to `stream_resolve_include_path()` *every* autoload path, regardless of if it's relative or absolute.
