### ISSUE TITLE
Sync errors after upgrading to 8.2.1 "Der Dateiname enth\\u00e4lt minde stens ein ung\\u00fcltiges Zeichen\"

### ISSUE THREAD

**Issue by a-schild** [owncloud/core#20824]
Server Debian 8, with Apache 64Bit

After upgrading owncloud from 8.1.4 to 8.2.1 we receive this error on some existing folders on the server:

```
{"reqId":"4zsiMTdJpjD4Z2eqRMtb","remoteAddr":"2001:470:26:421:1dd1:571b:1a3f:3327","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 Der Dateiname enth\\u00e4lt minde
stens ein ung\\u00fcltiges Zeichen\",\"Exception\":\"OC\\\\Connector\\\\Sabre\\\\Exception\\\\InvalidPath\",\"Code\":0,\"Trace\":\"
#0 \\\/home\\\/data\\\/cloud\\\/htdocs\\\/lib\\\/priv
ate\\\/connector\\\/sabre\\\/custompropertiesbackend.php(100): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Excel\\\/L\\\\xC3\\\\xB6hne 20...')\\n
#1 \\\/home\\\/data\\\/clou
d\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropertyStorage\\\/Plugin.php(86): OC\\\\Connector\\\\Sabre\\\\CustomPropertiesBackend->propFind('Excel\\\/L\\\\xC3\\\\xB6hne 2
0...', Object(Sabre\\\\DAV\\\\PropFind))\\n
#2 [internal function]: Sabre\\\\DAV\\\\PropertyStorage\\\\Plugin->propFind(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre
\\\\File))\\n
#3 \\\/home\\\/data\\\/cloud\\\/htdocs\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#4 \\\/home\\\/data\\\/clou
d\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1016): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n
#5 \\\/home\\\/data\\\/cloud\\\/htdocs\\\/3rdparty\
\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(936): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre\\\\File))\\n
#6 \\\/home\
\\/data\\\/cloud\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(327): Sabre\\\\DAV\\\\Server->getPropertiesForPath('Excel\\\/L\\\\xC3\\\\xB6hne 20...', Array, 1)
\\n
#7 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropfind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#8 \\\/home\\\/data\\\/cloud\\\/htdocs\\\/3rd
party\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#9 \\\/home\\\/data\\\/cloud\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/S
erver.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n
#10 \\\/home\\\/data\\\/cloud\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): S
abre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#11 \\\/home\\\/data\\\/cloud\\\/htdocs\\\/apps\\\/files\\\/appinfo\\\/remote
.php(55): Sabre\\\\DAV\\\\Server->exec()\\n
#12 \\\/home\\\/data\\\/cloud\\\/htdocs\\\/remote.php(137): require_once('\\\/home\\\/data\\\/clou...')\\n
#13 {main}\",\"File\":\"\\\/home\\\
/data\\\/cloud\\\/htdocs\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":112}","level":4,"time":"2015-11-30T08:57:58+00:00","method":"PROPFIND","url":"\/remote.php
\/webdav\/Excel\/L%C3%B6hne%202014\/Wanda%20Roma"}
```

It does not matter if we have a OS-X or Windows client (All running 2.0.2)

On client side the client shows this:

![owncloud_2015-11-30_10-05-47](https://cloud.githubusercontent.com/assets/1441009/11467683/07753cba-974a-11e5-8d8b-3e2e7db9a03d.png)

**Comment by PVince81** [comment]
Characters with umlauts should be allowed.
I just tested on my 8.2.1 server (openSUSE 13.2 x86_64) and syncing works fine.

Did anything else change in your environment ? Is the locale still properly set to UTF-8 ?

**Comment by a-schild** [comment]
We did only upgrade the owncloud instance, but did not modify server parameters.
Also I don't see which character is invalid, which one it is struggling with.

In the folder "Löhne 2014" there are other subfolders (Beside the "Wanda Roma") which it apparently does not fail.

Also this completely stops sync of anything on that share

**Comment by PVince81** [comment]
Let's try the following:
- create a new folder called "Töst" and see whether it syncs
- then create a folder "Löhne" but by copy-pasting the name from the file manager instead of typing it, in case it's using a different encoding (on Mac the UTF-8 encoding is sometimes slightly different)

**Comment by a-schild** [comment]
Currently the OS-X client is the "source" of the files.
The Windows client I did add, is just for testing, to retrieve a copy of the files.

It seems that it's a serverside problem, since the windows client can't retrieve a copy of the data.
Should I create this testfolder on serverside?

**Comment by PVince81** [comment]
Yes, try creating the folder in the web UI on a Windows machine.

Maybe the Mac uploaded the file with its own weird encoding and the file name is causing trouble somehow. In any way it might be a bug, but it would be good to find out where it comes from to have better reproduction steps.

**Comment by a-schild** [comment]
I did create a new folder with ö in it and it does sync.
I did then also use copy&paste on the webinterface to create a new folder with the Löhne 2014-2, which does also sync.

I think it's not the "Löhne 2014" causing problems, but rather the content of the "Wanda Roma" folder.

Here what the owncloud windows client shows me, when I try to expand the "Wanda Roma" folder:

![owncloud_2015-11-30_12-09-23](https://cloud.githubusercontent.com/assets/1441009/11470106/88ad58ba-975b-11e5-897d-f802e962af6f.png)

The total content of that folder are 1.2MB in size, and are 22 excel and word files.

![mc root sv20 __home_data_cloud_htdocs_data_marcelroth_files_excel_la hne 2014_w_2015-11-30_12-13-54](https://cloud.githubusercontent.com/assets/1441009/11470166/f5b4cdda-975b-11e5-8f61-32feb5431ec6.png)

**Comment by a-schild** [comment]
Looks like some of the files have 0x08 characters in their names....
Renaming in the webinterface does not work, it tells me that the file has been deleted (but that's not true)

I'm I allowed to rename the file in the server console?

![owncloud_2015-11-30_12-37-16](https://cloud.githubusercontent.com/assets/1441009/11470615/8f3c0c5e-975f-11e5-85cc-ff8002a2a76e.png)

**Comment by PVince81** [comment]
Try renaming the file in oc_filecache first, and then on disk in the data folder.
Ideal would be to do it in maintenance mode to avoid access to this file while you are renaming it, but it might work without.

Note: since 8.2 ownCloud doesn't detect FS changes from the data directory for performance reasons, so renaming it on-disk isn't enough.

**Comment by a-schild** [comment]
Ok,

got the problem solved by renaming the files (there have been about 20 of them in other folders too) and then issuing `sudo -u www-data php occ files:scan username`

Won't it bee a good idea to have a way to detect such "invalid" filenames on serverside?

**Comment by PVince81** [comment]
Yes. I think it would be good if the server could just skip the file in the listing and not break syncing.

I guess syncing doesn't work for ANY file in that folder, even valid ones ?

**Comment by a-schild** [comment]
Yep, the client stops in the detect phase and does not sync anything of that share at all.

**Comment by PVince81** [comment]
Ok, so the goal to fix this bug is as follows:
- PROPFIND should not stop on invalid file names but still return them in the response (ex: file name with ASCII 0x08 in it)

**Comment by a-schild** [comment]
Yep, and also log the invalid filenames somewhere so it's simpler to track down invalid names on server side

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
