### ISSUE TITLE
Cannot mount dropbox on master

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20835]
### Steps

1. Mount Dropbox storage as system-wide mount
```
{"reqId":"CCjK3fsHqvlp1ohDlm9+","remoteAddr":"127.0.0.1","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating \\\\OC\\\\Files\\\\Storage\\\\Dropbox storage failed\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(259): OC\\\\Files\\\\Storage\\\\Dropbox->__construct(Array)\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/globalstoragescontroller.php(174): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n
#3 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update(1, 'Dropbox', 'dropbox', 'oauth1::oauth1', Array, Array, Array, Array, 100)\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n
#8 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n
#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n
#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(858): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n
#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n
#12 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/dropbox.php\",\"Line\":59}","level":3,"time":"2015-11-30T13:31:54+00:00","method":"PUT","url":"\/owncloud\/index.php\/apps\/files_external\/globalstorages\/1"}
```

### Version
Observed on master (a94819f4a47ba98b185c9c75eab43d8cb933ed5c)

@icewind1991 @Xenopathic 

Bisect will follow.

**Comment by PVince81** [comment]
It only appears when setting up Dropbox directly on master, not upgrading.

**Comment by PVince81** [comment]
Weird, it works now... I got confused because it first shows a red square and then a few seconds later it transforms to a green circle. I was too fast.

Sorry for the noise.

**Comment by PVince81** [comment]
And no... when coming back from the bisect I mistakenly tested on another branch.

Got it happening on master now.

**Comment by PVince81** [comment]
One of these:
# bad: [28876bf46363116218c48021ddf556c53d5256f5] Display applicable global storages in personal mount list
git bisect bad 28876bf46363116218c48021ddf556c53d5256f5
# bad: [a1704c86233312c4574bc368b78b73fb6b605c2b] Render external storages list in JS
git bisect bad a1704c86233312c4574bc368b78b73fb6b605c2b
# first bad commit: [a1704c86233312c4574bc368b78b73fb6b605c2b] Render external storages list in JS

@Xenopathic @icewind1991

**Comment by Xenopathic** [comment]
It's probably a variable type issue. I'll investigate (end of term coming up woop!)

**Comment by PVince81** [comment]
@Xenopathic any update ?

**Comment by Xenopathic** [comment]
`configured` isn't being set to `true` for some reason, on the JS side...

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/issues/21517
