### ISSUE TITLE
Can't download a federated shared file with https self-signed certificates in both servers

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#20840]
To be a bit clearer, server A is located in port 32783 and server B in port 21143

### Steps to reproduce
1. Generate and share self-signed certificates in *both* servers
    ```
openssl genrsa -out /etc/apache2/ssl/server.key 2048
openssl req -x509 -new -days 365 -key /etc/apache2/ssl/server.key -out /etc/apache2/ssl/server.crt -subj "/C=US/ST=US/L=Lex/O=ownCloud/OU=qa/CN=10.0.2.6"
service apache2 restart

# get certificate for the remote server
openssl s_client -showcerts -connect 10.0.2.6:32783 </dev/null 2>/dev/null | openssl x509 -outform PEM > /usr/share/ca-certificates/10.0.2.6_32783.crt
echo '10.0.2.6_32783.crt' >> /etc/ca-certificates.conf
update-ca-certificates --fresh

# get certificate for the local server
openssl s_client -showcerts -connect 10.0.2.6:21143 </dev/null 2>/dev/null | openssl x509 -outform PEM > /usr/share/ca-certificates/10.0.2.6_21143.crt
echo '10.0.2.6_21143.crt' >> /etc/ca-certificates.conf
update-ca-certificates --fresh
    ```

2. Verify that you can connect with curl through https from both servers and the certificate is properly recognized
    ```
curl -u admin:11111 -v https://10.0.2.6:21143/status.php
* Hostname was NOT found in DNS cache
*   Trying 10.0.2.6...
* Connected to 10.0.2.6 (10.0.2.6) port 21143 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: ********************************
* 	 start date: 2015-11-30 12:31:16 GMT
* 	 expire date: 2016-11-29 12:31:16 GMT
* 	 common name: 10.0.2.6 (matched)
* 	 issuer: **********************************
* 	 SSL certificate verify ok.
............
    ```
3. In server A (server port 32789) upload a file and share it with server B (port 21143)
4. Try to download the shared file from the user account in server B

### Expected behaviour
The file is downloaded

### Actual behaviour
Can't download the file

From server B:
```
curl -u admin:11111 -v https://10.0.2.6:21143/remote.php/webdav/qwerty1.txt
* Hostname was NOT found in DNS cache
*   Trying 10.0.2.6...
* Connected to 10.0.2.6 (10.0.2.6) port 21143 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: ***************************************
* 	 start date: 2015-11-30 12:31:16 GMT
* 	 expire date: 2016-11-29 12:31:16 GMT
* 	 common name: 10.0.2.6 (matched)
* 	 issuer: *****************************************
* 	 SSL certificate verify ok.
* Server auth using Basic with user 'admin'
> GET /remote.php/webdav/qwerty1.txt HTTP/1.1
> Authorization: Basic YWRtaW46MTExMTE=
> User-Agent: curl/7.35.0
> Host: 10.0.2.6:21143
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Date: Mon, 30 Nov 2015 14:07:11 GMT
* Server Apache/2.4.7 (Ubuntu) is not blacklisted
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.13
< Set-Cookie: oc2risxep4j2=nojqlfjp75pjfu4bomlhlm9r35; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=ACpM5UnCvvgfbirrtMmyEnqStDL9gXc1hTFurBe4C8zdpO0KR1qv9vTfKxCZI1Uy8gsIU28DRZUpwOXxnUVDh6Yf3%2BP%2Ba5xOVwa5dJyoEXB72qCo6lwkHxIpI8dtovyj; path=/; secure; httponly
< Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< X-Robots-Tag: none
< Set-Cookie: oc2risxep4j2=if8h8ohbd79oa5h709lusl1j66; path=/; secure; HttpOnly
< Content-Length: 934
< Connection: close
< Content-Type: application/xml; charset=utf-8
< 
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>GuzzleHttp\Exception\RequestException</s:exception>
  <s:message>Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
[file] /opt/owncloud/3rdparty/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 406
[message] fopen(): Failed to enable crypto
[file] /opt/owncloud/3rdparty/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 406
[message] fopen(https://10.0.2.6:32789/public.php/webdav/): failed to open stream: operation failed
[file] /opt/owncloud/3rdparty/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 406
[message] Undefined variable: http_response_header
[file] /opt/owncloud/3rdparty/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 407</s:message>
</d:error>
* Closing connection 0
* SSLv3, TLS alert, Client hello (1):
```

The file can be downloaded fine using the account in server A. Again, from server B:
```
curl -u admin:11111 -v https://10.0.2.6:32789/remote.php/webdav/qwerty1.txt -o /tmp/ff.txt
* Hostname was NOT found in DNS cache
*   Trying 10.0.2.6...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 10.0.2.6 (10.0.2.6) port 32789 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: ********************************
* 	 start date: 2015-11-30 12:31:07 GMT
* 	 expire date: 2016-11-29 12:31:07 GMT
* 	 common name: 10.0.2.6 (matched)
* 	 issuer: ***********************************
* 	 SSL certificate verify ok.
* Server auth using Basic with user 'admin'
> GET /remote.php/webdav/qwerty1.txt HTTP/1.1
> Authorization: Basic YWRtaW46MTExMTE=
> User-Agent: curl/7.35.0
> Host: 10.0.2.6:32789
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 30 Nov 2015 14:11:07 GMT
* Server Apache/2.4.7 (Ubuntu) is not blacklisted
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.13
< Set-Cookie: oc5ea63ej8g3=prv2ekc2o1onlcrh3t09peitm1; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=mTLxMCApBh0Tks9twtLYi4t7CuUuoWFVi92a1D%2BHqYtymEP%2BVEBrZTGaiyuXnQCzb%2FCtyByOKW9ZnyqUvpQTK6z1jdZTbKg89KOd3IFm9Ai0K0sErfQWhltrBCCZl3Q5; path=/; secure; httponly
< Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< X-Robots-Tag: none
< Set-Cookie: oc5ea63ej8g3=is7qsukutigtmk76qkonugbhf5; path=/; secure; HttpOnly
< Last-Modified: Mon, 30 Nov 2015 12:29:20 GMT
< ETag: "c757b1dbc8187e93cc1d55a647488401"
< Content-Length: 102400
< Content-Disposition: attachment
< OC-ETag: "c757b1dbc8187e93cc1d55a647488401"
< Vary: Accept-Encoding
< Content-Type: text/plain;charset=UTF-8
< 
{ [data not shown]
100  100k  100  100k    0     0   183k      0 --:--:-- --:--:-- --:--:--  183k
* Connection #0 to host 10.0.2.6 left intact
```

Propfind calls are working:
```
curl -X PROPFIND -u admin:11111 -v https://10.0.2.6:21143/remote.php/webdav/qwerty1.txt 
* Hostname was NOT found in DNS cache
*   Trying 10.0.2.6...
* Connected to 10.0.2.6 (10.0.2.6) port 21143 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: **************************************
* 	 start date: 2015-11-30 12:31:16 GMT
* 	 expire date: 2016-11-29 12:31:16 GMT
* 	 common name: 10.0.2.6 (matched)
* 	 issuer: ******************************************
* 	 SSL certificate verify ok.
* Server auth using Basic with user 'admin'
> PROPFIND /remote.php/webdav/qwerty1.txt HTTP/1.1
> Authorization: Basic YWRtaW46MTExMTE=
> User-Agent: curl/7.35.0
> Host: 10.0.2.6:21143
> Accept: */*
> 
< HTTP/1.1 207 Multi-Status
< Date: Mon, 30 Nov 2015 14:13:24 GMT
* Server Apache/2.4.7 (Ubuntu) is not blacklisted
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.13
< Set-Cookie: oc2risxep4j2=s74jlu63ve41226u3hk4huid83; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=UJ484zgdIPzsb4adb4DaGpKzkBKjyKuioDEE5T6o2mQNk6lUV5Ehdbe5L9dLEBpQ%2B6gIbbQF7q0l4oL1Rm0O18UKm6E%2B1wuiyq3FIEgJnmyx0dDepjfN%2BMHikGYLUO5F; path=/; secure; httponly
< Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< X-Robots-Tag: none
< Set-Cookie: oc2risxep4j2=datht5lcccrjg3ptma1ki1paa6; path=/; secure; HttpOnly
< Vary: Brief,Prefer
< DAV: 1, 3, extended-mkcol
< Content-Length: 539
< Content-Type: application/xml; charset=utf-8
< 
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/webdav/qwerty1.txt</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 30 Nov 2015 12:29:20 GMT</d:getlastmodified><d:getcontentlength>102400</d:getcontentlength><d:resourcetype/><d:getetag>"c757b1dbc8187e93cc1d55a647488401"</d:getetag><d:getcontenttype>text/plain</d:getcontenttype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
* Connection #0 to host 10.0.2.6 left intact
```

### Server configuration
**Operating system**: ubuntu 14.04 on both servers

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** both servers 8.2.0 and both server 8.2.1

#### ownCloud log (data/owncloud.log)
Server A logs
```
{"reqId":"b+pBtXKsyVChS4uMTVn0","remoteAddr":"::1","app":"PHP","message":"Undefined offset: 0 at \/opt\/owncloud\/lib\/private\/setup\/mysql.php#45","level":3,"time":"2015-11-30T14:22:45+00:00"}
{"reqId":"b+pBtXKsyVChS4uMTVn0","remoteAddr":"::1","app":"PHP","message":"fopen(\/opt\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/opt\/owncloud\/lib\/private\/config.php#188","level":3,"time":"2015-11-30T14:22:48+00:00"}
```

Server B logs:
```
{"reqId":"vmI21FvQyVruGv7OoTdi","remoteAddr":"::1","app":"PHP","message":"Undefined offset: 0 at \/opt\/owncloud\/lib\/private\/setup\/mysql.php#45","level":3,"time":"2015-11-30T14:22:45+00:00"}
{"reqId":"vmI21FvQyVruGv7OoTdi","remoteAddr":"::1","app":"PHP","message":"fopen(\/opt\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/opt\/owncloud\/lib\/private\/config.php#188","level":3,"time":"2015-11-30T14:22:48+00:00"}
{"reqId":"kLCTg\/k48yq0Ayi1kybE","remoteAddr":"10.0.2.7","app":"webdav","message":"Exception: {\"Message\":\"Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:\\nerror:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed\\n[file] \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/StreamHandler.php\\n[line] 406\\n[message] fopen(): Failed to enable crypto\\n[file] \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/StreamHandler.php\\n[line] 406\\n[message] fopen(https:\\\/\\\/10.0.2.6:32795\\\/public.php\\\/webdav\\\/): failed to open stream: operation failed\\n[file] \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/StreamHandler.php\\n[line] 406\\n[message] Undefined variable: http_response_header\\n[file] \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/StreamHandler.php\\n[line] 407\",\"Exception\":\"GuzzleHttp\\\\Exception\\\\RequestException\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(104): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\RingException))\\n#1 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/opt\\\/owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(24): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(135): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(232): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(192): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/http\\\/client\\\/client.php(123): GuzzleHttp\\\\Client->get('https:\\\/\\\/10.0.2....', Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(347): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/10.0.2....', Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(286): OC\\\\Files\\\\Storage\\\\DAV->fopen('', 'rb')\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(302): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('', 'rb')\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(286): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->fopen('', 'rb')\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1021): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('', 'rb')\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(871): OC\\\\Files\\\\View->basicOperation('fopen', 'qwerty1.txt', Array, 'rb')\\n#15 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(266): OC\\\\Files\\\\View->fopen('qwerty1.txt', 'rb')\\n#16 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(82): OC\\\\Connector\\\\Sabre\\\\File->get()\\n#17 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#19 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#20 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#21 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#22 \\\/opt\\\/owncloud\\\/remote.php(137): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#23 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":51}","level":4,"time":"2015-11-30T14:23:37+00:00"}
```

**Comment by LukasReschke** [comment]
ownCloud uses the bundle from https://github.com/owncloud/core/blob/08248f66ba28db3f6e3328fc489fa52432c73544/resources/config/ca-bundle.crt
