### ISSUE TITLE
Smashbox test test_sharePropagationInsideGroups.py fails on master

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20892]
See https://ci.owncloud.org/job/smashbox-on-docker-ci/DOCKER_IMAGE=ubuntu_oc_lamp-git,TEST_NAME=test_sharePropagationInsideGroups,mirallBranch=v1.8.3,slave=SMASH/

and 
```
2015-12-02 11:51:32,724 - CRITICAL - recipient2 - Exception occured: OCS error: 403 
 Traceback (most recent call last):
  File "python/smashbox/multiprocessing_engine.py", line 164, in worker_wrap
    f(step)
  File "/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py", line 286, in recipient2
    share2_data = clients[0].share_file_with_group('/test/sub', group4, perms=31)
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 1178, in share_file_with_group
    self.__check_ocs_status(tree)
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 1395, in __check_ocs_status
    raise OCSResponseError(r)
OCSResponseError: OCS error: 403

2015-12-02 11:51:33,612 - CRITICAL - recipient4 - Exception occured: HTTP error: 404 
 Traceback (most recent call last):
  File "python/smashbox/multiprocessing_engine.py", line 164, in worker_wrap
    f(step)
  File "/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py", line 429, in recipient4
    sub_etags = get_client_etags(clients, '/sub')
  File "/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py", line 83, in get_client_etags
    new_etags.append(client.file_info(path).get_etag())
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 254, in file_info
    res = self.__make_dav_request('PROPFIND', path)
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 1451, in __make_dav_request
    raise HTTPResponseError(res)
HTTPResponseError: HTTP error: 404

2015-12-02 11:51:35,351 - ERROR - owner - recipient2 uploads to /test/test3.txt etag for / previous ["565ecd36bb035"] new ["565ecd36bb035"] 'etag for / previous [%s] new [%s]' % (root_etag2, root_etag3)) failed in owner() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 150]
2015-12-02 11:51:35,560 - ERROR - recipient3 - recipient2 uploads to /test/test3.txt etag for / previous [['"3be226d884ddaa3777da175c15564085"', '"c87fb34ea740303788567e5d3f217f87"']] new [['"3be226d884ddaa3777da175c15564085"', '"c87fb34ea740303788567e5d3f217f87"']] 'etag for / previous [%s] new [%s]' % (root_etags2, root_etags3)) failed in recipient3() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 374]
2015-12-02 11:51:35,576 - ERROR - recipient1 - recipient2 uploads to /test/test3.txt etag for / previous [['"733ef7f505edd6fb35e181b143eb5ca3"', '"75048b40d0679e0dfb3f4c2b20b7e54f"']] new [['"733ef7f505edd6fb35e181b143eb5ca3"', '"75048b40d0679e0dfb3f4c2b20b7e54f"']] 'etag for / previous [%s] new [%s]' % (root_etags2, root_etags3)) failed in recipient1() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 219]
2015-12-02 11:51:42,105 - ERROR - owner - recipient 4 uploads to /sub/test6.txt through reshare etag for / previous ["565ecd3bf0388"] new ["565ecd3bf0388"] 'etag for / previous [%s] new [%s]' % (root_etag5, root_etag6)) failed in owner() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 176]
2015-12-02 11:51:42,106 - ERROR - owner - recipient 4 uploads to /sub/test6.txt through reshare etag for /test previous ["565ecd3beecca"] new ["565ecd3beecca"] 'etag for /test previous [%s] new [%s]' % (test_etag3, test_etag4)) failed in owner() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 178]
2015-12-02 11:51:42,426 - ERROR - recipient1 - recipient 4 uploads to /sub/test6.txt through reshare etag for / previous [['"f7d1e26a8ca36c7c75ad3dcd77194664"', '"e80c78cce0c0c93f3d0b69eb5de0a8ef"']] new [['"f7d1e26a8ca36c7c75ad3dcd77194664"', '"e80c78cce0c0c93f3d0b69eb5de0a8ef"']] 'etag for / previous [%s] new [%s]' % (root_etags5, root_etags6)) failed in recipient1() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 246]
2015-12-02 11:51:42,427 - ERROR - recipient1 - recipient 4 uploads to /sub/test6.txt through reshare etag for /test previous [['"565ecd3beecca"', '"565ecd3beecca"']] new [['"565ecd3beecca"', '"565ecd3beecca"']] 'etag for /test previous [%s] new [%s]' % (test_etags3, test_etags4)) failed in recipient1() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 248]
2015-12-02 11:51:42,484 - ERROR - recipient3 - recipient 4 uploads to /sub/test6.txt through reshare etag for / previous [['"e22d1117883517ffd34d365eddf1e39c"', '"d0f426bb9ce50dafb60a54cb8b81c34a"']] new [['"e22d1117883517ffd34d365eddf1e39c"', '"d0f426bb9ce50dafb60a54cb8b81c34a"']] 'etag for / previous [%s] new [%s]' % (root_etags5, root_etags6)) failed in recipient3() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 396]
2015-12-02 11:51:42,484 - ERROR - recipient3 - recipient 4 uploads to /sub/test6.txt through reshare etag for /test previous [['"565ecd3beecca"', '"565ecd3beecca"']] new [['"565ecd3beecca"', '"565ecd3beecca"']] 'etag for /test previous [%s] new [%s]' % (test_etags3, test_etags4)) failed in recipient3() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 398]
2015-12-02 11:51:44,114 - ERROR - recipient1 - 3 error(s) reported
2015-12-02 11:51:44,116 - ERROR - owner - 3 error(s) reported
2015-12-02 11:51:44,118 - ERROR - recipient3 - 3 error(s) reported
SUMMARY:smash.:Elapsed time: 44s (0:00:44.694431)
CRITICAL:smash.:Aborting run -- non-zero exit code (2)
```

@jvillafanez @icewind1991

@rullzer can you confirm whether it is related to any recent changes to the share API ? I see a 403 error.

**Comment by PVince81** [comment]
`share_file_with_group('/test/sub', group4, perms=31)` throws 403

**Comment by jvillafanez** [comment]
The reported errors are probably caused by the 403 error when the file is shared. Until the share error is fixed, I wouldn't bother to look for propagation errors

**Comment by nickvergessen** [comment]
Still works for me from master 40 minutes ago,
CI has the same problem, so not sure what's actually wrong there.

**Comment by PVince81** [comment]
I'll investigate this since I can reproduce it

**Comment by nickvergessen** [comment]
I just created a docker on solidgear, but even there all tests run fine with the latest master.

**Comment by PVince81** [comment]
Hmm OCS error 403 probably doesn't mean real HTTP error 403.
I don't see anything in the logs.

**Comment by PVince81** [comment]
I put a breakpoint in `createShare` but it doesn't reach it with the value "group4" as if it was getting the 403 earlier. Routing issue ?

**Comment by PVince81** [comment]
Debug mode:
```
OCS request: POST http://127.0.0.1/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares {'headers': {'OCS-APIREQUEST': 'true'}, 'data': {'shareType': 1, 'shareWith': 'test4', 'permissions': 31, 'path': '/test/sub'}}
2015-12-02 15:22:17,045 - CRITICAL - recipient2 - Exception occured: OCS error: 403 
 Traceback (most recent call last):
  File "python/smashbox/multiprocessing_engine.py", line 164, in worker_wrap
    f(step)
  File "/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py", line 286, in recipient2
    share2_data = clients[0].share_file_with_group('/test/sub', group4, perms=31)
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 1185, in share_file_with_group
    self.__check_ocs_status(tree)
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 1402, in __check_ocs_status
    raise OCSResponseError(r)
OCSResponseError: OCS error: 403
```

**Comment by rullzer** [comment]
403 - public upload was disabled by the admin

https://doc.owncloud.org/server/8.2/developer_manual/core/ocs-share-api.html

**Comment by PVince81** [comment]
Ok, it's "test4" not "group4".

The code path reaches `shareItem` in the old Sharing code and the error message is:
"  $e->message                    = (string[66]) 'Sharing 349 failed, because this item is already shared with test4';
"

**Comment by PVince81** [comment]
So maybe a concurrency issue of some sorts ?

**Comment by PVince81** [comment]
oc_share:

```
MariaDB [owncloud]> select * from oc_share;
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
| id | share_type | share_with | uid_owner | uid_fileowner | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token | mail_send |
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
| 22 |          1 | test1      | test1     | NULL          |   NULL | folder    | 393         | /393        |         393 | /test       |          31 | 1449066379 |        0 | NULL       | NULL  |         0 |
| 23 |          1 | test2      | test1     | NULL          |   NULL | folder    | 393         | /393        |         393 | /test       |          31 | 1449066379 |        0 | NULL       | NULL  |         0 |
| 24 |          1 | test3      | test4     | NULL          |     23 | folder    | 393         | /393        |         393 | /test       |          31 | 1449066381 |        0 | NULL       | NULL  |         0 |
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
3 rows in set (0.01 sec)

MariaDB [owncloud]> select * from oc_filecache where fileid in (393, 394);
+--------+---------+----------------+----------------------------------+--------+------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
| fileid | storage | path           | path_hash                        | parent | name | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag          | permissions |
+--------+---------+----------------+----------------------------------+--------+------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
|    393 |      83 | files/test     | d9da358780951c01e7388fcaa673ba64 |    359 | test |        2 |        1 |    0 | 1449066378 |    1449066378 |         0 |                0 | 565eff8a4dfd4 |          31 |
|    394 |      83 | files/test/sub | 1cfe4d86fe7f09ed11fc644bc06a763a |    393 | sub  |        2 |        1 |    0 | 1449066378 |    1449066378 |         0 |                0 | 565eff8a48d83 |          31 |
+--------+---------+----------------+----------------------------------+--------+------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
```

**Comment by PVince81** [comment]
Note that there is both a user "test4" and a group "test4":
```
MariaDB [owncloud]> select * from oc_users;
+-------+-------------+----------------------------------------------------------------+
| uid   | displayname | password                                                       |
+-------+-------------+----------------------------------------------------------------+
| root  | NULL        | 1|$2y$10$qWjpDw./esN2dYb.Sz5BE..VXmNDEXokkV71.9GQdlA/qy8moZ/Qu |
| test  | NULL        | 1|$2y$10$xsKo7awF27RIGncn.zRQpuWvW358/WZBGP2tqhvbjz6yYu6yH5Kdy |
| test1 | NULL        | 1|$2y$10$sM463t1zJkcLrlp21xofRu2rzkqcMI/HEvDrwwbQyZFkuYZtG/FPe |
| test2 | NULL        | 1|$2y$10$xl9xFpjET4LtQcwCN1dtMuqk89pvuDZJ/lgA30DyqVHgxMx5qE34G |
| test3 | NULL        | 1|$2y$10$sbgFY5wefhKku3DIUZKGjuBDb1NPQoY1na/tEhD3gHlKpOezexTMK |
| test4 | NULL        | 1|$2y$10$peS1FWuKSxXGv6Eaj.xDLeWUayz/6zzDIDyGqZuOQRuaOk5PDbk5W |
| test5 | NULL        | 1|$2y$10$3dFQNdb4Ckh5q7HDayLacuzdiofhUhZzEjgMdJkGiRjPvjD.3gkv6 |
| test6 | NULL        | 1|$2y$10$kT4ADLcidJ0d5tFw1LYLPu8cOcl8CdoK546GwfXJz7M6SQ4FOilNC |
| test7 | NULL        | 1|$2y$10$4BIr4752UD.3FcMlh3LrOO4nDWsyBLP.VKAx0SkYvbxEBUg9jrypW |
| test8 | NULL        | 1|$2y$10$AQjO1tXdiLKlM6NTrTBcZu0ARwhXQlwiN9zffmNYh/a2FiqvdtJHu |
| test9 | NULL        | 1|$2y$10$27VO4GR6kEOQFxa0UUmS0e14BkAJnZed6m6GsVkJ.BirElMEycdwq |
+-------+-------------+----------------------------------------------------------------+
11 rows in set (0.00 sec)

MariaDB [owncloud]> select * from oc_groups;
+-------+
| gid   |
+-------+
| admin |
| test1 |
| test2 |
| test3 |
| test4 |
+-------+
```

I don't think it matters because some people like @nickvergessen had no issues when running their tests locally.

I run on master 8d218bf3ef842d76c2b97a175b28e13054497952

**Comment by PVince81** [comment]
```
MariaDB [owncloud]> select * from oc_group_user;
+-------+-------+
| gid   | uid   |
+-------+-------+
| admin | root  |
| test1 | test2 |
| test1 | test3 |
| test2 | test4 |
| test2 | test5 |
| test3 | test6 |
| test3 | test7 |
| test4 | test8 |
| test4 | test9 |
+-------+-------+
```

**Comment by nickvergessen** [comment]
Okay, now with test as group and user name I can reproduce it...

**Comment by rullzer** [comment]
> Ok, it's "test4" not "group4".

The code path reaches shareItem in the old Sharing code and the error message is:
" $e->message = (string[66]) 'Sharing 349 failed, because this item is already shared with test4';
"

On which line?

**Comment by PVince81** [comment]
@rullzer here https://github.com/owncloud/core/blob/master/lib/private/share/share.php#L755

Assigning it to you for research.
