### ISSUE TITLE
8.2.1 (stable) Internal Server Error -> Login LDAP User (Bug in "external sites" App)

### ISSUE THREAD

**Issue by JB1985** [owncloud/core#20941]
OS: Debian 7
PHP 5.4.45-0+deb7u2
ownCloud 8.2.1 (stable) 

Hi, 

I get an Internal Server Error if I try to login with a LDAP User. With local Users it works fine!

I have find this in the logs:

Debug   user_ldap   Count filter: objectclass=\* 2015-12-04T08:00:42+00:00
Debug   user_ldap   LDAP error Invalid DN syntax (34) after calling ldap_read   2015-12-04T08:00:41+00:00
Error   PHP ldap_read(): Search: Invalid DN syntax at /var/www/owncloud-dev82/apps/user_ldap/lib/ldap.php#257   2015-12-04T08:00:41+00:00
Error   PHP Array to string conversion at /var/www/owncloud-dev82/lib/private/template/functions.php#36 2015-12-04T08:00:38+00:00

This LDAP Config worked on OC 8.1.4  Version.

If I try to test the Base DN, Owncloud say me found over 1000 entries.

Logs complete:
```
{"reqId":"sUI2HbjIKm988hlnrlgJ","remoteAddr":"134.100.XX.XXX","app":"user_ldap","message":"No DN found for  on ldaps://ldap.rrz.uni-hamburg.de","level":0,"time":"2015-12-04T08:49:03+00:00","method":"GET","url":"/index.php/core/js/oc.js?v=d637017f19ffe772d42f6e3f7d6ef48d"}
{"reqId":"FSpfBCKHczZimZBmnGTd","remoteAddr":"134.100.XX.XXX","app":"user_ldap","message":"initializing paged search for  Filter objectClass=\* base Array
(
    [0] => cn=XXXX,ou=users,dc=uni-hamburg,dc=de
)
 attr Array
(
    [0] => 
)
 limit 500 offset 0","level":0,"time":"2015-12-04T08:49:11+00:00","method":"GET","url":"/index.php/apps/files/"}
{"reqId":"FSpfBCKHczZimZBmnGTd","remoteAddr":"134.100.XXX.XXX","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-12-04T08:49:11+00:00","method":"GET","url":"/index.php/apps/files/"}
{"reqId":"FSpfBCKHczZimZBmnGTd","remoteAddr":"134.100.XX.XXX","app":"user_ldap","message":"readAttribute: cn=XXXXX,ou=users,dc=uni-hamburg,dc=de found","level":0,"time":"2015-12-04T08:49:11+00:00","method":"GET","url":"/index.php/apps/files/"}
{"reqId":"FSpfBCKHczZimZBmnGTd","remoteAddr":"134.100.XX.XXX","app":"user_ldap","message":"initializing paged search for  Filter objectClass=\* base Array
(
    [0] => cn=XXXXX,ou=users,dc=uni-hamburg,dc=de
)
 attr Array
(
    [0] => displayname
)
 limit 500 offset 0","level":0,"time":"2015-12-04T08:49:11+00:00","method":"GET","url":"/index.php/apps/files/"}
{"reqId":"FSpfBCKHczZimZBmnGTd","remoteAddr":"134.100.XX.XXX","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-12-04T08:49:11+00:00","method":"GET","url":"/index.php/apps/files/"}
{"reqId":"FSpfBCKHczZimZBmnGTd","remoteAddr":"134.100.XX.XXX","app":"index","message":"Exception: {"Exception":"RuntimeException","Message":"image not found: image:mail.svg webroot: serverroot:/var/www/owncloud-dev82","Code":0,"Trace":"
#0 /var/www/owncloud-dev82/apps/external/appinfo/app.php(38): OC\URLGenerator->imagePath('external', 'mail.svg')
#1 /var/www/owncloud-dev82/lib/private/navigationmanager.php(63): OC_App::{closure}()
#2 /var/www/owncloud-dev82/lib/private/app.php(683): OC\NavigationManager->getAll()
#3 /var/www/owncloud-dev82/lib/private/templatelayout.php(101): OC_App::getNavigation()
#4 /var/www/owncloud-dev82/lib/private/template.php(214): OC_TemplateLayout->__construct('user', 'files')
#5 /var/www/owncloud-dev82/lib/private/template/base.php(121): OC_Template->fetchPage()
#6 /var/www/owncloud-dev82/apps/files/index.php(161): OC\Template\Base->printPage()
#7 /var/www/owncloud-dev82/lib/private/route/route.php(154) : runtime-created function(1): require_once('/var/www/ownclo...')
#8 [internal function]: __lambda_func(Array)
#9 /var/www/owncloud-dev82/lib/private/route/router.php(282): call_user_func('\x00lambda_1', Array)
#10 /var/www/owncloud-dev82/lib/base.php(851): OC\Route\Router->match('/apps/files/')
#11 /var/www/owncloud-dev82/index.php(39): OC::handleRequest()
#12 {main}","File":"/var/www/owncloud-dev82/lib/private/urlgenerator.php","Line":189}","level":3,"time":"2015-12-04T08:49:11+00:00","method":"GET","url":"/index.php/apps/files/"}
{"reqId":"IpTYQBw9+yKeWEOXlin3","remoteAddr":"134.100.XX.XXX","app":"user_ldap","message":"initializing paged search for  Filter objectClass=\* base Array
(
    [0] => cn=XXXXX,ou=users,dc=uni-hamburg,dc=de
)
 attr Array
(
    [0] => 
)
 limit 500 offset 0","level":0,"time":"2015-12-04T08:49:12+00:00","method":"GET","url":"/cron.php"}
{"reqId":"IpTYQBw9+yKeWEOXlin3","remoteAddr":"134.100.XX.XXX","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-12-04T08:49:12+00:00","method":"GET","url":"/cron.php"}
{"reqId":"IpTYQBw9+yKeWEOXlin3","remoteAddr":"134.100.XX.XXX","app":"user_ldap","message":"readAttribute: cn=XXXXX,ou=users,dc=uni-hamburg,dc=de found","level":0,"time":"2015-12-04T08:49:12+00:00","method":"GET","url":"/cron.php"}
```

**Comment by PVince81** [comment]
@blizzz

**Comment by blizzz** [comment]
It is a duplicate, please  use the search.

**Comment by Xenopathic** [comment]
``` Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"image not found: image:mail.svg webroot: serverroot:\\/var\\/www\\/owncloud-dev82\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud-dev82\\/apps\\/external\\/appinfo\\/app.php(38): OC\\URLGenerator->imagePath('external', 'mail.svg')\n#1 \\/var\\/www\\/owncloud-dev82\\/lib\\/private\\/navigationmanager.php(63): OC_App::{closure}()...`

This could be your issue

**Comment by blizzz** [comment]
thanks @Xenopathic – the mentioned LDAP error would be a dup, coming from a diagnosis test. I was too fast closing this, sorry.

**Comment by PVince81** [comment]
@icewind1991

**Comment by JB1985** [comment]
@Xenopathic 

you mean it is a app Bug?

**Comment by JB1985** [comment]
The App  "External Sites 1.2 by Frank Karlitschek (AGPL-Lizenziert)" makes the Internal Server Error.

I have disable the App and now the login works!

**Comment by PVince81** [comment]
@LukasReschke can you have a look at the problem with the "external sites" app ?

**Comment by PVince81** [comment]
Steps to reproduce:

1. Enable external sites app
1. Go to admin page
1. Add an external site and use the "external.png" icon
1. Delete the local file "apps/external/img/external.png"
1. Refresh the page

Expected: proper fallback in case the image does not exist
Actual: internal server error that makes ownCloud unusable

Not sure if the core API should be more tolerant or the external sites app should check for existence first.

It would probably be better to have the core API be more robust on that regard.

**Comment by PVince81** [comment]
Observed on 9.1.0beta2

**Comment by PVince81** [comment]
Still happening in 10.0.4

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
