### ISSUE TITLE
[master] php7 and oci cannot install database schema on setup

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#21040]
````
06:14:50 Testing with oci ...
06:14:50 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-00955: name is already used by an existing object in /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
06:14:50 Stack trace:
06:14:50 #0 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php(214): Doctrine\DBAL\Driver\OCI8\OCI8Exception::fromErrorInfo(Array)
06:14:50 #1 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php(116): Doctrine\DBAL\Driver\OCI8\OCI8Statement->execute()
06:14:50 #2 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(935): Doctrine\DBAL\Driver\OCI8\OCI8Connection->query('CREATE TABLE "o...')
06:14:50 #3 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db/mdb2schemamanager.php(168): Doctrine\DBAL\Connection->query('CREATE TABLE "o...')
06:14:50 #4 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db/mdb2schemamanager.php(71): OC\DB\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\DBAL\Schema\Schema))
06:14:50 #5 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db.php(218): OC\DB\MDB2SchemaManager->createDbFromStructure('/ssd/jenkins/wo...')
06:14:50 #6 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/installer.php(530): OC_DB::createDbFromStructure('/ssd/jenkins/wo...')
06:14:50 #7 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/app.php(1057): OC_Installer::installShippedApp('files_sharing')
06:14:50 #8 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/app.php(292): OC_App::installApp('files_sharing')
06:14:50 #9 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/tests/enable_all.php(13): OC_App::enable('files_sharing')
06:14:50 #10 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/tests/enable_all.php(19): enableApp('files_sharing')
06:14:50 #11 {main}
06:14:50 
06:14:50 Next Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE "oc_share_external" ("id" NUMBER(10) NOT NULL, "remote" VARCHAR2(512) NOT NULL, "remote_id" NUMBER(10) DEFAULT -1 NOT NULL, "share_token" VARCHAR2(64) NOT NULL, "password" VARCHAR2(64) DEFAULT NULL NULL, "name" VARCHAR2(64) NOT NULL, "owner" VARCHAR2(64) NOT NULL, "user" VARCHAR2(64) NOT NULL, "mountpoint" VARCHAR2(4000) NOT NULL, "mountpoint_hash" VARCHAR2(32) NOT NULL, "accepted" NUMBER(10) DEFAULT 0 NOT NULL, PRIMARY KEY("id"))':
06:14:50 
06:14:50 ORA-00955: name is already used by an existing object in /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:61
06:14:50 Stack trace:
06:14:50 #0 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception))
06:14:50 #1 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(945): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\OCI8\Driver), Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception), 'CREATE TABLE "o...')
06:14:50 #2 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db/mdb2schemamanager.php(168): Doctrine\DBAL\Connection->query('CREATE TABLE "o...')
06:14:50 #3 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db/mdb2schemamanager.php(71): OC\DB\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\DBAL\Schema\Schema))
06:14:50 #4 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db.php(218): OC\DB\MDB2SchemaManager->createDbFromStructure('/ssd/jenkins/wo...')
06:14:50 #5 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/installer.php(530): OC_DB::createDbFromStructure('/ssd/jenkins/wo...')
06:14:50 #6 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/app.php(1057): OC_Installer::installShippedApp('files_sharing')
06:14:50 #7 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/app.php(292): OC_App::installApp('files_sharing')
06:14:50 #8 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/tests/enable_all.php(13): OC_App::enable('files_sharing')
06:14:50 #9 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/tests/enable_all.php(19): enableApp('files_sharing')
06:14:50 #10 {main}Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-00955: name is already used by an existing object in /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
06:14:50 Stack trace:
06:14:50 #0 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php(214): Doctrine\DBAL\Driver\OCI8\OCI8Exception::fromErrorInfo(Array)
06:14:50 #1 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php(116): Doctrine\DBAL\Driver\OCI8\OCI8Statement->execute()
06:14:50 #2 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(935): Doctrine\DBAL\Driver\OCI8\OCI8Connection->query('CREATE TABLE "o...')
06:14:50 #3 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db/mdb2schemamanager.php(168): Doctrine\DBAL\Connection->query('CREATE TABLE "o...')
06:14:50 #4 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db/mdb2schemamanager.php(71): OC\DB\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\DBAL\Schema\Schema))
06:14:50 #5 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db.php(218): OC\DB\MDB2SchemaManager->createDbFromStructure('/ssd/jenkins/wo...')
06:14:50 #6 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/installer.php(530): OC_DB::createDbFromStructure('/ssd/jenkins/wo...')
06:14:50 #7 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/app.php(1057): OC_Installer::installShippedApp('files_trashbin')
06:14:50 #8 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/app.php(292): OC_App::installApp('files_trashbin')
06:14:50 #9 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/tests/enable_all.php(13): OC_App::enable('files_trashbin')
06:14:50 #10 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/tests/enable_all.php(20): enableApp('files_trashbin')
06:14:50 #11 {main}
06:14:50 
06:14:50 Next Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE "oc_files_trash" ("auto_id" NUMBER(10) NOT NULL, "id" VARCHAR2(250) DEFAULT '' NOT NULL, "user" VARCHAR2(64) DEFAULT '' NOT NULL, "timestamp" VARCHAR2(12) DEFAULT '' NOT NULL, "location" VARCHAR2(512) DEFAULT '' NOT NULL, "type" VARCHAR2(4) DEFAULT NULL NULL, "mime" VARCHAR2(255) DEFAULT NULL NULL, PRIMARY KEY("auto_id"))':
06:14:50 
06:14:50 ORA-00955: name is already used by an existing object in /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:61
06:14:50 Stack trace:
06:14:50 #0 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception))
06:14:50 #1 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(945): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\OCI8\Driver), Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception), 'CREATE TABLE "o...')
06:14:50 #2 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db/mdb2schemamanager.php(168): Doctrine\DBAL\Connection->query('CREATE TABLE "o...')
06:14:50 #3 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db/mdb2schemamanager.php(71): OC\DB\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\DBAL\Schema\Schema))
06:14:50 #4 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/db.php(218): OC\DB\MDB2SchemaManager->createDbFromStructure('/ssd/jenkins/wo...')
06:14:50 #5 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/installer.php(530): OC_DB::createDbFromStructure('/ssd/jenkins/wo...')
06:14:50 #6 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/app.php(1057): OC_Installer::installShippedApp('files_trashbin')
06:14:50 #7 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/app.php(292): OC_App::installApp('files_trashbin')
06:14:50 #8 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/tests/enable_all.php(13): OC_App::enable('files_trashbin')
06:14:50 #9 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/tests/enable_all.php(20): enableApp('files_trashbin')
06:14:50 #10 {main}Exception: App "LDAP user and group backend" cannot be installed because the following dependencies are not fulfilled: The library ldap is not available. in /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/app.php:1093
06:14:50 Stack trace:
06:14:50 #0 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/lib/private/app.php(292): OC_App::installApp('user_ldap')
06:14:50 #1 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/tests/enable_all.php(13): OC_App::enable('user_ldap')
06:14:50 #2 /ssd/jenkins/workspace/server-master-linux-php7/database/oci/label/SLAVE/tests/enable_all.php(22): enableApp('user_ldap')
06:14:50 #3 {main}

**Comment by DeepDiver1975** [comment]
This is still because of doctrine/dbal not working properly with php7 on oracle - refs https://github.com/owncloud/core/issues/18425
