### ISSUE TITLE
Too many errors and fails while syncing files

### ISSUE THREAD

**Issue by kapcom01** [owncloud/core#21168]
### Steps to reproduce
1. I just add a new file named `test`

### Expected behaviour
The file should be uploaded on the server with no errors.

### Actual behaviour
The owncloud client icon indicates that sync has began but it takes too long even for a 0 bytes files. After a while it turns to green indicating that sync is complete but nothing has been uploaded yet. Then it goes blue again and after a while a notification pops up that prompts me to read the error log and then the icon turns to red indicating failure. Once again the icon turns to syncing blue and this time completes with success and now the file has been uploaded successfully (after about 5 minutes for a 0 bytes file).
![2015-12-12 23-31-48](https://cloud.githubusercontent.com/assets/21684/11764067/f5aebfde-a12a-11e5-9f8a-004b0bc97ecc.png)

### Server configuration
**Operating system**: Ubuntu 14.04.3 LTS

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** sqlite

**PHP version:** PHP 5.5.9-1ubuntu4.14

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** updated from the previous version

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - external: 1.2
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - news: 6.1.1
  - notifications: 0.1.0
  - tasks: 0.8.1
  - user_external: 0.4
Disabled:
  - direct_menu
  - encryption
  - mail
  - mozilla_sync
  - ocDashboard
  - provisioning_api
  - templateeditor
  - updater
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc5dbfa47aaf',
  'passwordsalt' => '----------------',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '8.2.1.4',
  'installed' => true,
  'loglevel' => 0,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'owncloud.kapcom.gr',
  ),
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_smtppassword' => '----------',
  'mail_domain' => 'kapcom.gr',
  'secret' => '--------------',
  'trashbin_retention_obligation' => 'auto',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium 45.0.2454.101 Ubuntu 15.10 (64-bit)

**Operating system:** Ubuntu 15.10

#### Web server error log
```
no errors
```

#### ownCloud log (data/owncloud.log)
```
root@owncloud:/var/www/owncloud/data# tail -f owncloud.log  |grep test
{"reqId":"sUO8Ezqj8zKENS43I+xI","remoteAddr":"192.168.1.19","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT SUM(\\\"size\\\") AS f1 FROM \\\"oc_filecache\\\" WHERE \\\"parent\\\" = ? AND \\\"storage\\\" = ? AND \\\"size\\\" >= 0' with params [2, \\\"1\\\"]:\\n\\nSQLSTATE[HY000]: General error: 11 database disk image is malformed\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT SUM(\\\"siz...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/statementwrapper.php(73): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db.php(147): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/homecache.php(54): OC_DB::executeAudited('SELECT SUM(`siz...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(658): OC\\\\Files\\\\Cache\\\\HomeCache->calculateFolderSize('files', NULL)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(664): OC\\\\Files\\\\Cache\\\\Cache->correctFolderSize('files')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/updater.php(116): OC\\\\Files\\\\Cache\\\\Cache->correctFolderSize('files\\\/test', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(191): OC\\\\Files\\\\Cache\\\\Updater->update('\\\/\\\/test')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(115): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #33)\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('test', Resource id #33)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('test', Resource id #33, NULL)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":85}","level":4,"time":"2015-12-12T21:29:38+00:00","method":"PUT","url":"\/remote.php\/webdav\/test"}

```

**Comment by RealRancor** [comment]
@kapcom01 Seems you have some issues with your sqlite database:

> General error: 11 database disk image is malformed

A sane thing you could do is to convert this instance to MySQL.

**Comment by kapcom01** [comment]
Thank you for your answer.
Is there a guide to do this specifically for owncloud?

**Comment by RealRancor** [comment]
I'm not sure if that will help if the database is already malformed but still worth a try:

https://doc.owncloud.org/server/8.2/admin_manual/configuration_database/db_conversion.html

**Comment by kapcom01** [comment]
Wow! The conversion to mysql is completed and I see a HUGE difference! Everything syncs almost instantly! No errors at all! :smiley:

**Comment by RealRancor** [comment]
Nice :-)

In general sqlite is not recommended, even with the smallest setup.
