### ISSUE TITLE
Trying to access files shows "Can't read file" message

### ISSUE THREAD

**Issue by sameersbn** [owncloud/core#21298]
I am using owncloud 8.x and recently I noticed that I get the "Can't read file" message when I try to download most of the files. I have encryption enabled on the server and I am guessing for some reason the the files cannot be decrypted by owncloud. I am not exactly sure when the issue started to be able to figure out what I might have down wrong. Perhaps i must have played around with the encryption settings at some point.

I would like to point out that, any new files that I upload to the server can be downloaded just fine. Its that the older files that exist on the server are not longer accessible.

I am currently on owncloud 8.2.1 and am not able to figure out how this happened or how i could fix it to recover all my data. When I try accessing a file on the server, I see the following message in `owncloud.log`

```
{"reqId":"2kJjJBbc56+P5DJCvHN2","remoteAddr":"106.77.1.188","app":"no app in context","message":"Exception: {\"Exception\":\"OCA\\\\Encryption\\\\Exceptions\\\\MultiKeyDecryptException\",\"Message\":\"multikeydecrypt with share key failed:error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/keymanager.php(406): OCA\\\\Encryption\\\\Crypto\\\\Crypt->multiKeyDecrypt('6?^Z??\\\/_???D?+X...', '??Q$??????i\\\"~8?...', '-----BEGIN PRIV...')\\n#1 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(419): OCA\\\\Encryption\\\\KeyManager->getFileKey('\\\/sameer\\\/files\\\/D...', 'sameer')\\n#2 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(289): OCA\\\\Encryption\\\\Crypto\\\\Encryption->isReadable('\\\/sameer\\\/files\\\/D...', 'sameer')\\n#3 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(161): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->isReadable('files\\\/Documents...')\\n#4 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1023): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->isReadable('files\\\/Documents...')\\n#5 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(399): OC\\\\Files\\\\View->basicOperation('isReadable', '\\\/Documents\\\/Docu...')\\n#6 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(672): OC\\\\Files\\\\View->isReadable('\\\/Documents\\\/Docu...')\\n#7 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/lib\\\/private\\\/files.php(164): OC\\\\Files\\\\Filesystem::isReadable('\\\/Documents\\\/Docu...')\\n#8 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/lib\\\/private\\\/files.php(90): OC_Files::getSingleFile(Object(OC\\\\Files\\\\View), '\\\/Documents\\\/Docu...', 'BUSINESS APPLIC...', false)\\n#9 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(53): OC_Files::get('\\\/Documents\\\/Docu...', Array, false)\\n#10 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/usr\\\/share\\\/ngin...')\\n#11 [internal function]: __lambda_func(Array)\\n#12 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func('?lambda_1030', Array)\\n#13 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#14 \\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/www\\\/com.mydomain\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":564}","level":3,"time":"2015-12-18T17:30:26+00:00"}
```

In the ocdata folder (and the user folders therein) I notice directories named `encryption_migration_backup_2015-07-24_04-49-XX`. I was wondering if I could manually run some commands that would allow be to decrypt the various files.

Any help on this would be greatly appreciated.

```bash
# php --version
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

```bash
# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "ocva7s0hub4m",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mydomain.com"
        ],
        "datadirectory": "\/usr\/share\/nginx\/www\/com.mydomain\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.mydomain.com",
        "dbtype": "pgsql",
        "version": "8.2.1.4",
        "dbname": "owncloud_production",
        "dbhost": "172.17.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "noreply",
        "mail_domain": "mydomain.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Comment by sameersbn** [comment]
I managed to recover the installation by reverting to owncloud 8.0.3 and restoring the `file_encryption` keys from the `encryption_backup_` folders that are present in the `ocdata` folder and the user folders. I will be downloading all the files and setting up owncloud from scratch before uploading all the files.
