### ISSUE TITLE
Doctrine: UniqueConstraintViolationException

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#21320]
### Steps to reproduce
Go to owncloud admin and check the log.

(also, you can reproduce when you attempt to upload a couple of pictures directly into a folder)

### Expected behaviour
There are no log entries when uploading pictures.

### Actual behaviour
Here is the error that appears hundred times in the log:

```
Exception: {"Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Message":"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/045ce3e43f130491fe682f8dd9ffb9ad\", 1, 1450738513, \"files\\\/045ce3e43f130491fe682f8dd9ffb9ad\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\/045ce3e43f130491fe682f8dd9ffb9ad' for key 'lock_key_index'","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/db\/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/var\/www\/owncloud\/lib\/private\/db\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array)\n#4 \/var\/www\/owncloud\/lib\/private\/db\/connection.php(242): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#5 \/var\/www\/owncloud\/lib\/private\/lock\/dblockingprovider.php(113): OC\\DB\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#6 \/var\/www\/owncloud\/lib\/private\/lock\/dblockingprovider.php(158): OC\\Lock\\DBLockingProvider->initLockField('files\/045ce3e43...', 1)\n#7 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(639): OC\\Lock\\DBLockingProvider->acquireLock('files\/045ce3e43...', 1)\n#8 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(572): OC\\Files\\Storage\\Common->acquireLock('files\/M1\/home', 1, Object(OC\\Lock\\DBLockingProvider))\n#9 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(572): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/M1\/home', 1, Object(OC\\Lock\\DBLockingProvider))\n#10 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(572): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/M1\/home', 1, Object(OC\\Lock\\DBLockingProvider))\n#11 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1803): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/M1\/home', 1, Object(OC\\Lock\\DBLockingProvider))\n#12 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1902): OC\\Files\\View->lockPath('\/M1\/home', 1)\n#13 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1010): OC\\Files\\View->lockFile('\/M1\/home\/michae...', 1)\n#14 \/var\/www\/owncloud\/lib\/private\/files\/view.php(871): OC\\Files\\View->basicOperation('fopen', '\/M1\/home\/michae...', Array, 'r')\n#15 \/var\/www\/owncloud\/lib\/private\/files\/view.php(882): OC\\Files\\View->fopen('\/M1\/home\/michae...', 'r')\n#16 \/var\/www\/owncloud\/lib\/private\/preview\/image.php(51): OC\\Files\\View->toTmpFile('\/M1\/home\/michae...')\n#17 \/var\/www\/owncloud\/lib\/private\/preview.php(1136): OC\\Preview\\Image->getThumbnail('\/M1\/home\/michae...', 2048, 2048, false, Object(OC\\Files\\View))\n#18 \/var\/www\/owncloud\/lib\/private\/preview.php(770): OC\\Preview->generatePreview(464003)\n#19 \/var\/www\/owncloud\/lib\/private\/preview.php(795): OC\\Preview->getPreview()\n#20 \/var\/www\/owncloud\/core\/ajax\/preview.php(63): OC\\Preview->showPreview()\n#21 \/var\/www\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#22 [internal function]: __lambda_func(Array)\n#23 \/var\/www\/owncloud\/lib\/private\/route\/router.php(282): call_user_func('\\x00lambda_4219', Array)\n#24 \/var\/www\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/core\/preview.p...')\n#25 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#26 {main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66} 
```

Maybe it says something?

### Server configuration

```
$   
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

```
$ uname -a      
Linux binarykitchen.com 3.12.27-xenU #1 SMP Thu Aug 28 23:13:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Web server:

```
$ nginx -v
nginx version: nginx/1.8.1
```

Database:

```
$ mysql --version
mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3
```

PHP version:

```
$ php -v
PHP 5.5.27-1+deb.sury.org~trusty+1 (cli) (built: Jul 15 2015 12:14:44) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

ownCloud version:
ownCloud 8.2.1.4 (stable) 

Updated from an older ownCloud or fresh install:
Fresh install via apt-get

```
$ sudo -u www-data php ./occ app:list

Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - encryption: 1.1.0
  - external: 1.2
  - files: 1.2.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - music: 0.3.8
  - provisioning_api: 0.3.0
  - search_lucene: 0.7.0
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - files_external
  - firstrunwizard
  - notifications
  - user_external
  - user_ldap
```

The content of config/config.php: (Without sensitive data)

```
$ cat config.php                                                                                                                                                                                         1 
<?php
$CONFIG = array (
  'instanceid' => 'oc02ca513338',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 1,
  'logfile' => '/var/log/owncloud.log',
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'trusted_domains' => 
  array (
    0 => 'cloud.binarykitchen.com',
  ),
  'mail_smtpmode' => 'smtp',
  'secret' => 'xxx',
  'forceSSLforSubdomains' => true,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'mail_smtpauthtype' => 'PLAIN',
  'trashbin_retention_obligation' => 'auto',
);

```

Are you using external storage, if yes which one:
None

### Client configuration
Browser:
Firefox 41

Operating system:
Ubuntu 15.10

#### Web server error log

N/A

#### ownCloud log (data/owncloud.log)
N/A

#### Browser log
Irrelevant

**Comment by DeepDiver1975** [comment]
@icewind1991

**Comment by PVince81** [comment]
@binarykitchen 8.2.2 has been optimized a bit regarding locking, have you seen this error again in that version ?

**Comment by binarykitchen** [comment]
no idea, upgraded to v9

**Comment by PVince81** [comment]
Please check your transaction isolation modes: https://github.com/owncloud/core/issues/24882#issuecomment-222456110

OC 9.0.3 should tell you now in the admin page if yours are wrong.

If the mode is correct and the problem still occurs in 9.0.3, please reopen.
