### ISSUE TITLE
Windows Client Login fails: "No basic authentication headers were found"

### ISSUE THREAD

**Issue by srissel** [owncloud/core#21371]
Hello,

I migrated my ownCloud-Instance to a new server.
Accessing from the web works quite well so far, but every time I want to login with an OS client (I tried Windows and Android), the login fails with the following log message:

```
Exception: {
	"Message": "HTTP/1.1 401 No basic authentication headers were found",
	"Exception": "Sabre\\DAV\\Exception\\NotAuthenticated",
	"Code": 0,
	"Trace":
        "#0 /var/www/vhosts/euve103340.serverprofi24.de/cloud/lib/private/connector/sabre/auth.php(154): Sabre\DAV\Auth\Backend\AbstractBasic->authenticate(Object(OC\Connector\Sabre\Server), 'ownCloud')
        #1 /var/www/vhosts/euve103340.serverprofi24.de/cloud/lib/private/connector/sabre/auth.php(127): OC\Connector\Sabre\Auth->auth(Object(OC\Connector\Sabre\Server), 'ownCloud')
        #2 /var/www/vhosts/euve103340.serverprofi24.de/cloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php(118): OC\Connector\Sabre\Auth->authenticate(Object(OC\Connector\Sabre\Server), 'ownCloud')
        #3 [internal function]: Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
        #4 /var/www/vhosts/euve103340.serverprofi24.de/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
        #5 /var/www/vhosts/euve103340.serverprofi24.de/cloud/3rdparty/sabre/dav/lib/DAV/Server.php(456): Sabre\Event\EventEmitter->emit('beforeMethod', Array)
        #6 /var/www/vhosts/euve103340.serverprofi24.de/cloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
        #7 /var/www/vhosts/euve103340.serverprofi24.de/cloud/apps/files/appinfo/remote.php(55): Sabre\DAV\Server->exec()
        #8 /var/www/vhosts/euve103340.serverprofi24.de/cloud/remote.php(137): require_once('/var/www/vhosts...')
        #9 {main}",
	"File": "/var/www/vhosts/euve103340.serverprofi24.de/cloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php",
	"Line": 70
}
```

My server runs:
* Ubuntu 14.04
* PHP 5.5.9
* ownCloud 8.2.1

I found this issue on Github (https://github.com/owncloud/core/issues/14510), but I can't figure out, why a native client (even Windows) causes this error.

My original ownCloud instance on the old server never threw this error.

Do you have any help on this?

**Comment by srissel** [comment]
N.B. At the moment I use FastCGI, the old server runs PHP as ApacheModule.

**Comment by srissel** [comment]
The issue seems to relate to using PHP in FastCGI mode.
If I turn FastCGI off, native client login works well again.

Is this a common problem?

**Comment by RealRancor** [comment]
@srissel See my reply at your forums post: https://forum.owncloud.org/viewtopic.php?f=14&t=32230

Probably nothing what can be fixed within oC.

**Comment by MorrisJobke** [comment]
> @srissel See my reply at your forums post: https://forum.owncloud.org/viewtopic.php?f=14&t=32230
> 
> Probably nothing what can be fixed within oC.

Correct -> closing
