### ISSUE TITLE
Problems with the apps navigation after upgrade from 8.2.1.4 to 8.2.2.2 (solution is here)

### ISSUE THREAD

**Issue by arno01** [owncloud/core#21406]
Hi folks,
I'm here just to report my experience of today :-)

After upgrade from 8.2.1.4 to 8.2.2.2, I had problems with the Calendar and Contacts apps, I was getting the URL of the current page, e.g. "https://myowncloud.com/index.php/apps/files" each time when I was trying to open Calendar or Contacts app via selecting "Files" -> "Calendar" or "Contacts".

### Errors
The error log showed the following

#### For Calendar app
```
{"reqId":"nE6iJOTZ5TREp05eyg67","remoteAddr":"[--REMOVED--]","app":"no app in context","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"calendar_index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(325): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('calendar_index', Array, false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/cachingrouter.php(56): OC\\\\Route\\\\Router->generate('calendar_index', Array, false)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(65): OC\\\\Route\\\\CachingRouter->generate('calendar_index', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/helper.php(66): OC\\\\URLGenerator->linkToRoute('calendar_index', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/util.php(301): OC_Helper::linkToRoute('calendar_index', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/app.php(25): OCP\\\\Util::linkToRoute('calendar_index')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(160): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(141): OC_App::requireAppFile('calendar')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(1171): OC_App::loadApp('calendar', false)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(219): OC_App::updateApp('calendar')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(249): OC_Installer::updateApp(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(509): OC_Installer::updateAppByOCSId('168707')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(323): OC\\\\Updater->upgradeAppStoreApps(Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.2.2', '8.2.1.4')\\n#14 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":3,"time":"2015-12-31T00:09:58+01:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=[--REMOVED--]"}
```

#### For Contacts app
```
{"reqId":"nE6iJOTZ5TREp05eyg67","remoteAddr":"[--REMOVED--]","app":"no app in context","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"contacts_index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(325): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('contacts_index', Array, false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/cachingrouter.php(56): OC\\\\Route\\\\Router->generate('contacts_index', Array, false)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(65): OC\\\\Route\\\\CachingRouter->generate('contacts_index', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/helper.php(66): OC\\\\URLGenerator->linkToRoute('contacts_index', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/util.php(301): OC_Helper::linkToRoute('contacts_index', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/app.php(18): OCP\\\\Util::linkToRoute('contacts_index')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(160): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(141): OC_App::requireAppFile('contacts')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(1171): OC_App::loadApp('contacts', false)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(219): OC_App::updateApp('contacts')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(249): OC_Installer::updateApp(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(509): OC_Installer::updateAppByOCSId('168708')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(323): OC\\\\Updater->upgradeAppStoreApps(Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.2.2', '8.2.1.4')\\n#14 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":3,"time":"2015-12-31T00:10:01+01:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=[--REMOVED--]"}
```

## Solution

I have resolved this issue by removing the following entries from my ownCloud DB:

```
MariaDB [dbowncloud]> SELECT * FROM oc_appconfig WHERE appid=168708 OR appid=169914;
+--------+-----------+-------------+
| appid  | configkey | configvalue |
+--------+-----------+-------------+
| 168708 | enabled   | no          |
| 169914 | enabled   | no          |
+--------+-----------+-------------+
2 rows in set, 216 warnings (0.00 sec)

MariaDB [dbowncloud]> DELETE FROM oc_appconfig WHERE appid=168708 OR appid=169914;
Query OK, 2 rows affected, 216 warnings (0.00 sec)
```

Hope someone will find this useful!

**Comment by karlitschek** [comment]
@icewind1991 @PVince81

**Comment by PVince81** [comment]
possibly routing issue ? @icewind1991 @Xenopathic @MorrisJobke @LukasReschke

**Comment by Xenopathic** [comment]
If the app isn't enabled, how is it showing in the app drawer?

**Comment by arno01** [comment]
@Xenopathic well, the app was actually enabled. I've even tried to disable & enable it again. Apps *were* present when I hovered with the mouse pointer over the "Files", however the href link was always pointing to the present page.

**Comment by PVince81** [comment]
Please try again with 8.2.5 or 9.0.2. If the problem persists, please reopen.
