### ISSUE TITLE
multiple exception in database

### ISSUE THREAD

**Issue by kaplandani** [owncloud/core#21410]
I've noticed while deleting some local files I get an internal server error in the client log.
Checking the server reviled many fatal errors like this:

```
Exception: {"Message":"HTTP\/1.1 500 An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\"1\", \"2\", 1451433019, -1, \"56831c3b96431\", 1451433019, 31, \"371220\", \"b4067fcacf827ac349f04b29fa2a0e33\", \"files_encryption\\\/keys\\\/files\\\/W\\\/Old Projects\\\/NewCementec\\\/Pages\", \"Pages\", \"1\", \"1\", \"b4067fcacf827ac349f04b29fa2a0e33\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-b4067fcacf827ac349f04b29fa2a0e33' for key 'fs_storage_path_hash'","Exception":"Sabre\\DAV\\Exception","Code":0,"Trace":"#0 \/home\/cldk3\/public_html\/oc\/lib\/private\/connector\/sabre\/file.php(147): OC\\Connector\\Sabre\\File->convertToSabreException(Object(Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException))\n#1 \/home\/cldk3\/public_html\/oc\/lib\/private\/connector\/sabre\/directory.php(115): OC\\Connector\\Sabre\\File->put(Resource id #308)\n#2 \/home\/cldk3\/public_html\/oc\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('Infrastructures...', Resource id #308)\n#3 \/home\/cldk3\/public_html\/oc\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('W\/Old Projects\/...', Resource id #308, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/home\/cldk3\/public_html\/oc\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/home\/cldk3\/public_html\/oc\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \/home\/cldk3\/public_html\/oc\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/home\/cldk3\/public_html\/oc\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#9 \/home\/cldk3\/public_html\/oc\/remote.php(137): require_once('\/home\/cldk3\/pub...')\n#10 {main}","File":"\/home\/cldk3\/public_html\/oc\/lib\/private\/connector\/sabre\/file.php","Line":497}
```

Server version is 8.2.2on centos 7.0 with redis configured using php 5.4
Client is 2.1.0 build 5683

**Comment by LukasReschke** [comment]
@icewind1991 Any idea?

**Comment by nickvergessen** [comment]
exact mysql version please

**Comment by kaplandani** [comment]
5.5.44-MariaDB

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/issues/20555
