### ISSUE TITLE
WEBDAV Fails with wrong User and Password in a shared folder (SAMBA)

### ISSUE THREAD

**Issue by Netgear24** [owncloud/core#21420]
Owncloud 8.2.1 production

Server: 

IBM x3650
Intel Xeon E5420
12 GB Ram
8 x 146 GB SAS in a Raid 5

Error Log

```
{"reqId":"5q6qGGt9JGf7+5dhMa3p","remoteAddr":"87.245.xxx.xx","app":"webdav","message":"Exception: {\"Message\":\"Invalid login\",\"Exception\":\"Icewind\\\\SMB\\\\Exception\\\\AuthenticationException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Connection.php(43): Icewind\\\\SMB\\\\Connection->checkConnectionError('session setup f...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Share.php(345): Icewind\\\\SMB\\\\Connection->read()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Share.php(120): Icewind\\\\SMB\\\\Share->execute('allinfo \\\"\\\"')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(102): Icewind\\\\SMB\\\\Share->stat('\\\/')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(272): OC\\\\Files\\\\Storage\\\\SMB->getFileInfo('')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(91): OC\\\\Files\\\\Storage\\\\SMB->filetype('')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(99): OC\\\\Files\\\\Storage\\\\Common->is_dir('')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(104): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->is_dir('')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(99): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->is_dir('')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(99): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->is_dir('')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(102): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->is_dir('')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1207): OC\\\\Files\\\\Cache\\\\Watcher->update('', Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php(148): OC\\\\Files\\\\View->getFileInfo('Fotos_Beat')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/custompropertiesbackend.php(100): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Fotos_Beat')\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropertyStorage\\\/Plugin.php(86): OC\\\\Connector\\\\Sabre\\\\CustomPropertiesBackend->propFind('Fotos_Beat', Object(Sabre\\\\DAV\\\\PropFind))\\n#15 [internal function]: Sabre\\\\DAV\\\\PropertyStorage\\\\Plugin->propFind(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre\\\\Directory))\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#17 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1016): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#18 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(936): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre\\\\Directory))\\n#19 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(327): Sabre\\\\DAV\\\\Server->getPropertiesForPath('', Array, 1)\\n#20 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropfind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#21 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#22 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#23 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#24 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#25 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#26 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Connection.php\",\"Line\":69}","level":4,"time":"2016-01-02T21:46:59+00:00"}
```

I changed my password on an external samba share that was connected with my owncloud installation over VPN. The Sync process was slower than normal and then fails the webdav server completly. acces over https was again possible and works fine. only the sync client dont work properly

**Comment by karlitschek** [comment]
not sure this is an owncloud bug. might have something to do with your setup. I suggest to look at owncloud.org/support for different ways to get support. Thanks.
