### ISSUE TITLE
External storage failed

### ISSUE THREAD

**Issue by lolo4992** [owncloud/core#21474]
I run two different version of owncloud.
Owncloud 8.2.1 on Jessie
No problem to add an external storage which is on a Windows 2012 R2 server.

Owncloud 8.2.2 on Jessie
Cannot add an external storage which is on a Windows 2012 R2 server... I have a red square, excepted for one directory share. I did the same configuration :
SMB / CIFS 
Use authentification from OC
ip address of the Windows 2012 server

smbclient, php5-libsmbclient and cifs-utils are installed and up to date on both server

In the log, I've the following message
	Exception: {"Exception":"Icewind\\SMB\\Exception\\Exception","Message":"Unknown error (NT_STATUS_OBJECT_NAME_INVALID) for \/","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(364): Icewind\\SMB\\Parser->checkForError(Array, '\/')\n#1 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(128): Icewind\\SMB\\Share->parseOutput(Array, '\/')\n#2 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(102): Icewind\\SMB\\Share->stat('\/')\n#3 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(136): OC\\Files\\Storage\\SMB->getFileInfo('')\n#4 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(410): OC\\Files\\Storage\\SMB->stat('')\n#5 \/var\/www\/owncloud\/apps\/files_external\/lib\/config.php(261): OC\\Files\\Storage\\Common->test(false)\n#6 \/var\/www\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\n#7 \/var\/www\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(257): OCA\\Files_External\\Controller\\StoragesController->updateStorageStatus(Object(OCA\\Files_external\\Lib\\StorageConfig))\n#8 [internal function]: OCA\\Files_External\\Controller\\StoragesController->show(9)\n#9 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#10 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'show')\n#11 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'show')\n#12 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('GlobalStoragesC...', 'show', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#13 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#14 \/var\/www\/owncloud\/lib\/private\/route\/router.php(291): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#15 \/var\/www\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/files_ext...')\n#16 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#17 {main}","File":"\/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Parser.php","Line":66}

When I try : smbclient -L 172.20.1.2 -U admin
I have the same answer on both of the server.

Do I miss something or is it a bug of OC 8.2.2?

**Comment by karlitschek** [comment]
@Xenopathic @icewind1991 Do you know if we have a regression here?

**Comment by lolo4992** [comment]
Update.

I checked the mount.json files. It is exactly the same on my OC 8.2.1 and OC 8.2.2.

**Comment by Xenopathic** [comment]
There were no code changes to the SMB backend between 8.2.1 and 8.2.2.

**Comment by PVince81** [comment]
Are both ownCloud instances on the same server or different one ?
Does the failing folder contain special characters ?

If the servers are different, maybe you have installed php5-libsmbclient on one but not the other ?

**Comment by PVince81** [comment]
also, is that folder a DFS folder ? (which would only work if php5-libsmbclient is installed)

**Comment by lolo4992** [comment]
That is two different servers with the same model of computer. I did the same install on it excepted for the version of OC.

I've installed smbclient, php5-libsmbclient and cifs-utils on both. I purged it and reinstall it too.
The failing folder as no special caracters : Partage, Video. I tried to create a new one called test... but not working too. But I can share the folder ofcscan of the same server!

That is SMB share on my Windows server 2012.


The External storage seems to change between OC 8.2.1 and 8.2.2. On OC 8.2.1, I cannot access the advanced settings for each folder. It is working properly on OC 8.2.2.

I'll try to install again the server Jessie and OC to see if that happened again or not.

**Comment by lolo4992** [comment]
I did another OC 8.2.2.... No problem with external storage from Windows 2012. I didn't understand why... I did the same thing for installing the debian and the owncloud.

**Comment by Xenopathic** [comment]
@lolo4992 Can this be closed then? You can re-open it if the issue comes up again.

**Comment by AndrewTilson** [comment]
Not sure if related but if so i just posted this.
https://forum.owncloud.org/viewtopic.php?f=36&t=32458

**Comment by PVince81** [comment]
Closing due to lack of activity. It looks like an environment issue.
