### ISSUE TITLE
PDOException: SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress

### ISSUE THREAD

**Issue by datorexpert** [owncloud/core#21489]
Trying to upgrade from 8.0.4 to 8.0.10.
The permissions are set to 0777 for the entire installation.
The owncloud.log says:

```
{"reqId":"f47e2952896603fc709792d49b6847fd","remoteAddr":"192.168.10.174","app":"core","message":"starting upgrade from 8.0.4.2 to 8.0.10.2","level":0,"time":"2016-01-06T16:14:39+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=c3GcD989GGCbP7uUiFIBuqLhs\/k4Jl"}
{"reqId":"f47e2952896603fc709792d49b6847fd","remoteAddr":"192.168.10.174","app":"update","message":"Exception: {\"Message\":\"SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress\",\"Code\":\"HY000\",\"Trace\":\"#0 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1216): PDO->commit()\\n#1 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair\\\/repairlegacystorages.php(234): Doctrine\\\\DBAL\\\\Connection->commit()\\n#2 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair.php(62): OC\\\\Repair\\\\RepairLegacyStorages->run()\\n#3 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(277): OC\\\\Repair->run()\\n#4 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(177): OC\\\\Updater->doUpgrade('8.0.10.2', '8.0.4.2')\\n#5 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/core\\\/ajax\\\/update.php(64): OC\\\\Updater->upgrade()\\n#6 {main}\",\"File\":\"\\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php\",\"Line\":1216}","level":4,"time":"2016-01-06T16:14:40+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=c3GcD989GGCbP7uUiFIBuqLhs\/k4Jl"}
```

What is wrong?

**Comment by DeepDiver1975** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by datorexpert** [comment]
### Steps to reproduce
1. The current state is to go to my PC just go to the web browser and enter the path to the Owncloud installation.
2. If a do a refresh installation. Install version 8.0.4 via the app from QNAP and do the configuration. Then copy the 8.0.10 files via WinSCP over the old files.

### Expected behaviour
Should have v8.1.0

### Actual behaviour
The error above

### Server configuration
NAS server QNAP SS-839 32-bit x86

**Web server:**
[phpinfo.docx](https://github.com/owncloud/core/files/80105/phpinfo.docx)

**Database:**
Default

**PHP version:**
v5.5.29

**ownCloud version:** (see ownCloud admin page)
8.0.4 to 8.0.10

**Updated from an older ownCloud or fresh install:**
Updating

**List of activated apps:**
Default
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
Unable to run the command
```

**The content of config/config.php:**

```
Insert your config.php content here
<?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => '192.168.10.185',
  ),
  'datadirectory' => '/share/MD0_DATA/.qpkg/owncloud/owncloud/data',
  'overwrite.cli.url' => 'https://192.168.10.185:8081/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.0.4.2',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'theme' => '',
  'loglevel' => 0,
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome 47.0.2526.106 m

**Operating system:**
Windows 10 Home 64-bit

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
{"reqId":"f47e2952896603fc709792d49b6847fd","remoteAddr":"192.168.10.174","app":"core","message":"starting upgrade from 8.0.4.2 to 8.0.10.2","level":0,"time":"2016-01-06T16:14:39+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=c3GcD989GGCbP7uUiFIBuqLhs\/k4Jl"}
{"reqId":"f47e2952896603fc709792d49b6847fd","remoteAddr":"192.168.10.174","app":"update","message":"Exception: {\"Message\":\"SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress\",\"Code\":\"HY000\",\"Trace\":\"#0 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1216): PDO->commit()\\n#1 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair\\\/repairlegacystorages.php(234): Doctrine\\\\DBAL\\\\Connection->commit()\\n#2 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair.php(62): OC\\\\Repair\\\\RepairLegacyStorages->run()\\n#3 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(277): OC\\\\Repair->run()\\n#4 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(177): OC\\\\Updater->doUpgrade('8.0.10.2', '8.0.4.2')\\n#5 \\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/core\\\/ajax\\\/update.php(64): OC\\\\Updater->upgrade()\\n#6 {main}\",\"File\":\"\\\/share\\\/MD0_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php\",\"Line\":1216}","level":4,"time":"2016-01-06T16:14:40+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=c3GcD989GGCbP7uUiFIBuqLhs\/k4Jl"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
This can happen with sqlite database - please try to rerun the upgrade

**Comment by datorexpert** [comment]
I tried to rerun the upgrade by browsing to the owncloud installation. No
change, sorry!
Den 6 jan 2016 18:28 skrev "Thomas Müller" <notifications@github.com>:

**Comment by DeepDiver1975** [comment]
> I tried to rerun the upgrade by browsing to the owncloud installation.

do you have shell access to the server?

**Comment by DeepDiver1975** [comment]
can you run the upgrade using the occ command line tool?

**Comment by datorexpert** [comment]
Yes, I have shell access to the server.
What is the exact command to run? The server is on the NAS QNAP SS-839.

Best regards,
/Thomas
Den 6 jan 2016 19:03 skrev "Thomas Müller" <notifications@github.com>:

**Comment by RealRancor** [comment]
@datorexpert See the documentation:

https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/occ_command.html#command-line-upgrade-label

**Comment by PVince81** [comment]
Closing due to lack of feedback.
