### ISSUE TITLE
Installation broken on master

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21669]
I see the following when trying to install with SQLite:

```
An exception occurred while executing 'SELECT "uid", "displayname" FROM "oc_users" WHERE LOWER("uid") = LOWER(?)':

SQLSTATE[HY000]: General error: 1 no such table: oc_users					
```

**Comment by LukasReschke** [comment]
```
➜  master git:(0c0829f) ✗ git bisect good
c15cab7ed6bf2d3ce9009ca09c7c5f33b252860f is the first bad commit
commit c15cab7ed6bf2d3ce9009ca09c7c5f33b252860f
Author: Robin Appelman <icewind@owncloud.com>
Date:   Tue Dec 22 17:42:28 2015 +0100

    Allow admins to add system wide root certificates

:040000 040000 c36da7dd6c7c7d2eaaafe6b1995a37d5783e8ee0 b00a8a14a90638aff0b0b42745028bdda3206e92 M	apps
:040000 040000 56d0729d736cb64366858107ff89b45284b8c0dd 85c3032dbe0eb2d2715e50b06ca6adc41851ea08 M	lib
:040000 040000 8cadaa2d3d313bb243aac1f58515b54f19162083 c8770d20c7feaf8a5f3f72ae6a65dd5c4f3037bd M	settings
:040000 040000 0227feac495c8a0b5d87586af1f80da4b6b7a925 f5db78095e050919e853e4383364fef2347bb375 M	tests
```

**Comment by LukasReschke** [comment]
Broken with https://github.com/owncloud/core/pull/21336

**Comment by LukasReschke** [comment]
Stack trace:
```
Type: OC\DatabaseException
Code: 0
Message: An exception occurred while executing 'SELECT "uid", "displayname" FROM "oc_users" WHERE LOWER("uid") = LOWER(?)': SQLSTATE[HY000]: General error: 1 no such table: oc_users
File: /Users/lukasreschke/Documents/Programming/master/lib/private/db.php
Line: 70

Trace
#0 /Users/lukasreschke/Documents/Programming/master/lib/private/user/database.php(210): OC_DB::prepare('SELECT `uid`, `...')
#1 /Users/lukasreschke/Documents/Programming/master/lib/private/user/database.php(258): OC_User_Database->loadUser('admin')
#2 /Users/lukasreschke/Documents/Programming/master/lib/private/user/manager.php(133): OC_User_Database->userExists('admin')
#3 /Users/lukasreschke/Documents/Programming/master/lib/private/user/manager.php(162): OC\User\Manager->get('admin')
#4 /Users/lukasreschke/Documents/Programming/master/lib/private/user/manager.php(272): OC\User\Manager->userExists('admin')
#5 /Users/lukasreschke/Documents/Programming/master/lib/private/setup.php(350): OC\User\Manager->createUser('admin', 'admin')
#6 /Users/lukasreschke/Documents/Programming/master/core/setup/controller.php(64): OC\Setup->install(Array)
#7 /Users/lukasreschke/Documents/Programming/master/lib/base.php(830): OC\Core\Setup\Controller->run(Array)
#8 /Users/lukasreschke/Documents/Programming/master/index.php(39): OC::handleRequest()
#9 {main}
```

**Comment by icewind1991** [comment]
No clue how that stack trace relates to certificate stuff...

**Comment by LukasReschke** [comment]
This is caused by https://github.com/owncloud/core/commit/c15cab7ed6bf2d3ce9009ca09c7c5f33b252860f#diff-532788c3725aedf2a48a1300573ed382R65 which is called in the setup routine.

**Comment by LukasReschke** [comment]
It calls `\OC\Security\CertificateManager::needsRebundling` which iniitiates the view before ownCloud is installed => :bomb:

**Comment by LukasReschke** [comment]
Patch: https://github.com/owncloud/core/pull/21671
