### ISSUE TITLE
File upload failed with Fatal error, OK on next try

### ISSUE THREAD

**Issue by Morganlej** [owncloud/core#21711]
Possibly two issues: 
A) file upload temporarily failed
B) error described as fatal in web interface, but not as fatal in log file
### Steps to reproduce
1. Clean install OC 8.2.2, with on PHP 7.0.0, MySQL 5.5 on Apache, Linux - at my internet provider Binero.se, using their autoinstallation magic OneClick installer. Note: shared hosting.
2. Using the webUI to register one user, and make initial folders
3. Use previously configured client (2.0.2, Linux 64 bit, Mageia rpm) to upload a couple hundred files - total 1,1 GB
   Only this one client is running, with the goal of uploading all data to share later with other users.
   ### Expected behaviour
   A) No Error or Fatal in log
   B) Same level (Fatal/warining etc) shown in web user interface and log
### Actual behaviour

A) One Fatal shown in web interface log on admin page, occured about halfway through initial sync on a file approx 120GB.  Later the file got automatically uploaded with no problem.  The internet provider have checked that they were not doing some maintenenance at that time, and the could not see high load or something unusual. 

B) Error got flagged as Fatal in web user interface, but not as Fatal in logfile
### Server configuration

**Operating system**: Linux
**Web server:** Apache
**Database:** MySQL 5.5
**PHP version:** 7.0.0
**ownCloud version:** 8.2.2
**Updated from an older ownCloud or fresh install:** Fresh. ( I think i managed to completely uninstall all traces of the old one before making a reinstall.) I have since reentered users with same credentials and the clients have all five reconnected and resynced properly without any change in clients setup.
**List of activated apps:** As default
**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocuajnitgjur',
  'passwordsalt' => '****',
  'secret' => '****',
  'trusted_domains' => 
  array (
    0 => 'tribun.eu',
    1 => 'www.tribun.eu',
  ),
  'datadirectory' => '/storage/content/68/153468/tribun.eu/public_html/owncloud/.ht9cfqtj9kgt2e.data',
  'overwrite.cli.url' => 'http://tribun.eu/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => '153468-owncloud-dz62036',
  'dbhost' => 'owncloud-dz62036-153468.mysql.binero.se',
  'dbtableprefix' => 'kugp_',
  'dbuser' => '153468_dz62036',
  'dbpassword' => '****',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'owncloud-auto',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'tribun.eu',
  'loglevel' => 2,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one: never seen...
#### The Fatal message shown in web iu

copied from owncloud admin page (Firefox), which also showed the time 2016-01-12T23:50:13+00:00

Fatal   webdav  Exception: {"Message":"HTTP\/1.1 423 \"SvartenFullsynk\/BOM\/ProjektLaptop T61p Peter\/Program\/a_i386.deb-chunking-2792735725-27-26\" is locked","Exception":"OC\Connector\Sabre\Exception\FileLocked","Code":0,"Trace":"#0 \/storage\/content\/68\/153468\/tribun.eu\/public_html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\Connector\Sabre\Directory->createFile('varicad2011-en_...', Resource id #287)\n#1 \/storage\/content\/68\/153468\/tribun.eu\/public_html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\DAV\Server->createFile('SvartenFullsynk...', Resource id #287, NULL)\n#2 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#3 \/storage\/content\/68\/153468\/tribun.eu\/public_html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/storage\/content\/68\/153468\/tribun.eu\/public_html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)\n#5 \/storage\/content\/68\/153468\/tribun.eu\/public_html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#6 \/storage\/content\/68\/153468\/tribun.eu\/public_html\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\DAV\Server->exec()\n#7 \/storage\/content\/68\/153468\/tribun.eu\/public_html\/owncloud\/remote.php(137): require_once('\/storage\/conten...')\n#8 {main}","File":"\/storage\/content\/68\/153468\/tribun.eu\/public_html\/owncloud\/lib\/private\/connector\/sabre\/directory.php","Line":121} 
#### ownCloud log (data/owncloud.log) - the relevant line

{"reqId":"90R7R2F5HIHMVxp2xZev","remoteAddr":"128.127.184.27","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 423 \\"SvartenFullsynk\\/BOM\\/ProjektLaptop T61p Peter\\/Program\\/varicad2011-en_1.09_i386.deb-chunking-2792735725-27-26\\" is locked\",\"Exception\":\"OC\\Connector\\Sabre\\Exception\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\/storage\\/content\\/68\\/153468\\/tribun.eu\\/public_html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('varicad2011-en_...', Resource id #287)\n#1 \\/storage\\/content\\/68\\/153468\\/tribun.eu\\/public_html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('SvartenFullsynk...', Resource id #287, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \\/storage\\/content\\/68\\/153468\\/tribun.eu\\/public_html\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \\/storage\\/content\\/68\\/153468\\/tribun.eu\\/public_html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \\/storage\\/content\\/68\\/153468\\/tribun.eu\\/public_html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \\/storage\\/content\\/68\\/153468\\/tribun.eu\\/public_html\\/owncloud\\/apps\\/files\\/appinfo\\/remote.php(56): Sabre\\DAV\\Server->exec()\n#7 \\/storage\\/content\\/68\\/153468\\/tribun.eu\\/public_html\\/owncloud\\/remote.php(137): require_once('\\/storage\\/conten...')\n#8 {main}\",\"File\":\"\\/storage\\/content\\/68\\/153468\\/tribun.eu\\/public_html\\/owncloud\\/lib\\/private\\/connector\\/sabre\\/directory.php\",\"Line\":121}","level":4,"time":"2016-01-12T23:50:13+00:00"}

**Comment by RealRancor** [comment]
> B) Error got flagged as Fatal in web user interface, but not as Fatal in logfile

The error is logged as fatal in the logfile:

``"level":4,``

This is matching the levels described here: https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/logging_configuration.html

**Comment by Morganlej** [comment]
Ah, thank you.
I see the description say "4: FATAL: The server stops."
It is unclear what "stops" mean, i only saw a short pause in upload speed, then it ran again.
Does that mean my ISP have some autostarting function for it, or do Owncloud restart by itself?

**Comment by RealRancor** [comment]
ownCloud itself is just a web application written in PHP so it can't "stop". I think the message/documentation is misleading here.

**Comment by PVince81** [comment]
@icewind1991 I think we should log 423 only as 0 debug, not 4 fatal, because those "errors" aren't really errors, they happen when files are busy/locked due to concurrent access.

**Comment by PVince81** [comment]
So the bug here is only that the message is logged with the wrong level.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/26181

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
