### ISSUE TITLE
[8.2.2] Quota does not work over Webdav

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#21746]
### Expected behavior
Once the quota is reached you can't upload more information.

### Actual behavior
Unlimited quota

### Steps to reproduce
1. Add a user with a X quota, e.g. = 10 MB
2. connect the user over Webdav
3. Upload everything what you want and you have unlimited quota.

### Server configuration
**Operating system**:
Tested in:
Ubuntu 
Centos
Redhat

**Web server:**
Tested in:
2.2
2.4

**Database:**
Tested in:
MariaDB
Galera with MySQL

**PHP version:**
Tested in:
5.4 
5.6

**ownCloud version:** (see ownCloud admin page)
Tested in 
7.0.10
8.2.2

### Client configuration
Webdav over Windows

**Operating system:**
Windows 8.1

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"CN5K/h6pPoh/GqX8jp9h","remoteAddr":"91.11.102.80","app":"webdav","message":"Exception: {"Message":"HTTP/1.1 507 Insufficient Storage","Exception":"Sabre\DAV\Exception\InsufficientStorage","Code":0,"Trace":"
n#0 [internal function]: OC\Connector\Sabre\QuotaPlugin->checkQuota('huge-images/DSC...', Object(OC\Connector\Sabre\File), Resource id #41, false)n#1 /var/www/html/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
n#2 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(1085): Sabre\Event\EventEmitter->emit('beforeWriteCont...', Array)
n#3 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(501): Sabre\DAV\Server->updateFile('huge-images/DSC...', Resource id #41, NULL)
n#4 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
n#5 /var/www/html/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
n#6 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)
n#7 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
n#8 /var/www/html/owncloud/apps/files/appinfo/remote.php(56): Sabre\DAV\Server->exec()
n#9 /var/www/html/owncloud/remote.php(137): require_once('/var/www/html/o...')
n#10 {main}\",\"File\":\"/var/www/html/owncloud/lib/private/connector/sabre/quotaplugin.php\",\"Line\":108}","level":4,"time":"2016-01-15T13:56:35+01:00","method":"PUT","url":"/remote.php/webdav/huge-images/DSC_2447%20-%20Copy.JPG"}
```

@MorrisJobke 

00004579

**Comment by cdamken** [comment]
I'm seeing that in 8.2.2 the files are 0 kb, I thinkin in 8.2.2 is solved
