### ISSUE TITLE
SQL Error during upgrade | PostgreSQL 9.2

### ISSUE THREAD

**Issue by Romelhun** [owncloud/core#21763]
Dear Community,

during upgrade from 8.1.4 to 8.1.5 I have got error (see error description at the end).

### Steps to reproduce
1. yum upgrade

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache 2

**Database:** PostgreSQL 9.2

**PHP version:**  5.4.16

**ownCloud version:** 8.1.5

**Updated from an older ownCloud or fresh install:** updated from older one (from 8.1.4)

**Signing status (ownCloud 9.0 and above):**

```
Internal server error
```

**List of activated apps:**

```
Enabled:
 - activity: 2.0.2
 - contacts: 0.4.0.1
 - documents: 0.10.2
 - files: 1.1.10
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.3
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - music: 0.3.8
 - provisioning_api: 0.2
 - templateeditor: 0.1

```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'custom_id',
  'passwordsalt' => 'sensitive_hash',
  'secret' => 'secret_hash',
  'trusted_domains' =>
  array (
    0 => 'domain1',
    1 => 'domain2',
    2 => 'domain3',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://mysite.local/owncloud',
  'dbtype' => 'pgsql',
  'version' => '8.1.4.2',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'supersecretpass',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => true,
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 43.04

**Operating system:** Win 8.1

#### Web server error log
```
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE "oc_appconfig" ("                                                                                                                          appid" VARCHAR(32) DEFAULT '' NOT NULL, "configkey" VARCHAR(64) DEFAULT '' NOT NULL, "configvalue" TEXT DEFAULT NUL                                                                                                                          L, PRIMARY KEY("appid", "configkey"))':

SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "oc_appconfig" already exists
Update failed

```

#### Browser log
```
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE "oc_appconfig" ("                                                                                                                          appid" VARCHAR(32) DEFAULT '' NOT NULL, "configkey" VARCHAR(64) DEFAULT '' NOT NULL, "configvalue" TEXT DEFAULT NUL                                                                                                                          L, PRIMARY KEY("appid", "configkey"))':

SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "oc_appconfig" already exists
Update failed

```

**Comment by AceSlash** [comment]
No error with the following config:
- Debian 7.9
- apache httpd 2.2.22
- postgresql 9.3.10
- php 5.5.30
- Owncloud update from 8.1.4 to 8.1.5

```bash
# sudo -u www-data php occ app:list
Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.3
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - templateeditor: 0.1
 - user_ldap: 0.6.1.1
Disabled:
 - encryption
 - external
 - files_external
 - files_locking
 - provisioning_api
 - updater
 - user_external
 - user_webdavauth
```

**Comment by Romelhun** [comment]
Update - i hope it can help in the investigation:

If the table "oc_appconfig" exist, gives me the above described "Duplicate table" error.

If i drop the mentioned table gives me the following:

```bash
An unhandled exception has been thrown:
exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "oc_appconfig" does not exist
LINE 1: SELECT "configvalue", "configkey" FROM "oc_appconfig" WHERE ...
                                               ^' in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(830): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 /var/www/html/owncloud/lib/private/db/connection.php(130): Doctrine\DBAL\Connection->executeQuery('SELECT "configv...', Array, Array, NULL)
#3 /var/www/html/owncloud/lib/private/appconfig.php(95): OC\DB\Connection->executeQuery('SELECT `configv...', Array)
#4 /var/www/html/owncloud/lib/private/appconfig.php(156): OC\AppConfig->getAppValues('core')
#5 /var/www/html/owncloud/lib/private/allconfig.php(160): OC\AppConfig->getValue('core', 'encryption_enab...', 'no')
#6 /var/www/html/owncloud/lib/private/encryption/manager.php(78): OC\AllConfig->getAppValue('core', 'encryption_enab...', 'no')
#7 /var/www/html/owncloud/lib/base.php(750): OC\Encryption\Manager->isEnabled()
#8 /var/www/html/owncloud/lib/base.php(664): OC::registerEncryptionHooks()
#9 /var/www/html/owncloud/lib/base.php(1122): OC::init()
#10 /var/www/html/owncloud/console.php(41): require_once('/var/www/html/o...')
#11 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')
#12 {main}
```

**Comment by Romelhun** [comment]
Hello! 

At upgrade from 8.1.5 to 8.1.6 this issue still exist.

"Set log level to debug - current level: 'Info'
Checked database schema update
Checked database schema update for apps
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE "oc_appconfig" ("appid" VARCHAR(32) DEFAULT '' NOT NULL, "configkey" VARCHAR(64) DEFAULT '' NOT NULL, "configvalue" TEXT DEFAULT NULL, PRIMARY KEY("appid", "configkey"))':

SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "oc_appconfig" already exists
Update failed
Maintenance mode is kept active
Reset log level to 'Info'
"

I have to rebuild again the whole database from 0...

**Comment by PVince81** [comment]
@Romelhun how did you upgrade ?

You shouldn't delete tables, ownCloud should already detect that the table is there and should not try to recreate it.

Many try upgrading with the CLI `occ upgrade --skip-migration-test`.
Usually the migration test will duplicate the tables, but it should use another name. Maybe on your system it fails to use another name for some reason. (just guessing, if you try the above command it could help confirm it)

CC @nickvergessen

**Comment by Romelhun** [comment]
@PVince81 I followed described steps from documentation. 

I wouldn't risk again, so I moved from v8.x to v9.x with a full rebuild and it is now stable.
I upgraded once (on v9.x) and seems this bug is eliminated.

**Comment by nickvergessen** [comment]
So close this?
