### ISSUE TITLE
downloading a folder from Mac OS X produces an exception

### ISSUE THREAD

**Issue by vader2014** [owncloud/core#21866]
### Steps to reproduce
1. try to download a folder from a Mac OS X client
### Expected behaviour

produce and download a folder.tar file (windows and linux clients work without problems!)
### Actual behaviour

does not work
### Server configuration

**Operating system**: ubuntu wily

**Web server:** apache 2.4

**Database:** mariadb

**PHP version:**  7.0.2-4+deb.sury.org~wily+1 

**ownCloud version:** 8.2.2

**Updated from an older ownCloud or fresh install:** update from 8.2.1 and before!

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - conversations: 0.2.2
  - documents: 0.11.1
  - files: 1.2.0
  - files_antivirus: 0.8.0.0
  - files_external: 0.3.0
  - files_mv: 0.8.1
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - maps: 0.0.6
  - mozilla_sync: 1.4
  - notes: 0.9
  - notifications: 0.1.0
  - ocsms: 1.5.0
  - ocusagecharts: 3.4.4
  - search_lucene: 0.7.0
  - tasks: 0.8.1
Disabled:
  - allactivity
  - compress
  - dashboard
  - encryption
  - external
  - files_archive
  - files_clipboard
  - files_comments
  - files_embeddedvideo
  - files_epubviewer
  - files_share_watcher
  - files_videoviewer
  - grauphel
  - hls_streamplayer
  - html5_videoplayer
  - largefileupload
  - logreader
  - mail
  - music
  - passwordpolicy
  - polls
  - provisioning_api
  - sharelinks
  - storagecharts2
  - superlog
  - templateeditor
  - user_external
  - user_ldap
  - videos
  - weather
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "51a889bbe4727",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/data\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost:\/var\/run\/mysqld\/mysqld.sock",
        "dbtableprefix": "oc_",
        "version": "8.2.2.2",
        "installed": true,
        "forcessl": true,
        "filesystem_check_changes": 1,
        "asset-pipeline.enabled": "true",
        "overwritewebroot": "\/owncloud",
        "overwrite.cli.url": "\/owncloud",
        "updatechecker": false,
        "loglevel": 0,
        "logtimezone": "Europe\/Vienna",
        "log_authfailip": true,
        "log_rotate_size": 104857600,
        "knowledgebaseenabled": true,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": {
            "0": "OC\\Preview\\Image",
            "1": "OC\\Preview\\MP3",
            "2": "OC\\Preview\\TXT",
            "3": "OC\\Preview\\MarkDown",
            "4": "OC\\Preview\\Illustrator",
            "5": "OC\\Preview\\Postscript",
            "6": "OC\\Preview\\Photoshop",
            "7": "OC\\Preview\\TIFF",
            "8": "OC\\Preview\\Raw",
            "9": "OC\\Preview\\Movie",
            "14": "OC\\Preview\\PDF",
            "16": "OC\\Preview\\SVG"
        },
        "blacklisted_files": [
            "thumbnails-digikam.db",
            "digikam4.db",
            "digikam4.db-journal",
            "thumbnails-digikam.db-journal"
        ],
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/tmp\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "maintenance": false,
        "trusted_domains": [
            "dahoambeimir.no-ip.biz",
            "dahoambeimir.ddns.net",
            "192.168.1.252"
        ],
        "mail_smtpmode": "smtp",
        "mail_domain": "gmx.net",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "christoph.schoeller",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.gmx.net",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app.mail.server-side-cache.enabled": true,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9"

**Operating system:** Mac OS X
#### Web server error log

```
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:23 +0100] "POST /owncloud/index.php/apps/conversations/ajax/polling.php HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" MISS -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:26 +0100] "GET /owncloud/index.php/apps/files?dir=2016-dd-mm+-+xx+xxx HTTP/2" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" MISS -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:26 +0100] "GET /owncloud/index.php?redirect_url=%2Fowncloud%2Findex.php%2Fapps%2Ffiles%3Fdir%3D2016-dd-mm%2B-%2Bxx%2Bxxx HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" MISS -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:26 +0100] "GET /owncloud/assets/4c8b6e09711dbe82c788a1bd330110f9.css HTTP/2" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" - -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:26 +0100] "GET /owncloud/index.php/core/js/oc.js?v=e2b9d6c30f91ecfef09f014d766e2fd5 HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" MISS -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:26 +0100] "GET /owncloud/assets/bb28ac07d5a9502944ca5871ebc8c288.js HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" MISS 224717/771016 (29%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:26 +0100] "POST /owncloud/index.php/apps/conversations/ajax/polling.php HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" MISS -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:29 +0100] "POST /owncloud/index.php?redirect_url=%2Fowncloud%2Findex.php%2Fapps%2Ffiles%3Fdir%3D2016-mm-dd%2B-%2Bxx%2Bxxx HTTP/2" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" MISS -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:30 +0100] "GET /owncloud/index.php/apps/files?dir=2016-mm-dd%20-%20xx%20xxx HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" MISS -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:30 +0100] "GET /owncloud/assets/ec1e22daffef575577819a0ef8cf861a.css HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" MISS 26187/143204 (18%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:30 +0100] "GET /owncloud/index.php/core/js/oc.js?v=e2b9d6c30f91ecfef09f014d766e2fd5 HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" MISS -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:30 +0100] "GET /owncloud/assets/aa1658d0f00f006a2e4aa412e256f02b.js HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" MISS 419976/1483959 (28%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:31 +0100] "GET /owncloud/settings/img/personal.svg HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" - -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:31 +0100] "GET /owncloud/settings/img/help.svg HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" - -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:31 +0100] "GET /owncloud/apps2/conversations/img/conversations.svg HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" - -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:31 +0100] "GET /owncloud/apps2/notes/img/notes.svg HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" - -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:31 +0100] "GET /owncloud/apps2/maps/img/maps.svg HTTP/2" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" - -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:31 +0100] "GET /owncloud/apps2/tasks/img/tasks.svg HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" - -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:31 +0100] "GET /owncloud/apps/files/img/folder.svg HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" - -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:31 +0100] "GET /owncloud/apps/files/img/delete.svg HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" - -/- (-%)
xxx.xxx.xxx.xxx - - [22/Jan/2016:18:08:31 +0100] "GET /owncloud/core/img/actions/menu.svg HTTP/2" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" - -/- (-%)
```
#### ownCloud log (data/owncloud.log)

``````
{"reqId":"zraUO\/3KotLQZksWH4ko","remoteAddr":"xxx.xxx.xxx.xx","app":"no app in context","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Unable to send file 2016-mm-dd%20-%xxx.tar. HTML Headers have already been sent from \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/deepdiver1975\\\/tarstreamer\\\/src\\\/TarStreamer.php in line 30\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/streamer.php(57): ownCloud\\\\TarStreamer\\\\TarStreamer->sendHeaders('2016-mm-dd - xxx...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(118): OC\\\\Streamer->sendHeaders('2016-mm-dd - xxx...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(53): OC_Files::get('\\\/', '2016-dd-mm - xxx...', false)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#4 [internal function]: __lambda_func()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func('\\\\x00lambda_80', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/deepdiver1975\\\/tarstreamer\\\/src\\\/TarStreamer.php\",\"Line\":46}","level":3,"time":"2016-01-22T18:08:44+01:00"}```

#### Browser log
``````

n/a

```
```

**Comment by karlitschek** [comment]
@DeepDiver1975 can you have a look?

**Comment by DeepDiver1975** [comment]
````
Exception: {\"Exception\":\"Exception\",\"Message\":\"Unable to send file 2016-mm-dd%20-%xxx.tar. HTML Headers have already been sent from \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/deepdiver1975\\\/tarstreamer\\\/src\\\/TarStreamer.php in line 30\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/streamer.php(57): ownCloud\\\\TarStreamer\\\\TarStreamer->sendHeaders('2016-mm-dd - xxx...')\\n
#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(118): OC\\\\Streamer->sendHeaders('2016-mm-dd - xxx...')\\n
#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(53): OC_Files::get('\\\/', '2016-dd-mm - xxx...', false)\\n
#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n
#4 [internal function]: __lambda_func()\\n
#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func('\\\\x00lambda_80', Array)\\n
#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n
#7 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n
#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/deepdiver1975\\\/tarstreamer\\\/src\\\/TarStreamer.php\",\"Line\":46}","level":3,"time":"2016-01-22T18:08:44+01:00"}```

**Comment by DeepDiver1975** [comment]
So I assume that one of the apps is writing to the output buffer which is getting flushed in https://github.com/owncloud/TarStreamer/blob/master/src/TarStreamer.php#L30

@vader2014 May I ask you to disable all apps step by step to see which of them is causing the issue? THX

**Comment by vader2014** [comment]
i can ask but i doubt that the guy that had the problem (he downloaded from a windows system in the meanwhile) is really wanting to spend an hour debugging some issue of my cloud. unfortunately i have no Mac OS X client at hand myself.

**Comment by DeepDiver1975** [comment]
You should be capable to reproduce this using a linux machine as well. Mac and linux both get a tar archive delivered.

**Comment by vader2014** [comment]
with ubuntu wily/firefox 44 i get a zip file and this constellation is working.

**Comment by DeepDiver1975** [comment]
> with ubuntu wily/firefox 44 i get a zip file and this constellation is working.

hmmmm - let me reopen this one ....

**Comment by jospoortvliet** [comment]
I get a zip file at the moment, but interestingly, it is NOT a zip file... It is all files concatenated in one, recognized by my system as a PDF (but it only shows the first file, a PDF).

```Error 	PHP 	Cannot modify header information - headers already sent by (output started at /srv/www/htdocs/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /srv/www/htdocs/owncloud/3rdparty/sabre/http/lib/Sapi.php#58 ```
in my errorlog

Not sure if it is the same, I can create a separate issue if it is...

I have Contacts and Calendar and Documents disabled, still same thing. Now I only have activities, Files and the other basic stuff.

**Comment by jospoortvliet** [comment]
No, not PHP 7 related, I just installed 5 again and tested, same result.

**Comment by PVince81** [comment]
@jospoortvliet can you make a separate ticket ? A concatenated zip that actually contains a PDF sounds like a different issue.

**Comment by PVince81** [comment]
@jospoortvliet also please specify your OC version using the issue template :wink:

**Comment by PVince81** [comment]
@DeepDiver1975 have you been able to reproduce this ?

**Comment by DeepDiver1975** [comment]
not reproducible -> close -> please reopen if this happens again - THX

**Comment by kriztan** [comment]
I'm running OC 9.0.2 on CentOS and got this error message, too:
````
Exception: {"Exception":"Exception","Message":"Unable to send file 2016-07-12%20Krabbelgruppe.tar. HTML Headers have already been sent from \/var\/www\/virtual\/pixart\/html\/owncloud\/3rdparty\/deepdiver1975\/tarstreamer\/src\/TarStreamer.php in line 30","Code":0,"Trace":"#0 \/var\/www\/virtual\/pixart\/html\/owncloud\/lib\/private\/streamer.php(54): ownCloud\\TarStreamer\\TarStreamer->sendHeaders('2016-07-12 Krab...')\n#1 \/var\/www\/virtual\/pixart\/html\/owncloud\/lib\/private\/files.php(117): OC\\Streamer->sendHeaders('2016-07-12 Krab...')\n#2 \/var\/www\/virtual\/pixart\/html\/owncloud\/apps\/files_sharing\/lib\/controllers\/sharecontroller.php(490): OC_Files::get('\/Baby\/Fotos und...', '2016-07-12 Krab...', false)\n#3 [internal function]: OCA\\Files_Sharing\\Controllers\\ShareController->downloadShare('MKqas29P6tXvkrS', NULL, '\/', 'spxeqcbn3a')\n#4 \/var\/www\/virtual\/pixart\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/var\/www\/virtual\/pixart\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#6 \/var\/www\/virtual\/pixart\/html\/owncloud\/lib\/private\/appframework\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#7 \/var\/www\/virtual\/pixart\/html\/owncloud\/lib\/public\/appframework\/app.php(134): OC\\AppFramework\\App::main('ShareController', 'downloadShare', Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#8 \/var\/www\/virtual\/pixart\/html\/owncloud\/core\/routes.php(124): OCP\\AppFramework\\App->dispatch('ShareController', 'downloadShare')\n#9 [internal function]: OC\\Route\\Router->{closure}(Array)\n#10 \/var\/www\/virtual\/pixart\/html\/owncloud\/lib\/private\/route\/router.php(276): call_user_func(Object(Closure), Array)\n#11 \/var\/www\/virtual\/pixart\/html\/owncloud\/lib\/base.php(882): OC\\Route\\Router->match('\/s\/MKqas29P6tXv...')\n#12 \/var\/www\/virtual\/pixart\/html\/owncloud\/index.php(39): OC::handleRequest()\n#13 {main}","File":"\/var\/www\/virtual\/pixart\/html\/owncloud\/3rdparty\/deepdiver1975\/tarstreamer\/src\/TarStreamer.php","Line":46}

**Comment by PVince81** [comment]
@kriztan can you provide more details about your setup ?

**Comment by kriztan** [comment]
@PVince81 of course:
OC 9.0.2
OS: CentOS 6
PHP: 5.6.21
Apache: 2.2.15
Database: Mysql 5.1; Redis for cache
OC Apps activated: Collaborative tags; Comments; Deleted files; External user support; Federation; First Run Wizard; Gallery; Mail Template Editor; Notifications; PDF Viewer; Provisioning API; Share Files; Text Editor; Update notifications; Versions; Video Player; Calendar; Contacts; Notes; Direct Menu

Do you need further information?

**Comment by PVince81** [comment]
@kriztan thanks, I guess that should be enough.

It shows that it's not specific to PHP 7 and Apache 2.4 apparently.

**Comment by PVince81** [comment]
@felixheidecke can you have a look ? Thanks

**Comment by bpellowski** [comment]
Hi, I am experiencing this SAME EXACT issue here in our environment and our clients are not happy about it :( 

```
xception: {"Exception":"Exception","Message":"Unable to send file MU_Library.tar. HTML Headers have already been sent from \/var\/www\/html\/owncloud\/3rdparty\/deepdiver1975\/tarstreamer\/src\/TarStreamer.php in line 30","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/lib\/private\/Streamer.php(54): ownCloud\\TarStreamer\\TarStreamer->sendHeaders('MU_Library.tar')\n#1 \/var\/www\/html\/owncloud\/lib\/private\/legacy\/files.php(147): OC\\Streamer->sendHeaders('MU_Library')\n#2 \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/Controllers\/ShareController.php(503): OC_Files::get('\/Customers\/marq...', Array, Array)\n#3 [internal function]: OCA\\Files_Sharing\\Controllers\\ShareController->downloadShare('pzyfcv9TEcR3kch', 'MU_Library', '\/', 'g6i2gtjr3a2yczj...')\n#4 \/var\/www\/html\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/var\/www\/html\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#6 \/var\/www\/html\/owncloud\/lib\/private\/AppFramework\/App.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#7 \/var\/www\/html\/owncloud\/lib\/public\/AppFramework\/App.php(135): OC\\AppFramework\\App::main('ShareController', 'downloadShare', Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#8 \/var\/www\/html\/owncloud\/core\/routes.php(140): OCP\\AppFramework\\App->dispatch('ShareController', 'downloadShare')\n#9 [internal function]: OC\\Route\\Router->{closure}(Array)\n#10 \/var\/www\/html\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(Closure), Array)\n#11 \/var\/www\/html\/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/s\/pzyfcv9TEcR3...')\n#12 \/var\/www\/html\/owncloud\/index.php(39): OC::handleRequest()\n#13 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/deepdiver1975\/tarstreamer\/src\/TarStreamer.php","Line":46}
```

This only occurs when someone shares a link with a password and tries to open it on a Mac OSX system and download files. Any status on this?

**Comment by PVince81** [comment]
Share links, okay.

Can someone with a Mac try and reproduce this ?

@owncloud/qa

**Comment by michaelstingl** [comment]
I wasn't able to reproduce with oC 9.1.2 and Chrome 54 or Safari 10.0.1 on Mac OS 10.12.1.

**Comment by SergioBertolinSG** [comment]
> This only occurs when someone shares a link with a password and tries to open it on a Mac OSX system and download files.

Tested in oC 9.0.7 Mac OS 10.11 Safari 9.0. Working fine.

**Comment by PVince81** [comment]
Could be related to how the server is setup then

**Comment by bpellowski** [comment]
Could one of you email me at bpellowski@omniupdate.com and I can provide you a link to a folder on our customshare and a password with a test folder that you can try to download and report back if it fails? It very would could be an issue with the server config.

**Comment by bpellowski** [comment]
@PVince81 we managed to fix this problem on our end. The error was crying about line 30 in this file
`var/www/html/owncloud/3rdparty/deepdiver1975/tarstreamer/src/TarStreamer.php`
```
while (ob_get_level() > 0){
//line30                    ob_end_flush();
                                ob_end_clean();
                        }
```
Line 30 was ob_end_flush() so we commented it out and put ob_end_clean(); and now people can download files from owncloud on a mac

You guys have any idea why changing it from flush to clean works now?

**Comment by PVince81** [comment]
@iljan @phisch @jvillafanez ^

**Comment by vader2014** [comment]
the issue still persists with oc 10.0.2.1; the proposed fix from @bpellowski worked for me!

**Comment by jvillafanez** [comment]
@DeepDiver1975 since the proposed solution is in the tarstreamer repo, could you have a look?

**Comment by BakaRei** [comment]
I Guess There might be other string output before the tar file header.

**Comment by felixheidecke** [comment]
@PVince81 not sure how I can help?

**Comment by PVince81** [comment]
I seem to remember that we released a new version of tarstreamer, so this is likely fixed in 10.0.4 ?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by Terrox** [comment]
Ran into this today.
Smb share.
Same situation as bpellowski
Nextcloud 12.0.5

**Comment by PVince81** [comment]
@Terrox this is the ownCloud bug tracker. please report in https://github.com/nextcloud instead
