### ISSUE TITLE
Activity on sidebar is not able to load and leads to more problems.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21884]
### Steps to reproduce

1. Install current 9.0 master.
2. Upload several files in root folder.
3. Open sidebar of a file.

### Expected behaviour
Activity is shown. You are able to change to other file. You are able to keep using the server.

### Actual behaviour
Activity keeps loading, you can't change the view to another user. In some cases data is lost.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"g0voCZKGdZ\/PSD87ocCB","remoteAddr":"HIDED_IP","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/test_sample_message.eml not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(913): OC\\\\Files\\\\View->getOwner('\\\/test_sample_me...')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(86): OC\\\\Files\\\\Filesystem::getOwner('\\\/test_sample_me...')\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(139): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::resolveDetails(Array)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(28): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::logSinglePathAction('Create', Array)\\n#4 [internal function]: OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::create(Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/hook.php(104): call_user_func(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(535): OC_Hook::emit('OC_Filesystem', 'create', Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(586): OC\\\\Files\\\\View->emit_file_hooks_pre(false, '\\\/test_sample_me...', true)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(949): OC\\\\Files\\\\View->file_put_contents('\\\/test_sample_me...', Resource id #33)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(739): OC\\\\Files\\\\View->fromTmpFile('\\\/tmp\\\/phpRmTXzH', '\\\/test_sample_me...')\\n#10 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/upload.php(193): OC\\\\Files\\\\Filesystem::fromTmpFile('\\\/tmp\\\/phpRmTXzH', '\\\/test_sample_me...')\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#12 [internal function]: __lambda_func(Array)\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func('?lambda_128', Array)\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/base.php(864): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#15 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1582}","level":3,"time":"2016-01-25T11:45:18+00:00"}
{"reqId":"EZiC67dDB8AJd2HyEcLB","remoteAddr":"82.159.139.58","app":"PHP","message":"Argument 3 passed to OCA\\DAV\\SystemTag\\SystemTagsRelationsCollection::__construct() must be an instance of OCA\\DAV\\SystemTag\\IUserSession, instance of OC\\User\\Session given, called in \/opt\/owncloud\/apps\/dav\/lib\/rootcollection.php on line 72 and defined at \/opt\/owncloud\/apps\/dav\/lib\/systemtag\/systemtagsrelationscollection.php#43","level":3,"time":"2016-01-25T11:45:37+00:00"}
{"reqId":"EZiC67dDB8AJd2HyEcLB","remoteAddr":"HIDED_IP","app":"PHP","message":"Argument 4 passed to OCA\\DAV\\SystemTag\\SystemTagsRelationsCollection::__construct() must be an instance of OCA\\DAV\\SystemTag\\IGroupManager, instance of OC\\Group\\Manager given, called in \/opt\/owncloud\/apps\/dav\/lib\/rootcollection.php on line 72 and defined at \/opt\/owncloud\/apps\/dav\/lib\/systemtag\/systemtagsrelationscollection.php#45","level":3,"time":"2016-01-25T11:45:37+00:00"}
```

### Client configuration

**browser**
Chrome

**Comment by nickvergessen** [comment]
Should be fixed with https://github.com/owncloud/activity/pull/452 if you want to confirm

**Comment by SergioBertolinSG** [comment]
This is failing again with folders, I am only seeing it on enterprise theme.

@nickvergessen should I open a new issue on enterprise or reopen this one?

**Comment by nickvergessen** [comment]
Will have a look tomorrow

**Comment by nickvergessen** [comment]
Works for me in sidebar and activity app itself, with both themes default and enterprise.
However we fixed a bug yesterday that would cause non-firefox browsers to sometimes fail.
So maybe you can retry it: https://github.com/owncloud/activity/pull/456

**Comment by SergioBertolinSG** [comment]
@nickvergessen Yes, today is working fine, thanks.
