### ISSUE TITLE
owncloud 8.2 sync problem

### ISSUE THREAD

**Issue by casper000** [owncloud/core#21886]
hello developers and everyone

I have some strange issue during syncronization. in my situation lets take an example. user A owns all data on server. one of the folder hosts thousands of files. that folder is shared with user B C and D. they edit thos files during their working period. often in owncloud.log i see error that entry is duplicated and was error with database INSERT function. I have read on forums different posts. When I open client program whith user A on seperate computer, user A owns all data of server sometimes cannot download some files with same error. if I delete all data of user A while application is closed and reopen it, it start to download all data but i receive same error again on different files. I am not php expert but how it is possible data to be duplicated after each new download with different files when only user who is online at that period is user A. So if somebody had similar situation please let me know how you solved problem. 

I have attached config files and errors.  Error which is related to this issue and other errors also. Please if it is not bug help to solve problem. I don't really want to loose data.
### Server configuration

**Operating system**: 3.10.0-327.el7.x86_64

**Web server:** Apache/2.4.6

**Database:**15.1 Distrib 5.5.44-MariaDB

**PHP version:**PHP 5.6.16 (cli)

**ownCloud version:**8.2

**Updated from an older ownCloud or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:** 

```
Enabled:
  - activity: 2.1.3
  - announcementcenter: 1.0.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - gallery: 14.2.0
  - notifications: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_texteditor
  - files_videoviewer
  - firstrunwizard
  - provisioning_api
  - templateeditor
  - updater
  - user_external
  - user_ldap
```

**The content of config/config.php:**

``` php
<?php
$CONFIG = array (
  'instanceid' => 'XXXX',
  'passwordsalt' => 'XXXX',
  'secret' => 'XXXX',
  'trusted_domains' => 
  array (
    0 => 'host.mydomain.com',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'https://10.0.0.3/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'XXXX',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXX',
  'dbpassword' => 'XXXX',
  'logtimezone' => 'XXXX',
  'installed' => true,
  'has_internet_connection' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'XXXX',
  'mail_domain' => 'gmail.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'XXXX',
  'mail_smtppassword' => 'XXXX',
  'loglevel' => 2,
  'logdateformat' => 'Y-m-d_H:i:s',
  'knowledgebaseenabled' => false,
  'enable_avatars' => true,
  'allow_user_to_change_display_name' => false,
  'updatechecker' => false,
  'enable_previews' => true,
  'preview_max_x' => 1024,
  'preview_max_y' => 768,
  'preview_max_scale_factor' => 1,
  'preview_max_filesize_image' => 5,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
  ),
  'default_language' => 'en',
  'asset-pipeline.enabled' => true,
  'trashbin_retention_obligation' => 'auto',
  'activity_expire_days' => 365,
  'check_for_working_webdav' => true,
  'maintenance' => false,
  'singleuser' => false,
  'filesystem_check_changes' => 0,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser: Google Chrome**

**Operating system: Windiows 7 x86/x64**
#### ownCloud log (data/owncloud.log)

1.)

``` json
{"reqId":"VqMluqJqAMbqOji5-EIl5QAAAAk","remoteAddr":"10.0.0.114","app":"webdav","message":"Exception: 
{\"Message\":\"HTTP\\\/1.1 400 expected filesize 5242880 got 3981312\",\"Exception\":\"Sabre\\\\DAV\\\\Exception
\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\
/sabre\\\/file.php(101): OC\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #273)\\n#1 \\\/var\\\
/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(115): OC\\\\Connector\\\\Sabre
\\\\File->put(Resource id #273)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\
/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('IMG_2464.JPG-ch...', Resource id #273)\\n#3 \\\
/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\
Server->createFile('Tako\\\/Tako\\\/chven...', Resource id #273, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\
CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html
\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\
\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\
\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib
\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\
HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\
DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/html\\\
/o...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",
\"Line\":361}","level":4,"time":"2016-01-23_11:03:24"}
```

2.)

``` json
{"reqId":"VqMlfIQthxSvSXVqzxwHMAAAAAU","remoteAddr":"10.0.0.114","app":"PHP","message":
"fopen(\/var\/www\/html\/owncloud\/data\/user\/files\/user\/folder\/folder 2\/\
u10e1\u10d0\u10d1\u10d0\u10df\u10dd \u10e1\u10d0\u10ec\u10e7\u10dd\u10d1\u10e8\u10d8 \u10e2\
u10d5\u10d8\u10e0\u10d7\u10d8\u10e1 \u10db\u10d8\u10e6\u10d4\u10d1\u10d8\u10e1\u10d0\u10e1 \
u10e2\u10e0\u10d0\u10dc\u10e1\u10de\u10dd\u10e0\u10e2\u10d8\u10e0\u10d4\u10d1\u10d8\u10e1 \
u10de\u10d8\u10e0\u10dd\u10d1\u10d4\u10d1\u10d8\u10e1 \u10e8\u10d4\u10db\u10dd\u10ec\u10db\
u10d4\u10d1\u10d8\u10e1 \u10d8\u10dc\u10e1\u10e2\u10e0\u10e3\u10e5\u10ea\u10d8\u10d0.doc.ocTransferId1950661897.part): 
failed to open stream: File name too long at \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/local.php#247","
level":3,"time":"2016-01-23_11:02:20"}
```

3.) 

``` json
{"reqId":"VqKJhsMJfPc8BL80aJB5IQAAAAc","remoteAddr":"10.0.0.7","app":"webdav","message":
"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"DATA\\\/DATA\\\/\\u10d4\\u10e5\\u10d5\\u10d7\\
u10d8\\u10db\\u10d8\\u10e8\\u10d5\\u10d8\\u10da\\u10d8 \\u10d7\\u10d4\\u10dc\\u10d2\\u10d8\\
u10d6\\u10d8.xlsx\\\" is locked\",\"Exception\":\"OC\\\\Connector\\\\Sabre\\\\Exception\\\\
FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre
\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #273)
\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): 
Sabre\\\\DAV\\\\Server->updateFile('DATA\\\/DATA\\\/\\\\xE1\\\\x83\\\\x94\\\\xE1\\\\x83\\\\xA5\\\\xE1...',
Resource id #273, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), 
Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\
/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\
/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit(
'method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\
/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), 
Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\
/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\
/remote.php(137): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\
/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":164}","
level":4,"time":"2016-01-22_23:56:54"}
```

4.)

``` json
{"reqId":"VqNRV-8mrlhUzHzORU6BOQAAAAs","remoteAddr":"10.0.0.7","app":"core","message":
"Could not get application: cURL error 28: Connection timed out after 5001 milliseconds",
"level":3,"time":"2016-01-23_14:09:42"}
```

5.)

``` json
{"reqId":"VqNUSwmRo2LtoFbS8SEkRwAAAAo","remoteAddr":"10.0.0.7","app":"PHP","message":
"Cannot modify header information - headers already sent by (output started at 
\/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at 
\/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,
"time":"2016-01-23_14:22:03"}
```

Thank you

**Comment by PVince81** [comment]
2) is very strange. So many unicode characters and "File name too long" ?

I see you're using Mysql, if you have file names with emojis in it or UTF-16 characters it will not work properly with Mysql. See https://github.com/owncloud/core/pull/17978

**Comment by casper000** [comment]
you are right some users were using emojis but problem was with UTF-8 characters. file name was approximately 15 characters long but I don't really remember length. after renaming file it start to upload on server.

**Comment by gecube** [comment]
Good day!

I have similar problem with russian file names. Files with short names are OK, but when we try to download file with 136 symbols or more, we get the same error.

**Comment by PVince81** [comment]
@DeepDiver1975 @VicDeo @butonic might get even worse with 4-byte support ?

**Comment by butonic** [comment]
http://serverfault.com/questions/120397/max-length-of-url-257-characters-for-mod-rewrite might help. @casper000 @gecube can you try moving the htacces content to the apache vhost config?

**Comment by PVince81** [comment]
Closing due to lack of feedback, also sounds like to be an env issue so central is the place to ask env questions.
