### ISSUE TITLE
Broken installer page

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#21897]
```
{"reqId":"lWtTLe9pt7YxcMNT1pO7","remoteAddr":"192.168.56.1","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",\"Message\":\"Failed to connect to the database: An exception occurred while executing 'PRAGMA journal_mode = WAL':\\n\\nSQLSTATE[HY000]: General error: 10 disk I\\\/O error\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(973): OC\\\\DB\\\\Connection->connect()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(204): Doctrine\\\\DBAL\\\\Connection->executeUpdate('PRAGMA read_unc...', Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(621): OC\\\\DB\\\\Connection->executeUpdate('PRAGMA read_unc...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(136): Doctrine\\\\DBAL\\\\Connection->setTransactionIsolation(2)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DriverManager.php(172): OC\\\\DB\\\\Connection->__construct(Array, Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connectionfactory.php(118): Doctrine\\\\DBAL\\\\DriverManager::getConnection(Array, Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/server.php(360): OC\\\\DB\\\\ConnectionFactory->getConnection('sqlite', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(102): Pimple\\\\Container->offsetGet('DatabaseConnect...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/servercontainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('DatabaseConnect...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/server.php(870): OC\\\\ServerContainer->query('DatabaseConnect...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/server.php(260): OC\\\\Server->getDatabaseConnection()\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(102): Pimple\\\\Container->offsetGet('AppConfig')\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/servercontainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('AppConfig')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/server.php(809): OC\\\\ServerContainer->query('AppConfig')\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(1029): OC\\\\Server->getAppConfig()\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(156): OC_App::getAppVersions()\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(226): OC\\\\TemplateLayout->__construct('error', '')\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(121): OC_Template->fetchPage()\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(350): OC\\\\Template\\\\Base->printPage()\\n#21 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC_Template::printExceptionErrorPage(Object(Doctrine\\\\DBAL\\\\DBALException))\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php\",\"Line\":53}","level":3,"time":"2016-01-25T17:41:33+00:00"}
{"reqId":"A8u+6mir5\/dX6UEIdIKH","remoteAddr":"192.168.56.1","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#187","level":3,"time":"2016-01-25T17:44:40+00:00"}
```

Git bisect revealed this as the commit that killed it for me: https://github.com/owncloud/core/commit/ae7c49f93c7de919d0859abb5c75695c194dd2ff

Using git master, not installed, just trying to load up the installer page and I get a 500 internal sever error with the above two logs in the owncloud.log.

PHP 5.6.17-3

@icewind1991

**Comment by tomneedham** [comment]
See also https://github.com/owncloud/core/pull/21424

**Comment by tomneedham** [comment]
Hmm so actually this is just the template not loading. Before the referenced commit the template loads but the error in question still appears which sounds like an issue with my setup which broke since last week..... Not sure if this is still bug worthy? Just the exception is not caught like it was before.

**Comment by tomneedham** [comment]
More digging. With this implemented, it seems to try and access a sqlite db before I get the chance to select mysql (mariadb).

**Comment by MorrisJobke** [comment]
Same here ae7c49f93c7de919d0859abb5c75695c194dd2ff broke it.

@icewind1991  ;)

**Comment by MorrisJobke** [comment]
I guess it never worked but the exception was simply ignored :see_no_evil: https://github.com/owncloud/core/pull/21424/files#diff-4828f39ae4935d14b1dc1a6ffe323725L1037

Now the exception is visible -.- I will check if I can fix this.

**Comment by MorrisJobke** [comment]
Ah ... the install page isn't tested anymore.

@SergioBertolinSG @DeepDiver1975 Would it make sense to test a setup (SQLite) with an integration test?
