### ISSUE TITLE
[Files External] Cannot create a file in a webDav mountpoint

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21927]
### Steps to reproduce

1. As admin user configure a webDav mountpoint  and save it
2. Using webUI, try to create a new text file in the webDav mountpoint

### Expected behaviour

The file is created in the webDav mountpoint.

### Actual behaviour

The file cannot be created. An error message is shown.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-26T04:16:42+00:00 4c9e328211a3f986cd2c6186e4c1de755d5c940b

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; webDAV.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

![screen shot 2016-01-26 at 17 13 41](https://cloud.githubusercontent.com/assets/10596560/12587052/0e3575c0-c453-11e5-90ad-9b516fe74751.png)

```
{"reqId":"tDwyPhZAvwor0OzTiAfF","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined index: mtime at \/opt\/owncloud\/lib\/private\/files\/fileinfo.php#186","level":3,"time":"2016-01-26T16:13:28+00:00"}
{"reqId":"tDwyPhZAvwor0OzTiAfF","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined index: etag at \/opt\/owncloud\/lib\/private\/files\/fileinfo.php#171","level":3,"time":"2016-01-26T16:13:28+00:00"}
{"reqId":"tDwyPhZAvwor0OzTiAfF","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined index: mimetype at \/opt\/owncloud\/lib\/private\/files\/fileinfo.php#146","level":3,"time":"2016-01-26T16:13:28+00:00"}
{"reqId":"tDwyPhZAvwor0OzTiAfF","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined index: permissions at \/opt\/owncloud\/lib\/private\/files\/fileinfo.php#200","level":3,"time":"2016-01-26T16:13:28+00:00"}
{"reqId":"tDwyPhZAvwor0OzTiAfF","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined index: permissions at \/opt\/owncloud\/lib\/private\/files\/fileinfo.php#200","level":3,"time":"2016-01-26T16:13:28+00:00"}
{"reqId":"tDwyPhZAvwor0OzTiAfF","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined index: permissions at \/opt\/owncloud\/lib\/private\/files\/fileinfo.php#200","level":3,"time":"2016-01-26T16:13:28+00:00"}
{"reqId":"tDwyPhZAvwor0OzTiAfF","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined index: permissions at \/opt\/owncloud\/lib\/private\/files\/fileinfo.php#200","level":3,"time":"2016-01-26T16:13:28+00:00"}
{"reqId":"z4t557U5Vz3lo6GeGRZV","remoteAddr":"172.17.0.1","app":"PHP","message":"fopen(\/opt\/owncloud\/data\/admin\/files\/createIT.txt.ocTransferId1414473440.part): failed to open stream: No such file or directory at \/opt\/owncloud\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2016-01-26T16:13:28+00:00"}
{"reqId":"z4t557U5Vz3lo6GeGRZV","remoteAddr":"172.17.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(53): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/opt\\\/owncloud\\\/remote.php(137): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#7 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":287}","level":4,"time":"2016-01-26T16:13:28+00:00"}
{"reqId":"Cr2XqVwLJuOW\/BafslP8","remoteAddr":"172.17.0.1","app":"PHP","message":"fopen(\/opt\/owncloud\/data\/admin\/files\/createIT.txt.ocTransferId1414473440.part): failed to open stream: No such file or directory at \/opt\/owncloud\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2016-01-26T16:13:29+00:00"}
{"reqId":"Cr2XqVwLJuOW\/BafslP8","remoteAddr":"172.17.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(53): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/opt\\\/owncloud\\\/remote.php(137): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#7 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":287}","level":4,"time":"2016-01-26T16:13:29+00:00"}
```

**Comment by PVince81** [comment]
@icewind1991 @Xenopathic weird stuff

**Comment by PVince81** [comment]
@davitol what Webdav server are you connecting to ?

Works for me.

My steps:
1. `docker pull morrisjobke/webdav`
1. `docker run -d -e USERNAME=test -e PASSWORD=test -p 8888:80 morrisjobke/webdav`
1. Configure Webdav external storage to point to "localhost:8888/webdav" with username/password test/test
1. Upload a file there in the web UI
1. Create a file there with the text editor

Both work.

**Comment by PVince81** [comment]
@davitol told me that he connected to another OC.

Strangely, using the "Webdav" backend when connecting to another OC doesn't let you upload files (error). But using the "ownCloud" backend works.

The reason is because the "Webdav backend" allows storing part files on the remote storage.
The "ownCloud"  backend doesn't use part files because the back-ownCloud already has these.

To make this work, we'd need to either:
1) Make ownCloud detect that the Webdav backend is actually ownCloud, and switch to OC mode (disable part files)
or
2) Make it possible to PROPFIND part files from the remote ownCloud (this has potential for major breakage).

@icewind1991 @Xenopathic what do you think ?

I suppose solution 1) is easier

**Comment by PVince81** [comment]
@davitol I don't think this is a regression though, the logic with the part files exists since OC 8.0 or OC 8.1 I believe

**Comment by icewind1991** [comment]
From what I can tell this issue was introduced with 8.2 with dav locking work

fix is here https://github.com/owncloud/core/pull/22331
