### ISSUE TITLE
Warning appears to every user not allowed to connect to external storage using login credentials and no red row.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21951]
### Steps to reproduce
1. Enable external storage and mount a SFTP folder using login credentials store in session (probably happening with other storages and saving it in DB as well) available for all users.
2. Using a user which doesn't have access to that SFTP go to files view.
### Expected behaviour

SFTP folder doesn't appear.

Or SFTP folder appears with a red row indicating that login credentials are not met.
### Actual behaviour

A warning message appears saying that a mounted point cannot be used. Saying that a row with a red background appears, which doesn't happen. 
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes SFTP.

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"UuHo5r9D7FmT+hE9MTLM","remoteAddr":"82.159.139.58","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Login failed\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/sftp.php(154): OC\\\\Files\\\\Storage\\\\SFTP->getConnection()\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(232): OC\\\\Files\\\\Storage\\\\SFTP->test(false)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(244): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/userglobalstoragescontroller.php(112): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#4 [internal function]: OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController->show(1)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController), 'show')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController), 'show')\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('UserGlobalStora...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/base.php(864): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#12 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/sftp.php\",\"Line\":139}","level":3,"time":"2016-01-27T13:31:12+00:00"}
{"reqId":"cSirEUyKnHPT3jRzpFPi","remoteAddr":"82.159.139.58","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Login failed\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/sftp.php(154): OC\\\\Files\\\\Storage\\\\SFTP->getConnection()\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(232): OC\\\\Files\\\\Storage\\\\SFTP->test(false)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(244): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(290): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#4 [internal function]: OCA\\\\Files_External\\\\Controller\\\\StoragesController->show(1)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/base.php(864): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#12 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/sftp.php\",\"Line\":139}","level":3,"time":"2016-01-27T13:31:16+00:00"}
{"reqId":"Lk+apoH+T3+ZGl0GlL29","remoteAddr":"82.159.139.58","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Login failed\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/sftp.php(154): OC\\\\Files\\\\Storage\\\\SFTP->getConnection()\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(232): OC\\\\Files\\\\Storage\\\\SFTP->test(false)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(244): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/globalstoragescontroller.php(174): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#4 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update(1, 'SFTP', 'sftp', 'password::sessi...', Array, Array, Array, Array, 100)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/base.php(864): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#12 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/sftp.php\",\"Line\":139}","level":3,"time":"2016-01-27T13:31:18+00:00"}
```
### Client configuration

**browser**
Chrome

**Comment by SergioBertolinSG** [comment]
What is the expected behaviour here? I am not sure. 

Showing a warning and a red row to each user who doesn't match the credentials or removing the warning?

**Comment by Xenopathic** [comment]
We should definitely at least be listing the storage with a red row, as ultimately it's a misconfiguration by the admin.

**Comment by PVince81** [comment]
Is this still an issue with v9.0.3RC1 or v9.1.0beta2 ?

**Comment by SergioBertolinSG** [comment]
This is working fine in 9.1 (current master), but another problem has appeared: https://github.com/owncloud/core/issues/25272

**Comment by SergioBertolinSG** [comment]
This is still happening right after login. After going to other page and going back to the files view, the SFTP folder with the red background appears.

**Comment by PVince81** [comment]
Does the fix for https://github.com/owncloud/core/issues/25272 help ?

**Comment by SergioBertolinSG** [comment]
No, I think it is not related. I just thought it was fixed because that row is only missing after the login, but later it appears.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
