### ISSUE TITLE
cron.php runs infinity

### ISSUE THREAD

**Issue by colttt** [owncloud/core#22044]
as mentored her: https://github.com/owncloud/core/issues/21800 i enable cron via system's cron, BUT it never ends :(
at the moment it runs more than an hour:
```
www-data 28384 71.8  2.1 745696 262840 ?       R    10:15  69:50 /usr/bin/php -f /var/www/owncloud/cron.php
```
in the owncloud.log there is only this:
```
{"reqId":"fETO1q6hGQ6Xv6UmkThw","remoteAddr":"xx.197.xx.165","app":"files","message":" Backends provided no user object for bbe46a5a-7e23-1030-81c1-a1198bbfea79","level":3,"time":"2016-02-01T10:55:09+00:00"}
{"reqId":"fETO1q6hGQ6Xv6UmkThw","remoteAddr":"xx.197.xx.165","app":"files_sharing","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Backends provided no user object for bbe46a5a-7e23-1030-81c1-a1198bbfea79\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/cache.php(69): OC\\\\Files\\\\Filesystem::initMountPoints('bbe46a5a-7e23-1...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/cache.php(107): OC\\\\Files\\\\Cache\\\\Shared_Cache->getSourceCache('')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1234): OC\\\\Files\\\\Cache\\\\Shared_Cache->get('')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/serverfactory.php(83): OC\\\\Files\\\\View->getFileInfo('')\\n#4 [internal function]: OC\\\\Connector\\\\Sabre\\\\ServerFactory->OC\\\\Connector\\\\Sabre\\\\{closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php\",\"Line\":385}","level":3,"time":"2016-02-01T10:55:09+00:00"}
{"reqId":"agJHJNtVt0sJPMOU8Qtk","remoteAddr":"yy.16.bb.16","app":"files","message":" Backends provided no user object for 48570626-d444-1034-941a-4d48e44b87b8","level":3,"time":"2016-02-01T10:55:09+00:00"}
{"reqId":"agJHJNtVt0sJPMOU8Qtk","remoteAddr":"yy.16.bb.16","app":"files_sharing","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Backends provided no user object for 48570626-d444-1034-941a-4d48e44b87b8\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/cache.php(69): OC\\\\Files\\\\Filesystem::initMountPoints('48570626-d444-1...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/cache.php(107): OC\\\\Files\\\\Cache\\\\Shared_Cache->getSourceCache('')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1234): OC\\\\Files\\\\Cache\\\\Shared_Cache->get('')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/serverfactory.php(83): OC\\\\Files\\\\View->getFileInfo('')\\n#4 [internal function]: OC\\\\Connector\\\\Sabre\\\\ServerFactory->OC\\\\Connector\\\\Sabre\\\\{closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php\",\"Line\":385}","level":3,"time":"2016-02-01T10:55:09+00:00"}
{"reqId":"8yVdyDRkz55sWQlGc2hU","remoteAddr":"yy.16.bb.16","app":"files","message":" Backends provided no user object for 48570626-d444-1034-941a-4d48e44b87b8","level":3,"time":"2016-02-01T10:55:10+00:00"}
{"reqId":"8yVdyDRkz55sWQlGc2hU","remoteAddr":"yy.16.bb.16","app":"files_sharing","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Backends provided no user object for 48570626-d444-1034-941a-4d48e44b87b8\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/cache.php(69): OC\\\\Files\\\\Filesystem::initMountPoints('48570626-d444-1...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/cache.php(107): OC\\\\Files\\\\Cache\\\\Shared_Cache->getSourceCache('')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1234): OC\\\\Files\\\\Cache\\\\Shared_Cache->get('')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/serverfactory.php(83): OC\\\\Files\\\\View->getFileInfo('')\\n#4 [internal function]: OC\\\\Connector\\\\Sabre\\\\ServerFactory->OC\\\\Connector\\\\Sabre\\\\{closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php\",\"Line\":385}","level":3,"time":"2016-02-01T10:55:10+00:00"}
```
If I use AJAX-cron it works perfectly

I use Ubuntu LTS 14.04
MySQL with Apache 
owncloud version 8.2.1
PHP 5.5.9-1ubuntu4.14

**Comment by nickvergessen** [comment]
Can you try whether https://github.com/owncloud/core/pull/22006 solves your issue?
I think it is the same issue you are seeing.
Also it would be cool, if you can monitor the number of entries in the oc_jobs table before applying the patch and then maybe hourly to see if the number still grows, remains or shrinks.

**Comment by colttt** [comment]
Hello it was not a problem by cron.php. There was a lot of jobs in oc_jobs created by AJAX-cron.
![owncloud_jobs](https://cloud.githubusercontent.com/assets/10084871/12808564/06813bae-cb18-11e5-8914-5d6b959e90c4.png)

i think it can be closed?!
