### ISSUE TITLE
Moving a file to a shared nested folder structure as recipient using SSL and webdav fails.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22082]
### Steps to reproduce

Using ssl do:
~~1. Enable encryption.~~
2. admin user has a nested structure /folder/subfolder/subsubfolder.
3. admin user shares folder with user1.
4. Connect with cadaver using ssl with user1.
5. Move or copy a file from / to folder/subfolder/subsubfolder which was shared from admin.

### Expected behaviour
File is moved or copied.

### Actual behaviour
It returns forbidden and later 500.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.8","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
Yes.

**Logs**

```
{"reqId":"DpCDjCqK8UHaeTHjuFb4","remoteAddr":"HIDED_IP","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/folder-windows-credentials-32x32 (2) (1).svg.d1454433027 not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(913): OC\\\\Files\\\\View->getOwner('\\\/folder-windows...')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(90): OC\\\\Files\\\\Filesystem::getOwner('\\\/folder-windows...')\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(121): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::resolveDetails(Array)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(49): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::logOldNewPathAction('Restore', Array)\\n#4 [internal function]: OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::trash_post_restore(Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/hook.php(104): call_user_func(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/util.php(479): OC_Hook::emit('\\\\OCA\\\\Files_Tras...', 'post_restore', Array)\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(383): OCP\\\\Util::emitHook('\\\\OCA\\\\Files_Tras...', 'post_restore', Array)\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/files_trashbin\\\/ajax\\\/undelete.php(72): OCA\\\\Files_Trashbin\\\\Trashbin::restore('\\\/\\\/folder-window...', 'folder-windows-...', '1454433027')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#10 [internal function]: __lambda_func(Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func('?lambda_181', Array)\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/base.php(865): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_tra...')\\n#13 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1582}","level":3,"time":"2016-02-02T17:10:33+00:00"}
{"reqId":"pkPrJqi6mqorzYT5aGBR","remoteAddr":"HIDED_IP","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/FICHEROABORRAR.svg.d1454433096 not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(913): OC\\\\Files\\\\View->getOwner('\\\/FICHEROABORRAR...')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(90): OC\\\\Files\\\\Filesystem::getOwner('\\\/FICHEROABORRAR...')\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(121): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::resolveDetails(Array)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(49): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::logOldNewPathAction('Restore', Array)\\n#4 [internal function]: OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::trash_post_restore(Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/hook.php(104): call_user_func(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/util.php(479): OC_Hook::emit('\\\\OCA\\\\Files_Tras...', 'post_restore', Array)\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(383): OCP\\\\Util::emitHook('\\\\OCA\\\\Files_Tras...', 'post_restore', Array)\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/files_trashbin\\\/ajax\\\/undelete.php(72): OCA\\\\Files_Trashbin\\\\Trashbin::restore('\\\/\\\/FICHEROABORRA...', 'FICHEROABORRAR....', '1454433096')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#10 [internal function]: __lambda_func(Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func('?lambda_323', Array)\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/base.php(865): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_tra...')\\n#13 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1582}","level":3,"time":"2016-02-02T17:11:42+00:00"}
{"reqId":"mDtYCgTBtuEyulFw9lLt","remoteAddr":"HIDED_IP","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/FOLDER\\\/ANOTHER\\\/SUBFOLDER\\\/MOMO.JPG not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(913): OC\\\\Files\\\\View->getOwner('\\\/FOLDER\\\/ANOTHER...')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(86): OC\\\\Files\\\\Filesystem::getOwner('\\\/FOLDER\\\/ANOTHER...')\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(139): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::resolveDetails(Array)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(28): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::logSinglePathAction('Create', Array)\\n#4 [internal function]: OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::create(Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/hook.php(104): call_user_func(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(535): OC_Hook::emit('OC_Filesystem', 'create', Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(815): OC\\\\Files\\\\View->emit_file_hooks_pre(false, '\\\/FOLDER\\\/ANOTHER...', true)\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php(283): OC\\\\Files\\\\View->copy('MOMO.JPG', 'FOLDER\\\/ANOTHER\\\/...')\\n#9 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(684): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->copy('MOMO.JPG', 'FOLDER\\\/ANOTHER\\\/...')\\n#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpCopy(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:COPY', Array)\\n#13 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(53): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/opt\\\/owncloud\\\/remote.php(137): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#16 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1582}","level":3,"time":"2016-02-02T17:21:46+00:00"}
{"reqId":"mDtYCgTBtuEyulFw9lLt","remoteAddr":"HIDED_IP","app":"PHP","message":"Call to a member function getData() on a non-object at \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php#134","level":3,"time":"2016-02-02T17:21:46+00:00"}
{"reqId":"+YxlkTDpQSQ1+FUYP0iN","remoteAddr":"HIDED_IP","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/\\\/COSAS.txt not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(913): OC\\\\Files\\\\View->getOwner('\\\/\\\/COSAS.txt')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(86): OC\\\\Files\\\\Filesystem::getOwner('\\\/\\\/COSAS.txt')\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(139): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::resolveDetails(Array)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(28): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::logSinglePathAction('Create', Array)\\n#4 [internal function]: OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::create(Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/hook.php(104): call_user_func(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(239): OC_Hook::emit('OC_Filesystem', 'create', Array)\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(164): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->emitPreHooks(false)\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/directory.php(134): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #46)\\n#9 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('COSAS.txt', Resource id #46)\\n#10 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('COSAS.txt', Resource id #46, NULL)\\n#11 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#13 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#14 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(53): Sabre\\\\DAV\\\\Server->exec()\\n#16 \\\/opt\\\/owncloud\\\/remote.php(137): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#17 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1582}","level":3,"time":"2016-02-02T17:23:13+00:00"}
{"reqId":"dMeBvm4HXvhANNr8AQU2","remoteAddr":"HIDED_IP","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/FOLDER\\\/ANOTHER\\\/SUBFOLDER\\\/COSAS.txt not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(913): OC\\\\Files\\\\View->getOwner('\\\/FOLDER\\\/ANOTHER...')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(86): OC\\\\Files\\\\Filesystem::getOwner('\\\/FOLDER\\\/ANOTHER...')\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(139): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::resolveDetails(Array)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/admin_audit\\\/hooks\\\/handlers.php(28): OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::logSinglePathAction('Create', Array)\\n#4 [internal function]: OCA\\\\Admin_Audit\\\\Hooks\\\\Handlers::create(Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/hook.php(104): call_user_func(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(535): OC_Hook::emit('OC_Filesystem', 'create', Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(815): OC\\\\Files\\\\View->emit_file_hooks_pre(false, '\\\/FOLDER\\\/ANOTHER...', true)\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php(283): OC\\\\Files\\\\View->copy('COSAS.txt', 'FOLDER\\\/ANOTHER\\\/...')\\n#9 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(684): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->copy('COSAS.txt', 'FOLDER\\\/ANOTHER\\\/...')\\n#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpCopy(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:COPY', Array)\\n#13 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(53): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/opt\\\/owncloud\\\/remote.php(137): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#16 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1582}","level":3,"time":"2016-02-02T17:23:44+00:00"}
{"reqId":"dMeBvm4HXvhANNr8AQU2","remoteAddr":"HIDED_IP","app":"PHP","message":"Undefined index: size at \/opt\/owncloud\/lib\/private\/files\/cache\/scanner.php#201","level":3,"time":"2016-02-02T17:23:44+00:00"}
{"reqId":"dMeBvm4HXvhANNr8AQU2","remoteAddr":"HIDED_IP","app":"PHP","message":"Undefined index: size at \/opt\/owncloud\/lib\/private\/files\/cache\/scanner.php#201","level":3,"time":"2016-02-02T17:23:44+00:00"}
{"reqId":"dMeBvm4HXvhANNr8AQU2","remoteAddr":"HIDED_IP","app":"PHP","message":"Call to a member function getData() on a non-object at \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php#134","level":3,"time":"2016-02-02T17:23:44+00:00"}
```

### Client configuration

**browser**
Chrome

cadaver as webdav client.

**Comment by PVince81** [comment]
@SergioBertolinSG can you describe your nested structure with terms like "user X shared file A with user Y" ?

**Comment by PVince81** [comment]
@schiesbn @rullzer please have a look, encryption and/or sharing bug

**Comment by SergioBertolinSG** [comment]
Updated steps.

**Comment by rullzer** [comment]
I'm a bit confused about the ticket. Are you using the encryption app or just ssl to connect?

**Comment by SergioBertolinSG** [comment]
@rullzer both.

**Comment by rullzer** [comment]
Ah ok. @SergioBertolinSG does it all work if you do not have the encryption app enabled?

**Comment by SergioBertolinSG** [comment]
@rullzer just tested. It fails too without encryption app.  It returns 403 forbidden.

**Comment by rullzer** [comment]
This all works fine over here.
With which permissions did you share?

**Comment by SergioBertolinSG** [comment]
All permissions.

**Comment by SergioBertolinSG** [comment]
After discussed with @rullzer  the problem is the leading '/'

Using mv to a folder starting without '/' or starting with './' It worked correctly.

Since leading '/' is not expected to work, I'm closing this.
