### ISSUE TITLE
Exception in log about addressbookadapter.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22248]
### Observed behaviour

Exception happens always when setting up a server and it is logged.

```
{"reqId":"agCyTio0jEU7XJ0CP6Oa","remoteAddr":"::1","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(55): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(118): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/installer.php(622): include('\\\/opt\\\/owncloud\\\/a...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/installer.php(573): OC_Installer::includeAppScript('\\\/opt\\\/owncloud\\\/a...')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/installer.php(547): OC_Installer::installShippedApp('dav')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/opt\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/base.php(822): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":53}","level":3,"time":"2016-02-09T11:26:24+00:00"}
```

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.10","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.
**Are you using encryption:** 
No

**Logs**

```
{"reqId":"agCyTio0jEU7XJ0CP6Oa","remoteAddr":"::1","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(55): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(118): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/installer.php(622): include('\\\/opt\\\/owncloud\\\/a...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/installer.php(573): OC_Installer::includeAppScript('\\\/opt\\\/owncloud\\\/a...')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/installer.php(547): OC_Installer::installShippedApp('dav')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/opt\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/base.php(822): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":53}","level":3,"time":"2016-02-09T11:26:24+00:00"}
```

**Comment by SergioBertolinSG** [comment]
cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
this is not really necessary - agreed - will silence this beast

**Comment by DeepDiver1975** [comment]
no longer valid - migration code will be removed in 9.1 - #23976 remove
