### ISSUE TITLE
Upload of a picture to owncloud using "Easy Share Action" crashes

### ISSUE THREAD

**Issue by smico** [owncloud/core#22335]
Android ownCloud beta app (Version 20160120)

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start service com.owncloud.android.files.services.FileUploader@2fccfd1 with Intent { cmp=com.owncloud.android.beta/com.owncloud.android.files.services.FileUploader (has extras) }: java.lang.IllegalArgumentException: Trying to create a OCFile with a non valid remote path:
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3071)
        at android.app.ActivityThread.-wrap17(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5466)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalArgumentException: Trying to create a OCFile with a non valid remote path:
        at com.owncloud.android.datamodel.OCFile.<init>(OCFile.java:103)
        at com.owncloud.android.files.services.FileUploader.obtainNewOCFileToUpload(FileUploader.java:771)
        at com.owncloud.android.files.services.FileUploader.onStartCommand(FileUploader.java:286)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3054)
        ... 8 more

************ DEVICE INFORMATION ***********
Brand: google
Device: mako
Model: Nexus 4
Id: MMB29U
Product: occam

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 35b26cafd4

**Comment by RealRancor** [comment]
Hi,

the issue tracker of the android app is located here:

https://github.com/owncloud/android/issues

Please re-open there using the issue template provided here:

https://github.com/owncloud/android/blob/master/CONTRIBUTING.md#guidelines
