### ISSUE TITLE
Apache error: AH00161 MaxRequestWorkers

### ISSUE THREAD

**Issue by sHaggYcaT** [owncloud/core#22439]
I have simillar, but not same problem with: https://github.com/owncloud/core/issues/14175
But It doesn't apcu cache! 

After I restart apache, I see in error_log 

`[Tue Feb 16 17:32:26.951302 2016] [mpm_prefork:error] [pid 108] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting
`
And owncloud some times works extremely slow, or just not working (https timeout error). 

I've tryed to install apcu, removed it, installed redis for caching or for file locking - it doesn't affect. Same situation. Some times owncloud works fine, and some times it freezing, and has extremely performance degradation (in monitoring I see it 5-6 times per day, but probably it can be 20-30 times for some of minutes)

On old server:
owncloud-8.0.3, php 5.6, no any cache systems, sqlite(!) all works fine.

On new system:
owncloud-server-8.2.2-1.1.noarch, php-5.2 (centos default system package), maria-db, no cache or reddis cache I have this problem.

P.S. Of cource, I've tryed to up MaxRequestWorkers(to 10000), serverlimit, etc in apache, it also does not affect.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version :wink:

**Comment by sHaggYcaT** [comment]
### Steps to reproduce 

and 
### Expected behaviour
Tell us what should happen

To reproduce, I've updated from owncloud-8.0.3, php 5.6, no any cache systems, sqlite(!) // worked fine///
to new server: centos 7. Old server is one, new server deployed by Ansible. For me, situation reproduce. Old server works fine, new server reproduce performance problems :( If I reinstall owncloud by same playbook, I see problem again.
In playbook I use default (distribution) packages. Also, I use official (owncloud) rpm package.


### Server configuration
**Operating system**:

Old: Gentoo
New: centos 7

**Web server:**
Apache/2.2.29 - old 
2.4.6 - new

**Database:**
Old: sqlite
New: MariaDB 5.5.44.2

**PHP version:**
Old: 5.6.9-pl0-gentoo
New  5.4.16

**ownCloud version:** (see ownCloud admin page)
old: 8.0.3.4
new: 8.2.2.2 (latest rpm)

**Updated from an older ownCloud or fresh install:**
yes, updated

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```


```
Fatal	webdav	Exception: {"Message":"HTTP\/1.1 503 RedisException: read error on connection","Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Code":0,"Trace":"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/html\/owncloud\/remote.php(68): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/html\/owncloud\/remote.php(140): handleException(Object(RedisException))\n#6 {main}","File":"\/var\/www\/html\/owncloud\/remote.php","Line":66}	2016-02-16T19:02:10+03:00
Fatal	webdav	Exception: {"Message":"HTTP\/1.1 423 \"Shared\/2-marketing\/Pres PWT clients\/20160217 Complimentary information for La Redoute.pptx-chunking-1406753479-2-1\" is locked","Exception":"OC\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('20160217 Compli...', Resource id #278)\n#1 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('Shared\/2-market...', Resource id #278, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/html\/owncloud\/remote.php(137): require_once('\/var\/www\/html\/o...')\n#8 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/connector\/sabre\/directory.php","Line":121}	2016-02-16T18:48:21+03:00
Fatal	webdav	Exception: {"Message":"HTTP\/1.1 423 \"Shared\/2-marketing\/Pres PWT clients\/20160217 Complimentary information for La Redoute.pptx-chunking-1406753479-2-1\" is locked","Exception":"OC\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('20160217 Compli...', Resource id #278)\n#1 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('Shared\/2-market...', Resource id #278, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/html\/owncloud\/remote.php(137): require_once('\/var\/www\/html\/o...')\n#8 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/connector\/sabre\/directory.php","Line":121}

```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
Disabled:
  - encryption
  - external
  - files_external
  - notifications
  - provisioning_api
  - templateeditor
  - user_external
  - user_ldap


**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

If disabled any caching or filelocking problem not solving.

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "instanceid": "oc34mv0dgr64",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/QQ.XX.YY.ZZ\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "trusted_domains": [
            "YYY.XXX.TLD"
        ],
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "enable_avatars": false
    }
}



**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:**
Not depend of browser

**Operating system:**
Windows, Linux, Mac has a same problems


### Logs
#### Web server error log

```
[Tue Feb 16 18:48:09.901391 2016] [suexec:notice] [pid 9802] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Feb 16 18:48:09.902325 2016] [ssl:warn] [pid 9802] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Tue Feb 16 18:48:09.919845 2016] [auth_digest:notice] [pid 9802] AH01757: generating secret for digest authentication ...
[Tue Feb 16 18:48:09.920289 2016] [lbmethod_heartbeat:notice] [pid 9802] AH02282: No slotmem from mod_heartmonitor
[Tue Feb 16 18:48:09.921180 2016] [ssl:warn] [pid 9802] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Tue Feb 16 18:48:09.938595 2016] [mpm_prefork:notice] [pid 9802] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16 configured -- resuming normal operations
[Tue Feb 16 18:48:09.938617 2016] [core:notice] [pid 9802] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Tue Feb 16 18:48:16.952881 2016] [mpm_prefork:error] [pid 9802] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting
[Tue Feb 16 19:26:39.166987 2016] [authz_core:error] [pid 13929] [client 5.39.121.43:58351] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
```


#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

see above

#### Browser log
Here is firebug:
http://s15.postimg.org/i1n2oe93v/owncloud.png

**Comment by blizzz** [comment]
Did you update from  8.0.3.4 directly to 8.2.2.2? Since, this is not supported, you must not skip 8.1 inbetween.  This might, or might not, contribute to those issues, because next to the update there are several other changes (distribution → possibly other software versions, maybe configuration adjustments needed), that could play into it.

**Comment by PVince81** [comment]
Closing due to lack of activity.
Feel free to reopen if you're still having this issue with v9.0.1.
