### ISSUE TITLE
Cannot overwrite fed shared file as recipient

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22433]
### Steps

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create or upload a file "test.txt"
1. Share "test.txt" using **federated sharing** with "user2"
1. Login as "user2" in the web UI
1. Accept the share
1. Login as "user2" with a Webdav client (ex: cadaver)
1. Overwrite "test.txt" with a Webdav PUT

### Expected result
File was overwritten

### Actual result
```
{"reqId":"azA1FALbgExzc7qYzNUZ","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getQuota() on null at \/srv\/www\/htdocs\/owncloud\/apps\/files_trashbin\/lib\/trashbin.php#567","level":3,"time":"2016-02-16T14:27:32+00:00","method":"PUT","url":"\/owncloud\/public.php\/webdav\/"}
{"reqId":"7KrI6mSOZP2pDIVVp2Lv","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Server error response [url] http:\\\/\\\/localhost\\\/owncloud\\\/public.php\\\/webdav\\\/ [status code] 500 [reason phrase] Internal Server Error\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(GuzzleHttp\\\\Exception\\\\ServerException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1070): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #290)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('test.txt', Resource id #290, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(137): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#9 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":535}","level":4,"time":"2016-02-16T14:27:32+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/test.txt"}
```

### Versions
OC 9.0 git master 46b39c3465e2db9ba26b23d8d0dfca6cc670aaea

Please have a look @schiesbn @rullzer, seems related somehow to the trashbin ?

**Comment by PVince81** [comment]
Works fine in v8.2.2.

Let's bisect this quickly.

**Comment by PVince81** [comment]
Broken by @blizzz https://github.com/owncloud/core/pull/22252

**Comment by PVince81** [comment]
Let me take care of this as this is blocking me.

**Comment by PVince81** [comment]
Actually @blizzz didn't break it, but his code revealed another more obscure bug.

PR is here: https://github.com/owncloud/core/pull/22435
