### ISSUE TITLE
Locking issue when deleting multiple files/folders from S3 storage

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22465]
### Steps to reproduce
1. Setup a S3 external storage as "/s3" (amazon in my case)
2. Create a folder "/s3/test"
3. Create/upload a non-empty file as "/s3/test.txt"
4. In the web UI, select both "test" and "test.txt" in the "s3" folder
5. Click "Delete" in the selection bar to delete both
### Expected behaviour

Both deleted
### Actual behaviour

"test.txt" is gone but "test" receives 423 Locked.
### Server configuration

**Operating system**: openSUSE Tumbleweed

**Web server:** Apache 2.4

**Database:** Mariadb

**PHP version:** 5.6.17

**ownCloud version:** (see ownCloud admin page) 9.0 git master 7b0f83b616246c5274b551ab46b923b0989c464e
#### ownCloud log (data/owncloud.log)

```
{"reqId":"rTXFguCrcHDbTu+5j6l\/","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"s3\\\/test\\\" is locked\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('s3\\\/test')\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(137): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#8 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/directory.php\",\"Line\":279}","level":4,"time":"2016-02-17T12:12:05+00:00","method":"DELETE","url":"\/owncloud\/remote.php\/webdav\/s3\/test"}
```
### Network console

Every time I test this, I can see that "test.txt" is deleted faster even though the request for "test" was sent earlier. You can see this in the timeline column.

![s3-locking](https://cloud.githubusercontent.com/assets/277525/13109217/4b8cb222-d578-11e5-897b-2ff1fd772244.png)

The locking logic shouldn't allow this to happen because there is no situation where deleting one entry would lock the other one. So this is either a bug in locking itself, or something in S3 (maybe the slowness ?) triggers some kind of side effect ?

@icewind1991

**Comment by PVince81** [comment]
I forgot to mention: after this situation, deleting the "test" entry works fine.
So this only happens when deleting both at the same time.

**Comment by PVince81** [comment]
Downgrading to medium, it happens rarely and I couldn't reproduce it.
Also the workaround is to attempt to delete them again, then it works.

**Comment by PVince81** [comment]
didn't see this happen any more -> close
