### ISSUE TITLE
help !! pyOwncloud installation 

### ISSUE THREAD

**Issue by yavama** [owncloud/core#22517]
i've just installed pyOwncloud anc i've got this when runing oclient -h

root-DEBUG: ProgressBar not available
csync.csynclib.pre-DEBUG: Found ocsync at /usr/lib/libocsync.so.0
Traceback (most recent call last):
File "/usr/local/bin/oclient", line 9, in 
load_entry_point('pyOwnCloud==0.4.pre', 'console_scripts', 'oclient')()
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
return ep.load()
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
entry = import(self.module_name, globals(),globals(), ['name'])
File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csync.py", line 29, in 
import csynclib
File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csynclib/init.py", line 1, in 
from . import pre
File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csynclib/pre.py", line 25, in 
csynclib = getCSync()
File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csynclib/pre.py", line 12, in getCSync
return CDLL('/usr/lib/libocsync.so.0')
File "/usr/lib/python2.7/ctypes/init.py", line 365, in init
self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libocsync.so.0: wrong ELF class: ELFCLASS64

what's wrong with ? any help plz ?

**Comment by DeepDiver1975** [comment]
please talk to the maintainer of this tool - https://github.com/csawyerYumaed/pyOwnCloud
