### ISSUE TITLE
Locked folder after cancel an upload inside this folder

### ISSUE THREAD

**Issue by nasli** [owncloud/core#22524]
### Steps to reproduce
1.Upload a file with Android mobile client to a folder A
2.Cancel the upload
3.Upload again the file
4.After the file has been uploaded successfully, try to delete the folder

### Steps to reproduce2
1.Upload a file with Android mobile client to a folder A
2.Wifi connection lost, upload stopped
3.Wifi available 
4.After the file has been uploaded successfully, try to delete the folder
### Expected behaviour
Folder is removed from server

### Actual behaviour
We received 423 error when try to remove folder from server

### Server configuration
{"installed":true,"maintenance":false,"version":"9.0.0.12","versionstring":"9.0.0 beta 2","edition":""}

**Comment by MorrisJobke** [comment]
cc @PVince81 @icewind1991

**Comment by PVince81** [comment]
This is probably a stray lock. When the client aborts the connection, the PHP code might still be waiting for data, or it will fail with "Expected filesize XYZ got ABC". In such case I think we should already discard the lock.

**Comment by PVince81** [comment]
Hmm, I just discovered this: http://php.net/manual/en/features.connection-handling.php

Maybe there's a way to detect aborted uploads and shut down in a clean way, given that the PHP process doesn't get killed directly (like PHP-FPM does, I believe).

The workaround is to wait for the stray lock to expire. But I understand that it's not convenient for a user who just aborted an upload and wants to retry to wait such a long time.

@icewind1991 do you have any experience with http://php.net/manual/en/features.connection-handling.php ? Any thoughts ?

**Comment by PVince81** [comment]
On my system I see that `ignore_user_abort` defaults to `On` which means that if an upload is aborted, the PHP process will continue running. However if it's trying to read further data from `php://input`, it will likely wait forever and time out.

**Comment by PVince81** [comment]
Seems we can manually set http://php.net/manual/en/function.ignore-user-abort.php to true from the PHP code. So it might be possible to force PHP code continuation in case of aborted upload.
Then in the subsequent code, use `connection_aborted()` to detect an abort and clean up gracefully / exist the input stream loop (if not already).

**Comment by PVince81** [comment]
@nasli are you able to find out what the value is of "ignore_user_abort" in the test server php.ini ?

**Comment by nasli** [comment]
Thanks @PVince81 , we are checking it @SergioBertolinSG

**Comment by SergioBertolinSG** [comment]
@PVince81 hi, with both ignore_user_abort=On commented and uncommented the folders are getting locked.

Android
```
{"reqId":"xoKCEnDZZoLd0MgCoIiL","remoteAddr":"HIDDEN_IP","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"AndroidTest4On\\\" is locked\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#1 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('AndroidTest4On')\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#5 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/opt\\\/owncloud\\\/remote.php(164): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":283,\"User\":\"noe\"}","level":4,"time":"2016-10-10T09:15:30+00:00","method":"DELETE","url":"\/remote.php\/webdav\/AndroidTest4On\/","user":"noe"}
```

iOS
```
{"reqId":"5YjEyHF0aT7tMDPC3L2s","remoteAddr":"HIDDEN_IP","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"iostest2on\\\" is locked\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#1 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('iostest2on')\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#5 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/opt\\\/owncloud\\\/remote.php(164): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":283,\"User\":\"noe\"}","level":4,"time":"2016-10-10T09:20:23+00:00","method":"DELETE","url":"\/remote.php\/webdav\/iostest2on\/","user":"noe"}
```

When uploading files other exceptions appeared:
```
{"reqId":"KbmSnE0b5cyjI58AdgsP","remoteAddr":"HIDDEN_IP","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 1024000 got 870792\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #120)\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(136): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #120)\\n#2 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('20160826_112323...', Resource id #120)\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('AndroidTest4On\\\/...', Resource id #120, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/opt\\\/owncloud\\\/remote.php(164): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#10 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":404,\"User\":\"noe\"}","level":4,"time":"2016-10-10T09:19:38+00:00","method":"PUT","url":"\/remote.php\/webdav\/AndroidTest4On\/20160826_112323.mp4-chunking-3663-29-5","user":"noe"}
```

**Comment by nasli** [comment]
I added in the description of the issue new steps to reproduce2, that is while uploading file wifi connection lost, I can not reproduce with first steps stopping manually the file.

**Comment by PVince81** [comment]
Yeah, so likely the problem with the network disconnection is https://github.com/owncloud/core/issues/17254
