### ISSUE TITLE
Using occ files:scan option causes unhandled exception

### ISSUE THREAD

**Issue by Aesculapius** [owncloud/core#22624]
### Steps to reproduce
1. Manually add a file back to the storage filesystem, eg. from a backup
2. To have it appear in Owncloud, we need a rescan of that part
3. So in an ssh window, the following command was given: 

sudo -u www-data php occ files:scan --path="/Laurens/files/3. Werk/5. NVKI/Met bestuur gedeelde mappen/Bestuur/Missie en Visie"

which is the exact folder that new files were added to.

### Expected behaviour
A message telling that a rescan was done succesfully telling me how many files were added or removed from the database.

### Actual behaviour
The following error occurs and no new files have been added to the database:

An unhandled exception has been thrown:
OCP\AppFramework\QueryException: Could not resolve OCP\IDb! Class can not be instantiated in /var/www_ssl/lib/private/appframework/utility/simplecontainer.php:87
Stack trace:
#0 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(106): OC\AppFramework\Utility\SimpleContainer->resolve('OCP\\IDb')
#1 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(66): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDb')
#2 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(85): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#3 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(106): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Mail\\Db\\Mai...')
#4 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(66): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Mail\\Db\\Mai...')
#5 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(85): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#6 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(106): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Mail\\Servic...')
#7 /var/www_ssl/apps/mail/appinfo/register_command.php(14): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Mail\\Servic...')
#8 /var/www_ssl/lib/private/console/application.php(68): require('/var/www_ssl/ap...')
#9 /var/www_ssl/console.php(68): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www_ssl/occ(11): require_once('/var/www_ssl/co...')
#11 {main}

### Server configuration
**Operating system**: Ubuntu 14.04.3 LTS

**Web server:** Apache 2.4.7

**Database:** MySql 5.0.12

**PHP version:** 7.0.1-4

**ownCloud version:** 8.2.2

**Updated from an older ownCloud or fresh install:** updated
```
**List of activated apps:** 

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

Hmz, same error: 
An unhandled exception has been thrown:
OCP\AppFramework\QueryException: Could not resolve OCP\IDb! Class can not be instantiated in /var/www_ssl/lib/private/appframework/utility/simplecontainer.php:87
Stack trace:
#0 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(106): OC\AppFramework\Utility\SimpleContainer->resolve('OCP\\IDb')
#1 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(66): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDb')
#2 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(85): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#3 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(106): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Mail\\Db\\Mai...')
#4 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(66): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Mail\\Db\\Mai...')
#5 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(85): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#6 /var/www_ssl/lib/private/appframework/utility/simplecontainer.php(106): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Mail\\Servic...')
#7 /var/www_ssl/apps/mail/appinfo/register_command.php(14): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Mail\\Servic...')
#8 /var/www_ssl/lib/private/console/application.php(68): require('/var/www_ssl/ap...')
#9 /var/www_ssl/console.php(68): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www_ssl/occ(11): require_once('/var/www_ssl/co...')
#11 {main}

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome-latest

**Operating system:** Windows 7

#### ownCloud log (data/owncloud.log)
```
This is the last bit of it:

{"reqId":"nv2AVWGxhzx87uREmriC","remoteAddr":"131.174.244.74","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-02-23T11:01:38+00:00"}
{"reqId":"nv2AVWGxhzx87uREmriC","remoteAddr":"131.174.244.74","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-02-23T11:01:38+00:00"}
{"reqId":"nv2AVWGxhzx87uREmriC","remoteAddr":"131.174.244.74","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-02-23T11:01:38+00:00"}
{"reqId":"nv2AVWGxhzx87uREmriC","remoteAddr":"131.174.244.74","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-02-23T11:01:38+00:00"}
{"reqId":"nv2AVWGxhzx87uREmriC","remoteAddr":"131.174.244.74","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-02-23T11:01:38+00:00"}
{"reqId":"nv2AVWGxhzx87uREmriC","remoteAddr":"131.174.244.74","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php#65","level":3,"time":"2016-02-23T11:01:38+00:00"}
{"reqId":"nv2AVWGxhzx87uREmriC","remoteAddr":"131.174.244.74","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-02-23T11:01:38+00:00"}
{"reqId":"p7OWLUWo52BCend6Hdy2","remoteAddr":"131.174.244.74","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 501 There was no handler found for this \\\"LOCK\\\" method\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotImplemented\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www_ssl\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www_ssl\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#2 \\\/var\\\/www_ssl\\\/remote.php(137): require_once('\\\/var\\\/www_ssl\\\/ap...')\\n#3 {main}\",\"File\":\"\\\/var\\\/www_ssl\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":472}","level":4,"time":"2016-02-23T11:01:40+00:00"}
{"reqId":"IZ6uhnQzz1d44XNWyQcb","remoteAddr":"131.174.244.74","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 501 There was no handler found for this \\\"LOCK\\\" method\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotImplemented\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www_ssl\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www_ssl\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#2 \\\/var\\\/www_ssl\\\/remote.php(137): require_once('\\\/var\\\/www_ssl\\\/ap...')\\n#3 {main}\",\"File\":\"\\\/var\\\/www_ssl\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":472}","level":4,"time":"2016-02-23T11:01:59+00:00"}
{"reqId":"SMcl9rPG5nMu9daaUeJZ","remoteAddr":"82.170.246.171","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-02-23T12:07:19+00:00"}
{"reqId":"QraRFAw6jP8KAvQvxgyc","remoteAddr":"131.174.244.65","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-02-23T16:59:10+00:00"}
{"reqId":"AY9EY7FedE8J8wHRim3u","remoteAddr":"131.174.244.65","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-02-23T20:43:32+00:00"}
{"reqId":"azuoxpSXaOCtRejEdo2B","remoteAddr":"131.174.244.65","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www_ssl\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-02-23T20:43:46+00:00"}
{"reqId":"K9JvwTNYaqQT4ArWUKSo","remoteAddr":"109.232.42.33","app":"PHP","message":"filesize(): stat failed for \/yoda\/cloudstore\/data\/\/Sanne\/files_versions\/3. Werk\/5. NVKI\/Met bestuur gedeelde mappen\/Bestuur\/Missie en Visie\/Missie en Visie NVKI 2016.docx.v1455478367 at \/var\/www_ssl\/lib\/private\/files\/storage\/local.php#139","level":3,"time":"2016-02-24T12:23:07+00:00"}
{"reqId":"K9JvwTNYaqQT4ArWUKSo","remoteAddr":"109.232.42.33","app":"PHP","message":"fopen(\/yoda\/cloudstore\/data\/\/Sanne\/files_versions\/3. Werk\/5. NVKI\/Met bestuur gedeelde mappen\/Bestuur\/Missie en Visie\/Missie en Visie NVKI 2016.docx.v1455478367): failed to open stream: No such file or directory at \/var\/www_ssl\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2016-02-24T12:23:07+00:00"}
{"reqId":"akLe5qGLm0SQzJb8\/mAQ","remoteAddr":"109.232.42.33","app":"PHP","message":"filesize(): stat failed for \/yoda\/cloudstore\/data\/\/Sanne\/files_versions\/3. Werk\/5. NVKI\/Met bestuur gedeelde mappen\/Bestuur\/Missie en Visie\/Missie en Visie NVKI 2016.docx.v1455384129 at \/var\/www_ssl\/lib\/private\/files\/storage\/local.php#139","level":3,"time":"2016-02-24T12:24:34+00:00"}
{"reqId":"akLe5qGLm0SQzJb8\/mAQ","remoteAddr":"109.232.42.33","app":"PHP","message":"fopen(\/yoda\/cloudstore\/data\/\/Sanne\/files_versions\/3. Werk\/5. NVKI\/Met bestuur gedeelde mappen\/Bestuur\/Missie en Visie\/Missie en Visie NVKI 2016.docx.v1455384129): failed to open stream: No such file or directory at \/var\/www_ssl\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2016-02-24T12:24:35+00:00"}
{"reqId":"08PNULhq44wJ8oo7yepf","remoteAddr":"83.128.125.171","app":"PHP","message":"Array to string conversion at \/var\/www_ssl\/lib\/private\/template\/functions.php#36","level":3,"time":"2016-02-24T12:57:30+00:00"}
{"reqId":"tKsABR632SDuFZ+h9HL\/","remoteAddr":"83.128.125.171","app":"PHP","message":"Array to string conversion at \/var\/www_ssl\/lib\/private\/template\/functions.php#36","level":3,"time":"2016-02-24T12:58:13+00:00"}
```

**Comment by Aesculapius** [comment]
Never mind, this was caused by the Mail app. After I disabled that app, the occ command worked again as expected.
