### ISSUE TITLE
LDAP Issue - Intermittent dropping connection

### ISSUE THREAD

**Issue by arsefire** [owncloud/core#22710]
### Steps to reproduce
1. LDAP configured correctly, shows configuration OK.
2. User logs in, gets rejected.
3. Check logs, shows No LDAP Connection to server. LDAP box still shows configuration OK.

### Expected behaviour
LDAP gets configured, users able to log in.

### Actual behaviour
Issue is only intermittent, can be fine for hours / days and then suddenly reject a login attempt. Unticking Configuration Active on and off seems to resolve.

### Server configuration
**Operating system**:
Ubuntu 14.04.4 LTS (LDAP server is OS X 10.10.5)

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9-1

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - user_ldap: 0.7.1

Disabled:
  - allactivity
  - announcementcenter
  - encryption
  - external
  - files_external
  - files_pdfviewer
  - files_videoviewer
  - files_w2g
  - firstrunwizard
  - mail
  - news
  - user_external

**The content of config/config.php:**
```json
{
    "system": {
        "instanceid": "ocm3uj3081bo",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.0.5",
            "",
            "",
            "",
            "",
            "cloud.kendallkingscott.com",
            "www.cloud.kendallkingscott.com"
        ],
        "datadirectory": "\/var\/owncloud_data",
        "overwrite.cli.url": "http:\/\/www.cloud.kendallkingscott.com",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": 2,
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "kendall",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "cloud.notifications",
        "mail_domain": "kendallkingscott.co.uk",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.macace.net",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false
    }
}
```

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
```
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                          |
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                                                          |
| hasPagedResultSupport         |                                                                                                                          |
| homeFolderNamingRule          |                                                                                                                          |
| lastJpegPhotoLookup           | 0                                                                                                                        |
| ldapAgentName                 | uid=diradmin, cn=users, dc=zeus, dc=kendallkingscott, dc=com                                                             |
| ldapAgentPassword             | ***                                                                                                                      |
| ldapAttributesForGroupSearch  |                                                                                                                          |
| ldapAttributesForUserSearch   |                                                                                                                          |
| ldapBackupHost                |                                                                                                                          |
| ldapBackupPort                |                                                                                                                          |
| ldapBase                      | dc=zeus, dc=kendallkingscott, dc=com                                                                                     |
| ldapBaseGroups                | dc=zeus, dc=kendallkingscott, dc=com                                                                                     |
| ldapBaseUsers                 | dc=zeus, dc=kendallkingscott, dc=com                                                                                     |
| ldapCacheTTL                  | 600                                                                                                                      |
| ldapConfigurationActive       | 1                                                                                                                        |
| ldapEmailAttribute            | mail                                                                                                                     |
| ldapExperiencedAdmin          | 1                                                                                                                        |
| ldapExpertUUIDGroupAttr       |                                                                                                                          |
| ldapExpertUUIDUserAttr        |                                                                                                                          |
| ldapExpertUsernameAttr        |                                                                                                                          |
| ldapGroupDisplayName          | cn                                                                                                                       |
| ldapGroupFilter               | (&(|(objectclass=apple-group))(|(cn=bristolusers)(cn=exeterusers)(cn=management)(cn=ringwoodusers)(cn=teddingtonusers))) |
| ldapGroupFilterGroups         | bristolusers;exeterusers;management;ringwoodusers;teddingtonusers                                                        |
| ldapGroupFilterMode           | 0                                                                                                                        |
| ldapGroupFilterObjectclass    | apple-group                                                                                                              |
| ldapGroupMemberAssocAttr      | memberUid                                                                                                                |
| ldapHost                      | zeus.kendallkingscott.com                                                                                                |
| ldapIgnoreNamingRules         |                                                                                                                          |
| ldapLoginFilter               | (&(|(objectclass=posixAccount))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(cn=%uid))))                         |
| ldapLoginFilterAttributes     | cn                                                                                                                       |
| ldapLoginFilterEmail          | 1                                                                                                                        |
| ldapLoginFilterMode           | 0                                                                                                                        |
| ldapLoginFilterUsername       | 1                                                                                                                        |
| ldapNestedGroups              | 0                                                                                                                        |
| ldapOverrideMainServer        |                                                                                                                          |
| ldapPagingSize                | 500                                                                                                                      |
| ldapPort                      | 389                                                                                                                      |
| ldapQuotaAttribute            |                                                                                                                          |
| ldapQuotaDefault              |                                                                                                                          |
| ldapTLS                       | 0                                                                                                                        |
| ldapUserDisplayName           | cn                                                                                                                       |
| ldapUserFilter                | (|(objectclass=apple-user))                                                                                              |
| ldapUserFilterGroups          |                                                                                                                          |
| ldapUserFilterMode            | 0                                                                                                                        |
| ldapUserFilterObjectclass     | apple-user                                                                                                               |
| ldapUuidGroupAttribute        | auto                                                                                                                     |
| ldapUuidUserAttribute         | auto                                                                                                                     |
| turnOffCertCheck              | 0                                                                                                                        |
| useMemberOfToDetectMembership | 1                                                                                                                        |
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------+
```

### Client configuration
**Browser:**
N/A

**Operating system:**
N/A

#### ownCloud log (data/owncloud.log)

This is the specific error message I get every time it drops the LDAP connection - 

```json
Error	index	Exception: 
{"Exception":"OC\\ServerNotAvailableException","Message":"Connection to LDAP server could not be established","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/connection.php(605): OCA\\user_ldap\\lib\\Connection->getConnectionResource()\n#1 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/connection.php(558): OCA\\user_ldap\\lib\\Connection->bind()\n#2 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/connection.php(160): OCA\\user_ldap\\lib\\Connection->establishConnection()\n#3 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/connection.php(168): OCA\\user_ldap\\lib\\Connection->init()\n#4 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php(830): OCA\\user_ldap\\lib\\Connection->getConnectionResource()\n#5 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php(978): OCA\\user_ldap\\lib\\Access->executeSearch('(&(&(|(objectcl...', Array, Array, '500', NULL)\n#6 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php(791): OCA\\user_ldap\\lib\\Access->search('(&(&(|(objectcl...', Array, Array, '500', NULL)\n#7 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php(729): OCA\\user_ldap\\lib\\Access->searchGroups('(&(&(|(objectcl...', Array, '500', NULL)\n#8 \/var\/www\/owncloud\/apps\/user_ldap\/group_ldap.php(713): OCA\\user_ldap\\lib\\Access->fetchListOfGroups('(&(&(|(objectcl...', Array, '500', NULL)\n#9 \/var\/www\/owncloud\/apps\/user_ldap\/group_ldap.php(753): OCA\\user_ldap\\GROUP_LDAP->getGroupsChunk('', '500', NULL)\n#10 \/var\/www\/owncloud\/lib\/private\/group\/manager.php(199): OCA\\user_ldap\\GROUP_LDAP->getGroups('', NULL, NULL)\n#11 \/var\/www\/owncloud\/lib\/private\/group\/metadata.php(195): OC\\Group\\Manager->search('')\n#12 \/var\/www\/owncloud\/lib\/private\/group\/metadata.php(97): OC\\Group\\MetaData->getGroups('')\n#13 \/var\/www\/owncloud\/settings\/users.php(62): OC\\Group\\MetaData->get()\n#14 \/var\/www\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#15 [internal function]: __lambda_func(Array)\n#16 \/var\/www\/owncloud\/lib\/private\/route\/router.php(291): call_user_func('?lambda_663', Array)\n#17 \/var\/www\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/settings\/users')\n#18 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#19 {main}","File":"\/var\/www\/owncloud\/apps\/user_ldap\/lib\/connection.php","Line":175}	2016-02-29T09:06:10+00:00
Error	user_ldap	No LDAP Connection to server zeus.kendallkingscott.com	2016-02-29T09:06:10+00:00
```

**Comment by arsefire** [comment]
P.S. This is my first time posting so just wanted to say thanks for such awesome code!

**Comment by arsefire** [comment]
P.P.S. Installed swatch to monitor owncloud.log for LDAP failed connections and then gracefully restart Apache, however is there a command I could send to toggle -

`| ldapConfigurationActive       | 1   ` ?

**Comment by blizzz** [comment]
You can use the console commands for instance, .occ ldap:set-config $ID $NAME $VALUE

Other then restarting, you probably should check your environment and network. Theres nothing we could do in ownCloud about shaky network, unfortunately. Thus, closing.

**Comment by arsefire** [comment]
Cheers

**Comment by oskarp10** [comment]
Hi Arsefire,
I'm having the same problem: totally random disconnects on any of my five nodes (they work as a cluster).
I was just thinking about using swatch then I saw your post. Could you share the swatch filter and the scripts to restart please?

Thanks
Oskar

**Comment by arsefire** [comment]
Really sorry Oskar, don't have swatch setup any longer.

It took a bit of googling, but you should be able to monitor the owncloud
log for ldap disconnects and restart apache2.

It did work but just felt a bit of a blag.

Lewis.
