### ISSUE TITLE
app:enable broken if file id and app name do differ

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22730]
After installation:

> ➜  master git:(master) ✗ ./occ app:enable contacts

```
            <li>Message: Argument 1 passed to OC\App\DependencyAnalyzer::analyze() must be of the type array, null given, called in /Users/lukasreschke/Documents/Programming/master/lib/private/app.php on line 1096</li>
            <li>File: /Users/lukasreschke/Documents/Programming/master/lib/private/app/dependencyanalyzer.php</li>
            <li>Line: 52</li>
            </ul>

            <br />
        <h2><strong>Trace</strong></h2>
        <pre>#0 /Users/lukasreschke/Documents/Programming/master/lib/private/app.php(1096): OC\App\DependencyAnalyzer-&gt;analyze(NULL)
#1 /Users/lukasreschke/Documents/Programming/master/lib/private/app.php(297): OC_App::installApp(&#039;contactsrework&#039;)
#2 /Users/lukasreschke/Documents/Programming/master/core/command/app/enable.php(74): OC_App::enable(&#039;contacts&#039;)
#3 /Users/lukasreschke/Documents/Programming/master/3rdparty/symfony/console/Command/Command.php(259): OC\Core\Command\App\Enable-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/lukasreschke/Documents/Programming/master/3rdparty/symfony/console/Application.php(840): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/lukasreschke/Documents/Programming/master/3rdparty/symfony/console/Application.php(192): Symfony\Component\Console\Application-&gt;doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/lukasreschke/Documents/Programming/master/3rdparty/symfony/console/Application.php(123): Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/lukasreschke/Documents/Programming/master/lib/private/console/application.php(143): Symfony\Component\Console\Application-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/lukasreschke/Documents/Programming/master/console.php(86): OC\Console\Application-&gt;run()
#9 /Users/lukasreschke/Documents/Programming/master/occ(11): require_once(&#039;/Users/lukasres...&#039;)
#10 {main}</pre>
```

Works after second request … debugging …

**Comment by LukasReschke** [comment]
Aha. Caused because the app id is wrong which makes it explode hard. So https://github.com/owncloud/contacts/pull/67 should fix this, still should be fixed in core as well.

**Comment by nickvergessen** [comment]
Well appid has to be the folder name by definition, because we can not find the app classes otherwise with autoloading.
So the only thing we can fix here is the error message

**Comment by PVince81** [comment]
@VicDeo didn't we fix this recently ?

**Comment by VicDeo** [comment]
@PVince81 I don't think so.
I might be wrong but appid and app directory name should always be the same by design.

**Comment by PVince81** [comment]
Yes they must be but the error message is unrelated and confusing. I thought we fixed the message recently.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by PVince81** [comment]
low severity for a rare case.
