### ISSUE TITLE
pyocclient tests failing against stable9

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22771]
Tests run fine against stable8.2 and previous versions, but fail against stable9.

This could hint at possible regressions:
```
..................('Assertion error caught with data set ', ['test.txt'])
FF.............EE.....F.........................
======================================================================
ERROR: test_share_with_group (__main__.TestFileAccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/unittest_data_provider/__init__.py", line 7, in repl
    fn(self, *i)
  File "owncloud/test/test.py", line 614, in test_share_with_group
    share_info = self.client.share_file_with_group(path, self.test_group, perms=31)
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 1342, in share_file_with_group
    tree = ET.fromstring(res.text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 469-470: ordinal not in range(128)

======================================================================
ERROR: test_share_with_link (__main__.TestFileAccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/unittest_data_provider/__init__.py", line 7, in repl
    fn(self, *i)
  File "owncloud/test/test.py", line 576, in test_share_with_link
    share_info = self.client.share_file_with_link(path, public_upload=True, password='1234')
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 817, in share_file_with_link
    self.__check_ocs_status(tree)
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 1581, in __check_ocs_status
    raise OCSResponseError(r)
OCSResponseError: OCS error: 404

======================================================================
FAIL: test_get_shares (__main__.TestFileAccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/unittest_data_provider/__init__.py", line 7, in repl
    fn(self, *i)
  File "owncloud/test/test.py", line 736, in test_get_shares
    shares = self.client.get_shares(self.test_root + file_name, subfiles=True)
AssertionError: ResponseError not raised

======================================================================
FAIL: test_get_shares_empty (__main__.TestFileAccess)
Test get shares with empty result
----------------------------------------------------------------------
Traceback (most recent call last):
  File "owncloud/test/test.py", line 763, in test_get_shares_empty
    shares = self.client.get_shares(self.test_root + file_name)
AssertionError: ResponseError not raised

======================================================================
FAIL: test_update_share_user (__main__.TestFileAccess)
Test updating a share parameters - user share
----------------------------------------------------------------------
Traceback (most recent call last):
  File "owncloud/test/test.py", line 781, in test_update_share_user
    self.assertEqual(int(perms), self.client.OCS_PERMISSION_ALL)
AssertionError: 1 != 31

----------------------------------------------------------------------
Ran 66 tests in 168.792s

FAILED (failures=3, errors=2)
```

Setting to critical now until it's clearer whether it's actually a regression.

Ideal would be to port these tests to be done as integration tests too.

@rullzer 

CC @cmonteroluque

**Comment by PVince81** [comment]
Here a run with py.test, providing more info:

```
± % py.test owncloud/test/test.py                                                                                                                                                !10070
================================================================================= test session starts ==================================================================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.30, pluggy-0.3.1
rootdir: /home/vincent/work/workspace/pyocclient, inifile: 
collected 66 items 

owncloud/test/test.py .................FF.............FF.....F..........................

======================================================================================= FAILURES =======================================================================================
____________________________________________________________________________ TestFileAccess.test_get_shares ____________________________________________________________________________

self = <owncloud.test.test.TestFileAccess testMethod=test_get_shares>, args = (), i = ['test.txt']

    def repl(self, *args):
        for i in fn_data_provider():
            try:
>               fn(self, *i)

/usr/lib/python2.7/site-packages/unittest_data_provider/__init__.py:7: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
owncloud/test/test.py:736: in test_get_shares
    shares = self.client.get_shares(self.test_root + file_name, subfiles=True)
E   AssertionError: ResponseError not raised
--------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------
('Assertion error caught with data set ', ['test.txt'])
_________________________________________________________________________ TestFileAccess.test_get_shares_empty _________________________________________________________________________

self = <owncloud.test.test.TestFileAccess testMethod=test_get_shares_empty>

    def test_get_shares_empty(self):
        """Test get shares with empty result"""
        file_name = 'test.txt'
        self.assertTrue(self.client.put_file_contents(self.test_root + file_name, 'hello world!'))
    
        # Get all shares
        shares = self.client.get_shares()
        self.assertEquals(shares, [])
    
        shares = None
        with self.assertRaises(owncloud.ResponseError) as e:
>           shares = self.client.get_shares(self.test_root + file_name)
E           AssertionError: ResponseError not raised

owncloud/test/test.py:763: AssertionError
_________________________________________________________________________ TestFileAccess.test_share_with_group _________________________________________________________________________

self = <owncloud.test.test.TestFileAccess testMethod=test_share_with_group>, args = (), i = ['文件.txt']

    def repl(self, *args):
        for i in fn_data_provider():
            try:
>               fn(self, *i)

/usr/lib/python2.7/site-packages/unittest_data_provider/__init__.py:7: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
owncloud/test/test.py:614: in test_share_with_group
    share_info = self.client.share_file_with_group(path, self.test_group, perms=31)
owncloud/owncloud.py:1342: in share_file_with_group
    tree = ET.fromstring(res.text)
/usr/lib64/python2.7/xml/etree/ElementTree.py:1300: in XML
    parser.feed(text)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <xml.etree.ElementTree.XMLParser object at 0x7f3e4273ba10>
data = '<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data...are_with>
  <share_with_displayname>my_test_group</share_with_displayname>
  <mail_send>0</mail_send>
 </data>
</ocs>
'

    def feed(self, data):
        try:
>           self._parser.Parse(data, 0)
E           UnicodeEncodeError: 'ascii' codec can't encode characters in position 469-470: ordinal not in range(128)

/usr/lib64/python2.7/xml/etree/ElementTree.py:1640: UnicodeEncodeError
_________________________________________________________________________ TestFileAccess.test_share_with_link __________________________________________________________________________

self = <owncloud.test.test.TestFileAccess testMethod=test_share_with_link>, args = (), i = ['test.txt']

    def repl(self, *args):
        for i in fn_data_provider():
            try:
>               fn(self, *i)

/usr/lib/python2.7/site-packages/unittest_data_provider/__init__.py:7: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
owncloud/test/test.py:576: in test_share_with_link
    share_info = self.client.share_file_with_link(path, public_upload=True, password='1234')
owncloud/owncloud.py:817: in share_file_with_link
    self.__check_ocs_status(tree)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

tree = <Element 'ocs' at 0x7f3e426177d0>, accepted_codes = [100]

    @staticmethod
    def __check_ocs_status(tree, accepted_codes=[100]):
        """Checks the status code of an OCS request
    
            :param tree: response parsed with elementtree
            :param accepted_codes: list of statuscodes we consider good. E.g. [100,102] can be used to accept a POST
                   returning an 'already exists' condition
            :raises: HTTPResponseError if the http status is not 200, or OCSResponseError if the OCS status is not one of the accepted_codes.
            """
        code_el = tree.find('meta/statuscode')
        if code_el is not None and int(code_el.text) not in accepted_codes:
            r = requests.Response()
            msg_el = tree.find('meta/message')
            if msg_el is None:
                msg_el = tree  # fallback to the entire ocs response, if we find no message.
            r._content = ET.tostring(msg_el)
            r.status_code = int(code_el.text)
>           raise OCSResponseError(r)
E           OCSResponseError: OCS error: 404

owncloud/owncloud.py:1581: OCSResponseError
________________________________________________________________________ TestFileAccess.test_update_share_user _________________________________________________________________________

self = <owncloud.test.test.TestFileAccess testMethod=test_update_share_user>

    def test_update_share_user(self):
        """Test updating a share parameters - user share"""
        path = self.test_root + 'update_share_user.txt'
        self.assertTrue(self.client.put_file_contents(path, 'hello world!'))
    
        share_info = self.client.share_file_with_user(path, self.share2user)
        share_id = share_info.get_id()
        self.assertTrue(self.client.update_share(share_id, perms=self.client.OCS_PERMISSION_ALL))
        perms = self.client.get_shares(path)[0].get_permissions()
        # now the permissions should be OCS_PERMISSION_ALL,
        # because we've shared it with a user
>       self.assertEqual(int(perms), self.client.OCS_PERMISSION_ALL)
E       AssertionError: 1 != 31

owncloud/test/test.py:781: AssertionError
======================================================================== 5 failed, 61 passed in 164.39 seconds =========================================================================
```

**Comment by PVince81** [comment]
@rullzer you can run individual tests with py.test (you might need to install it), for example:
```
% py.test owncloud/test/test.py::TestFileAccess::test_get_shares
```

Looks like the first one is with chinese folder names, the XML response should contain the chinese folder name, and might not be properly encoded.

**Comment by PVince81** [comment]
Regarding the encoding issue, it looks like the difference is that in the past we only returned "id" and "permissions" and now we return the full share info.

Before:
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <id>12</id>
  <permissions>23</permissions>
  <expiration/>
 </data>
</ocs>
```

After:
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <id>3</id>
  <share_type>1</share_type>
  <uid_owner>admin</uid_owner>
  <displayname_owner>admin</displayname_owner>
  <permissions>19</permissions>
  <stime>1456915655</stime>
  <parent/>
  <expiration/>
  <token/>
  <uid_file_owner>admin</uid_file_owner>
  <displayname_file_owner>admin</displayname_file_owner>
  <path>/pyoctestroot1456915652/文件.txt</path>
  <item_type>file</item_type>
  <storage_id>home::admin</storage_id>
  <storage>1</storage>
  <item_source>14</item_source>
  <file_source>14</file_source>
  <file_parent>5</file_parent>
  <file_target>/文件.txt</file_target>
  <share_with>my_test_group</share_with>
  <share_with_displayname>my_test_group</share_with_displayname>
  <mail_send>0</mail_send>
 </data>
</ocs>
```

From what I heard, if no encoding is specified in the response, it should default to UTF-8.
I'll double check the python parser to make sure it defaults to that.

**Comment by PVince81** [comment]
Fix for encoding in pyocclient here: https://github.com/owncloud/pyocclient/pull/152

Now still need to investigate the other errors.
Did we change the API response expectations ?

**Comment by rullzer** [comment]
Ok I had a look and came across some stuff.

- [ ] TestFileAccess.test_get_shares: This passes subFiles=True as a get parameter. However the new code checks for 'true'. I checked and the old code indeed also checks for 'True'. Basically this is a doc issue since only define boolean but now what it means.

- [ ] TestFileAccess.test_get_shares_empty: Apperently the old code was inconsistent. When requesting all shares `../shares` if there were no shares we returned success and an empty array. However when quering a specific path `../shares?path=<PATH>` if there are no shares a 404 was returned. From my POV this is a bug in the old code. If multiple shares can be returned no shares in an empty array not a 404.

- [ ] TestFileAccess.test_share_with_link: This tests tries to share a file via public link with public upload. But we only allow public upload for folders. The new code is a bit stricter here.

- [ ] TestFileAccess.test_update_share_user: Here we try to update a share with all permissions. However for files all permissions make no sense. Since CREATE and DELETE permissions don't mean anything on them. The old code just swallowed this. But the new code has stricter permission checking. Again I would more rate this as a bug in the old code.

**Comment by PVince81** [comment]
Cool, so it looks like all remaining cases are about misuse of the API,

Can you fix the pyocclient unit tests then ?

Lowering severity then.

**Comment by rullzer** [comment]
Yep will fix pyocclient :)

**Comment by rullzer** [comment]
PR in https://github.com/owncloud/pyocclient/issues/153

**Comment by rullzer** [comment]
This is fixed with https://github.com/owncloud/pyocclient/pull/153 and https://github.com/owncloud/pyocclient/pull/152
