### ISSUE TITLE
Opendir Path is empty . External Storage Amazon s3. Opendir() is getting an empty path. Uploading to s3 is working. Syncing/downloading is not working

### ISSUE THREAD

**Issue by archupsg03** [owncloud/core#22801]
### Expected behaviour
Sync files from s3

### Actual behaviour
Exception

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** Mysql

**PHP version:**5.4

**ownCloud version:** 8.2 Enterprise Edition Trial

**Updated from an older ownCloud or fresh install:** Fresh Install

**Where did you install ownCloud from:** owncloud.com

**Are you using external storage, if yes which one:** local/smb/sftp/... s3

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No 

### Client configuration
**Browser:** Firefox

**Operating system:** Linux

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here

Exception: {"Exception":"Aws\\S3\\Exception\\InvalidArgumentException","Message":"Invalid Argument","Code":0,"Trace":"
#0 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Exception\/NamespaceExceptionFactory.php(76): Aws\\Common\\Exception\\NamespaceExceptionFactory->createException('Aws\\S3\\Exceptio...', Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Message\\Response), Array)\n
#1 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Exception\/ExceptionListener.php(55): Aws\\Common\\Exception\\NamespaceExceptionFactory->fromResponse(Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Message\\Response))\n
#2 [internal function]: Aws\\Common\\Exception\\ExceptionListener->onRequestError(Object(Guzzle\\Common\\Event), 'request.error', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n
#3 \/srv\/www\/htdocs\/owncloud\/3rdparty\/symfony\/event-dispatcher\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\\Common\\Event), 'request.error', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n
#4 \/srv\/www\/htdocs\/owncloud\/3rdparty\/symfony\/event-dispatcher\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php(53): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\\Common\\Event))\n
#5 \/srv\/www\/htdocs\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Message\/Request.php(589): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('request.error', Object(Guzzle\\Common\\Event))\n
#6 \/srv\/www\/htdocs\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Message\/Request.php(378): Guzzle\\Http\\Message\\Request->processResponse(Array)\n
#7 \/srv\/www\/htdocs\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(286): Guzzle\\Http\\Message\\Request->setState('complete', Array)\n
#8 \/srv\/www\/htdocs\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(244): Guzzle\\Http\\Curl\\CurlMulti->processResponse(Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Curl\\CurlHandle), Array)\n
#9 \/srv\/www\/htdocs\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(227): Guzzle\\Http\\Curl\\CurlMulti->processMessages()\n
#10 \/srv\/www\/htdocs\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(211): Guzzle\\Http\\Curl\\CurlMulti->executeHandles()\n
#11 \/srv\/www\/htdocs\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMulti.php(105): Guzzle\\Http\\Curl\\CurlMulti->perform()\n
#12 \/srv\/www\/htdocs\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Curl\/CurlMultiProxy.php(91): Guzzle\\Http\\Curl\\CurlMulti->send()\n
#13 \/srv\/www\/htdocs\/owncloud\/3rdparty\/guzzle\/http\/Guzzle\/Http\/Client.php(282): Guzzle\\Http\\Curl\\CurlMultiProxy->send()\n
#14 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Client\/AbstractClient.php(262): Guzzle\\Http\\Client->send(Object(Guzzle\\Http\\Message\\Request))\n
#15 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Guzzle\/Service\/Client.php(136): Aws\\Common\\Client\\AbstractClient->send(Object(Guzzle\\Http\\Message\\Request))\n
#16 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Guzzle\/Service\/Command\/AbstractCommand.php(153): Guzzle\\Service\\Client->execute(Object(Aws\\S3\\Command\\S3Command))\n
#17 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Guzzle\/Service\/Command\/AbstractCommand.php(189): Guzzle\\Service\\Command\\AbstractCommand->execute()\n
#18 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Iterator\/AwsResourceIterator.php(62): Guzzle\\Service\\Command\\AbstractCommand->getResult()\n
#19 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Guzzle\/Service\/Resource\/ResourceIterator.php(190): Aws\\Common\\Iterator\\AwsResourceIterator->sendRequest()\n
#20 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Guzzle\/Service\/Resource\/ResourceIterator.php(157): Guzzle\\Service\\Resource\\ResourceIterator->next()\n
#21 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/amazons3.php(278): Guzzle\\Service\\Resource\\ResourceIterator->rewind()\n
#22 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(89): OC\\Files\\Storage\\AmazonS3->opendir('')\n
#23 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/availability.php(93): OC\\Files\\Storage\\Wrapper\\Wrapper->opendir('')\n
#24 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(89): OC\\Files\\Storage\\Wrapper\\Availability->opendir('')\n
#25 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(89): OC\\Files\\Storage\\Wrapper\\Wrapper->opendir('')\n
#26 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(89): OC\\Files\\Storage\\Wrapper\\Wrapper->opendir('')\n
#27 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/cache\/scanner.php(300): OC\\Files\\Storage\\Wrapper\\Wrapper->opendir('')\n
#28 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/cache\/scanner.php(335): OC\\Files\\Cache\\Scanner->getNewChildren('')\n
#29 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/cache\/scanner.php(268): OC\\Files\\Cache\\Scanner->scanChildren('', false, 3, Array, true)\n
#30 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/cache\/watcher.php(103): OC\\Files\\Cache\\Scanner->scan('', false)\n
#31 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/view.php(1207): OC\\Files\\Cache\\Watcher->update('', Array)\n
#32 \/srv\/www\/htdocs\/owncloud\/lib\/private\/connector\/sabre\/objecttree.php(148): OC\\Files\\View->getFileInfo('Cleversafe')\n
#33 \/srv\/www\/htdocs\/owncloud\/lib\/private\/connector\/sabre\/custompropertiesbackend.php(100): OC\\Connector\\Sabre\\ObjectTree->getNodeForPath('Cleversafe')\n
#34 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropertyStorage\/Plugin.php(86): OC\\Connector\\Sabre\\CustomPropertiesBackend->propFind('Cleversafe', Object(Sabre\\DAV\\PropFind))\n
#35 [internal function]: Sabre\\DAV\\PropertyStorage\\Plugin->propFind(Object(Sabre\\DAV\\PropFind), Object(OC\\Connector\\Sabre\\Directory))\n
#36 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#37 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1016): Sabre\\Event\\EventEmitter->emit('propFind', Array)\n
#38 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(936): Sabre\\DAV\\Server->getPropertiesByNode(Object(Sabre\\DAV\\PropFind), Object(OC\\Connector\\Sabre\\Directory))\n
#39 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(327): Sabre\\DAV\\Server->getPropertiesForPath('', Array, 1)\n
#40 [internal function]: Sabre\\DAV\\CorePlugin->httpPropfind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#41 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#42 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n
#43 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#44 \/srv\/www\/htdocs\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n
#45 \/srv\/www\/htdocs\/owncloud\/remote.php(137): require_once('\/srv\/www\/htdocs...')\n
#46 {main}","File":"\/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Exception\/NamespaceExceptionFactory.php","Line":91}

**Comment by MorrisJobke** [comment]
cc @butonic @Xenopathic

**Comment by PVince81** [comment]
@archupsg03 are you using S3 as primary storage or as external storage ?
The former is configured in config.php while the latter is configured in the admin page.

**Comment by PVince81** [comment]
Okay, it's indeed external storage: "files_external\/lib\/amazons3.php"

Strange error: `NamespaceExceptionFactory` and `Aws\\S3\\Exception\\InvalidArgumentException`

**Comment by archupsg03** [comment]
Yeah I am using S3

**Comment by PVince81** [comment]
Syncing with Amazon S3 seems to work fine, no such error. Also our integration tests are running against a Ceph instance through the S3 interface, so it should work.
I think the region is optional.

Maybe some environment issue ?
You might have more luck checking http://owncloud.org/support

**Comment by archupsg03** [comment]
if it supposed to be environmental issue, uploading should also fail right ?

**Comment by archupsg03** [comment]
Hi 

We figured out the issue. Region name is mandatory for S3 emulated storage. Thanks for your support.
