### ISSUE TITLE
External storage previously encrypted files cannot be deleted from a different oC server.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22805]
### Steps to reproduce

Having serverA and serverB both using oC9.0.0
1. Enable encryption in serverA.
2. Enable external storage in serverA.
3. Mount an external storage in serverA (SMB for example). Upload some files.
4. Enable external storage in serverB.
5. Mount same external storage of point 3 in serverB.
6. Try to remove files in serverB.
### Expected behaviour

If user from serverB has enough permissions, files are deleted.
### Actual behaviour

There is an error and files are not deleted.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.0.0.16","versionstring":"9.0.0 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
Yes in serverA.

**Logs**

```
Exception: {"Message":"Module with id: OC_DEFAULT_MODULE does not exist.","Exception":"OC\\Encryption\\Exceptions\\ModuleDoesNotExistsException","Code":0,"Trace":"#0 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(375): OC\\Encryption\\Manager->getEncryptionModule('OC_DEFAULT_MODU...')\n#1 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(287): OC\\Files\\Storage\\Wrapper\\Encryption->fopen('Hayden.jpg', 'r')\n#2 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(678): OC\\Files\\Storage\\Wrapper\\Wrapper->fopen('Hayden.jpg', 'r')\n#3 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(593): OC\\Files\\Storage\\Wrapper\\Encryption->copyBetweenStorage(Object(OCA\\Files_Trashbin\\Storage), 'Hayden.jpg', 'files_trashbin\/...', true, true)\n#4 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(558): OC\\Files\\Storage\\Wrapper\\Encryption->moveFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'Hayden.jpg', 'files_trashbin\/...')\n#5 \/opt\/owncloud\/apps\/files_trashbin\/lib\/trashbin.php(235): OC\\Files\\Storage\\Wrapper\\Wrapper->moveFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'Hayden.jpg', 'files_trashbin\/...')\n#6 \/opt\/owncloud\/apps\/files_trashbin\/lib\/storage.php(160): OCA\\Files_Trashbin\\Trashbin::move2trash('SMB\/Hayden.jpg')\n#7 \/opt\/owncloud\/apps\/files_trashbin\/lib\/storage.php(95): OCA\\Files_Trashbin\\Storage->doDelete('Hayden.jpg', 'unlink')\n#8 \/opt\/owncloud\/lib\/private\/files\/view.php(1059): OCA\\Files_Trashbin\\Storage->unlink('Hayden.jpg')\n#9 \/opt\/owncloud\/lib\/private\/files\/view.php(641): OC\\Files\\View->basicOperation('unlink', '\/SMB\/Hayden.jpg', Array)\n#10 \/opt\/owncloud\/apps\/dav\/lib\/connector\/sabre\/file.php(333): OC\\Files\\View->unlink('\/SMB\/Hayden.jpg')\n#11 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(179): OCA\\DAV\\Connector\\Sabre\\File->delete()\n#12 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(287): Sabre\\DAV\\Tree->delete('SMB\/Hayden.jpg')\n#13 [internal function]: Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#14 \/opt\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#15 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#16 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#17 \/opt\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#18 \/opt\/owncloud\/remote.php(138): require_once('\/opt\/owncloud\/a...')\n#19 {main}","File":"\/opt\/owncloud\/lib\/private\/encryption\/manager.php","Line":172,"User":"admin"}
```
### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment]
It's indeed a problem, but a very rare use case, mostly only seen when testing.
Moving to backlog for now

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
