### ISSUE TITLE
Huge log when trying to Enable Path Style option in a S3 Amazon mount

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22847]
### Steps to reproduce
1. Configure a S3 Amazon mount
2. Check 'Enable Path Style' checkbox
### Expected behaviour

No log is shown
### Actual behaviour

owncloud.log file has a huge log
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0.0 RC1 (testing)
### Logs

```
{"reqId":"hJahYbQQRlQbFgT+eSMv","remoteAddr":"82.159.139.58","app":"files_external","message":"Exception: {\"Exception\":\"Aws\\\\S3\\\\Exception\\\\BucketAlreadyOwnedByYouException\",\"Message\":\"Your previous request to create the named bucket succeeded and you already own it.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/NamespaceExceptionFactory.php(76): Aws\\\\Common\\\\Exception\\\\NamespaceExceptionFactory->createException('Aws\\\\S3\\\\Exceptio...', Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Message\\\\Response), Array)\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/ExceptionListener.php(55): Aws\\\\Common\\\\Exception\\\\NamespaceExceptionFactory->fromResponse(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Message\\\\Response))\\n#2 [internal function]: Aws\\\\Common\\\\Exception\\\\ExceptionListener->onRequestError(Object(Guzzle\\\\Common\\\\Event), 'request.error', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(181): call_user_func(Array, Object(Guzzle\\\\Common\\\\Event), 'request.error', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(46): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\\\\Common\\\\Event))\\n#5 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(589): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->dispatch('request.error', Object(Guzzle\\\\Common\\\\Event))\\n#6 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(378): Guzzle\\\\Http\\\\Message\\\\Request->processResponse(Array)\\n#7 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/EntityEnclosingRequest.php(49): Guzzle\\\\Http\\\\Message\\\\Request->setState('complete', Array)\\n#8 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(286): Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest->setState('complete', Array)\\n#9 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(244): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processResponse(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Curl\\\\CurlHandle), Array)\\n#10 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(227): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processMessages()\\n#11 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(211): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->executeHandles()\\n#12 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(105): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->perform()\\n#13 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMultiProxy.php(91): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->send()\\n#14 \\\/opt\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Client.php(282): Guzzle\\\\Http\\\\Curl\\\\CurlMultiProxy->send()\\n#15 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Client\\\/AbstractClient.php(262): Guzzle\\\\Http\\\\Client->send(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest))\\n#16 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Client.php(136): Aws\\\\Common\\\\Client\\\\AbstractClient->send(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest))\\n#17 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Command\\\/AbstractCommand.php(153): Guzzle\\\\Service\\\\Client->execute(Object(Aws\\\\S3\\\\Command\\\\S3Command))\\n#18 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Command\\\/AbstractCommand.php(189): Guzzle\\\\Service\\\\Command\\\\AbstractCommand->execute()\\n#19 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Client.php(76): Guzzle\\\\Service\\\\Command\\\\AbstractCommand->getResult()\\n#20 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Client\\\/AbstractClient.php(107): Guzzle\\\\Service\\\\Client->__call('CreateBucket', Array)\\n#21 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/amazons3.php(589): Aws\\\\Common\\\\Client\\\\AbstractClient->__call('createBucket', Array)\\n#22 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/amazons3.php(589): Aws\\\\S3\\\\S3Client->createBucket(Array)\\n#23 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/amazons3.php(544): OC\\\\Files\\\\Storage\\\\AmazonS3->getConnection()\\n#24 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(231): OC\\\\Files\\\\Storage\\\\AmazonS3->test(false)\\n#25 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(256): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#26 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/globalstoragescontroller.php(179): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#27 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update(1, 'AmazonS3', 'amazons3', 'amazons3::acces...', Array, Array, Array, Array, 100)\\n#28 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#29 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#30 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#31 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#32 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#33 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#34 \\\/opt\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#35 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#36 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/NamespaceExceptionFactory.php\",\"Line\":91}","level":3,"time":"2016-03-04T09:06:20+00:00"}
{"reqId":"hJahYbQQRlQbFgT+eSMv","remoteAddr":"82.159.139.58","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creation of bucket failed. Your previous request to create the named bucket succeeded and you already own it.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/amazons3.php(544): OC\\\\Files\\\\Storage\\\\AmazonS3->getConnection()\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(231): OC\\\\Files\\\\Storage\\\\AmazonS3->test(false)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(256): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/globalstoragescontroller.php(179): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#4 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update(1, 'AmazonS3', 'amazons3', 'amazons3::acces...', Array, Array, Array, Array, 100)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#12 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/amazons3.php\",\"Line\":598}","level":3,"time":"2016-03-04T09:06:20+00:00"}
{"reqId":"m2OcjnuhnDrOzsPiO4Zh","remoteAddr":"82.159.139.58","app":"core","message":"File with id \"13\" has not been found.","level":3,"time":"2016-03-04T09:06:24+00:00"}
```

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** LDAP
### Client configuration

**Browser:** Firefox for Mac OSX

**Comment by davitol** [comment]
As the documentation says:

"Enable path style is usually not required (and is, in fact, incompatible with newer Amazon datacenters), but can be used with non-Amazon servers where the DNS infrastructure cannot be controlled. Ordinarily, requests will be made with http://bucket.hostname.domain/, but with path style enabled, requests are made with http://hostname.domain/bucket instead."

Why do we have this option available in a mount option that is called Amazon S3?

**Comment by Xenopathic** [comment]
This option is for connecting to an S3-compatible system where the DNS may not be so easily controlled, such as Ceph. For true Amazon S3 however, the checkbox should be deselected.

Does it work with the checkbox deselected? If so, then your S3 bucket is on one of those newer Amazon datacentres.

**Comment by PVince81** [comment]
Please try again with 10.0.4 and reopen if the problem persists there.

**Comment by davitol** [comment]
The log keeps showing but lthink it is not an oC issue but a S3 wrong configuration.

```
{"reqId":"LuRgkIeRl1qUG9TVRhGB","level":3,"time":"2017-12-13T11:05:40+00:00","remoteAddr":"85.57.168.79","user":"admin","app":"files_external","method":"PUT","url":"\/index.php\/apps\/files_external\/globalstorages\/1","message":"Exception: {\"Exception\":\"Aws\\\\S3\\\\Exception\\\\S3Exception\",\"Message\":\"The authorization header is malformed; the region 'eu-west-1' is wrong; expecting 'us-east-1'\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/NamespaceExceptionFactory.php(76): Aws\\\\Common\\\\Exception\\\\NamespaceExceptionFactory->createException('Aws\\\\\\\\S3\\\\\\\\Exceptio...', Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Message\\\\Response), Array)\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/ExceptionListener.php(55): Aws\\\\Common\\\\Exception\\\\NamespaceExceptionFactory->fromResponse(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Message\\\\Response))\\n#2 [internal function]: Aws\\\\Common\\\\Exception\\\\ExceptionListener->onRequestError(Object(Guzzle\\\\Common\\\\Event), 'request.error', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(174): call_user_func(Array, Object(Guzzle\\\\Common\\\\Event), 'request.error', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(43): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\\\\Common\\\\Event))\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(589): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->dispatch('request.error', Object(Guzzle\\\\Common\\\\Event))\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(378): Guzzle\\\\Http\\\\Message\\\\Request->processResponse(Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/EntityEnclosingRequest.php(49): Guzzle\\\\Http\\\\Message\\\\Request->setState('complete', Array)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(286): Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest->setState('complete', Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(244): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processResponse(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Curl\\\\CurlHandle), Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(227): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processMessages()\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(211): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->executeHandles()\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(105): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->perform()\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMultiProxy.php(91): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->send()\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Client.php(282): Guzzle\\\\Http\\\\Curl\\\\CurlMultiProxy->send()\\n#15 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Client\\\/AbstractClient.php(262): Guzzle\\\\Http\\\\Client->send(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest))\\n#16 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Client.php(136): Aws\\\\Common\\\\Client\\\\AbstractClient->send(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest))\\n#17 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Command\\\/AbstractCommand.php(153): Guzzle\\\\Service\\\\Client->execute(Object(Aws\\\\S3\\\\Command\\\\S3Command))\\n#18 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Command\\\/AbstractCommand.php(189): Guzzle\\\\Service\\\\Command\\\\AbstractCommand->execute()\\n#19 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Client.php(76): Guzzle\\\\Service\\\\Command\\\\AbstractCommand->getResult()\\n#20 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Client\\\/AbstractClient.php(107): Guzzle\\\\Service\\\\Client->__call('CreateBucket', Array)\\n#21 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/AmazonS3.php(589): Aws\\\\Common\\\\Client\\\\AbstractClient->__call('createBucket', Array)\\n#22 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/AmazonS3.php(544): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\AmazonS3->getConnection()\\n#23 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/External\\\/LegacyUtil.php(202): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\AmazonS3->test(false, true)\\n#24 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(255): OC\\\\Files\\\\External\\\\LegacyUtil::getBackendStatus('\\\\\\\\OCA\\\\\\\\Files_Exte...', Array, false, true)\\n#25 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/GlobalStoragesController.php(187): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OC\\\\Files\\\\External\\\\StorageConfig), true)\\n#26 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update(1, 'AmazonS3', 'amazons3', 'amazons3::acces...', Array, Array, Array, Array, 100, true)\\n#27 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#28 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#29 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#30 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Exter...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#31 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#32 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#33 \\\/opt\\\/owncloud\\\/lib\\\/base.php(929): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#34 \\\/opt\\\/owncloud\\\/index.php(56): OC::handleRequest()\\n#35 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/NamespaceExceptionFactory.php\",\"Line\":91}"}
```
