### ISSUE TITLE
Calendars "lost" after 8.2.2 -> 9.0RC1

### ISSUE THREAD

**Issue by willyaranda** [owncloud/core#22876]
### Steps to reproduce
1. Download OC 9.0 RC1
2. ./occ upgrade

### Expected behaviour
Calendars should show on Calendar.app or CalDAV on Android.

### Actual behaviour
No calendars available

### Server configuration
**Operating system**: `DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"`

**Web server:** `nginx version: nginx/1.9.12`

**Database:** `mysql  Ver 14.14 Distrib 5.7.11, for Linux (x86_64) using  EditLine wrapper`

**PHP version:** `PHP 5.6.18-1+deb.sury.org~trusty+1 (cli)`

**ownCloud version:** 9.0.0 RC1

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** 8.2.2

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.4
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.3
  - files_external: 0.5.2
  - files_pdfviewer: 0.7
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: true
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - firstrunwizard
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc20ea46a2a9",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.pijusmagnificus.com"
        ],
        "datadirectory": "\/home\/cloud\/",
        "dbtype": "mysql",
        "version": "9.0.0.16",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "theme": "",
        "loglevel": 3,
        "mail_smtpmode": "php",
        "mail_from_address": "cloud",
        "mail_domain": "pijusmagnificus.com",
        "log_rotate_size": 10485760,
        "asset-pipeline.enabled": true,
        "enable_avatars": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "default_language": "en",
        "updatechecker": true,
        "has_internet_connection": true,
        "appstoreenabled": true,
        "activity_expire_days": 10,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "password": ""
        },
        "debug": true
    }
}
```

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
**Browser:** Calendar.app or CalDAV

**Operating system:** MacOS 10.11 and Android 6

#### Web server error log
```
80.28.189.65 - - [04/Mar/2016:20:43:30 +0100] "PROPFIND /.well-known/caldav HTTP/1.1" 302 154 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - willyaranda [04/Mar/2016:20:43:30 +0100] "PROPFIND /remote.php/webdav/Terrel%C3%ADsticos HTTP/1.1" 207 385 "-" "Mozilla/5.0 (Macintosh) mirall/2.1.1"
80.28.189.65 - - [04/Mar/2016:20:43:30 +0100] "PROPFIND /remote.php/caldav/ HTTP/1.1" 401 367 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - willyaranda [04/Mar/2016:20:43:31 +0100] "PROPFIND /remote.php/caldav/ HTTP/1.1" 207 560 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - - [04/Mar/2016:20:43:31 +0100] "PROPFIND /remote.php/caldav/principals/users/willyaranda/ HTTP/1.1" 401 367 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - willyaranda [04/Mar/2016:20:43:31 +0100] "PROPFIND /remote.php/webdav/Bymovil HTTP/1.1" 207 374 "-" "Mozilla/5.0 (Macintosh) mirall/2.1.1"
80.28.189.65 - willyaranda [04/Mar/2016:20:43:32 +0100] "PROPFIND /remote.php/webdav/imprimir HTTP/1.1" 207 375 "-" "Mozilla/5.0 (Macintosh) mirall/2.1.1"
80.28.189.65 - willyaranda [04/Mar/2016:20:43:32 +0100] "PROPFIND /remote.php/caldav/principals/users/willyaranda/ HTTP/1.1" 404 211 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - - [04/Mar/2016:20:43:32 +0100] "PROPFIND / HTTP/1.1" 405 166 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - - [04/Mar/2016:20:43:32 +0100] "PROPFIND / HTTP/1.1" 405 166 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - willyaranda [04/Mar/2016:20:43:32 +0100] "PROPFIND /remote.php/webdav/sync HTTP/1.1" 207 390 "-" "Mozilla/5.0 (Macintosh) mirall/2.1.1"
```

#### ownCloud log (data/owncloud.log)
```
None while trying to list calendars
```

#### Browser log
```
Not applicable
```

**Comment by georgehrke** [comment]
@DeepDiver1975

**Comment by willyaranda** [comment]
I'm getting this log on the server:

```
{"reqId":"nU+9ZfBI6U2\/hrVrz2Y1","remoteAddr":"80.28.189.65","app":"caldav","message":"Exception: {\"Message\":\"An exception occurred while executing 'UPDATE `oc_calendars` SET `timezone` = ? WHERE `id` = ?' with params [\\\"BEGIN:VCALENDAR\\\\r\\\\nVERSION:2.0\\\\r\\\\nPRODID:-\\\\\\\/\\\\\\\/Apple Inc.\\\\\\\/\\\\\\\/Mac OS X 10.11.3\\\\\\\/\\\\\\\/EN\\\\r\\\\nCALSCALE:GREGORIAN\\\\r\\\\nBEGIN:VTIMEZONE\\\\r\\\\nTZID:Europe\\\\\\\/Madrid\\\\r\\\\nBEGIN:DAYLIGHT\\\\r\\\\nTZOFFSETFROM:+0100\\\\r\\\\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\\\\r\\\\nDTSTART:19810329T020000\\\\r\\\\nTZNAME:CEST\\\\r\\\\nTZOFFSETTO:+0200\\\\r\\\\nEND:DAYLIGHT\\\\r\\\\nBEGIN:STANDARD\\\\r\\\\nTZOFFSETFROM:+0200\\\\r\\\\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\\\\r\\\\nDTSTART:19961027T030000\\\\r\\\\nTZNAME:CET\\\\r\\\\nTZOFFSETTO:+0100\\\\r\\\\nEND:STANDARD\\\\r\\\\nEND:VTIMEZONE\\\\r\\\\nEND:VCALENDAR\\\\r\\\\n\\\", \\\"7\\\"]:\\n\\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'timezone' at row 1\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_cale...', Array)\\n#2 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/lib\\\/private\\\/db\\\/connection.php(205): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `oc_cale...', Array, Array)\\n#3 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `*PREFIX...', Array, Array)\\n#4 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/lib\\\/private\\\/db\\\/querybuilder\\\/querybuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/dav\\\/lib\\\/caldav\\\/caldavbackend.php(423): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropPatch.php(310): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->OCA\\\\DAV\\\\CalDAV\\\\{closure}(Array)\\n#7 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropPatch.php(238): Sabre\\\\DAV\\\\PropPatch->doCallBackMultiProp(Array, Object(Closure))\\n#8 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1195): Sabre\\\\DAV\\\\PropPatch->commit()\\n#9 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(385): Sabre\\\\DAV\\\\Server->updateProperties('calendars\\\/willy...', Array)\\n#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropPatch(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPPATC...', Array)\\n#13 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(75): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/remote.php(138): require_once('\\\/var\\\/www\\\/cloud....')\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115,\"User\":\"willyaranda\"}","level":4,"time":"2016-03-04T19:56:48+00:00"}
{"reqId":"L6Hz5ecdC38cYJA3wWFT","remoteAddr":"80.28.189.65","app":"caldav","message":"Exception: {\"Message\":\"An exception occurred while executing 'UPDATE `oc_calendars` SET `timezone` = ? WHERE `id` = ?' with params [\\\"BEGIN:VCALENDAR\\\\r\\\\nVERSION:2.0\\\\r\\\\nPRODID:-\\\\\\\/\\\\\\\/Apple Inc.\\\\\\\/\\\\\\\/Mac OS X 10.11.3\\\\\\\/\\\\\\\/EN\\\\r\\\\nCALSCALE:GREGORIAN\\\\r\\\\nBEGIN:VTIMEZONE\\\\r\\\\nTZID:Europe\\\\\\\/Madrid\\\\r\\\\nBEGIN:DAYLIGHT\\\\r\\\\nTZOFFSETFROM:+0100\\\\r\\\\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\\\\r\\\\nDTSTART:19810329T020000\\\\r\\\\nTZNAME:CEST\\\\r\\\\nTZOFFSETTO:+0200\\\\r\\\\nEND:DAYLIGHT\\\\r\\\\nBEGIN:STANDARD\\\\r\\\\nTZOFFSETFROM:+0200\\\\r\\\\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\\\\r\\\\nDTSTART:19961027T030000\\\\r\\\\nTZNAME:CET\\\\r\\\\nTZOFFSETTO:+0100\\\\r\\\\nEND:STANDARD\\\\r\\\\nEND:VTIMEZONE\\\\r\\\\nEND:VCALENDAR\\\\r\\\\n\\\", \\\"6\\\"]:\\n\\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'timezone' at row 1\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_cale...', Array)\\n#2 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/lib\\\/private\\\/db\\\/connection.php(205): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `oc_cale...', Array, Array)\\n#3 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `*PREFIX...', Array, Array)\\n#4 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/lib\\\/private\\\/db\\\/querybuilder\\\/querybuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/dav\\\/lib\\\/caldav\\\/caldavbackend.php(423): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropPatch.php(310): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->OCA\\\\DAV\\\\CalDAV\\\\{closure}(Array)\\n#7 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropPatch.php(238): Sabre\\\\DAV\\\\PropPatch->doCallBackMultiProp(Array, Object(Closure))\\n#8 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1195): Sabre\\\\DAV\\\\PropPatch->commit()\\n#9 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(385): Sabre\\\\DAV\\\\Server->updateProperties('calendars\\\/willy...', Array)\\n#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropPatch(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPPATC...', Array)\\n#13 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(75): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/remote.php(138): require_once('\\\/var\\\/www\\\/cloud....')\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115,\"User\":\"willyaranda\"}","level":4,"time":"2016-03-04T19:56:48+00:00"}
{"reqId":"1W\/hFptelZJ3GqsCJ8CZ","remoteAddr":"2001:41d0:1:de76::1","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/DB-backups\\\/all-20160304210001.gzip not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/lib\\\/private\\\/files\\\/filesystem.php(913): OC\\\\Files\\\\View->getOwner('\\\/DB-backups\\\/all...')\\n#1 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(191): OC\\\\Files\\\\Filesystem::getOwner('\\\/DB-backups\\\/all...')\\n#2 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(145): OCA\\\\Activity\\\\FilesHooks->getSourcePathAndOwner('\\\/DB-backups\\\/all...')\\n#3 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(101): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/DB-backups\\\/all...', 'file_created', 'created_self', 'created_by')\\n#4 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/activity\\\/lib\\\/fileshooksstatic.php(60): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/DB-backups\\\/all...')\\n#5 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#6 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/lib\\\/private\\\/hook.php(105): call_user_func(Array, Array)\\n#7 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/lib\\\/private\\\/filechunking.php(224): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#8 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(436): OC_FileChunking->file_assemble(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/DB-backup...', '\\\/willyaranda\\\/fi...')\\n#9 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #41)\\n#10 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/directory.php(134): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #41)\\n#11 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('all-20160304210...', Resource id #41)\\n#12 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('DB-backups\\\/all-...', Resource id #41, NULL)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#16 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/remote.php(138): require_once('\\\/var\\\/www\\\/cloud....')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud.pijusmagnificus.com\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1583}","level":3,"time":"2016-03-04T20:00:08+00:00"}
```

**Comment by georgehrke** [comment]
@DeepDiver1975 `Data too long for column 'timezone'` looks rather serious to me

**Comment by LukasReschke** [comment]
Should probably be a clob like in https://github.com/owncloudarchive/calendar/commit/8d8bb68b010fc2c42a258dee43516404a95ab861 or have a longer length defined.

`TEXT` as in https://github.com/owncloud/core/blob/45f49a090aea50b29a9162717ce38799cd0c7111/apps/dav/appinfo/database.xml#L338-L341 means a `varchar(255)` in MySQL. The timezone passed by @willyaranda is which is what is going to fail.

```
mysql> describe oc_calendars;
+---------------+---------------------+------+-----+---------+----------------+
| Field         | Type                | Null | Key | Default | Extra          |
+---------------+---------------------+------+-----+---------+----------------+
| id            | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| principaluri  | varchar(255)        | YES  | MUL | NULL    |                |
| displayname   | varchar(255)        | YES  |     | NULL    |                |
| uri           | varchar(255)        | YES  |     | NULL    |                |
| synctoken     | int(10) unsigned    | NO   |     | 1       |                |
| description   | varchar(255)        | YES  |     | NULL    |                |
| calendarorder | int(10) unsigned    | NO   |     | 0       |                |
| calendarcolor | varchar(255)        | YES  |     | NULL    |                |
| timezone      | varchar(255)        | YES  |     | NULL    |                |
| components    | varchar(255)        | YES  |     | NULL    |                |
| transparent   | smallint(6)         | NO   |     | 0       |                |
+---------------+---------------------+------+-----+---------+----------------+
11 rows in set (0.00 sec)
``` 

Not a database expert myself so I can just provide some of the debugging here :wink:

**Comment by LukasReschke** [comment]
Tentatively tagging as 9.0 and sev1-critical since this will lead to problems with importing existing calendars. The patch should be as easy as changing back the type to `clob` so I don't think there will be many potential problems also given that this is a _very_ separated part of ownCloud. It has no effect on any other functionality.

cc @karlitschek @cmonteroluque Please just retag if you disagree.

**Comment by LukasReschke** [comment]
Changing back to CLOB for master at https://github.com/owncloud/core/pull/22878. Input welcome…

**Comment by LukasReschke** [comment]
@willyaranda Any chance that you could test the update again with https://github.com/owncloud/core/pull/22878 applied on top of it?

**Comment by willyaranda** [comment]
yeah, it is just apply the patch?

**Comment by LukasReschke** [comment]
@willyaranda Yes. Get the 8.2 instance back, then update to 9.0 RC2 with that patch applied on top. This would be utmost appreciated. :rocket:

**Comment by willyaranda** [comment]
ok, so i will try when I'm back home as I need to mount the DB backup.

Will report in 2-3 hours. Thanks guys!

**Comment by LukasReschke** [comment]
Thanks. That's really awesome of you to do and very welcome!

**Comment by cmonteroluque** [comment]
@willyaranda please let us know as soon as you've had a chance. I merged the PRs but I'd like to get your feedback also.

**Comment by willyaranda** [comment]
Reported on the PR that this makes the upgrade going correctly and Calendar app in Mac is syncing correctly (but not on CalDAV, what is the new URL?)

**Comment by MorrisJobke** [comment]
> Reported on the PR that this makes the upgrade going correctly and Calendar app in Mac is syncing correctly (but not on CalDAV, what is the new URL?)

Thanks for the feedback :)

The old URLs should still work. Otherwise I would like you to open a new issue. (and note down which android app you use to sync the calendar)
