### ISSUE TITLE
Federated sharing: cannot upload if user quota is unlimited

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#22882]
### Steps to reproduce
1. Set up new OC 9.0 RC 2: `OC1`
2. Set user quota to `unlimited`
3. Share folder to other owncloud session `OC2` (tested with OC 8.1.5, OC 8.2.2) with write permissions
4. Upload files via webinterface of `OC2`
5. I can upload directly to `OC1`

### Expected behaviour
Upload file

### Actual behaviour
In `OC2` I get the message `not enough storage available`.
If I change the quota of the user in `OC1` to a value other than `unlimited` I can upload.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache + mod_php

**Database:** MySQL

These are some default setups, just from the archive-files (+APCU) and external storage support enabled. Tried the same with a OC 9.0 RC1 on a Debian 8+apache+mod_php7.0.4(dotdeb)+redis. Exactly the same. If you can't reproduce it, I can give more specification or access to the setup.

#### Owncloud logfile
`OC1`:
````
{"reqId":"z0PAMMWLaT6lNp\/EisUt","remoteAddr":"my-ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/oc9\\\/public.php(74): require_once('\\\/var\\\/www\\\/oc9\\\/ap...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-03-05T11:49:03+00:00","method":"PROPFIND","url":"\/oc9\/public.php\/webdav\/"}
{"reqId":"4Fl7MeTdmf+6933cySYX","remoteAddr":"my-ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/oc9\\\/public.php(74): require_once('\\\/var\\\/www\\\/oc9\\\/ap...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-03-05T11:49:03+00:00","method":"PROPFIND","url":"\/oc9\/public.php\/webdav\/"}
````
`OC2`: nothing

when a quota is set and the upload is successful:
`OC1`:
````
{"reqId":"MhvG2TIdSIPGyekjaoNa","remoteAddr":"my-ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/oc9\\\/public.php(74): require_once('\\\/var\\\/www\\\/oc9\\\/ap...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-03-05T11:53:13+00:00","method":"PROPFIND","url":"\/oc9\/public.php\/webdav\/"}
{"reqId":"SCPAbTWx3eoMT2ndRC9G","remoteAddr":"my-ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name copy could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('copy')\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(336): Sabre\\\\DAV\\\\Server->getPropertiesForPath('copy', Array, 0)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/oc9\\\/public.php(74): require_once('\\\/var\\\/www\\\/oc9\\\/ap...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":166,\"User\":false}","level":0,"time":"2016-03-05T11:53:14+00:00","method":"PROPFIND","url":"\/oc9\/public.php\/webdav\/copy"}
{"reqId":"ZwFE9VmXT5u9+9BpqqpK","remoteAddr":"my-ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name copy could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('copy')\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(336): Sabre\\\\DAV\\\\Server->getPropertiesForPath('copy', Array, 0)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/oc9\\\/public.php(74): require_once('\\\/var\\\/www\\\/oc9\\\/ap...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":166,\"User\":false}","level":0,"time":"2016-03-05T11:53:14+00:00","method":"PROPFIND","url":"\/oc9\/public.php\/webdav\/copy"}
{"reqId":"dnukELiTwusUTFg5XQi7","remoteAddr":"my-ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name copy could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('copy')\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(336): Sabre\\\\DAV\\\\Server->getPropertiesForPath('copy', Array, 0)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/oc9\\\/public.php(74): require_once('\\\/var\\\/www\\\/oc9\\\/ap...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":166,\"User\":false}","level":0,"time":"2016-03-05T11:53:14+00:00","method":"PROPFIND","url":"\/oc9\/public.php\/webdav\/copy"}
{"reqId":"wQkikk9hgIPgAONGQpzf","remoteAddr":"my-ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name copy could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('copy')\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(336): Sabre\\\\DAV\\\\Server->getPropertiesForPath('copy', Array, 0)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/oc9\\\/public.php(74): require_once('\\\/var\\\/www\\\/oc9\\\/ap...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":166,\"User\":false}","level":0,"time":"2016-03-05T11:53:14+00:00","method":"PROPFIND","url":"\/oc9\/public.php\/webdav\/copy"}
{"reqId":"h\/AeuVpR9fDOTNQwUBOy","remoteAddr":"my-ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name copy could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('copy')\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(336): Sabre\\\\DAV\\\\Server->getPropertiesForPath('copy', Array, 0)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/oc9\\\/public.php(74): require_once('\\\/var\\\/www\\\/oc9\\\/ap...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":166,\"User\":false}","level":0,"time":"2016-03-05T11:53:14+00:00","method":"PROPFIND","url":"\/oc9\/public.php\/webdav\/copy"}
{"reqId":"HvRYhxaYbYy+wqxT5+mA","remoteAddr":"my-ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/oc9\\\/public.php(74): require_once('\\\/var\\\/www\\\/oc9\\\/ap...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-03-05T11:53:16+00:00","method":"PROPFIND","url":"\/oc9\/public.php\/webdav\/"}
````

**Comment by PVince81** [comment]
That looks like a regression, likely caused by the change from https://github.com/owncloud/core/issues/19988, because fed sharing uses Webdav.

Now Webdav returns -3 for unlimited quota, so we need to adjust the DAV client code to understand that.

**Comment by PVince81** [comment]
This is bad, it breaks federated sharing. Setting to critical.

**Comment by PVince81** [comment]
Okay, uploading through Webdav works, it's only the web UI that doesn't understand that "-3" means infinite quota.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/22898

**Comment by PVince81** [comment]
CC @cmonteroluque

**Comment by PVince81** [comment]
Older OC versions also affected when connecting to an OC 9.0 instance: https://github.com/owncloud/core/issues/23547
