### ISSUE TITLE
Bug: Cannot connect to mySQL server using SSL via CA cert for PDO

### ISSUE THREAD

**Issue by Letterus** [owncloud/core#22938]
### Steps to reproduce
1. Enable using SSL for the mySQL/PDO connection using the following setting in `config.php`:
   `
   'dbdriveroptions' => array(
           PDO::MYSQL_ATTR_SSL_CA => '/cloud/data/sqlca.pem',
   ),`
2. Connect to your ownCloud instance using the browser.
3. Try to login or use the ownCloud client.
### Expected behaviour

You should get logged in/client shoud work.
### Actual behaviour

You get an 'internal server error'.
Error log see below.
### Server configuration

**Operating system**:
Linux 3.16.0-4-amd64 (SMP) x86_64

**Web server:**
Apache 2 at SSL.

**Database:**
mySQL 5.5

**PHP version:**
PHP Version 5.6.18 via fcgi

Configured as:

```
'./configure' '--prefix=/usr/local/php56' '--with-config-file-path=/etc/php56/cgi' '--with-gd' '--with-jpeg-dir' '--with-png-dir' '--with-zlib' '--enable-ftp' '--enable-gd-native-ttf' '--with-db4' '--with-ldap' '--enable-bcmath' '--enable-calendar' '--with-imap' '--with-bz2' '--enable-sockets' '--with-kerberos' '--with-imap-ssl' '--with-freetype-dir' '--with-curl' '--with-mysql=mysqlnd' '--with-mhash' '--with-gdbm' '--with-pgsql' '--with-gettext' '--with-mcrypt' '--with-openssl' '--with-pear=/usr/local/lib/php' '--enable-exif' '--enable-zip' '--disable-cli' '--enable-soap' '--enable-mbstring' '--with-xsl' '--with-xmlrpc' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-pdo-pgsql' '--enable-sysvshm' '--enable-shmop' '--with-mssql' '--enable-pcntl' '--enable-htscanner' '--with-tidy' '--enable-intl' '--enable-sysvsem' '--enable-sysvmsg' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--enable-opcache' '--with-pdo-odbc=unixODBC,/usr'
```

**ownCloud version:** (see ownCloud admin page)
8.2.2 Community

**Updated from an older ownCloud or fresh install:**
Fresh install.

**Where did you install ownCloud from:**
Shared hosting installer.

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, sftp.

**Are you using encryption:** yes/no
Yes.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.
#### Web server error log

```
[Tue Mar 08 11:08:41.799385 2016] [fcgid:warn] [pid 30106]  mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
[Tue Mar 08 11:08:41.799401 2016] [fcgid:warn] [pid 30106]  mod_fcgid: stderr: #0 /cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SHOW FULL TABLE...')
[Tue Mar 08 11:08:41.799404 2016] [fcgid:warn] [pid 30106]  mod_fcgid: stderr: #1 /cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\\DBAL\\Driver\\PDOConnection->query('SHOW FULL TABLE...')
[Tue Mar 08 11:08:41.799408 2016] [fcgid:warn] [pid 30106]  mod_fcgid: stderr: #2 /cloud/lib/private/db/connection.php(182): Doctrine\\DBAL\\Connection->executeQuery('SHOW FULL TABLE...', Array, Array, NULL)
[Tue Mar 08 11:08:41.799410 2016] [fcgid:warn] [pid 30106]  mod_fcgid: stderr: #3 /cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): OC\\DB\\Connection->executeQuery('SHOW FULL TABLE...', Array, Array)
[Tue Mar 08 11:08:41.799414 2016] [fcgid:warn] [pid 30106]  mod_fcgid: stderr: #4 /cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(219): Doctrine\\DBAL\\Conne in /cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
```
#### ownCloud log (data/owncloud.log)

```
# {"reqId":"w8sqlWZg4+4HPPnc\/XgF","remoteAddr":"109.90.216.128","app":"PHP","message":"PDOStatement::execute(): Error reading result set's header at \/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2016-03-08T10:07:37+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"} {"reqId":"w8sqlWZg4+4HPPnc\/XgF","remoteAddr":"109.90.216.128","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT * FROM `oc_storages` WHERE `id` = ?' with params [\\\"adc27de703e6304d2065efb95da94127\\\"]:\\n\\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM `...', Array)\\n#2 \\\/cloud\\\/lib\\\/private\\\/db\\\/statementwrapper.php(73): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/cloud\\\/lib\\\/private\\\/db.php(147): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/cloud\\\/lib\\\/private\\\/files\\\/cache\\\/storage.php(81): OC_DB::executeAudited('SELECT * FROM `...', Array)\\n#5 \\\/cloud\\\/lib\\\/private\\\/files\\\/cache\\\/storage.php(58): OC\\\\Files\\\\Cache\\\\Storage::getStorageById('adc27de703e6304...')\\n#6 \\\/cloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(86): OC\\\\Files\\\\Cache\\\\Storage->__construct(Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#7 \\\/cloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(317): OC\\\\Files\\\\Cache\\\\Cache->__construct(Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#8 \\\/cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(391): OC\\\\Files\\\\Storage\\\\Common->getCache('', Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#9 \\\/cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(391): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache('', Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#10 \\\/cloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(391): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache('', Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#11 \\\/cloud\\\/lib\\\/private\\\/files\\\/view.php(1233): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache('')\\n#12 \\\/cloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/serverfactory.php(119): OC\\\\Files\\\\View->getFileInfo('')\\n#13 [internal function]: OC\\\\Connector\\\\Sabre\\\\ServerFactory->OC\\\\Connector\\\\Sabre\\\\{closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#15 \\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#16 \\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/cloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/cloud\\\/remote.php(137): require_once('/...')\\n#19 {main}\",\"File\":\"\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":4,"time":"2016-03-08T10:07:37+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"} 
```

**Comment by PVince81** [comment]
Is this still an issue with OC 9.0 or 9.1 which have an upgraded Doctrine lib ?
