### ISSUE TITLE
[Failed update] Some files have not passed the integrity check

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#22979]
### Steps to reproduce
1. Update ownCloud via repositories (no occ command)
2. Run the update again but this time including the occ command

### Expected behaviour
No errors

### Actual behaviour
http://pastebin.com/EsApXFmR

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2.4
**Database:**
MySQL 5.5
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**
Updated from 8,2,2
**Where did you install ownCloud from:**
Repositories (ownCloud)
**Signing status (ownCloud 9.0 and above):**

http://pastebin.com/EsApXFmR

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - gallery
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocf4eb7ef1b5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "familjenpettersson.se"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/familjenpettersson.se\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "hostmaster",
        "mail_domain": "familjenpettersson.se",
        "mail_smtphost": "mail.citynetwork.se",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "forceSSLforSubdomains": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "app.mail.server-side-cache.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstore.experimental.enabled": true,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### ownCloud log (data/owncloud.log)
```
{"reqId":"nOHKErM4jbYRMdYTfMuC","remoteAddr":"","app":"PHP","message":"file_put_contents(\/var\/www\/owncloud\/data\/.htaccess): failed to open stream: Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#458","level":3,"time":"2016-03-09T00:46:16+00:00","method":"--","url":"--"}
{"reqId":"nOHKErM4jbYRMdYTfMuC","remoteAddr":"","app":"core","message":"No update found at the ownCloud appstore for app 166054","level":0,"time":"2016-03-09T00:46:37+00:00","method":"--","url":"--"}
{"reqId":"nOHKErM4jbYRMdYTfMuC","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"App can't be installed because it is not compatible with this version of ownCloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(201): OC_Installer::checkAppsIntegrity(Array, '\\\/tmp\\\/oc_tmp_2K0...', '\\\/tmp\\\/oc_tmp_Tk4...', false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(254): OC_Installer::updateApp(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(528): OC_Installer::updateAppByOCSId('169116')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(332): OC\\\\Updater->upgradeAppStoreApps(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(215): OC\\\\Updater->doUpgrade('9.0.0.19', '8.2.2.2')\\n#5 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/upgrade.php(225): OC\\\\Updater->upgrade()\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#11 \\\/var\\\/www\\\/owncloud\\\/console.php(88): OC\\\\Console\\\\Application->run()\\n#12 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php\",\"Line\":382}","level":3,"time":"2016-03-09T00:46:40+00:00","method":"--","url":"--"}
{"reqId":"4W2C+FvyI8Q9BddQYATC","remoteAddr":"212.107.137.215","app":"PHP","message":"OCP\\AutoloadNotAllowedException: Autoload path not allowed: \/var\/www\/owncloud\/apps\/dav\/lib\/connector\/sabre\/exceptionloggerplugin.php at \/var\/www\/owncloud\/lib\/autoloader.php#152","level":3,"time":"2016-03-09T00:47:04+00:00"}

```

**Comment by enoch85** [comment]
Issue solved by going making a backup of data & config dir then delete ownCloud and download the tar package and exctract. Then go to the Appstore and update it manually. cc @oparoz 

Keeping it open just in case.

**Comment by oparoz** [comment]
I'm guessing you've download a tar package which didn't include Gallery?

**Comment by enoch85** [comment]
@oparoz Correct.

**Comment by enoch85** [comment]
Feel free to close btw.
