### ISSUE TITLE
CalDAV is broken after Update to OC 9.0.0

### ISSUE THREAD

**Issue by freaknils** [owncloud/core#22996]
After a Upgrade to Owncloud 9.0.0 the same error like (https://github.com/owncloud/core/issues/21461) occurs!
### Steps to reproduce
1. Install Owncloud 9.0.0
2. Use a CalDAV/CardDav Client

### Actual behaviour
```
{"reqId":"IZIn8lGApvgs6EPBTxW+","remoteAddr":"<IP removed>","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/carddav.php(75): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/remote.php(138): require_once('\\\/usr\\\/share\\\/weba...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-03-09T09:16:23+00:00","method":"PROPFIND","url":"\/remote.php\/carddav\/"}
{"reqId":"4BFWyew2\/aVxf6bvZx3P","remoteAddr":"<IP removed>","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(75): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/remote.php(138): require_once('\\\/usr\\\/share\\\/weba...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-03-09T09:16:23+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/"}
```

### Server configuration
Archlinux 4.4.3-1-ARCH

**Web server:**
Nginx 1.9.12

**Database:**
Postgresql 9.5.1

**PHP version:**
PHP 7.0.4

**ownCloud version:** 
Owncloud: 9.0.0

**Updated from an older ownCloud or fresh install:**
Updated from OC 8.2.2

**Where did you install ownCloud from:**
[Archlinux Packages](https://www.archlinux.org/packages/community/any/owncloud/)

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

```
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /usr/share/webapps/owncloud/lib/private/db/connection.php:54
Stack trace:
#0 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /usr/share/webapps/owncloud/lib/private/db/connection.php(137): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /usr/share/webapps/owncloud/lib/private/db/connectionfactory.php(116): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /usr/share/webapps/owncloud/lib/private/server.php(362): OC\DB\ConnectionFactory->getConnection('pgsql', Array)
#8 /usr/share/webapps/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /usr/share/webapps/owncloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /usr/share/webapps/owncloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /usr/share/webapps/owncloud/lib/private/server.php(881): OC\ServerContainer->query('DatabaseConnect...')
#12 /usr/share/webapps/owncloud/lib/private/server.php(258): OC\Server->getDatabaseConnection()
#13 /usr/share/webapps/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /usr/share/webapps/owncloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('AppConfig')
#15 /usr/share/webapps/owncloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /usr/share/webapps/owncloud/lib/private/server.php(820): OC\ServerContainer->query('AppConfig')
#17 /usr/share/webapps/owncloud/lib/private/server.php(407): OC\Server->getAppConfig()
#18 /usr/share/webapps/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#19 /usr/share/webapps/owncloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('AppManager')
#20 /usr/share/webapps/owncloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#21 /usr/share/webapps/owncloud/lib/private/server.php(1058): OC\ServerContainer->query('AppManager')
#22 /usr/share/webapps/owncloud/lib/private/app.php(251): OC\Server->getAppManager()
#23 /usr/share/webapps/owncloud/lib/private/app.php(103): OC_App::getEnabledApps()
#24 /usr/share/webapps/owncloud/lib/base.php(572): OC_App::loadApps(Array)
#25 /usr/share/webapps/owncloud/lib/base.php(1103): OC::init()
#26 /usr/share/webapps/owncloud/console.php(46): require_once('/usr/share/weba...')
```

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => '<removed>',
  'passwordsalt' => '<removed>',
  'secret' => '<removed>',
  'trusted_domains' =>
  array (
    0 => '<removed>',
  ),
  'datadirectory' => '/usr/share/webapps/owncloud/data',
  'overwrite.cli.url' => 'https://<removed>.de',
  'dbtype' => 'pgsql',
  'version' => '9.0.0.19',
  'dbname' => 'ownclouddb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '<removed>',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'theme' => '',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
);
```
**Are you using encryption:** yes

### Client configuration
**Browser:** Firefox 44.0.2

**Operating system:** Archlinux 4.4.4-1-ARCH

#### Web server error log
```
2016/03/09 10:25:06 [error] 880#880: *118455 open() "/usr/share/webapps/owncloud/favicon.ico" failed (2: No such file or directory), client: <removed>, server: <removed>, request: "GET /favicon.ico HTTP/2.0", host: "<removed>"
2016/03/09 10:25:06 [error] 880#880: *118455 open() "/usr/share/webapps/owncloud/favicon.ico" failed (2: No such file or directory), client: <removed>, server: <removed>, request: "GET /favicon.ico HTTP/2.0", host: "<removed>"
2016/03/09 10:29:37 [error] 880#880: *118455 access forbidden by rule, client: <removed>, server: <removed>, request: "GET /data/.ocdata HTTP/2.0", host: "<removed>"
2016/03/09 10:29:54 [error] 880#880: *118455 access forbidden by rule, client: <removed>, server: <removed>, request: "GET /data/.ocdata HTTP/2.0", host: "<removed>"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"4BFWyew2\/aVxf6bvZx3P","remoteAddr":"<removed>","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(75): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/remote.php(138): require_once('\\\/usr\\\/share\\\/weba...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-03-09T09:16:23+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/"}
{"reqId":"VaRSzQPzTSi4tHCYZzJd","remoteAddr":"","app":"cron","message":"Failed to connect to the database: An exception occured in driver: could not find driver","level":4,"time":"2016-03-09T09:20:01+00:00","method":"--","url":"--"}
{"reqId":"cq7FIp3lrEOZUPAghm8q","remoteAddr":"","app":"cron","message":"Failed to connect to the database: An exception occured in driver: could not find driver","level":4,"time":"2016-03-09T09:25:01+00:00","method":"--","url":"--"}
{"reqId":"FBzZ9rt0PIdfvgMjkxky","remoteAddr":"","app":"cron","message":"Failed to connect to the database: An exception occured in driver: could not find driver","level":4,"time":"2016-03-09T09:30:01+00:00","method":"--","url":"--"}
```

Everything in Browser works well. Even the CalDAV and Cron fails.

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /usr/share/webapps/owncloud/lib/private/db/connection.php:54 Stack trace: #0 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect() #1 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion() #2 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform() #3 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform() #4

strange - looks like the postgres driver is not available ....

**Comment by freaknils** [comment]
But it is there. Via the webinterface everything works fine.

**Comment by DeepDiver1975** [comment]
> But it is there. Via the webinterface everything works fine.

Sure - I got that - this is what is call 'strange' :wink:

**Comment by PVince81** [comment]
See also https://github.com/owncloud/core/issues/22988

**Comment by freaknils** [comment]
Sorry my fault!

I use nginx and the DAV-URI had changed but I did not change the rewrite in nginx config.

Thanks!

**Comment by bitsandnumbers** [comment]
@freaknils What did you change about the DAV-URI in nginx.conf ? I have the same issue here...

**Comment by freaknils** [comment]
My changes in the relevant nginx config was:
 	rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
 	rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
 	rewrite ^/caldav(.*)$ /remote.php/dav$1 redirect;
 	rewrite ^/carddav(.*)$ /remote.php/dav$1 redirect;

**Comment by bitsandnumbers** [comment]
thanks @freaknils
