### ISSUE TITLE
[8.2.2] Root directory in mounted CIFS/SMB over Files external app have only read-only rights 

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#23001]
Ref: https://github.com/owncloud/gallery/issues/504

Expected behavior:
Open the gallery app and see the images that are available on mounted devices:

Actual behavior:
Nothing is displayed and the only message is on the web browser:
"Unknown error (22) for smb://10.1.10.103/carlos/.nomedia (500)

Try to create an .nomedia over the webUI and is not allowed. not even other files or folders.

Example: creating Test.txt :
```
{"reqId":"sqCQcv2LyOKeBSwHIho2","remoteAddr":"91.11.102.80","app":"index","message":"Exception: {"Exception":"Icewind\SMB\Exception\Exception","Message":"Unknown error (22) for smb://10.1.10.103/carlos/Test.txt","Code":22,"Trace":"
#0 /var/www/html/owncloud/apps/files_external/3rdparty/icewind/smb/src/NativeState.php(72): Icewind\SMB\NativeState->handleError('smb://10.1.10.1...')
#1 /var/www/html/owncloud/apps/files_external/3rdparty/icewind/smb/src/NativeState.php(180): Icewind\SMB\NativeState->testResult(false, 'smb://10.1.10.1...')
#2 /var/www/html/owncloud/apps/files_external/3rdparty/icewind/smb/src/NativeShare.php(105): Icewind\SMB\NativeState->stat('smb://10.1.10.1...')
#3 /var/www/html/owncloud/apps/files_external/3rdparty/icewind/smb/src/NativeShare.php(100): Icewind\SMB\NativeShare->getStat('/Test.txt')
#4 /var/www/html/owncloud/apps/files_external/lib/smb.php(102): Icewind\SMB\NativeShare->stat('/Test.txt')
#5 /var/www/html/owncloud/apps/files_external/lib/smb.php(290): OC\Files\Storage\SMB->getFileInfo('Test.txt')
#6 /var/www/html/owncloud/lib/private/files/storage/wrapper/wrapper.php(212): OC\Files\Storage\SMB->file_exists('Test.txt')
#7 /var/www/html/owncloud/lib/private/files/storage/wrapper/availability.php(225): OC\Files\Storage\Wrapper\Wrapper->file_exists('Test.txt')
#8 /var/www/html/owncloud/lib/private/files/storage/wrapper/wrapper.php(212): OC\Files\Storage\Wrapper\Availability->file_exists('Test.txt')
#9 /var/www/html/owncloud/lib/private/files/storage/wrapper/wrapper.php(212): OC\Files\Storage\Wrapper\Wrapper->file_exists('Test.txt')
#10 /var/www/html/owncloud/lib/private/files/view.php(1023): OC\Files\Storage\Wrapper\Wrapper->file_exists('Test.txt')
#11 /var/www/html/owncloud/lib/private/files/view.php(439): OC\Files\View->basicOperation('file_exists', '/Ext-Sally/Test...')
#12 /var/www/html/owncloud/lib/private/files/filesystem.php(688): OC\Files\View->file_exists('/Ext-Sally/Test...')
#13 /var/www/html/owncloud/apps/files/ajax/newfile.php(66): OC\Files\Filesystem::file_exists('/Ext-Sally/Test...')
#14 /var/www/html/owncloud/lib/private/route/route.php(154) : runtime-created function(1): require_once('/var/www/html/o...')
#15 [internal function]: __lambda_func(Array)
#16 /var/www/html/owncloud/lib/private/route/router.php(291): call_user_func('?lambda_797', Array)
#17 /var/www/html/owncloud/lib/base.php(851): OC\Route\Router->match('/apps/files/aja...')
#18 /var/www/html/owncloud/index.php(39): OC::handleRequest()
#19 {main}","File":"/var/www/html/owncloud/apps/files_external/3rdparty/icewind/smb/src/NativeState.php","Line":66}","level":3,"time":"2016-03-09T10:38:45+01:00","method":"POST","url":"/index.php/apps/files/ajax/newfile.php"}
```

Workaround is to create the .nomedia file direct over the SMB device.

```
ii  php5-libsmbclient                                     0.5.0-10.1                                          amd64        libsmbclient-php is a PHP extension that uses Samba's libsmbclient
```

My server stack:

• Operating system (name and version number):
```
Ubuntu 14.04.3 LTS
```

• URL from your ownCloud
https://cloud.damken.com/

• Your ownCloud availability:
over internet

• Webserver (name and version number):
```
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Oct 14 2015 14:20:21
```

• Apache modules enabled as declared in:
```
access_compat.load
auth_basic.load
authz_core.load
autoindex.conf
deflate.load
env.load
mime.conf
mpm_prefork.load
php5.conf
setenvif.conf
ssl.conf
status.load
alias.conf
authn_core.load
authz_host.load
autoindex.load
dir.conf
filter.load
mime.load
negotiation.conf
php5.load
setenvif.load
ssl.load
alias.load
authn_file.load
authz_user.load
deflate.conf
dir.load
headers.load
mpm_prefork.conf
negotiation.load
rewrite.load
socache_shmcb.load
status.conf
```

• Database (name and version number):
```
mysql  Ver 15.1 Distrib 5.5.46-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Connection id:          578875
Current database:
Current user:           root@localhost
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         5.5.46-MariaDB-1ubuntu0.14.04.2 (Ubuntu)
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    utf8
Conn.  characterset:    utf8
UNIX socket:            /var/run/mysqld/mysqld.sock
Uptime:                 22 days 7 hours 3 min 20 sec

Threads: 2  Questions: 176832246  Slow queries: 1  Opens: 159  Flush tables: 2  Open tables: 122  Queries per second avg: 91.803
--------------
```

• PHP (version number):
```
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

• PHP cache manager
```
Package: redis-server
Status: install ok installed
Priority: optional
Section: database
Installed-Size: 744
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: redis
Version: 2:2.8.4-2
Depends: libc6 (>= 2.14), libjemalloc1 (>= 2.1.1), redis-tools (= 2:2.8.4-2), adduser
Conffiles:
 /etc/default/redis-server 45e997df22f4c5c2b5c9ae159775a089
 /etc/redis/redis.conf e79ac99a5236e6ab3faf86bdd99affaf
 /etc/redis/sentinel.conf a95ae9b0242a03c5b4dd1af934478895
 /etc/init.d/redis-server 387b03762e0cf0db194e961104137b5a
 /etc/logrotate.d/redis-server 06755b99ef70d62a56cff94cbfc36de7
Description: Persistent key-value database with network interface
 Redis is a key-value database in a similar vein to memcache but the dataset
 is non-volatile. Redis additionally provides native support for atomically
 manipulating and querying data structures such as lists and sets.
 .
 The dataset is stored entirely in memory and periodically flushed to disk.
Original-Maintainer: Chris Lamb <lamby@debian.org>
Homepage: http://redis.io/
```

• PHP installed packages
```
libapache2-mod-php5 -> 5.5.9+dfsg-1ubuntu4.14
php-gettext -> 1.0.11-1
php-pear -> 5.5.9+dfsg-1ubuntu4.14
php5 -> 5.5.9+dfsg-1ubuntu4.14
php5-apcu -> 4.0.7-1build1~ubuntu14.04.1
php5-cgi -> 5.5.9+dfsg-1ubuntu4.14
php5-cli -> 5.5.9+dfsg-1ubuntu4.14
php5-common -> 5.5.9+dfsg-1ubuntu4.14
php5-curl -> 5.5.9+dfsg-1ubuntu4.14
php5-dev -> 5.5.9+dfsg-1ubuntu4.14
php5-gd -> 5.5.9+dfsg-1ubuntu4.14
php5-imagick -> 3.1.2-1build1
php5-intl -> 5.5.9+dfsg-1ubuntu4.14
php5-json -> 1.3.2-2build1
php5-libsmbclient -> 0.5.0-10.1
php5-mcrypt -> 5.4.6-0ubuntu5
php5-mysql -> 5.5.9+dfsg-1ubuntu4.14
php5-readline -> 5.5.9+dfsg-1ubuntu4.14
phpmyadmin -> 4:4.0.10-1
pkg-php-tools -> 1.11
```

• ownCloud Enterprise Server Version
```
{"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":""}
```

• Did you install your ownCloud with TAR files or packages?
TAR

• Tell us your migration path of the ownCloud software
8.1.0.8 -> 8.1.3.0 -> 8.1.4 -> 8.2.2

• Do you have records from your migration steps?
No

• List of owncloud-apps enabled/ in use:
```
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - delete_confirmation: 1.1.0
  - direct_menu: 0.5
  - documents: 0.11.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_mv: 0.8.1a
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - ownnote: 1.05
  - provisioning_api: 0.3.0
  - registration: 0.1.0
  - sharelinks: 1.0.1
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updater: 0.6
```

• The content of your config/config.php:
```
<?php
$CONFIG = array (
  'instanceid' => 'XXXXXX',
  'passwordsalt' => 'XXXXXX',
  'secret' => 'XXXXXX',
  'trusted_domains' =>
  array (
    0 => 'cloud.damken.com',
  ),
  'datadirectory' => '/mnt/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'XXXXXX',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXXXX',
  'dbpassword' => 'XXXXXX',
  'loglevel' => 0,
  'logtimezone' => 'Europe/Berlin',
  'log_rotate_size' => 10485760,
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'XXXXXX',
  'mail_domain' => 'damken.com',
  'mail_smtpsecure' => 'XXXXXX',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'XXXXXX',
  'mail_smtphost' => 'damken.com',
  'mail_smtpport' => 'XXXXXX',
  'mail_smtpname' => 'XXXXXX',
  'mail_smtppassword' => 'XXXXXX',
  'theme' => 'damken',
  'maintenance' => false,
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'appstore.experimental.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'trashbin_retention_obligation' => 'auto',
);
```

• Storage type and setup
```
NFS-> 
10.1.10.102:/mnt/md1/public/owncloud  /mnt/owncloud nfs soft,intr,rsize=8192,wsize=8192
```

• External storage type and setup
![capture1](https://cloud.githubusercontent.com/assets/7264495/12822225/4baf7f2a-cb67-11e5-867f-b61ab8066999.PNG)

**Comment by LukasReschke** [comment]
cc @icewind1991

**Comment by oparoz** [comment]
The key here is : 
>Try to create an .nomedia over the webUI and is not allowed. not even other files or folders.

which implies that the folder is read-only from the GUI.

**Comment by cdamken** [comment]
Thanks @LukasReschke  and @oparoz 

Same behavior is in 8.2.2 with WND 

@MorrisJobke 

00004932

**Comment by MorrisJobke** [comment]
@icewind1991 I wonder where this .nomedia is coming from/why it is needed.

**Comment by oparoz** [comment]
@MorrisJobke - Gallery looks for that file to determine if it should ignore that folder and with this setup, the filesystem doesn't even allow looking for it. I don't think it's important for this bug, it's just how it was uncovered.

**Comment by cdamken** [comment]
> @icewind1991 I wonder where this .nomedia is coming from/why it is needed.

Anyway, the main problem here is that I don't have rights to save in the root folder, I can save in one level deeper without problems

**Comment by MorrisJobke** [comment]
Maybe related to https://github.com/icewind1991/SMB/issues/45?

**Comment by oparoz** [comment]
Hmm... I think it's a different issue.

@cdamken - Which errors do you get in the browser logs when trying to create a file? On 9.0 There should be a clear error message sent by DAV.

**Comment by PVince81** [comment]
Googling "smbclient error 22" points at "Invalid argument", not sure if related.

@icewind1991 can you help identify what error 22 means ?

**Comment by PVince81** [comment]
Could it be a generic problem with dot files on SMB/CIFS ?

CC @jmaciasportela in case you have clues too

**Comment by icewind1991** [comment]
> @icewind1991 can you help identify what error 22 means ?

"Invalid argument" (They are [error.h](http://www.virtsync.com/c-error-codes-include-errno) error codes)

**Comment by PVince81** [comment]
Cannot reproduce. The gallery app works for me on SMB.

If I create a file ".nomedia" inside the share, the gallery app stops showing albums and tells they're private, which is expected.

**Comment by PVince81** [comment]
@cdamken is this still happening with 8.2.5 or 9.0.2 ?

**Comment by cdamken** [comment]
@PVince81 
> Cannot reproduce. The gallery app works for me on SMB.
> 
> If I create a file ".nomedia" inside the share, the gallery app stops showing albums and tells they're private, which is expected.

I'm still in 8.2.3 (Sorry :smile: ) but the error is the following here:

I have to create directly the file .nomedia in the storage:
```
sally:/DataVolume/shares/carlos# ls -la
total 256
drwxrwxrwx 4 carlos share 65536 Mar  1 04:24 .
drwxrwxr-x 8 root   share 65536 Aug  9  2013 ..
-rwxrw-r-- 1 carlos share     0 Jan  8 13:26 .nomedia
drwxrwxr-x 6 carlos share 65536 Sep 11  2015 Seagate
drwxrwxrwx 5 carlos share 65536 Dec 20 07:41 Western Digital
```
and then it works for the gallery app.

The problem is: I can create files in the folders and subfolder in  `Seagate` and `Western Digital`
but not in the root folder:
```
{"reqId":"KQJmPPF7vZWXc/hnxDko","remoteAddr":"93.202.88.105","app":"index","message":"Exception: {"Exception":"Icewind\SMB\Exception\Exception","Message":"Unknown error (22) for smb://10.1.10.103/carlos/Test.txt","Code":22,"Trace":"
#0 /var/www/html/owncloud/apps/files_external/3rdparty/icewind/smb/src/NativeState.php(72): Icewind\SMB\NativeState->handleError('smb://10.1.10.1...')
#1 /var/www/html/owncloud/apps/files_external/3rdparty/icewind/smb/src/NativeState.php(180): Icewind\SMB\NativeState->testResult(false, 'smb://10.1.10.1...')
#2 /var/www/html/owncloud/apps/files_external/3rdparty/icewind/smb/src/NativeShare.php(105): Icewind\SMB\NativeState->stat('smb://10.1.10.1...')
#3 /var/www/html/owncloud/apps/files_external/3rdparty/icewind/smb/src/NativeShare.php(100): Icewind\SMB\NativeShare->getStat('/Test.txt')
#4 /var/www/html/owncloud/apps/files_external/lib/smb.php(102): Icewind\SMB\NativeShare->stat('/Test.txt')
#5 /var/www/html/owncloud/apps/files_external/lib/smb.php(290): OC\Files\Storage\SMB->getFileInfo('Test.txt')
#6 /var/www/html/owncloud/lib/private/files/storage/wrapper/wrapper.php(212): OC\Files\Storage\SMB->file_exists('Test.txt')
#7 /var/www/html/owncloud/lib/private/files/storage/wrapper/availability.php(225): OC\Files\Storage\Wrapper\Wrapper->file_exists('Test.txt')
#8 /var/www/html/owncloud/lib/private/files/storage/wrapper/wrapper.php(212): OC\Files\Storage\Wrapper\Availability->file_exists('Test.txt')
#9 /var/www/html/owncloud/lib/private/files/storage/wrapper/wrapper.php(212): OC\Files\Storage\Wrapper\Wrapper->file_exists('Test.txt')
#10 /var/www/html/owncloud/lib/private/files/view.php(1023): OC\Files\Storage\Wrapper\Wrapper->file_exists('Test.txt')
#11 /var/www/html/owncloud/lib/private/files/view.php(439): OC\Files\View->basicOperation('file_exists', '/Ext-Sally/Test...')
#12 /var/www/html/owncloud/lib/private/files/filesystem.php(688): OC\Files\View->file_exists('/Ext-Sally/Test...')
#13 /var/www/html/owncloud/apps/files/ajax/newfile.php(66): OC\Files\Filesystem::file_exists('/Ext-Sally/Test...')
#14 /var/www/html/owncloud/lib/private/route/route.php(154) : runtime-created function(1): require_once('/var/www/html/o...')
#15 [internal function]: __lambda_func(Array)
#16 /var/www/html/owncloud/lib/private/route/router.php(291): call_user_func('?lambda_2883', Array)
#17 /var/www/html/owncloud/lib/base.php(851): OC\Route\Router->match('/apps/files/aja...')
#18 /var/www/html/owncloud/index.php(39): OC::handleRequest()
#19 {main}","File":"/var/www/html/owncloud/apps/files_external/3rdparty/icewind/smb/src/NativeState.php","Line":66}","level":3,"time":"2016-06-24T14:36:44+02:00","method":"POST","url":"/index.php/apps/files/ajax/newfile.php"}
```

I will upgrade now to test it in the 8.2.5

**Comment by PVince81** [comment]
@cdamken did it work with 8.2.6 ?

**Comment by PVince81** [comment]
Closing due to lack of feedback.

@cdamken please reopen if the problem still exists in 8.2.8
