### ISSUE TITLE
8.2 -> 9.0 failed ("Doctrine\DBAL\DBALException: Failed to connect to the database... " 

### ISSUE THREAD

**Issue by mistersixt** [owncloud/core#23013]
Running Debian Wheezy 64 Bit with PHP-5.6.19, lighttpd 1.4.31, sqlite database engine.

When trying to manual upgrade from 8.2 to 9.0 (not via any package system, doing it manually) I get back this:
```
$ php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checking whether the database schema for <activity> can be updated (this can take a long time depending on the database size)
Checking whether the database schema for <files_sharing> can be updated (this can take a long time depending on the database size)
Checking whether the database schema for <files_trashbin> can be updated (this can take a long time depending on the database size)
Checked database schema update for apps
Updating database schema
Updated database
Disabled incompatible app: calendar
Disabled 3rd-party app: calendar
Disabled incompatible app: contacts
Disabled 3rd-party app: contacts
Disabled 3rd-party app: files_videoviewer
Disabled 3rd-party app: ownnote
Disabled 3rd-party app: updater
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 0.8
Updating <files_texteditor> ...
Updated <files_texteditor> to 2.1
Updating <gallery> ...
Updated <gallery> to 14.5.0
Updating <files> ...
Updated <files> to 1.4.4
Updating <activity> ...
Updated <activity> to 2.2.1
Updating <encryption> ...
Updated <encryption> to 1.2.0
Updating <files_sharing> ...
Updated <files_sharing> to 0.9.1
Updating <files_trashbin> ...
Updated <files_trashbin> to 0.8.0
Updating <files_versions> ...
Updated <files_versions> to 1.2.0
Update 3rd-party app: calendar
Update 3rd-party app: contacts
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred while executing 'PRAGMA journal_mode = WAL':

SQLSTATE[HY000]: General error: 10 disk I/O error
Update failed
Maintenance mode is kept active
Reset log level
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 10 disk I/O error' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('UPDATE "oc_file...', Array)
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(984): Doctrine\DBAL\Driver\PDOConnection->prepare('UPDATE "oc_file...')
#2 /var/www/owncloud/lib/private/db/connection.php(205): Doctrine\DBAL\Connection->executeUpdate('UPDATE "oc_file...', Array, Array)
#3 /var/www/owncloud/lib/private/lock/dblockingprovider.php(263): OC\DB\Connection->executeUpdate('UPDATE `*PREFIX...', Array)
#4 [internal function]: OC\Lock\DBLockingProvider->releaseAll()
#5 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[HY000]: General error: 10 disk I/O error' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:7 in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php on line 85
$ 
```

So restored my backup from 8.2 for now.

Kind regards, Joerg.

**Comment by RealRancor** [comment]
@mistersixt Its highly advised to switch to MySQL or Postgresql

**Comment by nickvergessen** [comment]
`General error: 10 disk I/O error`

Seems like nothing we can do about, right @DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
> Seems like nothing we can do about, right @DeepDiver1975 ?

no 

@mistersixt please rerun the upgrade process until it finally works - there is nothing we can do - THX

**Comment by mistersixt** [comment]
I've just migrated from sqlite to MySql... so cannot try to reproduce anything right now. Thanks anyway,

regards, Joerg.

**Comment by pellenilsson** [comment]
I had the exact same problem. I'm pretty sure it's not a disk I/O problem, despite the error message. Just as for @mistersixt, the last log line before the error was `Update 3rd-party app: contacts`, so maybe the bug is triggered by using the contacts app with a sqlite database.

I'm running Debian Jessie with PHP 5.6.19 and Apache 2.4.10 and tried to upgrade from 8.2 to 9.0.1.

I also overcame the problem by switching to MySQL before upgrading.
