### ISSUE TITLE
Make publicwebdav.php more robust

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#23041]
I have seen many of these on a 8.2.2 instance:

```
Exception: {"Message":"Root can't be null","Exception":"InvalidArgumentException","Code":0,"Trace":"
#0 apps\/files_sharing\/publicwebdav.php(71): OC\\Files\\View->__construct(NULL)
#1 lib\/private\/connector\/sabre\/serverfactory.php(118): {closure}()
#2 [internal function]: OC\\Connector\\Sabre\\ServerFactory->OC\\Connector\\Sabre\\{closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
#3 3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)
#4 3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)
#5 3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
#6 apps\/files_sharing\/publicwebdav.php(75): Sabre\\DAV\\Server->exec()
#7 public.php(74): require_once('\/var\/www\/html\/r...')
#8 {main}","File":"lib\/private\/files\/view.php","Line":91}
```

Sadly I have not more information about the requested URL.

@LukasReschke @icewind1991 @schiesbn Could we make this more robust?

**Comment by MorrisJobke** [comment]
00005004

**Comment by LukasReschke** [comment]
This part here was added as a security hardening to core. Specifically for https://owncloud.org/security/advisory/?id=oc-sa-2015-011.

The problem there was that if "null" was passed as root all files of the sharing user would be disclosed. Pretty uncool stuff. To avoid this kind of security bug we added this to core, which also allows us now to actually notice other bugs.

So in this case this is [the following code](https://github.com/owncloud/core/blob/v8.2.2/apps/files_sharing/publicwebdav.php#L67-L71):
```php
OC_Util::setupFS($owner);
$ownerView = \OC\Files\Filesystem::getView();
$path = $ownerView->getPath($fileId);
return new \OC\Files\View($ownerView->getAbsolutePath($path));
```

What happens here is that `$ownerView->getPath($fileId)` returns `null` which is then used to setup the view. ownCloud then decides to stop processing instead of potentially delivering old files. 

The question now is why does that situation happens? These seem like Server-to-Server shares in subfolders that have been deleted on the origin server and not properly propagated (alternatively somebody is manually opening such URLs). Specifically:

1. User foo creates /1/2/3/
2. User foo shares 3 with bar on another server
3. User foo deletes 1
4. User bar accesses the share -> Request is sent and $path is `null` => ownCloud rightfully explodes.

Anyways, we need some way to handle this more gracefully. While something like the following would work it will still appear in the ownCloud error log:

```diff
diff --git a/apps/dav/appinfo/v1/publicwebdav.php b/apps/dav/appinfo/v1/publicwebdav.php
index b0ee264..e0eb26c 100644
--- a/apps/dav/appinfo/v1/publicwebdav.php
+++ b/apps/dav/appinfo/v1/publicwebdav.php
@@ -72,8 +72,12 @@ $server = $serverFactory->createServer($baseuri, $requestUri, $authBackend, func
        $path = $ownerView->getPath($fileId);
        $fileInfo = $ownerView->getFileInfo($path);
        $linkCheckPlugin->setFileInfo($fileInfo);
+       $absolutePath = $ownerView->getAbsolutePath($path);
+       if($absolutePath !== null) {
+               throw new \OCA\DAV\Connector\Sabre\Exception\Forbidden('$absolutePath cannot be null');
+       }

-       return new \OC\Files\View($ownerView->getAbsolutePath($path));
+       return new \OC\Files\View($absolutePath);
```

@icewind1991 @DeepDiver1975 Do we have any exception that will just be thrown by SabreDAV and not be logged?

**Comment by PVince81** [comment]
@Peter-Prochaska

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
