### ISSUE TITLE
"File entry could not be inserted with ..." during PUT

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#23043]
I have here a log file that contains thousands of these entries:

```
Exception: {"Message":"File entry could not be inserted with insertIfNotExist() but could also not be selected with getId() in order to perform an update. Please try again.","Exception":"RuntimeException","Code":0,"Trace":"
#0 lib/private/files/cache/scanner.php(226): OC\\Files\\Cache\\Cache->put('files/ABCDEF...', Array)
#1 lib/private/files/cache/scanner.php(189): OC\\Files\\Cache\\Scanner->addToCache('files/ABCDEF...', Array, -1)
#2 lib/private/files/cache/scanner.php(266): OC\\Files\\Cache\\Scanner->scanFile('files/ABCDEF...', 3, -1, NULL, true)
#3 lib/private/files/view.php(1202): OC\\Files\\Cache\\Scanner->scan('files/ABCDEF...', false)
#4 lib/private/connector/sabre/objecttree.php(148): OC\\Files\\View->getFileInfo('ABCDEFGHI...')
#5 3rdparty/sabre/dav/lib/DAV/CorePlugin.php(496): OC\\Connector\\Sabre\\ObjectTree->getNodeForPath('ABCDEFGHI...')
#6 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
#7 3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#8 3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)
#9 3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
#10 apps/files/appinfo/remote.php(56): Sabre\\DAV\\Server->exec()
#11 remote.php(137): require_once('/var/www/html/...')
#12 {main}","File":"lib/private/files/cache/cache.php","Line":267}
```

All of them happen during the webdav PUT. And this is a 8.2.2 instance. Nothing related to the request ID could be found in the logs.

@icewind1991 @PVince81 Any idea why this happens only then?

00005004

**Comment by PVince81** [comment]
Weird stuff.

@nickvergessen can you also join and help ?

**Comment by PVince81** [comment]
@MorrisJobke is this repeatable or is this a one-off ?

**Comment by nickvergessen** [comment]
Missing required information as asked by the issue template.

Especially DB information.

**Comment by MorrisJobke** [comment]
> @MorrisJobke is this repeatable or is this a one-off ?

It happened more often, but it's only from a log file a got. Sadly I have no more information, but thought it would be helpful nevertheless.

**Comment by MorrisJobke** [comment]
> Especially DB information.

It's a maxscale load balancer that writes to a galera mariadb cluster. The writes go only to the master instance while the reads are distributed across all nodes in the cluster.

**Comment by nickvergessen** [comment]
Can
```sql
SELECT @@GLOBAL.tx_isolation, @@tx_isolation
```
be executed and the result be posted here??

**Comment by MorrisJobke** [comment]
> be executed and the result be posted here??

I asked :)

**Comment by MorrisJobke** [comment]
@nickvergessen:

```
SELECT @@GLOBAL.tx_isolation, @@tx_isolation;
+-----------------------+-----------------+
| @@GLOBAL.tx_isolation | @@tx_isolation |
+-----------------------+-----------------+
| REPEATABLE-READ | REPEATABLE-READ |
+-----------------------+-----------------+
```

**Comment by nickvergessen** [comment]
Which does not match:
https://github.com/owncloud/core/issues/20555#issuecomment-157331571

**Comment by nickvergessen** [comment]
Closing since it's a duplicate?
