### ISSUE TITLE
No access to Users Site after Upgrade: Error 500

### ISSUE THREAD

**Issue by htwsaaraub** [owncloud/core#23045]
### Steps to reproduce
1. Log in to owncloud with an admin user
2. Click on the right side menu on the User Page

### Expected behaviour
The User Page should load.

### Actual behaviour
The Users Page could not be loaded. Error 500
I checked LDAP Configuration on the admin page. All settings are green. Both LDAP Server entries are okay. A connection could be established. I'm logged in with an LDAP User, User log in works.

request identifier: qci8pPzwQpi6mDGx2La6

### Server configuration
**Operating system**: debian 8

**Web server:** Apache/2.4.10 (Debian)

**Database:** MySQL 5.5.47-0+deb8u1 - (Debian)

**PHP version:** 5.6.17-0+deb8u1

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Updated from an older ownCloud or fresh install:** Upgrade from 8.2

**Where did you install ownCloud from:** debian packages from download.owncloud.org via apt

**Signing status (ownCloud 9.0 and above):**

```
Integrity failed: I deleted the content of the skeleton Directory to avoid copy the data in this folder, because we only have external storage in use. The users should not save there data on the owncloud server.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- core/skeleton/Documents/Example.odt
		- core/skeleton/Photos/Paris.jpg
		- core/skeleton/Photos/San Francisco.jpg
		- core/skeleton/Photos/Squirrel.jpg
	- EXTRA_FILE
		- .tag
		- .mailmap

Raw output
==========
Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [core/skeleton/Documents/Example.odt] => Array
                        (
                            [expected] => 4990a69b65fa2f34b36b622fd30eb8dc6656e5203adee1cfca1b3f592cf69028e7b1c8983c1d5d15e7906c2b039d5ca6b9fb50ec7f1d99b62f381ce726ff006b
                            [current] => 
                        )

                    [core/skeleton/Photos/Paris.jpg] => Array
                        (
                            [expected] => d1c076d8fd3637479a7bb50337deb36ad2f22a912017a188a6b3fd3458f744cb7cbece27c05683227c44072c8689dd3e2fdb21451728f70543bc59262fa4cb06
                            [current] => 
                        )

                    [core/skeleton/Photos/San Francisco.jpg] => Array
                        (
                            [expected] => 107ac5e7ebfaaf2b632c0dd2e3ca7925180fe5aec4d91579bec1a46aaac216588b7986ce352886c0062111fe912ee26eb9490c5d1b098cd0a35cf01f07bb6857
                            [current] => 
                        )

                    [core/skeleton/Photos/Squirrel.jpg] => Array
                        (
                            [expected] => 11e1baf404f0d2a1548337715e7904289ff51010438c1cdabcf6b0e34b8536af4b6e3cb3bca59be38022c70a5f3420eab4c25c4e9ca645f7527e1f6fca8202c8
                            [current] => 
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [.tag] => Array
                        (
                            [expected] => 
                            [current] => c705b8c49f2b8c93980d737a73b560bfff8a580af236236a174ada1570464904ab469c4195745619d1864832406648cd87f2d494cedcf85f946db85add5bcfdb
                        )

                    [.mailmap] => Array
                        (
                            [expected] => 
                            [current] => 71fa42ab145a19a8d9fa990b5eed243b05f6eb73d26587f0e62b0f381cab2728bbce35d4045430aa4c128fec6d62c7e01444e3494786d69a5fd5904339254bb0
                        )

                )

        )

)
```

**List of activated apps:**

```
Enabled:
  - comments: 0.2
  - dav: 0.1.5
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - activity
  - delete_confirmation
  - encryption
  - files_versions
  - gallery
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc1730d06673",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "aub-cloud",
            "aub-cloud.htwsaar.de",
            "134.96.211.97"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_from_address": "aub-cloud",
        "mail_smtpmode": "smtp",
        "mail_domain": "htwsaar.de",
        "mail_smtphost": "smtp.htwsaar.de",
        "mail_smtpport": "25",
        "enable_previews": true,
        "maintenance": false,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "htwsaar",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "updatechecker": false
    }
}
```

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
+-------------------------------+----------------------------------------------------------------------------------------------+
| Configuration                 | NEW                                                                                          |
+-------------------------------+----------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                            |
| hasPagedResultSupport         |                                                                                              |
| homeFolderNamingRule          | attr:cn                                                                                      |
| lastJpegPhotoLookup           | 0                                                                                            |
| ldapAgentName                 | CN=ADM.AUB,OU=Passwort-Admins,OU=Administratoren,DC=htw-saarland,DC=de,DC=local              |
| ldapAgentPassword             | ***                                                                                          |
| ldapAttributesForGroupSearch  |                                                                                              |
| ldapAttributesForUserSearch   |                                                                                              |
| ldapBackupHost                |                                                                                              |
| ldapBackupPort                |                                                                                              |
| ldapBase                      | DC=htw-saarland,DC=de,DC=local                                                               |
| ldapBaseGroups                | OU=Gruppen,DC=htw-saarland,DC=de,DC=local                                                    |
| ldapBaseUsers                 | DC=htw-saarland,DC=de,DC=local                                                               |
| ldapCacheTTL                  | 600                                                                                          |
| ldapConfigurationActive       | 1                                                                                            |
| ldapDynamicGroupMemberURL     |                                                                                              |
| ldapEmailAttribute            | mail                                                                                         |
| ldapExperiencedAdmin          | 0                                                                                            |
| ldapExpertUUIDGroupAttr       | cn                                                                                           |
| ldapExpertUUIDUserAttr        | cn                                                                                           |
| ldapExpertUsernameAttr        | cn                                                                                           |
| ldapGroupDisplayName          | cn                                                                                           |
| ldapGroupFilter               | (&(|(objectclass=group)))                                                                    |
| ldapGroupFilterGroups         |                                                                                              |
| ldapGroupFilterMode           | 0                                                                                            |
| ldapGroupFilterObjectclass    | group                                                                                        |
| ldapGroupMemberAssocAttr      | member                                                                                       |
| ldapHost                      | 134.96.208.XX                                                                                |
| ldapIgnoreNamingRules         |                                                                                              |
| ldapLoginFilter               | (&(|(objectclass=person))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(name=%uid)))) |
| ldapLoginFilterAttributes     | name                                                                                         |
| ldapLoginFilterEmail          | 1                                                                                            |
| ldapLoginFilterMode           | 0                                                                                            |
| ldapLoginFilterUsername       | 1                                                                                            |
| ldapNestedGroups              | 0                                                                                            |
| ldapOverrideMainServer        | 0                                                                                            |
| ldapPagingSize                | 1000                                                                                         |
| ldapPort                      | 389                                                                                          |
| ldapQuotaAttribute            |                                                                                              |
| ldapQuotaDefault              |                                                                                              |
| ldapTLS                       | 0                                                                                            |
| ldapUserDisplayName           | displayname                                                                                  |
| ldapUserDisplayName2          |                                                                                              |
| ldapUserFilter                | (|(objectclass=person))                                                                      |
| ldapUserFilterGroups          |                                                                                              |
| ldapUserFilterMode            | 0                                                                                            |
| ldapUserFilterObjectclass     | person                                                                                       |
| ldapUuidGroupAttribute        | auto                                                                                         |
| ldapUuidUserAttribute         | auto                                                                                         |
| turnOffCertCheck              | 0                                                                                            |
| useMemberOfToDetectMembership | 1                                                                                            |
+-------------------------------+----------------------------------------------------------------------------------------------+
+-------------------------------+---------------------------------------------------------------------------------+
| Configuration                 | s01                                                                             |
+-------------------------------+---------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                               |
| hasPagedResultSupport         |                                                                                 |
| homeFolderNamingRule          |                                                                                 |
| lastJpegPhotoLookup           | 0                                                                               |
| ldapAgentName                 | CN=ADM.AUB,OU=Passwort-Admins,OU=Administratoren,DC=htw-saarland,DC=de,DC=local |
| ldapAgentPassword             | ***                                                                             |
| ldapAttributesForGroupSearch  |                                                                                 |
| ldapAttributesForUserSearch   |                                                                                 |
| ldapBackupHost                |                                                                                 |
| ldapBackupPort                |                                                                                 |
| ldapBase                      | DC=htw-saarland,DC=de,DC=local                                                  |
| ldapBaseGroups                |                                                                                 |
| ldapBaseUsers                 |                                                                                 |
| ldapCacheTTL                  | 600                                                                             |
| ldapConfigurationActive       | 0                                                                               |
| ldapDynamicGroupMemberURL     |                                                                                 |
| ldapEmailAttribute            |                                                                                 |
| ldapExperiencedAdmin          | 0                                                                               |
| ldapExpertUUIDGroupAttr       | cn                                                                              |
| ldapExpertUUIDUserAttr        | cn                                                                              |
| ldapExpertUsernameAttr        | cn                                                                              |
| ldapGroupDisplayName          | cn                                                                              |
| ldapGroupFilter               |                                                                                 |
| ldapGroupFilterGroups         |                                                                                 |
| ldapGroupFilterMode           | 0                                                                               |
| ldapGroupFilterObjectclass    |                                                                                 |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                    |
| ldapHost                      | 134.96.208.XX                                                                   |
| ldapIgnoreNamingRules         |                                                                                 |
| ldapLoginFilter               |                                                                                 |
| ldapLoginFilterAttributes     |                                                                                 |
| ldapLoginFilterEmail          | 0                                                                               |
| ldapLoginFilterMode           | 0                                                                               |
| ldapLoginFilterUsername       | 1                                                                               |
| ldapNestedGroups              | 0                                                                               |
| ldapOverrideMainServer        |                                                                                 |
| ldapPagingSize                | 500                                                                             |
| ldapPort                      | 389                                                                             |
| ldapQuotaAttribute            |                                                                                 |
| ldapQuotaDefault              |                                                                                 |
| ldapTLS                       | 0                                                                               |
| ldapUserDisplayName           | displayName                                                                     |
| ldapUserDisplayName2          |                                                                                 |
| ldapUserFilter                | (&(|(objectclass=person)))                                                      |
| ldapUserFilterGroups          |                                                                                 |
| ldapUserFilterMode            | 0                                                                               |
| ldapUserFilterObjectclass     | person                                                                          |
| ldapUuidGroupAttribute        | auto                                                                            |
| ldapUuidUserAttribute         | auto                                                                            |
| turnOffCertCheck              | 0                                                                               |
| useMemberOfToDetectMembership | 1                                                                               |
+-------------------------------+---------------------------------------------------------------------------------+
+-------------------------------+----------------------------------------------------------------------------------------------+
| Configuration                 | s02                                                                                          |
+-------------------------------+----------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                            |
| hasPagedResultSupport         |                                                                                              |
| homeFolderNamingRule          | attr:cn                                                                                      |
| lastJpegPhotoLookup           | 0                                                                                            |
| ldapAgentName                 | CN=aub-cloud,OU=Dienste,DC=aub,DC=htw-saarland,DC=de,DC=local                                |
| ldapAgentPassword             | ***                                                                                          |
| ldapAttributesForGroupSearch  |                                                                                              |
| ldapAttributesForUserSearch   |                                                                                              |
| ldapBackupHost                |                                                                                              |
| ldapBackupPort                |                                                                                              |
| ldapBase                      | DC=aub,DC=htw-saarland,DC=de,DC=local                                                        |
| ldapBaseGroups                |                                                                                              |
| ldapBaseUsers                 |                                                                                              |
| ldapCacheTTL                  | 600                                                                                          |
| ldapConfigurationActive       | 1                                                                                            |
| ldapDynamicGroupMemberURL     |                                                                                              |
| ldapEmailAttribute            | mail                                                                                         |
| ldapExperiencedAdmin          | 0                                                                                            |
| ldapExpertUUIDGroupAttr       | cn                                                                                           |
| ldapExpertUUIDUserAttr        | cn                                                                                           |
| ldapExpertUsernameAttr        | cn                                                                                           |
| ldapGroupDisplayName          | cn                                                                                           |
| ldapGroupFilter               | (&(|(objectclass=group)))                                                                    |
| ldapGroupFilterGroups         |                                                                                              |
| ldapGroupFilterMode           | 1                                                                                            |
| ldapGroupFilterObjectclass    |                                                                                              |
| ldapGroupMemberAssocAttr      | member                                                                                       |
| ldapHost                      | ldaps://172.17.8.11                                                                          |
| ldapIgnoreNamingRules         |                                                                                              |
| ldapLoginFilter               | (&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                              |
| ldapLoginFilterEmail          | 1                                                                                            |
| ldapLoginFilterMode           | 1                                                                                            |
| ldapLoginFilterUsername       | 1                                                                                            |
| ldapNestedGroups              | 0                                                                                            |
| ldapOverrideMainServer        |                                                                                              |
| ldapPagingSize                | 500                                                                                          |
| ldapPort                      | 636                                                                                          |
| ldapQuotaAttribute            |                                                                                              |
| ldapQuotaDefault              |                                                                                              |
| ldapTLS                       | 0                                                                                            |
| ldapUserDisplayName           | displayName                                                                                  |
| ldapUserDisplayName2          |                                                                                              |
| ldapUserFilter                | (&(|(objectclass=person)))                                                                   |
| ldapUserFilterGroups          |                                                                                              |
| ldapUserFilterMode            | 0                                                                                            |
| ldapUserFilterObjectclass     |                                                                                              |
| ldapUuidGroupAttribute        | auto                                                                                         |
| ldapUuidUserAttribute         | auto                                                                                         |
| turnOffCertCheck              | 1                                                                                            |
| useMemberOfToDetectMembership | 1                                                                                            |
+-------------------------------+----------------------------------------------------------------------------------------------+


```

### Client configuration
**Browser: **
Google Chrome

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)

```
{"reqId":"J2ncKs+Rifbo040vc5NG","remoteAddr":"134.96.211.82","app":"index","message":"Exception: {\"Exception\":\"OC\\\\ServerNotAvailableException\",\"Message\":\"Lost connection to LDAP server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(266): OCA\\\\user_ldap\\\\lib\\\\LDAP->postFunctionCall()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(42): OCA\\\\user_ldap\\\\lib\\\\LDAP->invokeLDAPMethod('bind', Resource id #102, 'CN=aub-cloud,OU...', '0123456789abcde...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(611): OCA\\\\user_ldap\\\\lib\\\\LDAP->bind(Resource id #102, 'CN=aub-cloud,OU...', '0123456789abcde...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(538): OCA\\\\user_ldap\\\\lib\\\\Connection->bind()\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(160): OCA\\\\user_ldap\\\\lib\\\\Connection->establishConnection()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(168): OCA\\\\user_ldap\\\\lib\\\\Connection->init()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(845): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(1011): OCA\\\\user_ldap\\\\lib\\\\Access->executeSearch('(&(&(|(objectcl...', Array, Array, '500', NULL)\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(806): OCA\\\\user_ldap\\\\lib\\\\Access->search('(&(&(|(objectcl...', Array, Array, '500', NULL)\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(744): OCA\\\\user_ldap\\\\lib\\\\Access->searchGroups('(&(&(|(objectcl...', Array, '500', NULL)\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/group_ldap.php(796): OCA\\\\user_ldap\\\\lib\\\\Access->fetchListOfGroups('(&(&(|(objectcl...', Array, '500', NULL)\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/group_ldap.php(836): OCA\\\\user_ldap\\\\GROUP_LDAP->getGroupsChunk('', '500', NULL)\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/group_proxy.php(169): OCA\\\\user_ldap\\\\GROUP_LDAP->getGroups('', NULL, NULL)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/group\\\/manager.php(213): OCA\\\\user_ldap\\\\Group_Proxy->getGroups('', NULL, NULL)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/group\\\/metadata.php(188): OC\\\\Group\\\\Manager->search('')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/group\\\/metadata.php(90): OC\\\\Group\\\\MetaData->getGroups('')\\n#16 \\\/var\\\/www\\\/owncloud\\\/settings\\\/users.php(68): OC\\\\Group\\\\MetaData->get()\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 [internal function]: __lambda_func(Array)\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func('\\\\x00lambda_710', Array)\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/settings\\\/users')\\n#21 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php\",\"Line\":296}","level":3,"time":"2016-03-09T16:50:07+00:00"} {"reqId":"W9vAJoGN38poaVNOCrtu","remoteAddr":"134.96.211.82","app":"PHP","message":"Argument 7 passed to OCA\\user_ldap\\lib\\user\\Manager::__construct() must implement interface OCP\\IUserManager, instance of OCA\\user_ldap\\lib\\user\\Manager given, called in \/var\/www\/owncloud\/apps\/user_ldap\/lib\/proxy.php on line 76 and defined at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/user\/manager.php#90","level":3,"time":"2016-03-09T16:50:08+00:00"} {"reqId":"W9vAJoGN38poaVNOCrtu","remoteAddr":"134.96.211.82","app":"PHP","message":"array_filter() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/files_external\/service\/storagesservice.php#72","level":3,"time":"2016-03-09T16:50:08+00:00"} {"reqId":"HbDtb7JzaE2FV1eCwvgY","remoteAddr":"134.96.211.82","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/files_external\/lib\/config\/configadapter.php#75","level":3,"time":"2016-03-09T16:50:08+00:00"}
```

**Comment by htwsaaraub** [comment]
Here is the owncloud log

`{"reqId":"J2ncKs+Rifbo040vc5NG","remoteAddr":"134.96.211.82","app":"index","message":"Exception: {\"Exception\":\"OC\\\\ServerNotAvailableException\",\"Message\":\"Lost connection to LDAP server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(266): OCA\\\\user_ldap\\\\lib\\\\LDAP->postFunctionCall()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(42): OCA\\\\user_ldap\\\\lib\\\\LDAP->invokeLDAPMethod('bind', Resource id #102, 'CN=aub-cloud,OU...', '0123456789abcde...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(611): OCA\\\\user_ldap\\\\lib\\\\LDAP->bind(Resource id #102, 'CN=aub-cloud,OU...', '0123456789abcde...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(538): OCA\\\\user_ldap\\\\lib\\\\Connection->bind()\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(160): OCA\\\\user_ldap\\\\lib\\\\Connection->establishConnection()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(168): OCA\\\\user_ldap\\\\lib\\\\Connection->init()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(845): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(1011): OCA\\\\user_ldap\\\\lib\\\\Access->executeSearch('(&(&(|(objectcl...', Array, Array, '500', NULL)\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(806): OCA\\\\user_ldap\\\\lib\\\\Access->search('(&(&(|(objectcl...', Array, Array, '500', NULL)\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(744): OCA\\\\user_ldap\\\\lib\\\\Access->searchGroups('(&(&(|(objectcl...', Array, '500', NULL)\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/group_ldap.php(796): OCA\\\\user_ldap\\\\lib\\\\Access->fetchListOfGroups('(&(&(|(objectcl...', Array, '500', NULL)\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/group_ldap.php(836): OCA\\\\user_ldap\\\\GROUP_LDAP->getGroupsChunk('', '500', NULL)\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/group_proxy.php(169): OCA\\\\user_ldap\\\\GROUP_LDAP->getGroups('', NULL, NULL)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/group\\\/manager.php(213): OCA\\\\user_ldap\\\\Group_Proxy->getGroups('', NULL, NULL)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/group\\\/metadata.php(188): OC\\\\Group\\\\Manager->search('')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/group\\\/metadata.php(90): OC\\\\Group\\\\MetaData->getGroups('')\\n#16 \\\/var\\\/www\\\/owncloud\\\/settings\\\/users.php(68): OC\\\\Group\\\\MetaData->get()\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 [internal function]: __lambda_func(Array)\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func('\\\\x00lambda_710', Array)\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/settings\\\/users')\\n#21 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php\",\"Line\":296}","level":3,"time":"2016-03-09T16:50:07+00:00"}
{"reqId":"W9vAJoGN38poaVNOCrtu","remoteAddr":"134.96.211.82","app":"PHP","message":"Argument 7 passed to OCA\\user_ldap\\lib\\user\\Manager::__construct() must implement interface OCP\\IUserManager, instance of OCA\\user_ldap\\lib\\user\\Manager given, called in \/var\/www\/owncloud\/apps\/user_ldap\/lib\/proxy.php on line 76 and defined at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/user\/manager.php#90","level":3,"time":"2016-03-09T16:50:08+00:00"}
{"reqId":"W9vAJoGN38poaVNOCrtu","remoteAddr":"134.96.211.82","app":"PHP","message":"array_filter() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/files_external\/service\/storagesservice.php#72","level":3,"time":"2016-03-09T16:50:08+00:00"}
{"reqId":"HbDtb7JzaE2FV1eCwvgY","remoteAddr":"134.96.211.82","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/files_external\/lib\/config\/configadapter.php#75","level":3,"time":"2016-03-09T16:50:08+00:00"}
`

**Comment by RealRancor** [comment]
@htwsaaraub Please fill out the complete issue template instead of deleting it. This contains all needed infos to be able to tackle this...

**Comment by LukasReschke** [comment]
Please reopen once more information is provided.

**Comment by htwsaaraub** [comment]
Please find the requested issue template above. If you need more information, please let me know.

**Comment by htwsaaraub** [comment]
Will someone re-open this request or should I open a new one?

**Comment by Xenopathic** [comment]
@htwsaaraub Ah, you edited your comment. In future, just reply with the issue report contents, that way we get notified about it (also you should be able to re-open the issue yourself? Not sure how that works on GitHub...)

**Comment by 9662** [comment]
@htwsaaraub What does Apache's error log say?

Specifically, do you get any complaints about disallowed values in `.htaccess`? If so, and within your virtual hosts configuration if applicable, rather than the main server's, you will need to add the appropriate overrides. Something like the following may help:

```
<Directory /path/to/owncloud/installation>
  AllowOverride FileInfo Indexes Options=All,MultiViews
  Order allow,deny
  Allow from all
 </Directory>
```

Then restart Apache or reload config.

**Comment by PVince81** [comment]
Closing due to lack of feedback.
Feel free to reopen if you intend to post the required info.
