### ISSUE TITLE
There were problems with the code integrity check message - fresh ownCloud setup

### ISSUE THREAD

**Issue by wujekbogdan** [owncloud/core#23090]
### Steps to reproduce
1. Install ownCloud using the latest web installer
2. Choose MySQL during setup (I don't know if the issue is related to the database engine. I didn't try SQLite yet)
3. Create an admin account
4. Go to any page

### Expected behaviour
I should be able to star using the application

### Actual behaviour
1. An error appears at the top of the page: `There were problems with the code integrity check. More information…`
2. A blank page appears when I click the message. I can see various JS errors in the JS console.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6.16

**ownCloud version:** The latest stable. 9.0 (I'm not able to open the owncloud admin page)

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** Officjal web installer

**Signing status (ownCloud 9.0 and above):**
```
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [setup-owncloud.php] => Array
                        (
                            [expected] => 
                            [current] => d14a82180c8f1ccf28008e2079fa371492bbd3bf1dfbc6372647f047a44526b8a8c616d499e8c05fe1ad2ceb15925e859c8a1c1a6902089b8df6ba813ea531c1
                        )

                )

        )

)
```

**List of activated apps:** I didn't install any apps. This is a fresh install.

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'ochbyn0qxonu',
  'passwordsalt' => 'I1FFsQZzAJpCEXYQ/r/bt4Lf6rWSLy',
  'secret' => 'eE4qv/aP2miegebe5tCDoRFG8B05nJLYpA8NlKHpMMGx9kaW',
  'trusted_domains' => 
  array (
    0 => 'owncloud.MYDOMAIN.com',
  ),
  'datadirectory' => '/home/MY_USER_NAME/domains/MYDOMAIN.com/public_html/owncloud/data',
  'overwrite.cli.url' => 'http://owncloud.MYDOMAIN.com',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'XXX',
  'dbhost' => 'XXX',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'logtimezone' => 'UTC',
  'installed' => true,
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Browser:** Chrome 48.0.2564.116

**Operating system:** OSX 10.11.3

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VuF1rC4EU3IAAF15N@EAAADl","remoteAddr":"31.175.12.99","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_owadm\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'MY_USER_NAME_cloud'@'localhost' for table 'user'","level":3,"time":"2016-03-10T13:25:02+00:00"}
{"reqId":"VuF1rC4EU3IAAF15N@EAAADl","remoteAddr":"31.175.12.99","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `MY_USER_NAME_own` . * TO 'MY_USER_NAME_cloud'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'MY_USER_NAME_cloud'@'localhost' to database 'MY_USER_NAME_own'","level":3,"time":"2016-03-10T13:25:03+00:00"}
{"reqId":"VuF1rC4EU3IAAF15N@EAAADl","remoteAddr":"31.175.12.99","app":"PHP","message":"Undefined offset: 0 at \/home\/MY_USER_NAME\/domains\/MYDOMAIN.com\/public_html\/owncloud\/lib\/private\/setup\/mysql.php#46","level":3,"time":"2016-03-10T13:25:03+00:00"}
{"reqId":"VuF1rC4EU3IAAF15N@EAAADl","remoteAddr":"31.175.12.99","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/installer.php(621): include('\\\/home\\\/MY_USER_NAME\\\/d...')\\n#4 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/home\\\/MY_USER_NAME\\\/d...')\\n#5 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-03-10T13:25:09+00:00"}
{"reqId":"VuF1rC4EU3IAAF15N@EAAADl","remoteAddr":"31.175.12.99","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/installer.php(621): include('\\\/home\\\/MY_USER_NAME\\\/d...')\\n#4 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/home\\\/MY_USER_NAME\\\/d...')\\n#5 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/MY_USER_NAME\\\/domains\\\/MYDOMAIN.com\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-03-10T13:25:09+00:00"}
{"reqId":"VuF16S4EU3IAAF15QHkAAADv","remoteAddr":"31.175.12.99","app":"PHP","message":"Undefined index: newVersionString at \/home\/MY_USER_NAME\/domains\/MYDOMAIN.com\/public_html\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-10T13:26:01+00:00"}
{"reqId":"VuF2sy4EU3IAAGUPq2cAAAB5","remoteAddr":"31.175.12.99","app":"PHP","message":"Undefined index: newVersionString at \/home\/MY_USER_NAME\/domains\/MYDOMAIN.com\/public_html\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-10T13:29:24+00:00"}

```

#### Browser log
JS console
```
GET http://owncloud.MYDOMAIN.com/core/js/oc.js?v=2283f8413653a56b24f06ec30a36f55b 
jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAIt0ABEAAAABQDwAAQABAAAAAAAAAAAAAAAAAAAAA…CwKGBmIIpVWLACJWGwAUVjI2KwAiNEswkKAwIrswsQAwIrsxEWAwIrWbIEKAZFUkSzCxAEAisA' because it violates the following Content Security Policy directive: "font-src 'self'".
x.fn.offset @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1466(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1471(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1473
jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAI3gABIAAAABRWQAAQABAAAAAAAAAAAAAAAAAAAAA…IwnaGGIYHBlUELLMKwH6htK8MUhmKGIAYjqCImVEUgs1mBOtm1gRYpuNZmSrgAALqcEVgAAAA=' because it violates the following Content Security Policy directive: "font-src 'self'".
x.fn.offset @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1466(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1471(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1473
jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAI7kABEAAAABPbQAAQABAAAAAAAAAAAAAAAAAAAAA…hgZiCKVViwAiVhsAFFYyNisAIjRLMJCgMCK7MLEAMCK7MRFgMCK1myBCgGRVJEswsQBAIrAA==' because it violates the following Content Security Policy directive: "font-src 'self'".
x.fn.offset @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1466(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1471(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1473
jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAIw4ABEAAAABQcAAAQABAAAAAAAAAAAAAAAAAAAAA…hgZiCKVViwAiVhsAFFYyNisAIjRLMJCgMCK7MLEAMCK7MRFgMCK1myBCgGRVJEswsQBAIrAA==' because it violates the following Content Security Policy directive: "font-src 'self'".
x.fn.offset @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1466(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1471(anonymous function) @ jquery-ui.custom.js?v=2283f8413653a56b24f06ec30a36f55b:1473
shareconfigmodel.js?v=2283f8413653a56b24f06ec30a36f55b:24 Uncaught ReferenceError: oc_appconfig is not defined(anonymous function) @ shareconfigmodel.js?v=2283f8413653a56b24f06ec30a36f55b:24(anonymous function) @ shareconfigmodel.js?v=2283f8413653a56b24f06ec30a36f55b:89
js.js?v=2283f8413653a56b24f06ec30a36f55b:203 Uncaught TypeError: Cannot read property 'substring' of undefinedOC.filePath @ js.js?v=2283f8413653a56b24f06ec30a36f55b:203(anonymous function) @ viewer.js?v=2283f8413653a56b24f06ec30a36f55b:4
js.js?v=2283f8413653a56b24f06ec30a36f55b:735 Uncaught ReferenceError: oc_isadmin is not definedOC.isUserAdmin @ js.js?v=2283f8413653a56b24f06ec30a36f55b:735OCA.Files.DetailFileInfoView.extend.initialize @ systemtagsinfoview.js?v=2283f8413653a56b24f06ec30a36f55b:48Backbone.View @ backbone.js?v=2283f8413653a56b24f06ec30a36f55b:1192child @ backbone.js?v=2283f8413653a56b24f06ec30a36f55b:1852child @ backbone.js?v=2283f8413653a56b24f06ec30a36f55b:1852OCA.SystemTags.FilesPlugin.attach @ filesplugin.js?v=2283f8413653a56b24f06ec30a36f55b:34OC.Plugins.attach @ js.js?v=2283f8413653a56b24f06ec30a36f55b:843FileList.initialize @ filelist.js?v=2283f8413653a56b24f06ec30a36f55b:293FileList @ filelist.js?v=2283f8413653a56b24f06ec30a36f55b:36OCA.Files.App.initialize @ app.js?v=2283f8413653a56b24f06ec30a36f55b:67(anonymous function) @ app.js?v=2283f8413653a56b24f06ec30a36f55b:229(anonymous function) @ underscore.js?v=2283f8413653a56b24f06ec30a36f55b:768
jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6 GET http://owncloud.MYDOMAIN.com/core/js/oc.js?v=2283f8413653a56b24f06ec30a36f55b&_=1457617240188 404 (Not Found)send @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6x.extend.ajax @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6x.extend._evalUrl @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6x.fn.extend.domManip @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:5x.fn.extend.append @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:5(anonymous function) @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:5x.extend.access @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:4x.fn.extend.html @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:5(anonymous function) @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6c @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:4p.fireWith @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:4k @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6r @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6
jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:4 Uncaught SyntaxError: Unexpected identifier(anonymous function) @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:4x.extend.globalEval @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:4x.ajaxSetup.converters.text script @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6On @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6k @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6r @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6send @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6x.extend.ajax @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6x.extend._evalUrl @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6x.fn.extend.domManip @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:5x.fn.extend.append @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:5(anonymous function) @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:5x.extend.access @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:4x.fn.extend.html @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:5(anonymous function) @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6c @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:4p.fireWith @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:4k @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6r @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6
22app.js?v=2283f8413653a56b24f06ec30a36f55b:330 Uncaught TypeError: Cannot read property 'meta' of undefined(anonymous function) @ app.js?v=2283f8413653a56b24f06ec30a36f55b:330c @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:4p.fireWith @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:4k @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6r @ jquery.min.js?v=2283f8413653a56b24f06ec30a36f55b:6
```

**Comment by LukasReschke** [comment]
> setup-owncloud.php

Can you check whether that file is still existent on the file system? It should be deleted after installation. If it is not, then that's a bug that we need to fix in the PHP setup script :see_no_evil:

**Comment by wujekbogdan** [comment]
Yes. The file is still there. 
Deleting the file didn't solve the problem.

**Comment by mikebabb** [comment]
I'm having the same problem on a clean install of ownCloud 9. Like the OP, I've installed ownCloud in the root of my webserver rather than a subdirectory and I receive the message about a problem with the integrity check. Clicking "more information" takes me to `/apps/files/#security-warning`, which never loads or offers any further information.

I'm also seeing "no apps available for this version" in the apps screen, but I'm assuming that may be related to the original integrity check failure problem I'm having.

**Comment by Clickadelic** [comment]
I do get an error, close to this one, different error message, same installation procedure.
[owncloud.zip](https://github.com/owncloud/core/files/179484/owncloud.zip)

**Comment by theagencies** [comment]
I'm facing the exact same issue, both in Chrome and in Edge I may add.

**Comment by Bullnados** [comment]
Here also the same in FF the setuo-owncloud.php wasn't removed after installation

**Comment by TeddyM-DK** [comment]
I have the same problem.
I tried to install on a web hotel, so I do not have the option whereI can refresh/rescan files in console.
Without being burdened with knowledge in PHP or programming for that matter. I humble suggest a file-refresh / rescan button in the admin page.
As stated above, I have no skills in programming, I am only trying to provide alternative solution that may or may not work.

**Comment by sekmenhuseyin** [comment]
same problem happened when i installed autoinstall and manual install. and i cannot see any apps in the system, however they exists in the directory.
here is ther javascript errors:

```
GET https://cloud.sekmetech.net/core/js/oc.js?v=2283f8413653a56b24f06ec30a36f55b 404 (Not Found) apps:44 
shareconfigmodel.js?v=2283f84…:24 Uncaught ReferenceError: oc_appconfig is not defined(anonymous function) @ shareconfigmodel.js?v=2283f84…:24(anonymous function) @ shareconfigmodel.js?v=2283f84…:89
js.js?v=2283f84…:203 Uncaught TypeError: Cannot read property 'substring' of undefinedOC.filePath @ js.js?v=2283f84…:203(anonymous function) @ viewer.js?v=2283f84…:4
app.js?v=2283f84…:330 Uncaught TypeError: Cannot read property 'meta' of undefined
```

**Comment by geekonthepc** [comment]
I completed these exact same steps when I installed owncloud v9 and had the same problem. I have got to the point where I can still sync by avoiding the web panel, but cannot either see files in the web panel or access the admin page.

**Comment by rari2012** [comment]
I'm afraid to say: I do have the same issue here.
Is there any way to work around?

Thank you for any hints.
Ps: Deleted the setup file also. It's a fresh install, MySQL Database, Ubuntu Linux on a Host Europe Server

**Comment by geekonthepc** [comment]
Only solution I found was to reinstall using the traditional FTP/SSH upload installation - I simply couldn't get it to work properly using the web installer.

**Comment by PVince81** [comment]
@vicdeo can you have a look ?

**Comment by VicDeo** [comment]
@wujekbogdan @Bullnados @geekonthepc @rari2012  how did you you upladed `setup-owncloud.php`?
I mean did you chown it to `www-data` (or other user your webserver)?
Is it possible be that webserver was not able to delete the script due to lack of permissions?

**Comment by VicDeo** [comment]
@PVince81 I'm not 100% sure what causing this but good start will be to check if the file was really unlinked here
https://github.com/owncloud/administration/blob/master/web-installer/setup-owncloud.php#L328

**Comment by VicDeo** [comment]
@PVince81 Pushed https://github.com/owncloud/administration/issues/74

- [ ] Upload it to https://download.owncloud.com/download/community/setup-owncloud.php once PR is merged

**Comment by VicDeo** [comment]
@wujekbogdan @Bullnados @geekonthepc @rari2012 
Any volunteers to confirm that https://github.com/owncloud/administration/blob/fix-web-installer-self-destroy/web-installer/setup-owncloud.php 
fixes that?

**Comment by rari2012** [comment]
Hi,
Sorry for mycloud late answer.
I removed the Installation and startet frommen the sprach wohl auch neuer
Version. Not the one you provided.

I appreciate it,
Best regards
Ralf
Am 20.04.2016 19:41 schrieb "VicDeo" <notifications@github.com>:

**Comment by Bullnados** [comment]
Here also allright with new script :+1:  @VicDeo

**Comment by PVince81** [comment]
Any update ? Did the new script fix the issue for anyone else ?

**Comment by PVince81** [comment]
@VicDeo I tried the old installer from https://download.owncloud.com/download/community/setup-owncloud.php with the steps from https://github.com/owncloud/core/issues/23090#issue-139892300 but did not get any integrity check errors. ownCloud works fine.

Going to try again by setting up the permissions in a way that "setup-owncloud.php" cannot be removed.

**Comment by PVince81** [comment]
Hmm, I can't think of any way to setup permissions to allow the web server user to create/unpack ownCloud source code but at the same time prevent it to delete "setup-owncloud.php" within the same directory. It has to be the same dir, else it wouldn't display the integrity check message.

**Comment by VicDeo** [comment]
@PVince81 me too. But I see no other explanation to 
```
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [setup-owncloud.php] => Array
                        (
                            [expected] => 
                            [current] => d14a82180c8f1ccf28008e2079fa371492bbd3bf1dfbc6372647f047a44526b8a8c616d499e8c05fe1ad2ceb15925e859c8a1c1a6902089b8df6ba813ea531c1
                        )

                )

        )

)
```

except that `unlink` did not delete setup script.

**Comment by PVince81** [comment]
@VicDeo is there a situation where the `unlink` operation would try to delete it in the wrong location ? How do you find out about the script's location ?

**Comment by PVince81** [comment]
Maybe some PHP setups don't have `SCRIPT_FILENAME` properly set, or it points to the wrong location ?

**Comment by VicDeo** [comment]
@PVince81  https://github.com/owncloud/core/issues/23090#issuecomment-194892611
> I forgot to mention about it. I didn't install in the default ./owncload directory but in the . directory (the same directory as the installer script location). I don't know does it make any difference.

**Comment by PVince81** [comment]
That's what I just tested: I input "." in the field. It worked fine.

**Comment by PVince81** [comment]
Another theory is that maybe some web servers keep the file open/locked while it is being executed so the file cannot delete itself.

**Comment by PVince81** [comment]
At least it worked for @Bullnados.

@VicDeo I merged your PR https://github.com/owncloud/administration/pull/74, can you take care of the upload as per https://github.com/owncloud/core/issues/23090#issuecomment-212025902 ?

**Comment by PVince81** [comment]
Waiting for https://github.com/owncloud/administration/pull/74#issuecomment-215140595 before closing

**Comment by cmonteroluque** [comment]
asking @danimo for help with https://github.com/owncloud/core/issues/23090#issuecomment-215407298

**Comment by PVince81** [comment]
I just tested the download link and it delivers the new version: https://github.com/owncloud/administration/pull/74#issuecomment-216220515
