### ISSUE TITLE
OCA\\Files_Versions\\Hooks::write_hook: $absolutePath must be relative to "files"

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#23109]
I found following error in some logs quite often.

```
{"reqId":"...","remoteAddr":"...","app":"hook","message":"error while running hook (OCA\\Files_Versions\\Hooks::write_hook): $absolutePath must be relative to \"files\"","level":3,"time":"2016-03-09T02:37:16+01:00"}
{"reqId":"...","remoteAddr":"...","app":"webdav","message":"Exception: {\"Message\":\"HTTP/1.1 423 \\\"AES/aes.v\\\" is locked\",\"Exception\":\"OC\Connector\Sabre\Exception\FileLocked\",\"Code\":0,\"Trace\":\"
#0 3rdparty/sabre/dav/lib/DAV/Server.php(1087): OC\Connector\Sabre\File->put(Resource id #32)
#1 3rdparty/sabre/dav/lib/DAV/CorePlugin.php(501): Sabre\DAV\Server->updateFile('AES/aes.v', Resource id #32, NULL)
#2 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#3 3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#4 3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)
#5 3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#6 apps/files/appinfo/remote.php(56): Sabre\DAV\Server->exec()
#7 remote.php(137): require_once('/var/www/html/r...')
#8 {main}\",\"File\":\"lib/private/connector/sabre/file.php\",\"Line\":164}","level":4,"time":"2016-03-09T02:37:16+01:00"}
```

@schiesbn @icewind1991 Any idea why this is happening? Sadly I have not any additional information, but maybe the stack trace helps to find some issues here

00005004

**Comment by MorrisJobke** [comment]
Didn't noticed this again -> closing
