### ISSUE TITLE
Unable to login via LDAP, exception OCP\PreConditionNotMetException

### ISSUE THREAD

**Issue by mossholderm** [owncloud/core#23123]
### Steps to reproduce
1. Upgrade from 8.x to 9.0.0
2. Attempt to log in

### Expected behaviour
Login successful

### Actual behaviour
Login unsuccessful

### Server configuration
**Operating system**: CentOS 7, fully patched.

**Web server:** Apache httpd-2.4.6-40.el7.centos.x86_64

**Database:** MariaDB mariadb-5.5.44-2.el7.centos.x86_64

**PHP version:** php-5.4.16-36.el7_1.x86_64

**ownCloud version:** (see ownCloud admin page) 9.0.0 (stable)

**Updated from an older ownCloud or fresh install:** Updated.

**Where did you install ownCloud from:** Owncloud YUM repository

**Signing status (ownCloud 9.0 and above):** Good

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - announcementcenter: true
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - ownnote
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "5154b2aca4681",
        "check_for_working_htaccess": true,
        "datadirectory": "\/srv\/owncloud",
        "dbtype": "mysql",
        "dbname": "ownCloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "mysql01.mossholder.com",
        "dbtableprefix": "oc_",
        "forcessl": true,
        "installed": true,
        "loglevel": 0,
        "maintenance": false,
        "mail_from_address": "mail",
        "mail_smtpmode": "php",
        "mail_domain": "mossholder.com",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwritewebroot": "\/owncloud",
        "overwrite.cli.url": "\/owncloud",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbdriveroptions": {
            "1012": "\/etc\/ipa\/ca.crt"
        },
        "updatechecker": false,
        "trusted_domains": [
            "home.mossholder.com"
        ],
        "theme": "",
        "version": "9.0.0.19"
    }
}

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

```
+-------------------------------+---------------------------------------------+
| Configuration                 |                                             |
+-------------------------------+---------------------------------------------+
| hasMemberOfFilterSupport      |                                             |
| hasPagedResultSupport         |                                             |
| homeFolderNamingRule          | attr:uid                                    |
| lastJpegPhotoLookup           | 0                                           |
| ldapAgentName                 |                                             |
| ldapAgentPassword             | ***                                         |
| ldapAttributesForGroupSearch  |                                             |
| ldapAttributesForUserSearch   |                                             |
| ldapBackupHost                |                                             |
| ldapBackupPort                |                                             |
| ldapBase                      | dc=mossholder,dc=com                        |
| ldapBaseGroups                | cn=groups,cn=accounts,dc=mossholder,dc=com  |
| ldapBaseUsers                 | cn=users,cn=accounts,dc=mossholder,dc=com   |
| ldapCacheTTL                  | 600                                         |
| ldapConfigurationActive       | 1                                           |
| ldapDynamicGroupMemberURL     |                                             |
| ldapEmailAttribute            | mail                                        |
| ldapExperiencedAdmin          | 0                                           |
| ldapExpertUUIDGroupAttr       | ipaUniqueID                                 |
| ldapExpertUUIDUserAttr        | ipaUniqueID                                 |
| ldapExpertUsernameAttr        | uid                                         |
| ldapGroupDisplayName          | cn                                          |
| ldapGroupFilter               | (|(objectclass=posixgroup))      |
| ldapGroupFilterGroups         |                                             |
| ldapGroupFilterMode           | 1                                           |
| ldapGroupFilterObjectclass    | nestedgroup                                 |
| ldapGroupMemberAssocAttr      | uniqueMember                                |
| ldapHost                      | ldaps://ipa01.mossholder.com/               |
| ldapIgnoreNamingRules         |                                             |
| ldapLoginFilter               | (&(|(objectclass=inetorgperson))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                             |
| ldapLoginFilterEmail          | 0                                           |
| ldapLoginFilterMode           | 0                                           |
| ldapLoginFilterUsername       | 1                                           |
| ldapNestedGroups              | 1                                           |
| ldapOverrideMainServer        | 0                                           |
| ldapPagingSize                | 500                                         |
| ldapPort                      | 636                                         |
| ldapQuotaAttribute            |                                             |
| ldapQuotaDefault              |                                             |
| ldapTLS                       | 0                                           |
| ldapUserDisplayName           | displayname                                 |
| ldapUserDisplayName2          |                                             |
| ldapUserFilter                | (|(objectclass=inetorgperson))  |
| ldapUserFilterGroups          |                                             |
| ldapUserFilterMode            | 1                                           |
| ldapUserFilterObjectclass     | inetorgperson                               |
| ldapUuidGroupAttribute        | auto                                        |
| ldapUuidUserAttribute         | auto                                        |
| turnOffCertCheck              | 0                                           |
| useMemberOfToDetectMembership | 1                                           |
+-------------------------------+---------------------------------------------+
```

### Client configuration
**Browser:**  Firefox, Chrome

**Operating system:** Linux, Mac, Windows 7

#### Web server error log
```
192.251.13.62 - - [10/Mar/2016:15:50:11 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:50:41 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:51:11 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:51:41 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:52:11 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:52:41 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:11 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/index.php?logout=true&requesttoken=FQAcfCILFCMQPggACh8%2FM3c%2FPQVHOjszEQsgZRRALho%3D%3AltmMTmbmHhZnPvOy2QmghwcWSsMJE8XmV26%2B2R%2BFfZQ%3D HTTP/1.1" 302 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/ HTTP/1.1" 200 10833 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/core/vendor/jsTimezoneDetect/jstz.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/index.php/core/js/oc.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 200 2956 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/core/js/visitortimezone.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/core/js/lostpassword.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/core/js/login.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:28 -0500] "POST /owncloud/ HTTP/1.1" 200 10891 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:28 -0500] "GET /owncloud/index.php/core/js/oc.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 200 2956 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VuHeyHbCr8YW0RaWOJ2KhQAAAAQ","remoteAddr":"192.251.13.62","app":"user_ldap","message":"Exception: {\"Exception\":\"OCP\\\\PreConditionNotMetException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/allconfig.php(222): OC\\\\DB\\\\Connection->setValues('preferences', Array, Array, Array)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/user\\\/user.php(368): OC\\\\AllConfig->setUserValue('mattcm', 'user_ldap', 'displayName', 'Matt Mossholder')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/user\\\/user.php(383): OCA\\\\user_ldap\\\\lib\\\\user\\\\User->store('displayName', 'Matt Mossholder')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/user\\\/user.php(182): OCA\\\\user_ldap\\\\lib\\\\user\\\\User->composeAndStoreDisplayName('Matt Mossholder')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(732): OCA\\\\user_ldap\\\\lib\\\\user\\\\User->processAttributes(Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(705): OCA\\\\user_ldap\\\\lib\\\\Access->batchApplyUserAttributes(Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(678): OCA\\\\user_ldap\\\\lib\\\\Access->fetchListOfUsers('(&(|(objectclas...', Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(103): OCA\\\\user_ldap\\\\lib\\\\Access->fetchUsersByLoginName('mattcm', Array, 1)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(120): OCA\\\\user_ldap\\\\USER_LDAP->getLDAPUserByLoginName('mattcm')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user\\\/manager.php(183): OCA\\\\user_ldap\\\\USER_LDAP->checkPassword(*** username and password replaced ***)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(219): OC\\\\User\\\\Manager->checkPassword(*** username and password replaced ***)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user.php(162): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(1073): OC_User::login(*** username and password replaced ***)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(969): OC::tryFormLogin()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(931): OC::handleLogin()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php\",\"Line\":297}","level":3,"time":"2016-03-10T20:53:28+00:00","method":"POST","url":"\/owncloud\/"}
{"reqId":"VuHeyHbCr8YW0RaWOJ2KhQAAAAQ","remoteAddr":"192.251.13.62","app":"core","message":"Login failed: 'mattcm' (Remote IP: '192.251.13.62')","level":2,"time":"2016-03-10T20:53:28+00:00","method":"POST","url":"\/owncloud\/"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by LukasReschke** [comment]
@owncloud/ldap

**Comment by mossholderm** [comment]
Other symptoms:

- I can log in as the admin user, but none of the other accounts. 
- As admin, if I visit the Users page, the spinner just spins when trying to list "Everyone". Switching to the built in "Admins" group immediately returns the local admin account.
- occ ldap:check-user runs successfully.
- The LDAP settings in the Admin page get a green light.

**Comment by blizzz** [comment]
The Backtrace in readable:

```
{"reqId":"VuHeyHbCr8YW0RaWOJ2KhQAAAAQ","remoteAddr":"192.251.13.62","app":"user_ldap","message":"Exception: {\"Exception\":\"OCP\PreConditionNotMetException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"
#0 \/var\/www\/html\/owncloud\/lib\/private\/allconfig.php(222): OC\DB\Connection->setValues('preferences', Array, Array, Array)
#1 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(368): OC\AllConfig->setUserValue('mattcm', 'user_ldap', 'displayName', 'Matt Mossholder')
#2 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(383): OCA\user_ldap\lib\user\User->store('displayName', 'Matt Mossholder')
#3 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(182): OCA\user_ldap\lib\user\User->composeAndStoreDisplayName('Matt Mossholder')
#4 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php(732): OCA\user_ldap\lib\user\User->processAttributes(Array)
#5 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php(705): OCA\user_ldap\lib\Access->batchApplyUserAttributes(Array)
#6 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php(678): OCA\user_ldap\lib\Access->fetchListOfUsers('(&(|(objectclas...', Array)
#7 \/var\/www\/html\/owncloud\/apps\/user_ldap\/user_ldap.php(103): OCA\user_ldap\lib\Access->fetchUsersByLoginName('mattcm', Array, 1)
#8 \/var\/www\/html\/owncloud\/apps\/user_ldap\/user_ldap.php(120): OCA\user_ldap\USER_LDAP->getLDAPUserByLoginName('mattcm')
#9 \/var\/www\/html\/owncloud\/lib\/private\/user\/manager.php(183): OCA\user_ldap\USER_LDAP->checkPassword(*** username and password replaced )
#10 \/var\/www\/html\/owncloud\/lib\/private\/user\/session.php(219): OC\User\Manager->checkPassword( username and password replaced )
#11 \/var\/www\/html\/owncloud\/lib\/private\/user.php(162): OC\User\Session->login( username and password replaced )
#12 \/var\/www\/html\/owncloud\/lib\/base.php(1073): OC_User::login( username and password replaced ***)
#13 \/var\/www\/html\/owncloud\/lib\/base.php(969): OC::tryFormLogin()
#14 \/var\/www\/html\/owncloud\/lib\/base.php(931): OC::handleLogin()
#15 \/var\/www\/html\/owncloud\/index.php(39): OC::handleRequest()
#16 {main}\",\"File\":\"\/var\/www\/html\/owncloud\/lib\/private\/db\/connection.php\",\"Line\":297}","level":3,"time":"2016-03-10T20:53:28+00:00","method":"POST","url":"/owncloud/"}
```

Inserting that data to the database failed. Likely because it's there. Then, updating is attempted. This however returns 0 affected lines. Probably, because the value did not  change. However, the new Connection::setValue() throws this exception, when no rows are affected.

That's my theory for now at least. Only, I am not too fond of it, because I would have experienced the same.

@mossholderm can you post the results of ``SELECT * from oc_preference where userid = 'mattcm' and appid = 'user_ldap'`` in the database, please? 

cc @Xenopathic

**Comment by blizzz** [comment]
> I can log in as the admin user, but none of the other accounts. 

i.e. also no other local user?

**Comment by mossholderm** [comment]
Sorry, I should have been clearer... I can't log in as any LDAP user.  Admin is the only locally defined user.  Just to confirm, I created another local account, and that seems to work as well.

**Comment by mossholderm** [comment]
MariaDB [ownCloud]> SELECT * from oc_preferences where userid = 'mattcm' and appid = 'user_ldap';
+--------+-----------+--------------------+-----------------+
| userid | appid     | configkey          | configvalue     |
+--------+-----------+--------------------+-----------------+
| mattcm | user_ldap | displayName        | Matt Mossholder |
| mattcm | user_ldap | lastFeatureRefresh | 1457662793      |
+--------+-----------+--------------------+-----------------+
2 rows in set (0.00 sec)

**Comment by PatelParas** [comment]
I have never tried DisplayName ==> displayname   which have space character for ldap app:
```
| ldapUserDisplayName | displayname |
```
instead of this can you try ?:
```
samaccount or uid or objectGUID
```

**Comment by mossholderm** [comment]
Changing to uid had no noticeable impact.

**Comment by blizzz** [comment]
No, it would not have any impact, what the display name looks like does not matter. 

The only way I can see it fails is that the DB reports affectedRows as 0 here:

https://github.com/owncloud/core/blob/master/lib/private/db/connection.php#L296

I will add a patch later for further debugging, since I cannot reproduce it here (might be DB specific. I also have MariaDB, but in version 10.1). Would you be able & OK to test this? @mossholderm

**Comment by mossholderm** [comment]
Yes, I can test a patch, thanks.  Whenever you have it just let me know!

     --Matt

**Comment by Xenopathic** [comment]
I think I've got a patch that doesn't involve any DB-specific hackery, PR on the way

**Comment by Xenopathic** [comment]
@mossholderm Try the patch in #23164, you can get it in .patch form here: https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/23164.patch (ignore the changes to test files, they will probably fail to apply, the main file in lib/private/db is the only necessary one).

**Comment by mossholderm** [comment]
That did the trick!

**Comment by PVince81** [comment]
Weird. How likely would this bug be triggered in other situations ? Is LDAP the only env that can cause this ?

**Comment by blizzz** [comment]
It can happen on any DB-based config update where this is not caught.

**Comment by Xenopathic** [comment]
@PVince81 For example, if a DB user were to try to set their email or display name to the already-existing value, on some DBs that would perform an actual data update (and the DB layer would report 1 affected row), but on others the DB is smart enough to recognize that the value is unchanged, and report 0 affected rows, triggering this bug.

**Comment by suderman** [comment]
This patch helped me as well, and I'm not using LDAP. 

I upgraded from 8 to 9. Logging in would show an error and provide the login form a second time. However, hitting refresh would reveal that I successfully logged in the first time, but clearly the exception caused some confusion.

**Comment by PVince81** [comment]
I understand, but I'm surprised this didn't pop up earlier for other non-LDAP related stuff.
