### ISSUE TITLE
reset passwod  >  unhandled exception

### ISSUE THREAD

**Issue by max133** [owncloud/core#23139]
sudo -u www-data php /var/www/owncloud/occ user:resetpassword user

```
An unhandled exception has been thrown:
exception 'OCP\AutoloadNotAllowedException' with message 'Autoload path not allowed: /var/www/owncloud/config/config.php' in /var/www/owncloud/lib/autoloader.php:138
Stack trace:
#0 /var/www/owncloud/lib/autoloader.php(158): OC\Autoloader->isValidPath('/var/www/ownclo...')
#1 [internal function]: OC\Autoloader->load('OC\Config')
#2 /var/www/owncloud/lib/base.php(133): spl_autoload_call('OC\Config')
#3 /var/www/owncloud/lib/base.php(497): OC::initPaths()
#4 /var/www/owncloud/lib/base.php(1081): OC::init()
#5 /var/www/owncloud/console.php(42): require_once('/var/www/ownclo...')
#6 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#7 {main}odin@odin-server:/var/www/owncloud/config$ 
```

xubuntu 15,10
owncloud 8.2.2.2
current apache/mysql

**Comment by LukasReschke** [comment]
Please fill out the issue template. Thanks a lot.

**Comment by PVince81** [comment]
Closing due to lack of feedback
