### ISSUE TITLE
OC8->9 Upgrade Failed

### ISSUE THREAD

**Issue by yuichi-ikeda-nnetworks** [owncloud/core#23132]
### Steps to reproduce
1.yum update -y
2.OC Upgrade procedure
3.Upgrade Failed because "Exception: Error 16 interacting with memcached : NOT FOUND"

### Expected behaviour
Upgrade successful.

### Server configuration
CentOS6.7 x64

**Web server:**
Apache 2.2.15

**Database:**
Mysql-5.7.9

**PHP version:**
PHP 5.6.19
Memcached 1.4.25-1

**ownCloud version:** (see ownCloud admin page)
8.2.2->9.0.0(current)

**Updated from an older ownCloud or fresh install:**
Updeted older ownCloud.

**Where did you install ownCloud from:**
yum oc repository.

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
```json
{
    "system": {
        "instanceid": "oc0scurp4dxe",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "owncloud.ecbb.jp",
            "192.168.2.94",
            "192.168.2.246",
            "192.168.2.245"
        ],
        "datadirectory": "\/home\/owncloud",
        "overwrite.cli.url": "http:\/\/192.168.2.245\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "192.168.2.245",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "JST",
        "installed": true,
        "asset-pipeline.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "maintenance": false,
        "loglevel": 0,
        "updatechecker": false,
        "theme": ""
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Opera 34

**Operating system:**
Windows7 Home Premier x64

#### Web server error log
```
None
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"JV3+RQBFXLq5PYNEJXGR","remoteAddr":"192.168.2.166","app":"core","message":"starting upgrade from 8.2.2.2 to 9.0.0.19","level":0,"time":"2016-03-11T04:14:20+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=CScVSUURGAIUWGsMNEcJfjo1PVY8BzYkT1oobSpiGCg%3D%3AGvpb0AbVziXdLvSGCYSgHVztz%2Fc8d%2BvmN%2BcvjsWTfQs%3D"}
{"reqId":"JV3+RQBFXLq5PYNEJXGR","remoteAddr":"192.168.2.166","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Error 16 interacting with memcached : NOT FOUND\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/memcached.php(91): OC\\\\Memcache\\\\Memcached->verifyReturnCode()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/integritycheck\\\/checker.php(389): OC\\\\Memcache\\\\Memcached->remove('oc.integrityche...')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/integritycheck\\\/checker.php(502): OC\\\\IntegrityCheck\\\\Checker->cleanResults()\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/updater.php(349): OC\\\\IntegrityCheck\\\\Checker->runInstanceVerification()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/updater.php(215): OC\\\\Updater->doUpgrade('9.0.0.19', '8.2.2.2')\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/ajax\\\/update.php(120): OC\\\\Updater->upgrade()\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/memcached.php\",\"Line\":174}","level":3,"time":"2016-03-11T04:14:40+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=CScVSUURGAIUWGsMNEcJfjo1PVY8BzYkT1oobSpiGCg%3D%3AGvpb0AbVziXdLvSGCYSgHVztz%2Fc8d%2BvmN%2BcvjsWTfQs%3D"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by gdurin** [comment]
I have the very same problem under Ubuntu 14.04

**Comment by insertjokehere** [comment]
Same issue here: "Exception: Error 16 interacting with memcached : NOT FOUND"

**Comment by PVince81** [comment]
@icewind1991 @Xenopathic @MorrisJobke @nickvergessen

**Comment by MorrisJobke** [comment]
@yuichi-ikeda-nnetworks @insertjokehere @gdurin Are you sure, that memcached is running? This error is usually thrown, when the memcached instance could not be found/connected to.

**Comment by MorrisJobke** [comment]
Sorry I was wrong. It means, that the requested object could not be found: http://docs.libmemcached.org/client_errors/MEMCACHED_NOTFOUND.html#MEMCACHED_NOTFOUND

@LukasReschke It's in the integrity checker code (see stack trace)

**Comment by nickvergessen** [comment]
I'm on it

**Comment by nickvergessen** [comment]
Fix in https://github.com/owncloud/core/pull/23218

**Comment by insertjokehere** [comment]
I can confirm that applying to diff in 9190885b4e0bdcec4c7f3fafd3f0eb2dd727c716 lets me complete the upgrade. Obviously the integrety check is giving a warning for lib/private/memcache/memcached.php, but I can live with that until 9.0.1 is released. Thanks @nickvergessen!
