### ISSUE TITLE
Argument 8 passed to OC\Core\Avatar\AvatarController::__construct() must be an instance of OCP\Files\Folder, null given

### ISSUE THREAD

**Issue by sbryf** [owncloud/core#23158]
Hi there,

I am getting the following error in the log:

Argument 8 passed to OC\Core\Avatar\AvatarController::__construct() must be an instance of OCP\Files\Folder, null given, called in /core/application.php on line 90 and defined at /core/avatar/avatarcontroller.php#86

OwnCloud 8.2.3
Encryption on
Shared webhoster
PHP 5.5.28

Any idea how to fix that? Seems to be related to $c->query('UserFolder'), right?

Thanks.

**Comment by LukasReschke** [comment]
Can you please fill out the whole issue template? Thanks a lot.

**Comment by PVince81** [comment]
@rullzer

**Comment by rullzer** [comment]
> Seems to be related to $c->query('UserFolder'), right?

Yes but I don't see how that would break all of a sudden.

@sbryf can you fill out the whole issue template?

**Comment by sbryf** [comment]
### Steps to reproduce
Not sure how to reproduce this. Happens straight after I login - I am getting three error messages in the log regarding this with same content. Same when I switch to Profile or Admin - 2 error messages in the log.

### Expected behaviour
No error message

### Actual behaviour
Error message raised

### Server configuration
**Operating system:** Webhoster - domainfactory

**Web server:** Apache

**Database:** MySQL 5.6.19

**PHP version:** 5.5.28

**ownCloud version:** 8.2.3

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** web installer

**Signing status (ownCloud 9.0 and above):** n/a

**List of activated apps:**

Activity
Default encryption module
Deleted files
First Run Wizard
Gallery
Mail Template Editor
Notifications
PDF Viewer
Provisioning API
Share Files
Text Editor
Updater
Versions
Video Viewer

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => '...',
  'passwordsalt' => '...',
  'secret' => '...',
  'trusted_domains' => 
  array (
    0 => '...'
  ),
  'datadirectory' => '.../data',
  'overwrite.cli.url' => '...',
  'dbtype' => 'mysql',
  'version' => '8.2.3.2',
  'dbname' => '...',
  'dbhost' => '...',
  'dbtableprefix' => 'oc_',
  'dbuser' => '...',
  'dbpassword' => '...',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'noreply',
  'mail_smtpmode' => 'php',
  'mail_domain' => '...',
  'loglevel' => 1,
);


**Are you using external storage, if yes which one:** n/a

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** n/a

### Client configuration
**Browser:** Latest Chrome

**Operating system:** Windows 10

### Logs
#### Web server error log

n/a

#### ownCloud log (data/owncloud.log)

{"reqId":"Vukjf38AAAEAABCDOc8AAAAM","remoteAddr":"...","app":"PHP","message":"Argument 8 passed to OC\\Core\\Avatar\\AvatarController::__construct() must be an instance of OCP\\Files\\Folder, null given, called in .../core\/application.php on line 90 and defined at .../core\/avatar\/avatarcontroller.php#86","level":3,"time":"2016-03-16T09:12:31+00:00"}
{"reqId":"VukjgX8AAAEAABB3SUEAAAAA","remoteAddr":"...","app":"PHP","message":"Argument 8 passed to OC\\Core\\Avatar\\AvatarController::__construct() must be an instance of OCP\\Files\\Folder, null given, called in .../core\/application.php on line 90 and defined at .../core\/avatar\/avatarcontroller.php#86","level":3,"time":"2016-03-16T09:12:33+00:00"}
{"reqId":"Vukjhn8AAAEAABCPh-QAAAAY","remoteAddr":"...","app":"PHP","message":"Argument 8 passed to OC\\Core\\Avatar\\AvatarController::__construct() must be an instance of OCP\\Files\\Folder, null given, called in .../core\/application.php on line 90 and defined at .../core\/avatar\/avatarcontroller.php#86","level":3,"time":"2016-03-16T09:12:38+00:00"}
{"reqId":"VukkGn8AAAEAABCI714AAAAR","remoteAddr":"...","app":"PHP","message":"Argument 8 passed to OC\\Core\\Avatar\\AvatarController::__construct() must be an instance of OCP\\Files\\Folder, null given, called in .../core\/application.php on line 90 and defined at .../core\/avatar\/avatarcontroller.php#86","level":3,"time":"2016-03-16T09:15:06+00:00"}
{"reqId":"VukkHH8AAAEAABCo1bYAAAAf","remoteAddr":"...","app":"PHP","message":"Argument 8 passed to OC\\Core\\Avatar\\AvatarController::__construct() must be an instance of OCP\\Files\\Folder, null given, called in .../core\/application.php on line 90 and defined at .../core\/avatar\/avatarcontroller.php#86","level":3,"time":"2016-03-16T09:15:08+00:00"}
{"reqId":"VuklHH8AAAEAABCtn4YAAAAi","remoteAddr":"...","app":"PHP","message":"Argument 8 passed to OC\\Core\\Avatar\\AvatarController::__construct() must be an instance of OCP\\Files\\Folder, null given, called in .../core\/application.php on line 90 and defined at .../core\/avatar\/avatarcontroller.php#86","level":3,"time":"2016-03-16T09:19:25+00:00"}
{"reqId":"VuklLn8AAAEAABDFrdkAAAAs","remoteAddr":"...","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at .../lib\/private\/template\/functions.php:1) at .../lib\/private\/appframework\/http\/output.php#60","level":3,"time":"2016-03-16T09:19:42+00:00"}
{"reqId":"VuklLn8AAAEAABDFrdkAAAAs","remoteAddr":"...","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at .../lib\/private\/template\/functions.php:1) at .../lib\/private\/appframework\/http\/output.php#60","level":3,"time":"2016-03-16T09:19:42+00:00"}
{"reqId":"VuklLn8AAAEAABDFrdkAAAAs","remoteAddr":"...","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at .../lib\/private\/template\/functions.php:1) at .../lib\/private\/appframework\/http\/output.php#60","level":3,"time":"2016-03-16T09:19:42+00:00"}
{"reqId":"VuklLn8AAAEAABDFrdkAAAAs","remoteAddr":"...","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at .../lib\/private\/template\/functions.php:1) at .../lib\/private\/appframework\/http\/output.php#60","level":3,"time":"2016-03-16T09:19:42+00:00"}

#### Browser log

a) The javascript console log

Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.

**Comment by DeepDiver1975** [comment]
This happens if an avatar is requested when no user is logged in afaik

**Comment by PVince81** [comment]
Is this still happening ?

**Comment by sergeyun** [comment]
yes its still happening for owncloud 9.1.4

**Comment by PVince81** [comment]
Can someone enable XDebug and try again ? This should give a full stack trace in the logs which should help pinpoint the more precise code path leading to this error.

Does it happen for a specific user / specific avatar ? Or all users ?

**Comment by kdslkdsaldsal** [comment]
@PVince81 Noticed the same here today on 9.1.4. My owncloud.log seems to contain way more details, is that enough to debug this further (don't want to install and enable XDebug on my productive machine).

``
{"reqId":"UcDRfax5iK7VdCYuTn8w","remoteAddr":"xxxx","app":"index","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 8 passed to OC\\\\Core\\\\Controller\\\\AvatarController::__construct() must implement interface OCP\\\\Files\\\\Folder, null given, called in \\\/var\\\/www\\\/owncloud\\\/core\\\/Application.php on line 96\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/core\\\/Application.php(96): OC\\\\Core\\\\Controller\\\\AvatarController->__construct('core', Object(OC\\\\AppFramework\\\\Http\\\\Request), Object(OC\\\\AvatarManager), Object(OC\\\\Cache\\\\File), Object(OC\\\\L10N\\\\L10N), Object(OC\\\\User\\\\Manager), Object(OC\\\\User\\\\Session), NULL, Object(OC\\\\Log))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Core\\\\Application->OC\\\\Core\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(102): Pimple\\\\Container->offsetGet('AvatarControlle...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(82): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('AvatarControlle...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('AvatarControlle...', 'getAvatar', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#5 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/avatar\\\/User\\\/...')\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/AvatarController.php\",\"Line\":81}","level":3,"time":"2017-04-04T17:56:21+02:00","method":"GET","url":"\/avatar\/User\/32","user":"--"}
``

**Comment by PVince81** [comment]
In general it looks like it might be trying to use the avatar folder and for some reason it doesn't exist.
Is your data folder inside of ownCloud or outside ?

If outside, maybe the setupFS code didn't mount the user's home yet properly so the avatar code doesn't work in this specific code path.

**Comment by kdslkdsaldsal** [comment]
My data folder is located within the ownCloud installation folder /var/www/owncloud/data

**Comment by PVince81** [comment]
How often does this happen ? Does it happen for a specific user ?

**Comment by PVince81** [comment]
closing due to lack of feedback.

It is possible that it was due to a lowercase vs uppercase avatar name, which is a known issue that has been fixed in https://github.com/owncloud/core/pull/26398

**Comment by darootler** [comment]
Can anyone repoen this ticket and describe what information is needed? See also https://github.com/nextcloud/polls/issues/251

Regards
Richard

**Comment by PVince81** [comment]
> How often does this happen ? Does it happen for a specific user ?

But also, if everyone could use the issue template for their own posts, it would help cross-reference some potential environment issues

**Comment by darootler** [comment]
Like described in https://github.com/nextcloud/polls/issues/251 this error happens every time i access the newly created poll.

Regards
Richard

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by darootler** [comment]
I already descibed the issue, what infos are needed?

Regards
Richard

**Comment by kdslkdsaldsal** [comment]
@darootler See the comment in https://github.com/owncloud/core/issues/23158#issuecomment-346601029 which explains what information are missing.

**Comment by PVince81** [comment]
Can someone try on 10.0.4 and debug this ?

**Comment by darootler** [comment]
I think all the needed information is here --> https://github.com/nextcloud/polls/issues/251

If not, please just tell me what information is needed in detail.

Regards
Richard

**Comment by kdslkdsaldsal** [comment]
@darootler Please open https://github.com/owncloud/core/issues/new, copy the template from the new comment field in a new comment here and fill it out. This would be the required information needed in detail.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
