### ISSUE TITLE
Regression: Login fails for direct "App" access from external (Android) app.

### ISSUE THREAD

**Issue by fbartels** [owncloud/core#23184]
The issue has previously been discussed at https://github.com/owncloud/news/issues/936, https://github.com/owncloud/News-Android-App/issues/499 and https://github.com/Fmstrat/ownnote/issues/286

### Steps to reproduce
1. Have owncloud 9 with users in ldap and the owncloud news app installed
2. install owncloud news app for android and try to login

according to above tickets the same was also happening with the "ownnote" app and also when using owncloud 8.2.3. (I only did an upgrade from 8.1.x to 9.0, so I cannot speak for 8.2.3 myself)

### Expected behaviour
Android app should login and display/sync content of the owncloud app.

### Actual behaviour
Login fails

A workaround seems to be to remove the cors headers as happened in https://github.com/Fmstrat/ownnote/commit/b0254fcf24b262ef90e822a48d24e3bbf8491e89, but this makes the app vulnerable to CSRF attacks according to https://github.com/owncloud/news/issues/936#issuecomment-195716374 .

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** MySQL 5.5

**PHP version:** 5.5.9

**ownCloud version:** 9.0

**Updated from an older ownCloud or fresh install:** Update from 8.1

**Where did you install ownCloud from:** official apt repo

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**List of activated apps:** 
```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_markdown: 0.1
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: 7.1.2
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - calendar
  - encryption
  - imprint
  - search_lucene
  - tasks
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocs4bjhrchzz",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.101.100\/owncloud",
        "trusted_domains": [
            "192.168.101.100"
        ],
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "overwritehost": "xxx.de",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "customclient_android": "http:\/\/f-droid.org\/repository\/browse\/?fdfilter=owncloud&fdid=com.owncloud.android",
        "mail_smtpmode": "smtp",
        "mail_from_address": "support",
        "mail_domain": "xxx.de",
        "mail_smtpauth": 1,
        "mail_smtphost": "xxx.de",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "theme": "",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "maintenance": false
    }
}

```

**Are you using external storage, if yes which one:** sftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

```
+-------------------------------+---------------------------------------------------------------------+
| Configuration                 |                                                                     |
+-------------------------------+---------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                   |
| hasPagedResultSupport         |                                                                     |
| homeFolderNamingRule          |                                                                     |
| lastJpegPhotoLookup           | 0                                                                   |
| ldapAgentName                 | cn=Manager,dc=xxx,dc=de                                |
| ldapAgentPassword             | ***                                                                 |
| ldapAttributesForGroupSearch  |                                                                     |
| ldapAttributesForUserSearch   |                                                                     |
| ldapBackupHost                |                                                                     |
| ldapBackupPort                |                                                                     |
| ldapBase                      | dc=xxx,dc=de                                           |
| ldapBaseGroups                | dc=xxx,dc=de                                           |
| ldapBaseUsers                 | dc=xxx,dc=de                                           |
| ldapCacheTTL                  | 600                                                                 |
| ldapConfigurationActive       | 1                                                                   |
| ldapDynamicGroupMemberURL     |                                                                     |
| ldapEmailAttribute            | mail                                                                |
| ldapExperiencedAdmin          | 1                                                                   |
| ldapExpertUUIDGroupAttr       |                                                                     |
| ldapExpertUUIDUserAttr        |                                                                     |
| ldapExpertUsernameAttr        | mail                                                                |
| ldapGroupDisplayName          | cn                                                                  |
| ldapGroupFilter               | (&(|(objectclass=organization)))                                    |
| ldapGroupFilterGroups         |                                                                     |
| ldapGroupFilterMode           | 1                                                                   |
| ldapGroupFilterObjectclass    | organization                                                        |
| ldapGroupMemberAssocAttr      | uniqueMember                                                        |
| ldapHost                      | 192.168.101.103                                                     |
| ldapIgnoreNamingRules         |                                                                     |
| ldapLoginFilter               | (&(|(objectclass=mailUser))(|(mailPrimaryAddress=%uid)(mail=%uid))) |
| ldapLoginFilterAttributes     |                                                                     |
| ldapLoginFilterEmail          | 1                                                                   |
| ldapLoginFilterMode           | 1                                                                   |
| ldapLoginFilterUsername       | 0                                                                   |
| ldapNestedGroups              | 0                                                                   |
| ldapOverrideMainServer        | 0                                                                   |
| ldapPagingSize                | 500                                                                 |
| ldapPort                      | 389                                                                 |
| ldapQuotaAttribute            |                                                                     |
| ldapQuotaDefault              |                                                                     |
| ldapTLS                       | 0                                                                   |
| ldapUserDisplayName           | cn                                                                  |
| ldapUserDisplayName2          |                                                                     |
| ldapUserFilter                | (&(objectclass=mailUser)(enabledService=owncloud))                  |
| ldapUserFilterGroups          |                                                                     |
| ldapUserFilterMode            | 1                                                                   |
| ldapUserFilterObjectclass     | mailUser                                                            |
| ldapUuidGroupAttribute        | auto                                                                |
| ldapUuidUserAttribute         | auto                                                                |
| turnOffCertCheck              | 0                                                                   |
| useMemberOfToDetectMembership | 1                                                                   |
```

### Client configuration
**Browser:** works in webbrowser

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"B\/ii95aVHYgNeU85B4hv","remoteAddr":"xx.xx.xx.xx","app":"user_ldap","message":"Error when searching:  code ","level":3,"time":"2016-03-10T06:10:25+00:00"}
{"reqId":"B\/ii95aVHYgNeU85B4hv","remoteAddr":"xx.xx.xx.xx","app":"user_ldap","message":"Attempt for Paging?  ","level":3,"time":"2016-03-10T06:10:25+00:00"}
{"reqId":"B\/ii95aVHYgNeU85B4hv","remoteAddr":"xx.xx.xx.xx","app":"user_ldap","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"No user available for the given login name.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(120): OCA\\\\user_ldap\\\\USER_LDAP->getLDAPUserByLoginName('test@example.or...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user\\\/manager.php(183): OCA\\\\user_ldap\\\\USER_LDAP->checkPassword(*** username and password replaced ***)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(219): OC\\\\User\\\\Manager->checkPassword(*** username and password replaced ***)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/security\\\/corsmiddleware.php(91): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/middlewaredispatcher.php(92): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\CORSMiddleware->beforeController(Object(OCA\\\\News\\\\Controller\\\\UtilityApiController), 'version')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\News\\\\Controller\\\\UtilityApiController), 'version')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\UtilityApiController), 'version')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('UtilityApiContr...', 'version', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/api\\\/...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Line\":105}","level":3,"time":"2016-03-10T06:10:25+00:00"}
{"reqId":"B\/ii95aVHYgNeU85B4hv","remoteAddr":"xx.xx.xx.xx","app":"core","message":"Login failed: 'test@example.org' (Remote IP: 'xx.xx.xx.xx')","level":2,"time":"2016-03-10T06:10:25+00:00"}
```

**Comment by PVince81** [comment]
There was another issue in core where someone had to remove CORS, but I can't seem to find it.

@LukasReschke any idea ?

**Comment by PVince81** [comment]
Might be related to https://github.com/owncloud/core/issues/22893 which has the following fix: https://github.com/owncloud/core/pull/22901

**Comment by fbartels** [comment]
Hi,

thanks for looking into this.

I undid the manual workaround and applied the patch from #22901. problem still exists afterwards.

**Comment by fbartels** [comment]
I don't really understand how the ticket workflow is organised here. While #23248 (which is a duplicate of this one imho) has a label, milestone and assignee (but no further comments) this ticket here is unclassified until now.

**Comment by PVince81** [comment]
I was hoping that someone would find the duplicate and you did.

Closing as duplicate of https://github.com/owncloud/core/issues/23248
