### ISSUE TITLE
Clicking thumbnails in activity panel will 404 your request (file not found)

### ISSUE THREAD

**Issue by goopen** [owncloud/core#23331]
Hello,
Recent upgrade from owncloud 8.2 to 9.0 404's thumbnails in activity panel when clicking on them. Looks as if something is borked when checking the logfile since it says `open() "/var/www/owncloud404` which is wierd since the directory name is `owncloud` and not `owncloud404`. Might be expected tho.

### Steps to reproduce
1. Upload a picture via webgui/mobile/client
2. Check activity (www.example.com/index.php/apps/activity/)
3. Click recently added picture
4. Error 404

```
File not found
The specified document has not been found on the server.
You can click here to return to ownCloud.
```

### Expected behaviour
Clicking the thumbnail should display the picture for you.

### Actual behaviour
Clicking the thumnail will 404 the file you are looking for.

### Server configuration
**Operating system**: 
Ubuntu 14.04.3

**Web server:**
`nginx version: nginx/1.4.6 (Ubuntu)`

**Database:**
`mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.3`

**PHP version:**
`PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)`

**ownCloud version:** (see ownCloud admin page)
owncloud 9.0

**Updated from an older ownCloud or fresh install:**
Updated from 8.2

**Where did you install ownCloud from:**
Downloaded tarball and deployed it by extracting it. Did it twice due to another error with code signing. Only copied config file from previous installation.

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - firstrunwizard
  - user_external
  - user_ldap

```

`

```

{
    "system": {
        "default_language": "en",
        "instanceid": "oc9e477e0e85",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/mnt\/data\/owncloud-data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud-data",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 1,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "mail_from_address": "noreply",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "forceSSLforSubdomains": true,
        "asset-pipeline.enabled": true,
        "has_internet_connection": true,
        "check_for_working_webdav": false,
        "updatechecker": true,
        "has_working_htaccess": true,
        "appstoreenabled": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filesystem_check_changes": 1,
        "tempdirectory": "\/mnt\/data\/owncloud-tmp",
        "cache_path": "\/mnt\/data\/owncloud-tmp\/$user",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": {
            "0": "OC\\Preview\\PNG",
            "1": "OC\\Preview\\JPEG",
            "2": "OC\\Preview\\GIF",
            "11": "OC\\Preview\\Illustrator",
            "12": "OC\\Preview\\Postscript",
            "13": "OC\\Preview\\Photoshop",
            "14": "OC\\Preview\\TIFF"
        },
        "trashbin_retention_obligation": "auto"
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:** 
Firefox 44

**Operating system:** 
Windows 8.1

#### Web server error log
```
2016/03/16 21:02:20 [error] 13748#0: *106915 open() "/var/www/owncloud404" failed (2: No such file or directory), client: 31.*.*.*, server: *, request: "GET /files/index.php?dir=%2FPictures&scrollto=IMG_20140707_183928.jpg HTTP/1.1", host: "*"
2016/03/16 21:03:45 [error] 13748#0: *106915 open() "/var/www/owncloud404" failed (2: No such file or directory), client: 31.*.*.*, server: *, request: "GET /files/index.php?dir=%2F&scrollto=2.jpg HTTP/1.1", host: "*"
2016/03/16 21:05:09 [error] 13748#0: *106915 open() "/var/www/owncloud404" failed (2: No such file or directory), client: 31.*.*.*, server: *, request: "GET /files/index.php?dir=%2FCamera+Uploads&scrollto=IMG_20160316_121734.jpg HTTP/1.1", host: "*"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"YdRoADOzD3++achw0BMO","remoteAddr":"31.*.*.*","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/Camera Uploads\\\/IMG_20160316_121734.jpg not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/lib\\\/private\\\/files\\\/filesystem.php(913): OC\\\\Files\\\\View->getOwner('\\\/Camera Uploads...')\\n#1 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(191): OC\\\\Files\\\\Filesystem::getOwner('\\\/Camera Uploads...')\\n#2 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(145): OCA\\\\Activity\\\\FilesHooks->getSourcePathAndOwner('\\\/Camera Uploads...')\\n#3 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(101): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/Camera Uploads...', 'file_created', 'created_self', 'created_by')\\n#4 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/apps\\\/activity\\\/lib\\\/fileshooksstatic.php(60): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/Camera Uploads...')\\n#5 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#6 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/lib\\\/private\\\/hook.php(105): call_user_func(Array, Array)\\n#7 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/lib\\\/private\\\/filechunking.php(224): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#8 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(436): OC_FileChunking->file_assemble(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/Camera Up...', '\\\/goopen\\\/files\\\/C...')\\n#9 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #31)\\n#10 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/directory.php(134): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #31)\\n#11 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('IMG_20160316_12...', Resource id #31)\\n#12 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('Camera Uploads\\\/...', Resource id #31, NULL)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#16 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/var\\\/www\\\/***REMOVED VALUE***\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/***REMOVED VALUE***\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1583}","level":3,"time":"2016-03-16T18:18:42+00:00"}

```

**Comment by PVince81** [comment]
@nickvergessen regression or did this never work when introduced the activity tab ?

**Comment by nickvergessen** [comment]
Behaviour break in core, fixed with https://github.com/owncloud/activity/pull/484 for 9.0.1
