### ISSUE TITLE
Corporate proxy required: "Error occurred while checking server setup"

### ISSUE THREAD

**Issue by mathieumd** [owncloud/core#23347]
### Steps to reproduce
1. Install ownCloud on a server _without_ internet access (all outside traffic must pass through a corporate proxy);
2. Go to the page `/owncloud/index.php/settings/admin`;
3. Wait a few seconds until the timeout.
### Expected behaviour

The "Security & setup warnings" section should quickly display a list of configuration hints. Including one explaining that internet access is required, and how/where to configure the proxy address.
### Actual behaviour

The "Security & setup warnings" section is displaying a message not helpful:

> - Error occurred while checking server setup
> - You are accessing this site via HTTP. We strongly suggest you configure your server to require using HTTPS instead as described in our security tips.
>   
>   Please double check the installation guides ↗, and check for any errors or warnings in the log. 
### Other info

The request to "/index.php/settings/ajax/checksetup" fails with an Apache 500 error.

Using our proxy we does access the internet:

``` bash
# Without a proxy
curl -m2 http://www.owncloud.org
curl: (28) Connection timed out after 2001 milliseconds

# With a proxy
http_proxy=http://proxy:8080 curl -m2 http://www.owncloud.org
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
#...
```

But how/where should it be configured for ownCloud?
### Server configuration

**Operating system**: Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Web server:** httpd-2.4.6-40.el7.x86_64

**Database:** MariaDB-server-10.1.12-1.el7.centos.x86_64

**PHP version:** php-5.4.16-36.el7_1.x86_64

**ownCloud version:** (see ownCloud admin page) ownCloud 9.0.0 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** from the repo at http://download.owncloud.org/download/repositories/9.0/RHEL_7

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

``` json
{
    "system": {
        "updatechecker": false,
        "instanceid": "och44fk9z6wf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud-1",
            "owncloud-2",
            "owncloud"
        ],
        "overwrite.cli.url": "http:\/\/owncloud\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```

**Are you using external storage, if yes which one:** local (GlusterFS)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox 45

**Operating system:** Ubuntu 14.4
#### Web server error log

```
10.0.0.123 - - [17/Mar/2016:11:53:23 +0100] "GET /owncloud/index.php/settings/ajax/checksetup HTTP/1.1" 500 10025 "http://owncloud/" "Mozilla/5.0 (X11; Linux i686; rv:41.0) Gecko/20100101 Firefox/41.0 Iceweasel/41.0"
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"VuqMo3wSysbs5nj5oUvA4gAAAAU","remoteAddr":"10.0.0.123","app":"index","message":"Exception: {\"Exception\":\"GuzzleHttp\Exception\ConnectException\",\"Message\":\"cURL error 7: See http://curl.haxx.se/libcurl/c/libcurl-errors.html\",\"Code\":0,\"Trace\":\"#0 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(104): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\ConnectException))
#1 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#2 /var/www/html/owncloud/3rdparty/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#3 /var/www/html/owncloud/3rdparty/react/promise/src/Promise.php(114): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#4 /var/www/html/owncloud/3rdparty/react/promise/src/Promise.php(159): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#5 /var/www/html/owncloud/3rdparty/react/promise/src/Promise.php(128): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#6 /var/www/html/owncloud/3rdparty/react/promise/src/Promise.php(177): React\Promise\Promise->resolve(Array)
#7 [internal function]: React\Promise\Promise->React\Promise\{closure}(Array)
#8 /var/www/html/owncloud/3rdparty/react/promise/src/Deferred.php(35): call_user_func(Object(Closure), Array)
#9 /var/www/html/owncloud/3rdparty/guzzlehttp/ringphp/src/Client/CurlMultiHandler.php(247): React\Promise\Deferred->resolve(Array)
#10 /var/www/html/owncloud/3rdparty/guzzlehttp/ringphp/src/Client/CurlMultiHandler.php(136): GuzzleHttp\Ring\Client\CurlMultiHandler->processMessages()
#11 /var/www/html/owncloud/3rdparty/guzzlehttp/ringphp/src/Future/BaseFutureTrait.php(118): GuzzleHttp\Ring\Client\CurlMultiHandler->execute()
#12 /var/www/html/owncloud/3rdparty/guzzlehttp/ringphp/src/Future/BaseFutureTrait.php(55): GuzzleHttp\Ring\Future\FutureArray->invokeWait()
#13 /var/www/html/owncloud/3rdparty/guzzlehttp/ringphp/src/Future/BaseFutureTrait.php(118): GuzzleHttp\Ring\Future\FutureArray->wait()
#14 /var/www/html/owncloud/3rdparty/guzzlehttp/ringphp/src/Future/BaseFutureTrait.php(55): GuzzleHttp\Message\FutureResponse->invokeWait()
#15 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Client.php(176): GuzzleHttp\Message\FutureResponse->wait()
#16 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#17 /var/www/html/owncloud/lib/private/http/client/client.php(129): GuzzleHttp\Client->get('https://www.own...', Array)
#18 /var/www/html/owncloud/settings/controller/checksetupcontroller.php(194): OC\Http\Client\Client->get('https://www.own...')
#19 /var/www/html/owncloud/settings/controller/checksetupcontroller.php(340): OC\Settings\Controller\CheckSetupController->isUsedTlsLibOutdated()
#20 [internal function]: OC\Settings\Controller\CheckSetupController->check()
#21 /var/www/html/owncloud/lib/private/appframework/http/dispatcher.php(159): call_user_func_array(Array, Array)
#22 /var/www/html/owncloud/lib/private/appframework/http/dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\CheckSetupController), 'check')
#23 /var/www/html/owncloud/lib/private/appframework/app.php(110): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\CheckSetupController), 'check')
#24 /var/www/html/owncloud/lib/private/appframework/routing/routeactionhandler.php(45): OC\AppFramework\App::main('CheckSetupContr...', 'check', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#25 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
#26 /var/www/html/owncloud/lib/private/route/router.php(273): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
#27 /var/www/html/owncloud/lib/base.php(873): OC\Route\Router->match('/settings/ajax/...')
#28 /var/www/html/owncloud/index.php(39): OC::handleRequest()
#29 {main}\",\"File\":\"/var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php\",\"Line\":49}","level":3,"time":"2016-03-17T10:54:10+00:00"}
```

**Comment by DeepDiver1975** [comment]
@LukasReschke mind taking a look? THX

**Comment by DeepDiver1975** [comment]
@mathieumd you can disable internet connectivity setting this config parameter: https://github.com/owncloud/core/blob/master/config/config.sample.php#L474-L477

and the proxy can be configured here: https://github.com/owncloud/core/blob/master/config/config.sample.php#L364-L367

**Comment by DeepDiver1975** [comment]
> @LukasReschke mind taking a look? THX

... to see if we can enhance the messages being displayed - THX

**Comment by mathieumd** [comment]
Thanks @DeepDiver1975.

I set the `proxy` parameter, and indeed it fails instantly (so there is no timeout, apparently), but still the request fails with a 500 error code and the same message "Error occurred while checking server setup".

The `has_internet_connection` works, but I would prefer to get the `proxy` parameter to works, of course.

**Comment by LukasReschke** [comment]
> I set the proxy parameter, and indeed it fails instantly (so there is no timeout, apparently), but still the request fails with a 500 error code and the same message "Error occurred while checking server setup".

What's the error message you get in your logs with a configured proxy?

**Comment by mathieumd** [comment]
It's the same error message:

```
{"reqId":"VurYGXLTw8B4Y5tikRcEqwAAAAc","remoteAddr":"172.31.95.219","app":"index","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ConnectException\",\"Message\":\"cURL error 7: See http:\\\/\\\/curl.haxx.se\\\/libcurl\\\/c\\\/libcurl-errors.html\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(104): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\ConnectException))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/Promise.php(114): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/Promise.php(159): React\\\\Promise\\\\Promise->React\\\\Promise\\\\{closure}(Object(React\\\\Promise\\\\FulfilledPromise))\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/Promise.php(128): React\\\\Promise\\\\Promise->settle(Object(React\\\\Promise\\\\FulfilledPromise))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/Promise.php(177): React\\\\Promise\\\\Promise->resolve(Array)\\n#7 [internal function]: React\\\\Promise\\\\Promise->React\\\\Promise\\\\{closure}(Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/Deferred.php(35): call_user_func(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/CurlMultiHandler.php(247): React\\\\Promise\\\\Deferred->resolve(Array)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/CurlMultiHandler.php(136): GuzzleHttp\\\\Ring\\\\Client\\\\CurlMultiHandler->processMessages()\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/BaseFutureTrait.php(118): GuzzleHttp\\\\Ring\\\\Client\\\\CurlMultiHandler->execute()\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/BaseFutureTrait.php(55): GuzzleHttp\\\\Ring\\\\Future\\\\FutureArray->invokeWait()\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/BaseFutureTrait.php(118): GuzzleHttp\\\\Ring\\\\Future\\\\FutureArray->wait()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/BaseFutureTrait.php(55): GuzzleHttp\\\\Message\\\\FutureResponse->invokeWait()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(176): GuzzleHttp\\\\Message\\\\FutureResponse->wait()\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/http\\\/client\\\/client.php(129): GuzzleHttp\\\\Client->get('https:\\\/\\\/www.own...', Array)\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/settings\\\/controller\\\/checksetupcontroller.php(194): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/www.own...')\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/settings\\\/controller\\\/checksetupcontroller.php(340): OC\\\\Settings\\\\Controller\\\\CheckSetupController->isUsedTlsLibOutdated()\\n#20 [internal function]: OC\\\\Settings\\\\Controller\\\\CheckSetupController->check()\\n#21 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#22 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\CheckSetupController), 'check')\\n#23 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\CheckSetupController), 'check')\\n#24 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('CheckSetupContr...', 'check', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#25 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#26 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#27 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#28 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#29 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":49}","level":3,"time":"2016-03-17T16:15:22+00:00"}
```

`proxy` has been set:

```
/var/www/html/owncloud/occ config:list system |grep proxy
        "proxy": "myproxy.example.com:8080",
```

**Comment by mathieumd** [comment]
Sorry, I clicked the wrong button!! *^_^*

**Comment by mathieumd** [comment]
Got one step further, by enabling SELinux boolean `httpd_can_network_connect` (maybe it could be worth it to enhance the _Error occurred while checking server setup_ message by giving a few hint? I know that many simply has the habit of disabling SELinux, but enhancing the related doc/warnings could help to stop this bad habit, no?).

Now, one of the warning messages is still a surprinsing:

> This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.

Is it a "normal" warning message even though the `proxy` parameter is set?

**Comment by PVince81** [comment]
Ok, so a bug with Guzzle and proxy handling ? Maybe the proxy setting isn't set correctly for the internet connection check ?

Is this still happening in 9.1.0beta2 ?

**Comment by mathieumd** [comment]
Sorry, I don't have access anymore to the setup. I guess that if you cannot reproduce the bug yourself, then you have no choice but to close this issue.
