### ISSUE TITLE
Contacts not showing after upgrade

### ISSUE THREAD

**Issue by matyas1995** [owncloud/core#23365]
I upgraded my oc from 8.2.2 to 9 and the contacts app to 1.0.0.

Now none of the contacts can be seen in the contacts app, even though they are still in the database. CardDav clients can still sync, create and edit contacts. If I create a new contact in the contacts app, it only shows up in the list but cannot be edited in the app because no details are shown. When the page is reloaded it is not shown any more as well.

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2016-03-17 18-10-20](https://cloud.githubusercontent.com/assets/1005065/13854402/a6ffbe92-ec6b-11e5-9d91-6d98209e20ac.png)

**Comment by pb13** [comment]
I have the same issue:


### Steps to reproduce
perform upgrade to 9.0.0

### Expected behaviour
Contacts are available after enabling the app.

### Actual behaviour
No contacts are displayed even though the addressbook is present.

### Server configuration
**Operating system**:
Linux (Gentoo)

**Web server:**
Apache 2.4.18

**Database:**
MySQL 5.6.28

**PHP version:**
PHP 5.6.19

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0

**Updated from an older ownCloud or fresh install:**
Updated from 8.2.2

**Where did you install ownCloud from:**
gentoo package manager (portage)

**Signing status (ownCloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- .webapp
		- ._cfg0000_.htaccess
		- ._cfg0002_.htaccess
		- ._cfg0001_.htaccess
		- core/js/jquery-1.10.0.min.map
		- ._cfg0003_.htaccess
		- .htaccess.8.0.0-modified
		- .htaccess-8.0.3
		- .htaccess.bak

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.webapp] => Array
                        (
                            [expected] => 
                            [current] => 
                        )

                    [._cfg0000_.htaccess] => Array
                        (
                            [expected] => 
                            [current] => b05fc815082c58d62328dd44370d5315801d051595c20bade8fdb2caea78e30104468c93a2503f98eec69f529dda3ca56fe46dbb213949198c1a191af3f47027
                        )

                    [._cfg0002_.htaccess] => Array
                        (
                            [expected] => 
                            [current] => ea69c687b605c2d1cc116c55dd829635459ec9685093fbc05589bc3d2b3e1ee0d37017a0462021b97a5efc9a9228bf3f8442560c3fe0300f45f013f0397db55d
                        )

                    [._cfg0001_.htaccess] => Array
                        (
                            [expected] => 
                            [current] => 6746e05719fd9620658d1c8ecbd912eb4908dd5fb6c58db0982a70442467ae763152dde245f7fc3f76214316e32f59aba2e2d758a36f2ff02758ab4a03519ce6
                        )

                    [core/js/jquery-1.10.0.min.map] => Array
                        (
                            [expected] => 
                            [current] => 5e756821d3765176ca4a55700c65f40efa213e488a186b5fd38adeaeaa93b6a3ee3ae6ae828dbca555c4cf029bf1d52007a8cce4ce0e85430016a9878b6a6d62
                        )

                    [._cfg0003_.htaccess] => Array
                        (
                            [expected] => 
                            [current] => fbe0e4270d7e40c8a994889dcff0d53003b02307242541d3f5a325437a949be5acd1475bc65ce5442bd6b1bd0e7691ef1294e0e0169ba5b6ccd8813e72ce7421
                        )

                    [.htaccess.8.0.0-modified] => Array
                        (
                            [expected] => 
                            [current] => a1ffad2555b862252fd04fe2ec731b02992d6117390258dd89ba91f8ab37d8d9d91430edb1977ce0ec42b7faeda5ac5416b26ad175e6f9d0d7aae958d018019b
                        )

                    [.htaccess-8.0.3] => Array
                        (
                            [expected] => 
                            [current] => 9b474e822d26f9e3ba91197f2e869aed7b648e610f8181c25859d875d372870cdf7cc13d23550f4f061d73a3dde6e7d1069b9f3913fb159f44b2abe486f799e7
                        )

                    [.htaccess.bak] => Array
                        (
                            [expected] => 
                            [current] => 8aea61b36d1507a0c15c6b57c7e077c34201836b710edc325852058207ba3101e12d7e3411a44663808ef4cca89e0c4b3786181d176b2fa5db697b9839249102
                        )

                )

        )

)
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0
  - user_pwauth: 2.3
Disabled:
  - appframework
  - contacts.bak
  - encryption
  - external
  - files_pdfviewer
  - galleryplus
  - music
  - news
  - notes
  - templateeditor
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "50df827bd6ce3",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/domain.net\/cloud\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "forcessl": true,
        "loglevel": 2,
        "theme": "",
        "trusted_domains": [
            "domain.net"
        ],
        "overwritewebroot": "\/cloud",
        "overwrite.cli.url": "\/cloud",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "noreply",
        "mail_smtpmode": "php",
        "mail_domain": "domain.net",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie"
        ],
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "0": 0
        }
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** 
Unix user backend  2.3

### Client configuration
**Browser:**
Google Chrome Version 41.0.2272.118 (64-bit)

**Operating system:**
Arch Linux

### Logs
#### Web server error log
none of relevance

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Vu6vtX8AAAEAAEreaYsAAAAA","remoteAddr":"a.b.c.d","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/domain.net\\\/htdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/domain.net\\\/htdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/domain.net\\\/htdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/domain.net\\\/htdocs\\\/cloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/domain.net\\\/htdocs\\\/cloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/domain...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/domain.net\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/maintenanceplugin.php\",\"Line\":84}","level":4,"time":"2016-03-20T14:12:05+00:00"}
{"reqId":"Vu7Pu38AAAEAAHCIf5IAAAAB","remoteAddr":"a.b.c.d","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/domain.net\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('files')\\n#1 \\\/var\\\/www\\\/domain.net\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/util.php(137): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/domain.net\\\/htdocs\\\/cloud\\\/lib\\\/base.php(872): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/domain.net\\\/htdocs\\\/cloud\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/domain.net\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/app.php\",\"Line\":142}","level":3,"time":"2016-03-20T16:28:43+00:00"}
{"reqId":"Vu7Pyn8AAAEAAHcSxbsAAAAM","remoteAddr":"a.b.c.d","app":"core","message":"starting upgrade from 8.2.2.2 to 9.0.0.19","level":0,"time":"2016-03-20T16:28:58+00:00","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=EA1dNT8ZGF5BeAg%2BIhwSWgw%2BChQAByJVIhJlGgQi%3Azw8rjob%2B%2B9Kyjou1IOeMsVLdCH1bpfF4d%2FBrCJ9d"}
{"reqId":"VDJN3n9Ny7W1KqpFVp10","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-20T16:30:01+00:00","method":"--","url":"--"}
{"reqId":"Vu7Pyn8AAAEAAHcSxbsAAAAM","remoteAddr":"a.b.c.d","app":"core","message":"No update found at the ownCloud appstore for app 166054","level":0,"time":"2016-03-20T16:30:38+00:00","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=EA1dNT8ZGF5BeAg%2BIhwSWgw%2BChQAByJVIhJlGgQi%3Azw8rjob%2B%2B9Kyjou1IOeMsVLdCH1bpfF4d%2FBrCJ9d"}
{"reqId":"Obj3gVB9CIWHjkwa4l8V","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-20T16:45:01+00:00","method":"--","url":"--"}
{"reqId":"Vu7Pyn8AAAEAAHcSxbsAAAAM","remoteAddr":"a.b.c.d","app":"PHP","message":"hash_file(\/var\/www\/domain.net\/htdocs\/cloud\/.webapp): failed to open stream: Permission denied at \/var\/www\/domain.net\/htdocs\/cloud\/lib\/private\/integritycheck\/checker.php#186","level":3,"time":"2016-03-20T16:50:48+00:00","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=EA1dNT8ZGF5BeAg%2BIhwSWgw%2BChQAByJVIhJlGgQi%3Azw8rjob%2B%2B9Kyjou1IOeMsVLdCH1bpfF4d%2FBrCJ9d"}
{"reqId":"Vu7Pyn8AAAEAAHcSxbsAAAAM","remoteAddr":"a.b.c.d","app":"PHP","message":"hash_file(\/var\/www\/domain.net\/htdocs\/cloud\/.webapp-owncloud-9.0.0): failed to open stream: Permission denied at \/var\/www\/domain.net\/htdocs\/cloud\/lib\/private\/integritycheck\/checker.php#186","level":3,"time":"2016-03-20T16:50:48+00:00","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=EA1dNT8ZGF5BeAg%2BIhwSWgw%2BChQAByJVIhJlGgQi%3Azw8rjob%2B%2B9Kyjou1IOeMsVLdCH1bpfF4d%2FBrCJ9d"}
{"reqId":"Vu7crn8AAAEAAA6eeaMAAAAL","remoteAddr":"a.b.c.d","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/domain.net\/htdocs\/cloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-20T17:23:58+00:00"}
{"reqId":"Vu7czH8AAAEAAA6C1TkAAAAC","remoteAddr":"a.b.c.d","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/domain.net\/htdocs\/cloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-20T17:24:29+00:00"}
{"reqId":"Vu7dCX8AAAEAAA6cxcYAAAAJ","remoteAddr":"a.b.c.d","app":"core","message":"starting upgrade from 9.0.0.19 to 9.0.0.19","level":0,"time":"2016-03-20T17:25:29+00:00","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=JDItNno9VTIDeAw9KjQtDxBIKjAQPydWFi0MLTog%3ANHHq%2FK%2FGi9OzbGJdU9EicnIgwwXUNd91N8Ec%2BJWj"}
{"reqId":"Vu7dCX8AAAEAAA6cxcYAAAAJ","remoteAddr":"a.b.c.d","app":"PHP","message":"hash_file(\/var\/www\/domain.net\/htdocs\/cloud\/.webapp): failed to open stream: Permission denied at \/var\/www\/domain.net\/htdocs\/cloud\/lib\/private\/integritycheck\/checker.php#186","level":3,"time":"2016-03-20T17:26:00+00:00","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=JDItNno9VTIDeAw9KjQtDxBIKjAQPydWFi0MLTog%3ANHHq%2FK%2FGi9OzbGJdU9EicnIgwwXUNd91N8Ec%2BJWj"}
{"reqId":"Vu7dCX8AAAEAAA6cxcYAAAAJ","remoteAddr":"a.b.c.d","app":"PHP","message":"hash_file(\/var\/www\/domain.net\/htdocs\/cloud\/.webapp-owncloud-9.0.0): failed to open stream: Permission denied at \/var\/www\/domain.net\/htdocs\/cloud\/lib\/private\/integritycheck\/checker.php#186","level":3,"time":"2016-03-20T17:26:00+00:00","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=JDItNno9VTIDeAw9KjQtDxBIKjAQPydWFi0MLTog%3ANHHq%2FK%2FGi9OzbGJdU9EicnIgwwXUNd91N8Ec%2BJWj"}
{"reqId":"Vu7jAn8AAAEAAA6g93kAAAAN","remoteAddr":"a.b.c.d","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/domain.net\/htdocs\/cloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-20T17:50:58+00:00"}
{"reqId":"Vu7kPH8AAAEAABD@fWAAAAAG","remoteAddr":"a.b.c.d","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/domain.net\/htdocs\/cloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-20T17:56:12+00:00"}
{"reqId":"Vu7oPH8AAAEAABJ-CKgAAAAC","remoteAddr":"a.b.c.d","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/domain.net\/htdocs\/cloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-20T18:13:16+00:00"}
{"reqId":"Vu7zXH8AAAEAABXBkr0AAAAH","remoteAddr":"a.b.c.d","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/domain.net\/htdocs\/cloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-20T19:00:45+00:00"}
{"reqId":"Vu74MX8AAAEAABNyWH4AAAAM","remoteAddr":"a.b.c.d","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/domain.net\/htdocs\/cloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-20T19:21:21+00:00"}
```

#### Browser log
none of relevance
