### ISSUE TITLE
Occ command not working 

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/core#23380]
Hello,  I can't use the occ command anymore. It's an clean install on Owncloud 9.
### Steps to reproduce
1.
2.
3.

### Expected behaviour
I can't use the OCC Command in OC 9.

### Actual behaviour
I get an error message when I execute the command with sudo -u lars php occ 

### Server configuration
**Operating system**:
Ubuntu 14.04 LTE, Plesk 
**Web server:**
Apache 2.4.7
**Database:**
mysql 14.14
**PHP version:**
5.6.19
**ownCloud version:** (see ownCloud admin page)
Oc 9
**Updated from an older ownCloud or fresh install:**
Fresh install 
**Where did you install ownCloud from:**
Installed over Owncloud-setup.php
**Signing status (ownCloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- lib/base.php
- files_antivirus
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/base.php] => Array
                        (
                            [expected] => c16b751b0704d9f470520e7af12f091acd31f2d0e573a18f0825f4ea9fb60716c926915ade592c622e2fcc213603b5711ad10c8347cbfb4a905ae91db05f7c30
                            [current] => c82373bf8ff9de9917f31c8618fcd4e170d6f07b6e0b51f8ee53ea35b5d700520832168bc9a00d20c923a53598d79fd9b1cc9068fa55e72cb84ec7128bf92b55
                        )

                )

        )

    [files_antivirus] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocpsovzwa7ww',
  'passwordsalt' => 'eZCC32Qq0GjmKwtA2pPvk0gjNjQxF2',
  'secret' => 'mmJaAUqJEB2iiP15LiXoGS3iuWsLnOOz1eJAkh5QlrdFf7Q3',
  'trusted_domains' =>
  array (
    'xx.xx.xx.xx',
    'domain.tld',
  ),
  'datadirectory' => '/mnt/owncloud/data',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxxxxxxx',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  0 =>
  array (
    0 =>
    array (
      0 => 'localhost',
      1 => 11211,
    ),
    1 =>
    array (
      0 => 'domain.tld',
      1 => 11211,
    ),
  ),
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'loglevel' => 2,
  'maintenance' => false,
  'appstore.experimental.enabled' => true,
  'singleuser' => false,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'lars',
  'mail_domain' => 'xxxxxxxx',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxxxxxxx',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'lars@domain.tld',
  'mail_smtppassword' => 'xxxxxxx',
  'mail_smtpsecure' => 'ssl',
  'updatechecker' => false,
  'theme' => '',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Google drive 
**Are you using encryption:** yes/no
Yes

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
PHP Parse error:  syntax error, unexpected ''cloud-surfer.eu'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/www/vhosts/cloud-surfer.eu/Owncloud/config/config.php on line 9
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"nl\/aaiBFchAE+qgVaVQ9","remoteAddr":"","app":"core","message":"Error while running background job (class: OC\\BackgroundJob\\Legacy\\RegularJob, arguments: Array\n(\n    [0] => OCA\\Files_Antivirus\\Cron\\Task\n    [1] => run\n)\n): {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"File with id \\\"43647\\\" has not been found.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/apps\\\/files_antivirus\\\/lib\\\/backgroundscanner.php(78): OC\\\\Files\\\\View->getPath('43647')\\n#1 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/apps\\\/files_antivirus\\\/lib\\\/cron\\\/task.php(21): OCA\\\\Files_Antivirus\\\\BackgroundScanner->run()\\n#2 [internal function]: OCA\\\\Files_Antivirus\\\\Cron\\\\Task::run()\\n#3 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/legacy\\\/regularjob.php(28): call_user_func(Array)\\n#4 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OC\\\\BackgroundJob\\\\Legacy\\\\RegularJob->run(Array)\\n#5 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/cron.php(141): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1639}","level":3,"time":"2016-03-18T07:30:06+00:00"}
{"reqId":"xBRqhER\/+lmYrV9PhTGM","remoteAddr":"151.252.217.162","app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/opt\/plesk\/php\/5.6\/lib\/php\/modules\/apcu.so' - \/opt\/plesk\/php\/5.6\/lib\/php\/modules\/apcu.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2016-03-18T07:32:45+00:00"}
{"reqId":"ttRVftbevCMxkDqW\/Jkm","remoteAddr":"151.252.217.162","app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/opt\/plesk\/php\/5.6\/lib\/php\/modules\/apcu.so' - \/opt\/plesk\/php\/5.6\/lib\/php\/modules\/apcu.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2016-03-18T07:38:22+00:00"}
{"reqId":"ZuSnhj+U5blNT4d+oRIi","remoteAddr":"","app":"core","message":"Error while running background job (class: OC\\BackgroundJob\\Legacy\\RegularJob, arguments: Array\n(\n    [0] => OCA\\Files_Antivirus\\Cron\\Task\n    [1] => run\n)\n): {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"File with id \\\"43647\\\" has not been found.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/apps\\\/files_antivirus\\\/lib\\\/backgroundscanner.php(78): OC\\\\Files\\\\View->getPath('43647')\\n#1 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/apps\\\/files_antivirus\\\/lib\\\/cron\\\/task.php(21): OCA\\\\Files_Antivirus\\\\BackgroundScanner->run()\\n#2 [internal function]: OCA\\\\Files_Antivirus\\\\Cron\\\\Task::run()\\n#3 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/legacy\\\/regularjob.php(28): call_user_func(Array)\\n#4 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OC\\\\BackgroundJob\\\\Legacy\\\\RegularJob->run(Array)\\n#5 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/cron.php(141): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1639}","level":3,"time":"2016-03-18T07:45:06+00:00"}
{"reqId":"HrAmcXTaN8JMVEqy+BSO","remoteAddr":"151.252.217.162","app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/opt\/plesk\/php\/5.6\/lib\/php\/modules\/apcu.so' - \/opt\/plesk\/php\/5.6\/lib\/php\/modules\/apcu.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2016-03-18T07:53:18+00:00"}
{"reqId":"3Gsx6sTWvy7J1Eb5Hufj","remoteAddr":"","app":"core","message":"Error while running background job (class: OC\\BackgroundJob\\Legacy\\RegularJob, arguments: Array\n(\n    [0] => OCA\\Files_Antivirus\\Cron\\Task\n    [1] => run\n)\n): {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"File with id \\\"43647\\\" has not been found.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/apps\\\/files_antivirus\\\/lib\\\/backgroundscanner.php(78): OC\\\\Files\\\\View->getPath('43647')\\n#1 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/apps\\\/files_antivirus\\\/lib\\\/cron\\\/task.php(21): OCA\\\\Files_Antivirus\\\\BackgroundScanner->run()\\n#2 [internal function]: OCA\\\\Files_Antivirus\\\\Cron\\\\Task::run()\\n#3 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/legacy\\\/regularjob.php(28): call_user_func(Array)\\n#4 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OC\\\\BackgroundJob\\\\Legacy\\\\RegularJob->run(Array)\\n#5 \\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/cron.php(141): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/vhosts\\\/cloud-surfer.eu\\\/httpdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1639}","level":3,"time":"2016-03-18T08:00:15+00:00"}
```

**Comment by LukasReschke** [comment]
Please post the non-edited trusted_domains section. The error message indicates that you entered some wrong stuff in there.

**Comment by Happyfeet01** [comment]
It was my fail. it was the wrong path.. Can be closed.
Am 18.03.2016 9:07 vorm. schrieb "Lukas Reschke" <notifications@github.com>:
