### ISSUE TITLE
[OC8.2] Files created with 0 KB size when using an external SMB mount 

### ISSUE THREAD

**Issue by Trefex** [owncloud/core#23426]
When using the client AND the browser, files being uploaded to SMB get created with filesize 0 KB.

When using the browser, it seems fine.

### Expected behaviour
Files should be created with actual size.

### Actual behaviour
Files get created with 0 KB size.

### Server configuration
**Operating system**: 

CentOS 7.2

**Web server:** 

Apache 2

**Database:** 

MySQL

**PHP version:** 

5.6.19

**ownCloud version:** 

8.2.2 

**Updated from an older ownCloud or fresh install:** 

Updated from 8.0

**Where did you install ownCloud from:** 

CE Packages

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
[root@lcsb-oc1-server owncloud]# sudo -u apache php occ app:list
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.1
  - files: 1.2.0
  - files_external: 0.3.0
  - files_mv: 0.8.2
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - galleryplus: 14.3.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - user_ldap: 0.7.1
Disabled:
  - encryption
  - external
  - gallery
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocagvsml5uip",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.240.6.10",
            "lcsb-owncloud.uni.lu",
            "lcsb-oc1-server.uni.lu",
            "owncloud.lcsb.uni.lu"
        ],
        "theme": "owncloud-lcsb-theme",
        "debug": "false",
        "datadirectory": "\/mnt\/data\/oc-data",
        "overwrite.cli.url": "https:\/\/lcsb-owncloud.uni.lu\/",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "lcsb-oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "mail_smtpmode": "smtp",
        "mail_from_address": "lcsb-sysadmins",
        "mail_domain": "uni.lu",
        "mail_smtphost": "smtp.uni.lu",
        "mail_smtpport": "25",
        "maintenance": false,
        "loglevel": 3,
        "ldapIgnoreNamingRules": false,
        "preview_libreoffice_path": "\/bin\/libreoffice"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

SMB

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

FreeIPA

#### LDAP configuration (delete this part if not used)

```
[root@lcsb-oc1-server owncloud]# sudo -u apache php occ ldap:show-config
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                     |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                   |
| hasPagedResultSupport         |                                                                                                     |
| homeFolderNamingRule          |                                                                                                     |
| lastJpegPhotoLookup           | 0                                                                                                   |
| ldapAgentName                 | uid=ldapuser,cn=users,cn=accounts,dc=uni,dc=lu                                                 |
| ldapAgentPassword             | ***                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                     |
| ldapAttributesForUserSearch   |                                                                                                     |
| ldapBackupHost                | lums.uni.lu                                                                                         |
| ldapBackupPort                | 389                                                                                                 |
| ldapBase                      | dc=uni,dc=lu                                                                                        |
| ldapBaseGroups                | cn=groups,cn=accounts,dc=uni,dc=lu                                                                  |
| ldapBaseUsers                 | cn=users,cn=accounts,dc=uni,dc=lu                                                                   |
| ldapCacheTTL                  | 600                                                                                                 |
| ldapConfigurationActive       | 1                                                                                                   |
| ldapEmailAttribute            | mail                                                                                                |
| ldapExperiencedAdmin          | 0                                                                                                   |
| ldapExpertUUIDGroupAttr       |                                                                                                     |
| ldapExpertUUIDUserAttr        |                                                                                                     |
| ldapExpertUsernameAttr        |                                                                                                     |
| ldapGroupDisplayName          | cn                                                                                                  |
| ldapGroupFilter               | (&(objectclass=groupofnames)(memberOf=cn=owncloud,cn=groups,cn=accounts,dc=uni,dc=lu))              |
| ldapGroupFilterGroups         |                                                                                                     |
| ldapGroupFilterMode           | 1                                                                                                   |
| ldapGroupFilterObjectclass    |                                                                                                     |
| ldapGroupMemberAssocAttr      | member                                                                                              |
| ldapHost                      | lcsb-ipa.uni.lu                                                                                     |
| ldapIgnoreNamingRules         |                                                                                                     |
| ldapLoginFilter               | (&(&(objectClass=posixaccount)(memberof=cn=owncloud,cn=groups,cn=accounts,dc=uni,dc=lu))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                     |
| ldapLoginFilterEmail          | 0                                                                                                   |
| ldapLoginFilterMode           | 0                                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                                   |
| ldapNestedGroups              | 0                                                                                                   |
| ldapOverrideMainServer        |                                                                                                     |
| ldapPagingSize                | 500                                                                                                 |
| ldapPort                      | 389                                                                                                 |
| ldapQuotaAttribute            |                                                                                                     |
| ldapQuotaDefault              | 200000000000                                                                                        |
| ldapTLS                       | 0                                                                                                   |
| ldapUserDisplayName           | displayname                                                                                         |
| ldapUserFilter                | (&(objectClass=posixaccount)(memberof=cn=owncloud,cn=groups,cn=accounts,dc=uni,dc=lu))              |
| ldapUserFilterGroups          |                                                                                                     |
| ldapUserFilterMode            | 1                                                                                                   |
| ldapUserFilterObjectclass     | person                                                                                              |
| ldapUuidGroupAttribute        | auto                                                                                                |
| ldapUuidUserAttribute         | auto                                                                                                |
| turnOffCertCheck              | 0                                                                                                   |
| useMemberOfToDetectMembership | 1                                                                                                   |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
```

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
197889:{"reqId":"Vu@7R5aqXZxV8lEPqajHfwAAAAQ","remoteAddr":"10.244.9.34","app":"webdav","message":"Exception: {\"Message\":\"Invalid request for \\\/Laurent\\\/modelExploration\\\/jpg\\\/modelS10_Recon2.jpg\",\"Exception\":\"Icewind\\\\SMB\\\\Exception\\\\NotFoundException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Share.php(364): Icewind\\\\SMB\\\\Parser->checkForError(Array, '\\\/Laurent\\\/modelE...')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Share.php(128): Icewind\\\\SMB\\\\Share->parseOutput(Array, '\\\/Laurent\\\/modelE...')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(102): Icewind\\\\SMB\\\\Share->stat('\\\/Laurent\\\/modelE...')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(136): OC\\\\Files\\\\Storage\\\\SMB->getFileInfo('modelExploratio...')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(164): OC\\\\Files\\\\Storage\\\\SMB->stat('modelExploratio...')\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(171): OC\\\\Files\\\\Storage\\\\Common->filemtime('modelExploratio...')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(377): OC\\\\Files\\\\Storage\\\\SMB->hasUpdated('modelExploratio...', 1458515612)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(390): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated('modelExploratio...', 1458515612)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(377): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->hasUpdated('modelExploratio...', 1458515612)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(377): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated('modelExploratio...', 1458515612)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(123): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated('modelExploratio...', 1458515612)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1205): OC\\\\Files\\\\Cache\\\\Watcher->needsUpdate('modelExploratio...', Array)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php(148): OC\\\\Files\\\\View->getFileInfo('Atlas.Laurent\\\/m...')\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(178): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Atlas.Laurent\\\/m...')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('Atlas.Laurent\\\/m...')\\n#15 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Parser.php\",\"Line\":49}","level":4,"time":"2016-03-21T09:13:44+00:00”}
```

**Comment by Trefex** [comment]
```
[root@lcsb-oc1-server ~]# smbclient -V
Version 4.2.3
```

**Comment by PVince81** [comment]
@Trefex is this a DFS share ?

**Comment by Trefex** [comment]
@PVince81 Hey Vincent,

Yes it's an Isilon OneFS system in the back.

Best,

**Comment by PVince81** [comment]
No idea what this is... If this is using DFS you might need to upgrade libsmbclient / samba to 4.2.8 from what I heard due to bugs related to DFS shares.

**Comment by Trefex** [comment]
Well I don't know what you mean by DFS. For me DFS is Distributed FileSystem?

**Comment by Trefex** [comment]
4.2.8 is not available in CentOS 7.2?

**Comment by PVince81** [comment]
Yeah, DFS is Distributed File System.
If you don't know then you're probably not using it.

Not sure if the error you posted is related to the upload. But it seems that a patch for it would be this one: https://github.com/icewind1991/SMB/commit/7aa7b44b7cef86eda6f1ff7dce8ecaecfccdba14

**Comment by Trefex** [comment]
As I said, now we are using same words, so my SMB is using OneFS from EMC's Isilon system.

We have around 2 PiB storage there...

**Comment by MorrisJobke** [comment]
> Not sure if the error you posted is related to the upload. But it seems that a patch for it would be this one: icewind1991/SMB@7aa7b44

This patch went into 9.0.1.

@Trefex Please try again with 9.0.1 and report back if this is still not working. Thanks :)

**Comment by Trefex** [comment]
@MorrisJobke Ok thanks will do. Is it safe now to upgrade from 8.x to 9.0.1 ? I got a bit scared when 9.0 came out with the explosion of tickets on github / mailing list. Thanks

**Comment by MorrisJobke** [comment]
> @MorrisJobke Ok thanks will do. Is it safe now to upgrade from 8.x to 9.0.1 ? I got a bit scared when 9.0 came out with the explosion of tickets on github / mailing list. Thanks

It's only possible to upgrade from 8.2.x to upgrade to 9.0.x.

**Comment by Trefex** [comment]
Yeah that's what I meant.

On Fri, Apr 22, 2016 at 11:26 AM, Morris Jobke <notifications@github.com>
wrote:

> @MorrisJobke <https://github.com/MorrisJobke> Ok thanks will do. Is it
> safe now to upgrade from 8.x to 9.0.1 ? I got a bit scared when 9.0 came
> out with the explosion of tickets on github / mailing list. Thanks
>
> It's only possible to upgrade from 8.2.x to upgrade to 9.0.x.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/23426#issuecomment-213351520>
>



-- 
Christophe

*Official Mendeley Advisor*
*Ask me anything about Mendeley through http://bit.ly/ki1ceV
<http://bit.ly/ki1ceV>*
