### ISSUE TITLE
occ files:scan aborted when lacking permissions

### ISSUE THREAD

**Issue by Trefex** [owncloud/core#23451]
### Expected behaviour
When I run 

sudo -u apache php /var/www/html/owncloud/occ files:scan f750a00f-ac4311e4-bc279842-8ec34411

I want the run to complete and index files appropriately, even if the user does not have permissions to see contents of a specific sub-folder.

### Actual behaviour

I get an error

[Icewind\SMB\Exception\ForbiddenException]
  Invalid request for smb://atlas.uni.lux/LCSB_Administrative/Finance

and scan is aborted.

### Server configuration
**Operating system**:

CentOS 7.2

**Web server:**

Apache 2

**Database:**

MySQL

**PHP version:**

PHP 5.6

**ownCloud version:** (see ownCloud admin page)

8.2.3

**Updated from an older ownCloud or fresh install:**

Update

**Where did you install ownCloud from:**

owncloud.org

**Are you using external storage, if yes which one:** local/smb/sftp/...

SMB, Isilon OneFS

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

FreeIPA

#### ownCloud log (data/owncloud.log)

```
{"reqId":"VvAab3Q@zfpoD0P6cMqa1AAAAAs","remoteAddr":"10.244.9.34","app":"webdav","message":"Exception: {\"Message\":\"Invalid request for smb:\\\/\\\/atlas.uni.lux\\\/LCSB_Administrative\\\/Central%20Office\\\/1.%202016\",\"Exception\":\"Icewind\\\\SMB\\\\Exception\\\\ForbiddenException\",\"Code\":13,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(72): Icewind\\\\SMB\\\\NativeState->handleError('smb:\\\/\\\/atlas.uni...')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(101): Icewind\\\\SMB\\\\NativeState->testResult(false, 'smb:\\\/\\\/atlas.uni...')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(83): Icewind\\\\SMB\\\\NativeState->opendir('smb:\\\/\\\/atlas.uni...')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(120): Icewind\\\\SMB\\\\NativeShare->dir('\\\/Central Office...')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(269): OC\\\\Files\\\\Storage\\\\SMB->getFolderContents('Central Office\\\/...')\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(89): OC\\\\Files\\\\Storage\\\\SMB->opendir('Central Office\\\/...')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(93): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('Central Office\\\/...')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(89): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->opendir('Central Office\\\/...')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(89): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('Central Office\\\/...')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(300): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('Central Office\\\/...')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(335): OC\\\\Files\\\\Cache\\\\Scanner->getNewChildren('Central Office\\\/...')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(268): OC\\\\Files\\\\Cache\\\\Scanner->scanChildren('Central Office\\\/...', false, 3, Array, true)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1290): OC\\\\Files\\\\Cache\\\\Scanner->scan('Central Office\\\/...', false)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(199): OC\\\\Files\\\\View->getDirectoryContent('\\\/SMB\\\/Central Of...')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(195): OC\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(878): Sabre\\\\DAV\\\\Tree->getChildren('SMB\\\/Central Off...')\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(928): Sabre\\\\DAV\\\\Server->addPathNodesRecursively(Array, Object(Sabre\\\\DAV\\\\PropFind))\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(327): Sabre\\\\DAV\\\\Server->getPropertiesForPath('SMB\\\/Central Off...', Array, 1)\\n#18 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropfind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#21 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#22 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#23 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php\",\"Line\":42}","level":4,"time":"2016-03-21T15:59:43+00:00"}
```

**Comment by PVince81** [comment]
Indeed, that's bad.

The SMB exception isn't properly converted to ownCloud's own `ForbiddenException`.

Possible fix: https://github.com/owncloud/core/pull/22292

**Comment by PVince81** [comment]
Assigning @icewind1991 for the backport.

@icewind1991 does the scanner also automatically skip folders that threw `ForbiddenException` ?

**Comment by PVince81** [comment]
@Trefex I tested https://github.com/owncloud/core/pull/23481 (the backport of the fix) and the error disappears. Can you test it too ?

**Comment by Trefex** [comment]
@PVince81 could you tell me how to do this properly? Do I just replace the .php with the one from the commit ?

Thanks

**Comment by PVince81** [comment]
@Trefex no, never do that as you might have other changes.

1. Backup the OC source code (just in case)
1. Download the PR as patch https://github.com/owncloud/core/pull/23481.patch
1. `patch -p1 < 23481.patch`
