### ISSUE TITLE
oc9: no foldersync, no keepass, but windows and android clients working

### ISSUE THREAD

**Issue by EnzephaloN** [owncloud/core#23597]
Hello

I've installed owncloud 7 ón my server (Debian8) several months ago. All was working fine.
Some weeks ago I updated step-by-step to oc9.
Since oc9 "foldersync" and "keepass" on my phone are not working, displaying "Method Not Allowed" error.
**But**: Owncloud-webpage, Owncloud Windows-App and Owncloud Android-App working without errors! And if I test the connection with foldersync it says "success".
I also connected via cadaver to owncloud and was able to login.

php 5.6.17-0+dev8u1
Debian 8.1
Owncloud 9.0.0

I think this is very strange, cause foldersync does not work - owncloud-app works.

Do you habe any informations for me to get 3rd party applications running again?

best regards
Johannes

**Comment by Xenopathic** [comment]
Logs? Please don't just remove the issue template - it's there to provide us with information that we need.

**Comment by EnzephaloN** [comment]
Hi Xenopathic

The owncloud-Log is empty. Debug is on, Loglevel = 0. Which user/group should it have?

PHP-errror-log:
```
[26-Mar-2016 20:36:00 UTC] {"reqId":"YlpHMdU8IIEKf9mHuf02","remoteAddr":"91.137.36.153","app":"PHP","message":"fopen(\/media\/sf_Owncloud\/owncloud.log): failed to open stream: Operation not permitted at \/var\/www\/owncloud\/lib\/private\/log\/owncloud.php#98","level":0,"time":"2016-03-26T20:36:00+00:00","method":"OPTIONS","url":"\/remote.php\/webdav\/"}
[26-Mar-2016 20:36:00 UTC] {"reqId":"YlpHMdU8IIEKf9mHuf02","remoteAddr":"91.137.36.153","app":"PHP","message":"chmod(): Operation not permitted at \/var\/www\/owncloud\/lib\/private\/log\/owncloud.php#99","level":0,"time":"2016-03-26T20:36:00+00:00","method":"OPTIONS","url":"\/remote.php\/webdav\/"}
[26-Mar-2016 20:36:00 UTC] {"reqId":"YlpHMdU8IIEKf9mHuf02","remoteAddr":"91.137.36.153","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-03-26T20:36:00+00:00","method":"OPTIONS","url":"\/remote.php\/webdav\/"}
[26-Mar-2016 20:36:00 UTC] {"reqId":"YlpHMdU8IIEKf9mHuf02","remoteAddr":"91.137.36.153","app":"PHP","message":"fopen(\/media\/sf_Owncloud\/owncloud.log): failed to open stream: Operation not permitted at \/var\/www\/owncloud\/lib\/private\/log\/owncloud.php#98","level":0,"time":"2016-03-26T20:36:00+00:00","method":"OPTIONS","url":"\/remote.php\/webdav\/"}
[26-Mar-2016 20:36:00 UTC] {"reqId":"YlpHMdU8IIEKf9mHuf02","remoteAddr":"91.137.36.153","app":"PHP","message":"chmod(): Operation not permitted at \/var\/www\/owncloud\/lib\/private\/log\/owncloud.php#99","level":0,"time":"2016-03-26T20:36:00+00:00","method":"OPTIONS","url":"\/remote.php\/webdav\/"}
[26-Mar-2016 20:36:00 UTC] {"reqId":"YlpHMdU8IIEKf9mHuf02","remoteAddr":"91.137.36.153","app":"PHP","message":"chmod(): Operation not permitted at \/var\/www\/owncloud\/lib\/private\/log\/owncloud.php#99","level":3,"time":"2016-03-26T20:36:00+00:00","method":"OPTIONS","url":"\/remote.php\/webdav\/"}
```

Apache-Error-Log is empty.

Do you now see something?

best regards
Johannes

**Comment by Xenopathic** [comment]
`fopen(\/media\/sf_Owncloud\/owncloud.log): failed to open stream: Operation not permitted`

Assuming /media/sf_Owncloud is your data directory, it seems that ownCloud cannot create the log file, likely due to improper permissions. Make sure it has write access to that directory, and that if the log file exists, it is writable by the web server user. Then reproduce the issue and post the contents of that file.

**Comment by EnzephaloN** [comment]
Hello Xenopathic

I moved logfile to /var/log/owncloud.log by config.php-settings.
Now I have a new owncloud.log (date 2016-03-27) with last entry 2016-03-09 and no informations about last operations or errors.

best regards
Johannes

**Comment by EnzephaloN** [comment]
Oh my dear - I find something in other_vhost_access.log

```
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:23:18 +0200] "PROPFIND /owncloud/remote.php/webdav/Einstellungen/1Password/ HTTP/1.1" 405 814 "-" "android-cloud-api - Android 5.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:23:22 +0200] "PROPFIND /owncloud/remote.php/webdav/Einstellungen/1Password/ HTTP/1.1" 405 676 "-" "android-cloud-api - Android 5.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:23:30 +0200] "GET /owncloud/status.php HTTP/1.1" 404 3776 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:23:30 +0200] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 586 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:24:02 +0200] "GET /owncloud/status.php HTTP/1.1" 404 3776 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:24:02 +0200] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 586 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:24:34 +0200] "GET /owncloud/status.php HTTP/1.1" 404 3776 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:24:34 +0200] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 586 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:25:06 +0200] "GET /owncloud/status.php HTTP/1.1" 404 3776 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:25:06 +0200] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 586 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:25:38 +0200] "GET /owncloud/status.php HTTP/1.1" 404 3776 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:25:38 +0200] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 586 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:26:10 +0200] "GET /owncloud/status.php HTTP/1.1" 404 3776 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:26:10 +0200] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 586 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:26:42 +0200] "GET /owncloud/status.php HTTP/1.1" 404 3776 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:26:42 +0200] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 586 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:27:14 +0200] "GET /owncloud/status.php HTTP/1.1" 404 3776 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:27:14 +0200] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 586 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:27:46 +0200] "GET /owncloud/status.php HTTP/1.1" 404 3776 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:27:46 +0200] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 586 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:28:18 +0200] "GET /owncloud/status.php HTTP/1.1" 404 3776 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:28:18 +0200] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 586 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:28:50 +0200] "GET /owncloud/status.php HTTP/1.1" 404 3776 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
Owncloud:443 91.137.36.44 - - [27/Mar/2016:15:28:50 +0200] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 586 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
```
Is this helpful?

best regards
Johannes

**Comment by EnzephaloN** [comment]
other_vhost_access.log difference between "foldersync" app (not working) and "owncloud" app (working)

foldersync:
```
...
Owncloud:443 91.137.35.13 - - [28/Mar/2016:18:58:09 +0200] "PROPFIND /owncloud/remote.php/webdav/Einstellungen/1Password/ HTTP/1.1" 405 676 "-" "android-cloud-api - Android 5.1.1"
...
```

owncloud
```
...
Owncloud:443 91.137.35.13 - enzephalon [28/Mar/2016:18:56:28 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1959 "-" "Mozilla/5.0 (Android) ownCloud-android/1.9.1"
...
```

I tried foldersync with other oc9 server - this worked. I cannot see the differences between these servers or why the oc-app works but foldersync doesn't.

**Comment by EnzephaloN** [comment]
*solved*

After re-editing all remote-folder-settings in foldersync, the sync works as before.

**Comment by Xenopathic** [comment]
Glad to see you got it working
