### ISSUE TITLE
External local storage mount gives root folder access if available for multiple groups

### ISSUE THREAD

**Issue by Depariel** [owncloud/core#23617]
### Steps to reproduce
1. Add external local storage /mnt/Media from web admin panel
2. Add more than 1 group in the "Available for" field from the web admin panel
3. Attempt to access the folder from an admin account

### Expected behaviour
Users in the "Available for" groups should be able to access only the contents of /mnt/Media

### Actual behaviour
Users in the "Available for" groups can access the contents of /

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache2
**Database:**
SQLite
**PHP version:**
PHP 5.5.9-1ubuntu4.14
**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0 (stable)
**Updated from an older ownCloud or fresh install:**
Fresh install
**Where did you install ownCloud from:**
Ubuntu package
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocf4uykbd9dt",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE****"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "dbtype": "sqlite3",
        "version": "9.0.0.19",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes; local
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome 49.0.2623.87m (64-bit)
**Operating system:**
Windows 10 (64-bit)
#### Web server error log
Some (most? all?) of these seem to be for a different issue I'm having. Not sure if that issue is related.
```
[Sun Mar 27 08:03:36.783584 2016] [mpm_prefork:notice] [pid 28254] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Sun Mar 27 08:03:36.783625 2016] [core:notice] [pid 28254] AH00094: Command line: '/usr/sbin/apache2'
[Sun Mar 27 10:41:27.452332 2016] [authz_core:error] [pid 12865] [client ::1:59466] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 12:06:17.459172 2016] [authz_core:error] [pid 12860] [client ::1:36512] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 19:47:32.785862 2016] [authz_core:error] [pid 19297] [client ::1:40366] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 19:56:50.323431 2016] [authz_core:error] [pid 12864] [client ::1:40940] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 20:07:29.987675 2016] [authz_core:error] [pid 24136] [client ::1:41192] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 20:10:22.613497 2016] [authz_core:error] [pid 19256] [client ::1:41264] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 20:12:51.757491 2016] [authz_core:error] [pid 24271] [client ::1:41342] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 20:15:01.813658 2016] [authz_core:error] [pid 23801] [client ::1:41408] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 20:15:28.129872 2016] [authz_core:error] [pid 23801] [client ::1:41440] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 20:16:19.205617 2016] [authz_core:error] [pid 24461] [client ::1:41474] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 20:20:56.645510 2016] [authz_core:error] [pid 24359] [client ::1:41612] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 20:23:18.678928 2016] [authz_core:error] [pid 19297] [client ::1:41676] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 20:27:34.000457 2016] [:error] [pid 24253] [client ::1:41374] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 39 bytes) in /var/www/owncloud/lib/private/files/node/root.php on line 182
[Sun Mar 27 21:04:23.768999 2016] [authz_core:error] [pid 24687] [client ::1:42158] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 21:25:06.081372 2016] [:error] [pid 17528] [client ::1:41338] PHP Fatal error:  Maximum execution time of 3600 seconds exceeded in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91
[Sun Mar 27 21:27:50.370872 2016] [authz_core:error] [pid 19297] [client ::1:42460] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 21:27:51.454987 2016] [:error] [pid 17528] [client ::1:41338] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 5 database is locked' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /var/www/owncloud/lib/private/db/connection.php(205): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE "oc_file...', Array, Array)\n#3 /var/www/owncloud/lib/private/lock/dblockingprovider.php(263): OC\\DB\\Connection->executeUpdate('UPDATE `*PREFIX...', Array)\n#4 [internal function]: OC\\Lock\\DBLockingProvider->releaseAll()\n#5 {main}\n\nNext exception 'Doctrine\\DBAL\\Driver\\PDOException' with message 'SQLSTATE[HY000]: General error: 5 database is locked' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93\nStack trace:\n#0 /var/www in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php on line 85
[Sun Mar 27 21:27:54.016725 2016] [authz_core:error] [pid 23801] [client ::1:42464] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 21:37:05.995097 2016] [:error] [pid 26600] [client 192.168.1.168:60477] script '/var/www/html/status.php' not found or unable to stat
[Sun Mar 27 21:39:20.635956 2016] [authz_core:error] [pid 26601] [client ::1:42632] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 21:39:23.349023 2016] [authz_core:error] [pid 25569] [client ::1:42624] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 21:41:37.204830 2016] [authz_core:error] [pid 25569] [client 192.168.1.168:60732] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 21:43:30.630320 2016] [authz_core:error] [pid 26933] [client ::1:42688] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Mar 27 21:45:07.270331 2016] [authz_core:error] [pid 26999] [client ::1:42738] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Mar 28 19:19:33.523342 2016] [authz_core:error] [pid 26883] [client 127.0.0.1:52934] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Mar 28 19:20:02.778095 2016] [authz_core:error] [pid 19412] [client 192.168.1.168:49382] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Mar 28 19:25:31.623308 2016] [authz_core:error] [pid 19420] [client 192.168.1.168:49454] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Mar 28 19:28:03.558050 2016] [authz_core:error] [pid 26601] [client 192.168.1.168:49490] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Mar 28 19:36:27.732936 2016] [authz_core:error] [pid 26601] [client 192.168.1.168:49598] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Mar 28 19:37:15.930283 2016] [authz_core:error] [pid 21193] [client 192.168.1.168:49613] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Mar 28 19:42:06.069942 2016] [authz_core:error] [pid 26883] [client 192.168.1.168:49682] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Mar 28 20:29:54.736116 2016] [authz_core:error] [pid 21508] [client 192.168.1.168:50546] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Mar 28 21:19:20.229666 2016] [authz_core:error] [pid 20992] [client 192.168.1.168:51207] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Mar 28 21:34:38.145754 2016] [authz_core:error] [pid 23163] [client 192.168.1.168:51435] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
```

#### ownCloud log (data/owncloud.log)
I think these are the relevant lines. There are over 3800 total lines in my log file, though, so it's hard to say... For the full thing: [owncloud-log.txt](https://github.com/owncloud/core/files/192752/owncloud-log.txt)
```
{"reqId":"MtLE5XDget1j15He073L","remoteAddr":"::1","app":"PHP","message":"array_filter() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/files_external\/service\/storagesservice.php#72","level":3,"time":"2016-03-28T00:08:11+00:00"}
{"reqId":"MtLE5XDget1j15He073L","remoteAddr":"::1","app":"PHP","message":"array_map(): Argument #2 should be an array at \/var\/www\/owncloud\/apps\/files_external\/service\/storagesservice.php#75","level":3,"time":"2016-03-28T00:08:11+00:00"}
{"reqId":"MtLE5XDget1j15He073L","remoteAddr":"::1","app":"PHP","message":"array_filter() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/files_external\/service\/storagesservice.php#79","level":3,"time":"2016-03-28T00:08:11+00:00"}
{"reqId":"MtLE5XDget1j15He073L","remoteAddr":"::1","app":"PHP","message":"array_map(): Argument #2 should be an array at \/var\/www\/owncloud\/apps\/files_external\/service\/storagesservice.php#82","level":3,"time":"2016-03-28T00:08:11+00:00"}
{"reqId":"MtLE5XDget1j15He073L","remoteAddr":"::1","app":"PHP","message":"array_values() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/files_external\/service\/storagesservice.php#91","level":3,"time":"2016-03-28T00:08:11+00:00"}
{"reqId":"MtLE5XDget1j15He073L","remoteAddr":"::1","app":"PHP","message":"array_values() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/files_external\/service\/storagesservice.php#92","level":3,"time":"2016-03-28T00:08:11+00:00"}
{"reqId":"MtLE5XDget1j15He073L","remoteAddr":"::1","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/files_external\/lib\/storageconfig.php#217","level":3,"time":"2016-03-28T00:08:11+00:00"}
{"reqId":"MtLE5XDget1j15He073L","remoteAddr":"::1","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/files_external\/lib\/config\/configadapter.php#75","level":3,"time":"2016-03-28T00:08:11+00:00"}
```

This doesn't seem to happen if the "Accessible for" field is left blank or if there is only 1 group there. I haven't tested it with individual users or combinations of groups and users. I also haven't tested it using a non-admin account as the one attempting access.

**Comment by PVince81** [comment]
I cannot reproduce this issue.

Please check the following tables: "oc_storages", "oc_external_mounts", "oc_external_config" in case there are duplicate configs of some sorts.

**Comment by Depariel** [comment]
I attempted to look at those tables via the sqlite3 CLI tool and a Firefox addon called SQLite Manager, and neither were able to open the database (found in /var/www/owncloud/data/owncloud.db). Should I just try reinstalling owncloud?

**Comment by Depariel** [comment]
I just decided to reinstall using MySQL, and I can no longer reproduce the issue. I should probably have just used that from the start.
