### ISSUE TITLE
Integrity check failed on fresh install

### ISSUE THREAD

**Issue by opnoack** [owncloud/core#23624]
### Steps to reproduce
1. Download and install ownCloud 9.0.0 (tar.bz2)
2. Run installer
3. Log in

### Expected behaviour
Integrity check passes.

### Actual behaviour
Integrity check fails.

### Server configuration
**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache2 2.4.7-1ubuntu4.9

**Database:** MySQL 5.5.47-0ubuntu0.14.04.1

**PHP version:** PHP 7.0 7.0.4-7+deb.sury.org~trusty+2

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** No

**Where did you install ownCloud from:** From Archive

**Signing status (ownCloud 9.0 and above):** -

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- index.html

Raw output
==========
Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [index.html] => Array
                        (
                            [expected] => 27792cd8c483a51322e0d2b91668af80ea0943711cdfc57d7d13a91165e6a9e3f3c7d7a0b62e5eec37ce2799efe8363a7a9b31087e7b7e2ddf0d84af8b1997c8
                            [current] => 
                        )

                )

        )

)
```

**List of activated apps:** None

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'random',
  'passwordsalt' => 'random',
  'secret' => 'random',
  'trusted_domains' => 
  array (
    0 => '10.48.58.201',
  ),
  'datadirectory' => '/var/www/data',
  'overwrite.cli.url' => 'http://10.48.58.201',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => '',
  'dbuser' => 'owncloud',
  'dbpassword' => 'random',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chromium Version 49.0.2623.87 Ubuntu 15.10 (64-bit)

**Operating system:** Ubuntu 15.10

#### ownCloud log (data/owncloud.log)
```
{"reqId":"6wdnSg77Vdf402h692nd","remoteAddr":"10.48.48.1","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_admin\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'owncloud'@'localhost' for table 'user'","level":3,"time":"2016-03-29T12:16:57+00:00"}
{"reqId":"6wdnSg77Vdf402h692nd","remoteAddr":"10.48.48.1","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `owncloud` . * TO 'owncloud'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'owncloud'@'localhost' to database 'owncloud'","level":3,"time":"2016-03-29T12:16:57+00:00"}
{"reqId":"6wdnSg77Vdf402h692nd","remoteAddr":"10.48.48.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/lib\/private\/setup\/mysql.php#46","level":3,"time":"2016-03-29T12:16:57+00:00"}
{"reqId":"6wdnSg77Vdf402h692nd","remoteAddr":"10.48.48.1","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/lib\\\/private\\\/installer.php(621): include('\\\/var\\\/www\\\/apps\\\/d...')\\n#4 \\\/var\\\/www\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/var\\\/www\\\/apps\\\/d...')\\n#5 \\\/var\\\/www\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-03-29T12:16:59+00:00"}
{"reqId":"6wdnSg77Vdf402h692nd","remoteAddr":"10.48.48.1","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/lib\\\/private\\\/installer.php(621): include('\\\/var\\\/www\\\/apps\\\/d...')\\n#4 \\\/var\\\/www\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/var\\\/www\\\/apps\\\/d...')\\n#5 \\\/var\\\/www\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-03-29T12:16:59+00:00"}
{"reqId":"x5nBIn2mHjhKA+rQDSp2","remoteAddr":"10.48.48.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-29T12:17:16+00:00"}
{"reqId":"\/X\/tDGtC+pOOBJqI+\/1T","remoteAddr":"10.48.48.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-29T12:17:29+00:00"}
{"reqId":"0SaTcWtyRfhMrfjOlAZA","remoteAddr":"10.48.48.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-29T12:18:17+00:00"}
{"reqId":"oukciizs9GgjDTuhk00\/","remoteAddr":"10.48.48.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-29T12:18:23+00:00"}
{"reqId":"igHMUnEV3zBd+hEde9uw","remoteAddr":"10.48.48.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-29T12:20:00+00:00"}
{"reqId":"5\/6tUdUzyo2nFc9IPiH7","remoteAddr":"10.48.48.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-29T12:20:11+00:00"}
{"reqId":"YSylyugPqGdLjO8k2623","remoteAddr":"10.48.48.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-29T12:20:32+00:00"}
{"reqId":"WQU3Rd5dFCRluCmtfSZI","remoteAddr":"10.48.48.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-29T12:23:04+00:00"}
{"reqId":"+95m4KWzj+VEyOsKd6l6","remoteAddr":"10.48.48.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-29T12:23:12+00:00"}
{"reqId":"wn7Y7Upb9yod4L382Pqy","remoteAddr":"10.48.48.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-29T12:27:29+00:00"}
```

**Comment by LukasReschke** [comment]
Did you make sure to upload the `index.html` file as well? It seems to be missing.

**Comment by opnoack** [comment]
Problem solved: The index.html file was deleted by the roll-out script. Thanks for your hint.
