### ISSUE TITLE
Password reset problem - loading and loading

### ISSUE THREAD

**Issue by mislav-eu** [owncloud/core#23731]
### Steps to reproduce
1. Enable server encryption, recovery keys on admin, create user, enable recovery keys there.
2. Upload some files/folders, whatever you want to and make sure you configure email for this new user.
3. Configure SMTP for the admin user to be able to send emails
4. Try to log in with new user with wrong password and use option "Wrong password. Reset it?"
5. User receives email in format:
   https://domain.TLD/index.php/lostpassword/reset/form/C7FFirTZ5fHJse9NcN4xi/testUser
6. User clicks on that email and password reset option is provided - enter password
7. New windows is opened saying:
   Your files are encrypted. If you haven't enabled the recovery key, there will be no way to get your data back after your password is reset.
   If you are not sure what to do, please contact your administrator before you continue.
   Do you really want to continue?
8. Click on the check box and continue with password reset - screen is loading and loading:
   http://oi68.tinypic.com/5b92qw.jpg
### Expected behaviour

Tell us what should happen - password should change and user should be able to read the new files (even though they're encrypted)
### Actual behaviour

Tell us what happens instead - what happens is that on this screen on step 7. you click agree and continue - it's just loading and loading and loading. I gave up after trying it few times for 10-20 minutes and nothing happened.

Please note that if I cancel the operation, I can log in immediately with old password without any errors.
### Server configuration

**Operating system**: Debian 8.3

**Web server:** Apache 2.4.10

**Database:** MariaDB 10

**PHP version:** PHP 5.6 

**ownCloud version:** (see ownCloud admin page) - 9.0.0 stable

**Updated from an older ownCloud or fresh install:** - updated from 8.2.2 stable

**Where did you install ownCloud from:** - from official sources list, through apt-get

**Signing status (ownCloud 9.0 and above):**  - how to get this?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Enabled:
- activity: 2.2.1
- comments: 0.2
- dav: 0.1.5
- encryption: 1.2.0
- external: 1.2
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_mv: 0.8.2
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- gallery: 14.5.0
- notifications: 0.2.3
- passwordpolicy: 1.1
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- files_trashbin
- firstrunwizard
- galleryplus
- user_external
- user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
{
    "system": {
        "instanceid": "oc3su8t4jf9n",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XY"
        ],
        "datadirectory": "\/opt\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/XY",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "XY",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 3,
        "asset-pipeline.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "defaultapp": "files",
        "check_for_working_htaccess": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "enable_previews": true,
        "singleuser": false,
        "maintenance": false,
        "theme": "",
        "filesystem_check_changes": 0,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "mail_from_address": "XY",
        "mail_domain": "XY",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "XY",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}


**Are you using external storage, if yes which one:** local/smb/sftp/... - no external storage

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** - no external user-backend

### Client configuration 
**Browser:** Mozilla Firefox

**Operating system:** ubuntu 14.04 LTS

### Logs
#### ownCloud log (data/owncloud.log)
```

Insert your ownCloud log here

```
{"reqId":"Vzer5GHK82TxD9NoAXgc","remoteAddr":"XY","app":"PHP","message":"Call to undefined method OC_L10N::get() at \/var\/www\/owncloud\/apps\/passwordpolicy\/controller\/passwordpolicycontroller.php#27","level":3,"time":"2016-04-01T13:21:24+00:00"}

This is the only error in log - I'm not sure if it's connected to my problem or not.

#### Browser log
```

Insert your browser log here, this could for example include:
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://XY 'unsafe-eval'").

onsubmit attribute on DIV element

Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://XY 'unsafe-eval'").

try {  for(var lastpass_iter=0; lastpass...

testUser (line 1)
GET https://XY/ocs/v2.php/apps/notifications/api/v1/notifications?format=json 200 OK 194ms  c6df6eb...cc4a.js (line 6)

---

This above is when you click on the password reset link.

This below is when you're on step 7. and you click to continue with it

POST https://XY/index.php/lostpassword/set/sMkTVJbBIOUKZOgCZ9rtx/testUser 500 Internal Server Error     210ms   c6df6eb...cc4a.js (line 6)
"NetworkError: 500 Internal Server Error - https://XY/index.php/lostpassword/set/sMkTVJbBIOUKZOgCZ9rtx/testUser"
- no response body
- reseponse headers:
  HTTP/1.0 500 Internal Server Error
  Date: Fri, 01 Apr 2016 13:59:57 GMT
  Server: Apache
  strict-transport-security: max-age=63072000; includeSubdomains; preload
  Expires: Thu, 19 Nov 1981 08:52:00 GMT
  Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
  Pragma: no-cache
  content-security-policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src \* data: blob:; font-src 'self' data:; media-src *; connect-src *
  x-content-type-options: nosniff
  X-XSS-Protection: 1; mode=block
  x-robots-tag: none
  X-Frame-Options: SAMEORIGIN
  x-download-options: noopen
  X-Permitted-Cross-Domain-Policies: none
  Content-Length: 0
  Connection: close
  Content-Type: text/html; charset=UTF-8
- request headers:
  POST /index.php/lostpassword/set/sMkTVJbBIOUKZOgCZ9rtx/testUser HTTP/1.1
  Host: XY
  User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
  Accept: _/_
  Accept-Language: en-US,en;q=0.5
  Accept-Encoding: gzip, deflate, br
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  requesttoken: Bjo5HgkJMTgKBARYDVVRFiM8UiZxEyARCxwkURgxLHs=:2KAMGcsbXuCaFm9cEkcA9UfSNZKcizBP+vYzz5KD/Xs=
  OCS-APIREQUEST: true
  X-Requested-With: XMLHttpRequest
  Content-Length: 29
  Cookie: oc3su8t4jf9n=1s7t720ta1um3v625o06c87dg3; oc_sessionPassphrase=ge2IV1EkhggCl3vjEXPwUXgZxJ1pMtoeza8%2FERHkG3KRAhOsD4YynFAlp8q68CHeiZnr5nGY9DMF75mL5J8V3yjqPpCA5Wj4rzrxAvNE6RZR6Wq5oMgbWYUUxLDS2sI1
  Connection: keep-alive

after this, there'are only 

https://XY/ocs/v2.php/apps/notifications/api/v1/notifications?format=json 200 OK 211ms  c6df6eb...cc4a.js (line 6)
Response - {"ocs":{"meta":{"status":"ok","statuscode":200,"message":null},"data":[]}}

```

```

**Comment by tflidd** [comment]
Looks like the passwordpolicy-app is not ready for OC 9.0 yet. Can you disable it and try again?

**Comment by tflidd** [comment]
There are some changes in the repo of this app (no new version has been pushed to the app-store) but you can probably manually install a newer version from github: https://github.com/nickbooties/passwordpolicy/pull/16

**Comment by mislav-eu** [comment]
Hello @tflidd 

I've disabled passwordpolicy-app and process is indeed faster (more like instant), however after step 7) when I click to continue I get an error that there's no private key and that error occurred. 

If I try to log in back with the user/password, I get an error "internal error occurred, contact administrator" - if I hit F5 -> resend I'm somehow logged in and I have message:
"
Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files.
"

I've tried to log-out and log-in, but nothing happened. I'm not sure why this error is displayed, because my private keys exists:
# ls -la /opt/owncloud/data/testUserv/files_encryption/OC_DEFAULT_MODULE/
total 20K
drwxr-xr-x 2 www-data www-data 4.0K Mar 17 10:39 .
drwxr-xr-x 4 www-data www-data 4.0K Mar 17 10:40 ..
-rw-r--r-- 1 www-data www-data 4.4K Mar 17 10:39 testUserv.privateKey
-rw-r--r-- 1 www-data www-data  800 Mar 17 10:39 testUserv.publicKey

In the owncloud log, this is displayed:
{"reqId":"W3OuBSJZcQ1K67m3l4mi","remoteAddr":"93.138.92.80","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Bad Signature\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(456): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('e77gkexU\\\/YX1HBI...', '\\\\xD2E\\\"\\\\xCCU\\\\xDB@4\\\\xF1M\\\\x95\\\\x05\\\\x16O\\\\xF4...', '4d9e3c391d5aa7c...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(416): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('e77gkexU\\\/YX1HBI...', '\\\\xD2E\\\"\\\\xCCU\\\\xDB@4\\\\xF1M\\\\x95\\\\x05\\\\x16O\\\\xF4...', 'AES-256-CTR', 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/keymanager.php(354): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decryptPrivateKey('HBEGIN:cipher:A...', 'testpass', 'testUser')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/hooks\\\/userhooks.php(162): OCA\\\\Encryption\\\\KeyManager->init('testUser', 'testpass')\\n#4 [internal function]: OCA\\\\Encryption\\\\Hooks\\\\UserHooks->login(*** username and password replaced ***)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/hook.php(105): call_user_func(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/server.php(235): OC_Hook::emit('OC_User', 'post_login', Array)\\n#7 [internal function]: OC\\\\Server->OC\\\\{closure}(Object(OC\\\\User\\\\User), 'testpass')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/emittertrait.php(98): call_user_func_array(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/publicemitter.php(32): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'postLogin', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(225): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'postLogin', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user.php(162): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1073): OC_User::login(*** username and password replaced ***)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(969): OC::tryFormLogin()\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(931): OC::handleLogin()\\n#15 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":476}","level":3,"time":"2016-04-04T06:21:32+00:00"}

{"reqId":"W3OuBSJZcQ1K67m3l4mi","remoteAddr":"93.138.92.80","app":"handleLogin","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Bad Signature\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(456): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('e77gkexU\\\/YX1HBI...', '\\\\xD2E\\\"\\\\xCCU\\\\xDB@4\\\\xF1M\\\\x95\\\\x05\\\\x16O\\\\xF4...', '4d9e3c391d5aa7c...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(416): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('e77gkexU\\\/YX1HBI...', '\\\\xD2E\\\"\\\\xCCU\\\\xDB@4\\\\xF1M\\\\x95\\\\x05\\\\x16O\\\\xF4...', 'AES-256-CTR', 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/keymanager.php(354): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decryptPrivateKey('HBEGIN:cipher:A...', 'testpass', 'testUser')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/hooks\\\/userhooks.php(162): OCA\\\\Encryption\\\\KeyManager->init('testUser', 'testpass')\\n#4 [internal function]: OCA\\\\Encryption\\\\Hooks\\\\UserHooks->login(*** username and password replaced ***)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/hook.php(105): call_user_func(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/server.php(235): OC_Hook::emit('OC_User', 'post_login', Array)\\n#7 [internal function]: OC\\\\Server->OC\\\\{closure}(Object(OC\\\\User\\\\User), 'testpass')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/emittertrait.php(98): call_user_func_array(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/publicemitter.php(32): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'postLogin', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(225): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'postLogin', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user.php(162): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1073): OC_User::login(*** username and password replaced ***)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(969): OC::tryFormLogin()\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(931): OC::handleLogin()\\n#15 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":476}","level":3,"time":"2016-04-04T06:21:32+00:00"}

**Comment by PVince81** [comment]
@mislav-eu did you use the "homeDirectory" attribute for LDAP ?

@schiesbn could this be slightly related to the other recovery key issue with "homeDirectory" ?

**Comment by mislav-eu** [comment]
LDAP? I'm not using that, neither do I know what is homeDirectory. I create and manage all users directly through OC admin -> Users.

**Comment by tflidd** [comment]
Then you must not enable these....

> user_external
> user_ldap

**Comment by mislav-eu** [comment]
You're saying that app that were installed and not used at all/configured at all are cause of this problem? I've never even activated those, probably they were here by default.

I've upgraded last week my test machine to 9.0.1. and when I list now apps:

$ sudo -u www-data php occ app:list
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - files_mv
  - files_trashbin
  - firstrunwizard
  - galleryplus
  - passwordpolicy
  - user_external
  - user_ldap

And I didn't do anything manually.

I've tested it again and here's the first bug:
1) if my user is tTestA - password reset is working
2) if my user is tTestA and I try to log in with ttesta, it's working, however if I want to reset password for ttesta - it says that for this user password is not configured

So, kindly decide if you'll match case sensitive letters on log in/password reset or not.

Next, once I've received email, I've clicked on it, confirmed that I want to reset password and I've received the following error:
Private Key missing for user: please try to log-out and log-in again
http://oi68.tinypic.com/2450mjd.jpg

If I want to log in with new password, I receive error that internet error occurred and I can't log in, however if I resend the info I'm in (logged).

Then on the top of the page it is shown "Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files." - if I indeed go to personal settings, set old password and new one - error message is gone and I can access my files. This is fine as long as you know old password, however the point of the password reset is that you don't remember last password, so you can't do that.

**Comment by tflidd** [comment]
Oh sorry, I didn't see that it actually was disabled.

For the encryption, you can set a recovery key: https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/encryption_configuration.html#enabling-users-file-recovery-keys
Do you use external storage? (If not, see the first big red box in the above link).

It remains the issue with case sensitive user names.

**Comment by mislav-eu** [comment]
Password recovery keys are enabled on all users/admins.

**Comment by PVince81** [comment]
Is this still an issue with 9.0.7 or 9.1.3 ?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
