### ISSUE TITLE
webdav login isn't working for CIFS share with "session credentials" in OC 9.0.0

### ISSUE THREAD

**Issue by mitch-geht-ab** [owncloud/core#23756]
If I configure "username and password" in the admin interface, it works for the app/webdav and the web interface.
If I configure "Session credentials" it works in the web interface  but NOT in the app/webdav.
With latest OC8 Server it was working fine, after upgrade to OC9 it doesn't work anymore.
### Steps to reproduce
1. fresh OC9 installation (with ldap backend)
2. working samba server Version 4.1.17-Debian (without AD but with ldap backend)
3.  
### Expected behaviour

Opening OC Android App and open the external CIFS mount should show content of mounted share.
### Actual behaviour

Opening the mount it show's "Alles leer. Laden Sie etwas hoch" (empty directory).
### Server configuration

**Operating system**:
Description:    Debian GNU/Linux 8.3 (jessie)

**Web server:**
apache2     2.4.10-10+deb8u4

**Database:**
mysql   5.5.47-0+deb8u1

**PHP version:**
php   5.6.17+dfsg-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
https://owncloud.org/install/

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - external
  - user_external
```

**The content of config/config.php:**

```
    "system": {
        "instanceid": "oc902znrfp6m",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain1",
            "domain2"
        ],
        "datadirectory": "\/home\/webseiten\/domain1\/owncloud-data",
        "overwrite.cli.url": "https:\/\/domain1\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "db_owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "log_type": "syslog",
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "14",
        "trashbin_auto_expire": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "noreply",
        "mail_domain": "domain1",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "mailsrv-of-domain1",
        "mail_smtpport": "25",
        "loglevel": 1
    }

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
cifs

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

```
+-------------------------------+--------------------------------------------+
| Configuration                 |                                            |
+-------------------------------+--------------------------------------------+
| hasMemberOfFilterSupport      |                                            |
| hasPagedResultSupport         |                                            |
| homeFolderNamingRule          |                                            |
| lastJpegPhotoLookup           | 0                                          |
| ldapAgentName                 | cn=owncloud,ou=mgmt,dc=domain1,dc=de        |
| ldapAgentPassword             | ***                                        |
| ldapAttributesForGroupSearch  |                                            |
| ldapAttributesForUserSearch   |                                            |
| ldapBackupHost                |                                            |
| ldapBackupPort                |                                            |
| ldapBase                      | dc=domain1,dc=de                            |
| ldapBaseGroups                | dc=domain1,dc=de                            |
| ldapBaseUsers                 | dc=domain1,dc=de                            |
| ldapCacheTTL                  | 600                                        |
| ldapConfigurationActive       | 1                                          |
| ldapDynamicGroupMemberURL     |                                            |
| ldapEmailAttribute            | mail                                       |
| ldapExperiencedAdmin          | 1                                          |
| ldapExpertUUIDGroupAttr       |                                            |
| ldapExpertUUIDUserAttr        |                                            |
| ldapExpertUsernameAttr        |                                            |
| ldapGroupDisplayName          | cn                                         |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))             |
| ldapGroupFilterGroups         |                                            |
| ldapGroupFilterMode           | 0                                          |
| ldapGroupFilterObjectclass    | posixGroup                                 |
| ldapGroupMemberAssocAttr      | uniqueMember                               |
| ldapHost                      | ldaps://ldap-of-domain1                |
| ldapIgnoreNamingRules         |                                            |
| ldapLoginFilter               | (&(|(objectclass=posixAccount))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                            |
| ldapLoginFilterEmail          | 0                                          |
| ldapLoginFilterMode           | 0                                          |
| ldapLoginFilterUsername       | 1                                          |
| ldapNestedGroups              | 0                                          |
| ldapOverrideMainServer        |                                            |
| ldapPagingSize                | 500                                        |
| ldapPort                      | 636                                        |
| ldapQuotaAttribute            |                                            |
| ldapQuotaDefault              |                                            |
| ldapTLS                       | 0                                          |
| ldapUserDisplayName           | displayname                                |
| ldapUserDisplayName2          |                                            |
| ldapUserFilter                | (|(objectclass=posixAccount))              |
| ldapUserFilterGroups          |                                            |
| ldapUserFilterMode            | 1                                          |
| ldapUserFilterObjectclass     | posixAccount                               |
| ldapUuidGroupAttribute        | auto                                       |
| ldapUuidUserAttribute         | auto                                       |
| turnOffCertCheck              | 0                                          |
| useMemberOfToDetectMembership | 1                                          |
+-------------------------------+--------------------------------------------+
```
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

```
configured "Session credentials" for CIFS mount:
192.168.2.101 - thomas [03/Apr/2016:10:57:34 +0200] "PROPFIND /owncloud/remote.php/webdav/Multimedia/ HTTP/1.1" 503 1392 "-" "Mozilla/5.0 (Android) ownCloud-android/1.9.1"

configured "username and passwort" for CIFS mount:
192.168.2.101 - thomas [03/Apr/2016:10:58:24 +0200] "PROPFIND /owncloud/remote.php/webdav/Exchange/ HTTP/1.1" 207 2074 "-" "Mozilla/5.0 (Android) ownCloud-android/1.9.1"
```
#### ownCloud log (data/owncloud.log)

```
Here are the logs from logging in via app and configured "Session credentials" for CIFS mount:

Apr 02 09:41:39 montecito ownCloud[17693]: {webdav} Exception: {"Message":"HTTP\/1.1 503 Storage not available","Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Code":0,"Trace":"#0 \/home\/webseiten\/domain1\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(903): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('Multimedia')\n#1 \/home\/webseiten\/domain1\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(336): Sabre\\DAV\\Server->getPropertiesForPath('Multimedia', Array, 0)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPropFind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/home\/webseiten\/domain1\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/home\/webseiten\/domain1\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#5 \/home\/webseiten\/domain1\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/home\/webseiten\/domain1\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#7 \/home\/webseiten\/domain1\/owncloud\/remote.php(138): require_once('\/home\/webseiten...')\n#8 {main}","File":"\/home\/webseiten\/domain1\/owncloud\/apps\/dav\/lib\/connector\/sabre\/objecttree.php","Line":157,"User":"069e27e2-aebd-1030-94bc-fb0f24389eba"}

Login via "username and passwort" generates no logs (loglevel=1).
```

```
```

**Comment by PVince81** [comment]
@mitch-geht-ab did the user log out and log in again after the storage was configured ?
Seems it might be required to re-login to make sure the credentials get caught.

@Xenopathic @icewind1991 can you confirm ?

**Comment by mitch-geht-ab** [comment]
@PVince81 Sure. I've rebootet my smartphone. It assume that it is like a logout -> login.

**Comment by QuentinC** [comment]
Hello,

I have a similar problem, that may be linked to this one.
At first, I thought it was a problem with the Android app (see https://github.com/owncloud/android/issues/1674 ) but it seems to be a problem with the WebDAV front-end when using user credentials to access external storage.

I've tried to understand what could be the problem. It seems that some WebDAV clients cannot use cookies, and only send the basic auth header.

If the owncloud cookies are not in the query, the external storage won't be available. 

This makes, for example, the android app won't be able to access external storage. 

Can you confirm that ?

Thanks !

**Comment by caguiar** [comment]
Hello,
I had a differente problem (#25506) and after I intalled the patch (https://github.com/owncloud/core/pull/25751.patch), this particular issue is no longer.

**Comment by PVince81** [comment]
Is this still happening with 9.0.7 or 9.1.3 ?

**Comment by QuentinC** [comment]
Hello,

CIFS with user credentials is working normally for me on 9.1.3.

Thanks,

Quentin

**Comment by PVince81** [comment]
Thanks for the feedback, closing then.
