### ISSUE TITLE
OC 9 restoring server-side-encrypted files from backup ran into exception/error

### ISSUE THREAD

**Issue by victorbw** [owncloud/core#23775]
### Steps to reproduce
```
1. Install oc9 from scratch via bzip
2. activate Server-Side Encryption & recovery password
3. Create user, login, activate recovery password, upload files
4. manually copy complete users-data-dir to somewhere else (via SCP)
5. delete certain files (via SSH/SCP)
6. restore deleted files from backup (via SCP)
7. chown -R www-data:www-data /path/to/userdatadir
8. sudo -u www-data /var/www/html/owncloud php occ files:scan [username]
```

### Expected behaviour
`Files (*.pdf, *.jpg, etc.) readable`

### Actual behaviour
`restored files listed, but not readable. see error-log below`

### Server configuration
**Operating system**:
`Ubuntu 14.04.4 LTS x64`

**Web server:**
`Apache 2.4.7`

**Database:**
`MySQL v 14.14, distrib 5.5.47`

**PHP version:**
` 5.5.9`

**ownCloud version:**
`9.0.0 Stable`

**Updated from an older ownCloud or fresh install:**
`fresh, from scratch`

**Where did you install ownCloud from:**
`https://download.owncloud.org/community/owncloud-9.0.0.tar.bz2`

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
`no errors`

**List of activated apps:**
```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - files_w2g: 0.8.2.6
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - ownnote: 1.05
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "ocus26fatfwp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/owncloudlab2.cloud-hosting.ch",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "ocdb1",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "appstore.experimental.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "trashbin_retention_obligation": 30,
        "trashbin_auto_expire": true,
        "logdateformat": "F d, Y H:i:s",
        "log_rotate_size": 104857600,
        "logtimezone": "Europe\/Berlin",
        "versions_retention_obligation": "disabled",
        "enable_previews": true,
        "preview_max_scale_factor": 10,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": ""
    }
}


```

**Are you using external storage, if yes which one:** local/smb/sftp/...
`no`

**Are you using encryption:** 
`yes
`
### Client configuration
`Happens on every browser`

**Operating system:**
`Happens on every OS`

#### Web server error log

Insert your webserver log here
`nothing serious`

#### ownCloud log (data/owncloud.log)
```
{"reqId":"0D1SZehSmm8ll8hbe5dY","remoteAddr":"213.3.25.41","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Bad Signature\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(456): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('PEEMCtH+WSinDG6...', '???+????n??????...', '1e71fc7173f7e65...')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(416): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('PEEMCtH+WSinDG6...', '???+????n??????...', 'AES-256-CTR', 0)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/keymanager.php(354): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decryptPrivateKey('HBEGIN:cipher:A...', 'Mineral1', 'test1')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/hooks\\\/userhooks.php(162): OCA\\\\Encryption\\\\KeyManager->init('test1', 'Mineral1')\\n#4 [internal function]: OCA\\\\Encryption\\\\Hooks\\\\UserHooks->login(*** username and password replaced ***)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hook.php(105): call_user_func(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(235): OC_Hook::emit('OC_User', 'post_login', Array)\\n#7 [internal function]: OC\\\\Server->OC\\\\{closure}(Object(OC\\\\User\\\\User), 'Mineral1')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/emittertrait.php(98): call_user_func_array(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/publicemitter.php(32): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\OC\\\\User', 'postLogin', Array)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(225): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\OC\\\\User', 'postLogin', Array)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user.php(162): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(1073): OC_User::login(*** username and password replaced ***)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(969): OC::tryFormLogin()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(931): OC::handleLogin()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":476}","level":3,"time":"March 30, 2016 09:45:11"}
{"reqId":"0D1SZehSmm8ll8hbe5dY","remoteAddr":"213.3.25.41","app":"handleLogin","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Bad Signature\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(456): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('PEEMCtH+WSinDG6...', '???+????n??????...', '1e71fc7173f7e65...')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(416): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('PEEMCtH+WSinDG6...', '???+????n??????...', 'AES-256-CTR', 0)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/keymanager.php(354): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decryptPrivateKey('HBEGIN:cipher:A...', 'Mineral1', 'test1')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/hooks\\\/userhooks.php(162): OCA\\\\Encryption\\\\KeyManager->init('test1', 'Mineral1')\\n#4 [internal function]: OCA\\\\Encryption\\\\Hooks\\\\UserHooks->login(*** username and password replaced ***)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hook.php(105): call_user_func(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(235): OC_Hook::emit('OC_User', 'post_login', Array)\\n#7 [internal function]: OC\\\\Server->OC\\\\{closure}(Object(OC\\\\User\\\\User), 'Mineral1')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/emittertrait.php(98): call_user_func_array(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/publicemitter.php(32): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\OC\\\\User', 'postLogin', Array)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(225): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\OC\\\\User', 'postLogin', Array)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user.php(162): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(1073): OC_User::login(*** username and password replaced ***)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(969): OC::tryFormLogin()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(931): OC::handleLogin()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":476}","level":3,"time":"March 30, 2016 09:45:11"}
{"reqId":"EFVLeC6jDirUqdjdnA3F","remoteAddr":"213.3.25.41","app":"gallery","message":"Exception: Preview generation has failed","level":3,"time":"March 30, 2016 09:45:23"}
{"reqId":"5GrA4I+ZT1tfO9+3CSa2","remoteAddr":"213.3.25.41","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Bad Signature\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(456): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('PEEMCtH+WSinDG6...', '???+????n??????...', '1e71fc7173f7e65...')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(416): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('PEEMCtH+WSinDG6...', '???+????n??????...', 'AES-256-CTR', 0)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/keymanager.php(354): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decryptPrivateKey('HBEGIN:cipher:A...', 'Mineral1', 'test1')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/hooks\\\/userhooks.php(162): OCA\\\\Encryption\\\\KeyManager->init('test1', 'Mineral1')\\n#4 [internal function]: OCA\\\\Encryption\\\\Hooks\\\\UserHooks->login(*** username and password replaced ***)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hook.php(105): call_user_func(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(235): OC_Hook::emit('OC_User', 'post_login', Array)\\n#7 [internal function]: OC\\\\Server->OC\\\\{closure}(Object(OC\\\\User\\\\User), 'Mineral1')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/emittertrait.php(98): call_user_func_array(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/publicemitter.php(32): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\OC\\\\User', 'postLogin', Array)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(225): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\OC\\\\User', 'postLogin', Array)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user.php(162): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(1073): OC_User::login(*** username and password replaced ***)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(969): OC::tryFormLogin()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(931): OC::handleLogin()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":476}","level":3,"time":"March 30, 2016 09:45:34"}
{"reqId":"5GrA4I+ZT1tfO9+3CSa2","remoteAddr":"213.3.25.41","app":"handleLogin","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Bad Signature\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(456): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('PEEMCtH+WSinDG6...', '???+????n??????...', '1e71fc7173f7e65...')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(416): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('PEEMCtH+WSinDG6...', '???+????n??????...', 'AES-256-CTR', 0)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/keymanager.php(354): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decryptPrivateKey('HBEGIN:cipher:A...', 'Mineral1', 'test1')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/hooks\\\/userhooks.php(162): OCA\\\\Encryption\\\\KeyManager->init('test1', 'Mineral1')\\n#4 [internal function]: OCA\\\\Encryption\\\\Hooks\\\\UserHooks->login(*** username and password replaced ***)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hook.php(105): call_user_func(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(235): OC_Hook::emit('OC_User', 'post_login', Array)\\n#7 [internal function]: OC\\\\Server->OC\\\\{closure}(Object(OC\\\\User\\\\User), 'Mineral1')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/emittertrait.php(98): call_user_func_array(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/hooks\\\/publicemitter.php(32): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\OC\\\\User', 'postLogin', Array)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(225): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\OC\\\\User', 'postLogin', Array)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user.php(162): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(1073): OC_User::login(*** username and password replaced ***)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(969): OC::tryFormLogin()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(931): OC::handleLogin()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":476}","level":3,"time":"March 30, 2016 09:45:34"}

```

**Comment by LukasReschke** [comment]
> 6. restore deleted files from backup (via SCP)

This is the expected behaviour. You can't just restore single files that day. You also need to restore the version which is stored within the database.

**Comment by RealRancor** [comment]
Might be something which should be documented within https://github.com/owncloud/documentation/issues/2131

**Comment by victorbw** [comment]
Thank you guys, obviously this hint with the sql-backup wasnt clear enough (for me, and probably many other users), i'd appreciate to clarify this a little more on upcomming documentations.
