### ISSUE TITLE
Uncaught Error: Call to a member function getRequest() on null in response.php

### ISSUE THREAD

**Issue by d3xt3r01** [owncloud/core#23814]
### Steps to reproduce
1. try to load owncloud

### Expected behaviour
The login site should appear

### Actual behaviour
error 500

### Server configuration
**Operating system**:
Gentoo

**Web server:**
apache-2.4.18

**Database:**
mariadb-10.0.23

**PHP version:**
7.0.4-pl1-gentoo

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Updated from an older ownCloud or fresh install:**
updated

**Where did you install ownCloud from:**
www-apps/owncloud

**Signing status (ownCloud 9.0 and above):**
Not available

**List of activated apps:**
Not available

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => '***SECRET***',
  'passwordsalt' => '***SECRET***',
  'updatechecker' => false,
  'knowledgebaseenabled' => false,
  'trusted_domains' =>
  array (
    0 => 'd3xbucharest.go.ro',
  ),
  'appstoreenabled' => true,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'datadirectory' => '/var/www/d3xbucharest.go.ro/htdocs/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '***SECRET***',
  'installed' => true,
  'forcessl' => true,
  'mail_domain' => 'asandu.eu',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'sharing-noreply@asandu.eu',
  'mail_smtppassword' => '***SECRET***',
  'theme' => '',
  'secret' => '***SECRET***',
  'trashbin_retention_obligation' => '180, auto',
  'overwrite.cli.url' => '/owncloud',
  'loglevel' => 0,
  'maintenance' => false,
  'cache_path' => '',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/d3xbucharest.go.ro/htdocs/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 49 / CLI

**Operating system:**
Windows / Linux

#### Web server error log
```
[05-Apr-2016 20:32:26] WARNING: [pool www] child 18319 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getRequest() on null in /var/www/d3xbucharest.go.ro/htdocs/owncloud/lib/private/response.php:77"
[05-Apr-2016 20:32:26] WARNING: [pool www] child 18319 said into stderr: "Stack trace:"
[05-Apr-2016 20:32:26] WARNING: [pool www] child 18319 said into stderr: "#0 /var/www/d3xbucharest.go.ro/htdocs/owncloud/lib/base.php(512): OC_Response::setStatus(503)"
[05-Apr-2016 20:32:26] WARNING: [pool www] child 18319 said into stderr: "#1 /var/www/d3xbucharest.go.ro/htdocs/owncloud/lib/base.php(1103): OC::init()"
[05-Apr-2016 20:32:26] WARNING: [pool www] child 18319 said into stderr: "#2 /var/www/d3xbucharest.go.ro/htdocs/owncloud/index.php(37): require_once('/var/www/d3xbuc...')"
[05-Apr-2016 20:32:26] WARNING: [pool www] child 18319 said into stderr: "#3 {main}"
[05-Apr-2016 20:32:26] WARNING: [pool www] child 18319 said into stderr: "  thrown in /var/www/d3xbucharest.go.ro/htdocs/owncloud/lib/private/response.php on line 77"
```

#### ownCloud log (data/owncloud.log)
nothing

#### Browser log
nothing

**Comment by RealRancor** [comment]
Looks like a dup of https://github.com/owncloud/core/issues/23031 and/or https://github.com/owncloud/core/issues/21169

**Comment by d3xt3r01** [comment]
True, the patch here seems to have fixed this.

https://github.com/owncloud/core/pull/23032/files
