### ISSUE TITLE
favicon.ico --> no such file or directory

### ISSUE THREAD

**Issue by fotastisch** [owncloud/core#23852]
Hi!

I will add more infos when I've found them, I don't know all of them yet.
### Steps to reproduce
1. access owncloud via website/android app/synchronization profile

### Expected behaviour
Show website, synchronization

### Actual behaviour
nothing, internal server error

### Server configuration
**Operating system**: Raspbian Jessie

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 5.6? (I'll check that)

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar.bz2

**Signing status (ownCloud 9.0 and above):** ?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /var/www/owncloud/lib/private/db/connection.php:54
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/owncloud/lib/private/db/connection.php(137): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/owncloud/lib/private/db/connectionfactory.php(118): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/owncloud/lib/private/server.php(366): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/owncloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /var/www/owncloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /var/www/owncloud/lib/private/server.php(886): OC\ServerContainer->query('DatabaseConnect...')
#12 /var/www/owncloud/lib/private/server.php(260): OC\Server->getDatabaseConnection()
#13 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /var/www/owncloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('AppConfig')
#15 /var/www/owncloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /var/www/owncloud/lib/private/server.php(825): OC\ServerContainer->query('AppConfig')
#17 /var/www/owncloud/lib/private/util.php(424): OC\Server->getAppConfig()
#18 /var/www/owncloud/lib/private/util.php(357): OC_Util::loadVersion()
#19 /var/www/owncloud/lib/public/util.php(72): OC_Util::getVersion()
#20 /var/www/owncloud/lib/private/util.php(1448): OCP\Util::getVersion()
#21 /var/www/owncloud/lib/public/util.php(693): OC_Util::needUpgrade(Object(OC\AllConfig))
#22 /var/www/owncloud/lib/base.php(357): OCP\Util::needUpgrade()
#23 /var/www/owncloud/lib/base.php(643): OC::checkUpgrade(false)
#24 /var/www/owncloud/lib/base.php(1112): OC::init()
#25 /var/www/owncloud/console.php(46): require_once('/var/www/ownclo...')
#26 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')


**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'XXX',
  ),
  'datadirectory' => '/media/owncloud/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '9.0.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'XXX',
  'installed' => true,
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_smtpmode' => 'smtp',
  'mail_smtpname' => 'XXX',
  'mail_smtppassword' => 'XXX',
  'mail_from_address' => 'XXX',
  'mail_domain' => 'XXX',
  'mail_smtpauth' => true,
  'mail_smtpport' => '587',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'XXX',
  'mail_smtpauthtype' => 'PLAIN',
  'secret' => 'XXX',
  'appstore.experimental.enabled' => true,
  'trashbin_retention_obligation' => 'auto',
);


Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory)

#### ownCloud log (data/owncloud.log)
```
seems empty?

**Comment by Xenopathic** [comment]
```
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'
```

It's almost like the log message is telling you what the problem is...

**Comment by fotastisch** [comment]
Damn, I had not noticed that, I was just looking at the nginx errors... MySQL shows up in the processes, but should also show up when running `sudo find / -type s`? (Because it doesn't.)

**Comment by fotastisch** [comment]
Oh, and thanks of course for that hint when I was blind (again)! ;)

**Comment by Xenopathic** [comment]
Either your MySQL is listening on a TCP socket, in which case ownCloud needs to be connecting to 127.0.0.1:3306, or it's listening on a UNIX socket at /var/run/mysqld/mysqld.sock, in which case ownCloud is correctly configured (but you have some other issue). I'd suggest checking your MySQL configuration, and if you continue to have problems, ask over at https://owncloud.org/support
