### ISSUE TITLE
Issue with Apps in OwnCloud (latest version)

### ISSUE THREAD

**Issue by CheapApples12** [owncloud/core#23896]
### Steps to reproduce
1. Download OwnCloud
2. Encounter issues that piss me off

### Expected behaviour
What should happen, is apps should not only appear on the Apps page, but also not display the exact same content for every single category, and in some cases - not show apps at all. I want to enable encryption, and it's not even on the Apps page. Furthermore, the apps page contains only activated apps, all of the other categories display the exact same content. https://i.gyazo.com/e088ef5ab1ed63b43ca0e72230f30501.mp4

### Server configuration
**Database:** MySQL

**PHP version:** 5.5

**Where did you install ownCloud from:** I have tried both the Archive File and Web Installer in different directories

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
```
No errors have been found.

```

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'ocuzrx5g6q83',
  'passwordsalt' => '#####',
  'secret' => #####',
  'trusted_domains' => 
  array (
    0 => 'www.advenacm.com',
    1 => 'advenacm.com',
  ),
  'datadirectory' => '/home/advenacm/public_html/box/data',
  'overwrite.cli.url' => 'https://www.advenacm.com/box',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'advenacm_box',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'advenacm_box',
  'dbpassword' => '#######',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => false,
);

```
**Are you using encryption:** no (duhh)

### Client configuration
**Browser:** Google Chrome Version 50.0.2661.66 beta-m (64-bit)

**Operating system:** Windows 10.1 (Preview Build)

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VwqLKB-caaMACNTTg4sAAAMF","remoteAddr":"106.69.42.119","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/session\\\/memory.php(49): OC\\\\Session\\\\Memory->validateSession()\\n#1 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/security\\\/csrf\\\/tokenstorage\\\/sessionstorage.php(63): OC\\\\Session\\\\Memory->set('requesttoken', 'Yqp9T5ZOzCo4dGp...')\\n#2 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/security\\\/csrf\\\/csrftokenmanager.php(57): OC\\\\Security\\\\CSRF\\\\TokenStorage\\\\SessionStorage->setToken('Yqp9T5ZOzCo4dGp...')\\n#3 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/public\\\/util.php(496): OC\\\\Security\\\\CSRF\\\\CsrfTokenManager->getToken()\\n#4 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/template.php(75): OCP\\\\Util::callRegister()\\n#5 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/template.php(302): OC_Template->__construct('', 'installation', 'guest')\\n#6 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/core\\\/controller\\\/setupcontroller.php(95): OC_Template::printGuestPage('', 'installation', Array)\\n#7 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/core\\\/controller\\\/setupcontroller.php(75): OC\\\\Core\\\\Controller\\\\SetupController->display(Array)\\n#8 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/base.php(832): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/session\\\/memory.php\",\"Line\":105}","level":3,"time":"2016-04-10T17:19:38+00:00","method":"GET","url":"\/box\/","user":"--"}
{"reqId":"VwqLwB-caaMACNT1c0oAAANG","remoteAddr":"106.69.42.119","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2016-04-10T17:22:11+00:00","method":"POST","url":"\/box\/index.php","user":"--"}
{"reqId":"VwqLwB-caaMACNT1c0oAAANG","remoteAddr":"106.69.42.119","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2016-04-10T17:22:11+00:00","method":"POST","url":"\/box\/index.php","user":"--"}
{"reqId":"VwqLwB-caaMACNT1c0oAAANG","remoteAddr":"106.69.42.119","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_bradley.hodge\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'advenacm_box'@'localhost' for table 'user'","level":3,"time":"2016-04-10T17:22:11+00:00","method":"POST","url":"\/box\/index.php","user":"--"}
{"reqId":"VwqLwB-caaMACNT1c0oAAANG","remoteAddr":"106.69.42.119","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2016-04-10T17:22:11+00:00","method":"POST","url":"\/box\/index.php","user":"--"}
{"reqId":"VwqLwB-caaMACNT1c0oAAANG","remoteAddr":"106.69.42.119","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `advenacm_box` . * TO 'advenacm_box'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'advenacm_box'@'localhost' to database 'advenacm_box'","level":3,"time":"2016-04-10T17:22:11+00:00","method":"POST","url":"\/box\/index.php","user":"--"}
{"reqId":"VwqLwB-caaMACNT1c0oAAANG","remoteAddr":"106.69.42.119","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/installer.php(639): include('\\\/home\\\/advenacm\\\/...')\\n#4 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/installer.php(590): OC_Installer::includeAppScript('\\\/home\\\/advenacm\\\/...')\\n#5 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/installer.php(561): OC_Installer::installShippedApp('dav')\\n#6 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/base.php(832): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/advenacm\\\/public_html\\\/box\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-04-10T17:22:15+00:00","method":"POST","url":"\/box\/index.php","user":"--"}
{"reqId":"VwqLwB-caaMACNT1c0oAAANG","remoteAddr":"106.69.42.119","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/installer.php(639): include('\\\/home\\\/advenacm\\\/...')\\n#4 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/installer.php(590): OC_Installer::includeAppScript('\\\/home\\\/advenacm\\\/...')\\n#5 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/installer.php(561): OC_Installer::installShippedApp('dav')\\n#6 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/lib\\\/base.php(832): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/home\\\/advenacm\\\/public_html\\\/box\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/advenacm\\\/public_html\\\/box\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-04-10T17:22:15+00:00","method":"POST","url":"\/box\/index.php","user":"--"}
{"reqId":"VwqLwB-caaMACNT1c0oAAANG","remoteAddr":"106.69.42.119","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2016-04-10T17:22:15+00:00","method":"POST","url":"\/box\/index.php","user":"--"}
{"reqId":"VwqLwB-caaMACNT1c0oAAANG","remoteAddr":"106.69.42.119","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2016-04-10T17:22:15+00:00","method":"POST","url":"\/box\/index.php","user":"bradley.hodges@advenacm.com"}
{"reqId":"VwqL8B-caaMACNR4rNIAAAEF","remoteAddr":"106.69.42.119","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2016-04-10T17:22:56+00:00","method":"POST","url":"\/box\/settings\/apps\/experimental","user":"bradley.hodges@advenacm.com"}
{"reqId":"VwqNgB-caaMACWnDtCAAAABR","remoteAddr":"106.69.42.119","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2016-04-10T17:29:36+00:00","method":"POST","url":"\/box\/settings\/apps\/experimental","user":"bradley.hodges@advenacm.com"}
{"reqId":"VwqOax-caaMACQH62c4AAAAC","remoteAddr":"106.69.42.119","app":"core","message":"Trusted domain error. \"106.69.42.119\" tried to access using \"advenacm.com\" as host.","level":2,"time":"2016-04-10T17:33:31+00:00","method":"GET","url":"\/box\/version.php","user":"--"}
{"reqId":"VwqObR-caaMACW3jnO8AAACF","remoteAddr":"106.69.42.119","app":"core","message":"Trusted domain error. \"106.69.42.119\" tried to access using \"advenacm.com\" as host.","level":2,"time":"2016-04-10T17:33:33+00:00","method":"GET","url":"\/box\/core\/js\/oc.js?v=f474051010667eafc3e139228b8e9c48","user":"--"}
{"reqId":"VwqObx-caaMACNSUIJUAAAFF","remoteAddr":"106.69.42.119","app":"core","message":"Trusted domain error. \"106.69.42.119\" tried to access using \"advenacm.com\" as host.","level":2,"time":"2016-04-10T17:33:35+00:00","method":"GET","url":"\/box\/cron.php","user":"--"}
{"reqId":"VwqOeB-caaMACW3jnUwAAACM","remoteAddr":"106.69.42.119","app":"core","message":"Trusted domain error. \"106.69.42.119\" tried to access using \"advenacm.com\" as host.","level":2,"time":"2016-04-10T17:33:44+00:00","method":"GET","url":"\/box\/version.php","user":"--"}
{"reqId":"VwqOeh-caaMACW3jnWMAAACV","remoteAddr":"106.69.42.119","app":"core","message":"Trusted domain error. \"106.69.42.119\" tried to access using \"advenacm.com\" as host.","level":2,"time":"2016-04-10T17:33:46+00:00","method":"GET","url":"\/box\/core\/js\/oc.js?v=f474051010667eafc3e139228b8e9c48","user":"--"}
{"reqId":"VwqOfB-caaMACW3jnZMAAACF","remoteAddr":"106.69.42.119","app":"core","message":"Trusted domain error. \"106.69.42.119\" tried to access using \"advenacm.com\" as host.","level":2,"time":"2016-04-10T17:33:48+00:00","method":"GET","url":"\/box\/cron.php","user":"--"}
{"reqId":"VwqOhh-caaMACW3jnhAAAACS","remoteAddr":"106.69.42.119","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2016-04-10T17:33:58+00:00","method":"POST","url":"\/box\/settings\/admin\/security\/trustedDomains","user":"bradley.hodges@advenacm.com"}

```

**Comment by RealRancor** [comment]
@CheapApples12 As your logfile contains some stuff about xcache try to disable that to see if that is causing your issue.

**Comment by DeepDiver1975** [comment]
> Encounter issues that piss me off

Because no one of the contributors wants to read something like this I'm closing this with the reference to https://owncloud.org/community/code-of-conduct/

**Comment by CheapApples12** [comment]
Well, Thank you for your abundance of assistance @DeepDiver1975
