### ISSUE TITLE
[9.0.1] avatar is not loaded and uploading a new one results in error

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#23892]
````
{"reqId":"6UoFWFkGGHNtAV00Y5hR","remoteAddr":"188.194.67.114","app":"core","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotPermittedException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/avatar.php(127): OC\\\\Files\\\\Node\\\\Folder->newFile('avatar.jpg')\\n#1 \\\/var\\\/www\\\/owncloud\\\/core\\\/controller\\\/avatarcontroller.php(315): OC\\\\Avatar->set(Object(OC_Image))\\n#2 [internal function]: OC\\\\Core\\\\Controller\\\\AvatarController->postCroppedAvatar(Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\AvatarController), 'postCroppedAvat...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\AvatarController), 'postCroppedAvat...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('AvatarControlle...', 'postCroppedAvat...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(276): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(882): OC\\\\Route\\\\Router->match('\\\/avatar\\\/cropped')\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/folder.php\",\"Line\":171}","level":3,"time":"2016-04-10T10:05:49+00:00","method":"POST","url":"\/avatar\/cropped","user":"deepdiver"}

**Comment by DeepDiver1975** [comment]
closing in favor of https://github.com/owncloud/core/issues/22978
