### ISSUE TITLE
CalDav not working with Mac OS X Agenda application

### ISSUE THREAD

**Issue by alex3137** [owncloud/core#23908]
### Steps to reproduce
1. Create a new calendar from Owncloud web GUI
2. Configure this calendar in OS X Calendar application

### Expected behaviour
The calendar is added to OS X Calendar app

### Actual behaviour
Calendar is app is unable to verify account name or password

### Server configuration
**Operating system**: Debian 8.4

**Web server:** Apache 2.4.10

**Database:** SQLlite

**PHP version:** PHP 5.6.19

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** Official Debian package

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
    "system": {
        "updatechecker": false,
        "instanceid": "oc8pou1n9s2p",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.besnard.me"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/owncloud.besnard.me",
        "dbtype": "sqlite3",
        "version": "9.0.1.3",
        "logtimezone": "UTC",
        "installed": true
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** Encryption is provided by my HAProxy front-end

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Apple Calendar 8.0

**Operating system:** Mac OS X 10.11.4

#### Web server error log
```
10.10.10.100 - - [11/Apr/2016:10:45:27 +0000] "PROPFIND /.well-known/caldav HTTP/1.1" 301 577 "-" "Mac+OS+X/10.11.4 (15E65) accountsd/113"
10.10.10.100 - - [11/Apr/2016:10:45:27 +0000] "PROPFIND / HTTP/1.1" 405 1004 "-" "Mac+OS+X/10.11.4 (15E65) accountsd/113"
10.10.10.100 - - [11/Apr/2016:10:45:27 +0000] "PROPFIND /caldav/v2 HTTP/1.1" 405 539 "-" "Mac+OS+X/10.11.4 (15E65) accountsd/113"
10.10.10.100 - - [11/Apr/2016:10:45:27 +0000] "PROPFIND /principals/users/Alex/ HTTP/1.1" 405 552 "-" "Mac+OS+X/10.11.4 (15E65) accountsd/113"
10.10.10.100 - - [11/Apr/2016:10:45:27 +0000] "PROPFIND /principals/ HTTP/1.1" 405 541 "-" "Mac+OS+X/10.11.4 (15E65) accountsd/113"
10.10.10.100 - - [11/Apr/2016:10:45:27 +0000] "PROPFIND /dav/principals/ HTTP/1.1" 405 545 "-" "Mac+OS+X/10.11.4 (15E65) accountsd/113"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"JCvIGEFm6hozpSGdJ12v","remoteAddr":"10.10.10.100","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(639): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(590): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(561): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(832): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-04-11T10:19:50+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"JCvIGEFm6hozpSGdJ12v","remoteAddr":"10.10.10.100","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(639): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(590): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(561): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(832): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-04-11T10:19:50+00:00","method":"POST","url":"\/index.php","user":"--"}
```

**Comment by RealRancor** [comment]
405 means "Method not allowed" which is an issue within your webservers config not allowing this PROPFIND method.

You can close this issue and follow https://forum.owncloud.org/viewtopic.php?f=17&t=7536 how to fix your webservers config to provide that needed method.

**Comment by alex3137** [comment]
I removed my HAproxy server between my client and my owncloud server.

I still have the same issue and I don't understand from your link what modifications I need to apply on my Apache configuration (which was provided as part of the owncloud install btw).

The only modification I did from the default install is to modifiy DocumentRoot in apache default vhost to /var/www/owncloud

**Comment by RealRancor** [comment]
Please use the forums or the users mailinglist to get support for such configuration issues.

**Comment by alex3137** [comment]
Hum ok.... but isn't the apache configuration provided with Owncloud supposed to support *dav ??

**Comment by RealRancor** [comment]
There is no apache config provided by ownCloud, only a basic alias and minor other stuff. Various Apache configs and modules like mod_security could cause this issue and that is nothing what can be fixed by ownCloud.

Please use the forums / mailinglist as already advised for more support. The issue tracker here isn't the place to give support like this.
