### ISSUE TITLE
Uknown property displayname on login

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#24057]
#Plain install of current master. I got following on login in the log (web UI works fine):

```json
{
    "app": "no app in context",
    "level": 3,
    "message": {
        "Code": 0,
        "Exception": "Sabre\\DAV\\Exception\\BadRequest",
        "File": "apps/dav/lib/carddav/carddavbackend.php",
        "Line": 299,
        "Message": "Unknown property: displayname",
        "Trace": "
            #0 apps/dav/lib/hookmanager.php(118): OCA\\DAV\\CardDAV\\CardDavBackend->createAddressBook('principals/user...', 'contacts', Array)
            #1 [internal function]: OCA\\DAV\\HookManager->postLogin(Array)
            #2 lib/private/hook.php(105): call_user_func(Array, Array)
            #3 lib/private/Server.php(244): OC_Hook::emit('OC_User', 'post_login', Array)
            #4 [internal function]: OC\\Server->OC\\{closure}(Object(OC\\User\\User), 'mjob')
            #5 lib/private/Hooks/EmitterTrait.php(98): call_user_func_array(Object(Closure), Array)
            #6 lib/private/Hooks/PublicEmitter.php(32): OC\\Hooks\\BasicEmitter->emit('\\OC\\User', 'postLogin', Array)
            #7 lib/private/User/Session.php(225): OC\\Hooks\\PublicEmitter->emit('\\OC\\User', 'postLogin', Array)
            #8 lib/private/user.php(162): OC\\User\\Session->login(*** username and password replaced ***)
            #9 lib/base.php(1040): OC_User::login(*** username and password replaced ***)
            #10 lib/base.php(925): OC::tryFormLogin()
            #11 lib/base.php(887): OC::handleLogin()
            #12 index.php(39): OC::handleRequest()
            #13 {main}
        "
    },
    "method": "POST",
    "remoteAddr": "::1",
    "reqId": "/jrH/Un7YwX6JjSdrrMm",
    "time": "2016-04-18T10:38:18+00:00",
    "url": "/master/",
    "user": "mjob"
}
```

cc @DeepDiver1975 @LukasReschke

**Comment by MorrisJobke** [comment]
I just noticed that this only happens on https://github.com/owncloud/core/pull/24056

**Comment by MorrisJobke** [comment]
Possible fix:

```patch
diff --git a/apps/dav/lib/hookmanager.php b/apps/dav/lib/hookmanager.php
index 4a4704f..f63e9c1 100644
--- a/apps/dav/lib/hookmanager.php
+++ b/apps/dav/lib/hookmanager.php
@@ -115,7 +115,7 @@ class HookManager {
        if (empty($books)) {
            try {
                $this->cardDav->createAddressBook($principal, 'contacts', [
-                   'displayname' => 'Contacts']);
+                   '{DAV:}displayname' => 'Contacts']);
            } catch (\Exception $ex) {
                \OC::$server->getLogger()->logException($ex);
            }
```

**Comment by nickvergessen** [comment]
Fix looks good

**Comment by nickvergessen** [comment]
Received the same error on master now

**Comment by DeepDiver1975** [comment]
WTF! - I fixed this on the PR .....
