### ISSUE TITLE
Clean/Fix exceptions when running integration tests

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#24121]
Currently while runnning integration tests several carddav exception are thrown with every step.

This creates a lot of noise in the output of the tests. Will be better to have it silenced.
```
[Wed Apr 20 10:50:46 2016] Exception: {"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"Unknown property: displayname","Code":0,"Trace":"#0 \/var\/www\/html\/desarrollo_tests5\/apps\/dav\/lib\/hookmanager.php(118): OCA\\DAV\\CardDAV\\CardDavBackend->createAddressBook('principals\/user...', 'contacts', Array)\n#1 [internal function]: OCA\\DAV\\HookManager->postLogin(Array)\n#2 \/var\/www\/html\/desarrollo_tests5\/lib\/private\/hook.php(105): call_user_func(Array, Array)\n#3 \/var\/www\/html\/desarrollo_tests5\/lib\/private\/Server.php(243): OC_Hook::emit('OC_User', 'post_login', Array)\n#4 [internal function]: OC\\Server->OC\\{closure}(Object(OC\\User\\User), 'admin')\n#5 \/var\/www\/html\/desarrollo_tests5\/lib\/private\/hooks\/emittertrait.php(98): call_user_func_array(Object(Closure), Array)\n#6 \/var\/www\/html\/desarrollo_tests5\/lib\/private\/hooks\/publicemitter.php(32): OC\\Hooks\\BasicEmitter->emit('\\OC\\User', 'postLogin', Array)\n#7 \/var\/www\/html\/desarrollo_tests5\/lib\/private\/user\/session.php(226): OC\\Hooks\\PublicEmitter->emit('\\OC\\User', 'postLogin', Array)\n#8 \/var\/www\/html\/desarrollo_tests5\/lib\/private\/user.php(160): OC\\User\\Session->login(*** username and password replaced ***)\n#9 \/var\/www\/html\/desarrollo_tests5\/lib\/private\/api.php(359): OC_User::login(*** username and password replaced ***)\n#10 \/var\/www\/html\/desarrollo_tests5\/lib\/private\/api.php(297): OC_API::loginUser()\n#11 \/var\/www\/html\/desarrollo_tests5\/lib\/private\/api.php(156): OC_API::isAuthorised(Array)\n#12 [internal function]: OC_API::call(Array)\n#13 \/var\/www\/html\/desarrollo_tests5\/lib\/private\/route\/router.php(280): call_user_func(Array, Array)\n#14 \/var\/www\/html\/desarrollo_tests5\/ocs\/v1.php(52): OC\\Route\\Router->match('\/ocs\/cloud\/user...')\n#15 \/var\/www\/html\/desarrollo_tests5\/ocs\/v2.php(22): require_once('\/var\/www\/html\/d...')\n#16 {main}","File":"\/var\/www\/html\/desarrollo_tests5\/apps\/dav\/lib\/carddav\/carddavbackend.php","Line":299}

```

**Comment by SergioBertolinSG** [comment]
cc @DeepDiver1975

**Comment by MorrisJobke** [comment]
Should be fixed with https://github.com/owncloud/core/pull/24076

@SergioBertolinSG Please check that you have the latest master. Reopen if this issue still exist on latest master. Thanks.
