### ISSUE TITLE
CardDav Error at sync with OwnCloud/outlookcaldavsynchronizer

### ISSUE THREAD

**Issue by hegGK** [owncloud/core#24193]
When using caldavsynchronizer to sync carddav-data with owncloud, I get a 404 error from owncloud.
I reported that to CalDavSynchronizer at got this answer below which suggest a problem in OwnCloud.

The setup:
- hosted Owncloud V9.0.1
- W7 64 Client
- Outlook with CalDavSync 2.1.0.0
- One adressbook in OwnCloud synchronized with one adressbook in outlook

Any help is appreciated.

J. Hergeth
### The answer of the CalDavSynchronizer-Team is:

> The server returns a 404-error-response. As far as I know this should not happen, when executing an "addressbook-multiget". The Server should return a DAV:multistatus, which is containing a 404 error.
> IMHO this is a Bug on the server side.
> As a temporary workaround it should help, if you clear the cache of the affected profile.
> br
> Gerhard
> 
> [tickets:#289] CardDav Error at sync with OwnCloud
> Status: open
> Milestone: 1.0
> Created: Wed Apr 20, 2016 08:52 AM UTC by Joachim Hergeth
> Last Updated: Wed Apr 20, 2016 08:52 AM UTC
> Owner: nobody
> During synchronisation with an Owncloud server i get the error message below. It is totaly reproducable. I already deleted the profile an created it again. No change.
> Any suggestions?
> J. Hergeth
### The CalDavSynchronizer error message is:

```
<?xml version="1.0" encoding="utf-16"?>

Schulkontakte
4d554982-0b68-484d-9519-d7fd391fe818
2016-04-22T06:35:43.1677829Z


CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '404' ('NotFound'). Message:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>Card not found</s:message>
</d:error>

at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<EnsureSuccessStatusCode>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at CalDavSynchronizer.DataAccess.CardDavDataAccess.<GetEntities>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at CalDavSynchronizer.Implementation.Contacts.CardDavRepository.<Get>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at GenSync.Synchronization.Synchronizer7.EntityContainer.&lt;FillIfEmpty&gt;d__11.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at GenSync.Synchronization.Synchronizer7.<Synchronize>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at GenSync.Synchronization.Synchronizer7.&lt;SynchronizeNoThrow&gt;d__17.MoveNext()</ExceptionThatLeadToAbortion> <Duration>00:00:01.8660000</Duration> </Synchronization> 

```
### The Owncloud error message is:

```
Debug caldav Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\DAV\Exception\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#1 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#4 \/var\/www\/html\/owncloud\/apps\/dav\/appinfo\/v1\/caldav.php(76): Sabre\DAV\Server->exec()\n#5 \/var\/www\/html\/owncloud\/remote.php(138): require_once('\/var\/www\/html\/o...')\n#6 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false} 2016-04-22T06:52:15+00:00

Debug caldav Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\DAV\Exception\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#1 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#4 \/var\/www\/html\/owncloud\/apps\/dav\/appinfo\/v1\/caldav.php(76): Sabre\DAV\Server->exec()\n#5 \/var\/www\/html\/owncloud\/remote.php(138): require_once('\/var\/www\/html\/o...')\n#6 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}
```

**Comment by RealRancor** [comment]
@hegGK It might be useful to provide the URL you're using for accessing the address book (replace sensitive data within it).

**Comment by hegGK** [comment]
The URL is:
https://<servername>/owncloud/remote.php/dav/addressbooks/users/<username>/<adressbookname>/

where each of the <...> contains only ASCII chars.

**Comment by DeepDiver1975** [comment]
@evert Can I ask you to comment on this behavior?

I can simply reporduce this be sending an addressbook multiget request to the server asking for vcard which do not exist (e.g. having an invalid principal or addressbook name)
![bildschirmfoto von 2016-04-25 11-33-32](https://cloud.githubusercontent.com/assets/1005065/14779793/055e6650-0ada-11e6-9109-ba8143ee1cbe.png)


In case the vcard name itself is not available in the addressbook no result is returned:
![bildschirmfoto von 2016-04-25 11-32-54](https://cloud.githubusercontent.com/assets/1005065/14779665/7d3162c8-0ad9-11e6-81fd-af1b36747a07.png)

**Comment by DeepDiver1975** [comment]
out of scope for 9.1 -> 9.2

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).

**Comment by rm2342** [comment]
Has this issue been fixed? I have the exact same problem ("Card not found" message).

Here is the error msg from the owncloud.log:
{"reqId":"UIiDQMD9qSPRi5N3R7RD","level":0,"time":"2018-09-06T04:31:30+00:00","remoteAddr":"<replaced sensitive info>","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/remote.php\/carddav\/addressbooks\/<replaced sensitive info>\/","message":"token ef3a10c4c38a0e3d3f412d3a2bf1fb2bcc296dad1fcc217a3249377aa8985202add4f4e353847c07799fcc4b858c193a135f43d5199ed6dc0eb1a08bbfdcdc8d does not exist"}

Thank you!
