### ISSUE TITLE
PostgreSQL setup: lost control on error

### ISSUE THREAD

**Issue by strk** [owncloud/core#24220]
### Steps to reproduce
1. install
2. go to /owncloud URI to do setup
3. select PostgreSQL database backend
4. enter username/password/host:port
5. click install/setup (whatever the button says)

### Expected behaviour
Either get an error while still being able to change the setup or move over

### Actual behaviour
An error is printed and I cannot modify the configuration from the web anymore.
The error is:
```
Error occurred while checking PostgreSQL version
Please make sure you have PostgreSQL >= 9 or check the logs for more information about the error
```

**ownCloud version:** (see ownCloud admin page)
8.1.6

**Where did you install ownCloud from:**
http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_8.0/

### More info

The error in the log:
```js
{"reqId":"\/h7lklo\/NPasFBR3\/FJW","remoteAddr":"xx.xx.xx.xx","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",\"Message\":\"Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] fe_sendauth: no password supplied\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(429): OC\\\\DB\\\\Connection->connect()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(389): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatformVersion()\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(328): Doctrine\\\\DBAL\\\\Connection->detectDatabasePlatform()\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(621): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatform()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(83): Doctrine\\\\DBAL\\\\Connection->setTransactionIsolation(2)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DriverManager.php(172): OC\\\\DB\\\\Connection->__construct(Array, Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connectionfactory.php(124): Doctrine\\\\DBAL\\\\DriverManager::getConnection(Array, Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/server.php(302): OC\\\\DB\\\\ConnectionFactory->getConnection('pgsql', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(96): Pimple\\\\Container->offsetGet('DatabaseConnect...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/server.php(697): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('DatabaseConnect...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db.php(66): OC\\\\Server->getDatabaseConnection()\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db.php(143): OC_DB::prepare('SHOW SERVER_VER...', NULL, NULL)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(802): OC_DB::executeAudited('SHOW SERVER_VER...')\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(782): OC_Util::checkDatabaseVersion()\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(607): OC_Util::checkServer(Object(OC\\\\AllConfig))\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1122): OC::init()\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(46): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php\",\"Line\":50}","level":4,"time":"2016-04-24T10:25:37+00:00"}
```

**Comment by strk** [comment]
The config/config.php contains a `dbname` and `dbhost` variable but no `dbuser` and `dbpassword`, is that expected ?

**Comment by strk** [comment]
NOTE: manually adding `dbuser` and `dbpassword` in the `config.php` file and reloading the `/owncloud` url gives me back the initial (install) form while the PostgreSQL log show owncloud querying an `oc_appconfig` table for a `installed_version` key, not finding the table.

So it seems to be impossible to use PostgreSQL backend with this version

**Comment by strk** [comment]
I can NOT reproduce with version 9.0.1, so assuming fixed.
