### ISSUE TITLE
Dav: Internal Server Error "This is not supposed to happen"

### ISSUE THREAD

**Issue by skjnldsv** [owncloud/core#24263]
I have a strange error with `/apps/dav/lib/carddav/plugin.php`
I just accessed https://localhost:8080/remote.php/dav/principals/groups/admin/.
Nothing else in the log. Using the last calendar app, last core with the export patch (24c2252ff4af9838019da1a56ef11956a4d418ee) and contact from master.

@DeepDiver1975 

```
Internal Server Error
This is not supposed to happen

Technical details
Remote Address: 127.0.0.1
Request ID: aMkNa+tu6THLdVfQLVZ6
Type: LogicException
Code: 0
Message: This is not supposed to happen
File: /usr/share/webapps/owncloud/apps/dav/lib/carddav/plugin.php
Line: 54

Trace
#0 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php(159): OCA\DAV\CardDAV\Plugin->getAddressbookHomeForPrincipal('principals/grou...')
#1 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Browser/PropFindAll.php(53): Sabre\CardDAV\Plugin->Sabre\CardDAV\{closure}()
#2 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php(160): Sabre\DAV\Browser\PropFindAll->handle('{urn:ietf:param...', Object(Closure))
#3 [internal function]: Sabre\CardDAV\Plugin->propFindEarly(Object(Sabre\DAV\Browser\PropFindAll), Object(Sabre\CalDAV\Principal\User))
#4 /usr/share/webapps/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#5 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(999): Sabre\Event\EventEmitter->emit('propFind', Array)
#6 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Browser/Plugin.php(338): Sabre\DAV\Server->getPropertiesByNode(Object(Sabre\DAV\Browser\PropFindAll), Object(Sabre\CalDAV\Principal\User))
#7 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Browser/Plugin.php(139): Sabre\DAV\Browser\Plugin->generateDirectoryIndex('principals/grou...')
#8 [internal function]: Sabre\DAV\Browser\Plugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#9 /usr/share/webapps/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#10 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(459): Sabre\Event\EventEmitter->emit('method:GET', Array)
#11 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#12 /usr/share/webapps/owncloud/apps/dav/lib/server.php(152): Sabre\DAV\Server->exec()
#13 /usr/share/webapps/owncloud/apps/dav/appinfo/v2/remote.php(29): OCA\DAV\Server->exec()
#14 /usr/share/webapps/owncloud/remote.php(138): require_once('/usr/share/weba...')
#15 {main}
```

**Comment by LukasReschke** [comment]
@DeepDiver1975

**Comment by DeepDiver1975** [comment]
> #0 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php(159): OCA\DAV\CardDAV\Plugin->getAddressbookHomeForPrincipal('principals/grou...')

it would be great to know the full parameter being passed into this function ...

**Comment by skjnldsv** [comment]
If I open `https://localhost:8080/remote.php/dav/calendars/`, i've got: 
I have 2 users: admin and Test.

```
Not Found
Node with name 'Test' could not be found

Technical details
Remote Address: 127.0.0.1
Request ID: dp9sQBo6qLa80EbMJnt+
Type: Sabre\DAV\Exception\NotFound
Code: 0
Message: Node with name 'Test' could not be found
File: /usr/share/webapps/owncloud/apps/dav/lib/connector/sabre/davaclplugin.php
Line: 61

Trace
#0 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAVACL/Plugin.php(844): OCA\DAV\Connector\Sabre\DavAclPlugin->checkPrivileges('calendars/Test', '{DAV:}read', 1, false)
#1 [internal function]: Sabre\DAVACL\Plugin->propFind(Object(Sabre\DAV\PropFind), Object(OCA\DAV\CalDAV\CalendarHome))
#2 /usr/share/webapps/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#3 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(999): Sabre\Event\EventEmitter->emit('propFind', Array)
#4 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(919): Sabre\DAV\Server->getPropertiesByNode(Object(Sabre\DAV\PropFind), Object(OCA\DAV\CalDAV\CalendarHome))
#5 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(788): Sabre\DAV\Server->getPropertiesForPath('calendars', Array, 1)
#6 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Browser/Plugin.php(276): Sabre\DAV\Server->getPropertiesForChildren('calendars', Array)
#7 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Browser/Plugin.php(139): Sabre\DAV\Browser\Plugin->generateDirectoryIndex('calendars')
#8 [internal function]: Sabre\DAV\Browser\Plugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#9 /usr/share/webapps/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#10 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(459): Sabre\Event\EventEmitter->emit('method:GET', Array)
#11 /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#12 /usr/share/webapps/owncloud/apps/dav/lib/server.php(152): Sabre\DAV\Server->exec()
#13 /usr/share/webapps/owncloud/apps/dav/appinfo/v2/remote.php(29): OCA\DAV\Server->exec()
#14 /usr/share/webapps/owncloud/remote.php(138): require_once('/usr/share/weba...')
#15 {main}

```

**Comment by PVince81** [comment]
Still happening in 9.0.5 / 9.1.1 ?

**Comment by skjnldsv** [comment]
Don't seems to :)

Cloooosed!
