### ISSUE TITLE
Doctrine\DBAL\DBALException: Unknown database type requested, OC\DB\OCSqlitePlatform may not support it.

### ISSUE THREAD

**Issue by philthephatman** [owncloud/core#24313]
### Steps to reproduce

Upgrading from 9.0.1 Stable to 9.0.2 RC1
### Expected behaviour

Upgrade should be successful
### Actual behaviour

Upgrade unsuccessful
### Server configuration

Linux Mint 17.3 Rosa

Apache 2.4.20

sqlite3

PHP 5.6.20-1

9.0.2 RC1

Updated from 9.0.1 stable

Updated from web page

```
Log file:

{"reqId":"hV9bn7mHqqHXqJXC3\/gx","remoteAddr":"127.0.0.1","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",\"Message\":\"Unknown database type  requested, OC\\\\DB\\\\OCSqlitePlatform may not support it.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/SqliteSchemaManager.php(288): Doctrine\\\\DBAL\\\\Platforms\\\\AbstractPlatform->getDoctrineTypeMapping('')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(820): Doctrine\\\\DBAL\\\\Schema\\\\SqliteSchemaManager->_getPortableTableColumnDefinition(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/SqliteSchemaManager.php(228): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->_getPortableTableColumnList('sqlite_stat1', '\\\/var\\\/www\\\/ownclo...', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(175): Doctrine\\\\DBAL\\\\Schema\\\\SqliteSchemaManager->_getPortableTableColumnList('sqlite_stat1', '\\\/var\\\/www\\\/ownclo...', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(281): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->listTableColumns('sqlite_stat1')\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(268): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->listTableDetails('sqlite_stat1')\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(1040): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->listTables()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/repair\\\/sqliteautoincrement.php(60): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->createSchema()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/repair.php(87): OC\\\\Repair\\\\SqliteAutoincrement->run()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(313): OC\\\\Repair->run()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(215): OC\\\\Updater->doUpgrade('9.0.2.0', '9.0.1.3')\\n#11 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(120): OC\\\\Updater->upgrade()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Platforms\\\/AbstractPlatform.php\",\"Line\":423}","level":3,"time":"2016-04-27T16:08:02+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=OFonDy9%2FPycNGGppIhFyFDQbPgtWBSMwK2wZDVw4Xjs%3D%3Apjfhn4PMFWR9cp1vRZyLdNWIN%2FlZsNlS8vtCo4AXYLI%3D","user":"--"}
```

**Comment by RealRancor** [comment]
Something similar was reported in the past but was closed by the user: https://github.com/owncloud/core/issues/16134

**Comment by DeepDiver1975** [comment]
Which apps are installed?
Which tables do exist in the DB?

**Comment by philthephatman** [comment]
Apps installed:

  - activity: 2.2.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - documents: 0.12.0
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - files_videoviewerplus: 0.2.0
  - firstrunwizard: 1.1
  - galleryplus: true
  - mail: 0.4.2
  - news: 8.7.1
  - notifications: 0.2.3
  - ownnote: 1.07
  - provisioning_api: 0.4.1
  - shorten: 0.0.15
  - sketch: 0.1.2
  - systemtags: 0.2
  - templateeditor: 0.1
  - transmission: 0.2
  - updatenotification: 0.1.0
Disabled:
  - files_embeddedvideo
  - gallery
  - html5_videoplayer
  - libreonline
  - mobilecomp
  - user_external
  - user_ldap

Tables:

Not sure how to obtain this info?

**Comment by philthephatman** [comment]
![screenshot at 2016-04-27 16 48 05](https://cloud.githubusercontent.com/assets/18704274/14867744/fc2977c2-0c97-11e6-8cef-c5b36fe3a530.png)
![screenshot at 2016-04-27 16 48 39](https://cloud.githubusercontent.com/assets/18704274/14867747/fef648b8-0c97-11e6-8a4e-00257d5e260f.png)

Here are a couple of screenshots of tables included.

**Comment by nickvergessen** [comment]
The Exception happens on `OC\Repair\SqliteAutoincrement`

```json
{
    "reqId": "hV9bn7mHqqHXqJXC3/gx",
    "remoteAddr": "127.0.0.1",
    "app": "core",
    "message": {
        "Exception": {
            "Exception": "Doctrine\DBAL\DBALException",
            "Message": "Unknown database type requested, OC\DB\OCSqlitePlatform may not support it.",
            "Code": 0,
            "Trace": {
                "#0": [
                    "/var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php(288):",
                    "Doctrine\DBAL\Platforms\AbstractPlatform->getDoctrineTypeMapping('')"
                ],
                "#1": [
                    "/var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(820):",
                    "Doctrine\DBAL\Schema\SqliteSchemaManager->_getPortableTableColumnDefinition(Array)"
                ],
                "#2": [
                    "/var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php(228): Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList('sqlite_stat1', '/var/www/ownclo...', Array)",
                    null
                ],
                "#3": [
                    "/var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(175): Doctrine\DBAL\Schema\SqliteSchemaManager->_getPortableTableColumnList('sqlite_stat1', '/var/www/ownclo...', Array)",
                    null
                ],
                "#4": [
                    "/var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(281):",
                    "Doctrine\DBAL\Schema\AbstractSchemaManager->listTableColumns('sqlite_stat1')"
                ],
                "#5": [
                    "/var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(268):",
                    "Doctrine\DBAL\Schema\AbstractSchemaManager->listTableDetails('sqlite_stat1')"
                ],
                "#6": [
                    "/var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(1040):",
                    "Doctrine\DBAL\Schema\AbstractSchemaManager->listTables()"
                ],
                "#7": [
                    "/var/www/owncloud/lib/private/repair/sqliteautoincrement.php(60):",
                    "Doctrine\DBAL\Schema\AbstractSchemaManager->createSchema()"
                ],
                "#8": [
                    "/var/www/owncloud/lib/private/repair.php(87):",
                    "OC\Repair\SqliteAutoincrement->run()"
                ],
                "#9": [
                    "/var/www/owncloud/lib/private/updater.php(313):",
                    "OC\Repair->run()"
                ],
                "#10": [
                    "/var/www/owncloud/lib/private/updater.php(215): OC\Updater->doUpgrade('9.0.2.0', '9.0.1.3')",
                    null
                ],
                "#11": [
                    "/var/www/owncloud/core/ajax/update.php(120):",
                    "OC\Updater->upgrade()"
                ],
                "#12": [
                    "{main}",
                    null
                ]
            },
            "File": "/var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php",
            "Line": 423
        }
    },
    "level": 3,
    "time": "2016-04-27T16:08:02+00:00",
    "method": "GET",
    "url": "/owncloud/core/ajax/update.php?requesttoken=OFonDy9%2FPycNGGppIhFyFDQbPgtWBSMwK2wZDVw4Xjs%3D%3Apjfhn4PMFWR9cp1vRZyLdNWIN%2FlZsNlS8vtCo4AXYLI%3D",
    "user": "--"
}
```

**Comment by philthephatman** [comment]
Not sure what to do about this. Attempted to upgrade to the security release 9.0.2 today and got the same thing.

**Comment by PVince81** [comment]
Any more luck with 9.0.5 ? Any errors in the admin page related to code integrity check ?

How about your config.php ? Does it contain "sqlite" or "sqlite3" ?

**Comment by philthephatman** [comment]
Converted to PostgreSQL. No problems since.
