### ISSUE TITLE
Random GDrive SSL issue

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24407]
```
{"reqId":"5nF1pJAkZKRry0bWriP3","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"SSL CA bundle not found: \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/storage\\\/..\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/IO\\\/cacerts.pem\",\"Exception\":\"GuzzleHttp\\\\Exception\\\\RequestException\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(104): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\RingException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(135): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(129): GuzzleHttp\\\\Client->get('https:\\\/\\\/doc-0s-...', Array)\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/storage\\\/google.php(452): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/doc-0s-...', Array)\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(293): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\Google->fopen('bacon.txt', 'r')\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(317): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('bacon.txt', 'r')\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(293): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->fopen('bacon.txt', 'r')\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/PermissionsMask.php(110): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('bacon.txt', 'r')\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(848): OC\\\\Files\\\\Storage\\\\Wrapper\\\\PermissionsMask->fopen('bacon.txt', 'r')\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(916): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->readFirstBlock('bacon.txt')\\n#16 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(378): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getHeader('bacon.txt')\\n#17 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(293): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fopen('bacon.txt', 'rb')\\n#18 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1061): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('bacon.txt', 'rb')\\n#19 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(909): OC\\\\Files\\\\View->basicOperation('fopen', 'gdrive\\\/bacon.tx...', Array, 'rb')\\n#20 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(304): OC\\\\Files\\\\View->fopen('gdrive\\\/bacon.tx...', 'rb')\\n#21 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#22 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#23 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#24 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#25 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#26 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#27 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#28 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":51,\"User\":\"admin\"}","level":4,"time":"2016-05-03T08:23:37+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/gdrive\/bacon.txt","user":"admin"}
```

Happened when trying to download a file off GDrive.

@LukasReschke I hope it doesn't mean we need to update the cert bundles again ?!

**Comment by PVince81** [comment]
This was on master 547830d97edd2c4da46a2d7988873fdc65e00bb4

**Comment by PVince81** [comment]
Hmm, I retried several times and I always get the error.
Or maybe is Guzzle not properly finding the bundled cert bundle ?

**Comment by LukasReschke** [comment]
Broken by https://github.com/owncloud/core/pull/23985

**Comment by MorrisJobke** [comment]
@LukasReschke Ready for a PR: https://github.com/owncloud/core/compare/one-shall-adjust-the-path?expand=1 ?

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/24630
