### ISSUE TITLE
Desktop Client can't connect

### ISSUE THREAD

**Issue by artifactdev** [owncloud/core#24402]
### Steps to reproduce
1. Install Owncloud 9.0.2RC2
2. Try to Login with Desktop Sync Client
3.

### Expected behaviour
After entering the password the Client should connect to the server and should sync files. 

### Actual behaviour
After clicking ok in the password dialogue of the sync client the dialogue appears again, it won't login
### Server configuration
**Operating system**:
Debian 8
**Web server:**
Apache 2
**Database:**
MySql
**PHP version:**
5
**ownCloud version:** (see ownCloud admin page)
9.0.2RC2
**Updated from an older ownCloud or fresh install:**
Updated from 9.0.1
**Where did you install ownCloud from:**
manual
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.4.2
  - music: 0.3.11
  - notifications: 0.2.3
  - ownnote: 1.07
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc57857b2428",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.art-ifact.de",
            "dev.art-ifact.de\/owncloud"
        ],
        "datadirectory": "\/home\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.2.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "php",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "owncloud",
        "mail_domain": "art-ifact.de",
        "loglevel": 0,
        "debug": true,
        "trashbin_retention_obligation": "auto"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
-
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Chrome Works
**Operating system:**
OSX
### Logs
#### Web server error log
-

#### ownCloud log (data/owncloud.log)
{"reqId":"gA5FQ4tdDRIm2wln2XYw","remoteAddr":"37.24.141.7","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-05-03T05:51:50+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/\/","user":"--"}


#### Browser log
-

**Comment by RealRancor** [comment]
> Desktop Sync Client 3

Whay is the Desktop Sync Client 3? Is this a typo?

**Comment by artifactdev** [comment]
Oh yeah it's a typo. And I discovered that this was a Problem appearing with php-fpm (PHP7) without it it works again so I close this issue.
