### ISSUE TITLE
caldav REPORT does not seem to be work

### ISSUE THREAD

**Issue by remyd1** [owncloud/core#24420]
First of all, this issue is related to the caldav part of owncloud. As described in [owncloud-caldav github project](https://github.com/owncloud/calendar), "CalDAV-Backend which has moved into the ownCloud Core.", so I submit this here.
I removed some private informations.

### Steps to reproduce
1. Download a little bash script https://gist.github.com/remyd1/a353b07219884c5878cc27d04aab9d96#file-gistfile1-txt

This piece of code just make basic curl requests to query a caldav server.

2. create a ".client_config" file with your owncloud/caldav parameters, e.g.:
```
# owncloud server
user="foo:secret"
short_url="http://owncloud.ourdomain.net"
caldav_url=$short_url"/owncloud/remote.php/caldav/calendars/remy/test_shared_by_julien"
```
3. launch the script in gistfile1 from bash with "report basic" arguments.

### Expected behaviour
Like described in [sabre documentation](http://sabre.io/dav/building-a-caldav-client/) or the [RFC](https://tools.ietf.org/html/rfc4791#page-38) associated I should get an answer.

The GET and the REPORT requests works perfectly.

### Actual behaviour

For every REPORT request I tried, I get:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.0.8</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\ReportNotSupported</s:exception>
  <s:message/>
  <d:supported-report/>
</d:error>
```

### Server configuration
**Operating system**:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie
```

**Web server:**
```
sudo netstat -nap |grep 80
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      341/apache2
```
```
aptitude show apache2
Package: apache2                         
State: installed
Automatically installed: no
Version: 2.4.10-10
Priority: optional
Section: httpd
Maintainer: Debian Apache Maintainers <debian-apache@lists.debian.org>
Architecture: amd64
Uncompressed Size: 518 k
Depends: lsb-base, procps, perl, mime-support, apache2-bin (= 2.4.10-10), apache2-utils (>= 2.4), apache2-data (= 2.4.10-10)
PreDepends: dpkg (>= 1.17.14)
Recommends: ssl-cert
Suggests: www-browser, apache2-doc, apache2-suexec-pristine | apache2-suexec-custom
Conflicts: apache2.2-common (< 2.3~)
Replaces: apache2.2-common
Provides: httpd, httpd-cgi
Description: Apache HTTP Server
 The Apache HTTP Server Project's goal is to build a secure, efficient and extensible HTTP server as standards-compliant open source software. The result has long been the number one web server on the Internet. 
 
 Installing this package results in a full installation, including the configuration files, init scripts and support scripts.
Homepage: http://httpd.apache.org/

Tags: role::metapackage, suite::apache
```

**Database:**
sqlite3

**PHP version:**
```
PHP 5.6.14-0+deb8u1 (cli) (built: Oct  4 2015 16:13:10) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```
```
libapache2-mod-php5                                   5.6.14+dfsg-0+deb8u1            amd64                           server-side, HTML-embedded scripting language (Apache 2 module)
```
**ownCloud version:** (see ownCloud admin page)
9.0.1.3

**Updated from an older ownCloud or fresh install:**
Updated from owncloud 8.X

**Where did you install ownCloud from:**
From sources

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - dav: 0.1.6
  - documents: 0.12.0
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc0mjl4f8g9a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.65",
            "owncloud.ourdomain.net"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.1.65\/owncloud",
        "dbtype": "sqlite3",
        "version": "9.0.1.3",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "owncloud.ourdomain.net",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```

**Are you using external storage, if yes which one:**
local

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:**
no (local webdav)

### Client configuration
**Browser:**
Not relevant here.

**Operating system:**
Ubuntu Xenial

#### Web server error log
Not relevant here.

#### ownCloud log (data/owncloud.log)
```
{"reqId":"DTXt3BWs0Ep\/DbcyFdph","remoteAddr":"192.168.1.76","app":"PHP","message":"XMLReader::XML(): Empty string supplied as input at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/xml\/lib\/Service.php#116","level":3,"time":"2016-05-03T12:37:09+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/caldav\/calendars\/remy\/test_shared_by_julien","user":"remy"}
{"reqId":"DTXt3BWs0Ep\/DbcyFdph","remoteAddr":"192.168.1.76","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 415 Unsupported Media Type\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ReportNotSupported\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php\",\"Line\":719,\"User\":\"remy\"}","level":4,"time":"2016-05-03T12:37:09+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/caldav\/calendars\/remy\/test_shared_by_julien","user":"remy"}
```

It seems that REPORT queries are not supported in caldav 3.0.8. Moreover, the server does not see the full REPORT query.

**Comment by PVince81** [comment]
@DeepDiver1975

**Comment by DeepDiver1975** [comment]
> HTTP\\\/1.1 415 Unsupported Media Type
> Sabre\\\\DAV\\\\Exception\\\\ReportNotSupported\

Your request is not detected - you are doing something wrong with the xml body of the request.

**Comment by DeepDiver1975** [comment]
This is not a bug in the server -> close

**Comment by remyd1** [comment]
I followed the RFC...

**Comment by remyd1** [comment]
Ok, it works now. Sorry, I was trying to put the payload in a header...
