### ISSUE TITLE
Files and Gallery Icons Missing (9.0.2)

### ISSUE THREAD

**Issue by mrnoisytiger** [owncloud/core#24458]
### Steps to reproduce
1. Login to OwnCloud
2. Click the DropDown menu to switch apps

### Expected behavior
The Files and Gallery application should show an icon above the name of the application.

### Actual behavior
The image is broken and is not shown. 

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 9.0.2

**Updated from an older ownCloud or fresh install:** Updated from 9.0.1

**Where did you install ownCloud from:** Official Repository (apt-get)

**Signing status (ownCloud 9.0 and above):** Let's Encrypt SSL 

```
No errors have been found.
```

Files, Gallery, Mail, Contacts, Calendar, Weather, Transmission Web client

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videojs-sublime: 0.9.8
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.4.2
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - sharelinks: 1.0.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - transmission: 0.2
  - updatenotification: 0.1.0
  - weather: 1.3.3
Disabled:
  - delete_confirmation
  - encryption
  - user_external
  - user_ldap
```

  'overwrite.cli.url' => 'https://REMOVED/',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'REMOVED',
  'dbhost' => 'REMOVED',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'REMOVED',
  'dbpassword' => 'REMOVED',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'REMOVED',
  'mail_domain' => 'REMOVED',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'REMOVED',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'REMOVED',
  'mail_smtppassword' => 'REMOVED',
  'theme' => '',
  'maintenance' => false,
  'appstore.experimental.enabled' => true,
  'loglevel' => 3,
  'trashbin_retention_obligation' => 'auto',
  'asset-pipeline.enabled' => false,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'updatechecker' => false,
);

```
**Are you using external storage, if yes which one:** LOCAL

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Safari Technology Preview Release 3, Chrome, Safari

**Operating system:** OS X El Capitan Beta 3

### Logs
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"yuMyA2BsiPP4S3VvtjRE","remoteAddr":"128.97.50.97","app":"files_external","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"Sabre\\\\HTTP\\\\ClientHttpException: Service Unavailable\",\"Code\":1,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(558): OC\\\\Files\\\\Storage\\\\DAV->convertException(Object(Sabre\\\\HTTP\\\\ClientHttpException), '')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(434): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(231): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(256): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(303): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/userstoragescontroller.php(108): OCA\\\\Files_External\\\\Controller\\\\StoragesController->show('2')\\n#6 [internal function]: OCA\\\\Files_External\\\\Controller\\\\UserStoragesController->show('2')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\UserStoragesController), 'show')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\UserStoragesController), 'show')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('UserStoragesCon...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(276): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(882): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#14 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php\",\"Line\":797}","level":3,"time":"2016-05-05T21:03:28+00:00","method":"GET","url":"\/index.php\/apps\/files_external\/userstorages\/2","user":"fjen"
```

**Comment by RealRancor** [comment]
Try to first disable all non-shipped apps like mail, files_videojs-sublime, weather and sharelinks (not tagged as compatible with oC9 at the appstore)

**Comment by mrnoisytiger** [comment]
Well, this is embarrassing, but it appeared to be an issue with the CDN I was using. After waiting a bit, the issue managed to fix itself.
