### ISSUE TITLE
Cannot redeclare class OC_L10N

### ISSUE THREAD

**Issue by notaduck** [owncloud/core#24451]
After i upgraded owncloud through apt-get then i got a 404 not found and the log says:  
{"reqId":"68+FZuxytbvlU3dXoQY8","remoteAddr":"10.0.2.14","app":"PHP","message":"Cannot redeclare class OC_L10N at \/var\/www\/owncloud\/lib\/private\/l10n.php#43","level":3,"time":"2016-05-05T07:24:54+00:00"}

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:**  Apache/2.4.7 

**Database:** Mysql/MariaDB

**PHP version:** PHP 5.5.9-1ubuntu4.16

**ownCloud version:** (see ownCloud admin page) I was upgradin fron 9 to 9.x but when runing the `sudo -u www-data php occ` command i am getting a :  
PHP Fatal error:  Cannot redeclare class OC_L10N in /var/www/owncloud/lib/private/l10n.php on line 43

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocuid93uftur',
  'passwordsalt' => '6s61AFebDKrp6t36Pa1c/Tp4DfzCJD',
  'secret' => 'aGghvYFXHdRibH3vr0hn/8ZnaAJgxY2PJja4XVqQcMnAJRvF',
  'trusted_domains' => 
  array (
    0 => 'owncloud.techknight.eu',
    1 => '10.0.2.7',
  ),
  'datadirectory' => '/media/sdb/data',
  'overwrite.cli.url' => 'http://10.0.2.7',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'oxxxxxxxxd',
  'dbhost' => '10.0.2.4',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oxxxxxxxxr',
  'dbpassword' => 'xxxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => true,
  'trashbin_retention_obligation' => 'auto',
  'trusted_proxies' => 
  array (
    0 => '10.0.2.14',
  ),
  'overwriteprotocol' => 'https',
  'mail_smtpmode' => 'sendmail',
  'mail_from_address' => 'xxxxxxxx',
  'mail_domain' => 'gmail.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
);
```

**Are you using encryption:** yes/no Yes

#### ownCloud log (data/owncloud.log)
```
{"reqId":"LdbVPQXir9hVsqVCnPQM","remoteAddr":"","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-04-25T08:30:01+00:00","method":"--","url":"--","user":"--"}
{"reqId":"LdbVPQXir9hVsqVCnPQM","remoteAddr":"","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Skole\/KVUC\/Matematik\/Aflevering\/S\u00e6t 10\/opg5\/opg5.tex.v1457435013","level":3,"time":"2016-04-25T08:30:01+00:00","method":"--","url":"--","user":"--"}
{"reqId":"LdbVPQXir9hVsqVCnPQM","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(573): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('\\\\section{Opgave...', '0end')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(492): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fixUnencryptedSize('files_versions\\\/...', 3174, 3174)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(161): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->verifyUnencryptedSize('files_versions\\\/...', 3174)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(142): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->filesize('files_versions\\\/...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1063): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filesize('files_versions\\\/...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(402): OC\\\\Files\\\\View->basicOperation('filesize', '\\\/files_versions...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_versions\\\/lib\\\/storage.php(447): OC\\\\Files\\\\View->filesize('\\\/files_versions...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_versions\\\/lib\\\/storage.php(721): OCA\\\\Files_Versions\\\\Storage::getVersions('notaduck', '\\\/Skole\\\/KVUC\\\/Mat...')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_versions\\\/command\\\/expire.php(61): OCA\\\\Files_Versions\\\\Storage::expire('\\\/Skole\\\/KVUC\\\/Mat...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/command\\\/commandjob.php(34): OCA\\\\Files_Versions\\\\Command\\\\Expire->handle()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OC\\\\Command\\\\CommandJob->run('O:33:\\\"OCA\\\\Files...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/queuedjob.php(42): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#12 \\\/var\\\/www\\\/owncloud\\\/cron.php(141): OC\\\\BackgroundJob\\\\QueuedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php\",\"Line\":360}","level":3,"time":"2016-04-25T08:30:01+00:00","method":"--","url":"--","user":"--"}
{"reqId":"XcO+eK3ZtepjQ+hTov3J","remoteAddr":"10.0.1.68","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(588): Sabre\\\\DAV\\\\Server->createCollection('Skole\\\/KVUC\\\/Mate...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1121,\"User\":\"notaduck\"}","level":4,"time":"2016-04-30T10:30:13+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/Skole\/KVUC\/Matematik\/Aflevering","user":"notaduck"}
{"reqId":"fE89RT5jNS7RUxZWsGhB","remoteAddr":"10.0.2.14","app":"PHP","message":"Cannot redeclare class OC_L10N at \/var\/www\/owncloud\/lib\/private\/l10n.php#43","level":3,"time":"2016-05-05T07:22:59+00:00"}
{"reqId":"jip4i+FdzR4zKcnyojtm","remoteAddr":"10.0.2.14","app":"PHP","message":"Cannot redeclare class OC_L10N at \/var\/www\/owncloud\/lib\/private\/l10n.php#43","level":3,"time":"2016-05-05T07:23:09+00:00"}
{"reqId":"58vr0kNndF4pLiMbC\/k\/","remoteAddr":"10.0.2.14","app":"PHP","message":"Cannot redeclare class OC_L10N at \/var\/www\/owncloud\/lib\/private\/l10n.php#43","level":3,"time":"2016-05-05T07:23:18+00:00"}
{"reqId":"AYQ6bjll1vpebYj459ch","remoteAddr":"10.0.2.14","app":"PHP","message":"Cannot redeclare class OC_L10N at \/var\/www\/owncloud\/lib\/private\/l10n.php#43","level":3,"time":"2016-05-05T07:23:50+00:00"}
{"reqId":"FqhnuimSU4tsXaJVIqY\/","remoteAddr":"10.0.2.14","app":"PHP","message":"Cannot redeclare class OC_L10N at \/var\/www\/owncloud\/lib\/private\/l10n.php#43","level":3,"time":"2016-05-05T07:24:22+00:00"}
{"reqId":"68+FZuxytbvlU3dXoQY8","remoteAddr":"10.0.2.14","app":"PHP","message":"Cannot redeclare class OC_L10N at \/var\/www\/owncloud\/lib\/private\/l10n.php#43","level":3,"time":"2016-05-05T07:24:54+00:00"}

```

**Comment by LukasReschke** [comment]
From what version were you updating exactly? Also which packages did you use?

Did you have ownCloud 8 installed before? This files have been moved with https://github.com/owncloud/core/pull/21741

Can you post a `ls -lah` of `lib/private`?

**Comment by LukasReschke** [comment]
cc @jng

**Comment by notaduck** [comment]
I don't remember the exact version but i am pretty sure it was the latest update for owncloud 9.x
i have updated from owncloud 8 ->9 and then -> 9.x

```
root@Owncloud:/var/www/owncloud/lib/private# ls -lah
total 900K
drwxr-x--- 43 root www-data  12K May  5 11:24 .
drwxr-x---  6 root www-data 4.0K May  5 09:22 ..
drwxr-x---  2 root www-data 4.0K Apr 13 11:41 activity
-rw-r--r--  1 root root     9.6K May  3 11:29 activitymanager.php
-rw-r--r--  1 root root      14K May  3 11:29 allconfig.php
-rw-r--r--  1 root root      12K May  3 11:29 api.php
drwxr-x---  3 root www-data 4.0K May  5 09:22 app
-rw-r--r--  1 root root     6.8K May  3 11:29 appconfig.php
drwxr-x---  9 root www-data 4.0K May  5 09:22 appframework
-rw-r--r--  1 root root     1.3K May  3 11:29 apphelper.php
-rw-r--r--  1 root root      35K May  3 11:29 app.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 archive
-rw-r--r--  1 root root     4.0K May  3 11:29 archive.php
-rw-r--r--  1 root root     5.7K May  3 11:29 arrayparser.php
drwxr-xr-x  2 root root     4.0K May  5 09:22 assetic
-rw-r--r--  1 root root     1.5K May  3 11:29 avatarmanager.php
-rw-r--r--  1 root root     3.6K May  3 11:29 avatar.php
drwxr-x---  3 root www-data 4.0K May  5 09:22 backgroundjob
drwxr-x---  2 root www-data 4.0K May  5 09:22 cache
-rw-r-----  1 root www-data 1.9K Apr 13 11:41 capabilitiesmanager.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 command
drwxr-x---  2 root www-data 4.0K Apr 13 11:41 comments
-rw-r--r--  1 root root     7.4K May  3 11:29 config.php
drwxr-xr-x  3 root root     4.0K May  5 09:22 connector
drwxr-x---  2 root www-data 4.0K May  5 09:22 console
drwxr-xr-x  2 root root     4.0K May  5 09:22 contacts
-rw-r--r--  1 root root     5.5K May  3 11:29 contactsmanager.php
-rw-r--r--  1 root root     1.2K May  3 11:29 databaseexception.php
-rw-r--r--  1 root root      875 May  3 11:29 databasesetupexception.php
-rw-r--r--  1 root root      11K May  3 11:29 datetimeformatter.php
-rw-r--r--  1 root root     3.6K May  3 11:29 datetimezone.php
drwxr-x---  3 root www-data 4.0K May  5 09:22 db
-rw-r--r--  1 root root     9.9K May  3 11:29 db.php
-rw-r--r--  1 root root     7.3K May  3 11:29 defaults.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 diagnostics
drwxr-x---  4 root www-data 4.0K May  5 09:22 encryption
-rw-r--r--  1 root root     3.7K May  3 11:29 eventsource.php
-rw-r--r--  1 root root     6.3K May  3 11:29 filechunking.php
drwxr-x--- 11 root www-data 4.0K May  5 09:22 files
-rw-r--r--  1 root root     9.8K May  3 11:29 files.php
-rw-r--r--  1 root root      982 May  3 11:29 forbiddenexception.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 group
-rw-r--r--  1 root root     8.4K May  3 11:29 group.php
-rw-r--r--  1 root root      33K May  3 11:29 helper.php
-rw-r--r--  1 root root     1.3K May  3 11:29 hintexception.php
-rw-r--r--  1 root root     4.4K May  3 11:29 hook.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 hooks
drwxr-x---  3 root www-data 4.0K Apr 13 11:41 http
-rw-r--r--  1 root root     3.2K May  3 11:29 httphelper.php
-rw-r--r--  1 root root      33K May  3 11:29 image.php
-rw-r--r--  1 root root      18K May  3 11:29 installer.php
drwxr-x---  5 root www-data 4.0K Apr 13 11:41 integritycheck
-rw-r--r--  1 root root     5.3K May  3 11:29 json.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 l10n
-rw-r--r--  1 root root      16K May  3 11:29 l10n.php
-rw-r--r--  1 root root     6.3K May  3 11:29 largefilehelper.php
drwxr-x---  3 root www-data 4.0K May  5 09:22 legacy
drwxr-x---  2 root www-data 4.0K May  5 09:22 lock
drwxr-x---  2 root www-data 4.0K May  5 09:22 log
-rw-r--r--  1 root root     6.7K May  3 11:29 log.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 mail
drwxr-x---  2 root www-data 4.0K May  5 09:22 memcache
-rw-r--r--  1 root root     9.2K May  3 11:29 mimetypes.list.php
-rw-r--r--  1 root root     1.1K May  3 11:29 naturalsort_defaultcollator.php
-rw-r--r--  1 root root     4.0K May  3 11:29 naturalsort.php
-rw-r--r--  1 root root     2.5K May  3 11:29 navigationmanager.php
-rw-r--r--  1 root root      881 May  3 11:29 needsupdateexception.php
drwxr-x---  2 root www-data 4.0K Apr 13 11:41 notification
-rw-r--r--  1 root root      866 May  3 11:29 notsquareexception.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 ocs
-rw-r--r--  1 root root     9.2K May  3 11:29 ocsclient.php
-rw-r--r--  1 root root     7.7K May  3 11:29 ocs.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 preview
-rw-r--r--  1 root root      11K May  3 11:29 previewmanager.php
-rw-r--r--  1 root root      33K May  3 11:29 preview.php
-rw-r-----  1 root www-data 3.0K Apr 13 11:41 releasenotes.php
drwxr-x---  2 root www-data 4.0K Apr 13 11:41 repair
-rw-r--r--  1 root root      946 May  3 11:29 repairexception.php
-rw-r--r--  1 root root     4.3K May  3 11:29 repair.php
-rw-r--r--  1 root root     1.1K May  3 11:29 repairstep.php
-rw-r--r--  1 root root     8.6K May  3 11:29 response.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 route
drwxr-x---  4 root www-data 4.0K Apr 13 11:41 search
-rw-r--r--  1 root root     3.9K May  3 11:29 search.php
drwxr-x---  4 root www-data 4.0K May  5 09:22 security
-rw-r-----  1 root www-data 2.4K Apr 13 11:41 servercontainer.php
-rw-r--r--  1 root root      824 May  3 11:29 servernotavailableexception.php
-rw-r--r--  1 root root      26K May  3 11:29 server.php
-rw-r--r--  1 root root      871 May  3 11:29 serviceunavailableexception.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 session
drwxr-x---  2 root www-data 4.0K May  5 09:22 setup
-rw-r--r--  1 root root      14K May  3 11:29 setup.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 share
drwxr-x---  3 root www-data 4.0K Apr 13 11:41 share20
-rw-r--r--  1 root root     3.8K May  3 11:29 streamer.php
-rw-r--r--  1 root root     5.5K May  3 11:29 subadmin.php
-rw-r--r--  1 root root     2.1K May  3 11:29 systemconfig.php
drwxr-x---  2 root www-data 4.0K Apr 13 11:41 systemtag
drwxr-x---  2 root www-data 4.0K May  5 09:22 tagging
-rw-r--r--  1 root root     2.7K May  3 11:29 tagmanager.php
-rw-r--r--  1 root root      22K May  3 11:29 tags.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 template
-rw-r--r--  1 root root     9.6K May  3 11:29 templatelayout.php
-rw-r--r--  1 root root     8.9K May  3 11:29 template.php
-rw-r--r--  1 root root     5.3K May  3 11:29 tempmanager.php
-rw-r--r--  1 root root      16K May  3 11:29 updater.php
-rw-r--r--  1 root root     7.6K May  3 11:29 urlgenerator.php
drwxr-x---  2 root www-data 4.0K May  5 09:22 user
-rw-r--r--  1 root root      18K May  3 11:29 user.php
-rw-r--r--  1 root root      45K May  3 11:29 util.php

```

**Comment by RealRancor** [comment]
Which apps are installed / enabled? Have seen this if old apps are enabled which are not compatible with the current oC version.

**Comment by notaduck** [comment]
@RealRancor is there any way to see that? (I can't access occ commands and the web fronted)

**Comment by RealRancor** [comment]
@notaduck https://github.com/owncloud/core/wiki/Apps-in-the-release#currently-in-owncloud-900 are the default apps, everything else is 3rdparty and might break your install (especially during upgrades).

**Comment by notaduck** [comment]
I have webdav and videoveiwer and thumbnail editor enabled but nothin else different from the list. Do you know if there is any way to save the installation?

**Comment by rullzer** [comment]
@notaduck yeah that l10n.php file is not supposed to be there... It got moved to https://github.com/owncloud/core/blob/stable9/lib/private/legacy/l10n.php

So you now have it 2 times. And the autoloader apparently happily loads it twice.

**Comment by notaduck** [comment]
@rullzer where is the correct patch to the file?

**Comment by rullzer** [comment]
correct lib/private/legacy/l10n.php
Old one lib/private/l10n.php

But this seems like a packaging issue then @jnweiger

**Comment by PVince81** [comment]
Is this still an issue with the 9.0.3 packages ?

**Comment by PVince81** [comment]
Closing due to lack of feedback

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
