### ISSUE TITLE
Cannot modify header information - headers already sent (mailtest)

### ISSUE THREAD

**Issue by benkinooby** [owncloud/core#24461]
### Steps to reproduce
1. log in as admin
2. navigate to admin site
3. try to send a test mail
### Expected behaviour

Test mail will be successfully sent to mail address of admin
### Actual behaviour

No test mail sent
### Nota Bene

Requesting & sending password reset mails works as expected
### Server configuration

**Operating system**:
gentoo (ARM)

**Web server:**
nginx

**Database:**
mysql 5.6.28

**PHP version:**
5.6.20

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
updated from 8.2.3
I recall seeing similar messages in 8.2.2 and 8.2.3

**Where did you install ownCloud from:**
gentoo's package manager "portage"

**Signing status (ownCloud 9.0 and above):**
webapp is a gentoo tool for managing virtual hosts.

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
    - EXTRA_FILE
        - .webapp

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.webapp] => Array
                        (
                            [expected] => 
                            [current] => 
                        )
                )
        )
)
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_sharing: 0.9.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_pdfviewer
  - files_texteditor
  - files_videoplayer
  - firstrunwizard
  - gallery
  - templateeditor
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oce8d15oay3j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXX.XXX.com"
        ],
        "datadirectory": "\/var\/www\/XXX.XXX.com\/htdocs\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/XXX.XXX.com",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud02",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "YYY.YYY",
        "mail_domain": "gmx.at",
        "mail_smtphost": "mail.gmx.net",
        "mail_smtpport": "587",
        "loglevel": 0,
        "mail_smtpauthtype": "LOGIN",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Mozilla Firefox
#### ownCloud log (data/owncloud.log)

```
{"reqId":"8WQme6GS8zeNtZ0Q94Jn","remoteAddr":"XXX.XXX.XXX.XXX","app":"base","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"Cannot modify header information - headers already sent\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(2, 'Cannot modify h...', '\\\/var\\\/www\\\/XXX...', 47, Array)\\n#1 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php(47): setcookie('oce8d15oay3j', '', -1, '\\\/')\\n#2 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(425): OC\\\\Session\\\\Internal->__construct('oce8d15oay3j')\\n#3 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(579): OC::initSession()\\n#4 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(1112): OC::init()\\n#5 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/index.php(37): require_once('\\\/var\\\/www\\\/XXX...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php\",\"Line\":127}","level":3,"time":"2016-05-05T22:11:11+00:00","method":"POST","url":"\/index.php\/settings\/admin\/mailtest","user":"--"}
{"reqId":"8WQme6GS8zeNtZ0Q94Jn","remoteAddr":"XXX.XXX.XXX.XXX","app":"index","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"Cannot modify header information - headers already sent\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(2, 'Cannot modify h...', '\\\/var\\\/www\\\/XXX...', 103, Array)\\n#1 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/response.php(103): header('HTTP\\\/1.1 500 In...')\\n#2 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(436): OC_Response::setStatus(500)\\n#3 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(579): OC::initSession()\\n#4 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(1112): OC::init()\\n#5 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/index.php(37): require_once('\\\/var\\\/www\\\/XXX...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php\",\"Line\":127}","level":3,"time":"2016-05-05T22:11:11+00:00","method":"POST","url":"\/index.php\/settings\/admin\/mailtest","user":"--"}
{"reqId":"8WQme6GS8zeNtZ0Q94Jn","remoteAddr":"XXX.XXX.XXX.XXX","app":"PHP","message":"ErrorException: Cannot modify header information - headers already sent at \/var\/www\/XXX.XXX.com\/htdocs\/owncloud\/lib\/private\/session\/internal.php#127","level":3,"time":"2016-05-05T22:11:11+00:00","method":"POST","url":"\/index.php\/settings\/admin\/mailtest","user":"--"}
{"reqId":"8WQme6GS8zeNtZ0Q94Jn","remoteAddr":"XXX.XXX.XXX.XXX","app":"PHP","message":"Cannot modify header information - headers already sent at Unknown#0","level":3,"time":"2016-05-05T22:11:11+00:00","method":"POST","url":"\/index.php\/settings\/admin\/mailtest","user":"--"}
```

**Comment by benkinooby** [comment]
This issue is probably related to issue #24462 
Comparing the owncloud.log the exception is triggered in the same files and lines and only differ in the "url" part

**Comment by benkinooby** [comment]
FWIW:
The admin page also mentions: "No memory cache has been configured. To enhance your performance please configure a memcache if available."

**Comment by PVince81** [comment]
@LukasReschke

**Comment by PVince81** [comment]
Not sure if bug or env issue

**Comment by PVince81** [comment]
Is this still an issue with 9.0.7 or 9.1.3 ?

**Comment by benkinooby** [comment]
The issue still persists in 9.0.4
I'll upgrade to 9.0.7 asap and report back.

**Comment by kdslkdsaldsal** [comment]
> Not sure if bug or env issue

Normally such messages are environmental issues like edited files, own themes or 3rdparty apps containing files with an ending white space after the last line like explained here:

https://www.geeklog.net/faqman/index.php?op=view&t=38
https://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php

**Comment by benkinooby** [comment]
I use vim as editor and do not have any custom themes, mail templates or 3rd party apps installed. Also I never messed with any php files. Actually, now that this bug was revived after nearly a year I'm having a hard time to reproduce this specific bug/error message.

Ironically two things hold true currently (v9.0.4):
* owncloud started to spam activity notification mails after upgrading to 9.0.4. So, sending mail (note that this bug was in context of mailtest) definitively work. Sending the test mail still does *not* work (not that this report was in context of mailtest) but it does not reproduce the error messages from my initial report either
* I still get a lot of "headers already sent" errors in my logs but they are different to what I reported and by now I have a better idea of how to fix it. Thanks for the hints @kdslkdsaldsal 

On top of that I'm about to upgrade to 9.0.7.
I'd suggest to close this ticket for the above reasons.

If the issue still persists (it probably will) and I still consider it bug-report-worthy (I probably won't) I'll file a new bug against 9.0.7

Thank you very much for advice and attention.

**Comment by PVince81** [comment]
@benkinooby thanks for the feedback
