### ISSUE TITLE
Can't install on MySQL anymore

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#24470]
```
{"reqId":"i7kdnwlKWu2V+1Kre8zs","remoteAddr":"::1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'CREATE TABLE `oc_calendar_objects` (`id` INT UNSIGNED AUTO_INCREMENT NOT NULL, `calendarid` INT UNSIGNED DEFAULT 0 NOT NULL, `objecttype` VARCHAR(40) DEFAULT '' NOT NULL, `startdate` DATETIME DEFAULT '0000-00-00 00:00:00', `enddate` DATETIME DEFAULT '0000-00-00 00:00:00', `repeating` INT DEFAULT 0, `summary` VARCHAR(255) DEFAULT NULL, `calendardata` LONGTEXT DEFAULT NULL, `uri` VARCHAR(100) DEFAULT NULL, `lastmodified` INT DEFAULT 0, PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'startdate'\",\"Code\":0,\"Trace\":\"#0 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(945): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'CREATE TABLE `o...')\\n#2 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/lib\\\/private\\\/DB\\\/MDB2SchemaManager.php(168): Doctrine\\\\DBAL\\\\Connection->query('CREATE TABLE `o...')\\n#3 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/lib\\\/private\\\/DB\\\/MDB2SchemaManager.php(69): OC\\\\DB\\\\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#4 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/lib\\\/private\\\/legacy\\\/db.php(172): OC\\\\DB\\\\MDB2SchemaManager->createDbFromStructure('\\\/Users\\\/lukasres...')\\n#5 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/lib\\\/private\\\/Installer.php(563): OC_DB::createDbFromStructure('\\\/Users\\\/lukasres...')\\n#6 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/lib\\\/private\\\/Installer.php(539): OC\\\\Installer::installShippedApp('calendar')\\n#7 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/lib\\\/private\\\/Setup.php(370): OC\\\\Installer::installShippedApps()\\n#8 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/core\\\/Controller\\\/SetupController.php(64): OC\\\\Setup->install(Array)\\n#9 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/lib\\\/base.php(821): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#10 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/index.php(39): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":3,"time":"2016-05-06T11:50:09+00:00","method":"POST","url":"\/oc\/index.php","user":"--"}
```

cc @DeepDiver1975

**Comment by LukasReschke** [comment]
Caused by old calendar version. 🙈
