### ISSUE TITLE
"Punic Exception DataFileNotFound", "Message:"Unable to find the data file"

### ISSUE THREAD

**Issue by hendraw4n** [owncloud/core#24476]
### Steps to reproduce
1. change data directory from local storage to NFS
2. change 'datadirectory' on config.php to new location
3. revert back 'datadirectory' to the default

### Expected behaviour
Succeeds and redirect to files app

### Actual behaviour
can't login to web page, Succeeds using desktop client

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.2.3

**Where did you install ownCloud from:**
Packages

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

Enabled:
  - activity: 2.1.4
  - files: 1.2.1
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - user_ldap: 0.7.1
Disabled:
  - documents
  - encryption
  - external
  - firstrunwizard
  - user_external

**The content of config/config.php:**

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

{
    "system": {
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "8.2.3.2",
        "logtimezone": "Asia\/Jakarta",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 2,
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "forcessl": true,
        "asset-pipeline.enabled": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false,
        "appstore.experimental.enabled": true,
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
AD


#### ownCloud log (data/owncloud.log)

{"reqId":"WZg108xOs5t4B+obfOG2","remoteAddr":"10.10.10.10.","app":"index","message":"Exception: {\"Exception\":\"Punic\\\\Exception\\\\DataFileNotFound\",\"Message\":\"Unable to find the data file 'parentLocales'\",\"Code\":10004,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/punic\\\/punic\\\/code\\\/Data.php(445): Punic\\\\Data::getGeneric('parentLocales')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/punic\\\/punic\\\/code\\\/Data.php(505): Punic\\\\Data::explodeLocale('en')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/punic\\\/punic\\\/code\\\/Data.php(481): Punic\\\\Data::getLocaleAlternatives('en')\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/punic\\\/punic\\\/code\\\/Data.php(124): Punic\\\\Data::getLocaleFolder('en')\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/punic\\\/punic\\\/code\\\/Calendar.php(647): Punic\\\\Data::get('calendar', 'en')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/l10n.php(510): Punic\\\\Calendar::getDateFormat('short', 'en')\\n#6 \\\/var\\\/www\\\/owncloud\\\/core\\\/js\\\/config.php(70): OC_L10N->getDateFormat()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func('?lambda_191', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(849): OC\\\\Route\\\\Router->match('\\\/core\\\/js\\\/oc.js')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/punic\\\/punic\\\/code\\\/Data.php\",\"Line\":171}","level":3,"time":"2016-05-07T01:51:42+07:00"}

**Comment by Xenopathic** [comment]
That error is caused if there are missing files in 3rdparty, and is completely unrelated to setting the datadirectory. Did you change the ownCloud files in any way (update perhaps)?

**Comment by hendraw4n** [comment]
yes, we migrate to new server, it looks like the copy process is not perfect, after reinstall everything looks fine. thanks

**Comment by Bigpet** [comment]
I know I'm commenting on an old and dead issue but if anyone else finds this when googling for the error. My mistake was copying the owncloud directory with rsync and using `--exclude "data"` which excluded the directory `3rdparty\punic\punic\code\data`

**Comment by FHefner** [comment]
Thanks @Bigpet , I made exactly the same fault and it just took me about 4 hours since I saw. :D Now I can finally access my Nextcloud-Webinterface once again.

**Comment by csasarak** [comment]
I did the exact same thing, simple solution if you lost those files is to re-download the zip file and execute:
unzip <nextcloud zip> -d <path to installation without the final 'nextcloud'> 

Answer 'N' at the prompts to only replace files which aren't there.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
