### ISSUE TITLE
Restore previous version of an encrpyted file

### ISSUE THREAD

**Issue by tanjix** [owncloud/core#24517]
Hi,

I ran version 9.0.0 before and had trouble on restoring a previous version of one file. Server-side encryption is enabled.
When doing the restoure through the owncloud-webinterface, a few seconds later my desktion client start to sync the file but breaks with the error:

"... - server replied: Internal server error"

The owncloud.log-file says something about "Bad Signature" - full log excerpt is available below.

I updated to 9.0.2 as I read about https://github.com/owncloud/core/issues/22781 which seemes to be a similar issue. But the update did not solve the problem.

### Expected behaviour
file should get restored and decrypted before

### Actual behaviour
Error messages in the desktop client and in the owncloud.log-file; no restore; no decryption

### Server configuration
**Operating system:** Debian Linux 8.4 x64

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6.20

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** Updated from 9.0.0

**Where did you install ownCloud from:** deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /

**Signing status (ownCloud 9.0 and above):**

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- update.log

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [update.log] => Array
                        (
                            [expected] => 
                            [current] => 0238840ac15087658a129e88dc4fd3c51cac69fd9d70b1bf15a7622adb9eb6902062af432ffd7000e8095609b6caaa0e9f9380b7e401ba31af266d998c7416dd
                        )

                )

        )

)

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - external
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "updatechecker": false,
        "instanceid": "ocm8txot9xid",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "77.37.0.30",
            "cloud.ipffm.de"
        ],
        "datadirectory": "\/cloud",
        "overwrite.cli.url": "XXXXX",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "je",
        "mail_smtpmode": "php",
        "mail_domain": "XXXX",
        "singleuser": false,
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

#### ownCloud log (data/owncloud.log)
{"reqId":"3q3JeZ4N3W0R2jWyF9My","remoteAddr":"xx.xx.xx.xx","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(463): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('RASVTyjWLs611Go...', '\\\\x83%\\\\xC2\\\\xF3\\\\xBF\\\\f1\\\\x95\\\\x1Cp~v\\\\xBBo\\\\t...', 'd8eb07aa9b62e0c...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(363): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('RASVTyjWLs611Go...', '\\\\x83%\\\\xC2\\\\xF3\\\\xBF\\\\f1\\\\x95\\\\x1Cp~v\\\\xBBo\\\\t...', 'AES-256-CTR', 1, 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(459): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('RASVTyjWLs611Go...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(290): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(83): fread(Resource id #61, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(91): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #64, Resource id #66, '2336178')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":483,\"User\":\"USERNAME\"}","level":4,"time":"2016-05-09T14:23:43+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\PATH-TO-FILE","user":"USERNAME"}

**Comment by LukasReschke** [comment]
With what version of ownCloud did the version get created? Does it work with new files and new versions? Or old files and new versions?

Would also be awesome if you could look in the data folder for the version you tried to restore and could upload it somewhere. (if not stored in plaintext, if it is then please let us know)

That would be helpful. Thanks a lot.

**Comment by tanjix** [comment]
The versions were created with OC 9.0.0.

I just tried it with a new file on OC 9.0.2:

- Uploaded a new file with some content
- edited the file and waited to get it synced back
- reverted to the previous version: fine
- reverted back to the newer version: fine
- deleted the file
- restored the file
- reverted to the previous version: fine
- reverted to the newer version: fine

From here everything seems to be fine.

The file in question, that is not working, is an encrypted one. I uploaded it here: https://www.dropbox.com/s/4jlt1g73tkuw5ct/file.txt?dl=0

I furthermore noticed that when I click the file in question in the owncloud webinterface it says "file not found".

**Comment by tanjix** [comment]
Any update on this? I currently have the same problem again that I cannot restore a file from a previous version... :(

**Comment by PVince81** [comment]
Please try again with 9.0.4 or more recent.
There was another related fix https://github.com/owncloud/core/pull/25228

Please reopen if the problem persists, thanks.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
