### ISSUE TITLE
Contacts are deleted daily

### ISSUE THREAD

**Issue by ngrundmann** [owncloud/core#24546]
### Steps to reproduce
1. Add contacts to address book 
2. Wait until the next day
3. All contacts are gone

### Expected behavior
Contacts shouldn't be deleted daily

### Actual behavior
Contacts are deleted daily

### Server configuration
**Operating system:** Debian 8.4

**Web server:** Apache 2.4.10

**Database:** MySQL

**PHP version:** 5.6.20

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** ZIP-Archive from ownCloud.org

**Signing status (ownCloud 9.0 and above):** 

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - passwordpolicy: 1.1
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.n***"
        ],
        "datadirectory": "\/var\/www\/web1\/apps\/***\/data",
        "overwrite.cli.url": "https:\/\/cloud.***",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "web1_owncloudng",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "MET",
        "installed": true,
        "instanceid": "ocysxbd9hjn4",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstore.experimental.enabled": true,
        "theme": "",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "noreply",
        "mail_domain": "***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "loglevel": 0,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari/Firefox

**Operating system:** OS X 10.11.4/Windows 10

#### Web server error log
```
93.209.70.37 - - [10/May/2016:05:27:23 +0200] "OPTIONS /remote.php/caldav/principals/NilsGrundmann/ HTTP/1.1" 401 355 "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 807 4831
93.209.70.37 - - [10/May/2016:05:27:23 +0200] "OPTIONS /remote.php/caldav/principals/ngrundmann/ HTTP/1.1" 401 355 "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 820 4845
93.209.70.37 - - [10/May/2016:05:27:23 +0200] "OPTIONS /remote.php/caldav/principals/NilsGrundmann/ HTTP/1.1" 200 - "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 539 1089
93.209.70.37 - - [10/May/2016:05:27:23 +0200] "OPTIONS /remote.php/dav/principals/users/ngrundmann/ HTTP/1.1" 401 414 "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 617 5199
93.209.70.37 - - [10/May/2016:05:27:23 +0200] "OPTIONS /remote.php/caldav/principals/ngrundmann/ HTTP/1.1" 200 - "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 541 1089
93.209.70.37 - - [10/May/2016:05:27:23 +0200] "PROPFIND /remote.php/caldav/calendars/NilsGrundmann/ HTTP/1.1" 401 355 "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 2741 1346
93.209.70.37 - - [10/May/2016:05:27:23 +0200] "PROPFIND /remote.php/caldav/calendars/NilsGrundmann/ HTTP/1.1" 207 16749 "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 2800 17947
93.209.70.37 - - [10/May/2016:05:27:23 +0200] "OPTIONS /remote.php/dav/principals/users/ngrundmann/ HTTP/1.1" 200 - "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 338 1430
93.209.70.37 - - [10/May/2016:05:27:24 +0200] "REPORT /remote.php/dav/addressbooks/users/ngrundmann/Kontakte/ HTTP/1.1" 401 414 "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 619 1692
93.209.70.37 - - [10/May/2016:05:27:24 +0200] "PROPFIND /remote.php/caldav/calendars/ngrundmann/ HTTP/1.1" 401 355 "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 2747 1346
93.209.70.37 - - [10/May/2016:05:27:24 +0200] "PROPFIND /remote.php/caldav/calendars/ngrundmann/ HTTP/1.1" 207 19316 "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 2802 20514
93.209.70.37 - - [10/May/2016:05:27:24 +0200] "REPORT /remote.php/dav/addressbooks/users/ngrundmann/Kontakte/ HTTP/1.1" 207 322 "-" "iOS/9.3.1 (13E238) dataaccessd/1.0" 674 1540
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"8qbQ9e4WNuAG3MhGaP04","remoteAddr":"","app":"cron","message":"Run job with ID 174","level":0,"time":"2016-05-10T05:15:03+02:00","method":"--","url":"--","user":"--"}
{"reqId":"8qbQ9e4WNuAG3MhGaP04","remoteAddr":"","app":"cron","message":"Finished job with ID 174","level":0,"time":"2016-05-10T05:15:03+02:00","method":"--","url":"--","user":"--"}
{"reqId":"8qbQ9e4WNuAG3MhGaP04","remoteAddr":"","app":"cron","message":"Run job with ID 100","level":0,"time":"2016-05-10T05:15:03+02:00","method":"--","url":"--","user":"--"}
{"reqId":"8qbQ9e4WNuAG3MhGaP04","remoteAddr":"","app":"cron","message":"Finished job with ID 100","level":0,"time":"2016-05-10T05:15:03+02:00","method":"--","url":"--","user":"--"}
{"reqId":"bookDg0fUpGjXQrwNRQ9","remoteAddr":"93.209.70.37","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trac
e\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\
\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HT
TP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/remote.php(138): require_once('\\\/var\\\/www\\\/web1\\\/a...')\\n#6 {main}\",\"Fi
le\":\"\\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"ngrundmann\"}","level":0,"time":"2016-05-10T05:27:23+02:00","method":"OPTIONS","url":"\/remote.php\/caldav\/principals\/ngrundmann\/","user":"ngrundmann"}
{"reqId":"7dtJJKSoTElRHeWPtne7","remoteAddr":"93.209.70.37","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the 
server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/s
abre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdpar
ty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/apps\\\/dav\\\/lib\\\/server.php(144): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/web1\\\/apps\
\\/owncloudng\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(29): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/remote.php(138): require_once('\\\/var\\\/www\\\/web1\\\/a...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\
/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-05-10T05:27:23+02:00","method":"OPTIONS","url":"\/remote.php\/dav\/principals\/users\/ngrundmann\/","user":"--"}
{"reqId":"oFNK\/Cy1YCFszhZDMRp2","remoteAddr":"93.209.70.37","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the
 server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/
sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdpa
rty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/apps\\\/dav\\\/lib\\\/server.php(144): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/web1\\\/apps
\\\/owncloudng\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(29): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/remote.php(138): require_once('\\\/var\\\/www\\\/web1\\\/a...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\
\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-05-10T05:27:24+02:00","method":"REPORT","url":"\/remote.php\/dav\/addressbooks\/users\/ngrundmann\/Kontakte\/","user":"--"}
{"reqId":"BadXbCtQbinFT6gRkWST","remoteAddr":"93.209.70.37","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trac
e\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\
\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/remote.php(138): require_once('\\\/var\\\/www\\\/web1\\\/a...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/web1\\\/apps\\\/owncloudng\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"ngrundmann\"}","level":0,"time":"2016-05-10T05:27:24+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/ngrundmann\/","user":"ngrundmann"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Run job with ID 99","level":0,"time":"2016-05-10T05:30:01+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Finished job with ID 99","level":0,"time":"2016-05-10T05:30:01+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Run job with ID 98","level":0,"time":"2016-05-10T05:30:01+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Finished job with ID 98","level":0,"time":"2016-05-10T05:30:01+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Run job with ID 97","level":0,"time":"2016-05-10T05:30:01+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Finished job with ID 97","level":0,"time":"2016-05-10T05:30:01+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Run job with ID 96","level":0,"time":"2016-05-10T05:30:02+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Finished job with ID 96","level":0,"time":"2016-05-10T05:30:02+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Run job with ID 95","level":0,"time":"2016-05-10T05:30:02+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Finished job with ID 95","level":0,"time":"2016-05-10T05:30:02+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-05-10T05:30:02+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-05-10T05:30:02+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-05-10T05:30:02+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-05-10T05:30:02+02:00","method":"--","url":"--","user":"--"}
{"reqId":"SFASYPYjoDR8b1BWAh1P","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-05-10T05:30:02+02:00","method":"--","url":"--","user":"--"}
```

This problem first occurred after I reorganized all my contacts and address books. Furthermore I only can add one address book now. When I create a second one and reload the Contacts page my old address book is renamed to the new one.
I deleted all contacts, groups and address books and deinstalled the contacts apps. Then I reinstalled the contacts app and imported all contacts again.

I hope you can help me because I need my contacts and it's very annoying to reimport them every day.

Kind regards,
Nils

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by ngrundmann** [comment]
Update: I reinstalled ownCloud completely and haven't experienced this bug until now. So it seems like my old ownCloud installation was broken. Maybe the problem was that it was a fresh ownCloud installation but the contacts were imported from an earlier version? I experienced this problem first after the update from 9.0.1 to 9.0.2.

**Comment by nickvergessen** [comment]
@PVince81 close until someone else faces the same issue?
