### ISSUE TITLE
Doctrine\DBAL\Exception\DriverException upgradeing to 8.2.1.4 to 8.2.4

### ISSUE THREAD

**Issue by rovincent** [owncloud/core#24562]
### Steps to reproduce
1. Run update from the web admin page
2.After successful backup, download and move and then click on Start update
3. receive: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DROP INDEX activity_user_time': SQLSTATE[HY000]: General error: 11 database disk image is malformed

### Expected behaviour
Should update successfully, i have several owncloud installs that went fine including the sandbox for the prod server above that can not update. I'm in a bit of a pickle as people will be expecting to use service in about 2 hours.

### Actual behaviour
upgrade fails with above error

### Server configuration
**Operating system**: 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u5 x86_64 GNU/Linux

**Web server:** 
Apache

**Database:**
sqlite3

**PHP version:**
5.4.45-0+deb7u2

**ownCloud version:** (see ownCloud admin page)
8.2.1.4

**Updated from an older ownCloud or fresh install:**
Older install

**Where did you install ownCloud from:**
Standard stable web admin

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

I cant it gives me the update screen

**List of activated apps:**
standard
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - bookmarks
  - contacts
  - documents
  - encryption
  - external
  - files_encryption
  - files_external
  - files_locking
  - notifications
  - user_external
  - user_ldap
  - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocg9nlfepcb0',
  'passwordsalt' => '##############################',
  'secret' => '##############################################',
  'trusted_domains' =>
  array (
    0 => '#####',
    1 => '##########',
  ),
  'datadirectory' => '/oc',
  'overwrite.cli.url' => 'https://#######',
  'dbtype' => 'sqlite3',
  'version' => '8.2.1.4',
  'installed' => true,
  'forcessl' => false,
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'oc-tns',
  'mail_domain' => '#####',
  'mail_smtphost' => '######',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 0,
  'mail_smtpport' => '25',
  'enable_previews' => 'false',
  'trashbin_retention_obligation' => 'auto, auto',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
);

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
{
    "system": {
        "instanceid": "ocg9nlfepcb0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "######",
            "######"
        ],
        "datadirectory": "\/oc",
        "overwrite.cli.url": "https:\/\/########",
        "dbtype": "sqlite3",
        "version": "8.2.1.4",
        "installed": true,
        "forcessl": false,
        "forceSSLforSubdomains": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "oc-tns",
        "mail_domain": "vbiz.ca",
        "mail_smtphost": "#######",
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "mail_smtpport": "25",
        "enable_previews": "false",
        "trashbin_retention_obligation": "auto, auto",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
chrome, firefox

**Operating system:**
Windows 7
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
{"reqId":"KNRN+bdlyZ3ssAaiqIh2","remoteAddr":"10.11.0.6","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/var\\\/www\\\/lib\\\/private\\\/util.php(130): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/lib\\\/base.php(852): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/lib\\\/private\\\/app.php\",\"Line\":139}","level":3,"time":"2016-05-11T10:12:54+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=5e3f488145281dc3c8832d9f9f7711cb"}
{"reqId":"atJ0pCSYKqlzKiUrDCf6","remoteAddr":"10.11.0.6","app":"core","message":"starting upgrade from 8.2.1.4 to 8.2.4.2","level":0,"time":"2016-05-11T10:12:58+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=AgpMeD40OBEFJVADCiB5MR4LQjMZKXw4KRRFLlQ5%3Ap3g1iFouSHatDvMRNN0ucA%2BZqznK3j"}
{"reqId":"atJ0pCSYKqlzKiUrDCf6","remoteAddr":"10.11.0.6","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'DROP INDEX activity_user_time':\\n\\nSQLSTATE[HY000]: General error: 11 database disk image is malformed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(945): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'DROP INDEX acti...')\\n#2 \\\/var\\\/www\\\/lib\\\/repair\\\/sqliteautoincrement.php(93): Doctrine\\\\DBAL\\\\Connection->query('DROP INDEX acti...')\\n#3 \\\/var\\\/www\\\/lib\\\/private\\\/repair.php(87): OC\\\\Repair\\\\SqliteAutoincrement->run()\\n#4 \\\/var\\\/www\\\/lib\\\/private\\\/updater.php(304): OC\\\\Repair->run()\\n#5 \\\/var\\\/www\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.4.2', '8.2.1.4')\\n#6 \\\/var\\\/www\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":85}","level":3,"time":"2016-05-11T10:12:58+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=AgpMeD40OBEFJVADCiB5MR4LQjMZKXw4KRRFLlQ5%3Ap3g1iFouSHatDvMRNN0ucA%2BZqznK3j"}
{"reqId":"B0u8iEjxN4NnlGJir5TQ","remoteAddr":"10.11.0.6","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/var\\\/www\\\/lib\\\/private\\\/util.php(130): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/lib\\\/base.php(852): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/lib\\\/private\\\/app.php\",\"Line\":139}","level":3,"time":"2016-05-11T10:20:18+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=5e3f488145281dc3c8832d9f9f7711cb"}
{"reqId":"OZjJwXUGN3iwJxx0thfO","remoteAddr":"10.11.0.6","app":"core","message":"starting upgrade from 8.2.1.4 to 8.2.4.2","level":0,"time":"2016-05-11T10:22:03+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=GXtRCA48PiM9AFwTDCcCFxYWIXIfXCcXLR9EPEwZ%3AkBzAYNiGkmmdBq6tFSS4e4puuqoY%2BJ"}
{"reqId":"OZjJwXUGN3iwJxx0thfO","remoteAddr":"10.11.0.6","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'DROP INDEX activity_user_time':\\n\\nSQLSTATE[HY000]: General error: 11 database disk image is malformed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(945): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'DROP INDEX acti...')\\n#2 \\\/var\\\/www\\\/lib\\\/repair\\\/sqliteautoincrement.php(93): Doctrine\\\\DBAL\\\\Connection->query('DROP INDEX acti...')\\n#3 \\\/var\\\/www\\\/lib\\\/private\\\/repair.php(87): OC\\\\Repair\\\\SqliteAutoincrement->run()\\n#4 \\\/var\\\/www\\\/lib\\\/private\\\/updater.php(304): OC\\\\Repair->run()\\n#5 \\\/var\\\/www\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.4.2', '8.2.1.4')\\n#6 \\\/var\\\/www\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":85}","level":3,"time":"2016-05-11T10:22:03+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=GXtRCA48PiM9AFwTDCcCFxYWIXIfXCcXLR9EPEwZ%3AkBzAYNiGkmmdBq6tFSS4e4puuqoY%2BJ"}
{"reqId":"lx6HG232kmFAprITWiNd","remoteAddr":"10.11.0.6","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/var\\\/www\\\/lib\\\/private\\\/util.php(130): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/lib\\\/base.php(852): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/lib\\\/private\\\/app.php\",\"Line\":139}","level":3,"time":"2016-05-11T10:22:10+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=5e3f488145281dc3c8832d9f9f7711cb"}
{"reqId":"51A2\/261QdASHIcM8APq","remoteAddr":"10.11.0.6","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/var\\\/www\\\/lib\\\/private\\\/util.php(130): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/lib\\\/base.php(852): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/lib\\\/private\\\/app.php\",\"Line\":139}","level":3,"time":"2016-05-11T10:22:30+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=5e3f488145281dc3c8832d9f9f7711cb"}
{"reqId":"GdMFsj1cDnI93ZNS1tY4","remoteAddr":"10.11.0.6","app":"core","message":"starting upgrade from 8.2.1.4 to 8.2.4.2","level":0,"time":"2016-05-11T10:22:32+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=RAsaeDhZMwAHJkURBQ9gKTUdJxQZGyYmMjcfMR8F%3A6211o%2BddQKtfKYTJeXURcsqDjY4TxV"}
{"reqId":"GdMFsj1cDnI93ZNS1tY4","remoteAddr":"10.11.0.6","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'DROP INDEX activity_user_time':\\n\\nSQLSTATE[HY000]: General error: 11 database disk image is malformed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(945): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'DROP INDEX acti...')\\n#2 \\\/var\\\/www\\\/lib\\\/repair\\\/sqliteautoincrement.php(93): Doctrine\\\\DBAL\\\\Connection->query('DROP INDEX acti...')\\n#3 \\\/var\\\/www\\\/lib\\\/private\\\/repair.php(87): OC\\\\Repair\\\\SqliteAutoincrement->run()\\n#4 \\\/var\\\/www\\\/lib\\\/private\\\/updater.php(304): OC\\\\Repair->run()\\n#5 \\\/var\\\/www\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.4.2', '8.2.1.4')\\n#6 \\\/var\\\/www\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":85}","level":3,"time":"2016-05-11T10:22:32+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=RAsaeDhZMwAHJkURBQ9gKTUdJxQZGyYmMjcfMR8F%3A6211o%2BddQKtfKYTJeXURcsqDjY4TxV"}
{"reqId":"m2IR1X87d0o28UKPj5Lr","remoteAddr":"10.11.0.6","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/var\\\/www\\\/lib\\\/private\\\/util.php(130): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/lib\\\/base.php(852): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/lib\\\/private\\\/app.php\",\"Line\":139}","level":3,"time":"2016-05-11T10:23:55+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=5e3f488145281dc3c8832d9f9f7711cb"}
{"reqId":"HNnDFAem6EGdELYETyv9","remoteAddr":"10.11.0.6","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/var\\\/www\\\/lib\\\/private\\\/util.php(130): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/lib\\\/base.php(852): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/lib\\\/private\\\/app.php\",\"Line\":139}","level":3,"time":"2016-05-11T10:23:57+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=5e3f488145281dc3c8832d9f9f7711cb"}
{"reqId":"5PBKnYsp73n0gBhq0J3h","remoteAddr":"10.11.0.6","app":"core","message":"starting upgrade from 8.2.1.4 to 8.2.4.2","level":0,"time":"2016-05-11T10:24:01+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=Q0lOBmRZYxATX2IgJX1ROyITKz8pJSI0YFdbVyg4%3A1peO3%2B4tE2SWk%2BeXrVYySMuV89p2Ok"}
{"reqId":"5PBKnYsp73n0gBhq0J3h","remoteAddr":"10.11.0.6","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'DROP INDEX activity_user_time':\\n\\nSQLSTATE[HY000]: General error: 11 database disk image is malformed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(945): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'DROP INDEX acti...')\\n#2 \\\/var\\\/www\\\/lib\\\/repair\\\/sqliteautoincrement.php(93): Doctrine\\\\DBAL\\\\Connection->query('DROP INDEX acti...')\\n#3 \\\/var\\\/www\\\/lib\\\/private\\\/repair.php(87): OC\\\\Repair\\\\SqliteAutoincrement->run()\\n#4 \\\/var\\\/www\\\/lib\\\/private\\\/updater.php(304): OC\\\\Repair->run()\\n#5 \\\/var\\\/www\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.4.2', '8.2.1.4')\\n#6 \\\/var\\\/www\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":85}","level":3,"time":"2016-05-11T10:24:01+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=Q0lOBmRZYxATX2IgJX1ROyITKz8pJSI0YFdbVyg4%3A1peO3%2B4tE2SWk%2BeXrVYySMuV89p2Ok"}


#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by nickvergessen** [comment]
Nothing related to ownCloud, you have a problem with your database.
Try searching the web for `General error: 11 database disk image is malformed`
