### ISSUE TITLE
Chromium user agent too long for oc_authtoken

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24593]
### Steps

1. Using Chromium 49, login in ownCloud on master

### Expected result
Wrosk

### Actual result
```
{"reqId":"fwOT7ccIV5\/6+2tb\/9gw","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_authtoken`(`uid`,`password`,`name`,`token`,`type`,`last_activity`) VALUES(?,?,?,?,?,?)' with params [\\\"admin\\\", \\\"7f9044ffa49bf62a807d01738dea7ede|WuaASuLI0HN7x1wc|ad87d69226af13a0c43106f375e76816cfaec4bf91dad1241fe38ba31f3493374a3431db0f86d5e70f11db14118fb9330f244a1804b04d7300d7c7e00a9e7169\\\", \\\"Mozilla\\\\\\\/5.0 (X11; Linux x86_64) AppleWebKit\\\\\\\/537.36 (KHTML, like Gecko) Chrome\\\\\\\/49.0.2623.112 Safari\\\\\\\/537.36\\\", \\\"926b05a1aa07f57df6fe3efb7c7eae903ca5e73a164eeef87617931825270cdea479eba1de5e4cef97ccceb911cc85ac76beb53c16b5afff19b1dacd5166ebc5\\\", 0, 1463043153]:\\n\\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'name' at row 1\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(175): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(251): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(125): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('INSERT INTO `*P...', Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(84): OCP\\\\AppFramework\\\\Db\\\\Mapper->insert(Object(OC\\\\Authentication\\\\Token\\\\DefaultToken))\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(408): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->generateToken('e43bse8n93nbl6f...', 'admin', 'admin', 'Mozilla\\\/5.0 (X1...')\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(188): OC\\\\User\\\\Session->createSessionToken(Object(OC\\\\AppFramework\\\\Http\\\\Request), 'admin', 'admin')\\n#7 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin('admin', 'admin', '%2Fowncloud%2Fi...')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(45): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(871): OC\\\\Route\\\\Router->match('\\\/login')\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":3,"time":"2016-05-12T08:52:33+00:00","method":"POST","url":"\/owncloud\/index.php\/login?redirect_url=%252Fowncloud%252Findex.php%252Fapps%252Ffiles%252F","user":"admin"}
```

Looks like the user agent is too long for the table.
Please truncate it.

@ChristophWurst

**Comment by LukasReschke** [comment]
I'd vote for a TEXT field

**Comment by PVince81** [comment]
That was with mysql. Seems sqlite ignores field lengths.
