### ISSUE TITLE
oc_authtoken missing when accessing update screen with existing session

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24592]
### Steps

1. Checkout v9.0.2 from git
1. Setup ownCloud
1. Login as admin and keep logged in
1. Switch to master 8729415880181275c9d4a05707273e13c9cf7e1b
1. Refresh the page

### Expected result
Update page appears

### Actual result
Error page, log:
```
{"reqId":"8jaFPhGD6jt8Gn97L\/y9","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `id`, `uid`, `password`, `name`, `type`, `token`, `last_activity` FROM `oc_authtoken` WHERE `token` = ?' with params [\\\"1154847d4a5776ff188063e5205d682dc4b98213a5dd6c1821a62ed69c3e30dd5b7a26c571544f29adb5d4a168cb64745fa12bd2f2f22d3e5052d8cfc4c35769\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_authtoken' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(184): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenMapper.php(77): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(112): OC\\\\Authentication\\\\Token\\\\DefaultTokenMapper->getToken('1154847d4a5776f...')\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(220): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->getToken('kq0j4n000o4cabh...')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(208): OC\\\\User\\\\Session->validateSession(Object(OC\\\\User\\\\User))\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/L10N\\\/Factory.php(131): OC\\\\User\\\\Session->getUser()\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/L10N\\\/Factory.php(99): OC\\\\L10N\\\\Factory->findLanguage('core')\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Server.php(895): OC\\\\L10N\\\\Factory->get('core', NULL)\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Server.php(123): OC\\\\Server->getL10N('core')\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(102): Pimple\\\\Container->offsetGet('EncryptionManag...')\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('EncryptionManag...')\\n#16 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Server.php(681): OC\\\\ServerContainer->query('EncryptionManag...')\\n#17 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(726): OC\\\\Server->getEncryptionManager()\\n#18 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(645): OC::registerEncryptionWrapper()\\n#19 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(947): OC::init()\\n#20 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(37): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#21 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","level":3,"time":"2016-05-12T08:45:19+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","user":"admin"}
```

It looks like it's trying to access/use the session.
However when an update is due, the session must be ignored (or use the incognito mode).

Maybe the recent changes to the session workflow is causing this ?

@ChristophWurst @LukasReschke 

Assigning to @ChristophWurst as discussed

**Comment by PVince81** [comment]
Also make sure that all other endpoints (Webdav, OCS, etc) are properly returning "503 Service not available" when an update is due.

**Comment by ChristophWurst** [comment]
ref https://github.com/owncloud/core/pull/24189#issuecomment-217443594
