### ISSUE TITLE
Can't login from the web ui

### ISSUE THREAD

**Issue by McKay1717** [owncloud/core#24607]
### Steps to reproduce
1. Go to web ui login page
2. Try to login

### Expected behaviour
Login and acces to default app

### Actual behaviour
Can't login even if i provide  good info.
The web ui does not display error like "invalid password" but if login is bad , this message appear.
But WebDav Login work.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:**
```
nginx version: nginx/1.10.0 (Ubuntu)
```

**Database:** MySql 5.7.12

**PHP version:** 7.0

**ownCloud version:** 
```
 - installed: true
  - version: 9.1.0.1
  - versionstring: 9.1.0 pre alpha
  - edition: 
```

**Updated from an older ownCloud or fresh install:** Update from previus daily build

**Where did you install ownCloud from:** From daily archive

**Signing status (ownCloud 9.0 and above):**

```
Web GUI login fail, i can't provide that
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.4
  - federatedfilesharing: 0.2.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocle25k4x281",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mckay1717.eu"
        ],
        "datadirectory": "\/home\/data\/owncloud",
        "overwrite.cli.url": "https:\/\/cloud.mckay1717.eu\/",
        "dbtype": "mysql",
        "version": "9.1.0.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "mckay1717.eu",
        "mail_smtphost": "**SMTP Server IP",
        "mail_smtpport": "25",
        "maintenance": false,
        "asset-pipeline.enabled": true,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "loglevel": 0,
        "log_type": "owncloud",
        "trashbin_retention_obligation": 60
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "3"
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "0.7.3",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1440272163.8749",
            "lastcron": "1463077802",
            "lastupdateResult": "{\"version\":\"100.0.0.0\",\"versionstring\":\"ownCloud daily\",\"url\":\"https:\\\/\\\/download.owncloud.org\\\/community\\\/owncloud-daily-stable9.zip\",\"web\":\"https:\\\/\\\/doc.owncloud.org\\\/server\\\/8.2\\\/admin_manual\\\/maintenance\\\/upgrade.html\"}",
            "lastupdatedat": "0",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "updater.secret.created": "1461253861"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.2.4",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.10.2",
            "ocsid": "168711",
            "types": "",
            "unstable": "false"
        },
        "external": {
            "enabled": "no",
            "installed_version": "1.2",
            "ocsid": "166046",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.2.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.5.1",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "no",
            "installed_version": "0.5.1",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "\\OC\\Files\\Storage\\Dropbox,\\OC\\Files\\Storage\\Google,\\OC\\Files\\Storage\\Hubic,\\OC\\Files\\Storage\\Swift,\\OC\\Files\\Storage\\OwnCloud,\\OC\\Files\\Storage\\SFTP"
        },
        "files_hubic": {
            "enabled": "no",
            "installed_version": "8.0.2",
            "ocsid": "168188",
            "types": "filesystem"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_mv": {
            "enabled": "no",
            "installed_version": "0.8.2",
            "ocsid": "150271",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.10.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "cronjob_user_offset": "1000",
            "enabled": "yes",
            "installed_version": "0.9.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "15.0.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "14.3.0",
            "ocsid": "169116",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.2.0",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        }
    }
}


```

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:**Firefox 46.0

**OS:**KUbuntu 16.04

#### Web server error log
```
==> /var/log/nginx/access.log <==
69.162.124.230 - - [12/May/2016:20:23:50 +0200] "GET /login HTTP/1.1" 200 3814 "-" "Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)"
**Client IP** - - [12/May/2016:20:24:14 +0200] "POST /login?redirect_url=%252Findex.php%252Fapps%252Ffiles%252F HTTP/1.1" 303 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
**Client IP** - - [12/May/2016:20:24:14 +0200] "GET /login?user=McKay1717 HTTP/1.1" 200 3945 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
**Client IP** - - [12/May/2016:20:24:14 +0200] "GET /core/js/oc.js?v=a1bf2c7ae8e7960f42a9c1dc5fb3ab61 HTTP/1.1" 200 2561 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
**Client IP** - - [12/May/2016:20:26:11 +0200] "POST /login?user=McKay1717 HTTP/1.1" 303 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
**Client IP** - - [12/May/2016:20:26:11 +0200] "GET /apps/files/ HTTP/1.1" 303 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
**Client IP** - - [12/May/2016:20:26:11 +0200] "GET /login?redirect_url=%252Fapps%252Ffiles%252F HTTP/1.1" 200 3943 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
**Client IP** - - [12/May/2016:20:26:12 +0200] "GET /core/js/oc.js?v=a1bf2c7ae8e7960f42a9c1dc5fb3ab61 HTTP/1.1" 200 2561 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
**Client IP** - - [12/May/2016:20:26:12 +0200] "GET /assets/jquery.min.map; HTTP/1.1" 302 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
**Client IP** - - [12/May/2016:20:26:12 +0200] "GET /login HTTP/1.1" 200 3875 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
```
```
==> /var/log/nginx/error.log <==
2016/05/12 20:00:02 [notice] 21979#21979: signal process started

```

#### ownCloud log (data/owncloud.log)
```{"reqId":"0E\/QLtYLOZ5re\/WdbeVI","remoteAddr":"**Client IP**","app":"no app in context","message":"invalid token","level":2,"time":"2016-05-12T20:26:11+02:00","method":"GET","url":"\/apps\/files\/","user":"--"}
{"reqId":"0E\/QLtYLOZ5re\/WdbeVI","remoteAddr":"**Client IP**","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2016-05-12T20:26:11+02:00","method":"GET","url":"\/apps\/files\/","user":"--"}
{"reqId":"E2\/cx5kqaG\/MLO5pUzAs","remoteAddr":"**Client IP**","app":"no app in context","message":"validating default token <oc5pas4q44tf5cfvt76nr2vsu5>","level":0,"time":"2016-05-12T20:26:11+02:00","method":"GET","url":"\/login?redirect_url=%252Fapps%252Ffiles%252F","user":"--"}
{"reqId":"E2\/cx5kqaG\/MLO5pUzAs","remoteAddr":"**Client IP**","app":"no app in context","message":"invalid token","level":2,"time":"2016-05-12T20:26:11+02:00","method":"GET","url":"\/login?redirect_url=%252Fapps%252Ffiles%252F","user":"--"}
{"reqId":"odRY\/PhUgiffckaHaTlu","remoteAddr":"**Client IP**","app":"no app in context","message":"validating default token <oc5pas4q44tf5cfvt76nr2vsu5>","level":0,"time":"2016-05-12T20:26:11+02:00","method":"GET","url":"\/core\/js\/oc.js?v=a1bf2c7ae8e7960f42a9c1dc5fb3ab61","user":"--"}
{"reqId":"odRY\/PhUgiffckaHaTlu","remoteAddr":"**Client IP**","app":"no app in context","message":"invalid token","level":2,"time":"2016-05-12T20:26:11+02:00","method":"GET","url":"\/core\/js\/oc.js?v=a1bf2c7ae8e7960f42a9c1dc5fb3ab61","user":"--"}
{"reqId":"YidZ1maM8iwPwAJKblOd","remoteAddr":"**Client IP**","app":"no app in context","message":"validating default token <oc5pas4q44tf5cfvt76nr2vsu5>","level":0,"time":"2016-05-12T20:26:12+02:00","method":"GET","url":"\/assets\/jquery.min.map;","user":"--"}
{"reqId":"YidZ1maM8iwPwAJKblOd","remoteAddr":"**Client IP**","app":"no app in context","message":"invalid token","level":2,"time":"2016-05-12T20:26:12+02:00","method":"GET","url":"\/assets\/jquery.min.map;","user":"--"}
{"reqId":"w8ZHThJsHqMksh9zAIYi","remoteAddr":"**Client IP**","app":"no app in context","message":"validating default token <oc5pas4q44tf5cfvt76nr2vsu5>","level":0,"time":"2016-05-12T20:26:12+02:00","method":"GET","url":"\/login","user":"--"}
{"reqId":"w8ZHThJsHqMksh9zAIYi","remoteAddr":"**Client IP**","app":"no app in context","message":"invalid token","level":2,"time":"2016-05-12T20:26:12+02:00","method":"GET","url":"\/login","user":"--"}
```

#### Browser log
```
20:26:12,271 JQMIGRATE: Migrate is installed, version 1.4.01 273f6416d32fabf716aa74bb711532f5.js:7:542

**Comment by LukasReschke** [comment]
Please test https://github.com/owncloud/core/pull/24594 :)

**Comment by McKay1717** [comment]
I  have patch my install with that commit but that doesn't solve my problem

**Comment by McKay1717** [comment]
When i try to log me in with DAV , this error spawn but DAV work fine.
```
{"reqId":"YBbeu\/uODBc8L9es46sE","remoteAddr":"188.166.112.197","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/media\\\/ramdisk\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/media\\\/ramdisk\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/media\\\/ramdisk\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/media\\\/ramdisk\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/media\\\/ramdisk\\\/remote.php(164): require_once('\\\/media\\\/ramdisk\\\/...')\\n#6 {main}\",\"File\":\"\\\/media\\\/ramdisk\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-05-12T23:22:34+02:00","method":"OPTIONS","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"cMp8dQ\/n20eT8\/RuymEa","remoteAddr":"69.162.124.230","app":"no app in context","message":"validating default token <jft0ohqdjqah2esrkt97ksbmv6>","level":0,"time":"2016-05-12T23:25:33+02:00","method":"HEAD","url":"\/","user":"--"}
{"reqId":"cMp8dQ\/n20eT8\/RuymEa","remoteAddr":"69.162.124.230","app":"no app in context","message":"invalid token","level":2,"time":"2016-05-12T23:25:33+02:00","method":"HEAD","url":"\/","user":"--"}
{"reqId":"ZBSbYYXksrnd5aK21+gb","remoteAddr":"69.162.124.230","app":"no app in context","message":"validating default token <4f1dvlhvrl9rtfiebgrgfkeo96>","level":0,"time":"2016-05-12T23:25:34+02:00","method":"GET","url":"\/login","user":"--"}
{"reqId":"ZBSbYYXksrnd5aK21+gb","remoteAddr":"69.162.124.230","app":"no app in context","message":"invalid token","level":2,"time":"2016-05-12T23:25:34+02:00","method":"GET","url":"\/login","user":"--"}
```

**Comment by LukasReschke** [comment]
@christophwurst

**Comment by ChristophWurst** [comment]
@McKay1717 which client did you use to log into DAV?

**Comment by McKay1717** [comment]
I use davfs in a Kubuntu 16.04

**Comment by ChristophWurst** [comment]
Please have a look at the ``oc_authtoken`` (assuming your db prefix is oc) table and check if entries are generated when logging in.
No error message on the login screen means the login process succeeds. It seems that the login check fails on the next request though.

**Comment by McKay1717** [comment]
A new line was INSERT in oc_authtoken.

**Comment by ChristophWurst** [comment]
@McKay1717 do you still face those problems?

**Comment by McKay1717** [comment]
I have change my session handler in my php.ini and the problem was solve. T change memcache to files

**Comment by ChristophWurst** [comment]
What exactly did you change?

**Comment by McKay1717** [comment]
@ChristophWurst 
`session.save_handler = files //comment out
;session.save_handler = memcache //commented
;session.save_path = "tcp://192.168.7.139:11211,tcp://192.168.7.1:11211" //commanted
`

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
