### ISSUE TITLE
Setting SMB/CIFS external storage results in TimedOutException

### ISSUE THREAD

**Issue by StraToN** [owncloud/core#24627]
### Steps to reproduce
1. Go to Administration page, "External Storage" section
2. Select SMB / CIFS 
3. Enter configuration 

### Expected behaviour
Supposing configuration is correct, the external storage should be accessed and the icon should turn green (success)

### Actual behaviour
Spinner turns for 1-2 minutes before turning to red (fail) icon

### Server configuration
**Operating system**:
Ubuntu server 14.10

**Web server:**
Server version: Apache/2.4.7 (Ubuntu)

**Database:**
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.5.9-1ubuntu4.16 (cli) (built: Apr 20 2016 14:31:27) 

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.4 (stable) 

**Updated from an older ownCloud or fresh install:**
updated from 8.2.3 (stable)

**Where did you install ownCloud from:**
manual install

**Signing status (ownCloud 9.0 and above):**
N/A

**List of activated apps:**

```
Enabled:
  - activity: 2.1.4
  - calendar: 0.8.2
  - contacts: 0.5.0.0
  - encryption: 1.1.0
  - files: 1.2.1
  - files_external: 0.3.0
  - files_pdfviewer: 0.7.1
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - news: 6.1.1
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - bookmarks
  - calendarplus
  - external
  - mail
  - polls
  - roundcube
  - user_external
  - user_ldap
  - user_webdavauth

```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oczntxn0x87u',
  'passwordsalt' => '###',
  'secret' => '###',
  'trusted_domains' => 
  array (
    0 => 'cloud.murgia.fr',
  ),
  'defaultapp' => 'news',
  'datadirectory' => '/var/www/owncloud2/data',
  'overwrite.cli.url' => 'https://cloud.murgia.fr',
  'dbtype' => 'mysql',
  'version' => '8.2.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '###',
  'dbpassword' => '###',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 0,
  'forcessl' => true,
  'forceSSLforSubdomains' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'debug' => true,
  'trashbin_retention_obligation' => 'auto',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'postmaster',
  'mail_domain' => 'murgia.fr',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.murgia.fr',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'postmaster@murgia.fr',
  'mail_smtppassword' => '###',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'appstore.experimental.enabled' => true,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb (trying to...)

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Webdav

### Client configuration
**Browser:**
Mozilla Firefox 46.0

**Operating system:**
Xubuntu 16.04

#### Web server error log
```
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:08 +0200] "GET /index.php/settings/admin HTTP/1.1" 200 13157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:09 +0200] "GET /index.php/core/js/oc.js?v=0ebd9ecb064977ba027c5f51443abb58 HTTP/1.1" 200 3140 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:09 +0200] "GET /core/img/actions/delete.svg HTTP/1.1" 304 211 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:09 +0200] "GET /index.php/apps/notifications HTTP/1.1" 204 755 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:09 +0200] "GET /index.php/avatar/jmurgia/128 HTTP/1.1" 200 864 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:09 +0200] "GET /index.php/heartbeat HTTP/1.1" 200 931 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:09 +0200] "POST /index.php/displaynames HTTP/1.1" 200 834 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:10 +0200] "GET /core/img/actions/info.svg HTTP/1.1" 304 211 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:10 +0200] "GET /core/img/actions/checkbox-checked.svg HTTP/1.1" 304 211 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:10 +0200] "GET /core/img/actions/checkbox.svg HTTP/1.1" 304 211 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:10 +0200] "GET /core/img/loading-small.gif HTTP/1.1" 304 211 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:10 +0200] "GET /core/img/actions/triangle-s.svg HTTP/1.1" 304 211 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:10 +0200] "GET /core/vendor/select2/select2.png HTTP/1.1" 304 211 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:10 +0200] "GET /index.php/apps/encryption/ajax/getStatus HTTP/1.1" 200 886 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:10 +0200] "GET /index.php/apps/updater/backup/index HTTP/1.1" 200 1893 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - ethouret [13/May/2016:16:39:11 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1218 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
cloud.murgia.fr:443 78.119.228.216 - jmurgia [13/May/2016:16:39:14 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 500 1054 "-" "Mozilla/5.0 (Linux) mirall/2.2.0%nil (build 1605)"
cloud.murgia.fr:443 78.119.228.216 - jmurgia [13/May/2016:16:39:14 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1360 "-" "Mozilla/5.0 (Linux) mirall/2.2.0%nil (build 1605)"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:40 +0200] "GET /index.php/apps/news/folders HTTP/1.1" 200 1511 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:40 +0200] "GET /index.php/apps/news/feeds HTTP/1.1" 200 26059 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - ethouret [13/May/2016:16:39:41 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1218 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
cloud.murgia.fr:443 78.119.228.216 - jmurgia [13/May/2016:16:39:44 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1218 "-" "Mozilla/5.0 (Linux) mirall/2.2.0%nil (build 1605)"
cloud.murgia.fr:443 78.119.228.216 - ethouret [13/May/2016:16:40:11 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1218 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
cloud.murgia.fr:443 78.119.228.216 - jmurgia [13/May/2016:16:40:14 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1218 "-" "Mozilla/5.0 (Linux) mirall/2.2.0%nil (build 1605)"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:40:39 +0200] "GET /index.php/apps/news/folders HTTP/1.1" 200 1511 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:40:39 +0200] "GET /index.php/apps/news/feeds HTTP/1.1" 200 26059 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - ethouret [13/May/2016:16:40:41 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1218 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
cloud.murgia.fr:443 78.119.228.216 - jmurgia [13/May/2016:16:40:44 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1218 "-" "Mozilla/5.0 (Linux) mirall/2.2.0%nil (build 1605)"
cloud.murgia.fr:443 78.119.228.216 - ethouret [13/May/2016:16:41:11 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1218 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
cloud.murgia.fr:443 78.119.228.216 - jmurgia [13/May/2016:16:41:14 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1218 "-" "Mozilla/5.0 (Linux) mirall/2.2.0%nil (build 1605)"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:09 +0200] "PROPFIND /remote.php/webdav HTTP/1.1" 207 6515 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:39:09 +0200] "GET /index.php/apps/files_external/globalstorages/3 HTTP/1.1" 200 1261 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:41:40 +0200] "GET /index.php/apps/news/feeds HTTP/1.1" 200 26059 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - - [13/May/2016:16:41:40 +0200] "GET /index.php/apps/news/folders HTTP/1.1" 200 1511 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
cloud.murgia.fr:443 78.119.228.216 - ethouret [13/May/2016:16:41:41 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1218 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
```

##### Human-readable
```
{"reqId":"qCEJ7\/+l+8Pbfa4ag66z",
"remoteAddr":"78.119.228.216",
"app":"files_external",
"message":"Exception: {\"Exception\":\"Icewind\SMB\Exception\TimedOutException\",\"Message\":\"smb://192.168.0.141/media/\",\"Code\":110,\"Trace\":\"#0 /var/www/owncloud2/apps/files_external/3rdparty/icewind/smb/src/NativeState.php(72): Icewind\SMB\NativeState->handleError('smb://192.168.0...')\
#1 /var/www/owncloud2/apps/files_external/3rdparty/icewind/smb/src/NativeState.php(180): Icewind\SMB\NativeState->testResult(false, 'smb://192.168.0...')\
#2 /var/www/owncloud2/apps/files_external/3rdparty/icewind/smb/src/NativeShare.php(108): Icewind\SMB\NativeState->stat('smb://192.168.0...')\
#3 /var/www/owncloud2/apps/files_external/3rdparty/icewind/smb/src/NativeShare.php(103): Icewind\SMB\NativeShare->getStat('/')\
#4 /var/www/owncloud2/apps/files_external/lib/smb.php(110): Icewind\SMB\NativeShare->stat('/')\
#5 /var/www/owncloud2/apps/files_external/lib/smb.php(144): OC\Files\Storage\SMB->getFileInfo('')\
#6 /var/www/owncloud2/lib/private/files/storage/common.php(410): OC\Files\Storage\SMB->stat('')\
#7 /var/www/owncloud2/apps/files_external/lib/config.php(261): OC\Files\Storage\Common->test(false)\
#8 /var/www/owncloud2/apps/files_external/controller/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\OC\Files\Stora...', Array, false)\
#9 /var/www/owncloud2/apps/files_external/controller/globalstoragescontroller.php(174): OCA\Files_External\Controller\StoragesController->updateStorageStatus(Object(OCA\Files_external\Lib\StorageConfig))\
#10 [internal function]: OCA\Files_External\Controller\GlobalStoragesController->update(3, 'SMBVideos', 'smb', 'password::passw...', Array, Array, Array, Array, 100)\
#11 /var/www/owncloud2/lib/private/appframework/http/dispatcher.php(159): call_user_func_array(Array, Array)\
#12 /var/www/owncloud2/lib/private/appframework/http/dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_External\Controller\GlobalStoragesController), 'update')\
#13 /var/www/owncloud2/lib/private/appframework/app.php(108): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_External\Controller\GlobalStoragesController), 'update')\
#14 /var/www/owncloud2/lib/private/appframework/routing/routeactionhandler.php(45): OC\AppFramework\App::main('GlobalStoragesC...', 'update', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\
#15 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\
#16 /var/www/owncloud2/lib/private/route/router.php(291): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\
#17 /var/www/owncloud2/lib/base.php(853): OC\Route\Router->match('/apps/files_ext...')\
#18 /var/www/owncloud2/index.php(39): OC::handleRequest()\
#19 {main}\",\"File\":\"/var/www/owncloud2/apps/files_external/3rdparty/icewind/smb/src/NativeState.php\",\"Line\":54}",
"level":3,
"time":"2016-05-13T14:24:58+00:00",
"method":"PUT",
"url":"\/index.php\/apps\/files_external\/globalstorages\/3"}
```

##### RAW
```
{"reqId":"qCEJ7\/+l+8Pbfa4ag66z","remoteAddr":"78.119.228.216","app":"files_external","message":"Exception: {\"Exception\":\"Icewind\\\\SMB\\\\Exception\\\\TimedOutException\",\"Message\":\"smb:\\\/\\\/192.168.0.141\\\/media\\\/\",\"Code\":110,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud2\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(72): Icewind\\\\SMB\\\\NativeState->handleError('smb:\\\/\\\/192.168.0...')\\n#1 \\\/var\\\/www\\\/owncloud2\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(180): Icewind\\\\SMB\\\\NativeState->testResult(false, 'smb:\\\/\\\/192.168.0...')\\n#2 \\\/var\\\/www\\\/owncloud2\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(108): Icewind\\\\SMB\\\\NativeState->stat('smb:\\\/\\\/192.168.0...')\\n#3 \\\/var\\\/www\\\/owncloud2\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(103): Icewind\\\\SMB\\\\NativeShare->getStat('\\\/')\\n#4 \\\/var\\\/www\\\/owncloud2\\\/apps\\\/files_external\\\/lib\\\/smb.php(110): Icewind\\\\SMB\\\\NativeShare->stat('\\\/')\\n#5 \\\/var\\\/www\\\/owncloud2\\\/apps\\\/files_external\\\/lib\\\/smb.php(144): OC\\\\Files\\\\Storage\\\\SMB->getFileInfo('')\\n#6 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(410): OC\\\\Files\\\\Storage\\\\SMB->stat('')\\n#7 \\\/var\\\/www\\\/owncloud2\\\/apps\\\/files_external\\\/lib\\\/config.php(261): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#8 \\\/var\\\/www\\\/owncloud2\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#9 \\\/var\\\/www\\\/owncloud2\\\/apps\\\/files_external\\\/controller\\\/globalstoragescontroller.php(174): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#10 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update(3, 'SMBVideos', 'smb', 'password::passw...', Array, Array, Array, Array, 100)\\n#11 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#13 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#14 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#15 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#16 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#17 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/base.php(853): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#18 \\\/var\\\/www\\\/owncloud2\\\/index.php(39): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud2\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php\",\"Line\":54}","level":3,"time":"2016-05-13T14:24:58+00:00","method":"PUT","url":"\/index.php\/apps\/files_external\/globalstorages\/3"}
```

#### Browser log
```
N/A
```

**Comment by Xenopathic** [comment]
That exception is thrown if there is some issue connecting to your SMB server. Since this appears to be a configuration issue rather than an ownCloud issue, please ask on the forums or on IRC to get help.
