### ISSUE TITLE
GDrive can't upload files if name without extension already exists

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24631]
### Steps

1. Create a folder "test" directly on GDrive
1. Setup GDrive ext storage
1. In ownCloud, create a file "test.txt" (name must be the same like the folder + ".txt" extension)

### Expected
Can create the file

### Actual
```
{"reqId":"dD0ednjoIkqyq4vqcKCh","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 409 PUT is not allowed on non-files.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Code\":0,\"Trace\":\"
#0 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#6 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php\",\"Line\":509,\"User\":\"admin\"}","level":4,"time":"2016-05-13T16:38:05+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/gdrive\/test.txt","user":"admin"}
```

Likely a regression from the fix with part file renames: https://github.com/owncloud/core/pull/22405

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25007

Will double check if that's really a regression.

**Comment by PVince81** [comment]
Not a regression, this existed already in 8.0.6 and was never discovered !
