### ISSUE TITLE
Upgrade from stable9 fails

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#24666]
1. install stable9
2. checkout master
3. browse owncloud in master
4. :boom:

I got following error:

```
{
	"reqId":"jVCTq30rCVOv6t\/Hx0i8",
	"remoteAddr":"::1",
	"app":"index",
	"message":{
		"Exception":"Doctrine\DBAL\Exception\TableNotFoundException",
		"Message":"An exception occurred while executing 'SELECT "id", "uid", "password", "name", "type", "token", "last_activity" FROM "oc_authtoken" WHERE "token" = ?' with params ["900f5a05ce3f9bfe7098fdbb9b018bf24ca546827415b7f1c2d1e947be7118863b33334c74685fa2ab97325263e164f6c7bde2d11099b4ebd2c477cb98b9c8cc"]:

		SQLSTATE[HY000]: General error: 1 no such table: oc_authtoken",
		"Code":0,
		"Trace":"
			#0 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
			#1 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT "id", "u...', Array)
			#2 lib/private/DB/Connection.php(184): Doctrine\DBAL\Connection->executeQuery('SELECT "id", "u...', Array, Array, NULL)
			#3 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): OC\DB\Connection->executeQuery('SELECT `id`, `u...', Array, Array)
			#4 lib/private/DB/QueryBuilder/QueryBuilder.php(141): Doctrine\DBAL\Query\QueryBuilder->execute()
			#5 lib/private/Authentication/Token/DefaultTokenMapper.php(77): OC\DB\QueryBuilder\QueryBuilder->execute()
			#6 lib/private/Authentication/Token/DefaultTokenProvider.php(112): OC\Authentication\Token\DefaultTokenMapper->getToken('900f5a05ce3f9bf...')
			#7 lib/private/User/Session.php(220): OC\Authentication\Token\DefaultTokenProvider->getToken('kkj8obcdoe3tsv3...')
			#8 lib/private/User/Session.php(208): OC\User\Session->validateSession(Object(OC\User\User))
			#9 lib/private/L10N/Factory.php(131): OC\User\Session->getUser()
			#10 lib/private/L10N/Factory.php(99): OC\L10N\Factory->findLanguage('core')
			#11 lib/private/Server.php(899): OC\L10N\Factory->get('core', NULL)
			#12 lib/private/Server.php(123): OC\Server->getL10N('core')
			#13 3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
			#14 lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('EncryptionManag...')
			#15 lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('EncryptionManag...')
			#16 lib/private/Server.php(685): OC\ServerContainer->query('EncryptionManag...')
			#17 lib/base.php(726): OC\Server->getEncryptionManager()
			#18 lib/base.php(645): OC::registerEncryptionWrapper()
			#19 lib/base.php(947): OC::init()
			#20 index.php(37): require_once('/Users/morrisjo...')
			#21 {main}",
		"File":"3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php",
		"Line":58

	},
	"level":3,
	"time":"2016-05-17T12:15:53+00:00",
	"method":"GET",
	"url":"/master/",
	"user":"mjob"
}
```

@ChristophWurst I guess this is because the user is checked before the upgrade check happened.

**Comment by ChristophWurst** [comment]
@MorrisJobke known bug, please test https://github.com/owncloud/core/pull/24597.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/owncloud/core/issues/24592?

**Comment by MorrisJobke** [comment]
> Duplicate of #24592?

Indeed.

> @MorrisJobke known bug, please test #24597.

Works with this 🙌
