### ISSUE TITLE
NotFoundException thrown randomly

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#24678]
### Steps to reproduce
No idea, happens unexpectedly if I leave the browser tab open in the background, but not sure if that's the real cause :confused: 

### Expected behaviour
No error

### Actual behaviour
``NotFoundException`` is thrown

```

Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

Technical details

    Remote Address: ::1
    Request ID: K6hH7GwRbkkQ4SARvYIU
    Type: OCP\Files\NotFoundException
    Code: 0
    Message:
    File: /home/christoph/workspace/owncloud/lib/private/legacy/helper.php
    Line: 574


Trace

#0 /home/christoph/workspace/owncloud/apps/files/lib/Controller/ViewController.php(134): OC_Helper::getStorageInfo('/', false)
#1 /home/christoph/workspace/owncloud/apps/files/lib/Controller/ViewController.php(201): OCA\Files\Controller\ViewController->getStorageInfo()
#2 [internal function]: OCA\Files\Controller\ViewController->index('', '', NULL)
#3 /home/christoph/workspace/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
#4 /home/christoph/workspace/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files\Controller\ViewController), 'index')
#5 /home/christoph/workspace/owncloud/lib/private/AppFramework/App.php(110): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
#6 /home/christoph/workspace/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(45): OC\AppFramework\App::main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#7 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#8 /home/christoph/workspace/owncloud/lib/private/Route/Router.php(280): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#9 /home/christoph/workspace/owncloud/lib/base.php(874): OC\Route\Router->match('/apps/files/')
#10 /home/christoph/workspace/owncloud/index.php(39): OC::handleRequest()
#11 {main}
```

### Server configuration
**Operating system**:
Arch linux

**Web server:**
PHP built-in

**Database:**
sqlite

**PHP version:**
7.0.6

**ownCloud version:** (see ownCloud admin page)
current master

I have seen this exception 2 to 3 times since working on #24189, hence I suspect it's caused by the auth refactoring.

**Comment by PVince81** [comment]
This `OC_Helper::getStorageInfo('/', false)` is triggered by the periodic ajax call "getstoragestats.php" for the current folder. It updates the free space info, etc. (we should kill this at some point though).

I suspect that maybe your session was not available any more or for some reason the home storage was not available when it pinged the server. The latter is more mysterious and weird.

**Comment by nickvergessen** [comment]
I have this after running some unit tests

**Comment by PVince81** [comment]
Cannot reproduce, also this is old
