### ISSUE TITLE
directly log exception attributes as json members

### ISSUE THREAD

**Issue by butonic** [owncloud/core#24736]
``` json
{"reqId":"BZf2vsoB+quhM32oZuhd","remoteAddr":"172.16.12.66","app":"files","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(123): OCA\\\\windows_network_drive\\\\lib\\\\WND->hasUpdated('', 1463689062)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1206): OC\\\\Files\\\\Cache\\\\Watcher->needsUpdate('', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(861): OC\\\\Files\\\\View->getFileInfo('\\\/personalwnd', true)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/list.php(34): OC\\\\Files\\\\Filesystem::getFileInfo('\\\/personalwnd')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 [internal function]: __lambda_func(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func('?lambda_1142', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(853): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/windows_network_drive\\\/lib\\\/wnd.php\",\"Line\":618}","level":3,"time":"2016-05-19T20:26:21+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/list.php?dir=%2Fpersonalwnd&sort=name&sortdirection=asc"}
```

the message member contains the exception details as a plain string. we should extract them and store them as members of the log row. `code`, `Exception`, `Trace` could be extracted without problem. `Message` could be pulled up and replace tho old message.

Other exceptions may have other attributes, which could overwrite our own log members, so we should prefix our normal log row members with an underscore.

cc @MTRichards this would greatly enhance compatability with tools like splunk and elk.

**Comment by PVince81** [comment]
I guess this should be fine and I agree with the usefulness. Will this break with existing parsers that people might have been using, for example people who use fail2ban ? I guess it shouldn't as it would just have an additional json attribute that could be ignored by old parsers.

**Comment by PVince81** [comment]
I have an old PR here about this... https://github.com/owncloud/core/pull/26676
