### ISSUE TITLE
Internal Server Error and cannot execute OCC command no more

### ISSUE THREAD

**Issue by spacken** [owncloud/core#24780]
I tried to open Activities App and got an Error. That failed with an error. So i tried to disable the app. That didn't really work. Shortly after I get the following error:

"Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log."

When I now try to execute "php occ" as www-data user I get the following error:

An unhandled exception has been thrown:
exception 'OCP\AutoloadNotAllowedException' with message 'Autoload path not allowed: /var/www/owncloud/apps/activity/appinfo/application.php' in /var/www/owncloud/lib/autoloader.php:152
Stack trace:
#0 /var/www/owncloud/lib/autoloader.php(172): OC\Autoloader->isValidPath('/var/www/ownclo...')
#1 [internal function]: OC\Autoloader->load('OCA\\Activity\\Ap...')
#2 /var/www/owncloud/apps/activitydefaults/appinfo/application.php(45): spl_autoload_call('OCA\\Activity\\Ap...')
#3 /var/www/owncloud/apps/activitydefaults/appinfo/app.php(13): OCA\ActivityDefaults\AppInfo\Application->__construct()
#4 /var/www/owncloud/lib/private/app.php(163): require_once('/var/www/ownclo...')
#5 /var/www/owncloud/lib/private/app.php(144): OC_App::requireAppFile('activitydefault...')
#6 /var/www/owncloud/lib/private/app.php(117): OC_App::loadApp('activitydefault...')
#7 /var/www/owncloud/lib/private/console/application.php(95): OC_App::loadApps()
#8 /var/www/owncloud/console.php(83): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')

### Server configuration
**Operating system**:
Debian Jessie
**Web server:**
Apache 2.4
**Database:**
MariaDB 10.0
**PHP version:**
5.6.20
**ownCloud version:** (see ownCloud admin page)
9.0.2
**Updated from an older ownCloud or fresh install:**
9.0.1
**Where did you install ownCloud from:**
Owncloud repos
**Signing status (ownCloud 9.0 and above):**
??
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
cannot login no more

**List of activated apps:**

    Activity
    Collaborative tags
    Comments
    Deleted files
    External storage support
    Federation
    First Run Wizard
    Gallery
    LDAP user and group backend
    Mail Template Editor
    Notifications
    PDF Viewer
    Provisioning API
    Share Files
    Text Editor
    Update notification
    Versions
    Video player
    Documents
    Activity Defaults

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
<?php
$CONFIG = array (
  'instanceid' => 'oc8ve0jq579p',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => '192.168.201.147',
    1 => 'cloud.test.de',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://192.168.201.147',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'owncloudDB',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'logtimezone' => 'Europe/Berlin',
  'log_type' => 'owncloud',
  'log_authfailip' => true,
  'activity_expire_days' => 60,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'ldapIgnoreNamingRules' => false,
  'mail_smtpmode' => 'smtp',
  'appstore.experimental.enabled' => true,
  'mail_from_address' => 'cloud',
  'mail_domain' => 'test.de',
  'mail_smtphost' => '192.168.201.254',
  'mail_smtpport' => '25',
  'theme' => 'test',
  'loglevel' => 1,
  'asset-pipeline.enabled' => true,
  'maintenance' => false,
  'updatechecker' => false,
);


**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder
cannot execute occ no more get an error
Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 8.1
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
{"reqId":"V0L64n8AAQEAAAw5zDgAAAAB","remoteAddr":"192.168.201.106","app":"core","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/appinfo\\\/application.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(172): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Activity\\\\\\\\Ap...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activitydefaults\\\/appinfo\\\/application.php(45): spl_autoload_call('OCA\\\\\\\\Activity\\\\\\\\Ap...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activitydefaults\\\/appinfo\\\/routes.php(24): OCA\\\\ActivityDefaults\\\\AppInfo\\\\Application->__construct()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(330): include_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(145): OC\\\\Route\\\\Router->requireRouteFile('\\\/var\\\/www\\\/ownclo...', 'activitydefault...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(310): OC\\\\Route\\\\Router->loadRoutes()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/cachingrouter.php(56): OC\\\\Route\\\\Router->generate('js_config', Array, false)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(66): OC\\\\Route\\\\CachingRouter->generate('js_config', Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(141): OC\\\\URLGenerator->linkToRoute('js_config', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(225): OC\\\\TemplateLayout->__construct('error', '')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(122): OC_Template->fetchPage()\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(352): OC\\\\Template\\\\Base->printPage()\\n#13 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC_Template::printExceptionErrorPage(Object(OCP\\\\AutoloadNotAllowedException))\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":152}","level":3,"time":"2016-05-23T14:43:14+02:00","method":"GET","url":"\/","user":"--"}
{"reqId":"ToqP2ct64S0M+72qf3+a","remoteAddr":"","app":"cron","message":"Autoload path not allowed: \/var\/www\/owncloud\/apps\/activity\/appinfo\/application.php","level":4,"time":"2016-05-23T14:45:01+02:00","method":"--","url":"--","user":"--"}
{"reqId":"V0L7z38AAQEAAAxHUx0AAAAI","remoteAddr":"192.168.201.106","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/appinfo\\\/application.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(172): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Activity\\\\\\\\Ap...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activitydefaults\\\/appinfo\\\/application.php(45): spl_autoload_call('OCA\\\\\\\\Activity\\\\\\\\Ap...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activitydefaults\\\/appinfo\\\/app.php(13): OCA\\\\ActivityDefaults\\\\AppInfo\\\\Application->__construct()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(163): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(144): OC_App::requireAppFile('activitydefault...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('activitydefault...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(878): OC_App::loadApps()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":152}","level":3,"time":"2016-05-23T14:47:11+02:00","method":"GET","url":"\/","user":"--"}
{"reqId":"V0L7z38AAQEAAAxHUx0AAAAI","remoteAddr":"192.168.201.106","app":"core","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/appinfo\\\/application.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(172): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Activity\\\\\\\\Ap...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activitydefaults\\\/appinfo\\\/application.php(45): spl_autoload_call('OCA\\\\\\\\Activity\\\\\\\\Ap...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activitydefaults\\\/appinfo\\\/app.php(13): OCA\\\\ActivityDefaults\\\\AppInfo\\\\Application->__construct()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(163): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(144): OC_App::requireAppFile('activitydefault...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('activitydefault...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(878): OC_App::loadApps()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":152}","level":3,"time":"2016-05-23T14:47:11+02:00","method":"GET","url":"\/","user":"--"}
{"reqId":"V0L7z38AAQEAAAxHUx0AAAAI","remoteAddr":"192.168.201.106","app":"core","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/appinfo\\\/application.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(172): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Activity\\\\\\\\Ap...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activitydefaults\\\/appinfo\\\/application.php(45): spl_autoload_call('OCA\\\\\\\\Activity\\\\\\\\Ap...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activitydefaults\\\/appinfo\\\/routes.php(24): OCA\\\\ActivityDefaults\\\\AppInfo\\\\Application->__construct()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(330): include_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(145): OC\\\\Route\\\\Router->requireRouteFile('\\\/var\\\/www\\\/ownclo...', 'activitydefault...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(310): OC\\\\Route\\\\Router->loadRoutes()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/cachingrouter.php(56): OC\\\\Route\\\\Router->generate('js_config', Array, false)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(66): OC\\\\Route\\\\CachingRouter->generate('js_config', Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(141): OC\\\\URLGenerator->linkToRoute('js_config', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(225): OC\\\\TemplateLayout->__construct('error', '')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(122): OC_Template->fetchPage()\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(352): OC\\\\Template\\\\Base->printPage()\\n#13 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC_Template::printExceptionErrorPage(Object(OCP\\\\AutoloadNotAllowedException))\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":152}","level":3,"time":"2016-05-23T14:47:11+02:00","method":"GET","url":"\/","user":"--"}

Insert your ownCloud log here
[Mon May 23 12:04:00.000492 2016] [mpm_prefork:notice] [pid 1572] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1k configured -- resuming normal operations
[Mon May 23 12:04:00.000520 2016] [core:notice] [pid 1572] AH00094: Command line: '/usr/sbin/apache2'
[Mon May 23 12:07:29.976185 2016] [mpm_prefork:notice] [pid 1572] AH00169: caught SIGTERM, shutting down


#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by spacken** [comment]
The Activity App was disabled. OCC didn't work no more. I manually execute:
`update oc_appconfig set configvalue="yes" WHERE appid="activity" AND configkey="enabled";`
Then everything worked fine again
