### ISSUE TITLE
upgrade to 9.0.2 fails with db error

### ISSUE THREAD

**Issue by michiwend** [owncloud/core#24859]
### Steps to reproduce
1. set oc into maintenance mode
2. backup old dir (data dir is separate)
3. download and unpack official oc  9.0.2 tarball into install location, chown recursive
4. restore old config.php
5. restore old apps
6. run oc upgrade with `sudo -u www-data ./occ upgrade`
### Expected behaviour

upgrade process runs all the way through
### Actual behaviour

upgrade process aborts with db errors
### Server configuration

**Operating system**: Ubuntu 14.04.4 LTS
**Web server:** nginx 1.4.6
**Database:** PostgreSQL 9.3.12
**PHP version:** PHP 5.5.9-1ubuntu4.16 (fpm-fcgi) (built: Apr 20 2016 14:34:31)
**ownCloud version:** 9.0.2
**Updated from an older ownCloud or fresh install:** upgrade
**Where did you install ownCloud from:** tarball from official download page

**List of activated apps:**

```
Enabled:
  - dav: true
  - federatedfilesharing: true
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - systemtags: 0.2
  - templateeditor: 0.1
Disabled:
  - activity
  - calendar
  - comments
  - contacts
  - encryption
  - external
  - federation
  - files_encryption
  - files_external
  - files_locking
  - files_pdfviewer
  - files_videoviewer
  - mail
  - music
  - news
  - notifications
  - provisioning_api
  - updatenotification
  - updater
  - user_external
  - user_ldap
  - user_webdavauth
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc82005183ba",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.michiwend.com",
            "cloud.kamaji.org"
        ],
        "datadirectory": "\/home\/owncloud\/",
        "overwrite.cli.url": "https:\/\/cloud.michiwend.com",
        "dbtype": "pgsql",
        "version": "8.2.3.2",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "noreply",
        "mail_smtpmode": "php",
        "mail_domain": "cloud.michiwend.com",
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
#### ownCloud log (stdout)

```
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_appconfig" ("appid","configkey","configvalue") SELECT ?,?,? FROM "oc_appconfig" WHERE "appid" = ? AND "configkey" = ? HAVING COUNT(*) = 0' with params ["provisioning_api", "installed_version", "0.4.1", "provisioning_api", "installed_version"]:

SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
Update failed
Maintenance mode is kept active
Reset log level
```

**Comment by skriems** [comment]
Went into problems upgrading to oc9 weeks ago and ran into problems with SQL exceptions. Unfortunately I get the same exception as stated by @michiwend. As recommended I updated to the recent 8.2.5 first which worked flawlessly. I disabled every unneeded app but still no luck.

**Steps to reproduce**
after backup:
- stop and remove oc container
- delete all apps in /var/www/html/{{ oc directory }}/apps/ to be clean prior starting oc9 container
- start oc9 container
- `docker exec -it {{ oc container name }} bash`
- `apt-get update  && apt-get upgrade -y && apt-get install sudo`
- `sudo -u www-data php occ upgrade`

**Server configuration**

Operating system: Debian 8 Kernel 3.16.7
Web server: [nginx 1.9.11](https://hub.docker.com/_/nginx) proxy to [owncloud/9-apache](https://hub.docker.com/_/owncloud)
Database: PostgreSQL 9.4 installed on localhost
PHP version: PHP 5.6.21 (cli) (built: May  4 2016 03:57:52) shipped in oc docker image
ownCloud version: docker: [owncloud/9-apache](https://hub.docker.com/_/owncloud)
Updated from an older ownCloud or fresh install: upgrade from 8.2.5
Where did you install ownCloud from: docker. see ansible roles regarding [owncloud](https://github.com/skriems/ansible-debian8/blob/master/roles/owncloud/tasks/owncloud.yml) and [nginx](https://github.com/skriems/ansible-debian8/blob/master/roles/docker/tasks/nginx-proxy.yml)

**Enabled Apps**:
  - activity: 2.2.1
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - templateeditor: 0.1

**Comment by PVince81** [comment]
@VicDeo @nickvergessen

**Comment by nickvergessen** [comment]
Seems like it happens when enabling one of the new default apps.

**Comment by skriems** [comment]
@VicDeo,@nickvergessen: I don't know if it matters and if michiwend did the same but I migrated from mysql some versions ago...

**Comment by mrijke** [comment]
I'm also experiencing this issue, upgrading 8.2.6 to 9.0.3. The exception message is a bit different though:

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_appconfig" ("appid","configkey","configvalue") SELECT ?,?,? FROM "oc_appconfig" WHERE "appid" = ? AND "configkey" = ? HAVING COUNT(*) = 0' with params ["templateeditor", "installed_version", "0.1", "templateeditor", "installed_version"]:

SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
Update failed
```

Let me know if you need any further information or how I can help debug this issue.

**Comment by DeepDiver1975** [comment]
From my understanding this falls into the area of runtime exception which can happen under certain circumstances. Please try to rerun the upgrade and let us know if this works out.

**Comment by DeepDiver1975** [comment]
please reopen if this is not "going away" :wink: THX

**Comment by skriems** [comment]
Hey. Unfortunately it's still not working for me and I cannot seem to upgrade to any OCv9.

`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_appconfig" ("appid","configkey","configvalue") SELECT ?,?,? FROM "oc_appconfig" WHERE "appid" = ? AND "configkey" = ? HAVING COUNT(*) = 0' with params ["comments", "installed_version", "0.2", "comments", "installed_version"]:`

Steps that I took:

```
docker exec -it <name> /bin/bash
sudo -u www-data php occ maintenance:mode --on
(for no reason I invoked the upgrade cmd. It disabled all my 3rdParty Apps)
docker stop <name>
docker pull <oc9>
docker run ...
docker exec -it <name> /bin/bash
installed sudo and invoked the upgrade
```
The host is a debian system with Postgres 9.4.

**Comment by skriems** [comment]
the complete log message:
```
{"reqId":"xAeDyXcC59mV6O643zAY","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Doctrine \DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'INSERT INTO \\\"oc_appconfig\\\" (\\\"appid\\\",\\\"configkey\\\",\\\"configvalue\\\") SELECT ?,?,? FROM \\\"oc_appconfig\\\" WHERE \\\"appid\\\" = ? AND \\\"configkey\\\" = ? HAVING COUNT(*) = 0' with params [\\\"comments\\\", \\\"installed_version\\\", \\\"0.2\\\", \\\"comments\\\", \\\"installed_version\\\"]:\\n\\nSQLSTATE[25P02]: In failed sql transaction: 7 FEHLER:  aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO \\\"oc...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/db\\\/connection.php(205): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO \\\"oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/db\\\/adapter.php(93): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/db\\\/connection.php(243): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*appconf...', Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/appconfig.php(158): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*appconf...', Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/allconfig.php(162): OC\\\\AppConfig->setValue('comments', 'installed_versi...', '0.2')\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/installer.php(600): OC\\\\AllConfig->setAppValue('comments', 'installed_versi...', '0.2')\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/installer.php(556): OC_Installer::installShippedApp('comments')\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/updater.php(334): OC_Installer::installShippedApps(true)\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/updater.php(212): OC\\\\Updater->doUpgrade('9.0.3.2', '8.2.6.2')\\n#11 \\\/var\\\/www\\\/html\\\/core\\\/command\\\/upgrade.php(246): OC\\\\Updater->upgrade()\\n#12 \\\/var\\\/www\\\/html\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/html\\\/core\\\/command\\\/base.php(158): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#14 \\\/var\\\/www\\\/html\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): OC\\\\Core\\\\Command\\\\Base->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#15 \\\/var\\\/www\\\/html\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#16 \\\/var\\\/www\\\/html\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#17 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#18 \\\/var\\\/www\\\/html\\\/console.php(88): OC\\\\Console\\\\Application->run()\\n#19 \\\/var\\\/www\\\/html\\\/occ(11): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":91}","level":3,"time":"2016-07-26T07:55:51+00:00","method":"--","url":"--","user":"--"}
```

**Comment by doctorlard** [comment]
Not "going away" for me.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
