### ISSUE TITLE
APCu module not correctly loaded (RHEL 7.1 with PHP 5.5)

### ISSUE THREAD

**Issue by pako81** [owncloud/core#24874]
### Steps to reproduce
1. Upgrading PHP version from 5.4 to 5.5 in RHEL 7.1 as indicated at: https://doc.owncloud.com/server/9.0/admin_manual/installation/php_55_installation.html?highlight=php54 
2. Installing APCu by running `yum install php-pecl-apcu` and set the following in config.php: `'memcache.local' => '\OC\Memcache\APCu',`
3. Be sure to have `extension = apcu.so` in /etc/php.d/apcu.ini and `apc.enable_cli = 1` in /opt/rh/php55/root/etc/php.ini

### Expected behaviour
The APCu module should be loaded and oC should be accessible

### Actual behaviour
No APCu module loaded (see below) and oC not available:

![screenshot from 2016-05-27 14 33 27](https://cloud.githubusercontent.com/assets/12248713/15608216/b95c54e4-2418-11e6-9bce-a2128fc70548.png)

![screenshot from 2016-05-27 14 40 18](https://cloud.githubusercontent.com/assets/12248713/15608248/f5c1a312-2418-11e6-8b8a-a5da624e537d.png)

### Server configuration
**Operating system**:

RHEL 7.1

**Web server:**

Apache 2.4.6

**Database:**

MariaDB 5.5

**PHP version:**

5.5.21

**ownCloud version:** (see ownCloud admin page)

8.2.2

**Updated from an older ownCloud or fresh install:**

Fresh install

#### ownCloud log (data/owncloud.log)
```
{"reqId":"V0g0xtUFhMGrVzTek-RRTQAAAAM","remoteAddr":"::1","app":"core","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Memcache \\\\OC\\\\Memcache\\\\APCu not available for local cache\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(268): OC\\\\Memcache\\\\Factory->__construct('bf869b56fe76be4...', Object(OC\\\\Log), '\\\\\\\\OC\\\\\\\\Memcache\\\\\\\\AP...', NULL, NULL)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(104): Pimple\\\\Container->offsetGet('MemCacheFactory')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(754): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('MemCacheFactory')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(242): OC\\\\Server->getMemCacheFactory()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(104): Pimple\\\\Container->offsetGet('URLGenerator')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(727): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('URLGenerator')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/helper.php(174): OC\\\\Server->getURLGenerator()\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/functions.php(169): OC_Helper::imagePath('', 'favicon.png')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/templates\\\/layout.guest.php(15): image_path('', 'favicon.png')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(160): include('\\\/var\\\/www\\\/html\\\/o...')\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(138): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/html\\\/o...')\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(211): OC\\\\Template\\\\Base->fetchPage()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(233): OC_Template->fetchPage()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(121): OC_Template->fetchPage()\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(308): OC\\\\Template\\\\Base->printPage()\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(49): OC_Template::printErrorPage('Memcache \\\\\\\\OC\\\\\\\\Me...', 'Is the matching...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/factory.php\",\"Line\":94}","level":3,"time":"2016-05-27T11:51:34+00:00","method":"GET","url":"\/owncloud\/"}
{"reqId":"V0g36E8o6dW1wIqPMji-dwAAAAQ","remoteAddr":"::1","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-05-27T12:04:57+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"V0g4KoTwFvepTZilDBmpTAAAAAg","remoteAddr":"::1","app":"sharing_log","message":"User 'pastripodi' removed the share link for their folder (\/Documents) [CLIENT_IP: ::1]","level":1,"time":"2016-05-27T12:06:02+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/share.php"}
{"reqId":"V0g4K4TwFvepTZilDBmpTgAAAAg","remoteAddr":"::1","app":"sharing_log","message":"User pastripodi shared \"\/Documents\" with a public link, token=D35FT2BZKWC7Nha, without password, permissions: READ [CLIENT_IP: ::1]","level":1,"time":"2016-05-27T12:06:03+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/share.php"}
{"reqId":"V0g4TJ5pfWd3t0CXd-5YBgAAAAY","remoteAddr":"::1","app":"sharing_log","message":"User pastripodi shared \"\/Documents\" with a public link, token=D35FT2BZKWC7Nha, without password, permissions: READ UPDATE CREATE [CLIENT_IP: ::1]","level":1,"time":"2016-05-27T12:06:36+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/share.php"}
{"reqId":"V0g4UJ5pfWd3t0CXd-5YCAAAAAY","remoteAddr":"::1","app":"sharing_log","message":"User pastripodi shared \"\/Documents\" with a public link, token=D35FT2BZKWC7Nha, without password, permissions: READ [CLIENT_IP: ::1]","level":1,"time":"2016-05-27T12:06:40+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/share.php"}
{"reqId":"V0g4WNfnepW@zrwqIaZhDgAAAAQ","remoteAddr":"::1","app":"sharing_log","message":"User pastripodi shared \"\/Documents\" with a public link, token=D35FT2BZKWC7Nha, without password, permissions: READ UPDATE CREATE [CLIENT_IP: ::1]","level":1,"time":"2016-05-27T12:06:48+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/share.php"}
{"reqId":"V0g@1ZJhw4PwYpq-y-Lh7wAAAAs","remoteAddr":"::1","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-05-27T12:34:30+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"V0hAGwlxEwHVGARiGb6p8gAAAAQ","remoteAddr":"::1","app":"core","message":"Memcache \\OC\\Memcache\\APCu not available for local cache Is the matching PHP module installed and enabled?","level":3,"time":"2016-05-27T12:39:55+00:00","method":"GET","url":"\/owncloud\/"}
{"reqId":"V0hAGwlxEwHVGARiGb6p8gAAAAQ","remoteAddr":"::1","app":"core","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Memcache \\\\OC\\\\Memcache\\\\APCu not available for local cache\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(268): OC\\\\Memcache\\\\Factory->__construct('b51bee6357b89f4...', Object(OC\\\\Log), '\\\\\\\\OC\\\\\\\\Memcache\\\\\\\\AP...', NULL, NULL)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(104): Pimple\\\\Container->offsetGet('MemCacheFactory')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(754): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('MemCacheFactory')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(242): OC\\\\Server->getMemCacheFactory()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(104): Pimple\\\\Container->offsetGet('URLGenerator')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(727): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('URLGenerator')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/helper.php(174): OC\\\\Server->getURLGenerator()\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/functions.php(169): OC_Helper::imagePath('', 'favicon.png')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/templates\\\/layout.guest.php(15): image_path('', 'favicon.png')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(160): include('\\\/var\\\/www\\\/html\\\/o...')\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(138): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/html\\\/o...')\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(211): OC\\\\Template\\\\Base->fetchPage()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(233): OC_Template->fetchPage()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(121): OC_Template->fetchPage()\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(308): OC\\\\Template\\\\Base->printPage()\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(49): OC_Template::printErrorPage('Memcache \\\\\\\\OC\\\\\\\\Me...', 'Is the matching...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/factory.php\",\"Line\":94}","level":3,"time":"2016-05-27T12:39:55+00:00","method":"GET","url":"\/owncloud\/"}
```
Am I missing something ?

**Comment by RealRancor** [comment]
@pako81 If the APCu module is not correctly loaded in your phpinfo there is very likely nothing what can be done from oC side here.

**Comment by pako81** [comment]
@RealRancor thanks. I don't think it is a documentation issue however I suppose it most likely has to do with the PHP upgrade. Only, I don't see what could be the isue here as everything seems to be ok..

**Comment by DeepDiver1975** [comment]
> Be sure to have extension = apcu.so in /etc/php.d/apcu.ini

according to the phpinfo screenshot above this is the wrong location I'd say.
Should be /opt/rh/php55/root/etc/php.d ???

Anyway - system configuration issue -> close
