### ISSUE TITLE
Duplicate entry for key lock_key_index - UniqueConstraintViolationException

### ISSUE THREAD

**Issue by morno** [owncloud/core#24882]
### Steps to reproduce
1. upload file to server useing owncloud 2.2 (latest ver)
2.
3.

### Expected behaviour
Tell us what should happen
no errors i guess
### Actual behaviour
Tell us what happens instead
Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/2785cb66aceaa9e1be56502c759c2ed0\", 1, 1464466398, \"files\\\/2785cb66aceaa9e1be56502c759c2ed0\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\/2785cb66aceaa9e1be56502c759c2ed0' for key 'lock_key_index'","Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/html\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/var\/www\/html\/owncloud\/lib\/private\/db\/connection.php(205): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/var\/www\/html\/owncloud\/lib\/private\/db\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array)\n#4 \/var\/www\/html\/owncloud\/lib\/private\/db\/connection.php(243): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#5 \/var\/www\/html\/owncloud\/lib\/private\/lock\/dblockingprovider.php(113): OC\\DB\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#6 \/var\/www\/html\/owncloud\/lib\/private\/lock\/dblockingprovider.php(158): OC\\Lock\\DBLockingProvider->initLockField('files\/2785cb66a...', 1)\n#7 \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/common.php(663): OC\\Lock\\DBLockingProvider->acquireLock('files\/2785cb66a...', 1)\n#8 \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(577): OC\\Files\\Storage\\Common->acquireLock('files\/InstantUp...', 1, Object(OC\\Lock\\DBLockingProvider))\n#9 \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(577): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/InstantUp...', 1, Object(OC\\Lock\\DBLockingProvider))\n#10 \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php(1854): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/InstantUp...', 1, Object(OC\\Lock\\DBLockingProvider))\n#11 \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php(1960): OC\\Files\\View->lockPath('\/InstantUpload', 1)\n#12 \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php(1049): OC\\Files\\View->lockFile('\/InstantUpload\/...', 1)\n#13 \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php(909): OC\\Files\\View->basicOperation('fopen', 'InstantUpload\/P...', Array, 'rb')\n#14 \/var\/www\/html\/owncloud\/apps\/dav\/lib\/connector\/sabre\/file.php(304): OC\\Files\\View->fopen('InstantUpload\/P...', 'rb')\n#15 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(83): OCA\\DAV\\Connector\\Sabre\\File->get()\n#16 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#17 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#18 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#19 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#20 \/var\/www\/html\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#21 \/var\/www\/html\/owncloud\/remote.php(138): require_once('\/var\/www\/html\/o...')\n#22 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66,"User":"tobias"} 
### Server configuration
**Operating system**:
win10
**Web server:**
apache2
**Database:**
mysql
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
9.0.2
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
ur website
**Signing status (ownCloud 9.0 and above):**
donno
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by morno** [comment]
get this error too 

Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/2785cb66aceaa9e1be56502c759c2ed0\", 1, 1464466398, \"files\\\/2785cb66aceaa9e1be56502c759c2ed0\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\/2785cb66aceaa9e1be56502c759c2ed0' for key 'lock_key_index'","Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/html\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/var\/www\/html\/owncloud\/lib\/private\/db\/connection.php(205): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/var\/www\/html\/owncloud\/lib\/private\/db\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array)\n#4 \/var\/www\/html\/owncloud\/lib\/private\/db\/connection.php(243): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#5 \/var\/www\/html\/owncloud\/lib\/private\/lock\/dblockingprovider.php(113): OC\\DB\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#6 \/var\/www\/html\/owncloud\/lib\/private\/lock\/dblockingprovider.php(158): OC\\Lock\\DBLockingProvider->initLockField('files\/2785cb66a...', 1)\n#7 \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/common.php(663): OC\\Lock\\DBLockingProvider->acquireLock('files\/2785cb66a...', 1)\n#8 \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(577): OC\\Files\\Storage\\Common->acquireLock('files\/InstantUp...', 1, Object(OC\\Lock\\DBLockingProvider))\n#9 \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(577): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/InstantUp...', 1, Object(OC\\Lock\\DBLockingProvider))\n#10 \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php(1854): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/InstantUp...', 1, Object(OC\\Lock\\DBLockingProvider))\n#11 \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php(1960): OC\\Files\\View->lockPath('\/InstantUpload', 1)\n#12 \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php(1049): OC\\Files\\View->lockFile('\/InstantUpload\/...', 1)\n#13 \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php(909): OC\\Files\\View->basicOperation('fopen', 'InstantUpload\/P...', Array, 'rb')\n#14 \/var\/www\/html\/owncloud\/apps\/dav\/lib\/connector\/sabre\/file.php(304): OC\\Files\\View->fopen('InstantUpload\/P...', 'rb')\n#15 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(83): OCA\\DAV\\Connector\\Sabre\\File->get()\n#16 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#17 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#18 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#19 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#20 \/var\/www\/html\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#21 \/var\/www\/html\/owncloud\/remote.php(138): require_once('\/var\/www\/html\/o...')\n#22 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66,"User":"tobias"} 

anyone with more brain then me please help :P

**Comment by nickvergessen** [comment]
Seems like your transaction isolation level is not `READ COMMITED` 
Please run the following Query to verify:
```sql
SELECT @@GLOBAL.tx_isolation, @@tx_isolation
```

As per our  [docs](https://doc.owncloud.org/server/8.2/admin_manual/configuration_database/linux_database_configuration.html#mysql-mariadb-with-binary-logging-enabled) we need READ_COMMITED

**Comment by nickvergessen** [comment]
@PVince81 as discussed, added a warning in the admin UI https://github.com/owncloud/core/pull/24889

**Comment by PVince81** [comment]
Closing due to lack of feedback.

@morno please check https://github.com/owncloud/core/issues/24882#issuecomment-222456110

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
