### ISSUE TITLE
ownCloud server upgrade throws uncaught exception when database is upgraded too

### ISSUE THREAD

**Issue by knutschneider** [owncloud/core#24928]
### Steps to reproduce
1. Install old version of ownCloud from https://download.owncloud.org/download/repositories/stable/owncloud/
2. Install an old version of a DBMS, e.g. mariadb
3. apt-get update && apt-get upgrade now should upgrade both the DBMS and ownCloud
### Expected behaviour
- No error should happen on system upgrade (apt-get upgrade)
### Actual behaviour
- The following error occurs when upgrading, though nothing breaks ownCloud -> error can be ignored, but should still be caught and not displayed

```
Preparing to unpack .../mariadb-server-core-5.5_5.5.49-1ubuntu0.14.04.1_armhf.deb ...
Unpacking mariadb-server-core-5.5 (5.5.49-1ubuntu0.14.04.1) over (5.5.47-1ubuntu0.14.04.1) ...
Preparing to unpack .../mariadb-server_5.5.49-1ubuntu0.14.04.1_all.deb ...
Unpacking mariadb-server (5.5.49-1ubuntu0.14.04.1) over (5.5.47-1ubuntu0.14.04.1) ...

...
Preparing to unpack .../owncloud-server_9.0.2-1.deb ...
occ maintenance:mode --on
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused' in /usr/lib/owncloud/www/lib/private/db/connection.php:52
Stack trace:
#0 /usr/lib/owncloud/www/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /usr/lib/owncloud/www/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /usr/lib/owncloud/www/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /usr/lib/owncloud/www/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /usr/lib/owncloud/www/lib/private/db/connection.php(135): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /usr/lib/owncloud/www/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /usr/lib/owncloud/www/lib/private/db/connectionfactory.php(118): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /usr/lib/owncloud/www/lib/private/server.php(328): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /usr/lib/owncloud/www/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#9 /usr/lib/owncloud/www/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /usr/lib/owncloud/www/lib/private/server.php(763): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /usr/lib/owncloud/www/lib/private/db.php(42): OC\Server->getDatabaseConnection()
#12 /usr/lib/owncloud/www/lib/private/server.php(235): OC_DB::getConnection()
#13 /usr/lib/owncloud/www/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#14 /usr/lib/owncloud/www/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('AppConfig')
#15 /usr/lib/owncloud/www/lib/private/server.php(702): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /usr/lib/owncloud/www/lib/private/server.php(373): OC\Server->getAppConfig()
#17 /usr/lib/owncloud/www/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#18 /usr/lib/owncloud/www/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('AppManager')
#19 /usr/lib/owncloud/www/lib/private/server.php(929): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#20 /usr/lib/owncloud/www/lib/private/app.php(259): OC\Server->getAppManager()
#21 /usr/lib/owncloud/www/lib/private/app.php(104): OC_App::getEnabledApps()
#22 /usr/lib/owncloud/www/lib/base.php(566): OC_App::loadApps(Array)
#23 /usr/lib/owncloud/www/lib/base.php(1081): OC::init()
...
```

While it was upgrading `mysql -u owncloud -p` returned:

```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

So the database server was not running. OC somehow has to handle this

**Comment by PVince81** [comment]
@jnweiger

**Comment by RealRancor** [comment]
@PVince81 i doubt that this is a packaging issue. @knutschneider probably want to say that oC itself should catch this exception.

**Comment by PVince81** [comment]
If ownCloud hides these errors then how would an admin find out about connection errors in case of a manual upgrade ? Hiding the error only during a package upgrade would require the package to pass an additional option to tell ownCloud that it's in that mode. It doesn't feel like there is much benefit to this.

The part I'm wondering about is whether there is a way to influence the update order to avoid this issue to happen in the first place.

**Comment by crrodriguez** [comment]
The update order is unspecified and varies across distribution versions, package manager, etc..nothing can be done about that.
