### ISSUE TITLE
Feature Request: ownCloud logfile - line breakes

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#24984]
This is a feature request, hopefully not a stupid one...

For better readability when filing issues, I do linebrakes in the logs manually before n#x.
Because this is a lot of work, I have two questions:

- There are upcounting numbers starting with #0 but at the second number it starts with n#1 ect. Is it possible to have the numbering starting with n always ?
- Would it be possible by ownCloud to do the linebreakes before n#x automatically.

Here are example log entries:

**Before:**
```
Error while running background job (class: OC\Command\CommandJob, arguments: O:33:"OCA\Files_Versions\Command\Expire":2:{s:43:"OCA\Files_Versions\Command\ExpirefileName";s:211:"/a_file";s:39:"OCA\Files_Versions\Command\Expireuser";s:8:"a_user";}): {"Exception":"OC\\User\\NoUserException","Message":"Attempted to initialize mount points for null user and no user in session","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php(102): OC\\Files\\Filesystem::initMountPoints(false)\n#1 \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php(682): OCA\\Files_Versions\\Storage::getUidAndFilename('\/a_file')\n#2 \/var\/www\/owncloud\/apps\/files_versions\/command\/expire.php(61): OCA\\Files_Versions\\Storage::expire('\/a_file')\n#3 \/var\/www\/owncloud\/lib\/private\/command\/commandjob.php(34): OCA\\Files_Versions\\Command\\Expire->handle()\n#4 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OC\\Command\\CommandJob->run('O:33:\"OCA\\Files...')\n#5 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/queuedjob.php(42): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#6 \/var\/www\/owncloud\/cron.php(171): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#7 {main}","File":"\/var\/www\/owncloud\/lib\/private\/files\/filesystem.php","Line":376}
```
**After:**
```
Error while running background job (class: OC\Command\CommandJob, arguments: O:33:"OCA\Files_Versions\Command\Expire":2:{s:43:"OCA\Files_Versions\Command\ExpirefileName";s:211:"/a_file";s:39:"OCA\Files_Versions\Command\Expireuser";s:8:"a_user";}): {"Exception":"OC\\User\\NoUserException","Message":"Attempted to initialize mount points for null user and no user in session","Code":0,"Trace":"
#0 \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php(102): OC\\Files\\Filesystem::initMountPoints(false)\
n#1 \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php(682): OCA\\Files_Versions\\Storage::getUidAndFilename('\/a_file')\
n#2 \/var\/www\/owncloud\/apps\/files_versions\/command\/expire.php(61): OCA\\Files_Versions\\Storage::expire('\/a_file')\
n#3 \/var\/www\/owncloud\/lib\/private\/command\/commandjob.php(34): OCA\\Files_Versions\\Command\\Expire->handle()\
n#4 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OC\\Command\\CommandJob->run('O:33:\"OCA\\Files...')\
n#5 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/queuedjob.php(42): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\
n#6 \/var\/www\/owncloud\/cron.php(171): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\
n#7 {main}","File":"\/var\/www\/owncloud\/lib\/private\/files\/filesystem.php","Line":376}
```

**Comment by nickvergessen** [comment]
Well basically logging is "one entry per row". At least we can't do that atm per default, since it breaks well known log readers.
If you want it for personal use, try https://github.com/icewind1991/logreader

I wrote a script that fully converts exception stack traces to a better format:
https://gist.github.com/nickvergessen/3bc6c0c7ada1a3c4a1b1f5ed94cc61f6

**Comment by nickvergessen** [comment]
@DeepDiver1975 close "will not fix"?

**Comment by mmattel** [comment]
thx! will take a look at it, closing is fine to me
