### ISSUE TITLE
Sharing backend for calendar not found

### ISSUE THREAD

**Issue by fluancefg** [owncloud/core#25004]
### Steps to reproduce
1. Create a new (LDAP) user
2. Add the new user to a group. This group must have a access to a calendar shared by another user.
3. Try to login with the new user. He gets a blank page.
4. Remove it from the group, He's able to login normally.
### Expected behaviour

Logged in.
### Actual behaviour

Blank page.
### Server configuration

Debian 7.10

**Web server:**
Nginx 1.11

**Database:**
PostgreSQL 9.3

**PHP version:**
PHP 5.4.45

**ownCloud version:** (see ownCloud admin page)
9.0.2 stable

**Updated from an older ownCloud or fresh install:**
Updated from 9.0, updated from 8.x

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
# Technical information

The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.
# Results
- core
  - EXTRA_FILE
    - contacts/js/public/script.js
      ...
    - calendar/js/public/app.js
      ...
# Raw output

Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [contacts/js/public/script.js] => Array
                        (
                            [expected] => 
                            [current] => 764556922ec7f922bc9d8ebfe5a2f9a6642af84f546b8a8252dae8ce3c2fc529708118d51fdbcfe162af09e5390a00d6dd4c7bfe7827f4db65012790c1c4fd04
                        )
                   ...

```
                [calendar/js/public/app.js] => Array
                    (
                        [expected] => 
                        [current] => bb7eb579ac098911e4dae92df2d46436553e1d8ec977ba3469e48a9be30bdfbf976c2426a43280c3b3b01637f1931c153ff904e9cf348c13e1070b325648f99a
                    )

               ...
                    )

            )

    )
```

)

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Enabled:
- activity: 2.2.1
- calendar: true
- comments: 0.2
- contacts: 1.3.1.0
- dav: 0.1.6
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8.1
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
- user_ldap: 0.8.0
  Disabled:
- encryption
- external
- files_external
- user_external

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

{
    "system": {
        "instanceid": "oc1df352d530",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "cloud.fluance.net"
        ],
        "datadirectory": "\/home\/owncloud\/data",
        "dbtype": "pgsql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "dbhost": "localhost:45432",
        "dbtableprefix": "oc_",
        "installed": true,
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "mail.fluance.net",
        "mail_smtpport": 587,
        "mail_smtpsecure": "tls",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "loglevel": "3",
        "logtimezone": "Europe\/Zurich",
        "theme": "",
        "maintenance": false,
        "share_folder": "\/Shared",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\OC\Memcache\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\OC\Memcache\Redis",
        "log_rotate_size": 104857600,
        "log_rotate_sizerotation": 524288000,
        "remember_login_cookie_lifetime": 432000,
        "session_lifetime": 86400
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

+-------------------------------+-----------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                     |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                   |
| hasPagedResultSupport         |                                                                                                     |
| homeFolderNamingRule          |                                                                                                     |
| lastJpegPhotoLookup           | 0                                                                                                   |
| ldapAgentName                 |                                                                                                     |
| ldapAgentPassword             | **\*                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                     |
| ldapAttributesForUserSearch   |                                                                                                     |
| ldapBackupHost                |                                                                                                     |
| ldapBackupPort                |                                                                                                     |
| ldapBase                      | dc=fluance,dc=net                                                                                   |
| ldapBaseGroups                | ou=people,dc=fluance,dc=net                                                                         |
| ldapBaseUsers                 | ou=people,dc=fluance,dc=net                                                                         |
| ldapCacheTTL                  | 600                                                                                                 |
| ldapConfigurationActive       | 1                                                                                                   |
| ldapDynamicGroupMemberURL     |                                                                                                     |
| ldapEmailAttribute            | mail                                                                                                |
| ldapExperiencedAdmin          | 0                                                                                                   |
| ldapExpertUUIDGroupAttr       |                                                                                                     |
| ldapExpertUUIDUserAttr        |                                                                                                     |
| ldapExpertUsernameAttr        |                                                                                                     |
| ldapGroupDisplayName          | cn                                                                                                  |
| ldapGroupFilter               |                                                                                                     |
| ldapGroupFilterGroups         |                                                                                                     |
| ldapGroupFilterMode           | 0                                                                                                   |
| ldapGroupFilterObjectclass    |                                                                                                     |
| ldapGroupMemberAssocAttr      | member                                                                                              |
| ldapHost                      | localhost                                                                                           |
| ldapIgnoreNamingRules         |                                                                                                     |
| ldapLoginFilter               | (&(&(|(objectclass=inetOrgPerson))(|(memberof=cn=owncloud,ou=people,dc=fluance,dc=net)))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                     |
| ldapLoginFilterEmail          | 0                                                                                                   |
| ldapLoginFilterMode           | 0                                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                                   |
| ldapNestedGroups              | 0                                                                                                   |
| ldapOverrideMainServer        | 0                                                                                                   |
| ldapPagingSize                | 500                                                                                                 |
| ldapPort                      | 389                                                                                                 |
| ldapQuotaAttribute            |                                                                                                     |
| ldapQuotaDefault              |                                                                                                     |
| ldapTLS                       | 0                                                                                                   |
| ldapUserDisplayName           | cn                                                                                                  |
| ldapUserDisplayName2          |                                                                                                     |
| ldapUserFilter                | (&(|(objectclass=inetOrgPerson))(|(memberof=cn=owncloud,ou=people,dc=fluance,dc=net)))              |
| ldapUserFilterGroups          | owncloud                                                                                            |
| ldapUserFilterMode            | 0                                                                                                   |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                       |
| ldapUuidGroupAttribute        | auto                                                                                                |
| ldapUuidUserAttribute         | auto                                                                                                |
| turnOffCertCheck              | 0                                                                                                   |
| useMemberOfToDetectMembership | 0                                                                                                   |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```

Error   OCP\Share   Sharing backend for calendar not found 

 Error  no app in context   Exception: {"Exception":"Exception","Message":"Le service de partage pour calendar est introuvable","Code":0,"Trace":"#0 \/var\/www\/fluance.net\/owncloud\/lib\/private\/share\/helper.php(49): OC\Share\Share::getBackend('calendar')\n#1 \/var\/www\/fluance.net\/owncloud\/lib\/private\/share\/hooks.php(96): OC\Share\Helper::generateTarget('calendar', '3', 0, 'b6f30604-493d-1...', 'fluance', NULL, NULL)\n#2 [internal function]: OC\Share\Hooks::pre_addToGroup(Array)\n#3 \/var\/www\/fluance.net\/owncloud\/lib\/private\/hook.php(105): call_user_func(Array, Array)\n#4 \/var\/www\/fluance.net\/owncloud\/lib\/private\/server.php(194): OC_Hook::emit('OC_Group', 'pre_addToGroup', Array)\n#5 [internal function]: OC\Server->OC\{closure}(Object(OC\Group\Group), Object(OC\User\User))\n#6 \/var\/www\/fluance.net\/owncloud\/lib\/private\/hooks\/emittertrait.php(98): call_user_func_array(Object(Closure), Array)\n#7 \/var\/www\/fluance.net\/owncloud\/lib\/private\/hooks\/publicemitter.php(32): OC\Hooks\BasicEmitter->emit('\\OC\\Group', 'preAddUser', Array)\n#8 \/var\/www\/fluance.net\/owncloud\/lib\/private\/group\/group.php(136): OC\Hooks\PublicEmitter->emit('\\OC\\Group', 'preAddUser', Array)\n#9 \/var\/www\/fluance.net\/owncloud\/lib\/private\/group.php(150): OC\Group\Group->addUser(Object(OC\User\User))\n#10 \/var\/www\/fluance.net\/owncloud\/settings\/ajax\/togglegroups.php(75): OC_Group::addToGroup('b6f30604-493d-1...', 'fluanceit')\n#11 \/var\/www\/fluance.net\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/fluanc...')\n#12 [internal function]: __lambda_func(Array)\n#13 \/var\/www\/fluance.net\/owncloud\/lib\/private\/route\/router.php(276): call_user_func('\x00lambda_1135', Array)\n#14 \/var\/www\/fluance.net\/owncloud\/lib\/base.php(882): OC\Route\Router->match('\/settings\/ajax\/...')\n#15 \/var\/www\/fluance.net\/owncloud\/index.php(39): OC::handleRequest()\n#16 {main}","File":"\/var\/www\/fluance.net\/owncloud\/lib\/private\/share\/share.php","Line":1539} 

Error   PHP     Call to a member function file_exists() on a non-object at /var/www/fluance.net/owncloud/lib/private/files/filesystem.php#696 
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by hodyroff** [comment]
Is this still happening in 9.1.1?

**Comment by fluancefg** [comment]
Unfortunately I had no time to migrate the instance for now, it's still running 9.0.2 stable

**Comment by fluancefg** [comment]
I've migrated to nextcloud 10.0.6 and the issue has disappeared. So this bug can most probably be closed.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
