### ISSUE TITLE
Group rights for new user not applied (encryption enabled)

### ISSUE THREAD

**Issue by retide** [owncloud/core#25015]
<!--
### Steps to reproduce

In an encrypted environment:
1. Share folder of user U1 with group G and place documents in folder
2. Create a new user U2 as member of G
3. As U2, try to open documents (eg. pdf-file) within the shared folder
### Expected behaviour

Documents should open.
### Actual behaviour

Opening documents as user U1 works as expected. U2 can view content of folders, but trying to open any document yields an error. 

When trying to reproduce, unsharing and resharing folder with group fixed the issue, however with large amount of data in folder (x GB) resharing mostly did NOT solve the issue (tried for several folders and un-/resharing several times).

Error message in web-interface when trying to open a pdf-file: PDF.js v1.1.469 (build: f06aa6a)
Message: Unexpected server response (0) while retrieving PDF "https://wine.aix-cloud.de/remote.php/webdav/xTEST/essay.pdf".

Error when using Safari to download file: file is not downloaded ("Parsen der Antwort nicht möglich..." / "parsing response failed")

Error when using sync client: "connection terminated"
### Server configuration

**Operating system**: Linux (hosting provider; access to files on server, but no command line access)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0.7

**ownCloud version:** (see ownCloud admin page) 9.0.1

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** owncloud.org, fileupload via ftp, installation wizard

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Default encryption module 1.2.0
Deleted files 0.8.0
Federation 0.0.4
Gallery 14.5.0
Mail Template Editor 0.1
PDF Viewer 0.8
Provisioning API 0.4.1
Share Files 0.9.1
Text Editor 2.1
Update notification 0.1.0
Versions 1.2.0
Video player 0.9.8
Calendar 1.2.2
Contacts 1.3.1.0
Documents 0.12.0
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ochcpvcbjvcl',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'datadirectory' => '/var/www/vhosts/wine.aix-cloud.de/httpdocs/data',
  'overwrite.cli.url' => 'https://xxx',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'wine',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'wine',
  'dbpassword' => '',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 2,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_from_address' => 'admin',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxx',
);

```

**Are you using external storage, if yes which one:** no(?)

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox or Safari

**Operating system:** OSX 10.11 or Windows 10
#### Web server error log

```

```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"xGdLSg\/KlHh7TXbm7h\/5","remoteAddr":"132.230.xxx.xxx","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_admin\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'wine'@'localhost' for table 'user'","level":3,"time":"2016-06-01T17:07:34+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"xGdLSg\/KlHh7TXbm7h\/5","remoteAddr":"132.230.xxx.xxx","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `wine` . * TO 'wine'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'wine'@'%' to database 'wine'","level":3,"time":"2016-06-01T17:07:34+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"xGdLSg\/KlHh7TXbm7h\/5","remoteAddr":"132.230.xxx.xxx","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/lib\\\/private\\\/installer.php(639): include('\\\/var\\\/www\\\/vhosts...')\\n#4 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/lib\\\/private\\\/installer.php(590): OC_Installer::includeAppScript('\\\/var\\\/www\\\/vhosts...')\\n#5 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/lib\\\/private\\\/installer.php(561): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/lib\\\/base.php(832): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-06-01T17:07:35+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"xGdLSg\/KlHh7TXbm7h\/5","remoteAddr":"132.230.xxx.xxx","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/lib\\\/private\\\/installer.php(639): include('\\\/var\\\/www\\\/vhosts...')\\n#4 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/lib\\\/private\\\/installer.php(590): OC_Installer::includeAppScript('\\\/var\\\/www\\\/vhosts...')\\n#5 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/lib\\\/private\\\/installer.php(561): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/lib\\\/base.php(832): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/vhosts\\\/wine.aix-cloud.de\\\/httpdocs\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-06-01T17:07:35+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"5BULCT544CtVE5sAYvem","remoteAddr":"132.230.xxx.xxx","app":"core","message":"Login failed: 'twi' (Remote IP: '132.230.xxx.xxx')","level":2,"time":"2016-06-01T17:07:35+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Thailand","user":"--"}
{"reqId":"i\/WnZ+DacdDTExMEt01g","remoteAddr":"132.230.xxx.xxx","app":"core","message":"Login failed: 'twi' (Remote IP: '132.230.xxx.xxx')","level":2,"time":"2016-06-01T17:07:36+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/WINE","user":"--"}
{"reqId":"AEh7xJqj0Sh++bFpDuDP","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_cxEfzb): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:07:39+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"AEh7xJqj0Sh++bFpDuDP","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_hzx93r): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:07:39+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"AEh7xJqj0Sh++bFpDuDP","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_3nMjUH): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:07:39+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"AEh7xJqj0Sh++bFpDuDP","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_Pelivd): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:07:39+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"AEh7xJqj0Sh++bFpDuDP","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_cHr008): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:07:39+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"AEh7xJqj0Sh++bFpDuDP","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_3nMjUH-.zip): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:07:39+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"AEh7xJqj0Sh++bFpDuDP","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_9Cf4C6): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:07:39+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"tUb3o4bO55U8KQWNlgZl","remoteAddr":"132.230.xxx.xxx","app":"core","message":"Login failed: 'twi' (Remote IP: '132.230.xxx.xxx')","level":2,"time":"2016-06-01T17:07:45+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"gWU54cxStXwl3KEwZymY","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_cxEfzb): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:08:06+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"gWU54cxStXwl3KEwZymY","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_hzx93r): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:08:06+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"gWU54cxStXwl3KEwZymY","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_3nMjUH): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:08:06+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"gWU54cxStXwl3KEwZymY","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_Pelivd): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:08:06+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"gWU54cxStXwl3KEwZymY","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_cHr008): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:08:06+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"gWU54cxStXwl3KEwZymY","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_3nMjUH-.zip): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:08:06+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"gWU54cxStXwl3KEwZymY","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_9Cf4C6): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:08:06+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"jKueP58rGTIROshOOlHO","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_cxEfzb): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:35+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"jKueP58rGTIROshOOlHO","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_hzx93r): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:35+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"jKueP58rGTIROshOOlHO","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_3nMjUH): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:35+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"jKueP58rGTIROshOOlHO","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_Pelivd): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:35+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"jKueP58rGTIROshOOlHO","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_cHr008): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:35+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"jKueP58rGTIROshOOlHO","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_3nMjUH-.zip): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:35+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"jKueP58rGTIROshOOlHO","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_9Cf4C6): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:35+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"bFWmTrQ\/FOBw5fWgSB8g","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_cxEfzb): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:53+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"bFWmTrQ\/FOBw5fWgSB8g","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_hzx93r): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:53+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"bFWmTrQ\/FOBw5fWgSB8g","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_3nMjUH): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:53+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"bFWmTrQ\/FOBw5fWgSB8g","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_Pelivd): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:53+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"bFWmTrQ\/FOBw5fWgSB8g","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_cHr008): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:53+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"bFWmTrQ\/FOBw5fWgSB8g","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_3nMjUH-.zip): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:53+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"bFWmTrQ\/FOBw5fWgSB8g","remoteAddr":"132.230.xxx.xxx","app":"PHP","message":"unlink(\/tmp\/oc_tmp_9Cf4C6): Operation not permitted at \/var\/www\/vhosts\/wine.aix-cloud.de\/httpdocs\/lib\/private\/helper.php#235","level":3,"time":"2016-06-01T17:10:53+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"alLljnZwT8GFMIq4Ducc","remoteAddr":"132.230.xxx.xxx","app":"core","message":"Login failed: 'twi' (Remote IP: '132.230.xxx.xxx')","level":2,"time":"2016-06-01T17:13:48+00:00","method":"OPTIONS","url":"\/remote.php\/dav\/principals\/users\/twi\/","user":"--"}
```

**Comment by retide** [comment]
Probably same issue as #23432, still persistent in 9.0.1. If encryption is desired, this makes rights management via groups practically useless and drastically reduces owncloud's usefulness for teams with regularly changing members and more than trivial rights management requirements. 

It would be very helpful to show a warning in the administrator interface/group management panel when encryption is enabled. I spent quite some time trying to figure out what the error was. As a workaround, I am back to sharing and unsharing folders for each team member individually

**Comment by nickvergessen** [comment]
As far as I know that is the current limitation and no other solution is in sight yet.

**Comment by PVince81** [comment]
Technical limitation here: https://github.com/owncloud/core/issues/16332.

Use master key mode instead which doesn't have this limitation.
