### ISSUE TITLE
Update broken due to RemoveRootShares when an app needs update

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25156]
### Steps

1. Setup OC with master (cc532bb14aed74c397efa29a19ba48a3eeeb0cf0)
1. Increase version in "version.php"
1. Run update on the CLI => works fine
1. Increase version of "files_sharing" in its info.xml (or any filesystem-related app)
1. Run update on the CLI => :bomb: 

```
An unhandled exception has been thrown:
exception 'OC\NeedsUpdateException' in /srv/www/htdocs/owncloud/lib/private/legacy/app.php:147
Stack trace:
#0 /srv/www/htdocs/owncloud/lib/private/legacy/app.php(119): OC_App::loadApp('files_sharing')
#1 /srv/www/htdocs/owncloud/lib/private/legacy/util.php(135): OC_App::loadApps(Array)
#2 /srv/www/htdocs/owncloud/lib/private/Files/Filesystem.php(260): OC_Util::setupFS(NULL)
#3 /srv/www/htdocs/owncloud/lib/private/Server.php(174): OC\Files\Filesystem::getMountManager(NULL)
#4 /srv/www/htdocs/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#5 /srv/www/htdocs/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('RootFolder')
#6 /srv/www/htdocs/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('RootFolder')
#7 /srv/www/htdocs/owncloud/lib/private/Server.php(780): OC\ServerContainer->query('RootFolder')
#8 /srv/www/htdocs/owncloud/lib/private/Repair.php(140): OC\Server->getRootFolder()
#9 /srv/www/htdocs/owncloud/core/register_command.php(125): OC\Repair::getRepairSteps()
#10 /srv/www/htdocs/owncloud/lib/private/Console/Application.php(87): require_once('/srv/www/htdocs...')
#11 /srv/www/htdocs/owncloud/console.php(93): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /srv/www/htdocs/owncloud/occ(11): require_once('/srv/www/htdocs...')
#13 {main}
```

CC @rullzer 

This is because the injection in the repair step happens too early.

Let's try calling `getRootFolder` only in the run phase.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25158
