### ISSUE TITLE
Permissions in federated sharing are not being updated correctly after changes.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25189]
### Steps to reproduce:

Having two servers, serverA including userA and serverB including userB.
1. As userA federate share a folder FED_SHARED_FOLDER to userB.
2. As userB accept the fed share.
3. As userB upload some files to FED_SHARED_FOLDER.
4. As userA change permissions to FED_SHARED_FOLDER to not edit. (userB won't be able to upload)
5. As userB try to upload to FED_SHARED_FOLDER, it won't be possible.
6. As userA change permissions back and allow to edit in FED_SHARED_FOLDER.
7. As userB upload some files to FED_SHARED_FOLDER. 
### Expected behaviour:

userB can upload files.
### Actual behaviour

error 500.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
ServerA has PostgreSQL
ServerB has MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Current master on serverA and serverB
{"installed":true,"maintenance":false,"version":"9.1.0.8","versionstring":"9.1.0 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

last logs in serverB (perhaps not related)

```
{"reqId":"Nj4fQyklySzmZ2WYvmEc","remoteAddr":"HIDDEN_IP","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Backends provided no user object for admin@HIDDEN_SERVERA\\\/\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(200): OC\\\\Files\\\\Filesystem::initMountPoints('admin@docker.oc...')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(150): OCA\\\\Activity\\\\FilesHooks->getSourcePathAndOwner('\\\/PARA_GANDALF_Q...')\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(117): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/PARA_GANDALF_Q...', 'file_changed', 'changed_self', 'changed_by')\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/FilesHooksStatic.php(53): OCA\\\\Activity\\\\FilesHooks->fileUpdate('\\\/PARA_GANDALF_Q...')\\n#4 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileUpdate(Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): call_user_func(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1228): OC_Hook::emit('OC_Filesystem', 'post_update', Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1154): OC\\\\Files\\\\View->runHooks(Array, '\\\/PARA_GANDALF_Q...', true)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(670): OC\\\\Files\\\\View->basicOperation('file_put_conten...', '\\\/PARA_GANDALF_Q...', Array, 'Buenos dias man...')\\n#9 \\\/opt\\\/owncloud\\\/apps\\\/files_texteditor\\\/controller\\\/filehandlingcontroller.php(155): OC\\\\Files\\\\View->file_put_contents('\\\/PARA_GANDALF_Q...', 'Buenos dias man...')\\n#10 [internal function]: OCA\\\\Files_Texteditor\\\\Controller\\\\FileHandlingController->save('\\\/PARA_GANDALF_Q...', 'Buenos dias man...', 1466427757)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Texteditor\\\\Controller\\\\FileHandlingController), 'save')\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Texteditor\\\\Controller\\\\FileHandlingController), 'save')\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('FileHandlingCon...', 'save', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#15 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#16 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#17 \\\/opt\\\/owncloud\\\/lib\\\/base.php(866): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_tex...')\\n#18 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":405}","level":3,"time":"2016-06-20T13:02:52+00:00","method":"PUT","url":"\/index.php\/apps\/files_texteditor\/ajax\/savefile","user":"frodo"} {"reqId":"xgZYTRVpgjj7S0xDb2i+","remoteAddr":"HIDDEN_IP","app":"files","message":" Backends provided no user object for admin@HIDDEN_SERVERA\/","level":3,"time":"2016-06-20T13:10:47+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php","user":"frodo"} {"reqId":"xgZYTRVpgjj7S0xDb2i+","remoteAddr":"82.159.139.58","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Backends provided no user object for admin@docker.oc.solidgear.es:57953\\\/\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(200): OC\\\\Files\\\\Filesystem::initMountPoints('admin@docker.oc...')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(150): OCA\\\\Activity\\\\FilesHooks->getSourcePathAndOwner('\\\/COSAS\\\/gopher-a...')\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(106): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/COSAS\\\/gopher-a...', 'file_created', 'created_self', 'created_by')\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/FilesHooksStatic.php(45): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/COSAS\\\/gopher-a...')\\n#4 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): call_user_func(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(605): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(657): OC\\\\Files\\\\View->emit_file_hooks_post(false, '\\\/COSAS\\\/gopher-a...')\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1006): OC\\\\Files\\\\View->file_put_contents('\\\/COSAS\\\/gopher-a...', Resource id #256)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(716): OC\\\\Files\\\\View->fromTmpFile('\\\/tmp\\\/phpkOmlwT', '\\\/COSAS\\\/gopher-a...')\\n#10 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/upload.php(197): OC\\\\Files\\\\Filesystem::fromTmpFile('\\\/tmp\\\/phpkOmlwT', '\\\/COSAS\\\/gopher-a...')\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(154) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#12 [internal function]: __lambda_func(Array)\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func('?lambda_334', Array)\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/base.php(866): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#15 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":405}","level":3,"time":"2016-06-20T13:10:47+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php","user":"frodo"} 

```

Addressbooks were exchanged correctly before the tests.
### Client configuration

Chrome, Firefox.

**Comment by PVince81** [comment]
Can you try again with 9.1.1 RC1 ?

The error looks like https://github.com/owncloud/core/issues/24938 and might be blocking a legitimate 403 error

**Comment by PVince81** [comment]
@SergioBertolinSG can you retry with 9.1.3 RC1 ?

**Comment by davitol** [comment]
@PVince81 Tested following the steps, fed share 9.1.3 RC1 to 9.1.3 RC1and everything went fine
