### ISSUE TITLE
Issue with contacts cards table

### ISSUE THREAD

**Issue by martingwb** [owncloud/core#25275]
Hi,
I am having a problem with the contacts and calendars apps. I am not sure when this exactly started.
I guess I will have to repair the oc_cards table.  Is there a way to reinstall the tables for the contacts somehow?

**Steps to reproduce**
select "Contacts" ap
no contacts displayed, spinning wheel stays
**Expected behaviour**
Contacts should be displayed
**Actual behaviour**
Spinning wheel is displayed
oc.log
`{"reqId":"2YdCQ2b2Q5NkNFoDL0Ef","remoteAddr":"62.47.243.78","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECTid,uri,lastmodified,etag,size,carddataFROMoc_cardsWHEREaddressbookid= ?' with params [\\\"6\\\"]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'carddata' in 'field list'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctr....`

... and the table oc_cards is empty.

**Server configuration**
Os: raspbian
_Web server: nginx
*Database: mysql
*PHP version: 5.6.x
*ownCloud version: 9.0.1
*Contacts version: 1.3.1.0
*Updated from an older ownCloud or fresh install: fresh
*_Signing status (ownCloud 9.0 and above): **
No errors have been found.

**List of activated apps:**
pi@rpi /var/www/oc $ sudo -u www-data php occ app:list
Enabled:

activity: 2.2.1
announcementcenter: 1.1.2
bookmarks: true
calendar: 1.2.2
comments: 0.2
contacts: true
dav: 0.1.6
documents: true
federatedfilesharing: 0.1.0
federation: 0.0.4
files: 1.4.4
files_external: 0.5.2
files_pdfviewer: 0.8
files_sharing: 0.9.1
files_texteditor: 2.1
files_trashbin: 0.8.0
files_videoplayer: 0.9.8
galleryplus: 15.1.0
music: true
notifications: 0.2.3
ownbackup: true
ownnote: 1.08
systemtags: 0.2
templateeditor: 0.1
updatenotification: 0.1.0 Disabled:
encryption
external
files_versions
firstrunwizard
gallery
provisioning_api
user_external
user_ldap
**The content of config/config.php:**
pi@rpi /var/www/oc $ sudo -u www-data php occ config:list system
{
"system": {
"instanceid": "52386aa1107aa",
"passwordsalt": "REMOVED SENSITIVE VALUE",
"datadirectory": "\/mnt\/data\/oc-data",
"dbtype": "mysql",
"version": "9.0.1.3",
"dbname": "owncloud",
"dbhost": "127.0.0.1",
"dbtableprefix": "oc_",
"dbuser": "REMOVED SENSITIVE VALUE",
"dbpassword": "REMOVED SENSITIVE VALUE",
"installed": true,
"forcessl": true,
"updatechecker": true,
"has_internet_connection": true,
"check_for_working_htaccess": true,
"check_for_working_webdav": true,
"overwritehost": "whatever.crabdance.com:443",
"overwriteprotocol": "https",
"overwritewebroot": "\/oc",
"theme": "",
"maintenance": false,
"mail_domain": "gmail.com",
"mail_smtpmode": "smtp",
"mail_smtphost": "smtp.gmail.com",
"mail_smtpsecure": "tls",
"mail_smtpauth": 1,
"mail_smtpauthtype": "LOGIN",
"mail_smtpname": "REMOVED SENSITIVE VALUE",
"mail_smtppassword": "REMOVED SENSITIVE VALUE",
"trashbin_retention_obligation": "170, auto",
"logfile": "\/mnt\/data\/oc-data\/oc.log",
"loglevel": 2,
"logtimezone": "Europe\/Berlin",
"trusted_domains": [
"whatever.crabdance.com",
"rpi",
"10.0.0.63"
],
"mail_from_address": " whoever",
"default_language": "en",
"overwrite.cli.url": "https:\/\/whatever.crabdance.com\/oc",
"secret": "REMOVED SENSITIVE VALUE",
"memcache.local": "\OC\Memcache\APCu",
"mail_smtpport": "25",
"preview_libreoffice_path": "\/usr\/bin\/libreoffice",
"enable_previews": true,
"defaultapp": "files",
"knowledgebaseenabled": true,
"enable_avatars": true,
"appstoreenabled": true,
"appstore.experimental.enabled": false
}
}

**Are you using external storage, if yes which one: local/smb/sftp/...**
NO
**Are you using encryption: yes/no**
no
**Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...**
no

**Client configuration**
_Browser: Firefox, Chrome
*Operating system: Windows 7, Ubuntu 16.04
*_CardDAV-clients: davdroid

**Logs**
Web server error log: no errors displayed

ownCloud log (data/owncloud.log)
see above

Browser logs: no errors occur

**Comment by DeepDiver1975** [comment]
Please submit the full log line with the error - thx

**Comment by martingwb** [comment]
{"reqId":"CovlJtv37fz35UAkPeRu","remoteAddr":"85.115.58.180","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT `id`, `uri`, `lastmodified`, `etag`, `size`, `carddata` FROM `oc_cards` WHERE `addressbookid` = ?' with params [\\\"7\\\"]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'carddata' in 'field list'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 \\\/var\\\/www\\\/oc\\\/lib\\\/private\\\/db\\\/connection.php(184): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 \\\/var\\\/www\\\/oc\\\/lib\\\/private\\\/db\\\/querybuilder\\\/querybuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/oc\\\/apps\\\/dav\\\/lib\\\/carddav\\\/carddavbackend.php(383): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/AddressBook.php(78): OCA\\\\DAV\\\\CardDAV\\\\CardDavBackend->getCards('7')\\n#7 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(195): Sabre\\\\CardDAV\\\\AddressBook->getChildren()\\n#8 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(857): Sabre\\\\DAV\\\\Tree->getChildren('addressbooks\\\/us...')\\n#9 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(911): Sabre\\\\DAV\\\\Server->addPathNodesRecursively(Array, Object(Sabre\\\\DAV\\\\PropFind))\\n#10 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(334): Sabre\\\\DAV\\\\Server->getPropertiesForPath('addressbooks\\\/us...', Array, 1)\\n#11 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#14 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/var\\\/www\\\/oc\\\/apps\\\/dav\\\/lib\\\/server.php(142): Sabre\\\\DAV\\\\Server->exec()\\n#16 \\\/var\\\/www\\\/oc\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(29): OCA\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/oc\\\/remote.php(138): require_once('\\\/var\\\/www\\\/oc\\\/app...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71,\"User\":\"martin\"}","level":4,"time":"2016-06-28T13:41:17+02:00","method":"PROPFIND","url":"\/oc\/remote.php\/dav\/addressbooks\/users\/martin\/businesscontacts\/","user":"martin"}

**Comment by DeepDiver1975** [comment]
@martingwb how does the table look like? I assume the column 'carddata' exists?

**Comment by martingwb** [comment]
@DeepDiver1975 no
```
describe `oc_cards

 Field 	                Type 	            Null Key 	Default 	Extra 	
id 	                    bigint(20) unsigned NO 	 PRI 	NULL	auto_increment
addressbookid 	        int(11)	            NO 		     0	
uri 	                varchar(255)	    YES 		NULL	
lastmodified 	        bigint(20) unsigned	YES 		0	
etag 	                varchar(32)	        YES 		NULL	
size 	                bigint(20) unsigned	NO 		     0	
```

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
