### ISSUE TITLE
Can't Login to my Owncloud after Upgrade to 9.0.3

### ISSUE THREAD

**Issue by carlu93** [owncloud/core#25337]
### Steps to reproduce
1. Open web Browser
2. Goto to Owncloud
3. Click on Login Arrow

### Expected behaviour
Login and Files Overview should come up

### Actual behaviour
Nothing happens

### Server configuration
**Operating system**:
Opensuse Leap 42.1
**Web server:**
Apache 2.4.20
**Database:**
MariaDB 10.0.25
**PHP version:**
5.6.23
**ownCloud version:** (see ownCloud admin page)
9.0.3
**Updated from an older ownCloud or fresh install:**
Updated from 9.0.2
**Where did you install ownCloud from:**
Zypper Package
**Signing status (ownCloud 9.0 and above):**
?
**List of activated apps:**
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**
    "system": {
        "instanceid": "###",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "###"
        ],
        "datadirectory": "\/media\/data\/owncloud",
        "overwrite.cli.url": "###",
        "dbtype": "mysql",
        "version": "9.0.3.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "cache_path": "\/media\/data\/owncloud\/cache",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "maintenance": false,
        "loglevel": 3,
        "asset-pipeline.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "lund-it.de",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "###",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "trashbin_retention_obligation": "auto",
        "theme": "",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/owncloud"
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/..
No
### Client configuration
**Browser:**
Mozilla Firefox 47.0
**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VFncXHTgfHvaLzpkbUWv","remoteAddr":"192.168.1.110","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/core\\\/js\\\/oc.js) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-01T13:52:21+00:00","method":"GET","url":"\/core\/js\/oc.js?v=093029802c0279a994f44fdb029ac2bb","user":"--"}
{"reqId":"YIWODPP6vrRv7qxOf66i","remoteAddr":"192.168.1.110","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/core\\\/js\\\/oc.js) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-01T13:53:11+00:00","method":"GET","url":"\/core\/js\/oc.js?v=093029802c0279a994f44fdb029ac2bb","user":"--"}
{"reqId":"FGa59lzPNYjFPTELSmEF","remoteAddr":"192.168.1.110","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/core\\\/js\\\/oc.js) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-01T13:53:30+00:00","method":"GET","url":"\/core\/js\/oc.js?v=093029802c0279a994f44fdb029ac2bb","user":"--"}
{"reqId":"j6rGmBvfawPNSokIZL70","remoteAddr":"192.168.1.110","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/favicon.ico) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-01T13:53:40+00:00","method":"GET","url":"\/favicon.ico","user":"--"}
{"reqId":"B9AU+VNCntf71y+xf9SE","remoteAddr":"192.168.1.110","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/core\\\/js\\\/oc.js) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-01T13:53:44+00:00","method":"GET","url":"\/core\/js\/oc.js?v=093029802c0279a994f44fdb029ac2bb","user":"--"}
{"reqId":"sAANDkR046T6\/X9KP8pg","remoteAddr":"192.168.1.110","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/core\\\/js\\\/oc.js) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-01T13:58:02+00:00","method":"GET","url":"\/core\/js\/oc.js?v=093029802c0279a994f44fdb029ac2bb","user":"--"}
{"reqId":"cysteOL5Z3WUtaqdFdjq","remoteAddr":"","app":"PHP","message":"Module 'apcu' already loaded at Unknown#0","level":3,"time":"2016-07-01T14:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"nrCoAZV69s2P3Cyi5\/QH","remoteAddr":"192.168.1.110","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/core\\\/js\\\/oc.js) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-01T14:00:42+00:00","method":"GET","url":"\/core\/js\/oc.js?v=093029802c0279a994f44fdb029ac2bb","user":"--"}
{"reqId":"RKz4i4DP1fzUomPQxZGI","remoteAddr":"192.168.1.132","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/core\\\/js\\\/oc.js) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-01T14:01:33+00:00","method":"GET","url":"\/core\/js\/oc.js?v=093029802c0279a994f44fdb029ac2bb","user":"--"}

**Comment by RealRancor** [comment]
@carlu93 See this comment: https://github.com/owncloud/core/issues/25319#issuecomment-229844211

**Comment by carlu93** [comment]
@RealRancor Thank you very much. I got it fixed...

**Comment by capko** [comment]
I have problem access my owncloud after upgrade to 9.0.3 even when i input correct user and pass. Pressing enter nor click on arrow in password field does not trigger any action. Logon screen just sits there inert and i can't enter... 
@carlu93 See this comment: #25319 (comment) does not apply to me my setup is correct in this manner
