### ISSUE TITLE
Not able to link in smb-shares without "Remote Subfolder"

### ISSUE THREAD

**Issue by MasterG2000** [owncloud/core#25341]
### Steps to reproduce
1. Embed a SMB/CIFS Share without a "Remote Subfolder" (for example "\Server\DirectShare")
2. Go to your files
### Expected behaviour

The embedded share should be listed in your files.
### Actual behaviour

The embedded share is not listed in your files. But if you name a "Remote Subfolder" in the SMB/CIFS-shares configuration the share will appear in your files. It also doesn't help to fill in something like "\", "\", "/" or something like that in the SMB/CIFS-shares configuration.
### Server configuration

**Operating system**: Ubuntu Server 14.04.4 LTS 64-bit 

**Web server:** Apache 2.4

**Database:** MySQL 5.6

**PHP version:** PHP 7.0.5

**ownCloud version:** 9.0.3

**Updated from an older ownCloud or fresh install:** Yes, 9.0.0 -> 9.0.2 -> 9.0.3

**Where did you install ownCloud from:** In a VM from https://www.techandme.se/pre-configured-owncloud-installaton/

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - calendar
  - contacts
  - documents
  - encryption
  - files_antivirus
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.178.12",
            "owncloud",
            "gnemar.selfhost.tv"
        ],
        "datadirectory": "\/var\/data",
        "overwrite.cli.url": "https:\/\/192.168.178.12\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.3.2",
        "dbname": "owncloud_db",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ocnmcemo6p45",
        "appstore.experimental.enabled": "true",
        "mail_smtpmode": "smtp",
        "mail_smtpauth": "1",
        "mail_smtpport": "465",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "www.en0ch.se",
        "mail_domain": "gmail.com",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "htaccess.RewriteBase": "\/owncloud"
    }
}
```

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No
### Client configuration

**Browser:** Firefox 47

**Operating system:** Windows 7
#### Web server error log

```
[Sun Jul 03 06:29:57.600873 2016] [mpm_prefork:notice] [pid 59476] AH00163: Apache/2.4.7 (Ubuntu) OpenSSL/1.0.1f configured -- resuming normal operations
[Sun Jul 03 06:29:57.600907 2016] [core:notice] [pid 59476] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jul 03 13:24:36.977223 2016] [mpm_prefork:notice] [pid 59476] AH00169: caught SIGTERM, shutting down
[Sun Jul 03 13:24:37.921179 2016] [mpm_prefork:notice] [pid 30745] AH00163: Apache/2.4.7 (Ubuntu) OpenSSL/1.0.1f configured -- resuming normal operations
[Sun Jul 03 13:24:37.921239 2016] [core:notice] [pid 30745] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jul 03 13:28:15.938201 2016] [:error] [pid 42392] [client 80.128.104.205:58240] PHP Warning:  smbclient_state_errno(): supplied resource is not a valid smbclient state resource in /var/www/owncloud/apps/files_external/3rdparty/icewind/smb/src/NativeState.php on line 35
[Sun Jul 03 13:28:15.938830 2016] [:error] [pid 42392] [client 80.128.104.205:58240] PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in /var/www/owncloud/lib/private/files/filesystem.php:798\nStack trace:\n#0 /var/www/owncloud/lib/private/files/view.php(2011): OC\\Files\\Filesystem::normalizePath('/XXXXXX/files/...')\n#1 /var/www/owncloud/lib/private/files/view.php(1129): OC\\Files\\View->unlockFile('/Musik/The Prod...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 /var/www/owncloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown in /var/www/owncloud/lib/private/files/filesystem.php on line 798
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"VO7vAtWQE0iqlfPM7pxq","remoteAddr":"80.128.104.205","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/core\\\/js\\\/oc.js) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-03T11:10:43+00:00","method":"GET","url":"\/core\/js\/oc.js?v=febf0d742de80fc903d79a3b2aedb870","user":"--"}
{"reqId":"IHsCpiDoVy0gAv29KIZa","remoteAddr":"80.128.104.205","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/apps\\\/files\\\/) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-03T11:10:55+00:00","method":"GET","url":"\/apps\/files\/","user":"User1"}
{"reqId":"f1DhlJK5E2b6Imn\/nWa+","remoteAddr":"80.128.104.205","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/apps\\\/files\\\/core\\\/img\\\/breadcrumb.svg) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-03T11:10:56+00:00","method":"GET","url":"\/apps\/files\/core\/img\/breadcrumb.svg","user":"User1"}
{"reqId":"ehEI1IovJx9VFYS+PcOD","remoteAddr":"80.128.104.205","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/core\\\/js\\\/oc.js) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(837): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/request.php\",\"Line\":624}","level":3,"time":"2016-07-03T11:19:02+00:00","method":"GET","url":"\/core\/js\/oc.js?v=febf0d742de80fc903d79a3b2aedb870","user":"--"}
{"reqId":"5YLH4Hf4Nvr0uTMuv\/Ox","remoteAddr":"80.128.104.205","app":"core","message":"starting upgrade from 9.0.2.2 to 9.0.3.2","level":0,"time":"2016-07-03T11:26:21+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=LQ53NBgORXwMKXY4fjUuH1UiYwRCJnoEBiUUOHAFKzA%3D%3AKdAxtIw%2FcgEjQPcqleQ2zW2mWjfiItDsgxVgsN7aJ1E%3D","user":"--"}
{"reqId":"5YLH4Hf4Nvr0uTMuv\/Ox","remoteAddr":"80.128.104.205","app":"PHP","message":"file_put_contents(\/var\/data\/.htaccess): failed to open stream: Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#485","level":3,"time":"2016-07-03T11:26:21+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=LQ53NBgORXwMKXY4fjUuH1UiYwRCJnoEBiUUOHAFKzA%3D%3AKdAxtIw%2FcgEjQPcqleQ2zW2mWjfiItDsgxVgsN7aJ1E%3D","user":"--"}
```
#### Browser log

```
```

**Comment by PVince81** [comment]
Works for me on v9.0.3:
![smbconf1](https://cloud.githubusercontent.com/assets/277525/16554161/64e2f09e-41cd-11e6-8b43-9b77b7ed3cab.png)

**Comment by PVince81** [comment]
![smbconf2](https://cloud.githubusercontent.com/assets/277525/16554198/862f92e8-41cd-11e6-9c55-829d0bef9fa1.png)

**Comment by MasterG2000** [comment]
Hmm, very strange. The only different I see on the first view ist, that you used localhost as "Host" and I used the IP-address of my server. Are you able to check it with a smb-share on another server?

**Comment by MasterG2000** [comment]
Updated yesterday to 9.1.0 and still the same problem. The shares are only listed if I connect to a subfolder of the share. If I use the root folder the check in the administration panel is okay (green light) and if I go to my files the share is still missing.

**Comment by vellrind** [comment]
I have the same problem. External storage can't to connect to windows share without remote subfolder.
This problem has only the free version edition, enterprise edition is work fine.

**Comment by MasterG2000** [comment]
Sorry I was not able to check your hints before today. If I look on my PHPInfo I get the information that libsmbclient 0.8.0 is installed. So this should be fine right? But how can I check whether ownCloud uses this lib or not?

**Comment by jvillafanez** [comment]
Please check with the smbclient CLI command to check if you can connect to the SMB server (maybe you have some permission problem accessing that specific folder). In addition, verify the folder you're connecting to isn't hidden.

**Comment by MasterG2000** [comment]
Thanks for the replys and the support!!
With the update on 9.1.3 and some Ubuntu Updates it works now again for me (don't know which update fixed the Problem :-( ).
