### ISSUE TITLE
oc_trusted_servers table missing. 

### ISSUE THREAD

**Issue by Unknown2k** [owncloud/core#25497]
After upgrade to 9.x, I can't access the Admin page. 

 Base table or view not found: 1146 Table '.oc_trusted_servers' doesn't exist

### Steps to reproduce
Upgrade from 8.x to 9.

### Expected behaviour
Should be able to access Admin page after upgrade. 

### Actual behaviour
Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: 50.158.185.47
Request ID: 7Xr4OMWQRNhyb66hV3TX

### Server configuration
Debian 7
Apache/2.2.22
MySQL 5.5.49-0
PHP version: 5.5.36-1~dotdeb+7.1

Owncloud 9.0.3

Updated from 8.2, went from 8.2 to 8.2.6, to 9.0, etc. 

.tar

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No Errors Found. 

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Enabled:
  - activity: 2.2.1
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - templateeditor: 0.1
Disabled:
  - comments
  - encryption
  - external
  - files_antivirus
  - files_external
  - files_videoplayer
  - systemtags
  - updatenotification
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
{
    "system": {
        "instanceid": "ocb0da0de3aa",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.3.2",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "##########3",
            "#####33",
            "##############3"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbname": "owncloudgps",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "webmaster",
        "mail_smtpmode": "php",
        "mail_domain": "****",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

the Error from the log regarding this issue. 

{"reqId":"7Xr4OMWQRNhyb66hV3TX","remoteAddr":"50.158.185.47","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `url`, `url_hash`, `id`, `status`, `shared_secret`, `sync_token` FROM `oc_trusted_servers`':\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloudgps.oc_trusted_servers' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `url`, `...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(184): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `url`, `...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `url`, `...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/querybuilder\\\/querybuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/federation\\\/lib\\\/dbhandler.php(138): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/federation\\\/lib\\\/trustedservers.php(180): OCA\\\\Federation\\\\DbHandler->getAllServer()\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/federation\\\/settings\\\/settings-admin.php(41): OCA\\\\Federation\\\\TrustedServers->getServers()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(700): include('\\\/var\\\/www\\\/ownclo...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/settings\\\/admin.php(173): OC_App::getForms('admin')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 [internal function]: __lambda_func(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(276): call_user_func('\\\\x00lambda_191', Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(882): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#14 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","level":3,"time":"2016-07-16T05:18:34+00:00","method":"GET","url":"\/index.php\/settings\/admin","user":"contractor"}

**Comment by Unknown2k** [comment]
Update. 

I disabled "federation" app and I can now view the admin page. 

How can I fix federation?

**Comment by DeepDiver1975** [comment]
Please remove all entries from the table oc_appconfig with app=core and key=federation.
Then enable the app again.

**Comment by PVince81** [comment]
Please reopen if the advice above didn't help solve the issue.
