### ISSUE TITLE
Exception: files can't be disabled.

### ISSUE THREAD

**Issue by levin-kelevra** [owncloud/core#25526]
### Steps to reproduce
1. php ./occ -vvv upgrade

### Expected behaviour
Upgrade DB

### Actual behaviour
Fail

### Server configuration
**Operating system**: Ubuntu 14.06 x64

**Web server:** nginx

**Database:** postgres

**PHP version:** PHP 5.6.4-4ubuntu6.4 (cli) (built: Oct 28 2015 01:21:29) 

**ownCloud version:** latest git commit

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** git

**Signing status (ownCloud 9.0 and above):** 

**List of activated apps:**
Enabled:
  - comments: 0.3.0
  - dav: 0.2.5
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - testing
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc040bz9qumq",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "site.org"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/site.org",
        "dbtype": "pgsql",
        "version": "9.1.0.11",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpdebug": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "mail.org",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "loglevel": 0,
        "maintenance": true,
        "mail_smtpsecure": "ssl",
        "theme": "",
        "mail_smtphost": "mail.org"
    }
}

**Are you using encryption:** no

sudo -u www-data php ./occ -vvv upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2016-07-19T09:39:44+00:00 Set log level to debug
2016-07-19T09:39:44+00:00 Repair step: Repair MySQL database engine
2016-07-19T09:39:44+00:00 Repair info: Not a mysql database -> nothing to do
2016-07-19T09:39:44+00:00 Repair step: Repair MySQL collation
2016-07-19T09:39:44+00:00 Repair info: Not a mysql database -> nothing to no
2016-07-19T09:39:44+00:00 Repair step: Repair SQLite autoincrement
2016-07-19T09:39:44+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2016-07-19T09:39:44+00:00 Repair info: lucene_status table does not exist -> nothing to do
2016-07-19T09:39:44+00:00 Checking whether the database schema can be updated (this can take a long time depending on the database size)
2016-07-19T09:39:44+00:00  Checking table oc_appconfig
2016-07-19T09:39:45+00:00  Checking table oc_storages
2016-07-19T09:39:45+00:00  Checking table oc_mounts
2016-07-19T09:39:46+00:00  Checking table oc_mimetypes
2016-07-19T09:39:46+00:00  Checking table oc_filecache
2016-07-19T09:39:47+00:00  Checking table oc_group_user
2016-07-19T09:39:47+00:00  Checking table oc_group_admin
2016-07-19T09:39:47+00:00  Checking table oc_groups
2016-07-19T09:39:48+00:00  Checking table oc_preferences
2016-07-19T09:39:48+00:00  Checking table oc_properties
2016-07-19T09:39:48+00:00  Checking table oc_share
2016-07-19T09:39:49+00:00  Checking table oc_jobs
2016-07-19T09:39:49+00:00  Checking table oc_users
2016-07-19T09:39:49+00:00  Checking table oc_authtoken
2016-07-19T09:39:50+00:00  Checking table oc_vcategory
2016-07-19T09:39:50+00:00  Checking table oc_vcategory_to_object
2016-07-19T09:39:51+00:00  Checking table oc_systemtag
2016-07-19T09:39:51+00:00  Checking table oc_systemtag_object_mapping
2016-07-19T09:39:52+00:00  Checking table oc_systemtag_group
2016-07-19T09:39:52+00:00  Checking table oc_privatedata
2016-07-19T09:39:52+00:00  Checking table oc_file_locks
2016-07-19T09:39:53+00:00  Checking table oc_comments
2016-07-19T09:39:53+00:00  Checking table oc_comments_read_markers
2016-07-19T09:39:54+00:00  Checking table oc_credentials
2016-07-19T09:39:54+00:00 Checked database schema update
2016-07-19T09:39:54+00:00 Checking updates of apps
2016-07-19T09:39:54+00:00 Checked database schema update for apps
2016-07-19T09:39:54+00:00 Updating database schema
2016-07-19T09:39:54+00:00 Updated database
2016-07-19T09:39:54+00:00 Exception: files can't be disabled.
2016-07-19T09:39:54+00:00 Update failed
2016-07-19T09:39:54+00:00 Maintenance mode is kept active
2016-07-19T09:39:54+00:00 Reset log level

**Comment by PVince81** [comment]
What was the previous commit you were updating from ?
Are you on master ?

**Comment by levin-kelevra** [comment]
**
commit 4c425836c1b773101dc1f2f33c1589ab434ad0e6
Merge: 1133bdf f8069f7
Author: Vincent Petry <pvince81@owncloud.com>
Date:   Tue Jul 19 10:20:19 2016 +0200

    Merge pull request #25516 from owncloud/phantomjs-prebuilt
    
    Use phantomjs-prebuilt as warning is telling us

commit 1133bdf28959149bf8193adac0aff2178a74fbea
Author: Jenkins for ownCloud <owncloud-bot@tmit.eu>
Date:   Tue Jul 19 01:59:48 2016 -0400

    [tx-robot] updated from transifex

commit f8069f72f0fb5724796910a73d3c31946c489fda
Author: Thomas Müller <DeepDiver1975@users.noreply.github.com>
Date:   Mon Jul 18 14:16:55 2016 +0200

    Use phantomjs-prebuilt as warning is telling us

commit 7b295c01cf1b638f96ad64cf2d086f25bb1b6fee
Author: Vincent Petry <pvince81@owncloud.com>
Date:   Mon Jul 18 12:26:00 2016 +0200

    Increase version to 9.2 (#25510)

**

Yes, on master

**git status **
On branch master
Your branch is up-to-date with 'origin/master'.

**Comment by PVince81** [comment]
@levin-kelevra do you have the owncloud.log part with that exception ?

Updating from stable9.1 to master worked for me.

**Comment by PVince81** [comment]
Noooo, I posted too fast.

I see the error too, will try and debug.

**Comment by PVince81** [comment]
```
{"reqId":"0V9ix794HQSuqVRwgvUU","remoteAddr":"127.0.0.1","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"files can't be disabled.\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(407): OC\\\\App\\\\AppManager->disableApp('files')\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Updater.php(405): OC_App::disable('files')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Updater.php(250): OC\\\\Updater->checkAppsRequirements()\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Updater.php(150): OC\\\\Updater->doUpgrade('9.2.0.1', '9.1.0.14')\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/core\\\/ajax\\\/update.php(193): OC\\\\Updater->upgrade()\\n#5 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/App\\\/AppManager.php\",\"Line\":256}","level":3,"time":"2016-07-19T15:36:11+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=eXIeHw0qBwIBQCc%2BC1tuIxIAIjRRLHI7Zi4XMTFFIS8%3D%3AJEkTagkmq2Ryrc8Fe2xzayGc6MPCp%2BWifCVEE9SYafY%3D","user":"--"}
```

**Comment by PVince81** [comment]
Steps:

1. Checkout stable9.1 from git (28a689c856e6d77d8504e45d1328d4e2825b8b49)
1. Setup OC
1. Checkout master from git (a584840b4ed86e48ad4e53917b523e6197b92b51)
1. Run update (I did in the web UI)

**Comment by PVince81** [comment]
Aha! The files app says it only supports up to OC 9.1 so the updater tries to disable it :smile_cat: 

Let me check the requirements of the core apps and adjust them...

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/25537

- [ ] core apps: https://github.com/owncloud/core/pull/25537
- [ ] other bundled apps

**Comment by levin-kelevra** [comment]
d163b1275d60f3fda7e7d731ea29ca332e42e008 - is lasted works for me

**Comment by PVince81** [comment]
@levin-kelevra yes, we increased the version recently in version.php from 9.1 to 9.2, so obviously all dependency checks that wanted 9.1 would fail now.

**Comment by levin-kelevra** [comment]
how soon will the commit with the fix?

**Comment by PVince81** [comment]
As soon as people care about reviewing this pull request: https://github.com/owncloud/core/pull/25537
