### ISSUE TITLE
Unshare → Error deleting file

### ISSUE THREAD

**Issue by Goury** [owncloud/core#25593]
### Steps to reproduce
1. Share folder via link by user2
2. Follow this link by user1
3. Add to your owncloud by typing https://personal.owncloud.server.address
4. Files app freezing alot now
5. Unsharing results in message ''Error deleting file "filename"''
### Expected behaviour

Just unsharing
### Actual behaviour

Freezes and errors
### Server configuration

**Operating system**: Ubuntu Server 14.04

**Web server:** Apache2 through nginx

**Database:** mariadb 10.0

**PHP version:** 7.0

**ownCloud version:** 9.1.0 Stable

**Updated from an older ownCloud or fresh install:** Updated from 9.0 that was updated from 8.0.4 that was updated from 8.0.1 that was updated from 7.whatever, I do not remember this far

**Where did you install ownCloud from:** owncloud.org

**Signing status (ownCloud 9.0 and above):** All checks passed

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - music: 0.3.11
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc1f790fbefe",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.slayers.ru"
        ],
        "datadirectory": "\/home\/webserver\/cloud.slayers.ru\/www\/data",
        "overwrite.cli.url": "https:\/\/cloud.slayers.ru",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maintenance": false,
        "mail_from_address": "goury",
        "mail_smtpmode": "php",
        "mail_domain": "slayers.ru",
        "theme": "",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ]
    }
}

```

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** https with chinese ssl certificate

**Are you using an external user-backend, if yes which one:** nope
### Client configuration

**Browser:** Mozilla Firefox 47.0, Chromium 51.0.2704.79

**Operating system:** Ubuntu 14.04, 14.10, 15.04, 15.10, 16.04
#### Web server error log

nginx error log:

```
2016/07/24 21:12:53 [error] 4135#4135: *1860396 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 95.28.164.220, server: cloud.slayers.ru, request: "GET /index.php/core/preview.png?file=%2Ff9f35763f622af058bbbceffefa78ab0.jpg&c=a5d9c294eb57bf548cce5143af96f62f&x=32&y=32&forceIcon=0 HTTP/1.1", upstream: "http://127.0.0.1:8080/index.php/core/preview.png?file=%2Ff9f35763f622af058bbbceffefa78ab0.jpg&c=a5d9c294eb57bf548cce5143af96f62f&x=32&y=32&forceIcon=0", host: "cloud.slayers.ru"
2016/07/24 21:13:04 [error] 4135#4135: *1860395 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 95.28.164.220, server: cloud.slayers.ru, request: "GET /index.php/core/preview.png?file=%2Ffos-contact-backup.vcf&c=88b9834cdbf0104263f33ea015cb855f&x=32&y=32&forceIcon=0 HTTP/1.1", upstream: "http://127.0.0.1:8080/index.php/core/preview.png?file=%2Ffos-contact-backup.vcf&c=88b9834cdbf0104263f33ea015cb855f&x=32&y=32&forceIcon=0", host: "cloud.slayers.ru"
2016/07/24 21:13:22 [error] 4135#4135: *1860399 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 95.28.164.220, server: cloud.slayers.ru, request: "GET /index.php/core/preview.png?file=%2Fopenc_ffos22_modui02.zip&c=54ca2654ad042&x=32&y=32&forceIcon=0 HTTP/1.1", upstream: "http://127.0.0.1:8080/index.php/core/preview.png?file=%2Fopenc_ffos22_modui02.zip&c=54ca2654ad042&x=32&y=32&forceIcon=0", host: "cloud.slayers.ru"
2016/07/24 21:13:53 [error] 4135#4135: *1860396 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 95.28.164.220, server: cloud.slayers.ru, request: "DELETE /remote.php/webdav/Alef_audio HTTP/1.1", upstream: "http://127.0.0.1:8080/remote.php/webdav/Alef_audio", host: "cloud.slayers.ru"
2016/07/24 21:14:08 [error] 4136#4136: *1860346 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 95.28.164.220, server: cloud.slayers.ru, request: "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1", upstream: "http://127.0.0.1:8080/ocs/v2.php/apps/notifications/api/v1/notifications?format=json", host: "cloud.slayers.ru"
```

apache2 error log:

```
[Sun Jul 24 21:22:30.351089 2016] [negotiation:error] [pid 21726] [client 127.0.0.1:43600] AH00687: Negotiation: discovered file(s) matching request: /home/webserver/cloud.slayers.ru/www/settings/admin (None could be negotiated).
[Sun Jul 24 21:22:34.878848 2016] [authz_core:error] [pid 21762] [client 127.0.0.1:43644] AH01630: client denied by server configuration: /home/webserver/cloud.slayers.ru/www/data/htaccesstest.txt
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"wARY6Ee7Nh9Yh7WwFK1T","remoteAddr":"127.0.0.1","app":"PHP","message":"Illegal offset type at \/home\/webserver\/cloud.slayers.ru\/www\/lib\/private\/AppConfig.php#138","level":3,"time":"2016-07-24T18:37:47+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"raSMce4XgSaiyAUSLVMP","remoteAddr":"127.0.0.1","app":"PHP","message":"Illegal offset type at \/home\/webserver\/cloud.slayers.ru\/www\/lib\/private\/AppConfig.php#138","level":3,"time":"2016-07-24T18:37:47+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"Goury"}
{"reqId":"wARY6Ee7Nh9Yh7WwFK1T","remoteAddr":"127.0.0.1","app":"PHP","message":"Object of class OCA\\Music\\App\\Music could not be converted to string at \/home\/webserver\/cloud.slayers.ru\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2016-07-24T18:37:47+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"wARY6Ee7Nh9Yh7WwFK1T","remoteAddr":"127.0.0.1","app":"PHP","message":"Object of class OCA\\Music\\App\\Music could not be converted to string at \/home\/webserver\/cloud.slayers.ru\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2016-07-24T18:37:47+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"raSMce4XgSaiyAUSLVMP","remoteAddr":"127.0.0.1","app":"PHP","message":"Object of class OCA\\Music\\App\\Music could not be converted to string at \/home\/webserver\/cloud.slayers.ru\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2016-07-24T18:37:47+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"Goury"}
{"reqId":"raSMce4XgSaiyAUSLVMP","remoteAddr":"127.0.0.1","app":"PHP","message":"Object of class OCA\\Music\\App\\Music could not be converted to string at \/home\/webserver\/cloud.slayers.ru\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2016-07-24T18:37:47+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"Goury"}
{"reqId":"wARY6Ee7Nh9Yh7WwFK1T","remoteAddr":"127.0.0.1","app":"PHP","message":"Object of class OCA\\Music\\App\\Music could not be converted to string at \/home\/webserver\/cloud.slayers.ru\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#67","level":3,"time":"2016-07-24T18:37:47+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"raSMce4XgSaiyAUSLVMP","remoteAddr":"127.0.0.1","app":"PHP","message":"Object of class OCA\\Music\\App\\Music could not be converted to string at \/home\/webserver\/cloud.slayers.ru\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#67","level":3,"time":"2016-07-24T18:37:47+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"Goury"}
{"reqId":"raSMce4XgSaiyAUSLVMP","remoteAddr":"127.0.0.1","app":"PHP","message":"Illegal offset type at \/home\/webserver\/cloud.slayers.ru\/www\/lib\/private\/AppConfig.php#192","level":3,"time":"2016-07-24T18:37:47+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"Goury"}
{"reqId":"wARY6Ee7Nh9Yh7WwFK1T","remoteAddr":"127.0.0.1","app":"PHP","message":"Illegal offset type at \/home\/webserver\/cloud.slayers.ru\/www\/lib\/private\/AppConfig.php#192","level":3,"time":"2016-07-24T18:37:47+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"fkkvr4\/VoDIWhNIorotF","remoteAddr":"127.0.0.1","app":"no app in context","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCP\\\\Backgroundjob' not found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/webserver\\\/cloud.slayers.ru\\\/www\\\/lib\\\/private\\\/legacy\\\/app.php(186): require_once()\\n#1 \\\/home\\\/webserver\\\/cloud.slayers.ru\\\/www\\\/lib\\\/private\\\/legacy\\\/app.php(149): OC_App::requireAppFile('music')\\n#2 \\\/home\\\/webserver\\\/cloud.slayers.ru\\\/www\\\/lib\\\/private\\\/legacy\\\/app.php(119): OC_App::loadApp('music')\\n#3 \\\/home\\\/webserver\\\/cloud.slayers.ru\\\/www\\\/ocs\\\/v1.php(49): OC_App::loadApps()\\n#4 \\\/home\\\/webserver\\\/cloud.slayers.ru\\\/www\\\/ocs\\\/v2.php(22): require_once('\\\/home\\\/webserver...')\\n#5 {main}\",\"File\":\"\\\/home\\\/webserver\\\/cloud.slayers.ru\\\/www\\\/apps\\\/music\\\/appinfo\\\/app.php\",\"Line\":38}","level":3,"time":"2016-07-24T18:37:48+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"fkkvr4\/VoDIWhNIorotF","remoteAddr":"127.0.0.1","app":"PHP","message":"Illegal offset type in isset or empty at \/home\/webserver\/cloud.slayers.ru\/www\/lib\/private\/legacy\/app.php#651","level":3,"time":"2016-07-24T18:37:48+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"fkkvr4\/VoDIWhNIorotF","remoteAddr":"127.0.0.1","app":"PHP","message":"trim() expects parameter 1 to be string, object given at \/home\/webserver\/cloud.slayers.ru\/www\/lib\/private\/legacy\/app.php#576","level":3,"time":"2016-07-24T18:37:48+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"fkkvr4\/VoDIWhNIorotF","remoteAddr":"127.0.0.1","app":"PHP","message":"Object of class OCA\\Music\\App\\Music could not be converted to string at \/home\/webserver\/cloud.slayers.ru\/www\/lib\/private\/legacy\/app.php#75","level":3,"time":"2016-07-24T18:37:48+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"fkkvr4\/VoDIWhNIorotF","remoteAddr":"127.0.0.1","app":"PHP","message":"Illegal offset type in unset at \/home\/webserver\/cloud.slayers.ru\/www\/lib\/private\/App\/AppManager.php#258","level":3,"time":"2016-07-24T18:37:48+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"fkkvr4\/VoDIWhNIorotF","remoteAddr":"127.0.0.1","app":"PHP","message":"Illegal offset type at \/home\/webserver\/cloud.slayers.ru\/www\/lib\/private\/AppConfig.php#138","level":3,"time":"2016-07-24T18:37:48+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"fkkvr4\/VoDIWhNIorotF","remoteAddr":"127.0.0.1","app":"PHP","message":"Object of class OCA\\Music\\App\\Music could not be converted to string at \/home\/webserver\/cloud.slayers.ru\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2016-07-24T18:37:48+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"fkkvr4\/VoDIWhNIorotF","remoteAddr":"127.0.0.1","app":"PHP","message":"Object of class OCA\\Music\\App\\Music could not be converted to string at \/home\/webserver\/cloud.slayers.ru\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2016-07-24T18:37:48+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"fkkvr4\/VoDIWhNIorotF","remoteAddr":"127.0.0.1","app":"PHP","message":"Object of class OCA\\Music\\App\\Music could not be converted to string at \/home\/webserver\/cloud.slayers.ru\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#67","level":3,"time":"2016-07-24T18:37:48+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
{"reqId":"fkkvr4\/VoDIWhNIorotF","remoteAddr":"127.0.0.1","app":"PHP","message":"Illegal offset type at \/home\/webserver\/cloud.slayers.ru\/www\/lib\/private\/AppConfig.php#192","level":3,"time":"2016-07-24T18:37:48+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"katyshevich"}
```
#### Browser log

```
JQMIGRATE: Migrate is installed, version 1.4.0
https://cloud.slayers.ru/remote.php/webdav/Alef_audio Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://cloud.slayers.ru/remote.php/dav/systemtags-relations/files/45121 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://cloud.slayers.ru/remote.php/webdav/Alef_books Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://cloud.slayers.ru/remote.php/webdav/Alef_audio Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://cloud.slayers.ru/remote.php/webdav/Alef_books Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://cloud.slayers.ru/remote.php/webdav/Alef_audio Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://cloud.slayers.ru/remote.php/webdav/Alef_books Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://cloud.slayers.ru/remote.php/webdav/Alef_audio Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://cloud.slayers.ru/remote.php/webdav/Alef_books Failed to load resource: the server responded with a status of 503 (Service Unavailable)
```

**Comment by RealRancor** [comment]
@Goury Your logfiles shows errors about the enabled ``  - music: 0.3.11`` app. When having such issues try to first disable all 3rdparty apps like music.

**Comment by Goury** [comment]
It is exacly the same with or without this app, the only difference is occurrence of music app extra errors in log.

**Comment by RealRancor** [comment]
So then please disable the music app, clear your data/owncloud.log and re-do the steps to only have the relevant logentries about this issue in there.

**Comment by PVince81** [comment]
@Goury can you ask the public link owner whether the shared folder is stored on an external storage ? (maybe of type "local"). This issue sounds like https://github.com/owncloud/core/issues/25618

**Comment by Goury** [comment]
@PVince81 
I am the owner, there is no external storages for this one, everything is on my /dev/sda2

**Comment by PVince81** [comment]
Please try again with 9.1.2 or 9.1.3 RC1. A lot of issues have been fixed there, especially the "files app freezing a lot" kind.

If the problem about unshare still happens there, please reopen.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
