### ISSUE TITLE
Error deleting files in browser shared via link

### ISSUE THREAD

**Issue by daorte** [owncloud/core#25618]
### Steps to reproduce
1. With admin user create an external storage to a local folder with this params:
2. Folder Name: DATA
3. External Storage: Local
4. Authentication: None
5. Configuration: /home/ubuntu/data_disk1
6. Available for: userOne (only userOne can see this mount point)
7. Enable sharing is selected
8. Log in with 'userOne' and create a shared link
9. Enter with a browser to the URL of the shared link
10. Try to delete a file
### Expected behaviour

The file should be deleted
### Actual behaviour

A yellow error message is shown 'Error al borra el archivo 3.exe' in english is something like 'error deleting file 3.exe'
### Server configuration

Web server: Apache 2.4
Database: MySQL
PHP version: 7
OwnCloud: 9.1 upgraded from 9.0.4
### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

**Operating system:** Windows 8.1
#### ownCloud log (data/owncloud.log)

```
{"reqId":"6RfrNCKYpamXxfqRey4I","remoteAddr":"192.168.3.144","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-07-26T12:10:41+00:00","method":"DELETE","url":"\/owncloud\/public.php\/webdav\/Nueva%20carpeta\/3.exe","user":"--"}
{"reqId":"6RfrNCKYpamXxfqRey4I","remoteAddr":"192.168.3.144","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Attempted to initialize mount points for null user and no user in session\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(90): OC\\\\Files\\\\Filesystem::initMountPoints(false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(67): OCA\\\\Files_Trashbin\\\\Trashbin::getUidAndFilename('\\\/ROOT\\\/Users\\\/Nue...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OCA\\\\Files_Trashbin\\\\Trashbin::ensureFileScannedHook(Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1229): OC_Hook::emit('OC_Filesystem', 'delete', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1107): OC\\\\Files\\\\View->runHooks(Array, '\\\/ROOT\\\/Users\\\/Nue...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(689): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/Nueva carpeta\\\/...', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(333): OC\\\\Files\\\\View->unlink('\\\/Nueva carpeta\\\/...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('Nueva carpeta\\\/3...')\\n#9 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(87): Sabre\\\\DAV\\\\Server->exec()\\n#14 \\\/var\\\/www\\\/owncloud\\\/public.php(74): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":394}","level":3,"time":"2016-07-26T12:10:41+00:00","method":"DELETE","url":"\/owncloud\/public.php\/webdav\/Nueva%20carpeta\/3.exe","user":"--"}
{"reqId":"6RfrNCKYpamXxfqRey4I","remoteAddr":"192.168.3.144","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Attempted to initialize mount points for null user and no user in session\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(101): OC\\\\Files\\\\Filesystem::initMountPoints(false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(204): OCA\\\\Files_Versions\\\\Storage::getUidAndFilename('\\\/ROOT\\\/Users\\\/Nue...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_versions\\\/lib\\\/Hooks.php(90): OCA\\\\Files_Versions\\\\Storage::markDeletedFile('\\\/ROOT\\\/Users\\\/Nue...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OCA\\\\Files_Versions\\\\Hooks::pre_remove_hook(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1229): OC_Hook::emit('OC_Filesystem', 'delete', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1107): OC\\\\Files\\\\View->runHooks(Array, '\\\/ROOT\\\/Users\\\/Nue...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(689): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/Nueva carpeta\\\/...', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(333): OC\\\\Files\\\\View->unlink('\\\/Nueva carpeta\\\/...')\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('Nueva carpeta\\\/3...')\\n#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(87): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/var\\\/www\\\/owncloud\\\/public.php(74): require_once('\\\/var\\\/www\\\/ownclo...')\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":394}","level":3,"time":"2016-07-26T12:10:41+00:00","method":"DELETE","url":"\/owncloud\/public.php\/webdav\/Nueva%20carpeta\/3.exe","user":"--"}
{"reqId":"6RfrNCKYpamXxfqRey4I","remoteAddr":"192.168.3.144","app":"webdav","message":"Exception: {\"Message\":\"Attempted to initialize mount points for null user and no user in session\",\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(90): OC\\\\Files\\\\Filesystem::initMountPoints(false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(204): OCA\\\\Files_Trashbin\\\\Trashbin::getUidAndFilename('ROOT\\\/Users\\\/Nuev...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(160): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('ROOT\\\/Users\\\/Nuev...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(95): OCA\\\\Files_Trashbin\\\\Storage->doDelete('Users\\\/Nueva car...', 'unlink')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1118): OCA\\\\Files_Trashbin\\\\Storage->unlink('Users\\\/Nueva car...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(689): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/Nueva carpeta\\\/...', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(333): OC\\\\Files\\\\View->unlink('\\\/Nueva carpeta\\\/...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('Nueva carpeta\\\/3...')\\n#9 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(87): Sabre\\\\DAV\\\\Server->exec()\\n#14 \\\/var\\\/www\\\/owncloud\\\/public.php(74): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":394,\"User\":false}","level":4,"time":"2016-07-26T12:10:41+00:00","method":"DELETE","url":"\/owncloud\/public.php\/webdav\/Nueva%20carpeta\/3.exe","user":"--"}

```

**Comment by daorte** [comment]
More information,

Disabling the 'Deleted Files' app no error is shown and the file is deleted.

But, we need the trash bin functionality.

**Comment by PVince81** [comment]
Sounds similar to https://github.com/owncloud/core/issues/25593 but with different errors in log

**Comment by PVince81** [comment]
I could reproduce this on v9.1.0:
```
{"reqId":"bMpz6rAEZV61w5tVqgvt","remoteAddr":"127.0.0.1","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Attempted to initialize mount points for null user and no user in session\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(90): OC\\\\Files\\\\Filesystem::initMountPoints(false)\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(67): OCA\\\\Files_Trashbin\\\\Trashbin::getUidAndFilename('\\\/Local\\\/sharethi...')\\n
#2 [internal function]: OCA\\\\Files_Trashbin\\\\Trashbin::ensureFileScannedHook(Array)\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): call_user_func(Array, Array)\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1231): OC_Hook::emit('OC_Filesystem', 'delete', Array)\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1107): OC\\\\Files\\\\View->runHooks(Array, '\\\/DSC05207.JPG')\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(689): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/DSC05207.JPG', Array)\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(333): OC\\\\Files\\\\View->unlink('\\\/DSC05207.JPG')\\n
#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n
#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('DSC05207.JPG')\\n
#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n
#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(87): Sabre\\\\DAV\\\\Server->exec()\\n
#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/public.php(74): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#16 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":394}","level":3,"time":"2016-08-16T16:03:38+00:00","method":"DELETE","url":"\/owncloud\/public.php\/webdav\/DSC05207.JPG","user":"--"}
{"reqId":"bMpz6rAEZV61w5tVqgvt","remoteAddr":"127.0.0.1","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Attempted to initialize mount points for null user and no user in session\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(101): OC\\\\Files\\\\Filesystem::initMountPoints(false)\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(204): OCA\\\\Files_Versions\\\\Storage::getUidAndFilename('\\\/Local\\\/sharethi...')\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_versions\\\/lib\\\/Hooks.php(90): OCA\\\\Files_Versions\\\\Storage::markDeletedFile('\\\/Local\\\/sharethi...')\\n
#3 [internal function]: OCA\\\\Files_Versions\\\\Hooks::pre_remove_hook(Array)\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): call_user_func(Array, Array)\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1231): OC_Hook::emit('OC_Filesystem', 'delete', Array)\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1107): OC\\\\Files\\\\View->runHooks(Array, '\\\/DSC05207.JPG')\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(689): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/DSC05207.JPG', Array)\\n
#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(333): OC\\\\Files\\\\View->unlink('\\\/DSC05207.JPG')\\n
#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n
#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('DSC05207.JPG')\\n
#11 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n
#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(87): Sabre\\\\DAV\\\\Server->exec()\\n
#16 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/public.php(74): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#17 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":394}","level":3,"time":"2016-08-16T16:03:38+00:00","method":"DELETE","url":"\/owncloud\/public.php\/webdav\/DSC05207.JPG","user":"--"}
{"reqId":"bMpz6rAEZV61w5tVqgvt","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"Attempted to initialize mount points for null user and no user in session\",\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(90): OC\\\\Files\\\\Filesystem::initMountPoints(false)\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(204): OCA\\\\Files_Trashbin\\\\Trashbin::getUidAndFilename('Local\\\/sharethis...')\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(160): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('Local\\\/sharethis...')\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(95): OCA\\\\Files_Trashbin\\\\Storage->doDelete('sharethis\\\/DSC05...', 'unlink')\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1118): OCA\\\\Files_Trashbin\\\\Storage->unlink('sharethis\\\/DSC05...')\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(689): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/DSC05207.JPG', Array)\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(333): OC\\\\Files\\\\View->unlink('\\\/DSC05207.JPG')\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n
#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('DSC05207.JPG')\\n
#9 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n
#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(87): Sabre\\\\DAV\\\\Server->exec()\\n
#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/public.php(74): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#15 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":394,\"User\":false}","level":4,"time":"2016-08-16T16:03:38+00:00","method":"DELETE","url":"\/owncloud\/public.php\/webdav\/DSC05207.JPG","user":"--"}
```

**Comment by PVince81** [comment]
Ah yes... this is because external storages don't have a real owner.
And when using link shares, there is no logged in user since it's a public link.
So the code cannot find whose trashbin to use when deleting.

I'd say the most logic choice in such situation is to use the trashbin of whoever created the link share.

**Comment by PVince81** [comment]
Or a quickfix would be to skip the trashbin altogether in this use case.

But first, let's see how complicated it is to reach the link share's user...

**Comment by daorte** [comment]
As a workaround, we are not using the trash bin

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/26587
