### ISSUE TITLE
Internal server error after fresh install

### ISSUE THREAD

**Issue by Lars-** [owncloud/core#25645]
The error is solved by following this issue: https://github.com/owncloud/core/issues/8071
But then the owncloud webclient starts prompting that the integrity of the code isn't correct

### Steps to reproduce
1. Install owncloud via apt on Debian 8
2. Setup the recommended nGinx config

### Expected behaviour
The installer should start

### Actual behaviour
Internal server error

### Server configuration
**Operating system**: Debian 8.5

**Web server:** nGinx 1.9.10

**Database:** MariaDB 10.1.16

**PHP version:** 5.6.24

**ownCloud version:** Newest

**Updated from an older ownCloud or fresh install:** No

**Where did you install ownCloud from:** APT

**Signing status (ownCloud 9.0 and above):** Unknown

**List of activated apps:** 

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```json
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocwm9fjbskcw",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.ljpc.nl"
        ],
        "datadirectory": "\/cloud",
        "overwrite.cli.url": "https:\/\/cloud.ljpc.nl",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 52.0.2743.82

**Operating system:** Mac OSX 10.11.6

#### ownCloud log (data/owncloud.log)

```json
{"reqId":"0kNc6R81yk7V1UdKNdvL","remoteAddr":"82.73.176.6","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"template file not found: template:layout.guest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(198): OC\\\\Template\\\\TemplateFileLocator->find('layout.guest')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(85): OC_Template->findTemplate('', 'core', 'layout.guest')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(121): OC_Template->__construct('core', 'layout.guest')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC\\\\TemplateLayout->__construct('guest', '')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Template\\\/Base.php(129): OC_Template->fetchPage()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(310): OC\\\\Template\\\\Base->printPage()\\n#6 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/SetupController.php(95): OC_Template::printGuestPage('', 'installation', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/SetupController.php(75): OC\\\\Core\\\\Controller\\\\SetupController->display(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(829): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Template\\\/TemplateFileLocator.php\",\"Line\":55}","level":3,"time":"2016-07-29T11:02:05+00:00","method":"GET","url":"\/","user":"--"}
```

**Comment by PVince81** [comment]
> But then the owncloud webclient starts prompting that the integrity of the code isn't correct

details?

**Comment by PVince81** [comment]
> template file not found: template:layout.guest

this also looks like something is wrong with the source code, files might be missing. Please try removing the source code and replacing it with the same version from the tarball (or reinstall distro packages if you used them).

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
