### ISSUE TITLE
Feature request: Allow installation using an existing database

### ISSUE THREAD

**Issue by smy213** [owncloud/core#25665]
The current installation process of owncloud 9.1 requires creation of a new database. 
This is documented in [chapter "Installation Wizard"](https://doc.owncloud.org/server/9.1/admin_manual/installation/installation_wizard.html):

> You will need the root database login, or any administrator login that
> has permissions to create and modify databases, and then enter any name you want
> for your ownCloud database.

As this is a safe and secure default for hosts you have full access to, it should be possible to avoid this extra redirection and directly use an existing database. 

Use-Case: My provider won't let me create new databases. My plan includes 5 databases (Postgres or MySQL) with fixed names. CREATE DATABASE and CREATE USER always fail. 
### Server configuration

**ownCloud version:** 9.0.4, 9.1

**Updated from an older ownCloud or fresh install:** fresh install **impossible**

**Where did you install ownCloud from:** taz.bz2 from owncloud.org, problem exists for install using occ as as as using install wizard via browser
#### ownCloud log (data/owncloud.log)

```
{"reqId":"V55iHCUR4EoAAHNKWDgAAAAB","remoteAddr":"91.60.151.124","app":"no app in context","message":"Error occurred while checking PostgreSQL version, assuming >= 9","level":2,"time":"2016-07-31T20:39:56+00:00","method":"POST","url":"\/index.php\/settings\/integrity\/index.php","user":"--"}
{"reqId":"V55iHCUR4EoAAHNKWDgAAAAB","remoteAddr":"91.60.151.124","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",\"Message\":\"Failed to connect to the database: An exception occured in driver: could not find driver\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(429): OC\\\\DB\\\\Connection->connect()\\n#1 \\\/home\\\/www\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(389): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatformVersion()\\n#2 \\\/home\\\/www\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(328): Doctrine\\\\DBAL\\\\Connection->detectDatabasePlatform()\\n#3 \\\/home\\\/www\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(621): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatform()\\n#4 \\\/home\\\/www\\\/cloud\\\/lib\\\/private\\\/DB\\\/Connection.php(141): Doctrine\\\\DBAL\\\\Connection->setTransactionIsolation(2)\\n#5 \\\/home\\\/www\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DriverManager.php(172): OC\\\\DB\\\\Connection->__construct(Array, Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#6 \\\/home\\\/www\\\/cloud\\\/lib\\\/private\\\/DB\\\/ConnectionFactory.php(122): Doctrine\\\\DBAL\\\\DriverManager::getConnection(Array, Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#7 \\\/home\\\/www\\\/cloud\\\/lib\\\/private\\\/Server.php(410): OC\\\\DB\\\\ConnectionFactory->getConnection('pgsql', Array)\\n#8 \\\/home\\\/www\\\/cloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#9 \\\/home\\\/www\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(102): Pimple\\\\Container->offsetGet('DatabaseConnect...')\\n#10 \\\/home\\\/www\\\/cloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('DatabaseConnect...')\\n#11 \\\/home\\\/www\\\/cloud\\\/lib\\\/private\\\/Server.php(969): OC\\\\ServerContainer->query('DatabaseConnect...')\\n#12 \\\/home\\\/www\\\/cloud\\\/lib\\\/private\\\/legacy\\\/db.php(56): OC\\\\Server->getDatabaseConnection()\\n#13 \\\/home\\\/www\\\/cloud\\\/lib\\\/private\\\/legacy\\\/db.php(133): OC_DB::prepare('SHOW SERVER_VER...', NULL, NULL)\\n#14 \\\/home\\\/www\\\/cloud\\\/lib\\\/private\\\/legacy\\\/util.php(880): OC_DB::executeAudited('SHOW SERVER_VER...')\\n#15 \\\/home\\\/www\\\/cloud\\\/lib\\\/private\\\/legacy\\\/util.php(860): OC_Util::checkDatabaseVersion()\\n#16 \\\/home\\\/www\\\/cloud\\\/lib\\\/base.php(587): OC_Util::checkServer(Object(OC\\\\AllConfig))\\n#17 \\\/home\\\/www\\\/cloud\\\/lib\\\/base.php(967): OC::init()\\n#18 \\\/home\\\/www\\\/cloud\\\/index.php(37): require_once('\\\/home\\\/www\\\/cloud...')\\n#19 {main}\",\"File\":\"\\\/home\\\/www\\\/cloud\\\/lib\\\/private\\\/DB\\\/Connection.php\",\"Line\":58}","level":3,"time":"2016-07-31T20:39:56+00:00","method":"POST","url":"\/index.php\/settings\/integrity\/index.php","user":"--"}

```

**Comment by smy213** [comment]
I had this discussed [on central.owncloud.org "Installation 9.1 without creating a new database possible?"](https://central.owncloud.org/t/installation-9-1-without-creating-a-new-database-possible/1227) before creating an issue here.

**Comment by DeepDiver1975** [comment]
this was at least possible in the past - I'm not aware of any breakage in this area .... let's see ...

**Comment by PVince81** [comment]
I think you can use an existing database if you setup ownCloud using the web UI instead of the CLI.

**Comment by PVince81** [comment]
Well, it is possible with MySQL databases. Maybe the PostgreSQL code works differently ?

**Comment by PVince81** [comment]
Apparently not possible with MySQL either: https://github.com/owncloud/core/issues/27743

**Comment by tflidd** [comment]
User just reported on the forum that it works with an old 8 version (not sure which of the 8.x versions):

https://central.owncloud.org/t/webhost-wont-let-me-create-a-mysql-db-user/7724/7?u=tflidd

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).

**Comment by andrewjones216** [comment]
Hi, I don't think this should have been closed this is a real issue that was put on the backlog milestone.
I don't understand why loads of relevant cases are being closed at the moment?

**Comment by phil-davis** [comment]
You can thank the bot for that! Feel free to reopen if the issue is still a problem and relevant to fix...

**Comment by PVince81** [comment]
Feel free to submit a PR to move this forward

**Comment by jokinen77** [comment]
I encountered this problem today... Is there any progress? I'm running docker and postgresql. Docker image doesn't start because it fails to "The username is already being used".  Meaby change the database initialization "insert if not exists" like fix this?

**Comment by cdutsov** [comment]
Same problem here with MySQL. I cannot find a solution so far.
