### ISSUE TITLE
Delete non-existing file from index when deleting it

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#25793]
### Steps to reproduce
1. Create txt-file in web-interface
2. Delete file manually on the file system (which you shouldn't do)
3. Delete file via web-interface

### Expected behaviour
File is deleted from owncloud file index.

### Actual behaviour
After clicking on delete, the file seems to be deleted. If you navigate back to the same folder, the file seems to be back again. There is nothing in the owncloud.log!

### Deleting via client
If you delete via client, you get an error:
````
{"reqId":"uz4X0ynWciJrWP+ilrPn","remoteAddr":"2a02:xxxx:58f0:9632:35ea","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 403 Forbidden\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Forbidden\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OC\\\\Connector\\\\Sabre\\\\File->delete()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('temp\\\/test.txt')\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":315}","level":0,"time":"August 13, 2016 09:05:09","method":"DELETE","url":"\/owncloud\/remote.php\/webdav\/temp\/test.txt"}
````
If you try on the client to update the file, you get this error:
````
{"reqId":"O8s6BeKCgT+0Gp3N5Foz","remoteAddr":"2a02:xxxx:58f0:9632:35ea","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"temp\\\/test.txt\\\" is locked\",\"Exception\":\"OC\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(115): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #42)\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('test.txt', Resource id #42)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('temp\\\/test.txt', Resource id #42, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":172}","level":4,"time":"August 13, 2016 09:07:58","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/temp\/test.txt"}
````

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** Maria-DB

**PHP version:** 7.0 (dot-deb-packages

**ownCloud version:** 8.2.7

**Updated from an older ownCloud or fresh install:** updated

**The content of config/config.php:**

```
{
    "system": {
        "installed": true,
        "dbtype": "mysql",
        "dbname": "cloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "",
        "forcessl": true,
        "blacklisted_files": [
            ".htaccess"
        ],
        "allow_user_to_change_display_name": true,
        "updatechecker": false,
        "has_internet_connection": true,
        "enablebackup": false,
        "datadirectory": "\/var\/www\/owncloud\/data",
        "version": "8.2.7.1",
        "installedat": "1325006970.14",
        "lastupdatedat": "1329928732.51",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "log_rotate_size": 100000000,
        "instanceid": "507effec80781",
        "maintenance": false,
        "theme": "",
        "trusted_domains": [
            "example.com",
            "example.net"
        ],
        "asset-pipeline.enabled": false,
        "overwritewebroot": "\/owncloud",
        "overwrite.cli.url": "https:\/\/example.com\/owncloud",
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "example.com",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 90,
        "debug": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0
        }
    }
}
```

**Are you using external storage, if yes which one:** sftp, but this test was run on primary local storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 48

**Operating system:** OS X Mavericks

**Comment by PVince81** [comment]
9.1 should have a fix https://github.com/owncloud/core/pull/24813

backport would be slightly risky

**Comment by PVince81** [comment]
Should work already in 9.1.1
