### ISSUE TITLE
Federated reshare regression on single server

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25807]
The test test_remoteShareFile fails on stable9.1 and v9.1.0 but runs fine on stable9.

```
2016-08-15 17:49:05,500 - ERROR - sharee_two - File /home/vincent/work/smashdir/test_remoteShareFile/sharee_two/TEST_FILE_USER_RESHARE.dat does not exist but should error_check(os.path.exists(fn), "File %s does not exist but should" % fn) failed in expect_exists() ["/home_ssd/vincent/work/workspace/smashbox/python/smashbox/utilities/__init__.py" at line 795]
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
2016-08-15 17:49:07,009 - ERROR - sharee_two - File /home/vincent/work/smashdir/test_remoteShareFile/sharee_two/TEST_FILE_USER_RESHARE.dat does not exist but should error_check(os.path.exists(fn), "File %s does not exist but should" % fn) failed in expect_exists() ["/home_ssd/vincent/work/workspace/smashbox/python/smashbox/utilities/__init__.py" at line 795]
2016-08-15 17:49:10,139 - ERROR - sharee_two - 2 error(s) reported
SUMMARY:smash.:Elapsed time: 37s (0:00:37.811626)
CRITICAL:smash.:Aborting run -- non-zero exit code (2)
```

Detail:

```
********************************************************************************
(2) sharee_two:  SHAREE TWO CREATES WORKDIR
********************************************************************************
2016-08-15 17:48:40,504 - INFO - sharee_one - running 'mkdir -p /home/vincent/work/smashdir/test_remoteShareFile/sharee_one'
2016-08-15 17:48:40,504 - INFO - sharee_two - running 'mkdir -p /home/vincent/work/smashdir/test_remoteShareFile/sharee_two'
2016-08-15 17:48:40,509 - INFO - sharee_one - make_workdir /home/vincent/work/smashdir/test_remoteShareFile/sharee_one
2016-08-15 17:48:40,509 - INFO - sharer - make_workdir /home/vincent/work/smashdir/test_remoteShareFile/sharer
2016-08-15 17:48:40,509 - INFO - sharee_two - make_workdir /home/vincent/work/smashdir/test_remoteShareFile/sharee_two
...skipping...
wncloud://user3:test@127.0.0.1/owncloud/remote.php/webdav/ >> /home/vincent/work/smashdir/test_remoteShareFile/sharee_two-ocsync.step09.cnt000.log
 2>&1'
2016-08-15 17:49:02,537 - INFO - sharee_two - sync cmd is: /usr/bin/owncloudcmd --trust /home/vincent/work/smashdir/test_remoteShareFile/sharee_tw
o/ owncloud://user3:test@127.0.0.1/owncloud/remote.php/webdav/ >> /home/vincent/work/smashdir/test_remoteShareFile/sharee_two-ocsync.step09.cnt000
.log 2>&1
2016-08-15 17:49:02,537 - INFO - sharee_two - sync finished: 0:00:00.591869
2016-08-15 17:49:02,537 - INFO - sharee_two - running 'ls -lh --full-time /home/vincent/work/smashdir/test_remoteShareFile/sharee_two'
2016-08-15 17:49:02,541 - INFO - sharee_two - stdout: total 4.0K
-rw-r--r-- 1 vincent users 163 2016-08-15 17:48:40.000000000 +0200 welcome.txt

2016-08-15 17:49:02,541 - INFO - sharee_two - Listing remote shares for user user3
2016-08-15 17:49:03,087 - INFO - sharee_two - Accepting share 4 for user user3
2016-08-15 17:49:04,811 - INFO - sharee_two - running '/usr/bin/owncloudcmd --trust /home/vincent/work/smashdir/test_remoteShareFile/sharee_two/ o
wncloud://user3:test@127.0.0.1/owncloud/remote.php/webdav/ >> /home/vincent/work/smashdir/test_remoteShareFile/sharee_two-ocsync.step09.cnt001.log
 2>&1'
2016-08-15 17:49:05,477 - INFO - sharee_two - sync cmd is: /usr/bin/owncloudcmd --trust /home/vincent/work/smashdir/test_remoteShareFile/sharee_tw
o/ owncloud://user3:test@127.0.0.1/owncloud/remote.php/webdav/ >> /home/vincent/work/smashdir/test_remoteShareFile/sharee_two-ocsync.step09.cnt001
.log 2>&1
2016-08-15 17:49:05,477 - INFO - sharee_two - sync finished: 0:00:00.665529
2016-08-15 17:49:05,477 - INFO - sharee_two - running 'ls -lh --full-time /home/vincent/work/smashdir/test_remoteShareFile/sharee_two'
2016-08-15 17:49:05,481 - INFO - sharee_two - stdout: total 4.0K
-rw-r--r-- 1 vincent users 163 2016-08-15 17:48:40.000000000 +0200 welcome.txt

2016-08-15 17:49:05,481 - INFO - sharee_two - Checking that /home/vincent/work/smashdir/test_remoteShareFile/sharee_two/TEST_FILE_USER_RESHARE.dat
 is present in local directory for Sharee Two
2016-08-15 17:49:05,500 - ERROR - sharee_two - File /home/vincent/work/smashdir/test_remoteShareFile/sharee_two/TEST_FILE_USER_RESHARE.dat does not exist but should error_check(os.path.exists(fn), "File %s does not exist but should" % fn) failed in expect_exists() ["/home_ssd/vincent/work/workspace/smashbox/python/smashbox/utilities/__init__.py" at line 795]
```

**Comment by PVince81** [comment]
Could be one of these:
```
# possible first bad commit: [a3813c55dacb4df2a537dd0e7589f3014aa68780] Merge pull request #24124 from owncloud/encryped-size-progation
# possible first bad commit: [606b756a94643eaae87e18b39f6c75e6d18fec7e] Merge pull request #23918 from owncloud/cruds-for-federated-shares
# possible first bad commit: [2a6a336e873db394e9912de20478645f3e4b8fc4] always share with same default permissions, no special handling for remote shares
# possible first bad commit: [2edbb7d4bd65db3aae4c2243da58c987087d32a8] if share-permissions exists we use this information as indicator to check if the file has changed or not
# possible first bad commit: [e906796f99eaaea26cfbb3055ccc27024470b410] ask for share-permissions on propfind
```

But I need to redo the bisect because these commits produce different error messages than v9.1.0:

v9.1.0:
```
2016-08-15 19:20:44,889 - ERROR - sharee_two - File /home/vincent/work/smashdir/test_remoteShareFile/sharee_two/TEST_FILE_USER_RESHARE.dat does not exist but should error_check(os.path.exists(fn), "File %s does not exist but should" % fn) failed in expect_exists() ["/home/vincent/work/workspace/smashbox/python/smashbox/utilities/__init__.py" at line 795]
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
2016-08-15 19:20:46,441 - ERROR - sharee_two - File /home/vincent/work/smashdir/test_remoteShareFile/sharee_two/TEST_FILE_USER_RESHARE.dat does not exist but should error_check(os.path.exists(fn), "File %s does not exist but should" % fn) failed in expect_exists() ["/home/vincent/work/workspace/smashbox/python/smashbox/utilities/__init__.py" at line 795]
2016-08-15 19:20:49,403 - ERROR - sharee_two - 2 error(s) reported
SUMMARY:smash.:Elapsed time: 36s (0:00:36.100397)
CRITICAL:smash.:Aborting run -- non-zero exit code (2)
```

those commits:
```
2016-08-15 19:19:47,403 - ERROR - sharee_one - An error occurred while sharing the file error_check(result != -1, "An error occurred while sharing the file") failed in sharee_one() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_remoteShareFile.py" at line 202]
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
2016-08-15 19:19:48,761 - ERROR - sharee_two - File /home/vincent/work/smashdir/test_remoteShareFile/sharee_two/TEST_FILE_USER_RESHARE.dat does not exist but should error_check(os.path.exists(fn), "File %s does not exist but should" % fn) failed in expect_exists() ["/home/vincent/work/workspace/smashbox/python/smashbox/utilities/__init__.py" at line 795]
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
2016-08-15 19:19:49,845 - ERROR - sharee_two - File /home/vincent/work/smashdir/test_remoteShareFile/sharee_two/TEST_FILE_USER_RESHARE.dat does not exist but should error_check(os.path.exists(fn), "File %s does not exist but should" % fn) failed in expect_exists() ["/home/vincent/work/workspace/smashbox/python/smashbox/utilities/__init__.py" at line 795]
```

**Comment by PVince81** [comment]
Okay, for the next run: good cc4efc4, bad v9.1.0

**Comment by PVince81** [comment]
Started happening with 7b25839bd51b3b6cd920209c254f014c03437113 from the flat federated reshare https://github.com/owncloud/core/pull/24603

Now the question is whether it's a legitimate error or the test needs to be adjusted.

**Comment by DeepDiver1975** [comment]
adding to ci - https://ci.owncloud.org/job/smashbox-on-docker-daily-stable9.1/

**Comment by PVince81** [comment]
okay... I just tested this manually in the web UI, and federated reshares is broken...

**Comment by PVince81** [comment]
### Steps:

1. Create three users "user1", "user2" and "user3"
1. Login as "user1"
1. Create a file "reshare.txt" with some contents
1. Share "reshare.txt" with "user2@localhost/owncloud"
1. Login as "user2"
1. Accept the share
1. Share "reshare.txt" with "user3@localhost/owncloud"
1. Login as "user3"
1. Accept the share

### Expected
Received share "reshare.txt" appears in the file list

### Actual
The file doesn't appear at all.

### Versions
master/9.2 pre-alpha 74bd2c59546e0d105e960c77f4c7f4902168d04c

```
{"reqId":"SpKFIiESex8LmjpCMfeG","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(87): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/public.php(75): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-08-29T10:32:49+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/","user":"--"}
{"reqId":"c55mvp+SzSoNXtJ5jFCn","remoteAddr":"127.0.0.1","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-29T10:32:49+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/","user":"--"}
{"reqId":"c55mvp+SzSoNXtJ5jFCn","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getPath() on null at \/srv\/www\/htdocs\/owncloud\/apps\/dav\/appinfo\/v1\/publicwebdav.php#77","level":3,"time":"2016-08-29T10:32:49+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/","user":"--"}
{"reqId":"JXX8QG3KMnHP0+Lnli0L","remoteAddr":"127.0.0.1","app":"core","message":"Exception while scanning storage \"shared::9be4b23b1251a6c4ec9a8868c6c78df7\": Sabre\\HTTP\\ClientHttpException: Internal Server Error","level":3,"time":"2016-08-29T10:32:49+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"user3"}
{"reqId":"\/8Y6jMpTaUqnwOpqE3+n","remoteAddr":"127.0.0.1","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-29T10:32:49+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/","user":"--"}
{"reqId":"\/8Y6jMpTaUqnwOpqE3+n","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getPath() on null at \/srv\/www\/htdocs\/owncloud\/apps\/dav\/appinfo\/v1\/publicwebdav.php#77","level":3,"time":"2016-08-29T10:32:49+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/","user":"--"}
{"reqId":"JXX8QG3KMnHP0+Lnli0L","remoteAddr":"127.0.0.1","app":"core","message":"Exception while scanning storage \"shared::9be4b23b1251a6c4ec9a8868c6c78df7\": Sabre\\HTTP\\ClientHttpException: Internal Server Error","level":3,"time":"2016-08-29T10:32:49+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"user3"}
```

**Comment by PVince81** [comment]
Right, it seems it's because the owner is wrong:
```
MariaDB [owncloud]> select * from oc_share;
+----+------------+--------------------------+----------------------------------+--------------------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
| id | share_type | share_with               | uid_owner                        | uid_initiator            | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token           | mail_send |
+----+------------+--------------------------+----------------------------------+--------------------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
|  2 |          6 | user2@localhost/owncloud | user1                            | user1                    |   NULL | file      | 17          | NULL        |          17 |             |          19 | 1472466605 |        0 | NULL       | mWEox2hvTW0SDBd |         0 |
|  3 |          6 | user3@localhost/owncloud | user1@http://localhost/owncloud/ | user2                    |   NULL | file      | 32          | NULL        |          32 |             |          19 | 1472466622 |        0 | NULL       | HNV5X1M8cB4z7sb |         0 |
|  4 |          6 | user3@localhost/owncloud | user1                            | user2@localhost/owncloud |   NULL | file      | 17          | NULL        |          17 |             |          19 | 1472466623 |        0 | NULL       | HNV5X1M8cB4z7sb |         0 |
+----+------------+--------------------------+----------------------------------+--------------------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
```

A recent change to `getOwner()` made it return the full federated id instead of the current user. This made the logic write the wrong name in the database. This really needs a new and better API to distinguish both...

**Comment by SergioBertolinSG** [comment]
Reproduced in stable9.1 with same logs ```{"reqId":"G7\/oSFOs2jTt4xFgg4T2","remoteAddr":"172.17.0.1","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-29T11:02:53+00:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}```

**Comment by PVince81** [comment]
@SergioBertolinSG this one entry is harmless.

The sad part here is that we won't be able to accurately repair such shares. We could try and detect the bogus "@" in the owner's name, but needs to be distinguished from email addresses. So maybe these shares should simply be discarded and ask the users to share again.

**Comment by SergioBertolinSG** [comment]
Tested using two servers running stable9.1, no problems, federated shared correctly.

**Comment by PVince81** [comment]
@SergioBertolinSG confirmed working with three separate instances.

Now for the sake of clarity, let me post the database contents of the three.

There are three users: user1@localhost/owncloud shares with user2@localhost/owncloudtest who reshares with user3@localhost/owncloudtest2. As per the logic, when resharing "owncloudtest" will tell "owncloud" to share from user1 in behalf of user2. So in the end the shares are all from user1.

DB of user1@localhost/owncloud:
```
MariaDB [owncloud]> select * from oc_share;
+----+------------+-------------------------------+-----------+------------------------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
| id | share_type | share_with                    | uid_owner | uid_initiator                | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token           | mail_send |
+----+------------+-------------------------------+-----------+------------------------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
|  3 |          6 | user2@localhost/owncloudtest  | user1     | user1                        |   NULL | file      | 29          | NULL        |          29 |             |          19 | 1472477045 |        0 | NULL       | YxZFQQ1G3x2hSrY |         0 |
|  5 |          6 | user3@localhost/owncloudtest2 | user1     | user2@localhost/owncloudtest |   NULL | file      | 29          | NULL        |          29 |             |          19 | 1472477431 |        0 | NULL       | yA9xrunvMD6vKI0 |         0 |
+----+------------+-------------------------------+-----------+------------------------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
2 rows in set (0.00 sec)

MariaDB [owncloud]> select * from oc_share_external;
Empty set (0.00 sec)
```

DB of user2@localhost/owncloudtest:
```
MariaDB [owncloudtest]> select * from oc_share;
+----+------------+-------------------------------+----------------------------------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
| id | share_type | share_with                    | uid_owner                        | uid_initiator | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token           | mail_send |
+----+------------+-------------------------------+----------------------------------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
|  2 |          6 | user3@localhost/owncloudtest2 | user1@http://localhost/owncloud/ | user2         |   NULL | file      | 22          | NULL        |          22 |             |          19 | 1472477431 |        0 | NULL       | yA9xrunvMD6vKI0 |         0 |
+----+------------+-------------------------------+----------------------------------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
1 row in set (0.00 sec)

MariaDB [owncloudtest]> select * from oc_share_external;
+----+----------------------------+-----------+-----------------+----------+--------------+-------+-------+--------------+----------------------------------+----------+
| id | remote                     | remote_id | share_token     | password | name         | owner | user  | mountpoint   | mountpoint_hash                  | accepted |
+----+----------------------------+-----------+-----------------+----------+--------------+-------+-------+--------------+----------------------------------+----------+
|  1 | http://localhost/owncloud/ |         3 | YxZFQQ1G3x2hSrY |          | /reshare.txt | user1 | user2 | /reshare.txt | f3289e692129b677ae5f2101f2be25e4 |        1 |
+----+----------------------------+-----------+-----------------+----------+--------------+-------+-------+--------------+----------------------------------+----------+
1 row in set (0.00 sec)

MariaDB [owncloudtest]> select * from oc_federated_reshares;
+----------+-----------+
| share_id | remote_id |
+----------+-----------+
|        2 |         5 |
+----------+-----------+
1 row in set (0.00 sec)
```

DB of user3@localhost/owncloudtest2:
```
MariaDB [owncloudtest2]> select * from oc_share;
Empty set (0.00 sec)

MariaDB [owncloudtest2]> select * from oc_share_external;
+----+----------------------------+-----------+-----------------+----------+--------------+-------+-------+--------------+----------------------------------+----------+
| id | remote                     | remote_id | share_token     | password | name         | owner | user  | mountpoint   | mountpoint_hash                  | accepted |
+----+----------------------------+-----------+-----------------+----------+--------------+-------+-------+--------------+----------------------------------+----------+
|  1 | http://localhost/owncloud/ |         5 | yA9xrunvMD6vKI0 |          | /reshare.txt | user1 | user3 | /reshare.txt | f3289e692129b677ae5f2101f2be25e4 |        1 |
+----+----------------------------+-----------+-----------------+----------+--------------+-------+-------+--------------+----------------------------------+----------+
1 row in set (0.00 sec)

MariaDB [owncloudtest2]> select * from oc_federated_reshares;
Empty set (0.00 sec)
```

Now this all looks nice. But when sharing all from a single instance to itself, it gives the entries from https://github.com/owncloud/core/issues/25807#issuecomment-243095073 which don't seem to look exactly like the working pattern. Maybe there is some logic-magic based on file_source or so that breaks the shares.

**Comment by PVince81** [comment]
In total there are three oc_share entries.
Let's compare them closely:

- first entry: user1 shares with user2
    - single server:
```
|  2 |          6 | user2@localhost/owncloud | user1                            | user1                    |   NULL | file      | 17          | NULL        |          17 |             |          19 | 1472466605 |        0 | NULL       | mWEox2hvTW0SDBd |         0 |
```
    - multiple servers:
```
|  3 |          6 | user2@localhost/owncloudtest  | user1     | user1                        |   NULL | file      | 29          | NULL        |          29 |             |          19 | 1472477045 |        0 | NULL       | YxZFQQ1G3x2hSrY |         0 |
```

- second entry: user2 shares with user3
   - single server:
```
|  3 |          6 | user3@localhost/owncloud | user1@http://localhost/owncloud/ | user2                    |   NULL | file      | 32          | NULL        |          32 |             |          19 | 1472466622 |        0 | NULL       | HNV5X1M8cB4z7sb |         0 |
```
   - multiple server:
```
|  5 |          6 | user3@localhost/owncloudtest2 | user1     | user2@localhost/owncloudtest |   NULL | file      | 29          | NULL        |          29 |             |          19 | 1472477431 |        0 | NULL       | yA9xrunvMD6vKI0 |         0 |
```

- third entry: user1 shares with user3 (auto-generated through flat reshare logic)
   - single server:
```
|  4 |          6 | user3@localhost/owncloud | user1                            | user2@localhost/owncloud |   NULL | file      | 17          | NULL        |          17 |             |          19 | 1472466623 |        0 | NULL       | HNV5X1M8cB4z7sb |         0 |
```
   - multiple server:
```
|  2 |          6 | user3@localhost/owncloudtest2 | user1@http://localhost/owncloud/ | user2         |   NULL | file      | 22          | NULL        |          22 |             |          19 | 1472477431 |        0 | NULL       | yA9xrunvMD6vKI0 |         0 |
```

**Comment by PVince81** [comment]
It looks like in the case of the single server, the user name is correct but the format is different.
In some fields the value was supposed to be a local user but appears as federated cloud id, and on other fields it's the reverse.

Downgrading ticket to high for now as the regular feature does work.

**Comment by PVince81** [comment]
I just tested the same "multiple servers" scenario but create three users "user1", "user2" and "user3" on all three servers. The feature still works fine. So we can already exclude potential bugs related to having a local user with the same uid as a remote one.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
