### ISSUE TITLE
part/chunk files over filename size limit aborting sync

### ISSUE THREAD

**Issue by rkitover** [owncloud/core#25891]
### Steps to reproduce
1. use a file store on an FS with a 255 character limit, e.g. I am using OS X HFS+
2. create a very long file name in a synced directory on the client, e.g. 240 characters
### Expected behaviour

Long file names up to 255 characters should be synced correctly. Or at the very least skipped.
### Actual behaviour

The sync is completely aborted on the client because of the server exception.
The messages from owncloud.log are below.
### Server configuration

**Operating system**: OS X El Capitan 10.11.6

**Web server:** homebrew/apache/httpd24: stable 2.4.18

**Database:** postgresql: stable 9.5.4

**PHP version:** PHP 7.0.9 (cli) (built: Aug 21 2016 04:02:51) ( NTS )

**ownCloud version:** github: e5b91af

**Updated from an older ownCloud or fresh install:** updated from 9.0.2

**Where did you install ownCloud from:** github

**Signing status (ownCloud 9.0 and above):**

```
Integrity checker has been disabled. Integrity cannot be verified.
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - files_external
  - testing
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc1f9k2uq0qn",
        "datadirectory": "\/Volumes\/iMacBackup\/owncloud\/",
        "dbtype": "pgsql",
        "dbhost": "localhost",
        "dbname": "owncloud",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "arkady-imac.local",
            "arkady-imac",
            "akitover.crabdance.com"
        ],
        "overwrite.cli.url": "http:\/\/localhost",
        "version": "9.2.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "loglevel": 0
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Safari

**Operating system:** OS X El Capitan 10.11.6
#### Web server error log

Don't have the log for these requests anymore.
#### ownCloud log (data/owncloud.log)

```
{"reqId":"d9TTzzhMUUrWYYMqdfpC","remoteAddr":"::1","app":"PHP","message":"fopen(\/Volumes\/iMacBackup\/owncloud\/\/akitover\/cache\/Lyubich e
ds.(Operator Theory_ Advances and Applications 98) Yu. Lyubich,  V. Tkachenko  (auth.),  I. Gohberg,  Yu. Lyubich  (eds.)-New Results in Oper
ator Theory and Its Applications_ The Israel M. Glazman Memori.pdf-chunking-2286594033-0.Z9kdDh9qzhYqEfVd.part): failed to open stream: File
name too long at \/usr\/local\/var\/www\/htdocs\/owncloud\/lib\/private\/Files\/Storage\/Local.php#273","level":3,"time":"2016-08-21T08:20:29
+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/Books\/L\/Lyubich%20eds.(Operator%20Theory_%20Advances%20and%20Applications%209
8)%20Yu.%20Lyubich,%20%20V.%20Tkachenko%20%20(auth.),%20%20I.%20Gohberg,%20%20Yu.%20Lyubich%20%20(eds.)-New%20Results%20in%20Operator%20Theor
y%20and%20Its%20Applications_%20The%20Israel%20M.%20Glazman%20Memori.pdf-chunking-2286594033-2-0","user":"akitover"}
{"reqId":"d9TTzzhMUUrWYYMqdfpC","remoteAddr":"::1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 1000
0000 got 0\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/var\\\/www\\\/htdocs\\\/
owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource i
d #382)\\n#1 \\\/usr\\\/local\\\/var\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(136): OCA\\\\D
AV\\\\Connector\\\\Sabre\\\\File->put(Resource id #382)\\n#2 \\\/usr\\\/local\\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav
\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('Lyubich eds.(Op...', Resource id #382)\\n#3 \\
\/usr\\\/local\\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->
createFile('Books\\\/L\\\/Lyubich...', Resource id #382, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\
HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/local\\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\
\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/usr\\\/local\\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdpart
y\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/usr\\\/local\\\/var\\\
/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\
\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/usr\\\/local\\\/var\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/
v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/usr\\\/local\\\/var\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(164): require_on
ce('\\\/usr\\\/local\\\/var\\\/...')\\n#10 {main}\",\"File\":\"\\\/usr\\\/local\\\/var\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/
Connector\\\/Sabre\\\/File.php\",\"Line\":404,\"User\":\"akitover\"}","level":4,"time":"2016-08-21T08:20:29+00:00","method":"PUT","url":"\/ow
ncloud\/remote.php\/webdav\/Books\/L\/Lyubich%20eds.(Operator%20Theory_%20Advances%20and%20Applications%2098)%20Yu.%20Lyubich,%20%20V.%20Tkac
henko%20%20(auth.),%20%20I.%20Gohberg,%20%20Yu.%20Lyubich%20%20(eds.)-New%20Results%20in%20Operator%20Theory%20and%20Its%20Applications_%20Th
e%20Israel%20M.%20Glazman%20Memori.pdf-chunking-2286594033-2-0","user":"akitover"}
```

**Comment by PVince81** [comment]
Please note that running ownCloud on an Apple server isn't official supported.

However your request for a limitation is valid due to other related issues: https://github.com/owncloud/core/issues/25425
Is this closer to what you are experiencing ? If yes, we can close this as duplicate.

**Comment by rkitover** [comment]
@PVince81 linux has the same limitation:

```txt
rkitover@caelum ~ % uname -a
Linux caelum 4.1.5-x86_64-linode61 #7 SMP Mon Aug 24 13:46:31 EDT 2015 x86_64 GNU/Linux
rkitover@caelum ~ % mount | grep ' / '
/dev/sda on / type ext3 (rw,relatime,errors=remount-ro,barrier=0,data=writeback)
rkitover@caelum ~ % touch $(perl -le 'print("x" x 255)').txt
touch: cannot touch 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt': File name too long
```

The limitation is not added, it's part of regular linux file systems.

Yes #25425 is the same thing.

**Comment by rkitover** [comment]
A nice link someone gave me:

https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

as you can see, most file systems have the 255 limit.

**Comment by PVince81** [comment]
@rkitover indeed. I might have mixed it up with the maximum path length or dir depth.

Anyway, we need to find a way to prevent such cases to fail.

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/25425, need to use a different naming scheme for chunk files.
