### ISSUE TITLE
htaccess-options not working at webhoster domainfactory/ with Mac Os X El Capitan

### ISSUE THREAD

**Issue by daftmilk** [owncloud/core#25913]
### Steps to reproduce
1. Use webhosting at domainfactory (http://df.eu)
2. install owncloud and go to admin panel
3. misleading security warnings about missing options in .htaccess-file appear

### Expected behaviour
Instead of complaining about missing options in .htaccess it should at least suggest this possibly fix:

```
<IfModule mod_env.c>
    # Add security and privacy related headers
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-XSS-Protection "1; mode=block"
    Header always set X-Robots-Tag "none"
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set X-Download-Options "noopen"
    Header always set X-Permitted-Cross-Domain-Policies "none"
    Header set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
    SetEnv modHeadersAvailable true
  </IfModule>
```

I'd love it, if owncloud would fix the .htaccess itself.
Code signing should accept a changed .htaccess, because it is of no help, if code signing keeps complaining. It is tempting to ignore codesigning altogether.

For those who have similar problems and can't connect their Mac Os X Calendar or Contacts app, add this to your .htaccess at the root of your webspace:

```
## help el capitan find owncloud
Redirect 301 /.well-known/carddav /owncloud/remote.php/carddav
Redirect 301 /.well-known/caldav /owncloud/remote.php/caldav
```

### Actual behaviour
content of .htaccess, that is not recognized (does not work with domainfactory apparently)

Original partial content of .htaccess:
```
<IfModule mod_env.c>
    # Add security and privacy related headers
    Header set X-Content-Type-Options "nosniff"
    Header set X-XSS-Protection "1; mode=block"
    Header set X-Robots-Tag "none"
    Header set X-Frame-Options "SAMEORIGIN"
    Header set X-Download-Options "noopen"
    Header set X-Permitted-Cross-Domain-Policies "none"
    SetEnv modHeadersAvailable true
</IfModule>
```

### Server configuration
**Operating system**: x86_64 GNU/Linux

**Web server:** Apache/2.4.20

**Database:** MySQL 5

**PHP version:** PHP Version 5.6.12

**ownCloud version:** 9.10

**Updated from an older ownCloud or fresh install:** manual upgrade from 9.0.4

**Where did you install ownCloud from:** bz2-Archive (Updater always fails horribly)

**Signing status (ownCloud 9.0 and above):** hash_mismatch on .htaccess (I modified it, so it works, see above)

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => ab5f4c44ba2f9c66f2ed25c3ad3d84660b2808cca11ffa8fe2778a648a054d8ada495a0bf4715dc873aac1efe8dfd92a72f9a24441d8f5240834e639325fd892
                            [current] => 4745305b4f8e868ca5ecf81d6f0f3a9493c45fd4d7ae73d7aacc9272ca35151e993d21cb8d263aa5de333c4cd3fe5649f874e56ca8b366f3c16e4facb059baf0
                        )

                )

        )

)
```

**List of activated apps:**

```
  - activity: 2.3.2
  - calendar: 1.3.2
  - comments: 0.3.0
  - contacts: 1.3.1.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocbe8f65906e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.XXX-REDACTED-XXX"
        ],
        "maintenance": false,
        "datadirectory": "\/kunden\/XXX-REDACTED-XXX\/webseiten\/XXX-REDACTED-XXX\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/XXX-REDACTED-XXX\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "XXX-REDACTED-XXX",
        "dbhost": "XXX-REDACTED-XXX",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "forcessl": true,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "XXX-REDACTED-XXX",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_domain": "XXX-REDACTED-XXX",
        "mail_from_address": "owncloud",
        "loglevel": 0,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/tmp",
        "trashbin_retention_obligation": "auto",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/owncloud"
    }
}
```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ownCloud.app/Calendar.app/Contacts.app on mac os x/ios

### Client configuration
**Browser:** Safari Version 9.1.2 (11601.7.7)

**Operating system:** Mac Os X 10.11

#### Web server error log
```
not accessible
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"V7waVREDACTED","remoteAddr":"87.REDACTED","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/carddav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/remote.php(164): require_once('\\\/kunden\\\/XXX-REDACTED-XXX_...')\\n#6 {main}\",\"File\":\"\\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-08-23T09:41:42+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/carddav\/addressbooks\/XXX-REDACTED-XXX\/","user":"--"}
{"reqId":"V7wabREDACTED","remoteAddr":"87.REDACTED","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/carddav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/remote.php(164): require_once('\\\/kunden\\\/XXX-REDACTED-XXX_...')\\n#6 {main}\",\"File\":\"\\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-08-23T09:42:04+00:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/carddav\/principals\/XXX-REDACTED-XXX\/","user":"--"}
{"reqId":"V7wadREDACTED","remoteAddr":"87.REDACTED","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/carddav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/remote.php(164): require_once('\\\/kunden\\\/XXX-REDACTED-XXX_...')\\n#6 {main}\",\"File\":\"\\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-08-23T09:42:12+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/carddav\/addressbooks\/XXX-REDACTED-XXX\/","user":"--"}
{"reqId":"V7waiREDACTED","remoteAddr":"87.REDACTED","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/carddav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/remote.php(164): require_once('\\\/kunden\\\/XXX-REDACTED-XXX_...')\\n#6 {main}\",\"File\":\"\\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-08-23T09:42:34+00:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/carddav\/principals\/XXX-REDACTED-XXX\/","user":"--"}
{"reqId":"V7wakREDACTED","remoteAddr":"87.REDACTED","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/carddav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/remote.php(164): require_once('\\\/kunden\\\/XXX-REDACTED-XXX_...')\\n#6 {main}\",\"File\":\"\\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-08-23T09:42:42+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/carddav\/addressbooks\/XXX-REDACTED-XXX\/","user":"--"}
{"reqId":"V7wakREDACTED","remoteAddr":"87.REDACTED","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/kunden\/XXX-REDACTED-XXX\/webseiten\/XXX-REDACTED-XXX\/owncloud\/lib\/private\/TempManager.php#188","level":3,"time":"2016-08-23T09:42:43+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"V7waqREDACTED","remoteAddr":"87.REDACTED","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/carddav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/remote.php(164): require_once('\\\/kunden\\\/XXX-REDACTED-XXX_...')\\n#6 {main}\",\"File\":\"\\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-08-23T09:43:04+00:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/carddav\/principals\/XXX-REDACTED-XXX\/","user":"--"}
{"reqId":"V7waqREDACTED","remoteAddr":"87.REDACTED","app":"no app in context","message":"Installation is in transit between the old Encryption (ownCloud <= 8.0)\n\t\t\tand the new encryption. Please enable the \"Default encryption module\"\n\t\t\tand run 'occ encryption:migrate'","level":2,"time":"2016-08-23T09:43:05+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin","user":"adm"}
{"reqId":"V7waqREDACTED","remoteAddr":"87.REDACTED","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/kunden\/XXX-REDACTED-XXX\/webseiten\/XXX-REDACTED-XXX\/owncloud\/lib\/private\/TempManager.php#188","level":3,"time":"2016-08-23T09:43:06+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"V7waqREDACTED","remoteAddr":"87.REDACTED","app":"no app in context","message":"Invalidating tokens older than 2016-08-22T09:43:06+00:00","level":1,"time":"2016-08-23T09:43:06+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"V7wasREDACTED","remoteAddr":"87.REDACTED","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/carddav.php(82): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/remote.php(164): require_once('\\\/kunden\\\/XXX-REDACTED-XXX_...')\\n#6 {main}\",\"File\":\"\\\/kunden\\\/XXX-REDACTED-XXX\\\/webseiten\\\/XXX-REDACTED-XXX\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-08-23T09:43:13+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/carddav\/addressbooks\/XXX-REDACTED-XXX\/","user":"--"}
```

#### Browser log
not applicable  

Seen this problem ever since using owncloud with all Browsers and different Versions of PHP. The first version I ever used was owncloud 6.

```
```

**Comment by RealRancor** [comment]
HSTS never should be applied by default and can be easily added to the bottom of the .htaccess by the user

**Comment by daftmilk** [comment]
OK, understand. So ignore HSTS for now. Did you catch the main issue?

not working, original:

```
Header set X-Content-Type-Options "nosniff"
Header set …
```

working, modified:

```
Header always set X-Content-Type-Options "nosniff"
Header always set …
```

**Comment by RealRancor** [comment]
For this question you should contact the support of your hoster or a community like http://www.apachelounge.com/
