### ISSUE TITLE
9.1 SMB external files issue

### ISSUE THREAD

**Issue by anduz** [owncloud/core#26002]
### Steps to reproduce
1. From working 9.0.2 perform a apt-get upgrade
2. Upgrade owncloud sudo -u www-data php /var/www/owncloud/occ upgrade
### Expected behaviour

Owncloud upgraded to 9.1.0 with external files working
### Actual behaviour

Owncloud upgraded to 9.1.0 with external files NOT working
### Server configuration

**Operating system**:  Ubuntu 14.04

**Web server:** Apache 2.4.7-1ubuntu4.13

**Database:** mysql 5.5.50-0ubuntu0.14.04.1

**PHP version:** php5 5.5.9+dfsg-1ubuntu4.19

**Updated from an older ownCloud or fresh install:** Updated from 9.0.2

**Where did you install ownCloud from:** Virtual Appliance 

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

Enabled:
- activity: 2.3.2
- comments: 0.3.0
- dav: 0.2.5
- documents: 0.13.1
- federatedfilesharing: 0.3.0
- federation: 0.1.0
- files: 1.5.1
- files_external: 0.6.0
- files_pdfviewer: 0.8.1
- files_sharing: 0.10.0
- files_texteditor: 2.1
- files_trashbin: 0.9.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 15.0.0
- notifications: 0.3.0
- provisioning_api: 0.5.0
- systemtags: 0.3.0
- templateeditor: 0.1
- updatenotification: 0.2.1

**The content of config/config.php:**

{
    "system": {
        "memcache.local": "\OC\Memcache\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "mail_domain": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtpport": "465",
        "mail_from_address": "owncloud",
        "instanceid": "**_REMOVED SENSITIVE VALUE**_",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "localhost",
            "**_REMOVED SENSITIVE VALUE**_",
            "**_REMOVED SENSITIVE VALUE**_",
            "**_REMOVED SENSITIVE VALUE**_",
            "**_REMOVED SENSITIVE VALUE**_"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "Europe\/Berlin",
        "loglevel": 0,
        "logfile": "\/var\/www\/owncloud\/data\/owncloud.log",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "updatechecker": false
    }
}

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no
### Client configuration

**Browser:** Chrome

**Operating system:** Windows 10
#### ownCloud log (data/owncloud.log)

```
{"reqId":"sQxWvkHDVVN17x0qgLN2","remoteAddr":"X.X.X.X","app":"core","message":"File with id \"157807\" has not been found.","level":3,"time":"2016-09-01T10:55:17+02:00","method":"GET","url":"\/index.php\/settings\/admin\/log\/download","user":"USER1"}
{"reqId":"sQxWvkHDVVN17x0qgLN2","remoteAddr":"X.X.X.X","app":"no app in context","message":"Error getting storage info for mount at \/USER1\/files\/SMB1\/","level":3,"time":"2016-09-01T10:55:17+02:00","method":"GET","url":"\/index.php\/settings\/admin\/log\/download","user":"USER1"}
```

**Comment by PVince81** [comment]
> Owncloud upgraded to 9.1.0 with external files NOT working

This isn't enough information. What exactly are the symptoms ?

**Comment by anduz** [comment]
Users see this:
![1](https://cloud.githubusercontent.com/assets/4547041/18170733/b3f9f6c6-705f-11e6-9d7b-754a21f2e0b1.PNG)
Admin page show this on external files:
![admin](https://cloud.githubusercontent.com/assets/4547041/18170747/c98493de-705f-11e6-951a-14a25707b437.PNG)
and this on Log:
![log](https://cloud.githubusercontent.com/assets/4547041/18170798/f2bd718a-705f-11e6-818d-81bbccdd41e9.PNG)

What other info can help?
I've tried to add a new external smb share, but result is the same

**Comment by anduz** [comment]
Tried this:
apt-mark hold owncloud
apt-mark hold owncloud-files
apt-mark hold owncloud-deps-php5
apt-get upgrade
reboot

> Error	no app in context	Exception: {"Exception":"OCP\\Files\\StorageNotAvailableException","Message":"Storage with mount id 7 is not available","Code":1,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(577): OC\\Files\\Storage\\FailedStorage->acquireLock('scanner::', 2, Object(OC\\Lock\\DBLockingProvider))\n#1 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(577): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('scanner::', 2, Object(OC\\Lock\\DBLockingProvider))\n#2 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(577): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('scanner::', 2, Object(OC\\Lock\\DBLockingProvider))\n#3 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(577): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('scanner::', 2, Object(OC\\Lock\\DBLockingProvider))\n#4 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(299): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('scanner::', 2, Object(OC\\Lock\\DBLockingProvider))\n#5 \/var\/www\/owncloud\/lib\/private\/files\/utils\/scanner.php(172): OC\\Files\\Cache\\Scanner->scan('', true, 3)\n#6 \/var\/www\/owncloud\/apps\/files\/command\/scan.php(131): OC\\Files\\Utils\\Scanner->scan('\/willy')\n#7 \/var\/www\/owncloud\/apps\/files\/command\/scan.php(196): OCA\\Files\\Command\\Scan->scanFiles('willy', '\/willy', false, Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Command\/Command.php(259): OCA\\Files\\Command\\Scan->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 \/var\/www\/owncloud\/core\/command\/base.php(158): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Application.php(840): OC\\Core\\Command\\Base->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Application.php(192): Symfony\\Component\\Console\\Application->doRunCommand(Object(OCA\\Files\\Command\\Scan), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Application.php(123): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 \/var\/www\/owncloud\/lib\/private\/console\/application.php(145): Symfony\\Component\\Console\\Application->run(NULL, NULL)\n#14 \/var\/www\/owncloud\/console.php(84): OC\\Console\\Application->run()\n#15 \/var\/www\/owncloud\/occ(11): require_once('\/var\/www\/ownclo...')\n#16 {main}","File":"\/var\/www\/owncloud\/lib\/private\/files\/storage\/failedstorage.php","Line":193}	2016-09-01T17:40:14+02:00
Error	no app in context	Storage failedstorage not available

**Comment by PVince81** [comment]
Do you have php5-libsmbclient installed ?

**Comment by anduz** [comment]
This is before i do the upgrade:

> apt list --installed | grep libsmbclient
> libsmbclient/now 2:4.3.9+dfsg-0ubuntu0.14.04.1 amd64 [installed,upgradable to: 2:4.3.9+dfsg-0ubuntu0.14.04.3]
> php5-libsmbclient/now 0.7.0-4.1 amd64 [installed,upgradable to: 0.7.0-7.1]

**Comment by PVince81** [comment]
@jvillafanez

**Comment by jvillafanez** [comment]
I'll need more info. So far I don't see anything wrong: the mount point became unavailable and behaves as such. The question is why or how the mount point became unavailable? Are the credentials correct? Is the user account allowed to access? Does the remote folder have any special restriction (the folder is hidden, for example)?

**Comment by anduz** [comment]
I didn't change any settings during the upgrade, so username, password and rights are the same.
Maybe it has something to do with the libsmbclient and SBS 2008, where my network shares are?
Or is there anything else involved in the connection to the smb shares?

**Comment by jvillafanez** [comment]
I'm not sure if you updated the server properly... Your errors come from */lib/private/files/storage/wrapper/wrapper.php* but those files where renamed to uppercase -> */lib/private/Files/Storage/Wrapper/Wrapper.php* in 9.1.0.

As a general rule, you should wipe out all the ownCloud installation expect the *data* and *config* folder (DB remains untouched, obviously) and unpack the new code there. You can check more info in https://doc.owncloud.org/server/9.0/admin_manual/maintenance/upgrade.html

> Tried this:
apt-mark hold owncloud
apt-mark hold owncloud-files
apt-mark hold owncloud-deps-php5
apt-get upgrade

It's just a guess, but I don't think the apt-mark hold is good. Your server might be using a mix of the old installation with the new one.

Taking advantage that you're running a VM, just take an snapshot of the VM before upgrading and upgrade normally. If something goes wrong, you can reload the previous snapshot.

**Comment by PVince81** [comment]
Closing due to lack of feedback

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
