### ISSUE TITLE
deleted files still visible in web access in files oc 9.1

### ISSUE THREAD

**Issue by Blisk** [owncloud/core#26128]
### Steps to reproduce
1. this error is in owncloud /owncloud/data/owncloud.log

### Expected behaviour
Tell us what should happen
User deleted files and they are still on web access in folders but they are greyed out and can not be deleted or removed somehow. 
This happend after I upgrade from 7.2 to 9.1.
### Actual behaviour
Tell us what happens instead

"app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":306,\"User\":\"Jack\"}","level":4,"time":"2016-09-17T08:04:36+00:00","method":"GET","url":"\/remote.php\/webdav\/documents\/Navigacija\/iGOPrimo%202\/-posamezne_datoteke-\/SpeedCam_Full_EU\/speedcam_AND.txt","user":"Jack"}

### Server configuration
**Operating system**:
centos 7.2
**Web server:**
apache 2.4.6
**Database:**
5.5.5
**PHP version:**
5.4.16
**ownCloud version:** (see ownCloud admin page)
9.1
**Updated from an older ownCloud or fresh install:**
updated from 7
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**
X
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'my.domain.net',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://my.domain.net',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_denis',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'loglevel' => 0,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto, auto',
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'php',
  'mail_domain' => ',my.domain.net',

'memcache.local' => '\OC\Memcache\APC',
'preview_libreoffice_path' => '/usr/lib64/libreoffice',

  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    11 => 'OC\\Preview\\Illustrator',
    12 => 'OC\\Preview\\Postscript',
    13 => 'OC\\Preview\\Photoshop',
    14 => 'OC\\Preview\\TIFF'
  ),

);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
firefox
**Operating system:**
win 7
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...

**Comment by PVince81** [comment]
Mind posting a screenshot of the greyed out ?
Do you mean they become greyed out when clicking the delete action and then they just stay ?
There is no logic that shows greyed out file entries before doing any action.

Please try running `occ files:scan $userid` and replace $userid with that user's id.

The error you posted is from a custom webdav endpoint "webdav/documents", not sure from which app this is from ?

**Comment by PVince81** [comment]
Any update ?

**Comment by DeepDiver1975** [comment]
Just reopen as soon as there is more info

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
