### ISSUE TITLE
"Problem loading page, reloading in 5 seconds" with PHP 7

### ISSUE THREAD

**Issue by dergilb99** [owncloud/core#26218]
### Steps to reproduce
I don't know. It comes and goes. I switched to PHP 7 yesterday.

### Expected behaviour
The webinterface is not reloading constantly.

### Actual behaviour
The webinterface is reloading constantly.

![loop](https://cloud.githubusercontent.com/assets/13220171/18832516/30fefd2a-83ec-11e6-8fdc-ae259a9129cf.png)

### Server configuration

**Operating system**:
Solaris Unix (Hosted by Strato)

**Web server:**
Apache 2.2

**Database:**
MySQL 5.5.48

**PHP version:**
7.0.107.0.10

**ownCloud version:**
9.1.1 (stable)

**Updated from an older ownCloud or fresh install:**
Update from 9.1.0

**Where did you install ownCloud from:**
mydubiousfilez.hu

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Activity 2.3.2 
Default encryption module 1.3.0 
Deleted files 0.9.0 
First run wizard 1.1 
Gallery 15.0.0 
Notifications 0.3.0 
Provisioning API 0.5.0 
Share Files 0.10.0 
Update notification 0.2.1 
Versions 1.3.0 
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'datadirectory' => '/mnt/web024/a2/74/12345678/htdocs/owncloud_data',
  'tempdirectory' => '/mnt/web024/a2/74/12345678/htdocs/owncloud_data/temp',
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '9.1.1.3',
  'dbname' => 'xxx',
  'dbhost' => 'rdbms.strato.de',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'log_rotate_size' => 31457280,
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'www.abc.de',
  ),
  'theme' => '',
  'loglevel' => 2,
  'overwrite.cli.url' => 'https://www.abc.de/owncloud',
  'htaccess.RewriteBase' => '/owncloud',
  'updater.secret' => 'xxx',
);
```

**owncloud.log**

```
{"reqId":"V@gYCMCoKxsAAGscA6kAAAFI","remoteAddr":"x.x.x.x","app":"PHP","message":"Error: Class 'OCA\\DAV\\Connector\\Sabre\\ExceptionLoggerPlugin' not found at \/mnt\/web024\/a2\/74\/12345678\/htdocs\/owncloud\/remote.php#54","level":3,"time":"2016-09-25T18:33:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"--"}
{"reqId":"V@j-88CoKxsAACes4sUAAAHa","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received","level":3,"time":"2016-09-26T11:01:30+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"V@kAuMCoKxsAAC-YRPEAAAUJ","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/mnt\\\/web024\\\/a2\\\/...')\\n#6 {main}\",\"File\":\"\\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":84,\"User\":\"user1\"}","level":4,"time":"2016-09-26T11:04:27+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"user1"}
{"reqId":"V@kAusCoKxsAACpzy34AAAPq","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/mnt\\\/web024\\\/a2\\\/...')\\n#6 {main}\",\"File\":\"\\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":84,\"User\":\"user1\"}","level":4,"time":"2016-09-26T11:04:29+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"user1"}
{"reqId":"V@kB68CoKxsAACcGMOYAAADL","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 28: Connection timed out after 20000 milliseconds","level":3,"time":"2016-09-26T11:09:57+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"V@kFY8CoKxsAAGjRROQAAABy","remoteAddr":"x.x.x.x","app":"core","message":"Could not get categories: cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received","level":3,"time":"2016-09-26T11:24:41+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/categories","user":"admin"}
{"reqId":"V@kFh8CoKxsAAHGeKQYAAAJg","remoteAddr":"x.x.x.x","app":"core","message":"Could not get categories: cURL error 28: Connection timed out after 20000 milliseconds","level":3,"time":"2016-09-26T11:25:17+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=0","user":"admin"}
{"reqId":"V@kHhMCoKxsAAE38yKEAAALi","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/mnt\\\/web024\\\/a2\\\/...')\\n#6 {main}\",\"File\":\"\\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":84,\"User\":\"user1\"}","level":4,"time":"2016-09-26T11:33:24+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"user1"}
{"reqId":"V@kHmsCoKxsAACzhM8UAAAK7","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/mnt\\\/web024\\\/a2\\\/...')\\n#6 {main}\",\"File\":\"\\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":84,\"User\":\"user1\"}","level":4,"time":"2016-09-26T11:33:47+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"user1"}
```

**server's error.log**

No entries for the last days.

**Are you using external storage, if yes which one:**

No.

**Are you using encryption:**

Yes.

**Are you using an external user-backend, if yes which one:**

No.

### Client configuration
**Browser:**
Firefox 49.0.1 (64 bit) / Edge / Opera dev 41.0

**Operating system:**

Windows 10 Pro (64 bit)

**Comment by dergilb99** [comment]
Switching back to 5.6.22 seems to resolve this issue.

**Comment by DeepDiver1975** [comment]
Anything in data/owncloud.log ???

**Comment by dergilb99** [comment]
> Anything in data/owncloud.log ???

I'm sorry, I added it to my initial post.

**Comment by DeepDiver1975** [comment]
Looks like you are having issues with the connection with the appstore - according to the timeout.

**Comment by dergilb99** [comment]
> Looks like you are having issues with the connection with the appstore - according to the timeout. 

Maybe it was a temporary thing. I try and switch back to PHP 7.

**Comment by dergilb99** [comment]
Nope. It's a PHP 7 thing.

**Comment by dergilb99** [comment]
Since I'm about to reinstall it, I will close this matter for now.

**Comment by DeepDiver1975** [comment]
> {"reqId":"V@kB68CoKxsAACcGMOYAAADL","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 28: Connection timed out after 20000 milliseconds","level":3,"time":"2016-09-26T11:09:57+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"admin"}

there is a connection timeout then trying to access the appstore

**Comment by dergilb99** [comment]
After reinstalling 9.1.1, I had this problem again, but I was able to narrow it down and I can reproduce this.

Creating a folder in the share's root folder "Wer dies liest ist doof! Muahahahaha" will trigger this, while "Wer dies liest ist doof! Muahaha" will not. Creating a subfolder "haha" will trigger this, while "ha" will not.

There seems to be problem with folder length.

Maybe it's a shared hoster's issue (I do not believe that). But I installed OC 8.2 as well (same apps, encryption, you name it), just for the lolz:

With 8.2.8 I have no such problems.

**Comment by dergilb99** [comment]
> there is a connection timeout then trying to access the appstore

If the appstore is this thingy where I can enable and disable apps: That works fine.

**Comment by DeepDiver1975** [comment]
> If the appstore is this thingy where I can enable and disable apps: That works fine.

yes ....

**Comment by dergilb99** [comment]
I'm sorry, I deleted my post. So, why is there an appstore timeout when creating (and seeing) folder names with 36 characters?

**Comment by DeepDiver1975** [comment]
To be honest this is all a bit too unspecific. There is not really anything which I can use for analysis.

According to the screenshot your issue has been related to the apps mgmt screen.
If this issue is gone and you are facing something new - please open a new issue

**Comment by dergilb99** [comment]
> According to the screenshot your issue has been related to the apps mgmt screen.

I knew it was a mistake using that one.

> If this issue is gone and you are facing something new - please open a new issue

Ok.
