### ISSUE TITLE
"Problem loading page, reloading in 5 seconds" - Reloaded.

### ISSUE THREAD

**Issue by dergilb99** [owncloud/core#26262]
### Steps to reproduce
1. Create a path with at least 36 characters in the web interface in the share's root folder

For example

"Wer dies liest ist doof! Muahahahaha"

or

"Wer dies liest ist doof! Muahaha/haha"

### Expected behaviour
The directories are created without complaining.

### Actual behaviour
The directories are created with complaining:

![1](https://cloud.githubusercontent.com/assets/13220171/18991214/508c1cf8-8717-11e6-85a6-64a4b8c5ecdb.png)

Despite this bold statement, the directory is created. And then it's stuck in a reload loop:

![2](https://cloud.githubusercontent.com/assets/13220171/18991229/65cb2bd6-8717-11e6-8050-023bf5763438.png)

After the directory is created, the loop can be triggered anytime by browsing to that directory.

### Server configuration
**Operating system**:
Solaris Unix (Hosted by Strato)

**Web server:**
Apache 2.2

**Database:**
MySQL 5.6.31

**PHP version:**
5.6.262.0

**ownCloud version:** (see ownCloud admin page)
9.1.1 (this problem does not occur with 8.2.8)

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Activity 2.3.2 
Default encryption module 1.3.0 
Deleted files 0.9.0 
First run wizard 1.1 
Gallery 15.0.0 
Notifications 0.3.0 
Provisioning API 0.5.0 
Share Files 0.10.0 
Update notification 0.2.1 
Versions 1.3.0 
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'datadirectory' => '/mnt/web024/a2/74/12345678/htdocs/owncloud_data',
  'tempdirectory' => '/mnt/web024/a2/74/12345678/htdocs/owncloud_data/temp',
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '9.1.1.3',
  'dbname' => 'xxx',
  'dbhost' => 'rdbms.strato.de',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'log_rotate_size' => 31457280,
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'overwrite.cli.url' => 'https://www.abc.de/owncloud',
  'htaccess.RewriteBase' => '/owncloud',
  'trusted_domains' => 
  array (
    0 => 'www.abc.de',
  ),
  'loglevel' => 2,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
Yes.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**

Firefox 49.0.1 (64 bit)

**Operating system:**

Windows 10 Pro (64 bit)

#### Web server error log
```
28.09.2016 14:12:12 abc.de [client x.x.x.x] PHP Fatal error:  Class 'OC\\Authentication\\Token\\DefaultTokenMapper' not found in /mnt/web024/a2/74/12345678/htdocs/owncloud/lib/private/Server.php on line 216
28.09.2016 14:12:12 abc.de [client x.x.x.x] PHP Fatal error:  Class 'OC\\Authentication\\Token\\DefaultTokenMapper' not found in /mnt/web024/a2/74/12345678/htdocs/owncloud/lib/private/Server.php on line 216
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"V@2ctMCoKxsAAAgUsWEAAAD3","remoteAddr":"x.x.x.x","app":"DeleteOrphanedItems","message":"0 orphaned system tag relations deleted","level":0,"time":"2016-09-29T22:59:00+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"V@2ctMCoKxsAAAgUsWEAAAD3","remoteAddr":"x.x.x.x","app":"DeleteOrphanedItems","message":"0 orphaned user tag relations deleted","level":0,"time":"2016-09-29T22:59:00+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"V@2ctMCoKxsAAAgUsWEAAAD3","remoteAddr":"x.x.x.x","app":"DeleteOrphanedItems","message":"0 orphaned comments deleted","level":0,"time":"2016-09-29T22:59:00+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"V@2ctMCoKxsAAAgUsWEAAAD3","remoteAddr":"x.x.x.x","app":"DeleteOrphanedItems","message":"0 orphaned comment read marks deleted","level":0,"time":"2016-09-29T22:59:00+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"V@2ctcCoKxsAAAPKrFMAAAHR","remoteAddr":"x.x.x.x","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":0,"time":"2016-09-29T22:59:02+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"V@2ctcCoKxsAAAPKrFMAAAHR","remoteAddr":"x.x.x.x","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":0,"time":"2016-09-29T22:59:03+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"V@2ctcCoKxsAAAPKrFMAAAHR","remoteAddr":"x.x.x.x","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":0,"time":"2016-09-29T22:59:04+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"V@2c4sCoKxsAAAbkrrMAAAAl","remoteAddr":"x.x.x.x","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":0,"time":"2016-09-29T22:59:47+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=disabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"V@2c4sCoKxsAAAbkrrMAAAAl","remoteAddr":"x.x.x.x","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":0,"time":"2016-09-29T22:59:48+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=disabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"V@2c4sCoKxsAAAbkrrMAAAAl","remoteAddr":"x.x.x.x","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":0,"time":"2016-09-29T22:59:49+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=disabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"V@2c5cCoKxsAAB1jxsYAAACl","remoteAddr":"x.x.x.x","app":"core","message":"No update found at the ownCloud appstore for app encryption","level":0,"time":"2016-09-29T22:59:50+00:00","method":"POST","url":"\/owncloud\/index.php\/settings\/ajax\/enableapp.php","user":"admin"}
{"reqId":"V@2c6cCoKxsAABPJu5AAAACO","remoteAddr":"x.x.x.x","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":0,"time":"2016-09-29T22:59:54+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"V@2c6cCoKxsAABPJu5AAAACO","remoteAddr":"x.x.x.x","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":0,"time":"2016-09-29T22:59:55+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"V@2c6cCoKxsAABPJu5AAAACO","remoteAddr":"x.x.x.x","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":0,"time":"2016-09-29T22:59:55+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"admin"}
{"reqId":"V@2dBMCoKxsAACxP2p4AAACU","remoteAddr":"x.x.x.x","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-09-29T23:00:20+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"V@2qhcCoKxsAAGTBXowAAAGQ","remoteAddr":"x.x.x.x","app":"PHP","message":"simplexml_load_file(\/mnt\/web024\/a2\/74\/12345678\/htdocs\/owncloud\/apps\/files\/appinfo\/info.xml): failed to open stream: Interrupted system call at \/mnt\/web024\/a2\/74\/12345678\/htdocs\/owncloud\/lib\/private\/App\/InfoParser.php#53","level":3,"time":"2016-09-29T23:57:57+00:00","method":"GET","url":"\/owncloud\/index.php\/logout?requesttoken=KS0PAio5PmF7FhMlSXAeBF4aCSYSOA4oa1w2HXhSNj8%3D%3ANJnWrOKR4QKr12Q\/iomvYOcrRkrG%2BcuGvlNniDIm3No%3D","user":"sharinguser"}
{"reqId":"V@2wDMCoKxsAAAS@UC8AAAAp","remoteAddr":"x.x.x.x","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-09-30T00:21:32+00:00","method":"POST","url":"\/owncloud\/index.php\/heartbeat","user":"--"}
{"reqId":"V@27vcCoKxsAACculGoAAAAG","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 10000000 got 1720320\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #112)\\n#1 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(136): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #112)\\n#2 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('Family_DELME_un...', Resource id #112)\\n#3 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('Family_DELME_un...', Resource id #112, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/mnt\\\/web024\\\/a2\\\/...')\\n#10 {main}\",\"File\":\"\\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":404,\"User\":\"user2\"}","level":4,"time":"2016-09-30T01:11:35+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/Family_DELME_unvolls.7z-chunking-3644925395-15-6","user":"user2"}
{"reqId":"V@27vsCoKxsAABD2fKoAAADW","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 10000000 got 2277376\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #112)\\n#1 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(136): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #112)\\n#2 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('Family_DELME_un...', Resource id #112)\\n#3 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('Family_DELME_un...', Resource id #112, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/mnt\\\/web024\\\/a2\\\/...')\\n#10 {main}\",\"File\":\"\\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":404,\"User\":\"user2\"}","level":4,"time":"2016-09-30T01:11:35+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/Family_DELME_unvolls.7z-chunking-3644925395-15-7","user":"user2"}
{"reqId":"V@3bxcCoKxsAAFXgPlMAAAAR","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 409 The destination node is not found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(622): Sabre\\\\DAV\\\\Server->getCopyAndMoveInfo(Object(Sabre\\\\HTTP\\\\Request))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#4 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/mnt\\\/web024\\\/a2\\\/...')\\n#7 {main}\",\"File\":\"\\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":721,\"User\":\"sharinguser\"}","level":4,"time":"2016-09-30T03:28:05+00:00","method":"MOVE","url":"\/owncloud\/remote.php\/webdav\/einszweidreivierfuenfsechssiebenacht\/einszweidreivierfuenfsechssiebenacht","user":"sharinguser"}
{"reqId":"V@3gycCoKxsAAFVUE9gAAAAo","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(588): Sabre\\\\DAV\\\\Server->createCollection('Family\\\/einszwei...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/mnt\\\/web024\\\/a2\\\/...')\\n#7 {main}\",\"File\":\"\\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1121,\"User\":\"user1\"}","level":4,"time":"2016-09-30T03:49:29+00:00","method":"MKCOL","url":"\/owncloud\/remote.php\/webdav\/Family\/einszweidreivierfuenfsechssiebenacht\/New%20folder","user":"user1"}
{"reqId":"V@5QbsCoKxsAACuCZ8MAAAC9","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 409 The destination may not be part of the same subtree as the source path.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(622): Sabre\\\\DAV\\\\Server->getCopyAndMoveInfo(Object(Sabre\\\\HTTP\\\\Request))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#4 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/mnt\\\/web024\\\/a2\\\/...')\\n#7 {main}\",\"File\":\"\\\/mnt\\\/web024\\\/a2\\\/74\\\/12345678\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":744,\"User\":\"user1\"}","level":4,"time":"2016-09-30T11:45:50+00:00","method":"MOVE","url":"\/owncloud\/remote.php\/webdav\/Family\/Rezepte\/%23%20ACHTUNG%20-%20ER%20SYNCHRONISIERT%20DERZEIT%20FALSCH","user":"user1"}
```

#### Browser log
```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.(unknown)
JQMIGRATE: Migrate is installed, version 1.4.0
```

**Comment by DeepDiver1975** [comment]
> 28.09.2016 14:12:12 abc.de [client x.x.x.x] PHP Fatal error: Class 'OC\\Authentication\\Token\\DefaultTokenMapper' not found in /mnt/web024/a2/74/12345678/htdocs/owncloud/lib/private/Server.php on line 216 28.09.2016 14:12:12 abc.de [client x.x.x.x] PHP Fatal error: Class 'OC\\Authentication\\Token\\DefaultTokenMapper' not found in /mnt/web024/a2/74/12345678/htdocs/owncloud/lib/private/Server.php on line 216


there is something really fish with your installation ...

**Comment by dergilb99** [comment]
> there is something really fish with your installation ...

Obviously. That is why I went back to OC 8. No problems there.

**Comment by PVince81** [comment]
Are you sure it's simply 36 chars ? In both your examples you had either an exclamation point "!" or a slash "/" in the name.

**Comment by dergilb99** [comment]
> Are you sure it's simply 36 chars ?

Yes. "Wer dies liest ist doof! Muahahaha" works, while "Wer dies liest ist doof! Muahahahaha" does not. The slash was only there to demonstrate that the whole path counts, not only one directory name.

I did not try it, but I assume that "haha/haha/haha/haha/haha/haha/haha/haha/haha" also would fail. I'll try it now.

**Comment by dergilb99** [comment]
That's kind of embarrassing: It works now. Directory names with more than 36 chars, names only containing exclamation marks, it all works now.

I'm at a loss here, having no idea what's going on. It's like turning around and facing new strange things every other day while others vanish.

Since I do believe to start sounding crazy, what would you suggest I do?

**Comment by PVince81** [comment]
It's very unlikely that your manual cron run would cause directory creation issues.

**Comment by dergilb99** [comment]
> It's very unlikely that your manual cron run would cause directory creation issues.

Ok. I think I'm gonna cry in the cellar for a while.

**Comment by PVince81** [comment]
nah, just have a :beer: :smile:

**Comment by dergilb99** [comment]
> nah, just have a 🍺 😄

:-D
