### ISSUE TITLE
Cannot unshare after moving sub-folder share out as non-initiator

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26357]
### Steps
1. Create three users "user1", "user2", "user3"
2. Login as "user1"
3. Create a folder "base"
4. Share "base" with "user2"
5. Login as "user2"
6. Create a folder "base/sub"
7. Share "base/sub" with "user3" => this makes the share owner be "user1" but the initiator is "user2"
8. Move folder "base/sub" to the root
9. Check if "user3" still receives the folder "sub"
10. Try unsharing "/sub" as "user2" from "user3"
### Expected result

"user3" must still see the folder.
Unsharing works.
### Actual result

Even though the folder "sub" is still marked as shared with "user3", "user3" doesn't see it mounted.
Unsharing from "user3" appears to work in the UI but refreshing the dialog shows the share again.
The only way to make it work again is moving "sub" back into "base/sub"
### Versions

ownCloud v9.1.1

@owncloud/qa we need more of such crazy test cases

**Comment by PVince81** [comment]
I've checked v9.0.4 and only half of the issue exists:
- user3 still doesn't see the mount point even though it's marked as shared
- however it is possible to unshare permanently.

So this is half a regression...

**Comment by PVince81** [comment]
@felixboehm @butonic @cdamken in case people are share recipients for local shares but the share doesn't appear, might be useful to check if it's this scenario.

In the DB it appears like this:
```
MariaDB [owncloud]> select * from oc_share;
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
| id | share_type | share_with | uid_owner | uid_initiator | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token | mail_send |
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
|  1 |          0 | user2      | user1     | user1         |   NULL | folder    | 20          | NULL        |          20 | /base       |          31 | 1476289197 |        0 | NULL       | NULL  |         0 |
|  3 |          0 | user3      | user1     | user2         |   NULL | folder    | 38          | NULL        |          38 | /sub        |          31 | 1476289326 |        0 | NULL       | NULL  |         0 |
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
2 rows in set (0.00 sec)
```

Here even thought "sub" isn't owned by "user1" since "user2" moved it out, the share for "sub" still says that "user1" is the owner.

**Comment by PVince81** [comment]
Additional issue: login as "user3" and create a folder called "sub" => doesn't work, there's the ghost share...

**Comment by PVince81** [comment]
This scenario however seems to work:

1. Login as "user1"
1. Create a folder "base"
1. Share "base" with "user2"
1. Login as "user2"
1. Create a folder "/sub" (outside of "base2) which makes "user2" the initiator and owner
1. Move "/sub" into "/base"
1. Login as "user1"
1. Move "/base/sub" to the root
1. Check if "user3" still has access.

This is because moving a folder "sub" into a received share "base" will change the owner of all shares from "sub" become "user1". It's only when moving out as recipient that it isn't adjusted.

**Comment by PVince81** [comment]
@jvillafanez can you investigate ? Could help get familiar with the sharing 2.0 code.

**Comment by jvillafanez** [comment]
Checked the original steps in stable10 (10.0.4RC1) and user3 doesn't see the shared folder at step 9

I'm not sure where the problem is. I guess it's that the share metadata isn't properly updated when the file is rename / moved.

**Comment by jvillafanez** [comment]
Looks like the problem is around https://github.com/owncloud/core/blob/master/apps/dav/lib/DAV/FileCustomPropertiesBackend.php#L58 trying to get a missing node

Call trace: 
```
#0 \/opt\/owncloud\/apps\/dav\/lib\/DAV\/AbstractCustomPropertiesBackend.php(238): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('sub')\n
#1 \/opt\/owncloud\/apps\/dav\/lib\/DAV\/FileCustomPropertiesBackend.php(210): OCA\\DAV\\DAV\\AbstractCustomPropertiesBackend->getNodeForPath('sub')\n
#2 \/opt\/owncloud\/apps\/dav\/lib\/DAV\/FileCustomPropertiesBackend.php(56): OCA\\DAV\\DAV\\FileCustomPropertiesBackend->getNodeForPath('sub')\n
#3 \/opt\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/PropertyStorage\/Plugin.php(126): OCA\\DAV\\DAV\\FileCustomPropertiesBackend->delete('sub')\n
#4 [internal function]: Sabre\\DAV\\PropertyStorage\\Plugin->afterUnbind('sub')\n
#5 \/opt\/owncloud\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#6 \/opt\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/CorePlugin.php(649): Sabre\\Event\\EventEmitter->emit('afterUnbind', Array)\n
#7 [internal function]: Sabre\\DAV\\CorePlugin->httpMove(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#8 \/opt\/owncloud\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#9 \/opt\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:MOVE', Array)\n
#10 \/opt\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#11 \/opt\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(63): Sabre\\DAV\\Server->exec()\n
#12 \/opt\/owncloud\/remote.php(165): require_once('\/opt\/owncloud\/a...')\n
#13 {main}
```

Error log (with some additions):
```
{"reqId":"vderCjF0lD19xqPmaCF9","level":2,"time":"2017-11-16T11:12:28+00:00","remoteAddr":"10.0.2.4","user":"user2","app":"dav","method":"MOVE","url":"\/remote.php\/webdav\/sub","message":"Could not get node for path: \"sub\" : File with name sub could not be located#0 \/opt\/owncloud\/apps\/dav\/lib\/DAV\/AbstractCustomPropertiesBackend.php(238): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('sub')\n#1 \/opt\/owncloud\/apps\/dav\/lib\/DAV\/FileCustomPropertiesBackend.php(213): OCA\\DAV\\DAV\\AbstractCustomPropertiesBackend->getNodeForPath('sub')\n#2 \/opt\/owncloud\/apps\/dav\/lib\/DAV\/FileCustomPropertiesBackend.php(56): OCA\\DAV\\DAV\\FileCustomPropertiesBackend->getNodeForPath('sub')\n#3 \/opt\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/PropertyStorage\/Plugin.php(126): OCA\\DAV\\DAV\\FileCustomPropertiesBackend->delete('sub')\n#4 [internal function]: Sabre\\DAV\\PropertyStorage\\Plugin->afterUnbind('sub')\n#5 \/opt\/owncloud\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/opt\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/CorePlugin.php(649): Sabre\\Event\\EventEmitter->emit('afterUnbind', Array)\n#7 [internal function]: Sabre\\DAV\\CorePlugin->httpMove(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/opt\/owncloud\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#9 \/opt\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:MOVE', Array)\n#10 \/opt\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#11 \/opt\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(63): Sabre\\DAV\\Server->exec()\n#12 \/opt\/owncloud\/remote.php(165): require_once('\/opt\/owncloud\/a...')\n#13 {main}"}
```

I guess the `delete` method is called after the node is deleted and as consecuence we can't retrieve the node at that point.

Checking some workaround for the time being because executing that method before the deletion doesn't seems easily doable (it probably needs more code changes)

**Comment by jvillafanez** [comment]
I have patched something for the logged error, but the main issue still happens.

**Comment by jvillafanez** [comment]
I'm not sure if this can be solved or it's a part of a much bigger problem.

#### Weird thing number 1: `moveFromStorage` calls poping up.
This is weird because the storage is the same as the sharing seems to be implemented as a wrapper, not as storage. This means that there is only one storage involved (the local one) in this particular case (no external storage is involved in the tests), so we should be performing a rename

#### Weird thing number 2: shared wrapper madness.
In addition to the weird non-standard decorator implementation (if it can be called like that) for the VFS, we have the shared wrapper implemented as FS wrapper but acting like an storage anywhere else. This is, at least, confusing.

Having `moveFromStorage` in the storage implementation is bad:
* Storage functions should be limited to the storage itself. Inter-storage function should be placed somewhere else because it isn't the responsability of the storage. This might interfere with what the wrappers should be doing.
* The function is initiated in the target storage not in the source storage. At most, the source storage will get a delete action at some point (which I guess the SharedStorage ignores). In our particular case, we don't know if the source file has been deleted or moved to another storage, so it doesn't seem possible to adjust the share owner once we move the file out.

If the intended solution is to change the ownership of the share, I doubt it's possible with the current code, at least during the file move.

**Comment by PVince81** [comment]
Ah, this reminds me of the encryption wrapper. It is possible that the encryption wrapper (regardless of encryption state) is influencing this behavior or even preventing it...

**Comment by jvillafanez** [comment]
From my point of view, this is a won't fix unless we plan to make MASSIVE changes in the FS.

The `moveFromStorage` doesn't trigger for the shared wrapper when moving the shared file to the local root of the user. I'm pretty sure that the `copyFromStorage` won't trigger neither. This implies that only the `unlink` or `rmdir` calls are expected to be called for the shared wrapper, and this calls doesn't have any info about where the shared file has been moved.

If we plan solve this problem as repair step when we detect the problem, I'll need a hint to start looking.

**Comment by PVince81** [comment]
The problem is that this causes database inconsistencies when the operation is happening.

Ok, at least now we know it won't be a quick fix.

@jvillafanez what happens if you disable the encryption storage wrapper ?

**Comment by jvillafanez** [comment]
Encryption was disabled the whole time. Commenting https://github.com/owncloud/core/blob/master/lib/private/Encryption/Manager.php#L258 to prevent adding the wrapper shows the following error:
```
{"reqId":"jAd3Z2AzTIWUBYFZbrk1","level":3,"time":"2017-11-21T08:40:00+00:00","remoteAddr":"10.0.2.4","user":"qa2","app":"core","method":"MOVE","url":"\/remote.php\/webdav\/base\/sub1","message":"unable to rename, source directory is not writable : files\/base"}
```

Something is terrible wrong if removing a wrapper causes this failure...

**Comment by PVince81** [comment]
Ok, so it seems you have confirmed that the bug https://github.com/owncloud/core/issues/27124 still exists.

**Comment by jvillafanez** [comment]
List of actions to be taken:
* Clean all the wrappers. They MUST have the following structure:

    ```
    public function method($path) {
        // do something
        $result = parent::method($path);
        // do something
        return $result;
    }
    ```
* Remove optimizations for the wrappers (aka, checking if the source storage is `$this`). This is likely interfering with the normal operation and likely leading to unexpected errors.
* Provide a new component in charge of inter-storage operations.
    * Mark the `moveFromStorage` and `copyFromStorage` as deprecated methods.
    * Move that logic to the new component.
    * Replace all deprecated calls with the new component.
    * The new component will trigger a couple of events to notify the inter-storage copy and move.
        * Source and target storages and paths will be send in the event. To be decided the exact data that will be sent (having access to the storage object might not be a good idea, but there is info needed)
    * Adjust the sharing code to listen the event in order to adjust the file owner.

I think this is the smallest change set to fix this issue. This is my best bet at the moment.

**Comment by PVince81** [comment]
@jvillafanez thanks for the details.

How will the new component (let's call it the "MoveItComponent" (working title))  integrate with the storage wrapper idea ? For example, if encryption has special needs when doing move/copy like moving keys, at what level will this happen ? Will encryption implement it's own MoveItComponent implementations ? If yes, how to register ? `EncryptionWrapper->getMoveItComponent()` ?

**Comment by jvillafanez** [comment]
We'll have a `MultipleStorageOperator` class with `copy($source, $sourcePath, $target, $targetPath)` and a `move(....)` (same parameters).
The implementation of both methods will follow what the `moveFromStorage` and `copyFromStorage` methods are doing internally: basically
```
$sourceStream = $source->fopen($sourcePath, 'rb');
$targetStream = $target->fopen($targetPath, 'wb');
copy_stream($sourceStream, $targetStream);
```
This means that there won't be any change in the storage interface, and the wrappers won't need any change (except for what is planned for cleanup).

In case there are special needs during these operations, the `MultipleStorageOperator` class will trigger a new event (before and after) for those operations. For this particular issue, the files_sharing app will be listening to that event and adjust the file ownership once the move has been finished.

**Comment by jvillafanez** [comment]
Maybe touching a bit the `View` might be enough.

A couple of things to try:
* Check if listening to the rename event of the view is enough.
* Trigger an additional event for a rename between storages.

**Comment by jvillafanez** [comment]
Ok, it seems to be already implemented, but the hook doesn't work or it isn't being reached. Investigating.

**Comment by jvillafanez** [comment]
Looks like finally we have something small that seems to fix the problem. Note that there is still work to do in the PR, mainly checking performance and other scenarios.

I'll create another PR for the wrapper cleanup because it doesn't seem to affect the current PR but I think we'll need to do it anyway at some point.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).

**Comment by PVince81** [comment]
@jvillafanez AFAIK this is fixed already through https://github.com/owncloud/core/pull/29650 ? If yes, we can close this

**Comment by jvillafanez** [comment]
According to the PR, there are other tickets opened which the PR don't fix. This issue is mostly fixed by the PR so we can close this one and leave the new tickets for the future.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
