### ISSUE TITLE
Failure to upgrade to the latest version of ownCloud - CRASH

### ISSUE THREAD

**Issue by sbrl** [owncloud/core#26383]
### Server configuration
**Operating system**: Ubuntu 16.10

**Web server:** Nginx + PHP-FPM (7.0)

**Database:** SQLite

**PHP version:** 7.0.x

**ownCloud version:** (see ownCloud admin page) 9.0.2

**Updated from an older ownCloud or fresh install:** Updated several times.

**Where did you install ownCloud from:** I did a manual install from the official website.

**Signing status (ownCloud 9.0 and above):** Wat?

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - announcementcenter: 1.1.2
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - logreader: 1.1.2
  - music: 0.3.11
  - notifications: 0.2.3
  - ojsxc: 3.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.0
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
Disabled:
  - documents
  - encryption
  - files_versions
  - user_ldap
```

**The content of config/config.php:**

```
 system
{
    "system": {
        "instanceid": "oc7nu0qgtr6j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "trusted_domains": [
            "admin.starbeamrainbowlabs.com",
            "owncloud.starbeamrainbowlabs.com"
        ],
        "datadirectory": "\/srv\/owncloud-data",
        "overwrite.cli.url": "https:\/\/admin.starbeamrainbowlabs.com\/owncloud",
        "dbtype": "sqlite3",
        "version": "9.0.2.2",
        "installed": true,
        "forcessl": false,
        "mail_from_address": "postasaurus",
        "mail_smtpmode": "sendmail",
        "mail_domain": "starbeamrainbowlabs.com",
        "forceSSLforSubdomains": false,
        "theme": "",
        "ldapIgnoreNamingRules": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```

**Are you using external storage, if yes which one:** ummmm

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** nope

### Client configuration
**Browser:** Chrome, but this isn't relavent

**Operating system:** Ubuntu 16.10, but this isn't relavent

### Logs

**N/A**

Hello,

I've been having some issues upgrading my owncloud server to the latest version. When I run the `sudo -u www-data ./occ upgrade` command, I get this:

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
 Done                                                        
 6/6 [============================] 100%                     
Checked database schema update
Checking updates of apps
An unhandled exception has been thrown:
Error: [] operator not supported for strings in /srv/owncloud/lib/private/App/InfoParser.php:186
Stack trace:
#0 /srv/owncloud/lib/private/App/InfoParser.php(188): OC\App\InfoParser->xmlToArray(Object(SimpleXMLElement))
#1 /srv/owncloud/lib/private/App/InfoParser.php(59): OC\App\InfoParser->xmlToArray(Object(SimpleXMLElement))
#2 /srv/owncloud/lib/private/legacy/app.php(662): OC\App\InfoParser->parse('/srv/owncloud/a...')
#3 /srv/owncloud/lib/private/Updater.php(310): OC_App::getAppInfo('files')
#4 /srv/owncloud/lib/private/Updater.php(235): OC\Updater->checkAppUpgrade('9.1.0.15')
#5 /srv/owncloud/lib/private/Updater.php(150): OC\Updater->doUpgrade('9.1.0.15', '9.0.2.2')
#6 /srv/owncloud/core/Command/Upgrade.php(290): OC\Updater->upgrade()
#7 /srv/owncloud/3rdparty/symfony/console/Command/Command.php(259): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /srv/owncloud/3rdparty/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /srv/owncloud/3rdparty/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /srv/owncloud/3rdparty/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /srv/owncloud/lib/private/Console/Application.php(146): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /srv/owncloud/console.php(94): OC\Console\Application->run()
#13 /srv/owncloud/occ(11): require_once('/srv/owncloud/c...')
#14 {main}
```

(This issue originated in [this owncloud forum post](https://central.owncloud.org/t/cant-upgrade-owncloud-using-the-web-interface/1664/3).)

**Comment by RealRancor** [comment]
From a first look at this is looks like an issue in a 3rdparty app installed by the user. Have redirected him to the issue tracker here as oC should be a little bit verbose here and don't fail instantly.

**Comment by PVince81** [comment]
@VicDeo

**Comment by RealRancor** [comment]
Maybe an issue in the info.xml of a specific 3rdparty app?

@sbrl  Could you disable each 3rdparty app one by one and run the upgrade routine after each disabled 3rdparty app? Maybe this gives some pointers.

**Comment by sbrl** [comment]
@RealRancor I'm really sorry I haven't been able to get back to you - I have a rather limited amount of time at the moment :disappointed:

I disabled all the 3rd party apps, and then tried the upgrade again. I got the same exception:

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
 Done                                                        
 6/6 [============================] 100%                     
Checked database schema update
Checking updates of apps
An unhandled exception has been thrown:
Error: [] operator not supported for strings in /srv/owncloud/lib/private/App/InfoParser.php:186
Stack trace:
#0 /srv/owncloud/lib/private/App/InfoParser.php(188): OC\App\InfoParser->xmlToArray(Object(SimpleXMLElement))
#1 /srv/owncloud/lib/private/App/InfoParser.php(59): OC\App\InfoParser->xmlToArray(Object(SimpleXMLElement))
#2 /srv/owncloud/lib/private/legacy/app.php(662): OC\App\InfoParser->parse('/srv/owncloud/a...')
#3 /srv/owncloud/lib/private/Updater.php(310): OC_App::getAppInfo('files')
#4 /srv/owncloud/lib/private/Updater.php(235): OC\Updater->checkAppUpgrade('9.1.1.3')
#5 /srv/owncloud/lib/private/Updater.php(150): OC\Updater->doUpgrade('9.1.1.3', '9.0.2.2')
#6 /srv/owncloud/core/Command/Upgrade.php(290): OC\Updater->upgrade()
#7 /srv/owncloud/3rdparty/symfony/console/Command/Command.php(259): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /srv/owncloud/3rdparty/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /srv/owncloud/3rdparty/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /srv/owncloud/3rdparty/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /srv/owncloud/lib/private/Console/Application.php(146): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /srv/owncloud/console.php(94): OC\Console\Application->run()
#13 /srv/owncloud/occ(11): require_once('/srv/owncloud/c...')
#14 {main}
```

**Comment by RealRancor** [comment]
@sbrl No need to say sorry. :-)

Could be possible that oC is still trying to parse the appinfo/info.xml of all apps (even if disabled) so you could also try to delete one 3rdparty app after another from the /apps/ folder to see if you can identify an app causing that issue.

**Comment by sbrl** [comment]
I can't find the `appinfo/info.xml` file. Also, I haven't been moving any of the apps from the old folder to the new one before doing the upgrade:

```
sbrl@starbeamrainbowlabs.com:/srv/owncloud/apps$ ls
activity              files             files_versions     templateeditor
comments              files_antivirus   files_videoplayer  updatenotification
dav                   files_external    firstrunwizard     user_external
encryption            files_pdfviewer   gallery            user_ldap
external              files_sharing     notifications
federatedfilesharing  files_texteditor  provisioning_api
federation            files_trashbin    systemtags
```

**Comment by sbrl** [comment]
I don't know what I did, but it seems to have upgraded correctly this time.

Thanks for the help anyway!

**Comment by hjohanns** [comment]
For those (like me) trying to upgrade from old NC 9, problem is due to a bug fixed in a later version. Make sure that the file lib/private/App/InfoParser.php at lines 158-159 looks like
			if (!isset($array[$element])) {
                                $array[$element] = $totalElement > 1 ? [] : "";
Then the upgrade will pursue. 
Cheers, hj
