### ISSUE TITLE
Issue with shared calendar - owncloud 8.2.7.1

### ISSUE THREAD

**Issue by simogeo** [owncloud/core#26392]
### Steps to reproduce
1. Create a calendar
2. Share it with another user
3. Try to sync in TB - Lightning

### Expected behaviour
The calendar should be visible / editable from TB - Lightning

### Actual behaviour
TB - Lightning is not able to sync calendar. Own user calendar are working well

### Server configuration
**Operating system**: Ubuntu server 14.04 

**Web server:** Apache 2

**Database:** MYSQL

**PHP version:** 5.5.9

**ownCloud version:** : owncloud 8.2.7.1

**Updated from an older ownCloud or fresh install:** just updated to try to correct bug but it does not

**Where did you install ownCloud from:** 

**PHP error log - Here is a fatal error triggered by checking shared calendar and visible from admin page** : 

```php
Exception: {"Message":"End of document reached prematurely","Exception":"Sabre\\VObject\\EofException","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(168): Sabre\\VObject\\Parser\\MimeDir->readLine()\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(137): Sabre\\VObject\\Parser\\MimeDir->parseLine('BEGIN:VEVENT')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\\VObject\\Parser\\MimeDir->parseDocument()\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\\VObject\\Parser\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\n#4 \/var\/www\/owncloud\/apps2\/calendar\/lib\/sabre\/backend.php(384): Sabre\\VObject\\Reader::read('BEGIN:VCALENDAR...')\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(54): OCA\\Calendar\\Sabre\\Backend->getCalendarObject('8', 'd3628381-4823-4...')\n#6 [internal function]: Sabre\\CalDAV\\Backend\\AbstractBackend->Sabre\\CalDAV\\Backend\\{closure}('d3628381-4823-4...')\n#7 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(55): array_map(Object(Closure), Array)\n#8 \/var\/www\/owncloud\/apps2\/calendar\/lib\/sabre\/calendar.php(148): Sabre\\CalDAV\\Backend\\AbstractBackend->getMultipleCalendarObjects('8', Array)\n#9 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(272): OCA\\Calendar\\Sabre\\Calendar->getMultipleChildren(Array)\n#10 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(977): Sabre\\DAV\\Tree->getMultipleNodes(Array)\n#11 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(464): Sabre\\DAV\\Server->getPropertiesForMultiplePaths(Array, Array)\n#12 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(228): Sabre\\CalDAV\\Plugin->calendarMultiGetReport(Object(DOMDocument))\n#13 [internal function]: Sabre\\CalDAV\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\/laure...')\n#14 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#15 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(710): Sabre\\Event\\EventEmitter->emit('report', Array)\n#16 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#17 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#18 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#19 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#20 \/var\/www\/owncloud\/apps2\/calendar\/appinfo\/remote.php(60): Sabre\\DAV\\Server->exec()\n#21 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#22 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":250} 
```

**List of activated apps:** : 

```
Enabled:
  - activity: 2.1.4
  - calendar: 0.8.2
  - files: 1.2.1
  - files_pdfviewer: 0.7.1
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - bookmarks
  - documents
  - encryption
  - external
  - files_antivirus
  - files_comments
  - files_external
  - files_locking
  - notifications
  - provisioning_api
  - storagecharts2
  - tasks
  - user_external
  - user_ldap
  - user_webdavauth

```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc9b16e44659",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxxxx.com"
        ],
        "datadirectory": "\/data",
        "overwrite.cli.url": "http:\/\/xxxxx.com",
        "dbtype": "mysql",
        "version": "8.2.7.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "info",
        "mail_smtpmode": "php",
        "mail_domain": "xxxxx",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "theme": "",
        "maintenance": false,
        "loglevel": 4,
        "trashbin_retention_obligation": "auto"
    }
}

```
Thanks for your help

**Comment by RealRancor** [comment]
Hi,

> ownCloud version: : owncloud 8.2.7.1

the CalDAV / CardDAV topic is unsupported in anything below. Please close here and upgrade to at least 9.0.5 to get further support with this.
