### ISSUE TITLE
Update v9.1.0 to master NeedsUpdateException dav app

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26401]
### Steps

1. Setup v9.1.0
1. Check out master (a8e96d75a355d71f23093652ce842b5057575447)
1. Run `./occ upgrade`

### Expected
Success?

### Actual
```
An unhandled exception has been thrown:
exception 'OC\NeedsUpdateException' in /srv/www/htdocs/owncloud/lib/private/legacy/app.php:149
Stack trace:
#0 /srv/www/htdocs/owncloud/lib/private/legacy/app.php(121): OC_App::loadApp('dav')
#1 /srv/www/htdocs/owncloud/lib/private/legacy/util.php(135): OC_App::loadApps(Array)
#2 /srv/www/htdocs/owncloud/lib/private/Files/Filesystem.php(260): OC_Util::setupFS(NULL)
#3 /srv/www/htdocs/owncloud/lib/private/Server.php(176): OC\Files\Filesystem::getMountManager(NULL)
#4 /srv/www/htdocs/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#5 /srv/www/htdocs/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('RootFolder')
#6 /srv/www/htdocs/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('RootFolder')
#7 /srv/www/htdocs/owncloud/lib/private/Server.php(784): OC\ServerContainer->query('RootFolder')
#8 /srv/www/htdocs/owncloud/lib/private/Server.php(361): OC\Server->getRootFolder()
#9 /srv/www/htdocs/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#10 /srv/www/htdocs/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('AvatarManager')
#11 /srv/www/htdocs/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AvatarManager')
#12 /srv/www/htdocs/owncloud/lib/private/Server.php(775): OC\ServerContainer->query('AvatarManager')
#13 /srv/www/htdocs/owncloud/lib/private/Repair.php(147): OC\Server->getAvatarManager()
#14 /srv/www/htdocs/owncloud/core/register_command.php(125): OC\Repair::getRepairSteps()
#15 /srv/www/htdocs/owncloud/lib/private/Console/Application.php(88): require_once('/srv/www/htdocs...')
#16 /srv/www/htdocs/owncloud/console.php(98): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /srv/www/htdocs/owncloud/occ(11): require_once('/srv/www/htdocs...')
#18 {main}
```

Note that upgrading from v9.1.1 doesn't have this issue, so not sure if this is important.

In general we recommend people to first update to the last point release before going to the next major release.

@DeepDiver1975 @VicDeo what do you think ?

**Comment by butonic** [comment]
I am getting this now, but I was always on master only switching between branches that work on it ...

**Comment by butonic** [comment]
It seems it was introduced with c06f9dc4413da0905686860de39e54761edbfeb4
