### ISSUE TITLE
Shared file cannot be opened

### ISSUE THREAD

**Issue by kalletabur** [owncloud/core#26406]
### Steps to reproduce
1. User uploaded file
2. Shared this file
3. Shared file cannot be opened

### Expected behaviour
Shared file should be opened by another user

### Actual behaviour
User desktop client gets errors like "connection closed", "operation canceled" and so on

### My comments
Basically since the beginning of this sharedfilename.xlsx was uploaded into server there are DecryptionFailedException log entries (altogether 17 same entries).
User has keys (filekey and ShareKey) in 
data/$user/files_encryption/keys/files/$path_to_file/OC_DEFAULT_MODULE/ folder

I found similar issue [Unable to decrypt files on 8.2.2](https://github.com/owncloud/core/issues/23177). There are suggested lots of different solutions - patching, updating, changing oc_filecache. So I'm wondering - is there one solution or should I patch or update and then hope that everything will be fixed.

### Server configuration
**Operating system**:
Debian 8
**Web server:**
nginx 1.8
**Database:**
mysql 5.6
**PHP version:**
php 5.6
**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.2
**Updated from an older ownCloud or fresh install:**
ownCloud 8.1
**Where did you install ownCloud from:**
packages

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - contacts: 0.5.0.0
  - encryption: 1.1.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - user_ldap: 0.7.1
Disabled:
  - external
  - files_external
  - notifications
  - provisioning_api
  - templateeditor
  - user_external
```

**The content of config/config.php:**

```
        "instanceid": "instanceid",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.company.firm"
        ],
        "datadirectory": "\/ownclouddatadirectory\/",
        "overwrite.cli.url": "https:\/\/owncloud.company.firm",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "ownclouddatabase",
        "dbhost": "localhost",
        "dbtableprefix": "owncloud_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "someserver.company.firm",
        "mail_smtpport": "25",
        "forcessl": true,
        "maintenance": false,
        "singleuser": false,
        "loglevel": 1,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "trashbin_retention_obligation": "auto"
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 7

**Desktop client:**
Version 2.2.4

#### ownCloud log (data/owncloud.log)
```
{"reqId":"1Q9Mb0CkXqjN3iBUmHv0",
	"remoteAddr":"10.10.10.10",
	"app":"no app in context",
	"message":"Encryption module \"Default encryption module\" is not able to read \/u.username\/files\sharedfilename.xlsx",
	"level":2,
	"time":"2016-10-17T09:47:01+02:00"
	}
{"reqId":"1Q9Mb0CkXqjN3iBUmHv0",
	"remoteAddr":"10.10.10.10",
	"app":"no app in context",
	"message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",
		"Message\":\"Encryption module \\\"Default encryption module\\\" is not able to read \\\/u.username\\\/files\\\/files\sharedfilename.xlsx\",
		"Code\":0,\"Trace\":
			#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(289): OCA\\\\Encryption\\\\Crypto\\\\Encryption->isReadable('\\\/u.username\\\/fi...', 'u.username2')
			#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(161): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->isReadable('files\\\/sharedfilename...')
			#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(256): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->isReadable('files\\\/sharedfilename...')
			#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(161): OC\\\\Files\\\\Storage\\\\Shared->isReadable('')
			#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(170): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->isReadable('')
			#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(161): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->isReadable('')
			#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1023): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->isReadable('')
			#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(399): OC\\\\Files\\\\View->basicOperation('isReadable', '\\\/\\\//sharedfilename...')
			#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(672): OC\\\\Files\\\\View->isReadable('\\\/\\\/sharedfilename...')
			#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(164): OC\\\\Files\\\\Filesystem::isReadable('\\\/\\\/sharedfilename...')
			#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(90): OC_Files::getSingleFile(Object(OC\\\\Files\\\\View), '\\\/', '/sharedfilename...', false)
			#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(53): OC_Files::get('\\\/', Array, false)
			#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')
			#13 [internal function]: __lambda_func(Array)
			#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func('\\\\x00lambda_10904', Array)
			#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')
			#16 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()
			#17 {main}\",
		"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php\",
		"Line\":431}",
	"level":3,
	"time":"2016-10-17T09:47:01+02:00"
	}

```

**Comment by RealRancor** [comment]
@kalletabur 
> ownCloud 8.2.2

From the issue template you have filled out:

> Before reporting any issues please make sure that you're using the latest available version for your major branch (e.g. 9.0.x), see https://owncloud.org/changelog/

This avoids that you're creating issues for problems which might be already fixed in newer versions of ownCloud. Especially when using such outdated versions like 8.2.2 where 8.2.8 is current (https://owncloud.org/changelog/#latest8.2).

**Comment by kalletabur** [comment]
> .. update and then hope that everything will be fixed

So because I haven't updated there is no way to get support to solve my problem?

**Comment by RealRancor** [comment]
There won't be any support in here in general. This is a bugtracker for ownCloud, support is given at https://central.owncloud.org/

And before any bugs are reported, a stable release needs to be used.

**Comment by kalletabur** [comment]
Ok.
Sorry to posting wrong place.
Thanks

**Comment by RealRancor** [comment]
But before asking for support at central you should really update to 8.2.8 first.
