### ISSUE TITLE
Can't delete folder or files and can't create new folder but can upload files from web

### ISSUE THREAD

**Issue by kloknibor** [owncloud/core#26486]
### Steps to reproduce

1.Login to the owncloud web application (also creates errors when using desktop client)
2.create a folder, remove a folder or remove an existing file
3. you get a message the folder can not be created or the file/folder is not removed.
### Expected behaviour

I would expect that the folder/file gets deleted or created
### Actual behaviour

Returns an error that it can not be deleted
### Server configuration

**Operating system**: Debian jessie

**Web server:**  Directadmin

**Database:** MySQL

**PHP version:** PHP 5.6

**ownCloud version:** (see ownCloud admin page) ownCloud 9.1.1 (stable)

**Updated from an older ownCloud or fresh install:** resh install but just updated. Both fresh and updated install same

**Where did you install ownCloud from:** I installed it with Installatron

**Signing status (ownCloud 9.0 and above):** ownCloud 9.1.1 (stable)

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**

```
sudo -u www-data php occ app:list
PHP Warning:  require_once(/home/photocentr/domains/photocentric3dopenlab.com/pr                                     ivate_html/test/console.php): failed to open stream: Permission denied in /home/                                     photocentr/domains/photocentric3dopenlab.com/private_html/test/occ on line 11
PHP Fatal error:  require_once(): Failed opening required '/home/photocentr/doma                                     ins/photocentric3dopenlab.com/private_html/test/console.php' (include_path='.:/u                                     sr/local/lib/php') in /home/photocentr/domains/photocentric3dopenlab.com/private                                     _html/test/occ on line 11
root@server:/home/photocentr/domains/photocentric3dopenlab.com/private_html/test 
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocv41zfer0th',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'photocentric3dopenlab.com',
  ),
  'datadirectory' => '/home/photocentr/domains/photocentric3dopenlab.com/private_html/test/.htluxhpczf5atj.data',
  'overwrite.cli.url' => 'https://photocentric3dopenlab.com/test',
  'dbtype' => 'mysql',
  'version' => '9.1.1.3',
  'dbname' => 'photocentr_ownc1',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'ownc_',
  'dbuser' => 'photocentr_ownc1',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:** 
Chrome

**Operating system:**
Windows 10
#### Web server error log

```
There were no relevant apache/php log data
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"WA9R8lOI@Y8AAHbqxBUAAAAJ","remoteAddr":"94.30.0.108","app":"core","message":"Login failed: 'er6tza' (Remote IP: '94.30.0.108')","level":2,"time":"2016-10-25T12:37:06+00:00","method":"POST","url":"\/test\/index.php\/login","user":"--"}
{"reqId":"WA9R8lOI@Y8AAHbqxBYAAAAJ","remoteAddr":"94.30.0.108","app":"PHP","message":"Undefined offset: 1 at \/home\/photocentr\/domains\/photocentric3dopenlab.com\/private_html\/test\/core\/Controller\/LoginController.php#117","level":3,"time":"2016-10-25T12:37:06+00:00","method":"GET","url":"\/test\/index.php\/login?user=er6tza","user":"--"}
{"reqId":"WA9R8lOI@Y8AAHbqxBYAAAAJ","remoteAddr":"94.30.0.108","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/photocentr\/domains\/photocentric3dopenlab.com\/private_html\/test\/core\/templates\/login.php#23","level":3,"time":"2016-10-25T12:37:06+00:00","method":"GET","url":"\/test\/index.php\/login?user=er6tza","user":"--"}
{"reqId":"WA@QX1OI@Y8AABnJw4MAAAAY","remoteAddr":"94.30.0.108","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/app.php(119): OC_App::loadApp('dav')\\n#1 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/util.php(135): OC_App::loadApps(Array)\\n#2 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/base.php(890): OC_Util::setupFS()\\n#3 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":147}","level":3,"time":"2016-10-25T17:03:27+00:00","method":"GET","url":"\/test\/index.php\/core\/js\/oc.js?v=826499aca361ae8180c554b31d648bc7","user":"--"}
{"reqId":"WA@QX1OI@Y8AAGm7K8wAAAAG","remoteAddr":"94.30.0.108","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/app.php(119): OC_App::loadApp('dav')\\n#1 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/util.php(135): OC_App::loadApps(Array)\\n#2 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/base.php(890): OC_Util::setupFS()\\n#3 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":147}","level":3,"time":"2016-10-25T17:03:27+00:00","method":"GET","url":"\/test\/index.php\/core\/js\/oc.js?v=826499aca361ae8180c554b31d648bc7","user":"--"}
{"reqId":"WA@QX1OI@Y8AAAXp@04AAAAR","remoteAddr":"94.30.0.108","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/app.php(119): OC_App::loadApp('dav')\\n#1 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/util.php(135): OC_App::loadApps(Array)\\n#2 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/base.php(890): OC_Util::setupFS()\\n#3 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":147}","level":3,"time":"2016-10-25T17:03:27+00:00","method":"GET","url":"\/test\/index.php\/core\/js\/oc.js?v=826499aca361ae8180c554b31d648bc7","user":"--"}
{"reqId":"WA@QX1OI@Y8AAAHfnVkAAAAC","remoteAddr":"94.30.0.108","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/app.php(119): OC_App::loadApp('dav')\\n#1 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/util.php(135): OC_App::loadApps(Array)\\n#2 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/base.php(890): OC_Util::setupFS()\\n#3 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":147}","level":3,"time":"2016-10-25T17:03:28+00:00","method":"GET","url":"\/test\/index.php\/core\/js\/oc.js?v=826499aca361ae8180c554b31d648bc7","user":"--"}
{"reqId":"WA@SBlOI@Y8AAAXp@1EAAAAR","remoteAddr":"94.30.0.108","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/app.php(119): OC_App::loadApp('dav')\\n#1 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/util.php(135): OC_App::loadApps(Array)\\n#2 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/base.php(890): OC_Util::setupFS()\\n#3 \\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/photocentr\\\/domains\\\/photocentric3dopenlab.com\\\/private_html\\\/test\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":147}","level":3,"time":"2016-10-25T17:10:31+00:00","method":"GET","url":"\/test\/index.php\/core\/js\/oc.js?v=826499aca361ae8180c554b31d648bc7","user":"--"}
{"reqId":"WA@SDVOI@Y8AABmoCekAAAAH","remoteAddr":"94.30.0.108","app":"core","message":"starting upgrade from 9.1.0.15 to 9.1.1.3","level":0,"time":"2016-10-25T17:10:37+00:00","method":"GET","url":"\/test\/core\/ajax\/update.php?requesttoken=NChMVRI3RWc8Og5APTpmCg4wFgB7fmUYHAYnHVtbHCg%3D%3AXp4eQZ7SnsG1gkRZtsrQ02Ju%2B1rsp%2FnbUdk2DklLEc0%3D","user":"--"}
```
#### Browser log

```
https://photocentric3dopenlab.com/test/index.php/core/preview.png?file=%2FownCloud+Manual.pdf&c=08085a648738aa5315033512bd9edcc8&x=32&y=32&forceIcon=0 Failed to load resource: the server responded with a status of 404 (Not Found)
https://photocentric3dopenlab.com/test/index.php/core/preview.png?file=%2F.dropbox&c=8297647fdbe35accc6c91a9545e2025b&x=32&y=32&forceIcon=0 Failed to load resource: the server responded with a status of 404 (Not Found)
```

I checked the permission of the www-data I believe from the top of my head and it can acces everything. Owncloud is installed with installatron.

Also I tried restorting php.ini and setting everything to default value (php-mod) but no luck either. Also befoire the log was empty but now it just showed some information!

thanks in advance,

Kind regards,

Robin

PS : if it helps I can grant someone temporary SSH acces

**Comment by PVince81** [comment]
> Integrity checker has been disabled. Integrity cannot be verified.

Are you sure the ownCloud source code is the original one, unmodified ? Sometimes when people do a manual tarball update they mix up source code.

**Comment by RealRancor** [comment]
Most likely the integrity checker has been patched out here by the package provider "Installatron" as it wasn't disabled in the config.php. Have seen the same for Arch/AUR as they are shipping the github repos instead of the packages: https://github.com/owncloud/core/issues/23634

**Comment by kloknibor** [comment]
This is indeed installed by installatron a complete fresh install will give me exactly the same (A clean install from installatron). If it is easy to install it along my directadmin installation and multiple instances than I'm fine to find out what is wrong with it :/

**Comment by kloknibor** [comment]
@PVince81 what more info do you need? Installatron broke this part and isn't fixable (easily). I tried iot with 3 new installs, same problem.

Please let me know what other info I could supply?

**Comment by PVince81** [comment]
Have you tried installing directly from the original tarballs and skipping installatron altogether ?
If your worry is about having multiple instances you should be able to manually install OC into separate folders, just make sure their configs point to the correct data dir for each and that their instance ids is different (should be the case automatically anyway if you ran setup in each).

**Comment by kloknibor** [comment]
I'm just about to try that yes ;)! I'm running it along Direct admin but I can just install it in a subfolder of the domain correct?

**Comment by kloknibor** [comment]
@PVince81 I tried this but without luck :( Integrity is fine now :  

No errors have been found.

**Comment by kloknibor** [comment]
If it help here is the log when deleting a folder Steps where  : 

Login as admin
click new folder
called the folder testtt
made it - > got the error can't make folder. 

Seems like something is set up wrong in my server but didn't set anything to strange :/

**Comment by kloknibor** [comment]
I could solve this the same as issue : #26255 but |I'm not sure how safe this solution is. But it is a server set-up problem somewhere I suppose ;)!

**Comment by PVince81** [comment]
Does installatron also configure Apache properly ?

This is likely to be an issue with installatron or your setup, not a bug in ownCloud.

Please ask on central for further help and post your server / apache config there: http://central.owncloud.org/
