### ISSUE TITLE
 Every upgrade always attempts to CREATE TABLE oc_addressbooks

### ISSUE THREAD

**Issue by EricKerby** [owncloud/core#26513]
I ran into the reasonably well-documented issues migrating contacts/calendars from 8.x to 9.0.x (ie, bug #23867), but eventually resolved the issues and have been using the core contacts/calendars functionality fine since. Unfortunately, after every new point release (such as 9.1.0 to 9.1.1) when I run occ upgrade, I still see this error:
```
dav: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists
```

Despite the error, when I leave maintenance mode, everything seems to work just fine (though I do have to manually re-enable each of my plugins). Why does the upgrade script continue to attempt to re-create the addressbooks table?

### Steps to reproduce
1. Perform point release upgrade from 9.1.0 to 9.1.1 with package manager
2. Run occ upgrade command
3. Upgrade runs normally until hitting error described above

### Expected behaviour
occ upgrade should complete without error

### Actual behaviour
occ upgrade complains about oc_addressbooks already existing and fails to re-enable plugins or leave maintenance mode.

### Server configuration
Operating system: Ubuntu 14.04
Web server: Apache 2.4.7
Database: MySQL 5.5.52
PHP version: 5.5.9
ownCloud version (see ownCloud admin page): 9.1.1
Updated from an older ownCloud or fresh install: Updated numerous times

### Integrity status:
```
No errors have been found.
```

### ownCloud log (data/owncloud.log)
```
{"reqId":"xJXuCNKgy8r0vy1w4l7e","remoteAddr":"","app":"dav","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableExistsException\",\"Message\":\"An exception occu
rred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `ur
i` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`i
d`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':\\n\\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists\",\"Code\":0,\"Tra
ce\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertExcep
tion('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.ph
p(945): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'CREAT
E TABLE `o...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/MDB2SchemaManager.php(168): Doctrine\\\\DBAL\\\\Connection->query('CREATE TABLE `o...')\\n#3 \\\/var\\\/www\\\/
owncloud\\\/lib\\\/private\\\/DB\\\/MDB2SchemaManager.php(69): OC\\\\DB\\\\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#4 \\\/var\\\/www\\\/own
cloud\\\/lib\\\/private\\\/legacy\\\/db.php(172): OC\\\\DB\\\\MDB2SchemaManager->createDbFromStructure('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\
/Installer.php(563): OC_DB::createDbFromStructure('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Installer.php(533): OC\\\\Installer::installShippedA
pp('dav')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(258): OC\\\\Installer::installShippedApps(true)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.ph
p(150): OC\\\\Updater->doUpgrade('9.1.1.3', '9.1.0.15')\\n#9 \\\/var\\\/www\\\/owncloud\\\/core\\\/Command\\\/Upgrade.php(290): OC\\\\Updater->upgrade()\\n#10 \\\/var\\\/www\\\/owncloud\
\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\
\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(844): Symfony\\\\Component\\\\Console\\\\Comman
d\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud\\\/3
rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\
\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.p
hp(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleO
utput))\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Console\\\/Application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#15 \\\/var\\\/www\\\/own
cloud\\\/console.php(94): OC\\\\Console\\\\Application->run()\\n#16 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#17 {main}\",\"File\":\"\\\/var\\
\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":49}","level":3,"time":"2016-10-23T05:15:31+00:00","method":"-
-","url":"--","user":"--"}
```

**List of activated apps:**
```
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: true
  - documents: 0.13.1
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notes: 2.0.2
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "527b9da530a97",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/lib\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.1.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "trusted_domains": [
            "***",
            "***",
            "****"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_domain": "***",
        "mail_smtpauth": 1,
        "mail_from_address": "***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "maintenance": false,
        "log_rotate_size": 5242880,
        "appstore.experimental.enabled": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by EricKerby** [comment]
My issue is similar to the one reported in bug #25125: note that this bug was closed as a dupe, but is separate from #23867 since these upgrade failures are for versions higher than 9.0.1.

**Comment by PVince81** [comment]
@DeepDiver1975

**Comment by EricKerby** [comment]
I just performed an upgrade via the apt repo from 9.1.1 to 9.1.2 and this issue happened again as expected. I hit the error and when the upgrade finished and I turned off maintenance mode the calendar and contacts functionality (web apps and ability to sync via CalDAV and CardDAV) was disabled. I just had to open the owncloud web app and "Enable" Calendar and Contacts again. At that point syncing and the web apps worked again (so my database seems intact and functional despite the error I get EVERY upgrade).

Here's what I see in the occ upgrade console output:
```
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
 Done                                     
 24/24 [============================] 100%
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Disabled 3rd-party app: calendar
Disabled 3rd-party app: contacts
Disabled 3rd-party app: documents
Disabled 3rd-party app: notes
Update 3rd-party app: calendar
dav: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists
Drop old database tables
 Done                                            
 28/28 [============================] 100%       
Remove old (< 9.0) calendar/contact shares
 Done                                            
 4/4 [============================] 100%         
Fix permissions so avatars can be stored again
 Done                                            
 2/2 [============================] 100%         
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Reset log level
```

**Comment by PVince81** [comment]
@DeepDiver1975 did we move the address book table to migrations with a `hasTable` check ? If yes, this issue will likely disappear in OC 10.0.3+

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
