### ISSUE TITLE
Setup check for json_encode seems to fail on recent oC versions

### ISSUE THREAD

**Issue by ghost** [owncloud/core#26553]
Cross-posting from central at https://central.owncloud.org/t/http-error-500-blank-screen/3752

OS version: Ubuntu 16.04
oC version: 9.1.1

Seems the check for json_encode done in https://github.com/owncloud/core/blob/v9.1.1/lib/private/legacy/util.php#L747 doesn't work as expected and the user there is getting the following error:

```
PHP Fatal error: Uncaught Error: Call to undefined function OC\Log\json_encode() in /var/www/owncloud/lib/private/Log/Owncloud.php:112
Stack trace:
#0 [internal function]: OC\Log\Owncloud::write('PHP', 'Uncaught Error:...', 3)
#1 /var/www/owncloud/lib/private/Log.php(298): call_user_func(Array, 'PHP', 'Uncaught Error:...', 3)
#2 /var/www/owncloud/lib/private/Log.php(156): OC\Log->log(3, 'Uncaught Error:...', Array)
#3 /var/www/owncloud/lib/private/Log/ErrorHandler.php(67): OC\Log->critical('Uncaught Error:...', Array)
#4 [internal function]: OC\Log\ErrorHandler::onShutdown()
#5 {main}\n thrown in /var/www/owncloud/lib/private/Log/Owncloud.php on line 112
```

Installing the php-json package should solve that issue but oC doesn't provide this info to the user.

**Comment by RealRancor** [comment]
Seems the same is also failing for PDO: https://github.com/owncloud/core/blob/v9.1.1/lib/private/legacy/util.php#L756

```
{"reqId":"jGyAYvqFvO+jX+OoRcal","remoteAddr":"192.168.1.3","app":"index","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'PDO' not found\",\"Code\":0,\"Trace\":\"
#0 \\/var\\/www\\/owncloud\\/lib\\/private\\/Setup.php(170): OC\\Setup->getAvailableDbDriversForPdo()\n
#1 \\/var\\/www\\/owncloud\\/lib\\/private\\/legacy\\/util.php(642): OC\\Setup->getSupportedDatabases()\n
#2 \\/var\\/www\\/owncloud\\/lib\\/base.php(587): OC_Util::checkServer(Object(OC\\AllConfig))\n
#3 \\/var\\/www\\/owncloud\\/lib\\/base.php(973): OC::init()\n
#4 \\/var\\/www\\/owncloud\\/index.php(37): require_once('\\/var\\/www\\/ownclo...')\n
#5 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/lib\\/private\\/Setup.php\",\"Line\":114}","level":3,"time":"2016-11-06T11:03:56+00:00","method":"GET","url":"\/owncloud\/","user":"--"}
```
-> https://central.owncloud.org/t/http-error-500-blank-screen/3752/7

Wonder if this this util.php is used/working at all?

**Comment by PVince81** [comment]
I don't think we have a setup check for php-json, ideal would be to have a check in one single place that checks for all libraries.

**Comment by RealRancor** [comment]
Maybe the wording "setup check" was wrong here. Shouldn't oC show a message like seen in https://github.com/owncloud/core/issues/24637 if these modules are missing:

> PHP module GD not installed.
Please ask your server administrator to install the module.
PHP modules have been installed, but they are still listed as missing?
Please ask your server administrator to restart the web server.

**Comment by PVince81** [comment]
Hmm indeed, and from what I see it's there: https://github.com/owncloud/core/blob/v9.1.1/lib/private/legacy/util.php#L747

**Comment by RealRancor** [comment]
The same is also for PDO: https://github.com/owncloud/core/blob/v9.1.1/lib/private/legacy/util.php#L756

Could it be that these Classes / functions are called even before oC is reaching lib/private/legacy/util.php?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
