### ISSUE TITLE
Include app name in exceptions of /lib/private/Installer.php

### ISSUE THREAD

**Issue by ghost** [owncloud/core#26594]
### Steps to reproduce
1. Have oC 9.0.6 installed with 3rdparty apps from the appstore (namely: Gallery+)
2. Upgrade to 9.1.2
3. Check owncloud.log logfile

### Expected behaviour
The logfile should contain the app name which can't be installed. It might be useful to have the app name logged in all exceptions thrown in https://github.com/owncloud/core/blob/v9.1.2/lib/private/Installer.php#L330

### Actual behaviour
The logfile only contains the ocsid somewhere between a large blob of exception.

### Server configuration
**ownCloud version:** (see ownCloud admin page) 9.1.2

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VlXtwRwHz67\/R1neHl1L","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"App can't be installed because it is not compatible with this version of ownCloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Installer.php(210): OC\\\\Installer::checkAppsIntegrity(Array, '\\\/tmp\\\/oc_tmp_hYU...', '\\\/tmp\\\/oc_tmp_4nD...', false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Installer.php(263): OC\\\\Installer::updateApp(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(454): OC\\\\Installer::updateAppByOCSId('169116')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(254): OC\\\\Updater->upgradeAppStoreApps(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(150): OC\\\\Updater->doUpgrade('9.1.2.5', '9.0.6.5')\\n#5 \\\/var\\\/www\\\/owncloud\\\/core\\\/Command\\\/Upgrade.php(290): OC\\\\Updater->upgrade()\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(844): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Console\\\/Application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud\\\/console.php(102): OC\\\\Console\\\\Application->run()\\n#12 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Installer.php\",\"Line\":395}","level":3,"time":"2016-11-10T09:40:54+01:00","method":"--","url":"--","user":"--"}
```

**Comment by PVince81** [comment]
@DeepDiver1975 I heard you're working on app APIs ? :smile:

**Comment by RealRancor** [comment]
The question is also, especially for the "App can't be installed because it is not compatible with this version of ownCloud" message if the whole Exception needs to be printed out here.

**Comment by PVince81** [comment]
will be obsoleted by market logic
