### ISSUE TITLE
undefined $updateStepEnabled in core/Command/Upgrade.php#L199 

### ISSUE THREAD

**Issue by butonic** [owncloud/core#26680]
Tried updating master on oracle:
`grep GffT1NFRWOqmQ11vrbbN data/owncloud.log`:
```json
{"reqId":"GffT1NFRWOqmQ11vrbbN","remoteAddr":"","app":"PHP","message":"Undefined variable: updateStepEnabled at /home/jfd/www/core/core/Command/Upgrade.php#199","level":3,"time":"2016-11-22T07:49:59+00:00","method":"--","url":"--","user":"--"}
{"reqId":"GffT1NFRWOqmQ11vrbbN","remoteAddr":"","app":"core","message":"starting upgrade from 9.2.0.2 to 9.2.0.3","level":0,"time":"2016-11-22T07:49:59+00:00","method":"--","url":"--","user":"--"}
{"reqId":"GffT1NFRWOqmQ11vrbbN","remoteAddr":"","app":"core","message":"Failed to update database structure (exception 'Doctrine\DBAL\Driver\OCI8\OCI8Exception' with message 'ORA-02429: cannot drop index used for enforcement of unique/primary key' in /home/jfd/www/core/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
Stack trace:
#0 /home/jfd/www/core/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php(229): Doctrine\DBAL\Driver\OCI8\OCI8Exception::fromErrorInfo(Array)
#1 /home/jfd/www/core/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php(116): Doctrine\DBAL\Driver\OCI8\OCI8Statement->execute()
#2 /home/jfd/www/core/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(935): Doctrine\DBAL\Driver\OCI8\OCI8Connection->query('DROP INDEX appc...')
#3 /home/jfd/www/core/lib/private/DB/Migrator.php(257): Doctrine\DBAL\Connection->query('DROP INDEX appc...')
#4 /home/jfd/www/core/lib/private/DB/Migrator.php(85): OC\DB\Migrator->applySchema(Object(Doctrine\DBAL\Schema\Schema))
#5 /home/jfd/www/core/lib/private/DB/MDB2SchemaManager.php(118): OC\DB\Migrator->migrate(Object(Doctrine\DBAL\Schema\Schema))
#6 /home/jfd/www/core/lib/private/legacy/db.php(185): OC\DB\MDB2SchemaManager->updateDbFromStructure('/home/jfd/www/c...')
#7 /home/jfd/www/core/lib/private/Updater.php(275): OC_DB::updateDbFromStructure('/home/jfd/www/c...')
#8 /home/jfd/www/core/lib/private/Updater.php(227): OC\Updater->doCoreUpgrade()
#9 /home/jfd/www/core/lib/private/Updater.php(121): OC\Updater->doUpgrade('9.2.0.3', '9.2.0.2')
#10 /home/jfd/www/core/core/Command/Upgrade.php(259): OC\Updater->upgrade()
#11 /home/jfd/www/core/lib/composer/symfony/console/Command/Command.php(256): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/jfd/www/core/lib/composer/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/jfd/www/core/lib/composer/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/jfd/www/core/lib/composer/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/jfd/www/core/lib/private/Console/Application.php(158): Symfony\Component\Console\Application->run(NULL, NULL)
#16 /home/jfd/www/core/console.php(99): OC\Console\Application->run()
#17 /home/jfd/www/core/occ(11): require_once('/home/jfd/www/c...')
#18 {main}

Next exception 'Doctrine\DBAL\Exception\DriverException' with message 'An exception occurred while executing 'DROP INDEX appconfig_appid_key_index_new':

ORA-02429: cannot drop index used for enforcement of unique/primary key' in /home/jfd/www/core/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:76
Stack trace:
#0 /home/jfd/www/core/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception))
#1 /home/jfd/www/core/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(945): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\OCI8\Driver), Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception), 'DROP INDEX appc...')
#2 /home/jfd/www/core/lib/private/DB/Migrator.php(257): Doctrine\DBAL\Connection->query('DROP INDEX appc...')
#3 /home/jfd/www/core/lib/private/DB/Migrator.php(85): OC\DB\Migrator->applySchema(Object(Doctrine\DBAL\Schema\Schema))
#4 /home/jfd/www/core/lib/private/DB/MDB2SchemaManager.php(118): OC\DB\Migrator->migrate(Object(Doctrine\DBAL\Schema\Schema))
#5 /home/jfd/www/core/lib/private/legacy/db.php(185): OC\DB\MDB2SchemaManager->updateDbFromStructure('/home/jfd/www/c...')
#6 /home/jfd/www/core/lib/private/Updater.php(275): OC_DB::updateDbFromStructure('/home/jfd/www/c...')
#7 /home/jfd/www/core/lib/private/Updater.php(227): OC\Updater->doCoreUpgrade()
#8 /home/jfd/www/core/lib/private/Updater.php(121): OC\Updater->doUpgrade('9.2.0.3', '9.2.0.2')
#9 /home/jfd/www/core/core/Command/Upgrade.php(259): OC\Updater->upgrade()
#10 /home/jfd/www/core/lib/composer/symfony/console/Command/Command.php(256): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/jfd/www/core/lib/composer/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/jfd/www/core/lib/composer/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/jfd/www/core/lib/composer/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/jfd/www/core/lib/private/Console/Application.php(158): Symfony\Component\Console\Application->run(NULL, NULL)
#15 /home/jfd/www/core/console.php(99): OC\Console\Application->run()
#16 /home/jfd/www/core/occ(11): require_once('/home/jfd/www/c...')
#17 {main})","level":4,"time":"2016-11-22T07:50:54+00:00","method":"--","url":"--","user":"--"}
{"reqId":"GffT1NFRWOqmQ11vrbbN","remoteAddr":"","app":"core","message":"Exception: {"Exception":"Doctrine\DBAL\Exception\DriverException","Message":"An exception occurred while executing 'DROP INDEX appconfig_appid_key_index_new':\
\
ORA-02429: cannot drop index used for enforcement of unique/primary key","Code":0,"Trace":"#0 /home/jfd/www/core/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception))\
#1 /home/jfd/www/core/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(945): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\OCI8\Driver), Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception), 'DROP INDEX appc...')\
#2 /home/jfd/www/core/lib/private/DB/Migrator.php(257): Doctrine\DBAL\Connection->query('DROP INDEX appc...')\
#3 /home/jfd/www/core/lib/private/DB/Migrator.php(85): OC\DB\Migrator->applySchema(Object(Doctrine\DBAL\Schema\Schema))\
#4 /home/jfd/www/core/lib/private/DB/MDB2SchemaManager.php(118): OC\DB\Migrator->migrate(Object(Doctrine\DBAL\Schema\Schema))\
#5 /home/jfd/www/core/lib/private/legacy/db.php(185): OC\DB\MDB2SchemaManager->updateDbFromStructure('/home/jfd/www/c...')\
#6 /home/jfd/www/core/lib/private/Updater.php(275): OC_DB::updateDbFromStructure('/home/jfd/www/c...')\
#7 /home/jfd/www/core/lib/private/Updater.php(227): OC\Updater->doCoreUpgrade()\
#8 /home/jfd/www/core/lib/private/Updater.php(121): OC\Updater->doUpgrade('9.2.0.3', '9.2.0.2')\
#9 /home/jfd/www/core/core/Command/Upgrade.php(259): OC\Updater->upgrade()\
#10 /home/jfd/www/core/lib/composer/symfony/console/Command/Command.php(256): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\
#11 /home/jfd/www/core/lib/composer/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\
#12 /home/jfd/www/core/lib/composer/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\
#13 /home/jfd/www/core/lib/composer/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\
#14 /home/jfd/www/core/lib/private/Console/Application.php(158): Symfony\Component\Console\Application->run(NULL, NULL)\
#15 /home/jfd/www/core/console.php(99): OC\Console\Application->run()\
#16 /home/jfd/www/core/occ(11): require_once('/home/jfd/www/c...')\
#17 {main}","File":"/home/jfd/www/core/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php","Line":76}","level":3,"time":"2016-11-22T07:50:54+00:00","method":"--","url":"--","user":"--"}
```

`$updateStepEnabled` is undefined in https://github.com/owncloud/core/blob/master/core/Command/Upgrade.php#L199 I did not have to dig into this class. @PVince81 maybe.

Will look into the oracle problem later ... adding this to not forget it.

**Comment by butonic** [comment]
oracle problems were of my own making because I converted the appconfig configvalue to VARCHAR 4000 for testing ...

the undefined `$updateStepEnabled` remains an issue, though.

**Comment by PVince81** [comment]
`$updateStepEnabled` is some old stuff from before we killed upgrade migration. I fixed it here, please review: https://github.com/owncloud/core/pull/26686
