### ISSUE TITLE
OC9.1.2 - FTP mount (ftps) shows SSL/TLS already set-up for this stream

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#26738]
## Expected behavior

It should be possible to run a file scan on a FTP share, which has been mounted using `ftps`, without showing any errors.

## Current behavior

If you run a file scan on a FTP share, which has been mounted using `ftps`, an **SSL/TLS already set-up for this stream** exception is shown.

### Steps to reproduce
1. Create a mount to an external FTP storage and mark the `secure ftps://` option.
2. Make sure that you can access the new folder in the files menue.
3. Open a shell, switch to the web server user and run the following command:
```
> ./occ -vv files:scan --path="/juergen/files/FTP"

Starting scan for user 1 out of 1 (juergen)
        Folder /juergen/files/FTP/
Exception while scanning: opendir(): SSL/TLS already set-up for this stream
#0 [internal function]: OCA\Files\Command\Scan->exceptionErrorHandler(2, 'opendir(): SSL/...', '/var/www/htdocs...', 65, Array)
#1 /var/www/htdocs/owncloud/apps/files_external/lib/Lib/Storage/StreamWrapper.php(65): opendir('ftps://juergen:...')
#2 /var/www/htdocs/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(96): OCA\Files_External\Lib\Storage\StreamWrapper->opendir('')
#3 /var/www/htdocs/owncloud/lib/private/Files/Storage/Wrapper/Availability.php(105): OC\Files\Storage\Wrapper\Wrapper->opendir('')
#4 /var/www/htdocs/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(96): OC\Files\Storage\Wrapper\Availability->opendir('')
#5 /var/www/htdocs/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(96): OC\Files\Storage\Wrapper\Wrapper->opendir('')
#6 /var/www/htdocs/owncloud/lib/private/Files/Cache/Scanner.php(346): OC\Files\Storage\Wrapper\Wrapper->opendir('')
#7 /var/www/htdocs/owncloud/lib/private/Files/Cache/Scanner.php(397): OC\Files\Cache\Scanner->getNewChildren('')
#8 /var/www/htdocs/owncloud/lib/private/Files/Cache/Scanner.php(377): OC\Files\Cache\Scanner->handleChildren('', true, 3, '320450', true, 0)
#9 /var/www/htdocs/owncloud/lib/private/Files/Cache/Scanner.php(311): OC\Files\Cache\Scanner->scanChildren('', true, 3, 320450, true)
#10 /var/www/htdocs/owncloud/lib/private/Files/Utils/Scanner.php(195): OC\Files\Cache\Scanner->scan('', true, 3)
#11 /var/www/htdocs/owncloud/apps/files/lib/Command/Scan.php(158): OC\Files\Utils\Scanner->scan('/juergen/files/...')
#12 /var/www/htdocs/owncloud/apps/files/lib/Command/Scan.php(226): OCA\Files\Command\Scan->scanFiles('juergen', '/juergen/files/...', true, Object(Symfony\Component\Console\Output\ConsoleOutput), false)
#13 /var/www/htdocs/owncloud/3rdparty/symfony/console/Command/Command.php(259): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/htdocs/owncloud/core/Command/Base.php(158): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/htdocs/owncloud/3rdparty/symfony/console/Application.php(844): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/htdocs/owncloud/3rdparty/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/htdocs/owncloud/3rdparty/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/htdocs/owncloud/lib/private/Console/Application.php(146): Symfony\Component\Console\Application->run(NULL, NULL)
#19 /var/www/htdocs/owncloud/console.php(102): OC\Console\Application->run()
#20 /var/www/htdocs/owncloud/occ(11): require_once('/var/www/htdocs...')
#21 {main}

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 1       | 0     | 00:00:00     |
+---------+-------+--------------+
```

#### Server Configuration

OS: Linux 3.2.82
Web server: Apache2 2.4.23
Database: MariaDB 5.5.53
PHP version: 5.6.23
ownCloud version: 9.1.2

#### Client Configuration

Browser: Mozilla Firefox 50.0
Operating system: Windows 7

**Comment by RealRancor** [comment]
@j-ed I think the first step is to get files scanning on FTP to work at all: https://github.com/owncloud/core/issues/16407

**Comment by PVince81** [comment]
Does it work on master with the "files_external_ftp" app ? The FTP stuff was ported to use Flysystem's FTP connector (https://flysystem.thephpleague.com/) which might hopefully work better with more FTP configurations.

**Comment by nebulade** [comment]
I get the exact same issue, which came up after owncloud reports, that I don't have permissions to create files or folders in a few directories of the ftps storage, which is why I tried to rescan. What kind of additional info would be helpful?

Thanks.

**Comment by j-ed** [comment]
@PVince81 Is this already part of OC 9.1.3?

**Comment by PVince81** [comment]
Please try with OC 10.0.2 and the marketplace app "files_external_ftp" which uses a new API (flysystem) to connect to FTP. With a bit of luck this library might solve the problem already.
