### ISSUE TITLE
App passwords deleted after changing main password

### ISSUE THREAD

**Issue by nightspotlight** [owncloud/core#26731]
### Steps to reproduce
1. Login to ownCloud
2. Go to Personal settings
3. Create an app password with the name "owncloud @ smartphone"
4. Input and save the generated password into the app
5. Use the app for a while, close it
6. On next use of the app find the app asking for the password
7. Login to ownCloud, open Personal settings, find the app password disappeared

### Expected behaviour
App password should persist

### Actual behaviour
App passwords disappear after a while

### Server configuration
**Operating system:** Ubuntu 16.04.1 LTS

**Web server:** nginx/1.10.0

**Database:** mysql  Ver 15.1 Distrib 10.0.27-MariaDB

**PHP version:** PHP 7.0.8-0ubuntu0.16.04.3

**ownCloud version:** 9.1.2 (stable)

**Updated from an older ownCloud or fresh install:** Upgraded from 8.2 and 9.0

**Where did you install ownCloud from:** owncloud-9.1.2.tar.bz2

**Signing status (ownCloud 9.0 and above):** 

```
No errors have been found.
```

**List of activated apps:** 

```
Enabled:
  - activity: 2.3.2
  - audioplayer: 1.3.1
  - calendar: 1.4.1
  - comments: 0.3.0
  - contacts: true
  - dav: 0.2.7
  - direct_menu: true
  - documents: true
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc2p9k9xylq6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.nightspotlight.me"
        ],
        "datadirectory": "\/data\/owncloud-data",
        "overwrite.cli.url": "https:\/\/cloud.nightspotlight.me",
        "dbtype": "mysql",
        "version": "9.1.2.5",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "cloud",
        "mail_smtpmode": "php",
        "mail_domain": "nightspotlight.me",
        "loglevel": 4,
        "maintenance": false,
        "theme": "",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 50.0

**Operating system:** Windows 10

#### Web server error log
```
2016/11/26 15:14:15 [error] 18568#18568: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:unable to get local issuer certificate) while requesting certificate status, responder: ocsp.startssl.com
2016/11/26 15:16:12 [error] 18569#18569: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:unable to get local issuer certificate) while requesting certificate status, responder: ocsp.startssl.com
2016/11/26 19:19:34 [error] 18568#18568: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:unable to get local issuer certificate) while requesting certificate status, responder: ocsp.startssl.com
2016/11/26 19:46:38 [warn] 18568#18568: *65301 an upstream response is buffered to a temporary file /var/lib/nginx/fastcgi/8/86/0000001868 while reading upstream, client: x.x.x.x, server: cloud.nightspotlight.me, request: "GET /index.php/apps/audioplayer/getmusic HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "cloud.nightspotlight.me"
2016/11/26 19:47:57 [error] 18568#18568: *65301 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: cloud.nightspotlight.me, request: "POST /index.php/apps/audioplayer/scanforaudiofiles HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock", host: "cloud.nightspotlight.me"
```

#### ownCloud log (data/owncloud.log)
```
too long to paste. last line:
{"reqId":"euYTzto0uX5AUZwkG0m9","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(588): Sabre\\\\DAV\\\\Server->createCollection('InstantUpload', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1121,\"User\":\"user1\"}","level":4,"time":"2016-11-24T20:19:27+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/InstantUpload\/","user":"user1"}
```

#### Browser log
```
too long to paste, probably irrelevant
```

**Comment by PVince81** [comment]
Hmm weird... I also use app passwords extensively but never saw any of them disappear before with 9.1.1 or 9.1.2.

**Comment by PVince81** [comment]
@PhilippSchaffrath in case you find understand conditions an app password would auto-destruct

**Comment by nightspotlight** [comment]
Seems to not happen anymore when I input name without spaces.

**Comment by PVince81** [comment]
I also have names with spaces like "Desktop client".

**Comment by PVince81** [comment]
seems you're not alone: https://github.com/nextcloud/server/issues/2431

**Comment by PVince81** [comment]
@phisch

**Comment by nightspotlight** [comment]
Not sure if it's a bug or expected behavior, but after I changed my main password, my app passwords got deleted. But they only vanished after apps were opened. I still have two apps that were last opened a few days ago, and when I open them I expect their passwords to be autodestructed. This undermines the idea of having independent app passwords for me. Same setup but ownCloud v. 9.1.4.

If that is expected behavior, then a warning message should appear that app passwords get deleted with password update, to avoid this sort of confusion.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
I remember @tomneedham discovered the same issue, it happens only when changing the password either on DB or LDAP. Not sure whether we had a ticket for this, so reopening this for now.

**Comment by PVince81** [comment]
There is a technical challenge here: the app passwords are used to encrypt the user's password inside the database (combined with the secret from config.php and possibly other things). The reason for this is because said user's password is used to ping the LDAP server to detect whether the user was deleted and also to make user-key encryption work as it needs the user password as well.

If the user's password changed, then we need to iterate over all app passwords and then reencrypt the user's new password with said keys. However we don't have the actual list of app passwords as it would be a security issue, they are only hashed. So it is not possible to reencrypt with the original app passwords.

This is likely the reason why the old app passwords are deleted.

Yes, I also think this is suboptimal because the reason one wants to use app passwords is to be able to have them independent from the main password.

I wonder whether the oauth app also has a similar limitation.

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
> I wonder whether the oauth app also has a similar limitation.

not that I'm aware of - because no user password is stored together with the oauth token - which has it's own limitations .....

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).

**Comment by PVince81** [comment]
I'm reopening this as we need to decide whether we consider this "by design" or whether we want to invest time to rework this with a different approach that doesn't have the same shortcomings, if even possible.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by adriandab** [comment]
I have a similar issue with temporarily locked out accounts. 

Setup: Active Directory is the user DB, Desktop client installed with app passwords enabled. 

Reproduce:
1) use any other AD-connected service to login 3 times with wrong password, e.g., OWA, Imap, ftp..., thus locking it temporarily. 
2) make desktop client sync something (start resync, add file, ...)
3) Server deletes app password, even when the account becomes unlocked after 1h again.

**Comment by VikDex** [comment]
the app password must not be deleted. i set it back to the usual password, because you cannot set on this feature at this time ... please help to solve that, because it's adding more security in an easy way.

**Comment by eripslionoac** [comment]
Hello. 
I have the same issue here. App passwords/token are deleted after changing main password. Apps tries to authenticate many times and lock Active Directory account.

ownCloud version : 10.8.0.4

**Comment by phil-davis** [comment]
Note: I made issue #39490 to add test coverage for this. That will help us see if we can reproduce the issue, and minimize the chance of regressions.
