### ISSUE TITLE
Base table or view not found: 1146 Table 'mathcloud.oc_authtoken' doesn't exist

### ISSUE THREAD

**Issue by deepeshmittal** [owncloud/core#26783]
Hi All,

I did some search online and also on this forum and when I didn't find the solution yet I decided to post an issue here.

I was using OC 9.0.X version and I wanted to upgrade my OC to 9.1.X. While upgrading it was throwing error for PHP5 sqllite and pgsql packages probably because I have PHP 7 installed on my system. So I decided to download new tar file from OC website and tried to configuring new code with my existing data folder and MySQL database. But when I am trying to configure app from webpage by providing all required details like admin username, password, data folder and db information I get internal server error.

In owncloud log I am getting error "Base table or view not found: 1146 Table 'mathcloud.oc_authtoken' doesn't exist". Is this the new table added with OC 9.1 and not present in OC 9.0. Please let me know how can I configure new owncloud with my existing tables schema.

### Steps to reproduce
1. Configuring new OC using new .bz2 file from the OC website
2.
3.

### Expected behaviour
Successful installation

### Actual behaviour
Installation fails

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** apache2

**Database:** MySQL

**PHP version:** 7

**ownCloud version:** (see ownCloud admin page)  9.1.2.5

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** OC website

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"doZdCCPpzUsURj\/fw4F2","remoteAddr":"129.219.51.198","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `id`, `uid`, `login_name`, `password`, `name`, `type`, `token`, `last_activity`, `last_check` FROM `oc_authtoken` WHERE `token` = ?' with params [\\\"1c8c3d7f7995166e2facdd57e8f1c042891f6e7201d7009ba17108608d22aad6b82b39ac8e44e44272884d6c9327e2abb3d6f2636c50a1e02c645228eb435ba0\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'mathcloud.oc_authtoken' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(188): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenMapper.php(77): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(147): OC\\\\Authentication\\\\Token\\\\DefaultTokenMapper->getToken(*** sensitive parameters replaced ***)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(616): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->getToken(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(284): OC\\\\User\\\\Session->validateToken(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Setup.php(375): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/SetupController.php(64): OC\\\\Setup->install(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(829): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","level":3,"time":"2016-12-06T21:55:19+00:00","method":"POST","url":"\/owncloud\/index.php","user":"--"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
> But when I am trying to configure app from webpage by providing all required details like admin username, password, data folder and db information I get internal server error

This workflow will not work with existing data. See https://github.com/owncloud/core/issues/25665

You need to reuse your old database + config.php + data folder but with the new ownCloud tarball code, then upgrade to that.

Not an ownCloud bug, the install page works as expected.
