### ISSUE TITLE
HTTP 1.1 404 : NFS storage on local external storage 

### ISSUE THREAD

**Issue by kodoku** [owncloud/core#26876]
### Steps to reproduce
1. Install owncloud from RPM repo ownCloud 9.1.3 (stable)
2. Mount a NFS share on your server
3. add local storage on NFS directory

### Expected behaviour
Can see your files in owncloud

### Actual behaviour
Can't see files in owncloud. I can list my NFS directory with apache user.

### Server configuration
**Operating system**: Centos 7.3

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5

**PHP version:** 5.4.16

**ownCloud version:** 9.1.3 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** RPM

**Signing status (ownCloud 9.0 and above):** all clear

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc5lqcc57und",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.geekops.fr"
        ],
        "datadirectory": "\/data\/owncloud\/",
        "overwrite.cli.url": "http:\/\/cloud.geekops.fr\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.3.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APC"
    }
}

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:**no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows

#### Web server error log
```
no error
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"WGJC9pgTHRZT51FvIi4rlwAAAAE","remoteAddr":"192.168.1.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name NFSDirectory could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('yesyes')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(334): Sabre\\\\DAV\\\\Server->getPropertiesForPath('yesyes', Array, 1)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":170,\"User\":\"admin\"}","level":0,"time":"2016-12-27T10:31:18+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/yesyes","user":"admin"}
{"reqId":"WGJC9j6x1WvEGlB2tWzpFAAAAAA","remoteAddr":"192.168.1.1","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path '' is not accessible or present !!!","level":0,"time":"2016-12-27T10:31:18+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"admin"}
{"reqId":"WGJC9j6x1WvEGlB2tWzpFAAAAAA","remoteAddr":"192.168.1.1","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path '' is not accessible or present !!!","level":0,"time":"2016-12-27T10:31:18+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"admin"}
{"reqId":"WGJC-PXB4jeK61KAJ3xejQAAAAk","remoteAddr":"192.168.1.1","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path '' is not accessible or present !!!","level":0,"time":"2016-12-27T10:31:25+00:00","method":"PROPFIND","url":"\/remote.php\/webdav","user":"admin"}
{"reqId":"eZNHve\/PAHPBInHDtQNd","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APC not available for local cache","level":1,"time":"2016-12-27T10:37:33+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eZNHve\/PAHPBInHDtQNd","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APC not available for distributed cache","level":1,"time":"2016-12-27T10:37:33+00:00","method":"--","url":"--","user":"--"}

```

#### Browser log
```
```

**Comment by PVince81** [comment]
Assuming you don't have "open_basedir" enabled ?

Have you tried adding a leading slash to "/NFSDirectory" in the config ?

**Comment by PVince81** [comment]
closing due to lack of feedback
