### ISSUE TITLE
Webdav or OwnCloud client does not work with mod_lsapi

### ISSUE THREAD

**Issue by MrKoopie** [owncloud/core#26884]
### Steps to reproduce
1. Launch your OwnCloud client.
2. Connect to a server with mod_lsapi.c (the CloudLinux solution for implementing PHP)
3. It will fail (see owncloud logs) and not log in nor synchronise.

### Expected behaviour
Client can sync the files.

### Actual behaviour
Connection Lost: client can not sync file.

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0

**ownCloud version:** (see ownCloud admin page) ownCloud 9.1.3 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** source

**Signing status (ownCloud 9.0 and above):** ?

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - calendar
  - contacts
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "eqrtqertqewrt",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "eqrtqertq-ar.nl"
        ],
        "datadirectory": "\/home\/eqrtqertq\/ownclouddata",
        "tempdirectory": "\/home\/eqrtqertq\/tmp\/",
        "overwrite.cli.url": "https:\/\/eqrtqertq-ar.nl",
        "dbtype": "mysql",
        "version": "9.1.3.1",
        "dbname": "eqrterter",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": "0"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Chrome/Safari

**Operating system:** OS X

#### Web server error log
```
(70008)Partial results are valid but processing is incomplete: [client 123.123.123.123:41937] AH01270: Error reading request entity data
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"wer34t","remoteAddr":"123.123.123.123","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home\\\/username\\\/public_html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/home\\\/username\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home\\\/username\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home\\\/username\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home\\\/username\\\/public_html\\\/remote.php(164): require_once('\\\/home\\\/cloudharu...')\\n#6 {main}\",\"File\":\"\\\/home\\\/username\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-12-29T08:20:57+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
```

#### Browser log
```
unrelated.
```

**Comment by geligelu** [comment]
This looks very similar to my issue - the 'basic authentication' that I just posted! [](https://github.com/owncloud/core/issues/26883 )

**Comment by MrKoopie** [comment]
@geligelu Shout, you are right! Shame on me... Should have checked that one.

Here is the solution: https://github.com/owncloud/core/pull/26885

**Comment by MrKoopie** [comment]
Opened as this issue seems to be different from @geligelu

**Comment by PVince81** [comment]
PR was merged, thanks! Closing
