### ISSUE TITLE
OwnCloud 8.2.2 Error Creating the File or Folder

### ISSUE THREAD

**Issue by JustinCorneby** [owncloud/core#26931]
Using a browser I try and create a folder and at the top of the screen I see a message 'Error when creating the folder'.  I get a similar message if I try and create a file.

If I try a drag a file into the folder window the message at the top of the screen displays; 'Upload failed.  Could not find uploaded file'

I also use version 2.2.4 (build 6408) of the desktop client on a Windows 7 machine, and the sync has stopped working

I'm not always able to delete files and folders from the browser, they reappear after refreshing the web page.
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
Ubuntu 15.10:
apache 2.4.12
mysql 14.14 Distrib 5.6.28
php 5.6.11
ownCloud 8.2.2 - Fresh Install

**Where did you install ownCloud from:**
owncloud.org

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Returns nothing
```

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - user_ldap: 0.7.1
Disabled:
  - encryption
  - external
  - files_external
  - user_external

**The content of config/config.php:**
    "system": {
        "instanceid": "oc91vnuq8qng",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.xxxxxx.com",
            "xxx.xxx.xxx.xxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/oc.ogcuk.com\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "OwnCloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "OGCCloud",
        "mail_domain": "xxxxx.com",
        "mail_smtphost": "xxx.xxx.xxx.xxx",
        "mail_smtpport": "25",
        "appstore.experimental.enabled": false,
        "loglevel": 3
    }
```

Are you using encryption: = no

Are you using an external user-backend, if yes which one: LDAP

ldapAgentName        
ldapAgentPassword = ***                                                                                                           ldapAttributesForGroupSearch  	                                                                                                   ldapAttributesForUserSearch   	                                                                                                   ldapBackupHost                	                                                                                                   ldapBackupPort                	                                                                                                   
ldapBase                      	
ldapBaseGroups                	
ldapBaseUsers                 	
ldapCacheTTL= 600
ldapConfigurationActive = 1
ldapEmailAttribute = mail                                                                                              ldapExperiencedAdmin = 0
ldapExpertUUIDGroupAttr       	                                                                                                   ldapExpertUUIDUserAttr        	                                                                                                   ldapExpertUsernameAttr        	                                                                                                   ldapGroupDisplayName = cn                                                                                                
ldapGroupFilter               	                                                                                                   ldapGroupFilterGroups         	                                                                                                   ldapGroupFilterMode = 0
ldapGroupFilterObjectclass    	                                                                                                   ldapGroupMemberAssocAttr = uniqueMember                                                                                      ldapHost                      	
ldapIgnoreNamingRules         	                                                                                                   ldapLoginFilter = (&(&((objectclass=organizationalPerson)(objectclass=user))(((memberof=CN=Domain Users,CN=Users,DC=xxxxx,DC=intra)(primaryGroupID=513))))((samaccountname=%uid)((mailPrimaryAddress=%uid)(mail=%uid)))) 
ldapLoginFilterAttributes     	                                                                                                   ldapLoginFilterEmail = 1
ldapLoginFilterMode = 0
ldapLoginFilterUsername = 1
ldapNestedGroups = 0
ldapOverrideMainServer        	                                                                                                   ldapPagingSize = 500
ldapPort = 389
ldapQuotaAttribute            	                                                                                                   ldapQuotaDefault              	                                                                                                   
ldapTLS = 0
ldapUserDisplayName = displayName                                                                                       ldapUserFilter = (&((objectclass=organizationalPerson)(objectclass=user))(((memberof=CN=Domain Users,CN=Users,DC=xxxxx,DC=intra)(primaryGroupID=513))))                                                                   
ldapUserFilterGroups = Domain Users                                                                                      ldapUserFilterMode = 0
ldapUserFilterObjectclass = organizationalPerson;user                                                                         ldapUuidGroupAttribute = auto                                                                                              ldapUuidUserAttribute = auto                                                                                              turnOffCertCheck = 0
useMemberOfToDetectMembership = 1

### Client configuration
IE11, and Chrome 55

Windows 7

Owncloud Log
Exception: {"Message":"HTTP\/1.1 500 Could not write file contents","Exception":"Sabre\\DAV\\Exception","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/directory.php(115): OC\\Connector\\Sabre\\File->put(Resource id #33)\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('002.jpg', Resource id #33)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('S2007 - New Haw...', Resource id #33, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":128}

\OC\Files\Filesystem::fopen() failed

fopen(/var/www/owncloud/data/7CB31ED2-8DC5-4B1A-88CF-CE0801B1AE64/files/'Filename'): failed to open stream: Input/output error at /var/www/owncloud/lib/private/files/storage/local.php#247

OwnCloud Client Log

ownCloud/8.2.2,                   C:\OwnCloud,The item is not synced because of previous errors: Error downloading https://Example.com/remote.php/webdav/ownCloud/8.2.2 - server replied: Forbidden

C:\OwnCloud,The item is not synced because of previous errors: Error downloading https://example.com/owncloud/remote.php/webdav/'Filename' - server replied: Internal Server Error (Could not write file contents)

**Comment by kdslkdsaldsal** [comment]
From the issue template you have filled out:

> Before reporting any issues please make sure that you're using the latest available version for your major branch (e.g. 9.0.x), see https://owncloud.org/changelog/

8.2.2 is way too outdated to report issues for it here.

**Comment by PVince81** [comment]
Please try again with 8.2.9 or 9.0.7 and reopen if the problem persists, thanks
