### ISSUE TITLE
Don't write local files in integration tests

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27006]
The tests should not assume that they have write permissions (in my env they don't).

When running this:
```
± % sudo -uwwwrun ./run.sh features/sharing-v1.feature:59                   
./run.sh: line 3: composer: command not found
8080
23883
8180
23884
PHP 7.0.14 Development Server started at Mon Jan 23 20:26:21 2017
Listening on http://localhost:8180
Document root is /srv/www/htdocs/owncloud
Press Ctrl-C to quit.
PHP 7.0.14 Development Server started at Mon Jan 23 20:26:21 2017
Listening on http://localhost:8080
Document root is /srv/www/htdocs/owncloud
Press Ctrl-C to quit.
files_external enabled
Feature: sharing

  Background:                   # /srv/www/htdocs/owncloud/build/integration/features/sharing-v1.feature:2
    Given using api version "1" # FeatureContext::usingApiVersion()
    Given using old dav path    # FeatureContext::usingOldDavPath()

  Scenario: Creating a new public share                    # /srv/www/htdocs/owncloud/build/integration/features/sharing-v1.feature:59
[Mon Jan 23 20:26:22 2017] 127.0.0.1:47524 [404]: /ocs/v2.php/cloud/users/user0
[Mon Jan 23 20:26:22 2017] Successful addUser call with userid: user0
[Mon Jan 23 20:26:22 2017] 127.0.0.1:47528 [200]: /ocs/v1.php/cloud/users
[Mon Jan 23 20:26:23 2017] copying skeleton for user0 from /srv/www/htdocs/owncloud/core/skeleton to /user0/files/
[Mon Jan 23 20:26:23 2017] 127.0.0.1:47532 [200]: /ocs/v1.php/cloud/users/user0
[Mon Jan 23 20:26:24 2017] 127.0.0.1:47536 [200]: /ocs/v2.php/cloud/users/user0
    Given user "user0" exists                              # FeatureContext::assureUserExists()
    And As an "user0"                                      # FeatureContext::asAn()
[Mon Jan 23 20:26:24 2017] 127.0.0.1:47540 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares
    When creating a share with                             # FeatureContext::creatingShare()
      | path      | welcome.txt |
      | shareType | 3           |                                                                                                                                                                                 
    Then the OCS status code should be "100"               # FeatureContext::theOCSStatusCodeShouldBe()
    And the HTTP status code should be "200"               # FeatureContext::theHTTPStatusCodeShouldBe()
[Mon Jan 23 20:26:24 2017] 127.0.0.1:47544 [200]: /index.php/s/UZty8zOy9pXtjWY/download
    And Public shared file "welcome.txt" can be downloaded # FeatureContext::checkPublicSharedFile()
      Unable to open ./welcome.txt using mode w+: fopen(./welcome.txt): failed to open stream: Permission denied (GuzzleHttp\Exception\RequestException)
[Mon Jan 23 20:26:25 2017] 127.0.0.1:47548 [200]: /ocs/v1.php/cloud/users/user0
[Mon Jan 23 20:26:25 2017] 127.0.0.1:47552 [404]: /ocs/v2.php/cloud/users/user0
[Mon Jan 23 20:26:25 2017] Login failed: 'user0' (Remote IP: '127.0.0.1')
[Mon Jan 23 20:26:25 2017] Exception: {"Message":"HTTP\/1.1 401 Username or password was incorrect","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/srv\/www\/htdocs\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(57): Sabre\\DAV\\Server->exec()\n#5 \/srv\/www\/htdocs\/owncloud\/remote.php(164): require_once('\/srv\/www\/htdocs...')\n#6 {main}","File":"\/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}
[Mon Jan 23 20:26:25 2017] 127.0.0.1:47556 [401]: /remote.php/webdav/myFileToComment.txt
[Mon Jan 23 20:26:25 2017] 127.0.0.1:47560 [207]: /remote.php/dav/systemtags/
[Mon Jan 23 20:26:25 2017] Login failed: 'user0' (Remote IP: '127.0.0.1')
[Mon Jan 23 20:26:25 2017] Exception: {"Message":"HTTP\/1.1 401 Username or password was incorrect","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/srv\/www\/htdocs\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(57): Sabre\\DAV\\Server->exec()\n#5 \/srv\/www\/htdocs\/owncloud\/remote.php(164): require_once('\/srv\/www\/htdocs...')\n#6 {main}","File":"\/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}
[Mon Jan 23 20:26:25 2017] 127.0.0.1:47564 [401]: /remote.php/webdav/myFileToTag.txt
[Mon Jan 23 20:26:26 2017] Exception: {"Message":"HTTP\/1.1 404 Addressbook with name 'MyAddressbook' could not be found","Exception":"Sabre\\DAV\\Exception\\NotFound","Code":0,"Trace":"#0 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(76): Sabre\\CardDAV\\AddressBookHome->getChild('MyAddressbook')\n#1 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Schedule\/Plugin.php(334): Sabre\\DAV\\Tree->getNodeForPath('addressbooks\/us...')\n#2 [internal function]: Sabre\\CalDAV\\Schedule\\Plugin->beforeUnbind('addressbooks\/us...')\n#3 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(284): Sabre\\Event\\EventEmitter->emit('beforeUnbind', Array)\n#5 [internal function]: Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#8 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/Server.php(178): Sabre\\DAV\\Server->exec()\n#10 \/srv\/www\/htdocs\/owncloud\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#11 \/srv\/www\/htdocs\/owncloud\/remote.php(164): require_once('\/srv\/www\/htdocs...')\n#12 {main}","File":"\/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/AddressBookHome.php","Line":137,"User":"admin"}
[Mon Jan 23 20:26:26 2017] 127.0.0.1:47568 [404]: /remote.php/dav/addressbooks/users/admin/MyAddressbook
[Mon Jan 23 20:26:26 2017] Exception: {"Message":"HTTP\/1.1 404 Node with name 'MyCalendar' could not be found","Exception":"Sabre\\DAV\\Exception\\NotFound","Code":0,"Trace":"#0 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(76): OCA\\DAV\\CalDAV\\CalendarHome->getChild('MyCalendar')\n#1 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Schedule\/Plugin.php(334): Sabre\\DAV\\Tree->getNodeForPath('calendars\/admin...')\n#2 [internal function]: Sabre\\CalDAV\\Schedule\\Plugin->beforeUnbind('calendars\/admin...')\n#3 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(284): Sabre\\Event\\EventEmitter->emit('beforeUnbind', Array)\n#5 [internal function]: Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#8 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/Server.php(178): Sabre\\DAV\\Server->exec()\n#10 \/srv\/www\/htdocs\/owncloud\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#11 \/srv\/www\/htdocs\/owncloud\/remote.php(164): require_once('\/srv\/www\/htdocs...')\n#12 {main}","File":"\/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/CalDAV\/CalendarHome.php","Line":104,"User":"admin"}
[Mon Jan 23 20:26:26 2017] 127.0.0.1:47572 [404]: /remote.php/dav/calendars/admin/MyCalendar

--- Failed scenarios:

    /srv/www/htdocs/owncloud/build/integration/features/sharing-v1.feature:59
```

From what I see the function `checkPublicSharedFile` tries to save the stream to a local file.

This must be changed to download to memory. From what I see it even discards the file, only checking if the download goes through. So maybe use Guzzle stream mode and stream read everything but keep nothing.

@SergioBertolinSG low prio

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/issues/27008
