### ISSUE TITLE
Unable to bypass session when making WebDAV PROPFIND requests

### ISSUE THREAD

**Issue by perry-mitchell** [owncloud/core#27093]
### Steps to reproduce
1. Make an XHR (PROPFIND) request to get directory contents of **accountA**
2. Make a second XHR in the same page (PROPFIND) to get the directory contents of **accountB**
3. The contents returned by both requests is the contents of **accountA**

### Expected behaviour
Requests for each accounts' contents should return their respective contents

### Actual behaviour
A session is formed with the first account and each consecutive request returns only the contents of the first account.

On other occasions, if I log into owncloud's web interface and then make an XHR under another user, I receive "401 Unauthorized".

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7

**ownCloud version:** 9.1.3

**Updated from an older ownCloud or fresh install:** Fresh

**Where did you install ownCloud from:** zip from ownCloud website

**Signing status (ownCloud 9.0 and above):** Unsigned

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - calendar: true
  - comments: 0.3.0
  - contacts: true
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - firstrunwizard
  - gallery
  - notifications
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '5285d8dfdf7c1',
  'passwordsalt' => '<snip>',
  'datadirectory' => '/usr/share/nginx/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '9.1.3.1',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => '<snip>',
    1 => '<snip>',
  ),
  'mail_from_address' => 'no-reply',
  'mail_smtpmode' => 'php',
  'mail_domain' => '<snip>',
  'secret' => '<snip>',
  'loglevel' => 0,
  'trashbin_retention_obligation' => 'auto',
  'dbname' => '<snip>',
  'dbhost' => 'localhost:3306',
  'dbuser' => '<snip>',
  'dbpassword' => '<snip>',
);
```

**Are you using external storage, if yes which one:** nfs

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Google Chrome 55.0.2883.95 (64-bit)

**Operating system:** macOS Sierra 10.12.3

#### ownCloud log (data/owncloud.log)
```
{"reqId":"xEZ7NDlJeLMl5RiXw\/xw","remoteAddr":"<snip>","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 CSRF check not passed.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(146): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(163): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#5 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/remote.php(164): require_once('\\\/usr\\\/share\\\/ngin...')\\n#8 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php\",\"Line\":211,\"User\":\"user1\"}","level":0,"time":"2017-02-06T21:18:50+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"user1"}
{"reqId":"sT7MgGGLyl8com5gNYyn","remoteAddr":"<snip>","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2017-02-06T21:21:04+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"user2"}
{"reqId":"seNHtqYQnTAKZ2j8ztPS","remoteAddr":"<snip>","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2017-02-06T21:21:30+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"user1"}
{"reqId":"2L83abhCm7dw\/A72g4FF","remoteAddr":"<snip>","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/remote.php(164): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-02-06T21:21:42+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user1\/","user":"--"}
{"reqId":"cT0k8ZjJ8b8RxFuMXiQr","remoteAddr":"<snip>","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2017-02-06T21:21:52+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"user1"}
{"reqId":"pxpX4Hy+OfVTy9i4WNFk","remoteAddr":"<snip>","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2017-02-06T21:22:09+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"user1"}
{"reqId":"3IuduvS5RUnuR\/zmKKuV","remoteAddr":"<snip>","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2017-02-06T21:22:12+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"user1"}
```

#### Browser log (HAR portion)
```
{
"startedDateTime": "2017-02-06T21:22:09.801Z",
"time": 61.46399999852292,
"request": {
    "method": "PROPFIND",
    "url": "https://myHost/remote.php/webdav/",
    "httpVersion": "HTTP/1.1",
    "headers": [
    {
        "name": "Pragma",
        "value": "no-cache"
    },
    {
        "name": "Origin",
        "value": "chrome-extension://kimimehhmpknfpclifcokkonbgnfjeej"
    },
    {
        "name": "Accept-Encoding",
        "value": "gzip, deflate, sdch, br"
    },
    {
        "name": "Host",
        "value": "myHost"
    },
    {
        "name": "Accept-Language",
        "value": "en-US,en;q=0.8"
    },
    {
        "name": "User-Agent",
        "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"
    },
    {
        "name": "accept",
        "value": "*/*"
    },
    {
        "name": "Cache-Control",
        "value": "no-cache"
    },
    {
        "name": "x-perry-test",
        "value": "Ok"
    },
    {
        "name": "authorization",
        "value": "Basic /snip/"
    },
    {
        "name": "Cookie",
        "value": "cookie_test=test; oc_sessionPassphrase=/snip/; _ga=GA1.2.1632897266.1481365281; /snip/"
    },
    {
        "name": "Connection",
        "value": "keep-alive"
    },
    {
        "name": "ocs-api",
        "value": "true"
    },
    {
        "name": "depth",
        "value": "1"
    }
    ],
    "queryString": [],
    "cookies": [
    {
        "name": "cookie_test",
        "value": "test",
        "expires": null,
        "httpOnly": false,
        "secure": false
    },
    {
        "name": "oc_sessionPassphrase",
        "value": "snip",
        "expires": null,
        "httpOnly": false,
        "secure": false
    },
    {
        "name": "_ga",
        "value": "GA1.2.1632897266.1481365281",
        "expires": null,
        "httpOnly": false,
        "secure": false
    },
    {
        "name": "5285d8dfdf7c1",
        "value": "snip",
        "expires": null,
        "httpOnly": false,
        "secure": false
    }
    ],
    "headersSize": 781,
    "bodySize": 0
},
"response": {
    "status": 207,
    "statusText": "Multi-Status",
    "httpVersion": "HTTP/1.1",
    "headers": [
    {
        "name": "Pragma",
        "value": "no-cache"
    },
    {
        "name": "Date",
        "value": "Mon, 06 Feb 2017 21:22:09 GMT"
    },
    {
        "name": "Vary",
        "value": "Brief,Prefer"
    },
    {
        "name": "Server",
        "value": "nginx/1.10.0 (Ubuntu)"
    },
    {
        "name": "Transfer-Encoding",
        "value": "chunked"
    },
    {
        "name": "Content-Type",
        "value": "application/xml; charset=utf-8"
    },
    {
        "name": "DAV",
        "value": "1, 3, extended-mkcol"
    },
    {
        "name": "Cache-Control",
        "value": "no-store, no-cache, must-revalidate"
    },
    {
        "name": "Content-Security-Policy",
        "value": "default-src 'none';"
    },
    {
        "name": "Connection",
        "value": "keep-alive"
    },
    {
        "name": "Expires",
        "value": "Thu, 19 Nov 1981 08:52:00 GMT"
    }
    ],
    "cookies": [],
    "content": {
    "size": 7235,
    "mimeType": "application/xml",
    "compression": -13
    },
    "redirectURL": "",
    "headersSize": 398,
    "bodySize": 7248,
    "_transferSize": 7646
},
"cache": {},
"timings": {
    "blocked": 1.08399998862296,
    "dns": -1,
    "connect": -1,
    "send": 0.10400000610388993,
    "wait": 59.59399999119345,
    "receive": 0.6820000126026216,
    "ssl": -1
},
"serverIPAddress": "snip",
"connection": "231275",
"pageref": "page_4"
},
{
"startedDateTime": "2017-02-06T21:22:12.448Z",
"time": 68.94199998350814,
"request": {
    "method": "PROPFIND",
    "url": "https://myHost/remote.php/webdav/",
    "httpVersion": "HTTP/1.1",
    "headers": [
    {
        "name": "Pragma",
        "value": "no-cache"
    },
    {
        "name": "Origin",
        "value": "chrome-extension://kimimehhmpknfpclifcokkonbgnfjeej"
    },
    {
        "name": "Accept-Encoding",
        "value": "gzip, deflate, sdch, br"
    },
    {
        "name": "Host",
        "value": "myHost"
    },
    {
        "name": "Accept-Language",
        "value": "en-US,en;q=0.8"
    },
    {
        "name": "User-Agent",
        "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"
    },
    {
        "name": "accept",
        "value": "*/*"
    },
    {
        "name": "Cache-Control",
        "value": "no-cache"
    },
    {
        "name": "x-perry-test",
        "value": "Ok"
    },
    {
        "name": "authorization",
        "value": "Basic /snip/"
    },
    {
        "name": "Cookie",
        "value": "cookie_test=test; oc_sessionPassphrase=/snip.; _ga=GA1.2.1632897266.1481365281; /snip/"
    },
    {
        "name": "Connection",
        "value": "keep-alive"
    },
    {
        "name": "ocs-api",
        "value": "true"
    },
    {
        "name": "depth",
        "value": "1"
    }
    ],
    "queryString": [],
    "cookies": [
    {
        "name": "cookie_test",
        "value": "test",
        "expires": null,
        "httpOnly": false,
        "secure": false
    },
    {
        "name": "oc_sessionPassphrase",
        "value": "snip",
        "expires": null,
        "httpOnly": false,
        "secure": false
    },
    {
        "name": "_ga",
        "value": "GA1.2.1632897266.1481365281",
        "expires": null,
        "httpOnly": false,
        "secure": false
    },
    {
        "name": "5285d8dfdf7c1",
        "value": "snip",
        "expires": null,
        "httpOnly": false,
        "secure": false
    }
    ],
    "headersSize": 781,
    "bodySize": 0
},
"response": {
    "status": 207,
    "statusText": "Multi-Status",
    "httpVersion": "HTTP/1.1",
    "headers": [
    {
        "name": "Pragma",
        "value": "no-cache"
    },
    {
        "name": "Date",
        "value": "Mon, 06 Feb 2017 21:22:12 GMT"
    },
    {
        "name": "Vary",
        "value": "Brief,Prefer"
    },
    {
        "name": "Server",
        "value": "nginx/1.10.0 (Ubuntu)"
    },
    {
        "name": "Transfer-Encoding",
        "value": "chunked"
    },
    {
        "name": "Content-Type",
        "value": "application/xml; charset=utf-8"
    },
    {
        "name": "DAV",
        "value": "1, 3, extended-mkcol"
    },
    {
        "name": "Cache-Control",
        "value": "no-store, no-cache, must-revalidate"
    },
    {
        "name": "Content-Security-Policy",
        "value": "default-src 'none';"
    },
    {
        "name": "Connection",
        "value": "keep-alive"
    },
    {
        "name": "Expires",
        "value": "Thu, 19 Nov 1981 08:52:00 GMT"
    }
    ],
    "cookies": [],
    "content": {
    "size": 7235,
    "mimeType": "application/xml",
    "compression": -13
    },
    "redirectURL": "",
    "headersSize": 398,
    "bodySize": 7248,
    "_transferSize": 7646
},
"cache": {},
"timings": {
    "blocked": 0.952999980654568,
    "dns": -1,
    "connect": -1,
    "send": 0.11399999493733193,
    "wait": 66.7940000130329,
    "receive": 1.0809999948833422,
    "ssl": -1
},
"serverIPAddress": "snip",
"connection": "231275",
"pageref": "page_4"
}
```

So it seems that if **I'm logged in to the web interface**, I can only make requests for that user. If I'm not logged in to the web interface, only the first user I make a request with will be able to see their contents. Other requests in the same browser window will be tied to their account (cookie?).

![image](https://cloud.githubusercontent.com/assets/3869469/22667133/236af470-ecc4-11e6-9583-3db6ea35f014.png)

Here you can see that the oc session is sticking and preventing other requests from acting on their own. I'd been advised by some folk on the nextCloud channel to try `OCS-API: true` in the headers but this had no affect.

I'm building a browser/node integration that works with WebDAV/ownCloud, which functions fine in NodeJS (no session/cookies), but doesn't work in the browser because of mentioned issues.

**Comment by DeepDiver1975** [comment]
> Here you can see that the oc session is sticking and preventing other requests from acting on their own.

Yes - the session has more weight then the basic auth header.
With ownCloud 10 we will add oauth which will - as a side effect - allow us to drop sessions.
As soon as this is done your scenario will be possible.

Maybe you find a way to tell the XHR request to not submit the session cookie?

**Comment by perry-mitchell** [comment]
Thanks @DeepDiver1975. Not sure how easy it is (if at all possible) to drop cookies in XHRs.. 

OAuth sounds good.. but I guess that means that webdav + basic authorisation won't work in OC 10?

**Comment by PVince81** [comment]
I thought this could work by always passing a "Authorization" header matching user1 or user2 when making the request.

**Comment by perry-mitchell** [comment]
> I thought this could work by always passing a "Authorization" header matching user1 or user2 when making the request.

I did too.. at least that's what most WebDAV docs state. I don't know enough about OC's implementation or WebDAV enabled systems in general, but wouldn't it make sense that the Authorization header hold higher priority? It seems as though it should be checked first and then fall back to the session if it's omitted.

It basically means that if I sign in to OC, I can't make **any request** to any other account apart from the one I'm logged in to. This poses several problems:

1. It's a security risk. I could make a request to my WebDAV without correct auth and I'd still be able to get and modify the contents of another account.
2. No support for multiple accounts in the same browser session
3. No way to switch accounts

**Comment by perry-mitchell** [comment]
Seems I was able to get around the issue by using the native `fetch` API in Chrome.. XHRs wouldn't play ball. Obviously this is still an issue on older browsers where fetch isn't available, but perhaps it's not really worth the effort to continue investigating that route.

**Comment by PVince81** [comment]
Ref https://github.com/owncloud/core/issues/29779 which would remove session handling for Webdav.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
