### ISSUE TITLE
Trying to download ownCloud Config Report, an internal error is shown

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27145]
### Steps to reproduce
1. As admin user go to admin page
2. Browse to Additional section
3. Try to download the ownCloud Config Report

### Expected behaviour

The ownCloud Config Report is downloaded.

### Actual behaviour

An internal Server Error is shown.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.0"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"\/8XWnxftzEqpltibIEjv","remoteAddr":"82.159.139.58","app":"index","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method OC\\\\Server::getOcsClient()\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\ConfigReport\\\\AppInfo\\\\Application->OCA\\\\ConfigReport\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(111): Pimple\\\\Container->offsetGet('ReportDataColle...')\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/configreport\\\/lib\\\/AppInfo\\\/Application.php(53): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('ReportDataColle...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\ConfigReport\\\\AppInfo\\\\Application->OCA\\\\ConfigReport\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(111): Pimple\\\\Container->offsetGet('ReportControlle...')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(82): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('ReportControlle...')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ReportControlle...', 'getReport', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/base.php(894): OC\\\\Route\\\\Router->match('\\\/apps\\\/configrep...')\\n#10 \\\/opt\\\/owncloud\\\/index.php(46): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/configreport\\\/lib\\\/AppInfo\\\/Application.php\",\"Line\":42}","level":3,"time":"2017-02-13T07:56:04+00:00","method":"GET","url":"\/index.php\/apps\/configreport\/report","user":"admin"}
```

### Client configuration

**browser**

 Mozilla

![screen shot 2017-02-13 at 09 00 07](https://cloud.githubusercontent.com/assets/10596560/22875238/e030ae3c-f1ca-11e6-9df1-d642e8e46b9e.png)

![screen shot 2017-02-13 at 09 00 15](https://cloud.githubusercontent.com/assets/10596560/22875245/e9904a3c-f1ca-11e6-9dc4-5634fdedead7.png)

@tomneedham @DeepDiver1975

**Comment by PVince81** [comment]
@davitol for your next report about config report, submit here: https://github.com/owncloud/configreport

**Comment by PVince81** [comment]
@phisch please have a look, looks fishy

**Comment by tomneedham** [comment]
See proposed fix here https://github.com/owncloud/configreport/pull/10
