### ISSUE TITLE
[9.1.3] 503 Error: Call to a member function getFileInfo() on null

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#27179]
I'm not sure if this is a big problem, but in one month I have 18132 times this message:
```
{"reqId":"4CWJn8CGI7ZwqcXGmkLD","remoteAddr":"93.202.79.83","app":"webdav","message":"Exception: {"Message":"HTTP/1.1 503 Error: Call to a member function getFileInfo() on null","Exception":"Sabre\DAV\Exception\ServiceUnavailable","Code":0,"Trace":"
#0 [internal function]: {closure}(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#1 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)
#2 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)
#3 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#4 /var/www/owncloud/remote.php(69): Sabre\DAV\Server->exec()
#5 /var/www/owncloud/remote.php(169): handleException(Object(Error))
#6 {main}","File":"/var/www/owncloud/remote.php","Line":67,"User":false}","level":4,"time":"2017-01-31T14:44:11+01:00","method":"PROPFIND","url":"/remote.php/webdav/","user":"--"}
```
Owncloud 9.1.3 
MariaDB 10.0.29
PHP 7.0.13-0

Config report:
https://cloud.damken.com/index.php/s/SnVmBdScYn4oZAo
Password: config

**Comment by PVince81** [comment]
A PROPFIND with no user ? Strange...

**Comment by cdamken** [comment]
I think is my google drive sync

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
