### ISSUE TITLE
Backgroundjob error: InvalidFieldNameException, table: oc_jobs, column: execution_duration missing

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27232]
### Steps to reproduce
1. Setup core via git clone and finalize setup
2. Enable cron

### Expected behaviour
No errors should appear for background jobs

### Actual behaviour
Errors are logged when the backgroudjob runs

### Note
```
sudo -uwww-data ./occ upgrade
ownCloud is already latest version
```

### Server configuration
**Operating system**: Ubunu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** (see ownCloud admin page) 10.0.0.0

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** git

**Signing status (ownCloud 9.0 and above):**

```
Integrity checker has been disabled. Integrity cannot be verified.
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.2.8
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: true
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - testing
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc4azk63m7k4",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/core\/data",
        "overwrite.cli.url": "http:\/\/xxxx",
        "dbtype": "mysql",
        "version": "10.0.0.0",
        "dbname": "xxxx",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "filesystem_check_changes": 1,
        "loglevel": 1,
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ... no

### Client configuration
**Browser:** Opera

**Operating system:** Ubuntu 16.04

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Baj2gKVWY7bl3rH9ExC5","remoteAddr":"","app":"core","message":"Error while running background job (class: OC\\Authentication\\Token\\DefaultTokenCleanupJob, arguments: ): {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_jobs` SET `execution_duration` = ? WHERE `id` = ?' with params [0, \\\"11\\\"]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'execution_duration' in 'field list'\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\
n#1 \\\/var\\\/www\\\/owncloud\\\/core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_jobs...', Array)\\
n#2 \\\/var\\\/www\\\/owncloud\\\/core\\\/lib\\\/private\\\/DB\\\/Connection.php(214): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `oc_jobs...', Array, Array)\\
n#3 \\\/var\\\/www\\\/owncloud\\\/core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `oc_jobs...', Array, Array)\\
n#4 \\\/var\\\/www\\\/owncloud\\\/core\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\
n#5 \\\/var\\\/www\\\/owncloud\\\/core\\\/lib\\\/private\\\/BackgroundJob\\\/JobList.php(320): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\
n#6 \\\/var\\\/www\\\/owncloud\\\/core\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(66): OC\\\\BackgroundJob\\\\JobList->setExecutionTime(Object(OC\\\\Authentication\\\\Token\\\\DefaultTokenCleanupJob), 0)\\
n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/cron.php(121): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\
n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71}","level":3,"time":"2017-02-23T16:30:15+01:00","method":"--","url":"--","user":"--"}
```

**Comment by PVince81** [comment]
@mmattel works for me when setup from scratch.
Strangely also works when upgrading from the old commit. But maybe it's because it doesn't try to write a value there...

Are you sure you saw this on a brand new checkout ? Maybe you had the old commit and pulled ?

@noveens seems we forgot to increase the version to trigger a DB update. Will do in a minute.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/27233
