### ISSUE TITLE
Download multiple files

### ISSUE THREAD

**Issue by Chumachos** [owncloud/core#27356]
### Steps to reproduce
1. Select multiple files
2. Download zip file
3. Open zip with all the files

### Expected behaviour
Many pictures into a compressed file

### Actual behaviour
I downloaded 40 pictures, then I opened the compressed file without problems. After this, I downloaded 50 pictures and I have an error opening the compressed file. I try to download 40 pictures again and the result is error.

The zip is corrupted.

### Server configuration
**Operating system**: Debian 8 Jessie virtualized, 4 cpu

**Database:** mysql

**PHP version:** 5.6.30-0+deb8u1 

**ownCloud version:** 9.1.4.2

**Updated from an older ownCloud or fresh install:** 9.1.3.1

**Where did you install ownCloud from:** https://download.owncloud.org/community/owncloud-9.1.4.tar.bz2

**Signing status (ownCloud 9.0 and above):**

```
Integrity checker has been disabled. Integrity cannot be verified.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.9.0.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocqduqn2m0sk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/***REMOVED SENSITIVE VALUE***\/data",
        "overwrite.cli.url": "http:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Madrid",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "logfile": "\/var\/log\/owncloud.log",
        "mail_smtpmode": "smtp",
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": false,
        "mail_smtpsecure": "ssl",
        "mail_from_address": "webmaster",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** Yes, default encryption module

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 7 Professional

#### Web server error log

```
{"reqId":"oouhz\/g6nQS\/PclTjz3X","remoteAddr":"10.10.10.100","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Missing Signature\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php(527): OCA\\\\Encryption\\\\Crypto\\\\Crypt->hasSignature('xQw97HxQSvYJbcM...', 'AES-256-CTR')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php(460): OCA\\\\Encryption\\\\Crypto\\\\Crypt->splitMetaData('xQw97HxQSvYJbcM...', 'AES-256-CTR')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php(363): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('xQw97HxQSvYJbcM...', '\\\\f\\\\xFC\\\\xBD\\\\xB6\\\\xB4\\\\xAF\\\\x12>'\\\\x16:\\\\x80\\\\xC1;\\\\xC6...', 'AES-256-CTR', 1, 1080)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(459): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(290): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#5 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(83): fread(Resource id #653, 8192)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(91): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#8 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/mcnetic\\\/zipstreamer\\\/src\\\/ZipStreamer.php(368): fread(Resource id #656, 1048560)\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/mcnetic\\\/zipstreamer\\\/src\\\/ZipStreamer.php(222): ZipStreamer\\\\ZipStreamer->streamFileData(Resource id #656, 0, 1)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Streamer.php(97): ZipStreamer\\\\ZipStreamer->addFileFromStream(Resource id #656, 'Fotos HJT\\\/37.Cu...')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Streamer.php(79): OC\\\\Streamer->addFileFromStream(Resource id #656, 'Fotos HJT\\\/37.Cu...', 7103238)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/files.php(165): OC\\\\Streamer->addDirRecursive('\\\/\\\/Fotos HJT')\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Controllers\\\/ShareController.php(508): OC_Files::get('\\\/', 'Fotos HJT', Array)\\n#15 [internal function]: OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController->downloadShare('deXN71cNkO2eman', NULL, '\\\/', 'ouxqbsamwelkyaf...')\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'downloadShare')\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'downloadShare')\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/App.php(135): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#20 \\\/var\\\/www\\\/owncloud\\\/core\\\/routes.php(140): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#21 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#22 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(Closure), Array)\\n#23 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/s\\\/deXN71cNkO2e...')\\n#24 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#25 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php\",\"Line\":562}","level":3,"time":"2017-03-10T11:43:03+01:00","method":"GET","url":"\/index.php\/s\/deXN71cNkO2eman\/download?path=%2F&downloadStartSecret=ouxqbsamwelkyafkmoosz6w29","user":"--"}
```

**Comment by PVince81** [comment]
Maybe one of the files that is being packaged into the zip has encryption problems, so the zip creation aborts at this error which results in a corrupted zip.

Try downloading the files individually and find the one that is broken.

**Comment by Chumachos** [comment]
I downloaded individually the files and there aren't any problem. In small groups I can download without problem too.
I won't do that if one of that files is broken.

**Comment by PVince81** [comment]
Strange, because the log error you posted is related to an encryption issue. Is that entry from the time of the zip download ?

**Comment by Chumachos** [comment]
Is the unic log generated after zip download

**Comment by hodyroff** [comment]
same thing?
https://github.com/owncloud/core/issues/4715

**Comment by Chumachos** [comment]
> PVince81 commented on 19 Aug 2014
> It is partially fixed.
> If you select all files it will work fine, but if you individually select a lot of files (without having them all selected) then there is still a risk of the URL becoming too long.

> I'd say let's keep it, maybe there's a way to do this with a POST call.

In my case, if I select all files, it doesn't work. The URI generated isn't long:
https://ipserver/index.php/s/deXN71cNkO2eman

**Comment by PVince81** [comment]
Ok now I see the log: "Missing Signature". So it seems one of the files had trouble decrypting and this is the reason for the corrupted zip.

You might want to try with a more recent OC version like OC 9.1.6 where such errors were fixed for public links. Please reopen if the problem persists.
