### ISSUE TITLE
When using the user email to log in, warnings appear on the server log even if the authentication was successful

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#27390]
### Steps to reproduce
1. Set an email on the user settings view (i.e. `/settings/personal#email`)
2. Use that email to log in in from any of the clients or even from the web UI
3. Check the admin logs (`/settings/admin#log-section`)

### Actual behavior
There's a `Warning` on core and a exception on the logs (see below)

### Server configuration
**Operating system**: Ubuntu
**Web server:** Apache 2
**Database:** MySQL
**PHP version:** 5.5.9
**ownCloud version:** 9.1.4

#### Web server error log
```
Info	 admin_audit	User admin logged into ownCloud from IP address: XXX.XXX.XXX.XXX [CLIENT_IP: XXX.XXX.XXX.XXX] [USER_AGENT: Mozilla/5.0 (Macintosh) mirall/2.3.0 (build 4097)]	        2017-03-15T11:33:07+00:00
Info	 admin_audit	User admin attempted to log into ownCloud from IP address: XXX.XXX.XXX.XXX [CLIENT_IP: XXX.XXX.XXX.XXX] [USER_AGENT: Mozilla/5.0 (Macintosh) mirall/2.3.0 (build 4097)]	2017-03-15T11:33:07+00:00
Warning	 core	        Login failed: 'USER@DOMAIN.TLD' (Remote IP: 'XXX.XXX.XXX.XXX')	2017-03-15T11:33:07+00:00
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"B9dBhQlEgvUcc59A8vlo","remoteAddr":"XXX.XXX.XXX.XXX","app":"webdav","message":"Exception: {\"Message\":\"HTTP/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\DAV\Exception\NotAuthenticated\",\"Code\":0,\"Trace\":\"
#0 [internal function]: Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#1 /opt/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#2 /opt/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)
#3 /opt/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#4 /opt/owncloud/apps/dav/appinfo/v1/webdav.php(57): Sabre\DAV\Server->exec()
#5 /opt/owncloud/remote.php(164): require_once('/opt/owncloud/a...')
#6 {main}\",\"File\":\"/opt/owncloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-03-15T11:33:07+00:00","method":"GET","url":"/remote.php/webdav/","user":"--"}

{"reqId":"ENfzXJhFv6gGRbqbGSV2","remoteAddr":"XXX.XXX.XXX.XXX","app":"admin_audit","message":"User USER@DOMAIN.TLD attempted to log into ownCloud from IP address: XXX.XXX.XXX.XXX [CLIENT_IP: XXX.XXX.XXX.XXX] [USER_AGENT: Mozilla\/5.0 (Macintosh) mirall\/2.3.0 (build 4097)]","level":1,"time":"2017-03-15T11:33:07+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
```

cc/ @michaelstingl who saw this today.

**Comment by PVince81** [comment]
Authentication code changed a bit. Please try again with 10.0.4 and reopen if the problem persists.
