### ISSUE TITLE
Contacts empty after updating to 9.0.8

### ISSUE THREAD

**Issue by smartissimo** [owncloud/core#27429]
### Steps to reproduce
1. open "Contacts" App

### Expected behaviour
I expect to see the contacts of my two address books.

### Actual behaviour
The page is displaying the "loading" icon in the middle and "no contacts found" on the right. When I click on the "settings" icon I am able to export only one of my address books, while the other (https://cloud.mydomain.com/remote.php/dav/addressbooks/users/myusername/contacts2/?export) gives back a "500 Internal Server Error: File Not Found"

Also, when inspecting the page requests via Firebug, this is what I get:
> REPORT
> https://cloud.mydomain.com/remote.php/dav/addressbooks/users/myusername/contacts2/
> 500 Internal Server Error

When adding a new contact via the Web UI, this is what I get: 
> Could not create contact.
_(translated, may be slightly different)_

Deleting the app and re-installing it did not change anything.

### Server configuration
**Operating system**:
Ubuntu 12.04.5 LTS

**Database:**
mysql

**PHP version:**
5.6.6

**ownCloud version:** (see ownCloud admin page)
9.0.8

**Updated from an older ownCloud or fresh install:**
update from 8.2.9

**Where did you install ownCloud from:**
Web-Update

```
No errors have been found.
```

**List of activated apps:**
gallery
contacts
calendar

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'XXXXXXX',
  'passwordsalt' => 'XXXXXXX',
  'trusted_domains' => 
  array (
    0 => 'cloud.mydomain.com',
  ),
  'datadirectory' => '/var/www/vhosts/mydomain.com/httpdocs/owncloud/data',
  'version' => '9.0.8.2',
  'dbtype' => 'mysql',
  'dbhost' => 'localhost',
  'dbname' => 'owncloud',
  'dbuser' => 'XXXXXXX',
  'dbpassword' => 'XXXXXXX',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'forcessl' => true,
  'defaultapp' => 'calendar',
  'lost_password_link' => 'https://cloud.mydomain.com/contact/',
  'mail_domain' => 'mydomain.com',
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'php',
  'maintenance' => false,
  'loglevel' => 2,
  'secret' => 'XXXXXXX',
  'debug' => true,
  'appstore.experimental.enabled' => false,
);
```

#### ownCloud log (data/owncloud.log)
```
Error 	PHP 	is_readable(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (/var/www/vhosts/mydomain.com/:/tmp/) at /var/www/vhosts/mydomain.com/httpdocs/owncloud/3rdparty/paragonie/random_compat/lib/random.php#66 

Error 	PHP 	is_readable(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (/var/www/vhosts/mydomain.com/:/tmp/) at /var/www/vhosts/mydomain.com/httpdocs/owncloud/3rdparty/paragonie/random_compat/lib/random.php#66 

Error 	PHP 	is_readable(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (/var/www/vhosts/mydomain.com/:/tmp/) at /var/www/vhosts/mydomain.com/httpdocs/owncloud/3rdparty/paragonie/random_compat/lib/random.php#66 

[...]

Fatal	webdav	Exception: {"Message":"Invalid Mimedir file. Line starting at 4 did not follow iCalendar\/vCard conventions","Exception":"Sabre\\VObject\\ParseException","Code":0,"Trace":"#0 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(189): Sabre\\VObject\\Parser\\MimeDir->readProperty(';=\"<sn>id:78685...')\n#1 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(137): Sabre\\VObject\\Parser\\MimeDir->parseLine(';=\"<sn>id:78685...')\n#2 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\\VObject\\Parser\\MimeDir->parseDocument()\n#3 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\\VObject\\Parser\\MimeDir->parse('BEGIN:VCARD\\r\\nVE...', 0)\n#4 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(477): Sabre\\VObject\\Reader::read('BEGIN:VCARD\\r\\nVE...')\n#5 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(422): Sabre\\CardDAV\\Plugin->validateFilters('BEGIN:VCARD\\r\\nVE...', Array, 'anyof')\n#6 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(202): Sabre\\CardDAV\\Plugin->addressbookQueryReport(Object(Sabre\\CardDAV\\Xml\\Request\\AddressBookQueryReport))\n#7 [internal function]: Sabre\\CardDAV\\Plugin->report('{urn:ietf:param...', Object(Sabre\\CardDAV\\Xml\\Request\\AddressBookQueryReport), 'addressbooks\/us...')\n#8 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#9 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(716): Sabre\\Event\\EventEmitter->emit('report', Array)\n#10 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#11 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#12 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#13 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#14 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/apps\/dav\/lib\/server.php(152): Sabre\\DAV\\Server->exec()\n#15 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#16 \/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/remote.php(138): require_once('\/var\/www\/vhosts...')\n#17 {main}","File":"\/var\/www\/vhosts\/mydomain.com\/httpdocs\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":385,"User":"myusername"}
```

**Comment by kdslkdsaldsal** [comment]
Most likely caused by previously imported and already broken contacts / vcards. For calendars there is a known SQL statement like seen on e.g.:

https://central.owncloud.org/t/calendar-could-not-be-synced-or-exported/850

Something similar might be possible here.

**Comment by kdslkdsaldsal** [comment]
> Most likely caused by previously imported and already broken contacts / vcards.

Yes, this seems to be the case here:

> Please connect to the database and search through the table oc_cards - one of the cards is invalid and has to either be fixed or deleted.

-> https://github.com/owncloud/core/issues/24300

**Comment by smartissimo** [comment]
Hi,

In oc_cards as far as I can see everything looks good, but an invalid VCARD might actually be the problem. I experienced strange sync problems in past though different devices (where a missing "END" would be an explanation for).

Unfortunately the query ...
`SELECT * FROM `oc_contacts_cards` WHERE `carddata` NOT LIKE '%END:VCARD%' `
... did not return anything.

Any idea how I can find the invalid card?

**Comment by exi** [comment]
I have the same issue. Is there any way to validate cards en masse? I don't want to manually comb through a lot of cards.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
