### ISSUE TITLE
Cannot migrate from 9.1.4 to daily master, oc_accounts table does not exist

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27476]
### Steps

1. Setup ownCloud 9.1.4
1. Stay logged in
1. Replace the source code with the one from today's daily master (2017-03-24) and keep "data" and "config" folders
1. Open the web UI to view the update page <= error case 1
1. Clear cookies / cache to kill session
1. Open web UI again

### Expected result
Web UI can be opened and update can be run.

### Actual result
Error case 1 with existing session, white page with this exception displayed:
```
Exception occurred while logging exception: An exception occurred while executing 'SELECT * FROM `oc_accounts` WHERE `lower_user_id` = :dcValue1' with params ["admin"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloudtest.oc_accounts' doesn't exist
#0 /srv/www/htdocs/owncloudtest/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /srv/www/htdocs/owncloudtest/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(177): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM `...', Array)
#2 /srv/www/htdocs/owncloudtest/lib/public/AppFramework/Db/Mapper.php(252): Doctrine\DBAL\Statement->execute()
#3 /srv/www/htdocs/owncloudtest/lib/public/AppFramework/Db/Mapper.php(285): OCP\AppFramework\Db\Mapper->execute('SELECT * FROM `...', Array, NULL, NULL)
#4 /srv/www/htdocs/owncloudtest/lib/public/AppFramework/Db/Mapper.php(378): OCP\AppFramework\Db\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)
#5 /srv/www/htdocs/owncloudtest/lib/private/User/AccountMapper.php(59): OCP\AppFramework\Db\Mapper->findEntity('SELECT * FROM `...', Array)
#6 /srv/www/htdocs/owncloudtest/lib/private/User/Manager.php(144): OC\User\AccountMapper->getByUid('admin')
#7 /srv/www/htdocs/owncloudtest/lib/private/User/Session.php(201): OC\User\Manager->get('admin')
#8 /srv/www/htdocs/owncloudtest/lib/private/L10N/Factory.php(132): OC\User\Session->getUser()
#9 /srv/www/htdocs/owncloudtest/lib/private/L10N/Factory.php(100): OC\L10N\Factory->findLanguage('lib')
#10 /srv/www/htdocs/owncloudtest/lib/private/Server.php(1045): OC\L10N\Factory->get('lib', NULL)
#11 /srv/www/htdocs/owncloudtest/lib/base.php(228): OC\Server->getL10N('lib')
#12 /srv/www/htdocs/owncloudtest/lib/base.php(586): OC::checkConfig()
#13 /srv/www/htdocs/owncloudtest/lib/base.php(984): OC::init()
#14 /srv/www/htdocs/owncloudtest/index.php(47): require_once('/srv/www/htdocs...')
#15 {main}
```

Error case 2 without session: blue error page with exception in log:
```
{"reqId":"GM39rDwkyQluWsjqFF\/J","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `backend`, count(*) as `count` FROM `oc_accounts` GROUP BY `backend`':\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloudtest.oc_accounts' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `backend...', Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/DB\\\/Connection.php(193): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `backend...', Array, Array, NULL)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `backend...', Array, Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/User\\\/AccountMapper.php(89): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/User\\\/Manager.php(311): OC\\\\User\\\\AccountMapper->getUserCountPerBackend(false)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/base.php(360): OC\\\\User\\\\Manager->countUsers()\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/base.php(338): OC::printUpgradePage()\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/base.php(852): OC::checkUpgrade(true)\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/index.php(49): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","level":3,"time":"2017-03-24T08:35:55+00:00","method":"GET","url":"\/owncloudtest\/","user":"--"}
```

### Versions
ownCloud daily master 2017-03-24

These could be two different bugs:

1) When a session exists, it seems to expect the oc_account table to exist even though we haven't migrated yet

2) When displaying update page, it's asking "countUsers" to the user manager, possibly to display statistics. But that method requires the account table to exist.

**Comment by DeepDiver1975** [comment]
:hankey: 

````
#0 /home/deepdiver/Development/ownCloud/master-autotest/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /home/deepdiver/Development/ownCloud/master-autotest/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT "backend...', Array)
#2 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/DB/Connection.php(193): Doctrine\DBAL\Connection->executeQuery('SELECT "backend...', Array, Array, NULL)
#3 /home/deepdiver/Development/ownCloud/master-autotest/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): OC\DB\Connection->executeQuery('SELECT "backend...', Array, Array)
#4 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/DB/QueryBuilder/QueryBuilder.php(141): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/User/AccountMapper.php(89): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /home/deepdiver/Development/ownCloud/master-autotest/lib/private/User/Manager.php(311): OC\User\AccountMapper->getUserCountPerBackend(false)
#7 /home/deepdiver/Development/ownCloud/master-autotest/lib/base.php(360): OC\User\Manager->countUsers()
#8 /home/deepdiver/Development/ownCloud/master-autotest/lib/base.php(338): OC::printUpgradePage()
#9 /home/deepdiver/Development/ownCloud/master-autotest/lib/base.php(852): OC::checkUpgrade(true)
#10 /home/deepdiver/Development/ownCloud/master-autotest/index.php(49): OC::handleRequest()
#11 {main}

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/issues/27482
