### ISSUE TITLE
Cannot move received internal share into folder shared as link

### ISSUE THREAD

**Issue by butonic** [owncloud/core#27500]
### Steps to reproduce
1. As 'Alice' share folder '/foo' with 'Bob' with all permissions
2. As 'Bob' share folder '/bar' via link
3. As 'Bob' move received share folder '/foo' into '/bar'

### Expected behaviour
The move should succeed, at least the log message `It is not allowed to move one mount point into a shared folder` should be visible to the end user.

### Actual behaviour
Yellow notification with `Die Datei konnte nicht verschoben werden "foo"`. Not very hepful looks like oc is broken.

MOVE response is
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message/>
</d:error>
```

log
```json
{"reqId":"Czt5AbKEbmsvHki70kqn","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 403 Forbidden\",\"Exception\":\"Sabre\\\\DAV\\\\Excepti
on\\\\Forbidden\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jfd\\\/www\\\/stable9.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(640): OCA\\\\DAV\\\\Connector\\\\Sab
re\\\\ObjectTree->move('foo', 'bar\\\/foo')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Res
ponse))\\n#2 \\\/home\\\/jfd\\\/www\\\/stable9.1\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/home\\\/jfd\\\/
www\\\/stable9.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#4 \\\/home\\\/jfd\\\/www\\\/stable9
.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/home\\\/jfd\\\/www\\\/stable9.1\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/home\\\/jfd\\\/www\\\/stable9.1\\\/remote.php(164): require_once('\\\/home\\\/jfd\\\/www\\\/s...')\\n#7 {main}\",\"File\":\"\\\/home\\\/jfd\\\/www\\\/stable9.1\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":245,\"User\":\"t1\"}","level":0,"time":"2017-03-26T20:21:25+00:00","method":"MOVE","url":"\/oc\/stable9.1\/remote.php\/webdav\/foo","user":"t1"}
{"reqId":"3Zz04gSDHk7NF2j381by","remoteAddr":"127.0.0.1","app":"files","message":"It is not allowed to move one mount point into a shared folder","level":0,"time":"2017-03-26T20:22:23+00:00","method":"MOVE","url":"\/oc\/stable9.1\/remote.php\/webdav\/sub%20foo","user":"t1"}
```

Why is this forbidden if 'Bob' his permission to reshare?

### Server configuration
**ownCloud version:** 9.1

**Comment by PVince81** [comment]
It's a limitation of the mount point system, originally designed to avoid recursions/chains when resharing received mount points.

Slightly related: https://github.com/owncloud/core/pull/27539

**Comment by PVince81** [comment]
also I think even if we remove the restriction, it would not work without that PR https://github.com/owncloud/core/pull/27539

**Comment by PVince81** [comment]
Regarding the error message:

- [ ] make sure the message appears inside the exception
- [ ] properly parse exception messages from Sabre: https://github.com/owncloud/core/issues/24304

**Comment by butonic** [comment]
related: https://github.com/owncloud/core/issues/23111

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by jnweiger** [comment]
I'd suggest to make this a distinct error. Currently a client receives MOVE 403 Forbidden.
Not exactly sure what the payload says.
From a client perspective, I'd need something to give the end user a hint about the cause of this specific problem.

The definitiion of 403 is

          The request was valid, but the server is refusing action. The
          user might not have the necessary permissions for a resource, or
          may need an account of some sort. This code is also typically
          used if the request provided authentication via the
          WWW-Authenticate header field, but the server did not accept
          that authentication.

In this case it is not a matter of permissions of accounts.
One could argue that it should not be 403, or that we should have a SHARE_WITHIN_A_SHARE_ERROR indicator in the payload.

There are e.g. these alternatives:
409 Conflict
508 Loop detected
