### ISSUE TITLE
On Installation: Admin user is created even when installation failed; Can't log in and forced to create a new admin user

### ISSUE THREAD

**Issue by Cheet4h** [owncloud/core#27537]
### Steps to reproduce
1. Install ownCloud Server package
2. Enter details in the Installation wizard
3. Let the installation fail after login to the database and admin creation is successfull
( I describe the issue during which I experienced this [here](https://central.owncloud.org/t/owncloud-9-1-installation-internal-server-error-missing-table/6723)
4. Enter details in the installation wizard again with the same admin user name
5. Error "This username already exists" will be displayed

### Expected behaviour
Current admin user should be overwritten

### Actual behaviour
Will be aborted, forced to create multiple admin accounts during installation.

### Server configuration
**Operating system**: Debian 8 x64

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6.30

**ownCloud version:** 9.1

**Updated from an older ownCloud or fresh install:** Fresh Install

**Where did you install ownCloud from:** repository linked [here](http://download.owncloud.org/download/repositories/9.1/owncloud/)

**Signing status (ownCloud 9.0 and above):** not installed yet

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'ocih01ne5p5d',
  'passwordsalt' => '~~~',
  'secret' => '~~~',
  'trusted_domains' =>
  array (
    0 => '<mydomain>',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => '<mydomain>',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'ocdb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin031',
  'dbpassword' => '~~~',
);

```

**Are you using external storage, if yes which one:** -

**Are you using encryption:** not yet

**Are you using an external user-backend, if yes which one:** -

### Client configuration
**Browser:** Firefox 52.0.1

**Operating system:** Windows 10 1607

#### Web server error log
```
[Wed Mar 29 23:13:23.656505 2017] [mpm_event:notice] [pid 22944:tid 140528188147584] AH00489: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Wed Mar 29 23:13:23.656620 2017] [core:notice] [pid 22944:tid 140528188147584] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 29 23:13:28.880197 2017] [mpm_event:notice] [pid 22944:tid 140528188147584] AH00491: caught SIGTERM, shutting down
[Wed Mar 29 23:13:29.972440 2017] [mpm_prefork:notice] [pid 24037] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Wed Mar 29 23:13:29.972527 2017] [core:notice] [pid 24037] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 29 23:13:31.253293 2017] [mpm_prefork:notice] [pid 24037] AH00169: caught SIGTERM, shutting down
[Wed Mar 29 23:13:32.393996 2017] [mpm_prefork:notice] [pid 24137] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Wed Mar 29 23:13:32.394052 2017] [core:notice] [pid 24137] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 29 23:13:45.496756 2017] [mpm_prefork:notice] [pid 24137] AH00171: Graceful restart requested, doing restart
[Wed Mar 29 23:13:45.547235 2017] [mpm_prefork:notice] [pid 24137] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Wed Mar 29 23:13:45.547260 2017] [core:notice] [pid 24137] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 29 23:13:50.906584 2017] [mpm_prefork:notice] [pid 24137] AH00169: caught SIGTERM, shutting down
[Wed Mar 29 23:13:52.004504 2017] [mpm_prefork:notice] [pid 26579] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Wed Mar 29 23:13:52.004560 2017] [core:notice] [pid 26579] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 29 23:13:58.263117 2017] [mpm_prefork:notice] [pid 26579] AH00171: Graceful restart requested, doing restart
[Wed Mar 29 23:13:58.315026 2017] [mpm_prefork:notice] [pid 26579] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Wed Mar 29 23:13:58.315045 2017] [core:notice] [pid 26579] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 29 23:23:18.767063 2017] [authz_core:error] [pid 26875] [client 85.214.125.121:47104] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Wed Mar 29 23:23:55.125260 2017] [authz_core:error] [pid 26875] [client 85.214.125.121:49010] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Wed Mar 29 23:24:57.740554 2017] [authz_core:error] [pid 26904] [client 85.214.125.121:52678] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Wed Mar 29 23:29:59.013607 2017] [authz_core:error] [pid 26655] [client 85.214.125.121:43902] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Wed Mar 29 23:45:00.642744 2017] [authz_core:error] [pid 26657] [client 85.214.125.121:51874] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Mar 30 00:00:00.760192 2017] [authz_core:error] [pid 26875] [client 85.214.125.121:52086] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Mar 30 00:01:07.784714 2017] [authz_core:error] [pid 26904] [client 85.214.125.121:56612] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Mar 30 00:01:18.698832 2017] [authz_core:error] [pid 26875] [client 85.214.125.121:57768] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Mar 30 00:01:52.046273 2017] [authz_core:error] [pid 26657] [client 85.214.125.121:60010] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Mar 30 00:02:20.105304 2017] [authz_core:error] [pid 26905] [client 85.214.125.121:35112] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Mar 30 00:06:23.847626 2017] [authz_core:error] [pid 26904] [client 85.214.125.121:52688] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Mar 30 00:15:37.835276 2017] [authz_core:error] [pid 26659] [client 85.214.125.121:59768] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Mar 30 00:15:52.419388 2017] [authz_core:error] [pid 26655] [client 85.214.125.121:60002] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Mar 30 00:18:16.660607 2017] [authz_core:error] [pid 26903] [client 85.214.125.121:35128] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Mar 30 00:18:22.253425 2017] [authz_core:error] [pid 26875] [client 85.214.125.121:35190] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Mar 30 00:18:49.524811 2017] [authz_core:error] [pid 26659] [client 85.214.125.121:35730] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"u+5tD3F1DDTuQpAq2JFW","remoteAddr":"84.172.38.230","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `id`, `uid`, `login_name`, `password`, `name`, `type`, `token`, `last_activity`, `last_check` FROM `oc_authtoken` WHERE `token` = ?' with params [\\\"b6560416a52b90214fd657392de481c2e5b88dc8e27d750c268efa1c6d0af1f0627d45fe131b5b5566b1cf75d7a2aa362ecedccb27b086ede974bdd324f75b1c\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ocdb.oc_authtoken' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(188): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenMapper.php(77): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(147): OC\\\\Authentication\\\\Token\\\\DefaultTokenMapper->getToken(*** sensitive parameters replaced ***)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(616): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->getToken(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(284): OC\\\\User\\\\Session->validateToken(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Setup.php(375): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/SetupController.php(64): OC\\\\Setup->install(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(829): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","level":3,"time":"2017-03-29T21:04:53+00:00","method":"POST","url":"\/owncloud\/index.php","user":"--"}
{"reqId":"AuiPN4i3zM6Cj\/nEy4G1","remoteAddr":"84.172.38.230","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `id`, `uid`, `login_name`, `password`, `name`, `type`, `token`, `last_activity`, `last_check` FROM `oc_authtoken` WHERE `token` = ?' with params [\\\"8c01d3133829400749b6eb400987738a37087a479bd6bb8eb9acb81fe5d2c080c829c54d198590477a165de47373297f8b3a795418101871c63a700aa014a465\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ocdb.oc_authtoken' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(188): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenMapper.php(77): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(147): OC\\\\Authentication\\\\Token\\\\DefaultTokenMapper->getToken(*** sensitive parameters replaced ***)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(616): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->getToken(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(284): OC\\\\User\\\\Session->validateToken(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Setup.php(375): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/SetupController.php(64): OC\\\\Setup->install(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(829): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","level":3,"time":"2017-03-29T21:24:57+00:00","method":"POST","url":"\/owncloud\/index.php","user":"--"}
{"reqId":"EZFZ0XhHh7NzaecKHDyS","remoteAddr":"84.172.38.230","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `id`, `uid`, `login_name`, `password`, `name`, `type`, `token`, `last_activity`, `last_check` FROM `oc_authtoken` WHERE `token` = ?' with params [\\\"b3b06b66e6970efc6532aa1deb164c723b1d8f4e5f414a6ea035397d4fed43232169651f7bcbdcbb80313bc5a3ad9a83dbbe3d6fc602b049ca39b0ed7c8c15fd\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ocdb.oc_authtoken' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(188): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenMapper.php(77): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(147): OC\\\\Authentication\\\\Token\\\\DefaultTokenMapper->getToken(*** sensitive parameters replaced ***)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(616): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->getToken(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(284): OC\\\\User\\\\Session->validateToken(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Setup.php(375): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/SetupController.php(64): OC\\\\Setup->install(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(829): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","level":3,"time":"2017-03-29T22:01:08+00:00","method":"POST","url":"\/owncloud\/index.php","user":"--"}
{"reqId":"CPf5pFnFuX0nQo+nP5r4","remoteAddr":"84.172.38.230","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `id`, `uid`, `login_name`, `password`, `name`, `type`, `token`, `last_activity`, `last_check` FROM `oc_authtoken` WHERE `token` = ?' with params [\\\"b936c312e0bce34909c17bc0498963ed7d2a189a675f2b07a9321e5c71d413d403dfb2e8879170969409bf0adfb1316807d42eb1b43a01d1d1ad26c8e902e11e\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ocdb.oc_authtoken' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(188): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenMapper.php(77): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(147): OC\\\\Authentication\\\\Token\\\\DefaultTokenMapper->getToken(*** sensitive parameters replaced ***)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(616): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->getToken(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(284): OC\\\\User\\\\Session->validateToken(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Setup.php(375): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/SetupController.php(64): OC\\\\Setup->install(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(829): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","level":3,"time":"2017-03-29T22:02:20+00:00","method":"POST","url":"\/owncloud\/index.php","user":"--"}
{"reqId":"p2hzaHMpA2aSNarzMxjz","remoteAddr":"84.172.38.230","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `id`, `uid`, `login_name`, `password`, `name`, `type`, `token`, `last_activity`, `last_check` FROM `oc_authtoken` WHERE `token` = ?' with params [\\\"72cb8a239f51b0e03b6bb78ce3f81a8fe5d6b0f841bae1b4a7b922ccc044f3497f3827a69341e5036b0f56c16ac2d3c6b2710124b4aa6aead8a404d2d2fd1e65\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ocdb.oc_authtoken' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(188): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenMapper.php(77): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(147): OC\\\\Authentication\\\\Token\\\\DefaultTokenMapper->getToken(*** sensitive parameters replaced ***)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(616): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->getToken(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(284): OC\\\\User\\\\Session->validateToken(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Setup.php(375): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/SetupController.php(64): OC\\\\Setup->install(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(829): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","level":3,"time":"2017-03-29T22:18:16+00:00","method":"POST","url":"\/owncloud\/index.php","user":"--"}

```

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
