### ISSUE TITLE
Set same email to two users - internal server error on password reset

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27609]
1. Create two users "user1" and "user2"
1. Login as "user1"
1. Set an email address, receive mail, open link
1. Login as "user2"
1. Set the same email address, receive mail, open link

### Expected result
Password reset form can still be opened ?
Or receive an error earlier ?
Or don't send the email at all ?

### Actual result
Opening the link gives an error page "Internal Server Error"
```
{"reqId":"tcxrz4w39hbAx5FaWPfJ","level":3,"time":"2017-04-10T12:38:39+00:00","remoteAddr":"127.0.0.1","user":"user1","app":"index","method":"GET","url":"\/owncloud\/index.php\/settings\/mailaddress\/change\/DrdcxZUi1eeMwAkkPyswh\/user1","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_accounts` SET `email` = ? WHERE `id` = ?' with params [\\\"vincent@vvortex.ttv\\\", 3]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'vincent@vvortex.ttv' for key 'UNIQ_907AA303E7927C74'\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(178): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_acco...', Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(252): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(188): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('UPDATE `*PREFIX...', Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/User.php(152): OCP\\\\AppFramework\\\\Db\\\\Mapper->update(Object(OC\\\\User\\\\Account))\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/settings\\\/Controller\\\/UsersController.php(797): OC\\\\User\\\\User->setEMailAddress('vincent@vvortex...')\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/settings\\\/Controller\\\/UsersController.php(834): OC\\\\Settings\\\\Controller\\\\UsersController->setEmailAddress('user1', 'vincent@vvortex...')\\n#7 [internal function]: OC\\\\Settings\\\\Controller\\\\UsersController->changeMail('DrdcxZUi1eeMwAk...', 'user1')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'changeMail')\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'changeMail')\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('UsersController', 'changeMail', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(910): OC\\\\Route\\\\Router->match('\\\/settings\\\/maila...')\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66}"}
```

### Versions
ownCloud 10.0 beta2

@DeepDiver1975 @imujjwal96

**Comment by PVince81** [comment]
this also means a potential crash when syncing users from LDAP if two users have the same email address

cc @jvillafanez @davitol to be tested

**Comment by PVince81** [comment]
Uniqueness was removed from DB
