### ISSUE TITLE
Exception when changing email from empty to a confirmed address

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27674]
### Steps

1. Create a user "user1"
1. Login as "user1"
1. Go to personal page
1. Set an email address and click "Set email"
1. Open email
1. Open link
1. If that works so far, go back to personal page and reset the email address to empty and click "Set email"
1. Then set an address again
1. Open email and link

### Expected result
Link opens personal page with a confirmation that the email as changed.

### Actual result
Internal Server Error page.
Refreshing page does set the email correctly but with a failure message.

### Versions
ownCloud 10.0.0 RC1

```
{"reqId":"GtCzhjnfpWoPEdMf6Gug","level":3,"time":"2017-04-19T09:58:32+00:00","remoteAddr":"127.0.0.1","user":"user1","app":"index","method":"GET","url":"\/owncloud\/index.php\/settings\/mailaddress\/change\/ZssAVzwbYHLwQV1X7FwHc\/user1","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Couldn't send email address change notification mail. Please contact your administrator.\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Settings\\\\Controller\\\\UsersController->changeMail('ZssAVzwbYHLwQV1...', 'user1')\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'changeMail')\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'changeMail')\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('UsersController', 'changeMail', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#5 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(910): OC\\\\Route\\\\Router->match('\\\/settings\\\/maila...')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/settings\\\/Controller\\\/UsersController.php\",\"Line\":849}"}
```

@imujjwal96 @SergioBertolinSG FYI

I noticed in the DB that when creating a new user, the email address is first `NULL`.
Then later on when resetting it to empty the column value becomes an empty string.

It is likely that email code is expecting the value to be null but not checking about empty values.

@jvillafanez also discovered a similar issue about null vs empty strings.

**Comment by PVince81** [comment]
fix through https://github.com/owncloud/core/pull/27728
