### ISSUE TITLE
CalDav readv connection reset by peer

### ISSUE THREAD

**Issue by giubil** [owncloud/core#27680]
### Steps to reproduce
1. Access a calendar via CALDav on an external app (thunderbird, caldav for android, etc)

### Expected behaviour
Tell us what should happen

The owncloud installation returns the calendar

### Actual behaviour
Tell us what happens instead

Request fails, and is being logged in nginx error log

```
2017/04/19 15:24:46 [error] 27494#27494: *144013 readv() failed (104: Connection reset by peer) while reading upstream, client: 82.227.51.91, server: cloud.andromede-france.com, request: "PROPFIND /remote.php/dav/calendars/admin/hello-world/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.andromede-france.com"
```

### Server configuration
**Operating system**:
Debian jessie

**Web server:**
nginx

**Database:**
MySQL

**PHP version:**
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
9.0.8
**Updated from an older ownCloud or fresh install:**
Updated from owncloud 8

**Where did you install ownCloud from:**
Installed from tarball

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.4.1
  - comments: 0.2
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: 0.1.6
  - documents: 0.12.1
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - files_videoviewer
  - updater
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "occ9ig2bx4se",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.andromede-france.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.andromede-france.com",
        "dbtype": "mysql",
        "version": "9.0.8.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "no-repy",
        "mail_smtpmode": "php",
        "mail_domain": "gyss.fr",
        "maintenance": false,
        "theme": "",
        "loglevel": 0
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
N/A

**Operating system:**
N/A

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"yjOlKc30tt97smP928OT","remoteAddr":"82.227.51.91","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/server.php(152): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-04-19T13:24:45+00:00","method":"PROPFIND","url":"\/remote.php\/dav\/calendars\/admin\/new-test\/","user":"--"}
{"reqId":"GyHhpjApXlUxzJ1us8bi","remoteAddr":"82.227.51.91","app":"core","message":"Login failed: 'admin' (Remote IP: '82.227.51.91')","level":2,"time":"2017-04-19T13:24:46+00:00","method":"PROPFIND","url":"\/remote.php\/dav\/calendars\/admin\/hello-world\/","user":"--"}
{"reqId":"GyHhpjApXlUxzJ1us8bi","remoteAddr":"82.227.51.91","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 Username or password was incorrect, Username or password was incorrect\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/server.php(152): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-04-19T13:24:46+00:00","method":"PROPFIND","url":"\/remote.php\/dav\/calendars\/admin\/hello-world\/","user":"--"}
```

#### Browser log
```
N/A
```

### Nginx log
```
2017/04/19 15:24:22 [error] 27494#27494: *144013 readv() failed (104: Connection reset by peer) while reading upstream, client: 82.227.51.91, server: cloud.andromede-france.com, request: "PROPFIND /remote.php/dav/calendars/admin/test-calendar/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.andromede-france.com"
2017/04/19 15:24:22 [error] 27494#27494: *144013 readv() failed (104: Connection reset by peer) while reading upstream, client: 82.227.51.91, server: cloud.andromede-france.com, request: "PROPFIND /remote.php/dav/calendars/admin/new-test/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.andromede-france.com"
2017/04/19 15:24:32 [error] 27494#27494: *144013 readv() failed (104: Connection reset by peer) while reading upstream, client: 82.227.51.91, server: cloud.andromede-france.com, request: "PROPFIND /remote.php/dav/calendars/admin/hello-world/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.andromede-france.com"
2017/04/19 15:24:34 [error] 27494#27494: *144013 readv() failed (104: Connection reset by peer) while reading upstream, client: 82.227.51.91, server: cloud.andromede-france.com, request: "PROPFIND /remote.php/dav/calendars/admin/test-calendar/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.andromede-france.com"
2017/04/19 15:24:34 [error] 27494#27494: *144013 readv() failed (104: Connection reset by peer) while reading upstream, client: 82.227.51.91, server: cloud.andromede-france.com, request: "PROPFIND /remote.php/dav/calendars/admin/new-test/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.andromede-france.com"
2017/04/19 15:24:34 [error] 27494#27494: *144013 readv() failed (104: Connection reset by peer) while reading upstream, client: 82.227.51.91, server: cloud.andromede-france.com, request: "PROPFIND /remote.php/dav/calendars/admin/hello-world/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.andromede-france.com"
2017/04/19 15:24:45 [error] 27494#27494: *144013 readv() failed (104: Connection reset by peer) while reading upstream, client: 82.227.51.91, server: cloud.andromede-france.com, request: "PROPFIND /remote.php/dav/calendars/admin/test-calendar/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.andromede-france.com"
2017/04/19 15:24:45 [error] 27494#27494: *144013 readv() failed (104: Connection reset by peer) while reading upstream, client: 82.227.51.91, server: cloud.andromede-france.com, request: "PROPFIND /remote.php/dav/calendars/admin/new-test/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.andromede-france.com"
2017/04/19 15:24:46 [error] 27494#27494: *144013 readv() failed (104: Connection reset by peer) while reading upstream, client: 82.227.51.91, server: cloud.andromede-france.com, request: "PROPFIND /remote.php/dav/calendars/admin/hello-world/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.andromede-france.com"
2017/04/19 15:33:33 [error] 27489#27489: *144345 access forbidden by rule, client: 82.227.51.91, server: cloud.andromede-france.com, request: "GET /data/htaccesstest.txt?t=1492608789185 HTTP/2.0", host: "cloud.andromede-france.com"
```

No errors logged by php-fpm.
Restarting php-fpm service seems to fix the issue for about 5 minutes.

### Thunderbird log
```
Timestamp: 19/04/2017, 15:39:41
Warning: There has been an error reading data for calendar: test.  However, this error is believed to be minor, so the program will attempt to continue. Error code: DAV_NOT_DAV. Description: The resource at https://cloud.andromede-france.com/remote.php/dav/calendars/admin/hello-world/ is either not a DAV collection or not available
Source File: file:///Users/nowahe/Library/Thunderbird/Profiles/v8exvezp.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Line: 962
Timestamp: 19/04/2017, 15:39:41
Warning: There has been an error reading data for calendar: test.  However, this error is believed to be minor, so the program will attempt to continue. Error code: READ_FAILED. Description: 
Source File: file:///Users/nowahe/Library/Thunderbird/Profiles/v8exvezp.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Line: 962
Timestamp: 19/04/2017, 15:39:41
Error: [calCachedCalendar] replay action failed: null, uri=https://cloud.andromede-france.com/remote.php/dav/calendars/admin/hello-world/, result=2147500037, op=[xpconnect wrapped calIOperation]
Source File: file:///Users/nowahe/Library/Thunderbird/Profiles/v8exvezp.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCachedCalendar.js
Line: 327
```

Tested the endpoints with curl and cadaver, didn't have any problems.

**Comment by kdslkdsaldsal** [comment]
@giubil Please note this is a bugtracker of ownCloud. Such issues are mostly caused by environmental issues (broken / misconfigured webserver config, security modules etc.) where you should ask for support at https://central.owncloud.org/.

The forums there also contains a FAQ category containing a thread about WebDAV issues and how to solve these.

**Comment by PVince81** [comment]
please check your env and check the FAQ. Please reopen if everything in your env is correct and you think this is a bug.
