### ISSUE TITLE
Cannot upload a file to an external Storage via Desktop Client

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27686]
### Steps to reproduce

1. Mount an external Storage Mountpoint (e.g WebDAV) 
2. Using ownCloud Desktop Client, sync the server
3. Add a file to the External Storage via Desktop Client

### Expected behaviour

The file should be uploaded to the mountpoint

### Actual behaviour

Cannot upload a file to an external Storage via Desktop Client. 

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.0"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
WebDAV

**Are you using encryption:** 
No

**Logs**

Server Logs

```
{"reqId":"TS8WI46CLfGPQaUHZNE8","level":4,"time":"2017-04-19T14:58:44+00:00","remoteAddr":"82.159.139.58","user":"admin","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/WebDAV\/Screen%20Shot%202017-04-10%20at%2013.48.20.png","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 The computed checksum does not match the one received from the client.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #60)\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('Screen Shot 201...', Resource id #60)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('WebDAV\\\/Screen S...', Resource id #60, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/opt\\\/owncloud\\\/remote.php(165): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#9 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":139,\"User\":\"admin\"}"}
```

Desktop logs

```
04-19 15:31:55:157 0x7fcf8a44d620 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem &, const OCC::PropagatorJob &) "WebDAV/Screen Shot 2017-04-10 at 14.36.58 (2).png" INSTRUCTION_ERROR 6 "The item is not synced because of previous errors: Error downloading http://XXXXXXXXX/remote.php/webdav/WebDAV/Screen Shot 2017-04-10 at 14.36.58 (2).png - server replied: Bad Request (The computed checksum does not match the one received from the client.)"
04-19 15:31:55:158 0x7fcf8a44d620 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:/Users/davidsg/SacarCheckSums"
04-19 15:31:55:159 0x7fcf8a44d620 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:/Users/davidsg/SacarCheckSums/WebDAV"
04-19 15:31:55:160 0x7fcf8a44d620 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/davidsg/SacarCheckSums/WebDAV/Screen Shot 2017-04-10 at 14.36.58 (2).png"
04-19 15:31:55:165 0x7fcf8a44d620 OCC::SyncJournalFileRecord::SyncJournalFileRecord: OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem &, const QString &) "/Users/davidsg/SacarCheckSums/WebDAV" Retrieved inode  8090823 (previous item inode:  0 )
04-19 15:31:55:165 0x7fcf8a44d620 OCC::SyncJournalDb::setFileRecord: "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16);" 3854751747190235015 6 "WebDAV" 8090823 "1492608656" "2" "58f766908fcc5" "00000017ock3crhejtho" "MCK" 0 0 "" "" 0
04-19 15:31:55:166 0x7fcf8a44d620 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem &, const OCC::PropagatorJob &) "WebDAV" INSTRUCTION_NONE 4 ""
04-19 15:31:55:166 0x7fcf8a44d620 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:IGNORE:/Users/davidsg/SacarCheckSums/WebDAV"
04-19 15:31:55:180 0x7fcf8a44d620 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem &, const OCC::PropagatorJob &) "" INSTRUCTION_NONE 4 ""
04-19 15:31:55:181 0x7fcf8a44d620 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:IGNORE:/Users/davidsg/SacarCheckSums"
```

### Client configuration

**oC Desktop Client for OSX**

 version 2.2.4 and 2.3.1

@IljaN

**Comment by PVince81** [comment]
`$computedChecksums` is empty for some reason, debugging...

**Comment by PVince81** [comment]
Ok... it doesn't compute the checksum because the file is not under "data/$user/files". This condition must be fixed to only apply to the home storage.

**Comment by PVince81** [comment]
Fix is here, please verify: https://github.com/owncloud/core/pull/27689
