### ISSUE TITLE
Logs are spotted in owncloud.log when we create a DropBox mountpoint with files

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27688]
### Steps to reproduce

1. Mount a DropBox external Storage Mountpoint 

### Expected behaviour

No logs  should be shown in owncloud.log

### Actual behaviour

Logs are spotted in owncloud.log

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.0"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
DropBox

**Are you using encryption:** 
No

**Logs**

Server Logs

```
{"reqId":"teInWqdKxVxqTgSlg5rx","level":4,"time":"2017-04-19T15:34:03+00:00","remoteAddr":"82.159.139.58","user":"admin","app":"webdav","method":"GET","url":"\/remote.php\/dav\/files\/admin\/Dropbox\/IMG_20161128_093923.jpg","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(226): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#7 \\\/opt\\\/owncloud\\\/remote.php(165): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":324,\"User\":\"admin\"}"}
```

### Client configuration

**Browser**

**Comment by PVince81** [comment]
please retry with new Dropbox app and 10.0.4
