### ISSUE TITLE
Cannot upload files to a mountpoint via webUI using webDAV as external Storage

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27691]
### Steps to reproduce

1. Mount a WebDAV external Storage Mountpoint
2. Upload a file via webUI

### Expected behaviour

The file should be uploaded

### Actual behaviour

A 500 Internal server error is shown

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.0"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
WebDAV

**Are you using encryption:** 
No

**Logs**

Server Logs

```
{"reqId":"SPHyn001G7Cbj7OwhYBb","level":4,"time":"2017-04-20T07:48:24+00:00","remoteAddr":"82.159.139.58","user":"admin","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/WebDAV\/ExternalStorageDV.docx","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Server error response [url] http:\\\/\\\/docker.oc.solidgear.es:62546\\\/remote.php\\\/webdav\\\/\\\/ExternalStorageDV.docx.ocTransferId579160188.part [status code] 500 [reason phrase] Internal Server Error\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(164): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(GuzzleHttp\\\\Exception\\\\ServerException))\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #58)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('ExternalStorage...', Resource id #58)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('WebDAV\\\/External...', Resource id #58, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/opt\\\/owncloud\\\/remote.php(165): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#10 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":604,\"User\":\"admin\"}"}
```

### Client configuration

**Browser**

**Note:** Tested in 9.1.4 with the same webDAV backend an it works fine. Tested with an SFTP mountpoint and it works fine.

**Comment by PVince81** [comment]
Do other external storages work fine ? Is this limited to the DAV storage ?

**Comment by davitol** [comment]
> Note: Tested in 9.1.4 with the same webDAV backend an it works fine. Tested with an SFTP mountpoint and it works fine.

**Comment by davitol** [comment]
Fails too using cadaver:

```
dav:/remote.php/webdav/WebDAV/> mput 27689.patch
Uploading 27689.patch to `/remote.php/webdav/WebDAV/27689.patch':
Progress: [=============================>] 100.0% of 3051 bytes failed:
500 Internal Server Error
```

**Comment by PVince81** [comment]
But we have unit tests connecting to a DAV server (apache mod_dav) and they work, they have uploads.

**Comment by PVince81** [comment]
not aware of anyone else complaining about this, moving to triage for now

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
