### ISSUE TITLE
9.1.4 - no page refresh

### ISSUE THREAD

**Issue by TrapperPhD** [owncloud/core#27712]
### Steps to reproduce
1. manually updated from 8.2.7 to 8.2.10 to 9.0.8 to 9.1.4 (each time complete replacement (delete&new version moved in), except config.php and data folder)
2. only apps provided by OC activated (no apps manually installed)
2. log into OC as Administrator or user (Firefox)
3. moving from Files to Contacts via top left app menu (but also with other activities, very frequently, e.g. with log-off)

### Expected behaviour
page refresh

### Actual behaviour
warning note "Failed to request notifications. Please try to refresh the page manually."
![grafik](https://cloud.githubusercontent.com/assets/20625017/25243326/eadf1eac-25fc-11e7-9c1d-727ea01fcc22.png)

### Server configuration
**Operating system**: Ubuntu 14.04.1, latest updates installed

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** 9.1.4

**Updated from an older ownCloud or fresh install:** updated, see above; but completely fresh except config.php and data folder (no overwrite e.g.)

**Where did you install ownCloud from:** https://download.owncloud.org/community/owncloud-9.1.4.tar.bz2

**The content of config/config.php:**

 "instanceid": "oc3a41047555",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.7",
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/media\/Fileserver\/EigenWolke\/data",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "version": "9.1.4.2",
        "installed": true,
        "has_internet_connection": true,
        "forcessl": true,
        "maintenance": false,
        "updatechecker": false,
        "mail_from_address": "root",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "localhost",
        "mail_domain": "127.0.0.1",
        "loglevel": 0,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/owncloud",
        "xframe_restriction": false,
        "defaultapp": "files",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": true,
        "appcodechecker": false,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "cache_path": "",
        "quota_include_external_storage": false,
        "filesystem_check_changes": 1,
        "enable_avatars": true,
        "theme": "",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "asset-pipeline.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "integrity.check.disabled": true,
        "enable_previews": false

**List of activated apps:**

Enabled:
  - activity: 2.3.2
  - audioplayer: true
  - bookmarks: true
  - calendar: true
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: true
  - dav: 0.2.7
  - documents: true
  - encryption: 1.3.0
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.9.0.0
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_external: 0.4
Disabled:
  - user_ldap

**Are you using external storage, if yes which one:** local folders

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 52.0.2

**Operating system:** Windows 10

#### ownCloud log (data/owncloud.log)

```
{"reqId":"nKUsswdIKvmFArzFwgU0","remoteAddr":"192.168.1.1","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2017-04-20T18:00:12+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/integrity\/failed","user":"--"}
{"reqId":"8mCitujDVcypS45kIhN+","remoteAddr":"192.168.1.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2017-04-20T18:00:52+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/personal","user":"Administrator"}
{"reqId":"9+2U1AlMab+\/iGN8TjzH","remoteAddr":"91.89.24.89","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-04-20T18:01:20+00:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/caldav\/calendars\/czk\/","user":"--"}
{"reqId":"TexHdjltyyjrUiVE4vRP","remoteAddr":"192.168.1.1","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2017-04-20T18:04:19+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/configreport\/report","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","level":1,"time":"2017-04-20T18:10:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","level":1,"time":"2017-04-20T18:10:07+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 3204","level":0,"time":"2017-04-20T18:10:13+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 3204","level":0,"time":"2017-04-20T18:10:15+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash job with ID 3206","level":0,"time":"2017-04-20T18:10:16+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash job with ID 3206","level":0,"time":"2017-04-20T18:10:16+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Versions\\BackgroundJob\\ExpireVersions job with ID 3207","level":0,"time":"2017-04-20T18:10:16+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Versions\\BackgroundJob\\ExpireVersions job with ID 3207","level":0,"time":"2017-04-20T18:10:16+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 3208","level":0,"time":"2017-04-20T18:10:17+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2017-04-19T18:10:17+00:00","level":1,"time":"2017-04-20T18:10:17+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 3208","level":0,"time":"2017-04-20T18:10:17+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\UpdateNotification\\Notification\\BackgroundJob job with ID 3209","level":0,"time":"2017-04-20T18:10:17+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\UpdateNotification\\Notification\\BackgroundJob job with ID 3209","level":0,"time":"2017-04-20T18:10:17+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Antivirus\\Cron\\Task job with ID 3211","level":0,"time":"2017-04-20T18:10:17+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"PHP","message":"fread(): Length parameter must be greater than 0 at \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#83","level":3,"time":"2017-04-20T18:11:01+00:00","method":"--","url":"--","user":"Administrator"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"files_antivirus","message":"Scan started File: 4Account: Administrator Path: \/ownCloudUserManual.pdf","level":0,"time":"2017-04-20T18:11:01+00:00","method":"--","url":"--","user":"Administrator"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2017-04-20T18:11:01+00:00","method":"--","url":"--","user":"Administrator"}{"reqId":"7O0Jiwnw8sdt1\/1rNJ8E","remoteAddr":"192.168.1.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: multikeydecrypt with share key failed:error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":311,\"User\":\"cve\"}","level":4,"time":"2017-04-20T18:16:42+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/Fotos\/2015.2.jpg","user":"cve"}
{"reqId":"Y8DtQ7KMbuOzUfgoGijn","remoteAddr":"192.168.1.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: multikeydecrypt with share key failed:error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":311,\"User\":\"cve\"}","level":4,"time":"2017-04-20T18:16:45+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/Fotos\/2015.3.jpg","user":"cve"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2017-04-20T18:17:23+00:00","method":"--","url":"--","user":"cve"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Antivirus\\Cron\\Task job with ID 3211","level":0,"time":"2017-04-20T18:17:23+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Sharing\\DeleteOrphanedSharesJob job with ID 3212","level":0,"time":"2017-04-20T18:17:23+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2017-04-20T18:17:24+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Sharing\\DeleteOrphanedSharesJob job with ID 3212","level":0,"time":"2017-04-20T18:17:24+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Sharing\\ExpireSharesJob job with ID 3213","level":0,"time":"2017-04-20T18:17:24+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Sharing\\ExpireSharesJob job with ID 3213","level":0,"time":"2017-04-20T18:17:24+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2","level":0,"time":"2017-04-20T18:17:24+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2","level":0,"time":"2017-04-20T18:17:24+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\Activity\\BackgroundJob\\EmailNotification job with ID 2833","level":0,"time":"2017-04-20T18:17:24+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\Activity\\BackgroundJob\\EmailNotification job with ID 2833","level":0,"time":"2017-04-20T18:17:24+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2860","level":0,"time":"2017-04-20T18:17:25+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2860","level":0,"time":"2017-04-20T18:17:25+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2861","level":0,"time":"2017-04-20T18:17:25+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2861","level":0,"time":"2017-04-20T18:17:25+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\Activity\\BackgroundJob\\ExpireActivities job with ID 3164","level":0,"time":"2017-04-20T18:17:25+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\Activity\\BackgroundJob\\ExpireActivities job with ID 3164","level":0,"time":"2017-04-20T18:17:25+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3180","level":0,"time":"2017-04-20T18:17:25+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3180","level":0,"time":"2017-04-20T18:17:25+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3181","level":0,"time":"2017-04-20T18:17:25+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3181","level":0,"time":"2017-04-20T18:17:25+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3183","level":0,"time":"2017-04-20T18:17:26+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3183","level":0,"time":"2017-04-20T18:17:26+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\DAV\\CardDAV\\SyncJob job with ID 3200","level":0,"time":"2017-04-20T18:17:26+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\DAV\\CardDAV\\SyncJob job with ID 3200","level":0,"time":"2017-04-20T18:17:26+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\Federation\\SyncJob job with ID 3201","level":0,"time":"2017-04-20T18:17:26+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\Federation\\SyncJob job with ID 3201","level":0,"time":"2017-04-20T18:17:26+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 3203","level":0,"time":"2017-04-20T18:17:26+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 3203","level":0,"time":"2017-04-20T18:17:26+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Run OCA\\Files\\BackgroundJob\\ScanFiles job with ID 3202","level":0,"time":"2017-04-20T18:17:27+00:00","method":"--","url":"--","user":"--"}
{"reqId":"d5NqwAElnUyvceI0EPyH","remoteAddr":"","app":"cron","message":"Finished OCA\\Files\\BackgroundJob\\ScanFiles job with ID 3202","level":0,"time":"2017-04-20T18:17:28+00:00","method":"--","url":"--","user":"--"}
```

**Comment by kdslkdsaldsal** [comment]
> only apps provided by OC activated (no apps manually installed)

I can see at least two apps (audioplayer and bookmarks) which are 3rdparty apps not shipped with ownCloud.

**Comment by TrapperPhD** [comment]
OK, both have been activated by repository inside OC. I have now deactivated both (Bookmarks and Audioplayer) and restarted Apache2. 

The error message seems not to appear anymore. 
Thank you very much!

Interestingly, re-activating the Bookmarks and Audioplayer apps did **not** bring back the error note.

For someone else with a similar issue, if you want to track ...
I by chance also realized that encryption was activated for local external storage (which should not be activated). I am not sure if tgis was related but you might want to cross-check.
![grafik](https://cloud.githubusercontent.com/assets/20625017/25266736/85a91c4c-2672-11e7-922c-776bcbbd6623.png)

If you allow me, I would like to watch it for some hours today, and will close issue if I do not see it anymore.

**Comment by TrapperPhD** [comment]
I still see the error note "Failed to request notifications. Please try to refresh the page manually." with a user account ...
with having both apps disabled ...
but much less frequently ...

Anything else I should check?

**Comment by TrapperPhD** [comment]
Close it now, as error note comes just rarely only, non-systematically and without related items in ownCloud logfile.
