### ISSUE TITLE
Cannot create a file in a WebDAV mountpoint with encryption enabled.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27720]
### Steps to reproduce

1. Mount a WebDAV external Storage Mountpoint
2. Create a file in WebDAV Mountpoint
3. Enable encryption in the oC Server (logout/login)
4. Try to create a file in WebDAV Mountpoint

### Expected behaviour

The file should be created

### Actual behaviour

The file is not created and a error message is shown  ```Could not create file "YesEnc.txt"```

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.0 RC2"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
WebDAV

**Are you using encryption:** 
No

**Logs**

Server Logs

```
{"reqId":"ZVoGN0S5mRezwVtHxHEE","level":4,"time":"2017-04-21T10:48:59+00:00","remoteAddr":"82.159.139.58","user":"admin","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/WebDAV\/YesEnc.txt","message":"Exception: {\"Message\":\"Server error response [url] http:\\\/\\\/docker.oc.solidgear.es:62714\\\/remote.php\\\/webdav\\\/\\\/YesEnc.txt [status code] 503 [reason phrase] Service Unavailable\",\"Exception\":\"GuzzleHttp\\\\Exception\\\\ServerException\",\"Code\":503,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Subscriber\\\/HttpError.php(32): GuzzleHttp\\\\Exception\\\\RequestException::create(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Message\\\\Response))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Event\\\/Emitter.php(108): GuzzleHttp\\\\Subscriber\\\\HttpError->onComplete(Object(GuzzleHttp\\\\Event\\\\CompleteEvent), 'complete')\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(91): GuzzleHttp\\\\Event\\\\Emitter->emit('complete', Object(GuzzleHttp\\\\Event\\\\CompleteEvent))\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(136): GuzzleHttp\\\\Client->get('http:\\\/\\\/docker.o...', Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(350): OC\\\\Http\\\\Client\\\\Client->get('http:\\\/\\\/docker.o...', Array)\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(294): OC\\\\Files\\\\Storage\\\\DAV->fopen('YesEnc.txt', 'r')\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/PermissionsMask.php(117): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('YesEnc.txt', 'r')\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(294): OC\\\\Files\\\\Storage\\\\Wrapper\\\\PermissionsMask->fopen('YesEnc.txt', 'r')\\n#15 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(317): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('YesEnc.txt', 'r')\\n#16 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(848): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->fopen('YesEnc.txt', 'r')\\n#17 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(917): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->readFirstBlock('YesEnc.txt')\\n#18 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(948): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getHeader('YesEnc.txt')\\n#19 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(249): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getEncryptionModule('YesEnc.txt.ocTr...')\\n#20 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(261): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->unlink('YesEnc.txt.ocTr...')\\n#21 [internal function]: OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->unlink('YesEnc.txt.ocTr...')\\n#22 \\\/opt\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(169): call_user_func_array(Array, Array)\\n#23 \\\/opt\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(120): OCA\\\\Files_Trashbin\\\\Storage->doDelete('YesEnc.txt.ocTr...', 'unlink')\\n#24 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(198): OCA\\\\Files_Trashbin\\\\Storage->unlink('YesEnc.txt.ocTr...')\\n#25 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #60)\\n#26 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('YesEnc.txt', Resource id #60)\\n#27 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('WebDAV\\\/YesEnc.t...', Resource id #60, NULL)\\n#28 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#29 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#30 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#31 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#32 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#33 \\\/opt\\\/owncloud\\\/remote.php(165): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#34 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":89,\"User\":\"admin\"}"}
```

### Client configuration

**Browser**

Mozilla

@PVince81

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
please try again with 10.0.4
