### ISSUE TITLE
upgrade from 9.1.3.1 to 10.0.0.12 fails

### ISSUE THREAD

**Issue by pboosten** [owncloud/core#27848]
Press the Upgrade button

### Expected behaviour
I expect the upgrade to continue, either by web interface or with occ

### Actual behaviour
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT "id" FROM "oc_jobs" WHERE ("class" = ?) AND ("argument" = ?) LIMIT 1' with params ["OCA\\Market\\SyncJob", "null"]: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block

### Server configuration
OS: FreeBSD 10

Web server: 2.4.25_1

Database: postgresql 9.2.20

PHP version: 5.6.30

ownCloud version: 9.1.3.1 (db) -> 10.0.0 (files)

Updated from an older ownCloud : update from older (9.1.3.1)

Where did you install ownCloud from: port collection (FreeBSD)

Signing status (ownCloud 9.0 and above): ?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed: doesn't work, wants to upgrade



**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '<REMOVED>',
  'passwordsalt' => '<REMOVED>',
  'datadirectory' => '/usr/local/www/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '9.1.3.1',
  'dbname' => '<REMOVED>',
  'dbhost' => '<REMOVED>',
  'dbtableprefix' => 'oc_',
  'dbuser' => '<REMOVED>',
  'dbpassword' => '<REMOVED>',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'overwrite.cli.url' => '/cloud',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '<REMOVED>',
  ),
  'secret' => <REMOVED>',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '<REMOVED>',
  'mail_smtphost' => '<REMOVED>',
  'mail_smtpport' => '25',
  'forcessl' => false,
  'loglevel' => 2,
  'filesystem_check_changes' => 1,
  'htaccess.RewriteBase' => '/cloud',
  'mail_from_address' => 'owncloud',
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\MarkDown',
    8 => 'OC\\Preview\\PDF',
  ),
);

```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.

Enabled:
  - dav: 0.2.8
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_external: true
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - gallery: 15.0.0
Disabled:
  - activity
  - comments
  - configreport.not
  - encryption
  - example-theme
  - external
  - federation
  - files_antivirus
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - market
  - notifications
  - provisioning_api
  - systemtags
  - templateeditor
  - updatenotification
  - user_external
  - user_ldap

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser: Edge, IE, Chrome, Firefox

**Operating system: Windows 7, Windows 95, OS X

#### System error log
```
May 10 12:28:47 ra postgres[93677]: [2-2] STATEMENT:  CREATE TABLE "oc_external_mounts" ("mount_id" BIGSERIAL NOT NULL, "mount_point" VARCHAR(128) NOT NULL, "storage_backend" VARCHAR(64) NOT NULL, "auth_backend" VARCHAR(64) NOT NULL, "priority" INT DEFAULT 100 NOT NULL, "type" INT NOT NULL, PRIMARY KEY("mount_id"))
May 10 12:28:47 ra postgres[93677]: [3-1] ERROR:  current transaction is aborted, commands ignored until end of transaction block
May 10 12:28:47 ra postgres[93677]: [3-2] STATEMENT:  SELECT "id" FROM "oc_jobs" WHERE ("class" = $1) AND ("argument" = $2) LIMIT 1
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"WRLrXsCoDQ8AANiBDAwAAAAC","level":0,"time":"2017-05-10T10:28:46+00:00","remoteAddr":"192.168.13.196","user":"--","app":"core","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=dwJICzYLGFZFLWcyMy8AUyMcDjorKnAOYQczWxRfDDE%3D%3AX6yiDeantLVddfj5YMcRID7j1LyipnVeisl7j%2FpoDw8%3D","message":"starting upgrade from 9.1.3.1 to 10.0.0.12"}
{"reqId":"WRLrXsCoDQ8AANiBDAwAAAAC","level":3,"time":"2017-05-10T10:28:47+00:00","remoteAddr":"192.168.13.196","user":"--","app":"core","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=dwJICzYLGFZFLWcyMy8AUyMcDjorKnAOYQczWxRfDDE%3D%3AX6yiDeantLVddfj5YMcRID7j1LyipnVeisl7j%2FpoDw8%3D","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'SELECT \\\"id\\\" FROM \\\"oc_jobs\\\" WHERE (\\\"class\\\" = ?) AND (\\\"argument\\\" = ?) LIMIT 1' with params [\\\"OCA\\\\\\\\Market\\\\\\\\SyncJob\\\", \\\"null\\\"]:\\n\\nSQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT \\\"id\\\" FRO...', Array)\\n#2 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(190): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT \\\"id\\\" FRO...', Array, Array, NULL)\\n#3 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id` FRO...', Array, Array)\\n#4 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/JobList.php(140): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/JobList.php(63): OC\\\\BackgroundJob\\\\JobList->has('OCA\\\\\\\\Market\\\\\\\\Sync...', NULL)\\n#7 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(1114): OC\\\\BackgroundJob\\\\JobList->add('OCA\\\\\\\\Market\\\\\\\\Sync...')\\n#8 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/Installer.php(509): OC_App::setupBackgroundJobs(Array)\\n#9 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/Installer.php(461): OC\\\\Installer::installShippedApp('market')\\n#10 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(232): OC\\\\Installer::installShippedApps(true)\\n#11 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(108): OC\\\\Updater->doUpgrade('10.0.0.12', '9.1.3.1')\\n#12 \\\/usr\\\/local\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(190): OC\\\\Updater->upgrade()\\n#13 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":91}"}

```

**Comment by PVince81** [comment]
How did you upgrade OC ? Did you properly delete the old source code before replacing with the new one ?

**Comment by pboosten** [comment]
I assume the ports collection of FreeBSD takes care of that (it never failed before)

**Comment by pboosten** [comment]
Ha! It turned out that it didn't clean properly, the last time. I've deleted the port, and indeed several files weren't deleted. So deleting them manually (everything besides data and config), and reinstalling the port did the trick.

Thanks for the suggestion!

**Comment by kdslkdsaldsal** [comment]
@pboosten For the future it also worth to upgrade to the latest point release before jumping to the next major release to avoid further issues. In your case it is recommended to go from 9.1.3 to 9.1.5 first before doing the jump to 10.0.0
