### ISSUE TITLE
.htaccess in skeleton folder results in "Internal Server Error"

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#27853]
### Steps to reproduce
1. in config.php set skeletondirectory setting
2. copy a .htaccess file in that skeleton directory
3. create a new user
4. login as new user

### Expected behaviour
Login should work fine, .htaccess file should not be copied into user folder

### Actual behaviour
Internal Server Error message displayed

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache 2.2
**Database:**
sqlite
**PHP version:**
PHP 7.0.7-5
**ownCloud version:** (see ownCloud admin page)
10.0.0.12
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc150y5qiolb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "sqlite3",
        "version": "10.0.0.12",
        "logtimezone": "UTC",
        "skeletondirectory": "\/tmp\/data",
        "installed": true
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - testing
  - theme-example
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox
**Operating system:**
Debian

#### ownCloud log (data/owncloud.log)
```
{"reqId":"XdBR4L9dkpgaApHTUpfV","level":3,"time":"2017-05-11T03:20:08+00:00","remoteAddr":"::1","user":"user4","app":"index","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(102): OC\\\\Files\\\\Node\\\\Node->checkPermissions(3)\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/legacy\\\/util.php(417): OC\\\\Files\\\\Node\\\\File->fopen('w')\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/legacy\\\/util.php(395): OC_Util::copyr('\\\/tmp\\\/data', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#5 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Session.php(404): OC_Util::copySkeleton('user4', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#6 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Session.php(469): OC\\\\User\\\\Session->prepareUserLogin(true)\\n#7 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Session.php(299): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#8 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/core\\\/Controller\\\/LoginController.php(200): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#9 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#10 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#12 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#13 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/login')\\n#17 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/index.php(49): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}"}
```

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by individual-it** [comment]
I hope nobody (except of QA) is so stupid to place a forbidden file into the skeleton directory, so I leave it closed
