### ISSUE TITLE
Cannot uninstall LDAP app via market app after upgradid from oC 9.1.5

### ISSUE THREAD

**Issue by davitol** [owncloud/core#28001]
### Steps to reproduce

1. From a oC server 9.1.5 with Home LDAP and LDAP User apps enabled, upgrade to oC10 patched with https://github.com/owncloud/core/pull/27985
2. After the upgrade, go to market
3. Uninstall LDAP User App
4. Go back to files view

### Expected behaviour

Files view should be shown

### Actual behaviour

The oC server shows an internal server error

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.1" 

**Updated from an older ownCloud or fresh install:**
Updated from 9.1.5

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"v8QdUtwRskxzY5GReuK0","level":3,"time":"2017-05-24T19:21:58+00:00","remoteAddr":"81.40.164.56","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/market\/apps","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCA\\\\User_LDAP\\\\Helper' not found\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(42): OCA\\\\Files_LDAP_Home\\\\Storage::initiateLDAPAccess(Object(OC\\\\AllConfig))\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(150): OCA\\\\Files_LDAP_Home\\\\Storage->__construct(Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OCA\\\\Files_LDAP_Home\\\\Storage::setup(Array)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(452): OC_Hook::emit('OC_Filesystem', 'post_initMountP...', Array)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(375): OC\\\\Files\\\\Filesystem::initMountPoints('admin')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(297): OC\\\\Files\\\\Filesystem::init('admin', '\\\/admin\\\/files')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/base.php(917): OC_Util::setupFS()\\n#7 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php\",\"Line\":97}"}
{"reqId":"VwvYObNb6Knuq2qBX96B","level":3,"time":"2017-05-24T19:22:03+00:00","remoteAddr":"81.40.164.56","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCA\\\\User_LDAP\\\\Helper' not found\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(42): OCA\\\\Files_LDAP_Home\\\\Storage::initiateLDAPAccess(Object(OC\\\\AllConfig))\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(150): OCA\\\\Files_LDAP_Home\\\\Storage->__construct(Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OCA\\\\Files_LDAP_Home\\\\Storage::setup(Array)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(452): OC_Hook::emit('OC_Filesystem', 'post_initMountP...', Array)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(375): OC\\\\Files\\\\Filesystem::initMountPoints('admin')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(297): OC\\\\Files\\\\Filesystem::init('admin', '\\\/admin\\\/files')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/base.php(917): OC_Util::setupFS()\\n#7 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php\",\"Line\":97}"}
{"reqId":"ppdLLL6dm2xf68zWo6yI","level":3,"time":"2017-05-24T19:22:06+00:00","remoteAddr":"81.40.164.56","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/files\/undefined\/img\/notifications.svg","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCA\\\\User_LDAP\\\\Helper' not found\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(42): OCA\\\\Files_LDAP_Home\\\\Storage::initiateLDAPAccess(Object(OC\\\\AllConfig))\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(150): OCA\\\\Files_LDAP_Home\\\\Storage->__construct(Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OCA\\\\Files_LDAP_Home\\\\Storage::setup(Array)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(452): OC_Hook::emit('OC_Filesystem', 'post_initMountP...', Array)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(375): OC\\\\Files\\\\Filesystem::initMountPoints('admin')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(297): OC\\\\Files\\\\Filesystem::init('admin', '\\\/admin\\\/files')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/base.php(917): OC_Util::setupFS()\\n#7 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php\",\"Line\":97}"}
{"reqId":"RRYmtuneTV501wD8f6Db","level":3,"time":"2017-05-24T19:22:06+00:00","remoteAddr":"81.40.164.56","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/gallery\/config?extramediatypes=1","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCA\\\\User_LDAP\\\\Helper' not found\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(42): OCA\\\\Files_LDAP_Home\\\\Storage::initiateLDAPAccess(Object(OC\\\\AllConfig))\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php(150): OCA\\\\Files_LDAP_Home\\\\Storage->__construct(Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OCA\\\\Files_LDAP_Home\\\\Storage::setup(Array)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(452): OC_Hook::emit('OC_Filesystem', 'post_initMountP...', Array)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(375): OC\\\\Files\\\\Filesystem::initMountPoints('admin')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(297): OC\\\\Files\\\\Filesystem::init('admin', '\\\/admin\\\/files')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/base.php(917): OC_Util::setupFS()\\n#7 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_ldap_home\\\/lib\\\/Storage.php\",\"Line\":97}"}
{"reqId":"IQnhdxV1lP5fMhnEoLmZ","level":3,"time":"2017-05-24T19:22:06+00:00","remoteAddr":"81.40.164.56","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Error: Class 'OCA\\User_LDAP\\Helper' not found at \/opt\/owncloud\/apps\/files_ldap_home\/lib\/Storage.php#97"}
```

### Client configuration

**browser**

Mozilla

![screen shot 2017-05-24 at 19 00 23](https://cloud.githubusercontent.com/assets/10596560/26421842/d247e35c-40c7-11e7-90c7-10e38d4d1507.png)

@PVince81 FYI

**Comment by PVince81** [comment]
This is because you have Files_LDAP_Home enabled which depends on user_ldap... That's not an issue with the market or app manager. Just this weird inter-app dependency that is messing up.

@tomneedham you did some hacking around this ?

**Comment by PVince81** [comment]
@davitol if disabling files ldap home first and then uninstalling user_ldap work, then this is not critical.

Is there a workaround ? Are you able to disable ldap home from the CLI after seeing this error ?

**Comment by davitol** [comment]
> @davitol if disabling files ldap home first and then uninstalling user_ldap work, then this is not critical.

Disabling ldap home first via webUI the problem is solved, so no critical.

> Is there a workaround ? Are you able to disable ldap home from the CLI after seeing this error ?

WIP

@PVince81 @tomneedham

**Comment by PVince81** [comment]
backlog, I don't think it's critical and there's a workaround

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
This is not a core problem...
