### ISSUE TITLE
OC\RepairException: Upgrade is not possible. Unsuccessful upgrade from 10.0.0 to 10.0.1

### ISSUE THREAD

**Issue by ertomedia** [owncloud/core#28013]
### Steps to reproduce
Update from 10.0.0 using Softaculous (cpanel) updater.

### Actual behaviour
Displaying error message "OC\RepairException: Upgrade is not possible" when initiating the upgrade process. 

### Server configuration
**Operating system**: Linux

**Web server:** LiteSpeed

**Database:** MySQL

**PHP version:** 7.1

**ownCloud version:** 10.0.0

**Updated from an older ownCloud or fresh install:** Older version 10.0.0

**Where did you install ownCloud from:** Softaculous (cPanel)

**Are you using external storage, if yes which one:** Amazon S3

**Are you using encryption:** No

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 7

#### ownCloud log (data/owncloud.log)
```
{"reqId":"1YwhV18mnWUgoD5MEAR1","level":3,"time":"2017-05-26T04:46:30+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"index","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=a8df356309283a9df646ad223f9d7406","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/private\\\/legacy\\\/app.php(121): OC_App::loadApp('dav')\\n#1 \\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/private\\\/legacy\\\/util.php(145): OC_App::loadApps(Array)\\n#2 \\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/base.php(917): OC_Util::setupFS()\\n#3 \\\/my_home_path\\\/docs.tikimanado.com\\\/index.php(49): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":162}"}
{"reqId":"PTJXsOtNb8pKUcqLhHdg","level":0,"time":"2017-05-26T04:46:42+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=M3weYx5dAwgJdVE3KQQqFgQSUBNbJCcIMggcGlxiHUc%3D%3Ar4hHFmon8MeOkWxrgt8ZoiPKbelCdZOtSmfEDG%2BHPyA%3D","message":"starting upgrade from 10.0.0.12 to 10.0.1.5"}
{"reqId":"PTJXsOtNb8pKUcqLhHdg","level":3,"time":"2017-05-26T04:46:43+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=M3weYx5dAwgJdVE3KQQqFgQSUBNbJCcIMggcGlxiHUc%3D%3Ar4hHFmon8MeOkWxrgt8ZoiPKbelCdZOtSmfEDG%2BHPyA%3D","message":"Exception: {\"Exception\":\"OC\\\\RepairException\",\"Message\":\"Upgrade is not possible\",\"Code\":0,\"Trace\":\"#0 \\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/private\\\/Repair.php(88): OC\\\\Repair\\\\Apps->run(Object(OC\\\\Repair))\\n#1 \\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/private\\\/Updater.php(221): OC\\\\Repair->run()\\n#2 \\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/private\\\/Updater.php(108): OC\\\\Updater->doUpgrade('10.0.1.5', '10.0.0.12')\\n#3 \\\/my_home_path\\\/docs.tikimanado.com\\\/core\\\/ajax\\\/update.php(190): OC\\\\Updater->upgrade()\\n#4 {main}\",\"File\":\"\\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/private\\\/Repair\\\/Apps.php\",\"Line\":178}"}
{"reqId":"S1bWU4Jq7Lhh8cHIEz8p","level":3,"time":"2017-05-26T04:59:21+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"index","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=a8df356309283a9df646ad223f9d7406","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/private\\\/legacy\\\/app.php(121): OC_App::loadApp('dav')\\n#1 \\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/private\\\/legacy\\\/util.php(145): OC_App::loadApps(Array)\\n#2 \\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/base.php(917): OC_Util::setupFS()\\n#3 \\\/my_home_path\\\/docs.tikimanado.com\\\/index.php(49): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/my_home_path\\\/docs.tikimanado.com\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":162}"}
```

**Comment by PVince81** [comment]
no other details in the error message, like apps to disable ?

**Comment by tomneedham** [comment]
With that exception I would expect at least these two outputs: https://github.com/owncloud/core/blob/master/lib/private/Repair/Apps.php#L172-L176

**Comment by ertomedia** [comment]
Sorry, I forgot to put this detailed logs.

```
Preparing update
Set log level to debug
Turned on maintenance mode
Repair warning: Market app is unavailable for updating of apps. Enable with: occ:app:enable market
Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Repair warning: please install app manually with tarball or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery
OC\RepairException: Upgrade is not possible
```

**Comment by PVince81** [comment]
Try this: `occ:app:enable market`

Then rerun `occ upgrade`

**Comment by kdslkdsaldsal** [comment]
I wonder how much more info could be give to the users to solve such kind of issues.

IMHO the text contains all needed info but @ertomedia may be able to give some pointers if the text isn't that clear or is missing any information to solve this kind of issues.

**Comment by PVince81** [comment]
Please reopen if the above instructions didn't work and post details about the result.

Might also be good to try with 10.0.2 as some market related bugs were fixed.
