### ISSUE TITLE
after upgrade to owncloud 10.0 - no marketplace - no app store - .htaccess hash invalid - contacts-, calendar- and bookmarks apps incompatible - curl error 77

### ISSUE THREAD

**Issue by powerusergdfath** [owncloud/core#28025]
### Steps to reproduce
1. upgrade from owncloud 9.2 to 10.0 
2. install from official ubuntu repository - OS ubuntu 16.04 LTS
3. repair mode for upgrade were activated - as required by owncloud install routine

### Expected behaviour
everything should work as expected and as it did before the upgrade. 

### Actual behaviour
- contacts, calendar and bookmark apps appear as incompatible
- app store and/or? market place are not reachable via internet. owncloud tells me there is no internet connection. but from command line I were able to establish connections with wget or telnet 
- .htaccess file should successfully pass the integrity check but instead it is stigmatized as invalid (hash) and this ugly and disturbing yellow info bar is always prompted in admin tab.

### Server configuration
**Operating system**:
Ubuntu 16.04 LTS

**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
Ver 14.14 Distrib 5.7.18, for Linux (x86_64)

**PHP version:**

PHP 7.0.18-0ubuntu0.16.04.1 

**ownCloud version:** (see ownCloud admin page)

ownCloud 10.0.0

**Updated from an older ownCloud or fresh install:**
upgrade from 9.2
**Where did you install ownCloud from:**
ubuntu repository

**Signing status (ownCloud 9.0 and above):**
stable
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.

https://gist.github.com/powerusergdfath/db9c4290fb2c2dba77f0ada6cdb39dda

**The content of config/config.php:**

"config": {
        "updatechecker": false,
        "instanceid": "ocXXXXXXXX4u",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.---.---.--",
            "----------------------.XXXXXX.de"
        ],
        "datadirectory": "\----------/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.---.----./owncloud",
        "dbtype": "mysql",
        "version": "10.0.0.12",
        "dbname": "owXXXXXX",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "logdateformat": "F d, Y H:i:s",
        "installed": true,
        "mail_from_address": "------------",
        "mail_smtpmode": "smtp",
        "mail_domain": "XXX.net",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "XXX.XXX.net",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "maintenance": false,
        "theme": "",
        "Has_internet_connection": true,
        "Check_for_working_webdav": true,
        "Updater.server.url": "https:\/\/updates.owncloud.com\/server\/",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_certificate_management": false

**List of activated apps:**

 "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_certificate_management": false
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.3",
            "types": "filesystem"
        },
        "audioplayer": {
            "enabled": "no",
            "installed_version": "1.5.1",
            "ocsid": "174738",
            "signed": "true",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "12"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.9.0",
            "ocsid": "168710",
            "types": ""
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "1.4.1",
            "ocsid": "168707",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "yes",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "enabled": "no",
            "installed_version": "1.5.1",
            "ocsid": "168708",
            "signed": "true",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "ajax",
            "installedat": "1483106135.8531",
            "lastcron": "1495825050",
            "lastupdateResult": "[]",
            "lastupdatedat": "1495821211",
            "oc.integritycheck.checker": "{\"core\":{\"INVALID_HASH\":{\".htaccess\":{\"expected\":\"314e4e8-------------------------------------------------a02608173757189dd10bb56015a0a077dc40eea5f5d2a9561b87464aa9a7c6fa52e\",\"current\":\"3853732aff0c1322d-------------------------------------------------7fd01617764affa371d36bd195815f0129cc326cb24cf776faea902865da4385\"}}}}",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_default_expire_date": "yes",
            "shareapi_enforce_links_password": "yes",
            "vendor": ""
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.2.8",
            "types": "filesystem"
        },
        "documents": {
            "converter": "off",
            "enabled": "no",
            "installed_version": "0.13.1",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": ""
        },
        "federation": {
            "autoAddServers": "0",
            "enabled": "no",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.5.1",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "0.7.0",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.10.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "15.0.0",
            "types": ""
        },
        "market": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "music": {
            "enabled": "no",
            "installed_version": "0.3.12",
            "ocsid": "164319",
            "types": "filesystem"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "1.1.17",
            "ocsid": "174727",
            "types": "",
            "wopi_url": "https:\/\/localhost:9980"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.9.4",
            "ocsid": "164356",
            "signed": "true",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "audioplayer": "1.5.1",
            "core": "9.1.5",
            "enabled": "yes",
            "installed_version": "0.2.1",
            "richdocuments": "1.1.19",
            "types": ""
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

NO

**Are you using encryption:** yes/no

NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

NO

### Client configuration
**Browser:**
Firefox 53.0.3 (64-Bit)

**Operating system:**
Ubuntu 16.04 LTS

### Logs
#### Web server error log
[Fri May 26 07:35:01.931674 2017] [ssl:warn] [pid 5607] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 07:35:01.931771 2017] [ssl:error] [pid 5607] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F5592 / notbefore: Feb 28$
[Fri May 26 07:35:01.931776 2017] [ssl:error] [pid 5607] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling
[Fri May 26 07:35:01.931811 2017] [mpm_prefork:notice] [pid 5607] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri May 26 07:35:01.931814 2017] [core:notice] [pid 5607] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 26 09:58:03.933320 2017] [mpm_prefork:notice] [pid 5607] AH00169: caught SIGTERM, shutting down
[Fri May 26 09:58:04.942770 2017] [ssl:warn] [pid 8023] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 09:58:04.942851 2017] [ssl:error] [pid 8023] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F5D592 / notbefore: Feb 28$
[Fri May 26 09:58:04.942857 2017] [ssl:error] [pid 8023] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling
[Fri May 26 09:58:04.967312 2017] [ssl:warn] [pid 8024] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 09:58:04.967384 2017] [ssl:error] [pid 8024] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F57592 / notbefore: Feb 28$
[Fri May 26 09:58:04.967390 2017] [ssl:error] [pid 8024] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling
[Fri May 26 09:58:04.969832 2017] [mpm_prefork:notice] [pid 8024] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri May 26 09:58:04.969848 2017] [core:notice] [pid 8024] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 26 10:34:19.326867 2017] [mpm_prefork:notice] [pid 8024] AH00169: caught SIGTERM, shutting down
[Fri May 26 10:34:20.337703 2017] [ssl:warn] [pid 8196] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 10:34:20.337784 2017] [ssl:error] [pid 8196] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F57D592 / notbefore: Feb 28$
[Fri May 26 10:34:20.337788 2017] [ssl:error] [pid 8196] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling
[Fri May 26 10:34:20.362180 2017] [ssl:warn] [pid 8197] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 10:34:20.362248 2017] [ssl:error] [pid 8197] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F57592 / notbefore: Feb 28$
[Fri May 26 10:34:20.362252 2017] [ssl:error] [pid 8197] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling
[Fri May 26 10:34:20.364668 2017] [mpm_prefork:notice] [pid 8197] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri May 26 10:34:20.364686 2017] [core:notice] [pid 8197] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 26 12:29:17.125930 2017] [mpm_prefork:notice] [pid 8197] AH00169: caught SIGTERM, shutting down
[Fri May 26 12:29:18.180928 2017] [ssl:warn] [pid 23888] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 12:29:18.181009 2017] [ssl:error] [pid 23888] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F57592 / notbefore: Feb 2$
[Fri May 26 12:29:18.181021 2017] [ssl:error] [pid 23888] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling
[Fri May 26 12:29:18.205608 2017] [ssl:warn] [pid 23889] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 12:29:18.205678 2017] [ssl:error] [pid 23889] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F57592 / notbefore: Feb 2$
[Fri May 26 12:29:18.205682 2017] [ssl:error] [pid 23889] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling
[Fri May 26 12:29:18.208130 2017] [mpm_prefork:notice] [pid 23889] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri May 26 12:29:18.208149 2017] [core:notice] [pid 23889] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 26 18:39:53.284690 2017] [mpm_prefork:notice] [pid 23889] AH00169: caught SIGTERM, shutting down
[Fri May 26 18:39:54.293341 2017] [ssl:warn] [pid 25420] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 18:39:54.293418 2017] [ssl:error] [pid 25420] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F5D592 / notbefore: Feb 2$
[Fri May 26 18:39:54.293423 2017] [ssl:error] [pid 25420] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling
[Fri May 26 18:39:54.317772 2017] [ssl:warn] [pid 25421] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 18:39:54.317842 2017] [ssl:error] [pid 25421] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F57BD592 / notbefore: Feb 2$
[Fri May 26 18:39:54.317846 2017] [ssl:error] [pid 25421] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling
[Fri May 26 18:39:54.320315 2017] [mpm_prefork:notice] [pid 25421] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri May 26 18:39:54.320332 2017] [core:notice] [pid 25421] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 26 18:58:01.819654 2017] [mpm_prefork:notice] [pid 25421] AH00169: caught SIGTERM, shutting down
[Fri May 26 18:58:02.881409 2017] [ssl:warn] [pid 25602] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 18:58:02.881488 2017] [ssl:error] [pid 25602] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F57BD592 / notbefore: Feb 2$
[Fri May 26 18:58:02.881492 2017] [ssl:error] [pid 25602] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling
[Fri May 26 18:58:02.906249 2017] [ssl:warn] [pid 25603] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 18:58:02.906316 2017] [ssl:error] [pid 25603] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F57BD592 / notbefore: Feb 2$
[Fri May 26 18:58:02.906320 2017] [ssl:error] [pid 25603] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling
[Fri May 26 18:58:02.908800 2017] [mpm_prefork:notice] [pid 25603] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri May 26 18:58:02.908817 2017] [core:notice] [pid 25603] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 26 20:13:37.882785 2017] [mpm_prefork:notice] [pid 25603] AH00169: caught SIGTERM, shutting down
[Fri May 26 20:13:38.899817 2017] [ssl:warn] [pid 26008] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Fri May 26 20:13:38.899912 2017] [ssl:error] [pid 26008] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=ubuntu / issuer: CN=ubuntu / serial: F57592 / notbefore: Feb 2$
[Fri May 26 20:13:38.899917 2017] [ssl:error] [pid 26008] AH02604: Unable to configure certificate 127.0.1.1:443:0 for stapling

#### ownCloud log (data/owncloud.log) 
----------------------------------------ABSTRACT with curl error---------------------------------------------------------

{"reqId":"qvsIR35htSvMcMv3L1bN","level":3,"time":"May 26, 2017 18:40:30","remoteAddr":"192.XXX.XXX.XX","user":"XXX","app":"index","method":"GET","url":"\/owncloud\/index.php\/apps\/market\/categories","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\RequestException\",\"Message\":\"cURL error 77: error setting certificate verify locations:\\n  CAfile: \\\/XXX\\\/XXX\\\/owncloud\\\/data\\\/files_external\\\/rootcerts.crt\\n  CApath: \\\/etc\\\/ssl\\\/certs\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(103): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\RingException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(136): GuzzleHttp\\\\Client->get('https:\\\/\\\/api.own...', Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/market\\\/lib\\\/MarketService.php(373): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/api.own...', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/market\\\/lib\\\/MarketService.php(406): OCA\\\\Market\\\\MarketService->httpGet('https:\\\/\\\/api.own...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/market\\\/lib\\\/MarketService.php(392): OCA\\\\Market\\\\MarketService->queryData('categories', '\\\/api\\\/v1\\\/categor...')\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/market\\\/lib\\\/Controller\\\/MarketController.php(54): OCA\\\\Market\\\\MarketService->getCategories()\\n#13 [internal function]: OCA\\\\Market\\\\Controller\\\\MarketController->categories()\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Market\\\\Controller\\\\MarketController), 'categories')\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Market\\\\Controller\\\\MarketController), 'categories')\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Market\\\\\\\\Cont...', 'categories', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/market\\\/ca...')\\n#21 \\\/var\\\/www\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":51}"}

**Comment by kdslkdsaldsal** [comment]
> cURL error 77: error setting certificate verify locations:\\n  CAfile: \\\/XXX\\\/XXX\\\/owncloud\\\/data\\\/files_external\\\/rootcerts.crt\\n  CApath: \\\/etc\\\/ssl\\\/certs\

Looks somehow related to your certificate setup:

> CURLE_SSL_CACERT_BADFILE (77)
> 
> Problem with reading the SSL CA cert (path? access rights?) 

-> https://curl.haxx.se/libcurl/c/libcurl-errors.html

So check if the "CAfile" and "CApath" exists and that those are accessible by the user running ownCloud (mostly www-data)

As you're also saying:

> **Are you using external storage, if yes which one:** local/smb/sftp/... NO

you might want to disable the files_external app mentioned in the curl error:

``occ app:disable files_external``

Furthermore you should consider to remove these from your config.php:

``
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "Has_internet_connection": true,
        "Check_for_working_webdav": true,
        "Updater.server.url": "https:\/\/updates.owncloud.com\/server\/",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_certificate_management": false
``

Especially the last entry might be responsible for your issue.

In general please only add things to your config.php which you want to change from their defaults listed in the config.sample.php

**Comment by PVince81** [comment]
please also remove the value of ""appstoreurl" so it can default to the marketplace instead of the old URL

**Comment by powerusergdfath** [comment]
hey guys,

thank you very much your help! the entries you both mentioned in your posts I had added after the upgrade. so unfortunately it took no effect to remove this lines from config.php. 
I also checked the paths of both CA locations and it turned out the www-data user had the correct permissions. I also could not disable files_external with occ tool. 

After all this unsuccessful attempts to get owncloud running again I uninstalled it with this apt-get commands:

sudo apt-get purge owncloud
sudo apt-get purge owncloud-*
sudo apt-get autoremove

After that I tried to re-install but my first attempt via apt-get ended with the automatic install of version 9... and error message owncloud is not downgradable. I should mention that I did not change anything in my sources.list.

My next attempt via apt-get ended up with http 404 error. apt-get could not find version 10 on the download mirror anymore. I also cannot find version 10 here: https://download.owncloud.org/download/repositories/stable/owncloud/. Does anyone know what happened with the official ubuntu owncloud repository?    

All in all I am a little bit confused now ;-) My next try will be to download version 10 from here https://owncloud.org/install/# and install it manually.

Further help is still very appreciated :-)

**Comment by powerusergdfath** [comment]
installed successful version 9.1.5

**Comment by emerham** [comment]
sorry to reopen this issue, but I ran across this issue on an upgrade from 9.1 to 10.0 and all I ended up doing to fix was get the latest version of the mozilla certs [certs](https://central.owncloud.org/t/error-in-owncloud-when-restoring-directory-data/4158/3)
