### ISSUE TITLE
File Cache: Uploading File to Webinterface throws notification 'Internal Server Error' and Logs failed SQL query. Uploaded file is available after page reload.

### ISSUE THREAD

**Issue by TDannhauer** [owncloud/core#28046]
### Steps to reproduce
1. Open 10.0.01 webinterface
2. Create textfile on windows desktop
3. Upload textfile via drag'n'drop or via Button into OC 

### Expected behaviour
1. Upload progressbar displays completion status
2. After complete update the file is displayed without any error or notification (yellow top bar)

### Actual behaviour
1. Upload progressbar displays completion status
2. After complete upload a yellow notification is thown: "Internal Server Error"
3. After reloding the page ion the browser, the uplöoaded file is visible.
4. An error os logged in OC.

### Server configuration
**Operating system**:

**Web server:**
Apache 2.4.25

**Database:**
PSQL 9.6

**PHP version:**
7.0.19

**ownCloud version:** (see ownCloud admin page)
10.0.1.5

**Updated from an older ownCloud or fresh install:**
latest 9.x.y release

**Where did you install ownCloud from:**
Server package from the OC website

**Signing status (ownCloud 9.0 and above):**

```
"No errors have been found."
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc87896c1670",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "1": "owncloud.trusted.domain.tld"
        },
        "datadirectory": "\/extradata\/owncloud",
        "dbtype": "pgsql",
        "version": "10.0.1.5",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 4,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "mail.trusted.domain.tld",
        "mail_smtphost": "smtp.trusted.domain.tld",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "overwritehost": "owncloud.trusted.domain.tld",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "mail_smtpsecure": "tls",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "asset-pipeline.enabled": true
    }
}

```

**List of activated apps:**

```
  - activity: 2.3.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - external: true
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.1.0
  - notifications: 0.3.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - files_antivirus
  - provisioning_api
  - theme-example
  - user_external

```

**Are you using external storage, if yes which one:** None

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
Current Firefox release

**Operating system:**
Win 10 (up to date)

#### Web server error log
```
None
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"BtZhEQxc4yuh9ge7SkDc","level":4,"time":"2017-05-31T08:38:21+00:00","remoteAddr":"193.171.63.202","user":"USER","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/testfile.unkownsuffix","message":"Exception: {\"Message\":\"An exception occurred while executing 'UPDATE "oc_filecache" SET "mtime" = GREATEST("mtime", ?), "etag" = ? WHERE ("storage" = ?) AND ("path_hash" IN ('d41d8cd98f00b204e9800998ecf8427e', '45b963397aa40d4a0063e0d85e4fe7a1'))' with params ["1496219713.997", "592e80fdb5c9a", 5]:\\n\\nSQLSTATE[22P02]: Invalid text representation: 7 FEHLER:  ung\\u00fcltige Eingabesyntax f\\u00fcr ganze Zahl: \\u00bb1496219713.997\\u00ab\",\"Exception\":\"Doctrine\DBAL\Exception\DriverException\",\"Code\":0,\"Trace\":\"#0 /OC-ROOT/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))\\n#1 /OC-ROOT/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1015): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE "oc_file...', Array)\\n#2 /OC-ROOT/lib/private/DB/Connection.php(211): Doctrine\DBAL\Connection->executeUpdate('UPDATE "oc_file...', Array, Array)\\n#3 /OC-ROOT/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): OC\DB\Connection->executeUpdate('UPDATE "oc_file...', Array, Array)\\n#4 /OC-ROOT/lib/private/DB/QueryBuilder/QueryBuilder.php(141): Doctrine\DBAL\Query\QueryBuilder->execute()\\n#5 /OC-ROOT/lib/private/Files/Cache/Propagator.php(87): OC\DB\QueryBuilder\QueryBuilder->execute()\\n#6 /OC-ROOT/lib/private/Files/Cache/HomePropagator.php(48): OC\Files\Cache\Propagator->propagateChange('files/testfile....', '1496219713.997', 0)\\n#7 /OC-ROOT/lib/private/Files/Cache/Updater.php(138): OC\Files\Cache\HomePropagator->propagateChange('files/testfile....', '1496219713.997', 0)\\n#8 /OC-ROOT/lib/private/Files/View.php(314): OC\Files\Cache\Updater->update('files/testfile....', '1496219713.997')\\n#9 /OC-ROOT/lib/private/Files/View.php(1141): OC\Files\View->writeUpdate(Object(OCA\Files_Trashbin\Storage), 'files/testfile....', '1496219713.997')\\n#10 /OC-ROOT/lib/private/Files/View.php(551): OC\Files\View->basicOperation('touch', '/testfile.unkow...', Array, '1496219713.997')\\n#11 /OC-ROOT/apps/dav/lib/Connector/Sabre/File.php(215): OC\Files\View->touch('//testfile.unko...', '1496219713.997')\\n#12 /OC-ROOT/apps/dav/lib/Connector/Sabre/Directory.php(158): OCA\DAV\Connector\Sabre\File->put(Resource id #60)\\n#13 /OC-ROOT/lib/composer/sabre/dav/lib/DAV/Server.php(1095): OCA\DAV\Connector\Sabre\Directory->createFile('testfile.unkown...', Resource id #60)\\n#14 /OC-ROOT/lib/composer/sabre/dav/lib/DAV/CorePlugin.php(525): Sabre\DAV\Server->createFile('testfile.unkown...', Resource id #60, NULL)\\n#15 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#16 /OC-ROOT/lib/composer/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#17 /OC-ROOT/lib/composer/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:PUT', Array)\\n#18 /OC-ROOT/lib/composer/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#19 /OC-ROOT/apps/dav/appinfo/v1/webdav.php(63): Sabre\DAV\Server->exec()\\n#20 /OC-ROOT/remote.php(165): require_once('/var/www/USER...')\\n#21 {main}\",\"File\":\"/OC-ROOT/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php\",\"Line\":91,\"User\":\"USER\"}"}
```

**Comment by PVince81** [comment]
a decimal mtime 1496219713.997

**Comment by TDannhauer** [comment]
I changed the language in the OC preferences to english but the error still occurs.

**Comment by TDannhauer** [comment]
My database is PSQL. Any tests I should perform to verify your idea?

**Comment by PVince81** [comment]
Please follow up here https://github.com/owncloud/core/issues/27960#issuecomment-305181289, I'll see if I can solve it on the browser side.

**Comment by PVince81** [comment]
ok I think the problem is confirmed, let's follow up in the other ticket
