### ISSUE TITLE
App Settings not callable after upgrade to 10.0.2

### ISSUE THREAD

**Issue by cornelinux** [owncloud/core#28068]
### Steps to reproduce
1. Update ubuntu 14.04 to 16.04 to get php7
2. Update 9.1.4 EE to 10.0.2 EE
2. Open Settings-> Admin -> Additionl
3. Bam - Internal Server Error

### Expected behaviour
I want to see the app configurations

### Actual behaviour
Internal server error is shown.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:**  nginx with fpm

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** (see ownCloud admin page) 10.0.2

**Updated from an older ownCloud or fresh install:**  9.1.4

**Where did you install ownCloud from:**  from customer owncloud download.

**List of activated apps:**
Outputs this: I guess it is not the list?

<pre>
# sudo -u www-data php ./occ app:list
An unhandled exception has been thrown:
OCP\AppFramework\QueryException: Could not resolve CardDavBackend! Class CardDavBackend does not exist in /srv/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php:98
Stack trace:
#0 /srv/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(113): OC\AppFramework\Utility\SimpleContainer->resolve('CardDavBackend')
#1 /srv/www/owncloud/apps/dav/appinfo/register_command.php(36): OC\AppFramework\Utility\SimpleContainer->query('CardDavBackend')
#2 /srv/www/owncloud/lib/private/Console/Application.php(114): require('/srv/www/ownclo...')
#3 /srv/www/owncloud/console.php(98): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /srv/www/owncloud/occ(11): require_once('/srv/www/ownclo...')
</pre>

I have another error log:

<pre>
{"reqId":"J2qeIRhe5wsVcvoonsCL",
"level":3,
"time":"2017-06-02T19:41:12+00:00",
"remoteAddr":"87.138.204.124",
"user":"cornelius",
"app":"PHP",
"method":"GET",
"url":"\/owncloud\/settings\/admin?sectionid=additional",
"message":"Undefined index: urlGenerator at \/srv\/www\/owncloud\/apps\/configreport\/templates\/settings\/admin.php#31"}

{"reqId":"J2qeIRhe5wsVcvoonsCL",
"level":3,
"time":"2017-06-02T19:41:12+00:00",
"remoteAddr":"87.138.204.124",
"user":"cornelius",
"app":"index",
"method":"GET",
"url":"\/owncloud\/settings\/admin?sectionid=additional",
"message":"Exception: {
	\"Exception\":\"Error\",
	\"Message\":\"Call to a member function imagePath() on null\",
	\"Code\":0,\"Trace\":
	#0 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/Template\\\/Base.php(196): include()
	#1 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/Template\\\/Base.php(171): OC\\\\Template\\\\Base->load('\\\/srv\\\/www\\\/ownclo...', NULL)\
	#2 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC\\\\Template\\\\Base->fetchPage(NULL)\\
	#3 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/configreport\\\/settings\\\/admin.php(34): OC_Template->fetchPage()
	#4 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(757): include('\\\/srv\\\/www\\\/ownclo...')\\
	#5 \\\/srv\\\/www\\\/owncloud\\\/settings\\\/Panels\\\/Helper.php(35): OC_App::getForms('admin')\
	#6 \\\/srv\\\/www\\\/owncloud\\\/settings\\\/Panels\\\/Admin\\\/Legacy.php(45): OC\\\\Settings\\\\Panels\\\\Helper->getAdminForms()\\
	#7 \\\/srv\\\/www\\\/owncloud\\\/settings\\\/Controller\\\/SettingsPageController.php(142): OC\\\\Settings\\\\Panels\\\\Admin\\\\Legacy->getPanel()\\
	#8 \\\/srv\\\/www\\\/owncloud\\\/settings\\\/Controller\\\/SettingsPageController.php(104): OC\\\\Settings\\\\Controller\\\\SettingsPageController->getPanelsData(Array)\\n
	#9 [internal function]: OC\\\\Settings\\\\Controller\\\\SettingsPageController->getAdmin('additional')\\
	#10 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n
	#11 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\SettingsPageController), 'getAdmin')\\n
	#12 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\SettingsPageController), 'getAdmin')\\n
	#13 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('SettingsPageCon...', 'getAdmin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n
	#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\
	n#15 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n
	#16 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/base.php(918): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n
	#17 \\\/srv\\\/www\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n
	#18 {m
</pre>

#### Web server error log
None

2017/06/02 13:27:52 [error] 3519#3519: *102 open() "/srv/www/favicon.ico" failed (2: No such file or directory), client: 87.138.204.124, server: lancelot.netknights.it, request: "GET /favicon.ico HTTP/1.1", host: "lancelot.netknights.it"

#### ownCloud log (data/owncloud.log)

<pre>
{"reqId":"TtQITesaFc8mNznmBafe","level":3,"time":"2017-06-02T11:22:20+00:00","remoteAddr":"87.138.204.124","user":"cornelius","app":"PHP","method":"GET","url":"\/owncloud\/settings\/admin?sectionid=additional","message":"Undefined index: urlGenerator at \/srv\/www\/owncloud\/apps\/configreport\/templates\/settings\/admin.php#31"}
{"reqId":"TtQITesaFc8mNznmBafe","level":3,"time":"2017-06-02T11:22:20+00:00","remoteAddr":"87.138.204.124","user":"cornelius","app":"index","method":"GET","url":"\/owncloud\/settings\/admin?sectionid=additional","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function imagePath() on null\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/Template\\\/Base.php(196): include()\\n#1 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/Template\\\/Base.php(171): OC\\\\Template\\\\Base->load('\\\/srv\\\/www\\\/ownclo...', NULL)\\n#2 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#3 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/configreport\\\/settings\\\/admin.php(34): OC_Template->fetchPage()\\n#4 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(757): include('\\\/srv\\\/www\\\/ownclo...')\\n#5 \\\/srv\\\/www\\\/owncloud\\\/settings\\\/Panels\\\/Helper.php(35): OC_App::getForms('admin')\\n#6 \\\/srv\\\/www\\\/owncloud\\\/settings\\\/Panels\\\/Admin\\\/Legacy.php(45): OC\\\\Settings\\\\Panels\\\\Helper->getAdminForms()\\n#7 \\\/srv\\\/www\\\/owncloud\\\/settings\\\/Controller\\\/SettingsPageController.php(142): OC\\\\Settings\\\\Panels\\\\Admin\\\\Legacy->getPanel()\\n#8 \\\/srv\\\/www\\\/owncloud\\\/settings\\\/Controller\\\/SettingsPageController.php(104): OC\\\\Settings\\\\Controller\\\\SettingsPageController->getPanelsData(Array)\\n#9 [internal function]: OC\\\\Settings\\\\Controller\\\\SettingsPageController->getAdmin('additional')\\n#10 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\SettingsPageController), 'getAdmin')\\n#12 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\SettingsPageController), 'getAdmin')\\n#13 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('SettingsPageCon...', 'getAdmin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/base.php(918): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#17 \\\/srv\\\/www\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/srv\\\/www\\\/owncloud\\\/apps\\\/configreport\\\/templates\\\/settings\\\/admin.php\",\"Line\":31}"}
</pre>

**Comment by cornelinux** [comment]
I removed the complete program directory and used a clean unzip of 10.0.2. Then I copied the old ` ``config/config.php`` and it worked out well.

I still have the broken directory, if you need any information.

**Comment by PVince81** [comment]
seems related to the "configreport" app ? can you try disabling it ?

cc @sharidas @phisch

**Comment by sharidas** [comment]
Below are the steps followed:
```
sujith@sujith-Inspiron-5567 ~/test/enterprise $ tar jxf ~/Downloads/owncloud-enterprise-complete-9.1.4.tar.bz2 
sujith@sujith-Inspiron-5567 ~/test/enterprise $ mv owncloud/* .
sujith@sujith-Inspiron-5567 ~/test/enterprise $ rm -fr owncloud/
```
Logged in as admin from UI. And then followed some steps on the the console, logged here:

```
sujith@sujith-Inspiron-5567 ~/test/enterprise $ php occ maintenance:mode --on
Cannot load Xdebug - it was already loaded
Maintenance mode enabled
sujith@sujith-Inspiron-5567 ~/test/enterprise $
```
Stop Apache web server
```
sujith-Inspiron-5567 sujith # /etc/init.d/apache2 stop; 
[ ok ] Stopping apache2 (via systemctl): apache2.service.
sujith-Inspiron-5567 sujith #
```
Continue...
```
sujith@sujith-Inspiron-5567 ~/test/enterprise $ cd ..
sujith@sujith-Inspiron-5567 ~/test $ mv enterprise enterprise-old
sujith@sujith-Inspiron-5567 ~/test $ mkdir enterprise
enterprise_old/  enterprise-old/  enterprise_work/ 
sujith@sujith-Inspiron-5567 ~/test $ mkdir enterprise
sujith@sujith-Inspiron-5567 ~/test $ cd enterprise
sujith@sujith-Inspiron-5567 ~/test/enterprise $ ls
sujith@sujith-Inspiron-5567 ~/test/enterprise $ tar jxf ~/Downloads/owncloud-enterprise-complete-10.0.2.tar.bz2 
sujith@sujith-Inspiron-5567 ~/test/enterprise $ mv owncloud/* .
sujith@sujith-Inspiron-5567 ~/test/enterprise $ rm -fr owncloud/
sujith@sujith-Inspiron-5567 ~/test/enterprise $ cp -fa ../enterprise-old/config/config.php config/
sujith@sujith-Inspiron-5567 ~/test/enterprise $ cp -fa ../enterprise-old/data .
```
Start Apache web server
```
sujith-Inspiron-5567 sujith # /etc/init.d/apache2 stop; sleep 2; /etc/init.d/apache2 start
[ ok ] Stopping apache2 (via systemctl): apache2.service.
[ ok ] Starting apache2 (via systemctl): apache2.service.
sujith-Inspiron-5567 sujith #
```

Continue ...

```
sujith@sujith-Inspiron-5567 ~/test/enterprise $ php occ upgrade
Cannot load Xdebug - it was already loaded
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 0.8.2
Updating <files_texteditor> ...
Updated <files_texteditor> to 2.2
Updating <gallery> ...
Updated <gallery> to 16.0.2
Updating <activity> ...
Updated <activity> to 2.3.4
Updating <dav> ...
Updated <dav> to 0.2.9
Updating <files_external> ...
Updated <files_external> to 0.7.0
Updating <windows_network_drive> ...
Updated <windows_network_drive> to 0.6.0
Drop old database tables

 Done
 28/28 [============================] 100%
Fix permissions so avatars can be stored again
 Done
 2/2 [============================] 100%
Move user avatars outside the homes to the new location
 Done
 1/1 [============================] 100%
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Reset log level
sujith@sujith-Inspiron-5567 ~/test/enterprise $ php occ maintenance:mode --off
Cannot load Xdebug - it was already loaded
ownCloud is in maintenance mode - no app have been loaded

Maintenance mode disabled
sujith@sujith-Inspiron-5567 ~/test/enterprise $ ./occ app:list
Cannot load Xdebug - it was already loaded
Enabled:
  - activity: 2.3.4
  - admin_audit: true
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - enterprise_key: true
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firewall: 2.4.0
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - templateeditor: 0.1
  - theme-enterprise: 1.0.0
  - updatenotification: 0.2.1
  - windows_network_drive: 0.6.0
  - workflow: 0.2.3
Disabled:
  - announcementcenter
  - encryption
  - external
  - files_antivirus
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - theme-example
  - user_external
  - user_shibboleth
sujith@sujith-Inspiron-5567 ~/test/enterprise $
```
Here is the configreport: 
[config_report_20170621.txt](https://github.com/owncloud/core/files/1090583/config_report_20170621.txt)

Here is my owncloud.log:
```
sujith@sujith-Inspiron-5567 ~/test/enterprise $ cat  data/owncloud.log 
{"reqId":"C+T+gFtkgYsSm1BsDv1b","remoteAddr":"127.0.0.1","app":"PHP","message":"file_get_contents(\/home\/sujith\/test\/enterprise\/.htaccess): failed to open stream: No such file or directory at \/home\/sujith\/test\/enterprise\/lib\/private\/Setup.php#436","level":3,"time":"2017-06-21T06:25:42+00:00","method":"POST","url":"\/enterprise\/index.php","user":"--"}
{"reqId":"C+T+gFtkgYsSm1BsDv1b","remoteAddr":"127.0.0.1","app":"PHP","message":"copy(\/home\/sujith\/test\/enterprise\/.user.ini): failed to open stream: No such file or directory at \/home\/sujith\/test\/enterprise\/lib\/private\/IntegrityCheck\/Checker.php#194","level":3,"time":"2017-06-21T06:25:43+00:00","method":"POST","url":"\/enterprise\/index.php","user":"admin"}
{"reqId":"C+T+gFtkgYsSm1BsDv1b","remoteAddr":"127.0.0.1","app":"files","message":"Can't write upload limit to \/tmp\/oc_tmp_ZZRBhH-folder\/.user.ini. Please check the file permissions","level":2,"time":"2017-06-21T06:25:43+00:00","method":"POST","url":"\/enterprise\/index.php","user":"admin"}
{"reqId":"Ne4gQy4xMJT2kxsD3xyy","level":0,"time":"2017-06-21T06:28:42+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"starting upgrade from 9.1.4.2 to 10.0.2.1"}
{"reqId":"Ne4gQy4xMJT2kxsD3xyy","level":3,"time":"2017-06-21T06:28:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"file_get_contents(\/home\/sujith\/test\/enterprise\/.htaccess): failed to open stream: No such file or directory at \/home\/sujith\/test\/enterprise\/lib\/private\/Setup.php#415"}
{"reqId":"A1BTDXqgq5JZzmTtMZtI","level":3,"time":"2017-06-21T06:28:57+00:00","remoteAddr":"127.0.0.1","user":"--","app":"index","method":"GET","url":"\/enterprise\/index.php\/core\/js\/oc.js?v=a74b2cd9223df8733f0957d76a6df8c4","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM `oc_accounts` WHERE `lower_user_id` = :dcValue1' with params [\\\"\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'enterprisetest.oc_accounts' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM `...', Array)\\n#2 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(252): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(285): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('SELECT * FROM `...', Array, NULL, NULL)\\n#4 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(379): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#5 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/User\\\/AccountMapper.php(124): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array)\\n#6 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/User\\\/Manager.php(158): OC\\\\User\\\\AccountMapper->getByUid(false)\\n#7 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Group\\\/Manager.php(472): OC\\\\User\\\\Manager->get(false)\\n#8 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/legacy\\\/user.php(333): OC\\\\Group\\\\Manager->inGroup(false, 'admin')\\n#9 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/core\\\/js\\\/config.php(75): OC_User::isAdminUser(false)\\n#10 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Route\\\/Route.php(155) : runtime-created function(1): require_once('\\\/home\\\/sujith\\\/te...')\\n#11 [internal function]: __lambda_func()\\n#12 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func('\\\\x00lambda_17', Array)\\n#13 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/base.php(918): OC\\\\Route\\\\Router->match('\\\/core\\\/js\\\/oc.js')\\n#14 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/index.php(49): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}"}
{"reqId":"Ne4gQy4xMJT2kxsD3xyy","level":1,"time":"2017-06-21T06:29:32+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Insert new users ..."}
{"reqId":"Ne4gQy4xMJT2kxsD3xyy","level":1,"time":"2017-06-21T06:29:32+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Enable external storage: yes"}
{"reqId":"Ne4gQy4xMJT2kxsD3xyy","level":3,"time":"2017-06-21T06:29:35+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"copy(\/home\/sujith\/test\/enterprise\/.user.ini): failed to open stream: No such file or directory at \/home\/sujith\/test\/enterprise\/lib\/private\/IntegrityCheck\/Checker.php#193"}
{"reqId":"Ne4gQy4xMJT2kxsD3xyy","level":2,"time":"2017-06-21T06:29:35+00:00","remoteAddr":"","user":"--","app":"files","method":"--","url":"--","message":"Can't write upload limit to \/tmp\/oc_tmp_gsHiOU-folder\/.user.ini. Please check the file permissions"}
sujith@sujith-Inspiron-5567 ~/test/enterprise $
```
Not able to reproduce the error. Am I missing something here?

**Comment by fbassas** [comment]
I have the same use updating  from 9.1.6 to 10.0.3 in  a server with ubuntu 16.04 using packages.
After a "php occ upgrade" which seemed fine, an still in maintenance mode, I could execute "php occ" commands. After a "php occ maintenance:mode --off", all the following "php occ" commands give the same errors:
  $ php occ status
An unhandled exception has been thrown:
OCP\AppFramework\QueryException: Could not resolve CardDavBackend! Class CardDavBackend does not exist in /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php:98
Stack trace:
#0 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(113): OC\AppFramework\Utility\SimpleContainer->resolve('CardDavBackend')
#1 /var/www/owncloud/apps/dav/appinfo/register_command.php(36): OC\AppFramework\Utility\SimpleContainer->query('CardDavBackend')
#2 /var/www/owncloud/lib/private/Console/Application.php(114): require('/var/www/ownclo...')
#3 /var/www/owncloud/console.php(105): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')

**Comment by fbassas** [comment]
Here is my upgrade session for your revision. I have done it in a test environment and I can reproduce it if it is necessary
[owncloud_9_to_10_upgrade.docx](https://github.com/owncloud/core/files/1462113/owncloud_9_to_10_upgrade.docx)

**Comment by fbassas** [comment]
I opened #29544 because last comment on this was July 13 th
So I didn't know if this issue had continuity. Sorry for the inconveniences.

**Comment by fbassas** [comment]
I have done a test using owncloud 10.0.3 installation file instead of deb package, and all goes fine. So I can confirm what @sharidas did with 10.0.2 also works with 10.0.3
I have done this on a test environment. I am not very confident about installing it on production. I am not sure what will happen in future updates.

**Comment by PVince81** [comment]
Was any memcache or APCU involved ? Maybe the old PHP code was still in memory and didn't get cleared.

**Comment by kdslkdsaldsal** [comment]
I see a configured redis for memory caching at the setup of @fbassas but no memory cache configured for @cornelinux

**Comment by kdslkdsaldsal** [comment]
As pointed out by @fjavimartin in https://github.com/owncloud/core/issues/29544#issuecomment-345999981 this could be an issue with a wrong done upgrade (e.g. leaving old files behind):

> Hi, i have same issue and the way to solve it has been very easy: 
> 
> - Download Owncloud 10.0.3 version.
> - Descompress on a new folder.
> - Copy your config/config.php file to new installation config folder (set correct permission).
> - Config new installation folder on your web server domain config.
> - Restart WebServer.
> 
> This issue could be for an old library not present in 10.0.3 version. That's all.

And something similar (old code still in place) could also happen with PHP caching when using APCu/Opcache/Redis/Memcached as pointed out in https://github.com/owncloud/core/issues/28068#issuecomment-344248376

**Comment by fbassas** [comment]
I've just tried the new 10.0.4 and the issue persists.

**Comment by fbassas** [comment]
I'm sorry if it's obvious, but if I delete apps directory content before making package update, it works as expected.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by pquerner** [comment]
After upgrading from 9.1.6.2 to 10.0.4 I have the same issue.
I could find this in the owncloud.log file:

`
{"reqId":"5957EFChtxxxxx","level":0,"time":"2018-01-22T09:59:01+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin?sectionid=additional","message":"Undefined index: share_name at \/var\/www\/vhosts\/xxxxx\/10.0.4_test2\/lib\/private\/Share20\/DefaultShareProvider.php#1002"}
`

**Comment by PVince81** [comment]
I see no mention of "share_name" in this issue so not sure if it's the exact same issue. Maybe the same symptoms ?

@pquerner can you check if the column oc_share.name exists in your database ? If missing, it could be this issue https://github.com/owncloud/core/issues/28285

**Comment by pquerner** [comment]
@PVince81 same symptoms indeed. Still I see this getting logged here, so I thought it would need reporting.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by PVince81** [comment]
Please reopen if still happening with 10.0.7

**Comment by lungati** [comment]
Yes still happening in owncloud:10.0.7-fpm

**Comment by butonic** [comment]
@lungati @pquerner @fbassas @cornelinux  how did you upgrade? I saw this exception when the tarball was extracted over the existing code. using a fresh untarred source with the config copied over got rid of it.

**Comment by pquerner** [comment]
I extracted the tarball to a new empty directory and copied manually the configration data to the config.php.

**Comment by coreyman** [comment]
Had the same issue going from 9.1.8 to 10.0.8
I had to remove the entire directory (saving my /data and /config) and untar a new one.
Originally I used rsync to put the new files over the old ones.
