### ISSUE TITLE
can't disable app with occ command

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#28085]
### Steps to reproduce
1. run occ comand: sudo -u www-data php occ app:disable files_external
2.
3.

### Expected behaviour

files_external disabled
### Actual behaviour

files_external can't be disabled.
### Server configuration
**Operating system**:
ubuntu 16.04
**Web server:**
apache2
**Database:**
mysql
**PHP version:**
7
**ownCloud version:** (see ownCloud admin page)
10.0.2
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
owncloud.org

```
**The content of config/config.php:**
<?php
$CONFIG = array (
  'filelocking.enabled' => true,
  'memcache.locking' => '\OC\Memcache\Redis',
  'redis' => array(
                   'host' => 'localhost',
                   'port' => 6379,
                   'timeout' => 0.0,
                  ),
  'memcache.local' => 'OC\Memcache\APCu',
  'passwordsalt' => 'Bs6CIS8Xt2BMyU10dxWY74pOhffvgi',
  'secret' => 'HTwmjbQNwbLz74WrPFcl72NU61vG/APBriU3lqEWjCUSGpBN',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '10.0.2.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'admin',
  'dbpassword' => 'password',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'ocdgiwkoc4qu',
);

```

```

**List of activated apps:**
root@oc10:/var/www/owncloud# sudo -u www-data php occ config:list system
{
    "system": {
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "memcache.local": "OC\\Memcache\\APCu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "10.0.2.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ocdgiwkoc4qu"
    }
}

```

```

root@oc10:/var/www/owncloud# sudo -u www-data php occ app:list
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
firefox
**Operating system:**
ubuntu
#### ownCloud log (data/owncloud.log)
```

root@oc10:/var/www/owncloud/data# more owncloud.log 

{"reqId":"qDsDn6FcuGLiK3sYQfnp","level":3,"time":"2017-06-03T20:39:10+00:00","remoteAddr":"
","user":"--","app":"mysql.setup","method":"--","url":"--","message":

"Specific user creation failed: An exception occurred while executing 
'SELECT user FROM mysql.user WHERE user=?' 
with params [\"oc_admin\"]:\n\nSQLSTATE[42000]: 

Syntax error or access violation: 1142 SELECT command denied to 
user 'admin'@'localhost' for table 'user'"}


{"reqId":"c7f6KBjzstlbk9o1ybpz","level":3,"time":"2017-06-03T20:50:36+00:00",
"remoteAddr":"172.17.0.1","user":"--","app":"index","method":"GET","url":"\/owncloud\/index.php\/settings\/admin?sectionid=general","message":

"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCMemcacheAPCu' not found\",

\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Server.php(381): 
OC\\\\Memcache\\\\Factory->__construct('5d0de91ce88824c...', Object(OC\\\\Log), 'OCMemcacheAPCu', 'OCMemcacheAPCu', NULL)\\
n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple
\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\
n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(111
): Pimple\\\\Container->offsetGet('MemCacheFactory')\\
n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): 
OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('MemCache
Factory')\\
n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Server.php(1092): OC\\\\ServerContainer->query('MemCacheFactory')\\
n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(821): OC\\\\Server->getMemCacheFactory()\\
n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(560): OC::registerAutoloaderCache()\\
n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1003): OC::init()\\
n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(47): require_once('\\\/var\\\/www\\\/ownclo...')\\
n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Factory.php\",\"Line\":85}"}
```

![apps](https://cloud.githubusercontent.com/assets/24212810/26823995/f48b2e78-4aaf-11e7-8ad4-5ef258a1dd91.png)

**Comment by kdslkdsaldsal** [comment]
Look like its expected that you can't disable files_external: https://github.com/owncloud/core/pull/27051

**Comment by voroyam** [comment]
So the documentation should be adjusted?
