### ISSUE TITLE
Deleting a 250 char file does not move it to the trash but throws an exception

### ISSUE THREAD

**Issue by butonic** [owncloud/core#28095]
# Expected behavior
1. Create a file like `5 250 char dir name A0FB5FD8AED822D948D72E5080393378ABC35DA854C6347620EF55B6D8826C762F52C4404A70AAF08C26E8D6493A097FEB86820A4BF524F7692A6D0AA0B384B7B4EC012D91B3075D542325B98704246476D09B2387CF3CC5CF926177D27CCBA41899416F2519E30C3BBF39F0A54E310B9AC3D7`
2. delete it
3. it should be in the trashbin

# Actual behavior
```json
{
  "reqId":"WbYaa6m5nxg6ZjVWSYPN",
  "level":3,
  "time":"2017-06-07T08:24:29+00:00",
  "remoteAddr":"127.0.0.1",
  "user":"admin",
  "app":"PHP",
  "method":"DELETE",
  "url":"\/oc\/core\/remote.php\/webdav\/5%20250%20char%20dir%20name%20A0FB5FD8AED822D948D72E5080393378ABC35DA854C6347620EF55B6D8826C762F52C4404A70AAF08C26E8D6493A097FEB86820A4BF524F7692A6D0AA0B384B7B4EC012D91B3075D542325B98704246476D09B2387CF3CC5CF926177D27CCBA41899416F2519E30C3BBF39F0A54E310B9AC3D7",
  "message":"rename(\/home\/jfd\/www\/core\/data\/admin\/files\/5 250 char dir name A0FB5FD8AED822D948D72E5080393378ABC35DA854C6347620EF55B6D8826C762F52C4404A70AAF08C26E8D6493A097FEB86820A4BF524F7692A6D0AA0B384B7B4EC012D91B3075D542325B98704246476D09B2387CF3CC5CF926177D27CCBA41899416F2519E30C3BBF39F0A54E310B9AC3D7,\/home\/jfd\/www\/core\/data\/admin\/files_trashbin\/files\/5 250 char dir name A0FB5FD8AED822D948D72E5080393378ABC35DA854C6347620EF55B6D8826C762F52C4404A70AAF08C26E8D6493A097FEB86820A4BF524F7692A6D0AA0B384B7B4EC012D91B3075D542325B98704246476D09B2387CF3CC5CF926177D27CCBA41899416F2519E30C3BBF39F0A54E310B9AC3D7.d1496823869): File name too long at \/home\/jfd\/www\/core\/lib\/private\/Files\/Storage\/Local.php#264"
}
```

Appending a timestamp is such a bad idea. we could shrink the max allowed filename size to 255-12 chars ... or we add a flag to the filecache. I personally would go with the latter because then we don't need to move the files on disk. they can be moved in a background job async if we really want to move them away. For objectstorage it would make little difference since the metadata is mandatory anyway.

**Comment by phil-davis** [comment]
Similarly for renaming:
1) Start with an ordinary file name a.txt
2) Rename the file to abcdefghij0123456789etc.txt (with a name that is up around the 240-255 chars). That works.
3) Try to rename the file again back to a short name like b.txt. The webUI reports "cannot rename file". 

You can also just create the file directly with the long name (combining steps (1) and (2) together) then (3) has the same issue. I guess the rename does some similar thing with trying remember old names/versions of the file???

And there could be plenty more variations of doing things with files with long names approaching the limit.

**Comment by butonic** [comment]
hm, yes files_versions also appends a timestamp iirc

**Comment by butonic** [comment]
another length related exception occured when logging in a user for the first time that had long filenames in his files folder:
```json
{
  "reqId":"X1KYf5crl9U2dufyiucU",
  "level":0,
  "time":"2017-06-07T12:12:40+00:00",
  "remoteAddr":"127.0.0.1",
  "user":"admin",
  "app":"core",
  "method":"POST",
  "url":"\/oc\/core\/index.php\/login",
  "message":"Exception while scanning file \"files_trashbin\/files\/0 240 char dir name C890A33200E8370E2887C191893354D7BB28A15701F6B284F0023244BCD593BE3B3C1BED2DBA71801F9E4A3668F1EA4867D2A5FE6F37427915C0A23EB4492E122C688F24D55C2EA4D92A23AC79BAC538726FB7719C51021BF3A3AFF5DF1E856C39796F94ED4D1BA860B6E6A6C050.d1496830924\": An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`checksum`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\"1\", \"2\", 1496825324, -1, \"5937edb8b3fc1\", 1496825324, 31, \"\", 19, \"081ef3d7dbf66d0898ec3fbbf5356453\", \"files_trashbin\\\/files\\\/0 240 char dir name C890A33200E8370E2887C191893354D7BB28A15701F6B284F0023244BCD593BE3B3C1BED2DBA71801F9E4A3668F1EA4867D2A5FE6F37427915C0A23EB4492E122C688F24D55C2EA4D92A23AC79BAC538726FB7719C51021BF3A3AFF5DF1E856C39796F94ED4D1BA860B6E6A6C050.d1496830924\", \"0 240 char dir name C890A33200E8370E2887C191893354D7BB28A15701F6B284F0023244BCD593BE3B3C1BED2DBA71801F9E4A3668F1EA4867D2A5FE6F37427915C0A23EB4492E122C688F24D55C2EA4D92A23AC79BAC538726FB7719C51021BF3A3AFF5DF1E856C39796F94ED4D1BA860B6E6A6C050.d1496830924\", 1, 1, \"081ef3d7dbf66d0898ec3fbbf5356453\"]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'name' at row 1"
}
```

**Comment by butonic** [comment]
its getting better!

```
{"reqId":"8Sq6vJPDcTcYLI71cZXv","level":4,"time":"2017-06-08T08:50:02+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"webdav","method":"DELETE","url":"\/oc\/core\/remote.php\/webdav\/4%20230%20char%20dir%20name%20084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232\/3%20230%20char%20dir%20name%20084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232\/3%20230%20char%20dir%20name%20084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232\/3%20230%20char%20dir%20name%20084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232\/3%20230%20char%20dir%20name%20084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232\/43333%20230%20char%20name%20084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_files_trash` (`id`,`timestamp`,`location`,`user`) VALUES (?,?,?,?)' with params [\\\"43333 230 char name 084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232\\\", 1496911801, \\\"4 230 char dir name 084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232\\\\\\\/3 230 char dir name 084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232\\\\\\\/3 230 char dir name 084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232\\\\\\\/3 230 char dir name 084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232\\\\\\\/3 230 char dir name 084BF77A408D03070B7CDFD21DF2AB5C23DC6EB21B9D11CE47404FF405130974CF8F3AE003DB45366DF20E4687220769B96587F8F6B81B5D1BC338BAA0D06307B856E7D8AA68875222CBE035A5C7B10184C374863A8DC2452ABD54000886FAB8EC84F7DA88C6FD7232\\\", \\\"admin\\\"]:\\n\\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'location' at row 1\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jfd\\\/www\\\/core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/jfd\\\/www\\\/core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(178): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/home\\\/jfd\\\/www\\\/core\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(69): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/home\\\/jfd\\\/www\\\/core\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(295): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/home\\\/jfd\\\/www\\\/core\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(185): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('4 230 char dir ...')\\n#5 \\\/home\\\/jfd\\\/www\\\/core\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(120): OCA\\\\Files_Trashbin\\\\Storage->doDelete('files\\\/4 230 cha...', 'unlink')\\n#6 \\\/home\\\/jfd\\\/www\\\/core\\\/apps-repos\\\/workflow\\\/lib\\\/Engine\\\/Wrapper\\\/StorageWrapper.php(366): OCA\\\\Files_Trashbin\\\\Storage->unlink('files\\\/4 230 cha...')\\n#7 \\\/home\\\/jfd\\\/www\\\/core\\\/lib\\\/private\\\/Files\\\/View.php(1123): OCA\\\\Workflow\\\\Engine\\\\Wrapper\\\\StorageWrapper->unlink('files\\\/4 230 cha...')\\n#8 \\\/home\\\/jfd\\\/www\\\/core\\\/lib\\\/private\\\/Files\\\/View.php(693): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/4 230 char dir...', Array)\\n#9 \\\/home\\\/jfd\\\/www\\\/core\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(346): OC\\\\Files\\\\View->unlink('\\\/4 230 char dir...')\\n#10 \\\/home\\\/jfd\\\/www\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#11 \\\/home\\\/jfd\\\/www\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('4 230 char dir ...')\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/home\\\/jfd\\\/www\\\/core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/home\\\/jfd\\\/www\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#15 \\\/home\\\/jfd\\\/www\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/home\\\/jfd\\\/www\\\/core\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/home\\\/jfd\\\/www\\\/core\\\/remote.php(165): require_once('\\\/home\\\/jfd\\\/www\\\/c...')\\n#18 {main}\",\"File\":\"\\\/home\\\/jfd\\\/www\\\/core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115,\"User\":\"admin\"}"}
```

**Comment by butonic** [comment]
- [ ] chunked uploads also append '-chunking-2808953334-xxx' to the filename. Limiting chunked uploads to 255(filesystem max length)-24(or more, depending on the number of chunks)

**Comment by PVince81** [comment]
Related: issues with file name lengths due to appending shit: https://github.com/owncloud/core/pull/26978

**Comment by frederik12345** [comment]
Hi, Long path tool can solve this issue . I suggest try using Long path tool . It worked for me. I hope it helps. :)

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/core/pull/39168, the implementation initially prevents uploading such files.
