### ISSUE TITLE
Upload big files debian 8 / apache 2.4

### ISSUE THREAD

**Issue by Messa1** [owncloud/core#28096]
### Steps to reproduce
1. Install OwnCloud 10.0.2.1
2. Set Up Server for big files
https://doc.owncloud.org/server/10.0/admin_manual/configuration_files/big_file_upload_configuration.html
3. Set up php.ini, .user.ini & .htaccess also try some fixes i found like 'SSLRenegBufferSize' & 'LimitRequestBody'

### Expected behaviour
Upload big files

### Actual behaviour
Get error.

### Server configuration
**Operating system**:

**Web server:**
Apache 2.4
Debian 8

**Database:**
MySQL

**PHP version:**
5.6

**/etc/apache2/sites-enabled/owncloud.conf**

```
Alias /owncloud "/var/customers/webs/owncloud/"

<Directory /var/customers/webs/owncloud/>

SSLRenegBufferSize 10486000
LimitRequestBody 2147483647

  Options +FollowSymlinks
  AllowOverride All

 <IfModule mod_dav.c>
  Dav off
 </IfModule>

 SetEnv HOME /var/customers/webs/owncloud/
 SetEnv HTTP_HOME /var/customers/webs/owncloud/

</Directory>

```

**.user.ini**

```
upload_max_filesize= 16G
post_max_size= 16G
memory_limit=1024M
mbstring.func_overload=0
always_populate_raw_post_data=-1
default_charset='UTF-8'
output_buffering=0

```

**php.ini**

{} are some placeholder my foxlor system offers

```
allow_call_time_pass_reference = Off
allow_url_fopen = On
asp_tags = Off
disable_classes =
disable_functions = curl_exec,curl_multi_exec,parse_ini_file,passthru,popen,proc_close,proc_get_status,proc_nice,proc_open,proc_terminate,shell_exec,show_source,system
display_errors = Off
display_startup_errors = Off
enable_dl = Off
error_reporting = E_ALL & ~E_NOTICE
expose_php = Off
file_uploads = On
cgi.force_redirect = 1
gpc_order = "GPC"
html_errors = Off
ignore_repeated_errors = Off
ignore_repeated_source = Off
include_path = ".:{PEAR_DIR}"
log_errors = On
log_errors_max_len = 1024
magic_quotes_gpc = Off
magic_quotes_runtime = Off
magic_quotes_sybase = Off
max_execution_time = 1800
max_input_time = 3600
memory_limit = 1024M
{OPEN_BASEDIR_C}open_basedir = "{OPEN_BASEDIR}:/dev/urandom"
output_buffering = Off
post_max_size = 16400M
precision = 14
register_argc_argv = Off
register_globals = Off
report_memleaks = On
sendmail_path = "/usr/sbin/sendmail -t -i -f {CUSTOMER_EMAIL}"
session.auto_start = 0
session.bug_compat_42 = 0
session.bug_compat_warn = 1
session.cache_expire = 180
session.cache_limiter = nocache
session.cookie_domain =
session.cookie_lifetime = 0
session.cookie_path = /
session.entropy_file = /dev/urandom
session.entropy_length = 16
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.gc_probability = 1
session.name = PHPSESSID
session.referer_check =
session.save_handler = files
session.save_path = "{TMP_DIR}"
session.serialize_handler = php
session.use_cookies = 1
session.use_trans_sid = 0
short_open_tag = On
suhosin.mail.protect = 1
suhosin.simulation = Off
track_errors = Off
upload_max_filesize = 16G
upload_tmp_dir = "{TMP_DIR}"
variables_order = "GPCS"
;mail.add_x_header = On
;mail.log = "/var/log/phpmail.log"

opcache.restrict_api = "{DOCUMENT_ROOT}"

extension = apc.so

```

**htaccess**

```
....
#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####

ErrorDocument 403 //core/templates/403.php
ErrorDocument 404 //core/templates/404.php

<IfModule mod_rewrite.c>
  RewriteEngine on
  # force ssl
  RewriteCond     %{SERVER_PORT} ^80$
  RewriteRule     ^(.*)$ https://%{SERVER_NAME}%{REQUEST_URI} [L,R]
</IfModule>

<IfModule mod_fcgid.c>
FcgidMaxRequestLen 1073741824
FcgidMaxRequestsPerProcess 100
FcgidProcessLifeTime 7200
</IfModule>


```
**ownCloud version:** (see ownCloud admin page)
10.0.2.1

**Updated from an older ownCloud or fresh install:**
fresh

**Where did you install ownCloud from:**
Manuell - Upload ZIP

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocuXXXXX69',
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXXX',
  'secret' => 'XXXXXXXXXXXXXXXXXXXX',
  'trusted_domains' => 
  array (
    0 => 'cloudservice.DOMAIN.com',
  ),
  'datadirectory' => '/var/customers/webs/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '10.0.2.1',
  'dbname' => 'DBNAME',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'DBUSER',
  'dbpassword' => 'PASSWORT',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'DEBUG' => 1,
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\OC\Memcache\APC',
  'log_rotate_size' => '104857600',
  );

```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - federatedfilesharing: true
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external

```

**php info screenshot**
![bildschirmfoto 2017-06-07 um 15 49 21](https://user-images.githubusercontent.com/3908658/26881901-22091c4a-4b99-11e7-9c4c-f55566cf59d2.png)
![bildschirmfoto 2017-06-07 um 15 49 38](https://user-images.githubusercontent.com/3908658/26881898-21c3f84a-4b99-11e7-8c67-8f15da0b2393.png)
![bildschirmfoto 2017-06-07 um 15 49 48](https://user-images.githubusercontent.com/3908658/26881897-21c3744c-4b99-11e7-8763-121285d7fbc5.png)
![bildschirmfoto 2017-06-07 um 15 50 04](https://user-images.githubusercontent.com/3908658/26881903-23489964-4b99-11e7-9506-0ced8e87e016.png)

**Are you using encryption:** 
no

### Client configuration

**Operating system:**
Windows 10 (newest Version) and OSX El Capitan (Version 2.3.2 (build 4250))

#### ownCloud log (data/owncloud.log)
```
{"reqId":"98mtXch5vroE3CQg6ljQ","level":4,"time":"2017-06-07T13:33:02+00:00","remoteAddr":"84.115.147.111","user":"Admin","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/uploads\/Admin\/460196243\/00000000","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 10000000 got 1687552\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #66)\\n#1 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/UploadFolder.php(38): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('00000000', Resource id #66)\\n#2 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Upload\\\\UploadFolder->createFile('00000000', Resource id #66)\\n#3 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('uploads\\\/Admin\\\/4...', Resource id #66, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(229): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/customers\\\/...')\\n#11 {main}\",\"File\":\"\\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":156,\"User\":\"Admin\"}"}
{"reqId":"QwukVd11nKw7XQ12SzFa","level":4,"time":"2017-06-07T13:33:02+00:00","remoteAddr":"84.115.147.111","user":"Admin","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/uploads\/Admin\/2798992615\/00000000","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 10000000 got 40960\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #66)\\n#1 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/UploadFolder.php(38): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('00000000', Resource id #66)\\n#2 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Upload\\\\UploadFolder->createFile('00000000', Resource id #66)\\n#3 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('uploads\\\/Admin\\\/2...', Resource id #66, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(229): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/customers\\\/...')\\n#11 {main}\",\"File\":\"\\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":156,\"User\":\"Admin\"}"}
{"reqId":"hEUwUfFZCNmlfRcSFwxS","level":0,"time":"2017-06-07T13:33:12+00:00","remoteAddr":"84.115.147.111","user":"Admin","app":"webdav","method":"DELETE","url":"\/remote.php\/dav\/uploads\/Admin\/1257409783","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name \\\/\\\/1257409783 could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/UploadHome.php(50): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChild('1257409783')\\n#1 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\Upload\\\\UploadHome->getChild('1257409783')\\n#2 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Schedule\\\/Plugin.php(412): Sabre\\\\DAV\\\\Tree->getNodeForPath('uploads\\\/Admin\\\/1...')\\n#3 [internal function]: Sabre\\\\CalDAV\\\\Schedule\\\\Plugin->beforeUnbind('uploads\\\/Admin\\\/1...')\\n#4 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(286): Sabre\\\\Event\\\\EventEmitter->emit('beforeUnbind', Array)\\n#6 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#9 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(229): Sabre\\\\DAV\\\\Server->exec()\\n#11 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/customers\\\/...')\\n#13 {main}\",\"File\":\"\\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":243,\"User\":\"Admin\"}"}
{"reqId":"B1w9MpNmFwC4kzWd0fY0","level":4,"time":"2017-06-07T13:34:07+00:00","remoteAddr":"84.115.147.111","user":"Admin","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/files\/Admin\/Kunde\/Card\/Feuchtraumleuchte%202017\/%20LED-Feuchtraumleuchte_card.psd“,“message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 The computed checksum does not match the one received from the client.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #66)\\n#1 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('LED-Feuch...', Resource id #66)\\n#2 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('files\\\/Admin\\\/Led...', Resource id #66, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(229): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/customers\\\/...')\\n#10 {main}\",\"File\":\"\\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":139,\"User\":\"Admin\"}"}
{"reqId":"5Hml47d20OTi5PSZ013D","level":4,"time":"2017-06-07T13:34:07+00:00","remoteAddr":"84.115.147.111","user":"Admin","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/uploads\/Admin\/460196243\/00000000","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 10000000 got 40960\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #66)\\n#1 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/UploadFolder.php(38): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('00000000', Resource id #66)\\n#2 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Upload\\\\UploadFolder->createFile('00000000', Resource id #66)\\n#3 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('uploads\\\/Admin\\\/4...', Resource id #66, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(229): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/customers\\\/...')\\n#11 {main}\",\"File\":\"\\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":156,\"User\":\"Admin\"}"}
{"reqId":"NyrU7p900N2yjesHK8ti","level":4,"time":"2017-06-07T13:34:07+00:00","remoteAddr":"84.115.147.111","user":"Admin","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/uploads\/Admin\/2798992615\/00000000","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 10000000 got 40960\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #66)\\n#1 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/UploadFolder.php(38): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('00000000', Resource id #66)\\n#2 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Upload\\\\UploadFolder->createFile('00000000', Resource id #66)\\n#3 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('uploads\\\/Admin\\\/2...', Resource id #66, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(229): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/customers\\\/webs\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/customers\\\/...')\\n#11 {main}\",\"File\":\"\\\/var\\\/customers\\\/webs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":156,\"User\":\"Admin\"}"}

```

**Comment by kdslkdsaldsal** [comment]
As you're running PHP on Apache via cgi-fcgi / php-fpm try to move either to:

1. Apache + mod_php (officially supported)
2. nginx + php-fpm (community supported)

Both are known to work and are shouldn't show such issues.

**Comment by Messa1** [comment]
Im running there some other websites to. Is there a opportunity to remove  cgi-fcgi / php-fpm for a spec. domain? vHost?

**Comment by Messa1** [comment]
I have tested the windows client upload work, i got the error only at the mac client.

**Comment by PVince81** [comment]
This mostly looks like an environment issue, not an ownCloud bug.
If the problem persists please ask for help on http://central.owncloud.org/
