### ISSUE TITLE
Shared folder over link isn't accessible for logged in Users

### ISSUE THREAD

**Issue by ptrktws** [owncloud/core#28120]
### Steps to reproduce
1. Major Upgrade from OC7 to OC9.1
2. Create a folder or use existing one
3. Share the Folder over public Link

### Expected behaviour
Logged in users should have access to the folder as guests did or the owner of the folder

### Actual behaviour
Only guests and the owner have access over the public link

### Server configuration
**Operating system**:
Debian 8
**Web server:**
Apache

**Database:**
MySQL 5.5.55-0+deb8u1

**PHP version:**
php 5.6.30+dfsg-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
owncloud 9.1.6

**Updated from an older ownCloud or fresh install:**
Updated from 7

**Where did you install ownCloud from:**
First from tar archive, no its the stable release over ownclouds own package

**Signing status (ownCloud 9.0 and above):**

https://gist.github.com/ptrktws/1d1357ba78b9442a154579565cbddace

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "oc6ca0913f04",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/od\/data",
        "dbtype": "mysql",
        "version": "9.1.6.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true, 
        "theme": " ",
        "tempdirectory": "\/ot\/tmp\/",
        "ldapIgnoreNamingRules": false,
        "log_type": "owncloud",
        "logfile": "\/ol\/log\/owncloud.log",
        "loglevel": 0,
        "logtimezone": "Europe\/Berlin",
        "logdateformat": "F d, Y H:i:s",
        "default_language": "de",
        "updatechecker": false,
        "knowledgebaseenabled": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": " ",
        "mail_smtpport": "2526",
        "mail_from_address": "no-reply.owncloud",
        "mail_domain": " ",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appstoreurl": "https:\/\/marketplace.owncloud.com\/api\/v0",
        "forcessl": true,
        "maintenance": false,
        "singleuser": false,
        "trusted_domains": [
            " "
        ],
        "trashbin_retention_obligation": "auto"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "types": "filesystem"
        },
        "admin_migrate": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "backgroundjob": {
            "lastjob": "1529238"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.4.2",
            "ocsid": "7",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "yes",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.1",
            "ocsid": "1",
            "signed": "true",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "backgroundjobs_step": "regular_tasks",
            "backgroundjobs_task": "",
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "encryption_enabled": "yes",
            "global_cache_gc_lastrun": "1460103301",
            "installedat": "1372857204.9402",
            "lastcron": "1497284239",
            "lastupdateResult": "[]",
            "lastupdatedat": "1497273302",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_ampache": "media\/remote.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_contactthumbnail": "contacts\/thumbnail.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_upload": "no",
            "shareapi_default_expire_date": "no",
            "shareapi_exclude_groups": "no",
            "shareapi_share_policy": "global"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.2.7",
            "types": "filesystem"
        },
        "documents": {
            "converter": "local",
            "enabled": "no",
            "installed_version": "0.8.3",
            "ocsid": "168711",
            "types": ""
        },
        "encryption": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "masterKeyId": "master_e8a5c060",
            "publicShareKeyId": "pubShare_031f3c6a",
            "recoveryAdminEnabled": "1",
            "recoveryKeyId": "recovery_837b310c",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "2 GB",
            "enabled": "yes",
            "installed_version": "1.5.1",
            "types": "filesystem"
        },
        "files_imageviewer": {
            "enabled": "no",
            "installed_version": "1.0"
        },
        "files_odfviewer": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "0.10.0",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "15.0.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "14.1.0",
            "ocsid": "169116",
            "types": ""
        },
        "media": {
            "enabled": "no",
            "installed_version": "0.4.3"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "core": "9.1.6",
            "enabled": "yes",
            "installed_version": "0.2.1",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_ldap": {
            "cleanUpJobOffset": "550",
            "enabled": "yes",
            "enforce_home_folder_naming_rule": "",
            "installed_version": "0.9.0",
            "s03has_memberof_filter_support": "",
            "s03home_folder_naming_rule": "",
            "s03last_jpegPhoto_lookup": "0",
            "s03ldap_agent_password": "",
            "s03ldap_attributes_for_group_search": "",
            "s03ldap_attributes_for_user_search": "",
            "s03ldap_backup_host": "",
            "s03ldap_backup_port": "",
            "s03ldap_base": "dc=",
            "s03ldap_base_groups": "dc=",
            "s03ldap_base_users": "dc=",
            "s03ldap_cache_ttl": "600",
            "s03ldap_configuration_active": "1",
            "s03ldap_display_name": "cn",
            "s03ldap_dn": "cn=",
            "s03ldap_dynamic_group_member_url": "",
            "s03ldap_email_attr": "mail",
            "s03ldap_experienced_admin": "0",
            "s03ldap_expert_username_attr": "uid",
            "s03ldap_expert_uuid_group_attr": "entryUUID",
            "s03ldap_expert_uuid_user_attr": "uid",
            "s03ldap_group_display_name": "cn",
            "s03ldap_group_filter": "(&(|(objectclass=groupOfUniqueNames)))",
            "s03ldap_group_filter_mode": "1",
            "s03ldap_group_member_assoc_attribute": "uniqueMember",
            "s03ldap_groupfilter_groups": "",
            "s03ldap_groupfilter_objectclass": "groupOfUniqueNames",
            "s03ldap_host": "",
            "s03ldap_login_filter": "(&(|(objectclass=Account))(uid=%uid))",
            "s03ldap_login_filter_mode": "1",
            "s03ldap_loginfilter_attributes": "",
            "s03ldap_loginfilter_email": "0",
            "s03ldap_loginfilter_username": "1",
            "s03ldap_nested_groups": "0",
            "s03ldap_override_main_server": "0",
            "s03ldap_paging_size": "500",
            "s03ldap_port": "389",
            "s03ldap_quota_attr": "owncloudQuota",
            "s03ldap_quota_def": "2048000000",
            "s03ldap_tls": "0",
            "s03ldap_turn_off_cert_check": "0",
            "s03ldap_user_display_name_2": "",
            "s03ldap_user_filter_mode": "1",
            "s03ldap_userfilter_groups": "",
            "s03ldap_userfilter_objectclass": "Account",
            "s03ldap_userlist_filter": "(|(objectclass=Account))",
            "s03use_memberof_to_detect_membership": "1",
            "types": "authentication"
        },
        "user_migrate": {
            "enabled": "no",
            "installed_version": "0.1"
        }
    }
}

*** removed some data about ldap server and smtp server
```

### Client configuration
**Browser:**
Tested with Chrome and Firefox

**Operating system:**
Windows 7

#### ownCloud log (data/owncloud.log)
```
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"initializing paged search for  Filter (|(objectclass=someAccount)) base Array\n(\n    [0] => uid=*ldap callup*\n)n attr Array\n(\n    [0] => \n)n limit 500 offset 0","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"readAttribute: uid=*ldap callup* found","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"initializing paged search for  Filter (|(objectclass=someAccount)) base Array\n(\n    [0] => uid=*ldap callup*\n)n attr Array\n(\n    [0] => \n)n limit 500 offset 0","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"readAttribute: uid=*ldap callup* found","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"initializing paged search for  Filter (|(objectclass=someAccount)) base Array\n(\n    [0] => uid=*ldap callup*\n)n attr Array\n(\n    [0] => \n)n limit 500 offset 0","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"readAttribute: uid=*ldap callup* found","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"initializing paged search for  Filter (|(objectclass=someAccount)) base Array\n(\n    [0] => uid=*ldap callup*\n)n attr Array\n(\n    [0] => \n)n limit 500 offset 0","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"readAttribute: uid=*ldap callup* found","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=*ldap callup*\n)n attr Array\n(\n    [0] => cn\n)n limit 500 offset 0","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"initializing paged search for  Filter (|(objectclass=someAccount)) base Array\n(\n    [0] => uid=*ldap callup*\n)n attr Array\n(\n    [0] => \n)n limit 500 offset 0","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"readAttribute: uid=*ldap callup* found","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=*ldap callup*\n)n attr Array\n(\n    [0] => primaryGroupID\n)n limit 500 offset 0","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"Requested attribute primarygroupid not found for uid=*ldap callup*","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=*ldap callup*\n)n attr Array\n(\n    [0] => \n)n limit 500 offset 0","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"MsFyaLyIJtvdbVYlGbKY","remoteAddr":"172.16.30.155","app":"user_ldap","message":"readAttribute: cn=*ldap callup* found","level":0,"time":"June 13, 2017 09:39:42","method":"GET","url":"/index.php/apps/gallery/config.public?extramediatypes=1&token=wfLjHxjRndYWcUQ","user":"--"}
{"reqId":"HUxvDppROjcO01ITwvE1","remoteAddr":"172.16.30.155","app":"webdav","message":"Exception: {"Message":"File with id "17216127" has not been found.","Exception":"OCP\Files\NotFoundException","Code":0,"Trace":"
#0 /var/www/owncloud/apps/dav/appinfo/v1/publicwebdav.php(80): OC\Files\View->getPath(17216127)
#1 /var/www/owncloud/apps/dav/lib/Connector/Sabre/ServerFactory.php(130): {closure}(Object(OCA\DAV\Connector\Sabre\Server))
#2 [internal function]: OCA\DAV\Connector\Sabre\ServerFactory->OCA\DAV\Connector\Sabre\{closure}(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#3 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)
#4 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)
#5 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#6 /var/www/owncloud/apps/dav/appinfo/v1/publicwebdav.php(90): Sabre\DAV\Server->exec()
#7 /var/www/owncloud/public.php(74): require_once('/var/www/ownclo...')
#8 {main}","File":"/var/www/owncloud/lib/private/Files/View.php","Line":1711,"User":false}","level":4,"time":"June 13, 2017 09:39:42","method":"PROPFIND","url":"/public.php/webdav/","user":"--"}

```

#### Browser log

http://abload.de/img/ocerror42upl.png

**Comment by PVince81** [comment]
So are you saying that if a logged in user logs out and opens the public link it works correctly ?

**Comment by ptrktws** [comment]
Yes, that works. It's pretty weird. I found a similar issue in #26517 and the mentioned hotfix works also for me. But im not sure this is a good solution.

**Comment by gregoryR** [comment]
Seeing this on my instance too
The error message is the same in owncloud .log

`\"Message\":\"File with id \\\"499512\\\" has not been found.\",\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Code\":0...`

Using owncloud 9.1.6 with php 5.6. Users are authenticated using ldap

**Comment by PVince81** [comment]
Are you guys able to try again with 10.0.3 ? The avatar handling there has changed and usually doesn't require setting up the user's mounts so I expect a high probability that this bug will not occur any more there.

As I cannot reproduce this issue myself I'm unable to confirm whether this is fixed.

**Comment by gregoryR** [comment]
Hi Vincent
Yes, I run `"ownCloud version": "10.0.3.3",` with `"PHP Version": "5.6.30-0+deb8u1",` and I can't reproduce this error anymore.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
