### ISSUE TITLE
Owncloud 9.1.4.2 to 9.1.6 - Error 33 interacting with memcached : A BAD KEY WAS PROVIDED\\\/CHARACTERS OUT OF RANGE

### ISSUE THREAD

**Issue by wolle27** [owncloud/core#28152]
### Steps to reproduce
1. Upgrade from Owncloud 9.1.4.2 to 9.1.6 [stable]
2. restart webserver
3. Get internal server error 
4. Try to make the workaround with the memcached sha1 -> but does not work!

**Error Message in the Browser:**
```
internal server error

The server has an internal error and could not complete your request.

Please contact the server administrator, this error should occur several times, and add the technical details below to your request.

More details can be found in the server log.

Technical details

     Remote address: 187.175.xx.xx
     Requirement identification: .....
```

In the owncloud.log is then:
```
{"reqId":"j5+xDexg13FdxeB1mLYe","remoteAddr":"187.17xx.xx","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Error 33 interacting with memcached : A BAD KEY WAS PROVIDED\\\/CHARACTERS OUT OF RANGE\",
\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Memcached.php(126): OC\\\\Memcache\\\\Memcached->verifyReturnCode()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/
Storage.php(163): OC\\\\Memcache\\\\Memcached->remove('home::Wolfgang ...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Storage.php(71): OC\\\\Files\\\\Cache\\\\Storage::unsetCache('home::Wolfgang ...')\\n#3
\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(94): OC\\\\Files\\\\Cache\\\\Storage->__construct(Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/
Storage\\\/Home.php(75): OC\\\\Files\\\\Cache\\\\Cache->__construct(Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(387): OC\\\\Files\\\\Storage\\
\\Home->getCache('', Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(387): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache('', Object(OCA
\\\\Files_Trashbin\\\\Storage))\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/UserMountCache.php(91): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache()\\n#8 [internal function]: OC\\\\Files\\\\Config
\\\\UserMountCache->OC\\\\Files\\\\Config\\\\{closure}(Object(OC\\\\Files\\\\Mount\\\\MountPoint))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/UserMountCache.php(92): array_filter(Array, Object(Closure))\\n
#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(133): OC\\\\Files\\\\Config\\\\UserMountCache->registerMounts(Object(OC\\\\User\\\\User), Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/li
b\\\/private\\\/Files\\\/Filesystem.php(446): OC\\\\Files\\\\Config\\\\MountProviderCollection->registerMounts(Object(OC\\\\User\\\\User), Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(373): OC\\
\\Files\\\\Filesystem::initMountPoints('Wolfgang Saren')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(231): OC\\\\Files\\\\Filesystem::init('Wolfgang Saren', '\\\/Wolfgang Saren...')\\n#14 \\\/var\\\/www\\\
/owncloud\\\/lib\\\/base.php(890): OC_Util::setupFS()\\n#15 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Memcached.php\",\"Line\
":221}","level":3,"time":"2017-06-18T17:15:55+00:00","method":"GET","url":"\/owncloud\/","user":"Wolfgang Saren"}
{"reqId":"LwyOujx\/Vt53Qub2IYe0","remoteAddr":"187.175.xx.xx","app":"PHP","message":"Exception: Error 33 interacting with memcached : A BAD KEY WAS PROVIDED\/CHARACTERS OUT OF RANGE at \/var\/www\/owncloud\/lib\/private\/Memcache\
/Memcached.php#221","level":3,"time":"2017-06-18T17:16:01+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"Wolfgang Saren"}
```

I have tryed this one: [ISSUE 23076](https://github.com/owncloud/core/issues/23076#issuecomment-194799114)

But that doesn´t change nothing for me.

### Server configuration
**Operating system**:
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03)
**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Feb 24 2017 18:40:28

**Database:**
mysql  Ver 15.1 Distrib 10.0.30-MariaDB, for debian-linux-gnu (x86_64)
**PHP version:**
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
9.1.6 [stable]
**Updated from an older ownCloud or fresh install:**
Updated from 9.1.4.2 to 9.1.6

**Where did you install ownCloud from:**
With the updater

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'REMOVED',
  'passwordsalt' => 'REMOVED',
  'secret' => 'REMOVED',
  'trusted_domains' =>
  array (
    0 => 'REMOVED',
    1 => 'REMOVED',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://REMOVED/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.6.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'REMOVED',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'transfer',
  'mail_domain' => 'REMOVED',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpport' => '465',
  'mail_smtphost' => 'REMOVED',
  'mail_smtpname' => 'REMOVED',
  'mail_smtppassword' => 'REMOVED',
  'memcache.local' => '\OC\Memcache\Memcached',
  'memcache.distributed' => '\OC\Memcache\Memcached',
  'memcached_servers' => array(
     array('localhost', 11211),
     ),
  'loglevel' => 0,
  'maintenance' => false,
  'updater.secret' => 'REMOVED',
);

```

#### Web server error log
empty

#### ownCloud log (data/owncloud.log)
```
{"reqId":"DhoZ70u8qu3M0+m2j115","remoteAddr":"187.175.xx.xx","app":"no app in context","message":"CSRF check failed","level":0,"time":"2017-06-18T15:22:32+00:00","method":"POST","url":"\/owncloud\/index.php\/login","user":"--"}
{"reqId":"jMiaQgAA2OwT+FIKg9dK","remoteAddr":"187.175.xx.xx","app":"cron","message":"Started background job of class : OC\\Command\\CommandJob with arguments : O:33:\"OCA\\Files_Versions\\Command\\Expire\":2:{s:43:\"\u0000OCA\\Files_Ver$
{"reqId":"jMiaQgAA2OwT+FIKg9dK","remoteAddr":"187.175.xx.xx","app":"core","message":"Error while running background job (class: OC\\Command\\CommandJob, arguments: O:33:\"OCA\\Files_Versions\\Command\\Expire\":2:{s:43:\"\u0000OCA\\Files$
{"reqId":"nPr18dancLfHprSahQ\/4","remoteAddr":"187.175.xx.xx","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Error 33 interacting with memcached : A BAD KEY WAS PROVIDED\\\/CHARACTERS OUT OF RANGE\",\"Cod$
{"reqId":"S9Mret1Y+A5V0ouC1eR3","remoteAddr":"187.175.xx.xx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Exception: Error 33 interacting with memcached : A BAD KEY WAS PROVIDED\\\/CHARACTERS OUT OF RANGE\",\"Excep$
{"reqId":"0h2xKbaPzvZj2GtLkF6G","remoteAddr":"187.175.xx.xx","app":"PHP","message":"Exception: Error 33 interacting with memcached : A BAD KEY WAS PROVIDED\/CHARACTERS OUT OF RANGE at \/var\/www\/owncloud\/lib\/private\/Memcache\/Memcac$
{"reqId":"bmCv9\/JDzzflBZTM5aTT","remoteAddr":"187.175.xx.xx","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Error 33 interacting with memcached : A BAD KEY WAS PROVIDED\\\/CHARACTERS OUT OF RANGE\",\"Cod$
{"reqId":"81lA8elgcG8wlwvq4c8R","remoteAddr":"187.175.xx.xx","app":"no app in context","message":"CSRF check failed","level":0,"time":"2017-06-18T15:22:50+00:00","method":"POST","url":"\/owncloud\/index.php\/login","user":"--"}

```

#### How the Update was going?

```
Initializing
Current version is 9.1.4.2
Online version is 9.1.6 [stable]

    Checking system
    Checking system health.
    - file permissions are ok.
    Creating a checkpoint
    Created checkpoint 9.1.4.2-594696762fa38
    Downloading
    Current version is 9.1.4.2
    Online version is 9.1.6 [stable]
    Downloaded 0% (0 of 40029101) Downloaded 100% (40029101 of 40029101)
    Updating core
    Updating apps
    Extracting source into /var/www/owncloud/data/updater-data/_oc_upgrade/9.1.6
    sh: 1: unzip: not found

    Copying the application activity
    Copying the application comments
    Copying the application configreport
    Copying the application dav
    Copying the application encryption
    Copying the application external
    Copying the application federatedfilesharing
    Copying the application federation
    Copying the application files
    Copying the application files_antivirus
    Copying the application files_external
    Copying the application files_pdfviewer
    Copying the application files_sharing
    Copying the application files_texteditor
    Copying the application files_trashbin
    Copying the application files_versions
    Copying the application files_videoplayer
    Copying the application firstrunwizard
    Copying the application gallery
    Copying the application notifications
    Copying the application provisioning_api
    Copying the application systemtags
    Copying the application templateeditor
    Copying the application updatenotification
    Copying the application user_external
    Copying the application user_ldap
    ownCloud or one of the apps require upgrade - only a limited number of commands are available
    You may use your browser or the occ upgrade command to do the upgrade
    Set log level to debug
    Turned on maintenance mode
    Checking whether the database schema can be updated (this can take a long time depending on the database size)

    [1A oc_appconfig
    0/24 [>---------------------------] 0%
    [1A oc_appconfig
    1/24 [=>--------------------------] 4%
    [1A oc_storages
    2/24 [==>-------------------------] 8%
    [1A oc_mounts
    3/24 [===>------------------------] 12%
    [1A oc_mimetypes
    4/24 [====>-----------------------] 16%
    [1A oc_filecache
    5/24 [=====>----------------------] 20%
    [1A oc_group_user
    6/24 [=======>--------------------] 25%
    [1A oc_group_admin
    7/24 [========>-------------------] 29%
    [1A oc_groups
    8/24 [=========>------------------] 33%
    [1A oc_preferences
    9/24 [==========>-----------------] 37%
    [1A oc_properties
    10/24 [===========>----------------] 41%
    [1A oc_share
    11/24 [============>---------------] 45%
    [1A oc_jobs
    12/24 [==============>-------------] 50%
    [1A oc_users
    13/24 [===============>------------] 54%
    [1A oc_authtoken
    14/24 [================>-----------] 58%
    [1A oc_vcategory
    15/24 [=================>----------] 62%
    [1A oc_vcategory_to_object
    16/24 [==================>---------] 66%
    [1A oc_systemtag
    17/24 [===================>--------] 70%
    [1A oc_systemtag_object_mapping
    18/24 [=====================>------] 75%
    [1A oc_systemtag_group
    19/24 [======================>-----] 79%
    [1A oc_privatedata
    20/24 [=======================>----] 83%
    [1A oc_file_locks
    21/24 [========================>---] 87%
    [1A oc_comments
    22/24 [=========================>--] 91%
    [1A oc_comments_read_markers
    23/24 [==========================>-] 95%
    [1A oc_credentials
    24/24 [============================] 100%
    Checked database schema update
    Checking updates of apps
    Checked database schema update for apps
    Updating database schema
    Updated database
    Drop old database tables

    [1A Starting ...
    0/28 [>---------------------------] 0%
    [1A Drop old database table: calendar_calendars
    1/28 [=>--------------------------] 3%
    [1A Drop old database table: calendar_objects
    2/28 [==>-------------------------] 7%
    [1A Drop old database table: calendar_share_calendar
    3/28 [===>------------------------] 10%
    [1A Drop old database table: calendar_share_event
    4/28 [====>-----------------------] 14%
    [1A Drop old database table: file_map
    5/28 [=====>----------------------] 17%
    [1A Drop old database table: foldersize
    6/28 [======>---------------------] 21%
    [1A Drop old database table: fscache
    7/28 [=======>--------------------] 25%
    [1A Drop old database table: gallery_sharing
    8/28 [========>-------------------] 28%
    [1A Drop old database table: locks
    9/28 [=========>------------------] 32%
    [1A Drop old database table: log
    10/28 [==========>-----------------] 35%
    [1A Drop old database table: media_albums
    11/28 [===========>----------------] 39%
    [1A Drop old database table: media_artists
    12/28 [============>---------------] 42%
    [1A Drop old database table: media_sessions
    13/28 [=============>--------------] 46%
    [1A Drop old database table: media_songs
    14/28 [==============>-------------] 50%
    [1A Drop old database table: media_users
    15/28 [===============>------------] 53%
    [1A Drop old database table: permissions
    16/28 [================>-----------] 57%
    [1A Drop old database table: pictures_images_cache
    17/28 [=================>----------] 60%
    [1A Drop old database table: principalgroups
    18/28 [==================>---------] 64%
    [1A Drop old database table: principals
    19/28 [===================>--------] 67%
    [1A Drop old database table: queuedtasks
    20/28 [====================>-------] 71%
    [1A Drop old database table: sharing
    21/28 [=====================>------] 75%
    [1A Drop old database table: clndr_calendars
    22/28 [======================>-----] 78%
    [1A Drop old database table: clndr_objects
    23/28 [=======================>----] 82%
    [1A Drop old database table: clndr_share_event
    24/28 [========================>---] 85%
    [1A Drop old database table: clndr_share_calendar
    25/28 [=========================>--] 89%
    [1A Drop old database table: clndr_repeat
    26/28 [==========================>-] 92%
    [1A Drop old database table: contacts_addressbooks
    27/28 [===========================>] 96%
    [1A Drop old database table: contacts_cards
    28/28 [============================] 100%
    Remove old (< 9.0) calendar/contact shares

    [1A Starting ...
    0/4 [>---------------------------] 0%
    [1A Starting ...
    1/4 [=======>--------------------] 25%
    [1A Starting ...
    2/4 [==============>-------------] 50%
    [1A Starting ...
    3/4 [=====================>------] 75%
    [1A Starting ...
    4/4 [============================] 100%
    Fix permissions so avatars can be stored again

    [1A Starting ...
    0/2 [>---------------------------] 0%
    [1A Starting ...
    1/2 [==============>-------------] 50%
    [1A Done
    2/2 [============================] 100%
    Starting code integrity check...
    Finished code integrity check
    Update successful
    Turned off maintenance mode
    Reset log level

    Finishing the update
    Done
    Done
    All done!

This app will only backup core files (no personal data).

Please always do a separate backup of database and personal data before updating.
```

When i turn off the memchaned it works of course, but that can`t be the solution. It seems to be a Problem with only longer names for example my own: Wolfgang Sarens ... It fails. With other oney like "Gerd" - everything is okay.

Could you please help me to figure out the problem?

Thank you so much and best regards.

**Comment by wolle27** [comment]
Hello together,

I still couldn't figure it out and need your help.
I had to deactivate the memcached, can please somebody help me figuring this out?

Thanks so much!

**Comment by PVince81** [comment]
Any idea where that long key could come from ? Is it an LDAP user with a very long name ?

**Comment by PVince81** [comment]
Any chance to get the full log ? The part you posted above has all the lines truncated so they are missing the stack trace.

**Comment by wolle27** [comment]
Hello @PVince81,

yes the names where this error appears is like "Wolfgang Saren" or the other one has 16 characters. 
Bevor didn't seem to be a problem at least there were no errors like this.

Here is the full log of the message:

`{"reqId":"j5+xDexg13FdxeB1mLYe","remoteAddr":"187.175.xx.xx","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Error 33 interacting with memcached : A BAD KEY WAS PROVIDED\\\/CHARACTERS OUT OF RANGE\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Memcached.php(126): OC\\\\Memcache\\\\Memcached->verifyReturnCode()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Storage.php(163): OC\\\\Memcache\\\\Memcached->remove('home::Wolfgang ...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Storage.php(71): OC\\\\Files\\\\Cache\\\\Storage::unsetCache('home::Wolfgang ...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(94): OC\\\\Files\\\\Cache\\\\Storage->__construct(Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Home.php(75): OC\\\\Files\\\\Cache\\\\Cache->__construct(Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(387): OC\\\\Files\\\\Storage\\\\Home->getCache('', Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(387): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache('', Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/UserMountCache.php(91): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache()\\n#8 [internal function]: OC\\\\Files\\\\Config\\\\UserMountCache->OC\\\\Files\\\\Config\\\\{closure}(Object(OC\\\\Files\\\\Mount\\\\MountPoint))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/UserMountCache.php(92): array_filter(Array, Object(Closure))\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(133): OC\\\\Files\\\\Config\\\\UserMountCache->registerMounts(Object(OC\\\\User\\\\User), Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(446): OC\\\\Files\\\\Config\\\\MountProviderCollection->registerMounts(Object(OC\\\\User\\\\User), Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(373): OC\\\\Files\\\\Filesystem::initMountPoints('Wolfgang Saren')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(231): OC\\\\Files\\\\Filesystem::init('Wolfgang Saren', '\\\/Wolfgang Saren...')\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(890): OC_Util::setupFS()\\n#15 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Memcached.php\",\"Line\":221}","level":3,"time":"2017-06-18T17:15:55+00:00","method":"GET","url":"\/owncloud\/","user":"Wolfgang Saren"}`

and 

`{"reqId":"S9Mret1Y+A5V0ouC1eR3","remoteAddr":"82.82.xx.xx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Exception: Error 33 interacting with memcached : A BAD KEY WAS PROVIDED\\\/CHARACTERS OUT OF RANGE\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(166): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php\",\"Line\":153,\"User\":\"Joerg Hertesrank\"}","level":4,"time":"2017-06-18T15:22:41+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"Joerg Hertesrank"}`

thanks for your reply.
Regards,
Wolfgang

**Comment by PVince81** [comment]
Uh oh: https://stackoverflow.com/a/5828197

@butonic we need to hash the keys then.

**Comment by PVince81** [comment]
Can't reproduce the issue with memcached server 1.4.33 and the memcached PHP module 3.0.3.

Maybe more recent memcached version allow for spaces ?

**Comment by butonic** [comment]
[The binary protocol allows using whitespace in keys](http://grokbase.com/p/danga/memcached/07cmw1yhjs/what-is-a-valid-key). See https://github.com/owncloud/core/blob/stable9.1/config/config.sample.php#L947-L968 on how to enable it.

**Comment by PVince81** [comment]
please reopen if using binary did not work
