### ISSUE TITLE
Error when upload file with Windows 10 webdav client and simfs partition

### ISSUE THREAD

**Issue by hlecorche** [owncloud/core#28203]
### Steps to reproduce
1. Use simfs partition (in owncloud server)
2. Mount webdav with Windows 10 client
3. Upload file

### Expected behaviour
Upload file with Windows 10 webdav client without error

### Actual behaviour
Error with 0kb error (See https://github.com/nextcloud/server/pull/3757)

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2.4.10 (Debian)

**Database:** MySQL

**PHP version:**  5.6.30

**ownCloud version:** 10.0.2

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.

No errors have been found.
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"ZFlITxlMQD6uulxhoDLe","level":4,"time":"2017-06-23T21:13:06+02:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"webdav","method":"LOCK","url":"\/remote.php\/webdav\/xxx.txt","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 No subsystem set a valid HTTP status code. Something must have interrupted the request without providing further detail.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#2 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#3 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":495,\"User\":\"xxx\"}"}

```

https://github.com/nextcloud/server/pull/3757 fixs the problem.

**Comment by kdslkdsaldsal** [comment]
@hlecorche Nice catch, thanks. Do you have time to test https://github.com/owncloud/core/issues/28204 ?

**Comment by hlecorche** [comment]
@kdslkdsaldsal It's works. Thanks.
