### ISSUE TITLE
Update fails for 8.0.16. on a QNAP

### ISSUE THREAD

**Issue by 151kg** [owncloud/core#28235]
### Steps to reproduce
```
1. buy a QNap TS-451+
2. install OwnCloud via the QNap App Center
3. update to 8.0.16 using the Owncloud internal Update Service
```
### Expected behaviour
```
Update to 8.0.16 should be done
```

### Actual behaviour
```
Update to 8.0.16 fails with 
"PDOException: SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in Progress"
this is reproduceable
```

### Server configuration
**Operating system**:
```
QNAP Firmware 4.3.3.0229 build 20170624 (2017/06/26)
Linux NAS 4.2.8
```
**Web server:**
```
Apache 
```
**Database:**
```
default, sqlite
```
**PHP version:**
```
5.6.30
```
**ownCloud version:** (see ownCloud admin page)
```
?
```
**Updated from an older ownCloud or fresh install:**
```
Updated from 8.0.4.2
```
**Where did you install ownCloud from:**
```
QNAP repository
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No result, I get redirected to the OwnCloud DB upgrade start page.
```

**The content of config/config.php:**
```
cat config.php
<?php
$CONFIG = array (
  'instanceid' => 'ocgadiu6himr',
  'passwordsalt' => '[Value],
  'secret' => '[Value]',
  'trusted_domains' =>
  array (
    0 => '[local IP]',
    1 => '[exteral FQDN]',
  ),
  'datadirectory' => '/share/CACHEDEV1_DATA/.qpkg/owncloud/owncloud/data',
  'overwrite.cli.url' => 'https://[IP]:[Port]/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.0.4.2',
  'installed' => true,
  'mail_from_address' => 'own',
  'mail_smtpmode' => 'php',
  'mail_domain' => '[Value]',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'ssl',
  'mail_smtphost' => '[Value]',
  'mail_smtpname' => '[Value]',
  'mail_smtppassword' => '[Value]',
  'mail_smtpport' => '[Value]',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'filesystem_check_changes' => 1,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
```

Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.
```
Not possible
```
or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
```
occ was not executeable, I set the script as executeable and got the errormessage:
"env: can't execute 'php': No such file or directory"
```

**List of activated apps:**
```
non
```

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
OCC does not run
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
```
No
```
**Are you using encryption:** yes/no
```
No
```
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
```
No
```

### Client configuration
**Browser:**
```
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
```
**Operating system:**
```
Win 10
```
#### Web server error log
```
can't find at the moment. If you rely need it, I will search
```

#### ownCloud log (data/owncloud.log)
```
 cat owncloud.log


{"reqId":"6c13b239c3091ef5f6080ee2746b9af8","remoteAddr":"[remoteIP]","app":"PHP","message":"touch(): Unable to create file \/share\/CACHEDEV1_DATA\/.qpkg\/owncloud\/owncloud\/data\/owncloud.log because No such file or directory at \/share\/CACHEDEV1_DATA\/.qpkg\/owncloud\/owncloud\/lib\/private\/log\/owncloud.php#48","level":3,"time":"2017-06-26T19:42:44+00:00"}


{"reqId":"c631a4af948ef9310ac01f5b9e0194f4","remoteAddr":"[remoteIP]","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2017-06-26T19:43:21+00:00"}


{"reqId":"6f9124b9b85128045bd5578feb5a4414","remoteAddr":"[externalIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T19:52:23+00:00"}


{"reqId":"53695ffe6918677b16610801fea09595","remoteAddr":"[remoteIP]","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2017-06-26T19:53:25+00:00"}


{"reqId":"b65539ba9cac584711424e8658bf7de7","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T19:53:30+00:00"}


{"reqId":"a087e3a7732e7bd22b58e2358157652b","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T19:55:11+00:00"}


{"reqId":"3239e10d6e9edb9e77df6fa436e11f97","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T19:56:14+00:00"}


{"reqId":"06f10e74c3cc8fc13b7f8d47528b5a25","remoteAddr":"[externalIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T20:07:23+00:00"}


{"reqId":"09c87862d1fa877baf4d7adbd61afe37","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T20:08:08+00:00"}


{"reqId":"54f092b8b2b0d8e0f945e4725a8496e6","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T20:20:08+00:00"}


{"reqId":"2025bae4147b4aba2f0b3aa10894b850","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T20:32:08+00:00"}


{"reqId":"8677f063663625e8e219e1d13cf23f11","remoteAddr":"[externalIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T20:33:53+00:00"}


{"reqId":"6f1eb22cf6ff1c3e314276031c910b7b","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T20:38:40+00:00"}


{"reqId":"a98fc48b5a464fe50b4eba638fc25dce","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T20:39:16+00:00"}


{"reqId":"fd427f6e4d1a4c97016412e038ba5a9e","remoteAddr":"[remoteIP]","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/app.php(76): OC_App::loadApp('activity')\\n#1 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/util.php(75): OC_App::loadApps(Array)\\n#2 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/base.php(790): OC_Util::setupFS()\\n#3 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/index.php(44): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":96}","level":4,"time":"2017-06-26T20:39:32+00:00"}


{"reqId":"84b28153d6829211938838859a119a0b","remoteAddr":"[remoteIP]","app":"core","message":"starting upgrade from 8.0.4.2 to 8.0.16.3","level":0,"time":"2017-06-26T20:39:34+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=5wf\/UcXHQjok4ivZ.oeyVUPVUFy7EJ"}


{"reqId":"84b28153d6829211938838859a119a0b","remoteAddr":"[remoteIP]","app":"update","message":"Exception: {\"Message\":\"SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress\",\"Code\":\"HY000\",\"Trace\":\"#0 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1216): PDO->commit()\\n#1 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair\\\/repairlegacystorages.php(234): Doctrine\\\\DBAL\\\\Connection->commit()\\n#2 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair.php(62): OC\\\\Repair\\\\RepairLegacyStorages->run()\\n#3 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(274): OC\\\\Repair->run()\\n#4 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(174): OC\\\\Updater->doUpgrade('8.0.16.3', '8.0.4.2')\\n#5 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/core\\\/ajax\\\/update.php(64): OC\\\\Updater->upgrade()\\n#6 {main}\",\"File\":\"\\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php\",\"Line\":1216}","level":4,"time":"2017-06-26T20:39:38+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=5wf\/UcXHQjok4ivZ.oeyVUPVUFy7EJ"}


{"reqId":"8c92578285b6e60f4821640822e2d425","remoteAddr":"[remoteIP]","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2017-06-26T20:41:54+00:00"}


{"reqId":"4180642169716fdae88c96bcb5e877be","remoteAddr":"[remoteIP]","app":"core","message":"starting upgrade from 8.0.4.2 to 8.0.16.3","level":0,"time":"2017-06-26T20:42:08+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=5wf\/UcXHQjok4ivZ.oeyVUPVUFy7EJ"}


{"reqId":"4180642169716fdae88c96bcb5e877be","remoteAddr":"[remoteIP]","app":"update","message":"Exception: {\"Message\":\"SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress\",\"Code\":\"HY000\",\"Trace\":\"#0 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1216): PDO->commit()\\n#1 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair\\\/repairlegacystorages.php(234): Doctrine\\\\DBAL\\\\Connection->commit()\\n#2 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair.php(62): OC\\\\Repair\\\\RepairLegacyStorages->run()\\n#3 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(274): OC\\\\Repair->run()\\n#4 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(174): OC\\\\Updater->doUpgrade('8.0.16.3', '8.0.4.2')\\n#5 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/core\\\/ajax\\\/update.php(64): OC\\\\Updater->upgrade()\\n#6 {main}\",\"File\":\"\\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php\",\"Line\":1216}","level":4,"time":"2017-06-26T20:42:09+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=5wf\/UcXHQjok4ivZ.oeyVUPVUFy7EJ"}


{"reqId":"4180642169716fdae88c96bcb5e877be","remoteAddr":"[remoteIP]","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2017-06-26T20:42:09+00:00"}


{"reqId":"ffeb3cee32ac9d40f62c47ce76f6515b","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T20:44:08+00:00"}


{"reqId":"20ba7da92495c2eae72afca6f1f0c25f","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T20:54:38+00:00"}


{"reqId":"43393277201516710901735f6741698e","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T20:56:08+00:00"}


{"reqId":"7d84af1911fb196f31b3edeb528599eb","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T21:06:38+00:00"}


{"reqId":"a11b4c9331c190c27f6d028ddd417203","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T21:08:08+00:00"}


{"reqId":"0b7ffe407d922da5417c6300db0d1535","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T21:18:38+00:00"}


{"reqId":"8bdf17ba36732b45ffc51621f753ce42","remoteAddr":"[remoteIP]","app":"core","message":"starting upgrade from 8.0.4.2 to 8.0.16.3","level":0,"time":"2017-06-26T21:19:53+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=5wf\/UcXHQjok4ivZ.oeyVUPVUFy7EJ"}


{"reqId":"8bdf17ba36732b45ffc51621f753ce42","remoteAddr":"[remoteIP]","app":"update","message":"Exception: {\"Message\":\"SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress\",\"Code\":\"HY000\",\"Trace\":\"#0 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1216): PDO->commit()\\n#1 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair\\\/repairlegacystorages.php(234): Doctrine\\\\DBAL\\\\Connection->commit()\\n#2 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair.php(62): OC\\\\Repair\\\\RepairLegacyStorages->run()\\n#3 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(274): OC\\\\Repair->run()\\n#4 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(174): OC\\\\Updater->doUpgrade('8.0.16.3', '8.0.4.2')\\n#5 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/core\\\/ajax\\\/update.php(64): OC\\\\Updater->upgrade()\\n#6 {main}\",\"File\":\"\\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php\",\"Line\":1216}","level":4,"time":"2017-06-26T21:19:54+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=5wf\/UcXHQjok4ivZ.oeyVUPVUFy7EJ"}


{"reqId":"c9e1acf5677246958b80268954bae30b","remoteAddr":"[remoteIP]","app":"core","message":"starting upgrade from 8.0.4.2 to 8.0.16.3","level":0,"time":"2017-06-26T21:23:27+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=5wf\/UcXHQjok4ivZ.oeyVUPVUFy7EJ"}


{"reqId":"c9e1acf5677246958b80268954bae30b","remoteAddr":"[remoteIP]","app":"update","message":"Exception: {\"Message\":\"SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress\",\"Code\":\"HY000\",\"Trace\":\"#0 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1216): PDO->commit()\\n#1 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair\\\/repairlegacystorages.php(234): Doctrine\\\\DBAL\\\\Connection->commit()\\n#2 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair.php(62): OC\\\\Repair\\\\RepairLegacyStorages->run()\\n#3 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(274): OC\\\\Repair->run()\\n#4 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(174): OC\\\\Updater->doUpgrade('8.0.16.3', '8.0.4.2')\\n#5 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/core\\\/ajax\\\/update.php(64): OC\\\\Updater->upgrade()\\n#6 {main}\",\"File\":\"\\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php\",\"Line\":1216}","level":4,"time":"2017-06-26T21:23:28+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=5wf\/UcXHQjok4ivZ.oeyVUPVUFy7EJ"}


{"reqId":"2ddd117a1daf80c317c21a5be7f21dcd","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T21:30:38+00:00"}


{"reqId":"b09a646549b2a497bb176620dbcd75e9","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-26T21:42:39+00:00"}


{"reqId":"3090a87160fa0158d296690c6ec8ccd6","remoteAddr":"[remoteIP]","app":"core","message":"starting upgrade from 8.0.4.2 to 8.0.16.3","level":0,"time":"2017-06-27T15:24:51+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=03xRk2xdmivLy\/40Pmq.nfHae97JWx"}


{"reqId":"3090a87160fa0158d296690c6ec8ccd6","remoteAddr":"[remoteIP]","app":"update","message":"Exception: {\"Message\":\"SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress\",\"Code\":\"HY000\",\"Trace\":\"#0 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1216): PDO->commit()\\n#1 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair\\\/repairlegacystorages.php(234): Doctrine\\\\DBAL\\\\Connection->commit()\\n#2 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair.php(62): OC\\\\Repair\\\\RepairLegacyStorages->run()\\n#3 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(274): OC\\\\Repair->run()\\n#4 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(174): OC\\\\Updater->doUpgrade('8.0.16.3', '8.0.4.2')\\n#5 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/core\\\/ajax\\\/update.php(64): OC\\\\Updater->upgrade()\\n#6 {main}\",\"File\":\"\\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php\",\"Line\":1216}","level":4,"time":"2017-06-27T15:24:53+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=03xRk2xdmivLy\/40Pmq.nfHae97JWx"}


{"reqId":"2eb4ffde0755e4a340b1fb2884b2cb39","remoteAddr":"[remoteIP]","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-06-27T15:36:47+00:00"}
```
#### Browser log
```
n/a
```

**Comment by kdslkdsaldsal** [comment]
@151kg ownCloud 8.0 reached End-Of-Life long time ago. It doesn't make any sense to report any bugs for this old version for the simple reason that bugs won't be fixed (if its an oC bug at all).

Just install a fresh ownCloud 9.0+ and make sure you're using MySQL and you won't see such issue.

**Comment by 151kg** [comment]
Well, this is the Version QNAP gives its customers ^^
Any expirience or hints how to install a own Version on a Qnap?

**Comment by kdslkdsaldsal** [comment]
I think those questions / concerns should be directed to QNAP or a QNAP community.

**Comment by 151kg** [comment]
@kdslkdsaldsal You have a point there, I'll try my luck with them
