### ISSUE TITLE
Windows Client login fails since upgrade from 9.0.2 to 9.1.4 / 9.1.6

### ISSUE THREAD

**Issue by leobase** [owncloud/core#28245]
### Steps to reproduce
1. Upgrade from 9.0.2 to 9.1.4
2. Reboot Windows Desktop PC
3. ownCloud Desktop Client starts with asking for credentials
4. filling in credentials
5. Hit ok
6. ownCloud Client asks again for the credentials
7. Hitting OK with filled in credentials for 30 times and more, no connection
8. Remove Account from Client
9. Configure the same account again
10. At the end of configuration hitting "Connect" - Client is connected. 

In addition: If I disconnect the account after a succesful login, then I´m in the Loop again and need to delete the account and configure it again. 

### Expected behaviour
Login to ownCloud site in the client is done in background - connection is established without the need of filling in credentials.

### Actual behaviour
I will be asked for credentials in a loop. Sometimes it works if I wait for several minutes after reboot of the PC and then I need to hit "ok" only once. 

### Server configuration

Special configurations: LDAP auth. (Open LDAP) 

**Operating system:** Debian 8 Jessie

**Web server:** Apache 2.4.10-10+deb8u8

**Database:** mySQL 5.5.55-0+deb8u1

**PHP version:** 5.6.30+dfsg-0+deb8u1

**ownCloud version:** 9.1.6 stable

**Updated from an older ownCloud or fresh install:** 9.1.6 <- 9.1.4 <- 9.0.2 and before 8.x (Problem exists since upgrade from 9.0.2 -> 9.1.4)

**Where did you install ownCloud from:** ownCloud repository

**Signing status (ownCloud 9.0 and above):** Where can I check this?

```
https://gist.github.com/anonymous/d095b984151536c34e52a72124677af7
```

**The content of config/config.php:**

```
https://gist.github.com/anonymous/76853be62031b2d9073d95817b623d30
```

**List of activated apps:**
- Activity  2.3.2
- Admin Config Report  0.1.1
- Antivirus App for files  0.9.0.0
- Collaborative tags  0.3.0
- Comments  0.3.0
- Deleted files  0.9.0
- External Sites  
- First run wizard  1.1
- Gallery  15.0.0
- LDAP user and group backend  0.9.0
- Mail Template Editor  0.1
- Notifications  0.3.0
- PDF Viewer  0.8.1
- Provisioning API  0.5.0
- Share Files  0.10.0
- Text Editor  2.1
- Update notification  0.2.1
- Versions  1.3.0
- Video player  0.9.8
- Calendar  1.4.1
- Contacts  1.5.1
- Tasks  0.9.4
- Agree Disclaimer  1.0.4
- Direct Menu  0.9.2
- Files Move  0.8.2
- RainLoop  4.9
- Reader (ebook reader)  1.0.4
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP auth. (Open LDAP) 

#### LDAP configuration (delete this part if not used)
+-------------------------------+-----------------------------+
| Configuration                 |                             |
+-------------------------------+-----------------------------+
| hasMemberOfFilterSupport      |                             |
| hasPagedResultSupport         |                             |
| homeFolderNamingRule          |                             |
| lastJpegPhotoLookup           | 0                           |
| ldapAgentName                 | cn=xxx,dc=xxx,dc=xxx  |
| ldapAgentPassword             | ***                         |
| ldapAttributesForGroupSearch  |                             |
| ldapAttributesForUserSearch   | cn;sn;uid                   |
| ldapBackupHost                |                             |
| ldapBackupPort                |                             |
| ldapBase                      | dc=xxx,dc=xxx           |
| ldapBaseGroups                | ou=xxx,dc=xxx,dc=xxx |
| ldapBaseUsers                 | ou=xxx,dc=xxx,dc=xxx  |
| ldapCacheTTL                  | 600                         |
| ldapConfigurationActive       | 1                           |
| ldapDynamicGroupMemberURL     |                             |
| ldapEmailAttribute            | mail                        |
| ldapExperiencedAdmin          | 0                           |
| ldapExpertUUIDGroupAttr       |                             |
| ldapExpertUUIDUserAttr        |                             |
| ldapExpertUsernameAttr        |                             |
| ldapGroupDisplayName          | cn                          |
| ldapGroupFilter               | objectClass=posixGroup      |
| ldapGroupFilterGroups         |                             |
| ldapGroupFilterMode           | 1                           |
| ldapGroupFilterObjectclass    |                             |
| ldapGroupMemberAssocAttr      | uniqueMember                |
| ldapHost                      | xxx.xxx.xxx         |
| ldapIgnoreNamingRules         |                             |
| ldapLoginFilter               | userid=%uid                 |
| ldapLoginFilterAttributes     |                             |
| ldapLoginFilterEmail          | 1                           |
| ldapLoginFilterMode           | 0                           |
| ldapLoginFilterUsername       | 1                           |
| ldapNestedGroups              | 0                           |
| ldapOverrideMainServer        |                             |
| ldapPagingSize                | 0                           |
| ldapPort                      | 389                         |
| ldapQuotaAttribute            |                             |
| ldapQuotaDefault              |                             |
| ldapTLS                       | 0                           |
| ldapUserDisplayName           | uid                         |
| ldapUserDisplayName2          |                             |
| ldapUserFilter                | objectclass=*               |
| ldapUserFilterGroups          |                             |
| ldapUserFilterMode            | 1                           |
| ldapUserFilterObjectclass     | posixAccount                |
| ldapUuidGroupAttribute        | auto                        |
| ldapUuidUserAttribute         | auto                        |
| turnOffCertCheck              | 0                           |
| useMemberOfToDetectMembership | 1                           |
+-------------------------------+-----------------------------+
```

### Client configuration
**Browser:** Firefox, Chrome, IE

**Operating system:**
Windows 7 x64 / Windows Vista x86

#### Web server error log
```

What exactly do you need - the log contains thousends of lines?

No errors in Apache error.log 
No errors in php.log
```

#### ownCloud log (data/owncloud.log)
```
 "reqId":"WNk7EgoAAgwAAEchB8oAAAAG","remoteAddr":"87.78.93.65","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"2017-03-27T18:17:22+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7EgoAAgwAAEchB8oAAAAG","remoteAddr":"87.78.93.65","app":"core","message":"Login failed: 'ben' (Remote IP: '87.78.93.65')","level":2,"time":"2017-03-27T18:17:22+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7EgoAAgwAAEchB8oAAAAG","remoteAddr":"87.78.93.65","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 Username or password was incorrect\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-03-27T18:17:22+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7HgoAAgwAAAu8xAoAAAAC","remoteAddr":"87.78.93.65","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"2017-03-27T18:17:34+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7HgoAAgwAAAu8xAoAAAAC","remoteAddr":"87.78.93.65","app":"core","message":"Login failed: 'ben' (Remote IP: '87.78.93.65')","level":2,"time":"2017-03-27T18:17:34+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7HgoAAgwAAAu8xAoAAAAC","remoteAddr":"87.78.93.65","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 Username or password was incorrect\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-03-27T18:17:34+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7QAoAAgwAAAu@jKsAAAAE","remoteAddr":"87.78.93.65","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"2017-03-27T18:18:08+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7QAoAAgwAAAu@jKsAAAAE","remoteAddr":"87.78.93.65","app":"core","message":"Login failed: 'ben' (Remote IP: '87.78.93.65')","level":2,"time":"2017-03-27T18:18:08+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7QAoAAgwAAAu@jKsAAAAE","remoteAddr":"87.78.93.65","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 Username or password was incorrect\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-03-27T18:18:08+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7XgoAAgwAAAu9Lx8AAAAB","remoteAddr":"87.78.93.65","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"2017-03-27T18:18:38+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7XgoAAgwAAAu9Lx8AAAAB","remoteAddr":"87.78.93.65","app":"core","message":"Login failed: 'ben' (Remote IP: '87.78.93.65')","level":2,"time":"2017-03-27T18:18:38+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7XgoAAgwAAAu9Lx8AAAAB","remoteAddr":"87.78.93.65","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 Username or password was incorrect\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-03-27T18:18:38+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7XwoAAgwAADPppGoAAAAF","remoteAddr":"87.78.93.65","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"2017-03-27T18:18:39+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7XwoAAgwAADPppGoAAAAF","remoteAddr":"87.78.93.65","app":"core","message":"Login failed: 'ben' (Remote IP: '87.78.93.65')","level":2,"time":"2017-03-27T18:18:39+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"WNk7XwoAAgwAADPppGoAAAAF","remoteAddr":"87.78.93.65","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 Username or password was incorrect\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-03-27T18:18:39+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"--"}
```
```
If I delete the Account in the client and configure it again, connections works and I get this error, which is normal and can´t be solved (I tried every solution in the knowledgebase): 
{"reqId":"WNk8NwoAAgwAAEchB9AAAAAG","remoteAddr":"87.78.93.65","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-03-27T18:22:15+02:00","method":"GET","url":"\/remote.php\/webdav\/","user":"--"}
```

#### Browser log
```
It is not related to any browser
```

Additional Informations

    Web login works
    LDAP login works
    WebDAV login works
    It is no client bug (https://github.com/owncloud/client/issues/57141)
    It is not a problem with the Credential manager from Windows
    It is tested on 5 different PCs, everywhere the same problem
    It is not related to PHP-FPM
    This is, what happens on the client when it fails:
```
[quote="leobase, post:1, topic:8163"]
GET status.php
no cookies, with bad basic auth (no password)
RESPONSE
Set-Cookie:                     ocwoue...=u05lkk...; path=/; HttpOnly                     
Set-Cookie:                     oc_sessionPassphrase=YkMnI...; path=/; secure; httponly                                                   
GET status.php
with good basic auth, cookies from above
RESPONSE
no new cookies
PROPFIND
with good basic auth, cookies from above
RESPONSE
Set-Cookie:                     ocwoue...=243jgknd...; path=/; secure; HttpOnly
GET capabilities.php
with good basic auth, cookies updated
RESPONSE
Auth failed
[/quote]
```
This is the problem of the server:
```
[quote="leobase, post:1, topic:8163"]
Configuration` Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.
Login failed: 'ben' (Remote IP: ...)
Exception: {\"Message\":\"HTTP\\\/1.1 401 Username or password was incorrect\
[/quote]
```

**Comment by kdslkdsaldsal** [comment]
To clarify this was discussed in https://github.com/owncloud/client/issues/5714 as well as in https://central.owncloud.org/t/windows-client-login-fails-since-upgrade-from-9-0-2-to-9-1-4/6673 so i think it makes sense that some one of the core team is looking at this as it only happened after the upgrade.

**Comment by leobase** [comment]
And it seems to be a problem in next-cloud too:
https://help.nextcloud.com/t/ldap-ad-error-after-update-to-11-0-2/10505

**Comment by PVince81** [comment]
@jvillafanez @cdamken do these LDAP errors ring any bells ?

**Comment by leobase** [comment]
Yesterday I configured a new Mobile (Android) with the tool "folder sync" for syncing files between mobile and ownCloud. I´ve chosen "ownCloud" Version 9 in "folder sync" and no connection was possible. Then I configured the same connection with ownCloud Version 7/8 in "folder sync" and the connection could be established without problems. Maybe this helps to figure out what is going wrong.

**Comment by leobase** [comment]
As the last update here is one week ago, is there anything I can do to work around this error? Do you need something else for analysing? I have this error for months now and I want to have a working ownCloud-Sync again.

**Comment by PVince81** [comment]
Does the LDAP password maybe contain special characters and somehow something is preventing them to be sent properly ? Or did the LDAP password got lost/corrupt ? Are you able to list LDAP users in the user page ?

**Comment by PVince81** [comment]
Did you try connecting with another Webdav client like cadaver with any LDAP user ? I suspect the problem will also happen there.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
