### ISSUE TITLE
Internal server error when accessing to Security section and OAuth2 app enabled

### ISSUE THREAD

**Issue by davigonz** [owncloud/core#28335]
### Steps to reproduce
1. Enable OAuth 2 app.
2. Go to admin, settings.
2. Press in Security option in side menu.

### Expected behaviour
Security section is properly shown.

### Actual behaviour
Internal server error.

![internal_server_error](https://user-images.githubusercontent.com/15261363/27948138-e1a34528-62f8-11e7-86f9-2eefd2e9387b.png)

### Server configuration
**Web server:** Apache 2.4.18

**Database:** MySQL

**PHP version:** php7.0.18

**ownCloud version:** 10.0.2 (stable)

#### ownCloud log (data/owncloud.log)
```
{"reqId":"IAU7BOvTOjW9EXkRJzho","level":3,"time":"2017-07-07T06:51:55+00:00","remoteAddr":"90.173.169.6","user":"admin","app":"index","method":"GET","url":"\/index.php\/settings\/personal?sectionid=security","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM `oauth2_clients` WHERE `id` IN ( SELECT `client_id` FROM `oc_oauth2_authorization_codes` WHERE `user_id` = ? UNION SELECT `client_id` FROM `oc_oauth2_access_tokens` WHERE `user_id` = ? )' with params [\\\"admin\\\", \\\"admin\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_oauth2_authorization_codes' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM `...', Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(71): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(252): OC_DB_StatementWrapper->execute()\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(352): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('SELECT * FROM `...', Array, NULL, NULL)\\n#5 \\\/opt\\\/owncloud\\\/apps\\\/oauth2\\\/lib\\\/Db\\\/ClientMapper.php(108): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT * FROM `...', Array, NULL, NULL)\\n#6 \\\/opt\\\/owncloud\\\/apps\\\/oauth2\\\/lib\\\/Panels\\\/PersonalPanel.php(63): OCA\\\\OAuth2\\\\Db\\\\ClientMapper->findByUser('admin')\\n#7 \\\/opt\\\/owncloud\\\/settings\\\/Controller\\\/SettingsPageController.php(142): OCA\\\\OAuth2\\\\Panels\\\\PersonalPanel->getPanel()\\n#8 \\\/opt\\\/owncloud\\\/settings\\\/Controller\\\/SettingsPageController.php(85): OC\\\\Settings\\\\Controller\\\\SettingsPageController->getPanelsData(Array)\\n#9 [internal function]: OC\\\\Settings\\\\Controller\\\\SettingsPageController->getPersonal('security')\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\SettingsPageController), 'getPersonal')\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\SettingsPageController), 'getPersonal')\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('SettingsPageCon...', 'getPersonal', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/opt\\\/owncloud\\\/lib\\\/base.php(918): OC\\\\Route\\\\Router->match('\\\/settings\\\/perso...')\\n#17 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}"}
```

**Comment by DeepDiver1975** [comment]
the oauth app is still under development - please continue in https://github.com/owncloud/oauth2 - thx
