### ISSUE TITLE
Uploading a file in a mount point set up with a user without write permissions returns 500

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#28362]
### Steps to reproduce

1. Set up an external mount using a user with read-only permissions.
2. Upload a file to that external mounted folder.

### Expected behaviour
The upload should fail, informing the user showing a warning that you are not allowed to do that or something similar.

### Actual behaviour
There an internal server error 500.

### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.12","versionstring":"10.0.0","edition":"Enterprise","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SFTP, WND.

**Are you using encryption:** 
No

**Logs**
```
{"reqId":"XmsmvhcJkNaWjFzeZudc","level":4,"time":"2017-05-05T13:09:23+00:00","remoteAddr":"HIDDEN_IP","user":"admin","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/WND_READ_ONLY\/yeahscience.jpg","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Could not write file contents\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #83)\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('yeahscience.jpg', Resource id #83)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('WND_READ_ONLY\\\/y...', Resource id #83, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/opt\\\/owncloud\\\/remote.php(165): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#9 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":133,\"User\":\"admin\"}
```

### Client configuration

**Browser**
Chrome

cc: @jvillafanez

**Comment by PVince81** [comment]
Didn't @jvillafanez fix this with https://github.com/owncloud/core/pull/28598 ?

**Comment by jvillafanez** [comment]
I'm not sure. https://github.com/owncloud/core/pull/28598 checks if the file exists to throw a 404. This seems to be different.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by jvillafanez** [comment]
It seems the exception is thrown in https://github.com/owncloud/core/blob/2a6722494dcecf175597d524093ceeeef10d47ae/apps/dav/lib/Connector/Sabre/File.php#L158 . As the comment says, we don't know why the file can't be opened for writing.

This is handled by core, so it's expected to affect to any external storage that could present the same behaviour. In any case, I don't think we can provide a better error message in this scenario.
The only possiblity is that the backends throw a NotPermittedException if this is detected, but the basic detection mechanism will be the same: try to open the file and check the return value.

We'll need clear expectations in this regard.
