### ISSUE TITLE
Errors when concurrently deleting file with same name in different folders

### ISSUE THREAD

**Issue by fmkaiser** [owncloud/core#28512]
### Steps to reproduce
```
# Execute in synced folder on client
> mkdir foo; cd foo
> for x in {0..9}; do mkdir $x; echo $x > $x/test.txt; done
> sleep 60   # Wait for files to be synced
> for x in {0..9}; do rm $x/test.txt; done
```

### Expected behaviour
Files should be deleted / moved to trashbin on server.

### Actual behaviour
The server eventually throws an "internal server error":
```
# Client
07-27 15:36:43:694 27081 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const SyncFileItemPtr&) "foo/3/test.txt" INSTRUCTION_ERROR 6 "The item is not synced because of previous errors: Error transferring http://localhost/owncloud/remote.php/dav/files/test/foo/3/test.txt - server replied: Internal Server Error"

# Server
{"reqId":"WXnrpG0m6Awy0o67Hx80vAAAAAo","level":4,"time":"2017-07-27T13:33:24+00:00","remoteAddr":"x.x.x.x","user":"test","app":"webdav","method":"DELETE","url":"\/owncloud\/remote.php\/dav\/files\/test\/foo\/3\/test.txt","message":"Exception: {\"Message\":\"An exception occurred while executing 'UPDATE `oc_filecache` SET `storage` =  ?, `path` = ?, `path_hash` = ?, `name` = ?, `parent` =? WHERE `fileid` = ?' with params [3, \\\"files_trashbin\\\\\\\/files\\\\\\\/test.txt.d1501162404\\\", \\\"1d4ba23c260a0285e662417100793db8\\\", \\\"test.txt.d1501162404\\\", 30, 78]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-1d4ba23c260a0285e662417100793db8' for key 'fs_storage_path_hash'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_file...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(190): Doctrine\\\\DBAL\\\\Connection->executeQuery('UPDATE `oc_file...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(535): OC\\\\DB\\\\Connection->executeQuery('UPDATE `oc_file...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(474): OC\\\\Files\\\\Cache\\\\Cache->moveFromCache(Object(OC\\\\Files\\\\Cache\\\\HomeCache), 'files\\\/foo\\\/3\\\/tes...', 'files_trashbin\\\/...')\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Updater.php(196): OC\\\\Files\\\\Cache\\\\Cache->move('files\\\/foo\\\/3\\\/tes...', 'files_trashbin\\\/...')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(291): OC\\\\Files\\\\Cache\\\\Updater->renameFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/foo\\\/3\\\/tes...', 'files_trashbin\\\/...')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(185): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('foo\\\/3\\\/test.txt')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(120): OCA\\\\Files_Trashbin\\\\Storage->doDelete('files\\\/foo\\\/3\\\/tes...', 'unlink')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1123): OCA\\\\Files_Trashbin\\\\Storage->unlink('files\\\/foo\\\/3\\\/tes...')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(693): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/foo\\\/3\\\/test.txt', Array)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(346): OC\\\\Files\\\\View->unlink('\\\/foo\\\/3\\\/test.txt')\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('files\\\/test\\\/foo\\\/...')\\n#14 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(229): Sabre\\\\DAV\\\\Server->exec()\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66,\"User\":\"test\"}"}
```

At this point, filesystem and database seem to be inconsistent, leading to subsequent errors like this:
```
{"reqId":"WXnoBzDuddmSlhUzKOPidgAAAAU","level":4,"time":"2017-07-27T13:17:59+00:00","remoteAddr":"x.x.x.x","user":"test","app":"webdav","method":"GET","url":"\/owncloud\/remote.php\/dav\/files\/test\/foo\/1\/test.txt","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(229): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":319,\"User\":\"test\"}"}
{"reqId":"WXnoB@1E8Gd-hC5Uz@vpMQAAAAM","level":3,"time":"2017-07-27T13:17:59+00:00","remoteAddr":"x.x.x.x","user":"test","app":"PHP","method":"GET","url":"\/owncloud\/remote.php\/dav\/files\/test\/foo\/6\/test.txt","message":"fopen(\/var\/www\/html\/owncloud\/data\/test\/files\/foo\/6\/test.txt): failed to open stream: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Storage\/Local.php#276"}
```

### Server configuration
Tested with
1. Production system: ownCloud 9.0.8 EE with PHP 5.6.30 , MariaDB 10.0.31 (Galera cluster), Redis 3.2.3 cache & locking
2. Virgin test system: ownCloud 10.0.2 CE with PHP 7.1.7, MariaDB 5.5.52 (standalone)

### Client configuration
ownCloud Sync client 2.3.2

**Operating system:**
Linux OpenSuSE Leap 42.2 x86_64

**Comment by kdslkdsaldsal** [comment]
@fmkaiser It looks like this could be a reliable way to reproduce https://github.com/owncloud/core/issues/22563 which is known but couldn't be reproduced. 

Could you please post your gathered info / conclusion in there? Thanks
