### ISSUE TITLE
Inconsistency between OAuth2 access token and session cookie expirations

### ISSUE THREAD

**Issue by davivel** [owncloud/core#28707]
Same as https://github.com/owncloud/core/issues/28336 , but in other endpoints:

```/ocs/v1.php/cloud/capabilities```
```/ocs/v1.php/cloud/user```
```/index.php/avatar/[username]/[size_in_pixles]```

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
this is a tricky beast - requires redesign of core interfaces and implementations ...

**Comment by davivel** [comment]
@DeepDiver1975 , tested with the Android app.

```/ocs/v1.php/cloud/capabilities``` and ```/ocs/v1.php/cloud/user``` are working fine.

```/index.php/avatar/[username]/[size]``` is returning error 500.

In the logs I can see this:

```
{"reqId":"ii6upYu5P6PBn2q5J8Kw","level":3,"time":"2017-08-18T11:05:55+00:00","remoteAddr":"85.57.168.79","user":"--","app":"index","method":"GET","url":"\/index.php\/avatar\/diana\/145","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 8 passed to OC\\\\Core\\\\Controller\\\\AvatarController::__construct() must implement interface OCP\\\\Files\\\\Folder, null given, called in \\\/opt\\\/owncloud\\\/core\\\/Application.php on line 98\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/core\\\/Application.php(98): OC\\\\Core\\\\Controller\\\\AvatarController->__construct('core', Object(OC\\\\AppFramework\\\\Http\\\\Request), Object(OC\\\\AvatarManager), Object(OC\\\\Cache\\\\File), Object(OC\\\\L10N\\\\L10N), Object(OC\\\\User\\\\Manager), Object(OC\\\\User\\\\Session), NULL, Object(OC\\\\Log))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Core\\\\Application->OC\\\\Core\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(111): Pimple\\\\Container->offsetGet('AvatarControlle...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(81): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('AvatarControlle...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('AvatarControlle...', 'getAvatar', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#5 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/base.php(931): OC\\\\Route\\\\Router->match('\\\/avatar\\\/diana\\\/1...')\\n#8 \\\/opt\\\/owncloud\\\/index.php(56): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/core\\\/Controller\\\/AvatarController.php\",\"Line\":82}"}
```

**Comment by SamuAlfageme** [comment]
> `/index.php/avatar/[username]/[size]` is returning error 500.

We get & handle the same on the Desktop client when the avatar was not yet set by the user (was it in your case @davivel?)

**Comment by PVince81** [comment]
assigning to @phisch for the time being

but from reading @DeepDiver1975's comment it looks like this is a bigger topic that needs proper scheduling, no quickfix...

**Comment by PVince81** [comment]
seems there's a related WIP PR: https://github.com/owncloud/core/pull/28733

**Comment by PVince81** [comment]
Assigned to @DeepDiver1975 as he has an almost ready PR

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core/pull/28733 is merged and backported to stable10 -> close
