### ISSUE TITLE
Raised exceptions about REPORT operation when opening comments

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#28826]
### Steps to reproduce

1. Click on a file or folder row, seeing the sidebar open.
2. Open comments tab.

### Expected behaviour
No exceptions raised.

### Actual behaviour
there is an exception about REPORT operation each time the sidebar is opened.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**Cache**
DB

**ownCloud version:** (see ownCloud admin page)
(stable10)
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.0","versionstring":"10.0.3 beta","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
{"reqId":"f0CUMG7NF6LL59NbQz2k","level":4,"time":"2017-08-29T07:38:01+00:00","remoteAddr":"HIDDEN_IP","user":"admin","app":"webdav","method":"REPORT","url":"\/remote.php\/dav\/comments\/files\/22\/","message":"Exception: {\"Message\":\"Document is empty\\n on line 1, column 1\",\"Exception\":\"Sabre\\\\Xml\\\\LibXMLException\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/xml\\\/lib\\\/Element\\\/Base.php(86): Sabre\\\\Xml\\\\Reader->parseInnerTree()\\n#1 [internal function]: Sabre\\\\Xml\\\\Element\\\\Base::xmlDeserialize(Object(Sabre\\\\Xml\\\\Reader))\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/xml\\\/lib\\\/Reader.php(246): call_user_func(Array, Object(Sabre\\\\Xml\\\\Reader))\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/xml\\\/lib\\\/Reader.php(71): Sabre\\\\Xml\\\\Reader->parseCurrentElement()\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/xml\\\/lib\\\/Service.php(118): Sabre\\\\Xml\\\\Reader->parse()\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(714): Sabre\\\\Xml\\\\Service->parse('\\\"<?xml version=...', '\\\/remote.php\\\/dav...', NULL)\\n#6 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(234): Sabre\\\\DAV\\\\Server->exec()\\n#11 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#12 \\\/opt\\\/owncloud\\\/remote.php(175): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#13 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/xml\\\/lib\\\/Reader.php\",\"Line\":155,\"User\":\"admin\"}"}
```

### Client configuration

**Browser**
Chrome

**Comment by PVince81** [comment]
Cannot reproduce with 10.0.3beta tarball.

**Comment by PVince81** [comment]
mind posting a full page screenshot ? it's a quick way to see what file you selected and what tab you have selected in the sidebar

**Comment by SergioBertolinSG** [comment]
I'm using current stable10.

**Comment by SergioBertolinSG** [comment]
![report_exceptions](https://user-images.githubusercontent.com/9048796/29811019-5aef3db0-8ca2-11e7-9a87-b15f834f1930.gif)

**Comment by PVince81** [comment]
can you do some testing with system tags functionality ? I suspect that this will either affect the autocomplete box or the displaying of already set tags.

**Comment by SergioBertolinSG** [comment]
Seems related with comments, not with tags.

**Comment by SergioBertolinSG** [comment]
Actually comments are broken, they appear correctly after writing, but refreshing the web they dissapear.

**Comment by SergioBertolinSG** [comment]
Seems to be only a problem using the web ui. All comments test passed without problems.

**Comment by SergioBertolinSG** [comment]
Propfind works fine, it is just Report which fails when getting comments. 500 is answered. Some client logs:

```
Request URL:http://HIDDEN_HOST/remote.php/dav/comments/files/52/
Request Method:REPORT
Status Code:500 Internal Server Error
Remote Address:HIDDEN
Referrer Policy:no-referrer
Response Headers
view source
Cache-Control:no-store, no-cache, must-revalidate
Connection:close
Content-Length:227
Content-Security-Policy:default-src 'none';
Content-Type:application/xml; charset=utf-8
Date:Tue, 29 Aug 2017 10:50:49 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:no-cache
Server:Apache/2.4.18 (Ubuntu)
X-Content-Type-Options:nosniff
X-Download-Options:noopen
X-Frame-Options:SAMEORIGIN
X-Permitted-Cross-Domain-Policies:none
X-Robots-Tag:none
X-XSS-Protection:1; mode=block
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:es-ES,es;q=0.8,en;q=0.6
Connection:keep-alive
Content-Length:204
Content-Type:application/json
Cookie:PHPSESSID=cdue2jm4fb3dcd5qcsg279ocd2; oc_sessionPassphrase=GfcHRcbh88KzoCQ%2FwNJjbLyFDXoPAzjlw70LMerW2gUMNnYcOAwD7WvAV7xyonLCb9RqS7kz8XewDRxO0VKY1wDu9rvjKeEEL25wOPbWJkaUds7EXBsoRvlv0NT6jCTj; occiuutw7s2k=0pav6coh33vgj21uvaa2l5b4c0
Host:HIDDEN_HOST
Origin:HIDDEN_HOST
requesttoken:K3hgAlszMg0XCCxXBCgKC147OgE0GCIQBD8DfAtpem4=:qAYojjc8gkE9vARDgrPQFUdCjpdNA3K4gPmI/cC+7S4=
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
X-Requested-With:XMLHttpRequest
Request Payload
view source
<?xml version="1.0" encoding="utf-8" ?> <oc:filter-comments xmlns:D="DAV:" xmlns:oc="http://owncloud.org/ns"> <oc:limit>21</oc:limit> <oc:offset>0</oc:offset> </oc:filter-comments>
No Properties
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\Xml\LibXMLException</s:exception>
  <s:message>Document is empty
 on line 1, column 1</s:message>
</d:error>
```

**Comment by PVince81** [comment]
Likely related to my recent changes to the backbone webdav adapter...

**Comment by phil-davis** [comment]
I am getting some upload firewall tests failing with:
```
Failed asserting that 500 matches expected 403
```
but I have not tracked down just yet where the 500 internal error comes from, rather than 403.Nothing obvious in the oC log.

I also noticed https://github.com/owncloud/core/pull/28833 related to the recent CORS merging.

No ides yet if all this is related, but it looks suspicious.

**Comment by PVince81** [comment]
Regression introduced through https://github.com/owncloud/core/pull/28767

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/28836

**Comment by phil-davis** [comment]
I login and open the "sharing/details" sidebar of welcome.txt

In master before the fix the oC log has:
```
{"reqId":"xuhkeh7DQH4aILgArn3D","level":4,"time":"2017-08-29T12:56:17+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"webdav","method":"REPORT","url":"\/remote.php\/dav\/comments\/files\/9\/","message":"Exception: {\"Message\":\"Document is empty\\n on line 1, column 1\",\"Exception\":\"Sabre\\\\Xml\\\\LibXMLException\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/phil\\\/core\\\/lib\\\/composer\\\/sabre\\\/xml\\\/lib\\\/Element\\\/Base.php(86): Sabre\\\\Xml\\\\Reader->parseInnerTree()\\n#1 [internal function]: Sabre\\\\Xml\\\\Element\\\\Base::xmlDeserialize(Object(Sabre\\\\Xml\\\\Reader))\\n#2 \\\/home\\\/phil\\\/core\\\/lib\\\/composer\\\/sabre\\\/xml\\\/lib\\\/Reader.php(247): call_user_func(Array, Object(Sabre\\\\Xml\\\\Reader))\\n#3 \\\/home\\\/phil\\\/core\\\/lib\\\/composer\\\/sabre\\\/xml\\\/lib\\\/Reader.php(71): Sabre\\\\Xml\\\\Reader->parseCurrentElement()\\n#4 \\\/home\\\/phil\\\/core\\\/lib\\\/composer\\\/sabre\\\/xml\\\/lib\\\/Service.php(118): Sabre\\\\Xml\\\\Reader->parse()\\n#5 \\\/home\\\/phil\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(715): Sabre\\\\Xml\\\\Service->parse('\\\"<?xml version=...', '\\\/remote.php\\\/dav...', NULL)\\n#6 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/home\\\/phil\\\/core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/home\\\/phil\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#9 \\\/home\\\/phil\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/home\\\/phil\\\/core\\\/apps\\\/dav\\\/lib\\\/Server.php(236): Sabre\\\\DAV\\\\Server->exec()\\n#11 \\\/home\\\/phil\\\/core\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#12 \\\/home\\\/phil\\\/core\\\/remote.php(175): require_once('\\\/home\\\/phil\\\/core...')\\n#13 {main}\",\"File\":\"\\\/home\\\/phil\\\/core\\\/lib\\\/composer\\\/sabre\\\/xml\\\/lib\\\/Reader.php\",\"Line\":155,\"User\":\"admin\"}"}
```

Using the code in #28836 there is nothing coming in the oC log.

**Comment by phil-davis** [comment]
And it has fixed:
```
Failed asserting that 500 matches expected 403
```
that had started happening in some firewall tests.
