### ISSUE TITLE
UI test "create new app password" fails sometimes

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28889]
### Steps to reproduce
1. Run the UI test a few times:
```
bash tests/travis/start_behat_tests.sh --feature tests/ui/features/other/personalSecuritySettings.feature:3
```

### Expected behaviour
It should pass every time.

### Actual behaviour
Sometimes (maybe 1 in 5 for me) it fails with:
```
phil@phil-VirtualBox:~/core$ bash tests/travis/start_behat_tests.sh --feature tests/ui/features/other/personalSecuritySettings.feature:3
Running tests on 'chrome' () on 
Feature: personalSecuritySettings

  Scenario: create new app password                             # /home/phil/core/tests/ui/features/other/personalSecuritySettings.feature:3
    Given I am logged in as admin                               # FeatureContext::iAmLoggedInAsAdmin()
    And I am on the personal security settings page             # PersonalSecuritySettingsContext::iAmOnThePersonalSecuritySettingsPage()
    When I create a new App password                            # PersonalSecuritySettingsContext::iCreateANewAppPasswordForTheAppNamed()
    Then the new app should be listed in the App passwords list # PersonalSecuritySettingsContext::theAppShouldBeListedInTheAppPasswordsList()
      Behat\Testwork\Call\Exception\FatalThrowableError: Fatal error: Call to a member function getText() on null in /home/phil/core/tests/ui/features/lib/PersonalSecuritySettingsPage.php:75
      Stack trace:
      #0 /tmp/ProxyManagerGeneratedProxy__PM__PagePersonalSecuritySettingsPageGeneratedd2caffc4cff3642d7afddc3f55dded7d.php(44): Page\PersonalSecuritySettingsPage->getLinkedAppByName('gbJvCfeZ')
      #1 /home/phil/core/tests/ui/features/bootstrap/PersonalSecuritySettingsContext.php(67): ProxyManagerGeneratedProxy\__PM__\Page\PersonalSecuritySettingsPage\Generatedd2caffc4cff3642d7afddc3f55dded7d->getLinkedAppByName('gbJvCfeZ')
      #2 [internal function]: PersonalSecuritySettingsContext->theAppShouldBeListedInTheAppPasswordsList()
...
```

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
PHP dev server
**Database:**
MySQL
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
10.0.3 from git master as of now, in development VM

**Comment by phil-davis** [comment]
Backport stable10 #28894
