### ISSUE TITLE
Cannot upload a file using external oC mount instance

### ISSUE THREAD

**Issue by davitol** [owncloud/core#28929]
### Steps to reproduce

1. As admin user mount an ownCloud external Storage Mountpoint
2. Upload a file in the folder

### Expected behaviour

User can upload a file in the owncloud External Storage folder

### Actual behaviour

The file is not uploaded. A warning is shown

![screen shot 2017-09-06 at 17 42 54](https://user-images.githubusercontent.com/10596560/30121104-074eeffe-932b-11e7-992e-ab83302b3372.png)

**Note:** Tested in oC stable10 and it works fine. 
**Note2:** It can be also reproduced using the owncloud server as Ext storage via WebDAV 

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.3.0" Master Branch

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
ownCloud

**Are you using encryption:** 
No

**Logs**

Server Logs

```
{"reqId":"oMCbDc9DMda7lUWWGV9f","level":3,"time":"2017-09-06T15:45:16+00:00","remoteAddr":"85.57.168.79","user":"admin","app":"no app in context","method":"PUT","url":"\/remote.php\/webdav\/WebDAV\/Screen%20Shot%202017-09-06%20at%2010.58.48.png","message":"Exception: {\"Exception\":\"Sabre\\\\HTTP\\\\ClientHttpException\",\"Message\":\"Forbidden\",\"Code\":403,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(373): Sabre\\\\HTTP\\\\Client->send(Object(Sabre\\\\HTTP\\\\Request))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(532): Sabre\\\\DAV\\\\Client->request('MOVE', 'http:\\\/\\\/docker.o...', NULL, Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(272): OC\\\\Files\\\\Storage\\\\DAV->rename('Screen Shot 201...', 'Screen Shot 201...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/PermissionsMask.php(86): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rename('Screen Shot 201...', 'Screen Shot 201...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(272): OC\\\\Files\\\\Storage\\\\Wrapper\\\\PermissionsMask->rename('Screen Shot 201...', 'Screen Shot 201...')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(295): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rename('Screen Shot 201...', 'Screen Shot 201...')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(273): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->rename('Screen Shot 201...', 'Screen Shot 201...')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(272): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->rename('Screen Shot 201...', 'Screen Shot 201...')\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(103): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rename('Screen Shot 201...', 'Screen Shot 201...')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(566): OCA\\\\Files_Trashbin\\\\Storage->rename('Screen Shot 201...', 'Screen Shot 201...')\\n#10 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(207): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'Screen Shot 201...', 'Screen Shot 201...')\\n#11 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(162): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #50)\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('Screen Shot 201...', Resource id #50)\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('WebDAV\\\/Screen S...', Resource id #50, NULL)\\n#14 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#16 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#17 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#19 \\\/opt\\\/owncloud\\\/remote.php(175): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#20 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":160}"}
{"reqId":"oMCbDc9DMda7lUWWGV9f","level":3,"time":"2017-09-06T15:45:16+00:00","remoteAddr":"85.57.168.79","user":"admin","app":"files_external","method":"PUT","url":"\/remote.php\/webdav\/WebDAV\/Screen%20Shot%202017-09-06%20at%2010.58.48.png","message":"Forbidden"}
{"reqId":"oMCbDc9DMda7lUWWGV9f","level":4,"time":"2017-09-06T15:45:16+00:00","remoteAddr":"85.57.168.79","user":"admin","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/WebDAV\/Screen%20Shot%202017-09-06%20at%2010.58.48.png","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Failed to check file size: \",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(162): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #50)\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('Screen Shot 201...', Resource id #50)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('WebDAV\\\/Screen S...', Resource id #50, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/opt\\\/owncloud\\\/remote.php(175): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#9 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":245,\"User\":\"admin\"}"}
```

### Client configuration

**Browser**

Mozilla Firefox

**Comment by PVince81** [comment]
403 forbidden ??

**Comment by PVince81** [comment]
Uh oh, apparently we're still sending part files ?!

I'll have a look. We're supposed to disable part files when dealing with a remote OC like for federated shares.

**Comment by PVince81** [comment]
CLASS NAME MISMATCH

Ok... Will fix.

**Comment by sharidas** [comment]
@PVince81 Yah we can see part files in the destination folder or path.

**Comment by PVince81** [comment]
Wait, but this should be caught by the external storage automated tests already

**Comment by PVince81** [comment]
Ahhhh, it's not caught because the target docker used for ownCloud ext storage test is still on OC 9.1 which didn't have the part file restriction...

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/28931

**Comment by PVince81** [comment]
@davitol not sure how you tested with stable10, but in my case I was able to reproduce the issue, connecting from stable10 to a v10.0.3RC1 tarball instance. After patching with https://github.com/owncloud/core/pull/28931 the upload works. So the issue indeed exists in stable10.

**Comment by PVince81** [comment]
Uh oh, seems stable9.1 and stable9 might be affected as well: the wrong namespace is used there as well.

This means that stable9.1/stable9 instance cannot upload to a stable10 instance mounted as external storage. (this does not affect federated shares)

**Comment by PVince81** [comment]
Important note: when testing, the upload must be a Webdav PUT. In older versions the web UI did not use Webdav PUT for uploads so it might bypass the bug and part files.

**Comment by PVince81** [comment]
Indeed when connecting to 10.0.2 through external storage, it works fine. This is not normal, it should not work as part files are not allowed during PUT. This is issue A.

Nevertheless it seems that 10.0.2 was allowing it, and in 10.0.3 it stopped allowing it, but fails with 503 instead of 403. I've bisected it and uploading did work until 5761e09dd23416b97a8e59e44f5efea5fd262834 was merged (https://github.com/owncloud/core/pull/28633). This is issue B:

Issue A: OC 10 must not allow uploading part files
Issue B: "somehow" Fixes issue A.

I'll still look deeper into this as it is suspicious, in case there are other potential side effects.

**Comment by PVince81** [comment]
It turns out that part files were never properly blocked on Webdav but only in the web UI. I've reopened https://github.com/owncloud/core/issues/7496 to have a look.

I don't think we need to have a look at "issue B" because the proper blocking of part file would prevent issue B to occur in the first place (503).
