### ISSUE TITLE
Many files locked until few days while oc_file_locks table is empty

### ISSUE THREAD

**Issue by alcordier** [owncloud/core#29092]
### Steps to reproduce
1. Many files remain locked:

```
Fatal | webdav | Exception: {"Message":"HTTP\/1.1 423  \"Tri-bagages-S4\/Registre_journal_de_la_coordin\/Feuillets_d_observations\/162873_RJ_197_Visite  de chantier_220917.pdf\" is  locked","Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0   \/var\/www\/vhosts\/XXXX.fr\/cloud\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(179):  OCA\\DAV\\Connector\\Sabre\\File->delete()\n#1  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(285):  Sabre\\DAV\\Tree->delete('Tri-bagages-S4\/...')\n#2 [internal  function]:  Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request),  Object(Sabre\\HTTP\\Response))\n#3  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105):  call_user_func_array(Array, Array)\n#4  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459):  Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#5  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248):  Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request),  Object(Sabre\\HTTP\\Response))\n#6  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(61):  Sabre\\DAV\\Server->exec()\n#7  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/remote.php(164):  require_once('\/var\/www\/vhosts...')\n#8  {main}","File":"\/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":342,"User":"yyyy"} | 2017-09-22T15:42:12+00:00
Fatal | webdav | Exception: {"Message":"HTTP\/1.1 423  \"Tri-bagages-S4\/Dossier_des_Interventions_Ulte\/162873_DIUO_V2_180917.doc\"  is  locked","Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0   \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(179):  OCA\\DAV\\Connector\\Sabre\\File->delete()\n#1  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(285):  Sabre\\DAV\\Tree->delete('Tri-bagages-S4\/...')\n#2 [internal  function]:  Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request),  Object(Sabre\\HTTP\\Response))\n#3  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105):  call_user_func_array(Array, Array)\n#4  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459):  Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#5  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248):  Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request),  Object(Sabre\\HTTP\\Response))\n#6  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(61):  Sabre\\DAV\\Server->exec()\n#7  \/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/remote.php(164):  require_once('\/var\/www\/vhosts...')\n#8  {main}","File":"\/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":342,"User":"yyyy"} | 2017-09-22T15:42:12+00:00
```
At least, those files should be unlocked by cron job...

### Expected behaviour
There is no reason why files should remain locked.

### Actual behaviour
Well, I think it is clear...

### Server configuration
**Operating system**: CentOS 7.4

**Web server:** Apache 2.4

**Database:** 5.5.52-MariaDB

**PHP version:** 7.0.23

**ownCloud version:** ownCloud 9.1.6 (stable)

**Updated from an older ownCloud or fresh install:** updated from 8 one year ago

**Where did you install ownCloud from:** from official website + updates

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocqoz91sshtv",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.XXXXX.fr"
        ],
        "datadirectory": "\/var\/www\/vhosts\/XXXXX.fr\/cloud\/httpdocs\/DataLocal",
        "overwrite.cli.url": "http:\/\/cloud.XXXXX.fr\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.6.2",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "maintenance": false,
        "mail_from_address": "XXXXX",
        "mail_smtpmode": "php",
        "mail_domain": "XXXXX.fr",
        "singleuser": false
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - user_external
  - user_ldap
```

**Are you using external storage, if yes which one:**  yes : **local**

**Are you using encryption:** **no**

**Are you using an external user-backend, if yes which one:** **no**

### Client configuration
**Browser:** Firefox 55.0.3

**Operating system:** windows 10

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
```

**Comment by PVince81** [comment]
> "memcache.locking": "\\OC\\Memcache\\Redis",

You are using file locking with Redis, so it's not using the database. The cron job cleanup is only for the database table.

Redis already has a TTL support for keys and OC uses that to set a timeout value for locks, which is around an hour or so.

Now a lock should never stay for that lock. Usually a lock isn't properly cleared when an exception / error occurred during a file operation. Maybe some error happened there.

You could check owncloud.log for errors/exceptions around one hour before the entries you posted.

**Comment by alcordier** [comment]
I solved the problem by setting maintenance mode and using the following command:

```
$ redis-cli
127.0.0.1:6379> flushall
```
