### ISSUE TITLE
failed upgrade to 8.0.16

### ISSUE THREAD

**Issue by sagi7** [owncloud/core#29143]
### Steps to reproduce
1. select upgrade from the owncloud admin page of my server 
2.
3.

### Expected behaviour

The server should be upgraded to version 8.0.16

### Actual behaviour
PDOException: SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress
Unfortunately the failed sql statement is not shown 

### Server configuration
LInux on QNAP

**Web server:**
?

**Database:**
SQLITE

**PHP version:**
PHP 5.6.31 (cli) (built: Sep  1 2017 05:07:03)

**ownCloud version:** (see ownCloud admin page)
8.0.16

**Updated from an older ownCloud or fresh install:**
updated from a former 8.x version

**Where did you install ownCloud from:**
from the admin menu of qnap

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 

```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'occ5',
  'passwordsalt' => 'sla',
  'secret' => 'sssti',
  'trusted_domains' => 
  array (
    0 => 'qnap.fritz.box',
  ),
  'datadirectory' => '/share/CE_CACHEDEV1_DATA/.qpkg/owncloud/owncloud/data',
  'overwrite.cli.url' => 'http://myhost/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.0.4.2',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => true,
);

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**
Linux on QNAP

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"408be7a3f159ec69e792c7442c5e6596","remoteAddr":"192.168.53.121","app":"PHP","message":"touch(): Unable to create file \/share\/CE_CACHEDEV1_DATA\/.qpkg\/owncloud\/owncloud\/data\/owncloud.log because No such file or 
{"reqId":"9a94497b96dfccff2265e529a7a79ebe","remoteAddr":"192.168.53.121","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'al
ways_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-10-04T08:36:14+00:00"}
{"reqId":"7937ec2d3dc0c6d420cfacf0346d362f","remoteAddr":"192.168.53.121","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'al
ways_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-10-04T08:39:02+00:00"}
{"reqId":"cd117fe488876df5548640a5db7e5818","remoteAddr":"192.168.53.121","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'al
ways_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-10-04T08:39:47+00:00"}
{"reqId":"cb34eacbf6c8c8ccef322e72fa5383dc","remoteAddr":"","app":"update","message":"Exception: {\"Message\":\"SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress\",\"Code\":\"HY000\",\"Tra
ce\":\"#0 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1216): PDO->commit()\\n#1 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/ownclou
d\\\/owncloud\\\/lib\\\/private\\\/repair\\\/repairlegacystorages.php(234): Doctrine\\\\DBAL\\\\Connection->commit()\\n#2 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair.php(62): OC\\
\\Repair\\\\RepairLegacyStorages->run()\\n#3 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(274): OC\\\\Repair->run()\\n#4 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\
/owncloud\\\/lib\\\/private\\\/updater.php(174): OC\\\\Updater->doUpgrade('8.0.16.3', '8.0.4.2')\\n#5 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/core\\\/command\\\/upgrade.php(152): OC\\\\Updater->upgrad
e()\\n#6 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Command\\\/Command.php(252): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symf
ony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/S
ymfony\\\/Component\\\/Console\\\/Application.php(889): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\
\\\ConsoleOutput))\\n#8 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(193): Symfony\\\\Component\\\\Console\\\\Applicatio
n->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/share\\\/CE_CACHEDEV1_DATA\\\
/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(124): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\
\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/console.php(65): Symfony\\\\Component\\\\Console\\\\Application->run()\
\n#11 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/occ(11): require_once('\\\/share\\\/CE_CACHE...')\\n#12 {main}\",\"File\":\"\\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\
/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php\",\"Line\":1216}","level":4,"time":"2017-10-04T08:46:26+00:00","method":"--","url":"--"}
{"reqId":"54ac91d9e1d5cb8ead323fc7c7c96d88","remoteAddr":"192.168.53.121","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'al
ways_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-10-04T08:48:14+00:00"}
{"reqId":"a9ca0c11a88ac077a9e37421aef7b47b","remoteAddr":"192.168.53.121","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'al
ways_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-10-04T08:51:02+00:00"}
{"reqId":"c44739aa3625b0b5eeb3b65521460eee","remoteAddr":"","app":"update","message":"Exception: {\"Message\":\"SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress\",\"Code\":\"HY000\",\"Tra
ce\":\"#0 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1216): PDO->commit()\\n#1 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/ownclou
d\\\/owncloud\\\/lib\\\/private\\\/repair\\\/repairlegacystorages.php(234): Doctrine\\\\DBAL\\\\Connection->commit()\\n#2 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair.php(62): OC\\
\\Repair\\\\RepairLegacyStorages->run()\\n#3 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(274): OC\\\\Repair->run()\\n#4 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\
/owncloud\\\/lib\\\/private\\\/updater.php(174): OC\\\\Updater->doUpgrade('8.0.16.3', '8.0.4.2')\\n#5 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/core\\\/command\\\/upgrade.php(152): OC\\\\Updater->upgrad
e()\\n#6 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Command\\\/Command.php(252): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symf
ony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/S
ymfony\\\/Component\\\/Console\\\/Application.php(889): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\
\\\ConsoleOutput))\\n#8 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(193): Symfony\\\\Component\\\\Console\\\\Applicatio
n->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/share\\\/CE_CACHEDEV1_DATA\\\
/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(124): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\
\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/console.php(65): Symfony\\\\Component\\\\Console\\\\Application->run()\
\n#11 \\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/occ(11): require_once('\\\/share\\\/CE_CACHE...')\\n#12 {main}\",\"File\":\"\\\/share\\\/CE_CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\
/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php\",\"Line\":1216}","level":4,"time":"2017-10-04T08:51:31+00:00","method":"--","url":"--"}
{"reqId":"9c6d7115ef60ba7128fd65748523625a","remoteAddr":"192.168.53.121","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'al
ways_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-10-04T09:00:14+00:00"}


```

**Comment by kdslkdsaldsal** [comment]
Looks similar to existing issues like https://github.com/owncloud/core/issues/20697, https://github.com/owncloud/core/issues/27758, https://github.com/owncloud/core/issues/28235

**Comment by sagi7** [comment]
insert into oc_appconfig (appid, configkey, configvalue) values ('core', 'repairlegacystoragesdone', 'yes');
and after that sudo -u httpdusr /mnt/ext/opt/apache/bin/php occ upgrade did the job.

**Comment by sagi7** [comment]
Problem solved
