### ISSUE TITLE
Problem with cron.php

### ISSUE THREAD

**Issue by Etienne5131** [owncloud/core#29191]
Hi everyone !

I've got a problem with cron.php.

It started with an admin warning that I wanted to remove (cf [this issue](https://github.com/owncloud/documentation/issues/3448) on github/owncloud/doc). It led me to the following command to run : 

```
crontab -u www-data -e
*/15 * * * * /usr/bin/php -f /path/to/your/owncloud/cron.php
```

As it did not remove the warning message, I've tested the command given to cron by running 

`su -s /bin/bash -c '/usr/bin/php -f /var/www/owncloud/cron.php' www-data`

But it did not work. Instead, it gave me lots of error messages : 

```
PHP Fatal error: Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/owncloud/lib/private/DB/Connection.php:63
Stack trace:
#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/owncloud/lib/private/DB/Connection.php(146): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\D in /var/www/owncloud/lib/private/DB/Connection.php on line 63
PHP Fatal error: Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/owncloud/lib/private/DB/Connection.php:63
Stack trace:
#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/owncloud/lib/private/DB/Connection.php(146): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\D in /var/www/owncloud/lib/private/DB/Connection.php on line 63
```

Could you help me, please ?

**Comment by DeepDiver1975** [comment]
You are missing PHP modules.

**Comment by Etienne5131** [comment]
Which ones ?

**Comment by kdslkdsaldsal** [comment]
@Etienne5131 You shouldn't post your issue about the error message in here but in https://central.owncloud.org/ 😄 

I've only suggested you in https://github.com/owncloud/documentation/issues/3448 to create a new "Feature Request" to show a warning about a not running cron in the "Setup & Security" Warnings overview similar to the other warnings.

Closing here for now

**Comment by DeepDiver1975** [comment]
This depends in the db you Are using
