### ISSUE TITLE
SabreDav 500 error with wrong credentials doing propfind

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/core#29346]
### Steps to reproduce
1. Setup a client
```
$settings = array(
  'baseUri' => 'http://myowncloud.url/remote.php/webdav/',
  'userName' => 'wrong_username',
  'password' => 'wrong_password',
  'depth' => 1
);
$client = new Client($settings);
```
2. Do a propfind
```
$file_list = $client->propfind('', array(
  '{DAV:}getetag'
));
```

### Expected behaviour
Some kind of "Wrong credentials" message.
Using `$client->request('GET')` fails nicely:
```
Array (
  [body] => Sabre\DAV\Exception\NotAuthenticated Username or password was incorrect, Username or password was incorrect
  [statusCode] => 401
)
```

### Actual behaviour
```
Fatal error: Uncaught Sabre\HTTP\ClientHttpException: Unauthorized in /Volumes/Workspace/ocaccess/vendor/sabre/dav/lib/DAV/Client.php:234
```

@PVince81

**Comment by PVince81** [comment]
@hurradieweltgehtunter hmm, that's weird, as if the Sabre lib wouldn't catch its own exceptions.

Can you try adding `$client->setThrowExceptions(true);` ? With a bit of luck this might activate better error handling.

**Comment by hurradieweltgehtunter** [comment]
Doesn't seem to make a difference.

```
$settings = array(
  'baseUri' => 'http://myowncloud.url/remote.php/webdav/',
  'userName' => 'wrong_username',
  'password' => 'wrong_password',
  'depth' => 1
);

$client = new Client($settings);
$client->setThrowExceptions(true);
$file_list = $client->propfind('', array(
  '{DAV:}getetag')
);
```

Result:
```
Fatal error: Uncaught Sabre\HTTP\ClientHttpException: Unauthorized in /Volumes/Workspace/ocaccess/vendor/sabre/http/lib/Client.php:160 
Stack trace: 
#0 /Volumes/Workspace/ocaccess/vendor/sabre/dav/lib/DAV/Client.php(231): Sabre\HTTP\Client->send(Object(Sabre\HTTP\Request))
#1 /Volumes/Workspace/ocaccess/index.php(17): Sabre\DAV\Client->propFind('http://localhos...', Array)
#2 {main} thrown in /Volumes/Workspace/ocaccess/vendor/sabre/http/lib/Client.php on line 160
```

**Comment by PVince81** [comment]
Ok thanks. We'll need to debug into the lib to find if some catch block is missing there.

For now you'll need to catch the ClientHttpException yourself and check the 401 status code.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
