### ISSUE TITLE
a file called "0" cannot be uploaded by chunking

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#29599]
### Steps to reproduce
1. create a 20MB file and call it "0"
2. upload that file via WebUI

### Expected behaviour
file should be uploaded correctly

### Actual behaviour
file is not uploaded, Error message is shown: `File with name //0 could not be located`

### Server configuration
**Operating system**:
Ubuntu 17.10
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
10.0.3 (git) 
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc9xsmdtnlru",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "sqlite3",
        "logtimezone": "UTC",
        "installed": true,
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "default_language": "en",
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "log_type": "owncloud",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "debug": false,
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/tests\/ui\/skeleton",
        "version": "10.0.3.3",
        "csrf.disabled": true,
        "files_external_allow_create_new_local": "true"
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.3.2
  - diagnostics: 0.1.0
  - enterprise_key: 0.1.3
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_texteditor: 2.2
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firewall: 2.4.2
  - gallery: 16.0.2
  - market: 0.2.1
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - testing: 0.1.0
  - updatenotification: 0.2.1
Disabled:
  - customgroups
  - files_antivirus
  - multidirtest
  - password_policy
  - theme-example
  - user_ldap
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF 56
**Operating system:**
Ubuntu 17.10

#### ownCloud log (data/owncloud.log)
```
{"reqId":"3MEjkf334sbgcdmDs5mT","level":0,"time":"2017-11-16T14:44:34+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"webdav","method":"MOVE","url":"\/owncloud-core\/remote.php\/dav\/uploads\/admin\/web-file-upload-3578060c2c3fee1a31d85366bab7a6ee-1510843470131\/.file","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name \\\/\\\/0 could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChild('0')\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/CopyEtagHeaderPlugin.php(74): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/admin\\\/0')\\n#2 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CopyEtagHeaderPlugin->afterMove('uploads\\\/admin\\\/w...', 'files\\\/admin\\\/0')\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(648): Sabre\\\\Event\\\\EventEmitter->emit('afterMove', Array)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#8 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Server.php(256): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/remote.php(175): require_once('\\\/home\\\/artur\\\/www...')\\n#12 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":257,\"User\":\"admin\"}"}
```

#### Browser log
![image](https://user-images.githubusercontent.com/2425577/32897484-d36481f2-cb0d-11e7-890d-25fce24c2da6.png)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly duplicate or related issues are #29554 (overwriting a file with a folder and a folder with a file needs better error reporting), and #28748 ( hash '#' or question-mark '?' is not accepted in filenames).

**Comment by individual-it** [comment]
the file will end up as `.file` in the folder you have uploaded it to

**Comment by phil-davis** [comment]
Greetings Gitmate, nice to know that I have a reputation for logging (and/or fixing?) bugs about "0" :)

**Comment by individual-it** [comment]
after fixing this issue untag all tests (integration and UI) marked by `@skip @issue-29599`

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).

**Comment by individual-it** [comment]
Feel like we should keep this open

**Comment by phil-davis** [comment]
Seems to be a Sabre/DAV problem:
https://github.com/sabre-io/dav/issues/1021

Should be fixed by:
https://github.com/sabre-io/dav/pull/1022

so requires a new Sabre/DAV release that is also compatible with PHP 5.6 (otherwise this has to wait until PHP 5.6 support is dropped)

**Comment by individual-it** [comment]
sabre github repo says 3.1 and master are working with PHP 5.5 https://github.com/sabre-io/dav#build-status

**Comment by phil-davis** [comment]
There is a 3.2.* release series also (which ownCloud is using) https://github.com/sabre-io/dav/releases
And a recent 3.3 that does not seem to have a formal release tag yet.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by phil-davis** [comment]
This is waiting on progress of #31724 which is waiting on #31644

**Comment by phil-davis** [comment]
PR #37030 cleans up the unskipping of scenarios. Then this issue can be closed.
