### ISSUE TITLE
Decrypt all should ignore federated shares and invalid storages

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29723]
### Steps

1. Setup two instances OC_A and OC_B
1. Setup encryption with master key on OC_A
1. Login as admin@OC_A to initialize keys
1. Login as admin@OC_B
1. Create a folder "fed-share"
1. Share "fed-share" with admin@OC_A
1. Go to admin@OC_A session
1. Accept the share
1. Log out
1. Delete/destroy/block the OC_B instance so that OC_A cannot access it any more.
1. On OC_A, run `occ decrypt-all` and let it decrypt for the admin user

### Expected result
Successful decryption

### Actual result
Error message about `StorageInvalidException` or any other error related to the unavailable federated share.

### Version
ownCloud 10.0.4RC1 for both instances

We should skip incoming federated shares anyway during the decryption process!

**Comment by PVince81** [comment]
I don't have a stack trace for the above.

However, @SergioBertolinSG had a similar scenario on a test environment which I cannot reproduce currently. I do have the stack trace:
```
{"Exception":"InvalidArgumentException","Message":"Unable to parse malformed url: https:///ocs-provider/","Code":0,"Trace":"
#0 /opt/owncloud/lib/composer/guzzlehttp/guzzle/src/Message/Request.php(70): GuzzleHttp\Url::fromString('https:///ocs-pr...')\n
#1 /opt/owncloud/lib/composer/guzzlehttp/guzzle/src/Message/Request.php(42): GuzzleHttp\Message\Request->setUrl('https:///ocs-pr...')\n
#2 /opt/owncloud/lib/composer/guzzlehttp/guzzle/src/Message/MessageFactory.php(85): GuzzleHttp\Message\Request->__construct('GET', 'https:///ocs-pr...', Array, NULL, Array)\n
#3 /opt/owncloud/lib/composer/guzzlehttp/guzzle/src/Client.php(120): GuzzleHttp\Message\MessageFactory->createRequest('GET', 'https:///ocs-pr...', Array)\n
#4 /opt/owncloud/lib/composer/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->createRequest('GET', 'https:///ocs-pr...', Array)\n
#5 /opt/owncloud/lib/private/Http/Client/Client.php(136): GuzzleHttp\Client->get('https:///ocs-pr...', Array)\n
#6 /opt/owncloud/apps/federatedfilesharing/lib/DiscoveryManager.php(96): OC\Http\Client\Client->get('https:///ocs-pr...', Array)\n
#7 /opt/owncloud/apps/federatedfilesharing/lib/DiscoveryManager.php(145): OCA\FederatedFileSharing\DiscoveryManager->discover('https://')\n
#8 /opt/owncloud/apps/federatedfilesharing/lib/Notifications.php(289): OCA\FederatedFileSharing\DiscoveryManager->getShareEndpoint('https://')\n
#9 /opt/owncloud/apps/federatedfilesharing/lib/Notifications.php(234): OCA\FederatedFileSharing\Notifications->tryHttpPostToShareEndpoint('', '/0/decline', Array)\n
#10 /opt/owncloud/apps/federatedfilesharing/lib/Notifications.php(212): OCA\FederatedFileSharing\Notifications->sendUpdateToRemote(NULL, 0, NULL, 'decline')\n
#11 /opt/owncloud/apps/federatedfilesharing/appinfo/app.php(71): OCA\FederatedFileSharing\Notifications->sendDeclineShare(NULL, 0, NULL)\n
#12 [internal function]: OC_App::{closure}(Object(OCP\Share\Events\DeclineShare), 'OCP\\Share\\Event...', Object(Symfony\Component\EventDispatcher\EventDispatcher))\n
#13 /opt/owncloud/lib/composer/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Object(Closure), Object(OCP\Share\Events\DeclineShare), 'OCP\\Share\\Event...', Object(Symfony\Component\EventDispatcher\EventDispatcher))\n
#14 /opt/owncloud/lib/composer/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'OCP\\Share\\Event...', Object(OCP\Share\Events\DeclineShare))\n
#15 /opt/owncloud/apps/files_sharing/lib/External/Manager.php(339): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('OCP\\Share\\Event...', Object(OCP\Share\Events\DeclineShare))\n
#16 /opt/owncloud/apps/files_sharing/lib/External/Storage.php(232): OCA\Files_Sharing\External\Manager->removeShare('/96.jpeg')\n
#17 /opt/owncloud/apps/files_sharing/lib/External/Storage.php(187): OCA\Files_Sharing\External\Storage->checkStorageAvailability()\n
#18 /opt/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(374): OCA\Files_Sharing\External\Storage->hasUpdated('', 1482498146)\n
#19 /opt/owncloud/lib/private/Files/Storage/Wrapper/Availability.php(394): OC\Files\Storage\Wrapper\Wrapper->hasUpdated('', 1482498146)\n
#20 /opt/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(374): OC\Files\Storage\Wrapper\Availability->hasUpdated('', 1482498146)\n
#21 /opt/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(374): OC\Files\Storage\Wrapper\Wrapper->hasUpdated('', 1482498146)\n
#22 /opt/owncloud/lib/private/Files/Cache/Watcher.php(126): OC\Files\Storage\Wrapper\Wrapper->hasUpdated('', 1482498146)\n
#23 /opt/owncloud/lib/private/Files/View.php(1305): OC\Files\Cache\Watcher->needsUpdate('', Object(OC\Files\Cache\CacheEntry))\n
#24 /opt/owncloud/lib/private/Files/View.php(1343): OC\Files\View->getCacheEntry(Object(OCA\Files_Trashbin\Storage), '', '/96.jpeg')\n
#25 /opt/owncloud/lib/private/Files/Filesystem.php(910): OC\Files\View->getFileInfo('/admin/files/96...', true)\n
#26 /opt/owncloud/core/ajax/preview.php(51): OC\Files\Filesystem::getFileInfo('/96.jpeg')\n
#27 /opt/owncloud/lib/private/Route/Route.php(155) : runtime-created function(1): require_once('/opt/owncloud/c...')\n
#28 [internal function]: __lambda_func(NULL)\n
#29 /opt/owncloud/lib/private/Route/Router.php(342): call_user_func('\x00lambda_125', Array)\n
#30 /opt/owncloud/lib/base.php(929): OC\Route\Router->match('/core/preview.p...')\n
#31 /opt/owncloud/index.php(56): OC::handleRequest()\n
#32 {main}","File":"/opt/owncloud/lib/composer/guzzlehttp/guzzle/src/Url.php","Line":39
}
```

However I cannot re-trigger this because the trace above has already discarded the invalid share so it doesn't exist any more in `oc_share_external`. Remember that we have some conditions in which OC decides that the remote share is permanently not available any more and discards the mount point.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/29724

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by sharidas** [comment]
Reopening this issue.
