### ISSUE TITLE
Thumbnails not fetched in clients, depending on the auth method

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#29914]
In a Basic auth account, thumbnails are fetched by clients with the following request:

> GET \<URL\>/index.php/apps/files/api/v1/thumbnail/64/64/<pic_name.jpg>

responsed correctly with (response-body):                                                                                                                                                                                           
>Format: Portable network graphics
Size:   64 x 64 px
Mode:   RGBA
dpi:    (96, 96)

Same request under Bearer auth (OAuth2) returns `500 Internal Server Error` with an 8k html in response-body (i can attach if needed)

Of course, token is not expired when request is performed.

Server {"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.4.4","versionstring":"10.0.4","edition":"Enterprise","productname":"ownCloud"}

Curl command to get:

> curl -H 'Host:xxxx' 
-H 'Content-Type:application/x-www-form-urlencoded' 
-H 'Cookie:xxxx' 
-H 'Accept:\*/\*' 
-H 'Connection:keep-alive' 
-H 'Accept-Encoding:gzip, deflate' 
-H 'User-Agent:Mozilla/5.0 (iOS) ownCloud-iOS/3.7.0' 
-H 'Authorization:Basic/Bearer xxxx' 
-H 'OCS-APIREQUEST:true' 'https://\<URL\>/index.php/apps/files/api/v1/thumbnail/64/64/\<pic_name\>'

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by michaelstingl** [comment]
FYI: @DeepDiver1975 is currently working on preview generation too. (other endpoint)

**Comment by DeepDiver1975** [comment]
> In a Basic auth account, thumbnails are fetched by clients with the following request:
> 
>     GET <URL>/index.php/apps/files/api/v1/thumbnail/64/64/<pic_name.jpg>

I consider this endpoint not valid in terms of public usage. This was never tested to work properly with oauth.

**Comment by jesmrec** [comment]
Is this the new solution? https://github.com/owncloud/core/pull/29319

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by SergioBertolinSG** [comment]
Happening on 10.0.8alpha when using iOS app 3.7.3 and regular authentication.

Android app doesn't have problems.

```
{"reqId":"TcojoVMeJ8JF1eEYEolg","level":3,"time":"2018-04-11T11:31:49+00:00","remoteAddr":"IP","user":"--","app":"index","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/64\/64\/IMG_20180406_150533.jpg","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 2 passed to OCA\\\\Files\\\\Service\\\\TagService::__construct() must be an instance of OCP\\\\ITags, null given, called in \\\/opt\\\/owncloud\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php on line 86\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(86): OCA\\\\Files\\\\Service\\\\TagService->__construct(Object(OC\\\\User\\\\Session), NULL, NULL)\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(111): Pimple\\\\Container->offsetGet('TagService')\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(47): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('TagService')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(111): Pimple\\\\Container->offsetGet('APIController')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(80): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('APIController')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('APIController', 'getThumbnail', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/base.php(912): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/api...')\\n#11 \\\/opt\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Service\\\/TagService.php\",\"Line\":47}"}
```

**Comment by DeepDiver1975** [comment]
on master this also fails for basic auth .... :boom:

**Comment by PVince81** [comment]
regression ?

**Comment by jesmrec** [comment]
does it fox both cases? (basic and OAuth2)

**Comment by DeepDiver1975** [comment]
Should fix both. Yes.

**Comment by SergioBertolinSG** [comment]
Just tested using iOS app 3.7.3 and 10.0.8RC2.

When uploading a photo just taken the problem persist:

```
{"reqId":"JKN66ZAHr3JbW9AzvrDR","level":3,"time":"2018-04-17T13:57:10+00:00","remoteAddr":"HIDDEN_IP","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/64\/64\/Photo-2018-04-17-15-55-54_0311.JPG","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/admin\\\/files\\\/files\\\/Photo-2018-04-17-15-55-54_0311.JPG\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(129): OC\\\\Files\\\\Node\\\\Root->get('\\\/admin\\\/files\\\/fi...')\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/PreviewManager.php(142): OC\\\\Files\\\\Node\\\\Folder->get('files\\\/Photo-201...')\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ApiController.php(102): OC\\\\PreviewManager->createPreview('files\\\/Photo-201...', 64, 64, true)\\n#3 [internal function]: OCA\\\\Files\\\\Controller\\\\ApiController->getThumbnail(64, 64, 'Photo-2018-04-1...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ApiController), 'getThumbnail')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ApiController), 'getThumbnail')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('APIController', 'getThumbnail', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/base.php(912): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/api...')\\n#11 \\\/opt\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php\",\"Line\":187}"}
```

**Comment by DeepDiver1975** [comment]
This is a totally different error message.

Please collect more information about the scenario.

Full request please.

Thx

**Comment by phil-davis** [comment]
I noticed these this afternoon while testing on iOS with (and without) an app password.
I checked using Android just now, with current ``stable10`` (=10.0.8RC2) and get:
```
[Tue Apr 17 20:20:10 2018] Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"\/test123\/files\/files\/renamed.JPG","Code":0,"Trace":"#0 \/home\/phil\/ownCloud\/core\/lib\/private\/Files\/Node\/Folder.php(129): OC\\Files\\Node\\Root->get('\/test123\/files\/...')\n#1 \/home\/phil\/ownCloud\/core\/lib\/private\/PreviewManager.php(142): OC\\Files\\Node\\Folder->get('files\/renamed.J...')\n#2 \/home\/phil\/ownCloud\/core\/apps\/files\/lib\/Controller\/ApiController.php(102): OC\\PreviewManager->createPreview('files\/renamed.J...', 128, 128, true)\n#3 [internal function]: OCA\\Files\\Controller\\ApiController->getThumbnail(128, 128, 'renamed.JPG')\n#4 \/home\/phil\/ownCloud\/core\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/home\/phil\/ownCloud\/core\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files\\Controller\\ApiController), 'getThumbnail')\n#6 \/home\/phil\/ownCloud\/core\/lib\/private\/AppFramework\/App.php(103): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ApiController), 'getThumbnail')\n#7 \/home\/phil\/ownCloud\/core\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('APIController', 'getThumbnail', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#9 \/home\/phil\/ownCloud\/core\/lib\/private\/Route\/Router.php(342): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#10 \/home\/phil\/ownCloud\/core\/lib\/base.php(912): OC\\Route\\Router->match('\/apps\/files\/api...')\n#11 \/home\/phil\/ownCloud\/core\/index.php(55): OC::handleRequest()\n#12 {main}","File":"\/home\/phil\/ownCloud\/core\/lib\/private\/Files\/Node\/Root.php","Line":187}
[Tue Apr 17 20:20:10 2018] 10.49.208.250:2696 [500]: /index.php/apps/files/api/v1/thumbnail/128/128/renamed.JPG
```
If I download the file to the Android device, then I can refresh the folder etc. and not get any server error. But in that case there is no request for the thumbnail. I think after downloading the actual file, the Android app has generated a thumbnail locally from the file and so it does not bother asking the server for one.

I will look on iOS again also

**Comment by jesmrec** [comment]
@phil-davis i checked iOS and the problem is reproducible under 10.0.8RC2

**Comment by phil-davis** [comment]
On iOS I get
```
[Tue Apr 17 20:29:19 2018] Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"\/test123\/files\/files\/faaaaa\/20180416_143140.jpg","Code":0,"Trace":"#0 \/home\/phil\/ownCloud\/core\/lib\/private\/Files\/Node\/Folder.php(129): OC\\Files\\Node\\Root->get('\/test123\/files\/...')\n#1 \/home\/phil\/ownCloud\/core\/lib\/private\/PreviewManager.php(142): OC\\Files\\Node\\Folder->get('files\/faaaaa\/20...')\n#2 \/home\/phil\/ownCloud\/core\/apps\/files\/lib\/Controller\/ApiController.php(102): OC\\PreviewManager->createPreview('files\/faaaaa\/20...', 64, 64, true)\n#3 [internal function]: OCA\\Files\\Controller\\ApiController->getThumbnail(64, 64, 'faaaaa\/20180416...')\n#4 \/home\/phil\/ownCloud\/core\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/home\/phil\/ownCloud\/core\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files\\Controller\\ApiController), 'getThumbnail')\n#6 \/home\/phil\/ownCloud\/core\/lib\/private\/AppFramework\/App.php(103): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ApiController), 'getThumbnail')\n#7 \/home\/phil\/ownCloud\/core\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('APIController', 'getThumbnail', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#9 \/home\/phil\/ownCloud\/core\/lib\/private\/Route\/Router.php(342): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#10 \/home\/phil\/ownCloud\/core\/lib\/base.php(912): OC\\Route\\Router->match('\/apps\/files\/api...')\n#11 \/home\/phil\/ownCloud\/core\/index.php(55): OC::handleRequest()\n#12 {main}","File":"\/home\/phil\/ownCloud\/core\/lib\/private\/Files\/Node\/Root.php","Line":187}
[Tue Apr 17 20:29:19 2018] 10.49.208.250:11161 [500]: /index.php/apps/files/api/v1/thumbnail/64/64/faaaaa/20180416_143140.jpg
```
and even after downloading the actual file, this error still happens each time the folder is entered. I am guessing that iOS does not auto-generate itself a thumbnail when a file is downloaded. So it will keep trying to get a thumbnail from the server.

**Comment by phil-davis** [comment]
Note: ANdroid asks for a 128x128 preview, iOS asks for 64x64. They both have the similar 500 error.

**Comment by SergioBertolinSG** [comment]
```
GET http://HIDDEN_HOST/index.php/apps/files/api/v1/thumbnail/64/64/1518171156128.jpg

500 Internal Server Error 
```

REQUEST:
```
Host:              HIDDEN_HOST                                                                                                                         
Content-Type:      application/x-www-form-urlencoded                                                                                                                     
Cookie:            ,cookie_test=test; ocygxehjvm34=qv0qcnnjv2j23nth3hf6gbeeu1; oc_sessionPassphrase=aMkAdkelTkilmJJrBD8JOVSq3Kx7fLUHPHvkmLz2mkaiKtvsjgIqL%2Fy%2Bl3IgFEX%2
                   F0IIfn7dmxvIh%2BDjWl1ozrccbf5oPLOVfLbJ6QIjoUZN8AhImkpjYihz5PsoEXuRZ                                                                                   
Accept:            */*                                                                                                                                                   
Connection:        keep-alive                                                                                                                                            
Proxy-Connection:  keep-alive                                                                                                                                            
Accept-Encoding:   gzip, deflate                                                                                                                                         
User-Agent:        Mozilla/5.0 (iOS) ownCloud-iOS/3.7.3                                                                                                                  
Accept-Language:   en-GB;q=1, es-GB;q=0.9, pt-BR;q=0.8, fr-FR;q=0.7, de-DE;q=0.6                                                                                         
Authorization:     Basic YWRtaW46UGFzc3dvcmQ=                                                                                                                            
OCS-APIREQUEST:    true   
```


RESPONSE:

```
text/html 8.79k 1.72s
                         Request                                                  Response                                                  Detail
Server:                         Apache/2.4.18 (Ubuntu)                                                                                                                   
Expires:                        Thu, 19 Nov 1981 08:52:00 GMT                                                                                                            
Cache-Control:                  no-store, no-cache, must-revalidate                                                                                                      
Pragma:                         no-cache                                                                                                                                 
Content-Security-Policy:        default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src      
                                'self' data:; media-src *; connect-src *                                                                                                 
X-XSS-Protection:               1; mode=block                                                                                                                            
X-Content-Type-Options:         nosniff                                                                                                                                  
X-Frame-Options:                SAMEORIGIN                                                                                                                               
X-Robots-Tag:                   none                                                                                                                                     
X-Download-Options:             noopen                                                                                                                                   
X-Permitted-Cross-Domain-Polic  none                                                                                                                                     
ies:                                                                                                                                                                     
Set-Cookie:                     ocygxehjvm34=8gcossgl3tudkqrv6qq0i7klj1; path=/; HttpOnly                                                                                
Set-Cookie:                     cookie_test=test; expires=Tue, 17-Apr-2018 16:26:20 GMT; Max-Age=3600                                                                    
Connection:                     close                                                                                                                                    
Transfer-Encoding:              chunked                                                                         
Content-Type:                   text/html; charset=UTF-8           
```

**Comment by SergioBertolinSG** [comment]
Using android 2.7.0 with core 10.0.8RC2:

```
GET http://HIDDEN_HOST/index.php/apps/files/api/v1/thumbnail/448/448/1495179722766.jpg
                        ← 500 Internal Server Error text/html 9.08k 245ms
```


REQUEST:

```
Authorization:     Basic YWRtaW46UGFzc3dvcmQ=                                                                                         
User-Agent:        Mozilla/5.0 (Android) ownCloud-android/2.7.0                                                                       
Host:              HIDDEN_HOST                                                                                       
Cookie:            oc_sessionPassphrase=kXwzpUQmhpsfjRco930sBxtK5eSRRtYFXy7c2O93HKH9EqRp5uVFhDyffPMP2H5pFxbhUH%2BQD9UYBcGu0T11hYx%2F57
                   fYE0XYAHypleX%2Be5jMePhd910UXx0Swz9q0a1v; ocygxehjvm34=c9sbobu6lsoig3r7u9np12ipr3                                  
Proxy-Connection:  Keep-Alive 
```


RESPONSE:

```
Date:                           Tue, 17 Apr 2018 16:22:18 GMT                                                                         
Server:                         Apache/2.4.18 (Ubuntu)                                                                                
Expires:                        Thu, 19 Nov 1981 08:52:00 GMT                                                                         
Cache-Control:                  no-store, no-cache, must-revalidate                                                                   
Pragma:                         no-cache                                                                                              
Content-Security-Policy:        default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *;   
                                img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *                              
X-XSS-Protection:               1; mode=block                                                                                         
X-Content-Type-Options:         nosniff                                                                                               
X-Frame-Options:                SAMEORIGIN                                                                                            
X-Robots-Tag:                   none                                                                                                  
X-Download-Options:             noopen                                                                                                
X-Permitted-Cross-Domain-Polic  none                                                                                                  
ies:                                                                                                                                  
Connection:                     close                                                                                                 
Transfer-Encoding:              chunked                                                                                               
Content-Type:                   text/html; charset=UTF-8
```

**Comment by DeepDiver1975** [comment]
> Using android 2.7.0 with core 10.0.8RC2:
> 
> GET http://HIDDEN_HOST/index.php/apps/files/api/v1/thumbnail/448/448/1495179722766.jpg
>                         ← 500 Internal Server Error text/html 9.08k 245ms

What has to be done to trigger this api call in android? @SergioBertolinSG  THX

**Comment by SergioBertolinSG** [comment]
@DeepDiver1975 Using the android app, just open the files view having some images (jpeg) inside root folder.

**Comment by DeepDiver1975** [comment]
Reproduced! THX a lot!

**Comment by phil-davis** [comment]
Note: the problem happens on both Android and iOS using either "normal password" or an "app password". I can re-test the app password cases easily (I was testing in this area yesterday)

**Comment by DeepDiver1975** [comment]
the backport to stable10 introduced a bug due to different apis related to preview generation ... PR is coming ....

**Comment by PVince81** [comment]
fix https://github.com/owncloud/core/pull/31183 was merged
