### ISSUE TITLE
activity app loading forever when affected group was deleted

### ISSUE THREAD

**Issue by 3dmedium** [owncloud/core#29964]
### Steps to reproduce
1.  Share File with group
2.  Delete Group
3.  View Activity

### Expected behaviour
There is a loading circle forever

### Actual behaviour
Should load activities

### Server configuration
**Operating system**:   Linux Ubuntu 16.04 LTS

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:** MySQL

**PHP version:**  PHP 7.0.22-0ubuntu0.16.04.1

**ownCloud version:** (see ownCloud admin page)  10.0.3.3

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** owncloud official download

**Signing status (ownCloud 9.0 and above):** no problems
No errors have been found.

**The content of config/config.php:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.0.3.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 0,
        "log.condition": {
            "apps": [
                "files"
            ]
        },
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "activity_expire_days": 3650,
        "maintenance": false
    }
}

**List of activated apps:**
Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.0
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - external
  - files_antivirus
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
Opera, Chrome, IE, Edge

**Operating system:**
Win / Mac
#### Web server error log
`{"reqId":"5YLGesgOqpL3WCdWLaC2","level":3,"time":"2017-12-22T10:47:17+00:00","remoteAddr":"XXXXXXXXX","user":"XXXXXXXXX","app":"index","method":"GET","url":"\/index.php\/apps\/activity\/api\/v2\/activity\/all?format=json&previews=true&since=0","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getDisplayName() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Parameter\\\/Parameter.php(82): OCA\\\\Activity\\\\Formatter\\\\GroupFormatter->format(Object(OC\\\\Activity\\\\Event), 'GROUP NAME....')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/DataHelper.php(87): OCA\\\\Activity\\\\Parameter\\\\Parameter->format()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/DataHelper.php(129): OCA\\\\Activity\\\\DataHelper->translation('files_sharing', 'shared_group_se...', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/GroupHelper.php(207): OCA\\\\Activity\\\\DataHelper->formatStrings(Array, 'subject')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Data.php(287): OCA\\\\Activity\\\\GroupHelper->getActivities()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Controller\\\/OCSEndPoint.php(209): OCA\\\\Activity\\\\Data->get(Object(OCA\\\\Activity\\\\GroupHelper), Object(OCA\\\\Activity\\\\UserSettings), 'XXXXXXXXX', 0, 0, 'desc', 'all', '', 0)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Controller\\\/OCSEndPoint.php(181): OCA\\\\Activity\\\\Controller\\\\OCSEndPoint->get(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Controller\\\/EndPoint.php(68): OCA\\\\Activity\\\\Controller\\\\OCSEndPoint->getFilter(Array)\\n#8 [internal function]: OCA\\\\Activity\\\\Controller\\\\EndPoint->getFilter('all')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Activity\\\\Controller\\\\EndPoint), 'getFilter')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Activity\\\\Controller\\\\EndPoint), 'getFilter')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('EndPointControl...', 'getFilter', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(307): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(928): OC\\\\Route\\\\Router->match('\\\/apps\\\/activity\\\/...')\\n#16 \\\/var\\\/www\\\/owncloud\\\/index.php(56): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Formatter\\\/GroupFormatter.php\",\"Line\":44}"}`

**Comment by hodyroff** [comment]
Could you check it out with 10.0.4 as well, please?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
