### ISSUE TITLE
Can't upload files larger than 1G

### ISSUE THREAD

**Issue by deounix** [owncloud/core#29982]
Php: PHP 7.1.11
Owncloud: 10.0.4.4
Web server: Nginx 1.13.8
OS: Centos 7 64bit

```
php.ini

upload_max_filesize = 100G
```

nginx config

```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile off;
    sendfile_max_chunk 0;

    tcp_nopush          on;
    tcp_nodelay         on;

    aio threads;
	directio       1024;
    output_buffers 10 1024k;

    proxy_request_buffering off;

    keepalive_timeout   800;
    
    types_hash_max_size 100048;

    client_body_in_file_only clean;
    client_body_buffer_size 10048576k;
    client_max_body_size 100G;

    limit_conn_zone $binary_remote_addr zone=addr:40m;

    fastcgi_read_timeout 8000;

    include /etc/nginx/conf.d/*.conf;
}

```

```
upstream php-handler {
    server 127.0.0.1:9000;
}
 
server {
    listen 80;
    server_name dl1.example.com;
    # enforce https


    return 301 https://$server_name$request_uri;
}
 
server {
        listen 443 http2 ssl;
        server_name dl1.example.com www.dl1.example.com;
        ssl_certificate /etc/letsencrypt/live/dl1.example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dl1.example.com/privkey.pem;

        #limit_conn addr 15;
        #limit_rate 200k;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_ecdh_curve secp384r1;
        ssl_session_cache shared:SSL:10m;
        ssl_session_tickets off;
        ssl_stapling on;
        ssl_stapling_verify on;
        resolver 8.8.8.8 8.8.4.4 valid=300s;
        resolver_timeout 5s;
        # Disable preloading HSTS for now.  You can use the commented out header line that includes
        # the "preload" directive if you understand the implications.
        add_header Strict-Transport-Security "max-age=15552000; includeSubDomains";
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options nosniff;
        add_header X-Accel-Buffering no;
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Robots-Tag none;
        add_header X-Download-Options noopen;
        add_header X-Permitted-Cross-Domain-Policies none;


        # Path to the root of your installation
        root /usr/share/nginx/html/owncloud/;

        location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
        }
 
        # The following 2 rules are only needed for the user_webfinger app.
        # Uncomment it if you're planning to use this app.
        #rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        #rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;
 
        ssl_dhparam /etc/ssl/certs/dhparam.pem;

        location ~ /.well-known {
                allow all;
        }
 
        # set max upload size
        client_max_body_size 100G;
        fastcgi_buffering off;


        # Disable gzip to avoid the removal of the ETag header
        gzip off;
 
        # Uncomment if your server is build with the ngx_pagespeed module
        # This module is currently not supported.
        #pagespeed off;
 
        error_page 403 /core/templates/403.php;
        error_page 404 /core/templates/404.php;
 
        location / {
                rewrite ^ /index.php$uri;
        }
 
        location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
                return 404;
        }
        location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
                return 404;
        }
 
        location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+|core/templates/40[34])\.php(?:$|/) {
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_param HTTPS on;
                fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
                fastcgi_param front_controller_active true;
                fastcgi_pass php-handler;
                fastcgi_intercept_errors on;
                fastcgi_request_buffering off;
                fastcgi_read_timeout 8000;
        }
 
        location ~ ^/(?:updater|ocs-provider)(?:$|/) {
                try_files $uri $uri/ =404;
                index index.php;
        }
 
        # Adding the cache control header for js and css files
        # Make sure it is BELOW the PHP block
        location ~* \.(?:css|js)$ {
                try_files $uri /index.php$uri$is_args$args;
                add_header Cache-Control "public, max-age=7200";
                # Add headers to serve security related headers (It is intended to have those duplicated to the ones above)
                # Before enabling Strict-Transport-Security headers please read into this topic first.
                #add_header Strict-Transport-Security "max-age=15552000; includeSubDomains";
                add_header X-Content-Type-Options nosniff;
                add_header X-Frame-Options "SAMEORIGIN";
                add_header X-XSS-Protection "1; mode=block";
                add_header X-Robots-Tag none;
                add_header X-Download-Options noopen;
                add_header X-Permitted-Cross-Domain-Policies none;
                # Optional: Don't log access to assets
                access_log off;
        }

        location ~* \.(?:svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$ {
                try_files $uri /index.php$uri$is_args$args;
                # Optional: Don't log access to other assets
                access_log off;
        }
}

```

php-fpm config

```
[www]
user = nginx
group = nginx
listen = 127.0.0.1:9000

listen.allowed_clients = 127.0.0.1

pm = ondemand

pm.max_children = 15

pm.start_servers = 5

pm.min_spare_servers = 5

pm.max_spare_servers = 15

pm.max_requests = 0

slowlog = /var/log/php-fpm/www-slow.log

request_terminate_timeout = 20

env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp

php_admin_value[error_log] = /var/log/php-fpm/www-error.log
php_admin_flag[log_errors] = on

php_value[session.save_handler] = files
php_value[session.save_path]    = /var/lib/php/session
php_value[soap.wsdl_cache_dir]  = /var/lib/php/wsdlcache

php_flag[expose_php] = off
php_flag[short_open_tag] = on

```

nginx error log

`2017/12/28 04:38:16 [error] 464#464: *11 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 185.63.254.xx, server: dl1.example.com, request: "MOVE /remote.php/dav/uploads/deounix/web-file-upload-58e02e6361de7b4d7bf05150d7107e9a-1514467811799/.file HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "dl1.example.com"`

**Comment by deounix** [comment]
owncloud log

`{"reqId":"CUe6KjBHBMpsEDJth6Dp","level":3,"time":"2017-12-28T05:21:13+00:00","remoteAddr":"41.254.8.118","user":"--","app":"index","method":"GET","url":"\/s\/tAJSrVoTfTXuAYd\/download","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",\"Message\":\"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(429): OC\\\\DB\\\\Connection->connect()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(389): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatformVersion()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(328): Doctrine\\\\DBAL\\\\Connection->detectDatabasePlatform()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(623): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatform()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(147): Doctrine\\\\DBAL\\\\Connection->setTransactionIsolation(2)\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DriverManager.php(172): OC\\\\DB\\\\Connection->__construct(Array, Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#6 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/DB\\\/ConnectionFactory.php(145): Doctrine\\\\DBAL\\\\DriverManager::getConnection(Array, Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#7 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Server.php(487): OC\\\\DB\\\\ConnectionFactory->getConnection('mysql', Array)\\n#8 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#9 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(111): Pimple\\\\Container->offsetGet('DatabaseConnect...')\\n#10 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('DatabaseConnect...')\\n#11 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Server.php(1147): OC\\\\ServerContainer->query('DatabaseConnect...')\\n#12 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Server.php(239): OC\\\\Server->getDatabaseConnection()\\n#13 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#14 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(111): Pimple\\\\Container->offsetGet('AccountMapper')\\n#15 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('AccountMapper')\\n#16 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Server.php(999): OC\\\\ServerContainer->query('AccountMapper')\\n#17 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Server.php(244): OC\\\\Server->getAccountMapper()\\n#18 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#19 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(111): Pimple\\\\Container->offsetGet('UserManager')\\n#20 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('UserManager')\\n#21 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Server.php(992): OC\\\\ServerContainer->query('UserManager')\\n#22 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Server.php(288): OC\\\\Server->getUserManager()\\n#23 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#24 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(111): Pimple\\\\Container->offsetGet('UserSession')\\n#25 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('UserSession')\\n#26 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Server.php(1016): OC\\\\ServerContainer->query('UserSession')\\n#27 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Server.php(541): OC\\\\Server->getUserSession()\\n#28 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#29 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(111): Pimple\\\\Container->offsetGet('AppManager')\\n#30 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('AppManager')\\n#31 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Server.php(1346): OC\\\\ServerContainer->query('AppManager')\\n#32 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(343): OC\\\\Server->getAppManager()\\n#33 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(111): OC_App::getEnabledApps()\\n#34 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(579): OC_App::loadApps(Array)\\n#35 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1014): OC::init()\\n#36 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(54): require_once('\\\/usr\\\/share\\\/ngin...')\\n#37 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php\",\"Line\":64}"}`

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by mmattel** [comment]
Please add the corresponding owncloud log element(s).
Have you monitored server memory consumption?
Did you read the nginx part in the documentation (admin_manual/installation/nginx_configuration).
The changelog of 10.0.4 mentions "Disable nginx buffering for file downloads to avoid huge memory usage in some scenarios"

**Comment by deounix** [comment]
@mmattel No thing in owncloud.log.

This happened after upgrade owncloud from v10.0.3.3 to v10.0.4.4 I can't upload files more than 1G in owncloud v10.0.3.3 every thing working 100% and I didn't edit nginx config or any thing.

example : upload 3G file

![pic-20171228-212715](https://user-images.githubusercontent.com/17798647/34421106-f3217422-ec15-11e7-9eec-26b12707f61a.png)

uploading done then still showing (Processing files ...) and when I open to see what happened in Server

![pic-20171228-212937](https://user-images.githubusercontent.com/17798647/34421149-3b7983ea-ec16-11e7-809d-f33941c171cd.png)

Less than 1G uploaded

**Comment by individual-it** [comment]
owncloud config and list of installed apps would be helpful (see issue template)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
