### ISSUE TITLE
Encryption app load causes integrity exception inserting to user mount table

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#30105]
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'NB20430-5374084' for key 'mounts_user_root_index'","Code":0,"Trace":"
#0 /var/www/html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1015): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO `oc...', Array)
#2 /var/www/html/owncloud/lib/private/DB/Connection.php(211): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)
#3 /var/www/html/owncloud/lib/private/DB/Adapter.php(113): OC\DB\Connection->executeUpdate('INSERT INTO `oc...', Array)
#4 /var/www/html/owncloud/lib/private/DB/Connection.php(249): OC\DB\Adapter->insertIfNotExist('*PREFIX*mounts', Array, Array)
#5 /var/www/html/owncloud/lib/private/Files/Config/UserMountCache.php(140): OC\DB\Connection->insertIfNotExist('*PREFIX*mounts', Array, Array)
#6 /var/www/html/owncloud/lib/private/Files/Config/UserMountCache.php(120): OC\Files\Config\UserMountCache->addToCache(Object(OC\Files\Config\LazyStorageMountInfo))
#7 /var/www/html/owncloud/lib/private/Files/Config/MountProviderCollection.php(134): OC\Files\Config\UserMountCache->registerMounts(Object(OC\User\User), Array)
#8 /var/www/html/owncloud/lib/private/Files/Filesystem.php(448): OC\Files\Config\MountProviderCollection->registerMounts(Object(OC\User\User), Array)
#9 /var/www/html/owncloud/lib/private/Files/Filesystem.php(375): OC\Files\Filesystem::initMountPoints('NB20430')
#10 /var/www/html/owncloud/lib/private/legacy/util.php(297): OC\Files\Filesystem::init('NB20430', '/NB20430/files')
#11 /var/www/html/owncloud/lib/private/Files/Filesystem.php(353): OC_Util::setupFS()
#12 /var/www/html/owncloud/lib/private/Files/View.php(1114): OC\Files\Filesystem::resolvePath('/files_encrypti...')
#13 /var/www/html/owncloud/lib/private/Files/View.php(524): OC\Files\View->basicOperation('file_exists', '/files_encrypti...')
#14 /var/www/html/owncloud/lib/private/Encryption/Keys/Storage.php(215): OC\Files\View->file_exists('/files_encrypti...')
#15 /var/www/html/owncloud/lib/private/Encryption/Keys/Storage.php(112): OC\Encryption\Keys\Storage->getKey('/files_encrypti...')
#16 /var/www/html/owncloud/apps/encryption/lib/KeyManager.php(569): OC\Encryption\Keys\Storage->getSystemUserKey('pubShare_12fe8c...', 'OC_DEFAULT_MODU...')
#17 /var/www/html/owncloud/apps/encryption/lib/KeyManager.php(157): OCA\Encryption\KeyManager->getPublicShareKey()
#18 /var/www/html/owncloud/apps/encryption/lib/Users/Setup.php(85): OCA\Encryption\KeyManager->validateShareKey()
#19 /var/www/html/owncloud/apps/encryption/lib/AppInfo/Application.php(72): OCA\Encryption\Users\Setup->setupSystem()
#20 /var/www/html/owncloud/apps/encryption/appinfo/app.php(30): OCA\Encryption\AppInfo\Application->__construct(Array, true)
#21 /var/www/html/owncloud/lib/private/legacy/app.php(213): require_once('/var/www/html/o...')
#22 /var/www/html/owncloud/lib/private/legacy/app.php(164): OC_App::requireAppFile('encryption')
#23 /var/www/html/owncloud/lib/private/legacy/app.php(121): OC_App::loadApp('encryption')
#24 /var/www/html/owncloud/lib/private/legacy/util.php(145): OC_App::loadApps(Array)
#25 /var/www/html/owncloud/lib/private/Files/Filesystem.php(265): OC_Util::setupFS('')
#26 /var/www/html/owncloud/lib/private/Server.php(212): OC\Files\Filesystem::getMountManager(NULL)
#27 /var/www/html/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#28 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('RootFolder')
#29 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('RootFolder')
#30 /var/www/html/owncloud/lib/private/Server.php(906): OC\ServerContainer->query('RootFolder')
#31 /var/www/html/owncloud/lib/private/Server.php(405): OC\Server->getRootFolder()
#32 /var/www/html/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#33 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('AvatarManager')
#34 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AvatarManager')
#35 /var/www/html/owncloud/lib/private/Server.php(897): OC\ServerContainer->query('AvatarManager')
#36 /var/www/html/owncloud/apps/user_ldap/lib/Proxy.php(70): OC\Server->getAvatarManager()
#37 /var/www/html/owncloud/apps/user_ldap/lib/Proxy.php(91): OCA\User_LDAP\Proxy->addAccess('s01')
#38 /var/www/html/owncloud/apps/user_ldap/lib/User_Proxy.php(48): OCA\User_LDAP\Proxy->getAccess('s01')
#39 /var/www/html/owncloud/apps/user_ldap/appinfo/app.php(36): OCA\User_LDAP\User_Proxy->__construct(Array, Object(OCA\User_LDAP\LDAP), Object(OC\AllConfig))
#40 /var/www/html/owncloud/lib/private/legacy/app.php(213): require_once('/var/www/html/o...')
#41 /var/www/html/owncloud/lib/private/legacy/app.php(164): OC_App::requireAppFile('user_ldap')
#42 /var/www/html/owncloud/lib/private/legacy/app.php(121): OC_App::loadApp('user_ldap')
#43 /var/www/html/owncloud/remote.php(149): OC_App::loadApps(Array)
```

10.0.2

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are #27122 (error running cron.php), #16252 (Integrity Constraint Violations in server log file after running smashbox tests), #24882 (Duplicate entry for key lock_key_index - UniqueConstraintViolationException), #13427 (Fatal error installing latest master), and #13578 (Unknown error when access a remote share after remote sharing has been disabled).

**Comment by PVince81** [comment]
@tomneedham I seem to remember you mentioning that it could be an insertIfNotExists bug ? Maybe we can replace this one call with upsert ? I'm assigning you until we get more details.

**Comment by tomneedham** [comment]
Created an issue to properly track rewriting insertIfNotExists https://github.com/owncloud/core/issues/30119

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by PVince81** [comment]
not enough context to debug, leaving closed for now unless @tomneedham has more info
