### ISSUE TITLE
Previews in trashbin do not work

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#30189]
### Steps to reproduce
1. delete a file
2. check the trashbin

### Expected behaviour
files in trashbin should have a preview

### Actual behaviour
no previews are shown
![screenshot-2018-1-19 deleted files - owncloud](https://user-images.githubusercontent.com/2425577/35142778-717faf42-fd27-11e7-9070-d72cd5453d93.png)

Problem seems to have started with #29319 

### Server configuration
**Operating system**:
Ubuntu 17.10
**Web server:**
Apache2
**Database:**
Sqlite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
10.0.5 (git)
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git
**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc9xsmdtnlru",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "sqlite3",
        "logtimezone": "UTC",
        "installed": true,
        "default_language": "en",
        "theme": "",
        "loglevel": "0",
        "maintenance": false,
        "log_type": "owncloud",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "debug": false,
        "version": "10.0.5.2",
        "csrf.disabled": true,
        "files_external_allow_create_new_local": "true",
        "singleuser": false,
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "csrf.disabled=false": "",
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/tests\/ui\/skeleton",
        "mysql.utf8mb4": true,
        "firewall.rules": "[]"
    }
}

```

**List of activated apps:**

```Enabled:
  - comments: 0.3.0
  - dav: 0.3.2
  - diagnostics: 0.1.0
  - enterprise_key: 0.1.3
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_texteditor: 2.2
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firewall: 2.4.2
  - gallery: 16.0.2
  - market: 0.2.3
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - testing: 0.1.0
  - updatenotification: 0.2.1
Disabled:
  - customgroups
  - files_antivirus
  - multidirtest
  - notifications
  - password_policy
  - security
  - theme-example
  - user_ldap
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF 57
**Operating system:**
Ubuntu 17.10
#### ownCloud log (data/owncloud.log)
```
{"reqId":"bCgr4nX1T5eb4JXyMZXR","level":3,"time":"2018-01-19T09:04:54+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"index","method":"GET","url":"\/owncloud-core\/index.php\/apps\/files_trashbin\/ajax\/preview.php?file=%2Florem.txt.d1516351157&c=1516351157000","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OC\\\\Preview::__construct() must implement interface OCP\\\\Files\\\\Node or be null, string given, called in \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/files_trashbin\\\/ajax\\\/preview.php on line 51\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/files_trashbin\\\/ajax\\\/preview.php(51): OC\\\\Preview->__construct('admin', 'files_trashbin\\\/...', '\\\/lorem.txt.d151...')\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/home\\\/artur\\\/www...')\\n#2 [internal function]: OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(NULL)\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(Closure), Array)\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/base.php(915): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_tra...')\\n#5 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/index.php(55): OC::handleRequest()\\n#6 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Preview.php\",\"Line\":112}"}
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.
