### ISSUE TITLE
SMB does not handle too less space available messages properly in upload situations

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#30243]
### Steps to reproduce
1. Having a SMB mount which is almost full
2. Upload a file which is bigger than the free space

### Expected behaviour
SMB should tell that it is low on storage.

### Actual behaviour
This is what a windows direct mount tells me
![image](https://user-images.githubusercontent.com/3321281/35290060-5a9459d2-0069-11e8-8800-a11e25a130e5.png)

This is what ownCloud tells me
![image](https://user-images.githubusercontent.com/3321281/35290011-39cf5792-0069-11e8-8be4-43a78aff8560.png)

**Looking into the mount on the fileserver, you find as many .part files as you tried to upload**

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.4

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
no issues
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oct7bkicorxf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxx",
        "dbtype": "mysql",
        "version": "10.0.4.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "filesystem_check_changes": 1,
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_from_address": "xxx",
        "mail_smtpsecure": "tls",
        "mail_domain": "xxx",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "xxx",
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "preview_max_scale_factor": 1,
        "excluded_directories": [
            ".snapshot",
            "~snapshot"
        ],
        "upgrade.automatic-app-update": true,
        "quota_include_external_storage": false,
        "singleuser": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ]
    }
}

```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_clipboard: 0.6.5
  - files_external: 0.7.1
  - files_external_dropbox: 1.0.0
  - files_external_ftp: 0.2.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.3
  - music: 0.5.5
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** local, smb, ftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera

**Operating system:** W10x64

#### Web server error log
```
not relevant
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"0geKbDTIAdO1EzFjHf5f","level":4,"time":"2018-01-23T18:05:48+01:00","remoteAddr":"x.y.z.w","user":"user_x","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/rosa%40filer\/2HMA\/Erl\/20180123_Betriebspraktikum.pdf","message":"Exception: {\"Message\":\"Unknown error (16) for smb:\\\/\\\/filer\\\/rosa\\\/2HMA\\\/Erl\\\/20180123_Betriebspraktikum.pdf.ocTransferId740742595.part\",\"Exception\":\"Icewind\\\\SMB\\\\Exception\\\\Exception\",\"Code\":16,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(72): Icewind\\\\SMB\\\\NativeState->handleError('smb:\\\/\\\/filer\\\/ros...')\\
n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(146): Icewind\\\\SMB\\\\NativeState->testResult(false, 'smb:\\\/\\\/filer\\\/ros...')\\
n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(150): Icewind\\\\SMB\\\\NativeState->unlink('smb:\\\/\\\/filer\\\/ros...')\\
n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(368): Icewind\\\\SMB\\\\NativeShare->del('\\\/2HMA\\\/Erl\\\/20180...')\\
n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(261): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->unlink('\\\/2HMA\\\/Erl\\\/20180...')\\
n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(284): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->unlink('2HMA\\\/Erl\\\/201801...')\\
n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(261): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->unlink('2HMA\\\/Erl\\\/201801...')\\
n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(261): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->unlink('2HMA\\\/Erl\\\/201801...')\\
n#8 [internal function]: OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->unlink('2HMA\\\/Erl\\\/201801...')\\
n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(169): call_user_func_array(Array, Array)\\
n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(120): OCA\\\\Files_Trashbin\\\\Storage->doDelete('2HMA\\\/Erl\\\/201801...', 'unlink')\\
n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(181): OCA\\\\Files_Trashbin\\\\Storage->unlink('2HMA\\\/Erl\\\/201801...')\\
n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(171): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #76)\\
n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('20180123_Betrie...', Resource id #76)\\
n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('rosa@filer\\\/2HMA...', Resource id #76, NULL)\\
n#15 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\
n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\
n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\
n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\
n#19 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\
n#20 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/w...')\\
n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php\",\"Line\":66,\"User\":\"user_x\"}"}
```

#### Browser log
```
not relevant
```

@PVince81 @jvillafanez

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @PVince81, and @jvillafanez.

**Comment by jvillafanez** [comment]
Since there are plans to update the library, I'd rather wait until the update is merged and tested.

Nervertheless, we'll need to recheck this scenario. The error code 16 matches a "device or resouce busy" error, not a "disk full" one. I'm not sure if you have some kind of quota limitation or something similar in the windows machine, or if the "disk full" error happens when the whole disk is full, not just a partition.

**Comment by mmattel** [comment]
@jvillafanez It is necessary to document current behaviour and look on changes/improvements by the update and how/what we can test or add to tests. You btw remember our discussion regarding "must", "should", "is" .. 😄

**Comment by mmattel** [comment]
SMB is access to an external Windows based filesystem, whatever structure you have underneath. 
It does not know about that structure. It is unaware about disks, raid, partitions ect
It is even not aware about quotas as this is managed by the filesystem it accesses.
As long you do not own the filesystem (= local) this is true for all storage types.

This issue is about, that if you upload a file which is bigger than the available space, you get a undefined error message not pointing to the real cause.

**This highlights two things to be covered:**
1. get the right error message
2. check for available space BEFORE you try to upload from source (browser, client) to ownCloud
Preferred

or

2. check for available space BEFORE you try to upload from ownCloud to SMB
Second Choice

**ad 1**
https://github.com/eduardok/libsmbclient-php
The corrected error code for disk full is: ``ENOSPC 28 No space left on device``
Which gets triggered WHILE uploading from owncloud to SMB.
Needs checking why this one did not came up.

**ad 2**
I do no know if we currently do that for any storage implementation, would be a good idea, but for SMB we could do:
``array smbclient_statvfs ( resource $state, string $uri )``
Free Space = ``bsize`` (file system block size) x ``bfree`` (number of free blocks)
In case we do not get proper information, take unlimited (like -1) and if something goes wrong, we get 1.) anyways.

**Comment by mmattel** [comment]
Free space available for dropbox see: https://stackoverflow.com/questions/14853410/dropbox-api-how-can-i-get-the-amount-of-remaining-free-space
