### ISSUE TITLE
Do not let enable server encryption when there is no module loaded

### ISSUE THREAD

**Issue by davitol** [owncloud/core#30280]
If we enable server-side encryption without a module available we get:
![screen shot 2018-01-25 at 16 27 10](https://user-images.githubusercontent.com/10596560/35396443-1d186a5a-01ed-11e8-8258-41cafe3c6533.png)

So later if we do not have a module, we cannot revert the status and for example we cannot share a file via link.
![screen shot 2018-01-25 at 16 27 35](https://user-images.githubusercontent.com/10596560/35396678-a2e2b94c-01ed-11e8-985f-d5e5885304d7.png)

Should we disable that option until a encryption module is available?

**Comment by davitol** [comment]
Or trying to get a previous version of a file, the spinner keeps loading forever

```
{"reqId":"SXcJpOi61kX38PVPGacf","level":3,"time":"2018-01-25T15:42:26+00:00","remoteAddr":"85.57.168.79","user":"admin","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files_versions\/ajax\/getVersions.php?source=%2Fpepe.txt&start=0","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\ModuleDoesNotExistsException\",\"Message\":\"Module with id: OC_DEFAULT_MODULE does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(1001): OC\\\\Encryption\\\\Manager->getEncryptionModule('OC_DEFAULT_MODU...')\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(543): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getEncryptionModule('files_versions\\\/...')\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(518): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fixUnencryptedSize('files_versions\\\/...', 10, 10)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(166): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->verifyUnencryptedSize('files_versions\\\/...', 10)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(149): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->filesize('files_versions\\\/...')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(149): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filesize('files_versions\\\/...')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1183): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filesize('files_versions\\\/...')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(428): OC\\\\Files\\\\View->basicOperation('filesize', 'files_versions\\\/...')\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(463): OC\\\\Files\\\\View->filesize('\\\/files_versions...')\\n#9 \\\/opt\\\/owncloud\\\/apps\\\/files_versions\\\/ajax\\\/getVersions.php(35): OCA\\\\Files_Versions\\\\Storage::getVersions('admin', 'pepe.txt', '\\\/pepe.txt')\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#11 [internal function]: OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(NULL)\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(Closure), Array)\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ver...')\\n#14 \\\/opt\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/Encryption\\\/Manager.php\",\"Line\":198}"}
{"reqId":"ogOwLNIpVkyrjM21mvvR","level":3,"time":"2018-01-25T15:42:43+00:00","remoteAddr":"85.57.168.79","user":"admin","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files_versions\/ajax\/rollbackVersion.php?file=%2Fpepe.txt&revision=1516893683","message":"Encryption module defined in \"files\/pepe.txt\" not loaded!"}
```

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
