### ISSUE TITLE
occ no longer works correctly

### ISSUE THREAD

**Issue by riccardopirani** [owncloud/core#30305]
**Steps to reproduce**

1. enter into directory owncloud /var/ww/owncloud
2. call occ with this command: sudo -u www-data php occ
3. Display error

**Expected behaviour**
When i run occ i have this error: An unhandled exception has been thrown:
OCP\AppFramework\QueryException: Could not resolve CardDavBackend! Class CardDavBackend does not exist in /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php:98
Stack trace:
#0 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(113): OC\AppFramework\Utility\SimpleContainer->resolve('CardDavBackend')
#1 /var/www/owncloud/apps/dav/appinfo/registercommand.php(36): OC\AppFramework\Utility\SimpleContainer->query('CardDavBackend')_
#2 /var/www/owncloud/lib/private/Console/Application.php(115): require('/var/www/ownclo...')
#3 /var/www/owncloud/console.php(105): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/owncloud/occ(11): requireonce('/var/www/ownclo...')_

**Server configuration**

**Operating system:** Ubuntu Server 16.04.3 LTS

**Web server:** Apache 2.4.18

**Database:** MySQL

**PHP version:** 7.0.22

**ownCloud version:** ownCloud 10.0.4 (stable)

**Updated from an older ownCloud or fresh install:** Updated from an older ownCloud

**Where did you install ownCloud from:** owncloud.org

**Integrity Failder Link Gist:** https://gist.github.com/riccardopirani/5477f0f657545937800648c51949b61a

**List of activated apps:**
-- occ not work -- 
**List of app enable Image**: https://imgur.com/a/RcnJ8

**Are you using external storage, if yes which one**: smb server

**Are you using encryption**:  no

**Client configuration**
**Browser**: chrome
**Operating system**: windows

**Comment by PVince81** [comment]
Are you getting errors regarding integrity check ? It is likely that something went wrong with the source code update ?

**Comment by riccardopirani** [comment]
@PVince81  Yes from i see integrity error from WebSite! but how can I solve it since - OCC- does not work?

**Comment by PVince81** [comment]
you could delete the source code (but keep "config" and "data" folders) and replace it with the code from the 10.0.4 tarball: https://dl-oo.owncloud.org/community/owncloud-10.0.4.tar.bz2

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by Blindfreddy** [comment]
Please reopen, I have the same problem with the exact same error message running on raspbian jessie, php 5.6.33, apache 2.4.10, owncloud 10.0.8.5.

**Comment by DeepDiver1975** [comment]
> /var/www/owncloud/apps/dav/appinfo/registercommand.php(36):

this file was removed long time ago - see https://github.com/owncloud/core/tree/v10.0.4/apps/dav/appinfo

You did not follow the update procedure properly and have now a system in mixed state.

see https://doc.owncloud.org/server/latest/admin_manual/maintenance/upgrade.html?highlight=update#upgrading-from-9-1-to-version

**Comment by Blindfreddy** [comment]
Ok thanks - I followed the instructions but using 10.0.8 - all works now. Thanks.

Not sure how I ended up with a botched installation but it's academic now.
