### ISSUE TITLE
database deadlock when generating previews

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#30320]
### Steps to reproduce
1. get unlucky in running UI tests

#### ownCloud log (data/owncloud.log)
```
{"reqId":"oPP3QPj1L8F6lOIgd4nb","level":4,"time":"2018-01-30T20:50:27+00:00","remoteAddr":"172.27.0.3","user":"regularuser","app":"webdav","method":"GET","url":"\/remote.php\/dav\/files\/regularuser\/desktopapp.png?c=07bc6a6512db23736c566711a209f6fe&x=32&y=32&forceIcon=0&preview=1","message":"Exception: {\"Message\":\"An exception occurred while executing 'UPDATE `oc_filecache` SET `mtime` = GREATEST(`mtime`, ?), `etag` = ? WHERE (`storage` = ?) AND (`path_hash` IN ('d41d8cd98f00b204e9800998ecf8427e', '3b8779ba05b8f0aed49650f3ff8beb4b', '10839542e3644c5dc1304148ac609aa6'))' with params [1517345427, \\\"5a70da939bd85\\\", 6]:\\n\\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/drone\\\/src\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/drone\\\/src\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_file...', Array)\\n#2 \\\/drone\\\/src\\\/lib\\\/private\\\/DB\\\/Connection.php(210): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\\n#3 \\\/drone\\\/src\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\\n#4 \\\/drone\\\/src\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/drone\\\/src\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php(87): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/drone\\\/src\\\/lib\\\/private\\\/Files\\\/Cache\\\/HomePropagator.php(48): OC\\\\Files\\\\Cache\\\\Propagator->propagateChange('thumbnails\\\/488\\\/...', 1517345427, 2449)\\n#7 \\\/drone\\\/src\\\/lib\\\/private\\\/Files\\\/Cache\\\/Updater.php(138): OC\\\\Files\\\\Cache\\\\HomePropagator->propagateChange('thumbnails\\\/488\\\/...', 1517345427, 2449)\\n#8 \\\/drone\\\/src\\\/lib\\\/private\\\/Files\\\/View.php(331): OC\\\\Files\\\\Cache\\\\Updater->update('thumbnails\\\/488\\\/...', 1517345427)\\n#9 \\\/drone\\\/src\\\/lib\\\/private\\\/Files\\\/View.php(1202): OC\\\\Files\\\\View->writeUpdate(Object(OCA\\\\Files_Trashbin\\\\Storage), 'thumbnails\\\/488\\\/...')\\n#10 \\\/drone\\\/src\\\/lib\\\/private\\\/Files\\\/View.php(713): OC\\\\Files\\\\View->basicOperation('file_put_conten...', '\\\/thumbnails\\\/488...', Array, '\\\\x89PNG\\\\r\\\\n\\\\x1A\\\\n\\\\x00\\\\x00\\\\x00\\\\rIHD...')\\n#11 \\\/drone\\\/src\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}()\\n#12 \\\/drone\\\/src\\\/lib\\\/private\\\/Files\\\/View.php(715): OC\\\\Files\\\\View->emittingCall(Object(Closure), Array, 'file', 'update')\\n#13 \\\/drone\\\/src\\\/lib\\\/private\\\/Preview.php(1194): OC\\\\Files\\\\View->file_put_contents('thumbnails\\\/488\\\/...', '\\\\x89PNG\\\\r\\\\n\\\\x1A\\\\n\\\\x00\\\\x00\\\\x00\\\\rIHD...')\\n#14 \\\/drone\\\/src\\\/lib\\\/private\\\/Preview.php(1141): OC\\\\Preview->storeMaxPreview('thumbnails\\\/488\\\/...')\\n#15 \\\/drone\\\/src\\\/lib\\\/private\\\/Preview.php(762): OC\\\\Preview->generatePreview()\\n#16 \\\/drone\\\/src\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(166): OC\\\\Preview->getPreview()\\n#17 \\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/Files\\\/PreviewPlugin.php(93): OC\\\\Files\\\\Node\\\\File->getThumbnail(Array)\\n#18 [internal function]: OCA\\\\DAV\\\\Files\\\\PreviewPlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#20 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#21 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#22 \\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/Server.php(279): Sabre\\\\DAV\\\\Server->exec()\\n#23 \\\/drone\\\/src\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#24 \\\/drone\\\/src\\\/remote.php(175): require_once('\\\/drone\\\/src\\\/apps...')\\n#25 {main}\",\"File\":\"\\\/drone\\\/src\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115,\"User\":\"regularuser\"}"}
```

**Comment by PVince81** [comment]
The weird thing here is that this is a GET request but it still propagates etag. It seems to be related to thumbnail generation.

We should disable etag propagation when operating on the "thumbnails" or "gallery" folders.

@DeepDiver1975

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by PVince81** [comment]
@jvillafanez can we disable etag propagation on previews ?

**Comment by jvillafanez** [comment]
Probably not, the access to the previews uses a View object with everything it has...

**Comment by csware** [comment]
I get lots of similar log entries, however, for PUT (using MariaDB, no galera cluster, owncloud 10.0.10):

    {"reqId":"402fc379-d934-4b44-9301-35c221de1869","level":3,"time":"2018-11-30T10:54:34+01:00","remoteAddr":"x.xx.x.x","user":"USERNAME","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/files\/USERNAME\/path\/x%20x%20-%20x%20x%20x%20X%C3%B6xx.mp3","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_filecache` SET `mtime` = GREATEST(`mtime`, ?), `etag` = '5c0108da48690' WHERE (`storage` = '17') AND (`path_hash` = ?)' with params [1543571674, \\\"3b8779ba05b8f0aed49650f3ff8beb4b\\\"]:\\n\\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_file...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(207): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php(176): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(423): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(1326): OC\\\\Preview->deleteAllPreviews()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(1223): OC\\\\Preview::post_delete(Array, 'files\\\/')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OC\\\\Preview::post_write(Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(374): OC_Hook::emit('OC_Filesystem', 'post_write', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(286): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->emitPostHooks(true)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1129): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #530)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('files\\\/sven+ownc...', Resource id #530, NULL)\\n#14 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(298): Sabre\\\\DAV\\\\Server->exec()\\n#19 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#20 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/cloud....')\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}"}

**Comment by PVince81** [comment]
> Probably not, the access to the previews uses a View object with everything it has...

the etag propagator has a whitelist or blacklist of folders to propagate to, so it's likely just a matter of adding the preview/thumbnail folders there

**Comment by DeepDiver1975** [comment]
🤖 Automated issue triage by Claude Code review agent.

This issue was opened before 2020 and has had no activity since then, so we are closing it as outdated. If this is still relevant on a current ownCloud release, please **reopen** (or open a fresh issue) with up-to-date details — thank you!
