### ISSUE TITLE
occ command's unhandled exception stack trace is output to the console

### ISSUE THREAD

**Issue by settermjd** [owncloud/core#30322]
### Steps to reproduce

I can't speak for every occurrence of this, but if you run `occ upgrade` when the web UI renders "Please check that the data directory contains a file ".ocdata" in its root.", then a PHP stack trace similar to the following will be output to the console:

```console
An unhandled exception has been thrown:
exception 'Exception' with message 'Environment not properly prepared.' in /var/www/owncloud-10.0.4/lib/private/Console/Application.php:135
Stack trace:
#0 /var/www/owncloud-10.0.4/console.php(105): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/owncloud-10.0.4/occ(11): require_once('/var/www/ownclo...')
#2 {main}
```

### Expected behaviour

I'd expect that only the following message would be output to the console:

```console
Your data directory is invalid
Please check that the data directory contains a file ".ocdata" in its root.
```

### Actual behaviour

```console
sudo -u www-data ./occ upgrade
Your Data directory  is invalid
Please check that the data directory contains a file ".ocdata" in its root.

An unhandled exception has been thrown:
exception 'Exception' with message 'Environment not properly prepared.' in /var/www/owncloud-10.0.4/lib/private/Console/Application.php:135
Stack trace:
#0 /var/www/owncloud-10.0.4/console.php(105): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/owncloud-10.0.4/occ(11): require_once('/var/www/ownclo...')
#2 {main}
```

### Server configuration

**Operating system**: Ubuntu 14.04.5 LTS

**Web server:** Apache 2

**Database:** MariaDB Ver 15.1 Distrib 5.5.57-MariaDB

**PHP version:** PHP 5.6.33-1+ubuntu14.04.1+deb.sury.org+1 (cli) 

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** A clone of the master branch

**Comment by settermjd** [comment]
The exception is thrown in https://github.com/owncloud/core/blob/master/lib/private/Console/Application.php#L135. I'd suggest that it'd be better to just log the information, instead of throwing an exception.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
