### ISSUE TITLE
Error PHP hash_equals() function in Log.php line 288

### ISSUE THREAD

**Issue by Dallo71** [owncloud/core#30388]
### Steps to reproduce
1. On my system every occ command give me the warning
2. I found the warning in all log files

### Expected behaviour
Not have the warning

### Actual behaviour
**PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/owncloud/lib/private/Log.php on line 288**

### Server configuration
**Operating system**:
Linux Debian 8
Linux MD-FE 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Sep 20 2017 04:37:43

**Database:**
mysql  Ver 14.14 Distrib 5.5.59, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.6.33-0+deb8u1 (cli) (built: Jan  5 2018 15:46:26)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
version	10.0.4.4
versionstring	10.0.4
edition	Community
productname	MOREdrive

**Updated from an older ownCloud or fresh install:**
updated from 9.2 (and from all other old versions)

**Where did you install ownCloud from:**
Linux Distribution Packages Debian

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**The content of config/config.php:**
```shell
root@MD-FE www/owncloud# occ config:list system
PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/owncloud/lib/private/Log.php on line 288
{
    "system": {
        "version": "10.0.4.4",
        "installed": true,
        "updatechecker": false,
        "instanceid": "oclho491kcbx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "moredrive.unimore.it"
        ],
        "datadirectory": "\/var\/MOREdrive-data",
        "overwrite.cli.url": "https:\/\/moredrive.unimore.it",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "log_type": "owncloud",
        "logfile": "\/var\/www\/owncloud\/data\/log\/owncloud.log",
        "loglevel": 2,
        "log.condition": {
            "shared_secret": "***REMOVED SENSITIVE VALUE***",
            "users": [
                "***REMOVED SENSITIVE VALUE***"
            ]
        },
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Rome",
        "log_query": false,
        "cron_log": true,
        "log_rotate_size": 104857600,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0
        },
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "appstore.experimental.enabled": true,
        "theme": "",
        "mail_from_address": "supporto.moredrive",
        "mail_domain": "unimore.it",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp-relay.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_filesize_image": 50,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "maintenance": false,
        "singleuser": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "excluded_directories": [
            "\/var\/www\/owncloud\/themes\/MOREdrive\/",
            "\/var\/www\/owncloud\/apps\/piwik\/",
            "\/var\/www\/owncloud\/apps\/html5_videoplayer\/",
            "\/var\/www\/owncloud\/apps\/files_videojs-sublime\/"
        ],
        "integrity.excluded.files": [
            "README.md"
        ]
    }
}
```

**List of activated apps:**
```shell
root@MD-FE www/owncloud# occ app:list
PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/owncloud/lib/private/Log.php on line 288
Enabled:
  - announcementcenter: 1.2.0
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - encryption: 1.3.1
  - external: 1.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videojs-sublime: 0.9.8
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - html5_videoplayer: 1.0
  - impersonate: 0.1.2
  - market: 0.2.3
  - music: 0.5.5
  - notifications: 0.3.2
  - piwik: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - theme-MOREdrive: 1.0.0
  - updatenotification: 0.2.1
  - user_external: 0.4
  - user_ldap: 0.10.0
Disabled:
  - mail
  - theme-example
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
```shell
root@MD-FE www/owncloud# occ ldap:show-config
PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/owncloud/lib/private/Log.php on line 288
+-------------------------------+-------------------------------------------------------------------------------------------------+
| Configuration                 | s02                                                                                             |
+-------------------------------+-------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                                 |
| hasPagedResultSupport         |                                                                                                 |
| homeFolderNamingRule          |                                                                                                 |
| lastJpegPhotoLookup           | 0                                                                                               |
| ldapAgentName                 | cn=owncloud,ou=agents,dc=unimore,dc=it                                                          |
| ldapAgentPassword             | ***                                                                                             |
| ldapAttributesForGroupSearch  | cn                                                                                              |
| ldapAttributesForUserSearch   | sn;cn;uid                                                                                       |
| ldapBackupHost                |                                                                                                 |
| ldapBackupPort                |                                                                                                 |
| ldapBase                      | dc=unimore,dc=it                                                                                |
| ldapBaseGroups                | ou=bushygroups,dc=unimore,dc=it                                                                 |
| ldapBaseUsers                 | dc=unimore,dc=it                                                                                |
| ldapCacheTTL                  | 600                                                                                             |
| ldapConfigurationActive       | 1                                                                                               |
| ldapDynamicGroupMemberURL     |                                                                                                 |
| ldapEmailAttribute            | unimoremailprincipale                                                                           |
| ldapExperiencedAdmin          | 1                                                                                               |
| ldapExpertUUIDGroupAttr       |                                                                                                 |
| ldapExpertUUIDUserAttr        | entryuuid                                                                                       |
| ldapExpertUsernameAttr        | uid                                                                                             |
| ldapGroupDisplayName          | cn                                                                                              |
| ldapGroupFilter               | (&(objectclass=unimoreBushyGroup)(|(ou=unimore)(ou=moredrive)))                                 |
| ldapGroupFilterGroups         |                                                                                                 |
| ldapGroupFilterMode           | 0                                                                                               |
| ldapGroupFilterObjectclass    | unimoreGroup                                                                                    |
| ldapGroupMemberAssocAttr      | member                                                                                          |
| ldapHost                      | ***                                                                                             |
| ldapIgnoreNamingRules         |                                                                                                 |
| ldapLoginFilter               | uid=%uid                                                                                        |
| ldapLoginFilterAttributes     |                                                                                                 |
| ldapLoginFilterEmail          | 0                                                                                               |
| ldapLoginFilterMode           | 1                                                                                               |
| ldapLoginFilterUsername       | 1                                                                                               |
| ldapNestedGroups              | 0                                                                                               |
| ldapOverrideMainServer        |                                                                                                 |
| ldapPagingSize                | 500                                                                                             |
| ldapPort                      | 636                                                                                             |
| ldapQuotaAttribute            |                                                                                                 |
| ldapQuotaDefault              |                                                                                                 |
| ldapTLS                       | 0                                                                                               |
| ldapUserDisplayName           | cn                                                                                              |
| ldapUserDisplayName2          | unimoremailprincipale                                                                           |
| ldapUserFilter                | (&(|(ou=dipendenti)(ou=esterni)(ou=dottorandi)(ou=specializzandi))(objectclass=unimoreAccount)) |
| ldapUserFilterGroups          |                                                                                                 |
| ldapUserFilterMode            | 1                                                                                               |
| ldapUserFilterObjectclass     | unimoreAccount                                                                                  |
| ldapUuidGroupAttribute        | auto                                                                                            |
| ldapUuidUserAttribute         | auto                                                                                            |
| turnOffCertCheck              | 0                                                                                               |
| useMemberOfToDetectMembership | 1                                                                                               |
+-------------------------------+-------------------------------------------------------------------------------------------------+
```
### Client configuration
**Browser:**
Latest version of Chrome, Firefos, Internet Explorer

**Operating system:**
Windows 10 and Debian 8

#### Web server error log
```shell
/var/log/apache2/error.log

[Tue Feb 06 15:36:31.266741 2018] [:error] [pid 1203] [client 178.192.20.76:53097] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/owncloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/owncloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doc in /var/www/owncloud/lib/private/DB/Connection.php on line 64
[Tue Feb 06 15:36:31.288243 2018] [:error] [pid 1204] [client 155.185.36.182:64543] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/owncloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/owncloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doc in /var/www/owncloud/lib/private/DB/Connection.php on line 64
[Tue Feb 06 15:36:31.289372 2018] [:error] [pid 1204] [client 155.185.36.182:64543] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/owncloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/owncloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doc in /var/www/owncloud/lib/private/DB/Connection.php on line 64
[Tue Feb 06 15:36:31.623676 2018] [:error] [pid 1205] [client 91.253.4.238:8449] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/owncloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/owncloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doc in /var/www/owncloud/lib/private/DB/Connection.php on line 64
[Tue Feb 06 15:36:31.624449 2018] [:error] [pid 1205] [client 91.253.4.238:8449] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/owncloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/owncloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doc in /var/www/owncloud/lib/private/DB/Connection.php on line 64
[Tue Feb 06 15:36:31.750655 2018] [:error] [pid 1206] [client 155.185.166.204:52703] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/owncloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/owncloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doc in /var/www/owncloud/lib/private/DB/Connection.php on line 64
[Tue Feb 06 15:36:31.751385 2018] [:error] [pid 1206] [client 155.185.166.204:52703] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/owncloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/owncloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doc in /var/www/owncloud/lib/private/DB/Connection.php on line 64
[Tue Feb 06 16:10:32.912166 2018] [:error] [pid 2632] [client 155.185.3.191:51270] PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/owncloud/lib/private/Log.php on line 288
[Tue Feb 06 16:11:00.173925 2018] [:error] [pid 2572] [client 155.185.3.191:51280] PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/owncloud/lib/private/Log.php on line 288
[Tue Feb 06 16:11:05.001355 2018] [:error] [pid 2572] [client 155.185.3.191:51280] PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/owncloud/lib/private/Log.php on line 288
[Tue Feb 06 16:12:51.096381 2018] [:error] [pid 2837] [client 155.185.3.191:51311] PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/owncloud/lib/private/Log.php on line 288
[Tue Feb 06 16:14:08.547858 2018] [:error] [pid 2562] [client 155.185.3.191:51326] PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/owncloud/lib/private/Log.php on line 288
```
in the past 10 hours I have 750 rows like those in my apache error logs

#### ownCloud log (data/owncloud.log)
my /var/www/owncloud/data/log/owncloud.log stop logging 2 monts ago

#### Browser log
no error at the browser side

**Comment by mmattel** [comment]
@PVince81 

The root cause seems to be that according to the documentation of config.php, ``log_secret`` is missing in the request parameter queried (where to set this?) and therefore no parameter can be found in ``$request->getParam('log_secret')`` leading in returning Null instead of a found string.

``hash_equals`` requires a string as user parameter, but the return value was NULL creating the error.

If the queried request parameter is either not set or eg mistyped, the return value used could be forced to be an empty string like ``(string)$request->getParam('log_secret')``, but this would never highlight this fact...

Or logging a query just before ``hash_equals`` that ``$request->getParam('log_secret')`` returns NULL. 
Like: ``shared_secret`` is set, but request parameter ``log_secret`` not found. 
This would immediately point out where to look at.

**Comment by phil-davis** [comment]
Or you can just tell ``getParam`` to return an empty string if the param is not set:
```
hash_equals($logCondition['shared_secret'], $request->getParam('log_secret', ''))
```

**Comment by mmattel** [comment]
👍

**Comment by sharidas** [comment]
Closing this issue as the changes are merged to master and stable10 branch.
