### ISSUE TITLE
./occ files:scan user_name errores with file locked - and exits.

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#30505]
### Steps to reproduce
1. Create some mounts via UI
2. run ./occ files:scan user_name

### Expected behaviour
When an error like file locked occurs, it should 
a. report which file is locked from which storage (you just see the fileid)
b. continue scanning

### Actual behaviour
occ reports the error in full detail (see log below) but without the file name and stops scanning.
A verbose setting would show where it errored but slows down scanning.
What happens when a background scan runs, error and exit and show in eg the UI only a fraction of new files ?
Here it exited at a fraction of scannable files:
```
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 10408   | 28173 | 00:03:32     |
+---------+-------+--------------+
```
A successful rerun after a while showed the total number of files scanned:
```
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 14117   | 93859 | 00:08:16     |
+---------+-------+--------------+
```

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.6.1

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oct7bkicorxf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxx",
        "dbtype": "mysql",
        "version": "10.0.6.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "filesystem_check_changes": 1,
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "preview_max_scale_factor": 1,
        "excluded_directories": [
            ".snapshot",
            "~snapshot"
        ],
        "upgrade.automatic-app-update": true,
        "quota_include_external_storage": false,
        "singleuser": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ]
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_clipboard: 0.7.1
  - files_external: 0.7.1
  - files_external_dropbox: 1.0.1
  - files_external_ftp: 0.2.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.3
  - music: 0.5.5
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.2
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** smb, dropbox

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera

**Operating system:** W10x64

#### Web server error log
```
not relevant
```

#### ownCloud log (data/owncloud.log)
```
Exception during scan: OCP\Lock\LockedException: "files/db257fcf5a04a92aba614fb833bc57ce" is locked
#0 /var/www/owncloud/lib/private/Files/Storage/Common.php(653): OC\Lock\MemcacheLockingProvider->acquireLock('files/db257fcf5...', 2)
#1 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(589): OC\Files\Storage\Common->acquireLock('scanner::', 2, Object(OC\Lock\MemcacheLockingProvider))
#2 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(589): OC\Files\Storage\Wrapper\Wrapper->acquireLock('scanner::', 2, Object(OC\Lock\MemcacheLockingProvider))
#3 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(589): OC\Files\Storage\Wrapper\Wrapper->acquireLock('scanner::', 2, Object(OC\Lock\MemcacheLockingProvider))
#4 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(589): OC\Files\Storage\Wrapper\Wrapper->acquireLock('scanner::', 2, Object(OC\Lock\MemcacheLockingProvider))
#5 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(589): OC\Files\Storage\Wrapper\Wrapper->acquireLock('scanner::', 2, Object(OC\Lock\MemcacheLockingProvider))
#6 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(309): OC\Files\Storage\Wrapper\Wrapper->acquireLock('scanner::', 2, Object(OC\Lock\MemcacheLockingProvider))
#7 /var/www/owncloud/lib/private/Files/Utils/Scanner.php(238): OC\Files\Cache\Scanner->scan('', true, 3)
#8 /var/www/owncloud/apps/files/lib/Command/Scan.php(224): OC\Files\Utils\Scanner->scan('/user_1', false)
#9 /var/www/owncloud/apps/files/lib/Command/Scan.php(310): OCA\Files\Command\Scan->scanFiles('user_1', '/user_1', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false, false)
#10 /var/www/owncloud/lib/composer/symfony/console/Command/Command.php(262): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/owncloud/core/Command/Base.php(159): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/owncloud/lib/composer/symfony/console/Application.php(826): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/owncloud/lib/composer/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/owncloud/lib/composer/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/owncloud/lib/private/Console/Application.php(161): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/owncloud/console.php(106): OC\Console\Application->run()
#17 /var/www/owncloud/occ(11): require_once('/var/w...')
#18 {main}
```

#### Browser log
```
not relevant
```

**Comment by mmattel** [comment]
@PVince81

**Comment by mmattel** [comment]
The refrenced PR #30580 addresses another topic...
This one is about to continue scanning when a file is locked instead erroring and stopping.

**Comment by mmattel** [comment]
Raising the question: under which conditions do we want that the scanner full stops scanning?

I propose the following:
- full stop only on issues related to unrecoverable sw errors
- but contionue on all other errors like "file locked" or mount unintentionally disappeard
(just skip it and take the next mount)

In any ways log/report it.
