### ISSUE TITLE
Doctrine Exception on Upgrade -> 9.1.7

### ISSUE THREAD

**Issue by whyteks** [owncloud/core#30697]
Hi, 

On Ubuntu 14.04.2 LTS with php 5.5.9-1ubuntu4.23 I just had a hiccup with the upgrade process from 9.1.0 to 9.1.7 where occ upgrade threw an exception which unfortunately has scrolled off by terminal buffer now, but it was this one: 
https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L442:

For the sake of indexing the Exception Error is:
Unknown database type  requested - that is Unknown database type [NONE] requested.

I added some debug output in Doctrine and tracked it to the sqlite_stat1 table , which indeed, doesn't seem to have any types??

Getting a little frustrated with what I hoped to be a smooth and quick upgrade in order to run the file scan, I hacked Doctrine + added an extra condition to _getPortableTableColumnList () here:

https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php#L819

where I also checked for $table == "sqlite_stat1" and skipped calling _getPortableTableColumnDefinition()

That seemed to work, but I do NOT really know what I was doing.
I don't know what is at fault here, maybe Doctrine?  but though I'd write it up here as on OC issue as I could find no reference to the Exception.

**Comment by DeepDiver1975** [comment]
This table is used for analysing the database - https://www.sqlite.org/fileformat.html

As far as I can tell it is save to delete this table and rerun the update command.

But please create a backup of the database file.

**Comment by whyteks** [comment]
So maybe doctrine is at fault here, tables beginning with sqlite_ should be excluded from whatever it is doing there.
BTW, the backtrace in the log.. would have helped, I didn't need to go digging to find the culprit table.

Of course, Always backup everything!! 


```
< {"reqId":"vbGINkzrR1Aq42j38cev",
"remoteAddr":"",
"app":"core",
"message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",
\"Message\":\"Unknown database type  requested,
 OC\\\\DB\\\\OCSqlitePlatform may not support it.\",
\"Code\":0,
\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/SqliteSchemaManager.php(289): Doctrine\\\\DBAL\\\\Platforms\\\\AbstractPlatform->getDoctrineTypeMapping('')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(820): Doctrine\\\\DBAL\\\\Schema\\\\SqliteSchemaManager->_getPortableTableColumnDefinition(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/SqliteSchemaManager.php(228): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->_getPortableTableColumnList('sqlite_stat1',
 '\\\/var\\\/www\\\/ownclo...',
 Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(175): Doctrine\\\\DBAL\\\\Schema\\\\SqliteSchemaManager->_getPortableTableColumnList('sqlite_stat1',
 '\\\/var\\\/www\\\/ownclo...',
 Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(281): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->listTableColumns('sqlite_stat1')\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(268): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->listTableDetails('sqlite_stat1')\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(1040): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->listTables()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Repair\\\/SqliteAutoincrement.php(62): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->createSchema()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Repair.php(89): OC\\\\Repair\\\\SqliteAutoincrement->run(Object(OC\\\\Repair))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(228): OC\\\\Repair->run()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(150): OC\\\\Updater->doUpgrade('9.1.7.2',
 '9.1.6.2')\\n#11 \\\/var\\\/www\\\/owncloud\\\/core\\\/Command\\\/Upgrade.php(290): OC\\\\Updater->upgrade()\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput),
 Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(844): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput),
 Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade),
 Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput),
 Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput),
 Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Console\\\/Application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(NULL,
 NULL)\\n#17 \\\/var\\\/www\\\/owncloud\\\/console.php(102): OC\\\\Console\\\\Application->run()\\n#18 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#19 {main}\",
\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Platforms\\\/AbstractPlatform.php\",
\"Line\":423}",
"level":3,
"time":"2018-03-05T10:45:22+00:00",
"method":"--",
"url":"--",
"user":"--"}
```
