### ISSUE TITLE
[9.1.8RC1] Setting up LDAP server raises exception and hangs.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#30716]
### Steps to reproduce

1. Enable ldap app.
2. Set up ldap server.

### Expected behaviour

LDAP server can be configured without problems.

### Actual behaviour

Configuration keeps spinning forever.

![ldap_spinning_forever](https://user-images.githubusercontent.com/9048796/37047807-59baa538-216c-11e8-9b44-903eec27e585.gif)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**Cache**
DB

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.1.8.0","versionstring":"9.1.8 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
{"reqId":"B1dUbm\/GnvFn6aspVO5D","remoteAddr":"HIDDEN_IP","app":"index","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method OCA\\\\User_LDAP\\\\Connection::getLDAP()\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(160): OCA\\\\User_LDAP\\\\Connection->establishConnection()\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(169): OCA\\\\User_LDAP\\\\Connection->init()\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(855): OCA\\\\User_LDAP\\\\Connection->getConnectionResource()\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(1021): OCA\\\\User_LDAP\\\\Access->executeSearch('(&(|(objectclas...', Array, Array, 400, 0)\\n#4 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(816): OCA\\\\User_LDAP\\\\Access->search('(&(|(objectclas...', Array, Array, 400, 0)\\n#5 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Wizard.php(439): OCA\\\\User_LDAP\\\\Access->searchGroups('(&(|(objectclas...', Array, 400, 0)\\n#6 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Wizard.php(398): OCA\\\\User_LDAP\\\\Wizard->fetchGroups('ldap_userfilter...', 'ldapUserFilterG...')\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Wizard.php(375): OCA\\\\User_LDAP\\\\Wizard->determineGroups('ldap_userfilter...', 'ldapUserFilterG...')\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/ajax\\\/wizard.php(84): OCA\\\\User_LDAP\\\\Wizard->determineGroupsForUsers()\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(154) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#10 [internal function]: __lambda_func(NULL)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func('\\\\x00lambda_2106', Array)\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/user_ldap...')\\n#13 \\\/opt\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php\",\"Line\":541}","level":3,"time":"2018-03-06T17:11:00+00:00","method":"POST","url":"\/index.php\/apps\/user_ldap\/ajax\/wizard.php","user":"admin"}
```

### Client configuration

**Browser**
Chrome
  
cc @tomneedham

**Comment by SergioBertolinSG** [comment]
Works fine in 9.1.7.

**Comment by tomneedham** [comment]
what version of ldap is bundling in with the rc1?

**Comment by davitol** [comment]
user_ldap: 0.9.0

**Comment by PVince81** [comment]
reverted here https://github.com/owncloud/core/pull/30721
