### ISSUE TITLE
occ inconsistencies on LDap users

### ISSUE THREAD

**Issue by cormite** [owncloud/core#30750]
### Steps to reproduce
1. `occ ldap:check-user valid-user` returns: `The user is still available on LDAP`
2. `occ ldap:show-config valid-user` (same valid-user) returns: `Invalid configID`
3. `occ ldap:check-user --force valid-user` (same valid-user) returns: `The given user is not a recognized LDAP user.`
4. I also checked in the database, table `oc_ldap_user_mapping` and the user is there.

### Expected behaviour
If the user exists in LDap and it is seen via `occ ldap:check-user`, the user should be available in the frontend and occ ldap commands.

### Actual behaviour
The frontend does not show the user. The occ ldap commands show the aforementioned errors.

### Server configuration
**Operating system**: `CentOS Linux release 7.4.1708 (Core)`

**Web server:** `Apache/2.4.6`

**Database:** `mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1`

**PHP version:** `PHP 5.6.33`

**ownCloud version:** `ownCloud 10.0.1.5`

**Updated from an older ownCloud or fresh install:** `updated`

**Where did you install ownCloud from:** `compressed file`

**Signing status (ownCloud 9.0 and above):**
`https://gist.github.com/cormite/33f877edcf99581fc5aba85027ed6124`

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.0.1.5",
        "version.hide": true,
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "forcessl": true,
        "loglevel": 3,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "ldapUserCleanupInterval": 5
    }
}
```
**List of activated apps:**

```
Enabled:
  - activity: 2.3.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.2
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - impersonate: 0.1.0
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - user_ldap: 0.9.1

```

**Are you using external storage, if yes which one:** `NFS`

**Are you using encryption:** `No`

**Are you using an external user-backend, if yes which one:** `LDAP`

#### LDAP configuration (delete this part if not used)

```
+-------------------------------+-----------------------------------------------------------------------+
| Configuration                 |                                                                       |
+-------------------------------+-----------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                     |
| hasPagedResultSupport         |                                                                       |
| homeFolderNamingRule          |                                                                       |
| lastJpegPhotoLookup           | 0                                                                     |
| ldapAgentName                 |                                                                       |
| ldapAgentPassword             | ***                                                                   |
| ldapAttributesForGroupSearch  |                                                                       |
| ldapAttributesForUserSearch   |                                                                       |
| ldapBackupHost                |                                                                       |
| ldapBackupPort                | "***REMOVED SENSITIVE VALUE***"                                       |
| ldapBase                      | "***REMOVED SENSITIVE VALUE***"                                       |
| ldapBaseGroups                | "***REMOVED SENSITIVE VALUE***"                                       |
| ldapBaseUsers                 | "***REMOVED SENSITIVE VALUE***"                                       |
| ldapCacheTTL                  | 600                                                                   |
| ldapConfigurationActive       | 1                                                                     |
| ldapDynamicGroupMemberURL     |                                                                       |
| ldapEmailAttribute            | mail                                                                  |
| ldapExperiencedAdmin          | 0                                                                     |
| ldapExpertUUIDGroupAttr       | "***REMOVED SENSITIVE VALUE***"                                       |
| ldapExpertUUIDUserAttr        | "***REMOVED SENSITIVE VALUE***"                                       |
| ldapExpertUsernameAttr        |                                                                       |
| ldapGroupDisplayName          | cn                                                                    |
| ldapGroupFilter               | (&(|(objectclass=top)))                                               |
| ldapGroupFilterGroups         |                                                                       |
| ldapGroupFilterMode           | 0                                                                     |
| ldapGroupFilterObjectclass    | top                                                                   |
| ldapGroupMemberAssocAttr      | uniqueMember                                                          |
| ldapHost                      | "***REMOVED SENSITIVE VALUE***"                                       |
| ldapIgnoreNamingRules         |                                                                       |
| ldapLoginFilter               | "***REMOVED SENSITIVE VALUE***"                                       |
| ldapLoginFilterAttributes     |                                                                       |
| ldapLoginFilterEmail          | 0                                                                     |
| ldapLoginFilterMode           | 1                                                                     |
| ldapLoginFilterUsername       | 1                                                                     |
| ldapNestedGroups              | 0                                                                     |
| ldapOverrideMainServer        | 0                                                                     |
| ldapPagingSize                | 500                                                                   |
| ldapPort                      | "***REMOVED SENSITIVE VALUE***"                                       |
| ldapQuotaAttribute            | "***REMOVED SENSITIVE VALUE***"                                       |
| ldapQuotaDefault              | 53687091200                                                           |
| ldapTLS                       | 0                                                                     |
| ldapUserDisplayName           | displayname                                                           |
| ldapUserDisplayName2          |                                                                       |
| ldapUserFilter                | "***REMOVED SENSITIVE VALUE***"                                       |
| ldapUserFilterGroups          |                                                                       |
| ldapUserFilterMode            | 1                                                                     |
| ldapUserFilterObjectclass     |                                                                       |
| ldapUuidGroupAttribute        | auto                                                                  |
| ldapUuidUserAttribute         | auto                                                                  |
| turnOffCertCheck              | 0                                                                     |
| useMemberOfToDetectMembership | 1                                                                     |
+-------------------------------+-----------------------------------------------------------------------+
```

### Client configuration
**Browser:** `Chrome, Firefox`

**Operating system:** `Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux`

#### Web server error log
> Nothing LDap related

#### ownCloud log (data/owncloud.log)
```
{"reqId":"WqJnimS48wbflVGrgjpr4AAAABE","level":3,"time":"2018-03-09T10:52:58+00:00","remoteAddr":"10.150.1.111","user":"--","app":"user_ldap","method":"POST","url":"\/index.php\/login","message":"trying to set a quota for user USER but the user is missing"}
{"reqId":"WqJnkviSuE4ygKaNrOiepgAAAB0","level":3,"time":"2018-03-09T10:53:06+00:00","remoteAddr":"10.150.1.111","user":"--","app":"user_ldap","method":"POST","url":"\/index.php\/login?user=USER","message":"trying to set a quota for user USER but the user is missing"}
{"reqId":"WqJnn-iSuE4ygKaNrOieqwAAAB0","level":3,"time":"2018-03-09T10:53:19+00:00","remoteAddr":"10.150.1.111","user":"--","app":"user_ldap","method":"POST","url":"\/index.php\/login?user=USER","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"No user available for the given login name on ldaps:\\\/\\\/LDAP_SERVER\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php(117): OCA\\\\User_LDAP\\\\User_LDAP->getLDAPUserByLoginName('USER')\\n#1 [internal function]: OCA\\\\User_LDAP\\\\User_LDAP->checkPassword(*** sensitive parameters replaced ***)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(79): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Proxy.php(140): OCA\\\\User_LDAP\\\\User_Proxy->walkBackends('USER', 'checkPassword', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(194): OCA\\\\User_LDAP\\\\Proxy->handleRequest('USER', 'checkPassword', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Manager.php(215): OCA\\\\User_LDAP\\\\User_Proxy->checkPassword(*** sensitive parameters replaced ***)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(186): OC\\\\User\\\\Manager->checkPassword(*** sensitive parameters replaced ***)\\n#7 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(918): OC\\\\Route\\\\Router->match('\\\/login')\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php\",\"Line\":101}"}
{"reqId":"WqJnrN51HMPyGTQMzueCQwAAACQ","level":3,"time":"2018-03-09T10:53:32+00:00","remoteAddr":"10.150.1.111","user":"--","app":"user_ldap","method":"POST","url":"\/index.php\/login?user=USER","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"No user available for the given login name on ldaps:\\\/\\\/LDAP_SERVER\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php(117): OCA\\\\User_LDAP\\\\User_LDAP->getLDAPUserByLoginName('USER')\\n#1 [internal function]: OCA\\\\User_LDAP\\\\User_LDAP->checkPassword(*** sensitive parameters replaced ***)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(79): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Proxy.php(140): OCA\\\\User_LDAP\\\\User_Proxy->walkBackends('USER', 'checkPassword', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(194): OCA\\\\User_LDAP\\\\Proxy->handleRequest('USER', 'checkPassword', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Manager.php(215): OCA\\\\User_LDAP\\\\User_Proxy->checkPassword(*** sensitive parameters replaced ***)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(186): OC\\\\User\\\\Manager->checkPassword(*** sensitive parameters replaced ***)\\n#7 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(918): OC\\\\Route\\\\Router->match('\\\/login')\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php\",\"Line\":101}"}
{"reqId":"WqaEylpx3wCqmOX6CKeUVwAAABs","level":3,"time":"2018-03-12T13:46:50+00:00","remoteAddr":"10.150.1.111","user":"--","app":"user_ldap","method":"POST","url":"\/index.php\/login","message":"trying to set a quota for user USER but the user is missing"}

```

#### Browser log
```
a) nothing relevant to ldap
b) Everything has a `status 200`
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jvillafanez.

Possibly related issues are https://github.com/owncloud/core/issues/9449 (LDAP Issues), https://github.com/owncloud/core/issues/27912 (LDAP Issues finding all users), https://github.com/owncloud/core/issues/16933 (LDAP Scope), https://github.com/owncloud/core/issues/30124 (Invalid Private Key), and https://github.com/owncloud/core/issues/26104 (Username and password storing in plain text in the log file).

**Comment by jvillafanez** [comment]
There are some changes in that regard in the latest user_ldap version, so my recommendation is to update to ownCloud 10.0.7 and user_ldap 0.10.0 and retry.

> If the user exists in LDap and it is seen via occ ldap:check-user, the user should be available in the frontend and occ ldap commands.

This isn't true. the expectation is that the ldap:check-user connects "directly", with the ownCloud configuration, to the LDAP server and check if the user is there. This has nothing to do with the frontend. What is shown in the frontend are the accounts available in ownCloud, which are created via successful login or via `occ user:sync`. The user_ldap app doesn't (and won't) know anything about the ownCloud account nor how they're managed.

**Comment by cormite** [comment]
@jvillafanez I will soon make an upgrade of owncloud. Hopefully this fixes the problem.
Maybe I was not clear about the expected behavior, sorry about that. What I meant to say is that I expect all `occ ldap` commands to be consistent and also in parallel with the frontend, meaning that if a `occ ldap` command finds the user directly in ldap, I do not expect the other `occ ldap` commands to fail and neither I expect the frontend to not show me the user if `occ ldap` has found it in straight into LDap.
It is a bit confusing. Maybe I am not interpreting well the output. Please feel free to guide me in the right direction if so.

Thanks.

**Comment by jvillafanez** [comment]
ownCloud will show only the information stored in the accounts table. It won't connect directly to the LDAP server except during login to verify the credentials.
The `occ user:sync` will sync the information of the LDAP server into the accounts table. You'll need to run this command periodically. I think login with a specific user will also update the information of that specific user in the accounts table.

The user_ldap app won't interact directly with the accounts table. You can connect directly to the LDAP server with the app to perform some operations (such as checking the user existence), but such information might need to be updated via the `user:sync` command. This means that the information shown in ownCloud might not be up-to-date.
This was thought in order to reduce the workload in the LDAP server as well as improve the way the searches are performed.

In any case, the ldap command should always return consistent information.

**Comment by cormite** [comment]
@jvillafanez I see.

Perfectly clear now. Thanks for the time and the explanation.
I will follow your recommendation and update as soon as possible.
