### ISSUE TITLE
Insufficient Storage error handling

### ISSUE THREAD

**Issue by pako81** [owncloud/core#31284]
It looks like there is an uncaught exception in case of Insufficient Storage for WebDAV. This should be probably treated like a normal log message:
```
{"reqId":"421a6474-d32a-4da7-904f-564c2e4d02a2","level":4,"time":"2018-04-26T11:20:51+00:00","remoteAddr":"xxx.xx.xx.xxx","user":"user2","app":"webdav","method":"PUT","url":"/owncloud1008rc3/remote.php/dav/files/user2/ownCloud%20Manual2.pdf","message":"Exception: {\"Message\":\"HTTP/1.1 507 Insufficient Storage\",\"Exception\":\"Sabre\DAV\Exception\InsufficientStorage\",\"Code\":0,\"Trace\":\"
#0 /var/www/html/owncloud1008rc3/apps/dav/lib/Connector/Sabre/QuotaPlugin.php(134): OCA\DAV\Connector\Sabre\QuotaPlugin->checkQuota('//ownCloud Manu...')
#1 [internal function]: OCA\DAV\Connector\Sabre\QuotaPlugin->handleBeforeCreateFile('files/user2/own...', Resource id #69, Object(OCA\DAV\Connector\Sabre\Directory), false)
#2 /var/www/html/owncloud1008rc3/lib/composer/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#3 /var/www/html/owncloud1008rc3/lib/composer/sabre/dav/lib/DAV/Server.php(1093): Sabre\Event\EventEmitter->emit('beforeCreateFil...', Array)
#4 /var/www/html/owncloud1008rc3/lib/composer/sabre/dav/lib/DAV/CorePlugin.php(525): Sabre\DAV\Server->createFile('files/user2/own...', Resource id #69, NULL)
#5 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#6 /var/www/html/owncloud1008rc3/lib/composer/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#7 /var/www/html/owncloud1008rc3/lib/composer/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:PUT', Array)
#8 /var/www/html/owncloud1008rc3/lib/composer/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#9 /var/www/html/owncloud1008rc3/apps/dav/lib/Server.php(278): Sabre\DAV\Server->exec()
#10 /var/www/html/owncloud1008rc3/apps/dav/appinfo/v2/remote.php(31): OCA\DAV\Server->exec()
#11 /var/www/html/owncloud1008rc3/remote.php(165): require_once('/var/www/html/o...')
#12 {main}\",\"File\":\"/var/www/html/owncloud1008rc3/apps/dav/lib/Connector/Sabre/QuotaPlugin.php\",\"Line\":169,\"User\":\"user2\"}"}
```
Tested in 10.0.7 and 10.0.8. @tomneedham as discussed.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/15189 ([OC 8.0.2] Sabre Quota Plugin Errors - 507 Insufficient Storage ), https://github.com/owncloud/core/issues/6391 (ownCloud can't handle Unlimited Storage?), and https://github.com/owncloud/core/issues/29082 (a Error).

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by pako81** [comment]
@PVince81 ping

**Comment by michaelstingl** [comment]
HTTP status code `507 Insufficient Storage` is okay, but the response body isn't beautiful:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\InsufficientStorage</s:exception>
  <s:message/>
</d:error>
```

**Comment by PVince81** [comment]
@michaelstingl what message do you want there ?

**Comment by michaelstingl** [comment]
@PVince81 response message is the least problem. Level 4 exception in owncloud.log is much much bigger problem.

OCS API for example sometimes responds with a "nice" message:

`<message>can't change permission for public link share</message>`
(source: [docs](https://doc.owncloud.com/server/10.0/developer_manual/core/ocs-share-api.html#id40))

This can be displayed in the clients directly, and it's even translated automatically:
https://github.com/owncloud/core/blob/v10.0.8/apps/files_sharing/l10n/ja.json#L47

I'd love to get more of these "actionable" responses, but's that's probably another discussion…

**Comment by PVince81** [comment]
so can this ticket be closed ? further wishes to be raised as separate non-support ticket ?

**Comment by PVince81** [comment]
PR for the log level change was merged, will be in 10.0.10: https://github.com/owncloud/core/pull/31978

**Comment by pako81** [comment]
@PVince81 moving this to debug level would make for an admin more difficult to find out while uploads for a specific user failed, isn't it?

**Comment by PVince81** [comment]
@pako81 in general I'd expect that for said user the error response 507 is returned, that would be visible in the HTTP status code of the access log

**Comment by PVince81** [comment]
moving back to L3, so far nothing else to be done on server team

**Comment by PVince81** [comment]
I'm closing this. @pako81 @michaelstingl if there are additional wishes, please make new tickest.
