### ISSUE TITLE
Exception trying to download folder

### ISSUE THREAD

**Issue by sf96** [owncloud/core#31321]
###Steps to reproduce
1.Visit my OwnCloud File page
2.Try to download an entire folder usind "Download" Button ("Scarica" in my italian version)

###Expected behaviour
Download the entire folder with all documents and files

###Actual behaviour
Page Redirect with an error message : File cannot be read

###Server configuration
**Operating system**: Server Linux (Hosting Linux - Aruba.it)

**Database**: MySQL 5.5.59-38.11-log

**PHP version**: 5.4.16

**ownCloud version**: ownCloud	10.0.7 (stable)

**Updated from an older ownCloud or fresh install**: Updated to OwnCloud 10 - But I noticed the problem also before updating

**Where did you install ownCloud from**: Used the official package and uploaded by using ftp connection

###Error Log
Here some few lines of the log file. I try to download a folder just before saving log file so i think that the last two line are the most useful in order to understand the problem

```
{"reqId":"WuL31gQ5zNVy-CKLFa77kQAAAAA","level":0,"time":"2018-04-27T10:13:43+00:00","remoteAddr":"79.20.113.186","user":"segreteria","app":"no app in context","method":"GET","url":"\/cloud\/index.php\/apps\/gallery\/config?extramediatypes=1","message":"CSRF check failed"}
{"reqId":"WuL32QQ5zNVy-CKLFa77kgAAAAA","level":0,"time":"2018-04-27T10:13:46+00:00","remoteAddr":"79.20.113.186","user":"segreteria","app":"webdav","method":"PROPFIND","url":"\/cloud\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 CSRF check not passed.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(150): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(201): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(150): Sabre\\\\DAV\\\\Auth\\\\Plugin->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/remote.php(165): require_once('\\\/web\\\/htdocs\\\/www...')\\n#9 {main}\",\"File\":\"\\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php\",\"Line\":215,\"User\":\"segreteria\"}"}
{"reqId":"WuL331c3dyqh7MYIEefF5AAAAAY","level":0,"time":"2018-04-27T10:13:52+00:00","remoteAddr":"79.20.113.186","user":"segreteria","app":"webdav","method":"PROPFIND","url":"\/cloud\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 CSRF check not passed.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(150): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(201): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(150): Sabre\\\\DAV\\\\Auth\\\\Plugin->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/remote.php(165): require_once('\\\/web\\\/htdocs\\\/www...')\\n#9 {main}\",\"File\":\"\\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php\",\"Line\":215,\"User\":\"segreteria\"}"}
{"reqId":"WuL5APKP6MT4pgR9NPkUEgAAAAM","level":3,"time":"2018-04-27T10:18:42+00:00","remoteAddr":"79.20.113.186","user":"segreteria","app":"no app in context","method":"GET","url":"\/cloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2F&files=Fogli%20Settimana&downloadStartSecret=i1cbmzwbh7l","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Unable to send file Fogli%20Settimana.tar. HTML Headers have already been sent from \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/deepdiver1975\\\/tarstreamer\\\/src\\\/TarStreamer.php in line 30\",\"Code\":0,\"Trace\":\"#0 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/private\\\/Streamer.php(54): ownCloud\\\\TarStreamer\\\\TarStreamer->sendHeaders('Fogli Settimana...')\\n#1 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/private\\\/legacy\\\/files.php(147): OC\\\\Streamer->sendHeaders('Fogli Settimana')\\n#2 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/apps\\\/files\\\/ajax\\\/download.php(68): OC_Files::get('\\\/', 'Fogli Settimana', Array)\\n#3 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/web\\\/htdocs\\\/www...')\\n#4 [internal function]: OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(NULL)\\n#5 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(Closure), Array)\\n#6 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#7 \\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/index.php(55): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/web\\\/htdocs\\\/www.parrocchialuragomarinone.it\\\/home\\\/cloud\\\/lib\\\/composer\\\/deepdiver1975\\\/tarstreamer\\\/src\\\/TarStreamer.php\",\"Line\":46}"}
{"reqId":"WuL5An5pE9h@31ZzoxN4lgAAAAU","level":0,"time":"2018-04-27T10:18:43+00:00","remoteAddr":"79.20.113.186","user":"segreteria","app":"no app in context","method":"GET","url":"\/cloud\/index.php\/apps\/gallery\/config?extramediatypes=1","message":"CSRF check failed"}
```

**Comment by patrickjahns** [comment]
> PHP version: 5.4.16

ownCloud 10 requires at least php 5.6 - recommend to use php7. Please update your infrastructure accordingly and then try again

**Comment by sf96** [comment]
Upgrade to php 7.1 using my hosting setting page but the problem persist.

**Comment by PVince81** [comment]
downloading from Mac ?

if yes, this could be another manifestation of https://github.com/owncloud/core/issues/21866

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
