### ISSUE TITLE
"Could not open file" after uploading 10MB file on an Object Storage

### ISSUE THREAD

**Issue by vladfulgeanu** [owncloud/core#31398]
### Steps to reproduce
1. Upload multiple files using the web interface

### Expected behaviour
Being able to upload all of them

### Actual behaviour
Only the ones <10MB have uploaded. Any other file >10MB I try to upload gives a **Could not open file** error.

### Server configuration
**Operating system**: Ubuntu 17.10

**Web server:** Apache2 

**Database:** mysql  Ver 15.1 Distrib 10.1.30-MariaDB

**PHP version:** 7.1

**ownCloud version:** 10.0.8.5

**Updated from an older ownCloud or fresh install:** Updated from 10.0.5 (I think) through the web GUI

**Where did you install ownCloud from:** wget https://download.owncloud.org

**Signing status (ownCloud 9.0 and above):** 

No errors have been found.

**The content of config/config.php:**

```
{
        "instanceid": "ocyoumkqwgrf",
        "debug": "true",
        "loglevel": 0,
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\Swift",
            "arguments": {
                "username": "fQ65UMWWdqnN",
                "password": "***REMOVED SENSITIVE VALUE***",
                "container": "nismo_archive",
                "autocreate": false,
                "region": "DE1",
                "url": "https:\/\/auth.cloud.ovh.net\/v2.0",
                "tenantName": "3426834956170758",
                "serviceName": "swift",
                "urlType": "internal"
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "54.37.2.132"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/54.37.2.132\/owncloud",
        "dbtype": "mysql",
        "version": "10.0.8.5",
        "dbname": "owncloud",
        "dbhost": "localhost:5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    },
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.4
  - notifications: 0.3.3
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1

```

**Are you using external storage, if yes which one:** OpenStack Object Storage from OVH

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** I don't think so

### Client configuration
**Browser:** 66.0.3359

**Operating system:** Ubuntu 17.10

#### Web server error log
```
[08/May/2018:17:02:54 +0000] "MKCOL /owncloud/remote.php/dav/uploads/test/web-file-upload-273190993c9ca6ad93bcdc2ff6c01f4c-1525798974809 HTTP/1.1" 201 548 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
[08/May/2018:17:02:55 +0000] "PUT /owncloud/remote.php/dav/uploads/test/web-file-upload-273190993c9ca6ad93bcdc2ff6c01f4c-1525798974809/0 HTTP/1.1" 201 580 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
[08/May/2018:17:03:01 +0000] "PUT /owncloud/remote.php/dav/uploads/test/web-file-upload-273190993c9ca6ad93bcdc2ff6c01f4c-1525798974809/10485760 HTTP/1.1" 201 580 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
[08/May/2018:17:03:04 +0000] "MOVE /owncloud/remote.php/dav/uploads/test/web-file-upload-273190993c9ca6ad93bcdc2ff6c01f4c-1525798974809/.file HTTP/1.1" 503 752 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
[08/May/2018:17:03:08 +0000] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 853 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
[08/May/2018:17:03:04 +0000] "GET /owncloud/index.php/apps/files/ajax/getstoragestats.php?dir=%2Ftest%20Archive%2Fvideos HTTP/1.1" 200 883 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
[08/May/2018:17:03:12 +0000] "GET /owncloud/index.php/settings/admin/log/download HTTP/1.1" 200 6410577 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
[08/May/2018:17:03:18 +0000] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 853 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
[08/May/2018:17:03:26 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.27 (Ubuntu) (internal dummy connection)"

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"QXdSWuAf2nONQOyxy3Cj","level":3,"time":"2018-05-08T16:35:51+00:00","remoteAddr":"188.27.109.200","user":"test","app":"objectstore","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Could not get object: Client error response\n[status code] 429\n[reason phrase] Too Many Requests\n[url] https:\/\/storage.de1.cloud.ovh.net\/v1\/AUTH_4e399774f0c9740bc7b2f793740\/container_archive\/urn:oid:1482"}
{"reqId":"tbKjfeY5mkdAzQRSpy0Z","level":0,"time":"2018-05-08T17:03:06+00:00","remoteAddr":"188.27.109.200","user":"test","app":"PHP","method":"MOVE","url":"\/owncloud\/remote.php\/dav\/uploads\/test\/web-file-upload-273190993c9ca6ad93bcdc2ff6c01f4c-1525798974809\/.file","message":"rewinddir(): 106 is not a valid Directory resource at \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#31"}
{"reqId":"tbKjfeY5mkdAzQRSpy0Z","level":3,"time":"2018-05-08T17:03:07+00:00","remoteAddr":"188.27.109.200","user":"test","app":"objectstore","method":"MOVE","url":"\/owncloud\/remote.php\/dav\/uploads\/test\/web-file-upload-273190993c9ca6ad93bcdc2ff6c01f4c-1525798974809\/.file","message":"Could not get object: Client error response\n[status code] 429\n[reason phrase] Too Many Requests\n[url] https:\/\/storage.de1.cloud.ovh.net\/v1\/AUTH_4e399774f0c9740bc7b2f793740\/container_archive\/urn:oid:1507"}
{"reqId":"tbKjfeY5mkdAzQRSpy0Z","level":0,"time":"2018-05-08T17:03:07+00:00","remoteAddr":"188.27.109.200","user":"test","app":"PHP","method":"MOVE","url":"\/owncloud\/remote.php\/dav\/uploads\/test\/web-file-upload-273190993c9ca6ad93bcdc2ff6c01f4c-1525798974809\/.file","message":"fread() expects parameter 1 to be resource, boolean given at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php#901"}
{"reqId":"tbKjfeY5mkdAzQRSpy0Z","level":0,"time":"2018-05-08T17:03:07+00:00","remoteAddr":"188.27.109.200","user":"test","app":"PHP","method":"MOVE","url":"\/owncloud\/remote.php\/dav\/uploads\/test\/web-file-upload-273190993c9ca6ad93bcdc2ff6c01f4c-1525798974809\/.file","message":"fclose() expects parameter 1 to be resource, boolean given at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php#902"}
{"reqId":"tbKjfeY5mkdAzQRSpy0Z","level":3,"time":"2018-05-08T17:03:07+00:00","remoteAddr":"188.27.109.200","user":"test","app":"objectstore","method":"MOVE","url":"\/owncloud\/remote.php\/dav\/uploads\/test\/web-file-upload-273190993c9ca6ad93bcdc2ff6c01f4c-1525798974809\/.file","message":"Could not get object: Client error response\n[status code] 429\n[reason phrase] Too Many Requests\n[url] https:\/\/storage.de1.cloud.ovh.net\/v1\/AUTH_4e399774f0c9740bc7b2f793740\/container_archive\/urn:oid:1507"}
{"reqId":"tbKjfeY5mkdAzQRSpy0Z","level":4,"time":"2018-05-08T17:03:07+00:00","remoteAddr":"188.27.109.200","user":"test","app":"webdav","method":"MOVE","url":"\/owncloud\/remote.php\/dav\/uploads\/test\/web-file-upload-273190993c9ca6ad93bcdc2ff6c01f4c-1525798974809\/.file","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/AssemblyStream.php(270): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/AssemblyStream.php(116): OCA\\\\DAV\\\\Upload\\\\AssemblyStream->getStream(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File))\\n#2 [internal function]: OCA\\\\DAV\\\\Upload\\\\AssemblyStream->stream_read(8192)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/helper.php(297): fread(Resource id #98, 8192)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(168): OC_Helper::streamCopy(Resource id #98, Resource id #113)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(172): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #98)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(314): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('Ouch! test 37...', Resource id #98)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(130): Sabre\\\\DAV\\\\Tree->copyNode(Object(OCA\\\\DAV\\\\Upload\\\\FutureFile), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory), 'Ouch! test 37...')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(161): Sabre\\\\DAV\\\\Tree->copy('uploads\\\/test\\\/...', 'files\\\/test\\\/Ni...')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(642): Sabre\\\\DAV\\\\Tree->move('uploads\\\/test\\\/...', 'files\\\/test\\\/Ni...')\\n#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(278): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":375,\"User\":\"test\"}"}

```

#### Browser log
```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
```

I know this might be a file upload limit issue so I've changed this in the `.user.ini` file:
```
upload_max_filesize=1G
post_max_size=1G
memory_limit=1G
```
and this in the `php.ini` file:
```
upload_max_filesize = 1G
max_file_uploads = 200
```
I've went through a lot of older issues and also followed the `Uploading big files > 512MB` post, but I still get that error.

**Comment by vladfulgeanu** [comment]
@DeepDiver1975 it cannot be a case of rate limiting on the storage provider. As I said in the description, I selected multiple files for upload and only the ones less than 10MB got uploaded. If I deleted one of those and reupload it, it would get uploaded successfully, and whenever I upload a 10.1MB file it fails with `Could not open file` in the web interface.

Even if it were a rate limiting problem, why is the error message not helpful? 

Also, the order of the `owncloud.log` file messages is not always the same. The
 `rewinddir(): 260 is not a valid Directory resource at ...`
 line did get before
 `Could not get object: Client error response\n[status code] 429\n[reason phrase] Too Many Requests\n[url] ...`
 at some point.
