### ISSUE TITLE
Add keeweb support

### ISSUE THREAD

**Issue by theScrabi** [owncloud/core#31622]
I love keepass, but using the web version [keeweb](https://keeweb.info/) together with owncloud is not possible since oc 10.x broke compatibility with the [nextcloud port of keeweb](https://github.com/jhass/nextcloud-keeweb). However keeweb does not need to be an app within owncloud since it already comes along with webdav support. But trying to connect to the .kdbx file in owncloud using keeweb results in a 500 produced by and OPTIONS request.

Here is the stacktrace of my server:
```
#0 /var/www/owncloud/lib/public/Util.php(809): OCP\Util::getFullDomain('null')
#1 /var/www/owncloud/apps/dav/lib/Connector/Sabre/CorsPlugin.php(98): OCP\Util::isSameDomain('null', 'https://cloud.s...')
#2 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(407): OCA\DAV\Connector\Sabre\CorsPlugin->initialize(Object(OCA\DAV\Connector\Sabre\Server))
#3 /var/www/owncloud/apps/dav/lib/Server.php(101): Sabre\DAV\Server->addPlugin(Object(OCA\DAV\Connector\Sabre\CorsPlugin))
#4 /var/www/owncloud/apps/dav/appinfo/v2/remote.php(30): OCA\DAV\Server->__construct(Object(OC\AppFramework\Http\Request), '/owncloud/remot...')
#5 /var/www/owncloud/remote.php(165): require_once('/var/www/ownclo...')
#6 {main}
```

**Comment by theScrabi** [comment]
Here is the anonymized json error:
```
{
  "reqId": "",
  "level": 3,
  "time": "1970-01-01T00:00:00+00:00",
  "remoteAddr": "xx.xx.xx.xx",
  "user": "--",
  "app": "remote",
  "method": "OPTIONS",
  "url": "/owncloud/remote.php/dav/files/user/",
  "message": "Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Invalid url \\\"null\\\"\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/lib\\/public\\/Util.php(809): OCP\\\\Util::getFullDomain('null')\\n#1 \\/var\\/www\\/owncloud\\/apps\\/dav\\/lib\\/Connector\\/Sabre\\/CorsPlugin.php(98): OCP\\\\Util::isSameDomain('null', 'https:\\/\\/cloud.s...')\\n#2 \\/var\\/www\\/owncloud\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(407): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CorsPlugin->initialize(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Server))\\n#3 \\/var\\/www\\/owncloud\\/apps\\/dav\\/lib\\/Server.php(101): Sabre\\\\DAV\\\\Server->addPlugin(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CorsPlugin))\\n#4 \\/var\\/www\\/owncloud\\/apps\\/dav\\/appinfo\\/v2\\/remote.php(30): OCA\\\\DAV\\\\Server->__construct(Object(OC\\\\AppFramework\\\\Http\\\\Request), '\\/owncloud\\/remot...')\\n#5 \\/var\\/www\\/owncloud\\/remote.php(165): require_once('\\/var\\/www\\/ownclo...')\\n#6 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/lib\\/public\\/Util.php\",\"Line\":775}"
}
```

**Comment by DeepDiver1975** [comment]
The OPTIONS request as performed by keeweb holds a http header 'Origin' which holds the value 'null'

This is an invalid value - see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

Looks like an issue in keeweb to me ...

**Comment by DeepDiver1975** [comment]
see here - issue in keeweb - https://github.com/keeweb/keeweb/issues/877

**Comment by theScrabi** [comment]
I see. Thank you.
