### ISSUE TITLE
Cannot setup stable10

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31731]
### Steps

1. Run reset script https://gist.github.com/PVince81/3eaea646271546ef1fd5
1. Open web UI
1. Repeat

### Expected result
Login page, and after login see the files app

### Actual result
No login page, internal server error

### Version
stable10 ead51473584b887e9219737464a3764418b73d84, possibly after merging object store backprot

Please note that running the setup manually works fine.
If I only run `occ maintenance:install` with all arguments, the setup works fine as well.

I wonder if there is an issue with the current session from previous install not being cleared, as the error seems to imply it's trying to setup storage for the old user from a previous install.

### Log
```
{"reqId":"UJwVwBUI2Tc2ucwpr0Qv","level":3,"time":"2018-06-12T09:04:34+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"index","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(134): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(205): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(919): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":584}"}
{"reqId":"dqvti8fmfdz3I1vknx9U","level":0,"time":"2018-06-12T09:04:35+00:00","remoteAddr":"127.0.0.1","user":"--","app":"cron","method":"GET","url":"\/owncloud\/cron.php","message":"Started background job of class : OCA\\Files\\BackgroundJob\\ScanFiles with arguments : "}
{"reqId":"dqvti8fmfdz3I1vknx9U","level":0,"time":"2018-06-12T09:04:35+00:00","remoteAddr":"127.0.0.1","user":"--","app":"cron","method":"GET","url":"\/owncloud\/cron.php","message":"Finished background job, the job took : 0 seconds, this job is an instance of class : OCA\\Files\\BackgroundJob\\ScanFiles with arguments : "}
```

I'm tagging this as release blocker for now until I get into the bottom of it.
The thing is: my reset script has always worked all these years and stopped working today, so it might hint at a possible regression.

@DeepDiver1975 @patrickjahns 

Estimate: at least 1md

**Comment by PVince81** [comment]
This is the contents of "config.save.php" which is copied by my script for install:
```
<?php
$CONFIG = array (
  'instanceid' => 'ockbfur1449k',
  'passwordsalt' => 'REMOVED',
  'secret' => 'REMOVED',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/srv/www/htdocs/owncloud/data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '8.2.0.9',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'owncloud42',
  'logtimezone' => 'UTC',
  'installed' => false,
'has_internet_connection' => false,
//  'appstoreenabled' => false,
  'appstore.experimental.enabled' => true,
  'loglevel' => 0,

'apps_paths' => array(
        array(
                'path'=> '/srv/www/htdocs/owncloud/apps',
                'url' => '/apps',
                'writable' => true,
        ),
        array(
                'path'=> '/srv/www/htdocs/owncloud/apps2',
                'url' => '/apps2',
                'writable' => false,
        ),
        array(
                'path'=> '/srv/www/htdocs/owncloud/apps3',
                'url' => '/apps3',
                'writable' => false,
        ),
),
  
);
```

**Comment by PVince81** [comment]
If I change resetoc.sh to not use this config.php and delete config.php instead, the setup works fine... Hmmm...

**Comment by PVince81** [comment]
Setup works with v10.0.8 but not on recent commits... Bisecting...

**Comment by PVince81** [comment]
Here we go: f6f40e1a5cfc2b38969fe074fc94a74dce3ab717 from https://github.com/owncloud/core/pull/31428

@tomneedham see above

Not sure if this is expected now. I'm worried about other people using similar scripts.

cc @DeepDiver1975 auth pudding stuff

**Comment by PVince81** [comment]
If I clear cookies after seeing the error, I'm able to login.

**Comment by PVince81** [comment]
- Option 1: declare this "by design" as I'm reusing instance id from an old instance so the session cookie cannot be valid. => close
- Option 2: do more research and/or revert the fix in question to restore old behavior

@tomneedham @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> Option 1: declare this "by design" as I'm reusing instance id from an old instance so the session cookie cannot be valid. => close

:heavy_check_mark:

**Comment by PVince81** [comment]
Had a chat with @tomneedham and @butonic to understand the situation better.

Problem: we have an risky auth/session related PR https://github.com/owncloud/core/pull/31428 in stable10 for which we cannot guarantee that there are no side effects because there is no time for QA to schedule full auth regression testing.

The problem is question is that the PR itself prevents the creation of duplicate auth tokens in the database. An alternative fix is https://github.com/owncloud/core/pull/31460 which is much less intrusive and will not require full regression test. The duplicate check is necessary to avoid massive exception logging in some environments and scenarios as observed already.

The plan:
- [ ] revert https://github.com/owncloud/core/pull/31428 on stable10
- [ ] merge and backport https://github.com/owncloud/core/pull/31460 (the duplicate check)
- [ ] release 10.0.9
- [ ] reschedule https://github.com/owncloud/core/pull/31428 to be added in 10.0.10, because there we already have full auth regression test planned for password policy

In general this means that for 10.0.10 there should be no additional QA effort. However if we find some bigger issues with https://github.com/owncloud/core/pull/31428 we might need to revert it again.

@patrickjahns @DeepDiver1975 FYI
