### ISSUE TITLE
Setup page for stable10 / 10.0.9beta broken, chicken-egg problem

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31741]
### Steps

1. Extract OC 10.0.9 beta tarball
1. Run web UI setup

### Expected result
Setup page can be displayed

### Actual result
Internal server error
```
{"reqId":"yKtlzrlF0piZbdby9pK3","level":3,"time":"2018-06-12T20:36:16+00:00","remoteAddr":"127.0.0.1","user":"--","app":"index","method":"GET","url":"\/owncloudtest\/","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM \\\"oc_appconfig\\\"':\\n\\nSQLSTATE[HY000]: General error: 1 no such table: oc_appconfig\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM \\\"...', Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/DB\\\/Connection.php(189): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT * FROM \\\"...', Array, Array, NULL)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT * FROM \\\"...', Array, Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/AppConfig.php(301): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/AppConfig.php(122): OC\\\\AppConfig->loadConfigValues()\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/AllConfig.php(185): OC\\\\AppConfig->getValue('core', 'legal.imprint_u...', '')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/legacy\\\/defaults.php(307): OC\\\\AllConfig->getAppValue('core', 'legal.imprint_u...', '')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/legacy\\\/defaults.php(254): OC_Defaults->getImprintUrl()\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/legacy\\\/defaults.php(274): OC_Defaults->getShortFooter()\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/core\\\/templates\\\/layout.guest.php(51): OC_Defaults->getLongFooter()\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/Template\\\/Base.php(221): include('\\\/srv\\\/www\\\/htdocs...')\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/Template\\\/Base.php(196): OC\\\\Template\\\\Base->load('\\\/srv\\\/www\\\/htdocs...', NULL)\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/legacy\\\/template.php(233): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/legacy\\\/template.php(255): OC_Template->fetchPage()\\n#16 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/Template\\\/Base.php(177): OC_Template->fetchPage()\\n#17 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/legacy\\\/template.php(321): OC\\\\Template\\\\Base->printPage()\\n#18 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/core\\\/Controller\\\/SetupController.php(95): OC_Template::printGuestPage('', 'installation', Array)\\n#19 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/core\\\/Controller\\\/SetupController.php(75): OC\\\\Core\\\\Controller\\\\SetupController->display(Array)\\n#20 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/base.php(856): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#21 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/index.php(55): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":58}"}
```

### Version
ownCloud 10.0.9beta

The bug is likely introduce by https://github.com/owncloud/core/pull/31704. The setup page is using the regular footer in which the imprint / privacy policy URL must be injected. For these, the DB is required for accessing the appconfig settings. However the DB hasn't been setup yet...

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/13402 (... broken), https://github.com/owncloud/core/pull/30329 ([stable10] hotfix 10.0.6 commits), https://github.com/owncloud/core/pull/30535 (Merge Hotfix 10.0.7 back to stable10), and https://github.com/owncloud/core/issues/27476 (Cannot migrate from 9.1.4 to daily master, oc_accounts table does not exist).

**Comment by PVince81** [comment]
We need to detect whether OC is installed before reading the config.

I wonder if it would be possible and safe to add code in the IAppConfig implementation to return a dummy object that returns empty for any settings. This would cover any other code paths that might try to access app config settings when DB was not setup.

@VicDeo can you have a look ?

**Comment by PVince81** [comment]
@DeepDiver1975 any thoughts on the above approach or would it be too dangerous ?

**Comment by DeepDiver1975** [comment]
LBS:

```
	public function getImprintUrl() {
		try {
			return $this->config->getAppValue('core', 'legal.imprint_url', '');
		} catch (Exception $ex) {
			return '';
		}
	}
