### ISSUE TITLE
App password error after password reset

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#32038]
### Steps to reproduce
1. Comment out `$lastCheck` logic in lib/private/User/Session.php
1. Login as admin
1. Create a user "user1" with password "test" and an email address
1. Login as "user1"
1. Create an app password and copy it
1. Curl PROPFIND with the app password: `curl -D - -X PROPFIND -u user1:HPJSK-RWOXW-ZNBIH-AFSBH http://localhost/owncloud/remote.php/dav/files/user1/`
1. Log out
1. Login as "user1" with wrong password
1. Get password reset link by email and open it
1. Set the password to "test2"
1. Run the curl again with app password

### Expected result
No error, password invalidated (as observed on working systems)

### Actual result
Error during curl

### Log
```
{"reqId":"KWi8eMArwsxAciHW4i9t","level":3,"time":"2018-07-12T16:42:57+00:00","remoteAddr":"127.0.0.1","user":"--","app":"remote","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/user1\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getUID() on null\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(883): OC\\\\User\\\\Session->checkTokenCredentials(Object(OC\\\\Authentication\\\\Token\\\\DefaultToken), 'HPJSK-RWOXW-ZNB...')\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(331): OC\\\\User\\\\Session->validateToken(*** sensitive parameters replaced ***)\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(362): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(133): OC\\\\User\\\\Session->logClientIn(*** sensitive parameters replaced ***)\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php(105): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->validateUserPass(*** sensitive parameters replaced ***)\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(249): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(201): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(150): Sabre\\\\DAV\\\\Auth\\\\Plugin->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#9 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n
#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(282): Sabre\\\\DAV\\\\Server->exec()\\n
#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n
#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(165): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#16 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php\",\"Line\":825}"}
```

### Version
v10.0.9RC3

Regression from: v10.0.8

**Comment by phil-davis** [comment]
There have been other issues related to ``Call to a member function getUID() on null`` so maybe some of those other ways that code was calling ``getUID()`` in a bad way will give hints here also. e.g.
https://github.com/owncloud/core/issues/30335
https://github.com/owncloud/core/pull/30418

**Comment by PVince81** [comment]
@phil-davis any ticket with this error that is not post 10.0.8 is likely unrelated.

The code where the exception happens only exists on stable10 and in 10.0.9 RC as that's where we added the logging code that tries to read values from the `activeUser` by assuming that it's defined.

I'm wondering whether we should just remove all this logging stuff. It makes it harder to debug other stuff.

**Comment by phil-davis** [comment]
It certainly spews a lot of messages into the log when debug is enabled.
We need ``debug-level-+`` that can spew out even more than ``debug`` ;)

**Comment by PVince81** [comment]
PR is here https://github.com/owncloud/core/pull/32041
