### ISSUE TITLE
Files get locked after Ctrl+C interrupt decrypt command

### ISSUE THREAD

**Issue by davitol** [owncloud/core#32616]
### Steps to reproduce

1 - create 2 users admin and user1 
2 - Enable encryption with user-keys. Login as admin and user1.
3 - Now try to run decrypt-all command as follows: `./occ encryption:decrypt-all -c yes`
4 - set admin pwd
5 - Stop the command with crtl ^c
6 - re-enable encryption `./occ encryption:enable`
7  - re-run `./occ encryption:decrypt-all -c yes`

### Expected behaviour

Files should not get locked.

### Actual behaviour

Files get locked. In the rename operation, the file gets locked. And once the file gets locked try to give Ctrl+C interrupt.

![screen shot 2018-09-06 at 10 31 48](https://user-images.githubusercontent.com/10596560/45145094-1ccf8780-b1c0-11e8-92c4-c26852a5a434.png)

### Server logs

```
{"reqId":"fIPdClUXId4qyQRzPcM3","level":3,"time":"2018-09-05T15:07:06+00:00","remoteAddr":"","user":"--","app":"OC\\Encryption\\DecryptAll","method":"--","url":"--","message":"Exception trying to decrypt file <\/admin\/files\/file1.txt> for user <admin>: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'INSERT INTO \\\"oc_file_locks\\\" (\\\"key\\\",\\\"lock\\\",\\\"ttl\\\") SELECT ?,?,?  WHERE NOT EXISTS (SELECT 1 FROM \\\"oc_file_locks\\\" WHERE \\\"key\\\" = ?)' with params [\\\"files\\\\\\\/7ff417ff21a5d83e5e739f9907ece177\\\", 1, 1536163626, \\\"files\\\\\\\/7ff417ff21a5d83e5e739f9907ece177\\\"]:\\n\\nSQLSTATE[HY000]: General error: 5 database is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1015):
```

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**ownCloud version:**

ownCloud 10.0.10RC1

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
Yes

**Logs**

```
No logs in owncloud.log
```

### Client configuration

**browser**

Firefox

**Comment by PVince81** [comment]
it is possible that when ctrl+c is hit, PHP doesn't run the shutdown handler and destructors, so it wouldn't release the file locks

if that's the case, we need to add a handler for ctrl+c (pcntl extension) and somehow initiate graceful shutdown

@DeepDiver1975

**Comment by sharidas** [comment]
I was able to reproduce this error, by having Ctrl+C during rename operation at https://github.com/owncloud/core/blob/stable10/lib/private/Files/View.php#L1987.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22171 (Interruptable occ commands do not get interrupted when pressed ctrl-c), https://github.com/owncloud/core/issues/26838 (File locking), https://github.com/owncloud/core/issues/24737 (File Locked), https://github.com/owncloud/core/issues/28991 (file is locked), and https://github.com/owncloud/core/issues/16895 (File not decrypting).

**Comment by PVince81** [comment]
Another solution would be to provide an occ command to release the lock for all files.
The alternative is waiting one hour then running cron for lock expiration...

In a scenario where the admin decided to interrupt decryption after realizing that it takes longer than expected, they should be able to recover quickly from the file locks. That's where an occ command would come handy.

**Comment by DeepDiver1975** [comment]
🤖 Automated issue triage by Claude Code review agent.

This issue was opened before 2020 and has had no activity since then, so we are closing it as outdated. If this is still relevant on a current ownCloud release, please **reopen** (or open a fresh issue) with up-to-date details — thank you!
