### ISSUE TITLE
[10.0.10RC1] password cannot be "0" on the  "New User Registration Page"

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32626]
### Steps to reproduce
1. as admin create a user using the webUI
2. receive the user creation email
3. click on the set-password link
4. enter `0` as the password

### Expected behaviour
password is set or error message shown

### Actual behaviour
no error message shown to the user, password is not set, user stays on the page not knowing what happened
### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache2
**Database:**
sqlite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
10.0.10RC1
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
https://download.owncloud.org/community/testing/owncloud-10.0.10RC1.tar.bz2

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocqc3dn84731",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-10.0.10\/RC1\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-10.0.10\/RC1",
        "dbtype": "sqlite3",
        "version": "10.0.10.0",
        "logtimezone": "UTC",
        "installed": true
    },
    "apps": {
        "backgroundjob": {
            "lastjob": "3"
        },
        "comments": {
            "installed_version": "0.3.0",
            "types": "logging,dav",
            "enabled": "yes"
        },
        "configreport": {
            "installed_version": "0.1.1",
            "types": "filesystem",
            "enabled": "yes"
        },
        "core": {
            "installedat": "1536292163.739",
            "lastupdatedat": "1536297575",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "public_files": "files_sharing\/public.php",
            "first_install_version": "10.0.10.0",
            "lastcron": "1536298661",
            "lastupdateResult": "[]",
            "oc.integritycheck.checker": "{\"core\":{\"INVALID_HASH\":{\".htaccess\":{\"expected\":\"6fd2bca47deffbdf905bcd30ee3b487584823481202ecde931ee6527514be04d84e19aa3252d252347c5a7f0519fa903c1335de0ca26b111c2ea663300f4682f\",\"current\":\"cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e\"}},\"FILE_MISSING\":{\".user.ini\":{\"expected\":\"0a557e3cdca4c2e3675deed761d79d109011dcdebbd9c7f6429f1d3476938ec95729543d7384651d1d0c48e26c5024cc5f517445920915a704ea748bdb903c5f\",\"current\":\"\"}}}}"
        },
        "dav": {
            "installed_version": "0.4.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "federatedfilesharing": {
            "installed_version": "0.3.1",
            "types": "filesystem",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "0.1.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.5.1",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500"
        },
        "files_external": {
            "installed_version": "0.7.1",
            "ocsid": "166048",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_sharing": {
            "installed_version": "0.11.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_trashbin": {
            "installed_version": "0.9.1",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.3.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_videoplayer": {
            "installed_version": "0.9.8",
            "types": "",
            "enabled": "yes"
        },
        "firstrunwizard": {
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": "",
            "enabled": "yes"
        },
        "market": {
            "installed_version": "0.2.5",
            "types": "",
            "enabled": "yes"
        },
        "notifications": {
            "installed_version": "0.3.5",
            "types": "logging",
            "enabled": "yes"
        },
        "provisioning_api": {
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "systemtags": {
            "installed_version": "0.3.0",
            "types": "logging",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "0.2.1",
            "types": "",
            "enabled": "yes"
        }
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.5
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF 61.0.1
**Operating system:**
Ubuntu 18.04

#### ownCloud log (data/owncloud.log)
```
{"reqId":"w44RTFFtx7V4exCXIZMR","level":3,"time":"2018-09-07T05:58:37+00:00","remoteAddr":"127.0.0.1","user":"--","app":"index","method":"POST","url":"\/owncloud-10.0.10\/RC1\/index.php\/setpassword\/106663364831989254860\/uu3","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Password cannot be empty\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-10.0.10\\\/RC1\\\/settings\\\/Controller\\\/UsersController.php(660): OC\\\\User\\\\User->setPassword('0')\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-10.0.10\\\/RC1\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OC\\\\Settings\\\\Controller\\\\UsersController->setPassword('106663364831989...', 'uu3', '0')\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-10.0.10\\\/RC1\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'setPassword')\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-10.0.10\\\/RC1\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'setPassword')\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-10.0.10\\\/RC1\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('UsersController', 'setPassword', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#5 \\\/home\\\/artur\\\/www\\\/owncloud-10.0.10\\\/RC1\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#6 \\\/home\\\/artur\\\/www\\\/owncloud-10.0.10\\\/RC1\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/setpassword\\\/10...')\\n#7 \\\/home\\\/artur\\\/www\\\/owncloud-10.0.10\\\/RC1\\\/index.php(54): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-10.0.10\\\/RC1\\\/lib\\\/private\\\/User\\\/User.php\",\"Line\":294}"}
```

**Comment by phil-davis** [comment]
master PR #32261 stable10 PR #32581 implemented this.
The password cannot be the empty string, and it cannot be "0".
This needs to be either documented, or fixed to allow the string "0" as a password.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/32624 ([10.0.10RC1] cannot change users password on users-page with FF), https://github.com/owncloud/core/issues/22991 (Send password to new users), https://github.com/owncloud/core/issues/10092 (User Password Reset), https://github.com/owncloud/core/issues/4658 (5.0.11RC1 Not possible to access to new users), and https://github.com/owncloud/core/issues/32565 (SmokeTest Results 10.0.10RC1).

**Comment by PVince81** [comment]
not critical for the current release, moving to backlog

**Comment by JanAckermann** [comment]
Checked with latest master, not an issue anyore
