### ISSUE TITLE
Deleting a file from the trashbin throws an exception

### ISSUE THREAD

**Issue by davitol** [owncloud/core#33026]
### Steps to reproduce

1. In files view delete a file 
2. In trashbin view, delete the file

### Current behavior

An exception is shown in owncloud.log

Tested with oC 10.0.10. and files_trashbin: 0.9.1

```
{"reqId":"NtOh57amuLUerBaRCARB","level":3,"time":"2018-10-05T08:31:21+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"no app in context","method":"POST","url":"\/index.php\/apps\/files_trashbin\/ajax\/delete.php","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/admin\\\/files\\\/files_trashbin\\\/files\\\/ownCloud Manual.pdf.d1538728267\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(129): OC\\\\Files\\\\Node\\\\Root->get('\\\/admin\\\/files\\\/fi...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(1249): OC\\\\Files\\\\Node\\\\Folder->get('\\\/files_trashbin...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OC\\\\Preview::prepare_delete(Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(625): OC_Hook::emit('\\\\\\\\OCP\\\\\\\\Trashbin', 'preDelete', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(664): OCA\\\\Files_Trashbin\\\\Trashbin::emitTrashbinPreDelete('\\\/files_trashbin...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/ajax\\\/delete.php(65): OCA\\\\Files_Trashbin\\\\Trashbin::delete('ownCloud Manual...', 'admin', '1538728267')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(NULL)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_tra...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php\",\"Line\":192}"}
{"reqId":"NtOh57amuLUerBaRCARB","level":1,"time":"2018-10-05T08:31:21+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"admin_audit","method":"POST","url":"\/index.php\/apps\/files_trashbin\/ajax\/delete.php","message":"DeleteFromTrash \"\/admin\/files_trashbin\/files\/ownCloud Manual.pdf.d1538728267\" by user <admin>, displayName <admin>, owner: admin [CLIENT_IP: 172.18.0.1] [USER_AGENT: Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/69.0.3497.100 Safari\/537.36]"}
{"reqId":"NtOh57amuLUerBaRCARB","level":3,"time":"2018-10-05T08:31:21+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"no app in context","method":"POST","url":"\/index.php\/apps\/files_trashbin\/ajax\/delete.php","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/admin\\\/files\\\/files_trashbin\\\/files\\\/ownCloud Manual.pdf.d1538728267\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(129): OC\\\\Files\\\\Node\\\\Root->get('\\\/admin\\\/files\\\/fi...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(1319): OC\\\\Files\\\\Node\\\\Folder->get('\\\/files_trashbin...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OC\\\\Preview::post_delete(Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(633): OC_Hook::emit('\\\\\\\\OCP\\\\\\\\Trashbin', 'delete', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(666): OCA\\\\Files_Trashbin\\\\Trashbin::emitTrashbinPostDelete('\\\/files_trashbin...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/ajax\\\/delete.php(65): OCA\\\\Files_Trashbin\\\\Trashbin::delete('ownCloud Manual...', 'admin', '1538728267')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(NULL)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_tra...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php\",\"Line\":192}"}
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/27274 (delete), https://github.com/owncloud/core/issues/28095 (Deleting a 250 char file does not move it to the trash but throws an exception), https://github.com/owncloud/core/issues/13824 (Delete File), https://github.com/owncloud/core/issues/25619 (occ throws unhandled exception), and https://github.com/owncloud/core/pull/32148 ([stable10] throw exception when json_decode of log fails).

**Comment by JanAckermann** [comment]
Closing for now, if this bug is still existing, please reopen
