### ISSUE TITLE
No storage usage information available 

### ISSUE THREAD

**Issue by gabiann** [owncloud/core#33178]
Hi all,
One single account of 40 configured is experiencing problems uploading files.
All the syncs fails with the message "There is insufficient space available on the server for uploads".
In the desktop client e in the web interface the are no informations about the space usage and the available space.
In the desktop client the message is "Currently there is no storage usage information available".

SERVER CONFIGURATION : 

OS : Centos 7.4.1708
Webserver : Apache 2.4.28
Php : 7.0.32
Owncloud 10.0.10
MariaDB : 10.3.2

LDAP Integration ( release 0.11.0 ) is configured to interface owncloud with the active directory who provides authentication.
Actually quotas are configured : 500 GB default. The user experiencing the issue has a quota of 1024 GB.

Owncloud desktop client version 2.5.0

LOG ENTRY :

{"reqId":"9eaadb9b-dcef-4fa2-afff-957689e4b7fa","level":0,"time":"2018-10-12T09:42:15+00:00","remoteAddr":"188.216.44.90","user":"B80F44ED-CB71-4E18-86A7-8C1C40687781","app":"webdav","metho
d":"PUT","url":"\/remote.php\/dE-4E18-54RF-8C1C40687781\/Documents\/Private\123456qazwsc.pdf","message":"Exception: HTTP\/1.1 50
7 Insufficient Storage: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\InsufficientStorage\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/store1\\\/www\\\/owncloud\\\/v10.0.10\\\/apps\\\/d
av\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php(133): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\QuotaPlugin->checkQuota('\\\/Documents\\\/Priv...')\\n#1 [internal function]: OCA\\\\DAV\\\\Conn
ector\\\\Sabre\\\\QuotaPlugin->handleBeforeCreateFile('files\\\/B80F44ED-...', Resource id #484, Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory), false)\\n#2 \\\/store1\\\/www\\\/ownc
loud\\\/v10.0.10\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/store1\\\/www\\\/owncloud\\\/v10.0.10\\\/lib\\\/compo
ser\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1093): Sabre\\\\Event\\\\EventEmitter->emit('beforeCreateFil...', Array)\\n#4 \\\/store1\\\/www\\\/owncloud\\\/v10.0.10\\\/lib\\\/composer\\\
/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('files\\\/B80F44ED-...', Resource id #484, NULL)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin-
>httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/store1\\\/www\\\/owncloud\\\/v10.0.10\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait
.php(105): call_user_func_array(Array, Array)\\n#7 \\\/store1\\\/www\\\/owncloud\\\/v10.0.10\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmit
ter->emit('method:PUT', Array)\\n#8 \\\/store1\\\/www\\\/owncloud\\\/v10.0.10\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Objec
t(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/store1\\\/www\\\/owncloud\\\/v10.0.10\\\/apps\\\/dav\\\/lib\\\/Server.php(298): Sabre\\\\DAV\\\\Server->exec()\\n#10
 \\\/store1\\\/www\\\/owncloud\\\/v10.0.10\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/store1\\\/www\\\/owncloud\\\/v10.0.10\\\/remote.php(165)
: require_once('\\\/store1\\\/www\\\/own...')\\n#12 {main}\",\"File\":\"\\\/store1\\\/www\\\/owncloud\\\/v10.0.10\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php\",\"Line\":1
68}"}

Thank you and regards,

**Comment by gabiann** [comment]
No external storages are configured.
The datadir is an nfs mounted directory.
The files directory size of the user that is facing the issue is 53 GB ( default quota is 500 GB and user quota is 1024 GB )
