### ISSUE TITLE
[webUI tests] stale element reference checking thumbnail in details panel

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33330]
The following scenario, and similar ones that check the thumbnail in the details panel, sometimes fail:
```
  Scenario: the recipient user should be able to view different areas of details panel in Shared with you page # /drone/src/tests/acceptance/features/webUIFiles/fileDetails.feature:70
    Given the user has shared the folder "simple-folder" with the user "User Two" using the webUI              # WebUISharingContext::theUserSharesTheFileFolderWithTheUserUsingTheWebUI()
    And the user re-logs in as "user2" using the webUI                                                         # WebUILoginContext::theUserRelogsInUsingTheWebUI()
    When the user browses to the shared-with-you page                                                          # WebUIFilesContext::theUserBrowsesToTheSharedWithYouPage()
    Then the folder "simple-folder (2)" should be listed on the webUI                                          # WebUIFilesContext::theFileFolderShouldBeListedOnTheWebUI()
    When the user opens the file action menu of the folder "simple-folder (2)" in the webUI                    # WebUIFilesContext::theUserOpensTheFileActionMenuOfTheFolderInTheWebui()
    And the user clicks the details file action in the webUI                                                   # WebUIFilesContext::theUserClicksTheFileActionInTheWebui()
    Then the details dialog should be visible in the webUI                                                     # WebUIFilesContext::theDetailsDialogShouldBeVisibleInTheWebui()
    And the thumbnail should be visible in the details panel                                                   # WebUIFilesContext::theThumbnailShouldBeVisibleInTheDetailsPanel()
      WebDriver\Exception\StaleElementReference: stale element reference: element is not attached to the page document
        (Session info: chrome=70.0.3538.77)
        (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.4.0-135-generic x86_64) in /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
      Stack trace:
      #0 /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory(10, 'stale element r...')
      #1 /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(218): WebDriver\AbstractWebDriver->curl('POST', '/execute', Array)
      #2 /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/Container.php(224): WebDriver\AbstractWebDriver->__call('execute', Array)
      #3 /drone/src/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(288): WebDriver\Container->__call('execute', Array)
      #4 /drone/src/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(263): Behat\Mink\Driver\Selenium2Driver->executeJsOnElement(Object(WebDriver\Element), 'return argument...', true)
      #5 /drone/src/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(554): Behat\Mink\Driver\Selenium2Driver->executeJsOnXpath('((//html/.//*[c...', 'return {{ELEMEN...')
      #6 /drone/src/lib/composer/behat/mink/src/Element/NodeElement.php(129): Behat\Mink\Driver\Selenium2Driver->getAttribute('((//html/.//*[c...', 'style')
      #7 /drone/src/tests/acceptance/features/bootstrap/WebUIFilesContext.php(287): Behat\Mink\Element\NodeElement->getAttribute('style')
      #8 [internal function]: WebUIFilesContext->theThumbnailShouldBeVisibleInTheDetailsPanel()
```
e.g. it happened just now in core: https://drone.owncloud.com/owncloud/core/12093/493
and it has happened sometimes in when running with encryption and/or object store (files_primary_s3) - those are apps that have some impact on the backend timing/performance...

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), and https://github.com/owncloud/core/issues/32143 (MinkSelenium2Driver recent change breaks webUI tests).

**Comment by phil-davis** [comment]
Sample fail in test run with encryption: https://drone.owncloud.com/owncloud/encryption/278/721
```
  Scenario: user shares a file and then the details dialog should work in a Shared with others page # /var/www/owncloud/tests/acceptance/features/webUIFiles/fileDetails.feature:57
    Given the user has shared the folder "simple-folder" with the user "User Two" using the webUI   # WebUISharingContext::theUserSharesTheFileFolderWithTheUserUsingTheWebUI()
    When the user browses to the shared-with-others page                                            # WebUIFilesContext::theUserBrowsesToTheSharedWithOthersPage()
    Then the folder "simple-folder" should be listed on the webUI                                   # WebUIFilesContext::theFileFolderShouldBeListedOnTheWebUI()
    When the user opens the file action menu of the folder "simple-folder" in the webUI             # WebUIFilesContext::theUserOpensTheFileActionMenuOfTheFolderInTheWebui()
    And the user clicks the details file action in the webUI                                        # WebUIFilesContext::theUserClicksTheFileActionInTheWebui()
    Then the details dialog should be visible in the webUI                                          # WebUIFilesContext::theDetailsDialogShouldBeVisibleInTheWebui()
    And the thumbnail should be visible in the details panel                                        # WebUIFilesContext::theThumbnailShouldBeVisibleInTheDetailsPanel()
      WebDriver\Exception\StaleElementReference: stale element reference: element is not attached to the page document
        (Session info: chrome=70.0.3538.77)
        (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.4.0-135-generic x86_64) in /var/www/owncloud/lib/composer/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
      Stack trace:
      #0 /var/www/owncloud/lib/composer/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory(10, 'stale element r...')
      #1 /var/www/owncloud/lib/composer/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(218): WebDriver\AbstractWebDriver->curl('POST', '/execute', Array)
      #2 /var/www/owncloud/lib/composer/instaclick/php-webdriver/lib/WebDriver/Container.php(224): WebDriver\AbstractWebDriver->__call('execute', Array)
      #3 /var/www/owncloud/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(288): WebDriver\Container->__call('execute', Array)
      #4 /var/www/owncloud/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(263): Behat\Mink\Driver\Selenium2Driver->executeJsOnElement(Object(WebDriver\Element), 'return argument...', true)
      #5 /var/www/owncloud/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(554): Behat\Mink\Driver\Selenium2Driver->executeJsOnXpath('((//html/.//*[c...', 'return {{ELEMEN...')
      #6 /var/www/owncloud/lib/composer/behat/mink/src/Element/NodeElement.php(129): Behat\Mink\Driver\Selenium2Driver->getAttribute('((//html/.//*[c...', 'style')
      #7 /var/www/owncloud/tests/acceptance/features/bootstrap/WebUIFilesContext.php(287): Behat\Mink\Element\NodeElement->getAttribute('style')
      #8 [internal function]: WebUIFilesContext->theThumbnailShouldBeVisibleInTheDetailsPanel()
```

**Comment by phil-davis** [comment]
Sample fail in an ordinary core drone job:
https://drone.owncloud.com/owncloud/core/12599/472
```
  Scenario: user shares a file through public link and then the details dialog should work in a Shared by link page # /drone/src/tests/acceptance/features/webUIFiles/fileDetails.feature:44
    Given the user has created a new public link for the folder "simple-folder" using the webUI                     # WebUISharingContext::theUserCreatesANewPublicLinkForUsingTheWebUI()
    When the user browses to the shared-by-link page                                                                # WebUIFilesContext::theUserBrowsesToTheSharedByLinkPage()
    Then the folder "simple-folder" should be listed on the webUI                                                   # WebUIFilesContext::theFileFolderShouldBeListedOnTheWebUI()
    When the user opens the file action menu of the folder "simple-folder" in the webUI                             # WebUIFilesContext::theUserOpensTheFileActionMenuOfTheFolderInTheWebui()
    And the user clicks the details file action in the webUI                                                        # WebUIFilesContext::theUserClicksTheFileActionInTheWebui()
    Then the details dialog should be visible in the webUI                                                          # WebUIFilesContext::theDetailsDialogShouldBeVisibleInTheWebui()
    And the thumbnail should be visible in the details panel                                                        # WebUIFilesContext::theThumbnailShouldBeVisibleInTheDetailsPanel()
      WebDriver\Exception\StaleElementReference: stale element reference: element is not attached to the page document
        (Session info: chrome=70.0.3538.102)
        (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.4.0-135-generic x86_64) in /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
      Stack trace:
      #0 /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory(10, 'stale element r...')
      #1 /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(218): WebDriver\AbstractWebDriver->curl('POST', '/execute', Array)
      #2 /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/Container.php(224): WebDriver\AbstractWebDriver->__call('execute', Array)
      #3 /drone/src/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(288): WebDriver\Container->__call('execute', Array)
      #4 /drone/src/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(263): Behat\Mink\Driver\Selenium2Driver->executeJsOnElement(Object(WebDriver\Element), 'return argument...', true)
      #5 /drone/src/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(554): Behat\Mink\Driver\Selenium2Driver->executeJsOnXpath('((//html/.//*[c...', 'return {{ELEMEN...')
      #6 /drone/src/lib/composer/behat/mink/src/Element/NodeElement.php(129): Behat\Mink\Driver\Selenium2Driver->getAttribute('((//html/.//*[c...', 'style')
      #7 /drone/src/tests/acceptance/features/bootstrap/WebUIFilesContext.php(287): Behat\Mink\Element\NodeElement->getAttribute('style')
      #8 [internal function]: WebUIFilesContext->theThumbnailShouldBeVisibleInTheDetailsPanel()
      #9 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(109): call_user_func_array(Array, Array)
      #10 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(64): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
```
