### ISSUE TITLE
403 errors after moving

### ISSUE THREAD

**Issue by thommierother** [owncloud/core#33563]
When moving files, I frequently see the following pattern in the log:

```
{"reqId":"p1fxfIXNyd9SvUugiiEv","level":2,"time":"November 18, 2018 15:00:02","remoteAddr":"","user":"--","app":"filesystem","method":"--","url":"--","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"p1fxfIXNyd9SvUugiiEv","level":3,"time":"November 18, 2018 15:00:02","remoteAddr":"","user":"--","app":"files","method":"--","url":"--","message":"Exception: {\"Exception\":\"OC\\\\ForbiddenException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(139): OC\\\\Files\\\\Utils\\\\Scanner->shouldScan(Object(OC\\\\Files\\\\Mount\\\\MountPoint))\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(57): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/var\\\/www\\\/owncloud\\\/cron.php(120): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php\",\"Line\":192}"}
```

The client shows a 403 forbidden from the server but returns to "green" state shortly later. An idea about the reason or possible workarounds? Note: the server uses user key encryption
OC 10.0.0.10 stable,

**Comment by PVince81** [comment]
seems the logs are unrelated ? they look like they were triggered from cron.

Maybe some of your external storages or received federated shares have some blocked/forbidden entries ? Maybe the real error is on the target server.

**Comment by thommierother** [comment]
I have federation on this system with two other instances, both nextcloud 13, so it is possible that the root cause comes from the federation partner. Closing issue because the error disappears and is not permanent
