### ISSUE TITLE
Can't run local Drone with object store, race condition

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33863]
### Steps

1. git clone of master 5f51318b75bf4532ce53df7c29b7f4a2593a528c
2. `sudo rm -Rf config/config.php apps/{testing,files_primary_s3} && docker network prune -f && docker volume prune -f` (to cleanup)
3. `PHP_VERSION=7.1 DB_TYPE=sqlite TEST_SUITE=phpunit INSTALL_SERVER=true COVERAGE=false TEST_OBJECTSTORAGE=true drone exec`

### Expected
phpunit tests run

### Actual
Failure during setup, it seems install_server.sh is running too early, before the files_primary_s3 app can be installed. Or maybe config.php is mounted too early with the object store settings while the files_primary_s3 app isn't installed yet.
```
[scality:L0:0s] Host name has been modified to scality
[scality:L1:0s] Note: In your /etc/hosts file on Linux, OS X, or Unix with root permissions, make sure to associate 127.0.0.1 with scality
[scality:L2:0s] 
[scality:L3:0s] > s3@7.4.0 start /usr/src/app
[scality:L4:0s] > npm-run-all --parallel start_dmd start_s3server
[scality:L5:0s] 
[scality:L6:1s] 
[scality:L7:1s] > s3@7.4.0 start_s3server /usr/src/app
[scality:L8:1s] > node index.js
[scality:L9:1s] 
[scality:L10:1s] 
[scality:L11:1s] > s3@7.4.0 start_dmd /usr/src/app
[scality:L12:1s] > npm-run-all --parallel start_mdserver start_dataserver
[scality:L13:1s] 
[scality:L14:2s] 
[scality:L15:2s] > s3@7.4.0 start_mdserver /usr/src/app
[scality:L16:2s] > node mdserver.js
[scality:L17:2s] 
[install-server:L0:0s] + ./tests/drone/install-server.sh
[install-server:L1:0s] ++ pwd
[install-server:L2:0s] +++ dirname ./tests/drone/install-server.sh
[install-server:L3:0s] ++ cd ./tests/drone
[install-server:L4:0s] ++ pwd -P
[install-server:L5:0s] + [[ /drone/src == \/\d\r\o\n\e\/\s\r\c\/\t\e\s\t\s\/\d\r\o\n\e ]]
[install-server:L6:0s] + declare -x ADMIN_LOGIN
[install-server:L7:0s] + [[ -z '' ]]
[install-server:L8:0s] + ADMIN_LOGIN=admin
[install-server:L9:0s] + declare -x ADMIN_PASSWORD
[install-server:L10:0s] + [[ -z '' ]]
[install-server:L11:0s] + ADMIN_PASSWORD=admin
[install-server:L12:0s] + declare -x DATA_DIRECTORY
[install-server:L13:0s] + [[ -z '' ]]
[install-server:L14:0s] + DATA_DIRECTORY=/drone/src/data
[install-server:L15:0s] + declare -x DB_TYPE
[install-server:L16:0s] + [[ -z '' ]]
[install-server:L17:0s] + DB_TYPE=sqlite
[install-server:L18:0s] + declare -x DB_PREFIX
[install-server:L19:0s] + [[ -z '' ]]
[install-server:L20:0s] + DB_PREFIX=oc_
[install-server:L21:0s] + declare -x DB_USERNAME
[install-server:L22:0s] + [[ -z '' ]]
[install-server:L23:0s] + DB_USERNAME=owncloud
[install-server:L24:0s] + declare -x DB_PASSWORD
[install-server:L25:0s] + [[ -z '' ]]
[install-server:L26:0s] + DB_PASSWORD=owncloud
[install-server:L27:0s] + declare -x DB_NAME
[install-server:L28:0s] + [[ -z '' ]]
[install-server:L29:0s] + DB_NAME=owncloud
[install-server:L30:0s] + PLUGIN_DB_TIMEOUT=45
[install-server:L31:0s] + [[ -f config/config.php ]]
[install-server:L32:0s] + rm -rf /drone/src/data/index.html /drone/src/data/owncloud.db /drone/src/data/owncloud.log config/config.php
[install-server:L33:0s] + echo 'waiting for database to be ready'
[install-server:L34:0s] waiting for database to be ready
[install-server:L35:0s] + case "${DB_TYPE}" in
[install-server:L36:0s] + DB=sqlite
[install-server:L37:0s] + install_cmd='maintenance:install -vvv       --database=sqlite       --database-name=owncloud       --database-table-prefix=oc_       --admin-user=admin       --admin-pass=admin       --data-dir=/drone/src/data '
[install-server:L38:0s] + [[ sqlite != \s\q\l\i\t\e ]]
[install-server:L39:0s] + php occ maintenance:install -vvv --database=sqlite --database-name=owncloud --database-table-prefix=oc_ --admin-user=admin --admin-pass=admin --data-dir=/drone/src/data
[scality:L18:2s] 
[scality:L19:2s] > s3@7.4.0 start_dataserver /usr/src/app
[scality:L20:2s] > node dataserver.js
[scality:L21:2s] 
[install-server:L40:0s] creating sqlite db
[scality:L22:3s] {"name":"MetadataFileServer","time":1544546485574,"level":"info","message":"creating metadata service at /MDFile/metadata","hostname":"9ec6eb60c002","pid":89}
[scality:L23:3s] {"name":"MetadataFileServer","time":1544546485582,"level":"info","message":"starting metadata file backend server","hostname":"9ec6eb60c002","pid":89}
[scality:L24:3s] {"name":"MetadataFileServer","time":1544546485604,"level":"info","message":"This deployment's identifier is 6b353515-231b-4409-bdeb-4b36233be775","hostname":"9ec6eb60c002","pid":89}
[scality:L25:3s] {"name":"DataFileStore","time":1544546485724,"level":"info","message":"pre-creating 3511 subdirs...","hostname":"9ec6eb60c002","pid":96}
[scality:L26:4s] {"name":"DataFileStore","time":1544546485945,"level":"info","message":"data file store init complete, go forth and store data.","hostname":"9ec6eb60c002","pid":96}
[scality:L27:4s] {"name":"DataFileRESTServer","time":1544546485946,"method":"arsenal.network.Server.start","port":9991,"level":"info","message":"starting Server under http","hostname":"9ec6eb60c002","pid":96}
[scality:L28:4s] {"name":"DataFileRESTServer","time":1544546485968,"method":"arsenal.network.Server._onListening","address":{"address":"127.0.0.1","family":"IPv4","port":9991},"level":"info","message":"Server is listening","hostname":"9ec6eb60c002","pid":96}
[scality:L29:4s] {"name":"MetadataFileClient","time":1544546486453,"level":"info","message":"connecting to metadata service at http://localhost:9990/MDFile/metadata","hostname":"9ec6eb60c002","pid":51}
[scality:L30:4s] {"name":"S3","time":1544546486486,"level":"warn","message":"scality kms unavailable. Using file kms backend unless mem specified.","hostname":"9ec6eb60c002","pid":51}
[scality:L31:4s] {"name":"S3","time":1544546486607,"workerId":1,"workerPid":114,"level":"info","message":"new worker forked","hostname":"9ec6eb60c002","pid":51}
[scality:L32:4s] {"name":"S3","time":1544546486616,"workerId":2,"workerPid":120,"level":"info","message":"new worker forked","hostname":"9ec6eb60c002","pid":51}
[scality:L33:4s] {"name":"S3","time":1544546486642,"workerId":3,"workerPid":126,"level":"info","message":"new worker forked","hostname":"9ec6eb60c002","pid":51}
[scality:L34:4s] {"name":"S3","time":1544546486674,"workerId":4,"workerPid":132,"level":"info","message":"new worker forked","hostname":"9ec6eb60c002","pid":51}
[scality:L35:4s] {"name":"S3","time":1544546486700,"workerId":5,"workerPid":138,"level":"info","message":"new worker forked","hostname":"9ec6eb60c002","pid":51}
[scality:L36:4s] {"name":"S3","time":1544546486726,"workerId":6,"workerPid":144,"level":"info","message":"new worker forked","hostname":"9ec6eb60c002","pid":51}
[scality:L37:4s] {"name":"S3","time":1544546486748,"workerId":7,"workerPid":145,"level":"info","message":"new worker forked","hostname":"9ec6eb60c002","pid":51}
[scality:L38:4s] {"name":"S3","time":1544546486785,"workerId":8,"workerPid":151,"level":"info","message":"new worker forked","hostname":"9ec6eb60c002","pid":51}
[scality:L39:5s] {"name":"S3","time":1544546486809,"workerId":9,"workerPid":157,"level":"info","message":"new worker forked","hostname":"9ec6eb60c002","pid":51}
[scality:L40:5s] {"name":"S3","time":1544546486841,"workerId":10,"workerPid":163,"level":"info","message":"new worker forked","hostname":"9ec6eb60c002","pid":51}
[install-server:L41:2s] ownCloud was successfully installed
[install-server:L42:2s] + echo 'enabling apps'
[install-server:L43:2s] enabling apps
[install-server:L44:2s] + php occ app:enable files_sharing
[install-server:L45:3s] An unhandled exception has been thrown:
[install-server:L46:3s] Error: Class 'OCA\Files_Primary_S3\S3Storage' not found in /drone/src/lib/private/legacy/util.php:111
[install-server:L47:3s] Stack trace:
[install-server:L48:3s] #0 /drone/src/lib/private/legacy/util.php(278): OC_Util::initObjectStoreRootFS(Array)
[install-server:L49:3s] #1 /drone/src/lib/private/Files/Filesystem.php(264): OC_Util::setupFS('')
[install-server:L50:3s] #2 /drone/src/lib/private/Server.php(237): OC\Files\Filesystem::getMountManager(NULL)
[install-server:L51:3s] #3 /drone/src/lib/composer/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
[install-server:L52:3s] #4 /drone/src/lib/private/AppFramework/Utility/SimpleContainer.php(108): Pimple\Container->offsetGet('RootFolder')
[install-server:L53:3s] #5 /drone/src/lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query('RootFolder')
[install-server:L54:3s] #6 /drone/src/lib/private/Server.php(1004): OC\ServerContainer->query('RootFolder')
[install-server:L55:3s] #7 /drone/src/lib/private/AppFramework/DependencyInjection/DIContainer.php(151): OC\Server->getRootFolder()
[install-server:L56:3s] #8 /drone/src/lib/composer/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\DependencyInjection\DIContainer->OC\AppFramework\DependencyInjection\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
[install-server:L57:3s] #9 /drone/src/lib/private/AppFramework/Utility/SimpleContainer.php(108): Pimple\Container->offsetGet('OCP\\Files\\IRoot...')
[install-server:L58:3s] #10 /drone/src/lib/private/AppFramework/Utility/SimpleContainer.php(64): OC\AppFramework\Utility\SimpleContainer->query('OCP\\Files\\IRoot...')
[install-server:L59:3s] #11 /drone/src/lib/private/AppFramework/Utility/SimpleContainer.php(90): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
[install-server:L60:3s] #12 /drone/src/lib/private/AppFramework/Utility/SimpleContainer.php(110): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Files\\Comma...')
[install-server:L61:3s] #13 /drone/src/lib/private/ServerContainer.php(79): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Files\\Comma...')
[install-server:L62:3s] #14 /drone/src/lib/private/Console/Application.php(170): OC\ServerContainer->query('OCA\\Files\\Comma...')
[install-server:L63:3s] #15 /drone/src/lib/private/Console/Application.php(111): OC\Console\Application->loadCommandsFromInfoXml(Array)
[install-server:L64:3s] #16 /drone/src/console.php(105): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
[install-server:L65:3s] #17 /drone/src/occ(11): require_once('/drone/src/cons...')
[print-log:L0:0s] + cat /drone/src/data/owncloud.log
[print-log:L1:0s] {"reqId":"D1IFm73CuH66s0lGCKq4","level":3,"time":"2018-12-11T16:41:26+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"--","url":"--","message":"User backend OC\\User\\Database is returning home: \/drone\/src\/data\/admin for user: admin which differs from existing value: "}
2018/12/11 17:41:34 drone_step_10 : exit code 1
```

This is making debugging/testing with object store difficult locally.

Could this be a race condition ? I don't see any dependency blocks in the drone.yml, if such thing even exists.

@DeepDiver1975

**Comment by PVince81** [comment]
I've added these lines in install_server.sh before enabling of apps:
```
echo Waiting for object store app to appear
while ! test -d apps/files_primary_s3; do sleep 1; done
```

but this now waits forever.

I do see the scality image doing more stuff until it all stops.

Added an `echo` in the "prepare-objectstore" drone commands, but don't see anything appearing in the log.

**Comment by PVince81** [comment]
blocks https://github.com/owncloud/core/pull/33302#issuecomment-446257097

**Comment by patrickjahns** [comment]
@PVince81 
can you double check that no stray configration files was in the `config/` folder?

**Comment by PVince81** [comment]
@patrickjahns thanks for confirming.

I delete "config/config.php" before running drone as per initial post.
I do have other files in there that should not affect OC, will remove them just in case.

**Comment by PVince81** [comment]
ohh, what is this "scality.config.php" file doing in there... ok, will delete.

Thanks, that must have been it.

**Comment by patrickjahns** [comment]
> ohh, what is this "scality.config.php" file doing in there... ok, will delete.

This is copied over when bootstrapping the configuration for `files_primary_s3`.
`drone exec` doesn't cleanup after itself, as the workspace in the CI is temporary.

If drone is green, and locally something fails - I would recommend to start from a clean clone as well. Some gitignore rules also keep stray artifacts/configurations in local working directories

**Comment by patrickjahns** [comment]
Also not sure whats wrong, local run of that git sha finished green with:
```
[phpunit:L734:568s] OK, but incomplete, skipped, or risky tests!
[phpunit:L735:568s] Tests: 9974, Assertions: 54294, Skipped: 110.
```

**Comment by PVince81** [comment]
master should be fine, the branch I'm actually testing is https://github.com/owncloud/core/pull/33302 and it has Drone fails with object store.

running again now, I forgot to pipe the log output into a file

**Comment by PVince81** [comment]
issue reproduced on the branch, I should be able to continue from there.
thanks a lot!

```
[phpunit:L181:267s] 1) OCA\SystemTags\Tests\unit\ActivityListenerTest::testActivityOnMapperEvent with data set #1 ('OCP\SystemTag\ISystemTagObjec...gnTags', 'unassign_tag')
[phpunit:L182:267s] OCP\Files\StorageNotAvailableException: 
[phpunit:L183:267s] 
[phpunit:L184:267s] /drone/src/lib/private/Files/Storage/Wrapper/Availability.php:76
[phpunit:L185:267s] /drone/src/lib/private/Files/Storage/Wrapper/Availability.php:239
[phpunit:L186:267s] /drone/src/lib/private/Files/Storage/Wrapper/Wrapper.php:221
[phpunit:L187:267s] /drone/src/lib/private/Files/View.php:1363
[phpunit:L188:267s] /drone/src/lib/private/Files/View.php:1409
[phpunit:L189:267s] /drone/src/lib/private/Share/Share.php:122
[phpunit:L190:267s] /drone/src/lib/public/Share.php:77
[phpunit:L191:267s] /drone/src/apps/systemtags/lib/Activity/Listener.php:170
[phpunit:L192:267s] /drone/src/apps/systemtags/tests/unit/ActivityListenerTest.php:195
```
