### ISSUE TITLE
shareByPublicLink webUI test scenarios sometimes fail

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33938]
This was noticed in encryption https://drone.owncloud.com/owncloud/encryption/401/386

```
--- Failed scenarios:

    /var/www/owncloud/tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature:87
    /var/www/owncloud/tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature:188
    /var/www/owncloud/tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature:218
    /var/www/owncloud/tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature:260

43 scenarios (39 passed, 4 failed)
421 steps (401 passed, 4 failed, 16 skipped)
85m25.11s (38.65Mb)
webUI test run failed with exit status: 1
```

87 and 260 passed when they ran a 2nd time. 188 and 218 failed the 2nd time also.

The fail is:
```
  Scenario: user shares a public link via email adding few addresses before and then removing some addresses afterwards # /var/www/owncloud/tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature:188
    Given parameter "shareapi_allow_public_notification" of app "core" has been set to "yes"                            # FeatureContext::serverParameterHasBeenSetTo()
    And the user has reloaded the current page of the webUI                                                             # WebUIGeneralContext::theUserReloadsTheCurrentPageOfTheWebUI()
    When the user opens the share dialog for folder "simple-folder"                                                     # WebUISharingContext::theUserOpensTheShareDialogForFileFolder()
    And the user opens the public link share tab                                                                        # WebUISharingContext::theUserHasOpenedThePublicLinkShareTab()
    And the user opens the create public link share popup                                                               # WebUISharingContext::theUserOpensTheCreatePublicLinkSharePopup()
    And the user adds the following email addresses using the webUI:                                                    # WebUISharingContext::theUserAddsTheFollowingEmailAddressesUsingTheWebUI()
      | email           |
      | foo1234@bar.co  |
      | foo5678@bar.co  |
      | foo1234@barr.co |
      | foo5678@barr.co |
    And the user removes the following email addresses using the webUI:                                                 # WebUISharingContext::theUserRemovesTheFollowingEmailAddressesUsingTheWebui()
      | email           |
      | foo1234@bar.co  |
      | foo5678@barr.co |
INFORMATION: timed out waiting for outstanding ajax calls
    And the user creates the public link using the webUI                                                                # WebUISharingContext::createsThePublicLinkUsingTheWebUI()
      │ INFORMATION: timed out waiting for outstanding ajax calls
      exception 'SensioLabs\Behat\PageObjectExtension\PageObject\Exception\ElementNotFoundException' with message 'Page\FilesPageElement\SharingDialogElement\PublicLinkTab::findLinkEntryByName xpath .//*[@class='link-entry--title' and .=%s]/.. could not find link entry with the given name' in /var/www/owncloud/tests/acceptance/features/lib/OwncloudPage.php:823
      Stack trace:
      #0 /var/www/owncloud/tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/PublicLinkTab.php(340): Page\OwncloudPage->assertElementNotNull(NULL, 'Page\\FilesPageE...')
      #1 /var/www/owncloud/tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/PublicLinkTab.php(263): Page\FilesPageElement\SharingDialogElement\PublicLinkTab->findLinkEntryByName('Public link')
      #2 /var/www/owncloud/tests/acceptance/features/bootstrap/WebUISharingContext.php(364): Page\FilesPageElement\SharingDialogElement\PublicLinkTab->getLinkUrl('Public link')
      #3 [internal function]: WebUISharingContext->createsThePublicLinkUsingTheWebUI()
      #4 /var/www/owncloud/lib/composer/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(109): call_user_func_array(Array, Array)
```

**Comment by phil-davis** [comment]
The link name recently got adjusted to be called 'Public link', maybe something in that change? Or a pre-existing timing issue?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/32823 (webUI scenario shareByPublicLink.feature:153 fails sometimes), and https://github.com/owncloud/core/pull/32772 (webUI search tests).

**Comment by individual-it** [comment]
we have `INFORMATION: timed out waiting for outstanding ajax calls` so I assume that the ajax call was send but its still outstanding. With encryption everything just take longer, should we increase that timeout in case of encryption?

**Comment by individual-it** [comment]
did it happen again?

**Comment by phil-davis** [comment]
I have not seen this fail in nightly drone recently. Maybe fixed by other refactoring/fixing of wait-for-page-to-load methods that happened in core late last year. If nightly drone runs pass all weekend, then close this on Monday.

**Comment by phil-davis** [comment]
Test scenarios are passing regularly in drone, both nightly runs and for PRs.
Closing because can't reproduce the problem any more.
