### ISSUE TITLE
User are not able to save the file using LibreOffice after the file was unlocked via webUI

### ISSUE THREAD

**Issue by davitol** [owncloud/core#34153]
### Steps to reproduce
1. Open and edit remotely a file using LibreOffice
2. Via webUI unlock the file (click on the lock in the sidebar)
3. Try to save the file in Libreoffice

### Expected behaviour

User should be able to save the file using LibreOffice

### Actual behaviour

User are not able to save the file using LibreOffice after the file was unlocked via webUI. A log is spotted in owncloud.log and a warning appears in LibreOffice.

<img width="1023" alt="screen shot 2019-01-15 at 16 53 11" src="https://user-images.githubusercontent.com/10596560/51192093-15df2100-18e6-11e9-94e0-0272d1c18422.png">

owncloud.log

```
{"reqId":"YeR00n9yYSlm9rElfRbO","level":4,"time":"2019-01-15T15:49:49+00:00","remoteAddr":"172.20.0.1","user":"admin","app":"webdav","method":"UNLOCK","url":"\/remote.php\/dav\/files\/admin\/pepe.txt","message":"Exception: HTTP\/1.1 409 The locktoken supplied does not match any locks on this entity: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\LockTokenMatchesRequestUri\",\"Message\":\"The locktoken supplied does not match any locks on this entity\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Locks\\\\Plugin->httpUnlock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:UNLOCK', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(288): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Locks\\\/Plugin.php\",\"Line\":306}"}
```

### Server configuration
Ubuntu 16.0.4. LTS

**Web server:**
Apache 2.4.x

**Database:**
MariaDB

**PHP version:**
7.1

**Where did you install ownCloud from:**
https://download.owncloud.org/community/testing/owncloud-10.1.0beta.tar.bz2

<img width="1276" alt="screen shot 2019-01-15 at 17 01 58" src="https://user-images.githubusercontent.com/10596560/51192653-54291000-18e7-11e9-9df1-3ca510ed92dd.png">

**Comment by davitol** [comment]
Note: It also appears this log after a while:

```
{"reqId":"y7I3zHJccpdaSKdhhd64","level":4,"time":"2019-01-15T15:51:03+00:00","remoteAddr":"172.20.0.1","user":"admin","app":"webdav","method":"LOCK","url":"\/remote.php\/dav\/files\/admin\/pepe.txt","message":"Exception: HTTP\/1.1 400 An xml body is required for lock requests: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"An xml body is required for lock requests\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Locks\\\\Plugin->httpLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:LOCK', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(288): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Locks\\\/Plugin.php\",\"Line\":217}"}
```

**Comment by PVince81** [comment]
Hmm, normally one should only unlock the file if for example LibreOffice crashed or the computer in question crashed, leaving the lock in place.

Not sure if it's a proper use case to unlock while a client is still using it.

@DeepDiver1975 thoughts ?

**Comment by DeepDiver1975** [comment]
The behavior of libreoffice is absolutely fine. There is nothing to so for us.
