### ISSUE TITLE
federationSharing acceptance test failures

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#34186]
The following new scenarios seem to be failing too much in regular drone CI runs:
```
--- Failed scenarios:

    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:201
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:219

45 scenarios (43 passed, 2 failed)
466 steps (452 passed, 2 failed, 12 skipped)
31m25.99s (21.50Mb)
```

Need to investigate.

**Comment by phil-davis** [comment]
Example https://drone.owncloud.com/owncloud/core/14358/619
from unrelated PR #34158 
```
  Scenario: test resharing folder and set it as readonly by owner                                                                 # /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:219
    Given using server "LOCAL"                                                                                                    # FeatureContext::usingServer()
    And these users have been created:                                                                                            # FeatureContext::theseUsersHaveBeenCreated()
      | username |
      | user2    |
    When the user shares folder "simple-folder" with remote user "user1@%remote_server_without_scheme%" using the webUI           # WebUISharingContext::theUserSharesFileFolderWithUserUsingTheWebUI()
    And user "user1" re-logs in to "%remote_server%" using the webUI                                                              # WebUILoginContext::theUserRelogsInToUsingTheWebUI()
    And the user accepts the offered remote shares using the webUI                                                                # WebUISharingContext::theUserAcceptsTheOfferedRemoteShares()
    And user "user1" from server "REMOTE" shares "/simple-folder (2)" with user "user2" from server "LOCAL" using the sharing API # FederationContext::userFromServerSharesWithUserFromServerUsingTheSharingAPI()
    And user "user1" re-logs in to "%local_server%" using the webUI                                                               # WebUILoginContext::theUserRelogsInToUsingTheWebUI()
    And the user opens the share dialog for folder "simple-folder"                                                                # WebUISharingContext::theUserOpensTheShareDialogForFileFolder()
    And the user sets the sharing permissions of "user2@%local_server% (federated)" for "simple-folder" using the webUI to        # WebUISharingContext::theUserSetsTheSharingPermissionsOfForOnTheWebUI()
      | edit | no |
      SensioLabs\Behat\PageObjectExtension\PageObject\Exception\ElementNotFoundException: Page\FilesPageElement\SharingDialog::setSharingPermissions xpath .//*[@id='shareWithList']//*[@class='has-tooltip username' and .='user2@https://server (federated)']/.. could not find share permissions field for user user2@https://server (federated) in /drone/src/tests/acceptance/features/lib/OwncloudPage.php:821
      Stack trace:
      #0 /drone/src/tests/acceptance/features/lib/FilesPageElement/SharingDialog.php(309): Page\OwncloudPage->assertElementNotNull(NULL, 'Page\\FilesPageE...')
      #1 /drone/src/tests/acceptance/features/bootstrap/WebUISharingContext.php(499): Page\FilesPageElement\SharingDialog->setSharingPermissions('user2@https://s...', Array)
      #2 [internal function]: WebUISharingContext->theUserSetsTheSharingPermissionsOfForOnTheWebUI('user2@https://s...', 'simple-folder', Object(Behat\Gherkin\Node\TableNode))
      #3 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(109): call_user_func_array(Array, Array)
      #4 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(64): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #5 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Call/CallCenter.php(140): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #6 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Call/CallCenter.php(96): Behat\Testwork\Call\CallCenter->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #7 /drone/src/lib/composer/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(125): Behat\Testwork\Call\CallCenter->makeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #8 /drone/src/lib/composer/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(73): Behat\Behat\Tester\Runtime\RuntimeStepTester->testDefinition(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), Object(Behat\Behat\Definition\SearchResult), false)
      #9 /drone/src/lib/composer/behat/behat/src/Behat/Behat/Hook/Tester/HookableStepTester.php(74): Behat\Behat\Tester\Runtime\RuntimeStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #10 /drone/src/lib/composer/behat/behat/src/Behat/Behat/EventDispatcher/Tester/TickingStepTester.php(59): Behat\Behat\Hook\Tester\HookableStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #11 /drone/src/lib/composer/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingStepTester.php(73): Behat\Behat\EventDispatcher\Tester\TickingStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #12 /drone/src/lib/composer/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php(59): Behat\Behat\EventDispatcher\Tester\EventDispatchingStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #13 /drone/src/lib/composer/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php(76): Behat\Behat\Tester\StepContainerTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #14 /drone/src/lib/composer/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(74): Behat\Behat\Tester\Runtime\RuntimeScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #15 /drone/src/lib/composer/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(103): Behat\Behat\Hook\Tester\HookableScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #16 /drone/src/lib/composer/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php(69): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #17 /drone/src/lib/composer/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(84): Behat\Behat\Tester\Runtime\IsolatingScenarioTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #18 /drone/src/lib/composer/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #19 /drone/src/lib/composer/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(71): Behat\Behat\Hook\Tester\HookableFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #20 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #21 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #22 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(72): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #23 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #24 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(70): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
      #25 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
      #26 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
      #27 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
      #28 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #29 /drone/src/lib/composer/symfony/console/Command/Command.php(255): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #30 /drone/src/lib/composer/symfony/console/Application.php(953): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #31 /drone/src/lib/composer/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #32 /drone/src/lib/composer/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #33 /drone/src/lib/composer/symfony/console/Application.php(148): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #34 /drone/src/lib/composer/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
      #35 {main}
    And user "user2" re-logs in to "%local_server%" using the webUI                                                               # WebUILoginContext::theUserRelogsInToUsingTheWebUI()
    And the user accepts the offered remote shares using the webUI                                                                # WebUISharingContext::theUserAcceptsTheOfferedRemoteShares()
    Then as "user2" folder "/simple-folder (2)" should exist                                                                      # FeatureContext::asFileOrFolderShouldExist()
    And as "user2" file "/simple-folder (2)/lorem.txt" should exist                                                               # FeatureContext::asFileOrFolderShouldExist()
    When the user opens folder "simple-folder (2)" using the webUI                                                                # WebUIFilesContext::theUserOpensFolderNamedUsingTheWebUI()
    Then it should not be possible to delete file "lorem.txt" using the webUI                                                     # WebUIFilesContext::itShouldNotBePossibleToDeleteFileFolderUsingTheWebUI()
SCENARIO RESULT: (fail)
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/34149 (Expand apiFederation acceptance tests), and https://github.com/owncloud/core/issues/33422 (Extend federation acceptance tests).

**Comment by phil-davis** [comment]
It does not fail today. Tests have been run on top of both ``master`` and ``stable10``
I guess this problem was just with PRs that started out life before these test scenarios were added? But I have no idea why that should have been a problem.

Issue can easily be reopened if fails are seen again.

**Comment by skshetry** [comment]
Still getting the error. 
```
--- Failed scenarios:

    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:213
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:231
```

### Recent failures:
https://drone.owncloud.com/owncloud/core/14451/619
https://drone.owncloud.com/owncloud/core/14478/619

**Comment by phil-davis** [comment]
Hopefully this is fixed now. I anyone notices these ``federationSharing`` test fails again, please post details and reopen this issue.

**Comment by skshetry** [comment]
Noticed a failure in the PR #33994. But many scenarios are failing. Not related perhaps.
```
--- Failed scenarios:
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:69
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:89
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:109
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:129
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:151
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:231
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:260
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:272
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:281
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:292
```
If this happens again, let's reopen this issue.
