### ISSUE TITLE
share receiver can rename a file in a locked folder by using the loktocken of the owner

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34338]
### Steps to reproduce
1. create a folder with a file
2. share the folder to an other user
3. as owner lock the folder
4. as receiver find the locktoken by PROPFIND
5. as receiver rename the file by a MOVE request and giving the locktoken of the owner `curl -u uu2:uu2 -X MOVE "http://localhost/owncloud-core/remote.php/dav/files/uu2/folder/file.txt" -H "Destination: http://localhost/owncloud-core/remote.php/dav/files/uu2/folder/renamed.txt" -H "If: (<opaquelocktoken:8eccec3d-9c12-49e0-8ad0-54c6a5169c9d>)" -v`

### Expected behaviour
HTTP response 423
File is not renamed

### Actual behaviour
HTTP response 403
File **is** renamed

#### ownCloud log (data/owncloud.log)
```
{"reqId":"jOOLALr1P5HctlMUkOnb","level":0,"time":"2019-01-31T08:06:19+00:00","remoteAddr":"127.0.0.1","user":"uu2","app":"webdav","method":"MOVE","url":"\/owncloud-core\/remote.php\/dav\/files\/uu2\/folder\/file.txt","message":"Exception: HTTP\/1.1 403 Forbidden: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Forbidden\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\LockPlugin->beforeUnlock('files\\\/uu2\\\/folde...', Object(OC\\\\Lock\\\\Persistent\\\\Lock))\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Locks\\\/Plugin.php(347): Sabre\\\\DAV\\\\Server->emit('beforeUnlock', Array)\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Locks\\\/Plugin.php(311): Sabre\\\\DAV\\\\Locks\\\\Plugin->unlockNode('files\\\/uu2\\\/folde...', Object(Sabre\\\\DAV\\\\Locks\\\\LockInfo))\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\Locks\\\\Plugin->afterUnbind(*** sensitive parameters replaced ***)\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(648): Sabre\\\\DAV\\\\Server->emit('afterUnbind', Array)\\n#5 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(464): Sabre\\\\DAV\\\\Server->emit('method:MOVE', Array)\\n#7 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(241): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(309): Sabre\\\\DAV\\\\Server->start()\\n#9 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Server.php(299): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/remote.php(175): require_once('\\\/home\\\/artur\\\/www...')\\n#12 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php\",\"Line\":110}"}

```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @ownclouders, and @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/34337 (receiver cannot rename a locked share), https://github.com/owncloud/core/issues/2816 (By renaming a shared folder the old folder is kept), https://github.com/owncloud/core/issues/2170 (By renaming a shared folder is not shared any more), https://github.com/owncloud/core/issues/29554 (overwriting a file with a folder and a folder with a file needs better error reporting), and https://github.com/owncloud/core/issues/34300 (empty lock-token when unlocking public link results in an exception).

**Comment by PVince81** [comment]
so far we've been following https://tools.ietf.org/html/rfc4918

but that spec doesn't define any restrictions to users

I found this proposal that extends that: https://tools.ietf.org/html/draft-reschke-webdav-locking-05#section-2.3

> 
   Submitting a lock token provides no special access rights.  Anyone
   can find out anyone else's lock token by performing lock discovery.
   Locks MUST be enforced based upon whatever authentication mechanism
   is used by the server, not based on the secrecy of the token values.

and https://tools.ietf.org/html/draft-reschke-webdav-locking-05#section-8.2.1

I'll check how far Sabre supports this...

In any case, I think we should protect access to only the lock owner, like we do for UNLOCK.

**Comment by PVince81** [comment]
after discussing with @DeepDiver1975 and others, we agreed that locking is not a security thing but convenience. so the server will not enforce access in case a lock token is "abused".

we'll keep this as is for the current release and might reconsider in future releases.

moving to backlog

**Comment by phil-davis** [comment]
Note: I updated the "Actual Behavior" in the original post. The receiver now gets a "success" 201 HTTP status, as well as the file is renamed. So the behavior is now consistent (HTTP status and actual action match).

What needs to be decided now is if this is a bug or a feature. If a bug, then it needs to be scheduled to be fixed. If a feature, then we need to adjust the tests so that we expect the current behavior as correct.

**Comment by DeepDiver1975** [comment]
**Automated triage classification: needs-guidance** (ambiguous bug — needs a product/owner decision)

I re-verified this against current `master` (`apps/dav/lib/Connector/Sabre/LockPlugin.php`). The behavior described here still reproduces, and the root cause is locatable:

- Owner-based access control on persistent locks is enforced **only** in `LockPlugin::beforeUnlock()` — it checks `lock->getOwnerAccountId()` against the current user, plus the later `lock-breaker-groups` exception (added in `02dd7eff43`). So only **UNLOCK** is protected against lock-token abuse.
- For **MOVE / DELETE / COPY / PUT**, there is no equivalent owner check. Sabre's `DAV\Locks\Plugin` validates the supplied `If:` token purely by *possession* of a valid token, not by who owns it. Since any share member can read the token via `PROPFIND` (lock discovery), they can submit it in an `If:` header and perform the operation — exactly the reported rename-via-MOVE bypass.

This matches RFC 4918 / the `draft-reschke-webdav-locking-05` note already cited by @PVince81 in this thread: *"Submitting a lock token provides no special access rights… Locks MUST be enforced based upon whatever authentication mechanism is used by the server, not based on the secrecy of the token values."*

**Why this needs a decision rather than a fix:** the thread records an explicit, contradictory product stance. In 2019 @PVince81 (after discussing with @DeepDiver1975) concluded *"locking is not a security thing but convenience… the server will not enforce access in case a lock token is abused"* and moved it to backlog. But the most recent comment (@phil-davis, 2021) reopened the question — HTTP status is now a consistent `201` — and explicitly asked an owner to decide **bug vs. feature**, pinging @micbar.

So the open question is unchanged and is a policy call the triage agent should not make unilaterally:

1. **Treat as a bug** → enforce lock ownership for MOVE/DELETE/COPY/PUT (mirror the `beforeUnlock` owner + lock-breaker-group check across the mutating WebDAV methods), expecting `423 Locked` for non-owners. This makes persistent locking an access control, contradicting the 2019 "convenience only" decision.
2. **Treat as working-as-intended** → keep token-possession semantics (locking is advisory/convenience) and update the integration tests to expect the current `201` + rename as correct.

@DeepDiver1975 could you confirm the intended direction here (enforce ownership across all mutating methods, or formally accept advisory-lock behavior and adjust the tests)? That decision determines whether this gets scheduled as a fix or closed as by-design.

🤖 Automated issue analysis by Claude Code review agent.

**Comment by DeepDiver1975** [comment]
by design
