### ISSUE TITLE
[APP Development] Can't load PageController

### ISSUE THREAD

**Issue by PedroLuiz99** [owncloud/core#34393]
Hi!
I am starting to learn how the app development works on Owncloud, and I'm trying to create a simple dummy app, based in the documentation and code from other apps. 

Basically, when I try to access the main page (/apps/meunovoapp) of the app (that have only an echo), an error occurs:

![image](https://user-images.githubusercontent.com/21373133/52314262-0a3cc280-2999-11e9-8d6d-f4c3caeb23f4.png)

```json
{"reqId":"XFjfesEn749dZV-YtPrArgAAAFc","level":3,"time":"2019-02-05T00:57:30+00:00","remoteAddr":"MY-IP-ADDRESS","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/meunovoapp\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCA\\\\MeuNovoApp\\\\Controller\\\\PageController' not found\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\MeuNovoApp\\\\AppInfo\\\\Application->OCA\\\\MeuNovoApp\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#1 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(108): Pimple\\\\Container->offsetGet('PageController')\\n#2 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/App.php(77): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('PageController')\\n#3 \\\/www\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('PageController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#4 \\\/www\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#5 \\\/www\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/meunovoap...')\\n#6 \\\/www\\\/index.php(54): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/www\\\/apps\\\/meunovoapp\\\/lib\\\/AppInfo\\\/Application.php\",\"Line\":21}"}
```

My info.php
```xml
<?xml version="1.0"?>
<info>
    <id>meunovoapp</id>
    <namespace>MeuNovoApp</namespace>
    <name>Meu Novo App</name>
    <summary>Resumo</summary>
    <description>Descrição</description>
    <version>0.0.1</version>
    <licence>agpl</licence>
    <author>Pedro Luiz</author>
    <category>tools</category>
    <website>https://harpo.com.br</website>
    <dependencies>
        <owncloud min-version="8.2" max-version="11" />
    </dependencies>
</info>

```

My app.php:
```php
<?php
$app = new \OCA\MeuNovoApp\AppInfo\Application();
$app->registerNavigationEntry();

```

My routes.php:
```php
<?php
/**
 * Created by PhpStorm.
 * User: pedro
 * Date: 03/02/2019
 * Time: 17:17
 */

return [
    'routes' => [
        ['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
    ]
];
```

My Application.php:
```php
<?php


namespace OCA\MeuNovoApp\AppInfo;

use OCA\MeuNovoApp\Controller\PageController;
use OCP\AppFramework\App;
use OCP\IContainer;


class Application extends App {
    public function __construct (array $urlParams = array()) {
        parent::__construct('meunovoapp', $urlParams);
        $container = $this->getContainer();
        $server = $container->getServer();

        $container->registerService('PageController', function(IContainer $c) {

            $server = $c->query('ServerContainer');

//the error points to this line \/
            return new PageController(
                $c->query('AppName'),
                $server->getRequest(),
                $server->getDatabaseConnection(),
                $server->getL10N('meunovoapp')
            );
        });
    }

    public function registerNavigationEntry() {
        $container = $this->getContainer();
        $container->query('OCP\INavigationManager')->add(function () use ($container) {
            $urlGenerator = $container->query('OCP\IURLGenerator');
            $l10n = $container->query('OCP\IL10N');
            return [
                'id' => 'meunovoapp',
                'order' => 10,
                'href' => $urlGenerator->linkToRoute('meunovoapp.page.index'),
                'icon' => $urlGenerator->imagePath('meunovoapp', 'app.svg'),
                'name' => $l10n->t('Meu Novo App')
            ];
        });
    }
}
```

My Pagecontroller.php
```php
<?php

namespace OCA\MeuNovoApp\Controller;
use OCP\AppFramework\Http\TemplateResponse;
use OCP\AppFramework\Controller;
use OCP\IDBConnection;
use OCP\IL10N;
use OCP\IRequest;

class PageController extends Controller {
    public function __construct($AppName,
                                IRequest $request,
                                IDBConnection $connection,
                                IL10N $l
    ) {
        parent::__construct($AppName, $request);

        $this->connection = $connection;
        $this->l = $l;
    }

    public function index() {
        return new TemplateResponse('meunovoapp', 'main');
    }
}
```
My file structure:
![image](https://user-images.githubusercontent.com/21373133/52313505-e88e0c00-2995-11e9-9606-cd2da6bdad1e.png)

What is wrong in my code?

Thanks and sorry for the silly question.

### Steps to reproduce
1. Just try to open the app and the Owncloud error appears.

### Expected behaviour
A page with "Teste" echoed.

### Actual behaviour
The error listed above.

### Server configuration
**Operating system**: CentOS 7 x64

**Web server:** Apache 2 

**Database:** MyariaDB 10.3.4

**PHP version:** PHP-FPM 7.2.14

**ownCloud version:** 10.0.10.4

**Updated from an older ownCloud or fresh install:** Fresh Install

**Where did you install ownCloud from:** Tarball from Owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
- core
	- INVALID_HASH
		- .htaccess
	- FILE_MISSING
		- .user.ini
```

**The content of config/config.php:**
```
{
    "basic": {
        "license key": "***REMOVED SENSITIVE VALUE***",
        "date": "Wed, 06 Feb 2019 01:02:43 +0000",
        "ownCloud version": "10.0.10.4",
        "ownCloud version string": "10.0.10",
        "ownCloud edition": "Community",
        "server OS": "Linux",
        "server OS version": "Linux owncloud-compiller 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64",
        "server SAPI": "fpm-fcgi",
        "webserver version": "Apache\/2.4.6 (CentOS) OpenSSL\/1.0.2k-fips",
        "hostname": "compiler.hbackup.harpocloud.com.br",
        "logged-in user": "admin"
    },
    "stats": {
        "users": {
            "Database": {
                "count": 4,
                "seen": 1,
                "logged in (30 days)": 1
            }
        },
        "groups": {
            "OC\\Group\\Database": 1
        }
    },
    "config": {
        "debug": true,
        "instanceid": "oci0g8ovnocw",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "MY_DOMAIN"
        ],
        "datadirectory": "\/www\/data",
        "overwrite.cli.url": "MY_DOMAIN",
        "dbtype": "mysql",
        "version": "10.0.10.4",
        "dbname": "MY_DB",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```

**List of activated apps:**

```
Enabled:
  - HarpoBackup: 1.0.0
  - announcementcenter: 1.2.1
  - checksum: 0.3.5
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - groupalert: 1.0.5
  - market: 0.2.5
  - meunovoapp: 0.0.1
  - notifications: 0.3.5
  - polls: 0.8.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera

**Operating system:** Windows 10

#### Web server error log
```
Nothing relevant, just old errors.
```

#### ownCloud log (data/owncloud.log)
```
Listed above.
```

#### Browser log
```
jquery-migrate.min.js?v=c1df786cea9377901670747d2bef8e52:2 JQMIGRATE: Migrate is installed, version 1.4.0
shareconfigmodel.js?v=c1df786cea9377901670747d2bef8e52:24 Uncaught ReferenceError: oc_appconfig is not defined
    at shareconfigmodel.js?v=c1df786cea9377901670747d2bef8e52:24
    at shareconfigmodel.js?v=c1df786cea9377901670747d2bef8e52:99
(anonymous) @ shareconfigmodel.js?v=c1df786cea9377901670747d2bef8e52:24
(anonymous) @ shareconfigmodel.js?v=c1df786cea9377901670747d2bef8e52:99
js.js?v=c1df786cea9377901670747d2bef8e52:198 Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.filePath (js.js?v=c1df786cea9377901670747d2bef8e52:198)
    at viewer.js?v=c1df786cea9377901670747d2bef8e52:4
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @ownclouders, and @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/30799 (Some Images not loaded), https://github.com/owncloud/core/issues/26226 ([master] LDAP app not loaded during upgrade), https://github.com/owncloud/core/issues/19736 (App menu loading icon is off-center), https://github.com/owncloud/core/issues/515 (cannot load app - app is null), and https://github.com/owncloud/core/issues/3608 (app problem).
