### ISSUE TITLE
Issue upgrading from 10.0.9.5 to to 10.1.0-1+1.2 Debian 9.6

### ISSUE THREAD

**Issue by ManfredCologne** [owncloud/core#34773]
### Steps to reproduce
1. apt-get install owncloud-files
2.
3.

### Expected behaviour
Update to 10.1.0-1+1.2

### Actual behaviour
sudo -u www-data php ./occ migration:status
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/owncloud/lib/private/DB/Connection.php:62

### Server configuration
**Operating system**: 
Debian 9.6

**Web server:** 
Apache 2 (2.4.25-3+deb9u6)

**Database:** 
mariadb-server-10.1 (10.1.37-0+deb9u1)

**PHP version:** 
7.0.33-0+deb9u3

**ownCloud version:** 
10.1.0-1+1.2

**Updated from an older ownCloud or fresh install:**
10.0.9.5

**Where did you install ownCloud from:**
###### Debian Main Repos
deb http://ftp.de.debian.org/debian/ stable main contrib non-free
deb http://ftp.de.debian.org/debian/ stable-updates main contrib non-free
deb http://security.debian.org/ stable/updates main
deb http://ftp.debian.org/debian stretch-backports main

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '10.0.9.5',
  'dbname' => 'owncload',    --> is realy right so...
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_root',
  'dbpassword' => 'xxx',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'xxx',
    1 => 'xxx',
    2 => 'xxx',
    3 => 'xxx',
    4 => 'xxx',
    5 => 'xxx',
  ),
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => xxx',
  'mail_smtpport' => '25',
  'mail_from_address' => 'xxx',
  'mail_domain' => 'xxx',
  'loglevel' => 2,
  'secret' => 'xxx',
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.
not possible

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation Folder

 sudo -u www-data php occ config:list system
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/owncloud/lib/private/DB/Connection.php:62
Stack trace:
#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/owncloud/lib/private/DB/Connection.php(144): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/owncloud/lib/private/DB/ConnectionFactory.php(145): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/owncloud/lib/private/Server.php(530): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /var/www/owncloud/lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /var/www/owncloud/lib/private/Server.php(1215): OC\ServerContainer->query('DatabaseConnect...')
#12 /var/www/owncloud/lib/private/Server.php(405): OC\Server->getDatabaseConnection()
#13 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): Pimple\Container->offsetGet('AppConfig')
#15 /var/www/owncloud/lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /var/www/owncloud/lib/private/Server.php(1145): OC\ServerContainer->query('AppConfig')
#17 /var/www/owncloud/lib/private/Server.php(585): OC\Server->getAppConfig()
#18 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#19 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): Pimple\Container->offsetGet('AppManager')
#20 /var/www/owncloud/lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#21 /var/www/owncloud/lib/private/Server.php(1413): OC\ServerContainer->query('AppManager')
#22 /var/www/owncloud/lib/private/legacy/app.php(346): OC\Server->getAppManager()
#23 /var/www/owncloud/lib/private/legacy/app.php(110): OC_App::getEnabledApps()
#24 /var/www/owncloud/lib/base.php(577): OC_App::loadApps(Array)
#25 /var/www/owncloud/lib/base.php(994): OC::init()
#26 /var/www/owncloud/console.php(64): require_once('/var/www/ownclo...')
#27 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#28 {main}PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/owncloud/lib/private/DB/Connection.php:62
Stack trace:
#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/owncloud/lib/private/DB/Connection.php(144): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\D in /var/www/owncloud/lib/private/DB/Connection.php on line 62

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
same like sudo -u www-data php occ config:list system

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### ownCloud log (data/owncloud.log)
```
{"reqId":"U8IRFiankUajFQxCEjRK","level":3,"time":"2019-03-14T20:41:38+00:00","remoteAddr":"192.168.2.1","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?fallback=true&fallback_id=0&requesttoken=MghTJABNOQE2XxkpXUkRKAYaAlYzDg4eOHsUKndeWgA%3D%3AEmcjB%2BxoWkUb%2F0vYdCpcRIOUZIvs%2Fnq3ZnENxnFI%2FDQ%3D","message":"Exception: {\"Exception\":\"OC\\\\RepairException\",\"Message\":\"Upgrade is not possible\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Repair.php(91): OC\\\\Repair\\\\Apps->run(Object(OC\\\\Repair))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(219): OC\\\\Repair->run()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(111): OC\\\\Updater->checkAppsCompatibility()\\n#3 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(189): OC\\\\Updater->upgrade()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Repair\\\/Apps.php\",\"Line\":219}"}

```

**Comment by ho4ho** [comment]
> Failed to connect to the database: An exception occured in driver: could not find driver

Not bug in ownCloud, just miss installation PHP database driver

**Comment by ManfredCologne** [comment]
Special Thanks to ho4ho!

For other users:
apt-get install php7.0-mysql
phpenmod pdo_mysql
apt-get install php7.0-zip
apt-get install php-intl
apt-get install php-mbstring
apt-get install php-gd
apt-get install php-curl
systemctl restart apache2

as the Debian Package is not resolving the right packages.

Greetings
        Manfred
