### ISSUE TITLE
report oc:search-files with disconnected external storages causes 503

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#34937]
### Steps to reproduce
1. mount an external storage (samba e.g.)
2. disconnect it (e.g. turn off samba)
3. run a file search REPORT oc:search-files

### Expected behaviour
Search shall return search results (outside of the disconnected storage at least)

### Actual behaviour
The search terminates with a 503
![Screenshot from 2019-04-01 09-26-11](https://user-images.githubusercontent.com/1005065/55310224-37b96000-5460-11e9-848a-304fff710e8e.png)

### Server configuration
**ownCloud version:** master branch

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** git

**Are you using external storage, if yes which one:** samba - should be the same for any other external storage

#### ownCloud log (data/owncloud.log)
```
{"reqId":"e7fdcf58-a5b3-44cd-8e64-fc69c4623bff","level":3,"time":"2019-04-01T07:22:45+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"webdav","method":"REPORT","url":"\/remote.php\/dav\/files\/admin\/","message":"Caused by: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"\",\"Code\":1,\"Trace\":\"#0 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(458): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->checkAvailability()\\n#1 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(175): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->getMetaData('')\\n#2 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Checksum.php(187): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getMetaData('')\\n#3 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(579): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum->getMetaData('')\\n#4 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(116): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData('')\\n#5 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(157): OC\\\\Files\\\\Cache\\\\Scanner->getData('')\\n#6 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(330): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('', 3, -1, NULL, true)\\n#7 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/View.php(1368): OC\\\\Files\\\\Cache\\\\Scanner->scan('', false)\\n#8 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/View.php(1409): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), '', 'Daimler Supplie...')\\n#9 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php(179): OC\\\\Files\\\\View->getFileInfo('\\\/admin\\\/files\\\/Da...')\\n#10 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/apps\\\/dav\\\/lib\\\/Tree.php(67): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Daimler Supplie...')\\n#11 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(75): OCA\\\\DAV\\\\Tree->getNodeForPath('files\\\/admin\\\/Dai...')\\n#12 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/apps\\\/dav\\\/lib\\\/Tree.php(48): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/admin\\\/Dai...')\\n#13 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(270): OCA\\\\DAV\\\\Tree->getNodeForPath('\\\/files\\\/admin\\\/Da...')\\n#14 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/FilesSearchReportPlugin.php(163): Sabre\\\\DAV\\\\Tree->getMultipleNodes(Array)\\n#15 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1649): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\FilesSearchReportPlugin->getSearchResultIterator('\\\/files\\\/admin', Array, Array, 30)\\n#16 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/FilesSearchReportPlugin.php(136): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator))\\n#17 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\FilesSearchReportPlugin->onReport('{http:\\\/\\\/ownclou...', Object(OCA\\\\DAV\\\\Files\\\\Xml\\\\SearchRequest), 'files\\\/admin')\\n#18 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(720): Sabre\\\\DAV\\\\Server->emit('report', Array)\\n#19 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#20 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(464): Sabre\\\\DAV\\\\Server->emit('method:REPORT', Array)\\n#21 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(241): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#22 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(309): Sabre\\\\DAV\\\\Server->start()\\n#23 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/apps\\\/dav\\\/lib\\\/Server.php(299): Sabre\\\\DAV\\\\Server->exec()\\n#24 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#25 \\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/remote.php(175): require_once('\\\/home\\\/deepdiver...')\\n#26 {main}\",\"File\":\"\\\/home\\\/deepdiver\\\/Development\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php\",\"Line\":76}"}

```

**Comment by DeepDiver1975** [comment]
no prio
