### ISSUE TITLE
When I use make, something went wrong, how can I solve it?

### ISSUE THREAD

**Issue by limingpo** [owncloud/core#35069]
cd build && /usr/bin/yarn install
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ modclean -r --patterns="default:safe" && node -e "try { require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), '../core/vendor', 'junction') } catch (e) { }"
/home/orcadt/core-master/build/node_modules/modclean/bin/modclean.js:242
    async writeLogs() {
          ^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [build/node_modules] Error 1

**Comment by ho4ho** [comment]
Bugtracker no good for development thing, better ask by https://central.owncloud.org/c/development

**Comment by PVince81** [comment]
likely wrong node JS version. need to use the LTS version.

anyway, please ask on central instead of here
