### ISSUE TITLE
Cannot Unshare after deleting public link

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#35305]
Server: 10.2.0
Client: 2.6.0-daily20190522 (build 11801)

Steps to recreate:
1) Create a public link (right click on a **folder** in your file system -> select owncloud submenu -> select Share)
2) Open the link in browser
3) Add to your ownCloud (use another user from the same server) in the top right corner 
4) Confirm that you want to add remote share 
5) Immediately delete the public link 
6) Unshare the **folder**

Expected result: Folder has been unshared
Actual result: Folder cannot be unshared. No obvious error in the web ui. After unsharing the folder disappears but it's back once page has been refreshed

![Screenshot 2019-05-22 at 14 38 24](https://user-images.githubusercontent.com/49001702/58183895-69a4b100-7cb0-11e9-9276-1bd04ae6eba2.png)

**Comment by davitol** [comment]
I was able to reproduce it too using oC 10.2 but not in 10.1. So I think it is a regression @micbar @pmaier1 JFYI

**Comment by bhawanaprasain** [comment]
@davitol this bug exists in 10.1.0

**Comment by davitol** [comment]
> @davitol this bug exists in 10.1.0

Sorry it is true. It can be reproducible in 10.1.0. Refreshing the browser, the folder reappears

**Comment by davitol** [comment]
owncloud.log shows an Unauthorized exception

```
{"reqId":"7zZ7wZvOzz7qadeAjvA3","level":3,"time":"2019-06-27T10:05:34+00:00","remoteAddr":"172.18.0.1","user":"ana","app":"no app in context","method":"PROPFIND","url":"\/remote.php\/dav\/files\/ana\/SolidGEAR","message":"Exception: {\"Exception\":\"Sabre\\\\HTTP\\\\ClientHttpException\",\"Message\":\"Unauthorized\",\"Code\":401,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(231): Sabre\\\\HTTP\\\\Client->send(Object(Sabre\\\\HTTP\\\\Request))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(259): Sabre\\\\DAV\\\\Client->propFind('http:\\\/\\\/10.40.40...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Storage.php(304): OC\\\\Files\\\\Storage\\\\DAV->propfind('')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(631): OCA\\\\Files_Sharing\\\\External\\\\Storage->getPermissions('')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(578): OC\\\\Files\\\\Storage\\\\Common->getMetaData('')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(459): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData('')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Checksum.php(202): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->getMetaData('')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(578): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum->getMetaData('')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(115): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData('')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(152): OC\\\\Files\\\\Cache\\\\Scanner->getData('')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(325): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('', 3, -1, NULL, true)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1367): OC\\\\Files\\\\Cache\\\\Scanner->scan('', false)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1408): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), '', 'SolidGEAR')\\n#13 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php(179): OC\\\\Files\\\\View->getFileInfo('\\\/ana\\\/files\\\/Soli...')\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Tree.php(67): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('SolidGEAR')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(967): OCA\\\\DAV\\\\Tree->getNodeForPath('files\\\/ana\\\/Solid...')\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1666): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('files\\\/ana\\\/Solid...', Array, 1)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#18 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#21 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#22 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(294): Sabre\\\\DAV\\\\Server->exec()\\n#23 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#24 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#25 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":160}"}
{"reqId":"7zZ7wZvOzz7qadeAjvA3","level":3,"time":"2019-06-27T10:05:34+00:00","remoteAddr":"172.18.0.1","user":"ana","app":"files_external","method":"PROPFIND","url":"\/remote.php\/dav\/files\/ana\/SolidGEAR","message":"Unauthorized"}
```

**Comment by JammingBen** [comment]
Seems to be fixed meanwhile, works here.
