### ISSUE TITLE
Upgrade to 10.2.0 broke everything

### ISSUE THREAD

**Issue by eLvErDe** [owncloud/core#35303]
Hello,

I just updated using providing Debian package and after occ upgrade run nothing is working anymore.

Logs say:

```
{"reqId":"6b9cdf52-b037-416d-9699-7dac59436ca1","level":3,"time":"2019-05-22T12:11:31+00:00","remoteAddr":"213.135.232.249","user":"--","app":"PHP","method":"GET","url":"\/status.php","message":"Undefined index: version at \/var\/www\/owncloud\/lib\/private\/legacy\/app.php#852"}
{"reqId":"6b9cdf52-b037-416d-9699-7dac59436ca1","level":3,"time":"2019-05-22T12:11:31+00:00","remoteAddr":"213.135.232.249","user":"--","app":"PHP","method":"GET","url":"\/status.php","message":"Undefined index: version at \/var\/www\/owncloud\/lib\/private\/legacy\/app.php#856"}
{"reqId":"6b9cdf52-b037-416d-9699-7dac59436ca1","level":4,"time":"2019-05-22T12:11:31+00:00","remoteAddr":"213.135.232.249","user":"--","app":"remote","method":"GET","url":"\/status.php","message":"Invalid version string \"\""}
{"reqId":"1UVGwyQZQsxB2ehylVFI","level":3,"time":"2019-05-22T12:11:36+00:00","remoteAddr":"213.135.232.249","user":"--","app":"PHP","method":"GET","url":"\/","message":"Undefined index: version at \/var\/www\/owncloud\/lib\/private\/legacy\/app.php#852"}
{"reqId":"1UVGwyQZQsxB2ehylVFI","level":3,"time":"2019-05-22T12:11:36+00:00","remoteAddr":"213.135.232.249","user":"--","app":"PHP","method":"GET","url":"\/","message":"Undefined index: version at \/var\/www\/owncloud\/lib\/private\/legacy\/app.php#856"}
{"reqId":"1UVGwyQZQsxB2ehylVFI","level":3,"time":"2019-05-22T12:11:36+00:00","remoteAddr":"213.135.232.249","user":"--","app":"index","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"UnexpectedValueException\",\"Message\":\"Invalid version string \\\"\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(1135): Composer\\\\Semver\\\\VersionParser->normalize('')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(856): OC_App::atLeastMinorVersionLevelChanged(NULL, '1.6.2')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(1454): OC_App::shouldUpgrade('calendar')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(684): OC_Util::needUpgrade(Object(OC\\\\AllConfig))\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(594): OC_Util::checkServer(Object(OC\\\\AllConfig))\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(994): OC::init()\\n#6 \\\/var\\\/www\\\/owncloud\\\/index.php(53): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/composer\\\/semver\\\/src\\\/VersionParser.php\",\"Line\":172}"}
```

**Comment by eLvErDe** [comment]
Seems I fixed it myself but there's probably something broken:
I had a calendar.old app and removing it made the whole thing working again

**Comment by eLvErDe** [comment]
Still have the calendar.old files btw, if you want to make some tests.

**Comment by VicDeo** [comment]
@eLvErDe I guess it's a very old version of the calendar app. 
Could you share `grep version calendar.old/appinfo/info.xml` output?

**Comment by VicDeo** [comment]
Closing due to the lack of communication.
Probably was fixed by https://github.com/owncloud/core/pull/36054
