### ISSUE TITLE
Chunk assembly for delta-uploads returns 423 Locked

### ISSUE THREAD

**Issue by ckamm** [owncloud/core#35613]
See https://github.com/owncloud/client/issues/7262. Relates to https://github.com/owncloud/core/pull/29404. Tested with 192501e13e27f70f5d8f65ed0e9e70b86db96912.

When using the chunked uploading codepath for delta-uploads the final MOVE of `.file.zsync` does not succeed. Instead, an "423 Locked" error is returned.

Background: Normally chunked uploads are "complete", i.e. all data gets uploaded and the it's assembled when the `.file` file is moved to the final location. For delta-sync/"zsync" chunked uploads only some of the data is uploaded and then a `.file.zsync` file is moved to the final location. This move should use parts of the existing data and the new data that was uploaded to generate the final file and uses a new and (so far) rarely used codepath going through apps/dav/lib/Upload/AssemblyStreamZsync.php.

Server trace:
```
{"reqId":"a4d5b845-c822-4dd9-a975-d314f3318a00","level":4,"time":"2019-06-20T11:15:36+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"webdav",
"method":"MOVE","url":"\/remote.php\/dav\/uploads\/admin\/3829735225\/.file.zsync",
"message":"Exception: HTTP\/1.1 423 "file" is locked: {"Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Message":"\\"file\\" is locked","Code":0,
"Trace":"
#0 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Upload/AssemblyStream.php(285): OCA\\DAV\\Connector\\Sabre\\File->get()\
#1 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Upload/AssemblyStreamZsync.php(97): OCA\\DAV\\Upload\\AssemblyStream->getStream(Object(OCA\\DAV\\Connector\\Sabre\\File))\
#2 [internal function]: OCA\\DAV\\Upload\\AssemblyStreamZsync->stream_read(8192)\
#3 /var/www/owncloud/owncloud-20190620/lib/private/legacy/helper.php(305): fread(Resource id #43, 8192)\
#4 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Connector/Sabre/File.php(201): OC_Helper::streamCopy(Resource id #43, Resource id #48)\
#5 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Connector/Sabre/Directory.php(172): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id #43)\
#6 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Tree.php(311): OCA\\DAV\\Connector\\Sabre\\Directory->createFile('file...', Resource id #43)\
#7 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Tree.php(135): Sabre\\DAV\\Tree->copyNode(Object(OCA\\DAV\\Upload\\FutureFileZsync), Object(OCA\\DAV\\Connector\\Sabre\\Directory), 'file...')\
#8 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Tree.php(113): Sabre\\DAV\\Tree->copy('uploads/admin/3...', 'files/admin/WIS...')\
#9 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Tree.php(167): OCA\\DAV\\Tree->copy('uploads/admin/3...', 'files/admin/WIS...')\
#10 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Upload/ChunkingPluginZsync.php(142): Sabre\\DAV\\Tree->move('uploads/admin/3...', 'files/admin/WIS...')\
#11 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Upload/ChunkingPluginZsync.php(62): OCA\\DAV\\Upload\\ChunkingPluginZsync->performMove('uploads/admin/3...', 'files/admin/WIS...')\
#12 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/event/lib/WildcardEmitterTrait.php(96): OCA\\DAV\\Upload\\ChunkingPluginZsync->beforeMove('uploads/admin/3...', 'files/admin/WIS...')\
#13 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/CorePlugin.php(632): Sabre\\DAV\\Server->emit('beforeMove', Array)\
#14 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/event/lib/WildcardEmitterTrait.php(96): Sabre\\DAV\\CorePlugin->httpMove(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\
#15 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Server.php(464): Sabre\\DAV\\Server->emit('method:MOVE', Array)\
#16 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Server.php(241): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\
#17 /var/www/owncloud/owncloud-20190620/lib/composer/sabre/dav/lib/DAV/Server.php(309): Sabre\\DAV\\Server->start()\
#18 /var/www/owncloud/owncloud-20190620/apps/dav/lib/Server.php(305): Sabre\\DAV\\Server->exec()\
#19 /var/www/owncloud/owncloud-20190620/apps/dav/appinfo/v2/remote.php(31): OCA\\DAV\\Server->exec()\
#20 /var/www/owncloud/owncloud-20190620/remote.php(165): require_once('/var/www/ownclo...')\
#21 {main}","File":"/var/www/owncloud/owncloud-20190620/apps/dav/lib/Connector/Sabre/File.php","Line":408}"}
```

I guess that the AssemblyStreamZsync can't open the original file for reading because it's locked?

To reproduce with a client see https://github.com/owncloud/client/issues/7262. Otherwise follow the script in https://github.com/owncloud/core/issues/35613#issuecomment-505726558:
- upload a 11MB file full of zeroes
- create a chunked upload
- upload a 4-byte append to the file
- upload the new zsync file
- trigger the final move
-> 423 Locked

**Comment by micbar** [comment]
@pmaier1 @michaelstingl 
Could you provide info on the current state of delta sync on stable10?

**Comment by michaelstingl** [comment]
> Could you provide info on the current state of delta sync on stable10?

Delta sync only in `master`.

**Comment by DeepDiver1975** [comment]
Best would be to script this scenario in reproducible steps as an acceptance test.
This enables any server developer to quickly debug this.

**Comment by ckamm** [comment]
@DeepDiver1975 Here you go:
```
#!/bin/bash
SERVER=http://localhost
USER=admin
PASS=admin
UPID=1212
dd if=/dev/zero of=testfile count=11264 bs=1024
curl -u "$USER:$PASS" -X PUT "$SERVER/remote.php/dav/files/$USER/testfile" -v
curl -u "$USER:$PASS" -H 'Content-Length:0' -H 'OC-Total-Length:11534340' -X MKCOL "$SERVER/remote.php/dav/uploads/$USER/$UPID" -v
curl -u "$USER:$PASS" -H 'OC-Chunk-Offset:11534336' -H 'Content-Length:4' -X PUT "$SERVER/remote.php/dav/uploads/$USER/$UPID/0000000011534336" -v --data-binary 'neww'

zsync='zsync: 0.6.3\nBlocksize: 1048576\nLength: 11534340\nHash-Lengths: 1,8,16\nSHA-1: 153ea12ebcf59c98de962044177a01ad6a319a6c\n\n\x00\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x96/\x1dB\xab\x8a\xc9lH<\x92\x92t\x98\x00\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x96/\x1dB\xab\x8a\xc9lH<\x92\x92t\x98\x00\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x96/\x1dB\xab\x8a\xc9lH<\x92\x92t\x98\x00\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x96/\x1dB\xab\x8a\xc9lH<\x92\x92t\x98\x00\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x96/\x1dB\xab\x8a\xc9lH<\x92\x92t\x98\x00\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x96/\x1dB\xab\x8a\xc9lH<\x92\x92t\x98\x00\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x96/\x1dB\xab\x8a\xc9lH<\x92\x92t\x98\x00\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x96/\x1dB\xab\x8a\xc9lH<\x92\x92t\x98\x00\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x96/\x1dB\xab\x8a\xc9lH<\x92\x92t\x98\x00\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x96/\x1dB\xab\x8a\xc9lH<\x92\x92t\x98\x00\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x96/\x1dB\xab\x8a\xc9lH<\x92\x92t\x98\x00\x00\x01T\x15?\xfe\x8f\x13\x1eJp@\xdfd8\xea\xf0=\x82\x88\x1e\xed\xbe'
echo -ne $zsync | curl -u "$USER:$PASS" "$SERVER/remote.php/dav/uploads/$USER/$UPID/.zsync" -X PUT -v --data-binary '@-'

curl -u "$USER:$PASS" -H "Destination:/remote.php/dav/files/$USER/testfile" -H 'OC-Total-File-Length:11534340' -H 'OC-Total-Length:411' -H 'X-OC-Mtime:1561035576' -X MOVE "$SERVER/remote.php/dav/uploads/$USER/$UPID/.file.zsync" -v
```

**Comment by DeepDiver1975** [comment]
@micbar maybe Something for Piotr to look at next

**Comment by micbar** [comment]
@DeepDiver1975 @ckamm @mrow4a @michaelstingl 
I don't see the need to proceed here, as the decision has been made to drop delta-sync completely.

IMO we should close this issue.

**Comment by slinkinone** [comment]
Is **zsync** supported in the latest releases? Cause' due to [this](https://github.com/owncloud/core/commit/effb419bd5edcd2dcf4ba8e61a91766b78b3954d#diff-920833889854d937ebeda804d3eb5b19) commit, it seems server side doesn't have this functionality.

**Comment by mrow4a** [comment]
@ckamm it is still not clear to me what is the protocol over which clients should implement delta sync (sequence of requests, content of request body, content of headers). 

I am also not aware of even a unit test that covers the protocol. The only way we currently have to test delta sync is https://github.com/owncloud/smashbox/blob/master/lib/test_deltamove.py, which is using sync client. For example, we have extensive acceptance test for chunking upload, but not for delta sync: https://github.com/owncloud/core/blob/v10.3.0/tests/acceptance/features/apiWebdavUpload/uploadFileUsingNewChunking.feature

**Comment by michaelstingl** [comment]
delta-upload was removed from master branch quite some time ago.
