### ISSUE TITLE
Error from files _antivirus even if the app is disabled

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#35678]
I upgrade to the latest 0.15.1 version:
```
root@snoopy4:~/oC-Logs# more /var/www/owncloud/apps/files_antivirus/appinfo/info.xml |grep /version
	<version>0.15.1</version>
```

I see this error:

```
root@snoopy4:~/oC-Logs# more oclog10.2.1.txt |grep Antivirus |jq '.' | sed -e's:\\\\\\\\:\\:g' -e 's:\\\\\\:\\:g' -e 's:\\\\:\\:g' -e 's:\\":":g' -e 's:)\\:):g' -e 's:\\/:/:g' -e 's:#0:n#0:g' -e 's:n#:\n#:g' -e 's:\\n:\n:g' -e 's:\\t:\t:g'
{
  "reqId": "mDy1Bdhh71NdZNVPbSIc",
  "level": 3,
  "time": "2019-06-26T02:00:02+02:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "--",
  "url": "--",
  "message": "Exception: {"Exception":"OCP\AppFramework\QueryException","Message":"Could not resolve OCA\Files_Antivirus\Cron\Task! Class OCA\Files_Antivirus\Cron\Task does not exist","Code":0,"Trace":"
#0 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(110): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\Files_Antiv...')
#1 /var/www/owncloud/lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query('OCA\Files_Antiv...')
#2 /var/www/owncloud/lib/private/BackgroundJob/JobList.php(253): OC\ServerContainer->query('OCA\Files_Antiv...')
#3 /var/www/owncloud/lib/private/BackgroundJob/JobList.php(209): OC\BackgroundJob\JobList->buildJob(Array)
#4 /var/www/owncloud/cron.php(114): OC\BackgroundJob\JobList->getNext()
#5 {main}","File":"/var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php","Line":96}"
}
```

**Comment by VicDeo** [comment]
@cdamken see https://github.com/owncloud/core/issues/35589#issuecomment-504442196

**Comment by cortho** [comment]
Shouldn't disabling an app remove their background jobs and (re-)enabling it add them (from and into the db)?

**Comment by VicDeo** [comment]
>Shouldn't disabling an app remove their background jobs and (re-)enabling it add them (from and into the db)?

Common sense tells me that the answer on this question sounds like 'yes', but I'm not familiar with that part of core to say it explicitly.
