### ISSUE TITLE
Updating to 10.2.0 failed: UnexpectedValueException

### ISSUE THREAD

**Issue by fluffy-critter** [owncloud/core#35744]
### Steps to reproduce
1. Update the package repository (on Ubuntu 18.04)
2. `apt update && apt dist-upgrade`
3. Go to the ownCloud site and click "begin upgrade"

### Expected behaviour

It should have upgraded

### Actual behaviour

Summary error:

```
UnexpectedValueException: Invalid version string ""
```

Detailed log:

```
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updated "files_videoplayer" to 0.10.1
Updated "firstrunwizard" to 1.2.0
Updated "market" to 0.5.0
Updated "configreport" to 0.2.0
Updated "federatedfilesharing" to 0.4.0
UnexpectedValueException: Invalid version string ""
```

### Server configuration
**Operating system**:

Ubuntu 18.04

**Web server:**

Apache

**Database:**

SQLite

**PHP version:**

7.2.19-0ubuntu0.18.04.1

**ownCloud version:** (see ownCloud admin page)

```
$ dpkg -l owncloud*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                               Version                        Architecture                   Description
+++-==================================================-==============================-==============================-=========================================================================================================
un  owncloud                                           <none>                         <none>                         (no description available)
un  owncloud-config-apache                             <none>                         <none>                         (no description available)
ii  owncloud-files                                     10.2.0-1+1.1                   all                            ownCloud - Server
un  owncloud-server                                    <none>                         <none>                         (no description available)
```

**Updated from an older ownCloud or fresh install:**

Updated from 10.1

**Where did you install ownCloud from:**

```
$ cat /etc/apt/sources.list.d/owncloud.list 
deb http://download.owncloud.org/download/repositories/production/Ubuntu_18.04/ /
```

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

Information unavailable, as I am unable to login due to failed upgrade

**The content of config/config.php:**

```
root@nautilus:/var/www/owncloud# sudo -u www-data php occ config:list system
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocaud1yzx06z",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.beesbuzz.biz"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.beesbuzz.biz",
        "dbtype": "sqlite3",
        "version": "10.1.0.4",
        "logtimezone": "UTC",
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```

**List of activated apps:**

```
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - systemtags: 0.3.0
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes via LetsEncrypt

**Are you using an external user-backend, if yes which one:** PAM 

#### Web server error log
```
[Tue Jul 02 15:41:04.006079 2019] [php7:notice] [pid 6986] [client 2601:602:9c02:d7ec:6889:9b48:e29e:ca71:58129] {"reqId":"ucaoQEQWP1hrAR2Ui4xc","level":3,"time":"2019-07-02T22:41:04+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"PHP","method":"GET","url":"\\/core\\/ajax\\/update.php?requesttoken=Mgw4DHhFVHUnCyEACS8pCmZwLy5%2FKykrL2QSOjQXP2w%3D%3AJFik610%2FdmkkXwnZ%2BHZG7lYBjVsCvqZ%2F1OmMLxvffpY%3D","message":"fopen(\\/var\\/www\\/owncloud\\/data\\/owncloud.log): failed to open stream: Permission denied at \\/var\\/www\\/owncloud\\/lib\\/private\\/Log\\/Owncloud.php#126"}
[Tue Jul 02 15:46:41.478821 2019] [php7:notice] [pid 7069] [client 2601:602:9c02:d7ec:6889:9b48:e29e:ca71:58348] {"reqId":"XJkQFnUR6C4AzxOnNg0H","level":0,"time":"2019-07-02T22:46:41+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"core","method":"GET","url":"\\/core\\/ajax\\/update.php?requesttoken=CwEhMwkHAi8rMSkTIT9oaA99LC8QCDkfAUs0DyBUBxs%3D%3AsKpTGsfuhWcxpg%2F8BEYFXOIvDyUvb2bXuRjcXxSst%2Bc%3D","message":"starting upgrade from 10.1.0.4 to 10.2.0.5"}
[Tue Jul 02 15:46:42.932906 2019] [php7:notice] [pid 7069] [client 2601:602:9c02:d7ec:6889:9b48:e29e:ca71:58348] {"reqId":"XJkQFnUR6C4AzxOnNg0H","level":3,"time":"2019-07-02T22:46:42+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"PHP","method":"GET","url":"\\/core\\/ajax\\/update.php?requesttoken=CwEhMwkHAi8rMSkTIT9oaA99LC8QCDkfAUs0DyBUBxs%3D%3AsKpTGsfuhWcxpg%2F8BEYFXOIvDyUvb2bXuRjcXxSst%2Bc%3D","message":"Undefined index: version at \\/var\\/www\\/owncloud\\/lib\\/private\\/legacy\\/app.php#852"}
[Tue Jul 02 15:46:42.933019 2019] [php7:notice] [pid 7069] [client 2601:602:9c02:d7ec:6889:9b48:e29e:ca71:58348] {"reqId":"XJkQFnUR6C4AzxOnNg0H","level":3,"time":"2019-07-02T22:46:42+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"PHP","method":"GET","url":"\\/core\\/ajax\\/update.php?requesttoken=CwEhMwkHAi8rMSkTIT9oaA99LC8QCDkfAUs0DyBUBxs%3D%3AsKpTGsfuhWcxpg%2F8BEYFXOIvDyUvb2bXuRjcXxSst%2Bc%3D","message":"Undefined index: version at \\/var\\/www\\/owncloud\\/lib\\/private\\/legacy\\/app.php#856"}
[Tue Jul 02 15:46:42.933698 2019] [php7:notice] [pid 7069] [client 2601:602:9c02:d7ec:6889:9b48:e29e:ca71:58348] {"reqId":"XJkQFnUR6C4AzxOnNg0H","level":3,"time":"2019-07-02T22:46:42+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"core","method":"GET","url":"\\/core\\/ajax\\/update.php?requesttoken=CwEhMwkHAi8rMSkTIT9oaA99LC8QCDkfAUs0DyBUBxs%3D%3AsKpTGsfuhWcxpg%2F8BEYFXOIvDyUvb2bXuRjcXxSst%2Bc%3D","message":"Exception: {\\"Exception\\":\\"UnexpectedValueException\\",\\"Message\\":\\"Invalid version string \\\\\\"\\\\\\"\\",\\"Code\\":0,\\"Trace\\":\\"#0 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/legacy\\\\\\/app.php(1135): Composer\\\\\\\\Semver\\\\\\\\VersionParser->normalize('')\\\\n#1 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/legacy\\\\\\/app.php(856): OC_App::atLeastMinorVersionLevelChanged(NULL, '0.0.1')\\\\n#2 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/Updater.php(343): OC_App::shouldUpgrade('search_lucene')\\\\n#3 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/Updater.php(271): OC\\\\\\\\Updater->doAppUpgrade()\\\\n#4 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/Updater.php(112): OC\\\\\\\\Updater->doUpgrade('10.2.0.5', '10.1.0.4')\\\\n#5 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/core\\\\\\/ajax\\\\\\/update.php(189): OC\\\\\\\\Updater->upgrade()\\\\n#6 {main}\\",\\"File\\":\\"\\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/composer\\\\\\/composer\\\\\\/semver\\\\\\/src\\\\\\/VersionParser.php\\",\\"Line\\":172}"}
[Tue Jul 02 15:46:42.934400 2019] [php7:notice] [pid 7069] [client 2601:602:9c02:d7ec:6889:9b48:e29e:ca71:58348] {"reqId":"XJkQFnUR6C4AzxOnNg0H","level":3,"time":"2019-07-02T22:46:42+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"PHP","method":"GET","url":"\\/core\\/ajax\\/update.php?requesttoken=CwEhMwkHAi8rMSkTIT9oaA99LC8QCDkfAUs0DyBUBxs%3D%3AsKpTGsfuhWcxpg%2F8BEYFXOIvDyUvb2bXuRjcXxSst%2Bc%3D","message":"fopen(\\/var\\/www\\/owncloud\\/data\\/owncloud.log): failed to open stream: Permission denied at \\/var\\/www\\/owncloud\\/lib\\/private\\/Log\\/Owncloud.php#126"}
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"HEs4m8vi3OPoAQKjAxsK","level":3,"time":"2019-07-02T22:55:01+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"PHP","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=345e6b251789f0d4925fb3273405633f","message":"Undefined index: version at \/var\/www\/owncloud\/lib\/private\/legacy\/app.php#852"}
{"reqId":"HEs4m8vi3OPoAQKjAxsK","level":3,"time":"2019-07-02T22:55:01+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"PHP","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=345e6b251789f0d4925fb3273405633f","message":"Undefined index: version at \/var\/www\/owncloud\/lib\/private\/legacy\/app.php#856"}
{"reqId":"HEs4m8vi3OPoAQKjAxsK","level":3,"time":"2019-07-02T22:55:01+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"index","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=345e6b251789f0d4925fb3273405633f","message":"Exception: {\"Exception\":\"UnexpectedValueException\",\"Message\":\"Invalid version string \\\"\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(1135): Composer\\\\Semver\\\\VersionParser->normalize('')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(856): OC_App::atLeastMinorVersionLevelChanged(NULL, '0.0.1')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(187): OC_App::shouldUpgrade('search_lucene')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(124): OC_App::loadApp('search_lucene')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(147): OC_App::loadApps(Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#6 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/composer\\\/semver\\\/src\\\/VersionParser.php\",\"Line\":172}"}
{"reqId":"zSP7sf7t1hwUMYyIVmxp","level":0,"time":"2019-07-02T22:55:02+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=OjoICgw7ITw1PGVfFnd0CRpXQg8NAEgsPGoKOnoKVxc%3D%3ABpYmBOEfvZ%2F4G%2F3YWo7fEG8EyXkC8l2TklqNZCuaNDc%3D","message":"starting upgrade from 10.1.0.4 to 10.2.0.5"}
{"reqId":"zSP7sf7t1hwUMYyIVmxp","level":3,"time":"2019-07-02T22:55:04+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"PHP","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=OjoICgw7ITw1PGVfFnd0CRpXQg8NAEgsPGoKOnoKVxc%3D%3ABpYmBOEfvZ%2F4G%2F3YWo7fEG8EyXkC8l2TklqNZCuaNDc%3D","message":"Undefined index: version at \/var\/www\/owncloud\/lib\/private\/legacy\/app.php#852"}
{"reqId":"zSP7sf7t1hwUMYyIVmxp","level":3,"time":"2019-07-02T22:55:04+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"PHP","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=OjoICgw7ITw1PGVfFnd0CRpXQg8NAEgsPGoKOnoKVxc%3D%3ABpYmBOEfvZ%2F4G%2F3YWo7fEG8EyXkC8l2TklqNZCuaNDc%3D","message":"Undefined index: version at \/var\/www\/owncloud\/lib\/private\/legacy\/app.php#856"}
{"reqId":"zSP7sf7t1hwUMYyIVmxp","level":3,"time":"2019-07-02T22:55:04+00:00","remoteAddr":"2601:602:9c02:d7ec:6889:9b48:e29e:ca71","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=OjoICgw7ITw1PGVfFnd0CRpXQg8NAEgsPGoKOnoKVxc%3D%3ABpYmBOEfvZ%2F4G%2F3YWo7fEG8EyXkC8l2TklqNZCuaNDc%3D","message":"Exception: {\"Exception\":\"UnexpectedValueException\",\"Message\":\"Invalid version string \\\"\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(1135): Composer\\\\Semver\\\\VersionParser->normalize('')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(856): OC_App::atLeastMinorVersionLevelChanged(NULL, '0.0.1')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(343): OC_App::shouldUpgrade('search_lucene')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(271): OC\\\\Updater->doAppUpgrade()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(112): OC\\\\Updater->doUpgrade('10.2.0.5', '10.1.0.4')\\n#5 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(189): OC\\\\Updater->upgrade()\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/composer\\\/semver\\\/src\\\/VersionParser.php\",\"Line\":172}"}
```

#### Browser log
N/A

**Comment by fluffy-critter** [comment]
Never mind, switched to nextCloud.

**Comment by ho4ho** [comment]
> OC_App::shouldUpgrade('search_lucene')

Cause by outdated / archived app long removed should be?

https://github.com/owncloudarchive/search_lucene

**Comment by fluffy-critter** [comment]
I never had any third party apps installed. I only used the Ubuntu packages and only used it for basic storage.

Anyway I switched to nextCloud and it’s working fine.

**Comment by ho4ho** [comment]
> Third party apps are all apps that are not distributed by https://marketplace.owncloud.com/publishers/owncloud"

https://doc.owncloud.org/server/10.2/admin_manual/maintenance/manual_upgrade.html#review-third-party-apps

search_lucene = third party app AFAIK

**Comment by fluffy-critter** [comment]
Like I said, I never configured that app myself. It may have been configured by an older version of the owncloud installer without my knowledge. Regardless, I've already resolved the issue.
