### ISSUE TITLE
App tests failing after "Restore dav.tech_preview status after test run"

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36379]
After PR #36375 some app CI is failing.
e.g.
https://drone.owncloud.com/owncloud/configreport/736/17/9
```
Feature: generate a configreport via occ
  As an administrator
  I want to generate a configreport to file a support / help request
  So that administrator can check the server report

  ┌─ @BeforeScenario # OccContext::before()
  │
  ╳  Exception: runOcc called without adminUsername - pass the username or call SetupHelper::init in /var/www/owncloud/testrunner/tests/TestHelpers/SetupHelper.php:286
  ╳  Stack trace:
  ╳  #0 /var/www/owncloud/testrunner/tests/TestHelpers/SetupHelper.php(643): TestHelpers\SetupHelper::checkAdminUsername(NULL, 'runOcc')
  ╳  #1 /var/www/owncloud/testrunner/tests/acceptance/features/bootstrap/CommandLine.php(165): TestHelpers\SetupHelper::runOcc(Array, NULL, NULL, 'http://server', NULL)
  ╳  #2 /var/www/owncloud/testrunner/tests/acceptance/features/bootstrap/CommandLine.php(199): FeatureContext->getSystemConfig('dav.enable.tech...', NULL, NULL, NULL, 'http://server', NULL)
  ╳  #3 /var/www/owncloud/testrunner/tests/acceptance/features/bootstrap/OccContext.php(1026): FeatureContext->getSystemConfigValue('dav.enable.tech...')
  ╳  #4 [internal function]: OccContext->before(Object(Behat\Behat\Hook\Scope\BeforeScenarioScope))
  ╳  #5 /var/www/owncloud/testrunner/apps/configreport/vendor-bin/behat/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(109): call_user_func_array(Array, Array)
```

And similar in:
https://drone.owncloud.com/owncloud/activity/872/39/9

`git bisect` told me:
```
51d4e620364100839556713d132b52617f25da98 is the first bad commit
commit 51d4e620364100839556713d132b52617f25da98
Author: Dipak Acharya <dpakach@gmail.com>
Date:   Tue Nov 5 09:19:14 2019 +0545

    Acceptance tests: Restore dav.tech_preview status after test run
```

Probable for some apps that do not have all the core contexts, they get to the `BeforeScenario` in `OccContext` without some other `BeforeScenario` having called `SetupHelper::init`

**Comment by phil-davis** [comment]
The test fail is easily reproduced locally in `configreport` with:
```
make test-acceptance-api BEHAT_FEATURE=tests/acceptance/features/apiConfigReport/occConfigReportReturnCode.feature
```
