### ISSUE TITLE
scality docker sometimes crashes on startup

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36398]
`scality` is used in some CI so that we test that a `scality` server works with ownCloud.

In drone-docker it sometimes crashes on startup, e.g. https://drone.owncloud.com/owncloud/core/21255/27/2
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Linux 4.15.0-66-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! s3@7.4.0 start: `npm-run-all --parallel start_dmd start_s3server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3@7.4.0 start script 'npm-run-all --parallel start_dmd start_s3server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel start_dmd start_s3server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```
and the drone pipeline fails.

Investigate.

**Comment by phil-davis** [comment]
owncloud-ci PR has been merged. But we still do not seem to be getting the new scality version.
See comment https://github.com/owncloud-ci/scality-s3server/pull/2#issuecomment-553693949

**Comment by phil-davis** [comment]
scality is using the new version. The reported version in text output was not updated in that scality release.

This looks improved - I am not seeing a problem recently, e.g. for the 3 nights last weekend there were no scality fails.
