### ISSUE TITLE
Internal server error by upload empty .jpg file (Call to a member function file_get_contents() on null, publicpreview.php)

### ISSUE THREAD

**Issue by ho4ho** [owncloud/core#36416]
### Steps to reproduce
1. Have empty file "test.jpg"
2. Create folder "test" in ownCloud
3. Upload empty file "test.jpg" to folder "test" in ownCloud
4. Create public link of folder "test"
5. Access public link

### Expected behaviour
No error by owncloud.log

### Actual behaviour
Error by owncloud.log below

### Server configuration
**PHP version:** 7.3

**ownCloud version:** 10.3.0

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** tar.bz

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '10.3.1.1',
  'dbname' => '',
  'dbhost' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'logtimezone' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'php',
  'mail_domain' => '',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '',
  'appcodechecker' => false,
  'trusted_domains' =>
  array (
    0 => '',
  ),
  'secret' => '',
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MarkDown',
    6 => 'OC\\Preview\\MP3',
    7 => 'OC\\Preview\\TXT',
    8 => 'OC\\Preview\\Illustrator',
    9 => 'OC\\Preview\\Movie',
    10 => 'OC\\Preview\\MSOffice2003',
    11 => 'OC\\Preview\\MSOffice2007',
    12 => 'OC\\Preview\\MSOfficeDoc',
    13 => 'OC\\Preview\\OpenDocument',
    14 => 'OC\\Preview\\PDF',
    15 => 'OC\\Preview\\Photoshop',
    16 => 'OC\\Preview\\Postscript',
    17 => 'OC\\Preview\\StarOffice',
    18 => 'OC\\Preview\\SVG',
    19 => 'OC\\Preview\\TIFF',
    20 => 'OC\\Preview\\Font',
  ),
  'loglevel' => 2,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/var/run/redis/redis-server.sock',
    'port' => 0,
  ),
  'overwrite.cli.url' => '',
  'htaccess.RewriteBase' => '/',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/owncloud/apps-external',
      'url' => '/apps-external',
      'writable' => true,
    ),
  ),
  'theme' => '',
  'mysql.utf8mb4' => true,
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### ownCloud log (data/owncloud.log)
```
{"reqId":"","level":3,"time":"2019-11-12T10:44:30+00:00","remoteAddr":"","user":"--","app":"index","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=36&y=36&t=abc","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function file_get_contents() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/image.php(573): OC\\\\Files\\\\Filesystem::file_get_contents('\\\/var\\\/www\\\/ownclo...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(1170): OC_Image->loadFromFile('\\\/var\\\/www\\\/ownclo...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(799): OC\\\\Preview->getMimeIcon()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/ajax\\\/publicpreview.php(112): OC\\\\Preview->showPreview()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(NULL)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(920): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_sha...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":754}"}
```

**Comment by phil-davis** [comment]
I added the QA labels. because I can easily add a test scenario with an empty text file and make a public link share, view the empty file and... That will confirm whatever is the behaviour here.

**Comment by ho4ho** [comment]
Not happening by https://demo.owncloud.org use 10.3.1, already fixed by this?

Or other problem on upload not generate preview?

**Comment by ho4ho** [comment]
Ok, also not happen by 10.3.0. Asked uploader of file, had problem by uploading multi files from android firefox browser causing empty file uploaded.

So problem caused by upload problem seems to me, not by empty file.

**Comment by ho4ho** [comment]
Now only get this errors in owncloud.log, cron job fixed preview somehow?

```
{"reqId":"","level":3,"time":"2019-11-12T15:24:23+00:00","remoteAddr":"","user":"--","app":"PHP","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"file_get_contents(\/var\/www\/owncloud\/data\/abc\/files\/var\/www\/owncloud\/core\/img\/filetypes\/image.svg): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#227"}
{"reqId":"","level":3,"time":"2019-11-12T15:24:23+00:00","remoteAddr":"","user":"--","app":"PHP","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"imagecreatefromstring(): Empty string or invalid image at \/var\/www\/owncloud\/lib\/private\/legacy\/image.php#573"}
```

**Comment by ho4ho** [comment]
Ok, think found why different message shown. Different is by using same or different browser (different session).

## Same browser logged into ownCloud and have same session

Get error:

```
{"reqId":"","level":3,"time":"2019-11-12T15:24:23+00:00","remoteAddr":"","user":"--","app":"PHP","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"file_get_contents(\/var\/www\/owncloud\/data\/abc\/files\/var\/www\/owncloud\/core\/img\/filetypes\/image.svg): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#227"}
{"reqId":"","level":3,"time":"2019-11-12T15:24:23+00:00","remoteAddr":"","user":"--","app":"PHP","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"imagecreatefromstring(): Empty string or invalid image at \/var\/www\/owncloud\/lib\/private\/legacy\/image.php#573"}
```

## Different browser not logged into ownCloud and not have same session

Get error:

```
{"reqId":"","level":3,"time":"2019-11-12T15:47:26+00:00","remoteAddr":"","user":"--","app":"index","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function file_get_contents() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/image.php(573): OC\\\\Files\\\\Filesystem::file_get_contents('\\\/var\\\/www\\\/ownclo...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(1170): OC_Image->loadFromFile('\\\/var\\\/www\\\/ownclo...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(799): OC\\\\Preview->getMimeIcon()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/ajax\\\/publicpreview.php(112): OC\\\\Preview->showPreview()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(NULL)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(920): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_sha...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":754}"}
```

**Comment by phil-davis** [comment]
@skshetry you can assign someone to add test coverage for this "empty file" case. See comment https://github.com/owncloud/core/issues/36416#issuecomment-552861511

When there are acceptance tests, then we will have an automated-reproducible bug (or not!) and can remove the QA labels and let this be schedule or whatever.

**Comment by skshetry** [comment]
Cannot assign to Kiran, as he is not in org. We looked into this late yesterday, but couldn't reproduce. We followed the above steps, but there was no log at all, as mentioned.

@ho4ho, can you please give us more information regarding reproducing the issue? Assigning myself  for now.

**Comment by ho4ho** [comment]
@skshetry Maybe different by not using:

```
    1 => 'OC\\Preview\\JPEG',
```

in config.php (update first post) found by: https://github.com/owncloud/files_mediaviewer/pull/100 ?

New steps produce:

1. Configure JPEG preview by config.php (see above)
2. `touch test.jpg` to have empty file "test.jpg"
3. Create folder "test" in ownCloud
4. Upload empty file "test.jpg" to folder "test" in ownCloud
5. Create public link of folder "test"
6. Access public link (same browser with same session, different browser without session)

New logs produced by loglevel 0:

### Same browser logged into ownCloud and have same session

Get error:

```
{"reqId":"","level":0,"time":"2019-11-20T12:39:55+01:00","remoteAddr":"","user":"--","app":"core","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"Generating preview for \"\/test\/files\/test\/test.jpg\" with \"OC\\Preview\\JPEG\""}
{"reqId":"","level":0,"time":"2019-11-20T12:39:55+01:00","remoteAddr":"","user":"--","app":"core","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"OC_Image->fixOrientation() Image is not a JPEG."}
{"reqId":"","level":0,"time":"2019-11-20T12:39:55+01:00","remoteAddr":"","user":"--","app":"core","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"OC_Image->fixOrientation() Orientation: -1"}
{"reqId":"","level":3,"time":"2019-11-20T12:39:55+01:00","remoteAddr":"","user":"--","app":"PHP","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"file_get_contents(\/var\/www\/owncloud\/data\/test\/files\/var\/www\/owncloud\/core\/img\/filetypes\/image.svg): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#227"}
{"reqId":"","level":3,"time":"2019-11-20T12:39:55+01:00","remoteAddr":"","user":"--","app":"PHP","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"imagecreatefromstring(): Empty string or invalid image at \/var\/www\/owncloud\/lib\/private\/legacy\/image.php#573"}
{"reqId":"","level":0,"time":"2019-11-20T12:39:55+01:00","remoteAddr":"","user":"--","app":"core","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"OC_Image->loadFromFile, Default"}
```

### Different browser not logged into ownCloud and not have same session

Get error:

```
{"reqId":"","level":0,"time":"2019-11-20T12:42:39+01:00","remoteAddr":"","user":"--","app":"core","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"Generating preview for \"\/test\/files\/test\/test.jpg\" with \"OC\\Preview\\JPEG\""}
{"reqId":"","level":0,"time":"2019-11-20T12:42:39+01:00","remoteAddr":"","user":"--","app":"core","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"OC_Image->fixOrientation() Image is not a JPEG."}
{"reqId":"","level":0,"time":"2019-11-20T12:42:39+01:00","remoteAddr":"","user":"--","app":"core","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"OC_Image->fixOrientation() Orientation: -1"}
{"reqId":"","level":3,"time":"2019-11-20T12:42:39+01:00","remoteAddr":"","user":"--","app":"index","method":"GET","url":"\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=abc&x=32&y=32&t=abc","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function file_get_contents() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/image.php(573): OC\\\\Files\\\\Filesystem::file_get_contents('\\\/var\\\/www\\\/ownclo...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(1170): OC_Image->loadFromFile('\\\/var\\\/www\\\/ownclo...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(799): OC\\\\Preview->getMimeIcon()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/ajax\\\/publicpreview.php(112): OC\\\\Preview->showPreview()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(NULL)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(920): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_sha...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":754}"}
```

**Comment by skshetry** [comment]
@ho4ho, can you try the steps with the new user? Looking into your log, I notice the exception is for different file "image.svg" which is not in `data` directory somehow?

Removing `validateToken` logs, I get the following log on same session:
```
{"reqId":"XdYmc1XHMylJyPamNNNU2AAAAAE","level":0,"time":"2019-11-21T05:53:55+00:00","remoteAddr":"::1","user":"test_user","app":"core","method":"GET","url":"\/core\/remote.php\/dav\/files\/test_user\/test\/test.jpg?c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&forceIcon=0&preview=1","message":"Generating preview for \"\/test_user\/files\/test\/test.jpg\" with \"OC\\Preview\\JPEG\""}
{"reqId":"XdYmc1XHMylJyPamNNNU2AAAAAE","level":0,"time":"2019-11-21T05:53:55+00:00","remoteAddr":"::1","user":"test_user","app":"core","method":"GET","url":"\/core\/remote.php\/dav\/files\/test_user\/test\/test.jpg?c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&forceIcon=0&preview=1","message":"OC_Image->fixOrientation() Image is not a JPEG."}
{"reqId":"XdYmc1XHMylJyPamNNNU2AAAAAE","level":0,"time":"2019-11-21T05:53:55+00:00","remoteAddr":"::1","user":"test_user","app":"core","method":"GET","url":"\/core\/remote.php\/dav\/files\/test_user\/test\/test.jpg?c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&forceIcon=0&preview=1","message":"OC_Image->fixOrientation() Orientation: -1"}
{"reqId":"XdYmc1XHMylJyPamNNNU2AAAAAE","level":0,"time":"2019-11-21T05:53:55+00:00","remoteAddr":"::1","user":"test_user","app":"webdav","method":"GET","url":"\/core\/remote.php\/dav\/files\/test_user\/test\/test.jpg?c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&forceIcon=0&preview=1","message":"Exception: HTTP\/1.1 404 Not Found: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/saugat\\\/www\\\/core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): OCA\\\\DAV\\\\Files\\\\PreviewPlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home\\\/saugat\\\/www\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(464): Sabre\\\\DAV\\\\Server->emit('method:GET', Array)\\n#2 \\\/home\\\/saugat\\\/www\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(241): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/home\\\/saugat\\\/www\\\/core\\\/apps\\\/dav\\\/lib\\\/Server.php(326): Sabre\\\\DAV\\\\Server->start()\\n#4 \\\/home\\\/saugat\\\/www\\\/core\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#5 \\\/home\\\/saugat\\\/www\\\/core\\\/remote.php(165): require_once('\\\/home\\\/saugat\\\/ww...')\\n#6 {main}\",\"File\":\"\\\/home\\\/saugat\\\/www\\\/core\\\/apps\\\/dav\\\/lib\\\/Files\\\/PreviewPlugin.php\",\"Line\":116}"}
{"reqId":"XdYmfcPIqS@pZB4pPgCZUwAAAAA","level":0,"time":"2019-11-21T05:54:05+00:00","remoteAddr":"::1","user":"test_user","app":"guests","method":"POST","url":"\/core\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json","message":"ignoring user '', not a guest"}
{"reqId":"XdYmgq7a3NeXzabQt8e4fAAAAAk","level":0,"time":"2019-11-21T05:54:10+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&t=36EBiTCwRlV5SHU","message":"Generating preview for \"\/test_user\/files\/test\/test.jpg\" with \"OC\\Preview\\JPEG\""}
{"reqId":"XdYmgq7a3NeXzabQt8e4fAAAAAk","level":0,"time":"2019-11-21T05:54:10+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&t=36EBiTCwRlV5SHU","message":"OC_Image->fixOrientation() Image is not a JPEG."}
{"reqId":"XdYmgq7a3NeXzabQt8e4fAAAAAk","level":0,"time":"2019-11-21T05:54:10+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&t=36EBiTCwRlV5SHU","message":"OC_Image->fixOrientation() Orientation: -1"}
{"reqId":"XdYmg2FtffsrQvCF6W1ITgAAAAg","level":0,"time":"2019-11-21T05:54:11+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2F%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=1920&y=1920&a=1&t=36EBiTCwRlV5SHU","message":"Generating preview for \"\/test_user\/files\/test\/test.jpg\" with \"OC\\Preview\\JPEG\""}
{"reqId":"XdYmg2FtffsrQvCF6W1ITgAAAAg","level":0,"time":"2019-11-21T05:54:11+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2F%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=1920&y=1920&a=1&t=36EBiTCwRlV5SHU","message":"OC_Image->fixOrientation() Image is not a JPEG."}
{"reqId":"XdYmg2FtffsrQvCF6W1ITgAAAAg","level":0,"time":"2019-11-21T05:54:11+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2F%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=1920&y=1920&a=1&t=36EBiTCwRlV5SHU","message":"OC_Image->fixOrientation() Orientation: -1"}
{"reqId":"XdYmg8PIqS@pZB4pPgCZWAAAAAA","level":0,"time":"2019-11-21T05:54:11+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&t=36EBiTCwRlV5SHU","message":"Generating preview for \"\/test_user\/files\/test\/test.jpg\" with \"OC\\Preview\\JPEG\""}
{"reqId":"XdYmg8PIqS@pZB4pPgCZWAAAAAA","level":0,"time":"2019-11-21T05:54:11+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&t=36EBiTCwRlV5SHU","message":"OC_Image->fixOrientation() Image is not a JPEG."}
{"reqId":"XdYmg8PIqS@pZB4pPgCZWAAAAAA","level":0,"time":"2019-11-21T05:54:11+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&t=36EBiTCwRlV5SHU","message":"OC_Image->fixOrientation() Orientation: -1"}
```

There is an exception, but I guess, it's expected at the time (i.e. when it is uploaded, but that's the separate issue from the public link issue).


On the separate session, I get:
```
{"reqId":"XdYrgFXHMylJyPamNNNU9gAAAAE","level":0,"time":"2019-11-21T06:15:28+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&t=36EBiTCwRlV5SHU","message":"Generating preview for \"\/test_user\/files\/test\/test.jpg\" with \"OC\\Preview\\JPEG\""}
{"reqId":"XdYrgFXHMylJyPamNNNU9gAAAAE","level":0,"time":"2019-11-21T06:15:28+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&t=36EBiTCwRlV5SHU","message":"OC_Image->fixOrientation() Image is not a JPEG."}
{"reqId":"XdYrgFXHMylJyPamNNNU9gAAAAE","level":0,"time":"2019-11-21T06:15:28+00:00","remoteAddr":"::1","user":"--","app":"core","method":"GET","url":"\/core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2Ftest.jpg&c=10afa3ce61cca65ec7be85d3d3423a11&x=40&y=40&t=36EBiTCwRlV5SHU","message":"OC_Image->fixOrientation() Orientation: -1"}
```

**Comment by ho4ho** [comment]
Same error by https://github.com/owncloud/core/issues/36416#issuecomment-556024819 seen by creating new user and uploading empty .jpg.

By creating new user (test) seen this in log with diff reqID:

```
{"reqId":"","level":3,"time":"2019-11-21T09:50:04+01:00","remoteAddr":"","user":"admin","app":"no app in context","method":"POST","url":"\/settings\/users\/users","message":"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud\/data\/test for user: test which differs from existing value: "}
```

**Comment by kiranparajuli589** [comment]
No errors on `owncloud log` at the date of the comment

- OC version:
```
ownCloud 10.7.1 prealpha (git)

Developed by the ownCloud community, the source code is licensed under the AGPL.
```
- app:list
```
Enabled:
  - activity:
    - Version: 2.6.0
    - Path: /home/kiran/www/core/apps-external/activity
  - comments:
    - Version: 0.3.0
    - Path: /home/kiran/www/core/apps/comments
  - dav:
    - Version: 0.6.0
    - Path: /home/kiran/www/core/apps/dav
  - encryption:
    - Version: 1.5.0
    - Path: /home/kiran/www/core/apps-external/encryption
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /home/kiran/www/core/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /home/kiran/www/core/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /home/kiran/www/core/apps/files
  - files_external:
    - Version: 0.7.1
    - Path: /home/kiran/www/core/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.4
    - Path: /home/kiran/www/core/apps-external/files_mediaviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /home/kiran/www/core/apps/files_sharing
  - files_texteditor:
    - Version: 2.3.0
    - Path: /home/kiran/www/core/apps-external/files_texteditor
  - files_trashbin:
    - Version: 0.9.1
    - Path: /home/kiran/www/core/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /home/kiran/www/core/apps/files_versions
  - market:
    - Version: 0.6.0
    - Path: /home/kiran/www/core/apps/market
  - notifications:
    - Version: 0.5.2
    - Path: /home/kiran/www/core/apps-external/notifications
  - oauth2:
    - Version: 0.5.0
    - Path: /home/kiran/www/core/apps-external/oauth2
  - provisioning_api:
    - Version: 0.5.0
    - Path: /home/kiran/www/core/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /home/kiran/www/core/apps/systemtags
  - testing:
    - Version: 0.1.0
    - Path: /home/kiran/www/core/apps-external/testing
  - updatenotification:
    - Version: 0.2.1
    - Path: /home/kiran/www/core/apps/updatenotification
  - user_ldap:
    - Version: 0.15.2
    - Path: /home/kiran/www/core/apps-external/user_ldap
  - web:
    - Version: 3.0.0
    - Path: /home/kiran/www/core/apps-external/web

```

- Configuration: `config/config.php`
```php
<?php
$CONFIG = array (
  'instanceid' => 'ocrar1409iwi',
  'passwordsalt' => 'jtK3FT0sUbm8h9KvkPplWtfxLGUkYh',
  'secret' => 'mNnNYSH+Jm/1/aZmv0B3gF/lfkyBe0yNL3PXX0V64HVlojzw',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/home/kiran/www/core/data',
  'overwrite.cli.url' => 'http://localhost/core',
  'dbtype' => 'mysql',
  'version' => '10.7.1.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'owncloud',
  'dbpassword' => 'owncloud',
  'logtimezone' => 'UTC',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/home/kiran/www/core/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/home/kiran/www/core/apps-external',
      'url' => '/apps-external',
      'writable' => true,
    ),
  ),
  'installed' => true,
  'htaccess.RewriteBase' => '/core/',
  'cors.allowed-domains' => 
  array (
    0 => 'http://localhost:9100',
    1 => 'http://localhost/web/dist',
  ),
  'dav.enable.tech_preview' => true,
  'theme' => '',
  'loglevel' => '2',
  'maintenance' => false,
  'mail_domain' => 'foobar.com',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '1025',
  'sharing.federation.allowHttpFallback' => true,
  'grace_period.demo_key.show_popup' => false,
  'files_external_allow_create_new_local' => 'true',
  'log_type' => 'owncloud',
  'csrf.disabled' => true,
//  'web.baseUrl' => 'http://localhost/core/index.php/apps/web',
  'ldapIgnoreNamingRules' => false,
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    11 => 'OC\\Preview\\Illustrator',
    12 => 'OC\\Preview\\Postscript',
    13 => 'OC\\Preview\\Photoshop',
    14 => 'OC\\Preview\\TIFF'
  ),
);
```
