### ISSUE TITLE
OC\RepairException: Upgrade is not possible

### ISSUE THREAD

**Issue by MichaelRenner** [owncloud/core#36437]
### Steps to reproduce
1. Update to 10.3.1-1+2.1: apt update
2.
3.

### Expected behaviour
works like a charm

### Actual behaviour
Update fail with this message in the browser:

    Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.

    Repair warning: Please install or update the following apps manually or disable them with: occ app:disable files_videoplayer

But this also fails:
occ app:disable files_pdfviewer
An unhandled exception has been thrown:
Error: Call to undefined function simplexml_load_file() in /var/www/owncloud/lib/private/App/InfoParser.php:48
Stack trace:
#0 /var/www/owncloud/lib/private/App/AppManager.php(479): OC\App\InfoParser->parse('/var/www/ownclo...')
#1 /var/www/owncloud/lib/private/App/AppManager.php(768): OC\App\AppManager->getAppInfoByPath('/var/www/ownclo...')
#2 /var/www/owncloud/lib/private/App/AppManager.php(709): OC\App\AppManager->getAppVersionByPath('/var/www/ownclo...')
#3 /var/www/owncloud/lib/private/App/AppManager.php(651): OC\App\AppManager->findAppInDirectories('files')
#4 /var/www/owncloud/lib/private/legacy/app.php(548): OC\App\AppManager->getAppPath('files')
#5 /var/www/owncloud/lib/private/legacy/app.php(114): OC_App::getAppPath('files')
#6 /var/www/owncloud/lib/base.php(585): OC_App::loadApps(Array)
#7 /var/www/owncloud/lib/base.php(1005): OC::init()
#8 /var/www/owncloud/console.php(64): require_once('/var/www/ownclo...')
#9 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#10 {main}

### Server configuration
**Operating system**: Debian 9

**Web server:** 2.4.25-3+deb9u9

**Database:** mysql 5.5.9999+default

**PHP version:** 7.3.11

**ownCloud version:** 10.3.1

**Updated from an older ownCloud or fresh install:** update

**Where did you install ownCloud from:** via apt repository http://download.owncloud.org/download/repositories/production/Debian_9.0/ used since a long time.

**Signing status (ownCloud 9.0 and above):**
unknown, can't login.

**The content of config/config.php:**
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'ocxtammbxcvi',
  'passwordsalt' => '**************',
  'secret' => '*******************',
  'trusted_domains' => 
  array (
    0 => 'xfer.domain.org',
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'password' => '',
    'dbindex' => 0,
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://xfer.domain.org',
  'dbtype' => 'mysql',
  'version' => '10.2.1.4',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbuser' => 'ownuser',
  'dbpassword' => '***********.',
  'loglevel' => 2,
  'singleuser' => false,
  'theme' => '',
  'mail_domain' => 'domain.org',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'localhost',
);

**List of activated apps:**
occ app:list fail with the same exception. But: It seams to me, that files_videoplayer is not present.

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Linux

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
{"reqId":"jw77lMH3FZWkvzRjYLfZ","level":3,"time":"2019-11-18T20:09:09+00:00","remoteAddr":"2001:a61:3ba8:1001:287e:6cc0:d32c:f89a","user":"--","app":"PHP","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=OwZtW295XjkKUAxlfhB4NS4mCWE1SgsyD28aSAU6AmQ%3D%3ATp7cDNuQieF3%2Bc5smVq5t%2B3waWczNJ42u0yAhAsFMH4%3D","message":"Undefined index: files_videoplayer at \/var\/www\/owncloud\/apps\/market\/lib\/MarketService.php#145"}
{"reqId":"jw77lMH3FZWkvzRjYLfZ","level":3,"time":"2019-11-18T20:09:09+00:00","remoteAddr":"2001:a61:3ba8:1001:287e:6cc0:d32c:f89a","user":"--","app":"PHP","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=OwZtW295XjkKUAxlfhB4NS4mCWE1SgsyD28aSAU6AmQ%3D%3ATp7cDNuQieF3%2Bc5smVq5t%2B3waWczNJ42u0yAhAsFMH4%3D","message":"array_shift() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/market\/lib\/MarketService.php#146"}

**Comment by MichaelRenner** [comment]
Found it by my own:
apt install php7.3-curl
apt install php-xml
apt install php7.3-bz2 php7.3-zip
occ app:disable files_videoplayer

fixed it.
