### ISSUE TITLE
Background Jobs throw exceptions for disabled apps.

### ISSUE THREAD

**Issue by cortho** [owncloud/core#36908]
owncloud 10.3.2

When an app is disabled but has got background jobs, they still reside in the ```oc_jobs``` table:

```
| 15 | OCA\MyApp\BackgroundJob\CleanupTask    | null     | 1580999402 |   1581084002 |           0 |                  0 |
```

So every time when background jobs are run, exceptions like the one below are filling the logs:

```
{
"reqId":"U1LAvTkZxSAodGKjfWjB",
"level":3,
"time":"2020-02-07T15:04:09+00:00",
"remoteAddr":"",
"user":"--",
"app":"core",
"method":"--",
"url":"--",
"message":
	"Exception: {
		"Exception":"OCP\AppFramework\QueryException",
		"Message":"Could not resolve OCA\MyApp\BackgroundJob\CleanupTask! Class OCA\MyApp\BackgroundJob\CleanupTask does not exist",
		"Code":0,
		"Trace":
			"#0 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(110): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\MyApp\B...')
			#1 /var/www/owncloud/lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query('OCA\MyApp\B...')
			#2 /var/www/owncloud/lib/private/BackgroundJob/JobList.php(253): OC\ServerContainer->query('OCA\MyApp\B...')
			#3 /var/www/owncloud/lib/private/BackgroundJob/JobList.php(209): OC\BackgroundJob\JobList->buildJob(Array)
			#4 /var/www/owncloud/lib/private/BackgroundJob/JobList.php(213): OC\BackgroundJob\JobList->getNext()
			#5 /var/www/owncloud/lib/private/BackgroundJob/JobList.php(213): OC\BackgroundJob\JobList->getNext()
			#6 /var/www/owncloud/core/Command/System/Cron.php(114): OC\BackgroundJob\JobList->getNext()
			#7 /var/www/owncloud/lib/composer/symfony/console/Command/Command.php(255): OC\Core\Command\System\Cron->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
			#8 /var/www/owncloud/lib/composer/symfony/console/Application.php(982): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
			#9 /var/www/owncloud/lib/composer/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\System\Cron), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
			#10 /var/www/owncloud/lib/composer/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
			#11 /var/www/owncloud/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
			#12 /var/www/owncloud/console.php(106): OC\Console\Application->run()
			#13 /var/www/owncloud/occ(11): require_once('/var/www/owncloud/...')
			#14 {main}
		",
		"File":"/var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php","Line":96
	}"
}
```

This happens because exceptions are thrown in any case, even when the app is disabled, see https://github.com/owncloud/core/blob/01aedc001178929d87e437a741f43a9804d71975/lib/private/BackgroundJob/JobList.php#L250-L263

While this issue is not critical at all is annoying having those exceptions in the logs all the time.

(Edit: show surrounding lines in code)

**Comment by ho4ho** [comment]
Duplicate by #35589 , #35678

**Comment by cortho** [comment]
So there are chances this will get fixed some day?

**Comment by VicDeo** [comment]
This logging was added intentionally in https://github.com/owncloud/core/pull/32623 so the admin is warned that there are some unneeded jobs. 
Closing as a duplicate.

**Comment by cortho** [comment]
@VicDeo I see the logging was added intentionally in the issue you mentioned, but it was never considered that Exception should only be shown for enabled apps.
