### ISSUE TITLE
files_external:export and import of local mounts

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37054]
### Steps to reproduce
1. have some local mount `zzz`
```
$ php occ files_external:list
+----------+-------------+---------+---------------------+---------------+---------+------------------+-------------------+
| Mount ID | Mount Point | Storage | Authentication Type | Configuration | Options | Applicable Users | Applicable Groups |
+----------+-------------+---------+---------------------+---------------+---------+------------------+-------------------+
| 4        | /zzz        | Local   | None                |               |         | All              |                   |
+----------+-------------+---------+---------------------+---------------+---------+------------------+-------------------+
```

2. export those settings:
```
$ php occ files_external:export > zzz.dat
$ cat zzz.dat
cat zzz.dat
[
    {
        "mount_id": 5,
        "mount_point": "\/zzz",
        "storage": "Local",
        "authentication_type": "None",
        "configuration": "",
        "options": "",
        "applicable_users": "All",
        "applicable_groups": ""
    }
]
```

3. delete the mount point
```
$ php occ files_external:delete 4
$ php occ files_external:list
No admin mounts configured
```

4. try to import the mount point:
```
$ php occ files_external:import zzz.dat
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\Files\External\StorageConfig::setBackend() must be an instance of OCP\Files\External\Backend\Backend, null given, called in /home/phil/git/owncloud/core/apps/files_external/lib/Command/Import.php on line 185 and defined in /home/phil/git/owncloud/core/lib/private/Files/External/StorageConfig.php:180
Stack trace:
#0 /home/phil/git/owncloud/core/apps/files_external/lib/Command/Import.php(185): OC\Files\External\StorageConfig->setBackend(NULL)
#1 /home/phil/git/owncloud/core/apps/files_external/lib/Command/Import.php(134): OCA\Files_External\Command\Import->parseData(Array, Object(OC\Files\External\Service\GlobalStoragesService))
#2 [internal function]: OCA\Files_External\Command\Import->OCA\Files_External\Command\{closure}(Array)
#3 /home/phil/git/owncloud/core/apps/files_external/lib/Command/Import.php(135): array_map(Object(Closure), Array)
#4 /home/phil/git/owncloud/core/lib/composer/symfony/console/Command/Command.php(255): OCA\Files_External\Command\Import->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/phil/git/owncloud/core/core/Command/Base.php(159): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/phil/git/owncloud/core/lib/composer/symfony/console/Application.php(1001): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/phil/git/owncloud/core/lib/composer/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files_External\Command\Import), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/phil/git/owncloud/core/lib/composer/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/phil/git/owncloud/core/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/phil/git/owncloud/core/console.php(116): OC\Console\Application->run()
#11 /home/phil/git/owncloud/core/occ(11): require_once('/home/phil/git/...')
```

### Expected behaviour
Should be able to import from the export of a local mount

### Actual behaviour
It crashes (see traceback above)

### Server configuration
Current core master

Noticed while adding `files_external` `occ` command tests issue #36704

**Comment by phil-davis** [comment]
If I edit the exported JSON and adjust `storage` `Local` to have the full class name of the storage, and adjust the `authentication_type` to be `null::null` (instead of `None`) then the import works.
```
[
    {
        "mount_id": 3,
        "mount_point": "\/zzz",
        "storage": "\\OC\\Files\\Storage\\Local",
        "authentication_type": "null::null",
        "configuration": "datadir: \"\\\/home\\\/phil\\\/tmp\"",
        "options": "",
        "applicable_users": "All",
        "applicable_groups": ""
    }
]
```

**Comment by phil-davis** [comment]
Also note, when I change the system language to `de` then `files_external:export` outputs:
```
[
    {
        "mount_id": 3,
        "mount_point": "\/zzz",
        "storage": "Lokal",
        "authentication_type": "Keine",
        "configuration": "",
        "options": "",
        "applicable_users": "All",
        "applicable_groups": ""
    }
]
```

**Comment by phil-davis** [comment]
QA has provided test scenarios that demonstrate the problems - #37123 - so I ave taken off QA labels and assignment.
