### ISSUE TITLE
Upgrade from 9.1.0 to 10.4

### ISSUE THREAD

**Issue by alexmejiaec** [owncloud/core#37241]
### Steps to reproduce
1. Execute migration after following upgrade steps` php occ upgrade`

### Expected behaviour
Migration should finish

### Actual behaviour
Got error

### Server configuration
**Operating system**: Centos 7

**Web server:** Apache

**Database:** Maria db 10.1

**PHP version:** 7.3

**ownCloud version:** 10.4

**Updated from an older ownCloud or fresh install:** 9.1.0

**Where did you install ownCloud from:** Tar file

**Signing status (ownCloud 9.0 and above):**

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'www.stststst.us',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'userowncloud',
  'dbpassword' => 'xxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'xxxxxx.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.xxxxxxx.com',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'owncloud@xxxxxxxx.com',
  'mail_smtppassword' => '25jP2xxxxxx',
  'mail_smtpsecure' => 'tls',
  'maintenance' => true,
  'loglevel' => 0,
);

```

{
    "system": {
        "instanceid": "ocu2snlb1kwr",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.diligente.us"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/www.diligente.us\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "maintenance": true,
        "loglevel": 0,
        "singleuser": false
    }
}

```
```
Enabled:
  - activity: 2.5.3
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.5.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.2
  - files_pdfviewer: 0.11.1
  - files_sharing: 0.12.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - gallery: 16.1.1
  - market: 0.5.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.4.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
```

[root@owncloud owncloud]# sudo -u apache php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2020-04-12T00:15:42+00:00 Set log level to debug
2020-04-12T00:15:42+00:00 Repair step: Upgrade app code from the marketplace
2020-04-12T00:15:42+00:00 Repair info: Enabling market app to assist with update
2020-04-12T00:15:42+00:00 Repair info: Using market to update existing apps
2020-04-12T00:15:42+00:00 Repair info: Attempting to update the following existing compatible apps from market: activity, comments, configreport, dav, federatedfilesharing, federation, files, files_external, files_mediaviewer, files_pdfviewer, files_sharing, files_texteditor, files_trashbin, files_versions, firstrunwizard, gallery, market, notifications, provisioning_api, systemtags, templateeditor, updatenotification
2020-04-12T00:15:42+00:00 Repair info: Fetching app from market: activity
2020-04-12T00:15:44+00:00 Repair info:
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: comments
2020-04-12T00:15:44+00:00 Repair info: App (comments) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: configreport
2020-04-12T00:15:44+00:00 Repair info: App (configreport) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: dav
2020-04-12T00:15:44+00:00 Repair info: App (dav) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: federatedfilesharing
2020-04-12T00:15:44+00:00 Repair info: App (federatedfilesharing) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: federation
2020-04-12T00:15:44+00:00 Repair info: App (federation) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: files
2020-04-12T00:15:44+00:00 Repair info: App (files) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: files_external
2020-04-12T00:15:44+00:00 Repair info: App (files_external) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: files_mediaviewer
2020-04-12T00:15:44+00:00 Repair info:
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: files_pdfviewer
2020-04-12T00:15:44+00:00 Repair info:
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: files_sharing
2020-04-12T00:15:44+00:00 Repair info: App (files_sharing) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: files_texteditor
2020-04-12T00:15:44+00:00 Repair info:
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: files_trashbin
2020-04-12T00:15:44+00:00 Repair info: App (files_trashbin) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: files_versions
2020-04-12T00:15:44+00:00 Repair info: App (files_versions) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: firstrunwizard
2020-04-12T00:15:44+00:00 Repair info: App (firstrunwizard) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: gallery
2020-04-12T00:15:44+00:00 Repair info:
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: market
2020-04-12T00:15:44+00:00 Repair info:
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: notifications
2020-04-12T00:15:44+00:00 Repair info: App (notifications) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: provisioning_api
2020-04-12T00:15:44+00:00 Repair info: App (provisioning_api) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: systemtags
2020-04-12T00:15:44+00:00 Repair info: App (systemtags) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: templateeditor
2020-04-12T00:15:44+00:00 Repair info:
2020-04-12T00:15:44+00:00 Repair info: Fetching app from market: updatenotification
2020-04-12T00:15:44+00:00 Repair info: App (updatenotification) is not known at the marketplace.
2020-04-12T00:15:44+00:00 Repair info: App was not updated: activity
2020-04-12T00:15:44+00:00 Repair info: App was not updated: comments
2020-04-12T00:15:44+00:00 Repair info: App was not updated: configreport
2020-04-12T00:15:44+00:00 Repair info: App was not updated: dav
2020-04-12T00:15:44+00:00 Repair info: App was not updated: federatedfilesharing
2020-04-12T00:15:44+00:00 Repair info: App was not updated: federation
2020-04-12T00:15:44+00:00 Repair info: App was not updated: files
2020-04-12T00:15:44+00:00 Repair info: App was not updated: files_external
2020-04-12T00:15:44+00:00 Repair info: App was not updated: files_mediaviewer
2020-04-12T00:15:44+00:00 Repair info: App was not updated: files_pdfviewer
2020-04-12T00:15:44+00:00 Repair info: App was not updated: files_sharing
2020-04-12T00:15:44+00:00 Repair info: App was not updated: files_texteditor
2020-04-12T00:15:44+00:00 Repair info: App was not updated: files_trashbin
2020-04-12T00:15:44+00:00 Repair info: App was not updated: files_versions
2020-04-12T00:15:44+00:00 Repair info: App was not updated: firstrunwizard
2020-04-12T00:15:44+00:00 Repair info: App was not updated: gallery
2020-04-12T00:15:44+00:00 Repair info: App was not updated: market
2020-04-12T00:15:44+00:00 Repair info: App was not updated: notifications
2020-04-12T00:15:44+00:00 Repair info: App was not updated: provisioning_api
2020-04-12T00:15:44+00:00 Repair info: App was not updated: systemtags
2020-04-12T00:15:44+00:00 Repair info: App was not updated: templateeditor
2020-04-12T00:15:44+00:00 Repair info: App was not updated: updatenotification
2020-04-12T00:15:44+00:00 Repair step: Repair MySQL database engine
2020-04-12T00:15:44+00:00 Repair step: Repair MySQL collation
2020-04-12T00:15:44+00:00 Repair info: All tables already have the correct collation -> nothing to do
2020-04-12T00:15:44+00:00 Repair step: Repair SQLite autoincrement
2020-04-12T00:15:44+00:00 Repair step: Repair orphaned reshare
2020-04-12T00:15:44+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2020-04-12T00:15:44+00:00 Repair info: lucene_status table does not exist -> nothing to do
2020-04-12T00:15:44+00:00 Updating database schema
2020-04-12T00:15:44+00:00 Updated database
2020-04-12T00:15:44+00:00 Repair step: Repair mime types
2020-04-12T00:15:44+00:00 Repair step: Detect file cache entries with path that does not match parent-child relationships
2020-04-12T00:15:44+00:00 Repair warning: The file cache contains entries with invalid path values for the following storage numeric ids: 10
2020-04-12T00:15:44+00:00 Repair warning: Please run `occ files:scan --all --repair` to repairall affected storages or run `occ files:scan userid --repair for each user with affected storages
2020-04-12T00:15:44+00:00 Repair step: Generate ETags for file where no ETag is present.
2020-04-12T00:15:44+00:00 Repair info: ETags have been fixed for 0 files/folders.
2020-04-12T00:15:44+00:00 Repair step: Clean tags and favorites
2020-04-12T00:15:44+00:00 Repair info: 0 tags of deleted users have been removed.
2020-04-12T00:15:44+00:00 Repair info: 0 tags for delete files have been removed.
2020-04-12T00:15:44+00:00 Repair info: 0 tag entries for deleted tags have been removed.
2020-04-12T00:15:44+00:00 Repair info: 0 tags with no entries have been removed.
2020-04-12T00:15:44+00:00 Repair step: Drop old database tables
2020-04-12T00:15:44+00:00 Drop old database tables
2020-04-12T00:15:44+00:00
 Done
 29/29 [============================] 100%2020-04-12T00:15:44+00:00
2020-04-12T00:15:44+00:00 Repair step: Drop old background jobs
2020-04-12T00:15:44+00:00 Repair step: Remove getetag entries in properties table
2020-04-12T00:15:44+00:00 Repair info: Removed 0 unneeded "{DAV:}getetag" entries from properties table.
2020-04-12T00:15:44+00:00 Repair step: Repair invalid shares
2020-04-12T00:15:44+00:00 Repair step: Repair sub shares
2020-04-12T00:15:44+00:00 Repair step: Remove old share propagation app entries
2020-04-12T00:15:44+00:00 Repair step: Move user avatars outside the homes to the new location
2020-04-12T00:15:44+00:00 Repair info: No action required
2020-04-12T00:15:44+00:00 Repair step: Fix user avatars location
2020-04-12T00:15:44+00:00 Repair info: No action required
2020-04-12T00:15:44+00:00 Repair step: Remove shares of a users root folder
2020-04-12T00:15:44+00:00 Repair step: Repair unmerged shares
2020-04-12T00:15:44+00:00 Repair unmerged shares
2020-04-12T00:15:44+00:00
An unhandled exception has been thrown:
TypeError: Argument 1 passed to Symfony\Component\Console\Helper\ProgressBar::start() must be of the type int or null, array given, called in /var/www/html/owncloud/core/Command/Upgrade.php on line 150 and defined in /var/www/html/owncloud/lib/composer/symfony/console/Helper/ProgressBar.php:292
Stack trace:
#0 /var/www/html/owncloud/core/Command/Upgrade.php(150): Symfony\Component\Console\Helper\ProgressBar->start(Array)
#1 /var/www/html/owncloud/lib/composer/symfony/event-dispatcher/EventDispatcher.php(264): OC\Core\Command\Upgrade->OC\Core\Command\{closure}(Object(Symfony\Component\EventDispatcher\GenericEvent), '\\OC\\Repair::sta...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /var/www/html/owncloud/lib/composer/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, '\\OC\\Repair::sta...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#3 /var/www/html/owncloud/lib/composer/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, '\\OC\\Repair::sta...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#4 /var/www/html/owncloud/lib/private/Repair.php(227): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\EventDispatcher\GenericEvent), '\\OC\\Repair::sta...')
#5 /var/www/html/owncloud/lib/private/Repair.php(250): OC\Repair->emit('\\OC\\Repair', 'startProgress', Array)
#6 /var/www/html/owncloud/lib/private/Repair/RepairUnmergedShares.php(352): OC\Repair->startProgress(Array)
#7 /var/www/html/owncloud/lib/private/Repair.php(90): OC\Repair\RepairUnmergedShares->run(Object(OC\Repair))
#8 /var/www/html/owncloud/lib/private/Updater.php(284): OC\Repair->run()
#9 /var/www/html/owncloud/lib/private/Updater.php(112): OC\Updater->doUpgrade('10.4.0.4', '9.1.0.15')
#10 /var/www/html/owncloud/core/Command/Upgrade.php(261): OC\Updater->upgrade()
#11 /var/www/html/owncloud/lib/composer/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/owncloud/lib/composer/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/owncloud/lib/composer/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/owncloud/lib/composer/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/owncloud/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/owncloud/console.php(116): OC\Console\Application->run()
#17 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')

```

**Comment by VicDeo** [comment]
Confirmed.
`userManager->countUsers()` returns an array at
https://github.com/owncloud/core/blob/73fa4964e3da909aacc33a8bbfc5b5e877a3ef12/lib/private/Repair/RepairUnmergedShares.php#L352 

Introduced with https://github.com/owncloud/core/pull/26361

**Comment by VicDeo** [comment]
@alexmejiaec could you please try this change: https://github.com/owncloud/core/pull/37246/files ?

**Comment by piotr-sikora-v** [comment]
I can confirm... this fix work for me
Same upgrade version and same error before fix.
