### ISSUE TITLE
Internal Server Error Immediately After Install

### ISSUE THREAD

**Issue by kirkofthefleet** [owncloud/core#37542]
Unable to log into owncloud system. I was able to install and got to the page to set the admin password. I set the password and then it gave me the error outlined below. When going back to the server's IP or URL, I get the same error page over and over. The most recent error page shows the following and was generated while re-doing the steps in this guide. I have generated this page may times with many different Request IDs:

Internal Server Error
The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.

More details can be found in the server log.

Technical details
Remote Address: 10.0.0.110
Request ID: mnDkgiF6OAlolJkBKO3V
 
### Steps to reproduce
1. Fresh Install of OwnCloud
2. Set admin password, chose next
3.

### Expected behaviour
Expecting to continue setup

### Actual behaviour
Get an error message with the following:

Internal Server Error
The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.

More details can be found in the server log.

Technical details
Remote Address: 10.0.0.110
Request ID: ICwWfF1bu2OFIiS3Y4aB

### Server configuration
**Operating system**:
CentOS Linux release 7.8.2003 (Core)
**Web server:**
nginx version: nginx/1.18.0
**Database:**
5.5.65-MariaDB MariaDB Server
**PHP version:**
PHP 7.2.31 (cli) (built: Jun  9 2020 08:18:32) ( NTS )
**ownCloud version:** (see ownCloud admin page)
cat version.php
<?php
$OC_Version = array(10,4,1,3);
$OC_VersionString = '10.4.1';
$OC_Channel = 'stable';
$OC_Edition = 'community';
$OC_VersionCanBeUpgradedFrom = [[8,2,11],[9,0,9],[9,1]];
$OC_Build = '2020-04-15T11:37:14+00:00 b02254ba8a4ac4f8db102ea1e07fc67f9d8a3fae';
$vendor = 'owncloud';

**Updated from an older ownCloud or fresh install:**
No, this is a fresh install
**Where did you install ownCloud from:**
https://download.owncloud.org/community/owncloud-10.4.1.tar.bz2
**Signing status (ownCloud 9.0 and above):**

```
I am unable to reach this page.
```

**The content of config/config.php:**

```
sudo -u nginx php occ config:list system
{
    "system": {
        "instanceid": "ocycnucuqr3m",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.0.10"
        ],
        "datadirectory": "\/usr\/share\/nginx\/html\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/10.0.0.10",
        "dbtype": "sqlite3",
        "version": "10.4.1.3",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/usr\/share\/nginx\/html\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/usr\/share\/nginx\/html\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "installed": true
    }
}

```

**List of activated apps:**

```
sudo -u nginx php occ app:list
Enabled:
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.5.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.2
  - files_sharing: 0.12.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - market: 0.5.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Version 83.0.4103.106 (Official Build) (64-bit)
**Operating system:**
Windows 10
Microsoft Windows
Version 1903 (OS Build 18362.900)
#### Web server error log
```
cat error.log
2020/06/16 16:02:53 [emerg] 1600#1600: unknown directive "tream" in /etc/nginx/conf.d/owncloud.conf:1
2020/06/16 16:03:25 [emerg] 1845#1845: unknown directive "tream" in /etc/nginx/conf.d/owncloud.conf:1
2020/06/16 16:04:14 [emerg] 2101#2101: unknown directive "tream" in /etc/nginx/conf.d/owncloud.conf:1
2020/06/16 16:18:30 [error] 2129#2129: *4 open() "/usr/share/nginx/html/owncloud/favicon.ico" failed (2: No such file or directory), client: 10.0.0.110, server: 192.168.1.101, request: "GET /favicon.ico HTTP/1.1", host: "10.0.0.10", referrer: "https://10.0.0.10/"
2020/06/16 16:18:30 [error] 2129#2129: *4 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /usr/share/nginx/html/owncloud/lib/base.php on line 1016" while reading response header from upstream, client: 10.0.0.110, server: 192.168.1.101, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.0.0.10", referrer: "https://10.0.0.10/"
2020/06/16 16:30:32 [error] 340#340: *25 FastCGI sent in stderr: "PHP message: creating sqlite db" while reading response header from upstream, client: 10.0.0.110, server: 192.168.1.101, request: "POST /index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.0.0.10"
```

#### ownCloud log (data/owncloud.log)
```
less owncloud.log
idateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"zgssyX67O7OnrSoOhzSf","level":3,"time":"2020-06-16T16:55:08+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"POST","url":"\/index.php\/heartbeat","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"O7OKvORu8idt9qhiK6Zx","level":3,"time":"2020-06-16T17:08:06+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"GEs0VzWXSVHoIl3o098c","level":3,"time":"2020-06-16T17:10:09+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"POST","url":"\/index.php\/heartbeat","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"8ELark560R8Vdv74xPRr","level":3,"time":"2020-06-16T17:11:04+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"B5Kswp6yyURPyYQGQQLI","level":3,"time":"2020-06-16T17:12:58+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"mnDkgiF6OAlolJkBKO3V","level":3,"time":"2020-06-16T17:17:30+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"tULr4LgGl2K9XU4wyW2t","level":3,"time":"2020-06-16T17:25:10+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"POST","url":"\/index.php\/heartbeat","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"CW6CNBpBmmPS5ezpXT1f","level":3,"time":"2020-06-16T17:32:31+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"POST","url":"\/index.php\/heartbeat","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"A4riuySyXINt9shdMXK7","level":3,"time":"2020-06-16T17:37:17+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"LlRWe58HRAEXPC5xSyRk","level":3,"time":"2020-06-16T17:40:11+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"POST","url":"\/index.php\/heartbeat","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"PavUePRkXfqIEjwgpmB2","level":3,"time":"2020-06-16T17:47:32+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"POST","url":"\/index.php\/heartbeat","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"nHp9KURrx0TDvqjYqQ2w","level":3,"time":"2020-06-16T17:55:12+00:00","remoteAddr":"10.0.0.110","user":"--","app":"index","method":"POST","url":"\/index.php\/heartbeat","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(750): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(450): OC\\\\User\\\\Session->invalidateSessionToken()\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(587): OC::initSession()\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/base.php(1059): OC::init()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/index.php(53): require_once('\\\/usr\\\/share\\\/ngin...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
```

#### Browser log
```
===============================================================================================================================
From Wireshark
Only tried to load page. Typing my server's IP into the web browser URL bar only. This takes me to the error page listed above
===============================================================================================================================
Log was too large to paste. Attached text of network [capture.]([url]([url](url
[owncloud_wireshark.txt](https://github.com/owncloud/core/files/4788392/owncloud_wireshark.txt)
)))

Browser log:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery-migrate.min.js?v=4045cf9c1f1607c2e3887b5c9cf70fc4:2 JQMIGRATE: Migrate is installed, version 1.4.0
4/index.php/heartbeat:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

```

**Comment by kirkofthefleet** [comment]
I thought I also included my web server's log. It shows the following:

[root@cloud nginx]# cat error.log
2020/06/16 16:02:53 [emerg] 1600#1600: unknown directive "tream" in /etc/nginx/conf.d/owncloud.conf:1
2020/06/16 16:03:25 [emerg] 1845#1845: unknown directive "tream" in /etc/nginx/conf.d/owncloud.conf:1
2020/06/16 16:04:14 [emerg] 2101#2101: unknown directive "tream" in /etc/nginx/conf.d/owncloud.conf:1
2020/06/16 16:18:30 [error] 2129#2129: *4 open() "/usr/share/nginx/html/owncloud/favicon.ico" failed (2: No such file or directory), client: 10.0.0.110, server: 192.168.1.101, request: "GET /favicon.ico HTTP/1.1", host: "10.0.0.10", referrer: "https://10.0.0.10/"
2020/06/16 16:18:30 [error] 2129#2129: *4 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /usr/share/nginx/html/owncloud/lib/base.php on line 1016" while reading response header from upstream, client: 10.0.0.110, server: 192.168.1.101, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.0.0.10", referrer: "https://10.0.0.10/"
2020/06/16 16:30:32 [error] 340#340: *25 FastCGI sent in stderr: "PHP message: creating sqlite db" while reading response header from upstream, client: 10.0.0.110, server: 192.168.1.101, request: "POST /index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.0.0.10"

**Comment by DeepDiver1975** [comment]
> 2020/06/16 16:18:30 [error] 2129#2129: *4 FastCGI sent in stderr: "PHP message: PHP Parse error: syntax error, unexpected ':', expecting ';' or '{' in /usr/share/nginx/html/owncloud/lib/base.php on line 1016" while reading response header from upstream, client: 10.0.0.110, server: 192.168.1.101, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.0.0.10", referrer: "https://10.0.0.10/"

PHP 7 introduced return type declarations - see https://www.php.net/manual/en/functions.returning-values.php - it looks like you have an older php version installed in parallel to php 7 which is used in your setup. Please double check your setup. THX
