### ISSUE TITLE
Docker upgrade 10.5.0 to 10.6.0

### ISSUE THREAD

**Issue by konstantin-schura** [owncloud/core#38372]
### Steps to reproduce
1. Installed owncloud 10.5.0 in docker
2. upgrade to 10.6.0

### Actual behaviour
Upgrade failed with error
_Error: Class 'OCA\Activity\AppInfo\Application' not found in /mnt/data/apps/activity_backup/appinfo/app.php:23_

### Server configuration
**Operating system**:
Ubuntu 18.04

**Database:**
Mariadb in docker. mariadb Ver 15.1 Distrib 10.4.8-MariaDB

**ownCloud version:** (see ownCloud admin page)
Docker container 10.5.0
**Updated from an older ownCloud or fresh install:**
Update from 10.0.1
**Where did you install ownCloud from:**
Manual install.

```
/index.php/settings/integrity/failed 
No errors have been found.
```

```
{
"system": {
"apps_paths": [
{
"path": "/var/www/owncloud/apps",
"url": "/apps",
"writable": false
},
{
"path": "/var/www/owncloud/custom",
"url": "/custom",
"writable": true
}
],
"trusted_domains": [
"localhost"
],
"datadirectory": "/mnt/data/files",
"dbtype": "mysql",
"dbhost": "db",
"dbname": "owncloud",
"dbuser": "REMOVED SENSITIVE VALUE",
"dbpassword": "REMOVED SENSITIVE VALUE",
"dbtableprefix": "oc_",
"log_type": "owncloud",
"mail_smtpmode": "smtp",
"mail_smtphost": "REMOVED SENSITIVE VALUE",
"mail_smtpport": "25",
"mail_smtptimeout": 10,
"mail_domain": "REMOVED SENSITIVE VALUE",
"mail_from_address": "REMOVED SENSITIVE VALUE",
"supportedDatabases": [
"sqlite",
"mysql",
"pgsql"
],
"upgrade.disable-web": true,
"default_language": "en",
"overwrite.cli.url": "REMOVED SENSITIVE VALUE",
"htaccess.RewriteBase": "/",
"logfile": "/mnt/data/files/owncloud.log",
"loglevel": 2,
"memcache.local": "\OC\Memcache\APCu",
"mysql.utf8mb4": true,
"filelocking.enabled": true,
"memcache.distributed": "\OC\Memcache\Redis",
"memcache.locking": "\OC\Memcache\Redis",
"redis": {
"host": "redis",
"port": "6379"
},
"passwordsalt": "REMOVED SENSITIVE VALUE",
"secret": "REMOVED SENSITIVE VALUE",
"version": "10.5.0.10",
"logtimezone": "UTC",
"installed": true,
"instanceid": "REMOVED SENSITIVE VALUE",
"maintenance": false
}
}

```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.6.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.4
  - files_pdfviewer: 0.11.2
  - files_sharing: 0.13.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - gallery: 16.1.1
  - market: 0.6.0
  - notifications: 0.5.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.4.0
  - updatenotification: 0.2.1
Disabled:
  - activity
  - activity_backup
  - admin_audit
  - announcementcenter
  - configreport
  - customgroups
  - encryption
  - enterprise_key
  - external
  - files_antivirus
  - files_classifier
  - files_external_dropbox
  - files_external_ftp
  - files_ldap_home
  - firewall
  - guests
  - oauth2
  - password_policy
  - ransomware_protection
  - sharepoint
  - systemtags_management
  - theme-enterprise
  - twofactor_totp
  - user_external
  - user_ldap
  - user_shibboleth
  - windows_network_drive
  - wopi
  - workflow


```

**Are you using encryption:** no

### Logs
```
Creating volume folders...
Creating hook folders...
Waiting for MySQL...
services are ready!
Waiting for Redis...
services are ready!
Removing custom folder...
Linking custom folder...
Removing config folder...
Linking config folder...
Writing config file...
Fixing base perms...
Fixing data perms...
Fixing hook perms...
Upgrading server database...
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2021-02-02T17:09:47+00:00 Set log level to debug
2021-02-02T17:09:47+00:00 Repair step: Upgrade app code from the marketplace
2021-02-02T17:09:47+00:00 Repair info: Using market to update existing apps
2021-02-02T17:09:47+00:00 Repair info: Attempting to update the following existing compatible apps from market: comments, dav, federatedfilesharing, federation, files, files_external, files_mediaviewer, files_pdfviewer, files_sharing, files_texteditor, files_trashbin, files_versions, firstrunwizard, gallery, market, notifications, provisioning_api, systemtags, templateeditor, updatenotification
2021-02-02T17:09:47+00:00 Repair info: Fetching app from market: comments
2021-02-02T17:09:48+00:00 Repair info: App (comments) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: dav
2021-02-02T17:09:48+00:00 Repair info: App (dav) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: federatedfilesharing
2021-02-02T17:09:48+00:00 Repair info: App (federatedfilesharing) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: federation
2021-02-02T17:09:48+00:00 Repair info: App (federation) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: files
2021-02-02T17:09:48+00:00 Repair info: App (files) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: files_external
2021-02-02T17:09:48+00:00 Repair info: App (files_external) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: files_mediaviewer
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: files_pdfviewer
2021-02-02T17:09:48+00:00 Repair info: 
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: files_sharing
2021-02-02T17:09:48+00:00 Repair info: App (files_sharing) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: files_texteditor
2021-02-02T17:09:48+00:00 Repair info: 
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: files_trashbin
2021-02-02T17:09:48+00:00 Repair info: App (files_trashbin) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: files_versions
2021-02-02T17:09:48+00:00 Repair info: App (files_versions) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: firstrunwizard
2021-02-02T17:09:48+00:00 Repair info: App (firstrunwizard) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: gallery
2021-02-02T17:09:48+00:00 Repair info: 
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: market
2021-02-02T17:09:48+00:00 Repair info: 
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: notifications
2021-02-02T17:09:48+00:00 Repair info: App (notifications) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: provisioning_api
2021-02-02T17:09:48+00:00 Repair info: App (provisioning_api) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: systemtags
2021-02-02T17:09:48+00:00 Repair info: App (systemtags) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: templateeditor
2021-02-02T17:09:48+00:00 Repair info: 
2021-02-02T17:09:48+00:00 Repair info: Fetching app from market: updatenotification
2021-02-02T17:09:48+00:00 Repair info: App (updatenotification) is not known at the marketplace.
2021-02-02T17:09:48+00:00 Repair info: App was not updated: comments
2021-02-02T17:09:48+00:00 Repair info: App was not updated: dav
2021-02-02T17:09:48+00:00 Repair info: App was not updated: federatedfilesharing
2021-02-02T17:09:48+00:00 Repair info: App was not updated: federation
2021-02-02T17:09:48+00:00 Repair info: App was not updated: files
2021-02-02T17:09:48+00:00 Repair info: App was not updated: files_external
2021-02-02T17:09:48+00:00 Repair info: App was not updated: files_pdfviewer
2021-02-02T17:09:48+00:00 Repair info: App was not updated: files_sharing
2021-02-02T17:09:48+00:00 Repair info: App was not updated: files_texteditor
2021-02-02T17:09:48+00:00 Repair info: App was not updated: files_trashbin
2021-02-02T17:09:48+00:00 Repair info: App was not updated: files_versions
2021-02-02T17:09:48+00:00 Repair info: App was not updated: firstrunwizard
2021-02-02T17:09:48+00:00 Repair info: App was not updated: gallery
2021-02-02T17:09:48+00:00 Repair info: App was not updated: market
2021-02-02T17:09:48+00:00 Repair info: App was not updated: notifications
2021-02-02T17:09:48+00:00 Repair info: App was not updated: provisioning_api
2021-02-02T17:09:48+00:00 Repair info: App was not updated: systemtags
2021-02-02T17:09:48+00:00 Repair info: App was not updated: templateeditor
2021-02-02T17:09:48+00:00 Repair info: App was not updated: updatenotification
2021-02-02T17:09:48+00:00 Repair step: Repair MySQL database engine
2021-02-02T17:09:49+00:00 Repair step: Repair MySQL collation
2021-02-02T17:09:49+00:00 Repair info: All tables already have the correct collation -> nothing to do
2021-02-02T17:09:49+00:00 Repair step: Repair SQLite autoincrement
2021-02-02T17:09:49+00:00 Repair step: Repair orphaned reshare
2021-02-02T17:09:49+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2021-02-02T17:09:49+00:00 Repair info: removing duplicate entries from lucene_status
2021-02-02T17:09:49+00:00 Updating database schema
2021-02-02T17:09:49+00:00 Updated database
2021-02-02T17:09:49+00:00 Updating <files_sharing> ...
2021-02-02T17:09:50+00:00 Updated <files_sharing> to 0.14.0
An unhandled exception has been thrown:
Error: Class 'OCA\Activity\AppInfo\Application' not found in /mnt/data/apps/activity_backup/appinfo/app.php:23
Stack trace:
#0 /var/www/owncloud/lib/private/legacy/app.php(253): require_once()
#1 /var/www/owncloud/lib/private/legacy/app.php(192): OC_App::requireAppFile()
#2 /var/www/owncloud/lib/private/DB/MigrationService.php(102): OC_App::loadApp()
#3 /var/www/owncloud/lib/private/Installer.php(529): OC\DB\MigrationService->__construct()
#4 /var/www/owncloud/lib/private/Installer.php(496): OC\Installer::installShippedApp()
#5 /var/www/owncloud/lib/private/Updater.php(275): OC\Installer::installShippedApps()
#6 /var/www/owncloud/lib/private/Updater.php(112): OC\Updater->doUpgrade()
#7 /var/www/owncloud/core/Command/Upgrade.php(266): OC\Updater->upgrade()
#8 /var/www/owncloud/lib/composer/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#9 /var/www/owncloud/lib/composer/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 /var/www/owncloud/lib/composer/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/owncloud/lib/composer/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /var/www/owncloud/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#13 /var/www/owncloud/console.php(116): OC\Console\Application->run()
#14 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#15 {main}ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
```

Could some one help with this?

**Comment by JanAckermann** [comment]
Seems the application 'activity_backup' in your apps or apps-external folder causes trouble, if you don't need this anymore, I would suggest to solve the problem

**Comment by konstantin-schura** [comment]
> Seems the application 'activity_backup' in your apps or apps-external folder causes trouble, if you don't need this anymore, I would suggest remove or move to another dir to solve the problem

Thank you!
