### ISSUE TITLE
[QA] public link action "Add to your ownCloud" fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38543]
Seen with two instances sharing and receiving version 10.7.0RC1

* create a public link on folder Documents with password 1234
* open a new browser session with that link
* paste the URL of the receiving server into "Add to your ownCloud"
* a password requester appears. enter 1234
* an error occurs:
![image](https://user-images.githubusercontent.com/1108546/111555135-0985d580-8788-11eb-980c-de3593eb5639.png)

The sharing server log has
```
{"reqId":"YFKblaWcHko--H-SDqTDdAAAAAY","level":3,"time":"2021-03-18T00:15:17+00:00","remoteAddr":"2.247.255.99","user":"admin","app":"PHP","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Undefined index: domain at \/var\/www\/owncloud\/apps\/windows_network_drive\/lib\/wnd.php#54"}
{"reqId":"YFKbq@AOrrKYC67egQcpdgAAAAI","level":3,"time":"2021-03-18T00:15:39+00:00","remoteAddr":"2.247.255.99","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/s\/FebRgABG20Y3xOh","message":"Undefined index: domain at \/var\/www\/owncloud\/apps\/windows_network_drive\/lib\/wnd.php#54"}
{"reqId":"YFKbrHbbQUqnKrgPAzCHOgAAABA","level":3,"time":"2021-03-18T00:15:40+00:00","remoteAddr":"2.247.255.99","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/","message":"Undefined index: domain at \/var\/www\/owncloud\/apps\/windows_network_drive\/lib\/wnd.php#54"}
{"reqId":"YFKbs@bHS7Rlkv4sA3NZvQAAAAQ","level":3,"time":"2021-03-18T00:15:47+00:00","remoteAddr":"2.247.255.99","user":"admin","app":"PHP","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Undefined index: domain at \/var\/www\/owncloud\/apps\/windows_network_drive\/lib\/wnd.php#54"}
{"reqId":"YFKb0XlsbbLE8MLQ34WxqQAAAAE","level":3,"time":"2021-03-18T00:16:17+00:00","remoteAddr":"2.247.255.99","user":"admin","app":"PHP","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Undefined index: domain at \/var\/www\/owncloud\/apps\/windows_network_drive\/lib\/wnd.php#54"}
```

The receiving server log is
[owncloud.log.zip](https://github.com/owncloud/core/files/6160498/owncloud.log.zip)

**Comment by jnweiger** [comment]
Same error when sharing without password.
Same error when sharing to demo.owncloud.org

**Comment by micbar** [comment]
@jnweiger uhh, you may have found an edge case. Can you try that with a link which does not point to an external storage?

@jvillafanez this is the legacy WND implementation. Could we have changed anything?

**Comment by jvillafanez** [comment]
There should be some additional logs from https://github.com/owncloud/core/blob/master/apps/files_sharing/ajax/external.php#L102 or some lines below https://github.com/owncloud/core/blob/master/apps/files_sharing/ajax/external.php#L123

For the undefined variables, I couldn't reproduce the problem, but it's weird since the variables come from the storage factory as far as I know. Core should provide that information, assuming there isn't anything weird going on.

**Comment by jnweiger** [comment]
My links come from the Documents folder, that sits outside of the WND drive.

![image](https://user-images.githubusercontent.com/1108546/111626177-fdccfa00-87ed-11eb-97f5-5d4923f11c72.png)

**Comment by jnweiger** [comment]
```
{"reqId":"uUiyrEXKqeGx4moyGDX6","level":0,"time":"2021-03-18T00:27:00+00:00","remoteAddr":"2.247.255.99","user":"admin","app":"files_sharing","method":"POST","url":"\/apps\/files_sharing\/external","message":"Invalid remote storage: GuzzleHttp\\Exception\\RequestException: cURL error 60: SSL certificate problem: self signed certificate"}
```
Yes, the sending machine has only self signed certs.

Retrying in the other direction. This sending machine has proper certs, the receiving machine not.

* Adding the link now succeeds.
* But the contents is not writable, nor readable.
![image](https://user-images.githubusercontent.com/1108546/111628194-3c63b400-87f0-11eb-9261-3ed23803943c.png)

**Comment by jnweiger** [comment]
Files are unreadable also when both sending and receiving machine have proper certs.
![image](https://user-images.githubusercontent.com/1108546/111629007-20144700-87f1-11eb-9926-9a5bb5727fc0.png)

**Comment by jnweiger** [comment]
Reproduced with federation sharing from the menu:
* admin@oc-10-7-0-beta2.oidc-2-0-0-20210311.jw-qa.owncloud.works created a federated share on his Documents folder for demo@oc-10-7-0-rc1-oidc-2-0-0-20210316.jw-qa.owncloud.works

* demo user at the RC1 machine accepted the folder and has the same problem. Contents is not readable, nothing can be uploaded.

CAUTION: This logfile starts at the same point as the logfile above. It is long.
[owncloud.log-20210318.zip](https://github.com/owncloud/core/files/6164437/owncloud.log-20210318.zip)

**Comment by micbar** [comment]
Raising to p1

**Comment by jvillafanez** [comment]
Works for me with a fresh install. OC 10.7.0RC1 in both servers.
Certificates signed internally and CA imported into both ownCloud server, so they're valid and recognized by both servers.

I have some unrelated logs in the sending server, but I don't think they affect to this ticket:
```
{"reqId":"G8DezXnNUl8KhP4ODcqA","level":2,"time":"2021-03-19T08:17:55+00:00","remoteAddr":"10.0.2.27","user":"admin","app":"core","method":"PUT","url":"\/remote.php\/dav\/files\/admin\/documents\/dog-sneeze-4Gifs.gif","message":"ignoring lock release with type 1 for files\/0d26bcf67e3407193a36e5d63ea4cf64. Lock hasn't been acquired before"}
{"reqId":"G8DezXnNUl8KhP4ODcqA","level":2,"time":"2021-03-19T08:17:55+00:00","remoteAddr":"10.0.2.27","user":"admin","app":"core","method":"PUT","url":"\/remote.php\/dav\/files\/admin\/documents\/dog-sneeze-4Gifs.gif","message":"ignoring lock release with type 1 for files\/1643260a650f527e48dc851d27f8b4ad. Lock hasn't been acquired before"}
```

**Comment by VicDeo** [comment]
Works for me on a fresh local install either. 
Tried both password-protected publicly shared directory  + 'Add to your owncloud'  and a simple federated share case

May be some app should be configured additionally to reproduce this...

**Comment by jvillafanez** [comment]
I see some "bad gateway" errors in the provided logs:
```
{"reqId":"zyuUqaxUWBPVB9JdgwUL","level":3,"time":"2021-03-18T10:34:06+00:00","remoteAddr":"91.13.138.142","user":"admin","app":"no app in context","method":"GET","url":"\/remote.php\/dav\/files\/admin\/testfile%20%282%29.txt?c=47d7b20da3875288244be89ee1f8bdf6&x=32&y=32&forceIcon=0&preview=1","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ServerException\",\"Message\":\"Server error response [url] https:\\\/\\\/oc-10-7-0-rc1-oidc-2-0-0-20210316.jw-qa.owncloud.works\\\/public.php\\\/webdav\\\/ [status code] 502 [reason phrase] Bad Gateway\",\"Code\":502,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Subscriber\\\/HttpError.php(32): GuzzleHttp\\\\Exception\\\\RequestException::create()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Event\\\/Emitter.php(108): GuzzleHttp\\\\Subscriber\\\\HttpError->onComplete()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(91): GuzzleHttp\\\\Event\\\\Emitter->emit()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke()\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(28): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(*** sensitive parameters replaced ***)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(152): GuzzleHttp\\\\Client->get()\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(356): OC\\\\Http\\\\Client\\\\Client->get()\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(303): OC\\\\Files\\\\Storage\\\\DAV->fopen()\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(317): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen()\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Checksum.php(59): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->fopen()\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(303): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum->fopen()\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1220): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen()\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1066): OC\\\\Files\\\\View->basicOperation()\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(111): OC\\\\Files\\\\View->fopen()\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview\\\/TXT.php(44): OC\\\\Files\\\\Node\\\\File->fopen()\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(1129): OC\\\\Preview\\\\TXT->getThumbnail()\\n#21 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(768): OC\\\\Preview->generatePreview()\\n#22 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(170): OC\\\\Preview->getPreview()\\n#23 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Files\\\/PreviewPlugin.php(116): OC\\\\Files\\\\Node\\\\File->getThumbnail()\\n#24 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Files\\\\PreviewPlugin->httpGet()\\n#25 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#26 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#27 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(330): Sabre\\\\DAV\\\\Server->start()\\n#28 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#29 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#30 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":89}"}
{"reqId":"zyuUqaxUWBPVB9JdgwUL","level":3,"time":"2021-03-18T10:34:06+00:00","remoteAddr":"91.13.138.142","user":"admin","app":"files_external","method":"GET","url":"\/remote.php\/dav\/files\/admin\/testfile%20%282%29.txt?c=47d7b20da3875288244be89ee1f8bdf6&x=32&y=32&forceIcon=0&preview=1","message":"Server error response [url] https:\/\/oc-10-7-0-rc1-oidc-2-0-0-20210316.jw-qa.owncloud.works\/public.php\/webdav\/ [status code] 502 [reason phrase] Bad Gateway"}
```
Probably related to the problem, but they don't happen on my machine.

In addition, I haven't check with openidconnect. I don't know if the openidconnect app is related or not.

**Comment by jvillafanez** [comment]
It seems it works now in https://oc-10-7-0-rc1-oidc-2-0-0-20210319.jw-qa.owncloud.works . Picked the link from demo.owncloud.org

**Comment by micbar** [comment]
@jnweiger Ok, this seems to be related to the old test instance.

Close here?
