### ISSUE TITLE
Directory is unavailable - getChildren Exception

### ISSUE THREAD

**Issue by watels** [owncloud/core#38582]
### Steps to reproduce
1. Upgrade from 10.3.2.2 to 10.6.0.5
2. Login on Main user

### Expected behaviour
Files should appear on Web interface.

### Actual behaviour
 I get this error message : "Ce répertoire n'est pas disponible. Consultez les logs ou contactez votre administrateur" . Directory is unavailable.

### Server configuration
**Operating system**: Debian 10.8

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.2.34

**ownCloud version:** (see ownCloud admin page) 10.6.0

**Updated from an older ownCloud or fresh install:**  Update from 10.3.2.2

**Where did you install ownCloud from:** https://doc.owncloud.com/server/admin_manual/maintenance/upgrade.html

**Signing status (ownCloud 9.0 and above):** No errors have been found.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

{
    "system": {
        "instanceid": "**************",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***.***.***.***",
            "**********",
            "cloud.*******.fr"
        ],
        "datadirectory": "\/mnt\/owncloud_data\/data2",
        "overwrite.cli.url": "https:\/\/cloud.*******.fr\/owncloud",
        "dbtype": "mysql",
        "version": "10.6.0.5",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "preview_max_x": 1500,
        "preview_max_y": 1500,
        "forcessl": true,
        "asset-pipeline.enabled": true,
        "trashbin_retention_obligation": "180",
        "defaultapp": "files",
        "session_keepalive": true,
        "check_for_working_htaccess": true,
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "updatechecker": false,
        "theme": "",
        "loglevel": 0,
        "log_type": "owncloud",
        "logfile": "data\/owncloud.log",
        "logdateformat": "F d, Y H:i:s",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}

**List of activated apps:**

```
If you have access to your command line run e.g.:
Enabled:
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.6.0
  - federatedfilesharing: 0.5.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.4
  - files_sharing: 0.14.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - market: 0.6.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - federation
  - notifications
  - user_external


**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No


### Logs
#### Web server error log


#### ownCloud log (data/owncloud.log)
{"reqId":"annJr4LJtLh8sCu8Vqiw","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"--","app":"OC\\User\\Session::login","method":"POST","url":"\/owncloud\/index.php\/login?redirect_url=%252Fowncloud%252Findex.php%252Fapps%252Ffiles%252F","message":"regenerating session id for uid MyUser, password set"}
{"reqId":"annJr4LJtLh8sCu8Vqiw","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"POST","url":"\/owncloud\/index.php\/login?redirect_url=%252Fowncloud%252Findex.php%252Fapps%252Ffiles%252F","message":"token 88f6c70cd54ce99832f653b5e7924e42ead173d1944a35d0fa6dc7b5e4be3621fba7b6080b07e394345ce3218aa837ca04f8a84545258d44bd9198302acbbf2e does not exist"}
{"reqId":"annJr4LJtLh8sCu8Vqiw","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"--","app":"OC\\User\\Session::validateToken","method":"POST","url":"\/owncloud\/index.php\/login?redirect_url=%252Fowncloud%252Findex.php%252Fapps%252Ffiles%252F","message":"token 88f6c70cd54ce99832f653b5e7924e42ead173d1944a35d0fa6dc7b5e4be3621fba7b6080b07e394345ce3218aa837ca04f8a84545258d44bd9198302acbbf2e, not found"}
{"reqId":"annJr4LJtLh8sCu8Vqiw","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"POST","url":"\/owncloud\/index.php\/login?redirect_url=%252Fowncloud%252Findex.php%252Fapps%252Ffiles%252F","message":"token 88f6c70cd54ce99832f653b5e7924e42ead173d1944a35d0fa6dc7b5e4be3621fba7b6080b07e394345ce3218aa837ca04f8a84545258d44bd9198302acbbf2e does not exist"}
{"reqId":"annJr4LJtLh8sCu8Vqiw","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\Authentication\\Token\\DefaultTokenProvider::generateToken","method":"POST","url":"\/owncloud\/index.php\/login?redirect_url=%252Fowncloud%252Findex.php%252Fapps%252Ffiles%252F","message":"generating token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112, uid MyUser, loginName MyUser, pwd set, name Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/89.0.4389.90 Safari\/537.36, type temporary"}
{"reqId":"IYSYhNyXGTiziCsE18Hu","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"IYSYhNyXGTiziCsE18Hu","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"IYSYhNyXGTiziCsE18Hu","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"Sg2EuMEPugZHkztAWkoU","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=6bcdf4e08d6f00ee3dd024a15b9cca9b","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"Sg2EuMEPugZHkztAWkoU","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=6bcdf4e08d6f00ee3dd024a15b9cca9b","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"Sg2EuMEPugZHkztAWkoU","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=6bcdf4e08d6f00ee3dd024a15b9cca9b","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"Sg2EuMEPugZHkztAWkoU","level":0,"time":"March 25, 2021 08:08:58","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=6bcdf4e08d6f00ee3dd024a15b9cca9b","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"127T3y8NdLGw2MjJL4z0","level":0,"time":"March 25, 2021 08:08:59","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/MyUser\/","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"0FK9uzCywtIOXKIdVunu","level":0,"time":"March 25, 2021 08:08:59","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/avatar\/MyUser\/28","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"0FK9uzCywtIOXKIdVunu","level":0,"time":"March 25, 2021 08:08:59","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/avatar\/MyUser\/28","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"0FK9uzCywtIOXKIdVunu","level":0,"time":"March 25, 2021 08:08:59","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/avatar\/MyUser\/28","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"127T3y8NdLGw2MjJL4z0","level":4,"time":"March 25, 2021 08:08:59","remoteAddr":"***.***.***.***","user":"MyUser","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/MyUser\/","message":"Exception: Call to undefined method OCA\\DAV\\Connector\\Sabre\\File::getChildren(): {\"Exception\":\"Error\",\"Message\":\"Call to undefined method OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File::getChildren()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(900): Sabre\\\\DAV\\\\Tree->getChildren('files\\\/MyUser')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(982): Sabre\\\\DAV\\\\Server->generatePathNodes(Object(Sabre\\\\DAV\\\\PropFind), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1661): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('files\\\/MyUser', Array, 1)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1646): Sabre\\\\DAV\\\\Server->writeMultiStatus(Object(Sabre\\\\Xml\\\\Writer), Object(Generator), false)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(346): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit('method:PROPFIND', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(330): Sabre\\\\DAV\\\\Server->start()\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php\",\"Line\":200}"}
{"reqId":"sDiofUUXFEWIVHl4Vgmx","level":0,"time":"March 25, 2021 08:08:59","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/avatar\/MyUser\/28","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"sDiofUUXFEWIVHl4Vgmx","level":0,"time":"March 25, 2021 08:08:59","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/avatar\/MyUser\/28","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}
{"reqId":"sDiofUUXFEWIVHl4Vgmx","level":0,"time":"March 25, 2021 08:08:59","remoteAddr":"***.***.***.***","user":"MyUser","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/index.php\/avatar\/MyUser\/28","message":"token bf66b8711dc207cb47ed88a65bee82be9dc3e3294ae7d02c92e4cd9436d35bdc2a58f46d331c869957ecbac6dd509aef13bb6767f85ed2f12ba84ce7ef761112 with token id 12093 found, validating"}



#### Browser log
```
Insert your browser log here, this could for example include:
PROPFIND https://cloud.*********.fr/owncloud/remote.php/dav/files/MyUser/ 500 (Internal Server Error)

**Comment by watels** [comment]
In the same time I did an upgrade from Debian 8 to Debian 10... probably not the best idea but needed to upgrade PHP and I thought I had to.

Another thing is that it works without error on 2 other user logged on my Owncloud Server.
I have the issue with only one user... but the main one

**Comment by watels** [comment]
I lauched these commands and now it seems ok again :)

sudo -u www-data php occ maintenance:singleuser --on
sudo -u www-data php occ files:scan --all --repair
sudo -u www-data php occ maintenance:singleuser --off
