### ISSUE TITLE
[QA] Deleting 1000 subfolders via webUI  is unreliable

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38633]
Seen on server 10.6.0 and 10.7.0 with firefox 86.0

connect client to server, in the local sync folder run
```
#! /usr/bin/python3
import os
total=1200
os.system('mkdir d%d' % total)
for i in range(total):
  os.system('mkdir "d%d/Mo 12. Apr 12:55:27 +%04dDesktop-dingens"' % (total, i))
```

Using the web UI, navgate into the d1200 subfolder, select all:
![image](https://user-images.githubusercontent.com/1108546/114386480-8f335000-9b91-11eb-91f9-22ab048c80a3.png)

----
then hit the delete button in the upper right corner. An error occurs. 

![image](https://user-images.githubusercontent.com/1108546/114386518-9e1a0280-9b91-11eb-9e7b-c289e8f76faf.png)

----
the UI starts scrolling, while it deletes folders. Wait ca 1 minute until it finishes.
It stops with 587 folders remaining.

![image](https://user-images.githubusercontent.com/1108546/114386638-c4d83900-9b91-11eb-86b0-fe903fa8cd15.png)

----
Reload the web page. In reality, all folders (except one) were deleted.

![image](https://user-images.githubusercontent.com/1108546/114386716-e0434400-9b91-11eb-92f6-d20f6e2446b8.png)

**Comment by jnweiger** [comment]
The one error occured using local host. The log has
```
{"reqId":"GdiEAq57UQVlD1oCHqmT","level":2,"time":"2021-04-08T18:05:01+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"files_backup has been disabled because the license is not valid"}
{"reqId":"JYJEmaSTHLFEAZlOeg5F","level"::4,"time":"2021-04-12T11:13:36+00:00","remoteAddr":"172.17.0.1","user":"admin","app":"webdav","method":"DELETE","url":"\/remote.php\/dav\/files\/admin\/d1200\/Mo%2012.%20Apr%2012%3A55%3A27%20%2B0000Desktop-dingens","message":"Caused by: {\"Exception\":\"Doctrine\\\\DBAL\\\\Driver\\\\PDOException\",\"Message\":\"SQLSTATE[HY000]: General error: 5 database is locked\",\"Code\":\"HY000\",\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1073): Doctrine\\\\DBAL\\\\Driver\\\\PDOStatement->execute()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(207): Doctrine\\\\DBAL\\\\Connection->executeUpdate()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(206): OC\\\\DB\\\\Connection->executeUpdate()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(678): OC\\\\Lock\\\\DBLockingProvider->releaseLock()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Common->releaseLock()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(2116): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(2166): OC\\\\Files\\\\View->unlockPath()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1226): OC\\\\Files\\\\View->unlockFile()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(367): OC\\\\Files\\\\View->basicOperation()\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(*** sensitive parameters replaced ***)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(378): OC\\\\Files\\\\View->emittingCall()\\n#13 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(348): OC\\\\Files\\\\View->rmdir()\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(281): Sabre\\\\DAV\\\\Tree->delete()\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpDelete()\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#19 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(330): Sabre\\\\DAV\\\\Server->start()\\n#20 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#21 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/PDOStatement.php\",\"Line\":131}"}
{"reqId":"JYJEmaSTHLFEAZlOeg5F","level":4,"time":"2021-04-12T11:13:36+00:00","remoteAddr":"172.17.0.1","user":"admin","app":"webdav","method":"DELETE","url":"\/remote.php\/dav\/files\/admin\/d1200\/Mo%2012.%20Apr%2012%3A55%3A27%20%2B0000Desktop-dingens","message":"Caused by: {\"Exception\":\"PDOException\",\"Message\":\"SQLSTATE[HY000]: General error: 5 database is locked\",\"Code\":\"HY000\",\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/PDOStatement.php(129): PDOStatement->execute()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1073): Doctrine\\\\DBAL\\\\Driver\\\\PDOStatement->execute()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(207): Doctrine\\\\DBAL\\\\Connection->executeUpdate()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(206): OC\\\\DB\\\\Connection->executeUpdate()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(678): OC\\\\Lock\\\\DBLockingProvider->releaseLock()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Common->releaseLock()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(2116): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(2166): OC\\\\Files\\\\View->unlockPath()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1226): OC\\\\Files\\\\View->unlockFile()\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(367): OC\\\\Files\\\\View->basicOperation()\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(*** sensitive parameters replaced ***)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(378): OC\\\\Files\\\\View->emittingCall()\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(348): OC\\\\Files\\\\View->rmdir()\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(281): Sabre\\\\DAV\\\\Tree->delete()\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpDelete()\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#20 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(330): Sabre\\\\DAV\\\\Server->start()\\n#21 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#22 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#23 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/PDOStatement.php\",\"Line\":129}"}

**Comment by jnweiger** [comment]
On demo.owncloud.org (10.7.0) it stops much earlier (but erases all without error):

![image](https://user-images.githubusercontent.com/1108546/114387638-fa315680-9b92-11eb-94b5-d28aa2d7d4f1.png)
