### ISSUE TITLE
[QA] occ file:scan prints OCP\Lock\LockedException

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38655]
Seen with 10.7.0

Upload 1000 large files through a desktop client.
While the upload is running ...
Try `occ file:scan` several times. It eventually runs into a locked exception:

```
# occ file:scan --all

Scanning files for 1 users
Starting scan for user 1 out of 1 (admin)
Exception during scan: OCP\Lock\LockedException: "files/5b4975a590aa65e18b6d7eb5ac15929f" is locked
#0 /var/www/owncloud/lib/private/Files/Storage/Common.php(669): OC\Lock\MemcacheLockingProvider->acquireLock()
#1 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(599): OC\Files\Storage\Common->acquireLock()
#2 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(599): OC\Files\Storage\Wrapper\Wrapper->acquireLock()
#3 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(599): OC\Files\Storage\Wrapper\Wrapper->acquireLock()
#4 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(148): OC\Files\Storage\Wrapper\Wrapper->acquireLock()
#5 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(430): OC\Files\Cache\Scanner->scanFile()
#6 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(398): OC\Files\Cache\Scanner->handleChildren()
#7 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(401): OC\Files\Cache\Scanner->scanChildren()
#8 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(401): OC\Files\Cache\Scanner->scanChildren()
#9 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(401): OC\Files\Cache\Scanner->scanChildren()
#10 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(401): OC\Files\Cache\Scanner->scanChildren()
#11 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(401): OC\Files\Cache\Scanner->scanChildren()
#12 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(331): OC\Files\Cache\Scanner->scanChildren()
#13 /var/www/owncloud/lib/private/Files/Utils/Scanner.php(246): OC\Files\Cache\Scanner->scan()
#14 /var/www/owncloud/apps/files/lib/Command/Scan.php(251): OC\Files\Utils\Scanner->scan()
#15 /var/www/owncloud/apps/files/lib/Command/Scan.php(400): OCA\Files\Command\Scan->scanFiles()
#16 /var/www/owncloud/apps/files/lib/Command/Scan.php(362): OCA\Files\Command\Scan->userScan()
#17 /var/www/owncloud/apps/files/lib/Command/Scan.php(328): OCA\Files\Command\Scan->processUserChunks()
#18 /var/www/owncloud/lib/composer/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()
#19 /var/www/owncloud/core/Command/Base.php(159): Symfony\Component\Console\Command\Command->run()
#20 /var/www/owncloud/lib/composer/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#21 /var/www/owncloud/lib/composer/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#22 /var/www/owncloud/lib/composer/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#23 /var/www/owncloud/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#24 /var/www/owncloud/console.php(116): OC\Console\Application->run()
#25 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#26 {main}

+---------+-------+--------------+------------------+
| Folders | Files | Elapsed time | Items per second |
+---------+-------+--------------+------------------+
| 16      | 486   | 00:00:01     | 426              |
+---------+-------+--------------+------------------+
```

Expected behaviour: locked files are not an issue for files scan. We only read.

**Comment by JammingBen** [comment]
> Expected behaviour: locked files are not an issue for files scan. We only read.

A read action will lock the table via a shared lock (= read lock). While a table can have multiple share locks at the same time, an exclusive lock (= write lock) completely locks the table, denying any other locks. 

Probably the upload acquires an exclusive lock on the table. As a result, the scan command cannot acquire a shared lock during this process. I don't see a false behavior here.
