### ISSUE TITLE
white page :: include(/var/www/html/owncloud/lib/composer/composer/../../../lib/private/legacy/util.php

### ISSUE THREAD

**Issue by stabledave** [owncloud/core#39455]
### Steps to reproduce
1. update debian 10 to 11 
2. update php 7.2 to php 7.4 in the process
3. leave ownCloud 10.8 untouched

### Expected behaviour
/owncloud/ should display login screen

### Actual behaviour
/owncloud/ redirectes to /owncloud/login.php and shows a blank screen

### Server configuration
**Operating system**: debian 11, kernel 5.10.0-9

**Web server:** apache-2.4.51-1

**Database:** maria 10.5

**PHP version:** 7.4

**ownCloud version:** 10.8

**Updated from an older ownCloud or fresh install:** updated from 10.7 like ~3 months ago

**Where did you install ownCloud from:** manual

**Signing status (ownCloud 9.0 and above):**

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    1 => '',
    0 => '',
  ),
  'datadirectory' => '/home/user/DATA/',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '10.8.0.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'Europe/Berlin',
  'logdateformat' => 'H:i:s    d.m',
  'installed' => true,
  'loglevel' => 0,
  'maintenance' => true,
  'session_keepalive' => true,
  'filelocking.enabled' => false,
  'remember_login_cookie_lifetime' => 25920000,
  'session_lifetime' => 25920000,
  'singleuser' => false,
  'appstoreenabled' => true,
  'proxy' => '',
);

**List of activated apps:**
sudo -u www-data php occ app:list throws error too but basically just the default + calendar

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** 

**Operating system:**

#### Web server error log
```
[Thu Nov 04 14:23:21.436955 2021] [php7:warn] [pid 99013] [client 10.0.2.2:64724] PHP Warning:  include(/var/www/html/owncloud/lib/composer/composer/../../../lib/private/legacy/util.php): failed to open stream: No such file or directory in /var/www/html/owncloud/lib/composer/composer/ClassLoader.php on line 444
[Thu Nov 04 14:23:21.437048 2021] [php7:warn] [pid 99013] [client 10.0.2.2:64724] PHP Warning:  include(): Failed opening '/var/www/html/owncloud/lib/composer/composer/../../../lib/private/legacy/util.php' for inclusion (include_path='/var/www/html/owncloud/apps') in /var/www/html/owncloud/lib/composer/composer/ClassLoader.php on line 444
[Thu Nov 04 14:23:21.437132 2021] [php7:error] [pid 99013] [client 10.0.2.2:64724] PHP Fatal error:  Uncaught Error: Class 'OC_Util' not found in /var/www/html/owncloud/lib/private/Server.php:457\nStack trace:\n#0 /var/www/html/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(118): OC\\Server->OC\\{closure}()\n#1 /var/www/html/owncloud/lib/private/>
[Thu Nov 04 14:23:49.150997 2021] [php7:error] [pid 99016] [client 10.0.2.2:63202] script '/var/www/html/owncloud/status.php' not found or unable to stat
[Thu Nov 04 14:23:49.153951 2021] [php7:warn] [pid 99016] [client 10.0.2.2:63202] PHP Warning:  include(/var/www/html/owncloud/lib/composer/composer/../../../lib/private/legacy/util.php): failed to open stream: No such file or directory in /var/www/html/owncloud/lib/composer/composer/ClassLoader.php on line 444
[Thu Nov 04 14:23:49.154021 2021] [php7:warn] [pid 99016] [client 10.0.2.2:63202] PHP Warning:  include(): Failed opening '/var/www/html/owncloud/lib/composer/composer/../../../lib/private/legacy/util.php' for inclusion (include_path='/var/www/html/owncloud/apps') in /var/www/html/owncloud/lib/composer/composer/ClassLoader.php on line 444
[Thu Nov 04 14:23:49.154113 2021] [php7:error] [pid 99016] [client 10.0.2.2:63202] PHP Fatal error:  Uncaught Error: Class 'OC_Util' not found in /var/www/html/owncloud/lib/private/Server.php:457\nStack trace:\n#0 /var/www/html/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(118): OC\\Server->OC\\{closure}()\n#1 /var/www/html/owncloud/lib/private/>
[Thu Nov 04 14:23:56.372419 2021] [php7:error] [pid 99014] [client 10.0.2.2:46014] script '/var/www/html/system_api.php' not found or unable to stat
[Thu Nov 04 14:23:57.065110 2021] [php7:error] [pid 99022] [client 10.0.2.2:41862] script '/var/www/html/system_api.php' not found or unable to stat
[Thu Nov 04 14:23:57.742202 2021] [php7:error] [pid 99017] [client 10.0.2.2:41100] script '/var/www/html/system_api.php' not found or unable to stat
[Thu Nov 04 14:24:06.175799 2021] [php7:error] [pid 99022] [client 10.0.2.2:51323] script '/var/www/html/owncloud/status.php' not found or unable to stat
[Thu Nov 04 14:24:06.179329 2021] [php7:warn] [pid 99022] [client 10.0.2.2:51323] PHP Warning:  include(/var/www/html/owncloud/lib/composer/composer/../../../lib/private/legacy/util.php): failed to open stream: No such file or directory in /var/www/html/owncloud/lib/composer/composer/ClassLoader.php on line 444
[Thu Nov 04 14:24:06.179430 2021] [php7:warn] [pid 99022] [client 10.0.2.2:51323] PHP Warning:  include(): Failed opening '/var/www/html/owncloud/lib/composer/composer/../../../lib/private/legacy/util.php' for inclusion (include_path='/var/www/html/owncloud/apps') in /var/www/html/owncloud/lib/composer/composer/ClassLoader.php on line 444
[Thu Nov 04 14:24:06.179616 2021] [php7:error] [pid 99022] [client 10.0.2.2:51323] PHP Fatal error:  Uncaught Error: Class 'OC_Util' not found in /var/www/html/owncloud/lib/private/Server.php:457\nStack trace:\n#0 /var/www/html/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(118): OC\\Server->OC\\{closure}()\n#1 /var/www/html/owncloud/lib/private/>

```
#### ownCloud log (data/owncloud.log)
```
{"reqId":"6e6e8c72-6ea3-4333-a88d-83a989245b15","level":4,"time":"10:42:59    04.11","remoteAddr":"10.0.2.2","user":"X","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/X\/","message":"Exception: HTTP\/1.1 503 System in maintenance mode.: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"System in maintenance mode.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\DAV\\\\Server->emit('beforeMethod:PR...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(334): Sabre\\\\DAV\\\\Server->start()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":82}"}
{"reqId":"68ktfaWsaHRtQR3n29EN","level":4,"time":"10:44:53    04.11","remoteAddr":"10.0.2.2","user":"X","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/principals\/users\/X\/","message":"Exception: HTTP\/1.1 503 System in maintenance mode.: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"System in maintenance mode.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\DAV\\\\Server->emit('beforeMethod:PR...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(334): Sabre\\\\DAV\\\\Server->start()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":82}"}
{"reqId":"aTbpWU6RVqZ6EUzQZepF","level":0,"time":"10:48:27    04.11","remoteAddr":"10.0.2.2","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/principals\/users\/X\/","message":"invalidating token bcf1c555eba3427106590e0e03171fd452abe56742b043f72e239b38ab6abc47b316070d7aa2a58365d8d79940fbaf864ff5230a534f02af9acb5357ed69f7f5"}
{"reqId":"Yxs1g4Jyz17cnvVVOoTS","level":4,"time":"10:49:53    04.11","remoteAddr":"10.0.2.2","user":"X","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/principals\/users\/X\/","message":"Exception: HTTP\/1.1 503 System in maintenance mode.: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"System in maintenance mode.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\DAV\\\\Server->emit('beforeMethod:PR...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(334): Sabre\\\\DAV\\\\Server->start()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":82}"}

```

Appearently this 
[Thu Nov 04 14:23:21.436955 2021] [php7:warn] [pid 99013] [client 10.0.2.2:64724] PHP Warning:  include(/var/www/html/owncloud/lib/composer/composer/../../../lib/private/legacy/util.php): failed to open stream: No such file or directory in /var/www/html/owncloud/lib/composer/composer/ClassLoader.php on line 444
is what's causing problems. 
All mods required by oc manual are installed, other similar applications work after update (e.g. mattermost). 
Tried on fresh apache install in cloned env, still same behaviour, so I don't think it's apache. Any ideas? Couldn't find path lib/private/legacy in neither my oc dir nor in git repo so why is it included?

**Comment by JammingBen** [comment]
> Couldn't find path lib/private/legacy in neither my oc dir nor in git repo so why is it included?

This directory should definitely be available, see https://github.com/owncloud/core/tree/master/lib/private/legacy. Can you look again on your system? What about permissions, are they correct?

Also please try emptying your browser cache.

**Comment by stabledave** [comment]
ok
1. learned that git repo has case sensitive sorting, so I missed the legacy folder here, permissions is everything on www-data
2. anyways folder still missing in 10.8 owncloud server dir
3. checked 10.8 backup dir before dist upgrade, **also** no legacy folder, but was working for ~3 months
4. found the .bz2, unpacked again, legacy folder **included**
5. copied unpacked legacy dir to lib/private, error gone, but same php error with another File missing (lib/private/Log.php)
6. did this with several other missing files until dirs were matching again
7. works again

so I just checked the most recent backup with 10.7 and all files (including lib/private/legacy) were there. All 10.8 backups were missing the same files. I can't explain how owncloud was working without the files if the error was old extraction. Other explanation is backup process deleted the files not only in working dir but also the backups on unmounted volumes.
Anyways closing because I think it's unlikely that owncloud deleted the files, some magic error on my side I don't see.
Thanks for the help
