### ISSUE TITLE
Deleting versioned file with disabled trashbin causes exception

### ISSUE THREAD

**Issue by IljaN** [owncloud/core#39555]
### Steps to reproduce
1. Checkout master
2. ./occ a:d files_trashbin
3. Login in webui as user admin
4. Create a txt file with a few versions
5. Delete the file

### Expected behaviour
File and all versions are deleted without issues.

### Actual behaviour
This exception is thrown for every version.
``
{"Exception":"OCP\\Files\\NotFoundException","Message":"\/admin\/files\/Drong\/sasasa.txt","Code":0,"Trace":"#0 \/home\/ilja\/code\/core\/lib\/private\/Files\/Node\/Folder.php(130): OC\\Files\\Node\\Root->get()\n#1 \/home\/ilja\/code\/core\/lib\/private\/Preview.php(1386): OC\\Files\\Node\\Folder->get()\n#2 \/home\/ilja\/code\/core\/lib\/private\/Preview.php(1368): OC\\Preview::post_delete()\n#3 \/home\/ilja\/code\/core\/lib\/private\/legacy\/hook.php(103): OC\\Preview::post_delete_versions()\n#4 \/home\/ilja\/code\/core\/apps\/files_versions\/lib\/Storage.php(275): OC_Hook::emit()\n#5 \/home\/ilja\/code\/core\/apps\/files_versions\/lib\/Hooks.php(75): OCA\\Files_Versions\\Storage::delete()\n#6 \/home\/ilja\/code\/core\/lib\/private\/legacy\/hook.php(103): OCA\\Files_Versions\\Hooks::remove_hook()\n#7 \/home\/ilja\/code\/core\/lib\/private\/Files\/View.php(1344): OC_Hook::emit()\n#8 \/home\/ilja\/code\/core\/lib\/private\/Files\/View.php(1269): OC\\Files\\View->runHooks()\n#9 \/home\/ilja\/code\/core\/lib\/private\/Files\/View.php(776): OC\\Files\\View->basicOperation()\n#10 \/home\/ilja\/code\/core\/lib\/public\/Events\/EventEmitterTrait.php(50): OC\\Files\\View->OC\\Files\\{closure}(*** sensitive parameters replaced ***)\n#11 \/home\/ilja\/code\/core\/lib\/private\/Files\/View.php(786): OC\\Files\\View->emittingCall()\n#12 \/home\/ilja\/code\/core\/apps\/dav\/lib\/Connector\/Sabre\/File.php(431): OC\\Files\\View->unlink()\n#13 \/home\/ilja\/code\/core\/lib\/composer\/sabre\/dav\/lib\/DAV\/Tree.php(179): OCA\\DAV\\Connector\\Sabre\\File->delete()\n#14 \/home\/ilja\/code\/core\/lib\/composer\/sabre\/dav\/lib\/DAV\/CorePlugin.php(281): Sabre\\DAV\\Tree->delete()\n#15 \/home\/ilja\/code\/core\/lib\/composer\/sabre\/event\/lib\/WildcardEmitterTrait.php(89): Sabre\\DAV\\CorePlugin->httpDelete()\n#16 \/home\/ilja\/code\/core\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(472): Sabre\\DAV\\Server->emit()\n#17 \/home\/ilja\/code\/core\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(253): Sabre\\DAV\\Server->invokeMethod()\n#18 \/home\/ilja\/code\/core\/apps\/dav\/lib\/Server.php(345): Sabre\\DAV\\Server->start()\n#19 \/home\/ilja\/code\/core\/apps\/dav\/appinfo\/v2\/remote.php(31): OCA\\DAV\\Server->exec()\n#20 \/home\/ilja\/code\/core\/remote.php(165): require_once('\/home\/ilja\/code...')\n#21 {main}","File":"\/home\/ilja\/code\/core\/lib\/private\/Files\/Node\/Root.php","Line":197}
``

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
PHP

**Database:**
SQLite

**PHP version:**
7.4
**ownCloud version:** (see ownCloud admin page)
 61173b13edf9c513bc1d1c2d4de772687b0b0a03

**Updated from an older ownCloud or fresh install:**
fresh

**Where did you install ownCloud from:**
git

**Comment by IljaN** [comment]
Duplicates https://github.com/owncloud/core/issues/25287
