### ISSUE TITLE
Interner Serverfehler Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.

### ISSUE THREAD

**Issue by M-Stenzel** [owncloud/core#39750]
Hi team,

I am trying to open the landing page of owncloud - this fails miserably. Instead I receive:

**Interner Serverfehler
Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.

Bitte wende dich an den Serveradministrator, sollte dieser Fehler mehrfach auftreten und füge deiner Anfrage die unten stehenden technischen Details bei.

Weitere Details können im [Serverprotokoll](https://doc.owncloud.com/server/10.9/go.php?to=admin-logfiles) gefunden werden.**

**My browser logs tells me:**

       
GET https://www.xy-space.de/owncloud/index.php/login 500 (Internal Server Error)
jquery-migrate.min.js?v=821b54ae0f373a0da9f939fc068b77fb:2 JQMIGRATE: Migrate is installed, version 1.4.0
shareconfigmodel.js?v=821b54ae0f373a0da9f939fc068b77fb:24 
        
Uncaught ReferenceError: oc_appconfig is not defined
    at shareconfigmodel.js?v=821b54ae0f373a0da9f939fc068b77fb:24:33
    at shareconfigmodel.js?v=821b54ae0f373a0da9f939fc068b77fb:212:3
(anonym) @ shareconfigmodel.js?v=821b54ae0f373a0da9f939fc068b77fb:24
(anonym) @ shareconfigmodel.js?v=821b54ae0f373a0da9f939fc068b77fb:212
files_mediaviewer_init.js?v=821b54ae0f373a0da9f939fc068b77fb:1 
        
Uncaught TypeError: Cannot read properties of undefined (reading 'enabledPreviewProviders')
    at Object.473 (files_mediaviewer_init.js?v=821b54ae0f373a0da9f939fc068b77fb:1:115)
    at r (files_mediaviewer_init.js?v=821b54ae0f373a0da9f939fc068b77fb:1:1585)
    at files_mediaviewer_init.js?v=821b54ae0f373a0da9f939fc068b77fb:1:1823
    at files_mediaviewer_init.js?v=821b54ae0f373a0da9f939fc068b77fb:1:2536
473 @ files_mediaviewer_init.js?v=821b54ae0f373a0da9f939fc068b77fb:1
r @ files_mediaviewer_init.js?v=821b54ae0f373a0da9f939fc068b77fb:1
(anonym) @ files_mediaviewer_init.js?v=821b54ae0f373a0da9f939fc068b77fb:1
(anonym) @ files_mediaviewer_init.js?v=821b54ae0f373a0da9f939fc068b77fb:1

**The owncloud log tells me:**

{"reqId":"cPa6t7Zae0I2cgcVZzaA","level":3,"time":"2022-02-03T20:19:28+01:00","remoteAddr":"127.0.0.1","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/login","message":"session_name(): Cannot change session name when session is active at \/srv\/www\/htdocs\/owncloud\/lib\/private\/Session\/Internal.php#46"}
{"reqId":"cPa6t7Zae0I2cgcVZzaA","level":3,"time":"2022-02-03T20:19:28+01:00","remoteAddr":"127.0.0.1","user":"--","app":"index","method":"GET","url":"\/owncloud\/index.php\/login","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Memory.php(52): OC\\\\Session\\\\Memory->validateSession()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Security\\\/CSRF\\\/TokenStorage\\\/SessionStorage.php(63): OC\\\\Session\\\\Memory->set('requesttoken', 'fi\\\/LsFO98xAyuYw...')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Security\\\/CSRF\\\/CsrfTokenManager.php(59): OC\\\\Security\\\\CSRF\\\\TokenStorage\\\\SessionStorage->setToken('fi\\\/LsFO98xAyuYw...')\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/public\\\/Util.php(522): OC\\\\Security\\\\CSRF\\\\CsrfTokenManager->getToken(*** sensitive parameters replaced ***)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/Security\\\/SecurityMiddleware.php(144): OCP\\\\Util::callRegister()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/MiddlewareDispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\SecurityMiddleware->beforeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(86): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('LoginController', 'showLoginForm', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(927): OC\\\\Route\\\\Router->match('\\\/login')\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Memory.php\",\"Line\":120}"}

**My configuration as per occ config:list**

{
    "system": {
        "updatechecker": false,
        "trusted_domains": [
            "localhost",
            "localhost"
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/srv\/www\/htdocs\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "10.9.1.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "instanceid": "ocladtdxrgqr",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "loglevel": 1,
        "theme": "",
        "maintenance": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpport": "587",
        "integrity.excluded.files": [
            ".htaccess"
        ],
        "redis": {
            "host": "127.0.0.1",
            "port": "6380"
        },
        "allow_user_to_change_mail_address": ""
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.6.1",
            "signed": "true",
            "types": "filesystem"
        },
        "afterlogic": {
            "enabled": "no",
            "installed_version": "1.2.3",
            "signed": "true",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "3"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "yes",
            "installed_version": "0.2.0",
            "types": "filesystem"
        },
        "core": {
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "encryption_enabled": "yes",
            "installedat": "1516224015.6112",
            "lastcron": "1642535823",
            "lastupdateResult": "[]",
            "lastupdatedat": "0",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "umgmt_show_backend": "true",
            "umgmt_show_email": "true",
            "umgmt_show_is_enabled": "true",
            "umgmt_show_storage_location": "true",
            "vendor": "owncloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.7.0",
            "types": "filesystem"
        },
        "encryption": {
            "enabled": "yes",
            "installed_version": "1.5.1",
            "masterKeyId": "master_86cc07f1",
            "publicShareKeyId": "pubShare_86cc07f1",
            "recoveryKeyId": "recoveryKey_86cc07f1",
            "types": "filesystem",
            "useMasterKey": "1"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "filesystem"
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.5.2",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_mediaviewer": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "signed": "true",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "no",
            "installed_version": "1.0.1",
            "ocsid": "166049",
            "signed": "true",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.14.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.4.1",
            "signed": "true",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "no",
            "installed_version": "0.10.1",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "16.1.2",
            "signed": "true",
            "types": ""
        },
        "market": {
            "activity": "2.4.2",
            "enabled": "yes",
            "files_mediaviewer": "1.0.5",
            "files_pdfviewer": "1.0.1",
            "files_texteditor": "2.4.1",
            "gallery": "16.1.1",
            "installed_version": "0.6.2",
            "key": "",
            "market": "0.6.2",
            "onlyoffice": "6.4.3",
            "richdocuments": "2.6.0",
            "search_elastic": "2.0.0",
            "signed": "true",
            "templateeditor": "0.4.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.5.4",
            "types": "logging"
        },
        "onlyoffice": {
            "DocumentServerInternalUrl": "",
            "DocumentServerUrl": "https:\/\/www.xy-space.de\/onlyoffice\/",
            "StorageUrl": "",
            "customizationChat": "true",
            "customizationCompactHeader": "true",
            "customizationFeedback": "true",
            "customizationForcesave": "false",
            "customizationHelp": "true",
            "customizationReviewDisplay": "original",
            "customizationToolbarNoTabs": "false",
            "defFormats": "{\"csv\":\"true\",\"doc\":\"true\",\"docm\":\"true\",\"docx\":\"true\",\"dotx\":\"true\",\"epub\":\"true\",\"html\":\"true\",\"odp\":\"true\",\"ods\":\"true\",\"odt\":\"true\",\"otp\":\"true\",\"ots\":\"true\",\"ott\":\"true\",\"pdf\":\"true\",\"potm\":\"true\",\"potx\":\"true\",\"ppsm\":\"true\",\"ppsx\":\"true\",\"ppt\":\"true\",\"pptm\":\"true\",\"pptx\":\"true\",\"rtf\":\"true\",\"txt\":\"true\",\"xls\":\"true\",\"xlsm\":\"true\",\"xlsx\":\"true\",\"xltm\":\"true\",\"xltx\":\"true\"}",
            "demo": "{\"available\":false,\"enabled\":false,\"start\":{\"date\":\"2021-02-05 19:42:33.645493\",\"timezone_type\":3,\"timezone\":\"UTC\"}}",
            "editFormats": "{\"csv\":\"false\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"false\",\"rtf\":\"false\",\"txt\":\"false\"}",
            "enabled": "no",
            "groups": "[]",
            "installed_version": "6.4.3",
            "jwt_secret": "",
            "preview": "true",
            "sameTab": "false",
            "settings_error": "",
            "signed": "true",
            "types": "filesystem",
            "verify_peer_off": "true"
        },
        "phonetrack": {
            "enabled": "no",
            "installed_version": "0.2.8",
            "signed": "true",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "richdocuments": {
            "canonical_webroot": "",
            "doc_format": "odf",
            "edit_groups": "",
            "enabled": "no",
            "installed_version": "2.7.0",
            "menu_option": "true",
            "signed": "true",
            "types": "prevent_group_restriction",
            "wopi_url": "https:\/\/collabora.xy-space.de"
        },
        "search_elastic": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "scanExternalStorages": "1",
            "servers": "127.0.0.1:9200",
            "signed": "true",
            "types": "filesystem"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.4.0",
            "signed": "true",
            "types": ""
        },
        "updatenotification": {
            "core": "10.8.0",
            "enabled": "yes",
            "installed_version": "0.2.1",
            "types": ""
        }
    }
}

**apachectl -v**
Server version: Apache/2.4.52 (Linux/SUSE)

My apache logs do not show any owncloud related errors or warnings.

**sudo -u wwwrun ./occ check**
- no line - seems to be o. k.

**PHP installation**

[PHP 7.3.33 - phpinfo().pdf](https://github.com/owncloud/core/files/7997617/PHP.7.3.33.-.phpinfo.pdf)

My php log does not show any warnings or errors related to owncloud.

What could be the reason that the system fails?

Any clues? Thank you!

Martin.

**Comment by M-Stenzel** [comment]
This topic can be closed:

I further investigated and found out that sth. NEEDS to be wrong with php session/s.
So I replaced my apache php.ini with the default php.ini and the error went away.
By replacing I was able to login and now everything goes smoothly.

Martin.

P. S. One more thing: I should have posted here: https://central.owncloud.org
