### ISSUE TITLE
[QA] Moving a shared folder out of an external drive sometimes breaks sharing permanently

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39848]
Seen in server 10.9.1
* Admin creates (e.g. ) an SFTP mount and enables sharing.
* User testy enters the SFTP mount, creates an upload folder, with a public link (e.g.) for file drop
* Anonymous user can upload files through the link. OK.
* User testy moves the upload folder out of the SFTP mount.
* Anonymous user can no  longer upload files. BAD.
* User testy removes the public link, and creating a new public link on the upload folder.
* Still, the anonymous user gets an error on the new public link. BAD.
* User testy creates a subfolder insode upload, and creates a public link there.
* Again, the anonymous user gets an error on the new public link. BAD.

![image](https://user-images.githubusercontent.com/1108546/156562426-ce617cf4-334c-47ea-ac31-1af142f0a365.png)

Server log entry, when file drop fails:
```
{
  "reqId": "YiCuB1v1l1bTGHC4A01dQAAAAB4",
  "level": 0,
  "time": "2022-03-03T12:01:11+00:00",
  "remoteAddr": "80.139.83.98",
  "user": "--",
  "app": "webdav",
  "method": "PUT",
  "url": "/public.php/webdav/inksc.png",
  "message": "Exception: HTTP/1.1 404 Not Found: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/apps\\/dav\\/lib\\/Connector\\/Sabre\\/ServerFactory.php(156): {closure}(*** sensitive parameters replaced ***)\\n#1 \\/var\\/www\\/owncloud\\/lib\\/composer\\/sabre\\/event\\/lib\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ServerFactory->OCA\\\\DAV\\\\Connector\\\\Sabre\\\\{closure}(*** sensitive parameters replaced ***)\\n#2 \\/var\\/www\\/owncloud\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(456): Sabre\\\\DAV\\\\Server->emit()\\n#3 \\/var\\/www\\/owncloud\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#4 \\/var\\/www\\/owncloud\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n#5 \\/var\\/www\\/owncloud\\/apps\\/dav\\/appinfo\\/v1\\/publicwebdav.php(105): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\/var\\/www\\/owncloud\\/public.php(75): require_once('\\/var\\/www\\/ownclo...')\\n#7 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/apps\\/dav\\/appinfo\\/v1\\/publicwebdav.php\",\"Line\":85}"
}

**Comment by jnweiger** [comment]
Weird. This happens only with one firefox user account. Does it depend on a poisoned cookie?

[failing_drop.har.zip](https://github.com/owncloud/core/files/8177887/failing_drop.har.zip)

**Comment by jnweiger** [comment]
Cannot reproduce with 10.11.0-beta.1

**Comment by jnweiger** [comment]
Cannot reproduce with 10.12.0-rc.2
Closing.
