### ISSUE TITLE
[QA] automatic update fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40156]
Seen while testing the updater server for 10.10.0

![image](https://user-images.githubusercontent.com/1108546/174738347-12edf3db-33ac-4e5b-9220-ecf4426e4ec4.png)

```
{"reqId":"YrEDTyEfgXEsPm3SPCvN6wAAAAI","level":3,"time":"2022-06-20T23:31:28+00:00","remoteAddr":"65.108.61.163","user":"--","app":"index","method":"POST","url":"\/index.php\/occ\/upgrade","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OC_Mount_Config' not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(399): include_once()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(151): OC\\\\Route\\\\Router->requireRouteFile()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(279): OC\\\\Route\\\\Router->loadRoutes()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(931): OC\\\\Route\\\\Router->match()\\n#4 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/appinfo\\\/routes.php\",\"Line\":31}"}
```

Class OC_Mount_Config belongs to the files_external app.

Expected behaviour:

* 10.7.x updates smoothly to 10.8.0, which can then be updated to 10.0.0

Reproduced identical 
* using both updates.owncloud.com and a self-deployed updates server
* an ownCloud with mounted external storages and with files_external never enabled.
* when updating from the minimal community tar and the complete tar.

**Comment by jnweiger** [comment]
* The web UI then says

 Automatic updating is disabled in config.php. To upgrade your instance, please use the command line updater (occ upgrade).
 
 * `occ upgrade` succeeds.
 * 10.8.0.4 comes up, and announces that `owncloud 10.10.0 is available.

**Comment by pako81** [comment]
To be verified once latest version is available over the online updater.

**Comment by jnweiger** [comment]
In the enterprise theme, this web-updater should be disabled. Only a link to documentation should be shown.
See https://doc.owncloud.com/server/next/admin_manual/maintenance/upgrading/upgrade.html#upgrade-options

**Comment by IljaN** [comment]
@jnweiger What are the next steps here? Should we implement the suggestions?

**Comment by pako81** [comment]
Proposed something at https://github.com/owncloud/core/pull/40841
