### ISSUE TITLE
Docker Image fails with python exception NoneType has no attribute split

### ISSUE THREAD

**Issue by rayzorben** [owncloud/core#40399]
Latest docker image today.

When running (separate mariadb, separate redis) I get the following errors logged and container dies.

```
Start streaming logs:
Creating volume folders...
Creating hook folders...
Waiting for MySQL...
services are ready!
Waiting for Redis...
services are ready!
Removing custom folder...
Linking custom folder...
Removing config folder...
Linking config folder...
Writing config file...
Fixing base perms...
Fixing data perms...
Fixing hook perms...
Upgrading server database...
Console has to be executed with the user that owns the file config/config.php
Current user: www-data
Owner of config.php: root
Try adding 'sudo -u root ' to the beginning of the command (without the single quotes)
Console has to be executed with the user that owns the file config/config.php
Current user: www-data
Owner of config.php: root
Try adding 'sudo -u root ' to the beginning of the command (without the single quotes)
Writing objectstore config...
Writing php config...
Updating htaccess config...
Console has to be executed with the user that owns the file config/config.php
Current user: www-data
Owner of config.php: root
Try adding 'sudo -u root ' to the beginning of the command (without the single quotes)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/container/custom.py", line 860, in _stream_container_events_and_logs
    _stream_logs(container_client, resource_group_name, name, container_name, container_group.restart_policy)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/container/custom.py", line 814, in _stream_logs
    lines = log.content.split('\n')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by ho4ho** [comment]
Not issue directly by ownCloud but docker image, should go by https://github.com/owncloud-docker/server/issues ?

**Comment by rayzorben** [comment]
> Not issue directly by ownCloud but docker image, should go by https://github.com/owncloud-docker/server/issues ?

That page says to file issues at owncloud/core

**Comment by ho4ho** [comment]
Thinking this only if issue by ownCloud, but not by docker:
- Problem by docker container: https://github.com/owncloud-docker/server/issues
- Problem by ownCloud not by docker container: https://github.com/owncloud/core/issues
