### ISSUE TITLE
[QA] public links do not work with files_primary_s3

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40665]
Seen with core 10.12.0-rc.2

* Install server with files_primary_s3
* Create a public link. (file drop, read/write, read only does not matter.)
* paste the public link into a private browser window.
* An error occurs:
![grafik](https://user-images.githubusercontent.com/1108546/222854110-76033dd0-d450-46dd-850c-24d44b2c7824.png)

The log says:
```
{
  "reqId": "ZAJ-mnI5zr-f5hMlA2iXnQAAAAg",
  "level": 3,
  "time": "2023-03-03T23:15:38+00:00",
  "remoteAddr": "46.114.208.108",
  "user": "--",
  "app": "index",
  "method": "GET",
  "url": "/s/KuoxwuxY0uiyBkh",
  "message": "Exception: {
\"Exception\":\"Error\",
\"Message\":\"Call to a member function getFileInfo() on null\",
\"Code\":0,
\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/ObjectStore\\/ObjectStoreStorage.php(438): OC\\\\Files\\\\Filesystem::getFileInfo()\\n
#1 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/ObjectStore\\/ObjectStoreStorage.php(454): OC\\\\Files\\\\ObjectStore\\\\ObjectStoreStorage->getTotalUsedStorage()\\n
#2 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(335): OC\\\\Files\\\\ObjectStore\\\\ObjectStoreStorage->free_space()\\n
#3 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Availability.php(350): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->free_space()\\n
#4 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(335): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->free_space()\\n
#5 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(335): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->free_space()\\n
#6 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(335): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->free_space()\\n
#7 \\/var\\/www\\/owncloud\\/apps\\/files_sharing\\/lib\\/Controllers\\/ShareController.php(353): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->free_space()\\n
#8 \\/var\\/www\\/owncloud\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(169): OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController->showShare()\\n
#9 \\/var\\/www\\/owncloud\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n
#10 \\/var\\/www\\/owncloud\\/lib\\/private\\/AppFramework\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n
#11 \\/var\\/www\\/owncloud\\/lib\\/public\\/AppFramework\\/App.php(131): OC\\\\AppFramework\\\\App::main()\\n
#12 \\/var\\/www\\/owncloud\\/core\\/routes.php(130): OCP\\\\AppFramework\\\\App->dispatch()\\n
#13 \\/var\\/www\\/owncloud\\/lib\\/private\\/Route\\/Router.php(344): OC\\\\Route\\\\Router::{closure}(*** sensitive parameters replaced ***)\\n
#14 \\/var\\/www\\/owncloud\\/lib\\/base.php(913): OC\\\\Route\\\\Router->match()\\n
#15 \\/var\\/www\\/owncloud\\/index.php(54): OC::handleRequest()\\n
#16 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Filesystem.php\",
\"Line\":1030}"
}
```

This only happens, when the public link is created in the primary_s3 storage. E.g. an SFTP external storage is not affected.

Expected behaviour: 
* public links should also work with files_primary_s3

This appears to be a regression. It is not reproducable with 10.11.0 and files_primary_s3

**Comment by jnweiger** [comment]
Workaround:
* Apply revert of https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/40389.diff
