### ISSUE TITLE
[QA] Creating a new google drive external storage mounts fails after upgrade to 10.12.1: `invalid token format`

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40777]
Seen with 10.12.1 and files_external 0.9.0 (coming from 10.11.0 and files_external 0.9.0)

* Have a google drive prepared with client id and client secret according to https://doc.owncloud.com/server/10.12/admin_manual/configuration/files/external_storage/google.html
* Start 10.11.0 and connect an external mount 'GoogleDrive' using these credentials.
* A red square appears and an error message 
![image](https://user-images.githubusercontent.com/1108546/236869628-b67c2009-c401-4edc-bf60-6f231dd60868.png)
```
{"reqId":"ZFkPI6tMLaBmHIzc1RaA8QAAABo","level":3,"time":"2023-05-08T15:02:59+00:00","remoteAddr":"46.114.213.58","user":"admin","app":"files_external","method":"POST","url":"\
/apps\/files_external\/globalstorages","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating Google storage failed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/w
ww\\\/owncloud\\\/lib\\\/private\\\/Files\\\/External\\\/LegacyUtil.php(203): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\Google->__construct()\\n#1 \\\/var\\\/www\\\/owncloud\
\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(253): OC\\\\Files\\\\External\\\\LegacyUtil::getBackendStatus()\\n#2 \\\/var\\\/www\\\/owncloud\\\/app
s\\\/files_external\\\/lib\\\/Controller\\\/GlobalStoragesController.php(119): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus()\\n#3 \\\/var\\\
/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->create()\\n#4 \\\/var\\\/ww
w\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#5 \\\/var\\\/www\\\/owncloud\\\
/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routi
ng\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routin
g\\\\RouteActionHandler->__invoke()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(54): O
C::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/Google.php\",\"Line\":86}"}
{"reqId":"o8LEDdOl3XBKYeZ6bERP","level":1,"time":"2023-05-08T15:05:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"--","url":"--","message":"Invalidating tokens o
lder than 2023-05-08T14:45:02+00:00"}
{"reqId":"ZFkPtUcEzIYnHAhBipJ3xQAAAAA","level":1,"time":"2023-05-08T15:05:25+00:00","remoteAddr":"46.114.213.58","user":"--","app":"OC\\User\\Session::loginInOwnCloud","method
":"POST","url":"\/login?redirect_url=%252Fsettings%252Fadmin%253Fsectionid%253Dstorage%2526code%253D4%252F0AbUR2VN9ol1hnodQB984i7QK-FViesUdnks9KAbNr6hFKd4pkkINV2wUQcYFAJUZQrKN
PA%2526scope%253Dhttps%253A%252F%252Fwww.googleapis.com%252Fauth%252Fdrive","message":"login admin using \"password\" login type"}
{"reqId":"ZFkPth7q@ajKi7ldW3zRiQAAAAw","level":3,"time":"2023-05-08T15:05:26+00:00","remoteAddr":"46.114.213.58","user":"admin","app":"files_external","method":"GET","url":"\/
apps\/files_external\/globalstorages\/5?testOnly=true","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating Google storage failed\",\"Code\":0,\"Trace\":\
"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/External\\\/LegacyUtil.php(203): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\Google->__construct()\\n#1 \\\/var\\\/
www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(253): OC\\\\Files\\\\External\\\\LegacyUtil::getBackendStatus()\\n#2 \\\/var\\\/www\\\
/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(307): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OCA\\\\Files_External\\\\Controller\\\\StoragesController->show()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/Google.php\",\"Line\":86}"}
{"reqId":"ZFkPzoAIYzIKtcvEyM0O8AAAABY","level":1,"time":"2023-05-08T15:05:51+00:00","remoteAddr":"46.114.213.58","user":"admin","app":"core","method":"PROPFIND","url":"\/remote.php\/dav\/files\/admin\/GoogleDrive","message":"cleaning 1 stray shared locks for files\/fff4f8c62b326d382d0fe8e8e5f3d3c2"}
```
* Ignore the error, and click 'Grant Access' - The google drive login page opens, the grant succeeds. OKayish
![image](https://user-images.githubusercontent.com/1108546/236872066-5195f473-4e62-4b60-a50e-22b56102d1a7.png)

* Upgrade the ownCloud instance to 10.12.1
   - `wget https://download.owncloud.com/server/stable/owncloud-complete-20230415.tar.bz2`
   - `occ maintenance:mode --on`
   - `cd /var/www`
   - `mv owncloud owncloud-10.11.0`
   - `tar xf owncloud-complete-20230415.tar.bz2`
   - `chown -R www-data. owncloud`
   - `mv owncloud-10.11.0/data/ owncloud`
   -  `occ upgrade`
   - `mv owncloud-10.11.0/config/config.* owncloud/config/`
   - `mv owncloud-10.11.0/apps-external/ owncloud/`
   - `occ maintenance:mode --off`
* Re-login to the ownCloud web UI, the Google Drive mount is still green, and works.
* Try create a second Google Drive mount. The grant seems to succeed, as before, but the red square on the left side remains. BAD.
![image](https://user-images.githubusercontent.com/1108546/236871952-8cd92d3c-b27a-4058-9614-49b5c96f0d6e.png)
----
* The log now has an `invalid token format` error:
```
{"reqId":"ZFkXatizoNA5Qgxbg-rYQQAAAAc","level":3,"time":"2023-05-08T15:38:18+00:00","remoteAddr":"46.114.213.58","user":"admin","app":"files_external","method
":"POST","url":"\/apps\/files_external\/globalstorages","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating Google storage failed\",\"Co
de\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/External\\\/LegacyUtil.php(203): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\Goo
gle->__construct()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(253): OC\\\\Files\\\\External\\\\L
egacyUtil::getBackendStatus()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/GlobalStoragesController.php(119): OCA\\\\File
s_External\\\\Controller\\\\StoragesController->updateStorageStatus()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.
php(169): OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->create()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/Google.php\",\"Line\":86}"}
{"reqId":"ZFkXegNtjvN2tIcm9ebWxgAAAAs","level":1,"time":"2023-05-08T15:38:34+00:00","remoteAddr":"46.114.213.58","user":"--","app":"OC\\User\\Session::loginInOwnCloud","method":"POST","url":"\/login?redirect_url=%252Fsettings%252Fadmin%253Fsectionid%253Dstorage%2526code%253D4%25252F0AbUR2VPXDS7l6iRINB9mUOvtkUbbi1CoOREeWj-RFjqZn4ySwK7wgV2eKGANffHKVE4BSw%2526scope%253Dhttps%25253A%25252F%25252Fwww.googleapis.com%25252Fauth%25252Fdrive","message":"login admin using \"password\" login type"}
{"reqId":"ZFkXe65vEeLmdAY-OYUWxgAAAA8","level":3,"time":"2023-05-08T15:38:35+00:00","remoteAddr":"46.114.213.58","user":"admin","app":"files_external","method":"GET","url":"\/apps\/files_external\/globalstorages\/3?testOnly=true","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating Google storage failed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/External\\\/LegacyUtil.php(203): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\Google->__construct()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(253): OC\\\\Files\\\\External\\\\LegacyUtil::getBackendStatus()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(307): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OCA\\\\Files_External\\\\Controller\\\\StoragesController->show()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/Google.php\",\"Line\":86}"}
{"reqId":"ZFkXew852fYz8o@NThBlVgAAAA4","level":3,"time":"2023-05-08T15:38:35+00:00","remoteAddr":"46.114.213.58","user":"admin","app":"files_external","method":"PUT","url":"\/apps\/files_external\/globalstorages\/3","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Invalid token format\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/Google.php(78): Google\\\\Client->setAccessToken()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/External\\\/LegacyUtil.php(203): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\Google->__construct()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(253): OC\\\\Files\\\\External\\\\LegacyUtil::getBackendStatus()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/GlobalStoragesController.php(189): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google\\\/apiclient\\\/src\\\/Client.php\",\"Line\":521}"}

```

Expected behaviour:
* New google drive external storages can be added after an upgrade to 10.12.1

Note:
* Not reproducable with a freshly installed 10.12.1 -- seems only the upgrade case is affected.

@pako81 @mmattel ?? Needs Releasnotes Update: Known issues ??

**Comment by mmattel** [comment]
> Needs Releasnotes Update: Known issues

Absolutely and hopefully soon a patch fix/workaround.

**Comment by pako81** [comment]
I don't think is related to the upgrade itself. In my tests it is also reproducible on freshly installed 10.12.1. It seems to fail on https://github.com/owncloud/core/blob/master/apps/files_external/lib/Lib/Storage/Google.php#L78 when calling `setAccessToken()`.

By adding logging statements there, following is returned:

```
{\"error\":\"invalid_grant\",\"error_description\":\"Malformed auth code.\"}"}
```

It seems related to the fact that the token needs to be urldecoded before being passed to that method. At least this is what most of the online searches are pointing at when searching for that error messages.

**Comment by mmattel** [comment]
Have you tried manually urldecode the token before using it in the webui? Does it success then?

**Comment by mmattel** [comment]
Note that I have tried to online urldecode my client secret and the result is identical to the entered string...?

**Comment by pako81** [comment]
Definitely a bug introduced with version 10.12.1 and most likely related to the update of the google/apiclient from version 2.12.6 to 2.13.1 --> https://github.com/owncloud/core/pull/40683

**Comment by pako81** [comment]
Replacing https://github.com/owncloud/core/blob/master/apps/files_external/ajax/oauth2.php#L41 with:

```
$client->setPrompt('consent');
```

will make Google Drive integration great again. Source: https://github.com/googleapis/google-api-php-client/pull/2275#issuecomment-1367424475

**Comment by pako81** [comment]
And I guess this requires the Google Drive storages to be again mounted in order for the tokens to get correctly generated.

**Comment by phil-davis** [comment]
That is very annoying - a minor version release should be backward-compatible (2.12 to 2.13).
And detailed unit (or acceptance) test coverage is probably quite low - it would require having a proper test Google drive set up to really know if the calls from oC10 through the Google client API to a Google drive really all still work as expected.

**Comment by pako81** [comment]
Proposed fix: https://github.com/owncloud/core/pull/40783

**Comment by pako81** [comment]
https://github.com/owncloud/core/pull/40783 has been merged.
