### ISSUE TITLE
When I try to delete a user as admin I get Java error in Chrome

### ISSUE THREAD

**Issue by Thidjs** [owncloud/core#41075]
### Steps to reproduce
1. Login as admin in Chrome browser
2. Go to user administration
3. Press the trashbin to delete a user

### Expected behaviour
A popup asks me if I'm sure, when I click yes the user should be deleted and the popup should disappear

### Actual behaviour
When I click the trashbin, the popup asks me if I'm sure, when I click yes the popup stays, on the background the user seems to be deleted (but isn't after refresh) and in Chrome developer console I receive this error (s);
```
Missing argument $row in OC.Notification.hide() call, caller needs to be adjusted to only dismiss its own notification
hide @ js.js?v=a2f92824cb14e445e556e3eccb29664e:1117

deleteHandler.js?v=a2f92824cb14e445e556e3eccb29664e:137 Uncaught TypeError: Cannot read properties of undefined (reading 'data')
    at Object.error (deleteHandler.js?v=a2f92824cb14e445e556e3eccb29664e:137:40)
    at j (jquery.js:3099:30)
    at Object.fireWith [as rejectWith] (jquery.js:3211:7)
    at x (jquery.js:8266:14)
    at Function.ajax (jquery.js:8170:6)
    at DeleteHandler.deleteEntry (deleteHandler.js?v=a2f92824cb14e445e556e3eccb29664e:125:11)
    at users.js?v=a2f92824cb14e445e556e3eccb29664e:371:25
    at HTMLDivElement.click (oc-dialogs.js?v=a2f92824cb14e445e556e3eccb29664e:286:9)
    at HTMLButtonElement.<anonymous> (jquery.ocdialog.js?v=a2f92824cb14e445e556e3eccb29664e:108:18)
    at HTMLButtonElement.dispatch (jquery.js:4435:9)
error @ deleteHandler.js?v=a2f92824cb14e445e556e3eccb29664e:137
j @ jquery.js:3099
fireWith @ jquery.js:3211
x @ jquery.js:8266
ajax @ jquery.js:8170
DeleteHandler.deleteEntry @ deleteHandler.js?v=a2f92824cb14e445e556e3eccb29664e:125
(anonymous) @ users.js?v=a2f92824cb14e445e556e3eccb29664e:371
click @ oc-dialogs.js?v=a2f92824cb14e445e556e3eccb29664e:286
(anonymous) @ jquery.ocdialog.js?v=a2f92824cb14e445e556e3eccb29664e:108
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121
```

### Server configuration
**Operating system**:
Linux Ubuntu 22.04

**Web server:**
Apache 2.4.52

**Database:**
MariaDB 10.6.12

**PHP version:**
7.4.33

**ownCloud version:** (see ownCloud admin page)
10.13.2 (stable)

**Updated from an older ownCloud or fresh install:**
I keep owncloud up to date

**Where did you install ownCloud from:**
APT

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'maintenance' => false,
  'updatechecker' => false,
  'instanceid' => 'xxxxxxxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'owncloud.xxxxxxxxxxxxx.nl',
  ),
  'datadirectory' => '/var/owncloud-data',
  'overwrite.cli.url' => 'https://owncloud.xxxxxxxxxxxx.nl',
  'dbtype' => 'mysql',
  'version' => '10.13.2.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'xxxxxxxxxxxxx',
  'dbpassword' => 'xxxxxxxxx',
  'allow_user_to_change_mail_address' => '',
  'logtimezone' => 'Europe/Amsterdam',
  'log_type' => 'syslog',
  'syslog_tag' => 'ownCloud',
  'log.syslog.format' => '[%reqId%][%remoteAddr%][%user%][%app%][%method%][%url%] %message%',
  'loglevel' => 2,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/owncloud/apps-external',
      'url' => '/apps-external',
      'writable' => true,
    ),
  ),
  'installed' => true,
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\APCu',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' =>
  array (
    'host' => '/var/run/redis/redis-server.sock',
    'port' => 0,
  ),
  'http.cookie.samesite' => 'None',
  'mail_domain' => 'xxxxxxxxxxxxx.nl',  
 'mail_from_address' => 'xxxxxxxxxxxxxxx',
  'mail_smtpmode' => 'php',
  'integrity.check.disabled' => false,
  'theme' => '',
  'debug' => false,
);
```

**List of activated apps:**
Enabled:
  - activity:
    - Version: 2.7.2
    - Path: /var/www/owncloud/apps/activity
  - comments:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/comments
  - configreport:
    - Version: 0.2.2
    - Path: /var/www/owncloud/apps/configreport
  - dav:
    - Version: 0.7.0
    - Path: /var/www/owncloud/apps/dav
  - diagnostics:
    - Version: 0.2.0
    - Path: /var/www/owncloud/apps/diagnostics
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/owncloud/apps/federation
  - files:
    - Version: 1.6.0
    - Path: /var/www/owncloud/apps/files
  - files_external:
    - Version: 0.9.0
    - Path: /var/www/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.5
    - Path: /var/www/owncloud/apps/files_mediaviewer
  - files_pdfviewer:
    - Version: 1.0.1
    - Path: /var/www/owncloud/apps/files_pdfviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/owncloud/apps/files_sharing
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.3.0
    - Path: /var/www/owncloud/apps/firstrunwizard
  - gallery:
    - Version: 16.1.2
    - Path: /var/www/owncloud/apps-external/gallery
  - market:
    - Version: 0.8.0
    - Path: /var/www/owncloud/apps/market
  - notifications:
    - Version: 0.6.0
    - Path: /var/www/owncloud/apps/notifications
  - oauth2:
    - Version: 0.6.1
    - Path: /var/www/owncloud/apps/oauth2
  - onlyoffice:
    - Version: 8.2.3
    - Path: /var/www/owncloud/apps-external/onlyoffice
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/systemtags
  - templateeditor:
    - Version: 0.4.0
    - Path: /var/www/owncloud/apps/templateeditor
  - updatenotification:
    - Version: 0.2.1
    - Path: /var/www/owncloud/apps/updatenotification

```

**Are you using encryption:** no

```
```

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows

### Logs
#### Web server error log
```
No web server errors
```

#### ownCloud log (data/owncloud.log)
```
No OwnCloud errors
```

#### Browser log
```
Insert your browser log here, this could for example include:

Included in Actual Behaviour
```

**Comment by DeepDiver1975** [comment]
Any error in the server logs?
