### ISSUE TITLE
Start-up issues on Debian Linux

### ISSUE THREAD

**Issue by mdziczkowski** [owncloud/core#41312]
# OS info

**OS**: Debian (codename: bookworm)
**PHP version**: 8.2

# Issue description

While startup:

-  it complains that the PHP version is above 8.0, but the earlier versions of PHP are treated as depreated and not secure
- after editing the `base.php` file to disable the complain, I recieved the crash output in the console as listed in bellow section

## Console output

**Note**: For security reason, the path to where the owncloud archive has become extracted has been trunchated.

```
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught Error: Class "OC\Session\Memory" not found in lib/private/Server.php:1161

Stack trace:
#0 lib/private/Server.php(832): OC\Server->getSession()
#1 lib/composer/pimple/pimple/src/Pimple/Container.php(122): OC\Server->OC\{closure}()
#2 lib/private/AppFramework/Utility/SimpleContainer.php(107): Pimple\Container->offsetGet()
#3 lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query()
#4 lib/private/Server.php(1643): OC\ServerContainer->query()
#5 lib/private/Server.php(740): OC\Server->getCsrfTokenManager()
#6 lib/composer/pimple/pimple/src/Pimple/Container.php(122): OC\Server->OC\{closure}()
#7 lib/private/AppFramework/Utility/SimpleContainer.php(107): Pimple\Container->offsetGet()
#8 lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query()
#9 lib/private/Server.php(1017): OC\ServerContainer->query()
#10 lib/private/Log/Owncloud.php(88): OC\Server->getRequest()
#11 lib/private/Log/Owncloud.php(67): OC\Log\Owncloud::writeExtra()
#12 lib/private/Log.php(403): OC\Log\Owncloud::write()
#13 lib/private/Log.php(210): OC\Log->log()
#14 lib/private/Log/ErrorHandler.php(78): OC\Log->error()
#15 lib/private/Session/Session.php(28): OC\Log\ErrorHandler::onError()
#16 lib/composer/composer/ClassLoader.php(571): include('...')
#17 lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#18 lib/private/Session/Memory.php(39): Composer\Autoload\ClassLoader->loadClass()
#19 lib/composer/composer/ClassLoader.php(571): include('...')
#20 lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#21 lib/private/Server.php(1161): Composer\Autoload\ClassLoader->loadClass()
#22 lib/kernel.php(600): OC\Server->getSession()
#23 lib/kernel.php(1071): OC::init()
#24 lib/base.php(21): require_once('...')
#25 console.php(52): require_once('...')
#26 occ(11): require_once('...')
#27 {main} in lib/private/Session/Session.php on line 28
```

**Comment by phil-davis** [comment]
ownCloud 10 core only supports PHP 7.4
If you want a version of PHP 7.4 that continues to have security patches applied, then contact support for information.

**Comment by mdziczkowski** [comment]
@phil-davis I have a question: why OwnCloud is focused on depreaced version of PHP ?

**Comment by phil-davis** [comment]
> why OwnCloud is focused on deprecated version of PHP ?

I am not responsible for that decision, so I can't comment.

**Comment by DeepDiver1975** [comment]
> why OwnCloud is focused on depreaced version of PHP ?

https://central.owncloud.org/t/announcement-owncloud-10-and-php-versions/40251
