### ISSUE TITLE
No marketplace connection: cURL error 7

### ISSUE THREAD

**Issue by zubanst** [owncloud/core#41348]
### Steps to reproduce
1. Fresh install owncloud server latest version, on CentOS Stream 9 in High Availability configurationm SE enabled
2. Server accessible through nginx proxy
3. At the first login after install, accessing the marketplace from the portal ends up with the following error on the bottom right of the screen: _No marketplace connection: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://marketplace.owncloud.com/_

### Expected behaviour
Access the market place

### Actual behaviour
Error on the bottom right of the screen: _No marketplace connection: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://marketplace.owncloud.com/_

### Server configuration
**Operating system**: CentOS Stream 9 SE

**Web server:** Apache/2.4.62 (CentOS Stream)

**Database:** mysql version10.15.0.2

**PHP version:** PHP 7.4.33 (cli) (built: Nov 27 2024 16:03:02) ( NTS )

**ownCloud version:** (see ownCloud admin page) 10.15.0.2

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:** Official website

**Signing status (ownCloud 9.0 and above):** https://www.cloudcreator.eu/owncloud/index.php/settings/integrity/failed 'No errors have been found.'

**The content of config/config.php:**
"instanceid": "oc6eimh705sw",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.35",
            "192.168.0.38",
            "www.cloudcreator.eu"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.0.35\/owncloud",
        "dbtype": "mysql",
        "version": "10.15.0.2",
        "dbname": "owncloud_db",
        "dbconnectionstring": "",
        "dbhost": "localhost:3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "allow_user_to_change_mail_address": "",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls"
    },
    "integritychecker": {
        "passing": true,
        "enabled": true,
        "result": []
    },
    "core": {
        "OC_Channel": "production",
        "backgroundjobs_mode": "cron",
        "enable_external_storage": "yes",
        "first_install_version": "10.15.0.2",
        "installedat": "1734996827.6617",
        "lastcron": "1735558203",
        "lastupdateResult": "[]",
        "lastupdatedat": "1735557931",
        "public_files": "files_sharing\/public.php",
        "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php"
    },

**List of activated apps:**

Enabled:
  - activity:
    - Version: 2.7.2
    - Path: /var/www/html/owncloud/apps/activity
  - comments:
    - Version: 0.3.0
    - Path: /var/www/html/owncloud/apps/comments
  - configreport:
    - Version: 0.3.0
    - Path: /var/www/html/owncloud/apps/configreport
  - dav:
    - Version: 0.7.0
    - Path: /var/www/html/owncloud/apps/dav
  - diagnostics:
    - Version: 0.2.1
    - Path: /var/www/html/owncloud/apps/diagnostics
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/html/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/html/owncloud/apps/federation
  - files:
    - Version: 1.6.0
    - Path: /var/www/html/owncloud/apps/files
  - files_external:
    - Version: 0.9.0
    - Path: /var/www/html/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.5
    - Path: /var/www/html/owncloud/apps/files_mediaviewer
  - files_pdfviewer:
    - Version: 1.0.2
    - Path: /var/www/html/owncloud/apps/files_pdfviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/html/owncloud/apps/files_sharing
  - files_texteditor:
    - Version: 2.6.1
    - Path: /var/www/html/owncloud/apps/files_texteditor
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/html/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/html/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.3.0
    - Path: /var/www/html/owncloud/apps/firstrunwizard
  - market:
    - Version: 0.9.0
    - Path: /var/www/html/owncloud/apps/market
  - notifications:
    - Version: 0.6.0
    - Path: /var/www/html/owncloud/apps/notifications
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/html/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/html/owncloud/apps/systemtags
  - updatenotification:
    - Version: 0.2.1
    - Path: /var/www/html/owncloud/apps/updatenotification

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 131.0.6778.205

**Operating system:** Windows 11

#### Web server error log
```
empty
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Z2nzV5U5A9NvXaR_c4ledAAAAAE","level":3,"time":"2024-12-23T23:33:43+00:00","remoteAddr":"192.168.0.7","user":"--","app":"mysql.setup","method":"POST","url":"\/owncloud\/index.php","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_zubanst\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'owncloud_user'@'localhost' for table 'user'"}
{"reqId":"Z2n2k5U5A9NvXaR_c4lezgAAABQ","level":3,"time":"2024-12-23T23:47:31+00:00","remoteAddr":"192.168.0.7","user":"zubanst","app":"core","method":"GET","url":"\/owncloud\/index.php\/cron","message":"Error while running background job (class: OCA\\Market\\CheckUpdateBackgroundJob, arguments: ): {\"Exception\":\"OCP\\\\App\\\\AppManagerException\",\"Message\":\"No marketplace connection: cURL error 7:  (see https:\\\/\\\/curl.haxx.se\\\/libcurl\\\/c\\\/libcurl-errors.html) for https:\\\/\\\/marketplace.owncloud.com\\\/api\\\/v1\\\/platform\\\/10.15.0\\\/apps.json\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/HttpService.php(177): OCA\\\\Market\\\\HttpService->httpGet()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/HttpService.php(293): OCA\\\\Market\\\\HttpService->queryData()\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/HttpService.php(92): OCA\\\\Market\\\\HttpService->getEntities()\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/MarketService.php(574): OCA\\\\Market\\\\HttpService->getApps()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/MarketService.php(366): OCA\\\\Market\\\\MarketService->getApps()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/MarketService.php(309): OCA\\\\Market\\\\MarketService->getAppInfo()\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/MarketService.php(274): OCA\\\\Market\\\\MarketService->getAvailableUpdateVersions()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/CheckUpdateBackgroundJob.php(86): OCA\\\\Market\\\\MarketService->getUpdates()\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(81): OCA\\\\Market\\\\CheckUpdateBackgroundJob->run()\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(63): OC\\\\BackgroundJob\\\\Job->execute()\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/Controller\\\/CronController.php(83): OC\\\\BackgroundJob\\\\TimedJob->execute()\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OC\\\\Core\\\\Controller\\\\CronController->run()\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/kernel.php(925): OC\\\\Route\\\\Router->match()\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(32): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/HttpService.php\",\"Line\":264}"}
{"reqId":"Z2n2k5U5A9NvXaR_c4lezgAAABQ","level":3,"time":"2024-12-23T23:47:31+00:00","remoteAddr":"192.168.0.7","user":"zubanst","app":"core","method":"GET","url":"\/owncloud\/index.php\/cron","message":"Caused by: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ConnectException\",\"Message\":\"cURL error 7:  (see https:\\\/\\\/curl.haxx.se\\\/libcurl\\\/c\\\/libcurl-errors.html) for https:\\\/\\\/marketplace.owncloud.com\\\/api\\\/v1\\\/platform\\\/10.15.0\\\/apps.json\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Handler\\\/CurlFactory.php(158): GuzzleHttp\\\\Handler\\\\CurlFactory::createRejection()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Handler\\\/CurlFactory.php(110): GuzzleHttp\\\\Handler\\\\CurlFactory::finishError()\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Handler\\\/CurlHandler.php(47): GuzzleHttp\\\\Handler\\\\CurlFactory::finish()\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Handler\\\/Proxy.php(28): GuzzleHttp\\\\Handler\\\\CurlHandler->__invoke()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Handler\\\/Proxy.php(48): GuzzleHttp\\\\Handler\\\\Proxy::GuzzleHttp\\\\Handler\\\\{closure}(*** sensitive parameters replaced ***)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/PrepareBodyMiddleware.php(35): GuzzleHttp\\\\Handler\\\\Proxy::GuzzleHttp\\\\Handler\\\\{closure}(*** sensitive parameters replaced ***)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Middleware.php(31): GuzzleHttp\\\\PrepareBodyMiddleware->__invoke()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RedirectMiddleware.php(71): GuzzleHttp\\\\Middleware::GuzzleHttp\\\\{closure}(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Middleware.php(66): GuzzleHttp\\\\RedirectMiddleware->__invoke()\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/HandlerStack.php(75): GuzzleHttp\\\\Middleware::GuzzleHttp\\\\{closure}(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(333): GuzzleHttp\\\\HandlerStack->__invoke()\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(169): GuzzleHttp\\\\Client->transfer()\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(189): GuzzleHttp\\\\Client->requestAsync()\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/ClientTrait.php(44): GuzzleHttp\\\\Client->request()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(184): GuzzleHttp\\\\Client->get()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/HttpService.php(245): OC\\\\Http\\\\Client\\\\Client->get()\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/HttpService.php(177): OCA\\\\Market\\\\HttpService->httpGet()\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/HttpService.php(293): OCA\\\\Market\\\\HttpService->queryData()\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/HttpService.php(92): OCA\\\\Market\\\\HttpService->getEntities()\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/MarketService.php(574): OCA\\\\Market\\\\HttpService->getApps()\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/MarketService.php(366): OCA\\\\Market\\\\MarketService->getApps()\\n#21 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/MarketService.php(309): OCA\\\\Market\\\\MarketService->getAppInfo()\\n#22 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/MarketService.php(274): OCA\\\\Market\\\\MarketService->getAvailableUpdateVersions()\\n#23 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/market\\\/lib\\\/CheckUpdateBackgroundJob.php(86): OCA\\\\Market\\\\MarketService->getUpdates()\\n#24 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(81): OCA\\\\Market\\\\CheckUpdateBackgroundJob->run()\\n#25 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(63): OC\\\\BackgroundJob\\\\Job->execute()\\n#26 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/Controller\\\/CronController.php(83): OC\\\\BackgroundJob\\\\TimedJob->execute()\\n#27 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OC\\\\Core\\\\Controller\\\\CronController->run()\\n#28 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#29 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#30 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#31 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#32 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/kernel.php(925): OC\\\\Route\\\\Router->match()\\n#33 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(32): OC::handleRequest()\\n#34 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Handler\\\/CurlFactory.php\",\"Line\":210}"}
{"reqId":"Z2n5-NqROPNpkYQ4VVF5IgAAAIc","level":2,"time":"2024-12-24T00:02:00+00:00","remoteAddr":"192.168.0.38","user":"--","app":"core","method":"GET","url":"\/owncloud\/","message":"Trusted domain error. \"192.168.0.38\" tried to access using \"www.cloudcreator.eu\" as host."}
{"reqId":"Z2n5-Pt_RVytcgiVhAheSgAAAEY","level":2,"time":"2024-12-24T00:02:00+00:00","remoteAddr":"192.168.0.38","user":"--","app":"core","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=4c7c3d25e1468256753eab065694eb68","message":"Trusted domain error. \"192.168.0.38\" tried to access using \"www.cloudcreator.eu\" as host."}

```

#### Browser log
```
[www.cloudcreator.eu.har.zip](https://github.com/user-attachments/files/18274487/www.cloudcreator.eu.har.zip)

```

**Comment by iasdeoupxe** [comment]
> 3\. _No marketplace connection: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://marketplace.owncloud.com/_

```
CURLE_COULDNT_CONNECT (7)

Failed to connect() to host or proxy. 
```

Doesn't sound like a problem / bug / issue in ownCloud so probably could be closed.

**Comment by DeepDiver1975** [comment]
Please make sure the server has proper Internet connection. 
Indeed looks like a setup issue or the marketplace was temporary not available.

**Comment by zubanst** [comment]
How could you close an issue so easily? How could you suspect I don't have internet connection? How do you think the HA system was installed without internet connection. This is a poor support, so I need to reopen the case.

**Comment by iasdeoupxe** [comment]
@zubanst AFAICT there is no support here, only bug handling and this is clearly none in ownCloud. Installation/configuration support is given at https://central.owncloud.org/ by the community.

**Comment by zubanst** [comment]
For me this is a bug, reason why I opened the ticket, just it was dismissed in a finger clap. I provided all the details and described the issue. For you, this is a internet connection issue? Here is the curl result in command line:
[root@node1 ~]# curl https://marketplace.owncloud.com/
<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta content="IE=edge" http-equiv="X-UA-Compatible"><title>Marketplace</title><link rel="shortcut icon" href="/favicon.png"><link rel="apple-touch-icon-precomposed" href="/favicon.png"><link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"><link href="https://fonts.googleapis.com/css?family=Roboto:200,400,900" rel="stylesheet"><link href="/css/index.css" rel="stylesheet"><script type="text/javascript">var _paq = _paq || [];
                        _paq.push(['trackPageView']);
                        _paq.push(['enableLinkTracking']);
                        (function() {
                                var u="https://piwik.owncloud.com/";
                                _paq.push(['setTrackerUrl', u+'piwik.php']);
                                _paq.push(['setSiteId', '3']);
                                var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
                                g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
                        })();</script></head><body><noscript><p><img src="https://piwik.owncloud.com/piwik.php?idsite=3&rec=1" style="border:0;"></p></noscript><div id="app"></div><script src="/js/index.js"></script></body></html>

Best regards.

**Comment by iasdeoupxe** [comment]
Posted `cURL error 7` from the PHP curl library (which is something completely different then the command line `curl`client) clearly shows that this is a network / connectivity issue and NOT a bug in ownCloud.

Support for such system relevant problems is given by the community in the community forums.

**Comment by zubanst** [comment]
It is, but it proves the server has internet connection. Now, that the issue might be in the php environment on the CentOS stream, I'll check that.
