### ISSUE TITLE
memcached issues

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#6074]
1. the server to connect to is not configurable
2. memcached is used even if no memcached server is available/down
3. tests indicate issue for the case described in 2.

````
/usr/bin/php /tmp/ide-phpunit.php --configuration /home/deepdiver/Development/ownCloud/core/tests/phpunit-autotest.xml Test\Memcache\Memcached /home/deepdiver/Development/ownCloud/core/tests/lib/memcache/memcached.php
Testing started at 23:59 ...
PHPUnit 3.7.21 by Sebastian Bergmann.

Configuration read from /home/deepdiver/Development/ownCloud/core/tests/phpunit-autotest.xml


PHPUnit_Framework_ExpectationFailedException : Failed asserting that false is true.
#0 /usr/share/php/PHPUnit/Framework/Constraint.php(91): PHPUnit_Framework_Constraint->fail(false, '')
#1 /usr/share/php/PHPUnit/Framework/Assert.php(2134): PHPUnit_Framework_Constraint->evaluate(false, '')
#2 /usr/share/php/PHPUnit/Framework/Assert.php(888): PHPUnit_Framework_Assert::assertThat(false, Object(PHPUnit_Framework_Constraint_IsTrue), '')
#3 /home/deepdiver/Development/ownCloud/core/tests/lib/memcache/cache.php(16): PHPUnit_Framework_Assert::assertTrue(false)
#4 [internal function]: Test\Memcache\Cache->testExistsAfterSet()
#5 /usr/share/php/PHPUnit/Framework/TestCase.php(976): ReflectionMethod->invokeArgs(Object(Test\Memcache\Memcached), Array)
#6 /usr/share/php/PHPUnit/Framework/TestCase.php(831): PHPUnit_Framework_TestCase->runTest()
#7 /usr/share/php/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#8 /usr/share/php/PHPUnit/Framework/TestCase.php(776): PHPUnit_Framework_TestResult->run(Object(Test\Memcache\Memcached))
#9 /usr/share/php/PHPUnit/Framework/TestSuite.php(775): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#10 /usr/share/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Test\Memcache\Memcached), Object(PHPUnit_Framework_TestResult))
#11 /usr/share/php/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#12 /usr/share/php/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#13 /tmp/ide-phpunit.php(268): PHPUnit_TextUI_Command->run(Array, true)
#14 /tmp/ide-phpunit.php(506): IDE_Base_PHPUnit_TextUI_Command::main()
#15 {main}

PHPUnit_Framework_ExpectationFailedException : Failed asserting that null matches expected 'bar'.
Expected :bar
Actual   :null
 <Click to see difference>

#0 /usr/share/php/PHPUnit/Framework/Assert.php(2134): PHPUnit_Framework_Constraint_IsEqual->evaluate(NULL, '')
#1 /usr/share/php/PHPUnit/Framework/Assert.php(475): PHPUnit_Framework_Assert::assertThat(NULL, Object(PHPUnit_Framework_Constraint_IsEqual), '')
#2 /home/deepdiver/Development/ownCloud/core/tests/lib/memcache/cache.php(22): PHPUnit_Framework_Assert::assertEquals('bar', NULL)
#3 [internal function]: Test\Memcache\Cache->testGetAfterSet()
#4 /usr/share/php/PHPUnit/Framework/TestCase.php(976): ReflectionMethod->invokeArgs(Object(Test\Memcache\Memcached), Array)
#5 /usr/share/php/PHPUnit/Framework/TestCase.php(831): PHPUnit_Framework_TestCase->runTest()
#6 /usr/share/php/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#7 /usr/share/php/PHPUnit/Framework/TestCase.php(776): PHPUnit_Framework_TestResult->run(Object(Test\Memcache\Memcached))
#8 /usr/share/php/PHPUnit/Framework/TestSuite.php(775): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#9 /usr/share/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Test\Memcache\Memcached), Object(PHPUnit_Framework_TestResult))
#10 /usr/share/php/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#11 /usr/share/php/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#12 /tmp/ide-phpunit.php(268): PHPUnit_TextUI_Command->run(Array, true)
#13 /tmp/ide-phpunit.php(506): IDE_Base_PHPUnit_TextUI_Command::main()
#14 {main}

PHPUnit_Framework_Error_Warning : Invalid argument supplied for foreach()
#0 /home/deepdiver/Development/ownCloud/core/lib/private/memcache/memcached.php(64): PHPUnit_Util_ErrorHandler::handleError(2, 'Invalid argumen...', '/home/deepdiver...', 64, Array)
#1 /home/deepdiver/Development/ownCloud/core/tests/lib/memcache/cache.php(55): OC\Memcache\Memcached->clear()
#2 /usr/share/php/PHPUnit/Framework/TestCase.php(863): Test\Memcache\Cache->tearDown()
#3 /usr/share/php/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#4 /usr/share/php/PHPUnit/Framework/TestCase.php(776): PHPUnit_Framework_TestResult->run(Object(Test\Memcache\Memcached))
#5 /usr/share/php/PHPUnit/Framework/TestSuite.php(775): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#6 /usr/share/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Test\Memcache\Memcached), Object(PHPUnit_Framework_TestResult))
#7 /usr/share/php/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#8 /usr/share/php/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#9 /tmp/ide-phpunit.php(268): PHPUnit_TextUI_Command->run(Array, true)
#10 /tmp/ide-phpunit.php(506): IDE_Base_PHPUnit_TextUI_Command::main()
#11 {main}

PHPUnit_Framework_ExpectationFailedException : Failed asserting that null matches expected 'bar'.
Expected :bar
Actual   :null
 <Click to see difference>

#0 /usr/share/php/PHPUnit/Framework/Assert.php(2134): PHPUnit_Framework_Constraint_IsEqual->evaluate(NULL, '')
#1 /usr/share/php/PHPUnit/Framework/Assert.php(475): PHPUnit_Framework_Assert::assertThat(NULL, Object(PHPUnit_Framework_Constraint_IsEqual), '')
#2 /home/deepdiver/Development/ownCloud/core/tests/lib/memcache/cache.php(33): PHPUnit_Framework_Assert::assertEquals('bar', NULL)
#3 [internal function]: Test\Memcache\Cache->testArrayAccessSet()
#4 /usr/share/php/PHPUnit/Framework/TestCase.php(976): ReflectionMethod->invokeArgs(Object(Test\Memcache\Memcached), Array)
#5 /usr/share/php/PHPUnit/Framework/TestCase.php(831): PHPUnit_Framework_TestCase->runTest()
#6 /usr/share/php/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#7 /usr/share/php/PHPUnit/Framework/TestCase.php(776): PHPUnit_Framework_TestResult->run(Object(Test\Memcache\Memcached))
#8 /usr/share/php/PHPUnit/Framework/TestSuite.php(775): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#9 /usr/share/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Test\Memcache\Memcached), Object(PHPUnit_Framework_TestResult))
#10 /usr/share/php/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#11 /usr/share/php/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#12 /tmp/ide-phpunit.php(268): PHPUnit_TextUI_Command->run(Array, true)
#13 /tmp/ide-phpunit.php(506): IDE_Base_PHPUnit_TextUI_Command::main()
#14 {main}

PHPUnit_Framework_ExpectationFailedException : Failed asserting that null matches expected 'bar'.
Expected :bar
Actual   :null
 <Click to see difference>

#0 /usr/share/php/PHPUnit/Framework/Assert.php(2134): PHPUnit_Framework_Constraint_IsEqual->evaluate(NULL, '')
#1 /usr/share/php/PHPUnit/Framework/Assert.php(475): PHPUnit_Framework_Assert::assertThat(NULL, Object(PHPUnit_Framework_Constraint_IsEqual), '')
#2 /home/deepdiver/Development/ownCloud/core/tests/lib/memcache/cache.php(38): PHPUnit_Framework_Assert::assertEquals('bar', NULL)
#3 [internal function]: Test\Memcache\Cache->testArrayAccessGet()
#4 /usr/share/php/PHPUnit/Framework/TestCase.php(976): ReflectionMethod->invokeArgs(Object(Test\Memcache\Memcached), Array)
#5 /usr/share/php/PHPUnit/Framework/TestCase.php(831): PHPUnit_Framework_TestCase->runTest()
#6 /usr/share/php/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#7 /usr/share/php/PHPUnit/Framework/TestCase.php(776): PHPUnit_Framework_TestResult->run(Object(Test\Memcache\Memcached))
#8 /usr/share/php/PHPUnit/Framework/TestSuite.php(775): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#9 /usr/share/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Test\Memcache\Memcached), Object(PHPUnit_Framework_TestResult))
#10 /usr/share/php/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#11 /usr/share/php/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#12 /tmp/ide-phpunit.php(268): PHPUnit_TextUI_Command->run(Array, true)
#13 /tmp/ide-phpunit.php(506): IDE_Base_PHPUnit_TextUI_Command::main()
#14 {main}

PHPUnit_Framework_ExpectationFailedException : Failed asserting that false is true.
#0 /usr/share/php/PHPUnit/Framework/Constraint.php(91): PHPUnit_Framework_Constraint->fail(false, '')
#1 /usr/share/php/PHPUnit/Framework/Assert.php(2134): PHPUnit_Framework_Constraint->evaluate(false, '')
#2 /usr/share/php/PHPUnit/Framework/Assert.php(888): PHPUnit_Framework_Assert::assertThat(false, Object(PHPUnit_Framework_Constraint_IsTrue), '')
#3 /home/deepdiver/Development/ownCloud/core/tests/lib/memcache/cache.php(44): PHPUnit_Framework_Assert::assertTrue(false)
#4 [internal function]: Test\Memcache\Cache->testArrayAccessExists()
#5 /usr/share/php/PHPUnit/Framework/TestCase.php(976): ReflectionMethod->invokeArgs(Object(Test\Memcache\Memcached), Array)
#6 /usr/share/php/PHPUnit/Framework/TestCase.php(831): PHPUnit_Framework_TestCase->runTest()
#7 /usr/share/php/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#8 /usr/share/php/PHPUnit/Framework/TestCase.php(776): PHPUnit_Framework_TestResult->run(Object(Test\Memcache\Memcached))
#9 /usr/share/php/PHPUnit/Framework/TestSuite.php(775): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#10 /usr/share/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Test\Memcache\Memcached), Object(PHPUnit_Framework_TestResult))
#11 /usr/share/php/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#12 /usr/share/php/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#13 /tmp/ide-phpunit.php(268): PHPUnit_TextUI_Command->run(Array, true)
#14 /tmp/ide-phpunit.php(506): IDE_Base_PHPUnit_TextUI_Command::main()
#15 {main}

PHPUnit_Framework_Error_Warning : Invalid argument supplied for foreach()
#0 /home/deepdiver/Development/ownCloud/core/lib/private/memcache/memcached.php(64): PHPUnit_Util_ErrorHandler::handleError(2, 'Invalid argumen...', '/home/deepdiver...', 64, Array)
#1 /home/deepdiver/Development/ownCloud/core/tests/lib/memcache/cache.php(55): OC\Memcache\Memcached->clear()
#2 /usr/share/php/PHPUnit/Framework/TestCase.php(863): Test\Memcache\Cache->tearDown()
#3 /usr/share/php/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#4 /usr/share/php/PHPUnit/Framework/TestCase.php(776): PHPUnit_Framework_TestResult->run(Object(Test\Memcache\Memcached))
#5 /usr/share/php/PHPUnit/Framework/TestSuite.php(775): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#6 /usr/share/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Test\Memcache\Memcached), Object(PHPUnit_Framework_TestResult))
#7 /usr/share/php/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#8 /usr/share/php/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#9 /tmp/ide-phpunit.php(268): PHPUnit_TextUI_Command->run(Array, true)
#10 /tmp/ide-phpunit.php(506): IDE_Base_PHPUnit_TextUI_Command::main()
#11 {main}

PHPUnit_Framework_ExpectationFailedException : Failed asserting that false is true.
#0 /usr/share/php/PHPUnit/Framework/Constraint.php(91): PHPUnit_Framework_Constraint->fail(false, '')
#1 /usr/share/php/PHPUnit/Framework/Assert.php(2134): PHPUnit_Framework_Constraint->evaluate(false, '')
#2 /usr/share/php/PHPUnit/Framework/Assert.php(888): PHPUnit_Framework_Assert::assertThat(false, Object(PHPUnit_Framework_Constraint_IsTrue), '')
#3 /home/deepdiver/Development/ownCloud/core/tests/lib/cache.php(27): PHPUnit_Framework_Assert::assertTrue(false)
#4 [internal function]: Test_Cache->testSimple()
#5 /usr/share/php/PHPUnit/Framework/TestCase.php(976): ReflectionMethod->invokeArgs(Object(Test\Memcache\Memcached), Array)
#6 /usr/share/php/PHPUnit/Framework/TestCase.php(831): PHPUnit_Framework_TestCase->runTest()
#7 /usr/share/php/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#8 /usr/share/php/PHPUnit/Framework/TestCase.php(776): PHPUnit_Framework_TestResult->run(Object(Test\Memcache\Memcached))
#9 /usr/share/php/PHPUnit/Framework/TestSuite.php(775): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#10 /usr/share/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Test\Memcache\Memcached), Object(PHPUnit_Framework_TestResult))
#11 /usr/share/php/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#12 /usr/share/php/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#13 /tmp/ide-phpunit.php(268): PHPUnit_TextUI_Command->run(Array, true)
#14 /tmp/ide-phpunit.php(506): IDE_Base_PHPUnit_TextUI_Command::main()
#15 {main}

PHPUnit_Framework_Error_Warning : Invalid argument supplied for foreach()
#0 /home/deepdiver/Development/ownCloud/core/lib/private/memcache/memcached.php(64): PHPUnit_Util_ErrorHandler::handleError(2, 'Invalid argumen...', '/home/deepdiver...', 64, Array)
#1 /home/deepdiver/Development/ownCloud/core/tests/lib/cache.php(57): OC\Memcache\Memcached->clear('1_')
#2 [internal function]: Test_Cache->testClear()
#3 /usr/share/php/PHPUnit/Framework/TestCase.php(976): ReflectionMethod->invokeArgs(Object(Test\Memcache\Memcached), Array)
#4 /usr/share/php/PHPUnit/Framework/TestCase.php(831): PHPUnit_Framework_TestCase->runTest()
#5 /usr/share/php/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#6 /usr/share/php/PHPUnit/Framework/TestCase.php(776): PHPUnit_Framework_TestResult->run(Object(Test\Memcache\Memcached))
#7 /usr/share/php/PHPUnit/Framework/TestSuite.php(775): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#8 /usr/share/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Test\Memcache\Memcached), Object(PHPUnit_Framework_TestResult))
#9 /usr/share/php/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#10 /usr/share/php/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#11 /tmp/ide-phpunit.php(268): PHPUnit_TextUI_Command->run(Array, true)
#12 /tmp/ide-phpunit.php(506): IDE_Base_PHPUnit_TextUI_Command::main()
#13 {main}


Time: 0 seconds, Memory: 8.50Mb


FAILURES!
Tests: 9, Assertions: 13, Failures: 6, Errors: 3.

Process finished with exit code 2

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 What do you suggest?

I'll wrap my brain around this in 8.1

**Comment by DeepDiver1975** [comment]
> Should we close this and create a ticket for "Do not use caches unless configured", for all caches?

yes @bantu please take care of this - THX

**Comment by bantu** [comment]
@DeepDiver1975 I believe https://github.com/owncloud/core/pull/13368#issuecomment-70432545 takes care of that now.
