### ISSUE TITLE
RouteNotFoundException once after app deactivation 

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#8361]
I got following messages once after app deactivation (music and news have been disabled) It seems that the apps are loaded when they get deactivated. (looks like the navigation build step)

```
{"app":"index","message":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException: Route \"music_index\" does not exist.","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #1 \/srv\/http\/core\/lib\/private\/urlgenerator.php(41): OC\\Route\\Router->generate('music_index', Array)","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #2 \/srv\/http\/core\/lib\/private\/helper.php(44): OC\\URLGenerator->linkToRoute('music_index', Array)","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #3 \/srv\/http\/core\/lib\/public\/util.php(211): OC_Helper::linkToRoute('music_index', Array)","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #4 \/srv\/http\/core\/apps\/music\/appframework\/core\/api.php(239): OCP\\Util::linkToRoute('music_index', Array)","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #5 \/srv\/http\/core\/apps\/music\/appinfo\/app.php(41): OCA\\Music\\AppFramework\\Core\\API->linkToRoute('music_index')","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #6 \/srv\/http\/core\/lib\/private\/app.php(317): require('\/srv\/http\/core\/...')","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #7 \/srv\/http\/core\/settings\/ajax\/navigationdetect.php(9): OC_App::getAppNavigationEntries('music')","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #8 \/srv\/http\/core\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/srv\/http\/core\/...')","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #9 [internal function]: __lambda_func(Array)","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #10 \/srv\/http\/core\/lib\/private\/route\/router.php(206): call_user_func('\\x00lambdabda_2, Array)","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #11 \/srv\/http\/core\/lib\/base.php(744): OC\\Route\\Router->match('\/settings\/ajax\/...')","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #12 \/srv\/http\/core\/index.php(28): OC::handleRequest()","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Exception: #13 {main}","level":4,"time":"2014-04-25T15:25:46+00:00"}
{"app":"index","message":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException: Route \"news.page.index\" does not exist.","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #1 \/srv\/http\/core\/lib\/private\/urlgenerator.php(41): OC\\Route\\Router->generate('news.page.index', Array)","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #2 \/srv\/http\/core\/lib\/private\/helper.php(44): OC\\URLGenerator->linkToRoute('news.page.index', Array)","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #3 \/srv\/http\/core\/lib\/public\/util.php(211): OC_Helper::linkToRoute('news.page.index', Array)","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #4 \/srv\/http\/news\/appinfo\/app.php(27): OCP\\Util::linkToRoute('news.page.index')","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #5 \/srv\/http\/core\/lib\/private\/app.php(317): require('\/srv\/http\/news\/...')","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #6 \/srv\/http\/core\/settings\/ajax\/navigationdetect.php(9): OC_App::getAppNavigationEntries('news')","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #7 \/srv\/http\/core\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/srv\/http\/core\/...')","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #8 [internal function]: __lambda_func(Array)","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #9 \/srv\/http\/core\/lib\/private\/route\/router.php(206): call_user_func('\\x00lambdabda_2, Array)","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #10 \/srv\/http\/core\/lib\/base.php(744): OC\\Route\\Router->match('\/settings\/ajax\/...')","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #11 \/srv\/http\/core\/index.php(28): OC::handleRequest()","level":4,"time":"2014-04-25T15:28:46+00:00"}
{"app":"index","message":"Exception: #12 {main}","level":4,"time":"2014-04-25T15:28:46+00:00"}
```

**Comment by DeepDiver1975** [comment]
well - both music and news are single page apps - they will continue to operate even in case the app is disabled. The apps will still send requests to the server and the server cannot process them.

Won't finx in core from my understanding - the apps have to take care of this case properly.

**Comment by DeepDiver1975** [comment]
this is anyway a corner case

**Comment by MorrisJobke** [comment]
> well - both music and news are single page apps - they will continue to operate even in case the app is disabled. The apps will still send requests to the server and the server cannot process them.

They aren't loaded in any tab. I just have gone to the apps management and clicked "disable". Then this is printed to the log. It's more a log pollution.

**Comment by DeepDiver1975** [comment]
Apc or any other cache fu enabled?

**Comment by MorrisJobke** [comment]
Is just once for a deactivation.

**Comment by LukasReschke** [comment]
Can reproduce this on stable8.1 branch and I think I also talked with @PVince81 about this today.

**Comment by LukasReschke** [comment]
Moving to 8.1.1-next-maintenance.

**Comment by MorrisJobke** [comment]
@PVince81 @LukasReschke Status of this?

**Comment by DeepDiver1975** [comment]
8.1.2 - not that critical - maybe even 8.2

**Comment by MorrisJobke** [comment]
Reproduced in https://github.com/owncloud/core/pull/17736#issuecomment-122854625

**Comment by MorrisJobke** [comment]
Similiar to #18224

**Comment by LukasReschke** [comment]
Probably fixed with https://github.com/owncloud/core/pull/18844? (if not please reopen)
