### ISSUE TITLE
Server2server sharing doesn't work with php-fpm

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#9416]
I have an Apache webserver with php-fpm here.

mod_rewrite is working and I want to test the server2server sharing.

I just get following error in my logs after clicking the "Yes" button in the confirmation dialog of the server to server sharing:

```
{"reqId":"53b554abafbf1","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2014-07-03T13:03:39+00:00","method":"POST","url":"\/master\/public.php\/webdav\/"}
{"reqId":"53b554abafbf1","app":"webdav","message":"Exception: #1 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod('POST', '')","level":0,"time":"2014-07-03T13:03:39+00:00","method":"POST","url":"\/master\/public.php\/webdav\/"}
{"reqId":"53b554abafbf1","app":"webdav","message":"Exception: #2 \/home\/mjob\/Projekte\/owncloud\/master\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(433): call_user_func_array(Array, Array)","level":0,"time":"2014-07-03T13:03:39+00:00","method":"POST","url":"\/master\/public.php\/webdav\/"}
{"reqId":"53b554abafbf1","app":"webdav","message":"Exception: #3 \/home\/mjob\/Projekte\/owncloud\/master\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(455): Sabre\\DAV\\Server->broadcastEvent('beforeMethod', Array)","level":0,"time":"2014-07-03T13:03:39+00:00","method":"POST","url":"\/master\/public.php\/webdav\/"}
{"reqId":"53b554abafbf1","app":"webdav","message":"Exception: #4 \/home\/mjob\/Projekte\/owncloud\/master\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('POST', '')","level":0,"time":"2014-07-03T13:03:39+00:00","method":"POST","url":"\/master\/public.php\/webdav\/"}
{"reqId":"53b554abafbf1","app":"webdav","message":"Exception: #5 \/home\/mjob\/Projekte\/owncloud\/master\/apps\/files_sharing\/publicwebdav.php(75): Sabre\\DAV\\Server->exec()","level":0,"time":"2014-07-03T13:03:39+00:00","method":"POST","url":"\/master\/public.php\/webdav\/"}
{"reqId":"53b554abafbf1","app":"webdav","message":"Exception: #6 \/home\/mjob\/Projekte\/owncloud\/master\/public.php(46): require_once('\/home\/mjob\/Proj...')","level":0,"time":"2014-07-03T13:03:39+00:00","method":"POST","url":"\/master\/public.php\/webdav\/"}
{"reqId":"53b554abafbf1","app":"webdav","message":"Exception: #7 {main}","level":0,"time":"2014-07-03T13:03:39+00:00","method":"POST","url":"\/master\/public.php\/webdav\/"}
```

Can anybody help to setup this in the correct way?

cc @PVince81 @icewind1991 @schiesbn

**Comment by PVince81** [comment]
@MorrisJobke did you find a solution to this eventually ?

**Comment by MorrisJobke** [comment]
It works for me nowadays. I didn't remind if I changed something, but I don't think so. Because it also works fine on my minimal development installations.

**Comment by LukasReschke** [comment]
Pretty sure that was https://github.com/owncloud/core/issues/13398
