### ISSUE TITLE
Owncloud desktop client Csyns error, 400 bad request

### ISSUE THREAD

**Issue by theclansmen** [owncloud/core#9702]
### Steps to reproduce
1. My dekstop client could not sync with my server on MAC and PC
2.
3.

### Server configuration
**Operating system**: Win 7 / Mac OS

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page) 6.0.4

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** 

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oca2091aec74',
  'passwordsalt' => 'd486391d5fc4ebe85520768b6170da',
  'trusted_domains' => 
  array (
    0 => 'cloud.theclansmen.fr',
   'check_for_working_webdav' => true,
  ),
  'datadirectory' => '/home/theclans/cloud/data',
  'dbtype' => 'sqlite3',
  'version' => '6.0.4.1',
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'forcessl' => true,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/... NO

**Are you using encryption:** No

### Client configuration
**Browser:** Firefox 30.0

**Operating system:** Win 7 / Mac OS

#### Web server error log
```
Fatal 	index 	Symfony\Component\Routing\Exception\RouteNotFoundException: Route "contacts_index" does not exist. 	2014-07-17T10:11:25+00:00
Error 	search_lucene 	Cross-reference streams are not supported yet. Trace:\n#0 /home/theclans/cloud/apps/search_lucene/3rdparty/Zend/Pdf/Parser.php(460): Zend_Pdf_Parser->_loadXRefTable('116') #1 /home/theclans/cloud/apps/search_lucene/3rdparty/Zend/Pdf.php(318): Zend_Pdf_Parser->__construct('%PDF-1.5\r%\xE2\xE3\xCF\xD3\r...', Object(Zend_Pdf_ElementFactory_Proxy), false) #2 /home/theclans/cloud/apps/search_lucene/3rdparty/Zend/Pdf.php(255): Zend_Pdf->__construct('%PDF-1.5\r%\xE2\xE3\xCF\xD3\r...', NULL) #3 /home/theclans/cloud/apps/search_lucene/document/Pdf.php(21): Zend_Pdf::parse('%PDF-1.5\r%\xE2\xE3\xCF\xD3\r...') #4 /home/theclans/cloud/apps/search_lucene/document/Pdf.php(69): OCA\Search_Lucene\Document\Pdf->__construct('%PDF-1.5\r%\xE2\xE3\xCF\xD3\r...', false, false) #5 /home/theclans/cloud/apps/search_lucene/lib/indexer.php(94): OCA\Search_Lucene\Document\Pdf::loadPdf('%PDF-1.5\r%\xE2\xE3\xCF\xD3\r...') #6 /home/theclans/cloud/apps/search_lucene/lib/hooks.php(79): OCA\Search_Lucene\Indexer::indexFile('/Juin 2014.pdf', 'leclouddesamour...') #7 [internal function]: OCA\Search_Lucene\Hooks::doIndexFile('{"path":"\\/Juin...') #8 /home/theclans/cloud/lib/private/backgroundjob/legacy/queuedjob.php(16): call_user_func(Array, '{"path":"\\/Juin...') #9 /home/theclans/cloud/lib/private/backgroundjob/job.php(34): OC\BackgroundJob\Legacy\QueuedJob->run(Array) #10 /home/theclans/cloud/lib/private/backgroundjob/queuedjob.php(27): OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #11 /home/theclans/cloud/cron.php(114): OC\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #12 {main} 	2014-07-17T07:42:05+00:00
Warning 	core 	isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception) 	2014-07-17T07:42:03+00:00 
```

#### ownCloud log (data/owncloud.log)
```
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T22:55:26+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T22:57:25+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T22:57:27+00:00"}
{"app":"OC_USER_WEBDAVAUTH","message":"Invalid Url: \"\" ","level":3,"time":"2014-07-16T22:57:36+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T23:00:06+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T23:00:12+00:00"}
{"app":"search_lucene","message":"Cross-reference streams are not supported yet. Trace:\\n#0 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf\/Parser.php(460): Zend_Pdf_Parser->_loadXRefTable('116')\n#1 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf.php(318): Zend_Pdf_Parser->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', Object(Zend_Pdf_ElementFactory_Proxy), false)\n#2 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf.php(255): Zend_Pdf->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', NULL)\n#3 \/home\/theclans\/cloud\/apps\/search_lucene\/document\/Pdf.php(21): Zend_Pdf::parse('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...')\n#4 \/home\/theclans\/cloud\/apps\/search_lucene\/document\/Pdf.php(69): OCA\\Search_Lucene\\Document\\Pdf->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', false, false)\n#5 \/home\/theclans\/cloud\/apps\/search_lucene\/lib\/indexer.php(94): OCA\\Search_Lucene\\Document\\Pdf::loadPdf('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...')\n#6 \/home\/theclans\/cloud\/apps\/search_lucene\/lib\/hooks.php(79): OCA\\Search_Lucene\\Indexer::indexFile('\/Juin 2014.pdf', 'leclouddesamour...')\n#7 [internal function]: OCA\\Search_Lucene\\Hooks::doIndexFile('{\"path\":\"\\\\\/Juin...')\n#8 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/legacy\/queuedjob.php(16): call_user_func(Array, '{\"path\":\"\\\\\/Juin...')\n#9 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/job.php(34): OC\\BackgroundJob\\Legacy\\QueuedJob->run(Array)\n#10 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/queuedjob.php(27): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#11 \/home\/theclans\/cloud\/cron.php(114): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#12 {main}","level":3,"time":"2014-07-16T23:34:49+00:00"}
{"app":"Encryption library","message":"Could not get migration status for leclouddesamoureux, no record found","level":3,"time":"2014-07-16T23:35:03+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T23:35:46+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T23:42:54+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T23:45:00+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-17T07:42:03+00:00"}
{"app":"search_lucene","message":"Cross-reference streams are not supported yet. Trace:\\n#0 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf\/Parser.php(460): Zend_Pdf_Parser->_loadXRefTable('116')\n#1 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf.php(318): Zend_Pdf_Parser->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', Object(Zend_Pdf_ElementFactory_Proxy), false)\n#2 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf.php(255): Zend_Pdf->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', NULL)\n#3 \/home\/theclans\/cloud\/apps\/search_lucene\/document\/Pdf.php(21): Zend_Pdf::parse('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...')\n#4 \/home\/theclans\/cloud\/apps\/search_lucene\/document\/Pdf.php(69): OCA\\Search_Lucene\\Document\\Pdf->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', false, false)\n#5 \/home\/theclans\/cloud\/apps\/search_lucene\/lib\/indexer.php(94): OCA\\Search_Lucene\\Document\\Pdf::loadPdf('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...')\n#6 \/home\/theclans\/cloud\/apps\/search_lucene\/lib\/hooks.php(79): OCA\\Search_Lucene\\Indexer::indexFile('\/Juin 2014.pdf', 'leclouddesamour...')\n#7 [internal function]: OCA\\Search_Lucene\\Hooks::doIndexFile('{\"path\":\"\\\\\/Juin...')\n#8 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/legacy\/queuedjob.php(16): call_user_func(Array, '{\"path\":\"\\\\\/Juin...')\n#9 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/job.php(34): OC\\BackgroundJob\\Legacy\\QueuedJob->run(Array)\n#10 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/queuedjob.php(27): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#11 \/home\/theclans\/cloud\/cron.php(114): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#12 {main}","level":3,"time":"2014-07-17T07:42:05+00:00"}
{"app":"index","message":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException: Route \"contacts_index\" does not exist.","level":4,"time":"2014-07-17T10:11:25+00:00"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

i can't get my desktop client to work.
i can upload files to my owncloud using the web page but nothing can be done with the client. Client version is the last one.

please help me solving this.

**Comment by PVince81** [comment]
Are you guys still having issues with 7.0.5 or 8.0.2 ?
Has the OVH / SSL situation been solved ?

**Comment by oresch** [comment]
I'm now running 8.0.2 - no further issues to be reported.

**Comment by Rene33** [comment]
Absolutely no problem neither with 7.05 nor 8.02.
Everything is running fine. 

René Laversanne 
IXEO-Conseil
Tél. 05 56 808 801 
Mob. 06 09 82 21 53 
rene.laversanne@ixeo-conseil.com
www.ixeo-conseil.com

**Comment by PVince81** [comment]
Thanks. I'll close this then.

If you're still having issues, feel free to reopen.
Thanks.
