### ISSUE TITLE
 OC 6.04 -> 7.0.0 upgrade fails with "Failed to upgrade "files_sharing""

### ISSUE THREAD

**Issue by HackintoshHD** [owncloud/core#9810]
The upgrade of an ownCloud 6.0.4 instance to ownCloud 7.0.0 fails with the error message "Failed to upgrade 'files_sharing'":

![screenshot](https://pbs.twimg.com/media/BtP-CitCIAEIWzX.png:large)

This had obviously already been reported [here](http://forum.owncloud.org/viewtopic.php?f=29&t=22344) five days before the OC7 release.

From the instance's owncloud.log:

```
{"reqId":"[anonymised]","app":"core","message":"starting upgrade from 6.0.4.1 to 7.0.0.8","level":0,"time":"2014-07-23T18:04:07+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=[anonymised]"}
{"reqId":"[anonymised]","app":"files","message":"starting app upgrade from 1.1.7 to 1.1.9","level":0,"time":"2014-07-23T18:05:57+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=[anonymised]"}
{"reqId":"[anonymised]","app":"activity","message":"starting app upgrade from 1.1.2 to 1.1.23","level":0,"time":"2014-07-23T18:05:57+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=[anonymised]"}
{"reqId":"[anonymised]","app":"activity","message":"starting app upgrade from 1.1.2 to 1.1.23","level":0,"time":"2014-07-23T18:06:02+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"core","message":"Failed to update database structure (exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'activity_filter_app'' in \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php:742\nStack trace:\n#0 [internal function]: PDO->query('CREATE INDEX ac...')\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(742): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(179): Doctrine\\DBAL\\Connection->query('CREATE INDEX ac...')\n#3 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(35): OC\\DB\\Migrator->applySchema(Object(Doctrine\\DBAL\\Schema\\Schema))\n#4 \/var\/www\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(98): OC\\DB\\Migrator->migrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#5 \/var\/www\/owncloud\/lib\/private\/db.php(320): OC\\DB\\MDB2SchemaManager->updateDbFromStructure('\/var\/www\/ownclo...')\n#6 \/var\/www\/owncloud\/lib\/private\/app.php(1172): OC_DB::updateDbFromStructure('\/var\/www\/ownclo...')\n#7 \/var\/www\/owncloud\/lib\/private\/app.php(980): OC_App::updateApp('activity')\n#8 \/var\/www\/owncloud\/lib\/private\/app.php(87): OC_App::checkUpgrade('activity')\n#9 \/var\/www\/owncloud\/lib\/private\/app.php(72): OC_App::loadApp('activity')\n#10 \/var\/www\/owncloud\/remote.php(39): OC_App::loadApps(Array)\n#11 {main}\n\nNext exception 'Doctrine\\DBAL\\DBALException' with message 'An exception occurred while executing 'CREATE INDEX activity_filter_app ON `oc_activity` (`affecteduser`, `app`, `timestamp`)':\n\nSQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'activity_filter_app'' in \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php:47\nStack trace:\n#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(744): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(PDOException), 'CREATE INDEX ac...')\n#1 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(179): Doctrine\\DBAL\\Connection->query('CREATE INDEX ac...')\n#2 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(35): OC\\DB\\Migrator->applySchema(Object(Doctrine\\DBAL\\Schema\\Schema))\n#3 \/var\/www\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(98): OC\\DB\\Migrator->migrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#4 \/var\/www\/owncloud\/lib\/private\/db.php(320): OC\\DB\\MDB2SchemaManager->updateDbFromStructure('\/var\/www\/ownclo...')\n#5 \/var\/www\/owncloud\/lib\/private\/app.php(1172): OC_DB::updateDbFromStructure('\/var\/www\/ownclo...')\n#6 \/var\/www\/owncloud\/lib\/private\/app.php(980): OC_App::updateApp('activity')\n#7 \/var\/www\/owncloud\/lib\/private\/app.php(87): OC_App::checkUpgrade('activity')\n#8 \/var\/www\/owncloud\/lib\/private\/app.php(72): OC_App::loadApp('activity')\n#9 \/var\/www\/owncloud\/remote.php(39): OC_App::loadApps(Array)\n#10 {main})","level":4,"time":"2014-07-23T18:06:06+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"remote","message":"Konnte \"activity\" nicht aktualisieren.","level":4,"time":"2014-07-23T18:06:06+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"calendar","message":"starting app upgrade from 0.6.3 to 0.6.4","level":0,"time":"2014-07-23T18:06:09+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=[anonymised]"}
{"reqId":"[anonymised]","app":"contacts","message":"starting app upgrade from 0.3 to 0.3.0.17","level":0,"time":"2014-07-23T18:06:11+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=[anonymised]"}
{"reqId":"[anonymised]","app":"files_sharing","message":"starting app upgrade from 0.3.5 to 0.5.3","level":0,"time":"2014-07-23T18:06:13+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"files_pdfviewer","message":"starting app upgrade from 0.3 to 0.5","level":0,"time":"2014-07-23T18:06:16+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=[anonymised]"}
{"reqId":"[anonymised]","app":"files_sharing","message":"starting app upgrade from 0.3.5 to 0.5.3","level":0,"time":"2014-07-23T18:06:16+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=[anonymised]"}
{"reqId":"[anonymised]","app":"files_versions","message":"starting app upgrade from 1.0.3 to 1.0.5","level":0,"time":"2014-07-23T18:06:17+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"files_sharing","message":"starting app upgrade from 0.3.5 to 0.5.3","level":0,"time":"2014-07-23T18:06:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"files_versions","message":"starting app upgrade from 1.0.3 to 1.0.5","level":0,"time":"2014-07-23T18:06:20+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=[anonymised]"}
{"reqId":"[anonymised]","app":"gallery","message":"starting app upgrade from 0.5.3 to 0.5.4","level":0,"time":"2014-07-23T18:06:21+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"files_versions","message":"starting app upgrade from 1.0.3 to 1.0.5","level":0,"time":"2014-07-23T18:06:23+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"core","message":"Failed to update database structure (exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_files_versions' doesn't exist' in \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php:742\nStack trace:\n#0 [internal function]: PDO->query('ALTER TABLE `oc...')\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(742): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(179): Doctrine\\DBAL\\Connection->query('ALTER TABLE `oc...')\n#3 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(35): OC\\DB\\Migrator->applySchema(Object(Doctrine\\DBAL\\Schema\\Schema))\n#4 \/var\/www\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(98): OC\\DB\\Migrator->migrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#5 \/var\/www\/owncloud\/lib\/private\/db.php(320): OC\\DB\\MDB2SchemaManager->updateDbFromStructure('\/var\/www\/ownclo...')\n#6 \/var\/www\/owncloud\/lib\/private\/app.php(1172): OC_DB::updateDbFromStructure('\/var\/www\/ownclo...')\n#7 \/var\/www\/owncloud\/lib\/private\/app.php(980): OC_App::updateApp('files_versions')\n#8 \/var\/www\/owncloud\/lib\/private\/app.php(87): OC_App::checkUpgrade('files_versions')\n#9 \/var\/www\/owncloud\/lib\/private\/app.php(72): OC_App::loadApp('files_versions')\n#10 \/var\/www\/owncloud\/lib\/private\/util.php(72): OC_App::loadApps(Array)\n#11 \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php(800): OC_Util::setupFS()\n#12 \/var\/www\/owncloud\/lib\/autoloader.php(142): require_once('\/var\/www\/ownclo...')\n#13 [internal function]: OC\\Autoloader->load('OC\\Files\\Filesy...')\n#14 \/var\/www\/owncloud\/apps\/files_sharing\/appinfo\/update.php(90): spl_autoload_call('OC\\Files\\Filesy...')\n#15 \/var\/www\/owncloud\/apps\/files_sharing\/appinfo\/update.php(10): removeSharedFolder()\n#16 \/var\/www\/owncloud\/lib\/private\/app.php(1179): include('\/var\/www\/ownclo...')\n#17 \/var\/www\/owncloud\/lib\/private\/app.php(980): OC_App::updateApp('files_sharing')\n#18 \/var\/www\/owncloud\/lib\/private\/app.php(87): OC_App::checkUpgrade('files_sharing')\n#19 \/var\/www\/owncloud\/lib\/private\/app.php(72): OC_App::loadApp('files_sharing')\n#20 \/var\/www\/owncloud\/lib\/private\/updater.php(222): OC_App::loadApps()\n#21 \/var\/www\/owncloud\/lib\/private\/updater.php(137): OC\\Updater->doUpgrade('7.0.0.8', '6.0.4.1')\n#22 \/var\/www\/owncloud\/core\/ajax\/update.php(35): OC\\Updater->upgrade()\n#23 {main}\n\nNext exception 'Doctrine\\DBAL\\DBALException' with message 'An exception occurred while executing 'ALTER TABLE `oc_files_versions` ADD `user` VARCHAR(64) DEFAULT '' NOT NULL, ADD `size` VARCHAR(50) DEFAULT '' NOT NULL':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_files_versions' doesn't exist' in \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php:47\nStack trace:\n#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(744): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(PDOException), 'ALTER TABLE `oc...')\n#1 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(179): Doctrine\\DBAL\\Connection->query('ALTER TABLE `oc...')\n#2 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(35): OC\\DB\\Migrator->applySchema(Object(Doctrine\\DBAL\\Schema\\Schema))\n#3 \/var\/www\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(98): OC\\DB\\Migrator->migrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#4 \/var\/www\/owncloud\/lib\/private\/db.php(320): OC\\DB\\MDB2SchemaManager->updateDbFromStructure('\/var\/www\/ownclo...')\n#5 \/var\/www\/owncloud\/lib\/private\/app.php(1172): OC_DB::updateDbFromStructure('\/var\/www\/ownclo...')\n#6 \/var\/www\/owncloud\/lib\/private\/app.php(980): OC_App::updateApp('files_versions')\n#7 \/var\/www\/owncloud\/lib\/private\/app.php(87): OC_App::checkUpgrade('files_versions')\n#8 \/var\/www\/owncloud\/lib\/private\/app.php(72): OC_App::loadApp('files_versions')\n#9 \/var\/www\/owncloud\/lib\/private\/util.php(72): OC_App::loadApps(Array)\n#10 \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php(800): OC_Util::setupFS()\n#11 \/var\/www\/owncloud\/lib\/autoloader.php(142): require_once('\/var\/www\/ownclo...')\n#12 [internal function]: OC\\Autoloader->load('OC\\Files\\Filesy...')\n#13 \/var\/www\/owncloud\/apps\/files_sharing\/appinfo\/update.php(90): spl_autoload_call('OC\\Files\\Filesy...')\n#14 \/var\/www\/owncloud\/apps\/files_sharing\/appinfo\/update.php(10): removeSharedFolder()\n#15 \/var\/www\/owncloud\/lib\/private\/app.php(1179): include('\/var\/www\/ownclo...')\n#16 \/var\/www\/owncloud\/lib\/private\/app.php(980): OC_App::updateApp('files_sharing')\n#17 \/var\/www\/owncloud\/lib\/private\/app.php(87): OC_App::checkUpgrade('files_sharing')\n#18 \/var\/www\/owncloud\/lib\/private\/app.php(72): OC_App::loadApp('files_sharing')\n#19 \/var\/www\/owncloud\/lib\/private\/updater.php(222): OC_App::loadApps()\n#20 \/var\/www\/owncloud\/lib\/private\/updater.php(137): OC\\Updater->doUpgrade('7.0.0.8', '6.0.4.1')\n#21 \/var\/www\/owncloud\/core\/ajax\/update.php(35): OC\\Updater->upgrade()\n#22 {main})","level":4,"time":"2014-07-23T18:06:25+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=[anonymised]"}
{"reqId":"[anonymised]","app":"gallery","message":"starting app upgrade from 0.5.3 to 0.5.4","level":0,"time":"2014-07-23T18:06:27+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2014-07-23T18:06:28+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"remote","message":"Konnte \"files_sharing\" nicht aktualisieren.","level":4,"time":"2014-07-23T18:06:29+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files' !!! \ncache: Array\n(\n    [fileid] => 3\n    [storage] => local::\/var\/www\/owncloud\/data\/[anonymised]\/\n    [path] => files\n    [parent] => -1\n    [name] => files\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 0\n    [mtime] => 1360182326\n    [storage_mtime] => 1360182326\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => \n    [permissions] => 0\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1406138787\n    [size] => -1\n    [etag] => 53cff9abede3e\n    [storage_mtime] => 1406138787\n    [permissions] => 31\n)\n","level":0,"time":"2014-07-23T18:06:36+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files' !!! \ncache: Array\n(\n    [fileid] => 2\n    [storage] => local::\/var\/www\/owncloud\/data\/[anonymised]\/\n    [path] => files\n    [parent] => -1\n    [name] => files\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 1942513298\n    [mtime] => 1406124002\n    [storage_mtime] => 1403563950\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 53cfc972c6e91\n    [permissions] => 0\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1406138787\n    [size] => -1\n    [etag] => 53cff9b9af112\n    [storage_mtime] => 1406138787\n    [permissions] => 31\n)\n","level":0,"time":"2014-07-23T18:06:49+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"[anonymised]","app":"files_texteditor","message":"starting app upgrade from 0.3 to 0.4","level":0,"time":"2014-07-23T18:09:28+00:00","method":"GET","url":"\/owncloud\/"}
```

**Comment by PVince81** [comment]
Has this still been observed when upgrading from OC 6 to OC 7.0.4 ?

**Comment by PVince81** [comment]
Anyone still having issues with this ? (Upgrading from OC 6 to OC 7.0.4)

**Comment by maethor** [comment]
Nope. I did the upgrade few weeks ago, it works.

**Comment by PVince81** [comment]
Thanks a lot.
I'm closing this now.

If anyone is still having issues with 7.0.5 or 8.0.2, feel free to reopen.
Thanks.
